insert into public.golf_courses (country, name) values
  ('United States', 'Bridges Golf Course'),
  ('United States', 'Bridgeton Berry Hill Golf Course'),
  ('United States', 'Bridgewater Country Club'),
  ('United States', 'Bridgewater Golf Club'),
  ('United States', 'Bridgewater Links Golf Course'),
  ('United States', 'Bridgton Highlands Country Club'),
  ('United States', 'Brier Creek Country Club'),
  ('United States', 'Brier Creek Golf Course'),
  ('United States', 'Brierwood Country Club'),
  ('United States', 'Briery Country Club'),
  ('United States', 'Brigantine Clipper At Shipyard Golf Club'),
  ('United States', 'Brigantine Golf Links'),
  ('United States', 'Briggs Woods Golf Course'),
  ('United States', 'Bright Grandview Golf Course'),
  ('United States', 'Bright Meadows Golf Course Championship'),
  ('United States', 'Bright Meadows Golf Course Executive'),
  ('United States', 'Brighton Dale Links'),
  ('United States', 'Brighton Park Golf Course'),
  ('United States', 'Brights Creek Golf Club'),
  ('United States', 'Brightwater Club'),
  ('United States', 'Brightwood Hills Golf Course'),
  ('United States', 'Bringhurst Golf Course'),
  ('United States', 'Brinkley Country Club'),
  ('United States', 'Bristol Golf Club At The Cedars'),
  ('United States', 'Bristol Golf Park'),
  ('United States', 'Bristol Oaks Golf Club'),
  ('United States', 'Bristol Ridge Golf Course'),
  ('United States', 'Bristow Golf Country Club'),
  ('United States', 'Bristow Manor Golf Club'),
  ('United States', 'Britt Country Club'),
  ('United States', 'Broad Bay Country Club'),
  ('United States', 'Broad Run Golf Practice Facility'),
  ('United States', 'Broad Run Golfers Club'),
  ('United States', 'Broadacres Golf Club'),
  ('United States', 'Broadlands Golf Club'),
  ('United States', 'Broadlands Golf Course'),
  ('United States', 'Broadmoor Country Club'),
  ('United States', 'Broadmoor Golf Club'),
  ('United States', 'Broadmoor Golf Course'),
  ('United States', 'Broadmoor Golf Links'),
  ('United States', 'Broadmoore Golf Course'),
  ('United States', 'Brockton Country Club'),
  ('United States', 'Brockville Country Club'),
  ('United States', 'Brockville Highland Golf Club'),
  ('United States', 'Broken Arrow Golf Club'),
  ('United States', 'Broken Pine Golf Country Club'),
  ('United States', 'Broken Sound Club Club Course'),
  ('United States', 'Broken Sound Club Old Course'),
  ('United States', 'Broken Tee Englewood Golf Course'),
  ('United States', 'Broken Tee Englewood Par 3 Course'),
  ('United States', 'Bronson Golf Club'),
  ('United States', 'Bronzwood Golf Club'),
  ('United States', 'Brook Lea Country Club'),
  ('United States', 'Brook Tree Golf Course'),
  ('United States', 'Brook Valley Country Club'),
  ('United States', 'Brooke Hills Park Golf Course'),
  ('United States', 'Brookfield Country Club'),
  ('United States', 'Brookfield Hills Golf Course'),
  ('United States', 'Brookhaven Country Club'),
  ('United States', 'Brookhaven Golf Club'),
  ('United States', 'Brookhill Golf Course'),
  ('United States', 'Brookhills Golf Club'),
  ('United States', 'Brookings Country Club'),
  ('United States', 'Brooklake Country Club'),
  ('United States', 'Brookland Golf Park'),
  ('United States', 'Brooklawn Country Club'),
  ('United States', 'Brookledge Golf Course'),
  ('United States', 'Brookmeadow Country Club'),
  ('United States', 'Brookridge Golf Country Club'),
  ('United States', 'Brookridge Golf Fitness Championship Course'),
  ('United States', 'Brookridge Golf Fitness West Nine'),
  ('United States', 'Brooks Golf Club'),
  ('United States', 'Brookshire Golf Club'),
  ('United States', 'Brookside Country Club'),
  ('United States', 'Brookside Golf & Country Club'),
  ('United States', 'Brookside Golf Club'),
  ('United States', 'Brookside Golf Club C W Koiner Course'),
  ('United States', 'Brookside Golf Club E O Nay Course'),
  ('United States', 'Brookside Golf Course'),
  ('United States', 'Brookside Golf and Grill'),
  ('United States', 'Brookside Par 3 Golf Club'),
  ('United States', 'Brookside resort'),
  ('United States', 'Brookstone Golf Country Club'),
  ('United States', 'Brooksville Country Club'),
  ('United States', 'Brooktrails Golf Course'),
  ('United States', 'Brookview Golf Course'),
  ('United States', 'Brookville Country Club'),
  ('United States', 'Brookwood Golf Club'),
  ('United States', 'Brookwood Golf Course'),
  ('United States', 'Brookwoods Golf Club'),
  ('United States', 'Broomsedge Golf Club'),
  ('United States', 'Brown Acres Golf Course'),
  ('United States', 'Brown County Golf Course'),
  ('United States', 'Brown Deer Golf Club'),
  ('United States', 'Brown Deer Park Golf Course'),
  ('United States', 'Brown''s Run Country Club'),
  ('United States', 'Browns Lake Golf Course'),
  ('United States', 'Browns Mill Golf Course'),
  ('United States', 'Brownson Country Club'),
  ('United States', 'Brownstone Country Club Resort'),
  ('United States', 'Bruce Hills Golf Course'),
  ('United States', 'Brunswick Country Club'),
  ('United States', 'Brunswick Golf Club'),
  ('United States', 'Brunswick Golf Club Azalea Magnolia Course'),
  ('United States', 'Brunswick Golf Club Dogwood Azalea Course'),
  ('United States', 'Brunswick Golf Club Magnolia Dogwood'),
  ('United States', 'Brunswick Greens Golf Course'),
  ('United States', 'Brush Creek Golf Course'),
  ('United States', 'Brushy Mountain Golf Club'),
  ('United States', 'Brute At Grand Geneva Resort Spa'),
  ('United States', 'Bryan Park Champions Course'),
  ('United States', 'Bryan Park Players Course'),
  ('United States', 'Bryce Resort'),
  ('United States', 'Bryden Canyon Public Golf Course'),
  ('United States', 'Bryn Mawr Country Club'),
  ('United States', 'Buckeye Hills Country Club'),
  ('United States', 'Buckhorn Springs Golf Country Club'),
  ('United States', 'Buckingham Golf Country Club'),
  ('United States', 'Buckmeadow Golf Club'),
  ('United States', 'Bucknell Golf Club'),
  ('United States', 'Bucks Run Golf Club'),
  ('United States', 'Buckskin Golf Club'),
  ('United States', 'Bucksport Golf Club'),
  ('United States', 'Buena Vista Country Club'),
  ('United States', 'Buena Vista Golf Course'),
  ('United States', 'Buena Vista University Golf Course at Lake Creek'),
  ('United States', 'Buenaventura Golf Course'),
  ('United States', 'Buffalo Creek Golf Course'),
  ('United States', 'Buffalo Dunes Golf Course'),
  ('United States', 'Buffalo Golf Course'),
  ('United States', 'Buffalo Grove Golf Club'),
  ('United States', 'Buffalo Heights Golf Course'),
  ('United States', 'Buffalo Ridge Springs Golf Course'),
  ('United States', 'Buffalo Rock Golf Venue'),
  ('United States', 'Buffalo Run Golf Course'),
  ('United States', 'Buffalo Tournament Club'),
  ('United States', 'Buffalo Trace Golf Course'),
  ('United States', 'Buffalo Valley Golf Course'),
  ('United States', 'Buffer Park Golf Course'),
  ('United States', 'Buhl Farm Golf Course Driving Range'),
  ('United States', 'Bull Run Golf Club'),
  ('United States', 'Bull Valley Golf Club'),
  ('United States', 'Bull''s Eye Country Club'),
  ('United States', 'Bulls Bay Golf Club'),
  ('United States', 'Bulls Bridge Golf Club'),
  ('United States', 'Buncombe Creek Golf Course'),
  ('United States', 'Bungay Brook Golf Club'),
  ('United States', 'Bunker Hill Golf Course'),
  ('United States', 'Bunker Hills Executive Course'),
  ('United States', 'Bunker Hills Golf Course'),
  ('United States', 'Bunker Links Golf Course'),
  ('United States', 'Bunn Golf Course'),
  ('United States', 'Bur Mil Park Golf Course'),
  ('United States', 'Burden Lake Country Club'),
  ('United States', 'Burgis Back Nine'),
  ('United States', 'Burgundy Bay Golf Course'),
  ('United States', 'Burke Golf Course'),
  ('United States', 'Burke Lake Golf Center'),
  ('United States', 'Burl Oaks Golf Club'),
  ('United States', 'Burlingame Country Club'),
  ('United States', 'Burlington Country Club'),
  ('United States', 'Burlington Golf Club'),
  ('United States', 'Burnet Park Golf Course'),
  ('United States', 'Burnham Woods Golf Course'),
  ('United States', 'Burning Oak Country Club'),
  ('United States', 'Burning Ridge Golf Course'),
  ('United States', 'Burning Tree Country Club'),
  ('United States', 'Burning Tree Golf Club'),
  ('United States', 'Burnt Pine At Sandestin Golf And Beach Resort'),
  ('United States', 'Burr Oak Golf Club'),
  ('United States', 'Bushwood Golf Course'),
  ('United States', 'Butler Country Club'),
  ('United States', 'Butler National Golf Club'),
  ('United States', 'Butlers Golf Course Lakeside Course'),
  ('United States', 'Butlers Golf Course Woodside Course'),
  ('United States', 'Butte Country Club'),
  ('United States', 'Butte Creek Country Club'),
  ('United States', 'Butte des Morts Country Club'),
  ('United States', 'Butter Valley Golf Port'),
  ('United States', 'Butterbrook Golf Club'),
  ('United States', 'Butterfield Country Club'),
  ('United States', 'Butterfield Golf Course'),
  ('United States', 'Butterfield Trail Golf Club'),
  ('United States', 'Buttermilk Falls Golf Club'),
  ('United States', 'Butternut Creek Golf Course'),
  ('United States', 'Butternut Farm Golf Club'),
  ('United States', 'Butternut Hills Golf Course'),
  ('United States', 'Butternut Valley Golf'),
  ('United States', 'Button Hole Short Course Teaching Center'),
  ('United States', 'Buttonwood Golf Course'),
  ('United States', 'Byrd At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Byrncliff Golf Resort Banquets'),
  ('United States', 'Byron Hills Golf Course'),
  ('United States', 'C Way Golf Club'),
  ('United States', 'CNC Links'),
  ('United States', 'Cabarrus Country Club'),
  ('United States', 'Caberfae Peaks'),
  ('United States', 'Cabin Creek Golf Club'),
  ('United States', 'Cabin Greens Golf Course'),
  ('United States', 'Cabinet View Country Club'),
  ('United States', 'Cable Hollow Golf Course'),
  ('United States', 'Cabot Citrus Farms Karoo Course'),
  ('United States', 'Cabot Citrus Farms The Roost Course'),
  ('United States', 'Cabot Citrus Farms The Squeeze Course'),
  ('United States', 'Cabot Citrus Farms The Wedge Course'),
  ('United States', 'Cabot Links'),
  ('United States', 'Cacapon Resort State Park'),
  ('United States', 'Caddie Shack'),
  ('United States', 'Caddo Creek Golf Club'),
  ('United States', 'Cadillac Country Club'),
  ('United States', 'Cadiz Country Club'),
  ('United States', 'Caesars Pocono Palace Cove Haven'),
  ('United States', 'Cajun Pines Golf Course'),
  ('United States', 'Calabasas Golf Country Club'),
  ('United States', 'Calderone Farms Golf Club'),
  ('United States', 'Caldwell Country Club'),
  ('United States', 'Caldwell Golf Course'),
  ('United States', 'Caledonia Country Club'),
  ('United States', 'Caledonia Golf Club'),
  ('United States', 'Caledonia Golf Fish Club'),
  ('United States', 'Calhoun Elks Lodge Golf Club'),
  ('United States', 'Calhoun Hills Golf Complex'),
  ('United States', 'Caliente Springs Resort'),
  ('United States', 'California City Municipal Par 3 Golf Course'),
  ('United States', 'California Country Club'),
  ('United States', 'California Golf Club Of San Francisco'),
  ('United States', 'California Golf Course'),
  ('United States', 'California Oaks Golf Course'),
  ('United States', 'Callahan Golf Links'),
  ('United States', 'Callier Springs Country Club'),
  ('United States', 'Callippe Preserve Golf Course'),
  ('United States', 'Caloosa Golf Country Club'),
  ('United States', 'Calumet Country Club'),
  ('United States', 'Calumet Golf Club'),
  ('United States', 'Calusa Country Club'),
  ('United States', 'Calusa Country Club 12 Hole Course'),
  ('United States', 'Calusa Lakes Golf Club'),
  ('United States', 'Calusa Pines Golf Club'),
  ('United States', 'Calvert Crossing Golf Club'),
  ('United States', 'Cam2 Golf Club At Springview'),
  ('United States', 'Camaloch Golf Club'),
  ('United States', 'Camargo Club'),
  ('United States', 'Camarillo Springs Golf Course'),
  ('United States', 'Camas Meadows Golf Club'),
  ('United States', 'Cambrian Hills Golf Course'),
  ('United States', 'Cambridge Country Club'),
  ('United States', 'Camden Country Club'),
  ('United States', 'Camelback Golf Club Ambiente Course'),
  ('United States', 'Camelback Golf Club Padre Course'),
  ('United States', 'Camelia Boganvilia Golf Course At Cleveland Heights Golf Club'),
  ('United States', 'Cameron At Buffalo Hill Golf Club'),
  ('United States', 'Cameron Park Country Club'),
  ('United States', 'Camillus Golf Club'),
  ('United States', 'Camino Heights Golf Course'),
  ('United States', 'Camp Creek Golf Club'),
  ('United States', 'Camp Robinson Duffers Club'),
  ('United States', 'Campbells Scottish Highlands Golf Course'),
  ('United States', 'Campestre De Nogales'),
  ('United States', 'Camroden Golf Course'),
  ('United States', 'Canaan Country Club'),
  ('United States', 'Canadian Golf Club'),
  ('United States', 'Canajoharie Country Club'),
  ('United States', 'Canandaigua Country Club'),
  ('United States', 'Canasawacta Country Club'),
  ('United States', 'Candia Woods Golf Links'),
  ('United States', 'Candler Hills Golf Club'),
  ('United States', 'Candler Park Golf Course'),
  ('United States', 'Candlestone'),
  ('United States', 'Candlewood Country Club'),
  ('United States', 'Candlewood Golf Club'),
  ('United States', 'Candlewood Lake Club'),
  ('United States', 'Candlewood Valley Country Club'),
  ('United States', 'Cando Golf Club'),
  ('United States', 'Cane Garden Country Club Allamanda Hibiscus Course'),
  ('United States', 'Cane Garden Country Club Hibiscus Jacaranda Course'),
  ('United States', 'Cane Garden Country Club Jacaranda Allamanda Course'),
  ('United States', 'Cane Patch Par 3 Blue Nine'),
  ('United States', 'Cane Patch Par 3 Red Nine'),
  ('United States', 'Cane Patch Par 3 Yellow Nine'),
  ('United States', 'Cane Row Golf Turf Club'),
  ('United States', 'Canebrake Golf Club'),
  ('United States', 'Caney Golf Club'),
  ('United States', 'Cannon Golf Club'),
  ('United States', 'Cannonball Golf Course'),
  ('United States', 'Cannongate Golf At Sun City Peachtree'),
  ('United States', 'Canoa Hills Golf Course'),
  ('United States', 'Canoa Ranch Golf Club'),
  ('United States', 'Canongate Golf Club Lee Wilson Course'),
  ('United States', 'Canongate Golf Club Roquemore Burton Course'),
  ('United States', 'Canterbury Golf Club'),
  ('United States', 'Canterbury Green Golf Course'),
  ('United States', 'Canterbury Woods Country Club'),
  ('United States', 'Canterwood Golf Club'),
  ('United States', 'Cantiague Park Golf Course'),
  ('United States', 'Cantigny Golf'),
  ('United States', 'Cantigny Golf Youth Links'),
  ('United States', 'Canton Golf Club'),
  ('United States', 'Canyata Golf Club'),
  ('United States', 'Canyon At Forest Highlands Golf Club'),
  ('United States', 'Canyon At Mountain Dell Golf Course'),
  ('United States', 'Canyon Breeze Golf Course'),
  ('United States', 'Canyon Club'),
  ('United States', 'Canyon Crest Country Club'),
  ('United States', 'Canyon Estates Golf Course'),
  ('United States', 'Canyon Farms Golf Club'),
  ('United States', 'Canyon Gate Country Club'),
  ('United States', 'Canyon Hill At La Paloma Country Club'),
  ('United States', 'Canyon Hills Park Golf Course'),
  ('United States', 'Canyon Lake Country Club'),
  ('United States', 'Canyon Lakes At Spanish Trail Country Club'),
  ('United States', 'Canyon Lakes Golf Course'),
  ('United States', 'Canyon Lakes Golf Course Brewery'),
  ('United States', 'Canyon Meadow At Fox Hollow At Lakewood'),
  ('United States', 'Canyon Mesa Country Club'),
  ('United States', 'Canyon Oaks Country Club'),
  ('United States', 'Canyon River Golf Club'),
  ('United States', 'Canyon Springs Golf Course'),
  ('United States', 'Canyons At Oasis Golf Club'),
  ('United States', 'Canyons Golf Course'),
  ('United States', 'Cape Ann Golf Course'),
  ('United States', 'Cape Arundel Golf Club'),
  ('United States', 'Cape Cod Country Club'),
  ('United States', 'Cape Cod National Golf Club'),
  ('United States', 'Cape Fear Country Club'),
  ('United States', 'Cape Fear National At Brunswick Forest'),
  ('United States', 'Cape Girardeau Country Club'),
  ('United States', 'Cape Haze Links At Rotonda Golf Country Club'),
  ('United States', 'Cape Jaycee Municipal Golf Course'),
  ('United States', 'Cape May National Golf Club'),
  ('United States', 'Cape May Par 3 And Driving Range'),
  ('United States', 'Cape Neddick Country Club'),
  ('United States', 'Cape Royal Golf Club King Prince'),
  ('United States', 'Cape Royal Golf Club Prince Queen'),
  ('United States', 'Cape Royal Golf Club Queen King'),
  ('United States', 'Capital Canyon Club'),
  ('United States', 'Capital City Club Crabapple'),
  ('United States', 'Capital City Country Club'),
  ('United States', 'Capital Hills At Albany'),
  ('United States', 'Capitol City Golf Club'),
  ('United States', 'Capon Springs Golf Course'),
  ('United States', 'Capri Isles Golf Club'),
  ('United States', 'Caprock Ranch'),
  ('United States', 'Captains Cove'),
  ('United States', 'Captains Golf Course Port'),
  ('United States', 'Captains Golf Course Starboard'),
  ('United States', 'Captiva Course At South Seas Island Resort'),
  ('United States', 'Carbon Country Club'),
  ('United States', 'Card Inc. Golf & Country Club'),
  ('United States', 'Card Sound Golf Club'),
  ('United States', 'Cardinal At Diamondhead Country Club'),
  ('United States', 'Cardinal At Newport News Golf Club'),
  ('United States', 'Cardinal Country Club'),
  ('United States', 'Cardinal Creek Golf Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Blue Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Red Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams White Course'),
  ('United States', 'Cardinal Golf Course'),
  ('United States', 'Cardinal Hills Golf Course'),
  ('United States', 'Carefree Country Club'),
  ('United States', 'Carey Park Golf Course'),
  ('United States', 'Caribou Country Club'),
  ('United States', 'Caribou Highlands Golf And Rv'),
  ('United States', 'Carillon Golf Course'),
  ('United States', 'Carl Dickman Par 3 Golf Course'),
  ('United States', 'Carleton Glen Golf Club'),
  ('United States', 'Carlisle Barracks Golf Course'),
  ('United States', 'Carlisle Country Club'),
  ('United States', 'Carlowden Country Club'),
  ('United States', 'Carlton Oaks Lodge Country Club'),
  ('United States', 'Carmel Valley Ranch Resort'),
  ('United States', 'Carmi Country Club'),
  ('United States', 'Carmichaels Golf Club'),
  ('United States', 'Carnduff Golf Club'),
  ('United States', 'Caro Golf Club'),
  ('United States', 'Carolina Club The'),
  ('United States', 'Carolina Colours Golf Club'),
  ('United States', 'Carolina Country Club'),
  ('United States', 'Carolina Golf Club'),
  ('United States', 'Carolina Golf Par 3 Course'),
  ('United States', 'Carolina Lakes Golf Club'),
  ('United States', 'Carolina Lakes Golf Course'),
  ('United States', 'Carolina Meadows Golf Course'),
  ('United States', 'Carolina National Golf Club Egret Nine'),
  ('United States', 'Carolina National Golf Club Heron Nine'),
  ('United States', 'Carolina National Golf Club Ibis Nine'),
  ('United States', 'Carolina Plantation Golf Club'),
  ('United States', 'Carolina Shores Golf Country Club'),
  ('United States', 'Carolina Springs Golf Club'),
  ('United States', 'Carolinas Country Club'),
  ('United States', 'Caroline Virginia At Mallory Hill Golf Course'),
  ('United States', 'Carriage Greens Golf Club'),
  ('United States', 'Carrington Crossroads Golf Club'),
  ('United States', 'Carrington Golf Club'),
  ('United States', 'Carroll Country Club'),
  ('United States', 'Carroll County Country Club'),
  ('United States', 'Carroll Meadows golf course'),
  ('United States', 'Carroll Municipal Golf Course'),
  ('United States', 'Carroll Valley Golf Resort'),
  ('United States', 'Carrollton Park DGC'),
  ('United States', 'Carrollwood Country Club Cypress Meadows Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Carrollwood Country Club Meadows Pines Course'),
  ('United States', 'Carrollwood Country Club Pines Cypress Course'),
  ('United States', 'Carson Valley Golf Course'),
  ('United States', 'Carter Country Club'),
  ('United States', 'Carter Heights Golf Course'),
  ('United States', 'Carter Plantation'),
  ('United States', 'Carters Sweetland Pines Par 3 Golf Course'),
  ('United States', 'Cartersville Country Club'),
  ('United States', 'Carthage Golf Course'),
  ('United States', 'Carthage Municipal Golf Course'),
  ('United States', 'Caruthersville Country Club'),
  ('United States', 'Cary Country Club'),
  ('United States', 'Casablanca Resort Casino'),
  ('United States', 'Cascade Golf Course'),
  ('United States', 'Cascade Hills Country Club'),
  ('United States', 'Cascade Par 3 Golf Club'),
  ('United States', 'Cascades Golf Course'),
  ('United States', 'Cascata'),
  ('United States', 'Caseville Golf Course'),
  ('United States', 'Cashie Golf Country Club'),
  ('United States', 'Casolwood Golf Course'),
  ('United States', 'Casper Country Club'),
  ('United States', 'Casper Golf Club Highlands Links Course'),
  ('United States', 'Casper Golf Club Highlands Park Course'),
  ('United States', 'Casper Golf Club Park Links Course'),
  ('United States', 'Casperkill Golf Club'),
  ('United States', 'Cassadaga Country Club'),
  ('United States', 'Cassel Hills'),
  ('United States', 'Casselberry Golf Club'),
  ('United States', 'Casserly Par 3 Golf Course'),
  ('United States', 'Cassville Golf Club'),
  ('United States', 'Castine Golf Club'),
  ('United States', 'Castle Bay Country Club'),
  ('United States', 'Castle Creek Country Club'),
  ('United States', 'Castle Creek Golf Club'),
  ('United States', 'Castle Highlands Golf Course'),
  ('United States', 'Castle Hills Golf Course'),
  ('United States', 'Castle Oaks Golf Club'),
  ('United States', 'Castle Pines Golf Club'),
  ('United States', 'Castle Rock Golf Course'),
  ('United States', 'Castle Rock Golf Recreation'),
  ('United States', 'Castle Shannon Golf Course'),
  ('United States', 'Castlegar Golf Club'),
  ('United States', 'Castlewood Golf Course'),
  ('United States', 'Castlewoods Country Club The Bear Course'),
  ('United States', 'Caswell Pines Golf Club'),
  ('United States', 'Catalina Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Catalina Island Golf Club'),
  ('United States', 'Catalina Saddlebrooke At Saddlebrooke Country Club'),
  ('United States', 'Catamount Club'),
  ('United States', 'Catamount Ranch And Club'),
  ('United States', 'Catatonk Golf Club'),
  ('United States', 'Catawba Country Club'),
  ('United States', 'Catawba Creek Golf Course'),
  ('United States', 'Catawba Island Club'),
  ('United States', 'Cateechee Golf Club'),
  ('United States', 'Cathedral Canyon Golf Club'),
  ('United States', 'Cato Park'),
  ('United States', 'Catskill Golf Club'),
  ('United States', 'Catta Verdera Country Club'),
  ('United States', 'Cattail Creek Golf Course'),
  ('United States', 'Cattail Crossing Golf Course'),
  ('United States', 'Cattails At Meadowview Golf Course'),
  ('United States', 'Cattails Golf Club'),
  ('United States', 'Causeway Club'),
  ('United States', 'Cavalier Golf Yacht Club'),
  ('United States', 'Cavaliers Country Club'),
  ('United States', 'Cavalry Club'),
  ('United States', 'Cave Creek Golf Course'),
  ('United States', 'Caverns Country Club Resort'),
  ('United States', 'Cazenovia Country Club'),
  ('United States', 'Cazenovia Golf Club'),
  ('United States', 'Cazenovia Golf Course'),
  ('United States', 'Cda National Reserve'),
  ('United States', 'CeCelia''s Golf Course'),
  ('United States', 'Cecil Field Golf Club'),
  ('United States', 'Cedar Aspen At Mccall Golf Course'),
  ('United States', 'Cedar Beach Golf Course'),
  ('United States', 'Cedar Bend Golf Course'),
  ('United States', 'Cedar Chase Golf Club'),
  ('United States', 'Cedar Creek At Star Valley Ranch Country Club'),
  ('United States', 'Cedar Creek Family Golf Center'),
  ('United States', 'Cedar Creek Golf Club'),
  ('United States', 'Cedar Creek Golf Country Club'),
  ('United States', 'Cedar Creek Golf Course'),
  ('United States', 'Cedar Crest Golf Course'),
  ('United States', 'Cedar Farms Golf Club'),
  ('United States', 'Cedar Glen Golf Club'),
  ('United States', 'Cedar Glen Golf Course'),
  ('United States', 'Cedar Hammock Golf Country Club'),
  ('United States', 'Cedar Heights Golf Course'),
  ('United States', 'Cedar Hill Country Club'),
  ('United States', 'Cedar Hill Golf Club'),
  ('United States', 'Cedar Hill Golf Course'),
  ('United States', 'Cedar Hills Golf Club'),
  ('United States', 'Cedar Hills Golf Club Short Course'),
  ('United States', 'Cedar Hills Golf Course'),
  ('United States', 'Cedar Knob Golf Course'),
  ('United States', 'Cedar Lake Club'),
  ('United States', 'Cedar Lake Golf Club'),
  ('United States', 'Cedar Links Country Club'),
  ('United States', 'Cedar Park Golf Course'),
  ('United States', 'Cedar Park Putting Course'),
  ('United States', 'Cedar Pines Golf Course'),
  ('United States', 'Cedar Point Country Club'),
  ('United States', 'Cedar Point Country Club Par 3 Course'),
  ('United States', 'Cedar Point Golf Club'),
  ('United States', 'Cedar Pointe Golf Course'),
  ('United States', 'Cedar Rapids Country Club'),
  ('United States', 'Cedar Ridge Country Club'),
  ('United States', 'Cedar Ridge Golf Course'),
  ('United States', 'Cedar Ridges Golf Course'),
  ('United States', 'Cedar River Golf Club'),
  ('United States', 'Cedar River Golf Course'),
  ('United States', 'Cedar Rock Country Club'),
  ('United States', 'Cedar Springs Golf Course'),
  ('United States', 'Cedar Trace'),
  ('United States', 'Cedar Valley Golf And Country Club'),
  ('United States', 'Cedar Valley Golf Center'),
  ('United States', 'Cedar Valley Golf Club'),
  ('United States', 'Cedar Valley Golf Course'),
  ('United States', 'Cedar View Golf Course'),
  ('United States', 'Cedarbrook Country Club'),
  ('United States', 'Cedarbrook Golf Course'),
  ('United States', 'Cedarcrest Golf Course'),
  ('United States', 'Cedardell Golf Club'),
  ('United States', 'Cedaredge Golf Club'),
  ('United States', 'Cedarholm Golf Course'),
  ('United States', 'Cedars At High Cedars Golf Club'),
  ('United States', 'Cedars Country Club'),
  ('United States', 'Cedars Edge Golf Course'),
  ('United States', 'Cedars Golf Club'),
  ('United States', 'Cedars Golf Country Club'),
  ('United States', 'Cedars Golf Course'),
  ('United States', 'Cedarview Golf Course'),
  ('United States', 'Cedarwood Country Club'),
  ('United States', 'Celebration Golf Club'),
  ('United States', 'Celina Lynx Golf Club'),
  ('United States', 'Centennial Acres Midday Sunset'),
  ('United States', 'Centennial Acres Sunrise Midday'),
  ('United States', 'Centennial Acres Sunrise Sunset'),
  ('United States', 'Centennial At Philadelphia Country Club'),
  ('United States', 'Centennial Farm Golf Club'),
  ('United States', 'Centennial Golf Course'),
  ('United States', 'Centennial Park 9-Hole Golf Course'),
  ('United States', 'Centennial Toomey At Huntingdon Valley Country Club'),
  ('United States', 'Centennial Valley Golf Course'),
  ('United States', 'Center Country Club'),
  ('United States', 'Center West At Ridgewood Country Club The'),
  ('United States', 'Centerbrook Golf Course'),
  ('United States', 'Centerpointe Country Club'),
  ('United States', 'Centerton Golf Club'),
  ('United States', 'Central Valley Golf Club'),
  ('United States', 'Centre Hills Golf Course'),
  ('United States', 'Century Country Club'),
  ('United States', 'Century Oaks Golf Club'),
  ('United States', 'Cerbat Cliffs Golf Course'),
  ('United States', 'Cerritos Ironwood Golf Course'),
  ('United States', 'Chagrin Valley Country Club'),
  ('United States', 'Chalk Mountain Golf Course'),
  ('United States', 'Challenge At Pinewild Country Club'),
  ('United States', 'Challenge At Suntree Country Club'),
  ('United States', 'Challenge At White Deer Golf Club'),
  ('United States', 'Challenger 3 Golf Course'),
  ('United States', 'Challenger At Blue Hill Country Club'),
  ('United States', 'Challenger At Palm Valley Country Club'),
  ('United States', 'Challenger Golf Club Los Cumbres Course'),
  ('United States', 'Challis Golf Course'),
  ('United States', 'Chamberlyne Country Club'),
  ('United States', 'Chambers Bay'),
  ('United States', 'Chambersburg Country Club'),
  ('United States', 'Champaign Country Club'),
  ('United States', 'Champion At Battle Creek Public Golf'),
  ('United States', 'Champion At Fox Ridge Golf Course'),
  ('United States', 'Champion Hill Golf Course'),
  ('United States', 'Champion Hills Club'),
  ('United States', 'Champion Hills Country Club'),
  ('United States', 'Champion Lakes Golf And Country Club'),
  ('United States', 'Champion Lakes Golf Course'),
  ('United States', 'Champions At Palm Aire Country Club'),
  ('United States', 'Champions Golf Course'),
  ('United States', 'Champions Pointe Golf Club'),
  ('United States', 'Champions Retreat Golf Club Nicklaus Bluff Nine'),
  ('United States', 'Champions Retreat Golf Club Palmer Island Nine'),
  ('United States', 'Champions Retreat Golf Club Player Creek Nine'),
  ('United States', 'Champions Run'),
  ('United States', 'Champions Run Country Club'),
  ('United States', 'Championsgate Country Club'),
  ('United States', 'Championsgate Golf Club Champions 9'),
  ('United States', 'Championsgate Golf Club International'),
  ('United States', 'Championsgate Golf Club National'),
  ('United States', 'Championship At Blue Hill Country Club'),
  ('United States', 'Championship At Boca Raton Municipal Golf Course'),
  ('United States', 'Championship At Buffalo Hill Golf Club'),
  ('United States', 'Championship At Burns Park Golf Course'),
  ('United States', 'Championship At Colony West Country Club'),
  ('United States', 'Championship At Cyprian Keyes Golf Club'),
  ('United States', 'Championship At Ferncroft Country Club'),
  ('United States', 'Championship At Harbor Links Golf Course'),
  ('United States', 'Championship At Hollybrook Golf Tennis Club'),
  ('United States', 'Championship At Incline Village Golf Resort'),
  ('United States', 'Championship At Lake Shastina Golf Resort'),
  ('United States', 'Championship At Moon Valley Country Club'),
  ('United States', 'Championship At Palm Valley Country Club'),
  ('United States', 'Championship At Rebsamen Park Golf Course'),
  ('United States', 'Championship At Ridgecrest Golf Course'),
  ('United States', 'Championship At Rockland Lake Golf Course'),
  ('United States', 'Championship At Saint Clair Country Club'),
  ('United States', 'Championship At Saratoga Spa State Park'),
  ('United States', 'Championship At Seven Springs Country Club'),
  ('United States', 'Championship At Viewpoint Golf Resort'),
  ('United States', 'Championship Course At Crosswinds Golf Club'),
  ('United States', 'Championship Golf Course At University Of New Mexico'),
  ('United States', 'Champlain Country Club'),
  ('United States', 'Chandler Golf Course'),
  ('United States', 'Chandler Park Golf Course'),
  ('United States', 'Chanticlair Golf Club'),
  ('United States', 'Chanticleer At Greenville Country Club'),
  ('United States', 'Chantilly National Golf Country Club'),
  ('United States', 'Chaparral Country Club'),
  ('United States', 'Chapel Hill Country Club'),
  ('United States', 'Chapel Hill Golf Course'),
  ('United States', 'Chapel Hills Golf Course'),
  ('United States', 'Chappell Golf Course'),
  ('United States', 'Chardell Golf Course'),
  ('United States', 'Chardon Lakes Golf Course'),
  ('United States', 'Chardonnay Golf Club'),
  ('United States', 'Chariot Run'),
  ('United States', 'Charles River Country Club'),
  ('United States', 'Charles T Myers Public Golf Course'),
  ('United States', 'Charleston Municipal Golf Course'),
  ('United States', 'Charleston National Golf Club'),
  ('United States', 'Charleston Pines At Lima Golf Country Club'),
  ('United States', 'Charleston Springs Golf Course North Course'),
  ('United States', 'Charleston Springs Golf Course South Course'),
  ('United States', 'Charlevoix Municipal Golf Course'),
  ('United States', 'Charlie Vettner Golf Course'),
  ('United States', 'Charlie Yates Golf Course'),
  ('United States', 'Charlotte Country Club'),
  ('United States', 'Charlotte Harbor National Golf Club'),
  ('United States', 'Charlotte National Golf Course'),
  ('United States', 'Charter Oak Country Club'),
  ('United States', 'Chartiers Country Club'),
  ('United States', 'Charwood Golf Club'),
  ('United States', 'Chase Golf Course'),
  ('United States', 'Chase Hammond Golf Club'),
  ('United States', 'Chaska Golf Course'),
  ('United States', 'Chaska Par 30'),
  ('United States', 'Chaska Town Course'),
  ('United States', 'Chastain Park Golf Course'),
  ('United States', 'Chatata Valley Golf Club'),
  ('United States', 'Chateau Elan Golf Club Chateau Course'),
  ('United States', 'Chateau Elan Golf Club Executive Par 3 Course'),
  ('United States', 'Chateau Elan Golf Club Woodlands Course'),
  ('United States', 'Chateau Golf Country Club'),
  ('United States', 'Chatham Hills Golf Course'),
  ('United States', 'Chatham Seaside Links'),
  ('United States', 'Chatmoss Country Club'),
  ('United States', 'Chattahoochee Golf Club'),
  ('United States', 'Chattanooga Golf Country Club'),
  ('United States', 'Chattooga Golf Club'),
  ('United States', 'Chatuge Shores Golf Course'),
  ('United States', 'Chautauqua Golf Club Hill Course'),
  ('United States', 'Chautauqua Golf Club Lake Course'),
  ('United States', 'Chautauqua Point Golf Racquetball Center'),
  ('United States', 'Cheam Mountain Golf Course'),
  ('United States', 'Cheboygan Golf & Country Club'),
  ('United States', 'Chechessee Creek Club'),
  ('United States', 'Cheeca Lodge'),
  ('United States', 'Cheena Star Course At Santa Ana Golf Club'),
  ('United States', 'Chelmsford Country Club'),
  ('United States', 'Chemawa Golf Course'),
  ('United States', 'Chemung Golf Course'),
  ('United States', 'Chemung Hills Golf Club'),
  ('United States', 'Chena Bend Golf Course'),
  ('United States', 'Chenal Country Club Bear Den Mountain Course'),
  ('United States', 'Chenal Country Club Founders Course'),
  ('United States', 'Chenango Commons Golf Course'),
  ('United States', 'Chenango Valley State Park Golf Course'),
  ('United States', 'Chenequa Country Club'),
  ('United States', 'Chennault Park Golf Course'),
  ('United States', 'Chenoweth'),
  ('United States', 'Chequamegon Bay Golf Club'),
  ('United States', 'Chequessett Yacht Country Club'),
  ('United States', 'Cheraw State Park Golf Course'),
  ('United States', 'Cherokee Choctaw At Big Canoe Golf Club'),
  ('United States', 'Cherokee Creek Golf Club'),
  ('United States', 'Cherokee Golf Center'),
  ('United States', 'Cherokee Golf Country Club'),
  ('United States', 'Cherokee Golf Course'),
  ('United States', 'Cherokee Golf and Country Club'),
  ('United States', 'Cherokee Hills Golf Club'),
  ('United States', 'Cherokee Hills Golf Course'),
  ('United States', 'Cherokee National Golf Course'),
  ('United States', 'Cherokee Plantation'),
  ('United States', 'Cherokee Rose Country Club'),
  ('United States', 'Cherokee Run Golf Club'),
  ('United States', 'Cherokee Seminole At Indian Hills Country Club'),
  ('United States', 'Cherokee Springs Golf Club'),
  ('United States', 'Cherokee Trails Golf Course'),
  ('United States', 'Cherokee Valley Course And Club'),
  ('United States', 'Cherokee Valley Golf Club'),
  ('United States', 'Cherry Creek Golf Club'),
  ('United States', 'Cherry Creek Golf Course'),
  ('United States', 'Cherry Creek Golf The Links Course'),
  ('United States', 'Cherry Creek The Woods Course'),
  ('United States', 'Cherry Hill Country Club'),
  ('United States', 'Cherry Hill Golf Club'),
  ('United States', 'Cherry Hill Golf Course'),
  ('United States', 'Cherry Hill Golf Resort'),
  ('United States', 'Cherry Hills Course At Palmer Legends'),
  ('United States', 'Cherry Hills Golf Course'),
  ('United States', 'Cherry Island Golf Course'),
  ('United States', 'Cherry Oaks Golf Club'),
  ('United States', 'Cherry Ridge'),
  ('United States', 'Cherry Ridge Golf Course'),
  ('United States', 'Cherry Valley Club'),
  ('United States', 'Cherry Valley Country Club'),
  ('United States', 'Cherry Valley Golf Course'),
  ('United States', 'Cherryville Country Club'),
  ('United States', 'Cherrywood Golf Club'),
  ('United States', 'Cherrywood Golf Course'),
  ('United States', 'Chesapeake Bay Golf Club At Rising Sun'),
  ('United States', 'Chesapeake Golf Club'),
  ('United States', 'Chesapeake Hills Golf Club'),
  ('United States', 'Chesapeake Run Golf Club'),
  ('United States', 'Cheshire Hills Golf Course'),
  ('United States', 'Chesnee Country Club'),
  ('United States', 'Chestatee Golf Club'),
  ('United States', 'Chester Country Club'),
  ('United States', 'Chester Golf Club'),
  ('United States', 'Chester River Yacht Country Club'),
  ('United States', 'Chester Valley Golf Club'),
  ('United States', 'Chester Washington Golf Course'),
  ('United States', 'Chestnut Hill Golf Course'),
  ('United States', 'Chestnut Hills'),
  ('United States', 'Chestnut Hills Golf Club'),
  ('United States', 'Chestnut Mountain Golf Club'),
  ('United States', 'Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Chestnut Valley Golf Course'),
  ('United States', 'Chetremon Golf Course'),
  ('United States', 'Cheval Golf And Athletic Club'),
  ('United States', 'Chevy Chase Club'),
  ('United States', 'Chevy Chase Country Club'),
  ('United States', 'Chevy Chase Golf Club'),
  ('United States', 'Chewelah Golf Country Club'),
  ('United States', 'Chewelah Golf Country Club 9 Hole Course'),
  ('United States', 'Cheyenne Country Club'),
  ('United States', 'Cheyenne Golf Course'),
  ('United States', 'Cheyenne Hills Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course Coyote Run Junior'),
  ('United States', 'Chi Chi Rodriguez Golf Club'),
  ('United States', 'Chicago Golf Association'),
  ('United States', 'Chicago Golf Club'),
  ('United States', 'Chicago Heights Park District Golf Course East'),
  ('United States', 'Chicago Heights Park District Golf Course West'),
  ('United States', 'Chicago Highlands Club'),
  ('United States', 'Chick Evans Golf Course'),
  ('United States', 'Chickasaw Country Club'),
  ('United States', 'Chickasaw Point Golf Course'),
  ('United States', 'Chickasaw Pointe Golf Club'),
  ('United States', 'Chickasha Golf Country Club'),
  ('United States', 'Chicopee Country Club'),
  ('United States', 'Chicopee Woods Golf Course Mill Nine'),
  ('United States', 'Chicopee Woods Golf Course School Nine'),
  ('United States', 'Chicopee Woods Golf Course Village Nine'),
  ('United States', 'Chicora Country Club'),
  ('United States', 'Chiefland Golf Country Club'),
  ('United States', 'Chikaming Country Club'),
  ('United States', 'Childress Country Club'),
  ('United States', 'Chilliwack Golf Club'),
  ('United States', 'Chimera Golf Club'),
  ('United States', 'Chimney Oaks Golf Club'),
  ('United States', 'Chimney Rock Municipal Golf Course'),
  ('United States', 'China Lake Golf Course'),
  ('United States', 'Chinook Golf Country Club'),
  ('United States', 'Chip''s Clubhouse'),
  ('United States', 'Chipeta Golf Course'),
  ('United States', 'Chippanee Golf Club'),
  ('United States', 'Chippendale Golf Course'),
  ('United States', 'Chippers Practice Range'),
  ('United States', 'Chippewa Banks Disc Golf Course'),
  ('United States', 'Chippewa Golf Club'),
  ('United States', 'Chippewa Hills Country Club'),
  ('United States', 'Chiricahua Course At Desert Mountain Golf Club'),
  ('United States', 'Chisel Creek Golf Club'),
  ('United States', 'Chisholm Hills Country Club'),
  ('United States', 'Chockoyotte Country Club'),
  ('United States', 'Choctaw Cherokee At Indian Hills Country Club'),
  ('United States', 'Choctaw Country Club'),
  ('United States', 'Choctaw Creek At Big Canoe Golf Club'),
  ('United States', 'Choctaw Creek Golf Course'),
  ('United States', 'Cholla Course At We Ko Pa Golf Club'),
  ('United States', 'Chomonix Golf Course'),
  ('United States', 'Chosen Valley Golf Club'),
  ('United States', 'Choteau Country Club'),
  ('United States', 'Chris Bargas Golf Club At Whitney Farms'),
  ('United States', 'Christiana Creek Country Club'),
  ('United States', 'Christina Lake Golf Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Christopher Morley Park'),
  ('United States', 'Chula Vista At The Villages Executive Golf Trail'),
  ('United States', 'Chula Vista Golf Course'),
  ('United States', 'Churchill Greens At The Villages Executive Golf Trail'),
  ('United States', 'Churn Creek Golf Course'),
  ('United States', 'Cimarron County Golf Course'),
  ('United States', 'Cimarron Golf Club'),
  ('United States', 'Cimarron Golf Club Boulder Course'),
  ('United States', 'Cimarron Golf Club Pebble Par 3 Course'),
  ('United States', 'Cimarron Golf Course'),
  ('United States', 'Cimarron National Golf Club Aqua Canyon Course'),
  ('United States', 'Cimarron National Golf Club Cimarron National Course'),
  ('United States', 'Cimarron Valley Golf Club'),
  ('United States', 'Cimarrone Golf Club'),
  ('United States', 'Cincinnati Country Club'),
  ('United States', 'Cinder Ridge Golf Course'),
  ('United States', 'Cinnabar Hills Golf Club Canyon Mountain'),
  ('United States', 'Cinnabar Hills Golf Club Lake Canyon'),
  ('United States', 'Cinnabar Hills Golf Club Mountain Lake'),
  ('United States', 'Circle R Golf Course'),
  ('United States', 'Circlestone Country Club'),
  ('United States', 'Circling Hills Golf Course'),
  ('United States', 'Circling Raven Golf Club'),
  ('United States', 'Citrus Hills Golf Country Club Meadows Course'),
  ('United States', 'Citrus Hills Golf Country Club Oaks Course'),
  ('United States', 'Citrus National Golf Club'),
  ('United States', 'Citrus Springs Golf Country Club'),
  ('United States', 'City Club Marietta'),
  ('United States', 'City Of Douglas Municipal Golf Course'),
  ('United States', 'City Of Lauderhill Golf Course'),
  ('United States', 'City Of Portsmouth Bide A Wee Golf Course'),
  ('United States', 'City Park Golf Course'),
  ('United States', 'City Park Nine Golf Course'),
  ('United States', 'City of Florence Golf Course'),
  ('United States', 'Civitan Golf Course'),
  ('United States', 'Cj S Par 3 Golf Course'),
  ('United States', 'Claflin Golf Club'),
  ('United States', 'Clair Mar Golf Course'),
  ('United States', 'Claremont Country Club'),
  ('United States', 'Clarinda Country Club'),
  ('United States', 'Clarion Oaks Golf Course'),
  ('United States', 'Clark Lake Golf Course'),
  ('United States', 'Clarksdale Country Club'),
  ('United States', 'Clarksville Country Club'),
  ('United States', 'Clarmond Country Club'),
  ('United States', 'Classic At Suntree Country Club'),
  ('United States', 'Classic Golf Club'),
  ('United States', 'Clay Center Country Club'),
  ('United States', 'Clay County Country Club'),
  ('United States', 'Clayton Country Club'),
  ('United States', 'Clayton Golf Club'),
  ('United States', 'Clayton Park Golf Course'),
  ('United States', 'Clear Creek Golf Center'),
  ('United States', 'Clear Creek Golf Club'),
  ('United States', 'Clear Fork Valley Country Club'),
  ('United States', 'Clear Lake Country Club'),
  ('United States', 'Clear Lake Golf Club'),
  ('United States', 'Clearbrook'),
  ('United States', 'Clearbrook Golf Course'),
  ('United States', 'Clearfield Curwensville Country Club'),
  ('United States', 'Clearview Country Club'),
  ('United States', 'Clearview Golf Course'),
  ('United States', 'Clearview Park Golf Course'),
  ('United States', 'Clearwater Country Club'),
  ('United States', 'Clearwater Lake Golf Course'),
  ('United States', 'Clerbrook Golf Rv Resort'),
  ('United States', 'Clermont National Golf Course'),
  ('United States', 'Cleveland Country Club'),
  ('United States', 'Clewiston Golf Course'),
  ('United States', 'Cliff Park Inn Golf Course'),
  ('United States', 'Cliff View Golf Club And Inn'),
  ('United States', 'Cliffhangers Golf Course'),
  ('United States', 'Clifton Fine Municipal Golf Course'),
  ('United States', 'Clifton Highlands Golf Club'),
  ('United States', 'Clifton Highlands Short Course'),
  ('United States', 'Clifton Hollow Golf Club'),
  ('United States', 'Clifton Springs Country Club'),
  ('United States', 'Cliftondale Country Club'),
  ('United States', 'Clifty Creek Golf Course'),
  ('United States', 'Clinchview Golf Club'),
  ('United States', 'Clinton Country Club'),
  ('United States', 'Clinton Golf Course'),
  ('United States', 'Clinton Heights Golf'),
  ('United States', 'Clintonville Riverside Golf Course'),
  ('United States', 'Clio Country Club'),
  ('United States', 'Clipper Galleon At Shipyard Golf Club'),
  ('United States', 'Clive Clark Course At Hideaway Club'),
  ('United States', 'Cloquet Country Club'),
  ('United States', 'Cloud 9 At Angel Park Golf Club'),
  ('United States', 'Clover Hill Golf Course'),
  ('United States', 'Clover Meadows Golf Course'),
  ('United States', 'Clovercrest Golf Course'),
  ('United States', 'Cloverleaf Golf Course'),
  ('United States', 'Clovernook Country Club'),
  ('United States', 'Club Adena'),
  ('United States', 'Club At Hidden Creek The'),
  ('United States', 'Club At Polo Club The'),
  ('United States', 'Club At River Oaks'),
  ('United States', 'Club At Shoal Creek'),
  ('United States', 'Club Campestre De Cananea'),
  ('United States', 'Club Campestre De Tijuana'),
  ('United States', 'Club Campestre Mexicali'),
  ('United States', 'Club De Golf Baie Missisquoi'),
  ('United States', 'Club De Golf Chateau Bromont'),
  ('United States', 'Club De Golf Coaticook'),
  ('United States', 'Club De Golf De Cowansville'),
  ('United States', 'Club De Golf De Knowlton'),
  ('United States', 'Club De Golf De La Vallee Du Temiscouata'),
  ('United States', 'Club De Golf De Napierville'),
  ('United States', 'Club De Golf Dufferin Heights'),
  ('United States', 'Club De Golf International 2000 America Saint Bernard'),
  ('United States', 'Club De Golf International 2000 Champlain America'),
  ('United States', 'Club De Golf International 2000 Saint Bernard Champlain'),
  ('United States', 'Club De Golf Inverness'),
  ('United States', 'Club De Golf Lac Brome'),
  ('United States', 'Club De Golf Lac Megantic'),
  ('United States', 'Club De Golf Milby'),
  ('United States', 'Club De Golf North Hatley'),
  ('United States', 'Club De Golf Ormstown'),
  ('United States', 'Club De Golf St Anicet Port Lewis'),
  ('United States', 'Club De Golf St Anicet St Anicet'),
  ('United States', 'Club De Golf Trout River'),
  ('United States', 'Club De Golf Venise Le Deauville'),
  ('United States', 'Club De Golf Venise Le Venise'),
  ('United States', 'Club De Golf Waterville'),
  ('United States', 'Club Green Meadows'),
  ('United States', 'Club Med Sandpiper Bay'),
  ('United States', 'Club Tucker Golf Course'),
  ('United States', 'Cnc Links'),
  ('United States', 'Coachmans Golf Resort'),
  ('United States', 'Coahoma Country Club'),
  ('United States', 'Coakley Russo Memorial Golf Course'),
  ('United States', 'Coal Creek Golf Course'),
  ('United States', 'Coashaukee At Balsams Grand Resort Hotel The'),
  ('United States', 'Coatesville Country Club'),
  ('United States', 'Cobble Hill Golf Course'),
  ('United States', 'Cobblestone Creek Country Club'),
  ('United States', 'Cobblestone Creek Golf Club'),
  ('United States', 'Cobblestone Golf Course'),
  ('United States', 'Cobblestone Park Golf Club Black Course'),
  ('United States', 'Cobblestone Park Golf Club Garnet Course'),
  ('United States', 'Cobblestone Park Golf Club Gold Course'),
  ('United States', 'Cobbossee Colony Golf'),
  ('United States', 'Cobbs Glen Country Club'),
  ('United States', 'Cobleskill Golf Country Club'),
  ('United States', 'Cobre Valle Country Club'),
  ('United States', 'Cochecho Country Club'),
  ('United States', 'Cochise Course At Desert Mountain Golf Club'),
  ('United States', 'Cochiti Golf Club'),
  ('United States', 'Cocopah Bend Rv Golf Resort'),
  ('United States', 'Cocopah Rio Colorado Golf Course'),
  ('United States', 'Coeur Dalene Golf Club'),
  ('United States', 'Coeur Dalene Resort Golf Course'),
  ('United States', 'Coffee Mill Country Club'),
  ('United States', 'Coffeyville Country Club'),
  ('United States', 'Coffin Golf Course'),
  ('United States', 'Cog Hill Golf & Country Club'),
  ('United States', 'Coharie Country Club'),
  ('United States', 'Cohasse Country Club'),
  ('United States', 'Cohasset Golf Club'),
  ('United States', 'Cokesbury Hills Golf Club'),
  ('United States', 'Colbert Hills'),
  ('United States', 'Colbert Hills Par 3'),
  ('United States', 'Cold Brook Golf Rv Resort'),
  ('United States', 'Cold Spring Country Club'),
  ('United States', 'Cold Springs Golf Country Club'),
  ('United States', 'Cold Springs Golf Course'),
  ('United States', 'Cold Water Canyon Golf Course'),
  ('United States', 'Coldstream Country Club'),
  ('United States', 'Coldwater Country Club'),
  ('United States', 'Coldwater Golf Club'),
  ('United States', 'Coldwater Golf Course'),
  ('United States', 'Coldwater Golf Links'),
  ('United States', 'Cole Acres Golf Course'),
  ('United States', 'Colebrook Country Club'),
  ('United States', 'Colfax Golf Club'),
  ('United States', 'Colin Creek Golf Club'),
  ('United States', 'Colina Park Golf Course'),
  ('United States', 'College Fields Golf Club'),
  ('United States', 'College Hill Golf Course'),
  ('United States', 'College Park Municipal Golf Course'),
  ('United States', 'Collegiate Peaks Golf Course'),
  ('United States', 'Colliers Reserve Country Club'),
  ('United States', 'Collindale Golf Course'),
  ('United States', 'Collins Hill Golf Club'),
  ('United States', 'Collison Par 3 Golf Course'),
  ('United States', 'Colockum Ridge Golf Course'),
  ('United States', 'Colonia Country Club'),
  ('United States', 'Colonial Acres Golf Course'),
  ('United States', 'Colonial Charters Golf Club'),
  ('United States', 'Colonial Country Club'),
  ('United States', 'Colonial Golf Course'),
  ('United States', 'Colonial Golf Tennis Club'),
  ('United States', 'Colonial Golfers Club'),
  ('United States', 'Colonial Heritage 9 Course'),
  ('United States', 'Colonial Heritage Club'),
  ('United States', 'Colonial Hills Golf Club'),
  ('United States', 'Colonial Oaks Golf Club'),
  ('United States', 'Colonial Park Golf Course'),
  ('United States', 'Colonial Ridge Golf'),
  ('United States', 'Colonie Country Club'),
  ('United States', 'Colonnade Golf And Country Club'),
  ('United States', 'Colorado Golf Club'),
  ('United States', 'Colorado Golf Club 9 Hole Course'),
  ('United States', 'Colorado National Golf Club'),
  ('United States', 'Colorado Springs Country Club'),
  ('United States', 'Colton Golf Club'),
  ('United States', 'Colts Neck Golf Club'),
  ('United States', 'Columbia Country Club'),
  ('United States', 'Columbia Country Club Ridgewood Lakeside'),
  ('United States', 'Columbia Country Club Ridgewood Tall Pines'),
  ('United States', 'Columbia Country Club Tall Pines Lakeside'),
  ('United States', 'Columbia Edgewater Country Club Macan Course'),
  ('United States', 'Columbia Edgewater Country Club Par 3 Mason Course'),
  ('United States', 'Columbia Golf Club'),
  ('United States', 'Columbia Golf Country Club'),
  ('United States', 'Columbia Golf Course'),
  ('United States', 'Columbia Hills Golf and Swim Club'),
  ('United States', 'Columbia Park Golf Links'),
  ('United States', 'Columbia Point Golf Course'),
  ('United States', 'Columbine Country Club'),
  ('United States', 'Columbine Country Club Par 3 Golf Course'),
  ('United States', 'Columbus Country Club'),
  ('United States', 'Columbus Park Golf Course'),
  ('United States', 'Colusa Golf Country Club'),
  ('United States', 'Colwood Golf Center'),
  ('United States', 'Comanche Lake Golf Course'),
  ('United States', 'Comanche Nation Golf Course'),
  ('United States', 'Commonground Golf Course'),
  ('United States', 'Commonground Golf Course Junior Par 3 Course'),
  ('United States', 'Commonwealth National Golf Club'),
  ('United States', 'Community Golf Course'),
  ('United States', 'Como Park Golf Course'),
  ('United States', 'Compass Pointe Golf Course'),
  ('United States', 'Compton Par 3 Golf Course'),
  ('United States', 'Comstock River At Empire Ranch Golf Course'),
  ('United States', 'Conchas Dam Park Golf Course'),
  ('United States', 'Concord Country Club'),
  ('United States', 'Concord Crest Golf Course'),
  ('United States', 'Concord Golf Club'),
  ('United States', 'Concord Hills Golf Course'),
  ('United States', 'Concordia Golf Club'),
  ('United States', 'Concordia Golf Wellness'),
  ('United States', 'Conestoga Country Club'),
  ('United States', 'Conestoga Golf Club'),
  ('United States', 'Conesus Golf Club'),
  ('United States', 'Conewango Valley Country Club'),
  ('United States', 'Congaree Golf Club'),
  ('United States', 'Congress Lake Golf Club'),
  ('United States', 'Conklin Players Club'),
  ('United States', 'Conley Resort'),
  ('United States', 'Connecticut Golf Club'),
  ('United States', 'Connecticut National Golf Club'),
  ('United States', 'Connestee Falls Golf Course'),
  ('United States', 'Connoquenessing Country Club'),
  ('United States', 'Conocodell Golf Club'),
  ('United States', 'Conquistador Golf Course'),
  ('United States', 'Conrad Golf Course'),
  ('United States', 'Continental Country Club'),
  ('United States', 'Continental Golf Course'),
  ('United States', 'Contra Costa Country Club'),
  ('United States', 'Contraband Bayou Golf Club At Lauberge Du Lac'),
  ('United States', 'Conway Country Club'),
  ('United States', 'Conway Farms Golf Club'),
  ('United States', 'Cool Creek Country Club'),
  ('United States', 'Cool Springs Golf Course'),
  ('United States', 'Coon Rapids Country Club'),
  ('United States', 'Cooper Colony Country Club'),
  ('United States', 'Coopers Hawk Golf Course'),
  ('United States', 'Coosa Country Club'),
  ('United States', 'Coosaw Creek Country Club'),
  ('United States', 'Copake Country Club'),
  ('United States', 'Copley Country Club'),
  ('United States', 'Copper Basin Golf Club'),
  ('United States', 'Copper Canyon Golf Club Lake Mountain Course'),
  ('United States', 'Copper Canyon Golf Club Mountain Vista Course'),
  ('United States', 'Copper Canyon Golf Club Vista Lake Course'),
  ('United States', 'Copper Creek Golf Club'),
  ('United States', 'Copper Creek Golf Course'),
  ('United States', 'Copper Golf Club'),
  ('United States', 'Copper Hill Country Club'),
  ('United States', 'Copper Hill Golf Club'),
  ('United States', 'Copper Hills Golf and Country Club'),
  ('United States', 'Copper Mill Golf Club'),
  ('United States', 'Copper Ridge Golf Club'),
  ('United States', 'Copper River Country Club'),
  ('United States', 'Copper Rock Golf Course'),
  ('United States', 'Copperleaf Golf Club'),
  ('United States', 'Coral Canyon Golf Course'),
  ('United States', 'Coral Creek Club'),
  ('United States', 'Coral Creek Golf Course'),
  ('United States', 'Coral Oaks Golf Course'),
  ('United States', 'Coral Ridge Country Club'),
  ('United States', 'Coral Ridge Country Club Rees 9'),
  ('United States', 'Corbin Hills Golf Course'),
  ('United States', 'Cordevalle Golf Club'),
  ('United States', 'Cordova Bay Golf Course'),
  ('United States', 'Cordova Bay Golf Course Ridge'),
  ('United States', 'Cordova Golf Course'),
  ('United States', 'Corey Creek Golf Club'),
  ('United States', 'Corica Park South Course'),
  ('United States', 'Corica Park The Earl Fry North Course'),
  ('United States', 'Corica Park The Mif Albright Par 3 Course'),
  ('United States', 'Cornerstone Club'),
  ('United States', 'Corning Country Club'),
  ('United States', 'Cornwall Golf And Country Club'),
  ('United States', 'Coronach Golf Club'),
  ('United States', 'Coronado Country Club'),
  ('United States', 'Coronado Golf Course'),
  ('United States', 'Corral De Tierra Country Club'),
  ('United States', 'Correctionville Golf Club'),
  ('United States', 'Corry Country Club'),
  ('United States', 'Corte Bella Golf Club'),
  ('United States', 'Cortez Golf Course'),
  ('United States', 'Cortland Country Club'),
  ('United States', 'Corunna Hills Golf Course'),
  ('United States', 'Corydon Municipal Golf Course'),
  ('United States', 'Costa Del Sol Golf Club'),
  ('United States', 'Cotton Creek At The Craft Farms Resort'),
  ('United States', 'Cotton Dike At Dataw Island Golf Course'),
  ('United States', 'Cottonwood At Torrington Golf Course'),
  ('United States', 'Cottonwood Country Club'),
  ('United States', 'Cottonwood Falls Country Club'),
  ('United States', 'Cottonwood Golf Club'),
  ('United States', 'Cottonwood Golf Club Ivanhoe Course'),
  ('United States', 'Cottonwood Golf Course'),
  ('United States', 'Cottonwood Hills Golf Club'),
  ('United States', 'Cottonwood Hills Golf Club Championship Course'),
  ('United States', 'Cottonwood Hills Golf Club Executive Par 3 Course'),
  ('United States', 'Cottonwood Links'),
  ('United States', 'Cottonwood Silo At West Woods Golf Club'),
  ('United States', 'Cotuit Highground Country Club'),
  ('United States', 'Coudersport Golf Club'),
  ('United States', 'Cougar Point At Kiawah Island Golf Resort'),
  ('United States', 'Coulee Golf Bowl'),
  ('United States', 'Council Bluffs Country Club'),
  ('United States', 'Council Fire Golf Club'),
  ('United States', 'Council Grove Country Club'),
  ('United States', 'Council Mountain Golf Course'),
  ('United States', 'Country Club At Boca Raton Resort Club The'),
  ('United States', 'Country Club At Castle Pines'),
  ('United States', 'Country Club At Pleasantville The'),
  ('United States', 'Country Club Estates Golf Course'),
  ('United States', 'Country Club Of Alabama'),
  ('United States', 'Country Club Of Asheville The'),
  ('United States', 'Country Club Of Barre'),
  ('United States', 'Country Club Of Billerica'),
  ('United States', 'Country Club Of Buffalo'),
  ('United States', 'Country Club Of Canton'),
  ('United States', 'Country Club Of Charleston'),
  ('United States', 'Country Club Of Columbus'),
  ('United States', 'Country Club Of Coral Springs'),
  ('United States', 'Country Club Of Culpeper'),
  ('United States', 'Country Club Of Darien'),
  ('United States', 'Country Club Of Fairfax'),
  ('United States', 'Country Club Of Fairfield'),
  ('United States', 'Country Club Of Farmington'),
  ('United States', 'Country Club Of Florida'),
  ('United States', 'Country Club Of Green Valley'),
  ('United States', 'Country Club Of Gwinnett'),
  ('United States', 'Country Club Of Halifax'),
  ('United States', 'Country Club Of Harrisburg'),
  ('United States', 'Country Club Of Hilton Head'),
  ('United States', 'Country Club Of Ithaca The'),
  ('United States', 'Country Club Of Jackson Azalea Course'),
  ('United States', 'Country Club Of Jackson Cypress Course'),
  ('United States', 'Country Club Of Jackson Dogwood Course'),
  ('United States', 'Country Club Of Johnston County'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Marsh Pines'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Ocean Marsh'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Pines Ocean'),
  ('United States', 'Country Club Of Landfall Pete Dye Course'),
  ('United States', 'Country Club Of Leawood'),
  ('United States', 'Country Club Of Little Rock'),
  ('United States', 'Country Club Of Miami East'),
  ('United States', 'Country Club Of Miami West'),
  ('United States', 'Country Club Of Naples'),
  ('United States', 'Country Club Of New Bedford'),
  ('United States', 'Country Club Of New Canaan'),
  ('United States', 'Country Club Of New Hampshire'),
  ('United States', 'Country Club Of Newberry'),
  ('United States', 'Country Club Of Ocala'),
  ('United States', 'Country Club Of Orangeburg'),
  ('United States', 'Country Club Of Pittsfield'),
  ('United States', 'Country Club Of Rochester'),
  ('United States', 'Country Club Of Roswell'),
  ('United States', 'Country Club Of Salisbury'),
  ('United States', 'Country Club Of Sebring'),
  ('United States', 'Country Club Of Silver Springs Shores'),
  ('United States', 'Country Club Of The Rockies'),
  ('United States', 'Country Club Of The South'),
  ('United States', 'Country Club Of Vermont'),
  ('United States', 'Country Club Of Waterbury'),
  ('United States', 'Country Club Of Whispering Pines Pines Course'),
  ('United States', 'Country Club Of Whispering Pines River Course'),
  ('United States', 'Country Club Of Wilbraham'),
  ('United States', 'Country Club Of Winter Haven'),
  ('United States', 'Country Club Of York'),
  ('United States', 'Country Club of Beloit'),
  ('United States', 'Country Club of Decatur')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Country Club of Detroit'),
  ('United States', 'Country Club of Jackson'),
  ('United States', 'Country Club of Lansing'),
  ('United States', 'Country Club of Paducah'),
  ('United States', 'Country Club of Peoria Golf Course'),
  ('United States', 'Country Club of Sioux Falls'),
  ('United States', 'Country Club of Terre Haute'),
  ('United States', 'Country Club of the North'),
  ('United States', 'Country Drive Golf Course'),
  ('United States', 'Country Fareways Par 3 Golf Course'),
  ('United States', 'Country Greens Golf Course'),
  ('United States', 'Country Hills Golf Course'),
  ('United States', 'Country Land Golf Course'),
  ('United States', 'Country Mark Golf Course'),
  ('United States', 'Country Meadows Golf Course'),
  ('United States', 'Country Oaks Golf Course'),
  ('United States', 'Country Side Golf Club'),
  ('United States', 'Country View Golf Club'),
  ('United States', 'Country View Golf Course'),
  ('United States', 'Countryside Golf Club'),
  ('United States', 'Countryside Golf Course'),
  ('United States', 'Countryview Golf Club'),
  ('United States', 'Countryway Golf Club'),
  ('United States', 'County Line Country Club'),
  ('United States', 'County Line Golf Course'),
  ('United States', 'Course 4 Dubsdread At Cog Hill Golf And Country Club'),
  ('United States', 'Coushatta Country Club'),
  ('United States', 'Cove Cay Golf Club'),
  ('United States', 'Cove View Golf Course'),
  ('United States', 'Coventry Pines Public Golf Course'),
  ('United States', 'Covered Bridge Golf And Country Club'),
  ('United States', 'Covered Bridge Golf Club'),
  ('United States', 'Coves Golf Club'),
  ('United States', 'Covington Country Club'),
  ('United States', 'Covington Links Golf Course'),
  ('United States', 'Cowans Ford Country Club'),
  ('United States', 'Coweta Club At Arbor Springs Plantation'),
  ('United States', 'Coyote Creek Golf Club'),
  ('United States', 'Coyote Creek Golf Club The Tournament Course'),
  ('United States', 'Coyote Creek Golf Club The Valley Course'),
  ('United States', 'Coyote Creek Golf Course'),
  ('United States', 'Coyote Crossing Golf Club'),
  ('United States', 'Coyote Del Malpais Golf Course'),
  ('United States', 'Coyote Golf Club'),
  ('United States', 'Coyote Hills Golf Course'),
  ('United States', 'Coyote Lakes Golf Club'),
  ('United States', 'Coyote Moon Golf Course'),
  ('United States', 'Coyote Preserve Golf Club'),
  ('United States', 'Coyote Run Golf Course'),
  ('United States', 'Coyote Springs Golf Club'),
  ('United States', 'Coyote Trails Golf Course'),
  ('United States', 'Coyote Wash Golf Course'),
  ('United States', 'Coyote Willows Golf Club'),
  ('United States', 'Cozy Acres Golf Links'),
  ('United States', 'Crab Apple Ridge Golf Course'),
  ('United States', 'Crab Meadow Golf Course'),
  ('United States', 'Crab Orchard Golf Club'),
  ('United States', 'Crabapple Dogwood At Roanoke Country Club'),
  ('United States', 'Cracklewood Golf Club!'),
  ('United States', 'Crag Burn Golf Club'),
  ('United States', 'Cragie Brae Golf Club'),
  ('United States', 'Cragun S Legacy Dutch 27 Blue Nine'),
  ('United States', 'Cragun S Legacy Dutch 27 Red Nine'),
  ('United States', 'Cragun S Legacy Dutch 27 White Nine'),
  ('United States', 'Cragun S Legacy Lehman 18'),
  ('United States', 'Craig Wood Golf Country Club'),
  ('United States', 'Craig Woods Golf Club'),
  ('United States', 'Cramer Mountain Country Club'),
  ('United States', 'Cranberry Highlands Golf Course'),
  ('United States', 'Cranberry Hills'),
  ('United States', 'Cranberry Valley Golf Course'),
  ('United States', 'Cranbury Golf Club'),
  ('United States', 'Crandon Golf At Key Biscayne'),
  ('United States', 'Crane Creek Country Club'),
  ('United States', 'Crane Creek Golf Course'),
  ('United States', 'Crane Creek Reserve Golf Course At Melbourne'),
  ('United States', 'Crane Field Golf Course'),
  ('United States', 'Crane Lakes Golf Country Club'),
  ('United States', 'Crane Meadows Golf Course'),
  ('United States', 'Crane Watch Club'),
  ('United States', 'Crane''s Landing Golf Club at Marriott Lincolnshire Resort'),
  ('United States', 'Cranebrook Hills Golf Course'),
  ('United States', 'Cranes Bend At Orange Lake Resort'),
  ('United States', 'Cranston Country Club'),
  ('United States', 'Crawford Hills Municipal Golf Course'),
  ('United States', 'Crawfordsville Golf Course'),
  ('United States', 'Crazy Horse Sports Club Golf Course'),
  ('United States', 'Cream Ridge Golf Club'),
  ('United States', 'Cree Meadows Country Club'),
  ('United States', 'Creek At Carolina Trace Country Club'),
  ('United States', 'Creek At Quail Creek Country Club'),
  ('United States', 'Creek Cherokee At Big Canoe Golf Club'),
  ('United States', 'Creek Oaks At Temecula Creek Inn Golf Resort'),
  ('United States', 'Creek Side Golf'),
  ('United States', 'Creeks Golf Course At Quail Heights Country Club'),
  ('United States', 'Creeksbend Golf Course'),
  ('United States', 'Creekside At Bonita Bay Club'),
  ('United States', 'Creekside At Golf Club Of Georgia The'),
  ('United States', 'Creekside At Pebble Creek Country Club'),
  ('United States', 'Creekside Golf'),
  ('United States', 'Creekside Golf Country Club'),
  ('United States', 'Creekside Golf Course'),
  ('United States', 'Creekview Par Three'),
  ('United States', 'Creekview Par Three At Albion'),
  ('United States', 'Crescent Bar Resort'),
  ('United States', 'Crescent Farms Golf Club'),
  ('United States', 'Crescent Hill Golf Course'),
  ('United States', 'Crescent Oaks Country Club'),
  ('United States', 'Crescent Pointe Golf Club'),
  ('United States', 'Cress Creek Country Club'),
  ('United States', 'Cressmoor Country Club'),
  ('United States', 'Cresta Verde Golf Club'),
  ('United States', 'Crestbrook Park Golf Course'),
  ('United States', 'Crestmont Country Club'),
  ('United States', 'Crestmoor Golf Club'),
  ('United States', 'Creston Golf Club'),
  ('United States', 'Crestview Country Club'),
  ('United States', 'Crestview Executive Course'),
  ('United States', 'Crestview Golf Club'),
  ('United States', 'Crestview Golf Course'),
  ('United States', 'Crestwicke Country Club'),
  ('United States', 'Crestwood Country Club'),
  ('United States', 'Crestwood Golf Club'),
  ('United States', 'Creve Coeur Golf Course'),
  ('United States', 'Crewe Country Club'),
  ('United States', 'Cricket Hill Golf Club'),
  ('United States', 'Cricket Ridge Golf Course'),
  ('United States', 'Crimson Creek Golf Course'),
  ('United States', 'Crimson Ridge'),
  ('United States', 'Cripple Creek Golf Country Club'),
  ('United States', 'Croasdaile Country Club'),
  ('United States', 'Crockett Ridge Golf Course'),
  ('United States', 'Cronins Golf Resort'),
  ('United States', 'Crooked Cat At Orange County National'),
  ('United States', 'Crooked Creek Club'),
  ('United States', 'Crooked Creek Country Club'),
  ('United States', 'Crooked Creek Golf Club'),
  ('United States', 'Crooked Creek Golf Course'),
  ('United States', 'Crooked Hollow Golf Club'),
  ('United States', 'Crooked Lake Golf Club'),
  ('United States', 'Crooked Oak Golf Club'),
  ('United States', 'Crooked Oaks At Seabrook Island Resort'),
  ('United States', 'Crooked Pines Golf Swim Club'),
  ('United States', 'Crooked Stick Golf Club'),
  ('United States', 'Crooked Tree Golf Club'),
  ('United States', 'Crooked Tree Golf Course'),
  ('United States', 'Cross Creek Country Club'),
  ('United States', 'Cross Creek Golf Club'),
  ('United States', 'Cross Creek Golf Course'),
  ('United States', 'Cross Creek Golf Links'),
  ('United States', 'Cross Creek Plantation'),
  ('United States', 'Crosscreek Golf Club'),
  ('United States', 'Crossgates Golf Course'),
  ('United States', 'Crossings At Grove Park The'),
  ('United States', 'Crossings Golf Club'),
  ('United States', 'Crossroads At Palmetto Bluff'),
  ('United States', 'Crossroads Par 3 Golf Course'),
  ('United States', 'Crosswater At Sunriver Resort'),
  ('United States', 'Crosswinds Golf Club Jones Ouimet'),
  ('United States', 'Crosswinds Golf Club Ouimet Zaharias'),
  ('United States', 'Crosswinds Golf Club Zaharias Jones'),
  ('United States', 'Crotched Mountain Golf Club'),
  ('United States', 'Crow Canyon Country Club'),
  ('United States', 'Crow Creek Golf Club'),
  ('United States', 'Crow River Country Club'),
  ('United States', 'Crow Valley Golf Club'),
  ('United States', 'Crowders Mountain Golf Club'),
  ('United States', 'Crowfield Golf Country Club'),
  ('United States', 'Crowleys Ridge Country Club'),
  ('United States', 'Crown Colony Golf Country Club'),
  ('United States', 'Crown Hill Golf Club'),
  ('United States', 'Crown Park Golf Course'),
  ('United States', 'Crown Point Country Club'),
  ('United States', 'Crown Pointe Golf Club'),
  ('United States', 'Crowne Plaza Tennis Golf Resort'),
  ('United States', 'Cruiser At Seal Beach Navy Golf Course'),
  ('United States', 'Crumpin Fox Club'),
  ('United States', 'Cruz Farm Golf Club'),
  ('United States', 'Crystal Coast Country Club'),
  ('United States', 'Crystal Downs Country Club'),
  ('United States', 'Crystal Falls Golf Club'),
  ('United States', 'Crystal Golf Course'),
  ('United States', 'Crystal Lake Club'),
  ('United States', 'Crystal Lake Country Club'),
  ('United States', 'Crystal Lake Golf Club'),
  ('United States', 'Crystal Lake Golf Country Club'),
  ('United States', 'Crystal Lakes Golf Course'),
  ('United States', 'Crystal Springs'),
  ('United States', 'Crystal Springs Golf Club'),
  ('United States', 'Crystal Springs Golf Course'),
  ('United States', 'Crystal Tree Golf and Country Club'),
  ('United States', 'Crystal View Golf Course'),
  ('United States', 'Crystal Woods Golf Club'),
  ('United States', 'Crystalaire Country Club'),
  ('United States', 'Culbertson Hills Golf Resort'),
  ('United States', 'Cullasaja Club'),
  ('United States', 'Cultus Lake Golf Club'),
  ('United States', 'Culver Lake Golf Course'),
  ('United States', 'Cumberland Country Club'),
  ('United States', 'Cumberland Golf Club'),
  ('United States', 'Cumberland Trail Golf Club'),
  ('United States', 'Cummaquid Golf Club'),
  ('United States', 'Cummings Cove Golf Country Club'),
  ('United States', 'Currahee Club'),
  ('United States', 'Currie Municipal Golf Course'),
  ('United States', 'Currie Park Golf Course'),
  ('United States', 'Curtis Creek Golf Course'),
  ('United States', 'Custer Greens Golf Course'),
  ('United States', 'Cut Bank Golf Country Club'),
  ('United States', 'Cutalong At Lake Anna'),
  ('United States', 'Cutter Creek Golf Club'),
  ('United States', 'Cyclone golf performance center'),
  ('United States', 'Cypress At Palm Aire Country Club'),
  ('United States', 'Cypress At Royal Poinciana Golf Club'),
  ('United States', 'Cypress At Woodmont Country Club'),
  ('United States', 'Cypress Bend Golf Resort'),
  ('United States', 'Cypress Course At Stonegate Golf Club'),
  ('United States', 'Cypress Cove Country Club'),
  ('United States', 'Cypress Creek At Greystone'),
  ('United States', 'Cypress Creek Country Club'),
  ('United States', 'Cypress Creek Golf Links'),
  ('United States', 'Cypress Creek Golfers Club'),
  ('United States', 'Cypress Greens Golf Tennis Community'),
  ('United States', 'Cypress Head Golf Club'),
  ('United States', 'Cypress Knoll Golf Country Club'),
  ('United States', 'Cypress Lake Country Club'),
  ('United States', 'Cypress Lake Par 3 Golf Course'),
  ('United States', 'Cypress Lakes Country Club'),
  ('United States', 'Cypress Lakes Golf Club'),
  ('United States', 'Cypress Lakes Golf Country Club'),
  ('United States', 'Cypress Lakes Golf Course'),
  ('United States', 'Cypress Lakes Homeowners Golf Course'),
  ('United States', 'Cypress Landing Golf Course'),
  ('United States', 'Cypress Links At Mangrove Bay'),
  ('United States', 'Cypress Point Club'),
  ('United States', 'Cypress Point Country Club'),
  ('United States', 'Cypress Point Par 3 Golf Course'),
  ('United States', 'Cypress Point Rv Golf Club'),
  ('United States', 'Cypress Ridge Golf Course'),
  ('United States', 'Cypress Run Golf Club'),
  ('United States', 'Cypress Run Golf Course'),
  ('United States', 'Cypress Waterway At Arrowhead Country Club'),
  ('United States', 'Cypress Woods Golf Country Club'),
  ('United States', 'Cypresswood Golf Country Club'),
  ('United States', 'D W Field Golf Course'),
  ('United States', 'Dacotah Ridge Golf Club'),
  ('United States', 'Dad Miller Golf Course'),
  ('United States', 'Dairy Creek Golf Course'),
  ('United States', 'Dairymens Country Club'),
  ('United States', 'Dakota Creek Golf Country Club'),
  ('United States', 'Dakota Dunes Country Club'),
  ('United States', 'Dakota Landing Golf Course'),
  ('United States', 'Dakota Trails Golf Course'),
  ('United States', 'Dakota Winds Golf Course'),
  ('United States', 'Dalhousie Golf Club'),
  ('United States', 'Dalton Golf Country Club'),
  ('United States', 'Dalton Ranch Golf Club'),
  ('United States', 'Dan Hall Mountain Resort'),
  ('United States', 'Dan Valley Golf Course'),
  ('United States', 'Dancing Rabbit Golf Club The Azaleas'),
  ('United States', 'Dancing Rabbit Golf Club The Oaks'),
  ('United States', 'Dande Farms Golf Course'),
  ('United States', 'Dandrea Golf Club'),
  ('United States', 'Daniel Island Club Beresford Creek Course'),
  ('United States', 'Daniel Island Club Ralston Creek Course'),
  ('United States', 'Danville Golf Club'),
  ('United States', 'Darby Creek Golf Course'),
  ('United States', 'Darkhorse Golf Club'),
  ('United States', 'Darlington Country Club'),
  ('United States', 'Darlington Golf Course'),
  ('United States', 'Date Palm Country Club'),
  ('United States', 'Dauphin Highlands Golf Course'),
  ('United States', 'Dave White Municipal Golf Course'),
  ('United States', 'Davenport Country Club'),
  ('United States', 'David L Baker Memorial Golf'),
  ('United States', 'David Toms Academy 265'),
  ('United States', 'Davie Golf Country Club'),
  ('United States', 'Davis Countryside Meadows'),
  ('United States', 'Davis Golf Course'),
  ('United States', 'Davis Monthan Afb General William Blanchard Course'),
  ('United States', 'Davis Park Golf Course'),
  ('United States', 'Davison Country Club'),
  ('United States', 'Dawson Country Club'),
  ('United States', 'Dawson Golf Course'),
  ('United States', 'Dawson Ridge Golf Course'),
  ('United States', 'Dayton Community Golf Club'),
  ('United States', 'Dayton Country Club'),
  ('United States', 'Dayton Ridge Golf Club'),
  ('United States', 'Dayton Valley Golf Club'),
  ('United States', 'Daytona Golf Course'),
  ('United States', 'De Anza Country Club'),
  ('United States', 'De La Vista At The Villages Executive Golf Trail'),
  ('United States', 'De Smidt''s Golf Course & Country Club'),
  ('United States', 'DeMor Hills Golf Course'),
  ('United States', 'Deacon''s Lodge'),
  ('United States', 'Deal Golf Country Club'),
  ('United States', 'Dearborn Country Club'),
  ('United States', 'Dearborn Hills'),
  ('United States', 'Debary Golf Country Club'),
  ('United States', 'Debell Golf Club'),
  ('United States', 'Debell Golf Club Par 3 Course'),
  ('United States', 'Debordieu Colony Country Club'),
  ('United States', 'Decatur County Golf and Country Club'),
  ('United States', 'Decatur Golf Club'),
  ('United States', 'Deception Pass Golf Center'),
  ('United States', 'Dedham Country Polo Club'),
  ('United States', 'Deep Brook Golf Course'),
  ('United States', 'Deep Cliff Golf Course'),
  ('United States', 'Deep Creek Golf Club'),
  ('United States', 'Deep Springs Country Club'),
  ('United States', 'Deepdale Golf Club'),
  ('United States', 'Deer Brook Golf Club'),
  ('United States', 'Deer Cove'),
  ('United States', 'Deer Creek Golf Club'),
  ('United States', 'Deer Creek Golf Club At Meadow Ranch'),
  ('United States', 'Deer Creek Golf Course'),
  ('United States', 'Deer Creek Rv Golf Country Club'),
  ('United States', 'Deer Creek State Park Golf Course'),
  ('United States', 'Deer Creek Town Racquet Club'),
  ('United States', 'Deer Field Golf Course'),
  ('United States', 'Deer Haven Golf Club'),
  ('United States', 'Deer Island Country Club'),
  ('United States', 'Deer Lodge Golf Club'),
  ('United States', 'Deer Park Country Club'),
  ('United States', 'Deer Park Golf Club'),
  ('United States', 'Deer Ridge Golf Club'),
  ('United States', 'Deer Run At Sun N Lake Golf Country Club'),
  ('United States', 'Deer Run Championship At Newport News Golf Club'),
  ('United States', 'Deer Run Golf Club'),
  ('United States', 'Deer Run Golf Course'),
  ('United States', 'Deer Run Golf at Lakes of the North'),
  ('United States', 'Deer Trace Golf Links'),
  ('United States', 'Deer Track Golf'),
  ('United States', 'Deer Track Golf Course'),
  ('United States', 'Deer Trail Country Club'),
  ('United States', 'Deer Trails Country Club'),
  ('United States', 'Deer Trails Golf Course'),
  ('United States', 'Deer Valley Golf Club'),
  ('United States', 'Deer Valley Golf Course'),
  ('United States', 'Deer Valley Golf Course At Sun City West'),
  ('United States', 'Deer View Golf Course'),
  ('United States', 'Deercreek Country Club'),
  ('United States', 'Deercroft Golf Club'),
  ('United States', 'Deerfield Golf Club'),
  ('United States', 'Deerfield Golf Club and Learning Center'),
  ('United States', 'Deerfield Golf Course'),
  ('United States', 'Deerfield Golf Tennis Club'),
  ('United States', 'Deering Bay Yacht Country Club'),
  ('United States', 'Deerpath Golf Course'),
  ('United States', 'Deertrak Golf Club'),
  ('United States', 'Deerwood Club The'),
  ('United States', 'Deerwood Country Club'),
  ('United States', 'Deerwood Golf Club'),
  ('United States', 'Deerwood Golf Course Buck Course'),
  ('United States', 'Deerwood Golf Course Doe Course'),
  ('United States', 'Deerwood Golf Course Fawn Course'),
  ('United States', 'Degray Lake Golf Course'),
  ('United States', 'Del Lago Golf Club'),
  ('United States', 'Del Mar Country Club'),
  ('United States', 'Del Mar Golf Course'),
  ('United States', 'Del Montetm Golf Course'),
  ('United States', 'Del Norte Golf Club'),
  ('United States', 'Del Paso Country Club'),
  ('United States', 'Del Rio Country Club'),
  ('United States', 'Del Tura Golf Country Club North West'),
  ('United States', 'Del Tura Golf Country Club South North'),
  ('United States', 'Del Tura Golf Country Club West South'),
  ('United States', 'Delaire Country Club Hills Woods'),
  ('United States', 'Delaire Country Club Lakes Hills'),
  ('United States', 'Delaire Country Club Woods Lakes'),
  ('United States', 'Delano Golf Course'),
  ('United States', 'Delaveaga Golf Course Lodge'),
  ('United States', 'Delaware Country Club'),
  ('United States', 'Delaware Golf Club'),
  ('United States', 'Delaware Park Course'),
  ('United States', 'Delaware Springs Golf Course'),
  ('United States', 'Delbrook Golf Club'),
  ('United States', 'Delcastle Golf Course'),
  ('United States', 'Delhi Country Club'),
  ('United States', 'Dell Urich At Randolph Golf Course'),
  ('United States', 'Dellwood Country Club'),
  ('United States', 'Delmont Golf Course'),
  ('United States', 'Delphi Falls Golf Course'),
  ('United States', 'Delphi Golf Club'),
  ('United States', 'Delray Beach Golf Club'),
  ('United States', 'Delray Dunes Golf Country Club'),
  ('United States', 'Delta Country Club'),
  ('United States', 'Delta Knolls Golf Center'),
  ('United States', 'Delta Nine At Ascarate Park Golf Course'),
  ('United States', 'Deltona Club'),
  ('United States', 'Deme Acres Golf Course'),
  ('United States', 'Dempsey Ridge Golf Course'),
  ('United States', 'Den Brae Golf Club'),
  ('United States', 'Denison Country Club'),
  ('United States', 'Denison Golf Club'),
  ('United States', 'Dennis Highlands Golf Course'),
  ('United States', 'Dennis Pines Golf Course'),
  ('United States', 'Densons Creek Golf Course'),
  ('United States', 'Denver City Park Golf Course'),
  ('United States', 'Denver Country Club')
on conflict (country, name) do nothing;
