insert into public.golf_courses (country, name) values
  ('United States', 'The Omni Homestead Resort Spa Old Course'),
  ('United States', 'The Orchards At Egg Harbor'),
  ('United States', 'The Orchards Golf Club'),
  ('United States', 'The Orchards Golf Course'),
  ('United States', 'The Osprey At Haig Point Club'),
  ('United States', 'The Outlaw At Alto Lakes'),
  ('United States', 'The Palencia Club'),
  ('United States', 'The Palisades Country Club'),
  ('United States', 'The Palms Course'),
  ('United States', 'The Palms Golf Club'),
  ('United States', 'The Palms Golf Club At Forest Lakes'),
  ('United States', 'The Panther At Plantation Golf Country Club'),
  ('United States', 'The Par 3 At Pipestem State Park Resort'),
  ('United States', 'The Park Country Club'),
  ('United States', 'The Park West Palm'),
  ('United States', 'The Park West Palm The Lit 9'),
  ('United States', 'The Patriot Golf Club At Grand Harbor'),
  ('United States', 'The Pearl Club'),
  ('United States', 'The Pearl Golf Links East Course'),
  ('United States', 'The Pearl Golf Links North Course'),
  ('United States', 'The Pearl Golf Links West Course'),
  ('United States', 'The Peninsula Club'),
  ('United States', 'The Peninsula On The Indian River Bay Golf Club'),
  ('United States', 'The Pheasant Golf Links Front Back Course'),
  ('United States', 'The Pheasant Golf Links Roc Course'),
  ('United States', 'The Phoenician Golf Club'),
  ('United States', 'The Piedmont Club'),
  ('United States', 'The Pines'),
  ('United States', 'The Pines At Elizabeth City'),
  ('United States', 'The Pines At Lindsey Wilson'),
  ('United States', 'The Pines At North Park'),
  ('United States', 'The Pines Country Club'),
  ('United States', 'The Pines Golf Club'),
  ('United States', 'The Pines Golf Course'),
  ('United States', 'The Pines Golf Course At Fort Eustis Ponderosa Pines Shortleaf Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Ponderosa Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Shortleaf Pines'),
  ('United States', 'The Pines Of Chatom Golf Course'),
  ('United States', 'The Plantation Course At Edisto'),
  ('United States', 'The Plantation Golf And Country Club'),
  ('United States', 'The Plantation Golf Club Cranes Roost Course'),
  ('United States', 'The Plantation Golf Club Otter Creek Course'),
  ('United States', 'The Plateau Club'),
  ('United States', 'The Players Club'),
  ('United States', 'The Players Club at Foxfire'),
  ('United States', 'The Players Club at Woodland Trails'),
  ('United States', 'The Players Course At Wyboo'),
  ('United States', 'The Poconos Club'),
  ('United States', 'The Pointe Golf Club'),
  ('United States', 'The Pointe Golf Course'),
  ('United States', 'The Pointe Golf Event Center'),
  ('United States', 'The Polo Fields - Ann Arbor'),
  ('United States', 'The Ponds at Battle Creek'),
  ('United States', 'The Powder Horn Golf Club Eagle Nine'),
  ('United States', 'The Powder Horn Golf Club Mountain Nine'),
  ('United States', 'The Powder Horn Golf Club Stag Nine'),
  ('United States', 'The Practice Center - Clear Creek'),
  ('United States', 'The Practice Tee At Sunset Hills'),
  ('United States', 'The Prairie Club Dunes Course'),
  ('United States', 'The Prairie Club Horse Course'),
  ('United States', 'The Prairies Golf Club'),
  ('United States', 'The Prairies Golf Course'),
  ('United States', 'The Preserve'),
  ('United States', 'The Preserve At Boulder Hills'),
  ('United States', 'The Preserve At Ironhorse'),
  ('United States', 'The Preserve At Jordan Lake Golf Club'),
  ('United States', 'The Preserve At Oak Meadows'),
  ('United States', 'The Preserve At Turnbull Bay'),
  ('United States', 'The Preserve At Verdae'),
  ('United States', 'The Preserve Golf Club'),
  ('United States', 'The Preserve On Rathbun Lake'),
  ('United States', 'The Preserve at Oak Meadows'),
  ('United States', 'The Quarry'),
  ('United States', 'The Quarry At La Quinta'),
  ('United States', 'The Quarry At La Quinta Short Course'),
  ('United States', 'The Quarry Golf Club'),
  ('United States', 'The Quarry at Crystal Springs'),
  ('United States', 'The Quechee Club Highland Course'),
  ('United States', 'The Quechee Club Lakeland Course'),
  ('United States', 'The Quest Golf Club'),
  ('United States', 'The Rail Golf Course'),
  ('United States', 'The Ranch At Laguna Beach'),
  ('United States', 'The Ranch Club'),
  ('United States', 'The Ranch Country Club'),
  ('United States', 'The Ranch Golf Club'),
  ('United States', 'The Ranches Golf Club'),
  ('United States', 'The Raven Golf Club At Three Peaks'),
  ('United States', 'The Ravines Golf Course'),
  ('United States', 'The Refuge Golf Course'),
  ('United States', 'The Reserve At Lake Keowee'),
  ('United States', 'The Reserve At Moonlight Basin Golf Club'),
  ('United States', 'The Reserve At Orange Lake Resort'),
  ('United States', 'The Reserve At Spanos Park'),
  ('United States', 'The Reserve Club'),
  ('United States', 'The Reserve Club At Woodside Plantation Hollow Creek Course'),
  ('United States', 'The Reserve Club At Woodside Plantation The Reserve Course'),
  ('United States', 'The Reserve Golf Club'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Blue Heron Red Hawk'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Red Hawk White Egret'),
  ('United States', 'The Resort At Longboat Key Club Harbourside White Egret Blue Heron'),
  ('United States', 'The Resort At Longboat Key Club Links On Longboat'),
  ('United States', 'The Retreat'),
  ('United States', 'The Revenge'),
  ('United States', 'The Revival Golf Club At The Crescent'),
  ('United States', 'The Ridge'),
  ('United States', 'The Ridge At Back Brook'),
  ('United States', 'The Ridge At Castle Pines Colorado'),
  ('United States', 'The Ridge Country Club'),
  ('United States', 'The Ridge Golf Club'),
  ('United States', 'The Ridge Golf Course Events Center'),
  ('United States', 'The Ridges At Village Creek North Ridge East Ridge'),
  ('United States', 'The Ridges At Village Creek North Ridge West Ridge'),
  ('United States', 'The Ridges At Village Creek West Ridge East Ridge'),
  ('United States', 'The Ridges Golf Course'),
  ('United States', 'The Rim Golf Club'),
  ('United States', 'The Ritz Carlton Golf Club Orlando Grande Lakes'),
  ('United States', 'The River At Grand Harbor Golf Beach Club'),
  ('United States', 'The River Club'),
  ('United States', 'The River Club Golf Course'),
  ('United States', 'The River Course At Keystone'),
  ('United States', 'The River Golf Club'),
  ('United States', 'The River Golf Course, Inc.'),
  ('United States', 'The Rivercrest Golf Club And Preserve'),
  ('United States', 'The Riverside Club of West Virginia'),
  ('United States', 'The Riviera Country Club'),
  ('United States', 'The Rock Golf Club'),
  ('United States', 'The Rock Golf Club Resort'),
  ('United States', 'The Rock Golf Course'),
  ('United States', 'The Rockland Farm Course At Shenandoah Valley'),
  ('United States', 'The Rookery At Marco'),
  ('United States', 'The Rookery South'),
  ('United States', 'The Rose Golf Course'),
  ('United States', 'The Royal'),
  ('United States', 'The Royal Ancient Chappaquiddick Links'),
  ('United States', 'The Royal Virginian Golf Course'),
  ('United States', 'The Running Y Ranch Golf Course'),
  ('United States', 'The Saddle At Glencove'),
  ('United States', 'The Saints At Port St Lucie'),
  ('United States', 'The Salt Pond Golf Club'),
  ('United States', 'The Sanctuary'),
  ('United States', 'The Sanctuary Golf Club'),
  ('United States', 'The Sanctuary Golf Course At Pennbrooke Fairways'),
  ('United States', 'The Sands Golf Rv Resort'),
  ('United States', 'The Santaluz Club'),
  ('United States', 'The Savannah Golf Club'),
  ('United States', 'The Savannahs Golf Course'),
  ('United States', 'The Sawmill Golf Club'),
  ('United States', 'The Schoolhouse Nine'),
  ('United States', 'The Sea Ranch Golf Links'),
  ('United States', 'The Sedgewood Golf Club'),
  ('United States', 'The Senator Course At Shulas Golf Club'),
  ('United States', 'The Serradella'),
  ('United States', 'The Shoe Course At Golden Horseshoe Golf Club'),
  ('United States', 'The Shore Club'),
  ('United States', 'The Shores Of North River Golf Club'),
  ('United States', 'The Sidewinder Golf Course'),
  ('United States', 'The Silverleaf Golf Club'),
  ('United States', 'The Sound Golf Links At Albemarle Plantation'),
  ('United States', 'The South East At Upper Montclair Country Club'),
  ('United States', 'The Springs At Borrego'),
  ('United States', 'The Springs Club'),
  ('United States', 'The Spruce Creek Preserve Golf Club'),
  ('United States', 'The St Anne S Club'),
  ('United States', 'The Stadium Course At Pga West'),
  ('United States', 'The Summit'),
  ('United States', 'The Summit Club'),
  ('United States', 'The Swan Golf Country Club'),
  ('United States', 'The Tamaracks Golf Course'),
  ('United States', 'The Tattersall Youth Development Center At The First Tee Chesterfield Golf Course'),
  ('United States', 'The Territory'),
  ('United States', 'The Tesoro Club Palmer Course'),
  ('United States', 'The Tesoro Club Watson Course'),
  ('United States', 'The Third Golf Course'),
  ('United States', 'The Tillery Tradition Country Club'),
  ('United States', 'The Timbers Golf Club'),
  ('United States', 'The Titus Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Tradition Golf Club'),
  ('United States', 'The Traditional'),
  ('United States', 'The Trails Golf Club'),
  ('United States', 'The Tree Farm'),
  ('United States', 'The Tribute'),
  ('United States', 'The Trophy Club Of Apalachee'),
  ('United States', 'The Trophy Club Of Atlanta'),
  ('United States', 'The Tuxedo Club'),
  ('United States', 'The Valley At Eastport Golf Club'),
  ('United States', 'The Valley Club North Course'),
  ('United States', 'The Valley Club South Course'),
  ('United States', 'The Valley Club West Course'),
  ('United States', 'The Valley Golf Course'),
  ('United States', 'The Views Golf Club At Oro Valley'),
  ('United States', 'The Village Course At Waikoloa'),
  ('United States', 'The Village Of Fenney Gray Fox Course'),
  ('United States', 'The Village Of Fenney Red Fox Course'),
  ('United States', 'The Vineyard At Escondido'),
  ('United States', 'The Vineyards Golf Club'),
  ('United States', 'The Vintage At Staples'),
  ('United States', 'The Vintage Club Desert Course'),
  ('United States', 'The Vintage Club Mountain Course'),
  ('United States', 'The Virginian Golf Club'),
  ('United States', 'The Virtues Golf Club'),
  ('United States', 'The Vue'),
  ('United States', 'The Walker Golf Course At Clemson University'),
  ('United States', 'The Wanderers Club At Wellington'),
  ('United States', 'The Water S Edge Country Club'),
  ('United States', 'The Waterfront Country Club'),
  ('United States', 'The Wedgewood Club'),
  ('United States', 'The West South At Upper Montclair Country Club'),
  ('United States', 'The Wetlands Golf Course'),
  ('United States', 'The Wilderness at Fortune Bay'),
  ('United States', 'The Wilds'),
  ('United States', 'The Willows At Runk Pratt'),
  ('United States', 'The Windermere Club'),
  ('United States', 'The Wizard Golf Course'),
  ('United States', 'The Wolf At Tenkiller'),
  ('United States', 'The Wolverine Golf Course'),
  ('United States', 'The Wood'),
  ('United States', 'The Woodlands Golf Club'),
  ('United States', 'The Woodlands Golf Country Club'),
  ('United States', 'The Woods Golf Club'),
  ('United States', 'The Woods Of Westminster'),
  ('United States', 'The Woods Resort Mountain View Course'),
  ('United States', 'The Woods Resort Stony Lick Course'),
  ('United States', 'The Woods at Possum Run'),
  ('United States', 'The Wyndgate'),
  ('United States', 'The Yards'),
  ('United States', 'Thendara Golf Club'),
  ('United States', 'Theodore Wirth Golf Course'),
  ('United States', 'Third First At Lake Venice Golf Club'),
  ('United States', 'Third Nine At Edison Club The'),
  ('United States', 'Third Nine At Montclair Golf Club'),
  ('United States', 'Third Nine At Pleasant Valley Country Club'),
  ('United States', 'Third Nine First Nine At Bermuda Dunes Country Club'),
  ('United States', 'Thistle Foxglove At Resort At The Mountain The'),
  ('United States', 'Thistle Golf Club Cameron Course'),
  ('United States', 'Thistle Golf Club Mackay Course'),
  ('United States', 'Thistle Golf Club Stewart Course'),
  ('United States', 'Thomas Memorial Golf Country Club'),
  ('United States', 'Thomson Country Club'),
  ('United States', 'Thorn Apple Country Club'),
  ('United States', 'Thorn Spring Golf Course'),
  ('United States', 'Thornberry Creek Country Club'),
  ('United States', 'Thornblade Club'),
  ('United States', 'Thorncreek Golf Club'),
  ('United States', 'Thorndale Country Club'),
  ('United States', 'Thorne Hills Golf Course'),
  ('United States', 'Thornhurst Country Club'),
  ('United States', 'Thorny Lea Golf Club'),
  ('United States', 'Thoroughbred Golf Club'),
  ('United States', 'Thousand Acres Golf Club'),
  ('United States', 'Thousand Hills Resort Golf Club'),
  ('United States', 'Thousand Islands Country Club The Lake Course'),
  ('United States', 'Thousand Islands Country Club The Old Course'),
  ('United States', 'Thousand Oaks Golf Club'),
  ('United States', 'Three Crowns Golf Club'),
  ('United States', 'Three Eagles Golf Course'),
  ('United States', 'Three Elms Golf Course'),
  ('United States', 'Three Lakes Golf Course'),
  ('United States', 'Three Pines Country Club'),
  ('United States', 'Three Ponds Farm'),
  ('United States', 'Three Ponds Golf Club'),
  ('United States', 'Three Rivers Country Club'),
  ('United States', 'Three Rivers Golf Course'),
  ('United States', 'Three Sticks Golf Club'),
  ('United States', 'Thumper Pond'),
  ('United States', 'Thunder Bay Resort'),
  ('United States', 'Thunder Bayou Golf Links'),
  ('United States', 'Thunder Hills Country Club'),
  ('United States', 'Thunder Mountain Ranch Buckaroo Greens'),
  ('United States', 'Thunderbird At Spring Lake Golf Club'),
  ('United States', 'Thunderbird Country Club'),
  ('United States', 'Thunderbird Driving Range'),
  ('United States', 'Thunderbird Golf Course Resort'),
  ('United States', 'Thunderbird North'),
  ('United States', 'Thunderbird South'),
  ('United States', 'Thunderbolt Pass Golf Course'),
  ('United States', 'Thunderhart Golf Course'),
  ('United States', 'Thunderhawk Golf Club'),
  ('United States', 'Thundering Waters Golf Club'),
  ('United States', 'Tianna Country Club'),
  ('United States', 'Tiara Rado Golf Course'),
  ('United States', 'Tiburon Golf Club The Black Course'),
  ('United States', 'Tiburon Golf Club The Gold Course'),
  ('United States', 'Tiburon Golf Course'),
  ('United States', 'Ticonderoga Country Club'),
  ('United States', 'Tidelands Golf Country Club'),
  ('United States', 'Tidewater Golf Club'),
  ('United States', 'Tierra Del Sol Golf Club'),
  ('United States', 'Tierra Del Sol Golf Country Club'),
  ('United States', 'Tierra Del Sol Golf Course'),
  ('United States', 'Tierra Grande Country Club'),
  ('United States', 'Tierra Rejada Golf Club'),
  ('United States', 'Tiffany Greens Golf Club'),
  ('United States', 'Tiger Point Golf Club'),
  ('United States', 'Tigers Eye Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Tijeras Arroyo Golf Course'),
  ('United States', 'Tijeras Creek Golf Club'),
  ('United States', 'Tilbury Golf Course'),
  ('United States', 'Tilden Park Golf Course'),
  ('United States', 'Timber Banks Golf Club Marina'),
  ('United States', 'Timber City Golf Course'),
  ('United States', 'Timber Creek'),
  ('United States', 'Timber Creek Golf'),
  ('United States', 'Timber Creek Golf Course'),
  ('United States', 'Timber Creek Golf Course Lakes Oaks'),
  ('United States', 'Timber Creek Golf Course Sierra Pines'),
  ('United States', 'Timber Greens Country Club'),
  ('United States', 'Timber Lake Club'),
  ('United States', 'Timber Lake Golf Course'),
  ('United States', 'Timber Pines The Grand Pines Course'),
  ('United States', 'Timber Pines The Highlands Course'),
  ('United States', 'Timber Pines The Hills Course'),
  ('United States', 'Timber Pines The Lakes Course'),
  ('United States', 'Timber Ridge Golf Club'),
  ('United States', 'Timber Terrace Golf Course'),
  ('United States', 'Timber Trace Golf Club'),
  ('United States', 'Timber Trails Golf Club'),
  ('United States', 'Timber Truss Golf Course'),
  ('United States', 'Timber Wolf Golf Club'),
  ('United States', 'Timbergate Golf Course'),
  ('United States', 'Timberlake Country Club'),
  ('United States', 'Timberlake Golf Club'),
  ('United States', 'Timberlane Golf Recreation'),
  ('United States', 'Timberlin Golf Club'),
  ('United States', 'Timberline Golf Course'),
  ('United States', 'Timberline Short Nine'),
  ('United States', 'Timberlink Golf Course'),
  ('United States', 'Timberon Golf Country Club'),
  ('United States', 'Timberstone'),
  ('United States', 'Timberstone Golf Course'),
  ('United States', 'Timberton Golf Club'),
  ('United States', 'Timberview Golf Club'),
  ('United States', 'Timberwood Golf Club'),
  ('United States', 'Timpanogos Golf Club The Championship Course'),
  ('United States', 'Timpanogos Golf Club The Pasture Executive Course'),
  ('United States', 'Timuquana Country Club'),
  ('United States', 'Tin Cup Golf Driving Range'),
  ('United States', 'Tincap Golf Club'),
  ('United States', 'Tinker Afb Golf Course'),
  ('United States', 'Tioga Golf Club'),
  ('United States', 'Tippecanoe Country Club'),
  ('United States', 'Tippecanoe Lake Country Club'),
  ('United States', 'Tipsinah Mounds'),
  ('United States', 'Tipton Golf and Country Club'),
  ('United States', 'Tipton Municipal Golf Course'),
  ('United States', 'Tired Creek Golf Course'),
  ('United States', 'Tishomingo Golf Course'),
  ('United States', 'Toad Valley Golf Course'),
  ('United States', 'Toana Vista Golf Course'),
  ('United States', 'Tobacco Road Golf Club'),
  ('United States', 'Todd Creek Golf Club'),
  ('United States', 'Toddy Brook Golf Course'),
  ('United States', 'Toftrees Resort'),
  ('United States', 'Toiyabe Golf Club'),
  ('United States', 'Toka Sticks Golf Club'),
  ('United States', 'Toledo Country Club'),
  ('United States', 'Tom & Jerry''s Mini Golf'),
  ('United States', 'Tom Oleary Golf Club'),
  ('United States', 'Tomah VA Veterans Golf Course'),
  ('United States', 'Tomahawk Hills Golf Course'),
  ('United States', 'Tommy Jacobs Bel Air Greens'),
  ('United States', 'Toms River Country Club'),
  ('United States', 'Toms Run At Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Toomey Flynn At Huntingdon Valley Country Club'),
  ('United States', 'Tooth 9 Hole Course At Orange County National'),
  ('United States', 'Top Of The Rock Golf Course'),
  ('United States', 'Top Of The World Golf Course'),
  ('United States', 'Topeka Country Club'),
  ('United States', 'Topstone Golf Course'),
  ('United States', 'Torch'),
  ('United States', 'Torreon Golf Club Cabin Course'),
  ('United States', 'Torreon Golf Club Tower Course'),
  ('United States', 'Torres Blancas Golf Club'),
  ('United States', 'Torrey Oaks Rv And Golf Resort'),
  ('United States', 'Torri Erinn At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Torrington Country Club'),
  ('United States', 'Tortoise Hare At On Top Of The World'),
  ('United States', 'Tortuga At Haven Public Golf Club'),
  ('United States', 'Toscana Country Club North Course'),
  ('United States', 'Toscana Country Club South Course'),
  ('United States', 'Tot Hill Farm Golf Club'),
  ('United States', 'Totteridge Golf Course'),
  ('United States', 'Touchet Valley Golf Course'),
  ('United States', 'Touisset Country Club'),
  ('United States', 'Tournament At Burns Park Golf Course'),
  ('United States', 'Tournament Club of Iowa'),
  ('United States', 'Tournament Player’s Club at River’s Bend'),
  ('United States', 'Towanda Country Club'),
  ('United States', 'Tower Tee'),
  ('United States', 'Tower Tee Golf & Recreation'),
  ('United States', 'Towers Country Club'),
  ('United States', 'Town & Country Club'),
  ('United States', 'Town & Country Golf Course'),
  ('United States', 'Town Country Golf Links'),
  ('United States', 'Town Of Wallkill Golf Club'),
  ('United States', 'Town Park Villas Golf Course'),
  ('United States', 'Town and Country Golf Club'),
  ('United States', 'Towne Lake Hills Golf Club'),
  ('United States', 'Townsend Ridge Country Club'),
  ('United States', 'Tpc Boston'),
  ('United States', 'Tpc Colorado')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Tpc Deere Run'),
  ('United States', 'Tpc Harding Park Fleming Course'),
  ('United States', 'Tpc Harding Park Harding Course'),
  ('United States', 'Tpc Jasna Polana'),
  ('United States', 'Tpc Las Vegas'),
  ('United States', 'Tpc Louisiana'),
  ('United States', 'Tpc Michigan'),
  ('United States', 'Tpc Monterey At Pasadera'),
  ('United States', 'Tpc Myrtle Beach'),
  ('United States', 'Tpc Piper Glen'),
  ('United States', 'Tpc Potomac At Avenel Farm'),
  ('United States', 'Tpc Prestancia The Players Course'),
  ('United States', 'Tpc Prestancia The Stadium Course'),
  ('United States', 'Tpc River Highlands'),
  ('United States', 'Tpc Sawgrass Dyes Valley Course'),
  ('United States', 'Tpc Sawgrass The Players Stadium Course'),
  ('United States', 'Tpc Scottsdale The Champions Course'),
  ('United States', 'Tpc Scottsdale The Stadium Course'),
  ('United States', 'Tpc Southwind'),
  ('United States', 'Tpc Stonebrae'),
  ('United States', 'Tpc Sugarloaf Pines Course'),
  ('United States', 'Tpc Sugarloaf Stables Meadows Course'),
  ('United States', 'Tpc Summerlin'),
  ('United States', 'Tpc Tampa Bay'),
  ('United States', 'Tpc Treviso Bay'),
  ('United States', 'Tpc Wakefield Plantation'),
  ('United States', 'Tpc Wakefield Plantation Practice Course'),
  ('United States', 'Tpc Wisconsin'),
  ('United States', 'Tracy Country Club'),
  ('United States', 'Tracy Golf Country Club'),
  ('United States', 'Tradition At Tradition Golf Club'),
  ('United States', 'Tradition Golf Club'),
  ('United States', 'Tradition Golf Club At Oak Lane'),
  ('United States', 'Traditions At The Glen'),
  ('United States', 'Traditions Golf Club Learning Center'),
  ('United States', 'Traditions Of Braselton Golf Club'),
  ('United States', 'Traer Golf Club'),
  ('United States', 'Trail Blue At Blue Ridge Trail Golf Club'),
  ('United States', 'Trail Creek Course At Sun Valley Resort'),
  ('United States', 'Trail Ridge Golf Course At Sun City West'),
  ('United States', 'Trail Ruts Golf Course'),
  ('United States', 'Trail Side Golf and Foot Golf'),
  ('United States', 'Trailhead Golf Course'),
  ('United States', 'Trails End Golf Course'),
  ('United States', 'Trails West Golf Course'),
  ('United States', 'Tranquilo Golf Club At Four Seasons Resort Orlando'),
  ('United States', 'Transit Valley Country Club'),
  ('United States', 'Trapp River Golf Course'),
  ('United States', 'Trappers Turn Golf Club'),
  ('United States', 'Traveler''s Country Club'),
  ('United States', 'Travelers Rest Rv Resort Golf Course'),
  ('United States', 'Traverse City Golf and Country Club'),
  ('United States', 'Travis Pointe Country Club'),
  ('United States', 'Treasure Bay Golf Tennis'),
  ('United States', 'Tree Links Golf Course'),
  ('United States', 'Tree Top Golf Course'),
  ('United States', 'Treetops'),
  ('United States', 'Tregaron Golf Course'),
  ('United States', 'Trenton Country Club'),
  ('United States', 'Trenton Golf Club'),
  ('United States', 'Trestle Creek Golf Club'),
  ('United States', 'Treyburn Country Club'),
  ('United States', 'Treynor Recreation Area'),
  ('United States', 'Tri County Country Club'),
  ('United States', 'Tri Mountain Golf Course'),
  ('United States', 'Tri-City Country Club'),
  ('United States', 'Tri-Club Golf Club'),
  ('United States', 'Tri-County Golf Club'),
  ('United States', 'Tributary At River Strand Golf And Country Club'),
  ('United States', 'Tribute Golf Course'),
  ('United States', 'Trident Lakes Golf Club'),
  ('United States', 'Triggs Memorial Golf Course'),
  ('United States', 'Trillium Links'),
  ('United States', 'Trilogy Golf Club At La Quinta'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Players Loop'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Skills Course'),
  ('United States', 'Trilogy Golf Club At Vistancia'),
  ('United States', 'Trinidad Golf Course'),
  ('United States', 'Trinity Alps Golf Course'),
  ('United States', 'Trinity Golf Course'),
  ('United States', 'Triple Creek Golf Club'),
  ('United States', 'Triple Lakes Golf Course'),
  ('United States', 'Tripoli Country Club'),
  ('United States', 'Trona Golf Course'),
  ('United States', 'Troon Country Club'),
  ('United States', 'Trophy Lake Golf Casting Club'),
  ('United States', 'Trosper Golf Club'),
  ('United States', 'Trout Lake Golf Club'),
  ('United States', 'Troy Burne Golf Club'),
  ('United States', 'True Blue Golf Club'),
  ('United States', 'True North Golf Club'),
  ('United States', 'Trull Brook Golf Course'),
  ('United States', 'Truman At The Villages Executive Golf Trail'),
  ('United States', 'Trumann Country Club'),
  ('United States', 'Trumansburg Golf Club'),
  ('United States', 'Trump International Golf Club'),
  ('United States', 'Trump International Golf Club The Executive Golf Course'),
  ('United States', 'Trump National Doral Miami Blue Monster Course'),
  ('United States', 'Trump National Doral Miami Golden Palm Course'),
  ('United States', 'Trump National Doral Miami Red Tiger Course'),
  ('United States', 'Trump National Doral Miami Silver Fox Course'),
  ('United States', 'Trump National Golf Club'),
  ('United States', 'Trump National Golf Club Bedminster New Course'),
  ('United States', 'Trump National Golf Club Bedminster Old Course'),
  ('United States', 'Trump National Golf Club Charlotte'),
  ('United States', 'Trump National Golf Club Colts Neck Championship Course'),
  ('United States', 'Trump National Golf Club Colts Neck Par 3 Course'),
  ('United States', 'Trump National Golf Club Hudson Valley'),
  ('United States', 'Trump National Golf Club Philadelphia'),
  ('United States', 'Trump National Golf Club Washington D C Championship Course'),
  ('United States', 'Trump National Golf Club Washington D C River Course'),
  ('United States', 'Truth Or Consequence City Golf Course'),
  ('United States', 'Tryon Country Club'),
  ('United States', 'Tsawwassen Springs Golf'),
  ('United States', 'Tubac Golf Resort Anza Rancho'),
  ('United States', 'Tubac Golf Resort Otero Anza'),
  ('United States', 'Tubac Golf Resort Rancho Otero'),
  ('United States', 'Tuckaway Country Club'),
  ('United States', 'Tucson Catalina At Saddlebrooke Country Club'),
  ('United States', 'Tucson Country Club'),
  ('United States', 'Tucson Estates Country Club Golf Course'),
  ('United States', 'Tucumcari Municipal Golf Course'),
  ('United States', 'Tug Valley Country Club'),
  ('United States', 'Tulare Golf Course'),
  ('United States', 'Tullymore'),
  ('United States', 'Tulsa Country Club'),
  ('United States', 'Tumble Brook Country Club Blue Nine'),
  ('United States', 'Tumble Brook Country Club Green Nine'),
  ('United States', 'Tumble Brook Country Club Red Nine'),
  ('United States', 'Tumble Creek At Suncadia'),
  ('United States', 'Tumwater Valley Golf Club'),
  ('United States', 'Tunica National Golf And Tennis'),
  ('United States', 'Tunnel Hill Golf Course'),
  ('United States', 'Tupelo Bay Golf Complex Executive Course'),
  ('United States', 'Tupelo Bay Golf Complex Par 3 Course'),
  ('United States', 'Tupelo Country Club'),
  ('United States', 'Tupper Lake Country Club'),
  ('United States', 'Turin Highlands Golf Course'),
  ('United States', 'Turkana Golf Course'),
  ('United States', 'Turkey Creek Golf Club'),
  ('United States', 'Turkey Creek Golf Course'),
  ('United States', 'Turkey Run Golf Course'),
  ('United States', 'Turkeyfoot Lake Golf Links'),
  ('United States', 'Turlock Golf Country Club'),
  ('United States', 'Turnberry Golf Club'),
  ('United States', 'Turnberry Golf Course'),
  ('United States', 'Turnberry Isle Country Club Soffer Course'),
  ('United States', 'Turnberry Isle Country Club The Miller Course'),
  ('United States', 'Turner Highlands Country Club'),
  ('United States', 'Turner Hill Golf Racquet Club'),
  ('United States', 'Turquoise Hills Family Golf Center'),
  ('United States', 'Turtle Bay Resort Arnold Palmer Course'),
  ('United States', 'Turtle Bay Resort George Fazio Course'),
  ('United States', 'Turtle Bay Resort The Breaks Putting Course'),
  ('United States', 'Turtle Cove Property Owners Association Inc'),
  ('United States', 'Turtle Creek Club'),
  ('United States', 'Turtle Creek Golf Club'),
  ('United States', 'Turtle Creek Golf Course'),
  ('United States', 'Turtle Creek Golf Course At Garden Cathay'),
  ('United States', 'Turtle Hill Golf Course'),
  ('United States', 'Turtle Mound At The Villages Executive Golf Trail'),
  ('United States', 'Turtle Point At Kiawah Island Golf Resort'),
  ('United States', 'Turtle Run At Sun N Lake Golf Country Club'),
  ('United States', 'Turtle Run Golf Course'),
  ('United States', 'Turtleback'),
  ('United States', 'Turtleback Golf Course'),
  ('United States', 'Turtleback Mountain Golf Resort'),
  ('United States', 'Tuscan Ridge Golf Club'),
  ('United States', 'Tuscany Falls At Pebblecreek East Course'),
  ('United States', 'Tuscany Falls At Pebblecreek West Course'),
  ('United States', 'Tuscarora Country Club'),
  ('United States', 'Tuscarora Golf Club'),
  ('United States', 'Tuscawilla Golf Course'),
  ('United States', 'Tuscumbia Country Club'),
  ('United States', 'Tussey Mountain Golf Course'),
  ('United States', 'Tustin Ranch Golf Club'),
  ('United States', 'Tustin Trails Golf Course'),
  ('United States', 'Twaalfskill Club'),
  ('United States', 'Twain Harte Golf Club'),
  ('United States', 'Twelve Shores Golf Club'),
  ('United States', 'Twilight Golf Course'),
  ('United States', 'Twin Base Golf Course'),
  ('United States', 'Twin Beach Country Club'),
  ('United States', 'Twin Birch Golf Course'),
  ('United States', 'Twin Bridges Golf Club'),
  ('United States', 'Twin Bridges Golf Course'),
  ('United States', 'Twin Brook Golf Center'),
  ('United States', 'Twin Brooks Golf Course'),
  ('United States', 'Twin City Country Club'),
  ('United States', 'Twin Creeks Golf Course'),
  ('United States', 'Twin Falls Golf Club'),
  ('United States', 'Twin Falls Municipal Golf Course'),
  ('United States', 'Twin Falls State Park'),
  ('United States', 'Twin Hickory Golf Club'),
  ('United States', 'Twin Hills Country Club'),
  ('United States', 'Twin Hills Golf Country Club'),
  ('United States', 'Twin Hills Golf Course'),
  ('United States', 'Twin Isles Country Club'),
  ('United States', 'Twin Lake Par 3 Golf Course'),
  ('United States', 'Twin Lake Village Par 3 Golf Course'),
  ('United States', 'Twin Lakes Country Club'),
  ('United States', 'Twin Lakes Golf & Swim Club'),
  ('United States', 'Twin Lakes Golf Club'),
  ('United States', 'Twin Lakes Golf Country Club'),
  ('United States', 'Twin Lakes Golf Course'),
  ('United States', 'Twin Lakes Lakes Course'),
  ('United States', 'Twin Lakes Municipal Golf Course'),
  ('United States', 'Twin Lakes Oaks Course'),
  ('United States', 'Twin Lakes Of Kahoka'),
  ('United States', 'Twin Lakes Village Golf Course'),
  ('United States', 'Twin Oaks Country Club'),
  ('United States', 'Twin Oaks Golf Club'),
  ('United States', 'Twin Oaks Golf Country Club'),
  ('United States', 'Twin Oaks Golf Course'),
  ('United States', 'Twin Oaks Golf and Plantation Club'),
  ('United States', 'Twin Oaks Par 3 Golf Driving Range'),
  ('United States', 'Twin Orchards Country Club'),
  ('United States', 'Twin Peaks Golf Course'),
  ('United States', 'Twin Pines Golf Course'),
  ('United States', 'Twin Ponds Golf Club'),
  ('United States', 'Twin Ponds Golf Country Club'),
  ('United States', 'Twin Rivers Golf Club'),
  ('United States', 'Twin Rivers Golf Course'),
  ('United States', 'Twin Run Golf Course'),
  ('United States', 'Twin Springs Golf Course'),
  ('United States', 'Twin Valley Country Club'),
  ('United States', 'Twin Village Golf Club'),
  ('United States', 'Twin Warriors Golf Club'),
  ('United States', 'Twin Willows Par 3 Golf Course'),
  ('United States', 'Twin Woods Golf Club'),
  ('United States', 'Twineagles Golf Country Club Eagle Course'),
  ('United States', 'Twineagles Golf Country Club Talon Course'),
  ('United States', 'Twisted Dune Golf Club'),
  ('United States', 'Twisted Gun Golf Course'),
  ('United States', 'Twisted Oaks Golf Club'),
  ('United States', 'Twisted Pine Golf Course'),
  ('United States', 'Two East Course At Apple Greens Golf Course'),
  ('United States', 'Two Oaks North Golf Club'),
  ('United States', 'Two Rivers Country Club'),
  ('United States', 'Two Rivers Golf Club'),
  ('United States', 'Tyler Creek Golf Club'),
  ('United States', 'Tylertown Country Club'),
  ('United States', 'Tyngsboro Country Club'),
  ('United States', 'Tyoga Golf Course'),
  ('United States', 'Tyrone Hills Golf Club'),
  ('United States', 'U S Soldiers And Airmens Home Golf Course'),
  ('United States', 'Ubly Heights Golf & Country Club'),
  ('United States', 'Uchee Trail Country Club'),
  ('United States', 'Ukiah Valley Golf Course'),
  ('United States', 'Ulen Country Club'),
  ('United States', 'Umstead Pines Golf Swim Club At Willowhaven'),
  ('United States', 'Unc Finley Golf Course'),
  ('United States', 'Uncle Remus Golf Course'),
  ('United States', 'Undermountain Golf Course'),
  ('United States', 'Unf Golf Complex At The Hayt Learning Center'),
  ('United States', 'Unicorn Golf Course'),
  ('United States', 'Union City Country Club'),
  ('United States', 'Union Country Club'),
  ('United States', 'Union County Country Club'),
  ('United States', 'Union Golf Course'),
  ('United States', 'Union Hills Golf Country Club'),
  ('United States', 'Union Lake Golf Course'),
  ('United States', 'Union League Golf Club At Torresdale'),
  ('United States', 'Union League Liberty Hill'),
  ('United States', 'Union League National Golf Club Meade Grant'),
  ('United States', 'Union League National Golf Club Sherman Grant'),
  ('United States', 'Union League National Golf Club Sherman Meade'),
  ('United States', 'Uniontown Country Club'),
  ('United States', 'University Club'),
  ('United States', 'University Club Of Milwaukee'),
  ('United States', 'University Golf Club'),
  ('United States', 'University Of Denver Golf Club At Highlands Ranch'),
  ('United States', 'University Of Georgia Golf Course'),
  ('United States', 'University Of Idaho Golf Course'),
  ('United States', 'University Of Maryland Golf Course'),
  ('United States', 'University Of Montana Golf Course The'),
  ('United States', 'University Of New Mexico North Course'),
  ('United States', 'University Park Golf Course'),
  ('United States', 'University Ridge Golf Course'),
  ('United States', 'University of Illinois Golf Course'),
  ('United States', 'University of Louisville Golf Club'),
  ('United States', 'University of Michigan Golf Course'),
  ('United States', 'University of North Dakota Golf Course'),
  ('United States', 'Upland Hills Country Club'),
  ('United States', 'Upland Trace Golf Club'),
  ('United States', 'Uplands Golf Club'),
  ('United States', 'Upper At Baltusrol Golf Club'),
  ('United States', 'Upper At Peekn Peak Golf Course'),
  ('United States', 'Upper Canada Golf Course'),
  ('United States', 'Upper Lansdowne Golf Course'),
  ('United States', 'Urban Put Put'),
  ('United States', 'Urbana Country Club'),
  ('United States', 'Urbandale Golf & Country Club'),
  ('United States', 'Useless Bay Golf Country Club'),
  ('United States', 'Ute Creek Golf Course'),
  ('United States', 'Utica Golf Club'),
  ('United States', 'Va Jo Wa Golf Club'),
  ('United States', 'Vache Grasse Country Club'),
  ('United States', 'Vail Golf Club'),
  ('United States', 'Vails Grove Golf Course'),
  ('United States', 'Val Halla Golf Recreation Center'),
  ('United States', 'Valencia Country Club'),
  ('United States', 'Valencia Golf Country Club'),
  ('United States', 'Valhalla Golf Club'),
  ('United States', 'Valle Del Sol Golf Course'),
  ('United States', 'Valle Vista Golf Course'),
  ('United States', 'Valleaire Golf Club'),
  ('United States', 'Valley At Castlewood Country Club'),
  ('United States', 'Valley At Colonial Springs Golf Course'),
  ('United States', 'Valley At Cordillera Golf Course'),
  ('United States', 'Valley At Marriotts Desert Springs Resort'),
  ('United States', 'Valley At Towa Golf Resort'),
  ('United States', 'Valley Brook Golf Course'),
  ('United States', 'Valley Club Of Montecito'),
  ('United States', 'Valley Country Club'),
  ('United States', 'Valley Course At Christmans Windham House'),
  ('United States', 'Valley Gardens Golf Course'),
  ('United States', 'Valley Golf Center'),
  ('United States', 'Valley Golf Centre'),
  ('United States', 'Valley Golf Course'),
  ('United States', 'Valley Green Golf Country Club'),
  ('United States', 'Valley Green Golf Course'),
  ('United States', 'Valley Green Par 3 Course'),
  ('United States', 'Valley Hi Country Club'),
  ('United States', 'Valley Hi Municipal Golf Course'),
  ('United States', 'Valley High Golf Course'),
  ('United States', 'Valley Links Course'),
  ('United States', 'Valley Lo Club'),
  ('United States', 'Valley Mountain At Pinery Country Club'),
  ('United States', 'Valley Oaks At North Ranch Country Club'),
  ('United States', 'Valley Oaks At Valley Oaks Golf Club'),
  ('United States', 'Valley Of The Eagles Golf Links'),
  ('United States', 'Valley Of The Moon Golf Club'),
  ('United States', 'Valley Pine Country Club'),
  ('United States', 'Valley Pines Golf Club'),
  ('United States', 'Valley Point Golf Course'),
  ('United States', 'Valley View Country Club'),
  ('United States', 'Valley View Golf'),
  ('United States', 'Valley View Golf Club'),
  ('United States', 'Valley View Golf Course'),
  ('United States', 'Valley View Municipal Golf Course'),
  ('United States', 'Valley Vista At Los Coyotes Country Club'),
  ('United States', 'Valley Vista Golf Course'),
  ('United States', 'Valleywood Golf Club'),
  ('United States', 'Valleywood Golf Course'),
  ('United States', 'Valparaiso Country Club'),
  ('United States', 'Van Buren Golf Center'),
  ('United States', 'Van Buren Recreation Area Golf'),
  ('United States', 'Van Cortlandt Park Golf Course'),
  ('United States', 'Van Patten Golf Club Blue Red'),
  ('United States', 'Van Patten Golf Club Red White'),
  ('United States', 'Van Patten Golf Club White Blue'),
  ('United States', 'Van Schaick Island Country Club'),
  ('United States', 'Vanderbilt Country Club'),
  ('United States', 'Vandergrift Golf Club'),
  ('United States', 'Vanmetre 9 At Stonebridge'),
  ('United States', 'Vardon Golf Club'),
  ('United States', 'Vasari Country Club'),
  ('United States', 'Vashon Island Golf Country Club'),
  ('United States', 'Vassar Golf Course'),
  ('United States', 'Vassar Golf and Country Club'),
  ('United States', 'Veenker Memorial Golf Course'),
  ('United States', 'Venango Valley Inn Golf Course'),
  ('United States', 'Venetian Gardens Golf Course'),
  ('United States', 'Venetian Golf Club'),
  ('United States', 'Venice East Golf Club'),
  ('United States', 'Venice Golf Country Club'),
  ('United States', 'Ventana Canyon Canyon Course'),
  ('United States', 'Ventana Canyon Mountain Course'),
  ('United States', 'Ventura Country Club'),
  ('United States', 'Verde River Golf Social Club'),
  ('United States', 'Verdict Ridge Golf Country Club'),
  ('United States', 'Vermilion Golf Course'),
  ('United States', 'Vermilion River Greens'),
  ('United States', 'Vermillion Fairways'),
  ('United States', 'Vermont National Country Club'),
  ('United States', 'Vernon Hills Golf Course'),
  ('United States', 'Vernonia Golf Club'),
  ('United States', 'Vero Beach Country Club'),
  ('United States', 'Verona Hills Golf Club'),
  ('United States', 'Verona Meadows'),
  ('United States', 'Verrado Golf Club Founders Course'),
  ('United States', 'Verrado Golf Club Victory Course'),
  ('United States', 'Vesper Country Club'),
  ('United States', 'Vesper Hills Golf Club'),
  ('United States', 'Vestal Hills Country Club'),
  ('United States', 'Veteran''s Memorial Golf Course'),
  ('United States', 'Veterans Golf Course'),
  ('United States', 'Veterans Memorial Golf Course'),
  ('United States', 'Via Mizner Golf Country Club'),
  ('United States', 'Via Verde Country Club'),
  ('United States', 'Viburnum Golf & Country Club'),
  ('United States', 'Vic Meyers Golf Course At Sun Lakes'),
  ('United States', 'Vicksburg Country Club'),
  ('United States', 'Victoria Club'),
  ('United States', 'Victoria Country Club'),
  ('United States', 'Victoria Golf Centre'),
  ('United States', 'Victoria Golf Club'),
  ('United States', 'Victoria Golf Course'),
  ('United States', 'Victoria Hills Golf Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Victoria National Golf Club'),
  ('United States', 'Victors Par 3 Golf Course'),
  ('United States', 'Victory Hills Golf Course'),
  ('United States', 'Victory Lake Golf Course'),
  ('United States', 'Victory Links Golf Course'),
  ('United States', 'Victory Ranch Golf Club'),
  ('United States', 'Vienna Greens Country Club'),
  ('United States', 'Viera East Golf Club'),
  ('United States', 'Viking Golf Course'),
  ('United States', 'Viking Meadows Golf Club'),
  ('United States', 'Villa Olivia Country Club'),
  ('United States', 'Villa Roma Golf Course'),
  ('United States', 'Village At Jupiter Hills Club'),
  ('United States', 'Village Club Of Sands Point'),
  ('United States', 'Village Creek Golf Club'),
  ('United States', 'Village Golf Course'),
  ('United States', 'Village Green Country Club'),
  ('United States', 'Village Green Golf Club'),
  ('United States', 'Village Green Golf Course'),
  ('United States', 'Village Greens Golf Country Club'),
  ('United States', 'Village Greens Golf Course'),
  ('United States', 'Village Greens of Woodridge'),
  ('United States', 'Village Links Golf Club'),
  ('United States', 'Villages At Country Creek The'),
  ('United States', 'Villas Crossing Golf Course'),
  ('United States', 'Ville Platte Golf Country Club'),
  ('United States', 'Vinces Sport Center Par 3 Golf Course'),
  ('United States', 'Vineland Golf Course'),
  ('United States', 'Vineyard Golf At White Lake'),
  ('United States', 'Vineyard Golf Club'),
  ('United States', 'Vineyard Golf Course'),
  ('United States', 'Vineyard Greens Golf Course'),
  ('United States', 'Vineyard Knolls Golf Club'),
  ('United States', 'Vineyard National Golf Course'),
  ('United States', 'Vineyard Valley Golf Club'),
  ('United States', 'Vintage At White Deer Golf Club'),
  ('United States', 'Vintners Golf Club'),
  ('United States', 'Vinton Country Club'),
  ('United States', 'Virginia Amelia At Mallory Hill Golf Course'),
  ('United States', 'Virginia Beach National Golf Club'),
  ('United States', 'Virginia Country Club'),
  ('United States', 'Virginia Golf Center'),
  ('United States', 'Virginia Golf Course'),
  ('United States', 'Virginia Tech Golf Course'),
  ('United States', 'Viroqua Hills Golf Course'),
  ('United States', 'Visalia Country Club'),
  ('United States', 'Vista Golf Course'),
  ('United States', 'Vista Lake At Los Coyotes Country Club'),
  ('United States', 'Vista Plantation Golf Course'),
  ('United States', 'Volcano Golf Country Club'),
  ('United States', 'Volusia At The Villages Executive Golf Trail'),
  ('United States', 'Voyager Rv Resort And Golf Course'),
  ('United States', 'Voyager Village'),
  ('United States', 'Voyager Village Par 3'),
  ('United States', 'Wa Noa Golf Club'),
  ('United States', 'Waabooz Run Golf Course'),
  ('United States', 'Wabaunsee Pines Golf Course'),
  ('United States', 'Wabeek Country Club'),
  ('United States', 'Waccabuc Country Club'),
  ('United States', 'Wachesaw East Golf Club'),
  ('United States', 'Wachesaw Plantation Club'),
  ('United States', 'Wachusett Country Club'),
  ('United States', 'Wade Hampton Golf Course'),
  ('United States', 'Wagon Trail To Lonesome Pine Golf Course'),
  ('United States', 'Wahconah Country Club'),
  ('United States', 'Wahkonsa Country Club'),
  ('United States', 'Waialae Country Club'),
  ('United States', 'Waiehu Golf Course'),
  ('United States', 'Waikele Country Club'),
  ('United States', 'Waikoloa Beach Resort Beach Course'),
  ('United States', 'Waikoloa Beach Resort Kings Lakes Course'),
  ('United States', 'Wailea Golf Club Emerald Course'),
  ('United States', 'Wailea Golf Club Gold Course'),
  ('United States', 'Wailea Golf Club Old Blue Course'),
  ('United States', 'Wailua Municipal Golf Course'),
  ('United States', 'Wakonda Club'),
  ('United States', 'Wakulla Sands Golf Club'),
  ('United States', 'Walden Oaks Country Club'),
  ('United States', 'Walden Ponds Golf Club'),
  ('United States', 'Waldorf Astoria Golf Club'),
  ('United States', 'Waldron Country Club'),
  ('United States', 'Walker Creek Golf Course'),
  ('United States', 'Walking Stick Golf Course'),
  ('United States', 'Walla Walla Country Club'),
  ('United States', 'Wallingford Country Club'),
  ('United States', 'Wallinwood Springs Golf Club'),
  ('United States', 'Wallkill Golf Club'),
  ('United States', 'Walloon Lake Country Club'),
  ('United States', 'Walnut Creek Country Club'),
  ('United States', 'Walnut Creek Golf Club'),
  ('United States', 'Walnut Creek Golf Preserve'),
  ('United States', 'Walnut Greens Golf Course'),
  ('United States', 'Walnut Grove At The Villages Executive Golf Trail'),
  ('United States', 'Walnut Grove Golf Course'),
  ('United States', 'Walnut Lake Country Club'),
  ('United States', 'Walnut Lane Golf Club'),
  ('United States', 'Walnut Ridge Golf Country Club'),
  ('United States', 'Walpole Country Club'),
  ('United States', 'Walsenburg Golf Course'),
  ('United States', 'Walsh Golf Center'),
  ('United States', 'Walter E Hall Memorial Golf Course'),
  ('United States', 'Walter J Nagorski Golf Course'),
  ('United States', 'Walter Sellers Memorial Country Club'),
  ('United States', 'Walther''s Golf Driving Range'),
  ('United States', 'Walton Golf Club'),
  ('United States', 'Waltz Golf Farm'),
  ('United States', 'Wamego Country Club'),
  ('United States', 'Wampanoag Country Club'),
  ('United States', 'Wampanoag Golf Course'),
  ('United States', 'Wampatuck Country Club'),
  ('United States', 'Wanakah Country Club'),
  ('United States', 'Wanaki Golf Course'),
  ('United States', 'Wanamaker Course At Pga Golf Club'),
  ('United States', 'Wanango Country Club'),
  ('United States', 'Wander Springs Golf Course'),
  ('United States', 'Wandering Creek Golf Course'),
  ('United States', 'Wandermere Golf Course'),
  ('United States', 'Wanee Lake Country Club'),
  ('United States', 'Wannamoisett Country Club'),
  ('United States', 'Wanumetonomy Golf Country Club'),
  ('United States', 'Wapicada Golf Club'),
  ('United States', 'Wapsi Oaks Country Club'),
  ('United States', 'Wapsie Ridge Golf Course'),
  ('United States', 'Wapsipinicon Country Club'),
  ('United States', 'Ware Shoals Golf Course'),
  ('United States', 'Warfield Greens Golf Club'),
  ('United States', 'Warm Springs Golf Course'),
  ('United States', 'Warminsters Five Ponds Golf Club'),
  ('United States', 'Warner Springs Ranch'),
  ('United States', 'Warnimont Park Golf Course'),
  ('United States', 'Warren Country Club'),
  ('United States', 'Warren Golf Course'),
  ('United States', 'Warren Swigart 9-Hole Golf Course'),
  ('United States', 'Warren Valley Golf Course'),
  ('United States', 'Warrenbrook Golf Course'),
  ('United States', 'Warrenton Golf Course'),
  ('United States', 'Warrior Golf Club'),
  ('United States', 'Warrior Hills Golf Course'),
  ('United States', 'Warrior Run Golf Course'),
  ('United States', 'Warriors Path State Park Golf Course'),
  ('United States', 'Warroad Estates Golf Course'),
  ('United States', 'Warwick Country Club'),
  ('United States', 'Warwick Hills Golf & Country Club'),
  ('United States', 'Warwick Valley Country Club'),
  ('United States', 'Washakie Golf and RV Resort'),
  ('United States', 'Washington Country Club'),
  ('United States', 'Washington County Golf Country Club'),
  ('United States', 'Washington County Golf Course'),
  ('United States', 'Washington Golf Club'),
  ('United States', 'Washington Golf Country Club'),
  ('United States', 'Washington Golf Learning Center'),
  ('United States', 'Washington National Golf Club'),
  ('United States', 'Washington Park Golf Course'),
  ('United States', 'Washington Park Municipal Golf Course'),
  ('United States', 'Washington Township Municipal Golf Course'),
  ('United States', 'Washington Wilkes Country Club'),
  ('United States', 'Washington Yacht Country Club'),
  ('United States', 'Washoe Golf Course'),
  ('United States', 'Washtenaw Golf Club'),
  ('United States', 'Wasioto Winds At Pine Mountain State Park Golf Course'),
  ('United States', 'Waskada Golf Club'),
  ('United States', 'Watchung Valley Golf Club'),
  ('United States', 'Water Oak Golf Club'),
  ('United States', 'Water''s Edge Golf Club'),
  ('United States', 'Waterfall Golf Club'),
  ('United States', 'Waterford Golf Club'),
  ('United States', 'Waterlefe Golf River Club'),
  ('United States', 'Waterloo Country Club'),
  ('United States', 'Waterloo Golf Course'),
  ('United States', 'Watermark Country Club'),
  ('United States', 'Waters Edge Gold Course'),
  ('United States', 'Waters Edge Golf Course'),
  ('United States', 'Waters Mounds At Brickyard Plantation Golf Club'),
  ('United States', 'Watertown Coutry Club'),
  ('United States', 'Watertown Golf Club'),
  ('United States', 'Waterville Community Golf Association'),
  ('United States', 'Waterville Country Club'),
  ('United States', 'Waterville Valley Golf Club'),
  ('United States', 'Waterways Golf Resort East Course'),
  ('United States', 'Waterways Golf Resort West Course'),
  ('United States', 'Watkins Glen Golf Club'),
  ('United States', 'Watonga Golf Club'),
  ('United States', 'Waubeeka Golf Links'),
  ('United States', 'Waukewan Golf Club'),
  ('United States', 'Waukon Golf and Country Club'),
  ('United States', 'Waumbek Golf Club'),
  ('United States', 'Waupaca Country Club'),
  ('United States', 'Wausau Country Club'),
  ('United States', 'Wausaukee Club'),
  ('United States', 'Waushara Country Club'),
  ('United States', 'Waveland Golf Course'),
  ('United States', 'Waverly Municipal Golf Course'),
  ('United States', 'Waverly Oaks Golf Club'),
  ('United States', 'Wawasee Golf Club'),
  ('United States', 'Wawashkamo Golf Course'),
  ('United States', 'Wawenock Golf Club'),
  ('United States', 'Wawona Golf Course'),
  ('United States', 'Wawonowin Golf Course'),
  ('United States', 'Wayland Country Club'),
  ('United States', 'Wayne Hills Country Club'),
  ('United States', 'Waynesboro Country Club'),
  ('United States', 'Waynesboro Par 3 Golf Course'),
  ('United States', 'Waynesborough Country Club'),
  ('United States', 'Waynesville Inn Golf Club'),
  ('United States', 'Wayton Hill''s Golf Course'),
  ('United States', 'Wayzata Country Club'),
  ('United States', 'Weathervane Golf Club'),
  ('United States', 'WeaverRidge Golf Club'),
  ('United States', 'Webb Park Golf Course'),
  ('United States', 'Webbs Reserve Golf Club'),
  ('United States', 'Weber Park Golf Course'),
  ('United States', 'Webhannet Golf Club'),
  ('United States', 'Webster City Country Club'),
  ('United States', 'Weddington Golf And Tennis'),
  ('United States', 'Wedgefield Country Club'),
  ('United States', 'Wedgefield Golf Club'),
  ('United States', 'Wedgewood'),
  ('United States', 'Wedgewood Cove Golf Club'),
  ('United States', 'Wedgewood Golf & Country Club'),
  ('United States', 'Wedgewood Golf Club'),
  ('United States', 'Wedgewood Golf Club Maple Course'),
  ('United States', 'Wedgewood Golf Club Oak Course'),
  ('United States', 'Wedgewood Golf Club Pine Course'),
  ('United States', 'Wedgewood Golf Course'),
  ('United States', 'Wedgewood Par 3 Golf Course'),
  ('United States', 'Wedgewood Pines Country Club'),
  ('United States', 'Wedgwood Country Club'),
  ('United States', 'Wee Burn Country Club'),
  ('United States', 'Wee Nip At Grand Geneva Resort Spa'),
  ('United States', 'Weed Golf Club'),
  ('United States', 'Weekapaug Golf Club'),
  ('United States', 'Weeping Trout Sports Resort'),
  ('United States', 'Weequahic Park Golf Course'),
  ('United States', 'Weibring Golf Club'),
  ('United States', 'Weissinger Hills Golf Course'),
  ('United States', 'Wekiva Golf Club'),
  ('United States', 'Welk Resort San Diego Fountains Executive Course'),
  ('United States', 'Welk Resort San Diego Oaks Course'),
  ('United States', 'Wellen Park Golf Country Club'),
  ('United States', 'Wellesley Country Club'),
  ('United States', 'Wellesley Island State Park Golf Course'),
  ('United States', 'Wellington Country Club'),
  ('United States', 'Wellington Golf Club'),
  ('United States', 'Wellington Greens Golf Course'),
  ('United States', 'Wellington National Golf Club'),
  ('United States', 'Wellman Golf Club'),
  ('United States', 'Wellman Golf Course'),
  ('United States', 'Wells College Golf Course'),
  ('United States', 'Wells Golf Course'),
  ('United States', 'Wellshire Golf Course'),
  ('United States', 'Wellsville Country Club'),
  ('United States', 'Wemberly Hills Golf Course'),
  ('United States', 'Wenatchee Golf Country Club'),
  ('United States', 'Wendell Coffee Golf Center'),
  ('United States', 'Wendell Country Club'),
  ('United States', 'Wenham Country Club'),
  ('United States', 'Wentworth By The Sea Country Club'),
  ('United States', 'Wentworth Golf Club'),
  ('United States', 'Wentworth Hills Golf Country Club Semi Private'),
  ('United States', 'Wequetonsing Golf Club'),
  ('United States', 'Wesburn Golf Club'),
  ('United States', 'West Appleton Country Club'),
  ('United States', 'West At Belfair Golf Club'),
  ('United States', 'West At Broadmoor Golf Club'),
  ('United States', 'West At Bull Creek Golf Course'),
  ('United States', 'West At Churchville Park Golf Course'),
  ('United States', 'West At Country Club Of Hershey'),
  ('United States', 'West At Eagle Valley Golf Course'),
  ('United States', 'West At Fountains Country Club'),
  ('United States', 'West At Glendoveer Golf Course'),
  ('United States', 'West At Grandover Resort'),
  ('United States', 'West At Imperial Golf Club'),
  ('United States', 'West At Jacaranda Golf Club'),
  ('United States', 'West At Johns Island Club'),
  ('United States', 'West At Laurel Oak Country Club'),
  ('United States', 'West At Lincoln Park Golf Course'),
  ('United States', 'West At Maidstone Club'),
  ('United States', 'West At Malone Golf Club'),
  ('United States', 'West At Merion Golf Club'),
  ('United States', 'West At Mohawk Golf Club'),
  ('United States', 'West At Oak Hill Country Club'),
  ('United States', 'West At Oak Tree Country Club'),
  ('United States', 'West At Orangebrook Country Club'),
  ('United States', 'West At Rogues Roost Golf Country Club'),
  ('United States', 'West At Tamarack Golf Course'),
  ('United States', 'West At Westchester Country Club'),
  ('United States', 'West At Windyke Country Club'),
  ('United States', 'West At Winged Foot Golf Club'),
  ('United States', 'West At Wycliffe Country Club'),
  ('United States', 'West Bay Golf Club'),
  ('United States', 'West Bend Country Club'),
  ('United States', 'West Bend Golf and Country Club'),
  ('United States', 'West Bend Lakes'),
  ('United States', 'West Bend Lakes Golf Club'),
  ('United States', 'West Bolton Golf Club'),
  ('United States', 'West Branch Country Club'),
  ('United States', 'West Bridgewater Country Club'),
  ('United States', 'West Chase Golf Club'),
  ('United States', 'West Chester Golf Country Club'),
  ('United States', 'West Course At Belleair Country Club'),
  ('United States', 'West East At Ridgewood Country Club The'),
  ('United States', 'West End Golf Course'),
  ('United States', 'West Grand Golf'),
  ('United States', 'West Hill Country Club'),
  ('United States', 'West Hills Country Club'),
  ('United States', 'West Hills Country Club River Course'),
  ('United States', 'West Hills Par 3'),
  ('United States', 'West Lafayette Golf Club'),
  ('United States', 'West Lake Country Club'),
  ('United States', 'West Liberty Country Club'),
  ('United States', 'West Loch Municipal Golf Course'),
  ('United States', 'West Nine At Firethorn'),
  ('United States', 'West Nine At Southern Hills Country Club'),
  ('United States', 'West North At Cedar Knoll Country Club'),
  ('United States', 'West North At Elmridge Golf Club'),
  ('United States', 'West North At Krendale Golf Course'),
  ('United States', 'West North At Rolling Acres Golf Course'),
  ('United States', 'West Orange Country Club'),
  ('United States', 'West Ottawa Golf Course'),
  ('United States', 'West Pines Golf Club'),
  ('United States', 'West Plains Country Club'),
  ('United States', 'West Point Country Club'),
  ('United States', 'West Point Golf Course'),
  ('United States', 'West Public At Drumlins Golf Club'),
  ('United States', 'West Richland Municipal Golf'),
  ('United States', 'West Sayville Golf Course'),
  ('United States', 'West Seattle Golf Club'),
  ('United States', 'West Shore Country Club'),
  ('United States', 'West Shore Golf & Country Club'),
  ('United States', 'West Side Golf Club'),
  ('United States', 'West South At Cedar Knoll Country Club'),
  ('United States', 'West South At Fernandina Beach Golf Club'),
  ('United States', 'West South At South Hills Golf Club'),
  ('United States', 'West Warwick Country Club'),
  ('United States', 'Westborough Country Club'),
  ('United States', 'Westborough County Club'),
  ('United States', 'Westbrook Country Club'),
  ('United States', 'Westbrook Golf Club Lakes Course'),
  ('United States', 'Westbrook Golf Club Vistas Course'),
  ('United States', 'Westbrook Hills Golf Course'),
  ('United States', 'Westchase Golf Club'),
  ('United States', 'Westchester Golf Course'),
  ('United States', 'Westchester Hills Golf Club'),
  ('United States', 'Westdrift Manhattan Beach Golf Club'),
  ('United States', 'Western Acres Golf Course'),
  ('United States', 'Western Golf and Country Club'),
  ('United States', 'Western Greens Country Club'),
  ('United States', 'Western Hills Country Club'),
  ('United States', 'Western Hills Golf Club'),
  ('United States', 'Western Hills Golf Country Club'),
  ('United States', 'Western Hills Golf Course'),
  ('United States', 'Western Lakes Golf Course'),
  ('United States', 'Western Skies Golf Club'),
  ('United States', 'Western View Golf Club'),
  ('United States', 'Westerville Golf Center'),
  ('United States', 'Westfield Country Club'),
  ('United States', 'Westfield Golf Club'),
  ('United States', 'Westfields Golf Club'),
  ('United States', 'Westgate River Ranch Resort'),
  ('United States', 'Westhampton Country Club'),
  ('United States', 'Westhaven Golf Club'),
  ('United States', 'Westin Rancho Mirage Golf Resort Spa Pete Dye Resort Course'),
  ('United States', 'Westlake Country Club'),
  ('United States', 'Westlake Golf And Country Club'),
  ('United States', 'Westlake Golf Country Club'),
  ('United States', 'Westlake Golf Course'),
  ('United States', 'Westminster Country Club'),
  ('United States', 'Westminster National Golf Course'),
  ('United States', 'Westmoor Country Club'),
  ('United States', 'Westmoreland Country Club'),
  ('United States', 'Westmoreland Golf Club'),
  ('United States', 'Weston Golf Club'),
  ('United States', 'Weston Hills Country Club Players Course'),
  ('United States', 'Weston Hills Country Club Tour Course'),
  ('United States', 'Westover Golf Club'),
  ('United States', 'Westport Country Club The'),
  ('United States', 'Westport Golf Course'),
  ('United States', 'Westport Longshore Golf Club'),
  ('United States', 'Westridge Golf Club'),
  ('United States', 'Westvale Golf Course'),
  ('United States', 'Westview Golf Course'),
  ('United States', 'Westwind Golf Course'),
  ('United States', 'Westwind Rv Golf Resort'),
  ('United States', 'Westwood Country Club'),
  ('United States', 'Westwood Golf Club'),
  ('United States', 'Westwood Golf Course'),
  ('United States', 'Westwood Golf Course (9-hole)'),
  ('United States', 'Westwood Hills Country Club'),
  ('United States', 'Westwood Park Golf Course'),
  ('United States', 'Westwood West Golf Course'),
  ('United States', 'Westwoods Golf Club'),
  ('United States', 'Westwynd Golf Course'),
  ('United States', 'Wetherington Golf & Country Club'),
  ('United States', 'Wethersfield Country Club'),
  ('United States', 'Wetumka Golf Club'),
  ('United States', 'Wexford Golf'),
  ('United States', 'Weyhill At Saucon Valley Country Club'),
  ('United States', 'Weymont Run Country Club'),
  ('United States', 'Whaling City Golf Course At New Bedford'),
  ('United States', 'Wheatfield Valley Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Wheatland Golf Club'),
  ('United States', 'Wheatley Hills Golf Club'),
  ('United States', 'Wheeler Family Traditions Golf Club'),
  ('United States', 'Wheeling Country Club'),
  ('United States', 'Wheeling Country Club Golf Course'),
  ('United States', 'Wheeling Park Golf Course'),
  ('United States', 'Wheeling Park Minature Golf'),
  ('United States', 'Whidbey Golf Club'),
  ('United States', 'Whip Poor Will Golf Course'),
  ('United States', 'Whippoorwill Club'),
  ('United States', 'Whirlpool Golf Course'),
  ('United States', 'Whirlwind Golf Club The Cattail Course'),
  ('United States', 'Whirlwind Golf Club The Devils Claw Course'),
  ('United States', 'Whiskey Creek Country Club'),
  ('United States', 'Whisky Run Golf Club Fox'),
  ('United States', 'Whisper Creek Country Club'),
  ('United States', 'Whisper Lake Country Club'),
  ('United States', 'Whisper Rock Golf Club Lower Course'),
  ('United States', 'Whisper Rock Golf Club Upper Course'),
  ('United States', 'Whispering Creek Golf Club'),
  ('United States', 'Whispering Creek Golf Course'),
  ('United States', 'Whispering Firs Golf Club'),
  ('United States', 'Whispering Hills Golf Course'),
  ('United States', 'Whispering Lakes Golf Course'),
  ('United States', 'Whispering Meadows Golf Course'),
  ('United States', 'Whispering Oak At Verandah'),
  ('United States', 'Whispering Oaks Golf Club'),
  ('United States', 'Whispering Pines Golf Club'),
  ('United States', 'Whispering Pines Golf Course'),
  ('United States', 'Whispering Springs Golf Club'),
  ('United States', 'Whispering Willows Golf Course'),
  ('United States', 'Whispering Winds Golf Club'),
  ('United States', 'Whispering Woods Golf Club'),
  ('United States', 'Whispering Woods Golf Course'),
  ('United States', 'Whistling Straits'),
  ('United States', 'White At Eisenhower Park Golf Course'),
  ('United States', 'White At Ford Hill Country Club'),
  ('United States', 'White At Golf Club Of Avon'),
  ('United States', 'White At Penn State Golf Courses'),
  ('United States', 'White At Tunxis Country Club'),
  ('United States', 'White Barn Estates'),
  ('United States', 'White Bear Yacht Club'),
  ('United States', 'White Beeches Golf Country Club'),
  ('United States', 'White Birch Golf Course'),
  ('United States', 'White Birch Hills Golf Course'),
  ('United States', 'White Birches Country Club'),
  ('United States', 'White Blue At Buck Hill Falls Golf Club'),
  ('United States', 'White Blue At Glen Oaks Club'),
  ('United States', 'White Blue At Highland Lakes Golf Course'),
  ('United States', 'White Blue At Little Mill Country Club'),
  ('United States', 'White Blue At Myakka Pines Golf Club'),
  ('United States', 'White Blue At Ramblewood Country Club'),
  ('United States', 'White Blue At Shawnee Inn Golf Resort'),
  ('United States', 'White Blue At Shenandoah Valley Golf Club'),
  ('United States', 'White Blue At Town Of Colonie Golf Course'),
  ('United States', 'White Blue At Western Turnpike Golf Course'),
  ('United States', 'White Clay Creek Country Club At Delaware Park'),
  ('United States', 'White Cliffs Country Club'),
  ('United States', 'White Clouds At Sun Valley Resort'),
  ('United States', 'White Columns Golf Club'),
  ('United States', 'White Deer Country Club'),
  ('United States', 'White Deer Run Golf Club'),
  ('United States', 'White Eagle Golf Club'),
  ('United States', 'White Gold At Wyndemere Country Club'),
  ('United States', 'White Hawk Country Club'),
  ('United States', 'White Heron Golf Club'),
  ('United States', 'White Horse Golf Club'),
  ('United States', 'White Lake Golf Club'),
  ('United States', 'White Lake Oaks Golf Course'),
  ('United States', 'White Lick Golf Course'),
  ('United States', 'White Manor Country Club'),
  ('United States', 'White Mountain Country Club'),
  ('United States', 'White Mountain Golf Course Desert Nine'),
  ('United States', 'White Mountain Golf Course Lakes Nine'),
  ('United States', 'White Mountain Golf Course Sands Nine'),
  ('United States', 'White Mountain Golf Park'),
  ('United States', 'White Nine At Hyde Park Golf Course'),
  ('United States', 'White Oak Golf Course'),
  ('United States', 'White Oak Plantation'),
  ('United States', 'White Oaks Country Club'),
  ('United States', 'White Oaks Golf Club'),
  ('United States', 'White Path Golf Club'),
  ('United States', 'White Pine Golf Course'),
  ('United States', 'White Pine National'),
  ('United States', 'White Pines Country Club'),
  ('United States', 'White Pines Golf Club'),
  ('United States', 'White Pines Golf Course'),
  ('United States', 'White Plains Golf Club'),
  ('United States', 'White Plains Golf Course'),
  ('United States', 'White Red At Edgewood Country Club'),
  ('United States', 'White Red At Ramblewood Country Club'),
  ('United States', 'White Red At Sugar Mill Country Club'),
  ('United States', 'White Red At Timber Point Country Club'),
  ('United States', 'White Red At Willowbrook Golf Club'),
  ('United States', 'White River Golf Club'),
  ('United States', 'White Springs Golf Course'),
  ('United States', 'White Tail Golf Course'),
  ('United States', 'White Wing At Rio Verde Country Club'),
  ('United States', 'Whitebirch Golf Course'),
  ('United States', 'Whiteface Club'),
  ('United States', 'Whitefish Golf club'),
  ('United States', 'Whitefish Lake Golf Club'),
  ('United States', 'Whiteford Valley Golf Club'),
  ('United States', 'Whitehall Public Golf Course'),
  ('United States', 'Whitehawk Ranch Golf Club'),
  ('United States', 'Whitemarsh Valley Country Club'),
  ('United States', 'Whitetail Golf Club'),
  ('United States', 'Whitetail Golf Course'),
  ('United States', 'Whitetail Golf Resort'),
  ('United States', 'Whitetail Ridge Golf Course'),
  ('United States', 'Whitetail Run Golf Course'),
  ('United States', 'Whitewater Creek Country Club'),
  ('United States', 'Whitford Country Club'),
  ('United States', 'Whitinsville Golf Club'),
  ('United States', 'Whitmire Country Club'),
  ('United States', 'Whitmoor Country Club - North Course'),
  ('United States', 'Whitnall Park Golf Course'),
  ('United States', 'Whitney Oaks Golf Club'),
  ('United States', 'Whittaker Woods Golf Club'),
  ('United States', 'Whittier Mobile Country Club'),
  ('United States', 'Whittier Narrows Golf Course Mountain Course'),
  ('United States', 'Whittier Narrows Golf Course Mountain River'),
  ('United States', 'Whittier Narrows Golf Course Pine Mountain'),
  ('United States', 'Whittier Narrows Golf Course River Pine'),
  ('United States', 'Wianno Club'),
  ('United States', 'Wichita Country Club'),
  ('United States', 'Wichita County Municipal Golf Course'),
  ('United States', 'Wickenburg Country Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club Lil Wick'),
  ('United States', 'Wicker Hills Golf Club'),
  ('United States', 'Wicker Memorial Park Golf Course'),
  ('United States', 'Wicomico Shores Golf Course'),
  ('United States', 'Widows Walk Golf Course'),
  ('United States', 'Wigwam Resort Blue Course'),
  ('United States', 'Wigwam Resort Gold Course'),
  ('United States', 'Wigwam Resort Red Course'),
  ('United States', 'Wilcox Cove Cottages Golf'),
  ('United States', 'Wilcox Oaks Golf Club'),
  ('United States', 'Wild Bluff Golf Course'),
  ('United States', 'Wild Horse Plains Golf Course'),
  ('United States', 'Wild Marsh Golf Club'),
  ('United States', 'Wild Oak Golf Club'),
  ('United States', 'Wild Oaks Golf Course White Cedar Pin Oaks'),
  ('United States', 'Wild Oaks Golf Course White Cedar Willow Oaks'),
  ('United States', 'Wild Oaks Golf Course Willow Oaks Pin Oaks'),
  ('United States', 'Wild Quail Golf Country Club'),
  ('United States', 'Wild Ridge Golf Course'),
  ('United States', 'Wild Rock Golf Club at The Wilderness'),
  ('United States', 'Wild Turkey Golf Club'),
  ('United States', 'Wild Wing Plantation Avocet Course'),
  ('United States', 'Wild Wing Plantation Hummingbird Course'),
  ('United States', 'Wild Wings Golf Club'),
  ('United States', 'Wild Wood Country Club'),
  ('United States', 'Wildcat At Fort Jackson Golf Club'),
  ('United States', 'Wildcat Cliffs Country Club'),
  ('United States', 'Wildcat Creek Golf Course'),
  ('United States', 'Wildcat Crossing Golf Club'),
  ('United States', 'Wildcat Golf Course'),
  ('United States', 'Wildcat Run Country Club'),
  ('United States', 'Wildcreek Executive Golf Course'),
  ('United States', 'Wilderness Club'),
  ('United States', 'Wilderness Country Club'),
  ('United States', 'Wilderness Golf Course'),
  ('United States', 'Wilderness Valley'),
  ('United States', 'Wildfire Golf Club'),
  ('United States', 'Wildflower GC'),
  ('United States', 'Wildhawk Golf Club'),
  ('United States', 'Wildhorse Golf Club'),
  ('United States', 'Wildhorse Golf Course'),
  ('United States', 'Wildhorse Resort Golf Course'),
  ('United States', 'Wildwood Country Club'),
  ('United States', 'Wildwood Golf Club'),
  ('United States', 'Wildwood Golf Course'),
  ('United States', 'Wildwood Golf and RV Resort'),
  ('United States', 'Wildwood Green Golf Course'),
  ('United States', 'Wildwood Lake Golf Course'),
  ('United States', 'Wildwood Marshes Golf Course'),
  ('United States', 'Wildwood Mobile Country Club'),
  ('United States', 'Wilkes Barre Golf Club'),
  ('United States', 'Wilkshire Golf Course'),
  ('United States', 'Willandale Golf Club'),
  ('United States', 'Willapa Harbor Golf Course'),
  ('United States', 'Willard Golf Club'),
  ('United States', 'Willbrook Plantation Golf Club'),
  ('United States', 'William F Larkin Golf Course At Colonial Terrace'),
  ('United States', 'William J Devine Franklin Park Golf Course'),
  ('United States', 'William Land Park Municipal Golf Course'),
  ('United States', 'William S. Sahm Park Golf Course'),
  ('United States', 'Williams Country Club'),
  ('United States', 'Williams Country Club Golf Course'),
  ('United States', 'Williams Nine At Meadow Park Golf Course'),
  ('United States', 'Williamsburg Golf Club'),
  ('United States', 'Williamsburg National Golf Club Jamestown Course'),
  ('United States', 'Williamsburg National Golf Club Yorktown Course'),
  ('United States', 'Williamsport Country Club'),
  ('United States', 'Willingers Golf Club'),
  ('United States', 'Willis Case Golf Course'),
  ('United States', 'Williston Country Club'),
  ('United States', 'Williston Golf Club'),
  ('United States', 'Willoughby Golf Club'),
  ('United States', 'Willow Bend Country Club'),
  ('United States', 'Willow Brook Golf Course'),
  ('United States', 'Willow Creek Country Club'),
  ('United States', 'Willow Creek Golf'),
  ('United States', 'Willow Creek Golf Club At Eagle Vail'),
  ('United States', 'Willow Creek Golf Country Club'),
  ('United States', 'Willow Creek Golf Course'),
  ('United States', 'Willow Creek Municiple Golf Course'),
  ('United States', 'Willow Crest Golf Club'),
  ('United States', 'Willow Hills Golf Center'),
  ('United States', 'Willow Hollow Golf Course'),
  ('United States', 'Willow Lake Golf Club'),
  ('United States', 'Willow Lakes Golf Club'),
  ('United States', 'Willow Lakes Golf Course'),
  ('United States', 'Willow Oak At Hunters Creek Plantation'),
  ('United States', 'Willow Oaks Country Club'),
  ('United States', 'Willow Pond Golf Course'),
  ('United States', 'Willow Ridge Golf & Country Club'),
  ('United States', 'Willow Ridge Golf Club'),
  ('United States', 'Willow Ridge Golf Course'),
  ('United States', 'Willow Run Country Club'),
  ('United States', 'Willow Run Golf Club'),
  ('United States', 'Willow Run Golf Course'),
  ('United States', 'Willow Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Willow Springs Country Club'),
  ('United States', 'Willow Springs Golf Course'),
  ('United States', 'Willow Springs Golf and Country Club'),
  ('United States', 'Willow Tree Golf Course'),
  ('United States', 'Willow Vale Golf Club'),
  ('United States', 'Willow Valley Golf Course'),
  ('United States', 'Willow Wood Golf Course'),
  ('United States', 'Willowbend Country Club Bay Nine'),
  ('United States', 'Willowbend Country Club Bend Nine'),
  ('United States', 'Willowbend Country Club Bog Nine'),
  ('United States', 'Willowbend Golf Club'),
  ('United States', 'Willowbrook Country Club'),
  ('United States', 'Willowbrook Executive Golf Course At Willowcreek Golf Course'),
  ('United States', 'Willowbrook Golf Club'),
  ('United States', 'Willowbrook Golf Course'),
  ('United States', 'Willowbrook Golf Course The North Course'),
  ('United States', 'Willowbrook Golf Course The South Course'),
  ('United States', 'Willowbrook Golf Course The West Course'),
  ('United States', 'Willowcreek Golf Course'),
  ('United States', 'Willowdale Golf Club'),
  ('United States', 'Willowdale Golf Course'),
  ('United States', 'Willowhill Golf Course'),
  ('United States', 'Willowick Golf Course'),
  ('United States', 'Willows At Willowcreek Golf Club'),
  ('United States', 'Willows Run Golf Club Coyote Creek Course'),
  ('United States', 'Willows Run Golf Club Discovery Trails'),
  ('United States', 'Willows Run Golf Club Eagles Talon Course'),
  ('United States', 'Willows Run Golf Club Heron Links Course'),
  ('United States', 'Willsboro Golf Club'),
  ('United States', 'Wilmette Golf Club'),
  ('United States', 'Wilmington Municipal Golf Course'),
  ('United States', 'Wilmington Municipal Golf Course The First Tee Of Greater Wilmington'),
  ('United States', 'Wilshire Country Club'),
  ('United States', 'Wilshire Golf Club'),
  ('United States', 'Wilson At Griffith Park Golf Courses'),
  ('United States', 'Wilson Country Club'),
  ('United States', 'Wilson Lake Country Club'),
  ('United States', 'Wilson Road Golf Course'),
  ('United States', 'Wilsons Willow Run Executive Golf Course'),
  ('United States', 'Wiltwyck Golf Club'),
  ('United States', 'Winchester Country Club'),
  ('United States', 'Wind Watch Golf Country Club'),
  ('United States', 'Windance Country Club'),
  ('United States', 'Windber Country Club'),
  ('United States', 'Windermere Golf Club'),
  ('United States', 'Windham Country Club'),
  ('United States', 'Windham Golf Course'),
  ('United States', 'Winding Branch Golf Course'),
  ('United States', 'Winding Brook Country Club'),
  ('United States', 'Winding Creek Golf Club'),
  ('United States', 'Winding Creek Golf Course'),
  ('United States', 'Winding Hills Golf Club'),
  ('United States', 'Winding Ridge Gold Cub'),
  ('United States', 'Winding River Golf Course'),
  ('United States', 'Windmill At Indian Springs Country Club'),
  ('United States', 'Windmill Golf Center'),
  ('United States', 'Windmill Hill Golf Course'),
  ('United States', 'Windmill Lakes Golf Club'),
  ('United States', 'Windsong Farm Golf Club'),
  ('United States', 'Windsor At Walhalla'),
  ('United States', 'Windsor Club The'),
  ('United States', 'Windsor Golf Club'),
  ('United States', 'Windsor Parke Golf Club'),
  ('United States', 'Windstar On Naples Bay'),
  ('United States', 'Windstone Golf Country Club'),
  ('United States', 'Windswept Dunes Golf Course'),
  ('United States', 'Windwood Hollow Golf Course'),
  ('United States', 'Windwood of Watertown'),
  ('United States', 'Windy Acres Golf Course'),
  ('United States', 'Windy Harbor Golf Club'),
  ('United States', 'Windy Hill Country Club'),
  ('United States', 'Windy Hills Golf Course'),
  ('United States', 'Windy Knoll Golf Club'),
  ('United States', 'Windy Trails Golf Course At Altus Afb'),
  ('United States', 'Wine Valley Golf Course'),
  ('United States', 'Winfield Country Club'),
  ('United States', 'Wing Park Golf Course'),
  ('United States', 'Wing Point Golf Country Club'),
  ('United States', 'WingHaven Country Club'),
  ('United States', 'Winkler County Golf Course'),
  ('United States', 'Winkler Golf Club'),
  ('United States', 'Winn Mountain Golf Course'),
  ('United States', 'Winnapaug Country Club'),
  ('United States', 'Winnemucca Municipal Golf Course'),
  ('United States', 'Winnetka Golf Club'),
  ('United States', 'Winnfield Golf'),
  ('United States', 'Winona Country Club'),
  ('United States', 'Winstar Golf Course Redbud'),
  ('United States', 'Winstar Golf Course Scissortail'),
  ('United States', 'Winston Lake Golf Course'),
  ('United States', 'Winston Trails Golf Club'),
  ('United States', 'Winter Clove Inn Resort'),
  ('United States', 'Winter Creek Golf Country Club'),
  ('United States', 'Winter Park Golf Course'),
  ('United States', 'Winter Park Pines Golf Club'),
  ('United States', 'Winter Quarters Municipal Golf Course'),
  ('United States', 'Wintergreen Resort Devils Knob'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Shamokin'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Tuckahoe'),
  ('United States', 'Wintergreen Resort Stoney Creek Shamokin Tuckahoe'),
  ('United States', 'Winthrop Golf Club'),
  ('United States', 'Winthrop University Golf Course'),
  ('United States', 'Winton Country Club'),
  ('United States', 'Wintonbury Hills Golf Course'),
  ('United States', 'Wisconsin Club'),
  ('United States', 'Wisconsin River Country Club'),
  ('United States', 'Wissahickon Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Witch Golf Club'),
  ('United States', 'Woburn Country Club'),
  ('United States', 'Wohali Country Club Eagle Course'),
  ('United States', 'Wolf At Las Vegas Paiute Golf Resort'),
  ('United States', 'Wolf Creek Golf Club'),
  ('United States', 'Wolf Creek Golf Country Club'),
  ('United States', 'Wolf Creek Golf Course'),
  ('United States', 'Wolf Creek Golf Resort'),
  ('United States', 'Wolf Hollow Golf Club'),
  ('United States', 'Wolf Hollow Golf Course At Copiah Lincoln College'),
  ('United States', 'Wolf Laurel Country Club'),
  ('United States', 'Wolf Ridge Golf Course'),
  ('United States', 'Wolf Run Golf Club'),
  ('United States', 'Wolf Run Golf Course'),
  ('United States', 'Wolfe Island Riverfront Golf Course'),
  ('United States', 'Wolferts Roost Golf Course'),
  ('United States', 'Wolfridge Golf Course'),
  ('United States', 'Wollaston Golf Club'),
  ('United States', 'Wolves Crossing Golf Course'),
  ('United States', 'Wood Creek Golf Links'),
  ('United States', 'Wood Ranch Golf Club'),
  ('United States', 'Wood River Golf Course'),
  ('United States', 'Wood Wind Golf Club'),
  ('United States', 'Woodberry Forest Golf Course'),
  ('United States', 'Woodbine At Mohawk Park Golf Course'),
  ('United States', 'Woodbine Bend Golf Course'),
  ('United States', 'Woodbridge Golf Links'),
  ('United States', 'Woodbrier Golf Course'),
  ('United States', 'Woodbury Golf Course'),
  ('United States', 'Woodcreek Golf Club'),
  ('United States', 'Woodcrest Country Club'),
  ('United States', 'Woodcrest Golf Club'),
  ('United States', 'Wooded View Golf Course'),
  ('United States', 'Woodfield Country Club'),
  ('United States', 'Woodfin Ridge Golf Club'),
  ('United States', 'Woodgate Pines Golf Club'),
  ('United States', 'Woodhaven Country Club'),
  ('United States', 'Woodhaven Golf Club'),
  ('United States', 'Woodhill Country Club'),
  ('United States', 'Woodlake Country Club'),
  ('United States', 'Woodlake Golf Club'),
  ('United States', 'Woodland Country Club'),
  ('United States', 'Woodland Golf Club'),
  ('United States', 'Woodland Golf Course'),
  ('United States', 'Woodland Hills Country Club'),
  ('United States', 'Woodland Hills Golf Club'),
  ('United States', 'Woodland Hills Golf Course'),
  ('United States', 'Woodland Lakeside At Blue Hill Golf Course'),
  ('United States', 'Woodland Ridge Golf Course'),
  ('United States', 'Woodlands Championship Golf Course'),
  ('United States', 'Woodlands Club'),
  ('United States', 'Woodlands Course'),
  ('United States', 'Woodlands Creekside At Traces Golf Club The'),
  ('United States', 'Woodlands Golf Course'),
  ('United States', 'Woodlands Meadows At Traces Golf Club The'),
  ('United States', 'Woodlawn Country Club'),
  ('United States', 'Woodlawn Golf Club'),
  ('United States', 'Woodley Lakes Golf Course'),
  ('United States', 'Woodloch Springs Country Club'),
  ('United States', 'Woodlyn Hills Golf Course'),
  ('United States', 'Woodlynn Hills Golf Course'),
  ('United States', 'Woodmere Country Club'),
  ('United States', 'Woodmont Golf Country Club'),
  ('United States', 'Woodridge Golf Club'),
  ('United States', 'Woodruff Golf Course'),
  ('United States', 'Woods At Boca Woods Country Club'),
  ('United States', 'Woods Blue Grass At Old Westbury Golf Country Club'),
  ('United States', 'Woods Edge Golf Course')
on conflict (country, name) do nothing;