insert into public.golf_courses (country, name) values
  ('United States', 'Farwell Country Club'),
  ('United States', 'Fashion Golf Country Club'),
  ('United States', 'Faulkwood Shores Golf Club'),
  ('United States', 'Fauquier Springs Country Club'),
  ('United States', 'Fawn Creek Golf Course'),
  ('United States', 'Fawn Crest Golf Course'),
  ('United States', 'Fawn Lake Country Club'),
  ('United States', 'Fayetteville Country Club'),
  ('United States', 'Fazio Premier At Treetops Resort'),
  ('United States', 'Feather River Park Resort'),
  ('United States', 'Feather Sound Country Club'),
  ('United States', 'Fellows Creek Municipal Golf Club'),
  ('United States', 'Fendrich Golf Course'),
  ('United States', 'Fenner Hill Golf Club'),
  ('United States', 'Fennwood Hills Country Club'),
  ('United States', 'Fenton Farms Golf Club'),
  ('United States', 'Fenway Golf Club'),
  ('United States', 'Fenwick Golf Club'),
  ('United States', 'Fern Hill Golf Club'),
  ('United States', 'Ferndale Country Club'),
  ('United States', 'Fernwood Country Club'),
  ('United States', 'Fessenden Golf Club'),
  ('United States', 'Fianna Hills Country Club'),
  ('United States', 'Fiddlesticks Country Club Long Mean Course'),
  ('United States', 'Fiddlesticks Country Club Wee Friendly Course'),
  ('United States', 'Field Club of Omaha (north)'),
  ('United States', 'Field Club of Omaha (south)'),
  ('United States', 'Fields Ferry Golf Club'),
  ('United States', 'Fieldstone Golf Club'),
  ('United States', 'Fillmore Fairways Golf Course'),
  ('United States', 'Fillmore Golf Club'),
  ('United States', 'Fincastle On The Mountain Golf Course'),
  ('United States', 'Findlay Country Club'),
  ('United States', 'Finkbine Golf Course'),
  ('United States', 'Fircrest Golf Club'),
  ('United States', 'Fire Fox Resorts The Witch Golf Course'),
  ('United States', 'Fire Ridge Golf Club'),
  ('United States', 'Fire Ridge Golf Course'),
  ('United States', 'Firecliff At Desert Willow Golf Resort'),
  ('United States', 'Firefly Golf Course'),
  ('United States', 'Firefly Golf Links'),
  ('United States', 'Firekeeper Golf Course'),
  ('United States', 'Firelake Golf Course'),
  ('United States', 'Firerock Country Club'),
  ('United States', 'Firerock Country Club Littlerock Course'),
  ('United States', 'Firestone Country Club'),
  ('United States', 'Firethorn Golf Club'),
  ('United States', 'Firethorne Country Club'),
  ('United States', 'Fireweed Meadows Golf Course'),
  ('United States', 'First Nine At Edison Club The'),
  ('United States', 'First Nine At Montclair Golf Club'),
  ('United States', 'First Nine Second Nine At Bermuda Dunes Country Club'),
  ('United States', 'First Nine Second Nine At Cloverleaf Golf Club'),
  ('United States', 'First Nine Third Nine At Cloverleaf Golf Club'),
  ('United States', 'First Second At Lake Venice Golf Club'),
  ('United States', 'First Tee Northwest Arkansas'),
  ('United States', 'First Tee Of Augusta'),
  ('United States', 'First Tee Par 3 At Green Valley Ranch Golf Club'),
  ('United States', 'Fish Lake Country Club'),
  ('United States', 'Fisher Island Club'),
  ('United States', 'Fisher Park Golf Course'),
  ('United States', 'Fishermans Cove Golf Marina'),
  ('United States', 'Fishers Island Golf Country Club'),
  ('United States', 'Fishhook Golf Course'),
  ('United States', 'Fishkill Golf Course Driving Range'),
  ('United States', 'Five Flags Golf'),
  ('United States', 'Five Island Golf Course'),
  ('United States', 'Flagg Creek Golf Course'),
  ('United States', 'Flagstaff Ranch Golf Club'),
  ('United States', 'Flamingo Lakes Country Club'),
  ('United States', 'Flanders Valley Golf Club Red Gold Course'),
  ('United States', 'Flanders Valley Golf Club White Blue Course'),
  ('United States', 'Flatbush Golf Course'),
  ('United States', 'Flatirons Golf Course'),
  ('United States', 'Fleming County Golf Association'),
  ('United States', 'Fleming Island Golf Club'),
  ('United States', 'Fletchers Landing At Swingin Things'),
  ('United States', 'Flight Range'),
  ('United States', 'Flint Golf Club'),
  ('United States', 'Flint Hills Golf Course'),
  ('United States', 'Flint Hills National Golf Club'),
  ('United States', 'Flint River Golf Course'),
  ('United States', 'Florence Country Club'),
  ('United States', 'Florida Caverns Golf Course'),
  ('United States', 'Florida Keys Country Club'),
  ('United States', 'Florissant Golf Club'),
  ('United States', 'Flossmoor Country Club'),
  ('United States', 'Flourtown Country Club'),
  ('United States', 'Floyd Park Golf Course'),
  ('United States', 'Flushing Meadows Pitch Putt'),
  ('United States', 'Flushing Valley Golf Club'),
  ('United States', 'Flying "B" Golf Course'),
  ('United States', 'Flying Hills Golf Club'),
  ('United States', 'Flynn Centennial At Huntingdon Valley Country Club'),
  ('United States', 'Folkston Golf Club'),
  ('United States', 'Fon Du Lac Golf Course'),
  ('United States', 'Fonda Golf Course'),
  ('United States', 'Fontenelle Golf Course'),
  ('United States', 'Foothill Golf Course'),
  ('United States', 'Foothills Executive Golf Course'),
  ('United States', 'Foothills Golf Club'),
  ('United States', 'Foothills Golf Course Championship 18 Course'),
  ('United States', 'Foothills Golf Course Executive Course'),
  ('United States', 'Foothills Golf Course Par 3 Course'),
  ('United States', 'Foothills Par 3 Golf Course'),
  ('United States', 'Forbes Golf Course'),
  ('United States', 'Fords Colony Country Club Blackheath Course'),
  ('United States', 'Fords Colony Country Club Blue Heron Course'),
  ('United States', 'Fords Colony Country Club Marsh Hawk Course'),
  ('United States', 'Fordyce Country Club'),
  ('United States', 'Fore Honor Golf Course'),
  ('United States', 'Fore Kicks Golf Club'),
  ('United States', 'Fore U Golf Center'),
  ('United States', 'Fore Way Challenge Golf & Driving Range'),
  ('United States', 'Forebay Golf Course'),
  ('United States', 'Forest Akers East'),
  ('United States', 'Forest Akers West'),
  ('United States', 'Forest City Municipal Golf Course'),
  ('United States', 'Forest Country Club'),
  ('United States', 'Forest Course At Fiddlers Elbow Country Club'),
  ('United States', 'Forest Creek Golf Club North Course'),
  ('United States', 'Forest Creek Golf Club South Course'),
  ('United States', 'Forest Dale Golf Course'),
  ('United States', 'Forest Dunes Golf Resort'),
  ('United States', 'Forest E. Everhart Memorial Golf Course'),
  ('United States', 'Forest Glen Golf Country Club'),
  ('United States', 'Forest Greens Golf Club'),
  ('United States', 'Forest Heights Country Club'),
  ('United States', 'Forest Heights Golf Course'),
  ('United States', 'Forest Hill Field Club'),
  ('United States', 'Forest Hill Golf Course'),
  ('United States', 'Forest Hills'),
  ('United States', 'Forest Hills Country Club'),
  ('United States', 'Forest Hills Country Club Vue 791'),
  ('United States', 'Forest Hills Golf Club'),
  ('United States', 'Forest Hills Golf Course'),
  ('United States', 'Forest Lake At Stratton Mountain Country Club'),
  ('United States', 'Forest Lake Club'),
  ('United States', 'Forest Lake Country Club'),
  ('United States', 'Forest Lake Golf Club'),
  ('United States', 'Forest Lakes Golf Club At Abac'),
  ('United States', 'Forest Meadows Golf Course'),
  ('United States', 'Forest Oaks Country Club'),
  ('United States', 'Forest Oaks Golf Club'),
  ('United States', 'Forest Park Country Club'),
  ('United States', 'Forest Park Golf Course'),
  ('United States', 'Forest Point Golf Course'),
  ('United States', 'Forest View Golf Center'),
  ('United States', 'Forewinds Golf Course'),
  ('United States', 'Former Hara Greens'),
  ('United States', 'Forrest City Country Club'),
  ('United States', 'Forsgate Country Club The Banks'),
  ('United States', 'Forsgate Country Club The Palmer'),
  ('United States', 'Forsyth Country Club'),
  ('United States', 'Forsyth Golf Club'),
  ('United States', 'Fort Belvoir Golf Club Gunston Course'),
  ('United States', 'Fort Belvoir Golf Club Woodlawn Course'),
  ('United States', 'Fort Cherry Golf Club'),
  ('United States', 'Fort Collins Country Club'),
  ('United States', 'Fort Custer Golf Club'),
  ('United States', 'Fort Dodge Country Club'),
  ('United States', 'Fort Erie Golf Club'),
  ('United States', 'Fort Hays Municipal Golf Course'),
  ('United States', 'Fort Kent Golf Club'),
  ('United States', 'Fort Lauderdale Country Club North Course'),
  ('United States', 'Fort Lauderdale Country Club South Course'),
  ('United States', 'Fort Mill Golf Club'),
  ('United States', 'Fort Mitchell Country Club Golf Course'),
  ('United States', 'Fort Moore Golf Course Bradley Nine'),
  ('United States', 'Fort Moore Golf Course Marshall Nine'),
  ('United States', 'Fort Myers Country Club'),
  ('United States', 'Fort Sill Golf Club'),
  ('United States', 'Fort Smith Country Club'),
  ('United States', 'Fort Snelling Golf Course'),
  ('United States', 'Fort Washington Golf Country Club'),
  ('United States', 'Fortuna Delrey Golf Course'),
  ('United States', 'Forty Niner Country Club'),
  ('United States', 'Foss Park Golf Course'),
  ('United States', 'Fossil Island Golf Club'),
  ('United States', 'Fossil Trace Golf Club'),
  ('United States', 'Fosston Golf Club'),
  ('United States', 'Foster Country Club'),
  ('United States', 'Foster Golf Links'),
  ('United States', 'Foster Gulch Golf Course'),
  ('United States', 'Foster Park Golf Course'),
  ('United States', 'Fostoria Country Club'),
  ('United States', 'Founders At Penn National Golf Club Inn'),
  ('United States', 'Founders Club At St James Plantation'),
  ('United States', 'Founders Club Of Pawleys Island'),
  ('United States', 'Foundry Golf Club'),
  ('United States', 'Fountain Green Golf Course'),
  ('United States', 'Fountain Head Country Club'),
  ('United States', 'Fountain Hills Golf Club'),
  ('United States', 'Fountain Lakes Golf Course'),
  ('United States', 'Fountain Of The Sun Country Club'),
  ('United States', 'Fountain Springs Golf Course'),
  ('United States', 'Fountain Valley Golf Course'),
  ('United States', 'Fountainhead Creek Golf Club'),
  ('United States', 'Fountains Golf & Banquet'),
  ('United States', 'Four Bridges Country Club'),
  ('United States', 'Four Lakes Country Club'),
  ('United States', 'Four Lakes Golf Club'),
  ('United States', 'Four Mile Ranch Golf Club'),
  ('United States', 'Four Oaks Golf Course'),
  ('United States', 'Four Peaks Course At Sunland Springs Village'),
  ('United States', 'Four Seasons Country Club'),
  ('United States', 'Four Seasons Golf Club'),
  ('United States', 'Four Seasons Golf Course'),
  ('United States', 'Four Seasons Ranch Golf Course'),
  ('United States', 'Four Seasons Spa Country Club'),
  ('United States', 'Four Streams Golf Club'),
  ('United States', 'Four Willows Golf Course'),
  ('United States', 'Four Winds Golf Course'),
  ('United States', 'Fourth Nine At Montclair Golf Club'),
  ('United States', 'Fowler''s Mill Golf Course'),
  ('United States', 'Fox At Pittsburgh North Golf Club'),
  ('United States', 'Fox Bend Golf Course'),
  ('United States', 'Fox Chapel Golf Club'),
  ('United States', 'Fox Chase Golf Course At Carroll Farms'),
  ('United States', 'Fox Creek'),
  ('United States', 'Fox Creek Golf Club'),
  ('United States', 'Fox Creek Golf Course'),
  ('United States', 'Fox Den Golf Course'),
  ('United States', 'Fox Glen Golf Club'),
  ('United States', 'Fox Hill Country Club'),
  ('United States', 'Fox Hill Golf And Country Club'),
  ('United States', 'Fox Hills Country Club'),
  ('United States', 'Fox Hollow Golf Club'),
  ('United States', 'Fox Hollow Golf Course'),
  ('United States', 'Fox Hopyard Golf Club'),
  ('United States', 'Fox Lake Country Club'),
  ('United States', 'Fox Lake Golf Club'),
  ('United States', 'Fox Lake Golf Course'),
  ('United States', 'Fox Meadow Golf Course'),
  ('United States', 'Fox Prairie Golf Course'),
  ('United States', 'Fox Ridge'),
  ('United States', 'Fox Ridge Golf Club'),
  ('United States', 'Fox Ridge Golf Course'),
  ('United States', 'Fox River Resort'),
  ('United States', 'Fox Run Country Club'),
  ('United States', 'Fox Run Course At Glenview Champions Country Club'),
  ('United States', 'Fox Run Driving Range'),
  ('United States', 'Fox Run Golf Club'),
  ('United States', 'Fox Run Golf Course'),
  ('United States', 'Fox Run Golf Links'),
  ('United States', 'Fox Valley Golf Course'),
  ('United States', 'Fox Woods Golf Course'),
  ('United States', 'FoxCreek Golf & Racquet Club'),
  ('United States', 'Foxboro Golf Club'),
  ('United States', 'Foxborough Country Club'),
  ('United States', 'Foxburg Country Club'),
  ('United States', 'Foxchase Golf Club'),
  ('United States', 'Foxcliff Golf Club'),
  ('United States', 'Foxcroft Golf Club'),
  ('United States', 'Foxfire At Village Green'),
  ('United States', 'Foxfire Golf Club'),
  ('United States', 'Foxfire Resort Golf Club Grey Fox Course'),
  ('United States', 'Foxfire Resort Golf Club Red Fox Course'),
  ('United States', 'Foxford Hills Golf Course'),
  ('United States', 'Foxglove Pinecone At Resort At The Mountain The'),
  ('United States', 'Foxtail Golf Club North Course'),
  ('United States', 'Foxtail Golf Club South Course'),
  ('United States', 'Foxwood Country Club'),
  ('United States', 'Foxwood Hills Country Club'),
  ('United States', 'Framingham Country Club'),
  ('United States', 'Francis Byrne Golf Course'),
  ('United States', 'Francis Gross Golf Course'),
  ('United States', 'Francis Lake Golf Club'),
  ('United States', 'Francisco Grande Resort Golf Club'),
  ('United States', 'Franconia Golf Course'),
  ('United States', 'Frank E Peters Municipal Golf Course'),
  ('United States', 'Frank Skul Memorial Golf Course'),
  ('United States', 'Franklin Canyon Golf Course'),
  ('United States', 'Franklin Country Club'),
  ('United States', 'Franklin County Country Club'),
  ('United States', 'Franklin Golf Club'),
  ('United States', 'Franklin Golf Course'),
  ('United States', 'Franklin Hills Country Club'),
  ('United States', 'Franklin Valley Golf Club'),
  ('United States', 'Franklinton Country Club'),
  ('United States', 'Frasch Park Golf Club'),
  ('United States', 'Fraser Edmundston Golf Club'),
  ('United States', 'Fraserglen Golf Course Training Centre'),
  ('United States', 'Fraternal Order Of Eagles Eagles Hills Golf Course'),
  ('United States', 'Frazee Golf Course'),
  ('United States', 'Frear Park Golf Course'),
  ('United States', 'Fred Enke Golf Course'),
  ('United States', 'Frederic Golf Course'),
  ('United States', 'Frederica Golf Club'),
  ('United States', 'Frederick Golf Country Club'),
  ('United States', 'Frederick Peak Golf Club'),
  ('United States', 'Fredericksburg Country Club'),
  ('United States', 'Fredonia Country Club'),
  ('United States', 'Freedom Fairways'),
  ('United States', 'Freeport Mills Golf Course'),
  ('United States', 'Fremont Country Club'),
  ('United States', 'Fremont County Golf Course'),
  ('United States', 'Fremont County Recreation Area'),
  ('United States', 'Fremont Golf Club'),
  ('United States', 'Fremont Park Golf Course'),
  ('United States', 'French Camp Golf Course'),
  ('United States', 'French Creek Golf Course'),
  ('United States', 'French Oaks Golf Club'),
  ('United States', 'French Woods Golf Course'),
  ('United States', 'Frenchmans Bend Golf Country Club'),
  ('United States', 'Frenchmans Reserve Golf Course'),
  ('United States', 'Frenchs Hollow Fairways Golf Course'),
  ('United States', 'Fresh Meadow Country Club'),
  ('United States', 'Fresh Meadow Golf Club'),
  ('United States', 'Fresh Pond Golf Course'),
  ('United States', 'Friars Head Golf Course'),
  ('United States', 'Friars Presidio At Riverwalk Golf Club'),
  ('United States', 'Friendly Hills Country Club'),
  ('United States', 'Friendly Meadows Golf Course'),
  ('United States', 'Friendly Valley Golf Course'),
  ('United States', 'Frog Hollow Golf Club'),
  ('United States', 'Frog Rock Country Club'),
  ('United States', 'Front Back At Metedeconk National Golf Club'),
  ('United States', 'Front Back At Rolling Green Golf Club'),
  ('United States', 'Front Eighteen At Black Hawk Golf Course'),
  ('United States', 'Front Middle At Rolling Green Golf Club'),
  ('United States', 'Front Nine Back Nine At Southern Hills Country Club'),
  ('United States', 'Front Royal Golf Club'),
  ('United States', 'Front Third At Metedeconk National Golf Club'),
  ('United States', 'Frontier Road House Golf Course'),
  ('United States', 'Frost Creek'),
  ('United States', 'Frosty Valley Country Club'),
  ('United States', 'Frosty Valley Golf Links'),
  ('United States', 'Fruitport Golf Club'),
  ('United States', 'Frye Island Golf Course'),
  ('United States', 'Ft Cobb Golf Course'),
  ('United States', 'Fulda Town and Country Golf'),
  ('United States', 'Full Cry At Keswick Hall And Golf Club'),
  ('United States', 'Fuller''s Fairways'),
  ('United States', 'Fullerton Golf Course'),
  ('United States', 'Fulton Country Club'),
  ('United States', 'Furman University Golf Course'),
  ('United States', 'Furnace Bay Golf Course'),
  ('United States', 'Furnace Brook Golf Club'),
  ('United States', 'Furnace Creek Golf Course'),
  ('United States', 'Fyre Lake Golf Club'),
  ('United States', 'GLC Links'),
  ('United States', 'Gaffney Country Club'),
  ('United States', 'Gahanna Municipal Golf Course'),
  ('United States', 'Gaillardia Country Club'),
  ('United States', 'Gainesville Country Club'),
  ('United States', 'Gainesville Municipal Golf Course'),
  ('United States', 'Gainfield Farms Golf Course'),
  ('United States', 'Galax Municipal Golf Course'),
  ('United States', 'Galen Hall Golf Club'),
  ('United States', 'Galena Golf Club'),
  ('United States', 'Galena Ridge At Silver Mountain Resort'),
  ('United States', 'Galion Country Club'),
  ('United States', 'Galla Creek Golf Course'),
  ('United States', 'Galleon Brigantine At Shipyard Golf Club'),
  ('United States', 'Gallery Golf Club North Golf Course'),
  ('United States', 'Gallery Golf Club South Golf Course'),
  ('United States', 'Gallery Golf Course'),
  ('United States', 'Galloping Hill Golf Course'),
  ('United States', 'Galloping Hill Golf Course Learning Center 9'),
  ('United States', 'Galloway National Golf Club'),
  ('United States', 'Galway Golf Course'),
  ('United States', 'Gamble Sands Golf Club Cascade Putting Course'),
  ('United States', 'Gamble Sands Golf Club Quicksands Course'),
  ('United States', 'Gamble Sands Golf Club Scarecrow Course'),
  ('United States', 'Gamble Sands Golf Club The Sands Course'),
  ('United States', 'Gambler Ridge Golf Club'),
  ('United States', 'Gananoque Golf And Country Club'),
  ('United States', 'Ganienkeh Golf Course'),
  ('United States', 'Garden City Country Club'),
  ('United States', 'Garden City Golf Club'),
  ('United States', 'Garden Golf Club'),
  ('United States', 'Garden Of The Gods Club North Course'),
  ('United States', 'Garden Of The Gods Club South Course'),
  ('United States', 'Garden Of The Gods Club West Course'),
  ('United States', 'Garden Park'),
  ('United States', 'Gardiners Bay Country Club'),
  ('United States', 'Gardner Golf Course'),
  ('United States', 'Gardner Municipal Golf Course'),
  ('United States', 'Garland Lodge & Resort'),
  ('United States', 'Garner Country Club'),
  ('United States', 'Garner Golf and Country Club'),
  ('United States', 'Garnett Country Club'),
  ('United States', 'Garrison Golf Club'),
  ('United States', 'Garrisons Lake Golf Club'),
  ('United States', 'Gasparilla Inn Golf Course'),
  ('United States', 'Gaston Country Club'),
  ('United States', 'Gate City Golf Course'),
  ('United States', 'Gates Four Golf Country Club'),
  ('United States', 'Gates Park Golf Course'),
  ('United States', 'Gateway Cities Golf Club'),
  ('United States', 'Gateway Golf Course'),
  ('United States', 'Gateway Lodge Golf Course'),
  ('United States', 'Gateway National Golf Links'),
  ('United States', 'Gateway Recreation Golf Course'),
  ('United States', 'Gator Creek Golf Course'),
  ('United States', 'Gator Lakes Golf Course'),
  ('United States', 'Gator Trace Golf Country Club'),
  ('United States', 'Gauss'' Green Valley Golf Course'),
  ('United States', 'Gavilan Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Gay Brewer Jr Course At Picadome'),
  ('United States', 'Gaylord Country Club'),
  ('United States', 'Gearhart Golf Links'),
  ('United States', 'Gem Lake Hills Golf Course'),
  ('United States', 'Gene Torres Golf Course At Highlands University'),
  ('United States', 'Genegantslet Golf Club'),
  ('United States', 'General Burnside State Park'),
  ('United States', 'General Electric Athletic Club'),
  ('United States', 'General George V Underwood Jr Golf Complex Sunrise Course'),
  ('United States', 'General George V Underwood Jr Golf Complex Sunset Course'),
  ('United States', 'General James Hackler Golf Course At Coastal Carolina University'),
  ('United States', 'General Old Golf Course'),
  ('United States', 'Generations Golf Course'),
  ('United States', 'Genesee Valley Golf Course North'),
  ('United States', 'Genesee Valley Golf Course South'),
  ('United States', 'Genesee Valley Meadows Golf Course'),
  ('United States', 'Geneseo Golf Course'),
  ('United States', 'Geneva Country Club'),
  ('United States', 'Geneva Farm Golf Course'),
  ('United States', 'Geneva Golf Club'),
  ('United States', 'Geneva Golf and Country Club'),
  ('United States', 'Geneva on-the Lake Village Golf Course'),
  ('United States', 'Gentz''s Homestead Golf Course'),
  ('United States', 'George W. Dunne National Driving Range'),
  ('United States', 'George W. Dunne National Golf Course'),
  ('United States', 'George Wright Golf Course'),
  ('United States', 'George Young Golf Course'),
  ('United States', 'George Young Recreation'),
  ('United States', 'Georgetown Country Club'),
  ('United States', 'Georgia National Golf Club'),
  ('United States', 'Georgia Southern University Golf Course'),
  ('United States', 'Georgia Veterans Memorial Golf Course At Lake Blackshear Resort Golf Club'),
  ('United States', 'Germantown Country Club'),
  ('United States', 'Germany Hill Golf Course'),
  ('United States', 'Geronimo Course At Desert Mountain Golf Club'),
  ('United States', 'Gettysburg National Golf Club'),
  ('United States', 'Giant Oak Golf Club'),
  ('United States', 'Gibson Woods Golf Course'),
  ('United States', 'Gig Harbor Golf Country Club'),
  ('United States', 'Gil Morgan Golf Course'),
  ('United States', 'Gilbert Greens Country Club'),
  ('United States', 'Giles Country Club'),
  ('United States', 'Gillespie Country Club'),
  ('United States', 'Gillespie Golf Club'),
  ('United States', 'Gillette Golf Club'),
  ('United States', 'Gillette Ridge'),
  ('United States', 'Gilroy Golf Course'),
  ('United States', 'Glacier Club Golf Course'),
  ('United States', 'Glacier Club Mountain Course'),
  ('United States', 'Glacier Club Valley Course'),
  ('United States', 'Glacier Park Golf Club'),
  ('United States', 'Glacier View Golf Club'),
  ('United States', 'Glades At Colony West Country Club'),
  ('United States', 'Gladstan Golf Course'),
  ('United States', 'Gladstone Golf Club'),
  ('United States', 'Gladwin Heights Golf Course'),
  ('United States', 'Glasco Golf Club'),
  ('United States', 'Glass Hill Golf Club'),
  ('United States', 'Glastonbury Hills Country Club'),
  ('United States', 'Glen Abbey Golf Club'),
  ('United States', 'Glen Acres Golf Country Club'),
  ('United States', 'Glen Annie Golf Club'),
  ('United States', 'Glen Arven Country Club'),
  ('United States', 'Glen Brook Country Club'),
  ('United States', 'Glen Cove Golf Club'),
  ('United States', 'Glen Dornoch Waterway Golf Links'),
  ('United States', 'Glen Eagle Golf Club'),
  ('United States', 'Glen Eagle Golf Country Club'),
  ('United States', 'Glen Eagle Golf Course'),
  ('United States', 'Glen Echo Country Club'),
  ('United States', 'Glen Ellen Country Club'),
  ('United States', 'Glen Ellyn Village Links Golf Course'),
  ('United States', 'Glen Erin Golf Club'),
  ('United States', 'Glen Flora Country Club'),
  ('United States', 'Glen Head Country Club'),
  ('United States', 'Glen Hills Golf Club'),
  ('United States', 'Glen Ivy Golf Club'),
  ('United States', 'Glen Kernan Club'),
  ('United States', 'Glen Lake Golf & Practice Center'),
  ('United States', 'Glen Mills Golf Course'),
  ('United States', 'Glen Oak Country Club'),
  ('United States', 'Glen Oak Golf Club'),
  ('United States', 'Glen Oaks Country Club'),
  ('United States', 'Glen Oaks Golf Club'),
  ('United States', 'Glen Oaks Golf Course'),
  ('United States', 'Glen Oaks Golf Racquet Club'),
  ('United States', 'Glen Ridge Country Club'),
  ('United States', 'Glen View Club'),
  ('United States', 'Glenarbor Golf Club'),
  ('United States', 'Glenbrier Golf Course'),
  ('United States', 'Glenbrook Golf Course'),
  ('United States', 'Glencoe Country Club'),
  ('United States', 'Glencoe Golf Club'),
  ('United States', 'Glendale Country Club'),
  ('United States', 'Glendale Golf Course'),
  ('United States', 'Glendale Lakes Golf Course'),
  ('United States', 'Glendarin Hills Golf Club'),
  ('United States', 'Glendora Country Club'),
  ('United States', 'Gleneagle Golf Course'),
  ('United States', 'Gleneagles Country Club Legends Course'),
  ('United States', 'Gleneagles Country Club Victory Course'),
  ('United States', 'Gleneagles Golf Club'),
  ('United States', 'Gleneagles Golf Course At Mclaren Park'),
  ('United States', 'Gleneagles Turnberry At Waterford Golf Club'),
  ('United States', 'Glengarry Golf Links'),
  ('United States', 'Glenhardie Country Club'),
  ('United States', 'Glenhurst Golf Course'),
  ('United States', 'Glenkerry Golf Course'),
  ('United States', 'Glenlakes Country Club'),
  ('United States', 'Glenlakes Golf Club Lakes Course'),
  ('United States', 'Glenlakes Golf Club Vista Dunes Course'),
  ('United States', 'Glenlore Golf Course'),
  ('United States', 'Glenmary Country Club'),
  ('United States', 'Glenmaura National Golf Course'),
  ('United States', 'Glenmoor Country Club'),
  ('United States', 'Glenmoor Golf Course'),
  ('United States', 'Glenmore Country Club'),
  ('United States', 'Glenn Golf Country Club'),
  ('United States', 'Glenriddle Golf Club Man O War Course'),
  ('United States', 'Glenrochie Country Club'),
  ('United States', 'Glenrock Golf Course'),
  ('United States', 'Glenross Golf Club'),
  ('United States', 'Glens Falls Country Club'),
  ('United States', 'Glenview Golf Course'),
  ('United States', 'Glenview Park Golf Club'),
  ('United States', 'Glenview Prairie Club'),
  ('United States', 'Glenville Golf Club'),
  ('United States', 'Glenwild Golf Club And Spa'),
  ('United States', 'Glenwild Greens Golf Course'),
  ('United States', 'Glenwood Country Club'),
  ('United States', 'Glenwood Golf Course'),
  ('United States', 'Glenwood Springs Golf Club'),
  ('United States', 'Glenwoodie Golf Club'),
  ('United States', 'Glocester Country Club'),
  ('United States', 'Gloucester Country Club'),
  ('United States', 'Glynlea Country Club'),
  ('United States', 'Glynns Creek Golf Course'),
  ('United States', 'Goat Hill Park'),
  ('United States', 'Goddard State Memorial Park'),
  ('United States', 'Godwin Creek Golf Course'),
  ('United States', 'Gof Mohr Golf Course'),
  ('United States', 'Gogebic Country Club'),
  ('United States', 'Gold At Cedarbrook Golf Course'),
  ('United States', 'Gold At Congressional Country Club'),
  ('United States', 'Gold At Golden Horseshoe Golf Club The'),
  ('United States', 'Gold At Paradise Point Golf Course'),
  ('United States', 'Gold At Treasure Lake Golf Course'),
  ('United States', 'Gold Blue At Valley Brook Country Club'),
  ('United States', 'Gold Canyon Rv Golf Resort'),
  ('United States', 'Gold Green At Wyndemere Country Club'),
  ('United States', 'Gold Hills Golf Club'),
  ('United States', 'Gold Hills Golf Course'),
  ('United States', 'Gold Red At Lindenwood Golf Club'),
  ('United States', 'Gold Red At Westchester Golf Country Club'),
  ('United States', 'Gold White At Rothland Golf Course'),
  ('United States', 'Golden Bear Golf Club At Indigo Run'),
  ('United States', 'Golden Eagle Country Club'),
  ('United States', 'Golden Eagle Golf Club'),
  ('United States', 'Golden Eagle Golf Club At Tides Inn Resort'),
  ('United States', 'Golden Era Golf Course'),
  ('United States', 'Golden Gate Park Golf Course'),
  ('United States', 'Golden Hawk Golf Club'),
  ('United States', 'Golden Hills Country Club'),
  ('United States', 'Golden Hills Golf Club'),
  ('United States', 'Golden Lakes Golf Course'),
  ('United States', 'Golden Locket Golf Course'),
  ('United States', 'Golden Marsh At Harbour Ridge Yacht Country Club'),
  ('United States', 'Golden Oak Golf Club'),
  ('United States', 'Golden Oaks Golf Club'),
  ('United States', 'Golden Oaks Village Green Golf'),
  ('United States', 'Golden Ocala Golf Equestrian Club'),
  ('United States', 'Golden Pheasant Golf Club'),
  ('United States', 'Golden Plains At Akron Golf Course'),
  ('United States', 'Golden Sands Golf Community'),
  ('United States', 'Golden Sands Golf Course'),
  ('United States', 'Golden Valley Country Club'),
  ('United States', 'Goldendale Golf Club'),
  ('United States', 'Goldeneye Club'),
  ('United States', 'Goldsboro Municipal Golf Course'),
  ('United States', 'Goldside Golf Course'),
  ('United States', 'Golf Academy Of Delaware Vandegift Course'),
  ('United States', 'Golf Academy at Terra Cotta'),
  ('United States', 'Golf At Province Lake'),
  ('United States', 'Golf Center Des Plaines'),
  ('United States', 'Golf Club At Boulder Ridge'),
  ('United States', 'Golf Club At Cuscowilla'),
  ('United States', 'Golf Club At Fox Acres'),
  ('United States', 'Golf Club At Heather Ridge'),
  ('United States', 'Golf Club At Mansion Ridge'),
  ('United States', 'Golf Club At South Hampton'),
  ('United States', 'Golf Club At Stonebridge'),
  ('United States', 'Golf Club At Terra Lago North Course'),
  ('United States', 'Golf Club At Terra Lago South Course'),
  ('United States', 'Golf Club At Valley View'),
  ('United States', 'Golf Club At Wescott Plantation Black Robin Course'),
  ('United States', 'Golf Club At Wescott Plantation Burn Kill Course'),
  ('United States', 'Golf Club At Wescott Plantation Oak Forest Course'),
  ('United States', 'Golf Club Of Amelia Island At Summer Beach The'),
  ('United States', 'Golf Club Of Estrella'),
  ('United States', 'Golf Club Of Newport The'),
  ('United States', 'Golf Club Of South Georgia'),
  ('United States', 'Golf Club Of St Saint Joseph The'),
  ('United States', 'Golf Club Of The Everglades'),
  ('United States', 'Golf Club of Dublin'),
  ('United States', 'Golf Club of Illinois'),
  ('United States', 'Golf Club of Incline Village'),
  ('United States', 'Golf Club of Indiana'),
  ('United States', 'Golf Club of Wentzville'),
  ('United States', 'Golf Club of West Virginia'),
  ('United States', 'Golf Course At Bolduc Park The'),
  ('United States', 'Golf Course On Turkey Mountain'),
  ('United States', 'Golf Courses of Lawsonia'),
  ('United States', 'Golf Driving Range'),
  ('United States', 'Golf Du Moulin Laflamme'),
  ('United States', 'Golf Granby Ranch'),
  ('United States', 'Golf Hammock Country Club'),
  ('United States', 'Golf Headquarters Golfplex'),
  ('United States', 'Golf Hemmingford Frontier'),
  ('United States', 'Golf Hemmingford Village'),
  ('United States', 'Golf Learning Center'),
  ('United States', 'Golf North Hills'),
  ('United States', 'Golf Summerlin Eagle Crest Course'),
  ('United States', 'Golf Summerlin Highland Falls Course'),
  ('United States', 'Golf Summerlin Palm Valley Course'),
  ('United States', 'Golf The Round'),
  ('United States', 'Golf at Indian Creek'),
  ('United States', 'Golf at Indian Creek - Blackbird Course'),
  ('United States', 'Golf at Indian Creek - Gray Hawk Course'),
  ('United States', 'Golf at Indian Creek - Red Feather Course'),
  ('United States', 'Golfview Golf Recreation'),
  ('United States', 'Gooding Golf Course'),
  ('United States', 'Goodpark Golf Course'),
  ('United States', 'Goodrich Country Club'),
  ('United States', 'Goodrich Golf Course'),
  ('United States', 'Goodwin At Goodwin Golf Course'),
  ('United States', 'Goodyear Golf Club'),
  ('United States', 'Goose Creek Golf Club'),
  ('United States', 'Goose River Golf Club'),
  ('United States', 'Goose Run Golf Course At Naval Submarine Base'),
  ('United States', 'Gordon Pines Golf Course'),
  ('United States', 'Gordon Trent Golf Course'),
  ('United States', 'Gorge Vale Golf Club'),
  ('United States', 'Gorham Country Club'),
  ('United States', 'Goshen Golf Club'),
  ('United States', 'Gothic Hill Golf Course'),
  ('United States', 'Gouverneur Country Club'),
  ('United States', 'Governors Club Foothills Course'),
  ('United States', 'Governors Club Lakes Course'),
  ('United States', 'Governors Club Mountain Course'),
  ('United States', 'Governors Run Golf Club'),
  ('United States', 'Governors Run Golf Course'),
  ('United States', 'Governors Towne Club'),
  ('United States', 'Gowanda Country Club'),
  ('United States', 'Gowanie Country Club'),
  ('United States', 'Gowrie Municipal Golf Course'),
  ('United States', 'Gozzer Ranch Golf Lake Club'),
  ('United States', 'Grace At Saucon Valley Country Club'),
  ('United States', 'Graceville Golf Club'),
  ('United States', 'Gracewil Country Club'),
  ('United States', 'Graeagle Meadows Golf Course'),
  ('United States', 'Granada Farms Country Club'),
  ('United States', 'Granada Golf Course'),
  ('United States', 'Grand Beach Golf Course'),
  ('United States', 'Grand Canyon University Golf Course'),
  ('United States', 'Grand Cherokee State Park Golf Course'),
  ('United States', 'Grand Cypress Golf Club Cypress Course'),
  ('United States', 'Grand Cypress Golf Club Links Course'),
  ('United States', 'Grand Elk Golf Course'),
  ('United States', 'Grand Forks Country Club'),
  ('United States', 'Grand Geneva Golf Resort'),
  ('United States', 'Grand Haven Golf Club'),
  ('United States', 'Grand Lake Golf Course'),
  ('United States', 'Grand Lake Rv And Golf Resort'),
  ('United States', 'Grand Ledge Country Club'),
  ('United States', 'Grand National Golf Course'),
  ('United States', 'Grand Prairie Country Club'),
  ('United States', 'Grand Prarie Golf Course'),
  ('United States', 'Grand Reserve Golf Club'),
  ('United States', 'Grand Ridge Golf Club'),
  ('United States', 'Grand Royal At Grand Palms Golf Country Club'),
  ('United States', 'Grand View Golf Club'),
  ('United States', 'Grand View Golf Course'),
  ('United States', 'Grand View Lodge The Garden'),
  ('United States', 'Grand Vue Park Golf Course'),
  ('United States', 'Grande Dunes Members Club'),
  ('United States', 'Grande Dunes Resort Club'),
  ('United States', 'Grande Golf Club'),
  ('United States', 'Grande Oaks Golf Club'),
  ('United States', 'Grande Oaks Golf Club Par 3'),
  ('United States', 'Grande Vista Golf Club'),
  ('United States', 'Grandfather At Grandfather Golf Country Club'),
  ('United States', 'Grandote Peaks Golf Course'),
  ('United States', 'Grandpa''s Woods Golf Course'),
  ('United States', 'Grandpas Woods Golf'),
  ('United States', 'Grandview Country Club'),
  ('United States', 'Grandview Farms Golf Course'),
  ('United States', 'Grandview Golf Club'),
  ('United States', 'Grandview Golf Course'),
  ('United States', 'Grandview Golf Course At Sun City West'),
  ('United States', 'Grandy Nine Golf & Camp'),
  ('United States', 'Grangeville Country Club'),
  ('United States', 'Granite Bay Golf Club'),
  ('United States', 'Granite Fields Golf Club'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Granite Nine'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Milton Nine'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Quincy Nine'),
  ('United States', 'Granliden On Sunapee Golf Course'),
  ('United States', 'Grant Golf Club'),
  ('United States', 'Grant Park Golf Course'),
  ('United States', 'Grantsburg Golf Course'),
  ('United States', 'Grantwood Golf Course'),
  ('United States', 'Grape Ranch Golf Club'),
  ('United States', 'Grass Clippings At Rolling Hills'),
  ('United States', 'Grasslands Golf Country Club'),
  ('United States', 'Grassmere Country Club'),
  ('United States', 'Grassy Creek Golf Country Club'),
  ('United States', 'Grassy Hill Country Club'),
  ('United States', 'Grassy Lane Golf Club'),
  ('United States', 'Grave Yard Homestead At Flat Creek Golf Club'),
  ('United States', 'Gravel Pit'),
  ('United States', 'Gray Eagle Golf Club and Academy'),
  ('United States', 'Gray Plantation'),
  ('United States', 'Grayling Country Club'),
  ('United States', 'Grays Harbor Country Club'),
  ('United States', 'Great Bear Golf Club'),
  ('United States', 'Great Chebeague Golf Club'),
  ('United States', 'Great Cove Golf Course'),
  ('United States', 'Great Cove Golf Recreation'),
  ('United States', 'Great Eagle Golf Club'),
  ('United States', 'Great Gorge Golf Club Lake Quarry Course'),
  ('United States', 'Great Gorge Golf Club Quarry Rail Course'),
  ('United States', 'Great Gorge Golf Club Rail Lake Course'),
  ('United States', 'Great Hope Golf Course'),
  ('United States', 'Great Neck Country Club'),
  ('United States', 'Great Oaks Country Club'),
  ('United States', 'Great Outdoors Rv Golf Resort'),
  ('United States', 'Great River Golf Club'),
  ('United States', 'Great Rock Golf Club'),
  ('United States', 'Great Trail Golf Course'),
  ('United States', 'Greate Bay Golf Club'),
  ('United States', 'Greathorse Golf Course'),
  ('United States', 'Greatlife Golf Fitness Chisholm Trail'),
  ('United States', 'Greatlife Golf Fitness Lebanon'),
  ('United States', 'Greatlife Golf Fitness Salina'),
  ('United States', 'Greeley Country Club'),
  ('United States', 'Greeley County Golf Course'),
  ('United States', 'Green Acres Country Club'),
  ('United States', 'Green Acres Golf Club'),
  ('United States', 'Green Acres Golf Course'),
  ('United States', 'Green Acres Golf Recreation'),
  ('United States', 'Green At Bethpage State Park Golf Course'),
  ('United States', 'Green At Golden Horseshoe Golf Club The'),
  ('United States', 'Green At Tunxis Country Club'),
  ('United States', 'Green Bay Country Club'),
  ('United States', 'Green Brook Country Club'),
  ('United States', 'Green County Golf Association'),
  ('United States', 'Green Crest Golf Course'),
  ('United States', 'Green Gables Golf Course'),
  ('United States', 'Green Harbor Golf Club'),
  ('United States', 'Green Haven Golf Course'),
  ('United States', 'Green Hill Country Club'),
  ('United States', 'Green Hill Golf Club'),
  ('United States', 'Green Hill Golf Course'),
  ('United States', 'Green Hills Country Club'),
  ('United States', 'Green Hills Golf Course'),
  ('United States', 'Green Hills Municipal Golf Course'),
  ('United States', 'Green Island Country Club'),
  ('United States', 'Green Knoll Golf Course'),
  ('United States', 'Green Lakes Golf Course'),
  ('United States', 'Green Lea Golf Course'),
  ('United States', 'Green Mansions Golf Club'),
  ('United States', 'Green Meadow Country Club'),
  ('United States', 'Green Meadows Golf Club'),
  ('United States', 'Green Meadows Golf Course'),
  ('United States', 'Green Mountain National Golf Course'),
  ('United States', 'Green Oaks Country Club'),
  ('United States', 'Green Oaks Golf Club'),
  ('United States', 'Green Oaks Golf Course'),
  ('United States', 'Green Pond Country Club'),
  ('United States', 'Green Red At Sunken Meadow State Park Golf Course'),
  ('United States', 'Green Red At Town Of Colonie Golf Course'),
  ('United States', 'Green Ridge Golf Club'),
  ('United States', 'Green Ridge Public Golf Course'),
  ('United States', 'Green River Country Club'),
  ('United States', 'Green River Golf Club'),
  ('United States', 'Green River Golf Course'),
  ('United States', 'Green Spring Golf Course'),
  ('United States', 'Green Tree Golf Course'),
  ('United States', 'Green Trees Golf Course'),
  ('United States', 'Green Valley'),
  ('United States', 'Green Valley Country Club'),
  ('United States', 'Green Valley Golf Club'),
  ('United States', 'Green Valley Golf Course'),
  ('United States', 'Green Valley Greens Golf Course'),
  ('United States', 'Green Valley Ranch Golf Club'),
  ('United States', 'Green Way Golf Course'),
  ('United States', 'Green White At Wyndemere Country Club'),
  ('United States', 'Green Woods Country Club'),
  ('United States', 'Greenbelt Golf Course'),
  ('United States', 'Greenbriar At Ocean Aire Golf And Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Greenbriar Brooklyn'),
  ('United States', 'Greenbriar Golf Club At Whittingham'),
  ('United States', 'Greenbriar Golf Course'),
  ('United States', 'Greenbriar Hills Country Club'),
  ('United States', 'Greenbriar Woodlands Golf Course'),
  ('United States', 'Greenbrier Country Club'),
  ('United States', 'Greenbrier Golf Club'),
  ('United States', 'Greenbrier Greenbrier Course'),
  ('United States', 'Greenbrier Meadows Course'),
  ('United States', 'Greenbrier Old White Course'),
  ('United States', 'Greenbrier Sporting Club Snead Course'),
  ('United States', 'Greenbush Golf Course'),
  ('United States', 'Greencastle Golf Club'),
  ('United States', 'Greendale Golf Course'),
  ('United States', 'Greene Country Club Event Center'),
  ('United States', 'Greene County Country Club'),
  ('United States', 'Greene Hills Club'),
  ('United States', 'Greeneacre Golf Club'),
  ('United States', 'Greenfield Country Club'),
  ('United States', 'Greenfield Lakes Golf Course'),
  ('United States', 'Greenfield Park Golf Course'),
  ('United States', 'Greenhills Golf Course'),
  ('United States', 'Greenhorn Creek Golf Course'),
  ('United States', 'Greenlake Golf Course'),
  ('United States', 'Greenlea Golf Course'),
  ('United States', 'Greenlee Country Club'),
  ('United States', 'Greenock Country Club'),
  ('United States', 'Greens Folly Golf Course'),
  ('United States', 'Greens Golf Racquet Club'),
  ('United States', 'Greens Of Manatee Golf Course'),
  ('United States', 'Greensboro Country Club Farm Course'),
  ('United States', 'Greensboro Country Club Irving Park Course'),
  ('United States', 'Greensboro National Golf Club'),
  ('United States', 'Greensbridge Golf Course'),
  ('United States', 'Greensburg Country Club'),
  ('United States', 'Greenshire Golf Course'),
  ('United States', 'Greenvalley At Greenview Country Club'),
  ('United States', 'Greenview At Greenview Country Club'),
  ('United States', 'Greenview Golf Club'),
  ('United States', 'Greenville Country Club'),
  ('United States', 'Greenville Public Golf Course'),
  ('United States', 'Greenway Creek Golf Course'),
  ('United States', 'Greenway Park Golf Course'),
  ('United States', 'Greenwich Country Club'),
  ('United States', 'Greenwood Country Club'),
  ('United States', 'Greenwood Golf Course'),
  ('United States', 'Greenwood Hills Country Club'),
  ('United States', 'Greer Golf'),
  ('United States', 'Greeville Country Club'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Blue Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Gold Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills North Par 3 Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills South Par 3 Course'),
  ('United States', 'Grenadier Island Country Club'),
  ('United States', 'Gresham Golf Course'),
  ('United States', 'Grey Oaks Country Club Estuary Golf Course'),
  ('United States', 'Grey Oaks Country Club Palm Golf Course'),
  ('United States', 'Grey Oaks Country Club Pine Golf Course'),
  ('United States', 'GreyStone Golf Club'),
  ('United States', 'Greynolds Golf Course'),
  ('United States', 'Greystone Country Club'),
  ('United States', 'Greystone Golf Club'),
  ('United States', 'Greystone Golf Country Club'),
  ('United States', 'Greystone Golf Course'),
  ('United States', 'Greystone Mountain Golf Club'),
  ('United States', 'Greywalls Course At Marquette Golf Club'),
  ('United States', 'Griffin Bell Golf Conference Center'),
  ('United States', 'Griffin City Golf Course'),
  ('United States', 'Griffith E Harris Golf Course'),
  ('United States', 'Grindstone Neck Golf Course'),
  ('United States', 'Grinnell College Golf Course'),
  ('United States', 'Grinnell Cow Paddy Golf Club'),
  ('United States', 'Grizzly Oaks Disc Golf Course'),
  ('United States', 'Grizzly Ranch Golf Club'),
  ('United States', 'Groesbeck Golf Course'),
  ('United States', 'Grosse Ile Golf & Country Club'),
  ('United States', 'Groton Country Club'),
  ('United States', 'Grove City Country Club'),
  ('United States', 'Grove Lakes At Treesdale Golf Country Club'),
  ('United States', 'Grove Park Golf Club'),
  ('United States', 'Grove Park Golf Course'),
  ('United States', 'Grove Xxiii'),
  ('United States', 'Groveport Municipal Golf Course'),
  ('United States', 'Grover Cleveland Golf Course'),
  ('United States', 'Gruis Golf Course'),
  ('United States', 'Gruis Recreation Area The Barn'),
  ('United States', 'Guilford Lakes Golf Course'),
  ('United States', 'Gulf Harbour Golf Country Club'),
  ('United States', 'Gulf Hills Golf Club'),
  ('United States', 'Gulf Stream Golf Course'),
  ('United States', 'Gull Haven Golf Club'),
  ('United States', 'Gull Lake Country Club'),
  ('United States', 'Gull Lake View East'),
  ('United States', 'Gull Lake View West'),
  ('United States', 'Gully Golf Course'),
  ('United States', 'Gulph Mills Golf Club'),
  ('United States', 'Gun Ridge Golf Course'),
  ('United States', 'Gunflint Hills Golf Course'),
  ('United States', 'Guthrie Center Golf Club'),
  ('United States', 'Guthrie Golf Country Club'),
  ('United States', 'Guttenberg Community Golf'),
  ('United States', 'Guttenberg Golf and Country Club'),
  ('United States', 'Guyan Golf and Country Club'),
  ('United States', 'Gypsum Creek Golf Course'),
  ('United States', 'Gypsy Hill Golf Club'),
  ('United States', 'H Smith Richardson Golf Course'),
  ('United States', 'Hacienda Golf Club'),
  ('United States', 'Hackensack Golf Club'),
  ('United States', 'Haddam Community Golf Course'),
  ('United States', 'Hadley Acres Golf Club'),
  ('United States', 'Hadley Creek Golf Learning Center'),
  ('United States', 'Haile Plantation Golf Country Club'),
  ('United States', 'Hailwood Golf Course'),
  ('United States', 'Hale S Location Golf Course'),
  ('United States', 'Hales Mills Country Club'),
  ('United States', 'Half Moon Bay Golf Links Ocean Course'),
  ('United States', 'Half Moon Bay Golf Links Old Course'),
  ('United States', 'Halifax Country Club'),
  ('United States', 'Halifax Plantation'),
  ('United States', 'Halla Greens'),
  ('United States', 'Hallbrook Country Club'),
  ('United States', 'Hamakua Country Club'),
  ('United States', 'Hamilton College Golf Course'),
  ('United States', 'Hamilton Elks Golf Club'),
  ('United States', 'Hamilton Golf Club'),
  ('United States', 'Hamilton Lake Conference Center'),
  ('United States', 'Hamilton Mill Golf Course'),
  ('United States', 'Hamilton Trails Country Club'),
  ('United States', 'Hamlet Golf Country Club'),
  ('United States', 'Hamlet Golf Course'),
  ('United States', 'Hamlin Golf Club'),
  ('United States', 'Hammock At Ocean Reef Club'),
  ('United States', 'Hammock Bay Golf Course'),
  ('United States', 'Hammock Beach Resort The Conservatory Course'),
  ('United States', 'Hammock Beach Resort The Ocean Course'),
  ('United States', 'Hammock Creek Golf Club'),
  ('United States', 'Hammock Dunes Rees Jones Creek Course'),
  ('United States', 'Hammock Dunes Tom Fazio Links Course'),
  ('United States', 'Hammond Golf Center'),
  ('United States', 'Hammond Golf Club'),
  ('United States', 'Hampden Country Club'),
  ('United States', 'Hampshire Country Club'),
  ('United States', 'Hampton Country Club'),
  ('United States', 'Hampton Golf Village'),
  ('United States', 'Hampton Golf and Country Club'),
  ('United States', 'Hampton Hall Club'),
  ('United States', 'Hampton Heights Golf Course'),
  ('United States', 'Hampton Hills Golf Country Club'),
  ('United States', 'Hamptons Golf Club The'),
  ('United States', 'Hanah Mountain Resort Country Club'),
  ('United States', 'Hancock Golf Country Club'),
  ('United States', 'Hanging Rock Golf Club'),
  ('United States', 'Hankerd Hills Golf Course'),
  ('United States', 'Hanks Golf'),
  ('United States', 'Hanks Swank Par Three Golf Course'),
  ('United States', 'Hanks Woodlake Ranch Golf'),
  ('United States', 'Hannastown Golf Club'),
  ('United States', 'Hannibal Country Club'),
  ('United States', 'Hanover Country Club'),
  ('United States', 'Hanover Golf Club'),
  ('United States', 'Hansen Dam Golf Course'),
  ('United States', 'Hansen Park Golf Course'),
  ('United States', 'Hansford Golf Course'),
  ('United States', 'Happy Hollow Club'),
  ('United States', 'Hapuna Golf Course'),
  ('United States', 'Harbor At Wild Dunes Golf Links'),
  ('United States', 'Harbor Club On Lake Oconee'),
  ('United States', 'Harbor Hills Country Club'),
  ('United States', 'Harbor Lights Golf Country Club'),
  ('United States', 'Harbor Links At Sagamore Resort'),
  ('United States', 'Harbor Links Public Golf'),
  ('United States', 'Harbor Oaks Golf Club'),
  ('United States', 'Harbor Park Golf Course'),
  ('United States', 'Harbor Pines Golf Club'),
  ('United States', 'Harbor Point Golf Club'),
  ('United States', 'Harbor Ridge Golf Course'),
  ('United States', 'Harbor Shores'),
  ('United States', 'Harborside International Golf Center'),
  ('United States', 'Harbour Pointe Golf Club'),
  ('United States', 'Harbour Town Golf Links At Sea Pines Resort'),
  ('United States', 'Harbour View Golf Complex'),
  ('United States', 'Harbour Village Golf Yacht Club'),
  ('United States', 'Hardeman County Golf Country Club'),
  ('United States', 'Harding At Griffith Park Golf Courses'),
  ('United States', 'Hardscrabble Country Club'),
  ('United States', 'Hardwick Crossing Country Club'),
  ('United States', 'Hardwood Hills Golf Course'),
  ('United States', 'Hardys Custom Golf Center'),
  ('United States', 'Harkers Hollow Golf Club'),
  ('United States', 'Harlan Country Club'),
  ('United States', 'Harlan Golf and Country Club'),
  ('United States', 'Harlem Golf Course'),
  ('United States', 'Harlem Valley Golf Club'),
  ('United States', 'Harmon Golf Fitness Club'),
  ('United States', 'Harmony Golf Club'),
  ('United States', 'Harmony Golf Club Community'),
  ('United States', 'Harmony Golf Preserve'),
  ('United States', 'Harmony Landing'),
  ('United States', 'Harmony Ridge Golf Club'),
  ('United States', 'Harrington Golf Country Club'),
  ('United States', 'Harris Hill Golf Center'),
  ('United States', 'Harris Park Golf Course'),
  ('United States', 'Harrison Country Club'),
  ('United States', 'Harrison Hills Golf Course'),
  ('United States', 'Harrison Lake Country Club'),
  ('United States', 'Harrison Meadows Country Club'),
  ('United States', 'Harrison Park Golf Course'),
  ('United States', 'Harrisonville Golf Club'),
  ('United States', 'Harrisville Golf Course'),
  ('United States', 'Harry L Jones Sr Golf Course'),
  ('United States', 'Harry Mussatto Golf Course (WIU)'),
  ('United States', 'Hart Ridge Golf Course'),
  ('United States', 'Hartefeld National Golf Club'),
  ('United States', 'Hartford Golf Club'),
  ('United States', 'Hartford Golf Club Blue Course'),
  ('United States', 'Hartford Golf Club Green Course'),
  ('United States', 'Hartford Golf Club Red Course'),
  ('United States', 'Hartland Glen Golf Club'),
  ('United States', 'Hartley Hills Country Club'),
  ('United States', 'Hartmanns Deep Valley Golf Course'),
  ('United States', 'Hartstown Golf Course'),
  ('United States', 'Hartsville Country Club'),
  ('United States', 'Hartwell Golf Club'),
  ('United States', 'Hartwood Golf Course'),
  ('United States', 'Harvard Gulch Golf Course'),
  ('United States', 'Harvest Hill Golf Course'),
  ('United States', 'Harvest Hills Golf Course'),
  ('United States', 'Harvest Point Golf Course'),
  ('United States', 'Harwich Port Golf Club'),
  ('United States', 'Hastings Country Club'),
  ('United States', 'Hat Creek Golf Course'),
  ('United States', 'Hat Island Golf Course'),
  ('United States', 'Hatherly Country Club'),
  ('United States', 'Hattiesburg Country Club'),
  ('United States', 'Havana Golf Country Club'),
  ('United States', 'Havanah Hills'),
  ('United States', 'Havasu Island Golf Course'),
  ('United States', 'Havasu Springs Resort'),
  ('United States', 'Haven At Haven Public Golf Club'),
  ('United States', 'Haven Golf Club'),
  ('United States', 'Haverhill Country Club'),
  ('United States', 'Hawaii Country Club'),
  ('United States', 'Hawaii Kai Executive Golf Course'),
  ('United States', 'Hawaii Kai Golf Course'),
  ('United States', 'Hawaii Prince Golf Club A B Nines'),
  ('United States', 'Hawaii Prince Golf Club B C Nines'),
  ('United States', 'Hawaii Prince Golf Club C A Nines'),
  ('United States', 'Hawarden Golf Course'),
  ('United States', 'Hawk Golf Course'),
  ('United States', 'Hawk Hollow Golf Course'),
  ('United States', 'Hawk Meadows'),
  ('United States', 'Hawk Pointe Golf Course'),
  ('United States', 'Hawk Ridge Golf Course'),
  ('United States', 'Hawk S Eye At Shanty Creek'),
  ('United States', 'Hawk Valley Golf Club'),
  ('United States', 'Hawk''s Eye Golf Course'),
  ('United States', 'Hawk''s View Golf Club'),
  ('United States', 'Hawkes Bay At The Villages Executive Golf Trail'),
  ('United States', 'Hawks Landing Country Club'),
  ('United States', 'Hawks Landing Golf Club'),
  ('United States', 'Hawks Landing Golf Course'),
  ('United States', 'Hawks Point Golf Club'),
  ('United States', 'Hawks Ridge'),
  ('United States', 'Hawks Ridge Par 3 Course'),
  ('United States', 'Hawks Tail Of Greenfield'),
  ('United States', 'Hawkshead'),
  ('United States', 'Hawkshead Links Golf Course'),
  ('United States', 'Hawktree Golf Club'),
  ('United States', 'Hawley Golf and Country Club'),
  ('United States', 'Haworth Golf Club'),
  ('United States', 'Hawthorn Woods Country Club'),
  ('United States', 'Hawthorne Country Club'),
  ('United States', 'Hawthorne Hills Golf Course'),
  ('United States', 'Hawthorne Ridge Golf Course'),
  ('United States', 'Hawthorne Valley Golf Club'),
  ('United States', 'Hay Creek Golf Course'),
  ('United States', 'Hay Harbor Golf Club'),
  ('United States', 'Hayden Golf Club'),
  ('United States', 'Haymaker'),
  ('United States', 'Haynesville Golf Course'),
  ('United States', 'Haystack Mountain Golf Course'),
  ('United States', 'Hayward Golf Club'),
  ('United States', 'Hayward National Golf Club'),
  ('United States', 'Hazard Creek Golf Course'),
  ('United States', 'Hazelden Country Club'),
  ('United States', 'Hazelmere Country Club'),
  ('United States', 'Hazeltine National Golf Course'),
  ('United States', 'Hazelton Golf Club'),
  ('United States', 'Hazen Golf Club'),
  ('United States', 'Hazy Hills Golf Course'),
  ('United States', 'Headland Country Club'),
  ('United States', 'Headwaters Club At Teton Springs'),
  ('United States', 'Headwaters Club At Teton Springs Par 3 Course'),
  ('United States', 'Headwaters Golf Club'),
  ('United States', 'Headwaters Public Golf Course'),
  ('United States', 'Healdsburg Golf Club At Tayman Park'),
  ('United States', 'Healing Springs Ranch'),
  ('United States', 'Healy Point Country Club'),
  ('United States', 'Heart Of America Golf Academy River Course'),
  ('United States', 'Heart Of America Golf Academy Rock Course'),
  ('United States', 'Heart of the Valley Golf Club'),
  ('United States', 'Heartland Crossing Golf Links'),
  ('United States', 'Heartland Golf Park'),
  ('United States', 'Heartland Resort'),
  ('United States', 'Heartwell Golf Course'),
  ('United States', 'Heather Downs Country Club'),
  ('United States', 'Heather Gardens Golf Course'),
  ('United States', 'Heather Golf Country Club'),
  ('United States', 'Heather Highlands Golf Club'),
  ('United States', 'Heather Hills Golf Course'),
  ('United States', 'Heather Ridge Golf Course'),
  ('United States', 'Heathers Club of Bloomfield'),
  ('United States', 'Heatherwoode Golf Club'),
  ('United States', 'Heatherwoods Golf Course'),
  ('United States', 'Heathrow Country Club'),
  ('United States', 'Heaven On Earth Par 3 Ranch Golf Course'),
  ('United States', 'Hebron Country Club'),
  ('United States', 'Hebron Pines Rv And Golf'),
  ('United States', 'Hedingham Golf Club'),
  ('United States', 'Heidelberg Country Club'),
  ('United States', 'Heise Hills Golf Course'),
  ('United States', 'Helena Country Club'),
  ('United States', 'Helena West Helena Public Golf Course'),
  ('United States', 'Helfrich Golf Course'),
  ('United States', 'Hells Point Golf Club'),
  ('United States', 'Hemet Golf Club'),
  ('United States', 'Hemet West Mobile Estates'),
  ('United States', 'Hemingway Kilimanjaro At Havana Country Club'),
  ('United States', 'Hemlock Golf Club'),
  ('United States', 'Hemlock Golf Course'),
  ('United States', 'Hemlock Ridge Golf Course'),
  ('United States', 'Hemlock View Golf Course'),
  ('United States', 'Hempstead Golf Country Club'),
  ('United States', 'Henderson Country Club'),
  ('United States', 'Henderson Golf Club'),
  ('United States', 'Henderson Municipal Golf Course'),
  ('United States', 'Henderson Park Golf Course'),
  ('United States', 'Hendersonville Country Club'),
  ('United States', 'Hendricks Field Golf Course'),
  ('United States', 'Hendricks Golf Club'),
  ('United States', 'Henry Stambaugh Golf Course'),
  ('United States', 'Henryetta Golf Country Club'),
  ('United States', 'Henson Creek Golf Course'),
  ('United States', 'Herington Country Club'),
  ('United States', 'Heritage Bay Golf And Country Club Cypress Course'),
  ('United States', 'Heritage Bay Golf And Country Club Oak Course'),
  ('United States', 'Heritage Bay Golf And Country Club Pine Course'),
  ('United States', 'Heritage Bluffs Public Golf Club'),
  ('United States', 'Heritage Club'),
  ('United States', 'Heritage Country Club'),
  ('United States', 'Heritage Creek Golf Club'),
  ('United States', 'Heritage Eagle Bend Golf Club'),
  ('United States', 'Heritage Glen Golf Club'),
  ('United States', 'Heritage Golf Club'),
  ('United States', 'Heritage Golf Club Blue Course'),
  ('United States', 'Heritage Golf Club Green Course'),
  ('United States', 'Heritage Golf Club Orange Course'),
  ('United States', 'Heritage Golf Links Heritage Nine'),
  ('United States', 'Heritage Golf Links Legacy Nine'),
  ('United States', 'Heritage Golf Links Tradition Nine'),
  ('United States', 'Heritage Harbor'),
  ('United States', 'Heritage Harbour Golf Club'),
  ('United States', 'Heritage Hill Golf Course'),
  ('United States', 'Heritage Hills Golf Course'),
  ('United States', 'Heritage Hills Golf Resort'),
  ('United States', 'Heritage Hunt Golf Club'),
  ('United States', 'Heritage Isles Golf And Country Club'),
  ('United States', 'Heritage Landing Golf Country Club'),
  ('United States', 'Heritage Links'),
  ('United States', 'Heritage Links Golf Club'),
  ('United States', 'Heritage Oaks Golf Club'),
  ('United States', 'Heritage Oaks Golf Country Club'),
  ('United States', 'Heritage Oaks Golf Course'),
  ('United States', 'Heritage Of Hawk Ridge'),
  ('United States', 'Heritage Palms Golf Club'),
  ('United States', 'Heritage Park Golf Course'),
  ('United States', 'Heritage Pines Country Club'),
  ('United States', 'Heritage Ridge Golf Club'),
  ('United States', 'Heritage Shores Golf'),
  ('United States', 'Heritage Springs Country Club'),
  ('United States', 'Heritage Woods Golf Course'),
  ('United States', 'Heritage of Hawk Ridge'),
  ('United States', 'Hermitage Club'),
  ('United States', 'Hermon Meadow Golf Club Training Center'),
  ('United States', 'Hernando Oaks Golf Country Club'),
  ('United States', 'Herndon Centennial Golf Course'),
  ('United States', 'Heroes Golf Course'),
  ('United States', 'Heron At The Villages Executive Golf Trail'),
  ('United States', 'Heron Bay Golf Country Club'),
  ('United States', 'Heron Creek Golf And Country Club Creek Oaks Course'),
  ('United States', 'Heron Creek Golf And Country Club Marsh Creek Course'),
  ('United States', 'Heron Creek Golf And Country Club Oaks Marsh Course'),
  ('United States', 'Heron Creek Golf Club'),
  ('United States', 'Heron Eagle At Okeeheelee Golf Course'),
  ('United States', 'Heron Glen Golf Course'),
  ('United States', 'Heron Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Heron Lakes Golf Club Great Blue Course'),
  ('United States', 'Heron Lakes Golf Club Greenback Course'),
  ('United States', 'Heron Osprey At Burnt Store Marina Country Club'),
  ('United States', 'Heron Pelican At Burnt Store Marina Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Heron Point At Sea Pines Resort'),
  ('United States', 'Heron Ridge Golf Club'),
  ('United States', 'Herons Glen Golf Country Club'),
  ('United States', 'Herring Cove Provincial Golf Course'),
  ('United States', 'Hersheys Mill Golf Club'),
  ('United States', 'Hesperia Golf Country Club'),
  ('United States', 'Hessel Ridge Golf'),
  ('United States', 'Hesston Municipal Golf Park'),
  ('United States', 'Hi Point Golf Course'),
  ('United States', 'Hiawatha Country Club'),
  ('United States', 'Hiawatha Golf Club'),
  ('United States', 'Hiawatha Sportsman’s Club Golf Course'),
  ('United States', 'Hiawatha Trails'),
  ('United States', 'Hibiscus Golf Club'),
  ('United States', 'Hickory Bend Golf Course'),
  ('United States', 'Hickory Creek Golf Course'),
  ('United States', 'Hickory Flats Golf Course'),
  ('United States', 'Hickory Grove Country Club'),
  ('United States', 'Hickory Grove Golf Club'),
  ('United States', 'Hickory Grove Golf Course'),
  ('United States', 'Hickory Heights Golf Club'),
  ('United States', 'Hickory Hill Country Club Resort'),
  ('United States', 'Hickory Hill Golf Club'),
  ('United States', 'Hickory Hill Golf Course'),
  ('United States', 'Hickory Hill Golf Course Creekside Roadside'),
  ('United States', 'Hickory Hill Golf Course Fieldside Creekside'),
  ('United States', 'Hickory Hill Golf Course Roadside Fieldside'),
  ('United States', 'Hickory Hills Country Club'),
  ('United States', 'Hickory Hills Golf Club'),
  ('United States', 'Hickory Hills Golf Course'),
  ('United States', 'Hickory Hollow Golf Course'),
  ('United States', 'Hickory Knob Golf Course'),
  ('United States', 'Hickory Knoll Golf Course'),
  ('United States', 'Hickory Point Golf Course'),
  ('United States', 'Hickory Ridge Golf Country Club'),
  ('United States', 'Hickory Ridge Golf Course'),
  ('United States', 'Hickory Ridge Public Golf Center'),
  ('United States', 'Hickory Sticks Golf Club'),
  ('United States', 'Hickory Swing Golf Course'),
  ('United States', 'Hickory Woods Golf Course'),
  ('United States', 'Hidden Acres Executive Golf'),
  ('United States', 'Hidden Acres Golf Course'),
  ('United States', 'Hidden Bridge Golf Club'),
  ('United States', 'Hidden Cove Golf Course'),
  ('United States', 'Hidden Creek Country Club'),
  ('United States', 'Hidden Creek Family Golf Course'),
  ('United States', 'Hidden Creek Golf Club'),
  ('United States', 'Hidden Cypress Golf Club'),
  ('United States', 'Hidden Glen At Bentdale Farms'),
  ('United States', 'Hidden Greens'),
  ('United States', 'Hidden Greens North'),
  ('United States', 'Hidden Hills'),
  ('United States', 'Hidden Hills Golf Course'),
  ('United States', 'Hidden Hollow Country Club'),
  ('United States', 'Hidden Lake Country Club'),
  ('United States', 'Hidden Lakes Golf Course'),
  ('United States', 'Hidden Meadows Golf Course'),
  ('United States', 'Hidden Oaks Country Club'),
  ('United States', 'Hidden Oaks Golf Course'),
  ('United States', 'Hidden River Golf and Casting Club'),
  ('United States', 'Hidden Springs Country Club'),
  ('United States', 'Hidden Springs Golf Course'),
  ('United States', 'Hidden Trails Country Club'),
  ('United States', 'Hidden Valley Country Club'),
  ('United States', 'Hidden Valley Country Club Lakes Mountain'),
  ('United States', 'Hidden Valley Country Club Lakes Valley'),
  ('United States', 'Hidden Valley Country Club Mountain Valley'),
  ('United States', 'Hidden Valley Golf Club'),
  ('United States', 'Hidden Valley Golf Course'),
  ('United States', 'Hidden Valley Golf Resort'),
  ('United States', 'Hidden Valley Lake Golf Course'),
  ('United States', 'Hidden Valley Rv And Golf Park'),
  ('United States', 'Hidden Valley Rv And Golf Park Par 3'),
  ('United States', 'Hidden Waters Golf Course'),
  ('United States', 'Hiddenbrooke Golf Club'),
  ('United States', 'Hideaway Beach Golf Course'),
  ('United States', 'Hideaway Hills Golf Club'),
  ('United States', 'Hideout Golf Club'),
  ('United States', 'High Bridge Hills Golf Club'),
  ('United States', 'High Cliff Public Golf Course'),
  ('United States', 'High Grove Golf'),
  ('United States', 'High Hampton'),
  ('United States', 'High Meadows Country Club'),
  ('United States', 'High Meadows Golf Country Club'),
  ('United States', 'High Peaks Golf Course'),
  ('United States', 'High Point Country Club'),
  ('United States', 'High Point Golf Club'),
  ('United States', 'High Point Golf Course'),
  ('United States', 'High Pointe Golf Club'),
  ('United States', 'High Pointe Golf Course'),
  ('United States', 'High Ridge Country Club'),
  ('United States', 'High Valley Country Club'),
  ('United States', 'Highfield Club'),
  ('United States', 'Highfields Golf Country Club'),
  ('United States', 'Highland 9 Hole Golf Course'),
  ('United States', 'Highland At Brae Burn Country Club'),
  ('United States', 'Highland Country Club'),
  ('United States', 'Highland Creek Golf Club'),
  ('United States', 'Highland Fairways Golf Club'),
  ('United States', 'Highland Florida Golf Club'),
  ('United States', 'Highland Golf Club'),
  ('United States', 'Highland Golf Course'),
  ('United States', 'Highland Green Golf Club'),
  ('United States', 'Highland Greens Golf Course'),
  ('United States', 'Highland Hills Golf Course'),
  ('United States', 'Highland Lake Golf Course'),
  ('United States', 'Highland Links Cape Cod'),
  ('United States', 'Highland Links Golf Club'),
  ('United States', 'Highland Meadow Creek At Lancaster Country Club'),
  ('United States', 'Highland Meadows Golf Club'),
  ('United States', 'Highland Meadows Golf Country Club'),
  ('United States', 'Highland Meadows Golf Course'),
  ('United States', 'Highland National Golf Course'),
  ('United States', 'Highland Palms Senior Estates Country Club'),
  ('United States', 'Highland Park Golf Club'),
  ('United States', 'Highland Park Golf Course'),
  ('United States', 'Highland Spring Golf Course'),
  ('United States', 'Highland Springs Golf Course'),
  ('United States', 'Highland Springs Municipal Golf Course'),
  ('United States', 'Highland Springs Village Golf Club'),
  ('United States', 'Highland Walk At Victoria Bryant'),
  ('United States', 'Highland Woods Golf Country Club'),
  ('United States', 'Highland Woods Golf Course'),
  ('United States', 'Highlander Golf Club'),
  ('United States', 'Highlands At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Highlands At Dove Mountain'),
  ('United States', 'Highlands At Grand Geneva Resort Spa'),
  ('United States', 'Highlands Country Club'),
  ('United States', 'Highlands Course'),
  ('United States', 'Highlands Falls Country Club'),
  ('United States', 'Highlands Golf Club'),
  ('United States', 'Highlands Golf Club Hidden Valley Course'),
  ('United States', 'Highlands Golf Club Seven Springs Course'),
  ('United States', 'Highlands Golf Club The'),
  ('United States', 'Highlands Golf Course'),
  ('United States', 'Highlands Marshwood At Highland Oaks Golf Course'),
  ('United States', 'Highlands Of Donegal Golf Course'),
  ('United States', 'Highlands Reserve Golf Club'),
  ('United States', 'Highlands of Elgin'),
  ('United States', 'Hilaman Park Municipal Golf Course'),
  ('United States', 'Hiland Golf Course'),
  ('United States', 'Hiland Park Country Club'),
  ('United States', 'Hilands Golf Club'),
  ('United States', 'Hill At Castlewood Country Club'),
  ('United States', 'Hill Crest Country Club'),
  ('United States', 'Hill Golf Course'),
  ('United States', 'Hill N Dale Golf Country Club'),
  ('United States', 'Hill Ridge At La Paloma Country Club'),
  ('United States', 'Hill Top'),
  ('United States', 'Hill Top At The Villages Executive Golf Trail'),
  ('United States', 'Hillandale Country Club'),
  ('United States', 'Hillandale Golf Course'),
  ('United States', 'Hillcrest'),
  ('United States', 'Hillcrest Country Club'),
  ('United States', 'Hillcrest Country Club of Dallas County'),
  ('United States', 'Hillcrest Event Center'),
  ('United States', 'Hillcrest Golf & Country Club'),
  ('United States', 'Hillcrest Golf Center'),
  ('United States', 'Hillcrest Golf Club'),
  ('United States', 'Hillcrest Golf Club At Sun City West'),
  ('United States', 'Hillcrest Golf Country Club'),
  ('United States', 'Hillcrest Golf Course'),
  ('United States', 'Hillcrest Golf and Country Club'),
  ('United States', 'Hilldale Golf Club'),
  ('United States', 'Hillendale Golf Course'),
  ('United States', 'Hillhigh Hotel Spa Golf Resort Cedar Glade Golf Course'),
  ('United States', 'Hilliard Lakes Golf Club'),
  ('United States', 'Hills At Hernando Country Club'),
  ('United States', 'Hills At Jupiter Hills Club'),
  ('United States', 'Hills At Rotonda Golf Country Club'),
  ('United States', 'Hills Heart of the Lakes Golf Course'),
  ('United States', 'Hillsboro Elks Golf Course'),
  ('United States', 'Hillsboro Municipal Golf'),
  ('United States', 'Hillsborough Country Club'),
  ('United States', 'Hillsdale Country Club'),
  ('United States', 'Hillside Country Club'),
  ('United States', 'Hillside Golf Club'),
  ('United States', 'Hillside Links'),
  ('United States', 'Hilltop Country Club'),
  ('United States', 'Hilltop Golf Course'),
  ('United States', 'Hillview Country Club'),
  ('United States', 'Hillview Golf Course'),
  ('United States', 'Hilly Haven Golf Course'),
  ('United States', 'Hilo Municipal Golf Course'),
  ('United States', 'Hilton Chicago/Indian Lakes Resort'),
  ('United States', 'Hilton Head National Golf Club'),
  ('United States', 'Hinckley Hills Golf Course'),
  ('United States', 'Hinsdale Golf Club'),
  ('United States', 'Historic Black Knight Municipal Park'),
  ('United States', 'Hiwan Golf Club'),
  ('United States', 'Hoakalei Country Club At Ocean Pointe'),
  ('United States', 'Hobart Municipal Golf Course'),
  ('United States', 'Hobble Creek Golf Course'),
  ('United States', 'Hobbs Country Club'),
  ('United States', 'Hobbs Hole Golf Course'),
  ('United States', 'Hobe Sound Golf Club'),
  ('United States', 'Hocking Hills Golf Club'),
  ('United States', 'Hogansville Golf Club'),
  ('United States', 'Holbrook Country Club'),
  ('United States', 'Holden Hills Country Club'),
  ('United States', 'Hole 1'),
  ('United States', 'Hole 2'),
  ('United States', 'Hole 3'),
  ('United States', 'Hole In One Golf Center'),
  ('United States', 'Hole In The Wall Golf Club'),
  ('United States', 'Holiday Hills Golf Course'),
  ('United States', 'Holiday Hills Resort And Golf Club'),
  ('United States', 'Holiday Inn Golf Course'),
  ('United States', 'Holiday Lodge Golf Resort'),
  ('United States', 'Holiday Meadows Golf Course'),
  ('United States', 'Holland Heights Golf Course'),
  ('United States', 'Holland Hills Country Club'),
  ('United States', 'Holland Lake Golf Course'),
  ('United States', 'Holland Meadows Golf Course'),
  ('United States', 'Hollenback Golf Club'),
  ('United States', 'Holley Brook Golf Course'),
  ('United States', 'Holliday Farms'),
  ('United States', 'Hollis Golf Country Club'),
  ('United States', 'Hollow Acres Golf Center'),
  ('United States', 'Hollow Brook Golf Course'),
  ('United States', 'Holly Hills Golf Course'),
  ('United States', 'Holly Meadows Golf Course'),
  ('United States', 'Holly Ridge Golf Club'),
  ('United States', 'Holly Ridge Golf Course'),
  ('United States', 'Holly Ridge Golf Links'),
  ('United States', 'Holly Tree Country Club'),
  ('United States', 'Hollybrook Country Club'),
  ('United States', 'Hollydot Golf Course'),
  ('United States', 'Hollywood Beach Golf Country Club'),
  ('United States', 'Hollywood Golf Club'),
  ('United States', 'Holmes County Country Club'),
  ('United States', 'Holmes Harbor Golf Club'),
  ('United States', 'Holmes Park Golf Course'),
  ('United States', 'Holston Hills Community Golf Course'),
  ('United States', 'Holton Country Club'),
  ('United States', 'Holyoke Golf Club'),
  ('United States', 'Homer Golf Course'),
  ('United States', 'Homestead Golf Club'),
  ('United States', 'Homestead Golf Course'),
  ('United States', 'Homestead Old Mill At Flat Creek Golf Club'),
  ('United States', 'Homestead Springs Golf Course'),
  ('United States', 'Homewood Acres Golf Course'),
  ('United States', 'Homewood Golf Course'),
  ('United States', 'Hominy Hill Golf Course'),
  ('United States', 'Hon-E-Kor Country Club'),
  ('United States', 'Honesdale Golf Club'),
  ('United States', 'Honey Bee Golf Club'),
  ('United States', 'Honey Creek Golf Club'),
  ('United States', 'Honey Creek Golf Country Club'),
  ('United States', 'Honey Creek Golf Course'),
  ('United States', 'Honey Pond Farm'),
  ('United States', 'Honey Run Golf Club'),
  ('United States', 'Honeybrook Golf Club'),
  ('United States', 'Honeysuckle At The Villages Executive Golf Trail'),
  ('United States', 'Honeywell Golf Course'),
  ('United States', 'Honolulu Country Club'),
  ('United States', 'Hood River Golf Country Club'),
  ('United States', 'Hoodkroft Country Club'),
  ('United States', 'Hooper Golf Course'),
  ('United States', 'Hoopers Landing Golf Course'),
  ('United States', 'Hoosick Falls Country Club'),
  ('United States', 'Hoosier Heights Country Club'),
  ('United States', 'Hoosier Links Golf Club'),
  ('United States', 'Hop Brook Golf Course'),
  ('United States', 'Hop Meadow Country Club'),
  ('United States', 'Hope Country Club'),
  ('United States', 'Hope Golf Club'),
  ('United States', 'Hope Valley Country Club'),
  ('United States', 'Hopedale Country Club'),
  ('United States', 'Hopewell Valley Golf Country Club'),
  ('United States', 'Hopkinton Country Club'),
  ('United States', 'Hopson Hills Golf Course'),
  ('United States', 'Horn Rapids Golf Club'),
  ('United States', 'Hornell Golf Club'),
  ('United States', 'Horseleg Plantation Country Club'),
  ('United States', 'Horsepasture Par 3 Golf Course'),
  ('United States', 'Horseshoe Bay Golf Club'),
  ('United States', 'Horseshoe Bend Country Club'),
  ('United States', 'Horseshoe Bend Golf Course'),
  ('United States', 'Horseshoe Lake Golf Course'),
  ('United States', 'Hot Springs Country Club Arlington Course'),
  ('United States', 'Hot Springs Country Club Park Course'),
  ('United States', 'Hotchkiss School Golf Course'),
  ('United States', 'Houlton Community Golf Course'),
  ('United States', 'Houma Golf Club'),
  ('United States', 'Hound Ears Club'),
  ('United States', 'House on the Rock Resort'),
  ('United States', 'Houston Country Club'),
  ('United States', 'Houston Lake Country Club'),
  ('United States', 'Houston Springs Resort And Golf Course'),
  ('United States', 'Howell Par 3 Golf Course'),
  ('United States', 'Howell Park Golf Course'),
  ('United States', 'Hoxie Golf Course'),
  ('United States', 'Hoyt Lakes Municipal Golf Course'),
  ('United States', 'Hualalai Golf Course'),
  ('United States', 'Hubbard Golf Course Hill Afb'),
  ('United States', 'Hubbard Golf and Recreation Club'),
  ('United States', 'Huckleberry Creek Golf Course'),
  ('United States', 'Hudson Hills Golf Course'),
  ('United States', 'Hudson Mills Metropark Golf Course'),
  ('United States', 'Hudson National Golf Club'),
  ('United States', 'Hudson Valley Resort Conference Center'),
  ('United States', 'Hueston Woods State Park Golf Course'),
  ('United States', 'Hugo Golf Club'),
  ('United States', 'Huletts Golf Club'),
  ('United States', 'Hulman Links Golf Course'),
  ('United States', 'Humboldt  Country  Club'),
  ('United States', 'Humeston Lakeside Golf Course'),
  ('United States', 'Humphreys County Country Club'),
  ('United States', 'Hunter Country Club'),
  ('United States', 'Hunter Golf Club'),
  ('United States', 'Hunter Pope Country Club'),
  ('United States', 'Hunter Ranch Golf Course'),
  ('United States', 'Hunters Glen Golf Club'),
  ('United States', 'Hunters Green Country Club'),
  ('United States', 'Hunters Ridge Country Club'),
  ('United States', 'Hunters Ridge Golf Course'),
  ('United States', 'Hunters Run Golf Course'),
  ('United States', 'Hunters Station Golf Course'),
  ('United States', 'Hunting Creek Golf Course'),
  ('United States', 'Hunting Hawk Golf Club'),
  ('United States', 'Hunting Hills Country Club'),
  ('United States', 'Huntingburg Country Club'),
  ('United States', 'Huntingdon Country Club'),
  ('United States', 'Huntington Country Club'),
  ('United States', 'Huntington Crescent Club'),
  ('United States', 'Huntington Golf Club'),
  ('United States', 'Huntington Hills Golf Country Club'),
  ('United States', 'Huntington Park Golf Course'),
  ('United States', 'Huntmore Golf Club'),
  ('United States', 'Huntsman Springs Golf Club'),
  ('United States', 'Huntsville Golf Club'),
  ('United States', 'Huron Breeze Golf and Country Club'),
  ('United States', 'Huron Hills Golf Course'),
  ('United States', 'Huron Meadows Golf Course'),
  ('United States', 'Huron Oaks Golf Course'),
  ('United States', 'Huron Pines Golf and Country Club'),
  ('United States', 'Huron Shores Golf Club & Restaurant'),
  ('United States', 'Hurricane Golf Country Club'),
  ('United States', 'Hurryville Driving Range'),
  ('United States', 'Hurryville Driving Range Par 3'),
  ('United States', 'Hurstbourne Country Club'),
  ('United States', 'Huukan Golf Club'),
  ('United States', 'Hyannis Golf Club'),
  ('United States', 'Hyannisport Club'),
  ('United States', 'Hyatt Hills Golf Complex'),
  ('United States', 'Hyde Park Golf & Country Club'),
  ('United States', 'Hyde Park Golf Club'),
  ('United States', 'Hydeaway Golf'),
  ('United States', 'Hyland Golf Club'),
  ('United States', 'Hyland Greens Golf Course'),
  ('United States', 'Hyperion Field Club'),
  ('United States', 'Hyperion Golf Course'),
  ('United States', 'IBM Disc Golf Course'),
  ('United States', 'IMA Brookwood Golf Club'),
  ('United States', 'Ibis Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Ibis Landing Golf Country Club'),
  ('United States', 'Ida Grove Golf and Country Club'),
  ('United States', 'Idabel Country Club'),
  ('United States', 'Idaho Falls Country Club'),
  ('United States', 'Idle Creek Golf Course'),
  ('United States', 'Idle Hour Golf Country Club'),
  ('United States', 'IdleWild Golf Club'),
  ('United States', 'Idlewild Country Club'),
  ('United States', 'Idylwyld Golf Club'),
  ('United States', 'Illini Golf Course'),
  ('United States', 'Illinois Valley Golf Club'),
  ('United States', 'Img Academy Golf Club'),
  ('United States', 'Immergrun Golf Club'),
  ('United States', 'Imperial Lakes Golf Country Club'),
  ('United States', 'Independence Country Club'),
  ('United States', 'Independence Golf Club Championship'),
  ('United States', 'Independence Golf Club The Bear Course'),
  ('United States', 'Indian Bayou Golf Club'),
  ('United States', 'Indian Bluff Forest Preserve Golf Course'),
  ('United States', 'Indian Boundary Golf Course'),
  ('United States', 'Indian Camp Golf Course'),
  ('United States', 'Indian Canyon Golf Course'),
  ('United States', 'Indian Canyons Golf Resort North Course'),
  ('United States', 'Indian Canyons Golf Resort South Course'),
  ('United States', 'Indian Creek Country Club'),
  ('United States', 'Indian Creek Golf Course'),
  ('United States', 'Indian Head Golf Course'),
  ('United States', 'Indian Hill Country Club'),
  ('United States', 'Indian Hill Golf Club'),
  ('United States', 'Indian Hill Golf Course'),
  ('United States', 'Indian Hills Country Club'),
  ('United States', 'Indian Hills Golf Club'),
  ('United States', 'Indian Hills Golf Course'),
  ('United States', 'Indian Hills Golf Resort'),
  ('United States', 'Indian Hills State Golf Course'),
  ('United States', 'Indian Island Country Club'),
  ('United States', 'Indian Lake Estates Golf Country Club'),
  ('United States', 'Indian Lake Golf Club'),
  ('United States', 'Indian Lake Golf and Country Club'),
  ('United States', 'Indian Lake Hills Golf Course'),
  ('United States', 'Indian Lakes Golf Club'),
  ('United States', 'Indian Meadows Golf Club'),
  ('United States', 'Indian Mound Golf Club'),
  ('United States', 'Indian Mountain Golf Course')
on conflict (country, name) do nothing;