insert into public.golf_courses (country, name) values
  ('United States', 'Indian Palms Golf Country Club Indian Mountain'),
  ('United States', 'Indian Palms Golf Country Club Mountain Royal'),
  ('United States', 'Indian Palms Golf Country Club Royal Indian'),
  ('United States', 'Indian Peaks Golf Club'),
  ('United States', 'Indian Pond Country Club'),
  ('United States', 'Indian Ridge Country Club'),
  ('United States', 'Indian Ridge Country Club Arroyo Course'),
  ('United States', 'Indian Ridge Country Club Grove Course'),
  ('United States', 'Indian Ridge Golf Club'),
  ('United States', 'Indian River Club'),
  ('United States', 'Indian River Colony Club'),
  ('United States', 'Indian River Golf Club'),
  ('United States', 'Indian River Preserve Golf Club'),
  ('United States', 'Indian Run Golf Club'),
  ('United States', 'Indian Run Golf Course'),
  ('United States', 'Indian Spring Country Club East Course'),
  ('United States', 'Indian Spring Country Club West Course'),
  ('United States', 'Indian Spring Golf Club'),
  ('United States', 'Indian Springs Country Club'),
  ('United States', 'Indian Springs Golf And Country Club'),
  ('United States', 'Indian Springs Golf Club'),
  ('United States', 'Indian Springs Golf Course'),
  ('United States', 'Indian Springs Metropark Golf Course'),
  ('United States', 'Indian Springs Ranch'),
  ('United States', 'Indian Summer Golf Country Club'),
  ('United States', 'Indian Trace Golf Course'),
  ('United States', 'Indian Trail Golf Course'),
  ('United States', 'Indian Trails Golf Course'),
  ('United States', 'Indian Valley Country Club'),
  ('United States', 'Indian Valley Golf Club'),
  ('United States', 'Indian Valley Golf Course'),
  ('United States', 'Indian Wells Country Club The Classic Course'),
  ('United States', 'Indian Wells Country Club The Cove Course'),
  ('United States', 'Indian Wells Golf Resort Celebrity Course'),
  ('United States', 'Indian Wells Golf Resort Players Course'),
  ('United States', 'Indiana Country Club'),
  ('United States', 'Indianhead Golf Course'),
  ('United States', 'Indianola Country Club'),
  ('United States', 'Indianwood Gold & Country Club'),
  ('United States', 'Indianwood Golf Country Club'),
  ('United States', 'Indigo Creek Golf Club'),
  ('United States', 'Indio Golf Club'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Eisenhower Course'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Zaharias Course'),
  ('United States', 'Ingersoll Golf Course'),
  ('United States', 'Ingleside Golf Club'),
  ('United States', 'Ingleside Resort Country Club'),
  ('United States', 'Inglewood Country Club'),
  ('United States', 'Inkster Valley Golf Course'),
  ('United States', 'Inland Greens Golf Course'),
  ('United States', 'Inlet Golf Club'),
  ('United States', 'Inn Of The Mountain Gods'),
  ('United States', 'Inness Golf Course'),
  ('United States', 'Innis Arden Golf Club'),
  ('United States', 'Innisbrook Resort Golf Club Copperhead Course'),
  ('United States', 'Innisbrook Resort Golf Club Fox Squirrel Course'),
  ('United States', 'Innisbrook Resort Golf Club Island Course'),
  ('United States', 'Innisbrook Resort Golf Club North Course'),
  ('United States', 'Innisbrook Resort Golf Club South Course'),
  ('United States', 'Inniscrone Golf Club'),
  ('United States', 'Innsbrook Country Club'),
  ('United States', 'Innsbrook Golf Course'),
  ('United States', 'Innsbrook Village Country Club'),
  ('United States', 'Inshalla Country Club'),
  ('United States', 'Interbay Family Golf Center'),
  ('United States', 'Interlachen Country Club'),
  ('United States', 'Interlaken Golf Club'),
  ('United States', 'Interlochen Golf Course'),
  ('United States', 'Interlocken Golf Club Eldorado Sunshine'),
  ('United States', 'Interlocken Golf Club Sunshine Vista'),
  ('United States', 'Interlocken Golf Club Vista Eldorado'),
  ('United States', 'International At Cedar Valley Golf Club'),
  ('United States', 'International City Golf Club'),
  ('United States', 'International Club Of Myrtle Beach'),
  ('United States', 'International Country Club'),
  ('United States', 'International Golf Club Oaks Course'),
  ('United States', 'International Golf Club Pines Course'),
  ('United States', 'Intervale Country Club'),
  ('United States', 'Intimidator Golf Course'),
  ('United States', 'Inver Wood Golf Course'),
  ('United States', 'Inverness Club'),
  ('United States', 'Inverness Country Club'),
  ('United States', 'Inverness Golf Club'),
  ('United States', 'Inverness Golf Country Club'),
  ('United States', 'Inverness Hotel Golf Club'),
  ('United States', 'Inverugie Golf Club'),
  ('United States', 'Inwood Country Club'),
  ('United States', 'Inwood Golf Course'),
  ('United States', 'Ipswich Country Club'),
  ('United States', 'Irem Country Club'),
  ('United States', 'Irene Golf And Country Club'),
  ('United States', 'Irish Green Golf Course'),
  ('United States', 'Irish Hills Golf Club'),
  ('United States', 'Irish Hills Shore Golf Course'),
  ('United States', 'Irish Oaks Golf Course and Driving Range'),
  ('United States', 'Irish Waters Golf Course'),
  ('United States', 'Iron Forge At Penn National Golf Club Inn'),
  ('United States', 'Iron Horse Golf Club'),
  ('United States', 'Iron Horse Golf Course'),
  ('United States', 'Iron Links Golf Course'),
  ('United States', 'Iron Masters Country Club'),
  ('United States', 'Iron Play Golf Course'),
  ('United States', 'Iron River Country Club'),
  ('United States', 'Iron Valley Golf Club'),
  ('United States', 'Iron Wolf Golf Country Club'),
  ('United States', 'Ironbridge Golf Club'),
  ('United States', 'Ironclad Golf And Beer Garden'),
  ('United States', 'Irondequoit Country Club'),
  ('United States', 'Ironhorse Golf Club'),
  ('United States', 'Ironwood Acacia At Kierland Golf Club'),
  ('United States', 'Ironwood Country Club'),
  ('United States', 'Ironwood Golf Club'),
  ('United States', 'Ironwood Golf Country Club'),
  ('United States', 'Ironwood Golf Course'),
  ('United States', 'Ironwood Golf Range'),
  ('United States', 'Ironwood Green Golf Course'),
  ('United States', 'Ironwood Hills Golf Club'),
  ('United States', 'Iroquois Golf Club'),
  ('United States', 'Iroquois Golf Course'),
  ('United States', 'Irv Warren Memorial Golf Course'),
  ('United States', 'Irwin Country Club'),
  ('United States', 'Isabella Golf Course Nina'),
  ('United States', 'Isabella Golf Course Pinta'),
  ('United States', 'Isabella Golf Course Santa Maria'),
  ('United States', 'Ischua Valley Country Club'),
  ('United States', 'Isla Del Sol Golf Yacht Country Club'),
  ('United States', 'Island At Holiday Island Country Club'),
  ('United States', 'Island Country Club'),
  ('United States', 'Island Dunes Country Club'),
  ('United States', 'Island Green Golf Course'),
  ('United States', 'Island Green Longest Hole At Meadows Farms Golf Course'),
  ('United States', 'Island Green Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Island Hills Golf Club'),
  ('United States', 'Island Lake Golf'),
  ('United States', 'Island Oaks At Lima Golf Country Club'),
  ('United States', 'Island Park Village Resort'),
  ('United States', 'Island Pines Golf Club'),
  ('United States', 'Island Valley Golf Course'),
  ('United States', 'Island West Golf Club'),
  ('United States', 'Islands End Golf Country Club'),
  ('United States', 'Isle Dauphine Golf Club'),
  ('United States', 'Isleta Eagle Golf Course Arroyo Mesa Course'),
  ('United States', 'Isleta Eagle Golf Course Lakes Arroyo Course'),
  ('United States', 'Isleta Eagle Golf Course Mesa Lakes Course'),
  ('United States', 'Isleworth Country Club'),
  ('United States', 'Itasca Country Club'),
  ('United States', 'Iuka Country Club'),
  ('United States', 'Ivanhoe Club'),
  ('United States', 'Ives Grove Golf Links'),
  ('United States', 'Ives Hill Country Club'),
  ('United States', 'Ivey Ranch Country Club'),
  ('United States', 'Ivy Hill Golf Club'),
  ('United States', 'Ivy Hills Country Club'),
  ('United States', 'Iyopawa Island Golf Course'),
  ('United States', 'J B Golf Course'),
  ('United States', 'J F Kennedy Golf Center Par 3 Course'),
  ('United States', 'J F Kennedy Golf Center West Creek Course'),
  ('United States', 'J S Clark Park Golf Course'),
  ('United States', 'Jacaranda West Country Club'),
  ('United States', 'Jack Frost National Golf Course'),
  ('United States', 'Jack Olantern Golf Resort'),
  ('United States', 'Jackpot Golf Club'),
  ('United States', 'Jackson College Disc Golf'),
  ('United States', 'Jackson County Country Club'),
  ('United States', 'Jackson Golf Club'),
  ('United States', 'Jackson Heights Golf Club'),
  ('United States', 'Jackson Hole Golf Tennis Club'),
  ('United States', 'Jackson Park Driving Range'),
  ('United States', 'Jackson Park Golf Course'),
  ('United States', 'Jackson Valley Country Club'),
  ('United States', 'Jacksonville Beach Golf Club'),
  ('United States', 'Jacksonville Country Club'),
  ('United States', 'Jacksonville Golf Country Club'),
  ('United States', 'Jacob Riis Park Golf Course'),
  ('United States', 'Jacoby Golf Course'),
  ('United States', 'Jade Trace At Mystic Meadows'),
  ('United States', 'Jake Gaither Municipal Golf Course'),
  ('United States', 'Jal Country Club'),
  ('United States', 'James Baird State Park Golf Course'),
  ('United States', 'James C Haggerty North Kern Golf Course'),
  ('United States', 'James E Stewart Golf Course'),
  ('United States', 'James River Country Club'),
  ('United States', 'Jamestown Golf Course'),
  ('United States', 'Jamestown Park Golf Course'),
  ('United States', 'Janesville Country Club'),
  ('United States', 'Jasper Hills Golf Club'),
  ('United States', 'Jato Highlands Golf Course'),
  ('United States', 'Jawbone Creek Country Club'),
  ('United States', 'Jay Peak Golf Course'),
  ('United States', 'Jaycee Golf Course'),
  ('United States', 'Jefferson Barracks Golf Tee'),
  ('United States', 'Jefferson Country Club'),
  ('United States', 'Jefferson District Golf Course'),
  ('United States', 'Jefferson Golf Club'),
  ('United States', 'Jefferson Hills Golf Recreation'),
  ('United States', 'Jefferson Lakeside Country Club'),
  ('United States', 'Jefferson Landing On The New River'),
  ('United States', 'Jeffersonville Golf Club'),
  ('United States', 'Jekyll Island Golf Club Great Dunes Course'),
  ('United States', 'Jekyll Island Golf Club Indian Mound Course'),
  ('United States', 'Jekyll Island Golf Club Pine Lakes Course'),
  ('United States', 'Jennings Golf Club'),
  ('United States', 'Jennings Mill Country Club'),
  ('United States', 'Jenny Wiley State Resort Park'),
  ('United States', 'Jensen Beach Golf Club'),
  ('United States', 'Jeptha Lake Golf Course'),
  ('United States', 'Jeremy Ranch Golf Country Club'),
  ('United States', 'Jeremy S Creek'),
  ('United States', 'Jericho National Golf Club'),
  ('United States', 'Jerome Country Club'),
  ('United States', 'Jerry Tim Brooks Golf Course'),
  ('United States', 'Jester Park Executive Golf Course'),
  ('United States', 'Jester Park Golf Course'),
  ('United States', 'Jester Park Learning and Practice Facility'),
  ('United States', 'Jesup Golf & Country Club'),
  ('United States', 'Jewel Golf Course - Grand Nine'),
  ('United States', 'Jewel Golf Course - Woods Nine'),
  ('United States', 'Jewell Golf and Country Club'),
  ('United States', 'Jimmie Austin Golf Course'),
  ('United States', 'Jimmie Austin University Of Oklahoma Golf Course'),
  ('United States', 'Jo Daddys Golf Course'),
  ('United States', 'Joa Company Golf Course'),
  ('United States', 'Joe Louis "The Champ" Golf Course'),
  ('United States', 'John A White Golf Course'),
  ('United States', 'John Conrad Golf Course'),
  ('United States', 'John F Byrne Golf Course'),
  ('United States', 'John James Audubon Golf Course'),
  ('United States', 'John P Larkin Country Club'),
  ('United States', 'John Prince Golf Learning Center'),
  ('United States', 'Johnny Goodman Golf Course'),
  ('United States', 'Johnson County Country Club'),
  ('United States', 'Johnson Park Golf Course'),
  ('United States', 'Johnson Ridge Golf Course'),
  ('United States', 'Johnson W Parks Golf Course'),
  ('United States', 'Joliet Country Club (closed)'),
  ('United States', 'Jonathans Landing Golf Club Match Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Club Medal Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Course'),
  ('United States', 'Jonathans Landing Village Course'),
  ('United States', 'Jones At Lyman Orchards Golf Club'),
  ('United States', 'Jones At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Jones Beach State Park Golf Course'),
  ('United States', 'Jones Golf Course'),
  ('United States', 'Jones Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Jones Masterpiece At Treetops Resort'),
  ('United States', 'Jonesboro Country Club'),
  ('United States', 'Jordan River Par Three Golf Course'),
  ('United States', 'Joseph C Martin Golf Course'),
  ('United States', 'Joseph M Bartholomew Golf Course'),
  ('United States', 'Journey At Pechanga'),
  ('United States', 'Journey S End Golf Course'),
  ('United States', 'Jrs Pub Grill Golf Course'),
  ('United States', 'Juan De Fuca Parks Golf Club'),
  ('United States', 'Juday Creek Golf Course'),
  ('United States', 'Judge Rodney S. Webb Memorial Golf Park'),
  ('United States', 'Judith Shadows Golf Course'),
  ('United States', 'Jug Mountain Ranch Golf Course'),
  ('United States', 'Juliette Falls'),
  ('United States', 'Julington Creek Golf Club'),
  ('United States', 'Jumping Brook Country Club'),
  ('United States', 'Junction City Golf Course'),
  ('United States', 'Jungle At Green Meadow Golf Club'),
  ('United States', 'Juniata Golf Club'),
  ('United States', 'Junior National Golf Club'),
  ('United States', 'Juniper Hill Golf Course'),
  ('United States', 'Juniper Hills Country Club'),
  ('United States', 'Juniper Ridge R V Resort'),
  ('United States', 'Jupiter Country Club'),
  ('United States', 'Jupiter Dunes Golf Course'),
  ('United States', 'Jupiter Island Club'),
  ('United States', 'Jurupa Hills Country Club'),
  ('United States', 'Kaanapali Kai'),
  ('United States', 'Kah Wah C Country Club'),
  ('United States', 'Kahili Golf Course'),
  ('United States', 'Kahkwa Club'),
  ('United States', 'Kahler Mountain Club'),
  ('United States', 'Kahuku Golf Course'),
  ('United States', 'Kalamazoo Country Club'),
  ('United States', 'Kalispel Golf Country Club'),
  ('United States', 'Kalona Golf Club'),
  ('United States', 'Kaluhyat Golf Club At Turning Stone'),
  ('United States', 'Kampen Golf Course'),
  ('United States', 'Kane Country Club'),
  ('United States', 'Kaneohe Klipper Golf Course'),
  ('United States', 'Kankakee Country Club'),
  ('United States', 'Kankakee Elks Country Club'),
  ('United States', 'Kanon Valley Country Club'),
  ('United States', 'Kansas City Country Club'),
  ('United States', 'Kapalua Resort The Bay Course'),
  ('United States', 'Kapalua Resort The Plantation Course'),
  ('United States', 'Kapolei Golf Club'),
  ('United States', 'Karsten Creek Golf Club'),
  ('United States', 'Katahdin Country Club'),
  ('United States', 'Katke Golf Course'),
  ('United States', 'Kaufman Golf Course'),
  ('United States', 'Kaylers Bend Golf Course'),
  ('United States', 'Ke Olu Course At Hualalai'),
  ('United States', 'Kealohi Par 3 Golf Course'),
  ('United States', 'Kearny Golf Club'),
  ('United States', 'Kearsley Lake Golf Course'),
  ('United States', 'Kebo Valley Club'),
  ('United States', 'Keene Country Club'),
  ('United States', 'Keith Hills Golf Club Black Course'),
  ('United States', 'Keith Hills Golf Club Orange Course'),
  ('United States', 'Keith Hills Golf Club White Course'),
  ('United States', 'Kelley Greens Golf Course'),
  ('United States', 'Kellogg Executive 9'),
  ('United States', 'Kellogg Golf Course'),
  ('United States', 'Kelly Greens Golf Country Club'),
  ('United States', 'Kelly Plantation Golf Club'),
  ('United States', 'Kelly''s Miniature Golf'),
  ('United States', 'Kemper Lakes Golf Club'),
  ('United States', 'Kempsville Greens Golf Course'),
  ('United States', 'Ken Mcdonald Golf Course'),
  ('United States', 'Kenai Golf Course'),
  ('United States', 'Kendrick Golf Course'),
  ('United States', 'Kenduskeag Valley Golf Club'),
  ('United States', 'Keney Park Golf Club'),
  ('United States', 'Kenmure Country Club'),
  ('United States', 'Kennett Country Club'),
  ('United States', 'Kennett Square Golf Country Club'),
  ('United States', 'Kenosha Country Club'),
  ('United States', 'Kensington Driving Range'),
  ('United States', 'Kensington Golf Club'),
  ('United States', 'Kensington Golf Country Club'),
  ('United States', 'Kensington Metropark Golf Course'),
  ('United States', 'Kent Country Club'),
  ('United States', 'Kenterra Golf Course'),
  ('United States', 'Kenton Station Golf Course'),
  ('United States', 'Kentucky Dam Village State Resort Park'),
  ('United States', 'Kenwanda Golf Course'),
  ('United States', 'Kenwood Country Club'),
  ('United States', 'Kenwood Golf Country Club'),
  ('United States', 'Kenya Hemingway At Havana Country Club'),
  ('United States', 'Kenyon Country Club'),
  ('United States', 'Keokuk Country Club'),
  ('United States', 'Keowee Key Golf Country Club'),
  ('United States', 'Kern River Golf Course'),
  ('United States', 'Kern Valley Golf Course'),
  ('United States', 'Kernoustie Golf Club'),
  ('United States', 'Kernwood Country Club'),
  ('United States', 'Kerr Lake Country Club'),
  ('United States', 'Kershaw Country Club'),
  ('United States', 'Kestrel Ridge Golf Club'),
  ('United States', 'Kettle Brook Golf Club'),
  ('United States', 'Kettle Hills Golf Course'),
  ('United States', 'Kettle Valley Golf Club'),
  ('United States', 'Kewanee Dunes Golf Club'),
  ('United States', 'Keweenaw Mountain Lodge Golf Course'),
  ('United States', 'Key Colony Beach Golf Tennis'),
  ('United States', 'Key Royale Club'),
  ('United States', 'Key Vista Country Club'),
  ('United States', 'Key West Golf Club'),
  ('United States', 'Keyhole Country Club'),
  ('United States', 'Keystone Golf Country Club'),
  ('United States', 'Keystone Golf Course'),
  ('United States', 'Keystone Ranch Golf Course'),
  ('United States', 'Kiahuna Golf Club'),
  ('United States', 'Kiawah Island Club Cassique Course'),
  ('United States', 'Kiawah Island Club River Course'),
  ('United States', 'Kickingbird Golf Club'),
  ('United States', 'Kilgores Roundabout Plantation Golf Course'),
  ('United States', 'Kilimanjaro Kenya At Havana Country Club'),
  ('United States', 'Kilkarney Hills Golf Course'),
  ('United States', 'Killarney Lakeside Golf Club'),
  ('United States', 'Killian Greens Golf Club'),
  ('United States', 'Killington Golf Resort'),
  ('United States', 'Kilmarlic Golf Club'),
  ('United States', 'Kiln Creek Golf Club Resort'),
  ('United States', 'Kimball Farm Golf Club'),
  ('United States', 'Kimball Golf Club'),
  ('United States', 'Kimbeland Country Club'),
  ('United States', 'Kimberly Oaks Golf Club'),
  ('United States', 'Kimberton Golf Club'),
  ('United States', 'Kincaid Lake Golf Course'),
  ('United States', 'Kinderlou Forest Golf Club'),
  ('United States', 'Kinderton Country Club'),
  ('United States', 'King And Bear Golf Course At World Golf Village'),
  ('United States', 'King City Golf Course'),
  ('United States', 'King Ferry Golf Club'),
  ('United States', 'King Kamehameha Golf Club'),
  ('United States', 'King Links Golf Course'),
  ('United States', 'King Rail Reserve Golf Course'),
  ('United States', 'King Ranch Golf Course'),
  ('United States', 'King Valley Golf Course'),
  ('United States', 'King''s Walk'),
  ('United States', 'Kingfisher Golf Course'),
  ('United States', 'Kingham Prairie View Golf Course'),
  ('United States', 'Kings Arrow Ranch Hillsdale Course'),
  ('United States', 'Kings Country Club'),
  ('United States', 'Kings Creek Country Club'),
  ('United States', 'Kings Crossing Golf Club'),
  ('United States', 'Kings Deer Golf Club'),
  ('United States', 'Kings Gate Golf Club'),
  ('United States', 'Kings Grant Golf Country Club'),
  ('United States', 'Kings Mountain Country Club'),
  ('United States', 'Kings Mountain Golf Course'),
  ('United States', 'Kings Point Executive Course'),
  ('United States', 'Kings Point Executive Golf Course'),
  ('United States', 'Kings Point Par 3')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Kings Ridge Golf Club Kings Course'),
  ('United States', 'Kings Ridge Golf Club Ridge Course'),
  ('United States', 'Kings River Golf Country Club'),
  ('United States', 'Kings River Golf Course'),
  ('United States', 'Kings Valley Golf Course'),
  ('United States', 'Kings Walk'),
  ('United States', 'Kings Way Golf Club'),
  ('United States', 'Kingsboro Golf Club'),
  ('United States', 'Kingsmill Resort Plantation Course'),
  ('United States', 'Kingsmill Resort River Course'),
  ('United States', 'Kingston Fairways Golf Club'),
  ('United States', 'Kingsville Golf & Country Club'),
  ('United States', 'Kingswell Glen'),
  ('United States', 'Kingswood Golf Club'),
  ('United States', 'Kingwood Golf Club Resort'),
  ('United States', 'Kinkora Golf Course'),
  ('United States', 'Kinloch Golf Club'),
  ('United States', 'Kino Springs Golf Course'),
  ('United States', 'Kinsale Golf Club'),
  ('United States', 'Kinsale Golf and Fitness Club'),
  ('United States', 'Kinsley Country Club'),
  ('United States', 'Kinston Country Club'),
  ('United States', 'Kira S Kingdom Golf Course'),
  ('United States', 'Kirby Country Club'),
  ('United States', 'Kirkbrae Country Club'),
  ('United States', 'Kirkmans Lakeview Golf Course'),
  ('United States', 'Kirkwood National Golf Club'),
  ('United States', 'Kis N Greens Golf Course'),
  ('United States', 'Kishwaukee Country Club'),
  ('United States', 'Kiski Prep School Golf Course'),
  ('United States', 'Kiskiack Golf Club'),
  ('United States', 'Kissena Park Golf Course'),
  ('United States', 'Kissimmee Bay Country Club'),
  ('United States', 'Kissing Tree Golf Club'),
  ('United States', 'Kitsap Golf Country Club'),
  ('United States', 'Kittanning Country Club'),
  ('United States', 'Klinger Lake Country Club'),
  ('United States', 'Knickerbocker Country Club'),
  ('United States', 'Knights Play Golf Center'),
  ('United States', 'Knights Play Golf Center 9 Hole Par 3'),
  ('United States', 'Knights of Columbus Par 3 Course'),
  ('United States', 'Knob Hill Golf Course'),
  ('United States', 'Knobbs Creek Par 3 Golf Course'),
  ('United States', 'Knoll East Country Club The'),
  ('United States', 'Knoll Run Golf Course'),
  ('United States', 'Knoll View Golf Course'),
  ('United States', 'Knoll West Country Club'),
  ('United States', 'Knolls Country Club'),
  ('United States', 'Knollwood Club Golf Course'),
  ('United States', 'Knollwood Country Club'),
  ('United States', 'Knollwood Country Club - East Course'),
  ('United States', 'Knollwood Country Club - West Course'),
  ('United States', 'Knollwood Fairways'),
  ('United States', 'Knollwood Golf Course'),
  ('United States', 'Ko Olina Golf Club'),
  ('United States', 'Koa Fairways Golf Course'),
  ('United States', 'Koasati Pines At Coushatta'),
  ('United States', 'Kohala Golf Park'),
  ('United States', 'Kohanaiki Club'),
  ('United States', 'Kokomo Country Club'),
  ('United States', 'Kokopelli Club'),
  ('United States', 'Kokopelli Golf Course'),
  ('United States', 'Kona Country Club'),
  ('United States', 'Kona Mansion Inn'),
  ('United States', 'Koronis Hills Golf Club'),
  ('United States', 'Koshkonong Mounds Country Club'),
  ('United States', 'Kountryside Golf Course'),
  ('United States', 'Kraftsmens Club'),
  ('United States', 'Kresson Golf Club'),
  ('United States', 'Krooked Kreek Golf Course'),
  ('United States', 'Krueger-Haskell Golf Course'),
  ('United States', 'Kuehn Golf Course'),
  ('United States', 'Kukio 10 Hole Course'),
  ('United States', 'Kukio Championship Course'),
  ('United States', 'Kukuiolono Golf Course'),
  ('United States', 'Kukuiula Golf Course'),
  ('United States', 'Kulm Golf Club'),
  ('United States', 'Kwiniaska Golf Club'),
  ('United States', 'Kyle Memorial Golf Course'),
  ('United States', 'L A Golf Club'),
  ('United States', 'L W Clapp Golf Club'),
  ('United States', 'L''Anse Golf Club'),
  ('United States', 'L.C. Boles Golf Course Holes 1-2,9'),
  ('United States', 'L.C. Boles Golf Course Holes 3-8'),
  ('United States', 'LYNX Golf Course & Grill'),
  ('United States', 'La Canada Flintridge Country Club'),
  ('United States', 'La Cita Country Club'),
  ('United States', 'La Contenta Golf Club'),
  ('United States', 'La Crosse Country Club'),
  ('United States', 'La Cumbre Country Club'),
  ('United States', 'La Gorce Country Club'),
  ('United States', 'La Grange Country Club'),
  ('United States', 'La Jolla Beach Tennis Club'),
  ('United States', 'La Jolla Country Club'),
  ('United States', 'La Junta Golf Course'),
  ('United States', 'La Mirada Golf Club'),
  ('United States', 'La Porte City Golf Club'),
  ('United States', 'La Purisima Golf Course'),
  ('United States', 'La Quinta Country Club'),
  ('United States', 'La Quinta Resort Citrus Course'),
  ('United States', 'La Rinconada Country Club'),
  ('United States', 'La Valle Coastal Club East South Course'),
  ('United States', 'La Valle Coastal Club North East Course'),
  ('United States', 'La Valle Coastal Club South North Course'),
  ('United States', 'La Vida Country Club'),
  ('United States', 'La Vista El Cielo At Desert Princess Country Club'),
  ('United States', 'Lac Vieux Desert Golf Course'),
  ('United States', 'Lacoma Golf Course'),
  ('United States', 'Laconia Country Club'),
  ('United States', 'Ladera Golf Club'),
  ('United States', 'Ladera Golf Course Championship Course'),
  ('United States', 'Ladera Golf Course Executive Course'),
  ('United States', 'Lafayette Club'),
  ('United States', 'Lafayette Country Club'),
  ('United States', 'Lafayette Municipal Golf Course'),
  ('United States', 'Lafollette Country Club'),
  ('United States', 'Lafortune Park At Lafortune Park Golf Course'),
  ('United States', 'Lago Mar Country Club'),
  ('United States', 'Lagoon At Ponte Vedra Inn Club'),
  ('United States', 'Lagos Acres Golf & Country Club'),
  ('United States', 'Laguna Lake Golf Course'),
  ('United States', 'Laguna Oaks Golf Course'),
  ('United States', 'Laguna Seca Golf Club'),
  ('United States', 'Laguna Woods Golf Club 1 2 Course'),
  ('United States', 'Laguna Woods Golf Club 1 3 Course'),
  ('United States', 'Laguna Woods Golf Club 2 3 Course'),
  ('United States', 'Laguna Woods Golf Club Par 3 Course'),
  ('United States', 'Lahontan Golf Club'),
  ('United States', 'Lahontan Golf Club The Par 3 Course'),
  ('United States', 'Lake Almanor Country Club'),
  ('United States', 'Lake Almanor West Golf Course'),
  ('United States', 'Lake Arbor Golf Course'),
  ('United States', 'Lake Arrowhead Country Club'),
  ('United States', 'Lake Arrowhead Yacht Country Club Highlands Course'),
  ('United States', 'Lake Arthur Country Club'),
  ('United States', 'Lake Ashton Golf Club The East Course'),
  ('United States', 'Lake Ashton Golf Club The West Course'),
  ('United States', 'Lake At Carolina Trace Country Club'),
  ('United States', 'Lake At Mountain Dell Golf Course'),
  ('United States', 'Lake At Wasatch Mountain State Park'),
  ('United States', 'Lake Barrington Shores Golf Club'),
  ('United States', 'Lake Barton Golf Course'),
  ('United States', 'Lake Bess Country Club'),
  ('United States', 'Lake Bluff Golf Course'),
  ('United States', 'Lake Bonaventure Country Club'),
  ('United States', 'Lake Breeze Golf Club'),
  ('United States', 'Lake Bruin Golf Country Club'),
  ('United States', 'Lake Carlsbad Golf Course Championship Course'),
  ('United States', 'Lake Carlsbad Golf Course Par 3 Course'),
  ('United States', 'Lake Caroline Golf Club'),
  ('United States', 'Lake Carroll Golf Club'),
  ('United States', 'Lake Chabot Golf Course Executive Par 3 Course'),
  ('United States', 'Lake Chabot Golf Course The 18 Hole Course'),
  ('United States', 'Lake Charles Country Club'),
  ('United States', 'Lake Chelan Golf Course'),
  ('United States', 'Lake Chesdin Golf Club'),
  ('United States', 'Lake City Country Club'),
  ('United States', 'Lake City Golf'),
  ('United States', 'Lake Cora Hills'),
  ('United States', 'Lake Cushman Golf Course'),
  ('United States', 'Lake Darbonne Country Club'),
  ('United States', 'Lake Diamond Golf Country Club'),
  ('United States', 'Lake Doster Golf Club'),
  ('United States', 'Lake Erie Metropark Golf Course'),
  ('United States', 'Lake Estes Executive 9 Hole Course'),
  ('United States', 'Lake Fairways Country Club'),
  ('United States', 'Lake Forest Country Club'),
  ('United States', 'Lake Forest Golf Club'),
  ('United States', 'Lake Forest Golf Practice Center'),
  ('United States', 'Lake Gaston Golf Club'),
  ('United States', 'Lake Geneva Country Club'),
  ('United States', 'Lake Hallie Golf'),
  ('United States', 'Lake Havasu Golf Club East Course'),
  ('United States', 'Lake Havasu Golf Club West Course'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Dogwood'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Fox Run'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Sulphur Springs'),
  ('United States', 'Lake Hickory Country Club Town Course'),
  ('United States', 'Lake Hills Golf Club'),
  ('United States', 'Lake Isle Country Club'),
  ('United States', 'Lake James Golf Course'),
  ('United States', 'Lake Jonesco Golf Course'),
  ('United States', 'Lake Jovita Golf Country Club North Course'),
  ('United States', 'Lake Jovita Golf Country Club South Course'),
  ('United States', 'Lake Junaluska Golf Course'),
  ('United States', 'Lake June West Golf Course'),
  ('United States', 'Lake Kezar Country Club'),
  ('United States', 'Lake Kiowa Country Club'),
  ('United States', 'Lake Lackawanna Golf Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Ii Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Iii Course'),
  ('United States', 'Lake Land Village Golf Course Generation Ii Iii Course'),
  ('United States', 'Lake Leann Golf Course'),
  ('United States', 'Lake Limerick Country Club'),
  ('United States', 'Lake Lindero Golf Course'),
  ('United States', 'Lake Lorain Golf Club'),
  ('United States', 'Lake Lure Municipal Golf Course'),
  ('United States', 'Lake MacBride Golf Course'),
  ('United States', 'Lake Marion Golf Course'),
  ('United States', 'Lake Merced Golf Country Club'),
  ('United States', 'Lake Michigan Hills Golf Club'),
  ('United States', 'Lake Mills Golf Course'),
  ('United States', 'Lake Mohawk Golf Club'),
  ('United States', 'Lake Monterey Golf Course'),
  ('United States', 'Lake Monticello Golf Course'),
  ('United States', 'Lake Morey Inn Resort Country Club'),
  ('United States', 'Lake Mountain At Stratton Mountain Country Club'),
  ('United States', 'Lake Murray Golf Center'),
  ('United States', 'Lake Murray State Park Golf Course'),
  ('United States', 'Lake Nona Golf Country Club'),
  ('United States', 'Lake North At Mountain Gate Country Club'),
  ('United States', 'Lake Of The Forest Golf Course'),
  ('United States', 'Lake Of The Pines Country Club'),
  ('United States', 'Lake Of The Woods Country Club'),
  ('United States', 'Lake Oroville Golf Country Club'),
  ('United States', 'Lake Padden Golf Course'),
  ('United States', 'Lake Panorama National Golf Course'),
  ('United States', 'Lake Park Golf Course'),
  ('United States', 'Lake Pepin Golf Course'),
  ('United States', 'Lake Perry Country Club'),
  ('United States', 'Lake Pine Golf Course At Countryside Country Club'),
  ('United States', 'Lake Placid Club Links Course'),
  ('United States', 'Lake Placid Club Mountain Course'),
  ('United States', 'Lake Placid Club Pristine Nine Course'),
  ('United States', 'Lake Platte Golf Club'),
  ('United States', 'Lake Pleasant Golf Club'),
  ('United States', 'Lake Pleasant Golf Course'),
  ('United States', 'Lake Powell National Golf Course'),
  ('United States', 'Lake Providence Country Club'),
  ('United States', 'Lake Quivira Country Club'),
  ('United States', 'Lake Redding Golf Course'),
  ('United States', 'Lake Ridge Park Golf Marina'),
  ('United States', 'Lake Ripley Country Club'),
  ('United States', 'Lake Saint Louis 9-Hole Golf Course'),
  ('United States', 'Lake Shawnee Golf Course'),
  ('United States', 'Lake Shore Country Club'),
  ('United States', 'Lake Shore Course At Lake Shore Country Club'),
  ('United States', 'Lake Shore Golf Club'),
  ('United States', 'Lake Side Golf Course'),
  ('United States', 'Lake Spanaway Golf Course'),
  ('United States', 'Lake Spivey Golf Club'),
  ('United States', 'Lake St Catherine Country Club'),
  ('United States', 'Lake Success Golf Club'),
  ('United States', 'Lake Sunapee Country Club'),
  ('United States', 'Lake Superior View Golf'),
  ('United States', 'Lake Tahoe Golf Course'),
  ('United States', 'Lake Tamarisk Golf Course'),
  ('United States', 'Lake Toxaway Country Club'),
  ('United States', 'Lake Valley At Los Coyotes Country Club'),
  ('United States', 'Lake Valley At Pinery Country Club'),
  ('United States', 'Lake Valley Golf Club'),
  ('United States', 'Lake View At Callaway Gardens Resort'),
  ('United States', 'Lake View Country Club'),
  ('United States', 'Lake View Executive Golf Course'),
  ('United States', 'Lake View National Golf Course'),
  ('United States', 'Lake Village Country Club'),
  ('United States', 'Lake Wales Country Club'),
  ('United States', 'Lake Waramaug Country Club'),
  ('United States', 'Lake Wilderness Golf Course'),
  ('United States', 'Lake Wildwood Golf Course'),
  ('United States', 'Lake Winds Golf Course'),
  ('United States', 'Lake Windsor Country Club'),
  ('United States', 'Lake Winnipesaukee Golf Club'),
  ('United States', 'Lake Wisconsin Country Club'),
  ('United States', 'Lake Wissota Golf & Events'),
  ('United States', 'Lake Woods At Tri Cities Golf Course'),
  ('United States', 'Lake Woods Golf Club'),
  ('United States', 'Lake Worth Beach Golf Club'),
  ('United States', 'Lake Zurich Golf Club'),
  ('United States', 'Lake o'' the Hills Golf Course'),
  ('United States', 'Lake of the Sandhills'),
  ('United States', 'Lake of the Woods Golf Course'),
  ('United States', 'Lakeland Golf Club'),
  ('United States', 'Lakeland Hills Golf Course'),
  ('United States', 'Lakelands Golf and Country Club'),
  ('United States', 'Lakemont At Stone Mountain Golf Course'),
  ('United States', 'Lakeridge Golf Course'),
  ('United States', 'Lakes At Bear Lakes Country Club'),
  ('United States', 'Lakes At Blackhawk Country Club'),
  ('United States', 'Lakes At Boca Woods Country Club'),
  ('United States', 'Lakes At Colonial Springs Golf Course'),
  ('United States', 'Lakes At El Segundo The'),
  ('United States', 'Lakes At Leesburg'),
  ('United States', 'Lakes At North Ridge Country Club'),
  ('United States', 'Lakes At Palm Aire Country Club'),
  ('United States', 'Lakes At Quail West Golf Country Club'),
  ('United States', 'Lakes At Sandridge Golf Club'),
  ('United States', 'Lakes At Windy Hill Golf Course'),
  ('United States', 'Lakes Canyon At Blacklake Golf Course'),
  ('United States', 'Lakes Course At Genoa Lakes Golf Club'),
  ('United States', 'Lakes Cypress At Arrowhead Country Club'),
  ('United States', 'Lakes Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'Lakes Dunes At Gainey Ranch Golf Club'),
  ('United States', 'Lakes Fairways At Centennial Golf Club'),
  ('United States', 'Lakes Golf Course At Laura Walker State Park'),
  ('United States', 'Lakes Golf Course At Oakwood Country Club'),
  ('United States', 'Lakes Meadows At Centennial Golf Club'),
  ('United States', 'Lakes Oaks At Blacklake Golf Course'),
  ('United States', 'Lakes Oaks At Hacienda Hills Golf Country Club'),
  ('United States', 'Lakes Orchard At Treesdale Golf Country Club'),
  ('United States', 'Lakes Pines At Star Hill Golf Country Club'),
  ('United States', 'Lakes River Golf Course Cocoa Beach Country Club'),
  ('United States', 'Lakes Sound Course At Pelican Sound Golf River Club'),
  ('United States', 'Lakes Sunrise At Spanish Trail Country Club'),
  ('United States', 'Lakes Valley At North Ranch Country Club'),
  ('United States', 'Lakes Valley At Valley Oaks Golf Club'),
  ('United States', 'Lakes Waterway At Arrowhead Country Club'),
  ('United States', 'Lakes of Taylor Golf Club'),
  ('United States', 'Lakes of the Four Seasons Golf Course'),
  ('United States', 'Lakeshore Golf Course'),
  ('United States', 'Lakeshore Golf and Country Club'),
  ('United States', 'Lakeshore Yacht Country Club'),
  ('United States', 'Lakeside At Golf Club Of Georgia The'),
  ('United States', 'Lakeside At Juniper Hill Golf Course'),
  ('United States', 'Lakeside Country Club'),
  ('United States', 'Lakeside Golf Club'),
  ('United States', 'Lakeside Golf Course'),
  ('United States', 'Lakeside Links'),
  ('United States', 'Lakeside Memorial Golf Course'),
  ('United States', 'Lakeside Municipal Golf Course'),
  ('United States', 'Lakeside Park Golf Club'),
  ('United States', 'Lakeside Pines At Blue Hill Golf Course'),
  ('United States', 'Lakeside Village Golf Athletic Club'),
  ('United States', 'Lakeview Bayview At A C Read Golf Course'),
  ('United States', 'Lakeview Country Club'),
  ('United States', 'Lakeview Golf And Country Club'),
  ('United States', 'Lakeview Golf Club'),
  ('United States', 'Lakeview Golf Club Eagle Eye Par 3 Course'),
  ('United States', 'Lakeview Golf Club Lake Course'),
  ('United States', 'Lakeview Golf Club Mountain Course'),
  ('United States', 'Lakeview Golf Club Peak Course'),
  ('United States', 'Lakeview Golf Country Club'),
  ('United States', 'Lakeview Golf Course'),
  ('United States', 'Lakeview Golf Resort Lakeview Course'),
  ('United States', 'Lakeview Golf Resort Mountainview Course'),
  ('United States', 'Lakeview Hills Golf Resort - North Course'),
  ('United States', 'Lakeview Hills Golf Resort - South Course'),
  ('United States', 'Lakeview Municipal Golf Course'),
  ('United States', 'Lakeview Par 3 Golf Challenge'),
  ('United States', 'Lakeview Springs Golf'),
  ('United States', 'Lakeville Country Club'),
  ('United States', 'Lakevue North Golf Course'),
  ('United States', 'Lakewood Country Club'),
  ('United States', 'Lakewood Golf Club'),
  ('United States', 'Lakewood Golf Country Club'),
  ('United States', 'Lakewood Golf Course'),
  ('United States', 'Lakewood Links'),
  ('United States', 'Lakewood National Golf Club Commander Course'),
  ('United States', 'Lakewood National Golf Club Piper Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Cypress Links Course'),
  ('United States', 'Lakewood Ranch Golf Country Club King Dunes Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Royal Lakes Course'),
  ('United States', 'Lakewood on the Green'),
  ('United States', 'Lakin Country Club'),
  ('United States', 'Lakota Links Golf Club'),
  ('United States', 'Lamoine Valley Golf Club'),
  ('United States', 'Lamoni Golf and Country Club'),
  ('United States', 'Lamont Hill Resort'),
  ('United States', 'Lampman Golf Club'),
  ('United States', 'Lancaster Country Club'),
  ('United States', 'Lancaster Golf Center'),
  ('United States', 'Lancaster Golf Club'),
  ('United States', 'Lancaster Host Golf Resort'),
  ('United States', 'Lancaster Riverside Golf Club'),
  ('United States', 'Land O Lakes Golf Club'),
  ('United States', 'Lander Golf Country Club'),
  ('United States', 'Landings Golf Club'),
  ('United States', 'Landings Yacht Golf Tennis Club'),
  ('United States', 'Landis Creek Golf Club'),
  ('United States', 'Landsmeer Golf Club'),
  ('United States', 'Lane County Country Club'),
  ('United States', 'Lane Creek Golf Club'),
  ('United States', 'Lane Tree Golf Club'),
  ('United States', 'Langbrook Meadows Golf Country Club'),
  ('United States', 'Langendorf Park Golf Course'),
  ('United States', 'Langley Golf Club'),
  ('United States', 'Langston Golf Course'),
  ('United States', 'Lanier Islands Resort Legacy Golf Course'),
  ('United States', 'Lanier Islands Resort The Six'),
  ('United States', 'Lansbrook Golf Club'),
  ('United States', 'Lansdowne Resort Shark Bite Course'),
  ('United States', 'Lansdowne Resort The Norman Course'),
  ('United States', 'Lansdowne Resort The Robert Trent Jones Ii Course'),
  ('United States', 'Lansing Country Club'),
  ('United States', 'Lapeer Country Club'),
  ('United States', 'Laplaya Beach Golf Resort'),
  ('United States', 'Larchmont Golf Course'),
  ('United States', 'Largo Golf Course'),
  ('United States', 'Larimore Golf Club'),
  ('United States', 'Larned Country Club'),
  ('United States', 'Larry Gannon Municipal Golf Course'),
  ('United States', 'Las Animas Golf Course'),
  ('United States', 'Las Barrancas Golf Course'),
  ('United States', 'Las Campanas Sunrise Course'),
  ('United States', 'Las Campanas Sunset Course'),
  ('United States', 'Las Colinas Golf Club'),
  ('United States', 'Las Posas Country Club'),
  ('United States', 'Las Sendas Golf Club'),
  ('United States', 'Las Vegas Country Club'),
  ('United States', 'Las Vegas Golf Center')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Las Vegas Golf Club'),
  ('United States', 'Las Vegas National Golf Course'),
  ('United States', 'Lasalle Golf Country Club'),
  ('United States', 'Lassing Pointe Golf Course'),
  ('United States', 'Latah Creek Golf Course'),
  ('United States', 'Latex Golf Course'),
  ('United States', 'Latimer Golf Club'),
  ('United States', 'Latona Country Club'),
  ('United States', 'Latour Golf Club'),
  ('United States', 'Latourette Golf Course'),
  ('United States', 'Latrobe Country Club'),
  ('United States', 'Latrobe Elks Golf Club'),
  ('United States', 'Latta Lea Golf Club'),
  ('United States', 'Lauderdale Lakes Country Club'),
  ('United States', 'Laughlin Ranch Golf Club'),
  ('United States', 'Laurel Azalea At Houndslake Country Club'),
  ('United States', 'Laurel Country Club'),
  ('United States', 'Laurel Creek Country Club'),
  ('United States', 'Laurel Golf Club'),
  ('United States', 'Laurel Hill Golf Club'),
  ('United States', 'Laurel Island Links'),
  ('United States', 'Laurel Lane Country Club'),
  ('United States', 'Laurel Links Golf Course'),
  ('United States', 'Laurel Mill Golf Course'),
  ('United States', 'Laurel Oak At The Villages Executive Golf Trail'),
  ('United States', 'Laurel Oaks Golf Course'),
  ('United States', 'Laurel Ridge Country Club'),
  ('United States', 'Laurel Springs Golf Club'),
  ('United States', 'Laurel Valley Course At Palmer Legends'),
  ('United States', 'Laurel Valley Golf Club'),
  ('United States', 'Laurens Golf and Country Club'),
  ('United States', 'Lava Creek Golf Course'),
  ('United States', 'Laverne Golf Country Club'),
  ('United States', 'Lawrence Country Club'),
  ('United States', 'Lawrence Park Golf Club'),
  ('United States', 'Lawrence Yacht Country Club'),
  ('United States', 'Lawrenceville School Golf Course The'),
  ('United States', 'Lawton Country Club'),
  ('United States', 'Lawton Golf Club'),
  ('United States', 'Lawton Municipal Golf Course'),
  ('United States', 'Lbi National Golf Resort'),
  ('United States', 'Le Patrimoine Golf Club'),
  ('United States', 'Le Roy Country Club'),
  ('United States', 'Le Triomphe Golf Club'),
  ('United States', 'LeRoy Golf Course'),
  ('United States', 'Lead Country Club'),
  ('United States', 'Leake Country Club'),
  ('United States', 'Leaning Pines Golf Course'),
  ('United States', 'Leaning Rock Golf Course'),
  ('United States', 'Leaning Tree Golf Course'),
  ('United States', 'Leatherstocking Golf Course'),
  ('United States', 'Leavenworth Golf Club'),
  ('United States', 'Lebanon Country Club'),
  ('United States', 'Lebanon Pines Golf Course'),
  ('United States', 'Lebanon Valley Golf Course'),
  ('United States', 'Lebaron Hills Country Club'),
  ('United States', 'Lederach Golf Club'),
  ('United States', 'Ledge Meadows Golf Course'),
  ('United States', 'Ledgemont Country Club'),
  ('United States', 'Ledgerock Golf Club'),
  ('United States', 'Ledges Golf Club'),
  ('United States', 'Ledgeview Golf And Country Club'),
  ('United States', 'Ledgeview Golf Course'),
  ('United States', 'Leeds Golf Club'),
  ('United States', 'Lees Hill Golf Club'),
  ('United States', 'Leesville Municipal Golf Course'),
  ('United States', 'Leewood Golf Club'),
  ('United States', 'Lefleurss Bluff Golf Course'),
  ('United States', 'Leflore County Country Club'),
  ('United States', 'Legacy Club At Alaqua Lakes'),
  ('United States', 'Legacy Courses at Cragun''s'),
  ('United States', 'Legacy Golf Club'),
  ('United States', 'Legacy Golf Club Executive Course'),
  ('United States', 'Legacy Golf Course'),
  ('United States', 'Legacy Golf Course 3 Holes Course'),
  ('United States', 'Legacy Golf Links'),
  ('United States', 'Legacy Hills Golf Club'),
  ('United States', 'Legacy Pines Golf Club'),
  ('United States', 'Legacy Ridge Country Club'),
  ('United States', 'Legacy Ridge Golf Course At Westminster'),
  ('United States', 'Legend At Tahquitz Creek Golf Resort'),
  ('United States', 'Legend Lake Golf Course'),
  ('United States', 'Legend Oaks Golf Club'),
  ('United States', 'Legend Trail Golf Club'),
  ('United States', 'Legend Trail Golf Course'),
  ('United States', 'Legendary Run Golf Course'),
  ('United States', 'Legends Golf Club'),
  ('United States', 'Legends Golf Country Club'),
  ('United States', 'Legends Golf Course'),
  ('United States', 'Legends Golf Resort Heathland Course'),
  ('United States', 'Legends Golf Resort Moorland Course'),
  ('United States', 'Legends Golf Resort Parkland Course'),
  ('United States', 'Legends On The Niagara Golf Course Battlefield'),
  ('United States', 'Legends On The Niagara Golf Course Chippawa'),
  ('United States', 'Legends On The Niagara Golf Course Usshers Creek'),
  ('United States', 'Legends Walk At Orange Lake Resort'),
  ('United States', 'Legion Memorial Golf Course'),
  ('United States', 'Legion Town Country Club'),
  ('United States', 'Lehigh Country Club'),
  ('United States', 'Lehigh Resort Club'),
  ('United States', 'Lehman Golf Club'),
  ('United States', 'Leicester Country Club'),
  ('United States', 'Leilehua Golf Course'),
  ('United States', 'Leisure Village Golf Club'),
  ('United States', 'Leisure Village Golf Course'),
  ('United States', 'Leisure Village Golf Course East Course'),
  ('United States', 'Leisure Village Par 3'),
  ('United States', 'Leisure Village West Pines Nine'),
  ('United States', 'Leisure Village West Willow Nine'),
  ('United States', 'Leisure World 3 Par Golf Course'),
  ('United States', 'Leisure World Golf Coyote Run Course'),
  ('United States', 'Leisure World Golf Heron Lakes Course'),
  ('United States', 'Leisureville Fairway'),
  ('United States', 'Leisureville Golf Course'),
  ('United States', 'Leland Country Club'),
  ('United States', 'Lely Resort Golf Country Club Flamingo Island Course'),
  ('United States', 'Lely Resort Golf Country Club Mustang Course'),
  ('United States', 'Lemon Bay Golf Club'),
  ('United States', 'Lemondrop Lounge Golf Links'),
  ('United States', 'Lemoore Golf Course'),
  ('United States', 'Lenape Heights Golf Course'),
  ('United States', 'Lenawee Country Club'),
  ('United States', 'Lenoir Golf Course'),
  ('United States', 'Lenox Community Golf Course'),
  ('United States', 'Leo J Martin Memorial Golf Course'),
  ('United States', 'Leonardville Golf Course'),
  ('United States', 'Leopards Chase Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Les Bolstad Golf Course'),
  ('United States', 'Les Cheneaux Golf Course'),
  ('United States', 'Les Rochers Bleus Golf And Auberge'),
  ('United States', 'Les Vieux Chenes Golf Course'),
  ('United States', 'Leslie Park Golf Course'),
  ('United States', 'Lester Park Golf Course'),
  ('United States', 'Lew Wentz Golf Course'),
  ('United States', 'Lewis Clark Public Golf Course'),
  ('United States', 'Lewis River Golf Course'),
  ('United States', 'Lewiston Golf & Country Club'),
  ('United States', 'Lewiston Golf Country Club'),
  ('United States', 'Lewistown Country Club'),
  ('United States', 'Lexington Country Club'),
  ('United States', 'Lexington Golf Club'),
  ('United States', 'Lexington Golf Country Club'),
  ('United States', 'Lexington Oaks Golf Club'),
  ('United States', 'Liberal Country Club'),
  ('United States', 'Liberty Forge Golf Course'),
  ('United States', 'Liberty Hills Golf Club'),
  ('United States', 'Liberty Lake Golf Course'),
  ('United States', 'Liberty National Golf Course'),
  ('United States', 'Lick Creek Golf Course'),
  ('United States', 'Lida Greens'),
  ('United States', 'Lidgerwood Golf Course'),
  ('United States', 'Lido Golf Club'),
  ('United States', 'Ligonier Country Club'),
  ('United States', 'Likely Place Rv Golf'),
  ('United States', 'Lilmole Run Golf Course'),
  ('United States', 'Lily Lake Golf Resort'),
  ('United States', 'Limestone Country Club'),
  ('United States', 'Lincoln Country Club'),
  ('United States', 'Lincoln Elks Country Club'),
  ('United States', 'Lincoln Golf Course'),
  ('United States', 'Lincoln Greens Golf Course'),
  ('United States', 'Lincoln Hills Golf Club'),
  ('United States', 'Lincoln Hills Golf Course'),
  ('United States', 'Lincoln Homestead State Park'),
  ('United States', 'Lincoln Oaks Golf Course'),
  ('United States', 'Lincoln Park Golf Course'),
  ('United States', 'Lincoln Valley Golf Course / City of State Center'),
  ('United States', 'Lincolnshire Country Club'),
  ('United States', 'Lincolnshire Fields Country Club'),
  ('United States', 'Linda Vista Golf Course'),
  ('United States', 'Linden Golf Country Club'),
  ('United States', 'Linden Hall Golf Course'),
  ('United States', 'Linderhof Country Club'),
  ('United States', 'Lindsay Municipal Golf Course'),
  ('United States', 'Lindsborg Golf Course'),
  ('United States', 'Lindsey Golf Course'),
  ('United States', 'Linfield National Golf Club'),
  ('United States', 'Link Hills Country Club'),
  ('United States', 'Links & Tees Golf Facility'),
  ('United States', 'Links At Bear Lakes Country Club'),
  ('United States', 'Links At Bentonville Golf Athletic Club'),
  ('United States', 'Links At City Park Golf Course The'),
  ('United States', 'Links At Gettysburg'),
  ('United States', 'Links At Lowell The'),
  ('United States', 'Links At Norman Golf Country Club'),
  ('United States', 'Links At On Top Of The World'),
  ('United States', 'Links At Riverlakes Ranch'),
  ('United States', 'Links At Sandestin Golf And Beach Resort'),
  ('United States', 'Links At Sherwood The'),
  ('United States', 'Links At Sierra Blanca The'),
  ('United States', 'Links At Wild Dunes Golf Links'),
  ('United States', 'Links Canyon At Fox Hollow At Lakewood'),
  ('United States', 'Links Course At Paso Robles'),
  ('United States', 'Links Golf Club'),
  ('United States', 'Links Of Kent Golf Club & Event Centre'),
  ('United States', 'Links Of Lake Bernadette'),
  ('United States', 'Links Of Lake Mary'),
  ('United States', 'Links Of Sandpiper'),
  ('United States', 'Links Of Spruce Creek South'),
  ('United States', 'Links On The Bayou'),
  ('United States', 'Links Otryon'),
  ('United States', 'Links at Gateway'),
  ('United States', 'Links at Northfork'),
  ('United States', 'Links at Whitmore Lake Golf Course'),
  ('United States', 'Linkside At Pebble Creek Country Club'),
  ('United States', 'Linn Grove Country Club'),
  ('United States', 'Linrick Golf Course'),
  ('United States', 'Linville Falls Golf Club'),
  ('United States', 'Linville Golf Club'),
  ('United States', 'Linville Land Harbor Golf Club'),
  ('United States', 'Linville Ridge Country Club'),
  ('United States', 'Linwood Country Club'),
  ('United States', 'Lion Golf Club'),
  ('United States', 'Lion Hills Golf Course At East Mississippi Community College'),
  ('United States', 'Lions Club Municipal Golf Course'),
  ('United States', 'Lions Den Golf Club'),
  ('United States', 'Lions Head Country Club'),
  ('United States', 'Lions Paw At Ocean Ridge Plantation'),
  ('United States', 'Lisbon Village Country Club'),
  ('United States', 'Litchfield Country Club'),
  ('United States', 'Litchfield Golf Club'),
  ('United States', 'Litchfield Greens'),
  ('United States', 'Litl Links Golf Club'),
  ('United States', 'Little America Resort Golf'),
  ('United States', 'Little Apple Golf Course'),
  ('United States', 'Little Bear Golf Club'),
  ('United States', 'Little Bear Golf Course'),
  ('United States', 'Little Creek Golf Course'),
  ('United States', 'Little Creek Recreation Club'),
  ('United States', 'Little Crow Country Club'),
  ('United States', 'Little Falls Golf Course'),
  ('United States', 'Little Falls Municipal Golf Course'),
  ('United States', 'Little Fishing Creek Golf Course'),
  ('United States', 'Little Harbor Country Club'),
  ('United States', 'Little Met Golf Course'),
  ('United States', 'Little Miami Golf Center'),
  ('United States', 'Little Mountain Country Club'),
  ('United States', 'Little Nugget Golf Course (Closed)'),
  ('United States', 'Little Ocmulgee At Wallace Adams Course'),
  ('United States', 'Little River Country Club'),
  ('United States', 'Little River Inn Golf Tennis Club'),
  ('United States', 'Little River Municipal Golf Course'),
  ('United States', 'Little Willow Executive Course'),
  ('United States', 'Littleton Golf And Tennis Club'),
  ('United States', 'Live Oak Pitch Putt Golf Course'),
  ('United States', 'Live Oak Rv Golf Course'),
  ('United States', 'Live Oaks Golf Club'),
  ('United States', 'Livingston Country Club'),
  ('United States', 'Livingston Golf Country Club'),
  ('United States', 'Llanerch Country Club'),
  ('United States', 'Llano Grande Golf Course'),
  ('United States', 'Loblolly Executive Golf Course'),
  ('United States', 'Loblolly Pines Golf Course'),
  ('United States', 'Loch Haven Golf Center'),
  ('United States', 'Loch Lloyd Country Club'),
  ('United States', 'Loch Lloyd Country Club Sechrest Nine'),
  ('United States', 'Loch Lomond Golf Course'),
  ('United States', 'LochenHeath Golf Club'),
  ('United States', 'Lochmere Golf Club'),
  ('United States', 'Lochmere Golf Country Club'),
  ('United States', 'Lochmoor Club'),
  ('United States', 'Lochmor Golf Course'),
  ('United States', 'Lockeford Springs Golf Course'),
  ('United States', 'Lockport Golf and Recreation Club'),
  ('United States', 'Lockport Hole 1'),
  ('United States', 'Lockport Hole 2'),
  ('United States', 'Lockport Hole 3'),
  ('United States', 'Lockport Hole 4'),
  ('United States', 'Lockport Town Country Club'),
  ('United States', 'Lockwood Folly Country Club'),
  ('United States', 'Locust Hill Country Club'),
  ('United States', 'Locust Hills Golf Course'),
  ('United States', 'Lodge Of Four Seasons Cove Course'),
  ('United States', 'Lodge Of Four Seasons Ridge Course'),
  ('United States', 'Lodi Golf Club'),
  ('United States', 'Log Cabin Club'),
  ('United States', 'Logan Country Club'),
  ('United States', 'Logan Golf Country Club'),
  ('United States', 'Logan River Golf Course'),
  ('United States', 'Logansport Country Club'),
  ('United States', 'Loggers Trace'),
  ('United States', 'Loggers Trail Golf Course'),
  ('United States', 'Lomas Santa Fe Country Club'),
  ('United States', 'Lomas Santa Fe Executive Golf Course'),
  ('United States', 'London Downs Golf Club'),
  ('United States', 'Londonderry Country Club'),
  ('United States', 'Lone Palm Golf Club'),
  ('United States', 'Lone Pine Country Club'),
  ('United States', 'Lone Pine Golf Course'),
  ('United States', 'Lone Star Golf Course'),
  ('United States', 'Lone Tree Golf Club'),
  ('United States', 'Lone Tree Golf Club Hotel'),
  ('United States', 'Lone Tree Golf Course'),
  ('United States', 'Lonesome Pine Country Club'),
  ('United States', 'Long Bay Club'),
  ('United States', 'Long Beach Country Club'),
  ('United States', 'Long Bow Golf Club'),
  ('United States', 'Long Bridge Golf Course'),
  ('United States', 'Long Cove Club'),
  ('United States', 'Long Island National Golf Club'),
  ('United States', 'Long Lake Country Club'),
  ('United States', 'Long Meadow Golf Club'),
  ('United States', 'Long Point At Amelia Island Club'),
  ('United States', 'Long Prairie Country Club'),
  ('United States', 'Long Run Golf Course'),
  ('United States', 'Longbow Golf Club'),
  ('United States', 'Longest Hole Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Longhills Golf Course'),
  ('United States', 'Longhis Golf'),
  ('United States', 'Longleaf Executive Golf Course'),
  ('United States', 'Longleaf Golf Family Club'),
  ('United States', 'Longmeadow Country Club'),
  ('United States', 'Longue Vue Club'),
  ('United States', 'Longview Country Club'),
  ('United States', 'Longview Golf Course'),
  ('United States', 'Longwood Golf Course'),
  ('United States', 'Lonnie Poole Golf Course At North Carolina State University'),
  ('United States', 'Lonoke Golf Course'),
  ('United States', 'Lookaway Golf Club'),
  ('United States', 'Lookout Mountain Golf Club'),
  ('United States', 'Loomis Trail Golf Club'),
  ('United States', 'Loons Cove Golf Course'),
  ('United States', 'Lopez Island Golf Club'),
  ('United States', 'Lords Valley Country Club'),
  ('United States', 'Los Alamos Golf Course'),
  ('United States', 'Los Altos Golf Country Club'),
  ('United States', 'Los Altos Golf Course Executive Course'),
  ('United States', 'Los Altos Golf Course Los Altos Course'),
  ('United States', 'Los Amigos Country Club'),
  ('United States', 'Los Caballeros Golf Club'),
  ('United States', 'Los Feliz 3 Par Golf Course'),
  ('United States', 'Los Lagos At Costa Mesa Golf Country Club'),
  ('United States', 'Los Lagos Golf Club'),
  ('United States', 'Los Lagos Golf Course'),
  ('United States', 'Los Lagos La Vista At Desert Princess Country Club'),
  ('United States', 'Los Prados Golf Course'),
  ('United States', 'Los Robles Greens Golf Course'),
  ('United States', 'Los Verdes Golf Course'),
  ('United States', 'Losantiville Country Club'),
  ('United States', 'Lost Brook Golf Club'),
  ('United States', 'Lost City Golf Club East North'),
  ('United States', 'Lost City Golf Club East South'),
  ('United States', 'Lost City Golf Club South North'),
  ('United States', 'Lost Creek Golf Club'),
  ('United States', 'Lost Creek Golfers Club'),
  ('United States', 'Lost Dunes'),
  ('United States', 'Lost Key Golf Club'),
  ('United States', 'Lost Lake Golf Club'),
  ('United States', 'Lost Lake Woods Golf Course'),
  ('United States', 'Lost Marsh Golf Course'),
  ('United States', 'Lost Nation Golf Course'),
  ('United States', 'Lost Plantation Golf Club'),
  ('United States', 'Lost Springs Golf Athletic Club'),
  ('United States', 'Lost Spur Country Club'),
  ('United States', 'Lost Tree Club'),
  ('United States', 'Lost Woods Golf Course'),
  ('United States', 'Loudon Country Club'),
  ('United States', 'Loudon Meadows Golf Club'),
  ('United States', 'Loudoun Golf Country Club'),
  ('United States', 'Louisiana Technical Golf Course'),
  ('United States', 'Louisquisset Golf Club'),
  ('United States', 'Louisville Country Club'),
  ('United States', 'Lovington Country Club'),
  ('United States', 'Lower At Baltusrol Golf Club'),
  ('United States', 'Lower At Peekn Peak Golf Course'),
  ('United States', 'Lowlands Executive Golf Course'),
  ('United States', 'Loxahatchee Club'),
  ('United States', 'Loyal Oak Golf Course'),
  ('United States', 'Lpga International Hills Course'),
  ('United States', 'Lpga International Jones Course'),
  ('United States', 'Lpga International Practice Academy'),
  ('United States', 'Lsu Golf Course'),
  ('United States', 'Lu Gene Links Country Club'),
  ('United States', 'Lucas Oil Golf Course'),
  ('United States', 'Lucerne In Maine Golf Course'),
  ('United States', 'Lucky Hills Golf Course'),
  ('United States', 'Ludden Lake Golf Club'),
  ('United States', 'Ludlow Country Club'),
  ('United States', 'Lulu Country Club'),
  ('United States', 'Lunenburg Country Club'),
  ('United States', 'Lusk Municipal Golf Course'),
  ('United States', 'Lutz Executive Golf Center'),
  ('United States', 'Luverne Country Club'),
  ('United States', 'Lykens Valley Golf Course'),
  ('United States', 'Lyndon Golf Course'),
  ('United States', 'Lyndway Hills Golf Course'),
  ('United States', 'Lynndale''s Golf'),
  ('United States', 'Lynnwood Municipal Golf Course'),
  ('United States', 'Lynrock Golf Course'),
  ('United States', 'Lyon Oaks Golf Course'),
  ('United States', 'Lyons Town Country Club'),
  ('United States', 'M A 8 Golf'),
  ('United States', 'Ma Cal Grove Country Club'),
  ('United States', 'Macatawa Legends Golf & Country Club'),
  ('United States', 'Maccripine Country Club'),
  ('United States', 'Macdonald Golf Course'),
  ('United States', 'Macgregor Downs Country Club'),
  ('United States', 'Mack Mayfield Municipal Golf Course'),
  ('United States', 'Mackinaw Club'),
  ('United States', 'Macktown Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Macoby Run Golf Course'),
  ('United States', 'Macomb Country Club'),
  ('United States', 'Mad Anthony III''s Short Course'),
  ('United States', 'Mad Russian Golf Course'),
  ('United States', 'Madden Golf Course'),
  ('United States', 'Madeline Island Golf Club'),
  ('United States', 'Madera Golf Country Club'),
  ('United States', 'Madera Municipal Golf Course'),
  ('United States', 'Maderas Golf Club'),
  ('United States', 'Madison Country Club'),
  ('United States', 'Madison Golf & Country Club'),
  ('United States', 'Madison Golf Club'),
  ('United States', 'Madison Golf Course'),
  ('United States', 'Madison Green Country Club'),
  ('United States', 'Madison Meadows Golf Club'),
  ('United States', 'Madison Park Golf Course'),
  ('United States', 'Madisonville Country Club'),
  ('United States', 'Madrid Golf Course'),
  ('United States', 'Madrona Links Golf Course'),
  ('United States', 'Magellan Golf Course'),
  ('United States', 'Maggie Hathaway Par 3 Golf Course'),
  ('United States', 'Maggie Valley Resort Country Club'),
  ('United States', 'Magnolia At Beau Chene Golf Racquet Club'),
  ('United States', 'Magnolia Country Club'),
  ('United States', 'Magnolia Dogwood At Callawassie Island Club'),
  ('United States', 'Magnolia Green Golf Club'),
  ('United States', 'Magnolia Greens Golf Course Camellia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Camellia'),
  ('United States', 'Magnolia Grove Golf Club Crossings Course'),
  ('United States', 'Magnolia Grove Golf Club Falls Course'),
  ('United States', 'Magnolia Grove Golf Club Short Course'),
  ('United States', 'Magnolia Highlands At Highland Oaks Golf Course'),
  ('United States', 'Magnolia Landing Golf Country Club'),
  ('United States', 'Magnolia Plantation Golf Club'),
  ('United States', 'Magnolia Point Golf Country Club'),
  ('United States', 'Magnolia Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Magnolia Willow At Ben Geren Regional Park Golf Course'),
  ('United States', 'Mahnomen County Country Club'),
  ('United States', 'Mahoney Golf Course'),
  ('United States', 'Mahoning Country Club'),
  ('United States', 'Mahopac Golf Club'),
  ('United States', 'Main At Brae Burn Country Club'),
  ('United States', 'Main At Country Club The'),
  ('United States', 'Main At Shadow Lake Golf Racquet Club'),
  ('United States', 'Maine Golf Center Freeport'),
  ('United States', 'Mainland Golf Course'),
  ('United States', 'Mainlands Golf Course'),
  ('United States', 'Majestic Hills Golf Course'),
  ('United States', 'Majestic Oaks Golf Club'),
  ('United States', 'Majestic Oaks at Lake Lawn Resort'),
  ('United States', 'Majestic Springs Golf Club'),
  ('United States', 'Majestic at Lake Walden Golf Course'),
  ('United States', 'Makaha Valley Country Club'),
  ('United States', 'Makalei Golf Club'),
  ('United States', 'Makani Golf Club'),
  ('United States', 'Makefield Highlands Golf Club'),
  ('United States', 'Makena Beach Golf Resort'),
  ('United States', 'Maketewah Country Club'),
  ('United States', 'Makray Memorial Golf Club'),
  ('United States', 'Malden Country Club'),
  ('United States', 'Malden Municipal Golf Course'),
  ('United States', 'Mallard Creek Golf Club'),
  ('United States', 'Mallard Golf Club'),
  ('United States', 'Mallard Head Country Club'),
  ('United States', 'Mallard Pointe Golf Course'),
  ('United States', 'Mallards Landing Golf Course At Melbourne'),
  ('United States', 'Malvern Country Club'),
  ('United States', 'Mamala Bay Golf Course'),
  ('United States', 'Man O War Golf Course'),
  ('United States', 'Manada Golf Club'),
  ('United States', 'Manakiki Golf Course'),
  ('United States', 'Manakin At Hermitage Country Club'),
  ('United States', 'Manasquan River Golf Club'),
  ('United States', 'Manatee Cove Golf Course'),
  ('United States', 'Manatee Golf Course'),
  ('United States', 'Manchester Country Club'),
  ('United States', 'Manchester Golf and Country Club'),
  ('United States', 'Manele Golf Course'),
  ('United States', 'Mangrove At The Villages Executive Golf Trail'),
  ('United States', 'Mangrove Bay Golf Course'),
  ('United States', 'Mangum Golf Course'),
  ('United States', 'Manhattan Country Club'),
  ('United States', 'Manhattan Woods Golf Club'),
  ('United States', 'Manistee Golf & Country Club'),
  ('United States', 'Manito Golf Country Club'),
  ('United States', 'Manitou Passage Golf Club'),
  ('United States', 'Manitou Ridge Golf Course'),
  ('United States', 'Manitoulin Island Country Club'),
  ('United States', 'Manning Manilla Golf Course'),
  ('United States', 'Mannitto Golf Club'),
  ('United States', 'Manor Golf Course'),
  ('United States', 'Manor Valley Country Club'),
  ('United States', 'Mansfield Golf Country Club'),
  ('United States', 'Manson Golf and Country Club'),
  ('United States', 'Manteca Park Golf Course'),
  ('United States', 'Manteno Golf Club'),
  ('United States', 'Manufacturers Golf Country Club'),
  ('United States', 'Maple Bluff Country Club'),
  ('United States', 'Maple Brook Golf Course'),
  ('United States', 'Maple Chase Golf Country Club'),
  ('United States', 'Maple Creek Golf Club'),
  ('United States', 'Maple Creek Golf and Country Club'),
  ('United States', 'Maple Crest Golf Course'),
  ('United States', 'Maple Dale Country Club'),
  ('United States', 'Maple Grove Golf'),
  ('United States', 'Maple Grove Golf Course'),
  ('United States', 'Maple Heights Golf and Country Club'),
  ('United States', 'Maple Hill Golf Club'),
  ('United States', 'Maple Hill Golf Course'),
  ('United States', 'Maple Hills Golf Course'),
  ('United States', 'Maple Hills Public Golf Course'),
  ('United States', 'Maple Lane Golf Club'),
  ('United States', 'Maple Lane Golf Course'),
  ('United States', 'Maple Leaf Golf Country Club'),
  ('United States', 'Maple Leaf Golf Course'),
  ('United States', 'Maple Meadows Golf Club'),
  ('United States', 'Maple Moor Golf Course'),
  ('United States', 'Maple Ridge Golf'),
  ('United States', 'Maple Ridge Golf Club'),
  ('United States', 'Maple River Golf Club'),
  ('United States', 'Maple River Resort'),
  ('United States', 'Maple Run Golf Course'),
  ('United States', 'Maple Valley Golf & Country Club'),
  ('United States', 'Maple Willow At Hunters Creek Plantation'),
  ('United States', 'Maplecrest Country Club'),
  ('United States', 'Maplegate Country Club'),
  ('United States', 'Maplehurst Country Club'),
  ('United States', 'Maples At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Maplewood Country Club'),
  ('United States', 'Maplewood Golf Club'),
  ('United States', 'Maplewood Golf Course'),
  ('United States', 'Mapple Hills'),
  ('United States', 'Maquoketa Country Club'),
  ('United States', 'Marbella Country Club'),
  ('United States', 'Marcus Community Golf Club'),
  ('United States', 'Marcus Pointe Golf Club'),
  ('United States', 'Marengo Golf Club'),
  ('United States', 'Marengo Ridge Golf Curse'),
  ('United States', 'Margate Executive Golf Course'),
  ('United States', 'Mari Mac Golf Complex'),
  ('United States', 'Mariah Hills'),
  ('United States', 'Marian Hills Golf Course'),
  ('United States', 'Mariana Butte Golf Course'),
  ('United States', 'Marianna Country Club'),
  ('United States', 'Marias Valley Golf Country Club'),
  ('United States', 'Marietta Country Club'),
  ('United States', 'Marietta Country Club Lake View Nine'),
  ('United States', 'Marietta Country Club Mountain View Nine'),
  ('United States', 'Marietta Country Club Overlook Nine'),
  ('United States', 'Marin Country Club'),
  ('United States', 'Marine Memorial Golf Course'),
  ('United States', 'Marine Park Golf Course'),
  ('United States', 'Mariner Sands Country Club Blue Course'),
  ('United States', 'Mariner Sands Country Club Gold Course'),
  ('United States', 'Mariners Landing Golf Country Club'),
  ('United States', 'Mariners Point Golf Links Practice Center'),
  ('United States', 'Marion Country Club'),
  ('United States', 'Marion Golf Club'),
  ('United States', 'Marion Lake Golf Club'),
  ('United States', 'Marion Oaks Country Club'),
  ('United States', 'Marjon Golf Course'),
  ('United States', 'Mark Bostick Golf Course At The University Of Florida'),
  ('United States', 'Mark Twain Golf Course'),
  ('United States', 'Mark''s Golf'),
  ('United States', 'Mark''s Par 3'),
  ('United States', 'Marlboro Country Club'),
  ('United States', 'Marlborough Country Club'),
  ('United States', 'Maroon Creek Club Golf Course'),
  ('United States', 'Marquette Golf Club'),
  ('United States', 'Marquette Golf Club Greywalls'),
  ('United States', 'Marquette Park Golf Course'),
  ('United States', 'Marquette Trails Country Club'),
  ('United States', 'Marrakesh Golf Club'),
  ('United States', 'Mars Bethel Golf Course'),
  ('United States', 'Mars Hill Country Club'),
  ('United States', 'Marsh At Bonita Bay Club'),
  ('United States', 'Marsh Creek Country Club'),
  ('United States', 'Marsh Landing Country Club'),
  ('United States', 'Marsh Ridge Golf Course and Resort'),
  ('United States', 'Marsh View Pitch Putt'),
  ('United States', 'Marshall Canyon Golf Club'),
  ('United States', 'Marshall Country Club'),
  ('United States', 'Marshall Golf Club'),
  ('United States', 'Marshall Lakeside Country Club'),
  ('United States', 'Marshfield Country Club'),
  ('United States', 'Marshwood Magnolia At Highland Oaks Golf Course'),
  ('United States', 'Martin Downs Country Club Osprey Creek Course'),
  ('United States', 'Martindale Country Club'),
  ('United States', 'Martinsville Golf Club'),
  ('United States', 'Martis Camp Club'),
  ('United States', 'Marty Sanchez Links De Santa Fe Great 28 Course'),
  ('United States', 'Marty Sanchez Links De Santa Fe Links Course'),
  ('United States', 'Mary Calder Golf Club'),
  ('United States', 'Marysville Country Club'),
  ('United States', 'Marysville Golf Club'),
  ('United States', 'Marysville Golf Course'),
  ('United States', 'Marywood Country Club'),
  ('United States', 'Mascoutin Golf Club'),
  ('United States', 'Mason City Country Club'),
  ('United States', 'Massanutten Resort Mountain Greens Course'),
  ('United States', 'Massanutten Resort Woodstone Meadows Course'),
  ('United States', 'Massena Country Club'),
  ('United States', 'Masterpiece'),
  ('United States', 'Mastick Woods Golf Course'),
  ('United States', 'Mather Golf Course'),
  ('United States', 'Mattawang Golf Club'),
  ('United States', 'Matthew Creek Par 3'),
  ('United States', 'Mattoon Golf & Country Club'),
  ('United States', 'Mauh-Nah-Tee-See Country Club'),
  ('United States', 'Maui Country Club'),
  ('United States', 'Maui Nui Golf Club'),
  ('United States', 'Maumee Bay State Park Golf Course'),
  ('United States', 'Maumelle Country Club'),
  ('United States', 'Mauna Kea Golf Course'),
  ('United States', 'Mauna Lani Resort North Course'),
  ('United States', 'Mauna Lani Resort South Course'),
  ('United States', 'Mauna Lani Resort Wikiwiki Course'),
  ('United States', 'Maxwelton Braes Golf Resort'),
  ('United States', 'Maxwelton Golf Club'),
  ('United States', 'May River Golf Course At Palmetto Bluff'),
  ('United States', 'Mayacama Golf Club'),
  ('United States', 'Mayacoo Lakes Country Club'),
  ('United States', 'Mayapple Golf Links'),
  ('United States', 'Mayfair Country Club'),
  ('United States', 'Mayfield Sand Ridge Club'),
  ('United States', 'Mayflower Golf Club'),
  ('United States', 'Maynard Golf Course'),
  ('United States', 'Mays Landing Golf Club'),
  ('United States', 'Mayville Golf Club'),
  ('United States', 'Mayville Golf Course'),
  ('United States', 'McArthur Golf Course'),
  ('United States', 'McCaslin Brook Golf & Country Club'),
  ('United States', 'McCormick Creek Golf Course'),
  ('United States', 'McDonald Golf Course'),
  ('United States', 'McHenry Country Club'),
  ('United States', 'McLeansboro Golf Club'),
  ('United States', 'McMillen Park Golf Course'),
  ('United States', 'Mcalester Country Club'),
  ('United States', 'Mcarthur Golf Club'),
  ('United States', 'Mcarthur Golf Club Backyard Course'),
  ('United States', 'Mccall Field Golf Course'),
  ('United States', 'Mccanless Golf Club'),
  ('United States', 'Mccann Memorial Golf Course'),
  ('United States', 'Mccloud Golf Club'),
  ('United States', 'Mcconnellsville Golf Club'),
  ('United States', 'Mccormick Country Club'),
  ('United States', 'Mccormick Woods Golf Course'),
  ('United States', 'Mcculloughs Emerald Golf Links'),
  ('United States', 'Mcdaniel College Golf Club'),
  ('United States', 'Mcdonald Hills Golf Club'),
  ('United States', 'Mcdowell Mountain Golf Club'),
  ('United States', 'Mcgregor Links Country Club'),
  ('United States', 'Mcinnis Park Golf Center'),
  ('United States', 'Mckenzie Memorial Golf Course'),
  ('United States', 'Mclemore Club Highlands Course'),
  ('United States', 'Mclemore Club The Cairn Short Course'),
  ('United States', 'Mclemore Club The Keep'),
  ('United States', 'Mcpherson Country Club'),
  ('United States', 'Meade Country Club'),
  ('United States', 'Meadia Heights Golf Club'),
  ('United States', 'Meadow Acres Golf Course'),
  ('United States', 'Meadow At Forest Highlands Golf Club'),
  ('United States', 'Meadow At Mulligans South'),
  ('United States', 'Meadow Brook Club'),
  ('United States', 'Meadow Brook Golf Club'),
  ('United States', 'Meadow Brook Golf Course'),
  ('United States', 'Meadow Club'),
  ('United States', 'Meadow Course At Fiddlers Elbow Country Club'),
  ('United States', 'Meadow Creek Dogwood At Lancaster Country Club'),
  ('United States', 'Meadow Creek Golf Course'),
  ('United States', 'Meadow Golf Course At Pole Creek Golf Club'),
  ('United States', 'Meadow Greens Golf Course'),
  ('United States', 'Meadow Hills Golf Course'),
  ('United States', 'Meadow Lake Golf Club'),
  ('United States', 'Meadow Lake Golf Country Club'),
  ('United States', 'Meadow Lake Golf Resort'),
  ('United States', 'Meadow Lake Village And Golf Course'),
  ('United States', 'Meadow Lakes Golf Club'),
  ('United States', 'Meadow Lane Golf Course'),
  ('United States', 'Meadow Lark Country Club'),
  ('United States', 'Meadow Links & Golf Academy'),
  ('United States', 'Meadow Links At Fox Hollow At Lakewood'),
  ('United States', 'Meadow Links Golf Course'),
  ('United States', 'Meadow Links Golf Course At George T Bagby'),
  ('United States', 'Meadow Oak Golf Club'),
  ('United States', 'Meadow Oaks Golf Country Club'),
  ('United States', 'Meadow Park At Meadow Park Golf Course'),
  ('United States', 'Meadow Ponds Golf Course'),
  ('United States', 'Meadow Springs Country Club'),
  ('United States', 'Meadow Valley Golf Club'),
  ('United States', 'Meadow Valleys At Blackwolf Run Golf Course'),
  ('United States', 'Meadow Woods'),
  ('United States', 'Meadowbrook Country Club'),
  ('United States', 'Meadowbrook Golf Club'),
  ('United States', 'Meadowbrook Golf Course'),
  ('United States', 'Meadowbrook Golf and Country Club'),
  ('United States', 'Meadowbrook at Clayton'),
  ('United States', 'Meadowcreek Golf Course'),
  ('United States', 'Meadowcreek Golf Resort'),
  ('United States', 'Meadowgreens Golf Course'),
  ('United States', 'Meadowink Golf Course'),
  ('United States', 'Meadowlake Golf Course'),
  ('United States', 'Meadowland Golf Course'),
  ('United States', 'Meadowlands Golf Club'),
  ('United States', 'Meadowlands Golf Course'),
  ('United States', 'Meadowlark Golf Course'),
  ('United States', 'Meadowmeer Golf Country Club'),
  ('United States', 'Meadowood Golf Course'),
  ('United States', 'Meadowood Golf Tennis Club'),
  ('United States', 'Meadows Creekside At Traces Golf Club The'),
  ('United States', 'Meadows Golf Center'),
  ('United States', 'Meadows Golf Club'),
  ('United States', 'Meadows Golf Club The'),
  ('United States', 'Meadows Golf Course The'),
  ('United States', 'Meadows Oaks Golf Course At Pennbrooke Fairways'),
  ('United States', 'Meadows Of Six Mile Creek'),
  ('United States', 'Meadows Pinon At Pagosa Springs Golf Club'),
  ('United States', 'Meadowview Golf & Country Club'),
  ('United States', 'Meadowview Golf Course'),
  ('United States', 'Meadowwood Golf Course'),
  ('United States', 'Meander Golf Course'),
  ('United States', 'Mechanicville Golf Club'),
  ('United States', 'Mecklenburg Country Club'),
  ('United States', 'Medal Of Honor Golf Course'),
  ('United States', 'Medalist Golf Club'),
  ('United States', 'Medalist Village Golf'),
  ('United States', 'Medallion Golf Club'),
  ('United States', 'Medford Lakes Country Club'),
  ('United States', 'Medford Village Country Club'),
  ('United States', 'Medicine Lodge Golf Club'),
  ('United States', 'Medina Golf & Country Club'),
  ('United States', 'Medinah Country Club'),
  ('United States', 'Mee-Kwon Park Golf Course'),
  ('United States', 'Meeker Golf Course'),
  ('United States', 'Megunticook Golf Club'),
  ('United States', 'Meigs Golf Course'),
  ('United States', 'Mellen country Club'),
  ('United States', 'Melody Hill Golf Course'),
  ('United States', 'Melrose Country Club'),
  ('United States', 'Members Club At St James Plantation Cate Nine Course'),
  ('United States', 'Members Club At St James Plantation Irwin Course'),
  ('United States', 'Memorial Links Golf Club'),
  ('United States', 'Memorial Park Golf Course'),
  ('United States', 'Memphis Athletic Ministries Park Golf Course'),
  ('United States', 'Memphis Country Club The'),
  ('United States', 'Memphis National Golf Club Champions Course'),
  ('United States', 'Memphis National Golf Club Legends Course'),
  ('United States', 'Memphremagog Golf Club'),
  ('United States', 'Mendakota Country Club'),
  ('United States', 'Mendenhall Golf Course'),
  ('United States', 'Mendham Golf Tennis Club'),
  ('United States', 'Mendon Golf Club'),
  ('United States', 'Mendota Golf Club'),
  ('United States', 'Mendota Heights Par 3 Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Lakes Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Palms Golf Course'),
  ('United States', 'Menlo Country Club'),
  ('United States', 'Menomonie Country Club'),
  ('United States', 'Mentel Memorial Golf Course'),
  ('United States', 'Meramec Lakes Golf Course'),
  ('United States', 'Merced Golf Country Club'),
  ('United States', 'Mercer County Elks Golf Club'),
  ('United States', 'Mercer Oaks Golf Course East Course'),
  ('United States', 'Mercer Oaks Golf Course West Course'),
  ('United States', 'Mercer Public Golf Course'),
  ('United States', 'Merchantville Country Club'),
  ('United States', 'Mere Creek Golf Course'),
  ('United States', 'Meridian Golf Club'),
  ('United States', 'Meridian Golf Par 3 Golf Club'),
  ('United States', 'Meridian Hills County Club'),
  ('United States', 'Meridian Sun Golf Club'),
  ('United States', 'Meridian Valley Country Club'),
  ('United States', 'Merit Club'),
  ('United States', 'Mermaid Swim Golf Club'),
  ('United States', 'Merrick Road Park Golf Course'),
  ('United States', 'Merriland Farm Par 3 Golf Course'),
  ('United States', 'Merrill Golf Club'),
  ('United States', 'Merrimack Valley Golf Club'),
  ('United States', 'Mesa At Adobe Creek National Golf Course'),
  ('United States', 'Mesa Country Club'),
  ('United States', 'Mesa Del Sol Golf Course'),
  ('United States', 'Mesa Linda At Costa Mesa Golf Country Club'),
  ('United States', 'Mesa Verde Country Club'),
  ('United States', 'Mesa View Golf Course'),
  ('United States', 'Mesaba Country Club'),
  ('United States', 'Mesquite Ironwood At Kierland Golf Club'),
  ('United States', 'Met Links'),
  ('United States', 'Metairie Country Club'),
  ('United States', 'Metamora Country Club'),
  ('United States', 'Metamora Fields Golf Club'),
  ('United States', 'Metchosin Golf And Country Club'),
  ('United States', 'Methodist College Golf Club'),
  ('United States', 'Metropolis Country Club'),
  ('United States', 'Metrowest Golf Club'),
  ('United States', 'Metuchen Golf Country Club'),
  ('United States', 'Mga Links At Mamantapett'),
  ('United States', 'Miacomet Golf Course'),
  ('United States', 'Miami Beach Golf Club'),
  ('United States', 'Miami Shores Country Club')
on conflict (country, name) do nothing;