insert into public.golf_courses (country, name) values
  ('United States', 'Ausable Valley Golf Course'),
  ('United States', 'Austin Country Club'),
  ('United States', 'Autumn Ridge Colf Course'),
  ('United States', 'Autumn Ridge Golf'),
  ('United States', 'Avalon At Buhl Park Golf Course'),
  ('United States', 'Avalon Field Club At New Castle'),
  ('United States', 'Avalon Golf Club'),
  ('United States', 'Avalon Golf Links North West Course'),
  ('United States', 'Avalon Golf Links South North Course'),
  ('United States', 'Avalon Golf Links West South Course'),
  ('United States', 'Avalon Lakes Golf Course'),
  ('United States', 'Aviara Golf Club'),
  ('United States', 'Avila Beach Golf Resort'),
  ('United States', 'Avila Golf Country Club'),
  ('United States', 'Avoca Golf Club'),
  ('United States', 'Avon Field'),
  ('United States', 'Avon Oaks Country Club'),
  ('United States', 'Avondale Golf Club'),
  ('United States', 'Avondale Golf Tennis Club'),
  ('United States', 'Ayden Golf Country Club'),
  ('United States', 'Azalea Boganvilia Golf Course At Cleveland Heights Golf Club'),
  ('United States', 'Azalea Camelia Golf Course At Cleveland Heights Golf Club'),
  ('United States', 'Azalea City Golf Course'),
  ('United States', 'Azalea Dogwood At Houndslake Country Club'),
  ('United States', 'Azalea Sands Golf Course'),
  ('United States', 'Aztec Municipal Golf Course'),
  ('United States', 'Azusa Greens Golf Course'),
  ('United States', 'B''s On The  River'),
  ('United States', 'Babbitt Golf Course'),
  ('United States', 'Babcock National'),
  ('United States', 'Babe Zaharias Golf Course'),
  ('United States', 'Bacall At The Villages Executive Golf Trail'),
  ('United States', 'Bachelor Runn Campground'),
  ('United States', 'Back Acres Country Club'),
  ('United States', 'Back Bay Golf Course The'),
  ('United States', 'Back Creek Golf Club'),
  ('United States', 'Back Eighteen At Black Hawk Golf Course'),
  ('United States', 'Back Third At Metedeconk National Golf Club'),
  ('United States', 'Backbone Golf and Country Club'),
  ('United States', 'Bacon Park Golf Course'),
  ('United States', 'Bacon Park Golf Course Legends'),
  ('United States', 'Badlands Golf Course'),
  ('United States', 'Baehmann''s Par 3 Course'),
  ('United States', 'Bailey Creek Golf Course'),
  ('United States', 'Bailey Ranch Golf Club'),
  ('United States', 'Baileyton Golf Club'),
  ('United States', 'Bainbridge Country Club'),
  ('United States', 'Baiting Hollow Club'),
  ('United States', 'Baker Hill Golf Club'),
  ('United States', 'Bakersfield Country Club'),
  ('United States', 'Bala Golf Club'),
  ('United States', 'Balboa At Sepulveda Golf Complex'),
  ('United States', 'Balboa Golf Course'),
  ('United States', 'Bald Eagle Course At Eagle Creek Golf Club'),
  ('United States', 'Bald Eagle Golf Club'),
  ('United States', 'Bald Head Island Country Club'),
  ('United States', 'Bald Knob Country Club'),
  ('United States', 'Bald Mountain Golf Course At Rumbling Bald Resort On Lake Lure'),
  ('United States', 'Bald Peak Colony Club'),
  ('United States', 'Baldwin Golf Association'),
  ('United States', 'Bali Hai Golf Club'),
  ('United States', 'Ballamor Golf Club'),
  ('United States', 'Ballantyne Country Club'),
  ('United States', 'Ballenisles Country Club East Course'),
  ('United States', 'Ballenisles Country Club North Course'),
  ('United States', 'Ballenisles Country Club South Course'),
  ('United States', 'Ballston Spa Country Club'),
  ('United States', 'Ballwin Golf Course & Event Center'),
  ('United States', 'Ballyhack Golf Club'),
  ('United States', 'Ballyneal Golf Hunt Club'),
  ('United States', 'Ballyneal Golf Hunt Club The Mulligan Course'),
  ('United States', 'Ballyowen Golf Club'),
  ('United States', 'Ballys Golf Links At Ferry Point'),
  ('United States', 'Balmoral'),
  ('United States', 'Balmoral Golf Course'),
  ('United States', 'Balmoral Woods Country Club'),
  ('United States', 'Balsam Mountain Preserve'),
  ('United States', 'Banbury Golf Club'),
  ('United States', 'Bandemer Park Disc Golf'),
  ('United States', 'Banks Lake Golf Club'),
  ('United States', 'Banyan Creek Golf Club'),
  ('United States', 'Banyan Golf Course'),
  ('United States', 'Bar Harbor Golf Course'),
  ('United States', 'Baraboo Country Club'),
  ('United States', 'Barbara Worth Golf Resort'),
  ('United States', 'Bardmoor Golf Tennis Club'),
  ('United States', 'Barefoot Bay Golf Recreation Park'),
  ('United States', 'Barefoot Resort Golf Dye Course'),
  ('United States', 'Barefoot Resort Golf Fazio Course'),
  ('United States', 'Barefoot Resort Golf Love Course'),
  ('United States', 'Barefoot Resort Golf Norman Course'),
  ('United States', 'Barker Brook Golf Club'),
  ('United States', 'Barker Lake Golf Course'),
  ('United States', 'Barlett hills golf club'),
  ('United States', 'Barnes Brook Golf Ski'),
  ('United States', 'Barney Road Golf Course'),
  ('United States', 'Barnsley Resort'),
  ('United States', 'Barnyard 9 Golf Course'),
  ('United States', 'Barona Creek Golf Club'),
  ('United States', 'Barony At Port Royal Golf Club'),
  ('United States', 'Barracks Golf Course'),
  ('United States', 'Barren View Golf Course'),
  ('United States', 'Barrington Golf Club'),
  ('United States', 'Barrington Hall Golf Club'),
  ('United States', 'Barrington Hills Country Club'),
  ('United States', 'Bartlett Country Club'),
  ('United States', 'Bartley Cavanaugh Golf Course'),
  ('United States', 'Barton Golf Club'),
  ('United States', 'Barton Hills Country Club'),
  ('United States', 'Bartow Golf Course'),
  ('United States', 'Bartram Trail Golf Club'),
  ('United States', 'Bas Ridge Golf Course'),
  ('United States', 'Baseline Golf Course'),
  ('United States', 'Basin Harbor Club'),
  ('United States', 'Basking Ridge Country Club'),
  ('United States', 'Bass Creek Golf Club'),
  ('United States', 'Bass Lake Golf Course'),
  ('United States', 'Bass River Golf Course'),
  ('United States', 'Bass Rocks Golf Club'),
  ('United States', 'Batavia Country Club'),
  ('United States', 'Batesville Country Club'),
  ('United States', 'Batesville Municipal Golf Course'),
  ('United States', 'Bath Country Club'),
  ('United States', 'Baton Rouge Country Club'),
  ('United States', 'Battenkill Country Club'),
  ('United States', 'Battle Creek Country Club'),
  ('United States', 'Battle Creek Golf Club'),
  ('United States', 'Battle Ground Golf Club LLC'),
  ('United States', 'Battle Island State Golf Course'),
  ('United States', 'Battlefield Golf Club'),
  ('United States', 'Battlefield Golf Club At Centerville'),
  ('United States', 'Battleground Country Club'),
  ('United States', 'Battlement Mesa Golf Club'),
  ('United States', 'Bavarian Hills Golf Course'),
  ('United States', 'Baxter Springs Golf Country Club'),
  ('United States', 'Bay Breeze Golf Course'),
  ('United States', 'Bay Breeze Golf Links'),
  ('United States', 'Bay City Country Club'),
  ('United States', 'Bay Colony Golf Club'),
  ('United States', 'Bay Creek Resort Club Nicklaus Course'),
  ('United States', 'Bay Creek Resort Club Palmer Course'),
  ('United States', 'Bay Harbor Golf Club'),
  ('United States', 'Bay Hill Club Lodge Championship Course'),
  ('United States', 'Bay Hill Club Lodge Charger Course'),
  ('United States', 'Bay Hills Golf Club'),
  ('United States', 'Bay Hills Recreation Park'),
  ('United States', 'Bay Island At Bonita Bay Club'),
  ('United States', 'Bay Meadows Golf Club'),
  ('United States', 'Bay Meadows Golf Course'),
  ('United States', 'Bay Park Golf Course'),
  ('United States', 'Bay Path Golf Course'),
  ('United States', 'Bay Point Resort Meadows Course'),
  ('United States', 'Bay Point Resort Nicklaus Course'),
  ('United States', 'Bay Pointe Country Club'),
  ('United States', 'Bay Pointe Golf Club'),
  ('United States', 'Bay Ridge Golf Course'),
  ('United States', 'Bay Springs Country Club'),
  ('United States', 'Bay View Golf Club'),
  ('United States', 'Bay View Golf Course'),
  ('United States', 'Bay View Retirees Golf Course'),
  ('United States', 'Bayberry Hills Golf Course'),
  ('United States', 'Bayberry Hills Golf Course Links Nine'),
  ('United States', 'Bayhead Lake Golf Course At Countryside Country Club'),
  ('United States', 'Baylands Golf Links'),
  ('United States', 'Bayonet At Puppy Creek'),
  ('United States', 'Bayonne Golf Club'),
  ('United States', 'Bayou Bend Country Club'),
  ('United States', 'Bayou Bend Golf'),
  ('United States', 'Bayou Club'),
  ('United States', 'Bayou Country Club'),
  ('United States', 'Bayou Desiard Country Club'),
  ('United States', 'Bayou Lakeview At A C Read Golf Course'),
  ('United States', 'Bayou Oaks City Park North Course'),
  ('United States', 'Bayou Oaks City Park South Course'),
  ('United States', 'Bayou Vista Golf Course'),
  ('United States', 'Bayouside Golf Club'),
  ('United States', 'Bays Mountain Golf Club'),
  ('United States', 'Bayside Golf Course'),
  ('United States', 'Bayside Resort Golf Club'),
  ('United States', 'Baytowne At Sandestin Golf And Beach Resort'),
  ('United States', 'Baytree Golf Course'),
  ('United States', 'Baytree National Golf Links'),
  ('United States', 'Bayview Bayou At A C Read Golf Course'),
  ('United States', 'Bayview Golf Course'),
  ('United States', 'Baywood Golf Club'),
  ('United States', 'Baywood Golf Country Club'),
  ('United States', 'Baywood Greens'),
  ('United States', 'Bc Ranch Golf Club'),
  ('United States', 'Beach Grove Golf Club'),
  ('United States', 'Beach Grove Golf and Country Club'),
  ('United States', 'Beachwood Golf Club'),
  ('United States', 'Beacon Hill Country Club'),
  ('United States', 'Beacon Hill Golf Club'),
  ('United States', 'Beacon Hill Golf and Banquet Facility'),
  ('United States', 'Beacon Ridge Golf Country Club'),
  ('United States', 'Beacon Rock Public Golf'),
  ('United States', 'Beacon Woods Golf Club'),
  ('United States', 'Bear At Forest Country Club The'),
  ('United States', 'Bear Cave Park DISC Golf Course'),
  ('United States', 'Bear Chase Golf Club'),
  ('United States', 'Bear Course At Breckenridge Golf Club'),
  ('United States', 'Bear Creek Country Club'),
  ('United States', 'Bear Creek Golf Club'),
  ('United States', 'Bear Creek Golf Complex Bear Course'),
  ('United States', 'Bear Creek Golf Complex Cub Course'),
  ('United States', 'Bear Creek Golf Country Club'),
  ('United States', 'Bear Creek Golf Course'),
  ('United States', 'Bear Creek Lodge Golf Course'),
  ('United States', 'Bear Hill Golf Club'),
  ('United States', 'Bear Lake Golf Club'),
  ('United States', 'Bear Lake Golf Course'),
  ('United States', 'Bear Lake Highlands'),
  ('United States', 'Bear Lake West Golf Country Club'),
  ('United States', 'Bear Mountain Golf Course'),
  ('United States', 'Bear Mountain Ranch'),
  ('United States', 'Bear Trail Golf Club'),
  ('United States', 'Bear Trap Dunes Golf Club Black Bear Grizzly Course'),
  ('United States', 'Bear Trap Dunes Golf Club Grizzly Kodiak Course'),
  ('United States', 'Bear Trap Dunes Golf Club Kodiak Black Bear Course'),
  ('United States', 'Bear Valley Country Club'),
  ('United States', 'Bear Valley Golf Course'),
  ('United States', 'Bearpath'),
  ('United States', 'Bears Best Atlanta'),
  ('United States', 'Bears Paw Country Club'),
  ('United States', 'Beatrice Country Club'),
  ('United States', 'Beau Pre Country Club'),
  ('United States', 'Beau Pre Golf Club'),
  ('United States', 'Beau Rivage Golf Resort'),
  ('United States', 'Beauregard Country Club'),
  ('United States', 'Beautyberry At The Villages Executive Golf Trail'),
  ('United States', 'Beaver Bend Par 3'),
  ('United States', 'Beaver Brook Country Club'),
  ('United States', 'Beaver Brook Golf Club'),
  ('United States', 'Beaver Course At Breckenridge Golf Club'),
  ('United States', 'Beaver Creek Country Club'),
  ('United States', 'Beaver Creek Golf Club'),
  ('United States', 'Beaver Creek Golf Course'),
  ('United States', 'Beaver Creek Meadows Golf Course'),
  ('United States', 'Beaver Dam Country Club'),
  ('United States', 'Beaver Dam Farms'),
  ('United States', 'Beaver Dam Lodge Golf Rv Resort'),
  ('United States', 'Beaver Hills Country Club'),
  ('United States', 'Beaver Island Golf Course'),
  ('United States', 'Beaver Island State Park Golf Course'),
  ('United States', 'Beaver Lake Golf Country Club'),
  ('United States', 'Beaver Meadow Golf Club'),
  ('United States', 'Beaver Meadows Golf Club'),
  ('United States', 'Beaver Meadows Golf Recreation'),
  ('United States', 'Beaver Pioneer Park Golf Course'),
  ('United States', 'Beaver River Golf Club'),
  ('United States', 'Beaver Valley Golf Club'),
  ('United States', 'Beavercreek Golf Club'),
  ('United States', 'Beaverhead Country Club'),
  ('United States', 'Beckett Ridge Country Club'),
  ('United States', 'Bedens Brook Club The'),
  ('United States', 'Bedford Country Club'),
  ('United States', 'Bedford Creek Golf Course'),
  ('United States', 'Bedford Elks Golf Club'),
  ('United States', 'Bedford Golf Course'),
  ('United States', 'Bedford Golf Tennis Club'),
  ('United States', 'Bedford Hills Golf Club'),
  ('United States', 'Bedford Trails Golf Course'),
  ('United States', 'Bedford Valley'),
  ('United States', 'Bedfordshire Golf Club'),
  ('United States', 'Bedrock Golf Club'),
  ('United States', 'Beech Creek Golf Club'),
  ('United States', 'Beech Creek Golf Course'),
  ('United States', 'Beech Hollow Golf Course'),
  ('United States', 'Beech Mountain Club The'),
  ('United States', 'Beech Nut Golf Course'),
  ('United States', 'Beech Woods Golf Course'),
  ('United States', 'Beeches Golf Club'),
  ('United States', 'Beechmont Country Club'),
  ('United States', 'Beechwood Country Club'),
  ('United States', 'Beechwood Golf Club'),
  ('United States', 'Beechwood Golf Course'),
  ('United States', 'Beechwood Greens Golf Club'),
  ('United States', 'Beechwoods Golf Course'),
  ('United States', 'Beekman Country Club Highland Valley'),
  ('United States', 'Beekman Country Club Taconic Highland'),
  ('United States', 'Beekman Country Club Valley Taconic'),
  ('United States', 'Bekaert Employees Athletic Association'),
  ('United States', 'Bel Air Country Club'),
  ('United States', 'Bel Air Golf Course'),
  ('United States', 'Bel-Wood Country Club'),
  ('United States', 'Belden Hill Golf Course'),
  ('United States', 'Belgrade Lakes Golf Club'),
  ('United States', 'Belk Park Golf Course'),
  ('United States', 'Bell Gardens Golf Course'),
  ('United States', 'Bell Nob Executive Golf Course'),
  ('United States', 'Bell Nob Golf Course'),
  ('United States', 'Bella Collina Golf Club'),
  ('United States', 'Bella Collina Towne Golf Club Carnoustie Course'),
  ('United States', 'Bella Collina Towne Golf Club Muirfield Course'),
  ('United States', 'Bella Ridge Golf Club'),
  ('United States', 'Bella Rosa Golf Course'),
  ('United States', 'Bella Verde Golf Club Montebello 9 Course'),
  ('United States', 'Bella Verde Golf Club Signature Par 3 Course'),
  ('United States', 'Bella Vista Country Club'),
  ('United States', 'Bella Vista Country Club Berksdale Course'),
  ('United States', 'Bella Vista Country Club Brittany Executive Course'),
  ('United States', 'Bella Vista Country Club Country Club Course'),
  ('United States', 'Bella Vista Country Club Dogwood Hills Course'),
  ('United States', 'Bella Vista Country Club Highlands Course'),
  ('United States', 'Bella Vista Country Club Kingswood Course'),
  ('United States', 'Bella Vista Country Club Scotsdale Course'),
  ('United States', 'Bella Vista Golf Course'),
  ('United States', 'Bellair Golf Park'),
  ('United States', 'Bellaire At The Villages Executive Golf Trail'),
  ('United States', 'Belle Fourche Country Club'),
  ('United States', 'Belle Glade Country Club Calusa Course'),
  ('United States', 'Belle Glade Country Club Seminole Course'),
  ('United States', 'Belle Glade Country Club Tequesta Course'),
  ('United States', 'Belle Glade Municipal Golf Club'),
  ('United States', 'Belle Haven Country Club'),
  ('United States', 'Belle Isle Practice Center'),
  ('United States', 'Belle Meade Country Club'),
  ('United States', 'Belle Plaine Country Club'),
  ('United States', 'Belle River Golf and Country Club'),
  ('United States', 'Belle Terre Country Club'),
  ('United States', 'Bellefonte Country Club'),
  ('United States', 'Bellemeade Plantation At Valdosta Country Club'),
  ('United States', 'Bellerive Country Club'),
  ('United States', 'Belles Springs Golf Course'),
  ('United States', 'Belleview Golf Club'),
  ('United States', 'Belleville Country Club'),
  ('United States', 'Bellevue Country Club'),
  ('United States', 'Bellevue Golf Club'),
  ('United States', 'Bellevue Municipal Golf Course'),
  ('United States', 'Bellewood Golf Club'),
  ('United States', 'Bellingham Golf Country Club'),
  ('United States', 'Bello Woods Golf Course'),
  ('United States', 'Bellows Falls Country Club'),
  ('United States', 'Bellport Country Club'),
  ('United States', 'Bellwood Oaks Golf Course'),
  ('United States', 'Belmar Golf Club'),
  ('United States', 'Belmond Country Club'),
  ('United States', 'Belmont At The Villages Executive Golf Trail'),
  ('United States', 'Belmont Country Club'),
  ('United States', 'Belmont Golf Course'),
  ('United States', 'Belmont Hills Country Club'),
  ('United States', 'Belmont Lake Golf Club'),
  ('United States', 'Belmont Pines Golf Course'),
  ('United States', 'Belmor Park Golf Country Club'),
  ('United States', 'Beloit Club'),
  ('United States', 'Beloit Country Club'),
  ('United States', 'Belterra Golf Course'),
  ('United States', 'Belvedere Golf Club'),
  ('United States', 'Bemidji Town & Country Club'),
  ('United States', 'Bemus Point Golf Course'),
  ('United States', 'Ben Hawes At Ben Hawes State Park'),
  ('United States', 'Ben Lomond Golf Course'),
  ('United States', 'Benbow Valley Rv Resort Golf Course'),
  ('United States', 'Bend Of The River Golf Club'),
  ('United States', 'Benkelman Golf Course'),
  ('United States', 'Bennett City Golf'),
  ('United States', 'Bennett Valley Golf Course'),
  ('United States', 'Bennington Golf Club'),
  ('United States', 'Benona Shores Golf Course'),
  ('United States', 'Bensalem Township Country Club'),
  ('United States', 'Benson Park Golf Course'),
  ('United States', 'Bent Creek Country Club'),
  ('United States', 'Bent Creek Golf Club'),
  ('United States', 'Bent Creek Golf Course'),
  ('United States', 'Bent Hickory Golf Course Country Club'),
  ('United States', 'Bent Pine Golf Club'),
  ('United States', 'Bent Tree Country Club'),
  ('United States', 'Bent Tree Golf Club'),
  ('United States', 'Bentley Village Golf Club'),
  ('United States', 'Benton Country Club'),
  ('United States', 'Bentwater Golf Club'),
  ('United States', 'Bentwinds Golf Country Club'),
  ('United States', 'Bentwood Golf Course'),
  ('United States', 'Benvenue Country Club'),
  ('United States', 'Bergen Golf Course'),
  ('United States', 'Bergen Point Golf Club'),
  ('United States', 'Berkeley Country Club'),
  ('United States', 'Berkeley Hall Golf Club North Course'),
  ('United States', 'Berkeley Hall Golf Club South Course'),
  ('United States', 'Berkeley Hills Country Club'),
  ('United States', 'Berkleigh Golf Club'),
  ('United States', 'Berkley Hills Golf Course'),
  ('United States', 'Berkshire Country Club'),
  ('United States', 'Berkshire Hill Golf Course'),
  ('United States', 'Berkshire Hills Country Club'),
  ('United States', 'Berkshire Valley Golf Course'),
  ('United States', 'Berlin Country Club'),
  ('United States', 'Bermuda Creek Golf Club'),
  ('United States', 'Bermuda Run Country Club East Course'),
  ('United States', 'Bermuda Run Country Club West Course'),
  ('United States', 'Berrien Hills Golf Club'),
  ('United States', 'Berthold Golf Club'),
  ('United States', 'Berwick Golf Club'),
  ('United States', 'Bethany Bay Golf Club'),
  ('United States', 'Bethel Inn Country Club'),
  ('United States', 'Bethlehem Country Club'),
  ('United States', 'Bethlehem Golf Club Executive Nine'),
  ('United States', 'Bethlehem Golf Club Monocacy Course'),
  ('United States', 'Betmar Acres Golf Club Blue Course'),
  ('United States', 'Betmar Acres Golf Club Gold Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Betmar Acres Golf Club White Course'),
  ('United States', 'Betsie Valley'),
  ('United States', 'Better Shots Driving Range'),
  ('United States', 'Beverly Country Club'),
  ('United States', 'Beverly Golf Tennis Club'),
  ('United States', 'Bey Lea Municipal Golf Course'),
  ('United States', 'Biddeford Saco Country Club'),
  ('United States', 'Bidermann Golf Club'),
  ('United States', 'Bidwell Park Golf Course'),
  ('United States', 'Big Al''s Greens & Grille'),
  ('United States', 'Big Beaver Creek Golf Club'),
  ('United States', 'Big Bend Golf Country Club'),
  ('United States', 'Big Canyon Country Club'),
  ('United States', 'Big Creek Country Club'),
  ('United States', 'Big Creek Golf Course'),
  ('United States', 'Big Easy Ranch 9 Hole Course'),
  ('United States', 'Big Fish Golf Course'),
  ('United States', 'Big Foot Country Club'),
  ('United States', 'Big Lake Country Club'),
  ('United States', 'Big Met Golf Course'),
  ('United States', 'Big Oak Public Golf Course'),
  ('United States', 'Big Oaks Golf Course'),
  ('United States', 'Big River Golf Course'),
  ('United States', 'Big Rock Country Club'),
  ('United States', 'Big Run Golf Club'),
  ('United States', 'Big Sand Lake Club Golf Course'),
  ('United States', 'Big Sky Resort Golf Course'),
  ('United States', 'Big Spring Country Club'),
  ('United States', 'Big Stone Golf Course'),
  ('United States', 'Big Sugar Golf Club'),
  ('United States', 'Big Walnut Golf Course'),
  ('United States', 'Bigfoot Golf Country Club'),
  ('United States', 'Bigwood Golf Course'),
  ('United States', 'Bijou Municipal Golf Course'),
  ('United States', 'Bill Flynns Windham Country Club'),
  ('United States', 'Bill Roberts Municipal Golf Course'),
  ('United States', 'Billy Caldwell Golf Course'),
  ('United States', 'Biltmore Country Club'),
  ('United States', 'Biltmore Forest Country Club'),
  ('United States', 'Binder Park Golf Course'),
  ('United States', 'Binghamton Country Club'),
  ('United States', 'Birch Bay Village Golf Course'),
  ('United States', 'Birch Cedar At Mccall Golf Course'),
  ('United States', 'Birch Creek Golf Club'),
  ('United States', 'Birch Hill Country Club'),
  ('United States', 'Birch Hills Golf Course'),
  ('United States', 'Birch Pointe Golf Club'),
  ('United States', 'Birch Ridge Golf Course'),
  ('United States', 'Birch Run Golf Club'),
  ('United States', 'Birch Run Golf Course'),
  ('United States', 'Birch Tree Golf Course'),
  ('United States', 'Birch Valley Golf Course'),
  ('United States', 'Birchbank Golf Course'),
  ('United States', 'Birchwood At Spring Lake Golf Club'),
  ('United States', 'Birchwood Country Club'),
  ('United States', 'Birchwood Farms Golf & Country Club'),
  ('United States', 'Birchwood Golf Course'),
  ('United States', 'Bird City Golf Course'),
  ('United States', 'Bird Creek Golf Club'),
  ('United States', 'Bird Homestead Golf Course'),
  ('United States', 'Birdie Ranch At Silver Creek'),
  ('United States', 'Birdsfoot Golf Club'),
  ('United States', 'Birdwood Golf Course'),
  ('United States', 'Birdwood Golf Course Par 3'),
  ('United States', 'Birkdale Golf Club'),
  ('United States', 'Birmingham Country Club'),
  ('United States', 'Birnam Wood Golf Club'),
  ('United States', 'Birnamwood Golf Course'),
  ('United States', 'Bishop Country Club'),
  ('United States', 'Bishops Bay Golf Course'),
  ('United States', 'Bishops Gate Golf And Lakeside Community'),
  ('United States', 'Bison Golf Club'),
  ('United States', 'Bitter Creek At Willowcreek Golf Club'),
  ('United States', 'Bittersweet Golf Club'),
  ('United States', 'Bixby Village Golf Course'),
  ('United States', 'Black At Bethpage State Park Golf Course'),
  ('United States', 'Black At D Fairchild Wheeler Golf Course'),
  ('United States', 'Black Bear Golf Club'),
  ('United States', 'Black Bear Golf Course'),
  ('United States', 'Black Birch Golf Club'),
  ('United States', 'Black Brook Golf Club'),
  ('United States', 'Black Bull Golf Club'),
  ('United States', 'Black Canyon Golf Course'),
  ('United States', 'Black Creek Club'),
  ('United States', 'Black Creek Golf Club'),
  ('United States', 'Black Creek Golf Course'),
  ('United States', 'Black Desert Resort'),
  ('United States', 'Black Diamond Golf Course'),
  ('United States', 'Black Forest at Wilderness Valley'),
  ('United States', 'Black Gold Golf Club'),
  ('United States', 'Black Hall Club'),
  ('United States', 'Black Hawk Run Golf Club'),
  ('United States', 'Black Horse At Bayonet Black Horse Golf Course'),
  ('United States', 'Black Horse Golf And Learning Center'),
  ('United States', 'Black Lake Golf Course'),
  ('United States', 'Black Locust Disc Golf Course'),
  ('United States', 'Black Mesa Golf Club'),
  ('United States', 'Black Mountain Golf Course'),
  ('United States', 'Black Oak Golf Club'),
  ('United States', 'Black Oak Golf Course'),
  ('United States', 'Black River Golf Club'),
  ('United States', 'Black River Golf Course'),
  ('United States', 'Black Rock Country Club'),
  ('United States', 'Black Rock Creek Golf Club'),
  ('United States', 'Black Rock Golf Course'),
  ('United States', 'Black Sheep Golf Club'),
  ('United States', 'Black Squirrel Golf Club'),
  ('United States', 'Black Stone Creek Golf Club'),
  ('United States', 'Black Swan Country Club'),
  ('United States', 'Black Wolf Links'),
  ('United States', 'Blackberry Farm Golf Course'),
  ('United States', 'Blackberry Oaks Golf Course'),
  ('United States', 'Blackberry Ridge'),
  ('United States', 'Blackberry Trails Golf Course'),
  ('United States', 'Blackduck Municipal Golf Course'),
  ('United States', 'Blackfoot Municipal Golf Course'),
  ('United States', 'Blackford Golf Club'),
  ('United States', 'Blackhawk Country Club'),
  ('United States', 'Blackhawk Golf Course'),
  ('United States', 'Blackhead Mountain Lodge Country Club'),
  ('United States', 'Blackheath Golf Club'),
  ('United States', 'Blackledge Country Club Andersons Glen'),
  ('United States', 'Blackledge Country Club Gilead Highlands'),
  ('United States', 'Blacklick Woods Golf Course'),
  ('United States', 'Blackmer Municipal Golf Course'),
  ('United States', 'Blackmoor Golf Club'),
  ('United States', 'Blackmount Country Club'),
  ('United States', 'Blacksburg Country Club'),
  ('United States', 'Blackshire'),
  ('United States', 'Blackstone Country Club'),
  ('United States', 'Blackstone Golf Club'),
  ('United States', 'Blackstone Golf Course'),
  ('United States', 'Blackstone National Golf Club'),
  ('United States', 'Blackthorn Golf Club'),
  ('United States', 'Blackwell Municipal Golf Course'),
  ('United States', 'Blackwolf Run'),
  ('United States', 'Blackwood Golf Course'),
  ('United States', 'Blair Academy Golf Course'),
  ('United States', 'Blair Park Golf Course'),
  ('United States', 'Blakely Town Country Club'),
  ('United States', 'Blank Park Golf Course'),
  ('United States', 'Blessings Golf Club'),
  ('United States', 'Blind Brook Club'),
  ('United States', 'Blink Bonnie Golf Links'),
  ('United States', 'Blissful Meadows Golf Club'),
  ('United States', 'Bloch Memorial Golf Course'),
  ('United States', 'Bloody Point Golf Course'),
  ('United States', 'Bloomfield Country Club'),
  ('United States', 'Bloomfield Hills Country Club'),
  ('United States', 'Blooming Prairie Country Club'),
  ('United States', 'Bloomingdale Golf Club'),
  ('United States', 'Bloomingdale Golfers Club'),
  ('United States', 'Bloomington Country Club'),
  ('United States', 'Blossom Trails Golf Club'),
  ('United States', 'Blowing Rock Country Club'),
  ('United States', 'Blue Ash Golf Course'),
  ('United States', 'Blue At Arrowhead Golf Course'),
  ('United States', 'Blue At Bethpage State Park Golf Course'),
  ('United States', 'Blue At Congressional Country Club'),
  ('United States', 'Blue At Eisenhower Golf Course'),
  ('United States', 'Blue At Eisenhower Park Golf Course'),
  ('United States', 'Blue At Ford Hill Country Club'),
  ('United States', 'Blue At Golf Club Of Avon'),
  ('United States', 'Blue At Penn State Golf Courses'),
  ('United States', 'Blue At Ringgold Golf Club'),
  ('United States', 'Blue Bell Country Club'),
  ('United States', 'Blue Boy West Golf Course'),
  ('United States', 'Blue Cypress Golf Club'),
  ('United States', 'Blue Cypress Golf Rv Resort'),
  ('United States', 'Blue Fox Run Golf Club Blue Nine'),
  ('United States', 'Blue Fox Run Golf Club Red Nine'),
  ('United States', 'Blue Fox Run Golf Club White Nine'),
  ('United States', 'Blue Gold At Lindenwood Golf Club'),
  ('United States', 'Blue Gold At Westchester Golf Country Club'),
  ('United States', 'Blue Grass Over Look At Old Westbury Golf Country Club'),
  ('United States', 'Blue Green At Sunken Meadow State Park Golf Course'),
  ('United States', 'Blue Green At Town Of Colonie Golf Course'),
  ('United States', 'Blue Heron Golf Club'),
  ('United States', 'Blue Heron Golf Course'),
  ('United States', 'Blue Heron Pines'),
  ('United States', 'Blue Heron Pines Golf Club'),
  ('United States', 'Blue Hill Country Club'),
  ('United States', 'Blue Hills Country Club'),
  ('United States', 'Blue Hills Golf Course'),
  ('United States', 'Blue Knob Golf Club'),
  ('United States', 'Blue Lakes Country Club'),
  ('United States', 'Blue Mound Golf & Country Club'),
  ('United States', 'Blue Mountain View Golf Course'),
  ('United States', 'Blue Red At Buck Hill Falls Golf Club'),
  ('United States', 'Blue Red At Foxfire Country Club'),
  ('United States', 'Blue Red At Glen Oaks Club'),
  ('United States', 'Blue Red At Highland Lakes Golf Course'),
  ('United States', 'Blue Red At Little Mill Country Club'),
  ('United States', 'Blue Red At Myakka Pines Golf Club'),
  ('United States', 'Blue Red At Shawnee Inn Golf Resort'),
  ('United States', 'Blue Red At Shenandoah Valley Golf Club'),
  ('United States', 'Blue Red At Valley Brook Country Club'),
  ('United States', 'Blue Red At Western Turnpike Golf Course'),
  ('United States', 'Blue Ridge At Blue Ridge Trail Golf Club'),
  ('United States', 'Blue Ridge Country Club'),
  ('United States', 'Blue Ridge Golf Club'),
  ('United States', 'Blue Ridge Shadows Golf Club'),
  ('United States', 'Blue Rock Golf Course'),
  ('United States', 'Blue Rock Springs Golf Course East'),
  ('United States', 'Blue Rock Springs Golf Course West'),
  ('United States', 'Blue Shamrock Golf Club'),
  ('United States', 'Blue Sky Golf Club'),
  ('United States', 'Blue Stone Golf Course'),
  ('United States', 'Blue Top Ridge'),
  ('United States', 'Blue White At Edgewood Country Club'),
  ('United States', 'Blue White At Sugar Mill Country Club'),
  ('United States', 'Blue White At Timber Point Country Club'),
  ('United States', 'Blue White At Woods Golf Course The'),
  ('United States', 'Blueberry Hill Golf Club'),
  ('United States', 'Blueberry Hills Golf Course'),
  ('United States', 'Blueberry Pines Golf Club'),
  ('United States', 'Blueberry Plantation Country Club'),
  ('United States', 'Bluefield Elks Country Club'),
  ('United States', 'Blues Creek Golf Club'),
  ('United States', 'Bluestone Country Club'),
  ('United States', 'Bluff Creek Golf Course'),
  ('United States', 'Bluff Point Golf Club Resort'),
  ('United States', 'Bluff Pointe Golf Course Learning Center'),
  ('United States', 'Bluff River At Del Rio Country Club'),
  ('United States', 'Bluffs Golf Course'),
  ('United States', 'Bluffton Golf Club'),
  ('United States', 'Blush Hill Country Club'),
  ('United States', 'Blythe Golf Course'),
  ('United States', 'Blythefield Country Club'),
  ('United States', 'Blytheville Country Club'),
  ('United States', 'Blytheville Municipal Golf Course'),
  ('United States', 'Bob Burns Golf'),
  ('United States', 'Bob O Link Golf Club'),
  ('United States', 'Bob Oconnor Golf Course At Schenley Park The First Tee Of Pittsburgh'),
  ('United States', 'Bob-O-Link Golf Course'),
  ('United States', 'Bobby Jones Golf Club Championship Course'),
  ('United States', 'Bobby Jones Golf Club John Hamilton Gillespie Course'),
  ('United States', 'Bobby Jones Golf Course The Azalea Nine'),
  ('United States', 'Bobby Jones Golf Course The Cupp Links'),
  ('United States', 'Bobby Jones Golf Course The Magnolia Nine'),
  ('United States', 'Bobby Nichols Golf Course'),
  ('United States', 'Bobcat At Forest Country Club The'),
  ('United States', 'Boca Delray Golf Country Club'),
  ('United States', 'Boca Dunes Golf Country Club'),
  ('United States', 'Boca Greens Country Club'),
  ('United States', 'Boca Grove Plantation Golf Course'),
  ('United States', 'Boca Lago Country Club East Course'),
  ('United States', 'Boca Lago Country Club South Course'),
  ('United States', 'Boca Lago Country Club West Course'),
  ('United States', 'Boca Pointe Country Club'),
  ('United States', 'Boca Rio Golf Club'),
  ('United States', 'Boca Royale Golf Country Club'),
  ('United States', 'Boca West Country Club Dye Iv'),
  ('United States', 'Boca West Country Club Fazio Ii'),
  ('United States', 'Boca West Country Club Palmer I'),
  ('United States', 'Boca West Country Club Palmer Iii'),
  ('United States', 'Bocaire Country Club'),
  ('United States', 'Boeuf River Country Club'),
  ('United States', 'Bogalusa Country Club'),
  ('United States', 'Bogart At The Villages Executive Golf Trail'),
  ('United States', 'Bogey Club The'),
  ('United States', 'Bogey Hills Country Club'),
  ('United States', 'Boiling Springs Golf Course'),
  ('United States', 'Boise Ranch Golf Course'),
  ('United States', 'Boissevain Golf Club'),
  ('United States', 'Bolingbrook Golf Club'),
  ('United States', 'Bomber''s Golf Course'),
  ('United States', 'Bon Air Country Club'),
  ('United States', 'Bon Homme Country Club'),
  ('United States', 'Bonaventure Golf Club'),
  ('United States', 'Bonavista State Park Golf Course'),
  ('United States', 'Bonham Golf Country Club'),
  ('United States', 'Bonifay Country Club Destin Fort Walton'),
  ('United States', 'Bonifay Country Club Fort Walton Pensacola'),
  ('United States', 'Bonifay Country Club Pensacola Destin'),
  ('United States', 'Bonita Bay East Cypress Course'),
  ('United States', 'Bonita Bay East Sabal Course'),
  ('United States', 'Bonita Fairways'),
  ('United States', 'Bonita Golf Club'),
  ('United States', 'Bonita National Golf Country Club'),
  ('United States', 'Bonita Pass At The Villages Executive Golf Trail'),
  ('United States', 'Bonneville Golf Course'),
  ('United States', 'Bonnie Brae Golf Course'),
  ('United States', 'Bonnie Briar Country Club'),
  ('United States', 'Bonnie Brook Golf Course'),
  ('United States', 'Bonnie Brook Golf Range'),
  ('United States', 'Bonnie Dundee Golf Club'),
  ('United States', 'Bonnie View Golf Course'),
  ('United States', 'Bonniebrook Club House Golf Course'),
  ('United States', 'Bookcliff Country Club'),
  ('United States', 'Booker Country Club'),
  ('United States', 'Boomerang Links'),
  ('United States', 'Boone Creek Golf Course'),
  ('United States', 'Boone Golf Club'),
  ('United States', 'Boone Links Golf Course'),
  ('United States', 'Boone Valley Golf Club'),
  ('United States', 'Booneville Country Club'),
  ('United States', 'Boonsboro Country Club'),
  ('United States', 'Boothbay Harbor Country Club'),
  ('United States', 'Bos Landen Golf Club'),
  ('United States', 'Boscobel Country Club'),
  ('United States', 'Boston Golf Club'),
  ('United States', 'Bostonia Country Club'),
  ('United States', 'Botten''s Green Acres'),
  ('United States', 'Bottom Bellemeade At Valdosta Country Club'),
  ('United States', 'Boughton Ridge Golf Course'),
  ('United States', 'Boulder At Towa Golf Resort'),
  ('United States', 'Boulder City Municipal Golf Course'),
  ('United States', 'Boulder Country Club Championship Course'),
  ('United States', 'Boulder Country Club Par 3 Course'),
  ('United States', 'Boulder Creek Golf Club'),
  ('United States', 'Boulder Creek Golf Club Coyote Run Eldorado Valley'),
  ('United States', 'Boulder Creek Golf Club Desert Hawk Coyote Run'),
  ('United States', 'Boulder Creek Golf Club Desert Hawk Eldorado Valley'),
  ('United States', 'Boulder Creek Golf Country Club'),
  ('United States', 'Boulder Creek Golf Course'),
  ('United States', 'Boulder Oaks Golf Club'),
  ('United States', 'Boulder Pointe Golf Club'),
  ('United States', 'Boulder Ridge Country Club'),
  ('United States', 'Boundary Oak Golf Course'),
  ('United States', 'Bountiful Ridge Golf Course'),
  ('United States', 'Bourne Golf Club'),
  ('United States', 'Boutetourt Golf Swim Club'),
  ('United States', 'Bow Creek Golf Course'),
  ('United States', 'Bowden Golf Course'),
  ('United States', 'Bowdon Golf Club'),
  ('United States', 'Bowes Creek Country Club'),
  ('United States', 'Bowler''s Country Club'),
  ('United States', 'Bowling Green Country Club'),
  ('United States', 'Bowling Green Golf Club'),
  ('United States', 'Brabender Southwoods Golf Course'),
  ('United States', 'Brackenridge Heights Golf Course'),
  ('United States', 'Bradenton Country Club'),
  ('United States', 'Bradford Country Club'),
  ('United States', 'Bradford Creek Golf Club'),
  ('United States', 'Bradford Golf Club'),
  ('United States', 'Bradshaw Ranch Golf Course'),
  ('United States', 'Brae Burn Country Club'),
  ('United States', 'Brae Burn Golf Country Club'),
  ('United States', 'Brae Burn Golf Course'),
  ('United States', 'Brae Loch Golf Course'),
  ('United States', 'Brae-Burn Golf Club'),
  ('United States', 'Braelinn Golf Club'),
  ('United States', 'Braemar Country Club'),
  ('United States', 'Braemar Golf Course'),
  ('United States', 'Brainerd Golf Course'),
  ('United States', 'Braintree Municipal Golf Course'),
  ('United States', 'Brambles'),
  ('United States', 'Brambleton Regional Park Golf Course'),
  ('United States', 'Bramblewood Country Club'),
  ('United States', 'Brandermill Country Club'),
  ('United States', 'Brandon Golf Course'),
  ('United States', 'Brandywine Bay Golf Club'),
  ('United States', 'Branson Bay Golf Course'),
  ('United States', 'Brantingham Golf Club'),
  ('United States', 'Brasstown Valley Resort'),
  ('United States', 'Brattleboro Country Club'),
  ('United States', 'Brays Island Plantation Golf Club'),
  ('United States', 'Brazells Creek Golf Course'),
  ('United States', 'Brea Creek Golf Course'),
  ('United States', 'Breakfast Hill Golf Club'),
  ('United States', 'Breaking Bad Golf'),
  ('United States', 'Breckenridge Golf Tennis Club'),
  ('United States', 'Breckinridge County Community Center'),
  ('United States', 'Breckinridge Golf Course'),
  ('United States', 'Breda Golf Club'),
  ('United States', 'Breezewood Golf Links'),
  ('United States', 'Brent Bruehl Memorial Golf Course'),
  ('United States', 'Brentwood Country Club'),
  ('United States', 'Brentwood Farms Golf Club'),
  ('United States', 'Brentwood Golf Club Creekside Diablo Course'),
  ('United States', 'Brentwood Golf Club Creekside Hillside Course'),
  ('United States', 'Brentwood Golf Club Hillside Diablo Course'),
  ('United States', 'Brentwood Golf Club and Banquet Center'),
  ('United States', 'Breton Bay Golf Country Club'),
  ('United States', 'Bretton Woods Country Club'),
  ('United States', 'Bretton Woods Golf Course'),
  ('United States', 'Brevofield Golf Course'),
  ('United States', 'Briar Bay Golf Course'),
  ('United States', 'Briar Creek Country Club'),
  ('United States', 'Briar Creek Golf Course'),
  ('United States', 'Briar Leaf Golf Club'),
  ('United States', 'Briar Ridge Golf Course'),
  ('United States', 'Briarbrook Golf Course'),
  ('United States', 'Briardale Greens Golf Course'),
  ('United States', 'Briarwood At The Villages Executive Golf Trail'),
  ('United States', 'Briarwood Club of Ankeny'),
  ('United States', 'Briarwood Country Club'),
  ('United States', 'Briarwood Country Club At Sun City West'),
  ('United States', 'Briarwood Country Club The'),
  ('United States', 'Briarwood Golf Club'),
  ('United States', 'Briarwood Golf Club Final Five Course'),
  ('United States', 'Brickshire Golf Club'),
  ('United States', 'Brickyard At Riverside'),
  ('United States', 'Brickyard Crossing Golf Course'),
  ('United States', 'Bridge Golf Course'),
  ('United States', 'Bridge Street Golf At Snipes'),
  ('United States', 'Bridgemill Athletic Club'),
  ('United States', 'Bridger Creek Golf Course'),
  ('United States', 'Bridger Mountain Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Bridges Golf Course'),
  ('United States', 'Bridgeton Berry Hill Golf Course'),
  ('United States', 'Bridgewater Country Club'),
  ('United States', 'Bridgewater Golf Club'),
  ('United States', 'Bridgewater Links Golf Course'),
  ('United States', 'Bridgton Highlands Country Club'),
  ('United States', 'Brier Creek Country Club'),
  ('United States', 'Brier Creek Golf Course'),
  ('United States', 'Brierwood Country Club'),
  ('United States', 'Briery Country Club'),
  ('United States', 'Brigantine Clipper At Shipyard Golf Club'),
  ('United States', 'Brigantine Golf Links'),
  ('United States', 'Briggs Woods Golf Course'),
  ('United States', 'Bright Grandview Golf Course'),
  ('United States', 'Bright Meadows Golf Course Championship'),
  ('United States', 'Bright Meadows Golf Course Executive'),
  ('United States', 'Brighton Dale Links'),
  ('United States', 'Brighton Park Golf Course'),
  ('United States', 'Brights Creek Golf Club'),
  ('United States', 'Brightwater Club'),
  ('United States', 'Brightwood Hills Golf Course'),
  ('United States', 'Bringhurst Golf Course'),
  ('United States', 'Brinkley Country Club'),
  ('United States', 'Bristol Golf Club At The Cedars'),
  ('United States', 'Bristol Golf Park'),
  ('United States', 'Bristol Oaks Golf Club'),
  ('United States', 'Bristol Ridge Golf Course'),
  ('United States', 'Bristow Golf Country Club'),
  ('United States', 'Bristow Manor Golf Club'),
  ('United States', 'Britt Country Club'),
  ('United States', 'Broad Bay Country Club'),
  ('United States', 'Broad Run Golf Practice Facility'),
  ('United States', 'Broad Run Golfers Club'),
  ('United States', 'Broadacres Golf Club'),
  ('United States', 'Broadlands Golf Club'),
  ('United States', 'Broadlands Golf Course'),
  ('United States', 'Broadmoor Country Club'),
  ('United States', 'Broadmoor Golf Club'),
  ('United States', 'Broadmoor Golf Course'),
  ('United States', 'Broadmoor Golf Links'),
  ('United States', 'Broadmoore Golf Course'),
  ('United States', 'Brockton Country Club'),
  ('United States', 'Brockville Country Club'),
  ('United States', 'Brockville Highland Golf Club'),
  ('United States', 'Broken Arrow Golf Club'),
  ('United States', 'Broken Pine Golf Country Club'),
  ('United States', 'Broken Sound Club Club Course'),
  ('United States', 'Broken Sound Club Old Course'),
  ('United States', 'Broken Tee Englewood Golf Course'),
  ('United States', 'Broken Tee Englewood Par 3 Course'),
  ('United States', 'Bronson Golf Club'),
  ('United States', 'Bronzwood Golf Club'),
  ('United States', 'Brook Lea Country Club'),
  ('United States', 'Brook Tree Golf Course'),
  ('United States', 'Brook Valley Country Club'),
  ('United States', 'Brooke Hills Park Golf Course'),
  ('United States', 'Brookfield Country Club'),
  ('United States', 'Brookfield Hills Golf Course'),
  ('United States', 'Brookhaven Country Club'),
  ('United States', 'Brookhaven Golf Club'),
  ('United States', 'Brookhill Golf Course'),
  ('United States', 'Brookhills Golf Club'),
  ('United States', 'Brookings Country Club'),
  ('United States', 'Brooklake Country Club'),
  ('United States', 'Brookland Golf Park'),
  ('United States', 'Brooklawn Country Club'),
  ('United States', 'Brookledge Golf Course'),
  ('United States', 'Brookmeadow Country Club'),
  ('United States', 'Brookridge Golf Country Club'),
  ('United States', 'Brookridge Golf Fitness Championship Course'),
  ('United States', 'Brookridge Golf Fitness West Nine'),
  ('United States', 'Brooks Golf Club'),
  ('United States', 'Brookshire Golf Club'),
  ('United States', 'Brookside Country Club'),
  ('United States', 'Brookside Golf & Country Club'),
  ('United States', 'Brookside Golf Club'),
  ('United States', 'Brookside Golf Club C W Koiner Course'),
  ('United States', 'Brookside Golf Club E O Nay Course'),
  ('United States', 'Brookside Golf Course'),
  ('United States', 'Brookside Golf and Grill'),
  ('United States', 'Brookside Par 3 Golf Club'),
  ('United States', 'Brookside resort'),
  ('United States', 'Brookstone Golf Country Club'),
  ('United States', 'Brooksville Country Club'),
  ('United States', 'Brooktrails Golf Course'),
  ('United States', 'Brookview Golf Course'),
  ('United States', 'Brookville Country Club'),
  ('United States', 'Brookwood Golf Club'),
  ('United States', 'Brookwood Golf Course'),
  ('United States', 'Brookwoods Golf Club'),
  ('United States', 'Broomsedge Golf Club'),
  ('United States', 'Brown Acres Golf Course'),
  ('United States', 'Brown County Golf Course'),
  ('United States', 'Brown Deer Golf Club'),
  ('United States', 'Brown Deer Park Golf Course'),
  ('United States', 'Brown''s Run Country Club'),
  ('United States', 'Browns Lake Golf Course'),
  ('United States', 'Browns Mill Golf Course'),
  ('United States', 'Brownson Country Club'),
  ('United States', 'Brownstone Country Club Resort'),
  ('United States', 'Bruce Hills Golf Course'),
  ('United States', 'Brunswick Country Club'),
  ('United States', 'Brunswick Golf Club'),
  ('United States', 'Brunswick Golf Club Azalea Magnolia Course'),
  ('United States', 'Brunswick Golf Club Dogwood Azalea Course'),
  ('United States', 'Brunswick Golf Club Magnolia Dogwood'),
  ('United States', 'Brunswick Greens Golf Course'),
  ('United States', 'Brush Creek Golf Course'),
  ('United States', 'Brushy Mountain Golf Club'),
  ('United States', 'Brute At Grand Geneva Resort Spa'),
  ('United States', 'Bryan Park Champions Course'),
  ('United States', 'Bryan Park Players Course'),
  ('United States', 'Bryce Resort'),
  ('United States', 'Bryden Canyon Public Golf Course'),
  ('United States', 'Bryn Mawr Country Club'),
  ('United States', 'Buckeye Hills Country Club'),
  ('United States', 'Buckhorn Springs Golf Country Club'),
  ('United States', 'Buckingham Golf Country Club'),
  ('United States', 'Buckmeadow Golf Club'),
  ('United States', 'Bucknell Golf Club'),
  ('United States', 'Bucks Run Golf Club'),
  ('United States', 'Buckskin Golf Club'),
  ('United States', 'Bucksport Golf Club'),
  ('United States', 'Buena Vista Country Club'),
  ('United States', 'Buena Vista Golf Course'),
  ('United States', 'Buena Vista University Golf Course at Lake Creek'),
  ('United States', 'Buenaventura Golf Course'),
  ('United States', 'Buffalo Creek Golf Course'),
  ('United States', 'Buffalo Dunes Golf Course'),
  ('United States', 'Buffalo Golf Course'),
  ('United States', 'Buffalo Grove Golf Club'),
  ('United States', 'Buffalo Heights Golf Course'),
  ('United States', 'Buffalo Ridge Springs Golf Course'),
  ('United States', 'Buffalo Rock Golf Venue'),
  ('United States', 'Buffalo Run Golf Course'),
  ('United States', 'Buffalo Tournament Club'),
  ('United States', 'Buffalo Trace Golf Course'),
  ('United States', 'Buffalo Valley Golf Course'),
  ('United States', 'Buffer Park Golf Course'),
  ('United States', 'Buhl Farm Golf Course Driving Range'),
  ('United States', 'Bull Run Golf Club'),
  ('United States', 'Bull Valley Golf Club'),
  ('United States', 'Bull''s Eye Country Club'),
  ('United States', 'Bulls Bay Golf Club'),
  ('United States', 'Bulls Bridge Golf Club'),
  ('United States', 'Buncombe Creek Golf Course'),
  ('United States', 'Bungay Brook Golf Club'),
  ('United States', 'Bunker Hill Golf Course'),
  ('United States', 'Bunker Hills Executive Course'),
  ('United States', 'Bunker Hills Golf Course'),
  ('United States', 'Bunker Links Golf Course'),
  ('United States', 'Bunn Golf Course'),
  ('United States', 'Bur Mil Park Golf Course'),
  ('United States', 'Burden Lake Country Club'),
  ('United States', 'Burgis Back Nine'),
  ('United States', 'Burgundy Bay Golf Course'),
  ('United States', 'Burke Golf Course'),
  ('United States', 'Burke Lake Golf Center'),
  ('United States', 'Burl Oaks Golf Club'),
  ('United States', 'Burlingame Country Club'),
  ('United States', 'Burlington Country Club'),
  ('United States', 'Burlington Golf Club'),
  ('United States', 'Burnet Park Golf Course'),
  ('United States', 'Burnham Woods Golf Course'),
  ('United States', 'Burning Oak Country Club'),
  ('United States', 'Burning Ridge Golf Course'),
  ('United States', 'Burning Tree Country Club'),
  ('United States', 'Burning Tree Golf Club'),
  ('United States', 'Burnt Pine At Sandestin Golf And Beach Resort'),
  ('United States', 'Burr Oak Golf Club'),
  ('United States', 'Bushwood Golf Course'),
  ('United States', 'Butler Country Club'),
  ('United States', 'Butler National Golf Club'),
  ('United States', 'Butlers Golf Course Lakeside Course'),
  ('United States', 'Butlers Golf Course Woodside Course'),
  ('United States', 'Butte Country Club'),
  ('United States', 'Butte Creek Country Club'),
  ('United States', 'Butte des Morts Country Club'),
  ('United States', 'Butter Valley Golf Port'),
  ('United States', 'Butterbrook Golf Club'),
  ('United States', 'Butterfield Country Club'),
  ('United States', 'Butterfield Golf Course'),
  ('United States', 'Butterfield Trail Golf Club'),
  ('United States', 'Buttermilk Falls Golf Club'),
  ('United States', 'Butternut Creek Golf Course'),
  ('United States', 'Butternut Farm Golf Club'),
  ('United States', 'Butternut Hills Golf Course'),
  ('United States', 'Butternut Valley Golf'),
  ('United States', 'Button Hole Short Course Teaching Center'),
  ('United States', 'Buttonwood Golf Course'),
  ('United States', 'Byrd At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Byrncliff Golf Resort Banquets'),
  ('United States', 'Byron Hills Golf Course'),
  ('United States', 'C Way Golf Club'),
  ('United States', 'CNC Links'),
  ('United States', 'Cabarrus Country Club'),
  ('United States', 'Caberfae Peaks'),
  ('United States', 'Cabin Creek Golf Club'),
  ('United States', 'Cabin Greens Golf Course'),
  ('United States', 'Cabinet View Country Club'),
  ('United States', 'Cable Hollow Golf Course'),
  ('United States', 'Cabot Citrus Farms Karoo Course'),
  ('United States', 'Cabot Citrus Farms The Roost Course'),
  ('United States', 'Cabot Citrus Farms The Squeeze Course'),
  ('United States', 'Cabot Citrus Farms The Wedge Course'),
  ('United States', 'Cabot Links'),
  ('United States', 'Cacapon Resort State Park'),
  ('United States', 'Caddie Shack'),
  ('United States', 'Caddo Creek Golf Club'),
  ('United States', 'Cadillac Country Club'),
  ('United States', 'Cadiz Country Club'),
  ('United States', 'Caesars Pocono Palace Cove Haven'),
  ('United States', 'Cajun Pines Golf Course'),
  ('United States', 'Calabasas Golf Country Club'),
  ('United States', 'Calderone Farms Golf Club'),
  ('United States', 'Caldwell Country Club'),
  ('United States', 'Caldwell Golf Course'),
  ('United States', 'Caledonia Country Club'),
  ('United States', 'Caledonia Golf Club'),
  ('United States', 'Caledonia Golf Fish Club'),
  ('United States', 'Calhoun Elks Lodge Golf Club'),
  ('United States', 'Calhoun Hills Golf Complex'),
  ('United States', 'Caliente Springs Resort'),
  ('United States', 'California City Municipal Par 3 Golf Course'),
  ('United States', 'California Country Club'),
  ('United States', 'California Golf Club Of San Francisco'),
  ('United States', 'California Golf Course'),
  ('United States', 'California Oaks Golf Course'),
  ('United States', 'Callahan Golf Links'),
  ('United States', 'Callier Springs Country Club'),
  ('United States', 'Callippe Preserve Golf Course'),
  ('United States', 'Caloosa Golf Country Club'),
  ('United States', 'Calumet Country Club'),
  ('United States', 'Calumet Golf Club'),
  ('United States', 'Calusa Country Club'),
  ('United States', 'Calusa Country Club 12 Hole Course'),
  ('United States', 'Calusa Lakes Golf Club'),
  ('United States', 'Calusa Pines Golf Club'),
  ('United States', 'Calvert Crossing Golf Club'),
  ('United States', 'Cam2 Golf Club At Springview'),
  ('United States', 'Camaloch Golf Club'),
  ('United States', 'Camargo Club'),
  ('United States', 'Camarillo Springs Golf Course'),
  ('United States', 'Camas Meadows Golf Club'),
  ('United States', 'Cambrian Hills Golf Course'),
  ('United States', 'Cambridge Country Club'),
  ('United States', 'Camden Country Club'),
  ('United States', 'Camelback Golf Club Ambiente Course'),
  ('United States', 'Camelback Golf Club Padre Course'),
  ('United States', 'Camelia Boganvilia Golf Course At Cleveland Heights Golf Club'),
  ('United States', 'Cameron At Buffalo Hill Golf Club'),
  ('United States', 'Cameron Park Country Club'),
  ('United States', 'Camillus Golf Club'),
  ('United States', 'Camino Heights Golf Course'),
  ('United States', 'Camp Creek Golf Club'),
  ('United States', 'Camp Robinson Duffers Club'),
  ('United States', 'Campbells Scottish Highlands Golf Course'),
  ('United States', 'Campestre De Nogales'),
  ('United States', 'Camroden Golf Course'),
  ('United States', 'Canaan Country Club'),
  ('United States', 'Canadian Golf Club'),
  ('United States', 'Canajoharie Country Club'),
  ('United States', 'Canandaigua Country Club'),
  ('United States', 'Canasawacta Country Club'),
  ('United States', 'Candia Woods Golf Links'),
  ('United States', 'Candler Hills Golf Club'),
  ('United States', 'Candler Park Golf Course'),
  ('United States', 'Candlestone'),
  ('United States', 'Candlewood Country Club'),
  ('United States', 'Candlewood Golf Club'),
  ('United States', 'Candlewood Lake Club'),
  ('United States', 'Candlewood Valley Country Club'),
  ('United States', 'Cando Golf Club'),
  ('United States', 'Cane Garden Country Club Allamanda Hibiscus Course'),
  ('United States', 'Cane Garden Country Club Hibiscus Jacaranda Course'),
  ('United States', 'Cane Garden Country Club Jacaranda Allamanda Course'),
  ('United States', 'Cane Patch Par 3 Blue Nine'),
  ('United States', 'Cane Patch Par 3 Red Nine'),
  ('United States', 'Cane Patch Par 3 Yellow Nine'),
  ('United States', 'Cane Row Golf Turf Club'),
  ('United States', 'Canebrake Golf Club'),
  ('United States', 'Caney Golf Club'),
  ('United States', 'Cannon Golf Club'),
  ('United States', 'Cannonball Golf Course'),
  ('United States', 'Cannongate Golf At Sun City Peachtree'),
  ('United States', 'Canoa Hills Golf Course'),
  ('United States', 'Canoa Ranch Golf Club'),
  ('United States', 'Canongate Golf Club Lee Wilson Course'),
  ('United States', 'Canongate Golf Club Roquemore Burton Course'),
  ('United States', 'Canterbury Golf Club'),
  ('United States', 'Canterbury Green Golf Course'),
  ('United States', 'Canterbury Woods Country Club'),
  ('United States', 'Canterwood Golf Club'),
  ('United States', 'Cantiague Park Golf Course'),
  ('United States', 'Cantigny Golf'),
  ('United States', 'Cantigny Golf Youth Links'),
  ('United States', 'Canton Golf Club'),
  ('United States', 'Canyata Golf Club'),
  ('United States', 'Canyon At Forest Highlands Golf Club'),
  ('United States', 'Canyon At Mountain Dell Golf Course'),
  ('United States', 'Canyon Breeze Golf Course'),
  ('United States', 'Canyon Club'),
  ('United States', 'Canyon Crest Country Club'),
  ('United States', 'Canyon Estates Golf Course'),
  ('United States', 'Canyon Farms Golf Club'),
  ('United States', 'Canyon Gate Country Club'),
  ('United States', 'Canyon Hill At La Paloma Country Club'),
  ('United States', 'Canyon Hills Park Golf Course'),
  ('United States', 'Canyon Lake Country Club'),
  ('United States', 'Canyon Lakes At Spanish Trail Country Club'),
  ('United States', 'Canyon Lakes Golf Course'),
  ('United States', 'Canyon Lakes Golf Course Brewery'),
  ('United States', 'Canyon Meadow At Fox Hollow At Lakewood'),
  ('United States', 'Canyon Mesa Country Club'),
  ('United States', 'Canyon Oaks Country Club'),
  ('United States', 'Canyon River Golf Club'),
  ('United States', 'Canyon Springs Golf Course'),
  ('United States', 'Canyons At Oasis Golf Club'),
  ('United States', 'Canyons Golf Course'),
  ('United States', 'Cape Ann Golf Course'),
  ('United States', 'Cape Arundel Golf Club'),
  ('United States', 'Cape Cod Country Club'),
  ('United States', 'Cape Cod National Golf Club'),
  ('United States', 'Cape Fear Country Club'),
  ('United States', 'Cape Fear National At Brunswick Forest'),
  ('United States', 'Cape Girardeau Country Club'),
  ('United States', 'Cape Haze Links At Rotonda Golf Country Club'),
  ('United States', 'Cape Jaycee Municipal Golf Course'),
  ('United States', 'Cape May National Golf Club'),
  ('United States', 'Cape May Par 3 And Driving Range'),
  ('United States', 'Cape Neddick Country Club'),
  ('United States', 'Cape Royal Golf Club King Prince'),
  ('United States', 'Cape Royal Golf Club Prince Queen'),
  ('United States', 'Cape Royal Golf Club Queen King'),
  ('United States', 'Capital Canyon Club'),
  ('United States', 'Capital City Club Crabapple'),
  ('United States', 'Capital City Country Club'),
  ('United States', 'Capital Hills At Albany'),
  ('United States', 'Capitol City Golf Club'),
  ('United States', 'Capon Springs Golf Course'),
  ('United States', 'Capri Isles Golf Club'),
  ('United States', 'Caprock Ranch'),
  ('United States', 'Captains Cove'),
  ('United States', 'Captains Golf Course Port'),
  ('United States', 'Captains Golf Course Starboard'),
  ('United States', 'Captiva Course At South Seas Island Resort'),
  ('United States', 'Carbon Country Club'),
  ('United States', 'Card Inc. Golf & Country Club'),
  ('United States', 'Card Sound Golf Club'),
  ('United States', 'Cardinal At Diamondhead Country Club'),
  ('United States', 'Cardinal At Newport News Golf Club'),
  ('United States', 'Cardinal Country Club'),
  ('United States', 'Cardinal Creek Golf Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Blue Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Red Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams White Course'),
  ('United States', 'Cardinal Golf Course'),
  ('United States', 'Cardinal Hills Golf Course'),
  ('United States', 'Carefree Country Club'),
  ('United States', 'Carey Park Golf Course'),
  ('United States', 'Caribou Country Club'),
  ('United States', 'Caribou Highlands Golf And Rv'),
  ('United States', 'Carillon Golf Course'),
  ('United States', 'Carl Dickman Par 3 Golf Course'),
  ('United States', 'Carleton Glen Golf Club'),
  ('United States', 'Carlisle Barracks Golf Course'),
  ('United States', 'Carlisle Country Club'),
  ('United States', 'Carlowden Country Club'),
  ('United States', 'Carlton Oaks Lodge Country Club'),
  ('United States', 'Carmel Valley Ranch Resort'),
  ('United States', 'Carmi Country Club'),
  ('United States', 'Carmichaels Golf Club'),
  ('United States', 'Carnduff Golf Club'),
  ('United States', 'Caro Golf Club'),
  ('United States', 'Carolina Club The'),
  ('United States', 'Carolina Colours Golf Club'),
  ('United States', 'Carolina Country Club'),
  ('United States', 'Carolina Golf Club'),
  ('United States', 'Carolina Golf Par 3 Course'),
  ('United States', 'Carolina Lakes Golf Club'),
  ('United States', 'Carolina Lakes Golf Course'),
  ('United States', 'Carolina Meadows Golf Course'),
  ('United States', 'Carolina National Golf Club Egret Nine'),
  ('United States', 'Carolina National Golf Club Heron Nine'),
  ('United States', 'Carolina National Golf Club Ibis Nine'),
  ('United States', 'Carolina Plantation Golf Club'),
  ('United States', 'Carolina Shores Golf Country Club'),
  ('United States', 'Carolina Springs Golf Club'),
  ('United States', 'Carolinas Country Club'),
  ('United States', 'Caroline Virginia At Mallory Hill Golf Course'),
  ('United States', 'Carriage Greens Golf Club'),
  ('United States', 'Carrington Crossroads Golf Club'),
  ('United States', 'Carrington Golf Club'),
  ('United States', 'Carroll Country Club'),
  ('United States', 'Carroll County Country Club'),
  ('United States', 'Carroll Meadows golf course'),
  ('United States', 'Carroll Municipal Golf Course'),
  ('United States', 'Carroll Valley Golf Resort'),
  ('United States', 'Carrollton Park DGC'),
  ('United States', 'Carrollwood Country Club Cypress Meadows Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Carrollwood Country Club Meadows Pines Course'),
  ('United States', 'Carrollwood Country Club Pines Cypress Course'),
  ('United States', 'Carson Valley Golf Course'),
  ('United States', 'Carter Country Club'),
  ('United States', 'Carter Heights Golf Course'),
  ('United States', 'Carter Plantation'),
  ('United States', 'Carters Sweetland Pines Par 3 Golf Course'),
  ('United States', 'Cartersville Country Club'),
  ('United States', 'Carthage Golf Course'),
  ('United States', 'Carthage Municipal Golf Course'),
  ('United States', 'Caruthersville Country Club'),
  ('United States', 'Cary Country Club'),
  ('United States', 'Casablanca Resort Casino'),
  ('United States', 'Cascade Golf Course'),
  ('United States', 'Cascade Hills Country Club'),
  ('United States', 'Cascade Par 3 Golf Club'),
  ('United States', 'Cascades Golf Course'),
  ('United States', 'Cascata'),
  ('United States', 'Caseville Golf Course'),
  ('United States', 'Cashie Golf Country Club'),
  ('United States', 'Casolwood Golf Course'),
  ('United States', 'Casper Country Club'),
  ('United States', 'Casper Golf Club Highlands Links Course'),
  ('United States', 'Casper Golf Club Highlands Park Course'),
  ('United States', 'Casper Golf Club Park Links Course'),
  ('United States', 'Casperkill Golf Club'),
  ('United States', 'Cassadaga Country Club'),
  ('United States', 'Cassel Hills'),
  ('United States', 'Casselberry Golf Club'),
  ('United States', 'Casserly Par 3 Golf Course'),
  ('United States', 'Cassville Golf Club'),
  ('United States', 'Castine Golf Club'),
  ('United States', 'Castle Bay Country Club'),
  ('United States', 'Castle Creek Country Club'),
  ('United States', 'Castle Creek Golf Club'),
  ('United States', 'Castle Highlands Golf Course'),
  ('United States', 'Castle Hills Golf Course'),
  ('United States', 'Castle Oaks Golf Club'),
  ('United States', 'Castle Pines Golf Club'),
  ('United States', 'Castle Rock Golf Course'),
  ('United States', 'Castle Rock Golf Recreation'),
  ('United States', 'Castle Shannon Golf Course'),
  ('United States', 'Castlegar Golf Club'),
  ('United States', 'Castlewood Golf Course'),
  ('United States', 'Castlewoods Country Club The Bear Course'),
  ('United States', 'Caswell Pines Golf Club'),
  ('United States', 'Catalina Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Catalina Island Golf Club'),
  ('United States', 'Catalina Saddlebrooke At Saddlebrooke Country Club'),
  ('United States', 'Catamount Club'),
  ('United States', 'Catamount Ranch And Club'),
  ('United States', 'Catatonk Golf Club'),
  ('United States', 'Catawba Country Club'),
  ('United States', 'Catawba Creek Golf Course'),
  ('United States', 'Catawba Island Club'),
  ('United States', 'Cateechee Golf Club'),
  ('United States', 'Cathedral Canyon Golf Club'),
  ('United States', 'Cato Park'),
  ('United States', 'Catskill Golf Club'),
  ('United States', 'Catta Verdera Country Club'),
  ('United States', 'Cattail Creek Golf Course'),
  ('United States', 'Cattail Crossing Golf Course'),
  ('United States', 'Cattails At Meadowview Golf Course'),
  ('United States', 'Cattails Golf Club'),
  ('United States', 'Causeway Club'),
  ('United States', 'Cavalier Golf Yacht Club'),
  ('United States', 'Cavaliers Country Club'),
  ('United States', 'Cavalry Club'),
  ('United States', 'Cave Creek Golf Course'),
  ('United States', 'Caverns Country Club Resort'),
  ('United States', 'Cazenovia Country Club'),
  ('United States', 'Cazenovia Golf Club'),
  ('United States', 'Cazenovia Golf Course'),
  ('United States', 'Cda National Reserve'),
  ('United States', 'CeCelia''s Golf Course'),
  ('United States', 'Cecil Field Golf Club'),
  ('United States', 'Cedar Aspen At Mccall Golf Course'),
  ('United States', 'Cedar Beach Golf Course'),
  ('United States', 'Cedar Bend Golf Course'),
  ('United States', 'Cedar Chase Golf Club'),
  ('United States', 'Cedar Creek At Star Valley Ranch Country Club'),
  ('United States', 'Cedar Creek Family Golf Center'),
  ('United States', 'Cedar Creek Golf Club'),
  ('United States', 'Cedar Creek Golf Country Club'),
  ('United States', 'Cedar Creek Golf Course'),
  ('United States', 'Cedar Crest Golf Course'),
  ('United States', 'Cedar Farms Golf Club'),
  ('United States', 'Cedar Glen Golf Club'),
  ('United States', 'Cedar Glen Golf Course'),
  ('United States', 'Cedar Hammock Golf Country Club'),
  ('United States', 'Cedar Heights Golf Course'),
  ('United States', 'Cedar Hill Country Club'),
  ('United States', 'Cedar Hill Golf Club'),
  ('United States', 'Cedar Hill Golf Course'),
  ('United States', 'Cedar Hills Golf Club'),
  ('United States', 'Cedar Hills Golf Club Short Course'),
  ('United States', 'Cedar Hills Golf Course'),
  ('United States', 'Cedar Knob Golf Course'),
  ('United States', 'Cedar Lake Club'),
  ('United States', 'Cedar Lake Golf Club'),
  ('United States', 'Cedar Links Country Club'),
  ('United States', 'Cedar Park Golf Course'),
  ('United States', 'Cedar Park Putting Course'),
  ('United States', 'Cedar Pines Golf Course'),
  ('United States', 'Cedar Point Country Club'),
  ('United States', 'Cedar Point Country Club Par 3 Course'),
  ('United States', 'Cedar Point Golf Club'),
  ('United States', 'Cedar Pointe Golf Course'),
  ('United States', 'Cedar Rapids Country Club'),
  ('United States', 'Cedar Ridge Country Club'),
  ('United States', 'Cedar Ridge Golf Course'),
  ('United States', 'Cedar Ridges Golf Course'),
  ('United States', 'Cedar River Golf Club'),
  ('United States', 'Cedar River Golf Course'),
  ('United States', 'Cedar Rock Country Club'),
  ('United States', 'Cedar Springs Golf Course'),
  ('United States', 'Cedar Trace'),
  ('United States', 'Cedar Valley Golf And Country Club'),
  ('United States', 'Cedar Valley Golf Center'),
  ('United States', 'Cedar Valley Golf Club'),
  ('United States', 'Cedar Valley Golf Course'),
  ('United States', 'Cedar View Golf Course'),
  ('United States', 'Cedarbrook Country Club'),
  ('United States', 'Cedarbrook Golf Course'),
  ('United States', 'Cedarcrest Golf Course'),
  ('United States', 'Cedardell Golf Club'),
  ('United States', 'Cedaredge Golf Club'),
  ('United States', 'Cedarholm Golf Course'),
  ('United States', 'Cedars At High Cedars Golf Club'),
  ('United States', 'Cedars Country Club'),
  ('United States', 'Cedars Edge Golf Course'),
  ('United States', 'Cedars Golf Club'),
  ('United States', 'Cedars Golf Country Club'),
  ('United States', 'Cedars Golf Course'),
  ('United States', 'Cedarview Golf Course'),
  ('United States', 'Cedarwood Country Club'),
  ('United States', 'Celebration Golf Club'),
  ('United States', 'Celina Lynx Golf Club'),
  ('United States', 'Centennial Acres Midday Sunset'),
  ('United States', 'Centennial Acres Sunrise Midday'),
  ('United States', 'Centennial Acres Sunrise Sunset'),
  ('United States', 'Centennial At Philadelphia Country Club'),
  ('United States', 'Centennial Farm Golf Club'),
  ('United States', 'Centennial Golf Course'),
  ('United States', 'Centennial Park 9-Hole Golf Course'),
  ('United States', 'Centennial Toomey At Huntingdon Valley Country Club'),
  ('United States', 'Centennial Valley Golf Course'),
  ('United States', 'Center Country Club'),
  ('United States', 'Center West At Ridgewood Country Club The'),
  ('United States', 'Centerbrook Golf Course'),
  ('United States', 'Centerpointe Country Club'),
  ('United States', 'Centerton Golf Club'),
  ('United States', 'Central Valley Golf Club'),
  ('United States', 'Centre Hills Golf Course'),
  ('United States', 'Century Country Club'),
  ('United States', 'Century Oaks Golf Club'),
  ('United States', 'Cerbat Cliffs Golf Course'),
  ('United States', 'Cerritos Ironwood Golf Course'),
  ('United States', 'Chagrin Valley Country Club'),
  ('United States', 'Chalk Mountain Golf Course'),
  ('United States', 'Challenge At Pinewild Country Club'),
  ('United States', 'Challenge At Suntree Country Club'),
  ('United States', 'Challenge At White Deer Golf Club'),
  ('United States', 'Challenger 3 Golf Course'),
  ('United States', 'Challenger At Blue Hill Country Club'),
  ('United States', 'Challenger At Palm Valley Country Club'),
  ('United States', 'Challenger Golf Club Los Cumbres Course'),
  ('United States', 'Challis Golf Course'),
  ('United States', 'Chamberlyne Country Club'),
  ('United States', 'Chambers Bay'),
  ('United States', 'Chambersburg Country Club'),
  ('United States', 'Champaign Country Club'),
  ('United States', 'Champion At Battle Creek Public Golf'),
  ('United States', 'Champion At Fox Ridge Golf Course'),
  ('United States', 'Champion Hill Golf Course'),
  ('United States', 'Champion Hills Club'),
  ('United States', 'Champion Hills Country Club'),
  ('United States', 'Champion Lakes Golf And Country Club'),
  ('United States', 'Champion Lakes Golf Course'),
  ('United States', 'Champions At Palm Aire Country Club'),
  ('United States', 'Champions Golf Course'),
  ('United States', 'Champions Pointe Golf Club'),
  ('United States', 'Champions Retreat Golf Club Nicklaus Bluff Nine'),
  ('United States', 'Champions Retreat Golf Club Palmer Island Nine'),
  ('United States', 'Champions Retreat Golf Club Player Creek Nine'),
  ('United States', 'Champions Run'),
  ('United States', 'Champions Run Country Club'),
  ('United States', 'Championsgate Country Club'),
  ('United States', 'Championsgate Golf Club Champions 9'),
  ('United States', 'Championsgate Golf Club International'),
  ('United States', 'Championsgate Golf Club National'),
  ('United States', 'Championship At Blue Hill Country Club'),
  ('United States', 'Championship At Boca Raton Municipal Golf Course'),
  ('United States', 'Championship At Buffalo Hill Golf Club'),
  ('United States', 'Championship At Burns Park Golf Course'),
  ('United States', 'Championship At Colony West Country Club'),
  ('United States', 'Championship At Cyprian Keyes Golf Club'),
  ('United States', 'Championship At Ferncroft Country Club'),
  ('United States', 'Championship At Harbor Links Golf Course'),
  ('United States', 'Championship At Hollybrook Golf Tennis Club'),
  ('United States', 'Championship At Incline Village Golf Resort'),
  ('United States', 'Championship At Lake Shastina Golf Resort'),
  ('United States', 'Championship At Moon Valley Country Club'),
  ('United States', 'Championship At Palm Valley Country Club'),
  ('United States', 'Championship At Rebsamen Park Golf Course'),
  ('United States', 'Championship At Ridgecrest Golf Course'),
  ('United States', 'Championship At Rockland Lake Golf Course'),
  ('United States', 'Championship At Saint Clair Country Club'),
  ('United States', 'Championship At Saratoga Spa State Park'),
  ('United States', 'Championship At Seven Springs Country Club'),
  ('United States', 'Championship At Viewpoint Golf Resort'),
  ('United States', 'Championship Course At Crosswinds Golf Club'),
  ('United States', 'Championship Golf Course At University Of New Mexico'),
  ('United States', 'Champlain Country Club'),
  ('United States', 'Chandler Golf Course'),
  ('United States', 'Chandler Park Golf Course'),
  ('United States', 'Chanticlair Golf Club'),
  ('United States', 'Chanticleer At Greenville Country Club'),
  ('United States', 'Chantilly National Golf Country Club'),
  ('United States', 'Chaparral Country Club'),
  ('United States', 'Chapel Hill Country Club'),
  ('United States', 'Chapel Hill Golf Course'),
  ('United States', 'Chapel Hills Golf Course'),
  ('United States', 'Chappell Golf Course'),
  ('United States', 'Chardell Golf Course'),
  ('United States', 'Chardon Lakes Golf Course'),
  ('United States', 'Chardonnay Golf Club'),
  ('United States', 'Chariot Run'),
  ('United States', 'Charles River Country Club'),
  ('United States', 'Charles T Myers Public Golf Course'),
  ('United States', 'Charleston Municipal Golf Course'),
  ('United States', 'Charleston National Golf Club'),
  ('United States', 'Charleston Pines At Lima Golf Country Club'),
  ('United States', 'Charleston Springs Golf Course North Course'),
  ('United States', 'Charleston Springs Golf Course South Course'),
  ('United States', 'Charlevoix Municipal Golf Course'),
  ('United States', 'Charlie Vettner Golf Course'),
  ('United States', 'Charlie Yates Golf Course'),
  ('United States', 'Charlotte Country Club'),
  ('United States', 'Charlotte Harbor National Golf Club'),
  ('United States', 'Charlotte National Golf Course'),
  ('United States', 'Charter Oak Country Club'),
  ('United States', 'Chartiers Country Club'),
  ('United States', 'Charwood Golf Club'),
  ('United States', 'Chase Golf Course'),
  ('United States', 'Chase Hammond Golf Club'),
  ('United States', 'Chaska Golf Course'),
  ('United States', 'Chaska Par 30'),
  ('United States', 'Chaska Town Course'),
  ('United States', 'Chastain Park Golf Course'),
  ('United States', 'Chatata Valley Golf Club'),
  ('United States', 'Chateau Elan Golf Club Chateau Course'),
  ('United States', 'Chateau Elan Golf Club Executive Par 3 Course'),
  ('United States', 'Chateau Elan Golf Club Woodlands Course'),
  ('United States', 'Chateau Golf Country Club'),
  ('United States', 'Chatham Hills Golf Course'),
  ('United States', 'Chatham Seaside Links'),
  ('United States', 'Chatmoss Country Club'),
  ('United States', 'Chattahoochee Golf Club'),
  ('United States', 'Chattanooga Golf Country Club'),
  ('United States', 'Chattooga Golf Club'),
  ('United States', 'Chatuge Shores Golf Course'),
  ('United States', 'Chautauqua Golf Club Hill Course'),
  ('United States', 'Chautauqua Golf Club Lake Course'),
  ('United States', 'Chautauqua Point Golf Racquetball Center'),
  ('United States', 'Cheam Mountain Golf Course'),
  ('United States', 'Cheboygan Golf & Country Club'),
  ('United States', 'Chechessee Creek Club'),
  ('United States', 'Cheeca Lodge'),
  ('United States', 'Cheena Star Course At Santa Ana Golf Club'),
  ('United States', 'Chelmsford Country Club'),
  ('United States', 'Chemawa Golf Course'),
  ('United States', 'Chemung Golf Course'),
  ('United States', 'Chemung Hills Golf Club'),
  ('United States', 'Chena Bend Golf Course'),
  ('United States', 'Chenal Country Club Bear Den Mountain Course'),
  ('United States', 'Chenal Country Club Founders Course'),
  ('United States', 'Chenango Commons Golf Course'),
  ('United States', 'Chenango Valley State Park Golf Course'),
  ('United States', 'Chenequa Country Club'),
  ('United States', 'Chennault Park Golf Course'),
  ('United States', 'Chenoweth'),
  ('United States', 'Chequamegon Bay Golf Club'),
  ('United States', 'Chequessett Yacht Country Club'),
  ('United States', 'Cheraw State Park Golf Course'),
  ('United States', 'Cherokee Choctaw At Big Canoe Golf Club'),
  ('United States', 'Cherokee Creek Golf Club'),
  ('United States', 'Cherokee Golf Center'),
  ('United States', 'Cherokee Golf Country Club'),
  ('United States', 'Cherokee Golf Course'),
  ('United States', 'Cherokee Golf and Country Club'),
  ('United States', 'Cherokee Hills Golf Club'),
  ('United States', 'Cherokee Hills Golf Course'),
  ('United States', 'Cherokee National Golf Course'),
  ('United States', 'Cherokee Plantation'),
  ('United States', 'Cherokee Rose Country Club'),
  ('United States', 'Cherokee Run Golf Club'),
  ('United States', 'Cherokee Seminole At Indian Hills Country Club'),
  ('United States', 'Cherokee Springs Golf Club'),
  ('United States', 'Cherokee Trails Golf Course'),
  ('United States', 'Cherokee Valley Course And Club'),
  ('United States', 'Cherokee Valley Golf Club'),
  ('United States', 'Cherry Creek Golf Club'),
  ('United States', 'Cherry Creek Golf Course'),
  ('United States', 'Cherry Creek Golf The Links Course'),
  ('United States', 'Cherry Creek The Woods Course'),
  ('United States', 'Cherry Hill Country Club'),
  ('United States', 'Cherry Hill Golf Club'),
  ('United States', 'Cherry Hill Golf Course'),
  ('United States', 'Cherry Hill Golf Resort'),
  ('United States', 'Cherry Hills Course At Palmer Legends'),
  ('United States', 'Cherry Hills Golf Course'),
  ('United States', 'Cherry Island Golf Course'),
  ('United States', 'Cherry Oaks Golf Club'),
  ('United States', 'Cherry Ridge'),
  ('United States', 'Cherry Ridge Golf Course'),
  ('United States', 'Cherry Valley Club'),
  ('United States', 'Cherry Valley Country Club'),
  ('United States', 'Cherry Valley Golf Course'),
  ('United States', 'Cherryville Country Club'),
  ('United States', 'Cherrywood Golf Club'),
  ('United States', 'Cherrywood Golf Course'),
  ('United States', 'Chesapeake Bay Golf Club At Rising Sun'),
  ('United States', 'Chesapeake Golf Club'),
  ('United States', 'Chesapeake Hills Golf Club'),
  ('United States', 'Chesapeake Run Golf Club'),
  ('United States', 'Cheshire Hills Golf Course'),
  ('United States', 'Chesnee Country Club'),
  ('United States', 'Chestatee Golf Club'),
  ('United States', 'Chester Country Club'),
  ('United States', 'Chester Golf Club'),
  ('United States', 'Chester River Yacht Country Club'),
  ('United States', 'Chester Valley Golf Club'),
  ('United States', 'Chester Washington Golf Course'),
  ('United States', 'Chestnut Hill Golf Course'),
  ('United States', 'Chestnut Hills'),
  ('United States', 'Chestnut Hills Golf Club'),
  ('United States', 'Chestnut Mountain Golf Club'),
  ('United States', 'Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Chestnut Valley Golf Course'),
  ('United States', 'Chetremon Golf Course'),
  ('United States', 'Cheval Golf And Athletic Club'),
  ('United States', 'Chevy Chase Club'),
  ('United States', 'Chevy Chase Country Club'),
  ('United States', 'Chevy Chase Golf Club'),
  ('United States', 'Chewelah Golf Country Club'),
  ('United States', 'Chewelah Golf Country Club 9 Hole Course'),
  ('United States', 'Cheyenne Country Club'),
  ('United States', 'Cheyenne Golf Course'),
  ('United States', 'Cheyenne Hills Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course Coyote Run Junior'),
  ('United States', 'Chi Chi Rodriguez Golf Club'),
  ('United States', 'Chicago Golf Association'),
  ('United States', 'Chicago Golf Club'),
  ('United States', 'Chicago Heights Park District Golf Course East'),
  ('United States', 'Chicago Heights Park District Golf Course West'),
  ('United States', 'Chicago Highlands Club'),
  ('United States', 'Chick Evans Golf Course'),
  ('United States', 'Chickasaw Country Club'),
  ('United States', 'Chickasaw Point Golf Course'),
  ('United States', 'Chickasaw Pointe Golf Club'),
  ('United States', 'Chickasha Golf Country Club'),
  ('United States', 'Chicopee Country Club'),
  ('United States', 'Chicopee Woods Golf Course Mill Nine'),
  ('United States', 'Chicopee Woods Golf Course School Nine'),
  ('United States', 'Chicopee Woods Golf Course Village Nine'),
  ('United States', 'Chicora Country Club'),
  ('United States', 'Chiefland Golf Country Club'),
  ('United States', 'Chikaming Country Club'),
  ('United States', 'Childress Country Club'),
  ('United States', 'Chilliwack Golf Club'),
  ('United States', 'Chimera Golf Club'),
  ('United States', 'Chimney Oaks Golf Club'),
  ('United States', 'Chimney Rock Municipal Golf Course'),
  ('United States', 'China Lake Golf Course'),
  ('United States', 'Chinook Golf Country Club'),
  ('United States', 'Chip''s Clubhouse'),
  ('United States', 'Chipeta Golf Course'),
  ('United States', 'Chippanee Golf Club'),
  ('United States', 'Chippendale Golf Course'),
  ('United States', 'Chippers Practice Range'),
  ('United States', 'Chippewa Banks Disc Golf Course'),
  ('United States', 'Chippewa Golf Club'),
  ('United States', 'Chippewa Hills Country Club'),
  ('United States', 'Chiricahua Course At Desert Mountain Golf Club'),
  ('United States', 'Chisel Creek Golf Club'),
  ('United States', 'Chisholm Hills Country Club'),
  ('United States', 'Chockoyotte Country Club'),
  ('United States', 'Choctaw Cherokee At Indian Hills Country Club'),
  ('United States', 'Choctaw Country Club'),
  ('United States', 'Choctaw Creek At Big Canoe Golf Club'),
  ('United States', 'Choctaw Creek Golf Course'),
  ('United States', 'Cholla Course At We Ko Pa Golf Club'),
  ('United States', 'Chomonix Golf Course'),
  ('United States', 'Chosen Valley Golf Club'),
  ('United States', 'Choteau Country Club'),
  ('United States', 'Chris Bargas Golf Club At Whitney Farms'),
  ('United States', 'Christiana Creek Country Club'),
  ('United States', 'Christina Lake Golf Club')
on conflict (country, name) do nothing;