insert into public.golf_courses (country, name) values
  ('United States', 'Miami Shores Golf Course'),
  ('United States', 'Miami Springs Golf Country Club'),
  ('United States', 'Miami Valley Golf Club'),
  ('United States', 'Miami Whitewater Forest Golf Course'),
  ('United States', 'Miamiview Golf Course'),
  ('United States', 'Miccosukee Golf Country Club Barracuda Course'),
  ('United States', 'Miccosukee Golf Country Club Dolphin Course'),
  ('United States', 'Miccosukee Golf Country Club Marlin Course'),
  ('United States', 'Michaywe Pines'),
  ('United States', 'Michigan City Municipal Golf Course'),
  ('United States', 'Michigan Meadows Golf Course'),
  ('United States', 'Michipicoten Golf Club'),
  ('United States', 'Micke Grove Golf Links'),
  ('United States', 'Mickey S On Flambeau'),
  ('United States', 'Mickey''s Golf Range'),
  ('United States', 'Mickylee Pitch Putt At The Villages Executive Golf Trail'),
  ('United States', 'Mid Carolina Club'),
  ('United States', 'Mid Iron Golf Club'),
  ('United States', 'Mid Pacific Country Club'),
  ('United States', 'Mid Pines Inn Golf Club'),
  ('United States', 'Mid South Club'),
  ('United States', 'Mid Vallee Golf Course'),
  ('United States', 'Middle Back At Rolling Green Golf Club'),
  ('United States', 'Middle Channel Golf & Country Club'),
  ('United States', 'Middle Lake At Woodbridge Golf Country Club'),
  ('United States', 'Middle South At Heather Hill Country Club'),
  ('United States', 'Middlebrook Country Club'),
  ('United States', 'Middlecreek Golf Course'),
  ('United States', 'Middlefork Country Club'),
  ('United States', 'Middlesboro Country Club'),
  ('United States', 'Middleton Golf Course'),
  ('United States', 'Middletown Country Club'),
  ('United States', 'Midland Country Club'),
  ('United States', 'Midland Hills Country Club'),
  ('United States', 'Midland Trail Golf Club'),
  ('United States', 'Midland Valley Golf Club'),
  ('United States', 'Midlane Golf Resort'),
  ('United States', 'Midlothian Country Club'),
  ('United States', 'Midnight Sun Golf Course'),
  ('United States', 'Midvale Golf Country Club'),
  ('United States', 'Midville Country Club'),
  ('United States', 'Midway Golf Club'),
  ('United States', 'Midway Golf Complex'),
  ('United States', 'Midway Par 3 East Nine'),
  ('United States', 'Midway Par 3 Golf Course'),
  ('United States', 'Midway Par 3 North Nine'),
  ('United States', 'Midway Par 3 West Nine'),
  ('United States', 'Milan Creek Golf Course'),
  ('United States', 'Milbrook Club'),
  ('United States', 'Milburn Country Club'),
  ('United States', 'Mile Square Golf Course The Classic Course'),
  ('United States', 'Mile Square Golf Course The Players Course'),
  ('United States', 'Miles City Town Country Club'),
  ('United States', 'Miles Grant Country Club'),
  ('United States', 'Milestone Golf Club'),
  ('United States', 'Milford Country Club'),
  ('United States', 'Milham Park Golf Club'),
  ('United States', 'Mililani Golf Club'),
  ('United States', 'Militia Hill Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Mill Creek Country Club'),
  ('United States', 'Mill Creek Golf Club'),
  ('United States', 'Mill Creek Golf Course'),
  ('United States', 'Mill Creek Golf Course (North)'),
  ('United States', 'Mill Creek Golf Course (South)'),
  ('United States', 'Mill Creek Metroparks Par-3 Golf Course'),
  ('United States', 'Mill Pond Golf Course'),
  ('United States', 'Mill Quarter Plantation Country Club'),
  ('United States', 'Mill Race Golf Camping Resort'),
  ('United States', 'Mill Race Golf Course'),
  ('United States', 'Mill River Club'),
  ('United States', 'Mill River Country Club'),
  ('United States', 'Mill Road Acres Golf Course'),
  ('United States', 'Mill Run Golf Course'),
  ('United States', 'Mill Valley Country Club'),
  ('United States', 'Mill Valley Golf Course'),
  ('United States', 'Millbrook Country Club'),
  ('United States', 'Millbrook Golf Tennis Club'),
  ('United States', 'Millburn Municipal Golf Course'),
  ('United States', 'Millcreek Golf And Learning Center'),
  ('United States', 'Millers Glen Golf Gourse'),
  ('United States', 'Mills Creek Golf Course'),
  ('United States', 'Millsite Golf Course'),
  ('United States', 'Millstone Executive Golf Course'),
  ('United States', 'Millstone Golf Course'),
  ('United States', 'Millwood Country Club'),
  ('United States', 'Millwood Farms Golf Course'),
  ('United States', 'Millwood Landing Golf Rv Resort'),
  ('United States', 'Milt''s Golf Course (9-Hole)'),
  ('United States', 'Milton Freewater Golf Course'),
  ('United States', 'Miltonvale Country Club'),
  ('United States', 'Milts Golf Center'),
  ('United States', 'Milwaukee Country Club'),
  ('United States', 'Mimosa Hills Golf Country Club'),
  ('United States', 'Minakwa Golf Course'),
  ('United States', 'Miner Hills Golf Course'),
  ('United States', 'Mineral Mound State Park Golf Course'),
  ('United States', 'Minerals Golf Club'),
  ('United States', 'Mines Golf Course'),
  ('United States', 'Mingo Bottom Golf Club'),
  ('United States', 'Mingo Springs Golf Course'),
  ('United States', 'Mini Golf'),
  ('United States', 'Mini-Golf'),
  ('United States', 'Mini-golf Course'),
  ('United States', 'Miniature Golf'),
  ('United States', 'Minibel Golf Course'),
  ('United States', 'Mink Lake Golf Course'),
  ('United States', 'Mink Meadows Golf Club'),
  ('United States', 'Minne Monesse Golf Club'),
  ('United States', 'Minneapolis Golf Club'),
  ('United States', 'Minneapolis Golf Course'),
  ('United States', 'Minnechaug Golf Course'),
  ('United States', 'Minnehaha Country Club'),
  ('United States', 'Minneopa Golf Club'),
  ('United States', 'Minnesota Valley Country Club'),
  ('United States', 'Minnesott Golf Country Club'),
  ('United States', 'Minnesuing Acres Conference Center'),
  ('United States', 'Minniwaska Golf Club'),
  ('United States', 'Minocqua Country Club'),
  ('United States', 'Minor Park Golf Course'),
  ('United States', 'Mint Valley Golf Course'),
  ('United States', 'Mint Valley Golf Course Executive Course'),
  ('United States', 'Mira Mesa At The Villages Executive Golf Trail'),
  ('United States', 'Mirabel Golf Club'),
  ('United States', 'Miracle Hill Driving Range'),
  ('United States', 'Miracle Hill Golf Course'),
  ('United States', 'Miramar Memorial Golf Course'),
  ('United States', 'Miromar Lakes Golf Club'),
  ('United States', 'Mirror Lake Golf Club Lake Course'),
  ('United States', 'Mirror Lake Golf Club Mountain Course'),
  ('United States', 'Mirror Lake Golf Course'),
  ('United States', 'Misquamicut Club'),
  ('United States', 'Missaukee Golf Club'),
  ('United States', 'Missing Links Golf Course'),
  ('United States', 'Mission Bay Golf Course'),
  ('United States', 'Mission Hills Country Club'),
  ('United States', 'Mission Hills Gary Player Course'),
  ('United States', 'Mission Hills Golf Course'),
  ('United States', 'Mission Hills Of Hayward Golf Course'),
  ('United States', 'Mission Inn Resort Club El Campeon Course'),
  ('United States', 'Mission Inn Resort Club Las Colinas Course'),
  ('United States', 'Mission Lake Country Club'),
  ('United States', 'Mission Lakes Country Club'),
  ('United States', 'Mission Mountain Golf Club'),
  ('United States', 'Mission Royale Golf Club'),
  ('United States', 'Mission Trails Golf Course'),
  ('United States', 'Mission Valley Golf Country Club'),
  ('United States', 'Mission Viejo Country Club'),
  ('United States', 'Mississippi National Golf Links'),
  ('United States', 'Mississippi State University Golf Club'),
  ('United States', 'Missoula Country Club'),
  ('United States', 'Missouri Bluffs Golf Club'),
  ('United States', 'Mistwood Golf Course'),
  ('United States', 'Misty Creek Country Club'),
  ('United States', 'Mizner Country Club'),
  ('United States', 'Moab Golf Club'),
  ('United States', 'Moanalua Golf Club'),
  ('United States', 'Moccasin Bend Golf Club'),
  ('United States', 'Moccasin Run Golf Course'),
  ('United States', 'Moccasin Wallow Golf Club'),
  ('United States', 'Modesto Municipal Golf Course'),
  ('United States', 'Moffett Field Golf Club'),
  ('United States', 'Mohansic Golf Course'),
  ('United States', 'Mohawk Glen Golf Course'),
  ('United States', 'Mohawk Golf and Country Club'),
  ('United States', 'Mohawk River Country Club Chateau'),
  ('United States', 'Mohawk Valley Country Club'),
  ('United States', 'Mohegan Sun Golf Club'),
  ('United States', 'Mohican Hills Golf Club'),
  ('United States', 'Mohonk Mountain House Golf Course'),
  ('United States', 'Moila Country Club'),
  ('United States', 'Mojave Resort Golf Club'),
  ('United States', 'Monadnock Country Club'),
  ('United States', 'Monarch Bay Golf Club Marina Course'),
  ('United States', 'Monarch Bay Golf Club Tony Lema Course'),
  ('United States', 'Monarch Beach Golf Links'),
  ('United States', 'Monarch Country Club'),
  ('United States', 'Monarch Dunes Golf Club The Challenge Course'),
  ('United States', 'Monarch Dunes Golf Club The Old Course'),
  ('United States', 'Monarch Golf Club At Royal Highlands'),
  ('United States', 'Monarch Ridge Golf Course'),
  ('United States', 'Money Hill Golf Country Club'),
  ('United States', 'Monmouth Country Club'),
  ('United States', 'Monona Golf Course'),
  ('United States', 'Monongahela Valley Country Club'),
  ('United States', 'Monoosnock Country Club'),
  ('United States', 'Monroe Country Club'),
  ('United States', 'Monroe Golf & Country Club'),
  ('United States', 'Monroe Golf Club'),
  ('United States', 'Monroe Golf Country Club'),
  ('United States', 'Monroeton Golf Club'),
  ('United States', 'Monster Golf Club At Resorts World Catskills'),
  ('United States', 'Montague Golf Club'),
  ('United States', 'Montammy Golf Club'),
  ('United States', 'Montauk Downs State Park'),
  ('United States', 'Montaup Country Club'),
  ('United States', 'Montcalm Golf Club'),
  ('United States', 'Montclair Golf Club'),
  ('United States', 'Montclair Golf Course'),
  ('United States', 'Monte Vista Country Club'),
  ('United States', 'Monte Vista Golf Club'),
  ('United States', 'Montecito Country Club'),
  ('United States', 'Monterey Country Club'),
  ('United States', 'Monterey Park Golf Course'),
  ('United States', 'Monterey Pines Golf Club'),
  ('United States', 'Monterey Yacht Country Club'),
  ('United States', 'Montezuma Country Club'),
  ('United States', 'Monticello Country Club'),
  ('United States', 'Monticello Golf Club'),
  ('United States', 'Monticello Golf Club At Savannah Lakes'),
  ('United States', 'Montour Heights Country Club'),
  ('United States', 'Montpelier Elks Country Club'),
  ('United States', 'Montpelier Golf Course'),
  ('United States', 'Montreux Golf Country Club'),
  ('United States', 'Monument At Adobe Creek National Golf Course'),
  ('United States', 'Monument At Troon North Golf Club'),
  ('United States', 'Monument Express At Troon North Golf Club'),
  ('United States', 'Monument Shadows Golf Course'),
  ('United States', 'Moody Quiet Pines Golf Course'),
  ('United States', 'Moon Brook Country Club'),
  ('United States', 'Moon Golf Club'),
  ('United States', 'Moon Walk At Moon Valley Country Club'),
  ('United States', 'Moor Downs Golf Course'),
  ('United States', 'Moore Golf Club'),
  ('United States', 'Moores Mill Golf Club'),
  ('United States', 'Moorestown Field Club'),
  ('United States', 'Mooresville Golf Club'),
  ('United States', 'Moorings Country Club'),
  ('United States', 'Moorland Road Golf Center'),
  ('United States', 'Moorpark Country Club The Canyon Crest Golf Course'),
  ('United States', 'Moorpark Country Club The Creekside Golf Course'),
  ('United States', 'Moorpark Country Club The Ridgeline Golf Course'),
  ('United States', 'Moors Golf Club'),
  ('United States', 'Moose Ridge Golf Course'),
  ('United States', 'Moose River Golf Course'),
  ('United States', 'Moose Run Golf Course Creek Course'),
  ('United States', 'Moose Run Golf Course Hill Course'),
  ('United States', 'Moraga Country Club'),
  ('United States', 'Moraine Country Club'),
  ('United States', 'Morees Cheraw Country Club'),
  ('United States', 'Morefar Golf Course'),
  ('United States', 'Morehead City Country Club'),
  ('United States', 'Morehouse Country Club'),
  ('United States', 'Morgan Creek Golf And Country Club'),
  ('United States', 'Morgan Creek Golf Course'),
  ('United States', 'Morgan Dairy Golf Club'),
  ('United States', 'Morgan Hill Golf Course'),
  ('United States', 'Morgan Hills Golf Course'),
  ('United States', 'Morgan River At Dataw Island Golf Course'),
  ('United States', 'Morgan S Crossing'),
  ('United States', 'Moriah Country Club'),
  ('United States', 'Morning Star Golf Course'),
  ('United States', 'Morningstar Golf''s Club'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Champions Course'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Legends Course'),
  ('United States', 'Morrilton Country Club'),
  ('United States', 'Morris County Golf Club'),
  ('United States', 'Morris Park Country Club'),
  ('United States', 'Morrisburg Golf Club'),
  ('United States', 'Morrison Lake Golf Club'),
  ('United States', 'Morro Bay Golf Course'),
  ('United States', 'Moscow Elks Golf Club'),
  ('United States', 'Moselem Springs Golf Club'),
  ('United States', 'Moses Lake Golf Club'),
  ('United States', 'Mosholu Golf Course'),
  ('United States', 'Moss Ridge'),
  ('United States', 'Mossland Memorial Golf Course'),
  ('United States', 'Mosswood Country Club'),
  ('United States', 'Mossy Creek Golf Club'),
  ('United States', 'Mossy Oak Golf Club'),
  ('United States', 'Motorcoach Country Club'),
  ('United States', 'Mound City Golf Club'),
  ('United States', 'Mound Golf Course'),
  ('United States', 'Mound Grove Golf Recreation'),
  ('United States', 'Mound View Golf Course'),
  ('United States', 'Mounds Ditches At Brickyard Plantation Golf Club'),
  ('United States', 'Moundsville Country Club'),
  ('United States', 'Mount Airy Country Club'),
  ('United States', 'Mount Airy Golf Club'),
  ('United States', 'Mount Ayr Golf and Country Club'),
  ('United States', 'Mount Carmel Municipal Golf Course'),
  ('United States', 'Mount Cashmere Golf Course'),
  ('United States', 'Mount Dora Golf Club'),
  ('United States', 'Mount Douglas Golf Course'),
  ('United States', 'Mount Fairweather Golf Course'),
  ('United States', 'Mount Frontenac Golf Course'),
  ('United States', 'Mount Hawley Country Club'),
  ('United States', 'Mount Hood Golf Course'),
  ('United States', 'Mount Huff Golf Course'),
  ('United States', 'Mount Kisco Country Club'),
  ('United States', 'Mount Lebanon Golf Course'),
  ('United States', 'Mount Massive Golf Course'),
  ('United States', 'Mount Mitchell Golf Club'),
  ('United States', 'Mount Odin Golf Course'),
  ('United States', 'Mount Ogden Golf Course'),
  ('United States', 'Mount Pleasant At Mount Washington Hotel Resort'),
  ('United States', 'Mount Pleasant Country Club'),
  ('United States', 'Mount Pleasant Golf & Country Club'),
  ('United States', 'Mount Pocono Public Golf Course'),
  ('United States', 'Mount Prospect Golf Course'),
  ('United States', 'Mount Saint Helena Golf Course'),
  ('United States', 'Mount Shasta Resort'),
  ('United States', 'Mount Si Golf Course'),
  ('United States', 'Mount Snow Golf Club'),
  ('United States', 'Mount Summit Golf Course'),
  ('United States', 'Mount Tabor Country Club'),
  ('United States', 'Mount Vernon Country Club'),
  ('United States', 'Mount Vintage Golf Club Chester Course'),
  ('United States', 'Mount Vintage Golf Club Independent Course'),
  ('United States', 'Mount Vintage Golf Club Vintage Course'),
  ('United States', 'Mount Washington At Mount Washington Hotel Resort'),
  ('United States', 'Mountain Air Country Club'),
  ('United States', 'Mountain Aire Golf Club'),
  ('United States', 'Mountain At Angel Park Golf Club'),
  ('United States', 'Mountain At Cordillera Golf Course'),
  ('United States', 'Mountain At Incline Village Golf Resort'),
  ('United States', 'Mountain At Wasatch Mountain State Park'),
  ('United States', 'Mountain Brook Golf Club'),
  ('United States', 'Mountain Falls Golf Course'),
  ('United States', 'Mountain Flowers'),
  ('United States', 'Mountain Forest At Stratton Mountain Country Club'),
  ('United States', 'Mountain Glen Golf Course'),
  ('United States', 'Mountain Harbour Golf Club'),
  ('United States', 'Mountain Lake'),
  ('United States', 'Mountain Lake At Pinery Country Club'),
  ('United States', 'Mountain Lake Golf Course'),
  ('United States', 'Mountain Laurel Golf Club'),
  ('United States', 'Mountain Meadows Golf Course'),
  ('United States', 'Mountain Ranch Golf Club At Fairfield Bay'),
  ('United States', 'Mountain Ridge'),
  ('United States', 'Mountain Ridge Country Club'),
  ('United States', 'Mountain Shadows Golf Course'),
  ('United States', 'Mountain Springs At Grandfather Golf Country Club'),
  ('United States', 'Mountain Top Course'),
  ('United States', 'Mountain Top Golf Course'),
  ('United States', 'Mountain Valley Golf Center'),
  ('United States', 'Mountain Valley Golf Course Mountain Course'),
  ('United States', 'Mountain Valley Golf Course Valley Course'),
  ('United States', 'Mountain View At Callaway Gardens Resort'),
  ('United States', 'Mountain View At Desert Willow Golf Resort'),
  ('United States', 'Mountain View Country Club'),
  ('United States', 'Mountain View Golf Club'),
  ('United States', 'Mountain View Golf Course'),
  ('United States', 'Mountain View Grand Golf Course'),
  ('United States', 'Mountain Vista Golf Club San Gorgonio Course'),
  ('United States', 'Mountain Vista Golf Club Santa Rosa Course'),
  ('United States', 'Mountain Vista Greens Golf Course'),
  ('United States', 'Mountaineer Golf Country Club'),
  ('United States', 'Mountaineer Woodview Golf Course'),
  ('United States', 'Mountaineers Woodview Golf Course'),
  ('United States', 'Mountaintop Golf Lake Club'),
  ('United States', 'Mountainview Country Club'),
  ('United States', 'Mountainview Par 3 Gramling Course'),
  ('United States', 'Mozingo Lake Recreation Watson 9 Course'),
  ('United States', 'Mr Golfs Ultimate Range'),
  ('United States', 'Mr. Golf'),
  ('United States', 'Mt Adams Country Club'),
  ('United States', 'Mt Anthony Golf Tennis Club'),
  ('United States', 'Mt Freedom Golf'),
  ('United States', 'Mt Graham Golf Course'),
  ('United States', 'Mt Hope Golf Course'),
  ('United States', 'Mt Kineo Golf Course'),
  ('United States', 'Mt Meadows Golf Course'),
  ('United States', 'Mt Pleasant Golf Club'),
  ('United States', 'Mt Whitney Golf Club'),
  ('United States', 'Mt Woodson Golf Club'),
  ('United States', 'Mud Run Golf Course'),
  ('United States', 'Mueller''s Valley View Farm Golf Course'),
  ('United States', 'Muirfield Village Golf Club'),
  ('United States', 'Mulberry Hills Golf Course'),
  ('United States', 'Muleshoe Country Club'),
  ('United States', 'Mulholland Hills Country Club Canyons'),
  ('United States', 'Mulholland Hills Country Club Trails'),
  ('United States', 'Mulholland Hills Country Club Vista'),
  ('United States', 'Mullenhurst Golf Course'),
  ('United States', 'Mullett Lake Country Club'),
  ('United States', 'Mulligan S Pointe'),
  ('United States', 'Mulligan''s Fairway'),
  ('United States', 'Mulligans Creekside Golf Center'),
  ('United States', 'Mulligans Island Par 3 Course'),
  ('United States', 'Muncie Elks Country Club'),
  ('United States', 'Munoscong Golf Club'),
  ('United States', 'Muroc Lake Golf Course'),
  ('United States', 'Murphy Creek Golf Course'),
  ('United States', 'Murphys Garrison Golf Center'),
  ('United States', 'Murray Parkway Golf Course'),
  ('United States', 'Murrysville Golf Club'),
  ('United States', 'Muscatine Municipal Golf Course'),
  ('United States', 'Musgrove Mill Golf Club'),
  ('United States', 'Muskeg Meadows Golf Course'),
  ('United States', 'Muskego Lakes Country Club'),
  ('United States', 'Muskegon Country Club'),
  ('United States', 'Muskogee Country Club'),
  ('United States', 'Muttontown Golf Country Club'),
  ('United States', 'Myerlee Country Club'),
  ('United States', 'Myers Park Country Club'),
  ('United States', 'Mylora Golf Course'),
  ('United States', 'Mylora On No 5 Road'),
  ('United States', 'Myopia Hunt Club'),
  ('United States', 'Myrick Hills Country Club'),
  ('United States', 'Myrtle Beach National Golf Club Kings North Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Myrtle Beach National Golf Club South Creek Course'),
  ('United States', 'Myrtle Beach National Golf Club West Course'),
  ('United States', 'Mystery Valley Golf Club'),
  ('United States', 'Mystic Creek Golf Club'),
  ('United States', 'Mystic Dunes Golf Club'),
  ('United States', 'Mystic Oak Golf Course'),
  ('United States', 'NCR Country Club'),
  ('United States', 'Nabnasset Lake Country Club'),
  ('United States', 'Naga-Waukee War Memorial Golf Course'),
  ('United States', 'Nags Head Golf Links'),
  ('United States', 'Nahma Golf Course'),
  ('United States', 'Nakoma Country Club'),
  ('United States', 'Nakoma Golf Resort Dragon Course'),
  ('United States', 'Nancy Lopez Golf Course At Spring River'),
  ('United States', 'Nanea Golf Club'),
  ('United States', 'Naniloa Golf Club'),
  ('United States', 'Nansemond River Golf Club'),
  ('United States', 'Nantucket Golf Club'),
  ('United States', 'Napa Golf Course At Kennedy Park'),
  ('United States', 'Napa Valley Country Club'),
  ('United States', 'Naperbrook Golf Course'),
  ('United States', 'Naperville Country Club'),
  ('United States', 'Naples Beach Hotel Golf Club'),
  ('United States', 'Naples Golf Country Club'),
  ('United States', 'Naples Grande Golf Club'),
  ('United States', 'Naples Heritage'),
  ('United States', 'Naples Lakes Country Club'),
  ('United States', 'Naples National Golf Club'),
  ('United States', 'Napoleon Municipal Golf Course'),
  ('United States', 'Nas Jacksonville Golf Club Blue Nine'),
  ('United States', 'Nas Jacksonville Golf Club Red Nine'),
  ('United States', 'Nas Jacksonville Golf Club White Nine'),
  ('United States', 'Nashawtuc Country Club'),
  ('United States', 'Nashua Country Club'),
  ('United States', 'Nashville Country Club'),
  ('United States', 'Nashville Golf Course'),
  ('United States', 'Nassau Country Club'),
  ('United States', 'Natanis Golf Course Arrowhead'),
  ('United States', 'Natanis Golf Course Tomahawk'),
  ('United States', 'Natchez Trace Golf Club'),
  ('United States', 'Natchitoches Country Club'),
  ('United States', 'National City Golf Course'),
  ('United States', 'National Golf Club'),
  ('United States', 'National Golf Club Of Kansas City'),
  ('United States', 'National Golf Links'),
  ('United States', 'National Golf Links Of America'),
  ('United States', 'Nationview Golf Course'),
  ('United States', 'Native Oaks Golf Club'),
  ('United States', 'Nature Walk Course At Chinquapin'),
  ('United States', 'Nature Walk Golf Club'),
  ('United States', 'Naval Air Station Barbers Point Golf Course'),
  ('United States', 'Naval Base San Diegos Golf Performance Center'),
  ('United States', 'Navesink Country Club'),
  ('United States', 'Navy Marine Golf Course'),
  ('United States', 'Needham Golf Club'),
  ('United States', 'Needles Eye Golf Club'),
  ('United States', 'Nehoiden Golf Club At Wellesley College'),
  ('United States', 'Neillsville Country Club'),
  ('United States', 'Nemacolin Country Club'),
  ('United States', 'Nemacolin Woodlands Resort Mystic Rock Course'),
  ('United States', 'Nemacolin Woodlands Resort Shepherds Rock Golf Course'),
  ('United States', 'Nemadji Golf Course'),
  ('United States', 'Neosho Municipal Golf Course Lakes Nine'),
  ('United States', 'Neosho Municipal Golf Course Oaks Nine'),
  ('United States', 'Neosho Municipal Golf Course Valley Nine'),
  ('United States', 'Neshaminy Valley Golf Club'),
  ('United States', 'Neshanic Valley Golf Course Academy Course'),
  ('United States', 'Neshanic Valley Golf Course Lake Ridge Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Lake Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Ridge Course'),
  ('United States', 'Neshobe Golf Club'),
  ('United States', 'Ness County Country Club'),
  ('United States', 'Nettle Creek Country Club'),
  ('United States', 'Neumann Golf Course'),
  ('United States', 'Nevada Country Club'),
  ('United States', 'Nevada County Country Club'),
  ('United States', 'Nevel Meade Golf Course'),
  ('United States', 'New Albany Country Club'),
  ('United States', 'New Albany Golf Course'),
  ('United States', 'New Albany Links Golf Club'),
  ('United States', 'New Berlin Hills Golf Course'),
  ('United States', 'New Bern Golf Country Club'),
  ('United States', 'New Ellenton Golf Course'),
  ('United States', 'New England Golf Club'),
  ('United States', 'New Haven Country Club'),
  ('United States', 'New Haven Golf Club'),
  ('United States', 'New Holland Pitch Putt'),
  ('United States', 'New Hope Village Golf Course'),
  ('United States', 'New Horizons Golf Course'),
  ('United States', 'New Jersey National Golf Club'),
  ('United States', 'New Kirk Country Club'),
  ('United States', 'New Meadows Golf Club'),
  ('United States', 'New Mexico Military Institute Golf Course'),
  ('United States', 'New Mexico State University Golf Course'),
  ('United States', 'New Mexico Tech Golf Course'),
  ('United States', 'New Orleans Country Club'),
  ('United States', 'New Paltz Golf Course'),
  ('United States', 'New Richmond Golf Club'),
  ('United States', 'New Richmond Links Course'),
  ('United States', 'New River Country Club'),
  ('United States', 'New Rockford Golf Club'),
  ('United States', 'New Salisbury Golf Course'),
  ('United States', 'New Smyrna Golf Club'),
  ('United States', 'New Ulm Country Club'),
  ('United States', 'New York Chiropractic College Executive Links Course'),
  ('United States', 'New York Country Club'),
  ('United States', 'New York Presbyterian Hospital Golf Course'),
  ('United States', 'Newark Country Club'),
  ('United States', 'Newark Valley Golf Club'),
  ('United States', 'Newberry Country Club'),
  ('United States', 'Newcastle Country Club'),
  ('United States', 'Newell Golf Course'),
  ('United States', 'Newfane Pro Am Par 3 Golf Course'),
  ('United States', 'Newfoundland Golf Course'),
  ('United States', 'Newlands Golf And Country Club'),
  ('United States', 'Newman Golf Course'),
  ('United States', 'Newman Municipal Golf Course'),
  ('United States', 'Newnan Country Club'),
  ('United States', 'Newport American Legion Country Club'),
  ('United States', 'Newport Beach Country Club'),
  ('United States', 'Newport Beach Golf Course'),
  ('United States', 'Newport Country Club'),
  ('United States', 'Newport Golf Club'),
  ('United States', 'Newport National Golf Club Orchard Course'),
  ('United States', 'Newton Commonwealth Golf Course'),
  ('United States', 'Newton Country Club'),
  ('United States', 'Newton Public Golf Course Driving Range'),
  ('United States', 'Newtown Country Club'),
  ('United States', 'Niagara County Golf Course'),
  ('United States', 'Niagara Falls Country Club'),
  ('United States', 'Niagara Frontier Country Club'),
  ('United States', 'Niagara National Golf Country Club'),
  ('United States', 'Niagara On The Lake Golf Club'),
  ('United States', 'Niagara Orleans Country Club'),
  ('United States', 'Nibley Park Golf Course'),
  ('United States', 'Nick Stoner Golf Course'),
  ('United States', 'Nickerson Dunes Pitch Putt'),
  ('United States', 'Nicklaus At Colleton River Club'),
  ('United States', 'Nicklaus Golf Club At Lionsgate'),
  ('United States', 'Nickol Knoll Golf Course'),
  ('United States', 'Nico Wynd Golf Club'),
  ('United States', 'Nicolet Country Club'),
  ('United States', 'Nile Shrine Golf Course'),
  ('United States', 'Nine At Eagle Crest Golf Course'),
  ('United States', 'Nine Hole At Balboa Park Municipal Golf Club'),
  ('United States', 'Nine Hole At Bangor Municipal Golf Course'),
  ('United States', 'Nine Hole At Bright Leaf Golf Resort'),
  ('United States', 'Nine Hole At On Top Of The World Golf Club'),
  ('United States', 'Nine Hole At Outdoor Resort Country Club'),
  ('United States', 'Nine Hole At Race Brook Country Club'),
  ('United States', 'Nine Hole At Santa Teresa Golf Club'),
  ('United States', 'Nine Hole At South Park Golf Course'),
  ('United States', 'Nine Hole At South Suburban Golf Course'),
  ('United States', 'Nine Hole At Village Links Of Glen Ellyn'),
  ('United States', 'Nine Hole Executive At Viewpoint Golf Resort'),
  ('United States', 'Nine Hole Par 3 At Smithtown Landing Golf Club'),
  ('United States', 'Nine Hole Regulation At Highland View Golf Club'),
  ('United States', 'Nine Springs Golf Course'),
  ('United States', 'Nippersink Resort'),
  ('United States', 'Nippo Lake Golf Club'),
  ('United States', 'Nishna Hills Golf Club'),
  ('United States', 'Nishna Valley Golf Course'),
  ('United States', 'Nissequogue Golf Course'),
  ('United States', 'Nittany Country Club'),
  ('United States', 'Nkmip Canyon Desert Golf Course'),
  ('United States', 'No 7 At Desert Mountain Golf Club'),
  ('United States', 'Nob North Golf Course'),
  ('United States', 'Nocona Hills Country Club'),
  ('United States', 'Nolichucky View Golf Club'),
  ('United States', 'Nonami Plantation Golf Course'),
  ('United States', 'Nonesuch River Golf Club'),
  ('United States', 'Nonquitt Golf Club'),
  ('United States', 'Norfolk Country Club'),
  ('United States', 'Norfolk Golf Club'),
  ('United States', 'Norman K. Probstein Golf Course'),
  ('United States', 'Normandie Golf Club'),
  ('United States', 'Normandy Shores Golf Course'),
  ('United States', 'Normanside Country Club'),
  ('United States', 'Norsk Golf Club'),
  ('United States', 'North Adams Country Club'),
  ('United States', 'North Andover Country Club'),
  ('United States', 'North At Admiral Baker Golf Course'),
  ('United States', 'North At Alondra Park Golf Course'),
  ('United States', 'North At Antelope Hills Golf Course'),
  ('United States', 'North At Bay Palms Golf Complex'),
  ('United States', 'North At Boulders Golf Club Resort'),
  ('United States', 'North At Bretwood Golf Course'),
  ('United States', 'North At Canoe Brook Country Club'),
  ('United States', 'North At Carmel Country Club'),
  ('United States', 'North At Cherokee Town Country Club'),
  ('United States', 'North At Cherokee Village'),
  ('United States', 'North At Coto De Caza Golf Racquet Club'),
  ('United States', 'North At Country Club Of Scranton The'),
  ('United States', 'North At Crestview Country Club'),
  ('United States', 'North At Daytona Beach Golf Country Club'),
  ('United States', 'North At Deerfield Country Club'),
  ('United States', 'North At Earlywine Golf Course'),
  ('United States', 'North At Fountains Country Club'),
  ('United States', 'North At Frenchmans Creek Beach Country Club'),
  ('United States', 'North At Heather Hill Country Club'),
  ('United States', 'North At Hunters Run Golf Course'),
  ('United States', 'North At Hyde Park Golf Course'),
  ('United States', 'North At Ironwood Country Club'),
  ('United States', 'North At Johns Island Club'),
  ('United States', 'North At Lake Hefner Golf Course'),
  ('United States', 'North At Lake Henry Golf Club'),
  ('United States', 'North At Los Angeles Country Club The'),
  ('United States', 'North At Los Serranos Golf Country Club'),
  ('United States', 'North At Moss Creek Golf Club'),
  ('United States', 'North At Quail Ridge Country Club'),
  ('United States', 'North At Raintree Country Club'),
  ('United States', 'North At Rancho Murieta Country Club'),
  ('United States', 'North At Randolph Golf Course'),
  ('United States', 'North At Torrey Pines Municipal Golf Course'),
  ('United States', 'North At Victor Hills Golf Club'),
  ('United States', 'North At Vineyards Of Naples The'),
  ('United States', 'North At Wilmington Country Club'),
  ('United States', 'North Bellingham Golf Course'),
  ('United States', 'North Bend Golf Course'),
  ('United States', 'North Branch Golf Course'),
  ('United States', 'North Carolina State University Club'),
  ('United States', 'North Conway Country Club'),
  ('United States', 'North Country Golf Club'),
  ('United States', 'North County Country Club'),
  ('United States', 'North Course'),
  ('United States', 'North Course At Highlands Ridge'),
  ('United States', 'North Course At Lake Of Isles'),
  ('United States', 'North Course At Shadow Wood Country Club'),
  ('United States', 'North Course At Terry Hills Golf Course'),
  ('United States', 'North Course At Whitefish Lake Golf Club'),
  ('United States', 'North Course Golf Course At Stonewall Links'),
  ('United States', 'North Creek Golf Club'),
  ('United States', 'North East At Athens Country Club'),
  ('United States', 'North East At Farmington Country Club'),
  ('United States', 'North East At Lakes Country Club The'),
  ('United States', 'North East At Oaks North Golf Course'),
  ('United States', 'North East At Ocean Breeze Golf Country Club'),
  ('United States', 'North East At Sahalee Country Club'),
  ('United States', 'North East At Silver Lakes Country Club'),
  ('United States', 'North Eighteen At Cross Creek Resort'),
  ('United States', 'North Fork Country Club'),
  ('United States', 'North Fork Golf Tennis Club'),
  ('United States', 'North Golf Course At Big Cypress Golf Country Club'),
  ('United States', 'North Golf Course At Granite Falls Golf Club'),
  ('United States', 'North Golf Course At Sun City'),
  ('United States', 'North Greens Golf Course'),
  ('United States', 'North Haven Golf Club'),
  ('United States', 'North Hempstead Country Club'),
  ('United States', 'North Hill Country Club'),
  ('United States', 'North Hills Country Club'),
  ('United States', 'North Hills Municipal Golf Course'),
  ('United States', 'North Jersey Country Club'),
  ('United States', 'North Kent Golf Course'),
  ('United States', 'North Kingstown Municipal Golf Club'),
  ('United States', 'North Kossuth Golf Club'),
  ('United States', 'North Las Vegas Golf Course'),
  ('United States', 'North Links Golf Course'),
  ('United States', 'North Oaks Golf Course'),
  ('United States', 'North Olmsted Golf Club'),
  ('United States', 'North Palm Beach Country Club'),
  ('United States', 'North Park Dr Range Par 3'),
  ('United States', 'North Park Golf Course'),
  ('United States', 'North Ridge Country Club'),
  ('United States', 'North Ridge Golf Club'),
  ('United States', 'North Shore Country Club'),
  ('United States', 'North Shore Golf Club'),
  ('United States', 'North Shore Golf Course'),
  ('United States', 'North South At Elmridge Golf Club'),
  ('United States', 'North South At Killearn Country Club Inn'),
  ('United States', 'North South At Krendale Golf Course'),
  ('United States', 'North South At Mountain Gate Country Club'),
  ('United States', 'North South At Rolling Acres Golf Course'),
  ('United States', 'North South At Silver Lakes Country Club'),
  ('United States', 'North South At South Hills Golf Club'),
  ('United States', 'North Star Golf Course'),
  ('United States', 'North Stone Club'),
  ('United States', 'North Topeka Golf Center'),
  ('United States', 'North West At Fernandina Beach Golf Club'),
  ('United States', 'North West At South Hills Golf Club'),
  ('United States', 'North Woodmere Golf Course'),
  ('United States', 'Northampton Country Club'),
  ('United States', 'Northampton Valley Country Club'),
  ('United States', 'Northbrook Country Club'),
  ('United States', 'Northdale Golf Club'),
  ('United States', 'Northeast Harbor Golf Club'),
  ('United States', 'Northern Bay Resort'),
  ('United States', 'Northern FonDuLac Archery Golf'),
  ('United States', 'Northern Hills Golf Course'),
  ('United States', 'Northern Links Golf Course'),
  ('United States', 'Northern Michigan University Golf Course'),
  ('United States', 'Northern Pines Golf Club'),
  ('United States', 'Northfield Country Club'),
  ('United States', 'Northfield Golf Club'),
  ('United States', 'Northfields'),
  ('United States', 'Northgreen Country Club'),
  ('United States', 'Northland Country Club'),
  ('United States', 'Northmoor Country Club'),
  ('United States', 'Northmoor Golf Course'),
  ('United States', 'Northport Creek'),
  ('United States', 'Northport Golf Club'),
  ('United States', 'Northport Golf Course'),
  ('United States', 'Northport Point Golf Club'),
  ('United States', 'Northridge Country Club'),
  ('United States', 'Northridge Hills'),
  ('United States', 'Northside Golf Club'),
  ('United States', 'Northstar California Golf Course'),
  ('United States', 'Northville Hills Golf Club'),
  ('United States', 'Northwest Angle Golf Course'),
  ('United States', 'Northwestern Hills Golf Course'),
  ('United States', 'Northwinds Golf Course'),
  ('United States', 'Northwood Country Club'),
  ('United States', 'Northwood Family Traditions'),
  ('United States', 'Northwood Golf Club'),
  ('United States', 'Northwood Golf Course'),
  ('United States', 'Northwood Hills Golf Course'),
  ('United States', 'Northwoods Golf Course'),
  ('United States', 'Norton Country Club'),
  ('United States', 'Norton Knolls Golf Course'),
  ('United States', 'Norvelt Golf Club Lukes Links Course'),
  ('United States', 'Norvelt Golf Club Norvelt Course'),
  ('United States', 'Norway Country Club'),
  ('United States', 'Norwich Golf Club'),
  ('United States', 'Norwood Acres'),
  ('United States', 'Norwood Country Club'),
  ('United States', 'Norwood Golf Club'),
  ('United States', 'Norwood Hills Country Club'),
  ('United States', 'Norwoods Golf Club'),
  ('United States', 'Nottoway River Country Club'),
  ('United States', 'Nowata Country Club'),
  ('United States', 'Noyac Golf Club'),
  ('United States', 'Noyes Park Golf Course'),
  ('United States', 'NuMark Golf Course'),
  ('United States', 'Nutters Chapel Golf Country Club'),
  ('United States', 'Nutters Crossing Golf Course'),
  ('United States', 'Oahu Country Club'),
  ('United States', 'Oak At Beau Chene Golf Racquet Club'),
  ('United States', 'Oak Bluff At Del Rio Country Club'),
  ('United States', 'Oak Brook Golf'),
  ('United States', 'Oak Brook Golf Club'),
  ('United States', 'Oak Brook Golf Course'),
  ('United States', 'Oak Country Club'),
  ('United States', 'Oak Creek Golf Club'),
  ('United States', 'Oak Creek Golf Course'),
  ('United States', 'Oak Crest Golf Course'),
  ('United States', 'Oak Glen Golf Course'),
  ('United States', 'Oak Grove Golf Club'),
  ('United States', 'Oak Grove Golf Course'),
  ('United States', 'Oak Hall Par 3'),
  ('United States', 'Oak Harbor Country Club'),
  ('United States', 'Oak Harbor Golf Club'),
  ('United States', 'Oak Harbor Golf Course'),
  ('United States', 'Oak Hill Country Club'),
  ('United States', 'Oak Hill Golf Club'),
  ('United States', 'Oak Hill Golf Course'),
  ('United States', 'Oak Hills Country Club'),
  ('United States', 'Oak Hills Golf Club'),
  ('United States', 'Oak Hills Golf Country Club'),
  ('United States', 'Oak Hills Golf Course'),
  ('United States', 'Oak Hills Golf Event Center'),
  ('United States', 'Oak Hills Park Golf Course'),
  ('United States', 'Oak Hollow Golf Course'),
  ('United States', 'Oak Island Golf Club'),
  ('United States', 'Oak Knoll Country Club'),
  ('United States', 'Oak Knoll Golf Course'),
  ('United States', 'Oak Knolls Golf Course'),
  ('United States', 'Oak Lake Golf Course'),
  ('United States', 'Oak Lane Golf Club'),
  ('United States', 'Oak Lawn Country Club'),
  ('United States', 'Oak Leaf Golf Course'),
  ('United States', 'Oak Maple At Hunters Creek Plantation'),
  ('United States', 'Oak Marsh Golf Course'),
  ('United States', 'Oak Meadow Country Club'),
  ('United States', 'Oak Mountain Championship Golf Course'),
  ('United States', 'Oak Park Country Club'),
  ('United States', 'Oak Park Golf & Recreation'),
  ('United States', 'Oak Point At Kiawah Island Golf Resort'),
  ('United States', 'Oak Pointe Country Club'),
  ('United States', 'Oak Quarry Golf Club'),
  ('United States', 'Oak Ridge Golf Club'),
  ('United States', 'Oak Ridge Golf Course'),
  ('United States', 'Oak Run Golf Club'),
  ('United States', 'Oak Shadows Golf Club'),
  ('United States', 'Oak Springs Golf Club'),
  ('United States', 'Oak Stonehouse At Temecula Creek Inn Golf Resort'),
  ('United States', 'Oak Summit Golf Course'),
  ('United States', 'Oak Tree Country Club'),
  ('United States', 'Oak Tree Golf Club'),
  ('United States', 'Oak Tree National Golf Club'),
  ('United States', 'Oak Tree Spruce At Middle Island Country Club'),
  ('United States', 'Oak Valley Golf Club'),
  ('United States', 'Oakbourne Country Club'),
  ('United States', 'Oakbrook Golf Club'),
  ('United States', 'Oakbrook Golf Course'),
  ('United States', 'Oakcreek Country Club'),
  ('United States', 'Oakdale Country Club'),
  ('United States', 'Oakdale Golf Country Club'),
  ('United States', 'Oakdale Golf Course'),
  ('United States', 'Oakgreen Golf Course & Driving Range'),
  ('United States', 'Oakhaven Golf Club'),
  ('United States', 'Oakhurst Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Oakhurst Golf & Country Club'),
  ('United States', 'Oakland Acres Golf Club'),
  ('United States', 'Oakland Beach Golf Club'),
  ('United States', 'Oakland Country Club'),
  ('United States', 'Oakland Golf Club'),
  ('United States', 'Oakland Hills Country Club'),
  ('United States', 'Oakland Plantation Country Club'),
  ('United States', 'Oakland Plantation Golf Course At Lsu'),
  ('United States', 'Oakland University Golf and Learning Center'),
  ('United States', 'Oakleaf Golf and Country Club'),
  ('United States', 'Oakleigh At The Villages Executive Golf Trail'),
  ('United States', 'Oakley Country Club'),
  ('United States', 'Oakmont Country Club'),
  ('United States', 'Oakmont East Golf Course'),
  ('United States', 'Oakmont Golf Center'),
  ('United States', 'Oakmont Green Golf Club'),
  ('United States', 'Oakmoore Golf Course'),
  ('United States', 'Oakridge Country Club'),
  ('United States', 'Oakridge Golf Course'),
  ('United States', 'Oaks At Ft Walton Beach Golf Club'),
  ('United States', 'Oaks At North Ridge Country Club'),
  ('United States', 'Oaks At Palm Aire Country Club'),
  ('United States', 'Oaks Canyon At Blacklake Golf Course'),
  ('United States', 'Oaks Country Club'),
  ('United States', 'Oaks Course At Stonegate Golf Club'),
  ('United States', 'Oaks Golf Club The'),
  ('United States', 'Oaks Golf Country Club'),
  ('United States', 'Oaks Golf Course'),
  ('United States', 'Oaks Lakes At North Ranch Country Club'),
  ('United States', 'Oaks Lakes At Valley Oaks Golf Club'),
  ('United States', 'Oaks National Golf Club'),
  ('United States', 'Oaks Palms At Hacienda Hills Golf Country Club'),
  ('United States', 'Oaksridge Golf Course'),
  ('United States', 'Oakton Driving Range'),
  ('United States', 'Oaktree Golf Club'),
  ('United States', 'Oaktree Golf Course'),
  ('United States', 'Oakview Golf Country Club'),
  ('United States', 'Oakview Lakes Golf Course'),
  ('United States', 'Oakview Links'),
  ('United States', 'Oakwing Golf Club'),
  ('United States', 'Oakwood Country Club'),
  ('United States', 'Oakwood Country Club Par 3 Course'),
  ('United States', 'Oakwood Golf Club'),
  ('United States', 'Oakwood Golf Course'),
  ('United States', 'Oakwood Park Golf Course'),
  ('United States', 'Oakwood Supper Club & Golf Course'),
  ('United States', 'Oakwoods Country Club'),
  ('United States', 'Oasis Country Club'),
  ('United States', 'Oasis Golf Club'),
  ('United States', 'Oasis Rv Park Golf Course'),
  ('United States', 'Oberlin Country Club'),
  ('United States', 'Oberlin Golf Club'),
  ('United States', 'Ocala Golf Club'),
  ('United States', 'Ocala National Golf Club'),
  ('United States', 'Ocala Palms Golf Club'),
  ('United States', 'Occano'),
  ('United States', 'Occoneechee Golf Club'),
  ('United States', 'Ocean Acres Country Club'),
  ('United States', 'Ocean At Ponte Vedra Inn Club'),
  ('United States', 'Ocean City Golf Club Newport Bay'),
  ('United States', 'Ocean City Golf Club Seaside'),
  ('United States', 'Ocean City Golf Course'),
  ('United States', 'Ocean Club At The Hutchinson Island Beach Resort And Marina'),
  ('United States', 'Ocean County Golf Course At Atlantis'),
  ('United States', 'Ocean County Golf Course At Forge Pond'),
  ('United States', 'Ocean Creek At Fripp Island Resort'),
  ('United States', 'Ocean Edge Resort Club On Cape Cod'),
  ('United States', 'Ocean Forest Golf Club'),
  ('United States', 'Ocean Hills Country Club'),
  ('United States', 'Ocean Palm Golf Course'),
  ('United States', 'Ocean Pines Golf Club'),
  ('United States', 'Ocean Point At Fripp Island Resort'),
  ('United States', 'Ocean Resorts Golf Club'),
  ('United States', 'Ocean Shores Golf Course'),
  ('United States', 'Ocean View Municipal Golf Course'),
  ('United States', 'Ocean Village Golf Course'),
  ('United States', 'Ocean Winds At Seabrook Island Resort'),
  ('United States', 'Oceana Golf Club'),
  ('United States', 'Oceans Golf Club'),
  ('United States', 'Oceanside Golf Country Club'),
  ('United States', 'Oceanside Golf Course'),
  ('United States', 'Ocilla Country Club'),
  ('United States', 'Oconee Country Club'),
  ('United States', 'Oconomowoc Golf Club'),
  ('United States', 'Ocotillo Golf Club Blue White'),
  ('United States', 'Ocotillo Golf Club Gold Blue'),
  ('United States', 'Ocotillo Golf Club White Gold'),
  ('United States', 'Odana Hills Golf Course'),
  ('United States', 'Odessa Golf Club Rv Park'),
  ('United States', 'Odessa National Golf Club'),
  ('United States', 'Odonnell Golf Club'),
  ('United States', 'Odyssey Country Club'),
  ('United States', 'Ogden Golf Country Club'),
  ('United States', 'Ogeechee Valley Country Club'),
  ('United States', 'Oglebay Resort Crispin Course'),
  ('United States', 'Oglebay Resort Crispin Golf Course'),
  ('United States', 'Oglebay Resort Par 3 Course'),
  ('United States', 'Oglebay Resort Speidel Golf Club Par 3 Course'),
  ('United States', 'Ohio Prestwick Country Club'),
  ('United States', 'Ohio State University Golf Course'),
  ('United States', 'Ohio University Driving Range'),
  ('United States', 'Ohio University Golf Course'),
  ('United States', 'Ohoopee Match Club'),
  ('United States', 'Oil Field Recreation Association Golf Course'),
  ('United States', 'Ojai Valley Inn'),
  ('United States', 'Ojibwa Golf & Bowl'),
  ('United States', 'Ojibwa Golf Bowl'),
  ('United States', 'Okanogan Valley Golf Club'),
  ('United States', 'Okatie Creek Golf Club'),
  ('United States', 'Okatoma Golf Club'),
  ('United States', 'Okeechobee At The Villages Executive Golf Trail'),
  ('United States', 'Okeene Golf Club'),
  ('United States', 'Okefenokee Country Club'),
  ('United States', 'Okemah Golf Course'),
  ('United States', 'Oklahoma City Golf Country Club'),
  ('United States', 'Okmulgee Country Club'),
  ('United States', 'Okoboji View Golf Course'),
  ('United States', 'Okolona Country Club'),
  ('United States', 'Old At Canongate On White Oak'),
  ('United States', 'Old At Country Club Of Scranton The'),
  ('United States', 'Old At Saucon Valley Country Club'),
  ('United States', 'Old At Saxon Golf Course'),
  ('United States', 'Old Avalon Golf Course'),
  ('United States', 'Old Baldy Club'),
  ('United States', 'Old Baldy Golf Course'),
  ('United States', 'Old Barnwell Old Barnwell Golf Course'),
  ('United States', 'Old Bridge Golf Club'),
  ('United States', 'Old Brockway Golf Course'),
  ('United States', 'Old Capital Golf Club'),
  ('United States', 'Old Channel Trail'),
  ('United States', 'Old Chatham Golf Club'),
  ('United States', 'Old Club Par 3 Course'),
  ('United States', 'Old Corkscrew Golf Club'),
  ('United States', 'Old Course Golf Course At Stonewall Links'),
  ('United States', 'Old Course Sauk Centre'),
  ('United States', 'Old Dane Golf Club'),
  ('United States', 'Old Edwards Club'),
  ('United States', 'Old Elm Club'),
  ('United States', 'Old Erie Golf Club'),
  ('United States', 'Old Field Short Course'),
  ('United States', 'Old Greenwood Golf Course'),
  ('United States', 'Old Hickory At Fort Jackson Golf Club'),
  ('United States', 'Old Hickory Golf Club'),
  ('United States', 'Old Landing Golf Course'),
  ('United States', 'Old Lyme Country Club'),
  ('United States', 'Old Marsh Country Club'),
  ('United States', 'Old Marsh Golf Club'),
  ('United States', 'Old Memorial Golf Club'),
  ('United States', 'Old Mill Golf Club'),
  ('United States', 'Old Mill Graveyard At Flat Creek Golf Club'),
  ('United States', 'Old North State Club At Uwharrie Point'),
  ('United States', 'Old Oak Country Club'),
  ('United States', 'Old Oakland Golf Club'),
  ('United States', 'Old Oaks Golf Course'),
  ('United States', 'Old Orange At Verandah'),
  ('United States', 'Old Orchard Country Club'),
  ('United States', 'Old Orchard GC'),
  ('United States', 'Old Palm Golf Club'),
  ('United States', 'Old Ranch Country Club'),
  ('United States', 'Old River Golf Course'),
  ('United States', 'Old Sandwich Golf Club'),
  ('United States', 'Old South Golf Links'),
  ('United States', 'Old Tabby Links'),
  ('United States', 'Old Tappan Golf Course'),
  ('United States', 'Old Toccoa Farm'),
  ('United States', 'Old Top Farm'),
  ('United States', 'Old Town Club'),
  ('United States', 'Old Town Golf Course'),
  ('United States', 'Old Trail Golf Club'),
  ('United States', 'Old Union Golf Course'),
  ('United States', 'Old Warson Country Club'),
  ('United States', 'Old Waverly Golf Club'),
  ('United States', 'Old Wayne Golf Course'),
  ('United States', 'Old Works'),
  ('United States', 'Old Works Little Bear'),
  ('United States', 'Old York Country Club'),
  ('United States', 'Old York Road Country Club'),
  ('United States', 'Olde Atlanta Golf Club'),
  ('United States', 'Olde Barnstable Fairgrounds Golf Club'),
  ('United States', 'Olde Beau Resort Golf Club'),
  ('United States', 'Olde Beaufort Golf Club'),
  ('United States', 'Olde Course At Loveland'),
  ('United States', 'Olde Dutch Mill Golf Course'),
  ('United States', 'Olde Eight'),
  ('United States', 'Olde English Trail Golf Club'),
  ('United States', 'Olde Florida Golf Club'),
  ('United States', 'Olde Fort Golf Course'),
  ('United States', 'Olde Hickory Golf Country Club'),
  ('United States', 'Olde Homeplace Golf Club'),
  ('United States', 'Olde Homestead Golf Club'),
  ('United States', 'Olde Kinderhook Golf Course'),
  ('United States', 'Olde Liberty Golf Country Club'),
  ('United States', 'Olde Mill Golf Club'),
  ('United States', 'Olde Mill Resort'),
  ('United States', 'Olde Oak Golf Club'),
  ('United States', 'Olde Oaks Golf Club Cypress Meadow'),
  ('United States', 'Olde Oaks Golf Club Cypress Oak'),
  ('United States', 'Olde Oaks Golf Club Meadow Oak'),
  ('United States', 'Olde Page At Page Belcher Golf Course'),
  ('United States', 'Olde Point Golf Country Club'),
  ('United States', 'Olde Salem Greens Golf Course'),
  ('United States', 'Olde Scotland Links At Bridgewater'),
  ('United States', 'Olde Stonewall Golf Club'),
  ('United States', 'Olde Sycamore Golf Club'),
  ('United States', 'Oldfield Club'),
  ('United States', 'Oldham County Country Club'),
  ('United States', 'Ole Miss Golf Course'),
  ('United States', 'Ole Monterey Golf Club'),
  ('United States', 'Olivas Links Golf Course'),
  ('United States', 'Olive Branch Country Club'),
  ('United States', 'Olive Glenn Golf Country Club'),
  ('United States', 'Olivet Country Club'),
  ('United States', 'Olomana Golf Links'),
  ('United States', 'Olympia Country Golf Club'),
  ('United States', 'Olympia Fields Country Club'),
  ('United States', 'Olympic Hills Golf Club'),
  ('United States', 'Olympic View Golf Club'),
  ('United States', 'Omaha Country Club'),
  ('United States', 'Omni Amelia Island Resort Spa Little Sandy Short Course'),
  ('United States', 'Omni Amelia Island Resort Spa Oak Marsh'),
  ('United States', 'Omni Bedford Springs Resort Old Course'),
  ('United States', 'Omni La Costa Resort Spa North Course'),
  ('United States', 'Omni La Costa Resort Spa South Course'),
  ('United States', 'Omni Rancho Las Palmas Resort North South'),
  ('United States', 'Omni Rancho Las Palmas Resort South West'),
  ('United States', 'Omni Rancho Las Palmas Resort West North'),
  ('United States', 'One East Course At Apple Greens Golf Course'),
  ('United States', 'One Two Course At Apple Greens Golf Course'),
  ('United States', 'Oneida Community Golf Club'),
  ('United States', 'Oneida Golf & Country Club'),
  ('United States', 'Oneka Ridge Golf Course'),
  ('United States', 'Oneonta Country Club'),
  ('United States', 'Onondaga Golf Country Club'),
  ('United States', 'Ontario Country Club'),
  ('United States', 'Onteora Club'),
  ('United States', 'Ontonagon Golf Club'),
  ('United States', 'Onwentsia Club'),
  ('United States', 'Ooltewah Club'),
  ('United States', 'Oquirrh Hills Golf Course'),
  ('United States', 'Orange At Ford Hill Country Club'),
  ('United States', 'Orange At Palmetto Pines Golf Course'),
  ('United States', 'Orange Beach Golf Center'),
  ('United States', 'Orange Blossom Hills Golf Country Club'),
  ('United States', 'Orange Hills Country Club'),
  ('United States', 'Orange Tree Golf Club'),
  ('United States', 'Orange Tree Golf Conference Resort'),
  ('United States', 'Orcas Island Country Golf Club'),
  ('United States', 'Orchard Creek'),
  ('United States', 'Orchard Creek Public Golf Club'),
  ('United States', 'Orchard Golf Country Club'),
  ('United States', 'Orchard Grove At Treesdale Golf Country Club'),
  ('United States', 'Orchard Hill Country Club'),
  ('United States', 'Orchard Hills Golf Club'),
  ('United States', 'Orchard Hills Golf Course'),
  ('United States', 'Orchard Lake Country Club'),
  ('United States', 'Orchard Park Country Club'),
  ('United States', 'Orchard Ponds Golf Club'),
  ('United States', 'Orchard Ridge Country Club'),
  ('United States', 'Orchard Trace Golf Club'),
  ('United States', 'Orchard Vali Golf Club'),
  ('United States', 'Orchard Valley Golf Course'),
  ('United States', 'Orchard Vally Golf Course'),
  ('United States', 'Orchards Executive Golf Course'),
  ('United States', 'Orchards Golf Club'),
  ('United States', 'Orchards at Egg Harbor'),
  ('United States', 'Orchid Island Golf Beach Club'),
  ('United States', 'Oregon Country Club'),
  ('United States', 'Oregon Trail Country Club'),
  ('United States', 'Orgill Golf Course'),
  ('United States', 'Origins Golf Club'),
  ('United States', 'Orinda Country Club'),
  ('United States', 'Oriole Golf Club'),
  ('United States', 'Oriskany Hill Golf Club'),
  ('United States', 'Orleans Country Club'),
  ('United States', 'Oro Valley Country Club'),
  ('United States', 'Orofino Golf Course'),
  ('United States', 'Orono Public Golf Course'),
  ('United States', 'Oroville Golf Club'),
  ('United States', 'Osage City Country Club'),
  ('United States', 'Osawatomie Golf Course'),
  ('United States', 'Osborne Country Club'),
  ('United States', 'Osceola Golf Course'),
  ('United States', 'Osceola Municipal Golf Course'),
  ('United States', 'Osgood Golf Course'),
  ('United States', 'Oshkosh Country Club'),
  ('United States', 'Oshux Golf'),
  ('United States', 'Osiris Country Club'),
  ('United States', 'Oskaloosa Golf'),
  ('United States', 'Oso Creek Golf Course'),
  ('United States', 'Osoyoos Golf And Country Club Desert Gold'),
  ('United States', 'Osoyoos Golf And Country Club Park Meadows'),
  ('United States', 'Osprey Heron At Okeeheelee Golf Course'),
  ('United States', 'Osprey Point At Kiawah Island Golf Resort'),
  ('United States', 'Osprey Point Golf Club Falcon Raven Course'),
  ('United States', 'Osprey Point Golf Club Hawk Falcon Course'),
  ('United States', 'Osprey Point Golf Club Hawk Raven Course'),
  ('United States', 'Osseo Golf Club'),
  ('United States', 'Oswego Country Club The'),
  ('United States', 'Oswego Golf Association'),
  ('United States', 'Othello Golf Club'),
  ('United States', 'Otsego Golf Club'),
  ('United States', 'Ottawa Golf Course'),
  ('United States', 'Ottawa Park Golf Course'),
  ('United States', 'Otte Golf & Family Fun Center'),
  ('United States', 'Otter Creek Golf Course'),
  ('United States', 'Otter Valley Country Club'),
  ('United States', 'Otterkill Golf Country Club'),
  ('United States', 'Ottumwa Country Club'),
  ('United States', 'Ouachita Country Club'),
  ('United States', 'Ould Newbury Golf Club'),
  ('United States', 'Ouleout Creek Golf Course'),
  ('United States', 'Outdoor Country Club'),
  ('United States', 'Outdoor Resort Indio'),
  ('United States', 'Outlaw At Paradise Pointe Golf Complex'),
  ('United States', 'Outlaw Course At Desert Mountain Golf Club'),
  ('United States', 'Outlaw Golf Club At Hideout Canyon Challenge Course'),
  ('United States', 'Over Lake Golf Course'),
  ('United States', 'Over Look Woods At Old Westbury Golf Country Club'),
  ('United States', 'Overbrook Golf Club'),
  ('United States', 'Overlake Golf Country Club'),
  ('United States', 'Overland Golf Course'),
  ('United States', 'Overland Park Golf Course'),
  ('United States', 'Overlook Golf Course'),
  ('United States', 'Overlook The'),
  ('United States', 'Overpeck Golf Course'),
  ('United States', 'Owasco Country Club'),
  ('United States', 'Owasso Golf Athletic Club'),
  ('United States', 'Owatonna Country Club'),
  ('United States', 'Owens Brockway Golf Course'),
  ('United States', 'Owensboro Country Club'),
  ('United States', 'Owl Creek Country Club'),
  ('United States', 'Owls Head Golf Club'),
  ('United States', 'Owls Nest Golf Club'),
  ('United States', 'Owosso Country Club'),
  ('United States', 'Oxbow Country Club'),
  ('United States', 'Oxbow Creek Golf Course'),
  ('United States', 'Oxbow Golf Course'),
  ('United States', 'Oxford Hills Country Club'),
  ('United States', 'Oxford Valley Golf Course'),
  ('United States', 'Oxmoor Country Club'),
  ('United States', 'Oyster Bay Golf Links'),
  ('United States', 'Oyster Bay Town Golf Course Clubhouse'),
  ('United States', 'Oyster Creek Golf Country Club'),
  ('United States', 'Oyster Harbors Club'),
  ('United States', 'Oyster Reef Golf Course'),
  ('United States', 'Ozark Recreation Association Club'),
  ('United States', 'Ozark Ridge Golf Course'),
  ('United States', 'Ozarks National'),
  ('United States', 'Ozaukee Country Club'),
  ('United States', 'O’Bannon Creek Golf Club'),
  ('United States', 'Paa Ko Ridge Golf Club Course 1'),
  ('United States', 'Paa Ko Ridge Golf Club Course 2'),
  ('United States', 'Paa Ko Ridge Golf Club Course 3'),
  ('United States', 'Pablo Creek Club'),
  ('United States', 'Pacific Grove Golf Links'),
  ('United States', 'Pacific Springs Golf Course'),
  ('United States', 'Packanack Golf Club'),
  ('United States', 'Packsaddle Ridge Golf Course'),
  ('United States', 'Paganica Golf Course'),
  ('United States', 'Paint Creek Country Club'),
  ('United States', 'Painted Desert Golf Club'),
  ('United States', 'Painted Dunes Desert Golf Club East West Course'),
  ('United States', 'Painted Dunes Desert Golf Course East North Course'),
  ('United States', 'Painted Dunes Desert Golf Course North West Course'),
  ('United States', 'Painted Hills Golf Club'),
  ('United States', 'Painted Mountain Golf Club'),
  ('United States', 'Pajaro Valley Golf Club'),
  ('United States', 'Pakachoag Golf Course'),
  ('United States', 'Pala Mesa Resort'),
  ('United States', 'Palacio Del Mar Golf Course'),
  ('United States', 'Palatine Hills Golf Course'),
  ('United States', 'Palatka Golf Club'),
  ('United States', 'Pali Municipal Golf Course'),
  ('United States', 'Palisade State Park Golf Course'),
  ('United States', 'Palisades Golf Course'),
  ('United States', 'Pallo''s Par 3 Golf Course'),
  ('United States', 'Palm At Angel Park Golf Club'),
  ('United States', 'Palm At Mccormick Ranch Golf Club'),
  ('United States', 'Palm Beach Country Club'),
  ('United States', 'Palm Beach Golf Course'),
  ('United States', 'Palm Beach National Golf Course'),
  ('United States', 'Palm Cove Golf And Yacht Club'),
  ('United States', 'Palm Creek Golf Club'),
  ('United States', 'Palm Desert Country Club'),
  ('United States', 'Palm Desert Greens Country Club'),
  ('United States', 'Palm Desert Resort Country Club'),
  ('United States', 'Palm Harbor Golf Club'),
  ('United States', 'Palm Hill Country Club'),
  ('United States', 'Palm Royale Country Club'),
  ('United States', 'Palm Valley Golf Club'),
  ('United States', 'Palm Valley Golf Club North South'),
  ('United States', 'Palm Valley Golf Club North West'),
  ('United States', 'Palm Valley Golf Club South West'),
  ('United States', 'Palma Ceia Golf Country Club'),
  ('United States', 'Palmbrook Golf Club'),
  ('United States', 'Palmer At Oasis Golf Club'),
  ('United States', 'Palmer Course At Wildfire Golf Club At Desert Ridge'),
  ('United States', 'Palmer Golf Course'),
  ('United States', 'Palmer Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Palmer Hills Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Palmetto At Glades Country Club'),
  ('United States', 'Palmetto At Myrtlewood Golf Club'),
  ('United States', 'Palmetto At The Villages Executive Golf Trail'),
  ('United States', 'Palmetto Golf Club'),
  ('United States', 'Palmetto Golf Course'),
  ('United States', 'Palmetto Hills Golf Club'),
  ('United States', 'Palmetto Magnolia At Callawassie Island Club'),
  ('United States', 'Palmetto Pine Country Club'),
  ('United States', 'Palmira Golf Club'),
  ('United States', 'Palmira Golf Club Egret Ibis'),
  ('United States', 'Palmira Golf Club Ibis Osprey'),
  ('United States', 'Palmira Golf Club Osprey Egret'),
  ('United States', 'Palms At Marriotts Desert Springs Resort'),
  ('United States', 'Palms At Palm Aire Country Club'),
  ('United States', 'Palms At Pompano Beach Golf Course'),
  ('United States', 'Palms At Rotonda Golf Country Club'),
  ('United States', 'Palms Golf Club'),
  ('United States', 'Palms Golf Course At Oakwood Country Club'),
  ('United States', 'Palms Lakes At Hacienda Hills Golf Country Club'),
  ('United States', 'Palmyra Golf Course'),
  ('United States', 'Palo Alto Hills Golf Country Club'),
  ('United States', 'Palo Verde Golf Course'),
  ('United States', 'Palos Country Club'),
  ('United States', 'Palos Hills Golf Club'),
  ('United States', 'Palos Verdes Golf Club'),
  ('United States', 'Palos Verdes Shores Golf Club'),
  ('United States', 'Palouse Ridge Golf Club At Washington State University'),
  ('United States', 'Pan-Yak Golf Course'),
  ('United States', 'Pana Country Club'),
  ('United States', 'Panama Country Club'),
  ('United States', 'Panhandle State University Golf Course'),
  ('United States', 'Panola Country Club'),
  ('United States', 'Panola Mountain Golf Club 10 Hole Course'),
  ('United States', 'Panola Mountain Golf Club 18 Hole Course'),
  ('United States', 'Panola Woods Country Club'),
  ('United States', 'Panorama At Balsams Grand Resort Hotel The'),
  ('United States', 'Panorama Golf Course'),
  ('United States', 'Panorama Village Golf Course'),
  ('United States', 'Panorama West Golf Course'),
  ('United States', 'Panther Creek Country Club'),
  ('United States', 'Panther Lake At Orange County National'),
  ('United States', 'Panther National Championship Course'),
  ('United States', 'Panther National Short Course Panther9'),
  ('United States', 'Panther Run Golf Club'),
  ('United States', 'Panther Valley Golf Country Club'),
  ('United States', 'Panthers Run At Ocean Ridge Plantation'),
  ('United States', 'Paola Country Club'),
  ('United States', 'Pap Pap Par 3 Golf Course'),
  ('United States', 'Papago Golf Club'),
  ('United States', 'Par 3 At Battle Creek Public Golf'),
  ('United States', 'Par 3 At Ben Hawes State Park'),
  ('United States', 'Par 3 At Borland Golf Center'),
  ('United States', 'Par 3 At Bright Leaf Golf Resort'),
  ('United States', 'Par 3 At Cherokee Ridge Golf Course'),
  ('United States', 'Par 3 At Clovis Municipal Golf Course'),
  ('United States', 'Par 3 At Colleton River Club'),
  ('United States', 'Par 3 At Cyprian Keyes Golf Club'),
  ('United States', 'Par 3 At Fore Lakes Golf Course'),
  ('United States', 'Par 3 At Fox Ridge Golf Course'),
  ('United States', 'Par 3 At Hollybrook Golf Tennis Club'),
  ('United States', 'Par 3 At Indian Tree Golf Club'),
  ('United States', 'Par 3 At Jefferson Park Golf Club'),
  ('United States', 'Par 3 At Lafortune Park Golf Course'),
  ('United States', 'Par 3 At Marine Memorial Golf Course'),
  ('United States', 'Par 3 At Mill Creek Golf Club'),
  ('United States', 'Par 3 At Olde Homestead Golf Club'),
  ('United States', 'Par 3 At Tri Palm Country Club'),
  ('United States', 'Par 3 At Vista Valencia Golf Course'),
  ('United States', 'Par 3 At Westchester Golf Country Club'),
  ('United States', 'Par 3 At Windyke Country Club'),
  ('United States', 'Par 3 Championship At Scallys Golf Center'),
  ('United States', 'Par 3 Course'),
  ('United States', 'Par 3 Course At Crosswinds Golf Club'),
  ('United States', 'Par 3 Course At Eagle Point Golf Club'),
  ('United States', 'Par 3 Golf At Sandy Bottom Park'),
  ('United States', 'Par 3 Golf Course At Westchester Country Club'),
  ('United States', 'Par 3 Practice At Tradition Golf Club'),
  ('United States', 'Par 3 West'),
  ('United States', 'Par Three At Highland View Golf Club'),
  ('United States', 'Par Three At Jackson Park Golf Course'),
  ('United States', 'Par Three At Quaker Meadows Golf Club'),
  ('United States', 'Par Three At Windy Hill Golf Course'),
  ('United States', 'Paradise Golf Course'),
  ('United States', 'Paradise Golf Resort'),
  ('United States', 'Paradise Hills Golf Course'),
  ('United States', 'Paradise Peak West'),
  ('United States', 'Paradise Valley'),
  ('United States', 'Paradise Valley Country Club'),
  ('United States', 'Paradise Valley Golf & Country Club'),
  ('United States', 'Paradise Valley Golf Club'),
  ('United States', 'Paradise Valley Golf Course'),
  ('United States', 'Paradise Valley Par 3'),
  ('United States', 'Paragould Country Club'),
  ('United States', 'Paramount Country Club'),
  ('United States', 'Paramus Golf Course'),
  ('United States', 'Paris Golf Country Club'),
  ('United States', 'Paris Hill Country Club'),
  ('United States', 'Paris Mountain Country Club'),
  ('United States', 'Park City Golf Club'),
  ('United States', 'Park Falls Country Club'),
  ('United States', 'Park Hill Golf Club'),
  ('United States', 'Park Hills Country Club'),
  ('United States', 'Park Hills Golf Course'),
  ('United States', 'Park Hills Golf Supper Club'),
  ('United States', 'Park Meadows Golf Club'),
  ('United States', 'Park Ridge Country Club'),
  ('United States', 'Park Ridge Golf Course'),
  ('United States', 'Park Shore Golf Course'),
  ('United States', 'Parke County Golf Course'),
  ('United States', 'Parkland Golf Club'),
  ('United States', 'Parkston Country Club'),
  ('United States', 'Parkview Fairways Golf Course'),
  ('United States', 'Parkview Golf Course'),
  ('United States', 'Parkway Golf Course'),
  ('United States', 'Parsons Katy Golf Club'),
  ('United States', 'Parto''s Big On Golf'),
  ('United States', 'Partos Big On Golf Learning Center'),
  ('United States', 'Partridge Run Golf Country Club'),
  ('United States', 'Pasadena Ridge Par 3 Golf Course'),
  ('United States', 'Pasadena Yacht Country Club'),
  ('United States', 'Pasatiempo Golf Club'),
  ('United States', 'Pascagoula Country Club'),
  ('United States', 'Paschal Golf Club'),
  ('United States', 'Pasco Golfland'),
  ('United States', 'Pasfield Golf Course'),
  ('United States', 'Paso Robles Golf Club'),
  ('United States', 'Pass Christian Isles Golf Club'),
  ('United States', 'Passaconaway Country Club'),
  ('United States', 'Pathfinder Village Golf Course'),
  ('United States', 'Patricia Island Golf Club'),
  ('United States', 'Patrick Farms Golf Course'),
  ('United States', 'Patriot Golf Club'),
  ('United States', 'Patriot Golf Course'),
  ('United States', 'Patriot Hills Golf Club'),
  ('United States', 'Patriots Glen Golf Club'),
  ('United States', 'Patriots Point Golf Links'),
  ('United States', 'Patterson Club'),
  ('United States', 'Pattison Park Golf course'),
  ('United States', 'Patty Jewett Golf Course Peak Nine'),
  ('United States', 'Patty Jewett Golf Course Plains Nine'),
  ('United States', 'Patty Jewett Golf Course Prairie Nine'),
  ('United States', 'Paul Harney Golf Club'),
  ('United States', 'Paul Hunt Thompson Golf Course'),
  ('United States', 'Paullina Golf Course'),
  ('United States', 'Pauls Valley Municipal Golf Course'),
  ('United States', 'Pauma Valley Country Club'),
  ('United States', 'Paupack Hills Golf Country Club'),
  ('United States', 'Paw Paw Lake Golf Course'),
  ('United States', 'Pawhuska Golf Country Club'),
  ('United States', 'Pawleys Plantation Golf Country Club'),
  ('United States', 'Pawnee Municipal Golf Course'),
  ('United States', 'Pawtucket Country Club'),
  ('United States', 'Paxon Hollow Golf Club'),
  ('United States', 'Paxton Park Golf Course'),
  ('United States', 'Payne S Valley'),
  ('United States', 'Payson Golf Club'),
  ('United States', 'Peabody Golf Course'),
  ('United States', 'Peace Pipe Golf Club'),
  ('United States', 'Peace Portal Par 3 Golf Course'),
  ('United States', 'Peach Tree Golf Country Club'),
  ('United States', 'Peach Trees Executive Golf Club'),
  ('United States', 'Peachtree Golf Center'),
  ('United States', 'Peachtree Golf Club'),
  ('United States', 'Peachtree Hills Country Club'),
  ('United States', 'Peacock Gap Golf Club'),
  ('United States', 'Peaks At Tonto Verde Golf Club'),
  ('United States', 'Peaks Par 3 Golf Course'),
  ('United States', 'Pearl At Kalauao'),
  ('United States', 'Pearl Lakes Country Club'),
  ('United States', 'Pearl Municipal Golf Course'),
  ('United States', 'Pease Blue Golf Course'),
  ('United States', 'Pease Original 18 Golf Course'),
  ('United States', 'Pebble Beach Golf Linkstm'),
  ('United States', 'Pebble Brook Golf Club'),
  ('United States', 'Pebble Creek'),
  ('United States', 'Pebble Creek Golf Club'),
  ('United States', 'Pebble Creek Golf Course'),
  ('United States', 'Pebble Lake Golf Club'),
  ('United States', 'Pebble Lake Golf Course'),
  ('United States', 'Pebble Ponds Golf Course'),
  ('United States', 'Pebblebrook Golf Club'),
  ('United States', 'Pebblebrook Golf Course'),
  ('United States', 'Pebblebrook Golf Links'),
  ('United States', 'Pebblewood Golf Course'),
  ('United States', 'Pecan Valley At Mohawk Park Golf Course'),
  ('United States', 'Pecan Valley Golf Course'),
  ('United States', 'Peddie Golf Club'),
  ('United States', 'Pehquenakonck Country Club'),
  ('United States', 'Pekin Country Club'),
  ('United States', 'Pelham Bay At Pelham Split Rock Golf Course'),
  ('United States', 'Pelham Country Club'),
  ('United States', 'Pelican At The Villages Executive Golf Trail'),
  ('United States', 'Pelican Falls At Pelican Lakes Golf Club'),
  ('United States', 'Pelican Golf Club'),
  ('United States', 'Pelican Lakes At Pelican Lakes Golf Club'),
  ('United States', 'Pelican Marsh Golf Club'),
  ('United States', 'Pelican Osprey At Burnt Store Marina Country Club'),
  ('United States', 'Pelican Point Golf Club Get Golf Ready Course'),
  ('United States', 'Pelican Point Golf Club Links Course'),
  ('United States', 'Pelican Pointe Golf Country Club Hatchett Meadows Course'),
  ('United States', 'Pelican Pointe Golf Country Club Meadows Preserve Course'),
  ('United States', 'Pelican Pointe Golf Country Club Preserve Hatchett Course'),
  ('United States', 'Pelicans Nest Golf Club Gator Course'),
  ('United States', 'Pelicans Nest Golf Club Hurricane Course'),
  ('United States', 'Pella Golf & Country Club'),
  ('United States', 'Pembroke Country Club'),
  ('United States', 'Pembroke Lakes Golf Racquet Club'),
  ('United States', 'Pembroke Pines Country Club'),
  ('United States', 'Pend Oreille Golf Country Club'),
  ('United States', 'Pendaries Golf Country Club'),
  ('United States', 'Pender Island Golf And Country Club'),
  ('United States', 'Penderbrook Golf Club'),
  ('United States', 'Pendleton Golf Club'),
  ('United States', 'Pendleton Harbor Golf Course'),
  ('United States', 'Pendleton Hills'),
  ('United States', 'Penfield Country Club'),
  ('United States', 'Peninsula Golf Club'),
  ('United States', 'Peninsula Golf Country Club'),
  ('United States', 'Peninsula Golf Course'),
  ('United States', 'Peninsula Golf Resort'),
  ('United States', 'Peninsula State Park Golf Course'),
  ('United States', 'Penmar Golf Course'),
  ('United States', 'Penn Oaks Country Club'),
  ('United States', 'Penn Terra Golf Course'),
  ('United States', 'Penney Farms Retirement Community Golf Course'),
  ('United States', 'Pennhills Club'),
  ('United States', 'Pennrose Park Country Club'),
  ('United States', 'Pennsauken Country Club'),
  ('United States', 'Pennyrile Forest State Park Resort'),
  ('United States', 'Penobscot Valley Country Club'),
  ('United States', 'Pensacola Country Club'),
  ('United States', 'Peoria Pines Golf Club'),
  ('United States', 'Peoria Ridge'),
  ('United States', 'Pepper Pike Club'),
  ('United States', 'Pequabuck Golf Club'),
  ('United States', 'Pequot Golf Club'),
  ('United States', 'Perdido Bay Golf Club'),
  ('United States', 'Perham Lakeside Golf Club'),
  ('United States', 'Peridia Golf Country Club'),
  ('United States', 'Perinton Golf Country Club'),
  ('United States', 'Perry Creek Golf Racquet Club'),
  ('United States', 'Perry Golf Country Club'),
  ('United States', 'Perry Golf Course'),
  ('United States', 'Perry Golf and Country Club'),
  ('United States', 'Perry Park Country Club'),
  ('United States', 'Perryton Golf Club'),
  ('United States', 'Perryville Country Club'),
  ('United States', 'Persimmon Country Club'),
  ('United States', 'Persimmon Hill Golf Club'),
  ('United States', 'Persimmon Ridge Golf Club'),
  ('United States', 'Perttu''s Big Spruce Golf Course'),
  ('United States', 'Petaluma Golf Country Club'),
  ('United States', 'Pete Brown Golf Facility'),
  ('United States', 'Pete Dye Challenge At Mission Hills Country Club'),
  ('United States', 'Pete Dye Course'),
  ('United States', 'Pete Dye Course At Hideaway Club'),
  ('United States', 'Pete Dye River Course Of Virginia Tech'),
  ('United States', 'Peter Yegen Jr Golf Club'),
  ('United States', 'Petersburg Country Club'),
  ('United States', 'Petoskey - Bay View Country Club'),
  ('United States', 'Petrifying Springs Golf Course'),
  ('United States', 'Pevely Farms Golf Course'),
  ('United States', 'Pfau Indiana University Golf Course'),
  ('United States', 'Pga National Resort Champion Course'),
  ('United States', 'Pga National Resort Estates Course'),
  ('United States', 'Pga National Resort Fazio Course'),
  ('United States', 'Pga National Resort Palmer Course'),
  ('United States', 'Pga National Resort The Match'),
  ('United States', 'Pga National Resort The Staple'),
  ('United States', 'Pga West Greg Norman Course'),
  ('United States', 'Pga West Jack Nicklaus Tournament Course'),
  ('United States', 'Pga West Pete Dye Dunes Course'),
  ('United States', 'Pga West Pete Dye Mountain Course'),
  ('United States', 'Pga West Private Arnold Palmer Course'),
  ('United States', 'Pga West Private Jack Nicklaus Private Course'),
  ('United States', 'Pga West Private Tom Weiskopf Course'),
  ('United States', 'Pheasand Hills Golf Course'),
  ('United States', 'Pheasant Acres Golf Course'),
  ('United States', 'Pheasant Glen Golf Resort'),
  ('United States', 'Pheasant Hill Country Club'),
  ('United States', 'Pheasant Hollow Golf Course'),
  ('United States', 'Pheasant Links'),
  ('United States', 'Pheasant Ridge Golf Club'),
  ('United States', 'Pheasant Ridge Golf Course'),
  ('United States', 'Pheasant Run Golf Club'),
  ('United States', 'Pheasant Run Golf Course'),
  ('United States', 'Pheasant Run Golfcourse'),
  ('United States', 'Phil Harris Golf Course'),
  ('United States', 'Philadelphia Country Club'),
  ('United States', 'Philipsburg Elks Lodge Country Club'),
  ('United States', 'Phillip J Rotella Memorial Golf Course'),
  ('United States', 'Phillips Park Golf Course'),
  ('United States', 'Phillipsburg Golf Course'),
  ('United States', 'Philmont Country Club'),
  ('United States', 'Phoenix Country Club 1'),
  ('United States', 'Phoenixville Country Club'),
  ('United States', 'Piankatank River Golf Club'),
  ('United States', 'Picacho Hills Country Club'),
  ('United States', 'Picatinny Golf Club'),
  ('United States', 'Pickaway Golf Course'),
  ('United States', 'Pickens Golf Club'),
  ('United States', 'Pickering Valley Golf Club'),
  ('United States', 'Pickwick Landing State Park Golf Course'),
  ('United States', 'Pico Rivera Golf Club'),
  ('United States', 'Pictured Rocks Golf Club'),
  ('United States', 'Piedmont Canyon Club'),
  ('United States', 'Piedmont Driving Club'),
  ('United States', 'Piedmont Driving Club Par 3 Course'),
  ('United States', 'Piedmont Golf Club'),
  ('United States', 'Pierce Lake Golf Course and Park'),
  ('United States', 'Pierce Park Golf & Events'),
  ('United States', 'Pierce Park Greens'),
  ('United States', 'Pierson Golf Course'),
  ('United States', 'Pigeon Creek Golf Course'),
  ('United States', 'Pike Lake Golf Course'),
  ('United States', 'Pike Run Country Club'),
  ('United States', 'Pike Run Golf Club'),
  ('United States', 'Pikeville Country Club'),
  ('United States', 'Pilgrim''s Run Golf Course'),
  ('United States', 'Pilgrims Oak Golf Course'),
  ('United States', 'Pilot Knob Park Golf Course'),
  ('United States', 'Pimlico At The Villages Executive Golf Trail'),
  ('United States', 'Pinch Brook Golf Course'),
  ('United States', 'Pine Acres Country Club'),
  ('United States', 'Pine Acres Golf Course'),
  ('United States', 'Pine Acres Par 3 Golf Course Driving Range'),
  ('United States', 'Pine At Mccormick Ranch Golf Club'),
  ('United States', 'Pine Barrens'),
  ('United States', 'Pine Bay Golf Course'),
  ('United States', 'Pine Bayhead Golf Course At Countryside Country Club'),
  ('United States', 'Pine Beach East Golf Course'),
  ('United States', 'Pine Bluff Country Club'),
  ('United States', 'Pine Brook Country Club'),
  ('United States', 'Pine Brook Golf Course'),
  ('United States', 'Pine Brook Golf Links'),
  ('United States', 'Pine Burr Country Club'),
  ('United States', 'Pine Burr Golf Course'),
  ('United States', 'Pine Canyon Club'),
  ('United States', 'Pine Creek Golf Club'),
  ('United States', 'Pine Creek Golf Course'),
  ('United States', 'Pine Crest Golf Course'),
  ('United States', 'Pine Edge Golf Course'),
  ('United States', 'Pine Forest Country Club'),
  ('United States', 'Pine Grove Country Club'),
  ('United States', 'Pine Grove Golf Course'),
  ('United States', 'Pine Grove Springs Country Club'),
  ('United States', 'Pine Hill Country Club'),
  ('United States', 'Pine Hill Golf Club'),
  ('United States', 'Pine Hill Golf Country Club'),
  ('United States', 'Pine Hill Golf Course'),
  ('United States', 'Pine Hills Country Club'),
  ('United States', 'Pine Hills Golf Club'),
  ('United States', 'Pine Hills Golf Course'),
  ('United States', 'Pine Hollow Country Club'),
  ('United States', 'Pine Hollow Golf Club'),
  ('United States', 'Pine Hollow Golf Course'),
  ('United States', 'Pine Island Country Club'),
  ('United States', 'Pine Island Golf Course'),
  ('United States', 'Pine Island Ridge Country Club'),
  ('United States', 'Pine Islands Golf Club'),
  ('United States', 'Pine Knob Golf Club'),
  ('United States', 'Pine Knoll Executive Golf Course'),
  ('United States', 'Pine Knolls Country Club'),
  ('United States', 'Pine Knolls Golf Course'),
  ('United States', 'Pine Lake Country Club'),
  ('United States', 'Pine Lake Golf Club'),
  ('United States', 'Pine Lake Golf Course'),
  ('United States', 'Pine Lakes Country Club'),
  ('United States', 'Pine Lakes Golf Club'),
  ('United States', 'Pine Marsh Golf Course'),
  ('United States', 'Pine Meadow Country Club Estates'),
  ('United States', 'Pine Meadow Golf Club'),
  ('United States', 'Pine Meadows Golf Club'),
  ('United States', 'Pine Meadows Golf Course'),
  ('United States', 'Pine Mountain Golf Club'),
  ('United States', 'Pine Mountain Golf Course'),
  ('United States', 'Pine Mountain Lake Golf Course'),
  ('United States', 'Pine Needles Country Club'),
  ('United States', 'Pine Needles Lodge Golf Club'),
  ('United States', 'Pine Needles Lodge Golf Club Practice Loop'),
  ('United States', 'Pine Oaks Golf Club'),
  ('United States', 'Pine Orchard Yacht Country Club'),
  ('United States', 'Pine Ridge Classic Golf Course'),
  ('United States', 'Pine Ridge Country Club'),
  ('United States', 'Pine Ridge Golf Club'),
  ('United States', 'Pine Ridge Golf Club Little Pine'),
  ('United States', 'Pine Ridge Golf Course'),
  ('United States', 'Pine Ridge Municipal Golf Center'),
  ('United States', 'Pine River Country Club'),
  ('United States', 'Pine River Golf Club'),
  ('United States', 'Pine Royale Golf Club'),
  ('United States', 'Pine Shore Golf Course'),
  ('United States', 'Pine Trace Golf Club'),
  ('United States', 'Pine Tree Golf Club'),
  ('United States', 'Pine Valley Country Club'),
  ('United States', 'Pine Valley Golf & Country Club'),
  ('United States', 'Pine Valley Golf Club'),
  ('United States', 'Pine Valley Golf Club Championship'),
  ('United States', 'Pine Valley Golf Club Short'),
  ('United States', 'Pine Valley Golf Course')
on conflict (country, name) do nothing;