insert into public.golf_courses (country, name) values
  ('United States', 'Silver Blue At Foxfire Country Club'),
  ('United States', 'Silver Creek Golf Club'),
  ('United States', 'Silver Creek Golf Course'),
  ('United States', 'Silver Creek Plantation'),
  ('United States', 'Silver Creek Valley Country Club'),
  ('United States', 'Silver Dollar Golf Trap Club Bobcat Gator Course'),
  ('United States', 'Silver Dollar Golf Trap Club Gator Panther Course'),
  ('United States', 'Silver Dollar Golf Trap Club Panther Bobcat Course'),
  ('United States', 'Silver Fox Golf Course'),
  ('United States', 'Silver King Golf Club'),
  ('United States', 'Silver Lake At The Villages Executive Golf Trail'),
  ('United States', 'Silver Lake Country Club'),
  ('United States', 'Silver Lake Golf Course'),
  ('United States', 'Silver Lakes Rv Resort Golf Club'),
  ('United States', 'Silver Oak Golf Course'),
  ('United States', 'Silver Oaks Golf Club'),
  ('United States', 'Silver Ridge'),
  ('United States', 'Silver Sage Golf Course'),
  ('United States', 'Silver Spring Country Club'),
  ('United States', 'Silver Spring Golf Club'),
  ('United States', 'Silver Spring Golf Course'),
  ('United States', 'Silver Springs Country Club'),
  ('United States', 'Silver Springs Golf Club'),
  ('United States', 'Silverado Golf Country Club'),
  ('United States', 'Silverado Resort Spa North Course'),
  ('United States', 'Silverado Resort Spa South Course'),
  ('United States', 'Silverbell Municipal Golf Course'),
  ('United States', 'Silvercrest Golf Club'),
  ('United States', 'Silvermine Golf Club Pro Shop 9 Course'),
  ('United States', 'Silvermine Golf Club Woods 9 Barn 9 Course'),
  ('United States', 'Silverrock Resort'),
  ('United States', 'Silverthorn Country Club'),
  ('United States', 'Sim Park Golf Course'),
  ('United States', 'Simi Hills Golf Course'),
  ('United States', 'Simpson Country Club'),
  ('United States', 'Simsbury Farms Golf Club'),
  ('United States', 'Sinaloa Golf Course'),
  ('United States', 'Sinclair Golf Club'),
  ('United States', 'Singing Bridge Golf Course'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Oak Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Pine Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Willow Glen'),
  ('United States', 'Sinking Valley Country Club'),
  ('United States', 'Sinnissippi Golf Course'),
  ('United States', 'Sioux City Country Club'),
  ('United States', 'Sioux Valley Golf Course'),
  ('United States', 'Siren National Golf Club'),
  ('United States', 'Sistersville Country Club Golf Course'),
  ('United States', 'Sitzmark Lodge'),
  ('United States', 'Siwanoy Country Club'),
  ('United States', 'Six Lakes Country Club'),
  ('United States', 'Skagit Golf Country Club'),
  ('United States', 'Skamania Lodge The Gorge 9'),
  ('United States', 'Skaneateles Country Club'),
  ('United States', 'Skenandoa Club Of Clinton'),
  ('United States', 'Skene Valley Country Club'),
  ('United States', 'Skippack Golf Course'),
  ('United States', 'Skokie Country Club'),
  ('United States', 'Skungamaug River Golf Club'),
  ('United States', 'Sky Meadow Country Club'),
  ('United States', 'Sky Mountain Golf Course'),
  ('United States', 'Sky Ranch Golf Course'),
  ('United States', 'Sky Valley Country Club'),
  ('United States', 'Skybrook Golf Club'),
  ('United States', 'Skyland Lakes Golf Course Resort'),
  ('United States', 'Skyline Country Club'),
  ('United States', 'Skyline Golf Course'),
  ('United States', 'Skyline Mountain Resort And Golf Course'),
  ('United States', 'Skyline Public Golf Course'),
  ('United States', 'Skyline Ranch Country Club'),
  ('United States', 'Skylinks At Buchanan Fields'),
  ('United States', 'Skylinks Golf Course'),
  ('United States', 'Skyridge Golf Course'),
  ('United States', 'Skytop Lodge Poconos Golf Course'),
  ('United States', 'Skytop Mountain Golf Club'),
  ('United States', 'Skyview At Terra Vista'),
  ('United States', 'Skyview Golf Club'),
  ('United States', 'Skyway Golf Course'),
  ('United States', 'Skyway Golf Course At Lincoln Park West'),
  ('United States', 'Skyway Golf Park'),
  ('United States', 'Slammer And Squire Golf Course At World Golf Village'),
  ('United States', 'Slayton Country Club'),
  ('United States', 'Sleeping Giant Golf Course'),
  ('United States', 'Sleeping Indian Cottonwood At West Woods Golf Club'),
  ('United States', 'Sleepy Eye Golf Club'),
  ('United States', 'Sleepy Hole Golf Course'),
  ('United States', 'Sleepy Hollow Country Club'),
  ('United States', 'Sleepy Hollow Country Club Lower Course'),
  ('United States', 'Sleepy Hollow Country Club Upper Course'),
  ('United States', 'Sleepy Hollow Golf Club'),
  ('United States', 'Sleepy Hollow Golf Country Club'),
  ('United States', 'Sleepy Hollow Golf Course'),
  ('United States', 'Sleepy Hollow Sports Park'),
  ('United States', 'Sliding Rock Golf Course'),
  ('United States', 'Sligo Creek Golf Course'),
  ('United States', 'Slippery Elm Golf Course'),
  ('United States', 'Slippery Rock Golf Club Events Center'),
  ('United States', 'Sloan Golf Course'),
  ('United States', 'Sly Fox Golf Club'),
  ('United States', 'Smethport Country Club'),
  ('United States', 'Smileys Executive Golf Club'),
  ('United States', 'Smith Center Municipal Golf Course'),
  ('United States', 'Smithfield Golf Club'),
  ('United States', 'Smithfields Country Club'),
  ('United States', 'Smock Golf Course'),
  ('United States', 'Smoke Rise Country Club'),
  ('United States', 'Smoky Hill Country Club'),
  ('United States', 'Smoky Mountain Country Club'),
  ('United States', 'Smoky River Golf Course'),
  ('United States', 'Smugglers Glen Golf Course'),
  ('United States', 'Snake River Golf Course'),
  ('United States', 'Snee Farm Country Club'),
  ('United States', 'Snohomish Public Golf Course'),
  ('United States', 'Snoqualmie Falls Golf Course'),
  ('United States', 'Snow Hill Country Club'),
  ('United States', 'Snow Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Snow Snake Golf Course'),
  ('United States', 'Snowcreek Golf Course'),
  ('United States', 'Snowflake Municipal Golf Course 18 Hole Course'),
  ('United States', 'Snowflake Municipal Golf Course 9 Hole Course'),
  ('United States', 'Snowflake Ski Club'),
  ('United States', 'Snowmass Club'),
  ('United States', 'Snyder Park Golf Course'),
  ('United States', 'Soaring Eagles Golf Course'),
  ('United States', 'Social Nine At Maddens On Gull Lake'),
  ('United States', 'Sodus Bay Heights Golf Club'),
  ('United States', 'Soldier Hill Golf Course'),
  ('United States', 'Soldier Hollow Golf Course The Gold Course'),
  ('United States', 'Soldier Hollow Golf Course The Silver Course'),
  ('United States', 'Soldiers Creek Golf Club'),
  ('United States', 'Soldiers Field Golf Course'),
  ('United States', 'Soleta Golf Golf Club'),
  ('United States', 'Soleta Golf Golf Club The Colt'),
  ('United States', 'Solina Golf Club'),
  ('United States', 'Solitude Links Golf Course & Banquet Center'),
  ('United States', 'Somerby Golf Club'),
  ('United States', 'Somers National Golf Club'),
  ('United States', 'Somerset Country Club'),
  ('United States', 'Somerset Farms Golf Course'),
  ('United States', 'Somerset Golf Course'),
  ('United States', 'Somerset Hills Country Club'),
  ('United States', 'Somersett Country Club Canyon Nine'),
  ('United States', 'Somersett Country Club Championship'),
  ('United States', 'Songbird Hills Golf Club'),
  ('United States', 'Sonnenalp Resort Of Vail'),
  ('United States', 'Sonnys Par 3 And Driving Range'),
  ('United States', 'Sonoma Golf Club'),
  ('United States', 'Sonoma Ranch Golf Course'),
  ('United States', 'Sonora Dunes Golf Course'),
  ('United States', 'Sonoran Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Sonoran Golf Course At Oakwood Country Club'),
  ('United States', 'Sonyea Golf Course'),
  ('United States', 'Sorrento Par 3 Golf Course'),
  ('United States', 'Souhegan Woods Golf Club'),
  ('United States', 'Soule Park Golf Club'),
  ('United States', 'Sound Of Freedom Golf Course'),
  ('United States', 'Sound River Course At Pelican Sound Golf River Club'),
  ('United States', 'South At Admiral Baker Golf Course'),
  ('United States', 'South At Antelope Hills Golf Course'),
  ('United States', 'South At Bay Palms Golf Complex'),
  ('United States', 'South At Boulders Golf Club Resort'),
  ('United States', 'South At Bretwood Golf Course'),
  ('United States', 'South At Canoe Brook Country Club'),
  ('United States', 'South At Carmel Country Club'),
  ('United States', 'South At Cherokee Town Country Club'),
  ('United States', 'South At Cherokee Village'),
  ('United States', 'South At Churchville Park Golf Course'),
  ('United States', 'South At Coto De Caza Golf Racquet Club'),
  ('United States', 'South At Country Club Of Scranton The'),
  ('United States', 'South At Crestview Country Club'),
  ('United States', 'South At Daytona Beach Golf Country Club'),
  ('United States', 'South At Deerfield Country Club'),
  ('United States', 'South At Earlywine Golf Course'),
  ('United States', 'South At Fountains Country Club'),
  ('United States', 'South At Frenchmans Creek Beach Country Club'),
  ('United States', 'South At Hunters Run Golf Course'),
  ('United States', 'South At Ironwood Country Club'),
  ('United States', 'South At Johns Island Club'),
  ('United States', 'South At Lake Hefner Golf Course'),
  ('United States', 'South At Los Angeles Country Club The'),
  ('United States', 'South At Los Serranos Golf Country Club'),
  ('United States', 'South At Moss Creek Golf Club'),
  ('United States', 'South At Quail Ridge Country Club'),
  ('United States', 'South At Raintree Country Club'),
  ('United States', 'South At Rancho Murieta Country Club'),
  ('United States', 'South At Torrey Pines Municipal Golf Course'),
  ('United States', 'South At Victor Hills Golf Club'),
  ('United States', 'South At Vineyards Of Naples The'),
  ('United States', 'South At Westchester Country Club'),
  ('United States', 'South At Wilmington Country Club'),
  ('United States', 'South Bend Country Club'),
  ('United States', 'South Bluff Country Club'),
  ('United States', 'South Course'),
  ('United States', 'South Course At Big Cypress Golf Country Club'),
  ('United States', 'South Course At Highlands Ridge'),
  ('United States', 'South Course At Lake Of Isles'),
  ('United States', 'South Course At Shadow Wood Country Club'),
  ('United States', 'South Course At Terry Hills Golf Course'),
  ('United States', 'South Course At Whitefish Lake Golf Club'),
  ('United States', 'South East At Farmington Country Club'),
  ('United States', 'South East At Killearn Country Club Inn'),
  ('United States', 'South East At Newaukum Valley Golf Course'),
  ('United States', 'South East At Spanish Wells Country Club'),
  ('United States', 'South Fork Country Club'),
  ('United States', 'South Forty Golf Course Driving Range'),
  ('United States', 'South Gate Municipal Golf Course'),
  ('United States', 'South Gleason Park Course'),
  ('United States', 'South Golf Course At Granite Falls Golf Club'),
  ('United States', 'South Granville Country Club'),
  ('United States', 'South Grove Golf Course'),
  ('United States', 'South Harbour Golf Links'),
  ('United States', 'South Hardin Recreation Area'),
  ('United States', 'South Hill Country Club'),
  ('United States', 'South Hills Country Club'),
  ('United States', 'South Hills Golf & Country Club'),
  ('United States', 'South Hills Golf Club'),
  ('United States', 'South Hills Golf Course'),
  ('United States', 'South Lake At Mountain Gate Country Club'),
  ('United States', 'South Lakes Golf Course'),
  ('United States', 'South Mountain Golf Club'),
  ('United States', 'South Mountain Golf Course'),
  ('United States', 'South Nine At Cross Creek Resort'),
  ('United States', 'South North At Athens Country Club'),
  ('United States', 'South North At Cedar Knoll Country Club'),
  ('United States', 'South North At Farmington Country Club'),
  ('United States', 'South North At Fernandina Beach Golf Club'),
  ('United States', 'South North At Lakes Country Club The'),
  ('United States', 'South North At Oaks North Golf Course'),
  ('United States', 'South North At Ocean Breeze Golf Country Club'),
  ('United States', 'South North At Sahalee Country Club'),
  ('United States', 'South North At Spanish Wells Country Club'),
  ('United States', 'South Par 3 At Alondra Park Golf Course'),
  ('United States', 'South Park Golf Course'),
  ('United States', 'South Portland Municipal Golf Course'),
  ('United States', 'South Ridge Golf Course'),
  ('United States', 'South Riding Golf Club'),
  ('United States', 'South Shore Country Club'),
  ('United States', 'South Shore Golf Club'),
  ('United States', 'South Shore Golf Course'),
  ('United States', 'South Shore Village Golf Club'),
  ('United States', 'South Side Country Club'),
  ('United States', 'South Side Links'),
  ('United States', 'South Toledo Golf Club'),
  ('United States', 'South Wales Golf Club'),
  ('United States', 'South West At Elmridge Golf Club'),
  ('United States', 'South West At Krendale Golf Course'),
  ('United States', 'South West At Monterey Country Club'),
  ('United States', 'South West At Newaukum Valley Golf Course'),
  ('United States', 'South West At Rolling Acres Golf Course'),
  ('United States', 'South Winn Golf & Country Club'),
  ('United States', 'Southampton Country Club'),
  ('United States', 'Southampton Golf Club'),
  ('United States', 'Southaven Golf Center'),
  ('United States', 'Southborough Golf Club'),
  ('United States', 'Southbridge Savannah Golf Club'),
  ('United States', 'Southern Delaware Golf Club'),
  ('United States', 'Southern Dunes Golf Country Club'),
  ('United States', 'Southern Dunes Golf Course'),
  ('United States', 'Southern Dutchess Country Club'),
  ('United States', 'Southern Fairways Golf Course'),
  ('United States', 'Southern Gate Golf Course'),
  ('United States', 'Southern Highlands Golf Course'),
  ('United States', 'Southern Hills Golf Club'),
  ('United States', 'Southern Hills Golf Course'),
  ('United States', 'Southern Hills Plantation'),
  ('United States', 'Southern Meadows Par Four'),
  ('United States', 'Southern Oaks Country Club'),
  ('United States', 'Southern Oaks Golf Club'),
  ('United States', 'Southern Oaks Golf Course'),
  ('United States', 'Southern Pines Golf Club'),
  ('United States', 'Southern Ridge Golf Club'),
  ('United States', 'Southern Star At The Villages Executive Golf Trail'),
  ('United States', 'Southern Tee Golf Course'),
  ('United States', 'Southern Trace Country Club'),
  ('United States', 'Southern Wayne Country Club'),
  ('United States', 'Southers Marsh Golf Club'),
  ('United States', 'Southgate Golf Club'),
  ('United States', 'Southglenn Country Club'),
  ('United States', 'Southington Country Club'),
  ('United States', 'Southland Golf Country Club'),
  ('United States', 'Southmoor Golf Course (former)'),
  ('United States', 'Southmoore Golf Course'),
  ('United States', 'Southpointe Golf Club'),
  ('United States', 'Southport Springs Golf Country Club'),
  ('United States', 'Southridge Golf Club'),
  ('United States', 'Southshore Golf Club'),
  ('United States', 'Southshore Golf Learning Center'),
  ('United States', 'Southview Country Club'),
  ('United States', 'Southward Ho Country Club'),
  ('United States', 'Southwick Country Club'),
  ('United States', 'Southwinds Golf Course'),
  ('United States', 'Southwood Golf Club'),
  ('United States', 'Spanish Hills Golf Country Club'),
  ('United States', 'Spanish Lakes Country Club'),
  ('United States', 'Spanish Lakes Fairways'),
  ('United States', 'Spanish Lakes Golf Course'),
  ('United States', 'Spanish Lakes Golf Village'),
  ('United States', 'Spanish Peaks Mountain Club Toms 10 Golf Course'),
  ('United States', 'Spanish Trail Golf Club'),
  ('United States', 'Spanish Wells Club'),
  ('United States', 'Sparta Country Club'),
  ('United States', 'Sparta Moose Lodge Golf Course'),
  ('United States', 'Spearfish Canyon Country Club'),
  ('United States', 'Speedway Putting Course At Sea Island Golf Club'),
  ('United States', 'Speers Public Golf Course'),
  ('United States', 'Speidel Jones Golf Course'),
  ('United States', 'Speidel Palmer Golf Course'),
  ('United States', 'Spencer Golf and Country Club'),
  ('United States', 'Spencer T. Olin Community Golf Course'),
  ('United States', 'Spessard Holland Golf Course'),
  ('United States', 'Spider Lake Golf Resort'),
  ('United States', 'Spirit Hollow Golf Course'),
  ('United States', 'Split Rock At Pelham Split Rock Golf Course'),
  ('United States', 'Split Rock Golf Club'),
  ('United States', 'Split Rock Golf Club North Course'),
  ('United States', 'Split Rock Golf Club South Course'),
  ('United States', 'Spook Rock Golf Course'),
  ('United States', 'Spooky Brook Golf Course'),
  ('United States', 'Spooner Golf Club'),
  ('United States', 'Sportsmans Golf Course'),
  ('United States', 'Spotswood Country Club'),
  ('United States', 'Sprain Lake Golf Course'),
  ('United States', 'Spreading Antlers Golf Course'),
  ('United States', 'Spring Bayou Golf Country Club'),
  ('United States', 'Spring Brook Country Club'),
  ('United States', 'Spring Brook Golf Course'),
  ('United States', 'Spring Creek Golf Club'),
  ('United States', 'Spring Creek Golf Course'),
  ('United States', 'Spring Creek Golf Course Country Club'),
  ('United States', 'Spring Ford Country Club'),
  ('United States', 'Spring Green Municipal Golf Course'),
  ('United States', 'Spring Hill Country Club'),
  ('United States', 'Spring Hill Golf Club'),
  ('United States', 'Spring Hill Golf Course'),
  ('United States', 'Spring Hills Country Club'),
  ('United States', 'Spring Hills Golf Club'),
  ('United States', 'Spring Hills Golf Course'),
  ('United States', 'Spring Hollow Golf Course'),
  ('United States', 'Spring Lake Country Club'),
  ('United States', 'Spring Lake Golf & Country Club'),
  ('United States', 'Spring Lake Golf Club'),
  ('United States', 'Spring Lake Golf Course'),
  ('United States', 'Spring Lake Golf Resort Bobcat Run Executive Course'),
  ('United States', 'Spring Lakes Golf Club'),
  ('United States', 'Spring Meadow Golf Club'),
  ('United States', 'Spring Meadows Country Club'),
  ('United States', 'Spring Meadows Golf Club'),
  ('United States', 'Spring Mill At Philadelphia Country Club'),
  ('United States', 'Spring Mill Country Club'),
  ('United States', 'Spring Run Golf Club'),
  ('United States', 'Spring Valley Country Club'),
  ('United States', 'Spring Valley Golf Club'),
  ('United States', 'Spring Valley Golf Course'),
  ('United States', 'Springbrook Country Club'),
  ('United States', 'Springbrook Golf Club'),
  ('United States', 'Springbrook Golf Course'),
  ('United States', 'Springbrook Greens Golf Course'),
  ('United States', 'Springdale Country Club'),
  ('United States', 'Springdale Golf Club'),
  ('United States', 'Springdale Park and Golf Course'),
  ('United States', 'Springdale Resort'),
  ('United States', 'Springfield Country Club'),
  ('United States', 'Springfield Golf Center'),
  ('United States', 'Springfield Golf Club'),
  ('United States', 'Springfield Golf Country Club'),
  ('United States', 'Springfield Golf Course'),
  ('United States', 'Springfield Golf Resort'),
  ('United States', 'Springfield Oaks Golf Course'),
  ('United States', 'Springhaven Club'),
  ('United States', 'Springhill Country Club'),
  ('United States', 'Springhill Golf Course'),
  ('United States', 'Springside Par 3 Golf Course'),
  ('United States', 'Springvale Golf Course'),
  ('United States', 'Springville Country Club'),
  ('United States', 'Spruce Creek Country Club'),
  ('United States', 'Spruce Dogwood At Middle Island Country Club'),
  ('United States', 'Spruce Ridge Golf Club'),
  ('United States', 'Spruce Ridge Golf Course'),
  ('United States', 'Spruce Run Golf Course'),
  ('United States', 'Spud Run Golf'),
  ('United States', 'Spy Ring Golf Club'),
  ('United States', 'Spyglass Hilltm Golf Course'),
  ('United States', 'Squaw Creek Golf Course'),
  ('United States', 'Squaw Mountain Village Golf Course'),
  ('United States', 'Squire Creek Country Club'),
  ('United States', 'Squires Golf Club'),
  ('United States', 'Squirrel Run Country Club'),
  ('United States', 'St Alban''s Golf Course'),
  ('United States', 'St Andrews At Westcliffe'),
  ('United States', 'St Andrews By The Lake Golf Club'),
  ('United States', 'St Andrews Club'),
  ('United States', 'St Andrews Country Club Arnold Palmer Course'),
  ('United States', 'St Andrews Country Club Fazio Ii Course'),
  ('United States', 'St Andrews Golf Club'),
  ('United States', 'St Andrews Golf Club The'),
  ('United States', 'St Andrews South Golf Club'),
  ('United States', 'St Anne Country Club'),
  ('United States', 'St Augustine Shores Golf Club'),
  ('United States', 'St Bonaventure Golf Club'),
  ('United States', 'St Croix Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'St Davids Golf Club'),
  ('United States', 'St George Country Club'),
  ('United States', 'St George Golf Club'),
  ('United States', 'St Georges Golf Country Club'),
  ('United States', 'St Helens Golf Course'),
  ('United States', 'St Ives Country Club'),
  ('United States', 'St James Bay Golf Club'),
  ('United States', 'St John Golf Country Club'),
  ('United States', 'St Johns Golf Club'),
  ('United States', 'St Johns Golf Country Club'),
  ('United States', 'St Johnsbury Country Club'),
  ('United States', 'St Joseph Bay Golf Club'),
  ('United States', 'St Joseph Country Club'),
  ('United States', 'St Lawrence State Park Golf Course'),
  ('United States', 'St Lawrence University Golf Country Club'),
  ('United States', 'St Lucie Trail Golf Club'),
  ('United States', 'St Malo Golf Cabins'),
  ('United States', 'St Maries Golf Course'),
  ('United States', 'St Marlo Country Club'),
  ('United States', 'St Martins Golf Course At Philadelphia Cricket Club'),
  ('United States', 'St Mary Golf Country Club'),
  ('United States', 'St Marys Public Golf Course'),
  ('United States', 'St Mellion Golf Club Nicklaus Course'),
  ('United States', 'St Petersburg Country Club'),
  ('United States', 'St Stanislaus Golf Course'),
  ('United States', 'St Stephen Golf Club'),
  ('United States', 'St. Anne''s Golf Course'),
  ('United States', 'St. Bernard Golf Club'),
  ('United States', 'St. Charles Disc Golf Course'),
  ('United States', 'St. Charles Golf Club'),
  ('United States', 'St. Clair Country Club'),
  ('United States', 'St. Clair Golf Club'),
  ('United States', 'St. Clair Parkway Golf Course'),
  ('United States', 'St. Cloud Country Club'),
  ('United States', 'St. Croix Valley Golf Course'),
  ('United States', 'St. Denis Golf Course'),
  ('United States', 'St. Germain Golf 9 Hole'),
  ('United States', 'St. Louis Country Club'),
  ('United States', 'St. Mike''s Golf Course'),
  ('United States', 'St. Peters Golf Course'),
  ('United States', 'St. Urho'),
  ('United States', 'Stadium Golf Club'),
  ('United States', 'Stafford Country Club'),
  ('United States', 'Stafford County Country Club'),
  ('United States', 'Stagg Hill Golf Club'),
  ('United States', 'Stahlstown Par 3 Golf Course'),
  ('United States', 'Stallion Mountain Golf Club'),
  ('United States', 'Stamford Golf Course'),
  ('United States', 'Stamford Valley Golf Course'),
  ('United States', 'Standard Club The'),
  ('United States', 'Standard Country Club'),
  ('United States', 'Stanford Golf Club'),
  ('United States', 'Stanley Golf Course Blue White'),
  ('United States', 'Stanley Golf Course Red Blue'),
  ('United States', 'Stanley Golf Course White Red'),
  ('United States', 'Stansbury Park Golf Course'),
  ('United States', 'Stanton County Prairie Pines'),
  ('United States', 'Stanton Ridge Golf Country Club'),
  ('United States', 'Stanwich Club'),
  ('United States', 'Star Valley Rv Golf Course'),
  ('United States', 'Star Valley View Golf Course'),
  ('United States', 'Stardust Golf Course At Sun City West'),
  ('United States', 'Starfire Golf Club The King Course'),
  ('United States', 'Starfire Golf Club The Mulligan 9'),
  ('United States', 'Starke Country Club'),
  ('United States', 'Starkville Country Club'),
  ('United States', 'Starmount Forest Country Club'),
  ('United States', 'Starx Golf Course'),
  ('United States', 'States Golf Club'),
  ('United States', 'Statesville Country Club'),
  ('United States', 'Steamboat Golf Club'),
  ('United States', 'Steel Canyon Golf Club'),
  ('United States', 'Steel Club Championship Course'),
  ('United States', 'Steel Club Hill Nine'),
  ('United States', 'Steel Creek Golf Course'),
  ('United States', 'Steele Canyon Golf Club Canyon Ranch'),
  ('United States', 'Steele Canyon Golf Club Canyon Vineyard'),
  ('United States', 'Steele Canyon Golf Club Ranch Vineyard'),
  ('United States', 'Steele Hill Resort Golf Course'),
  ('United States', 'Steeple Chase Golf Club'),
  ('United States', 'Stengers Shamrock Farms Par 3 Golf Course'),
  ('United States', 'Stephen Golf Course'),
  ('United States', 'Sterling Country Club'),
  ('United States', 'Sterling Farms Golf Course'),
  ('United States', 'Sterling Grove Golf Country Club'),
  ('United States', 'Sterling Hills Golf Club'),
  ('United States', 'Sterling National Country Club'),
  ('United States', 'Sterling Park Golf Club'),
  ('United States', 'Steubenville Country Club'),
  ('United States', 'Steve Hogan Golf Course'),
  ('United States', 'Stevens Point Country Club'),
  ('United States', 'Stewartville Golf Club'),
  ('United States', 'Stillmeadow Country Club'),
  ('United States', 'Stillwater Country Club'),
  ('United States', 'Stillwater Golf And Country Club'),
  ('United States', 'Stillwater Golf Course'),
  ('United States', 'Stillwater Oaks Golf Course'),
  ('United States', 'Stillwater Valley Golf Club'),
  ('United States', 'Stirrup Cup Course At Glenview Champions Country Club'),
  ('United States', 'Stoatin Brae Golf Club'),
  ('United States', 'Stock Farm'),
  ('United States', 'Stockbridge Golf Club'),
  ('United States', 'Stockdale Country Club'),
  ('United States', 'Stockton Golf Country Club'),
  ('United States', 'Stoeckeler Memorial Park Golf Course'),
  ('United States', 'Stone Canyon Club'),
  ('United States', 'Stone Creek At Page Belcher Golf Course'),
  ('United States', 'Stone Creek Cove Golf Course'),
  ('United States', 'Stone Creek Golf Club'),
  ('United States', 'Stone Creek Golf Course'),
  ('United States', 'Stone Crossing Golf Club'),
  ('United States', 'Stone Dock Golf Club'),
  ('United States', 'Stone E Lea Golf Course'),
  ('United States', 'Stone Eagle Golf Club'),
  ('United States', 'Stone Harbor Golf Club'),
  ('United States', 'Stone Hedge Country Club'),
  ('United States', 'Stone Meadow Golf'),
  ('United States', 'Stone Meadows Golf Course'),
  ('United States', 'Stone Mountain Golf Club'),
  ('United States', 'Stone Oak Country Club'),
  ('United States', 'Stone Ridge Golf Club'),
  ('United States', 'Stone Tree Golf Club'),
  ('United States', 'StoneRidge Golf Club'),
  ('United States', 'Stonebridge Country Club'),
  ('United States', 'Stonebridge Golf Club'),
  ('United States', 'Stonebridge Golf Club Creekside Sunrise Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Championship Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Harvey 9 Course'),
  ('United States', 'Stonebridge Golf Club Sagebrush Creekside Course'),
  ('United States', 'Stonebridge Golf Club Sunrise Sagebrush Course'),
  ('United States', 'Stonebridge Golf Country Club'),
  ('United States', 'Stonebridge Golf Links Country Club'),
  ('United States', 'Stonebridge Meadows Golf Club'),
  ('United States', 'Stonebrook Golf Course'),
  ('United States', 'Stonebrooke Golf Course'),
  ('United States', 'Stonecreek Golf Club'),
  ('United States', 'Stonecrest'),
  ('United States', 'Stonecrest Golf Club'),
  ('United States', 'Stonecrest Golf Club Meadows Course'),
  ('United States', 'Stonecrest Golf Course'),
  ('United States', 'Stonegate Golf Club'),
  ('United States', 'Stonegate Golf Course'),
  ('United States', 'Stoneham Oaks Golf Course'),
  ('United States', 'Stonehedge Golf Course'),
  ('United States', 'Stonehedge North'),
  ('United States', 'Stonehedge South'),
  ('United States', 'Stonehedges Golf Club'),
  ('United States', 'Stonehenge Golf Club'),
  ('United States', 'Stonehenge Golf Country Club'),
  ('United States', 'Stonehenge Golf Course'),
  ('United States', 'Stonehouse Creek At Temecula Creek Inn Golf Resort'),
  ('United States', 'Stonehouse Golf Club'),
  ('United States', 'Stoneleigh Golf Club'),
  ('United States', 'Stonemont At Stone Mountain Golf Course'),
  ('United States', 'Stoneridge Golf Course'),
  ('United States', 'Stones Throw Golf Course'),
  ('United States', 'Stonewall Golf Club At Lake Manassas'),
  ('United States', 'Stonewall Golf Course'),
  ('United States', 'Stonewall Orchard Golf Club'),
  ('United States', 'Stonewater Country Club'),
  ('United States', 'Stonewater Golf Club'),
  ('United States', 'Stonewolf Golf Club'),
  ('United States', 'Stoney Creek Golf Club'),
  ('United States', 'Stoney Creek Golf Course'),
  ('United States', 'Stoney Links'),
  ('United States', 'Stoney Links Golf Course (closed)'),
  ('United States', 'Stoney Ridge Golf Course'),
  ('United States', 'Stoneybrook East Golf Course'),
  ('United States', 'Stoneybrook Golf Club'),
  ('United States', 'Stoneybrook Golf Country Club'),
  ('United States', 'Stoneybrook West Golf Course'),
  ('United States', 'Stonington Country Club'),
  ('United States', 'Stony Creek Golf Course'),
  ('United States', 'Stony Creek Metropark Golf Course'),
  ('United States', 'Stony Ford Golf Course'),
  ('United States', 'Stony Point Golf Course'),
  ('United States', 'Stonybrook Golf Club'),
  ('United States', 'Stonybrook Golf Course'),
  ('United States', 'Stonycreek Golf Club'),
  ('United States', 'Stonycroft Hills Club'),
  ('United States', 'Stop N Sock Golf Course'),
  ('United States', 'Storm King Golf Club'),
  ('United States', 'Storm Lake Golf Course'),
  ('United States', 'Stoughton Acres Golf Course'),
  ('United States', 'Stoughton Country Club'),
  ('United States', 'Stow North At Stow Acres Country Club'),
  ('United States', 'Stow South At Stow Acres Country Club'),
  ('United States', 'Stowaway Golf Course'),
  ('United States', 'Stowe Country Club'),
  ('United States', 'Stoweflake Mountain Resort Spa'),
  ('United States', 'Straight River Golf Course'),
  ('United States', 'Stratford Country Club'),
  ('United States', 'Stratton Golf Club'),
  ('United States', 'Strawberry Farms Golf Club'),
  ('United States', 'Strawberry Ridge Golf Course'),
  ('United States', 'Strawberry Valley Golf Club'),
  ('United States', 'Streamside Golf Course'),
  ('United States', 'Streamside Golf Course And Country Club'),
  ('United States', 'Streamsong Resort Black Course'),
  ('United States', 'Streamsong Resort Blue Course'),
  ('United States', 'Streamsong Resort Red Course'),
  ('United States', 'Streamsong Resort The Chain'),
  ('United States', 'Streamsong Resort The Gauntlet Putting Course'),
  ('United States', 'Streamwood Oaks Golf Club'),
  ('United States', 'Stripe Show Golf Club'),
  ('United States', 'Stroud Municipal Golf Course'),
  ('United States', 'Stryker Golf Course'),
  ('United States', 'Studebaker Park'),
  ('United States', 'Studio59 Golf - Libertyville Golf Course'),
  ('United States', 'Stumpy Lake Golf Course'),
  ('United States', 'Stuttgart Country Club'),
  ('United States', 'Suburban Golf Club'),
  ('United States', 'Sudden Valley Golf Country Club'),
  ('United States', 'Suffield Country Club'),
  ('United States', 'Suffield Springs Golf Club'),
  ('United States', 'Suffolk Golf Course'),
  ('United States', 'Sugar Bush Golf Course'),
  ('United States', 'Sugar Creek Country Club'),
  ('United States', 'Sugar Creek Golf Course'),
  ('United States', 'Sugar Creek Golf Tennis Club'),
  ('United States', 'Sugar Hill Golf Club'),
  ('United States', 'Sugar Hill Golf Course'),
  ('United States', 'Sugar Hills Golf Club'),
  ('United States', 'Sugar Mountain Golf Club'),
  ('United States', 'Sugar Oaks Golf Country Club'),
  ('United States', 'Sugar Ridge Golf Club'),
  ('United States', 'Sugar River Greens'),
  ('United States', 'Sugar Springs Golf Club'),
  ('United States', 'Sugar Valley Lakes Homes Association'),
  ('United States', 'Sugarbrooke Golf Course'),
  ('United States', 'Sugarbush Golf Club'),
  ('United States', 'Sugarbush Golf Course'),
  ('United States', 'Sugarland Country Club'),
  ('United States', 'Sugarloaf Golf Club'),
  ('United States', 'Sugarloaf Golf Club Resort'),
  ('United States', 'Sugarmill Woods Country Club Cypress Course'),
  ('United States', 'Sugarmill Woods Country Club Oak Course'),
  ('United States', 'Sugarmill Woods Country Club Pine Course'),
  ('United States', 'Sullivan County Golf Country Club'),
  ('United States', 'Sullivan Elks Country Club'),
  ('United States', 'Sullivans Par 3'),
  ('United States', 'Sulphur Hills Golf Course'),
  ('United States', 'Sultan’s Run Golf Club'),
  ('United States', 'Summer Breeze Par Three Golf Course'),
  ('United States', 'Summerfield Crossings Golf Club'),
  ('United States', 'Summerglen Golf Club'),
  ('United States', 'Summergrove Golf Club'),
  ('United States', 'Summerheights Golf Links South Course'),
  ('United States', 'Summerheights Golf Links West Course'),
  ('United States', 'Summertree Golf Club'),
  ('United States', 'Summertree Golf Course'),
  ('United States', 'Summerville Country Club'),
  ('United States', 'Summit At Cordillera Summit Course'),
  ('United States', 'Summit Chase Country Club'),
  ('United States', 'Summit Country Club'),
  ('United States', 'Summit Golf Course'),
  ('United States', 'Summit Hills Country Club'),
  ('United States', 'Summit Hills Golf Club'),
  ('United States', 'Summit Municipal Golf Course'),
  ('United States', 'Summit Springs Golf Course'),
  ('United States', 'Sumo Golf Village'),
  ('United States', 'Sumpwams Creek At E Donald Conroy Golf Course'),
  ('United States', 'Sumter Country Club'),
  ('United States', 'Sun City Country Club'),
  ('United States', 'Sun City Lakes Golf Club East Course'),
  ('United States', 'Sun City Lakes Golf Club West Course'),
  ('United States', 'Sun City South Golf Course'),
  ('United States', 'Sun Country Golf Resort'),
  ('United States', 'Sun Hills Golf Course'),
  ('United States', 'Sun Lakes Country Club'),
  ('United States', 'Sun Lakes Country Club Executive Course'),
  ('United States', 'Sun Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Sun River Golf Club'),
  ('United States', 'Sun Valley Golf Course'),
  ('United States', 'Sun Village Golf Course'),
  ('United States', 'Sun Willows Golf Course'),
  ('United States', 'Sunbird Golf Resort'),
  ('United States', 'Sunbrook Golf Club Black Rock The Point Course'),
  ('United States', 'Sunbrook Golf Club The Point Woodbridge Course'),
  ('United States', 'Sunbrook Golf Club Woodbridge Black Rock Course'),
  ('United States', 'Suncadia Resort Prospector Course'),
  ('United States', 'Suncadia Resort Rope Rider Course'),
  ('United States', 'Suncoast Golf Center'),
  ('United States', 'Suncrest Country Club'),
  ('United States', 'Suncrest Golf Course'),
  ('United States', 'Sundale Country Club'),
  ('United States', 'Sundance'),
  ('United States', 'Sundance Golf Banquet Bowl'),
  ('United States', 'Sundance Golf Club'),
  ('United States', 'Sundance Golf Course'),
  ('United States', 'Sunday River Golf Club'),
  ('United States', 'Sundown Golf Country Club'),
  ('United States', 'Suneagles Golf Club'),
  ('United States', 'Sunflower Hills Golf Course'),
  ('United States', 'Sunken Gardens Golf Course'),
  ('United States', 'Sunkist Country Club'),
  ('United States', 'Sunland Golf Country Club'),
  ('United States', 'Sunland Village East Golf Course'),
  ('United States', 'Sunland Village Golf Course'),
  ('United States', 'Sunnehanna Country Club'),
  ('United States', 'Sunnidell Golf Course'),
  ('United States', 'Sunningdale Country Club'),
  ('United States', 'Sunny Brae Golf & Country Club'),
  ('United States', 'Sunny Hill Golf Course'),
  ('United States', 'Sunny Hill Resort Golf Course'),
  ('United States', 'Sunny Hills Golf Club'),
  ('United States', 'Sunnybrook Country Club'),
  ('United States', 'Sunnybrook Golf Club'),
  ('United States', 'Sunnycrest Golf Course'),
  ('United States', 'Sunnylands Golf Course'),
  ('United States', 'Sunnyside Country Club'),
  ('United States', 'Sunnyside Golf Country Club'),
  ('United States', 'Sunnyside Par 3 Golf Course'),
  ('United States', 'Sunnyvale Municipal Golf Course'),
  ('United States', 'Sunridge Canyon Golf Club'),
  ('United States', 'Sunridge Golf Club'),
  ('United States', 'Sunrise Canyon At Spanish Trail Country Club'),
  ('United States', 'Sunrise Country Club'),
  ('United States', 'Sunrise Course At Country Club At Mirasol'),
  ('United States', 'Sunrise Golf Course'),
  ('United States', 'Sunrise Lakes Phase 3 Golf Course'),
  ('United States', 'Sunrise Lakes Phase Iv Golf Course'),
  ('United States', 'Sunrise Ridge Golf Course'),
  ('United States', 'Sunrise Vista Golf Course'),
  ('United States', 'Sunserra Golf At Crescent Bar'),
  ('United States', 'Sunset At Lancaster Country Club'),
  ('United States', 'Sunset Country Club'),
  ('United States', 'Sunset Course At Country Club At Mirasol'),
  ('United States', 'Sunset Golf Course'),
  ('United States', 'Sunset Grove Country Club'),
  ('United States', 'Sunset Hill Golf Club'),
  ('United States', 'Sunset Hill Golf Course'),
  ('United States', 'Sunset Hills Country Club'),
  ('United States', 'Sunset Hills Golf Club'),
  ('United States', 'Sunset Hills Golf Course'),
  ('United States', 'Sunset Hills Golf Course Old Course'),
  ('United States', 'Sunset Hills Golf Course Par 3 Course'),
  ('United States', 'Sunset Par 3'),
  ('United States', 'Sunset Ridge Country Club'),
  ('United States', 'Sunset Ridge Golf Club'),
  ('United States', 'Sunset Ridge Golf Links'),
  ('United States', 'Sunset Ridge Golf Links Par 3 Course'),
  ('United States', 'Sunset Valley Country Club'),
  ('United States', 'Sunset Valley Golf Course'),
  ('United States', 'Sunset View Golf Course'),
  ('United States', 'Sunshine Woods Golf Club'),
  ('United States', 'Suntides Golf Course'),
  ('United States', 'Superior Country Club'),
  ('United States', 'Superior National at Lutsen-Golf Course'),
  ('United States', 'Superstition Course At Sunland Springs Village'),
  ('United States', 'Superstition Mountain Golf Country Club Lost Gold Course'),
  ('United States', 'Superstition Mountain Golf Country Club Prospector Course'),
  ('United States', 'Superstition Springs Golf Club'),
  ('United States', 'Suppesville Golf Course'),
  ('United States', 'Surf Golf Beach Club'),
  ('United States', 'Surfside Golf Course'),
  ('United States', 'Surrey Hills Country Club'),
  ('United States', 'Susquehanna Valley Country Club'),
  ('United States', 'Sutton Bay Golf'),
  ('United States', 'Sutton Creek Golf Course'),
  ('United States', 'Suwannee Country Club'),
  ('United States', 'Swainsboro Golf Club'),
  ('United States', 'Swallows Nest Country Club'),
  ('United States', 'Swamp Fox Golf Club'),
  ('United States', 'Swan Hills Golf Course'),
  ('United States', 'Swan Lake Country Club'),
  ('United States', 'Swan Lake Golf Club'),
  ('United States', 'Swan Lake Golf Country Club'),
  ('United States', 'Swan Lake Golf Courses'),
  ('United States', 'Swan Lakes Golf Course'),
  ('United States', 'Swan Point Yacht Country Club'),
  ('United States', 'Swan Valley Golf Course'),
  ('United States', 'Swanhills'),
  ('United States', 'Swannanoa Country Club'),
  ('United States', 'Swansea Clinton Hills Conservation Park'),
  ('United States', 'Swansea Country Club'),
  ('United States', 'Swansea Country Club Par 3 Course'),
  ('United States', 'Swanson Meadows Golf Course'),
  ('United States', 'Swartz Creek Golf Course'),
  ('United States', 'Sweet Water Golf Course'),
  ('United States', 'Sweetbriar Golf & Pro Shop'),
  ('United States', 'Sweetens Cove Golf Club'),
  ('United States', 'Sweetgrass Golf Club'),
  ('United States', 'Sweetgum At The Villages Executive Golf Trail'),
  ('United States', 'Sweetwater Country Club'),
  ('United States', 'Sweetwater Golf Country Club'),
  ('United States', 'Sweetwater Golf Tennis Club'),
  ('United States', 'Swenson Park Golf Course Magnolia Executive Par 3'),
  ('United States', 'Swenson Park Golf Course The Oak Course'),
  ('United States', 'Swinomish Golf Links'),
  ('United States', 'Swiss Fairways Golf Course'),
  ('United States', 'Switzerland of Ohio Golf Course'),
  ('United States', 'Swope Memorial Golf Course'),
  ('United States', 'Sycamore Country Club'),
  ('United States', 'Sycamore Creek County Club'),
  ('United States', 'Sycamore Creek Golf Course'),
  ('United States', 'Sycamore Golf Club'),
  ('United States', 'Sycamore Hills Country Club'),
  ('United States', 'Sycamore Hills Golf Club'),
  ('United States', 'Sycamore Ridge')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Sycamore Ridge Golf Club'),
  ('United States', 'Sycamore Springs'),
  ('United States', 'Sycamore Springs Golf Course'),
  ('United States', 'Sycamore Valley Golf Course'),
  ('United States', 'Sydney R. Marovitz Golf Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club North South Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club Par 3 Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club South West Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club West North Course'),
  ('United States', 'Sylvan Glen Golf Course'),
  ('United States', 'Sylvan Heights Golf Course'),
  ('United States', 'Sylvan Hills Golf Course'),
  ('United States', 'Sylvania Golf Club'),
  ('United States', 'Syracuse Country Club'),
  ('United States', 'TPC Deere Run'),
  ('United States', 'TPC Michigan'),
  ('United States', 'TPC Twin Cities'),
  ('United States', 'TPC Wisconsin'),
  ('United States', 'Taberna Country Club'),
  ('United States', 'Table Mountain Golf Club'),
  ('United States', 'Tacoma Country Golf Club'),
  ('United States', 'Taconic Golf Club'),
  ('United States', 'Tagalong Golf & Resort'),
  ('United States', 'Tahlequah City Golf Course'),
  ('United States', 'Tahoe City Golf Course'),
  ('United States', 'Tahoe Paradise Golf Course'),
  ('United States', 'Tahoma Valley Golf Country Club'),
  ('United States', 'Talamore Country Club'),
  ('United States', 'Talamore Golf Resort'),
  ('United States', 'Talbot Trail Golf Club'),
  ('United States', 'Talega Golf Club'),
  ('United States', 'Talis Park Golf Club'),
  ('United States', 'Talisker Golf At Tuhaye Golf Course'),
  ('United States', 'Talking Rock Golf Club'),
  ('United States', 'Talking Stick Golf Club Oodham Course'),
  ('United States', 'Talking Stick Golf Club Piipaash Course'),
  ('United States', 'Tall Pines Players Club'),
  ('United States', 'Tall Timber Golf Course'),
  ('United States', 'Tallahatchie Country Club'),
  ('United States', 'Talley Ho Course At Glenview Champions Country Club'),
  ('United States', 'Tallgrass Country Club'),
  ('United States', 'Tallulah Country Club'),
  ('United States', 'Tallwood Country Club'),
  ('United States', 'Tally Mountain Golf Course'),
  ('United States', 'Talon At Grayhawk Golf Club'),
  ('United States', 'Talons of Tuscany Golf Club'),
  ('United States', 'Talonscove At Saratoga Springs'),
  ('United States', 'Tam O''Shanter Country Club'),
  ('United States', 'Tam O''Shanter Golf Course'),
  ('United States', 'Tam Oshanter Golf Country Club'),
  ('United States', 'Tam Oshanter Of Pennsylvania'),
  ('United States', 'Tama Toledo Country Club'),
  ('United States', 'Tamahka Trails'),
  ('United States', 'Tamaqua Golf Course'),
  ('United States', 'Tamarac Golf Course'),
  ('United States', 'Tamarack Country Club'),
  ('United States', 'Tamarack Golf Club'),
  ('United States', 'Tamarack Golf Course'),
  ('United States', 'Tamarack Resort Osprey Meadows Golf Course'),
  ('United States', 'Tamarisk Country Club'),
  ('United States', 'Tamarisk Golf Course'),
  ('United States', 'Tamaron Country Club'),
  ('United States', 'Tamaya Cheena Course At Santa Ana Golf Club'),
  ('United States', 'Tamaya Star Course At Santa Ana Golf Club'),
  ('United States', 'Tameka Woods Golf Course'),
  ('United States', 'Tamer Win Golf & Country Club'),
  ('United States', 'Tampa Bay Golf Country Club'),
  ('United States', 'Tampa Bay Golf Country Club Executive Course'),
  ('United States', 'Tampa Palms Golf Country Club'),
  ('United States', 'Tan Tara Golf Club'),
  ('United States', 'Tanglewood Club'),
  ('United States', 'Tanglewood Golf And Country Club'),
  ('United States', 'Tanglewood Golf Club'),
  ('United States', 'Tanglewood Golf Club Championship Course'),
  ('United States', 'Tanglewood Golf Club Par 3 Course'),
  ('United States', 'Tanglewood Golf Club Reynolds Course'),
  ('United States', 'Tanglewood Golf Course'),
  ('United States', 'Tanglewood Greens'),
  ('United States', 'Tanglewood Manor Golf Club'),
  ('United States', 'Tanglewood Marsh Golf Course'),
  ('United States', 'Tanglewood Resort Hotel And Conference Center'),
  ('United States', 'Tanglewood Shores Golf Country Club'),
  ('United States', 'Tannenbaum Golf Club'),
  ('United States', 'Tannenhauf Golf Club'),
  ('United States', 'Tanner Valley Golf 18 Hole'),
  ('United States', 'Tanner''s Brook'),
  ('United States', 'Tanoan Country Club Acoma Course'),
  ('United States', 'Tanoan Country Club Sandia Course'),
  ('United States', 'Tanoan Country Club Zia Course'),
  ('United States', 'Taos Country Club'),
  ('United States', 'Tapawingo National Golf Club'),
  ('United States', 'Tapps Island Golf Course'),
  ('United States', 'Tara Golf Club At Savannah Lakes'),
  ('United States', 'Tara Golf Country Club'),
  ('United States', 'Tara Greens Golf Center Pitch N Putt'),
  ('United States', 'Tara Hills Country Club'),
  ('United States', 'Tara Hills Golf Course'),
  ('United States', 'Targhee Village Golf Course'),
  ('United States', 'Tarkio Golf Club'),
  ('United States', 'Tarpon Boil At The Villages Executive Golf Trail'),
  ('United States', 'Tarpon Springs Golf Course'),
  ('United States', 'Tarpon Woods Golf Club'),
  ('United States', 'Tarratine Golf Club'),
  ('United States', 'Tarry Brae Golf Course'),
  ('United States', 'Tashua Knolls Golf Club Tashua Glen'),
  ('United States', 'Tashua Knolls Golf Club Tashua Knolls'),
  ('United States', 'Tater Hill Country Club'),
  ('United States', 'Tatnuck Country Club'),
  ('United States', 'Tatum Ranch Golf Club'),
  ('United States', 'Tatum Ridge Golf Links'),
  ('United States', 'Tavistock Country Club'),
  ('United States', 'Tawas Creek Golf Club'),
  ('United States', 'Taylor Meadows Golf Course'),
  ('United States', 'Taylors Creek Golf Course'),
  ('United States', 'Taylors Par 3'),
  ('United States', 'Tazewell County Country Club'),
  ('United States', 'Tchefuncta Country Club'),
  ('United States', 'Teal Bend Golf Club'),
  ('United States', 'Tecolote Canyon Golf Course'),
  ('United States', 'Tecumseh Golf Club'),
  ('United States', 'Ted Makalena Golf Course'),
  ('United States', 'Tedesco Country Club'),
  ('United States', 'Tee Hi Club'),
  ('United States', 'Tee Time Golf Cafe'),
  ('United States', 'Tee Time Golf Complex'),
  ('United States', 'Tee-Hi Golf Course'),
  ('United States', 'Teetering Rocks Executive Links'),
  ('United States', 'Tega Cay Golf Club The Cove'),
  ('United States', 'Tega Cay Golf Club The Grande View'),
  ('United States', 'Tega Cay Golf Club The Pines'),
  ('United States', 'Tehama Golf Club'),
  ('United States', 'Tekoa Country Club'),
  ('United States', 'Tekoa Golf Course'),
  ('United States', 'Teleli Golf Club'),
  ('United States', 'Telemark Golf Course'),
  ('United States', 'Telluride Golf Club'),
  ('United States', 'Temple Terrace Golf Country Club'),
  ('United States', 'Templewood Golf Course'),
  ('United States', 'Tennessee Valley Country Club'),
  ('United States', 'Tepetonka Golf Club'),
  ('United States', 'Tequesta Country Club'),
  ('United States', 'Terra Ceia Bay Golf Tennis Club'),
  ('United States', 'Terra Greens Golf Course'),
  ('United States', 'Terra Verde Golf Course'),
  ('United States', 'Terrace At Saint Clair Country Club'),
  ('United States', 'Terrace Bluff Golf Course'),
  ('United States', 'Terrace Hill Golf Club'),
  ('United States', 'Terrace Hills Golf Course'),
  ('United States', 'Terrace Lakes Resort'),
  ('United States', 'Terrace Park Country Club'),
  ('United States', 'Terrace View Golf Course'),
  ('United States', 'Terradyne Country Club'),
  ('United States', 'Terrapin Hills Country Club'),
  ('United States', 'Terraverde Country Club'),
  ('United States', 'Terravita Golf Club'),
  ('United States', 'Territory Golf Club'),
  ('United States', 'Terry Park Golf Course'),
  ('United States', 'Teton Lakes Golf Course Middle Fork'),
  ('United States', 'Teton Lakes Golf Course North Fork'),
  ('United States', 'Teton Lakes Golf Course South Fork'),
  ('United States', 'Teton Pines Country Club Resort'),
  ('United States', 'Teton Reserve'),
  ('United States', 'Teugega Country Club'),
  ('United States', 'Tewksbury Country Club'),
  ('United States', 'Tex Consolver Municipal Golf Course'),
  ('United States', 'Texarkana Country Club'),
  ('United States', 'Texarkana Golf Ranch'),
  ('United States', 'Thal Acres Golf Course'),
  ('United States', 'Thal Acres Links Lanes'),
  ('United States', 'Thanksgiving Point Golf Club'),
  ('United States', 'Thatcher Golf Course'),
  ('United States', 'Thayer Country Club'),
  ('United States', 'The 1912 Club'),
  ('United States', 'The 500 Club'),
  ('United States', 'The 500 Club Futures Course'),
  ('United States', 'The Abington Club'),
  ('United States', 'The Alpine'),
  ('United States', 'The Amelia River Club'),
  ('United States', 'The Apawamis Club'),
  ('United States', 'The Aquidneck Club'),
  ('United States', 'The Arboretum Club'),
  ('United States', 'The Architects Golf Club'),
  ('United States', 'The Arizona Country Club'),
  ('United States', 'The Arnold Palmer Signature Course At Stonewall Resort'),
  ('United States', 'The Ashford Short Course'),
  ('United States', 'The Atchafalaya At Idlewild'),
  ('United States', 'The Azalea At Pinewild Country Club'),
  ('United States', 'The Back Nine Club'),
  ('United States', 'The Barn Golf Club'),
  ('United States', 'The Bath Golf Club'),
  ('United States', 'The Baths Of Blackwolf Run'),
  ('United States', 'The Bay Club At Mattapoisett'),
  ('United States', 'The Bayonet At Bayonet Black Horse Golf Course'),
  ('United States', 'The Bear Golf Course'),
  ('United States', 'The Bear S Club Par 3 Course'),
  ('United States', 'The Bears Club'),
  ('United States', 'The Beaufort Club'),
  ('United States', 'The Biltmore Golf Course'),
  ('United States', 'The Blandford Golf Tennis Club'),
  ('United States', 'The Bluff Golf Links'),
  ('United States', 'The Bluffs At Coffee Mill'),
  ('United States', 'The Bluffs At The National Golf Club Of Kansas City'),
  ('United States', 'The Bluffs On Thompson Creek'),
  ('United States', 'The Bobcat At Plantation Golf Country Club'),
  ('United States', 'The Boca Raton'),
  ('United States', 'The Bog'),
  ('United States', 'The Bolivar Golf Club'),
  ('United States', 'The Bourne'),
  ('United States', 'The Brassie Golf Club'),
  ('United States', 'The Breakers Ocean Course'),
  ('United States', 'The Breakers Rees Jones Course'),
  ('United States', 'The Bridgehampton Club'),
  ('United States', 'The Bridges'),
  ('United States', 'The Bridges At Beresford'),
  ('United States', 'The Bridges At Rancho Santa Fe'),
  ('United States', 'The Bridges At Springtree Golf Club'),
  ('United States', 'The Bridges Golf Club'),
  ('United States', 'The Bridges Golf Club At Hollywood Casino'),
  ('United States', 'The Bridges Golf Country Club'),
  ('United States', 'The Brookside Club'),
  ('United States', 'The Bucks Club'),
  ('United States', 'The Bull at Pinehurst Farms'),
  ('United States', 'The Calibogue The Haig At Haig Point Club'),
  ('United States', 'The Canyons At Bighorn Golf Club'),
  ('United States', 'The Canyons At Blackjack Ridge'),
  ('United States', 'The Cape Club'),
  ('United States', 'The Cape Club Of Palm City'),
  ('United States', 'The Cape Club Of Sharon'),
  ('United States', 'The Captain''s Club at Woodfield'),
  ('United States', 'The Cardinal By Pete Dye'),
  ('United States', 'The Cascade At Gold Mountain Golf Course'),
  ('United States', 'The Cedars At Dungeness'),
  ('United States', 'The Challenge At Cypress Hills'),
  ('United States', 'The Challenge Golf Club'),
  ('United States', 'The Champion Turf Club At St James'),
  ('United States', 'The Champions Club At Summerfield'),
  ('United States', 'The Chief Golf Course'),
  ('United States', 'The Chimneys Golf Course'),
  ('United States', 'The Classic'),
  ('United States', 'The Classic Club'),
  ('United States', 'The Classic at Madden''s'),
  ('United States', 'The Classics Country Club'),
  ('United States', 'The Cleghorn Club'),
  ('United States', 'The Cliffs At Glassy Golf Course'),
  ('United States', 'The Cliffs At Keowee Falls Golf Course'),
  ('United States', 'The Cliffs At Keowee Springs'),
  ('United States', 'The Cliffs At Keowee Vineyards'),
  ('United States', 'The Cliffs At Mountain Park Golf Course'),
  ('United States', 'The Cliffs At Walnut Cove'),
  ('United States', 'The Cliffs Valley Golf Course'),
  ('United States', 'The Club At Arrowcreek Challenge Course'),
  ('United States', 'The Club At Arrowcreek Legend Course'),
  ('United States', 'The Club At Black Rock 18 Hole Putting Course'),
  ('United States', 'The Club At Black Rock Jim Engh Course'),
  ('United States', 'The Club At Brookstone'),
  ('United States', 'The Club At Clear Creek'),
  ('United States', 'The Club At Crazy Horse Ranch'),
  ('United States', 'The Club At Crested Butte'),
  ('United States', 'The Club At Discovery Harbour'),
  ('United States', 'The Club At Eaglebrooke'),
  ('United States', 'The Club At Emerald Hills'),
  ('United States', 'The Club At Flying Horse'),
  ('United States', 'The Club At Flying Horse North Course'),
  ('United States', 'The Club At Forest Ridge'),
  ('United States', 'The Club At Gateway'),
  ('United States', 'The Club At Grandezza'),
  ('United States', 'The Club At Hokulia'),
  ('United States', 'The Club At Ibis The Heritage Course'),
  ('United States', 'The Club At Ibis The Legend Course'),
  ('United States', 'The Club At Ibis The Tradition Course'),
  ('United States', 'The Club At Irish Creek'),
  ('United States', 'The Club At Kingsmill Woods Course'),
  ('United States', 'The Club At Lake Sinclair'),
  ('United States', 'The Club At Longview'),
  ('United States', 'The Club At Mediterra North Course'),
  ('United States', 'The Club At Mediterra South Course'),
  ('United States', 'The Club At Morningside'),
  ('United States', 'The Club At Nevillewood'),
  ('United States', 'The Club At New Seabury Dunes Course'),
  ('United States', 'The Club At New Seabury Ocean Course'),
  ('United States', 'The Club At Old Hawthorne'),
  ('United States', 'The Club At Olde Cypress'),
  ('United States', 'The Club At Osprey Cove'),
  ('United States', 'The Club At Pelican Bay North Course'),
  ('United States', 'The Club At Pine Forest'),
  ('United States', 'The Club At Pradera'),
  ('United States', 'The Club At Prescott Lakes'),
  ('United States', 'The Club At Ravenna'),
  ('United States', 'The Club At Renaissance'),
  ('United States', 'The Club At River Forest'),
  ('United States', 'The Club At River Wilderness'),
  ('United States', 'The Club At Savannah Harbor'),
  ('United States', 'The Club At Savannah Quarters'),
  ('United States', 'The Club At Seven Canyons'),
  ('United States', 'The Club At Shadow Lakes'),
  ('United States', 'The Club At Shannondell'),
  ('United States', 'The Club At Shepard Hills'),
  ('United States', 'The Club At Silver Lake'),
  ('United States', 'The Club At Snoqualmie Ridge'),
  ('United States', 'The Club At Spanish Peaks'),
  ('United States', 'The Club At Spurwing Challenge Course'),
  ('United States', 'The Club At Spurwing Championship Course'),
  ('United States', 'The Club At Starr Pass Gambler Pioneer'),
  ('United States', 'The Club At Starr Pass Palmer Gambler'),
  ('United States', 'The Club At Starr Pass Pioneer Palmer'),
  ('United States', 'The Club At Stoneridge'),
  ('United States', 'The Club At Sunrise'),
  ('United States', 'The Club At The Highlands'),
  ('United States', 'The Club At The Strand Preserve Savannah Course'),
  ('United States', 'The Club At The Strand Sabal Preserve Course'),
  ('United States', 'The Club At The Strand Savannah Sabal Course'),
  ('United States', 'The Club At Twin Lakes'),
  ('United States', 'The Club At Venetian Bay'),
  ('United States', 'The Club At Viniterra'),
  ('United States', 'The Club At Westminster'),
  ('United States', 'The Club Of Staunton'),
  ('United States', 'The Club Pelican Bay Club Bay Course'),
  ('United States', 'The Club Pelican Bay Club Pelican Course'),
  ('United States', 'The Club Pelican Bay Pelican Bay Course'),
  ('United States', 'The Club Renaissance'),
  ('United States', 'The Club at Lac La Belle'),
  ('United States', 'The Club at Strawberry Creek'),
  ('United States', 'The Club at Tartan Fields'),
  ('United States', 'The Clubs At Arrowhead'),
  ('United States', 'The Clubs At Arrowhead Legend Course'),
  ('United States', 'The College Golf Course At Delhi'),
  ('United States', 'The Colony Golf Country Club'),
  ('United States', 'The Columbia Golf And Country Club'),
  ('United States', 'The Concession Golf Club'),
  ('United States', 'The Concession Golf Club The Gimme Course'),
  ('United States', 'The Country Club'),
  ('United States', 'The Country Club At Dc Ranch'),
  ('United States', 'The Country Club At Lake City'),
  ('United States', 'The Country Club At Soboba Springs'),
  ('United States', 'The Country Club At The Golden Nugget'),
  ('United States', 'The Country Club At Woodmoor'),
  ('United States', 'The Country Club Of Arkansas'),
  ('United States', 'The Country Club Of Colorado At Cheyenne Mountain Resort'),
  ('United States', 'The Country Club Of Greenfield'),
  ('United States', 'The Country Club Of Lexington'),
  ('United States', 'The Country Club Of Louisiana'),
  ('United States', 'The Country Club Of Meadville'),
  ('United States', 'The Country Club Of Mount Dora'),
  ('United States', 'The Country Club Of North Carolina Cardinal Course'),
  ('United States', 'The Country Club Of North Carolina Dogwood Course'),
  ('United States', 'The Country Club Of Orlando'),
  ('United States', 'The Country Club Of Oxford'),
  ('United States', 'The Country Club Of Rancho Bernardo'),
  ('United States', 'The Country Club Of Sapphire Valley'),
  ('United States', 'The Country Club Of South Carolina'),
  ('United States', 'The Country Club Of Spartanburg'),
  ('United States', 'The Country Club Of Troy'),
  ('United States', 'The Country Club Of Virginia James River Course'),
  ('United States', 'The Country Club Of Virginia Tuckahoe Creek Course'),
  ('United States', 'The Country Club Of Virginia Westhampton Course'),
  ('United States', 'The Country Club at Muirfield Village'),
  ('United States', 'The Country Club of Indianapolis'),
  ('United States', 'The Country Club of Saint Albans'),
  ('United States', 'The County Club of Hudson'),
  ('United States', 'The Course At Eagle Mountain'),
  ('United States', 'The Course At Petteys Park'),
  ('United States', 'The Course At River Oaks'),
  ('United States', 'The Course At Wente Vineyards'),
  ('United States', 'The Cove Of Rotonda Golf Center'),
  ('United States', 'The Coves At Round Mountain'),
  ('United States', 'The Creek'),
  ('United States', 'The Creek At Hard Labor State Park'),
  ('United States', 'The Creek At Qualchan Golf Course'),
  ('United States', 'The Creek Golf Club'),
  ('United States', 'The Creeks Golf Rv Resort'),
  ('United States', 'The Crosby Club'),
  ('United States', 'The Crossings'),
  ('United States', 'The Crossings At Carlsbad'),
  ('United States', 'The Crossings At Montevideo'),
  ('United States', 'The Crossings Golf Club'),
  ('United States', 'The Crossings Golf Course'),
  ('United States', 'The Crown Golf Club'),
  ('United States', 'The Currituck Club'),
  ('United States', 'The Cypress At Palm Beach Polo Country Club'),
  ('United States', 'The Dalles Golf Country Club'),
  ('United States', 'The Den at Fox Creek'),
  ('United States', 'The Derby Golf Country Club'),
  ('United States', 'The Divide Golf Club'),
  ('United States', 'The Dogwoods Golf Course At Hugh White State Park'),
  ('United States', 'The Dominion Club'),
  ('United States', 'The Dream GC'),
  ('United States', 'The Duke At Rancho El Dorado'),
  ('United States', 'The Dunes At Maui Lani Golf Course'),
  ('United States', 'The Dunes Club'),
  ('United States', 'The Dunes Golf Beach Club'),
  ('United States', 'The Dunes Golf Tennis Club'),
  ('United States', 'The Dye Preserve Golf Club'),
  ('United States', 'The Eagles Golf Club Forest'),
  ('United States', 'The Eagles Golf Club Lakes'),
  ('United States', 'The East West At Upper Montclair Country Club'),
  ('United States', 'The Eastwood Golf Course & Restaurant'),
  ('United States', 'The Eighteen Hole At Centre Hills Country Club'),
  ('United States', 'The Elks Golf Course At Sandpoint'),
  ('United States', 'The Elms Golf Club'),
  ('United States', 'The Emerald Golf Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'The Emerald Golf Course'),
  ('United States', 'The Estancia Club'),
  ('United States', 'The Evans at Canal Shores'),
  ('United States', 'The Executive At Fore Lakes Golf Course'),
  ('United States', 'The Executive At Victor Hills Golf Club'),
  ('United States', 'The Executive Course At Lakehouse'),
  ('United States', 'The Fairways'),
  ('United States', 'The Fairways At Prestonwood Country Club'),
  ('United States', 'The Fairways at Twin Lakes'),
  ('United States', 'The Fall Line East Course'),
  ('United States', 'The Fall Line Short Course'),
  ('United States', 'The Fall Line West Course'),
  ('United States', 'The Falls Club Of The Palm Beaches'),
  ('United States', 'The Falls Golf Club'),
  ('United States', 'The Falls at Barber Creek'),
  ('United States', 'The Farms Country Club'),
  ('United States', 'The Farms Golf Club'),
  ('United States', 'The Federal Club'),
  ('United States', 'The Fields Golf Club'),
  ('United States', 'The Fields Golf Course'),
  ('United States', 'The First Tee Of Central Arkansas Chairmans Course'),
  ('United States', 'The First Tee Of Central Arkansas Honors Course'),
  ('United States', 'The First Tee Of Fort Smith The Jack Stephens Youth Golf Academy'),
  ('United States', 'The First Tee Of Greater Richmond'),
  ('United States', 'The First Tee Of Hampton Roads'),
  ('United States', 'The First Tee Of Monterey County'),
  ('United States', 'The First Tee Of North Florida Brentwood Golf Course'),
  ('United States', 'The First Tee Of Phoenix'),
  ('United States', 'The First Tee Of The Lowcountry Golf Course'),
  ('United States', 'The First Tee Of Troup County'),
  ('United States', 'The First Tee Syracuse Golf Complex At Butternut Creek'),
  ('United States', 'The First Tee Youth Golf Course'),
  ('United States', 'The Florida Club'),
  ('United States', 'The Floridian'),
  ('United States', 'The Floridian The Harmon Par 3 Course'),
  ('United States', 'The Ford Field River Club'),
  ('United States', 'The Fort Golf Course'),
  ('United States', 'The Fortress Golf Course'),
  ('United States', 'The Founders Golf Club'),
  ('United States', 'The Fountaingrove Club'),
  ('United States', 'The Four Seasons Island Resort'),
  ('United States', 'The Fox Golf Club'),
  ('United States', 'The Fox Valley Club'),
  ('United States', 'The Frog At The Georgian'),
  ('United States', 'The Gailes'),
  ('United States', 'The Gauntlet Golf Club'),
  ('United States', 'The General'),
  ('United States', 'The Georgia Club Chancellors Black Silver Course'),
  ('United States', 'The Georgia Club Chancellors Red Black Course'),
  ('United States', 'The Georgia Club Chancellors Red Silver Course'),
  ('United States', 'The Glacier Golf Course & The Prairie Glen Golf Course'),
  ('United States', 'The Glades Resort'),
  ('United States', 'The Glen Club'),
  ('United States', 'The Glen Golf Park'),
  ('United States', 'The Golden Bear Club At Keene S Point'),
  ('United States', 'The Golf Center At Balloon Fiesta Park'),
  ('United States', 'The Golf Center At Palm Desert'),
  ('United States', 'The Golf Center Par 3 Course'),
  ('United States', 'The Golf Club'),
  ('United States', 'The Golf Club At Bear Dance'),
  ('United States', 'The Golf Club At Blue Heron Hills'),
  ('United States', 'The Golf Club At Bluewater Bay'),
  ('United States', 'The Golf Club At Bradshaw Farm Blue Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm Red Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm White Nine'),
  ('United States', 'The Golf Club At Briars Creek'),
  ('United States', 'The Golf Club At Chaparral Pines'),
  ('United States', 'The Golf Club At Chapel Ridge'),
  ('United States', 'The Golf Club At Cimarron Trails'),
  ('United States', 'The Golf Club At Copper Valley'),
  ('United States', 'The Golf Club At Creighton Farms'),
  ('United States', 'The Golf Club At Devils Tower'),
  ('United States', 'The Golf Club At Dove Mountain Saguaro Tortolita'),
  ('United States', 'The Golf Club At Dove Mountain Tortolita Wild Burro'),
  ('United States', 'The Golf Club At Dove Mountain Wild Burro Saguaro'),
  ('United States', 'The Golf Club At Eagle Creek'),
  ('United States', 'The Golf Club At Equinox'),
  ('United States', 'The Golf Club At Fiddlers Creek'),
  ('United States', 'The Golf Club At Grays Crossing'),
  ('United States', 'The Golf Club At Hawks Prairie The Links'),
  ('United States', 'The Golf Club At Hawks Prairie The Woodlands'),
  ('United States', 'The Golf Club At Hilton Head Lakes'),
  ('United States', 'The Golf Club At Indigo Run'),
  ('United States', 'The Golf Club At Mattaponi Springs'),
  ('United States', 'The Golf Club At Middle Bay'),
  ('United States', 'The Golf Club At Newcastle China Creek Course'),
  ('United States', 'The Golf Club At Newcastle Coal Creek Course'),
  ('United States', 'The Golf Club At North Hampton'),
  ('United States', 'The Golf Club At Oxford Greens'),
  ('United States', 'The Golf Club At Rainmakers'),
  ('United States', 'The Golf Club At Rancho California'),
  ('United States', 'The Golf Club At Redlands Mesa'),
  ('United States', 'The Golf Club At Redmond Ridge'),
  ('United States', 'The Golf Club At Sacconnesset'),
  ('United States', 'The Golf Club At Southport'),
  ('United States', 'The Golf Club At Southwind'),
  ('United States', 'The Golf Club At Star Fort'),
  ('United States', 'The Golf Club At Summerbrooke'),
  ('United States', 'The Golf Club At The Highlands'),
  ('United States', 'The Golf Club At Wyndhurst Manor Club'),
  ('United States', 'The Golf Club Of Bristol'),
  ('United States', 'The Golf Club Of California'),
  ('United States', 'The Golf Club Of Cypress Creek'),
  ('United States', 'The Golf Club Of Fernley'),
  ('United States', 'The Golf Club Of Jupiter'),
  ('United States', 'The Golf Club Of New England'),
  ('United States', 'The Golf Club Of Oklahoma'),
  ('United States', 'The Golf Club Of Purchase'),
  ('United States', 'The Golf Club Of Quincy'),
  ('United States', 'The Golf Club Tierra Oaks'),
  ('United States', 'The Golf Club at Cedar Creek'),
  ('United States', 'The Golf Club at Eagle Pointe'),
  ('United States', 'The Golf Club at Little Turtle'),
  ('United States', 'The Golf Club at Mt. Brighton'),
  ('United States', 'The Golf Club at Stonelick Hills'),
  ('United States', 'The Golf Club at Table Creek'),
  ('United States', 'The Golf Club at Yankee Trace'),
  ('United States', 'The Golf Club of Bucyrus'),
  ('United States', 'The Golf Course at Branch River'),
  ('United States', 'The Golf Course at Camelot'),
  ('United States', 'The Golf Depot'),
  ('United States', 'The Golf Dome'),
  ('United States', 'The Golf Garden Of Destin'),
  ('United States', 'The Golf Lodge At The Quarry'),
  ('United States', 'The Golf Preserve'),
  ('United States', 'The Golf Ranch'),
  ('United States', 'The Golf Village'),
  ('United States', 'The Grand Bear Golf Course'),
  ('United States', 'The Grand Golf Club'),
  ('United States', 'The Greens At Beaumont'),
  ('United States', 'The Greens At Churchill S'),
  ('United States', 'The Greens At Deerfield'),
  ('United States', 'The Greens At Half Hollow'),
  ('United States', 'The Greens At Hamilton Run'),
  ('United States', 'The Greens At North Hills'),
  ('United States', 'The Greens At Tanyard'),
  ('United States', 'The Greens Burns Flat Golf Course'),
  ('United States', 'The Greens Golf Course'),
  ('United States', 'The Greens Of Altus Golf Course'),
  ('United States', 'The Greens Of Greenville'),
  ('United States', 'The Greens On Blossom Way Golf Country Club'),
  ('United States', 'The Grizzly Golf and Social Lodge'),
  ('United States', 'The Grove Country Club'),
  ('United States', 'The Groves Golf And Country Club'),
  ('United States', 'The Groves Golf Course'),
  ('United States', 'The Habitat Golf Course'),
  ('United States', 'The Hamptons Golf Course Lakes Links'),
  ('United States', 'The Hamptons Golf Course Woods Lakes'),
  ('United States', 'The Hamptons Golf Course Woods Links'),
  ('United States', 'The Harbor At Grand Harbor Golf Beach Club'),
  ('United States', 'The Harvester Golf Club'),
  ('United States', 'The Hasentree Club'),
  ('United States', 'The Haven Country Club'),
  ('United States', 'The Havens Country Club'),
  ('United States', 'The Hawk Country Club'),
  ('United States', 'The Hawthorns Golf & Country Club'),
  ('United States', 'The Hayden Lake Country Club'),
  ('United States', 'The Haytm'),
  ('United States', 'The Heather'),
  ('United States', 'The Heathlands'),
  ('United States', 'The Heights Golf Club'),
  ('United States', 'The Heritage At Marion Country Club'),
  ('United States', 'The Heritage Club'),
  ('United States', 'The Heritage Golf Club'),
  ('United States', 'The Hickory At Hamilton Farm'),
  ('United States', 'The Hideaway At Country Greens'),
  ('United States', 'The Hideaway Country Club'),
  ('United States', 'The Hideout'),
  ('United States', 'The Hideout Golf Club'),
  ('United States', 'The Highland Course At Primland Resort'),
  ('United States', 'The Highlands'),
  ('United States', 'The Highlands At Hamilton Farm'),
  ('United States', 'The Highlands At Prestonwood Country Club'),
  ('United States', 'The Highlands Golf Club At Fisher Mountain'),
  ('United States', 'The Highlands Golf Course'),
  ('United States', 'The Hill At Blacksburg Municipal Golf Course'),
  ('United States', 'The Hills At Portal Golf Club'),
  ('United States', 'The Hills Course At Red Hawk'),
  ('United States', 'The Hills Golf Club at McKendree University'),
  ('United States', 'The Hollows Golf Club Cottage Road'),
  ('United States', 'The Hollows Golf Club Lake Cottage'),
  ('United States', 'The Hollows Golf Club Lake Road'),
  ('United States', 'The Holly At Pinewild Country Club'),
  ('United States', 'The Home Course'),
  ('United States', 'The Homestead Golf Course'),
  ('United States', 'The Honors Course'),
  ('United States', 'The Hoop Loop At Tsatsu Dunes'),
  ('United States', 'The Idaho Club'),
  ('United States', 'The Inn At Pocono Manor East Course'),
  ('United States', 'The Inn Golf Course'),
  ('United States', 'The Institute Llc'),
  ('United States', 'The Island Country Club'),
  ('United States', 'The Jay Lionel Hebert Municipal Golf Course'),
  ('United States', 'The Jayhawk Club'),
  ('United States', 'The Jewel Golf Club'),
  ('United States', 'The Jewel of Grand Blanc'),
  ('United States', 'The Kaddyshack Par 3 Golf Course'),
  ('United States', 'The Kanawha Club'),
  ('United States', 'The King And Prince Beach Golf Resort'),
  ('United States', 'The Kingsley Club'),
  ('United States', 'The Kittansett Club'),
  ('United States', 'The Knolls Golf Course'),
  ('United States', 'The Lake Club'),
  ('United States', 'The Lakes'),
  ('United States', 'The Lakes At Ahwatukee'),
  ('United States', 'The Lakes Country Club'),
  ('United States', 'The Lakes Course At Red Hawk'),
  ('United States', 'The Lakes Golf & Country Club'),
  ('United States', 'The Lakes Golf Club'),
  ('United States', 'The Lakes Golf Course'),
  ('United States', 'The Lamberts Point Golf Course'),
  ('United States', 'The Landing At Fort Harrison'),
  ('United States', 'The Landing At Pleasant Point'),
  ('United States', 'The Landing Golf Course'),
  ('United States', 'The Landings Club Deer Creek Course'),
  ('United States', 'The Landings Club Magnolia Course'),
  ('United States', 'The Landings Club Marshwood Course'),
  ('United States', 'The Landings Club Oakridge Course'),
  ('United States', 'The Landings Club Palmetto Course'),
  ('United States', 'The Landings Club Terrapin Point Course'),
  ('United States', 'The Landings Golf Club Trestle Bluff'),
  ('United States', 'The Ledgend'),
  ('United States', 'The Ledges'),
  ('United States', 'The Ledges Golf Club'),
  ('United States', 'The Leelanau Club at Bahle Farms'),
  ('United States', 'The Legacy'),
  ('United States', 'The Legacy Golf Club'),
  ('United States', 'The Legacy Golf Tennis Club Championship Course'),
  ('United States', 'The Legacy Golf Tennis Club Executive Course'),
  ('United States', 'The Legacy Resort At Frenchman Hills'),
  ('United States', 'The Legend Golf Course'),
  ('United States', 'The Legend at Bergamont'),
  ('United States', 'The Legend at Brandybrook'),
  ('United States', 'The Legend at Bristlecone'),
  ('United States', 'The Legend at Merrill Hills'),
  ('United States', 'The Legends At Chateau Elan'),
  ('United States', 'The Legends At Orange Lake Resort'),
  ('United States', 'The Legends Golf Club'),
  ('United States', 'The Legends Golf Course At Parris Island'),
  ('United States', 'The Legends of Massillon'),
  ('United States', 'The Lincoln Hills Golf Club Hills Course'),
  ('United States', 'The Lincoln Hills Golf Club Orchard Course'),
  ('United States', 'The Links At Audubon'),
  ('United States', 'The Links At Bodega Harbour'),
  ('United States', 'The Links At Boynton Beach Championship Course'),
  ('United States', 'The Links At Boynton Beach The Family Course'),
  ('United States', 'The Links At Brick Landing'),
  ('United States', 'The Links At Cadron Valley Golf Country Club'),
  ('United States', 'The Links At Cobble Creek'),
  ('United States', 'The Links At Cotton Valley Golf Club'),
  ('United States', 'The Links At Dardenne'),
  ('United States', 'The Links At Davy Crockett'),
  ('United States', 'The Links At Erie Village'),
  ('United States', 'The Links At Everline'),
  ('United States', 'The Links At Fayetteville Golf Country Club'),
  ('United States', 'The Links At Fort Smith Golf Athletic Club'),
  ('United States', 'The Links At Fox Meadows'),
  ('United States', 'The Links At Galloway'),
  ('United States', 'The Links At Grandview'),
  ('United States', 'The Links At Greenfield Plantation'),
  ('United States', 'The Links At Greystone'),
  ('United States', 'The Links At Hampton Cove'),
  ('United States', 'The Links At Harrison Golf Athletic Club'),
  ('United States', 'The Links At Hemlock Creek'),
  ('United States', 'The Links At Hiawatha Landing'),
  ('United States', 'The Links At Ivy Ridge'),
  ('United States', 'The Links At Jonesboro Golf Athletic Club'),
  ('United States', 'The Links At Kansas Golf Club'),
  ('United States', 'The Links At Kiley Ranch'),
  ('United States', 'The Links At Labelle Winery'),
  ('United States', 'The Links At Lake Toccoa'),
  ('United States', 'The Links At Lakehouse'),
  ('United States', 'The Links At Lang Farm'),
  ('United States', 'The Links At Lighthouse Sound'),
  ('United States', 'The Links At Moses Pointe'),
  ('United States', 'The Links At Mulberry Hill'),
  ('United States', 'The Links At Muny'),
  ('United States', 'The Links At Mustang Creek Golf Country Club'),
  ('United States', 'The Links At Oklahoma City Golf Athletic Club'),
  ('United States', 'The Links At Outlook'),
  ('United States', 'The Links At Overlake'),
  ('United States', 'The Links At Overton Park'),
  ('United States', 'The Links At Oxford Golf Country Club'),
  ('United States', 'The Links At Pine Hill'),
  ('United States', 'The Links At Poland Spring Resort'),
  ('United States', 'The Links At Pretty Prairie'),
  ('United States', 'The Links At Rainbow Curve Golf Country Club'),
  ('United States', 'The Links At Rising Star Casino'),
  ('United States', 'The Links At Riverside'),
  ('United States', 'The Links At Rolling Hills'),
  ('United States', 'The Links At Rolling Meadows'),
  ('United States', 'The Links At Sleepy Ridge'),
  ('United States', 'The Links At Spanish Baytm'),
  ('United States', 'The Links At Spring Church'),
  ('United States', 'The Links At Springdale Golf Country Club'),
  ('United States', 'The Links At Starkville Golf Country Club'),
  ('United States', 'The Links At Stillwater Golf Country Club'),
  ('United States', 'The Links At Stono Ferry'),
  ('United States', 'The Links At Summerly'),
  ('United States', 'The Links At Terranea'),
  ('United States', 'The Links At Teton Peaks'),
  ('United States', 'The Links At Texarkana Golf Athletic Club'),
  ('United States', 'The Links At The Rock Golf Country Club'),
  ('United States', 'The Links At Union Vale'),
  ('United States', 'The Links At Valley Fields'),
  ('United States', 'The Links At Whitehaven'),
  ('United States', 'The Links At Woodcliff'),
  ('United States', 'The Links Golf Club'),
  ('United States', 'The Links Golf Club At Queen Creek'),
  ('United States', 'The Links Golf Course'),
  ('United States', 'The Links Indoor Golf'),
  ('United States', 'The Links Of Madison County Golf Country Club'),
  ('United States', 'The Links Of Naples'),
  ('United States', 'The Links Of North Dakota'),
  ('United States', 'The Links On Memorial Golf Athletic Club'),
  ('United States', 'The Links at Bowen Lake'),
  ('United States', 'The Links at Crystal Lake'),
  ('United States', 'The Links at Ireland Grove'),
  ('United States', 'The Links at Rising Star Casino Resort'),
  ('United States', 'The Links by the Tracks'),
  ('United States', 'The Links of Jacksonville'),
  ('United States', 'The Links of Novi'),
  ('United States', 'The Little Club'),
  ('United States', 'The Little Course'),
  ('United States', 'The Lodge Golf Course'),
  ('United States', 'The Loma Club'),
  ('United States', 'The Loon Golf Resort'),
  ('United States', 'The Loop at Chaska'),
  ('United States', 'The Lynx At River Bend Golf Club'),
  ('United States', 'The Madison Club'),
  ('United States', 'The Magnolia At Pinewild Country Club'),
  ('United States', 'The Majors Golf Club At Bayside Lakes'),
  ('United States', 'The Manor Golf And Country Club'),
  ('United States', 'The Manor Golf Club'),
  ('United States', 'The Meadow At Peabody'),
  ('United States', 'The Meadows'),
  ('United States', 'The Meadows At Countrywood'),
  ('United States', 'The Meadows At Middlesex Golf Club'),
  ('United States', 'The Meadows At Prestonwood Country Club'),
  ('United States', 'The Meadows Country Club'),
  ('United States', 'The Meadows Golf And Country Club'),
  ('United States', 'The Meadows at Grand Valley State University'),
  ('United States', 'The Meadows of Six Mile Creek Golf Course'),
  ('United States', 'The Medalist Golf Club'),
  ('United States', 'The Members Club At Aldarra'),
  ('United States', 'The Members Club At Wildewood'),
  ('United States', 'The Members Club At Woodcreek'),
  ('United States', 'The Metropolitan Golf Links'),
  ('United States', 'The Mill Course'),
  ('United States', 'The Milton Hoosic Club'),
  ('United States', 'The Minikahda Club'),
  ('United States', 'The Mission Club'),
  ('United States', 'The Montrose Club'),
  ('United States', 'The Monument'),
  ('United States', 'The Moor'),
  ('United States', 'The Moor At The Highlands Boyne'),
  ('United States', 'The Moorings Yacht Country Club Hawks Nest'),
  ('United States', 'The Moorings Yacht Country Club Moorings Course'),
  ('United States', 'The Mountain At Christmans Windham House'),
  ('United States', 'The Mountain Course At Spruce Peak'),
  ('United States', 'The Mountains At Bighorn Golf Club'),
  ('United States', 'The Myth'),
  ('United States', 'The National'),
  ('United States', 'The National Golf Club Of Louisiana'),
  ('United States', 'The National Golf Country Club'),
  ('United States', 'The National Golf Course at Eagle Creek'),
  ('United States', 'The Natural at Beaver Creek Resort'),
  ('United States', 'The Neuse Golf Club'),
  ('United States', 'The New England Country Club'),
  ('United States', 'The New Vineyards Golf Course'),
  ('United States', 'The Nightmare GC'),
  ('United States', 'The Nine Hole At Augusta National Golf Club'),
  ('United States', 'The Nine Hole At Centre Hills Country Club'),
  ('United States', 'The Nine Hole Par 3 At Bel Aire Golf Club'),
  ('United States', 'The North At Goodwin Golf Course'),
  ('United States', 'The Oaks'),
  ('United States', 'The Oaks At Margaritaville Lake Resort'),
  ('United States', 'The Oaks At Spanish Fork'),
  ('United States', 'The Oaks Club At Valencia'),
  ('United States', 'The Oaks Club Eagle Course'),
  ('United States', 'The Oaks Club Heron Course'),
  ('United States', 'The Oaks Course'),
  ('United States', 'The Oaks Golf Club'),
  ('United States', 'The Oaks Golf Course'),
  ('United States', 'The Oaks Golf Links'),
  ('United States', 'The Oaks at Kincheloe'),
  ('United States', 'The Oasis'),
  ('United States', 'The Ocean Course At Hokuala'),
  ('United States', 'The Ocean Course At Kiawah Island Golf Resort'),
  ('United States', 'The Ocean North At Pelican Hill Golf Club'),
  ('United States', 'The Ocean South At Pelican Hill Golf Club'),
  ('United States', 'The Old Collier Golf Club'),
  ('United States', 'The Old Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Olde Farm Golf Club'),
  ('United States', 'The Olympic At Gold Mountain Golf Course'),
  ('United States', 'The Olympic Club Cliffs Course'),
  ('United States', 'The Olympic Club Lake Course'),
  ('United States', 'The Olympic Club Ocean Course'),
  ('United States', 'The Omni Grove Park Inn'),
  ('United States', 'The Omni Homestead Resort Spa Cascades Course')
on conflict (country, name) do nothing;