insert into public.golf_courses (country, name) values
  ('United States', 'Pine View Golf Course'),
  ('United States', 'Pine View Highlands'),
  ('United States', 'Pine Woods Golf Course'),
  ('United States', 'Pinebrook Ironwood Golf Course'),
  ('United States', 'Pinecone Thistle At Resort At The Mountain The'),
  ('United States', 'Pinecrest Country Club'),
  ('United States', 'Pinecrest Golf Club'),
  ('United States', 'Pinecrest Golf Course'),
  ('United States', 'Pinecrest Lake Golf Club'),
  ('United States', 'Pinecroft Golf Course'),
  ('United States', 'Pinehaven Country Club'),
  ('United States', 'Pinehills At Myrtlewood Golf Club'),
  ('United States', 'Pinehills Golf Club Jones Course'),
  ('United States', 'Pinehills Golf Club Nicklaus Course'),
  ('United States', 'Pinehurst Golf Club'),
  ('United States', 'Pinehurst Golf Course'),
  ('United States', 'Pinehurst Resort Country Club No 1'),
  ('United States', 'Pinehurst Resort Country Club No 10'),
  ('United States', 'Pinehurst Resort Country Club No 2'),
  ('United States', 'Pinehurst Resort Country Club No 3'),
  ('United States', 'Pinehurst Resort Country Club No 4'),
  ('United States', 'Pinehurst Resort Country Club No 5'),
  ('United States', 'Pinehurst Resort Country Club No 6'),
  ('United States', 'Pinehurst Resort Country Club No 7'),
  ('United States', 'Pinehurst Resort Country Club No 8'),
  ('United States', 'Pinehurst Resort Country Club No 9'),
  ('United States', 'Pinehurst Resort Country Club The Cradle'),
  ('United States', 'Pinehurst Resort Country Club Thistle Dhu Putting Course'),
  ('United States', 'Pineknoll Golf Club'),
  ('United States', 'Pinelands Golf Club'),
  ('United States', 'Pinemoor West Golf Club'),
  ('United States', 'Pineridge Golf Course'),
  ('United States', 'Pines At Clermont'),
  ('United States', 'Pines At Colonial Springs Golf Course'),
  ('United States', 'Pines At Diamondhead Country Club'),
  ('United States', 'Pines At Ft Walton Beach Golf Club'),
  ('United States', 'Pines At Glades Country Club'),
  ('United States', 'Pines At Pompano Beach Golf Course'),
  ('United States', 'Pines At Royal Poinciana Golf Club'),
  ('United States', 'Pines At Willowcreek Golf Club'),
  ('United States', 'Pines At Woodmont Country Club'),
  ('United States', 'Pines Course'),
  ('United States', 'Pines Golf Club'),
  ('United States', 'Pines Golf Club The'),
  ('United States', 'Pines Golf Course'),
  ('United States', 'Pines Lake At Tri Cities Golf Course'),
  ('United States', 'Pines Sands At Star Hill Golf Country Club'),
  ('United States', 'Pines Woodland At Blue Hill Golf Course'),
  ('United States', 'Pinetop Country Club'),
  ('United States', 'Pinetop Lakes Golf Country Club'),
  ('United States', 'Pinetree Country Club'),
  ('United States', 'Pinetuck Golf Course'),
  ('United States', 'Pineview Country Club'),
  ('United States', 'Pinewood Country Club'),
  ('United States', 'Pinewood Golf Club'),
  ('United States', 'Pinewood Golf Course'),
  ('United States', 'Piney Apple Golf Course'),
  ('United States', 'Piney Point Golf Club'),
  ('United States', 'Pinnacle At Troon North Golf Club'),
  ('United States', 'Pinnacle Country Club'),
  ('United States', 'Pinnacle Country Club and Golf Course'),
  ('United States', 'Pinnacle Golf Club'),
  ('United States', 'Pinnacle Hills Golf Course'),
  ('United States', 'Pinnacle Peak Country Club'),
  ('United States', 'Pinnacle State Park Golf Club'),
  ('United States', 'Pinon At Towa Golf Resort'),
  ('United States', 'Pinon Hills Golf Course'),
  ('United States', 'Pinon Ponderosa At Pagosa Springs Golf Club'),
  ('United States', 'Pioneer Creek'),
  ('United States', 'Pioneer Family Golf Center'),
  ('United States', 'Pioneer Hills Golf Course'),
  ('United States', 'Pioneer Pointe'),
  ('United States', 'Pioneer Town & Country Club'),
  ('United States', 'Piper Glen Golf Course'),
  ('United States', 'Piper Hills Golf Course'),
  ('United States', 'Pipers Landing Country Club'),
  ('United States', 'Pipestone Creek Golf Course'),
  ('United States', 'Pipestone Golf & Country Club'),
  ('United States', 'Piping Rock Club'),
  ('United States', 'Piscataquis Country Club'),
  ('United States', 'Pismo State Beach Golf Course'),
  ('United States', 'Pistakee Golf Course'),
  ('United States', 'Pitch And Putt At Evergreen Golf Course Inc'),
  ('United States', 'Pitch Putt At Pine Hills Country Club'),
  ('United States', 'Pitch Putt At Scallys Golf Center'),
  ('United States', 'Pitman Golf Course'),
  ('United States', 'Pittsboro Golf Club'),
  ('United States', 'Pittsburgh Field Club'),
  ('United States', 'Pittsburgh National Golf Club'),
  ('United States', 'Placid Lakes Country Club'),
  ('United States', 'Plainfield Country Club'),
  ('United States', 'Plainfield West Nine'),
  ('United States', 'Plains Municipal Golf Course'),
  ('United States', 'Plainsman Golf Club'),
  ('United States', 'Plandome Country Club'),
  ('United States', 'Plantation At Ponte Vedra'),
  ('United States', 'Plantation At Sea Island Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club North South Course'),
  ('United States', 'Plantation Bay Golf And Country Club Prestwick Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club South West Course'),
  ('United States', 'Plantation Bay Golf And Country Club West North Course'),
  ('United States', 'Plantation Bottom At Valdosta Country Club'),
  ('United States', 'Plantation Golf Club'),
  ('United States', 'Plantation Golf Course'),
  ('United States', 'Plantation Lakes Golf And Country Club'),
  ('United States', 'Plantation On Crystal River Championship Course'),
  ('United States', 'Plantation On Crystal River Lagoons Course'),
  ('United States', 'Plantation Palms Golf Club'),
  ('United States', 'Plantation Preserve Golf Course'),
  ('United States', 'Planterra Ridge Golf Club'),
  ('United States', 'Planters Row At Port Royal Golf Club'),
  ('United States', 'Platteville Golf and Country Club'),
  ('United States', 'Player At Lyman Orchards Golf Club'),
  ('United States', 'Player S Ridge Golf'),
  ('United States', 'Players Club At Deer Creek Highlands 9'),
  ('United States', 'Players Club At Deer Creek Palmer Championship'),
  ('United States', 'Players Club At St James Plantation'),
  ('United States', 'Pleasant Acres Golf Course'),
  ('United States', 'Pleasant Hill Golf Club'),
  ('United States', 'Pleasant Hill Golf Course'),
  ('United States', 'Pleasant Hills Golf Course'),
  ('United States', 'Pleasant Knolls Golf Course At Turning Stone'),
  ('United States', 'Pleasant Meadows'),
  ('United States', 'Pleasant Run Golf Club'),
  ('United States', 'Pleasant Run Recreation Center'),
  ('United States', 'Pleasant Valley Country Club'),
  ('United States', 'Pleasant Valley Golf Club'),
  ('United States', 'Pleasant Valley Golf Course'),
  ('United States', 'Pleasant Valley Sports Club'),
  ('United States', 'Pleasant View Golf Club'),
  ('United States', 'Pleasant View Golf Course'),
  ('United States', 'Pleasanton Golf Center'),
  ('United States', 'Pleasantville Golf & Country Club'),
  ('United States', 'Plentywood Golf Club'),
  ('United States', 'Plum Brook Country Club'),
  ('United States', 'Plum Brook Golf Course'),
  ('United States', 'Plum Creek Golf Country Club'),
  ('United States', 'Plum Creek Golf Course'),
  ('United States', 'Plum Hollow Country Club'),
  ('United States', 'Plum Lake Golf Course'),
  ('United States', 'Plum River Golf Course'),
  ('United States', 'Plum Tree Country Club'),
  ('United States', 'Plumas Lake Golf Country Club'),
  ('United States', 'Plumas Pines Golf Resort'),
  ('United States', 'Plym Park Golf Course'),
  ('United States', 'Plymouth Country Club'),
  ('United States', 'Pocahontas Country Club'),
  ('United States', 'Pocahontas Golf Club'),
  ('United States', 'Pocantico Hills Golf Course'),
  ('United States', 'Pocasset Golf Club'),
  ('United States', 'Poco Diablo Resort'),
  ('United States', 'Pocono Farms Golf Course'),
  ('United States', 'Pocono Hills Golf Course'),
  ('United States', 'Pohick Bay Golf Course'),
  ('United States', 'Pohlcat'),
  ('United States', 'Poinciana Country Club'),
  ('United States', 'Point Judith Country Club'),
  ('United States', 'Point O'' Woods'),
  ('United States', 'Point Rock Golf Club'),
  ('United States', 'Point Sebago Golf Beach Resort'),
  ('United States', 'Point University Golf Club'),
  ('United States', 'Pointe Aux Barques Golf Course'),
  ('United States', 'Pointe South Golf Club'),
  ('United States', 'Pointe West Country Club'),
  ('United States', 'Pointe West Golf Course'),
  ('United States', 'Poipu Bay Golf Course'),
  ('United States', 'Pokegama Golf Course'),
  ('United States', 'Pokegama Pitch & Putt'),
  ('United States', 'Pole Valley Players Golf Course'),
  ('United States', 'Polo Fields Golf and Country Club'),
  ('United States', 'Polo Golf Country Club'),
  ('United States', 'Polo Park East'),
  ('United States', 'Polo Park Golf Course'),
  ('United States', 'Polson Bay Golf Course Championship Course'),
  ('United States', 'Polson Bay Golf Course Olde Course'),
  ('United States', 'Pomona Golf Country Club'),
  ('United States', 'Pomperaug Golf Club'),
  ('United States', 'Pompey Club The'),
  ('United States', 'Ponca City Country Club'),
  ('United States', 'Ponce De Leon Golf Course'),
  ('United States', 'Pondera Golf Club'),
  ('United States', 'Ponderosa Butte Public Golf Course'),
  ('United States', 'Ponderosa Country Club'),
  ('United States', 'Ponderosa Golf Club'),
  ('United States', 'Ponderosa Golf Course'),
  ('United States', 'Ponderosa Meadows At Pagosa Springs Golf Club'),
  ('United States', 'Ponderosa Pines Golf Course'),
  ('United States', 'Ponderosa Springs Golf Course'),
  ('United States', 'Ponds Golf Course At Quail Heights Country Club'),
  ('United States', 'Ponemah Green Family Golf Center'),
  ('United States', 'Ponta Creek Golf Course Nas'),
  ('United States', 'Pontiac Country Club'),
  ('United States', 'Pontotoc Country Club'),
  ('United States', 'Poolesville Golf Course'),
  ('United States', 'Poolsbrook Golf Course'),
  ('United States', 'Popes Grove Golf Course'),
  ('United States', 'Poplar Creek Golf Course'),
  ('United States', 'Poplar Forest Golf Course'),
  ('United States', 'Poplar Golf Course'),
  ('United States', 'Poplar Grove Golf Club'),
  ('United States', 'Poppy Estate Golf Course'),
  ('United States', 'Poppy Hills Golf Course'),
  ('United States', 'Poppy Ridge Golf Course 18 Hole'),
  ('United States', 'Poppy Ridge Golf Course The Ridge 9'),
  ('United States', 'Poquoy Brook Golf Course'),
  ('United States', 'Port Bay Golf Club'),
  ('United States', 'Port Charlotte Golf Club'),
  ('United States', 'Port Huron Elks Lodge Golf Course'),
  ('United States', 'Port Huron Golf Club'),
  ('United States', 'Port Jefferson Country Club At Harbor Hills'),
  ('United States', 'Port Ludlow Golf Resort'),
  ('United States', 'Port Townsend Golf Club'),
  ('United States', 'Portage Country Club'),
  ('United States', 'Portage Golf Club'),
  ('United States', 'Portage Hills Country Club'),
  ('United States', 'Portage Lake Golf Course'),
  ('United States', 'Portales Country Club'),
  ('United States', 'Porter S Neck Country Club'),
  ('United States', 'Porter Valley Country Club'),
  ('United States', 'Porterville Municipal Golf Course'),
  ('United States', 'Portland Country Club'),
  ('United States', 'Portland Golf Course'),
  ('United States', 'Portland Golf Course West'),
  ('United States', 'Portola Country Club'),
  ('United States', 'Portsmouth Country Club'),
  ('United States', 'Posse At Paradise Pointe Golf Complex'),
  ('United States', 'Poston Butte Golf Club'),
  ('United States', 'Potomac Shores Golf Club'),
  ('United States', 'Potowomut Golf Club'),
  ('United States', 'Potsdam Golf Country Club'),
  ('United States', 'Pottawatomie Golf Course'),
  ('United States', 'Pottawattamie Country Club'),
  ('United States', 'Potters Park Golf Course'),
  ('United States', 'Pound Ridge Golf Club'),
  ('United States', 'Powell Country Club'),
  ('United States', 'Powelton Club The'),
  ('United States', 'Power Ranch Golf Club'),
  ('United States', 'Poxabogue Golf Center'),
  ('United States', 'Practice Area'),
  ('United States', 'Practice Area - Driving Range'),
  ('United States', 'Prague Golf Course'),
  ('United States', 'Prairie At Green Meadow Golf Club'),
  ('United States', 'Prairie Bluff Public Golf Club'),
  ('United States', 'Prairie Country Club'),
  ('United States', 'Prairie Creek Golf Course'),
  ('United States', 'Prairie Dog Golf Course'),
  ('United States', 'Prairie Dunes Country Club'),
  ('United States', 'Prairie Dunes Golf Course'),
  ('United States', 'Prairie Falls Golf Club'),
  ('United States', 'Prairie Farms Golf Course'),
  ('United States', 'Prairie Highlands Golf Course'),
  ('United States', 'Prairie Isle Golf Club'),
  ('United States', 'Prairie Landing'),
  ('United States', 'Prairie Landing Golf Club'),
  ('United States', 'Prairie Links Golf Course & Event Center'),
  ('United States', 'Prairie Pines Golf Club'),
  ('United States', 'Prairie Pines Golf Course'),
  ('United States', 'Prairie Ridge Golf Course'),
  ('United States', 'Prairie Rose Golf Club'),
  ('United States', 'Prairie Trace Golf Club'),
  ('United States', 'Prairie Trail Golf Course'),
  ('United States', 'Prairie Trails Golf Course'),
  ('United States', 'Prairie View Golf Club'),
  ('United States', 'Prairie View Golf Course'),
  ('United States', 'Prairie Vista Golf Course'),
  ('United States', 'Prairie West Colf Course'),
  ('United States', 'Prairie West Golf Club At Weatherford'),
  ('United States', 'Prairie Winds Golf Club'),
  ('United States', 'Prairie Winds Golf Course'),
  ('United States', 'Prairie Woods Golf Course'),
  ('United States', 'Prairie du Chien Country Club'),
  ('United States', 'Prairiewood Golf Course'),
  ('United States', 'Preakness Hills Country Club'),
  ('United States', 'Preakness Valley Golf Course East'),
  ('United States', 'Preakness Valley Golf Course West'),
  ('United States', 'Prentice Pines Golf Course'),
  ('United States', 'Prentiss Country Club'),
  ('United States', 'Prescott Country Club'),
  ('United States', 'Prescott Golf Club'),
  ('United States', 'Preserve At Quail West Golf Country Club'),
  ('United States', 'Preserve Golf Course'),
  ('United States', 'Presidential At Hickory Valley Golf Club'),
  ('United States', 'Presidents Golf Course'),
  ('United States', 'Presidio Golf Course'),
  ('United States', 'Presidio Hills Golf Course'),
  ('United States', 'Presque Isle Country Club'),
  ('United States', 'Prestbury Golf Course'),
  ('United States', 'Preston Golf Country Club'),
  ('United States', 'Preston Golf and Country Club'),
  ('United States', 'Prestwick Country Club'),
  ('United States', 'Prestwick Golf Club'),
  ('United States', 'Prestwick Village Golf Club'),
  ('United States', 'Priest Lake Golf Club'),
  ('United States', 'Primghar Golf and Country Club'),
  ('United States', 'Primm Valley Golf Club Desert Course'),
  ('United States', 'Primm Valley Golf Club Lakes Course'),
  ('United States', 'Primrose At Country Club The'),
  ('United States', 'Prince George Golf Course'),
  ('United States', 'Prince William Golf Club'),
  ('United States', 'Princess Anne Country Club'),
  ('United States', 'Princeton Country Club'),
  ('United States', 'Princeton Elks Golf Course'),
  ('United States', 'Princeton Valley Golf Course'),
  ('United States', 'Princeville Makai Golf Club Makai Course'),
  ('United States', 'Princeville Makai Golf Club Woods Course'),
  ('United States', 'Prison View Golf Course'),
  ('United States', 'Pro Putt Miniature Golf Course'),
  ('United States', 'Proctor Golf Club and Course'),
  ('United States', 'Proctor Pittsford Country Club'),
  ('United States', 'Profile Golf Club'),
  ('United States', 'Promontory Club Dye Canyon Golf Course'),
  ('United States', 'Promontory Club Painted Valley Golf Course'),
  ('United States', 'Prospect Hill Golf Course'),
  ('United States', 'Prospect Point Golf Club'),
  ('United States', 'Prospect Valley Golf Club'),
  ('United States', 'Prouts Neck Country Club'),
  ('United States', 'Providence Club'),
  ('United States', 'Providence Country Club'),
  ('United States', 'Providence Golf Club'),
  ('United States', 'Pruneridge Golf Course'),
  ('United States', 'Pryor Creek Golf Club Elmer Link Course'),
  ('United States', 'Pryor Creek Golf Club Johnny Walker Course'),
  ('United States', 'Pryor Creek Municipal Golf Course'),
  ('United States', 'Ptarmigan Country Club'),
  ('United States', 'Puakea Golf Course'),
  ('United States', 'Pub Course At Mcmenamins Edgefield East 12'),
  ('United States', 'Pub Course At Mcmenamins Edgefield West 20'),
  ('United States', 'Pudding Ridge Golf Club'),
  ('United States', 'Pueblo Country Club'),
  ('United States', 'Pueblo El Mirage Golf Club'),
  ('United States', 'Puerto Del Sol Golf Course'),
  ('United States', 'Pukalani Country Club'),
  ('United States', 'Pumpkin Hollow Driving Range'),
  ('United States', 'Pumpkin Vine Golf Course'),
  ('United States', 'Punderson Golf Course'),
  ('United States', 'Punxsutawney Country Club'),
  ('United States', 'Purgatory Golf Club'),
  ('United States', 'Purple Hawk Country Club'),
  ('United States', 'Purple Sage Municipal Golf Course'),
  ('United States', 'Purpoodock Club'),
  ('United States', 'Putnam County Golf Course'),
  ('United States', 'Putting Green Mini Golf'),
  ('United States', 'Quaboag Country Club'),
  ('United States', 'Quail At Quail Creek Country Club'),
  ('United States', 'Quail Brook Golf Course'),
  ('United States', 'Quail Chase Golf Course'),
  ('United States', 'Quail Creek Golf Club'),
  ('United States', 'Quail Creek Golf Club Coyote Road Runner Course'),
  ('United States', 'Quail Creek Golf Club Quail Coyote Course'),
  ('United States', 'Quail Creek Golf Club Road Runner Quail Course'),
  ('United States', 'Quail Creek Golf Country Club'),
  ('United States', 'Quail Creek Golf Course'),
  ('United States', 'Quail Dunes Golf Course'),
  ('United States', 'Quail Hollow Country Club'),
  ('United States', 'Quail Hollow Golf Club'),
  ('United States', 'Quail Hollow Golf Course Championship'),
  ('United States', 'Quail Hollow Golf Course Short'),
  ('United States', 'Quail Lodge Resort Golf Club'),
  ('United States', 'Quail Meadows Golf Course'),
  ('United States', 'Quail Ridge Country Club'),
  ('United States', 'Quail Ridge Golf Club'),
  ('United States', 'Quail Ridge Golf Country Club'),
  ('United States', 'Quail Ridge Golf Course'),
  ('United States', 'Quail Ridge Golf World Executive Golf Course'),
  ('United States', 'Quail Run At Rio Verde Country Club'),
  ('United States', 'Quail Run Executive Golf Course'),
  ('United States', 'Quail Run Golf Club'),
  ('United States', 'Quail Run Golf Course'),
  ('United States', 'Quail Valley Golf Club'),
  ('United States', 'Quail Valley Golf Course'),
  ('United States', 'Quail Village Golf Club'),
  ('United States', 'Quailwood Greens Golf Course'),
  ('United States', 'Quaker Creek Golf Course'),
  ('United States', 'Quaker Hill Country Club'),
  ('United States', 'Quaker Meadows Golf Course'),
  ('United States', 'Quaker Ridge Golf Club'),
  ('United States', 'Quality Inn Suites Golf Resort'),
  ('United States', 'Quanah Country Club'),
  ('United States', 'Quarry At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Quarry Oaks Golf Course'),
  ('United States', 'Quarry Pines Golf Club'),
  ('United States', 'Quarry Ridge Golf Center'),
  ('United States', 'Quarry Ridge Golf Course'),
  ('United States', 'Quarry View Golf Course'),
  ('United States', 'Quartz Mountain Golf Course'),
  ('United States', 'Quashnet Valley Country Club'),
  ('United States', 'Queen Valley Golf Course'),
  ('United States', 'Queenfield Golf Club'),
  ('United States', 'Queens Harbour Yacht Country Club'),
  ('United States', 'Queensbury Country Club'),
  ('United States', 'Queenston Golf Club'),
  ('United States', 'Querbes Park Golf Course'),
  ('United States', 'Quicksilver Golf Club'),
  ('United States', 'Quidnessett Country Club'),
  ('United States', 'Quiet Times Golf Course'),
  ('United States', 'Quig''s Maplewood Golf Course'),
  ('United States', 'Quimby Golf Course'),
  ('United States', 'Quincy Country Club'),
  ('United States', 'Quincy Golf Course'),
  ('United States', 'Quinnatisset Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Quint Valley Golf Club'),
  ('United States', 'Quinter Golf Club'),
  ('United States', 'Quintero Golf Club'),
  ('United States', 'Quinton Oaks Golf Course'),
  ('United States', 'Quitman Country Club'),
  ('United States', 'Quixote Club'),
  ('United States', 'Quogue Field Club'),
  ('United States', 'Raber Golf Course'),
  ('United States', 'Rabun County Golf Club'),
  ('United States', 'Raccoon Creek Golf Course'),
  ('United States', 'Raccoon Hill Golf Club'),
  ('United States', 'Raccoon International'),
  ('United States', 'Raceway Golf Club'),
  ('United States', 'Racine Country Club'),
  ('United States', 'Rackham Golf Course'),
  ('United States', 'Radcliffe Friendly Fareways'),
  ('United States', 'Radisson Greens Golf Course'),
  ('United States', 'Radley Run Country Club'),
  ('United States', 'Radnor Valley Country Club'),
  ('United States', 'Radrick Farms Golf Course'),
  ('United States', 'Railside Golf Club'),
  ('United States', 'Rainbow Golf Club'),
  ('United States', 'Rainbow S End Golf Club'),
  ('United States', 'Raindance National'),
  ('United States', 'Rainier Golf Country Club'),
  ('United States', 'Raintree Country Club'),
  ('United States', 'Raintree Golf & Event Center'),
  ('United States', 'Raintree Golf Club'),
  ('United States', 'Raintree Golf Course'),
  ('United States', 'Raisin Valley Golf Club'),
  ('United States', 'Raleigh Country Club'),
  ('United States', 'Raleigh Golf Association'),
  ('United States', 'Raleigh Golf Association Stockholders Course'),
  ('United States', 'Ralph Myhre Golf Course'),
  ('United States', 'Rammler Golf Club'),
  ('United States', 'Rams Hill Golf Club'),
  ('United States', 'Ramsey Golf Country Club'),
  ('United States', 'Ramsey Lake Golf Course'),
  ('United States', 'Ranch At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Ranch At Roaring Fork Golf Course'),
  ('United States', 'Ranch At Tonto Verde Golf Club'),
  ('United States', 'Ranch Club Golf Course'),
  ('United States', 'Ranch Course At Alisal'),
  ('United States', 'Ranch Course At Genoa Lakes Golf Club'),
  ('United States', 'Ranch Golf Course At Pole Creek Golf Club'),
  ('United States', 'Rancho Bernardo Inn'),
  ('United States', 'Rancho Carlsbad Golf Club'),
  ('United States', 'Rancho Casa Blanca Country Club'),
  ('United States', 'Rancho Del Pueblo Golf Course'),
  ('United States', 'Rancho Del Rey Golf Club'),
  ('United States', 'Rancho Del Sol Golf Club'),
  ('United States', 'Rancho La Quinta Jones Course'),
  ('United States', 'Rancho La Quinta Pate Course'),
  ('United States', 'Rancho Manana Golf Club'),
  ('United States', 'Rancho Maria Golf Club'),
  ('United States', 'Rancho Mirage Country Club'),
  ('United States', 'Rancho Monserate Country Club'),
  ('United States', 'Rancho Park Golf Course'),
  ('United States', 'Rancho Park Par 3 Golf Course'),
  ('United States', 'Rancho San Joaquin Golf Course'),
  ('United States', 'Rancho San Marcos Golf Course'),
  ('United States', 'Rancho Santa Fe Golf Club'),
  ('United States', 'Rancho Sierra Golf Course'),
  ('United States', 'Rancho Solano Golf Course'),
  ('United States', 'Rancho Vista Golf Course'),
  ('United States', 'Rancocas Golf Club'),
  ('United States', 'Randall Hills Country Club'),
  ('United States', 'Randall Oaks Golf Course'),
  ('United States', 'Randolph Country Club'),
  ('United States', 'Range End Country Club'),
  ('United States', 'Range Line Golf Course'),
  ('United States', 'Raptor At Grayhawk Golf Club'),
  ('United States', 'Raquette River Golf Country Club'),
  ('United States', 'Raritan Landing Golf Course'),
  ('United States', 'Raritan Valley Country Club'),
  ('United States', 'Raspberry Falls Golf Hunt Club'),
  ('United States', 'Raspberry Ridge Golf Course'),
  ('United States', 'Raton Country Club'),
  ('United States', 'Rattle Run Golf Course'),
  ('United States', 'Rattlesnake Ridge Golf Club'),
  ('United States', 'Raven At Sandestin Golf And Beach Resort'),
  ('United States', 'Raven Golf Club At Snowshoe Mountain'),
  ('United States', 'Raven Golf Club Phoenix'),
  ('United States', 'Raven Rock Golf Course'),
  ('United States', 'Ravenna Creeks Golf Course'),
  ('United States', 'Ravens Claw Golf Club'),
  ('United States', 'Ravenwood Golf Course'),
  ('United States', 'Ravines Golf Club'),
  ('United States', 'Ravinia Green Country Club'),
  ('United States', 'Ravisloe Country Club'),
  ('United States', 'Ray Golf Association'),
  ('United States', 'Rayburn Country Resort'),
  ('United States', 'Raymond Memorial Golf Course'),
  ('United States', 'Raymond Shoal Creek Golf Course'),
  ('United States', 'Raystown Golf Resort'),
  ('United States', 'Rea Park Golf Course'),
  ('United States', 'Reading Country Club'),
  ('United States', 'Recreation Park 18 Golf Course'),
  ('United States', 'Recreation Park 9 Golf Course'),
  ('United States', 'Red Apple Inn Country Club'),
  ('United States', 'Red Arrow Golf Course'),
  ('United States', 'Red At Bethpage State Park Golf Course'),
  ('United States', 'Red At Cedarbrook Golf Course'),
  ('United States', 'Red At D Fairchild Wheeler Golf Course'),
  ('United States', 'Red At Eisenhower Park Golf Course'),
  ('United States', 'Red At Ford Hill Country Club'),
  ('United States', 'Red At Golf Club Of Avon'),
  ('United States', 'Red At Palmetto Pines Golf Course'),
  ('United States', 'Red At Tunxis Country Club'),
  ('United States', 'Red Bank Plantation'),
  ('United States', 'Red Barn Golf Course'),
  ('United States', 'Red Bird Golf Links'),
  ('United States', 'Red Blue At Edgewood Country Club'),
  ('United States', 'Red Blue At Lindenwood Golf Club'),
  ('United States', 'Red Blue At Ramblewood Country Club'),
  ('United States', 'Red Blue At Sugar Mill Country Club'),
  ('United States', 'Red Blue At Sunken Meadow State Park Golf Course'),
  ('United States', 'Red Blue At Timber Point Country Club'),
  ('United States', 'Red Blue At Westchester Golf Country Club'),
  ('United States', 'Red Blue At Woods Golf Course The'),
  ('United States', 'Red Bridge Golf And Country Club'),
  ('United States', 'Red Carpet Golf Course'),
  ('United States', 'Red Cloud Golf Course'),
  ('United States', 'Red Dog Run'),
  ('United States', 'Red Farm Golf'),
  ('United States', 'Red Fox Country Club'),
  ('United States', 'Red Fox Run'),
  ('United States', 'Red Gold At Rothland Golf Course'),
  ('United States', 'Red Gold At Valley Brook Country Club'),
  ('United States', 'Red Hawk Golf Club'),
  ('United States', 'Red Hawk Golf Course & Learning Center'),
  ('United States', 'Red Hawk Ridge'),
  ('United States', 'Red Hill Country Club'),
  ('United States', 'Red Hook Golf Club'),
  ('United States', 'Red Ledges Golf Club 12 Hole Golf Park Course'),
  ('United States', 'Red Ledges Golf Club Nicklaus Signature Course'),
  ('United States', 'Red Lodge Mountain Golf Course'),
  ('United States', 'Red Maples Golf Course'),
  ('United States', 'Red Martin Country Club'),
  ('United States', 'Red Mountain Ranch Country Club'),
  ('United States', 'Red Nine At Hyde Park Golf Course'),
  ('United States', 'Red Oak Country Club'),
  ('United States', 'Red Oaks Golf Course'),
  ('United States', 'Red Pines Golf Course'),
  ('United States', 'Red Reef Executive Golf Course'),
  ('United States', 'Red River Golf Club'),
  ('United States', 'Red Rock Country Club'),
  ('United States', 'Red Rock Golf Course'),
  ('United States', 'Red Rocks Country Club'),
  ('United States', 'Red Run Golf Club'),
  ('United States', 'Red Silver At Foxfire Country Club'),
  ('United States', 'Red Sky Golf Club Fazio Course'),
  ('United States', 'Red Sky Golf Club Norman Course'),
  ('United States', 'Red Tail Golf Club'),
  ('United States', 'Red Tail Run Golf Club'),
  ('United States', 'Red Trail Links'),
  ('United States', 'Red White At Arrowhead Golf Course'),
  ('United States', 'Red White At Buck Hill Falls Golf Club'),
  ('United States', 'Red White At Glen Oaks Club'),
  ('United States', 'Red White At Highland Lakes Golf Course'),
  ('United States', 'Red White At Little Mill Country Club'),
  ('United States', 'Red White At Myakka Pines Golf Club'),
  ('United States', 'Red White At Ringgold Golf Club'),
  ('United States', 'Red White At Rothland Golf Course'),
  ('United States', 'Red White At Shawnee Inn Golf Resort'),
  ('United States', 'Red White At Town Of Colonie Golf Course'),
  ('United States', 'Red White At Western Turnpike Golf Course'),
  ('United States', 'Red White At Woods Golf Course The'),
  ('United States', 'Red Wing Golf Club'),
  ('United States', 'Red Wing Lake Golf Course'),
  ('United States', 'Red Wolf Golf Club'),
  ('United States', 'Red Yellow At Willowbrook Golf Club'),
  ('United States', 'RedTail Golf Club'),
  ('United States', 'Redbud Crabapple At Roanoke Country Club'),
  ('United States', 'Redbud Springs Golf Club'),
  ('United States', 'Redding Country Club'),
  ('United States', 'Redfish Run At The Villages Executive Golf Trail'),
  ('United States', 'Redhawk Golf Club'),
  ('United States', 'Redhawk Golf Course'),
  ('United States', 'Redland Golf Country Club'),
  ('United States', 'Redlands Country Club'),
  ('United States', 'Redmont Country Club'),
  ('United States', 'Redstick Golf Club'),
  ('United States', 'Redstone Resort'),
  ('United States', 'Redtail Golf Club'),
  ('United States', 'Redwood Canyon Golf Course'),
  ('United States', 'Redwood Empire Golf Country Club'),
  ('United States', 'Redwood Falls Golf Club'),
  ('United States', 'Reedsburg Country Club'),
  ('United States', 'Reedy Creek Golf Course'),
  ('United States', 'Reedy Meadow Golf Course'),
  ('United States', 'Reems Creek Golf Course'),
  ('United States', 'Reeves Golf Course'),
  ('United States', 'Reflection Bay Golf Club'),
  ('United States', 'Reflection Ridge Golf Club'),
  ('United States', 'Regatta Bay Golf Yacht Club'),
  ('United States', 'Regency At Dominion Valley Country Club'),
  ('United States', 'Regency At Monroe Golf And Country Club'),
  ('United States', 'Regents Glen Country Club'),
  ('United States', 'Regulation At Borland Golf Center'),
  ('United States', 'Regulation At Jackson Park Golf Course'),
  ('United States', 'Regulation At Jefferson Park Golf Club'),
  ('United States', 'Regulation At Las Positas Golf Course'),
  ('United States', 'Regulation At Marine Memorial Golf Course'),
  ('United States', 'Regulation At Mick Riley Golf Course'),
  ('United States', 'Regulation At Pleasant Valley Country Club'),
  ('United States', 'Regulation Eighteen At Smithtown Landing Golf Club'),
  ('United States', 'Regulation Nine At Cherokee Ridge Golf Course'),
  ('United States', 'Rehoboth Beach Country Club'),
  ('United States', 'Rehoboth Country Club'),
  ('United States', 'Reid Municipal Golf Course'),
  ('United States', 'Reidy Creek Golf Course'),
  ('United States', 'Remington Golf Club'),
  ('United States', 'Remsen Golf Course'),
  ('United States', 'Remuda Golf Course'),
  ('United States', 'Renaissance Golf Club'),
  ('United States', 'Renaissance Golf Course'),
  ('United States', 'Renaissance Vinoy Resort'),
  ('United States', 'Rendezvous Meadows Golf Course'),
  ('United States', 'Renegade Course At Desert Mountain Golf Club'),
  ('United States', 'Renwood Golf Course'),
  ('United States', 'Republic Golf Course Club'),
  ('United States', 'Reservation Golf Club'),
  ('United States', 'Reserve Club At St James Plantation'),
  ('United States', 'Reserve Run Golf Course'),
  ('United States', 'Reservoir Creek Golf Course'),
  ('United States', 'Resort At Tahquitz Creek Golf Resort'),
  ('United States', 'Reston National Golf Course'),
  ('United States', 'Retreat At Sea Island Golf Club'),
  ('United States', 'Reunion Country Club'),
  ('United States', 'Reunion Golf Country Club'),
  ('United States', 'Reunion Resort Nicklaus Course'),
  ('United States', 'Reunion Resort Palmer Course'),
  ('United States', 'Reunion Resort Watson Course'),
  ('United States', 'Revere Golf Club Concord Course'),
  ('United States', 'Revere Golf Club Lexington Course'),
  ('United States', 'Reynolds Golf Course'),
  ('United States', 'Reynolds Lake Oconee Great Waters'),
  ('United States', 'Reynolds Lake Oconee Richland Course'),
  ('United States', 'Reynolds Lake Oconee The Creek Club'),
  ('United States', 'Reynolds Lake Oconee The Landing'),
  ('United States', 'Reynolds Lake Oconee The National'),
  ('United States', 'Reynolds Lake Oconee The Oconee'),
  ('United States', 'Reynolds Lake Oconee The Preserve Course'),
  ('United States', 'Reynolds Park Golf Course'),
  ('United States', 'Rhinelander Country Club'),
  ('United States', 'Rhode Island Country Club'),
  ('United States', 'Rhodes Ranch Country Club'),
  ('United States', 'Rib Mountain Golf Course'),
  ('United States', 'Rice Lake Golf and Country Club'),
  ('United States', 'Riceville Country Club'),
  ('United States', 'Rich Harvest Farms Golf Course'),
  ('United States', 'Rich Maiden Golf Course'),
  ('United States', 'Rich Valley Golf Course'),
  ('United States', 'Richford Country Club'),
  ('United States', 'Richland Country Club'),
  ('United States', 'Richland Greens Golf Center'),
  ('United States', 'Richmond Country Club'),
  ('United States', 'Richmond County Country Club'),
  ('United States', 'Richmond Hill Golf Club'),
  ('United States', 'Richmond Pitch And Putt At The Villages Executive Golf Trail'),
  ('United States', 'Richter Park Golf Course'),
  ('United States', 'Ridder Farm Golf Country Club'),
  ('United States', 'Ridge At Mulligans South'),
  ('United States', 'Ridge Canyon At La Paloma Country Club'),
  ('United States', 'Ridge Club'),
  ('United States', 'Ridge Country Club'),
  ('United States', 'Ridge Creek Dinuba Golf Club'),
  ('United States', 'Ridge Golf Club'),
  ('United States', 'Ridge Golf Course'),
  ('United States', 'Ridge Golf Course At Pole Creek Golf Club'),
  ('United States', 'Ridge Manor Oaks Golf Country Club'),
  ('United States', 'Ridge Stone Golf Club'),
  ('United States', 'Ridge Trail At Blue Ridge Trail Golf Club'),
  ('United States', 'Ridge top golf course'),
  ('United States', 'Ridgecrest Country Club'),
  ('United States', 'Ridgefield Golf Course'),
  ('United States', 'Ridgefields Country Club'),
  ('United States', 'Ridgemark Golf Country Club'),
  ('United States', 'Ridgemont Country Club'),
  ('United States', 'Ridgemoor Country Club'),
  ('United States', 'Ridgepointe Country Club'),
  ('United States', 'Ridges at Sand Creek'),
  ('United States', 'Ridgeview Country Club'),
  ('United States', 'Ridgeview Golf Course'),
  ('United States', 'Ridgeway Country Club'),
  ('United States', 'Ridgeway Shores Golf Club'),
  ('United States', 'Ridgewood Country Club'),
  ('United States', 'Ridgewood Golf Course'),
  ('United States', 'Riegelwood Country Club'),
  ('United States', 'Rifle Creek Golf Course'),
  ('United States', 'Rifle River Golf Course'),
  ('United States', 'Riley Grove Course At Palmer Legends'),
  ('United States', 'Rio Bend Golf Course'),
  ('United States', 'Rio Bravo Country Club'),
  ('United States', 'Rio Grande Club'),
  ('United States', 'Rio Hondo Golf Club'),
  ('United States', 'Rio Mimbres Country Club'),
  ('United States', 'Rio Pinar Golf'),
  ('United States', 'Rio Vista Golf Club'),
  ('United States', 'Rio Vista Golf Course'),
  ('United States', 'Riomar Country Club'),
  ('United States', 'Rip Arnold At Cherry Hills Country Club'),
  ('United States', 'Rip Van Winkle Country Club'),
  ('United States', 'Ripon Golf Club'),
  ('United States', 'Rippling Rapids Golf Club'),
  ('United States', 'Rising Sun Golf Course At Mountain Sky Guest Ranch'),
  ('United States', 'Rittswood Golf Club'),
  ('United States', 'Ritz Carlton Members Golf Club'),
  ('United States', 'Ritzville Municipal Golf'),
  ('United States', 'Rivard Golf Country Club'),
  ('United States', 'River At Indian Springs Country Club'),
  ('United States', 'River Bank Golf Course'),
  ('United States', 'River Bend Country Club'),
  ('United States', 'River Bend Golf Club'),
  ('United States', 'River Bend Golf Club North Course'),
  ('United States', 'River Bend Golf Club South Course'),
  ('United States', 'River Bend Golf Country Club'),
  ('United States', 'River Bend Golf Course'),
  ('United States', 'River Bend Links'),
  ('United States', 'River Bend Municipal Golf Course'),
  ('United States', 'River Bend Ymca Golf Course'),
  ('United States', 'River Birch Golf Club'),
  ('United States', 'River Birch Golf Course'),
  ('United States', 'River Club'),
  ('United States', 'River Club of Mequon'),
  ('United States', 'River Course At Alisal'),
  ('United States', 'River Course At Fiddlers Elbow Country Club'),
  ('United States', 'River Creek Club'),
  ('United States', 'River Creek Golf Course'),
  ('United States', 'River Creek Park Golf Course'),
  ('United States', 'River Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'River Edge Golf Course'),
  ('United States', 'River Falls Golf Club'),
  ('United States', 'River Falls Plantation'),
  ('United States', 'River Forest Country Club'),
  ('United States', 'River Forest Golf Course'),
  ('United States', 'River Glen Country Club'),
  ('United States', 'River Golf Country Club The'),
  ('United States', 'River Greens Golf Course'),
  ('United States', 'River Hall Country Club'),
  ('United States', 'River Heights Golf Course'),
  ('United States', 'River Hills Country Club'),
  ('United States', 'River Hills Golf Country Club'),
  ('United States', 'River Island Country Club'),
  ('United States', 'River Island Golf Course'),
  ('United States', 'River Isles Golf Course'),
  ('United States', 'River Lake At Woodbridge Golf Country Club'),
  ('United States', 'River Lakes Course At Pelican Sound Golf River Club'),
  ('United States', 'River Lakes Golf Course'),
  ('United States', 'River Landing At Sandy Ridge'),
  ('United States', 'River Landing Landing Course'),
  ('United States', 'River Landing River Course'),
  ('United States', 'River Marsh Golf Club Hyatt Chesapeake Bay'),
  ('United States', 'River Middle At Woodbridge Golf Country Club'),
  ('United States', 'River Oak At Del Rio Country Club'),
  ('United States', 'River Oaks Golf Club'),
  ('United States', 'River Oaks Golf Course'),
  ('United States', 'River Park Golf Course'),
  ('United States', 'River Pointe Golf Club'),
  ('United States', 'River Ridge At Harbour Ridge Yacht Country Club'),
  ('United States', 'River Ridge Golf Club'),
  ('United States', 'River Ridge Golf Club The Victoria Lakes Course'),
  ('United States', 'River Ridge Golf Club The Vineyard Course'),
  ('United States', 'River Ridge Golf Course'),
  ('United States', 'River Road Golf Club'),
  ('United States', 'River Run Golf Country Club'),
  ('United States', 'River Run Golf Course'),
  ('United States', 'River Run Golf Links'),
  ('United States', 'River Run Ii Golf Links'),
  ('United States', 'River Tasalmi Golf Course'),
  ('United States', 'River Trace Golf At Mac'),
  ('United States', 'River Vale Country Club'),
  ('United States', 'River Valley Country Club'),
  ('United States', 'River Valley Golf Course'),
  ('United States', 'River Valley Ranch Golf Club'),
  ('United States', 'River View Club'),
  ('United States', 'River View Golf Course'),
  ('United States', 'River Wilds Golf Club'),
  ('United States', 'River''s Edge Golf Club'),
  ('United States', 'Riverbend Golf Club'),
  ('United States', 'Riverbend Golf Course'),
  ('United States', 'Rivercliff Golf Course'),
  ('United States', 'Riverdale Country Club'),
  ('United States', 'Riverdale Dunes'),
  ('United States', 'Riverdale Knolls'),
  ('United States', 'Riverfront Golf Club'),
  ('United States', 'Riveria Country Club Golf Course'),
  ('United States', 'Riverland Country Club'),
  ('United States', 'Riverlands Golf Country Club'),
  ('United States', 'Rivermeadow Golf Club'),
  ('United States', 'Rivermont Golf Country Club'),
  ('United States', 'Rivermoor Golf Club'),
  ('United States', 'Riverpines Golf Course'),
  ('United States', 'Riverpines Golf Course Par 3 Course'),
  ('United States', 'Rivers Bend Golf Club'),
  ('United States', 'Rivers Bend Golf Course'),
  ('United States', 'Rivers Edge Golf Club'),
  ('United States', 'Rivers Edge Golf Club At Burley'),
  ('United States', 'Rivers Edge Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Riverside At Greenville Country Club'),
  ('United States', 'Riverside At Juniper Hill Golf Course'),
  ('United States', 'Riverside Country Club'),
  ('United States', 'Riverside Golf & Recreation'),
  ('United States', 'Riverside Golf Academy'),
  ('United States', 'Riverside Golf Center'),
  ('United States', 'Riverside Golf Centre'),
  ('United States', 'Riverside Golf Club'),
  ('United States', 'Riverside Golf Country Club'),
  ('United States', 'Riverside Golf Course'),
  ('United States', 'Riverside Golf Course North Course'),
  ('United States', 'Riverside Golf Course Practice Course'),
  ('United States', 'Riverside Golf Course South Course'),
  ('United States', 'Riverside Greens'),
  ('United States', 'Riverside Municipal Golf Course'),
  ('United States', 'Riverside Of Fresno Golf Course'),
  ('United States', 'Riverside Recreation Golf Course'),
  ('United States', 'Riverton Country Club'),
  ('United States', 'Riverton Golf Club'),
  ('United States', 'Riverton Pointe Golf And Country Club'),
  ('United States', 'Rivertowne Country Club'),
  ('United States', 'Riverview Country Club'),
  ('United States', 'Riverview Golf Club'),
  ('United States', 'Riverview Golf Country Club'),
  ('United States', 'Riverview Golf Course'),
  ('United States', 'Riverview Highlands Golf Course'),
  ('United States', 'Riverview Park Golf Course'),
  ('United States', 'Riverview Rv Resort'),
  ('United States', 'Riverwalk Golf Club'),
  ('United States', 'Riverwalk Golf Club Sunset 9'),
  ('United States', 'Riverwood Golf Club'),
  ('United States', 'Riverwood Golf Club Deer Run Riverview Course'),
  ('United States', 'Riverwood Golf Club Meadowlands Deer Run Course'),
  ('United States', 'Riverwood Golf Club Riverview Meadowlands Course'),
  ('United States', 'Riverwood National'),
  ('United States', 'Riverwood Resort'),
  ('United States', 'Riverwoods'),
  ('United States', 'Riviera Country Club'),
  ('United States', 'Riviera Hills Golf And Country Club'),
  ('United States', 'Roadhaven Golf Course'),
  ('United States', 'Roadrunner Dunes Golf Course'),
  ('United States', 'Roadrunner Golf Country Club'),
  ('United States', 'Roane County Country Club'),
  ('United States', 'Roanoke Country Club'),
  ('United States', 'Roaring Fork Club'),
  ('United States', 'Roaring Gap Golf Club'),
  ('United States', 'Rob Roy Golf Club'),
  ('United States', 'Robbers Row At Port Royal Golf Club'),
  ('United States', 'Robbinhurst Golf Club'),
  ('United States', 'Robersonville Country Club'),
  ('United States', 'Robert A. Black Golf Course'),
  ('United States', 'Robert Cupp At Palmetto Hall Plantation'),
  ('United States', 'Robert Moses Golf Course'),
  ('United States', 'Robert T Lynch Municipal Brookline Golf Course'),
  ('United States', 'Robert Trent Jones Golf Club'),
  ('United States', 'Robert Trent Jones Golf Course Cornell University'),
  ('United States', 'Robertshaw Acres Golf Club'),
  ('United States', 'Robson Ranch Golf Club'),
  ('United States', 'Rochelle Country Club'),
  ('United States', 'Rochelle Ranch Golf Course'),
  ('United States', 'Rochester Country Club'),
  ('United States', 'Rochester Golf & Country Club'),
  ('United States', 'Rochester Golf Club'),
  ('United States', 'Rochester Place Golf Club'),
  ('United States', 'Rock Barn Golf And Spa Jackson Course'),
  ('United States', 'Rock Barn Golf And Spa Jones Course'),
  ('United States', 'Rock Creek Cattle Company'),
  ('United States', 'Rock Creek Country Club'),
  ('United States', 'Rock Creek Golf And Country Club'),
  ('United States', 'Rock Creek Golf Club'),
  ('United States', 'Rock Creek Golf Course'),
  ('United States', 'Rock Creek Park Golf'),
  ('United States', 'Rock Harbor Golf Course Boulder'),
  ('United States', 'Rock Harbor Golf Course Rock'),
  ('United States', 'Rock Hill Country Club'),
  ('United States', 'Rock Hill Golf Country Club'),
  ('United States', 'Rock Hollow Golf Course'),
  ('United States', 'Rock Island Golf Course'),
  ('United States', 'Rock Manor Golf Club'),
  ('United States', 'Rock Port Golf and Country Club'),
  ('United States', 'Rock Ridge Country Club'),
  ('United States', 'Rock Ridge Golf Course'),
  ('United States', 'Rock River Golf Course'),
  ('United States', 'Rock River Hills Golf Course'),
  ('United States', 'Rock Spring Golf Club'),
  ('United States', 'Rock Spring Golf Course'),
  ('United States', 'Rock Valley Golf Club'),
  ('United States', 'Rockaway Hunting Golf Course'),
  ('United States', 'Rockaway River Country Club'),
  ('United States', 'Rockfish Golf Course'),
  ('United States', 'Rockford Country Club'),
  ('United States', 'Rockingham Country Club'),
  ('United States', 'Rockland Country Club'),
  ('United States', 'Rockland Golf Club'),
  ('United States', 'Rockland Golf Course'),
  ('United States', 'Rockledge Country Club'),
  ('United States', 'Rockleigh Golf Course Blue'),
  ('United States', 'Rockleigh Golf Course Red White'),
  ('United States', 'Rockport Golf Club'),
  ('United States', 'Rockrimmon Country Club'),
  ('United States', 'Rockville Links Club'),
  ('United States', 'Rockwind Community Links Championship Course'),
  ('United States', 'Rockwind Community Links Lil Rock Par 3 Course'),
  ('United States', 'Rocky Bayou Country Club'),
  ('United States', 'Rocky Branch Golf Club'),
  ('United States', 'Rocky Creek Golf Club'),
  ('United States', 'Rocky Ford Golf Course'),
  ('United States', 'Rocky Ford Par 3'),
  ('United States', 'Rocky Gap Casino Resort'),
  ('United States', 'Rocky Knoll Country Club'),
  ('United States', 'Rocky Lakes Golf Course'),
  ('United States', 'Rocky Point Golf Course'),
  ('United States', 'Rocky Ridge Golf Club'),
  ('United States', 'Rocky River Golf Club At Concord'),
  ('United States', 'Rocky Run Golf Course'),
  ('United States', 'Rocky Spring Golf Course'),
  ('United States', 'Rogala Public Links'),
  ('United States', 'Rogers City Country Club'),
  ('United States', 'Rogers Gardens Golf Course'),
  ('United States', 'Rogers Park Golf Course'),
  ('United States', 'Rogers Park Golf Course Short Course'),
  ('United States', 'Rohannas Golf Course'),
  ('United States', 'Rolfe Golf Club'),
  ('United States', 'Rolling Acres Golf Club'),
  ('United States', 'Rolling Acres Golf Course'),
  ('United States', 'Rolling Fields Golf Club'),
  ('United States', 'Rolling Green Country Club'),
  ('United States', 'Rolling Green Golf Club'),
  ('United States', 'Rolling Green Golf Course'),
  ('United States', 'Rolling Green Golf Course Country Club'),
  ('United States', 'Rolling Greens Executive Golf Course'),
  ('United States', 'Rolling Greens Golf Club'),
  ('United States', 'Rolling Greens Golf Course'),
  ('United States', 'Rolling Hills'),
  ('United States', 'Rolling Hills Country Club'),
  ('United States', 'Rolling Hills County Park Disc Golf'),
  ('United States', 'Rolling Hills Golf Club'),
  ('United States', 'Rolling Hills Golf Course'),
  ('United States', 'Rolling Knolls Golf Course'),
  ('United States', 'Rolling Meadows'),
  ('United States', 'Rolling Meadows Country Club'),
  ('United States', 'Rolling Meadows Golf Club'),
  ('United States', 'Rolling Meadows Golf Course'),
  ('United States', 'Rolling Oaks Golf Course'),
  ('United States', 'Rolling Pines Golf Course'),
  ('United States', 'Rolling Rock Club'),
  ('United States', 'Rolling S Golf Club'),
  ('United States', 'Rolling Turf Golf Club'),
  ('United States', 'Rollingstone Ranch Golf Club'),
  ('United States', 'Roman Nose Golf Course'),
  ('United States', 'Rome Country Club'),
  ('United States', 'Ron Jaworskis Riverwinds Golf Tennis Club'),
  ('United States', 'Ron Jaworskis Valleybrook Country Club'),
  ('United States', 'Rooling Hills Golf Course'),
  ('United States', 'Roosevelt Course At The Villages Executive Golf Trail'),
  ('United States', 'Roosevelt Golf Course'),
  ('United States', 'Roosevelt Memorial Golf Course'),
  ('United States', 'Roosevelt Municipal Golf Course'),
  ('United States', 'Rooster Run Golf Club'),
  ('United States', 'Root River Country Club'),
  ('United States', 'Root River Golf Club'),
  ('United States', 'Roscoe Mountain Club'),
  ('United States', 'Rose Brook Golf Course'),
  ('United States', 'Rose City Golf Course'),
  ('United States', 'Rose Creek Golf Club'),
  ('United States', 'Rose Creek Golf Course'),
  ('United States', 'Rose Hill Golf Club'),
  ('United States', 'Rose Lake Golf Club'),
  ('United States', 'Rose Park Golf Course'),
  ('United States', 'Rose Ridge Golf Course'),
  ('United States', 'Rosedale Golf Country Club'),
  ('United States', 'Roseland Golf and Curling Club'),
  ('United States', 'Roses Run Country Club'),
  ('United States', 'Rosman-Glendale Farm Golf Course'),
  ('United States', 'Ross Mountain Club'),
  ('United States', 'Rossmoor Golf Club The Creekside Golf Course'),
  ('United States', 'Rossmoor Golf Club The Dollar Ranch Golf Course'),
  ('United States', 'Rossmoor Golf Course'),
  ('United States', 'Roswell Country Club'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Long Meadow'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Pine Valley Course'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The White Marsh'),
  ('United States', 'Rouge Park Golf Course'),
  ('United States', 'Round Barn Golf Club'),
  ('United States', 'Round Grove Golf and Country Club'),
  ('United States', 'Round Hill Club'),
  ('United States', 'Round Hill Community Golf Club'),
  ('United States', 'Round Hill Golf Country Club'),
  ('United States', 'Round Lake Public Golf Course'),
  ('United States', 'Round Mountain Golf Club'),
  ('United States', 'Round Valley Golf Course'),
  ('United States', 'Route 56 Golf Course'),
  ('United States', 'Rowley Country Club'),
  ('United States', 'Roxboro Country Club'),
  ('United States', 'Roxiticus Golf Club'),
  ('United States', 'Royal City Public Golf Course'),
  ('United States', 'Royal Colwood Golf Club'),
  ('United States', 'Royal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Royal Crest Country Club'),
  ('United States', 'Royal Crest Golf Club'),
  ('United States', 'Royal Fox Country Club'),
  ('United States', 'Royal Fox Golf Club'),
  ('United States', 'Royal Golf Club'),
  ('United States', 'Royal Hawaiian Golf Club'),
  ('United States', 'Royal Hylands Golf Club'),
  ('United States', 'Royal Kaanapali'),
  ('United States', 'Royal Kunia Country Club'),
  ('United States', 'Royal Lakes Golf Country Club'),
  ('United States', 'Royal Manchester Golf Links'),
  ('United States', 'Royal Melbourne'),
  ('United States', 'Royal New Kent Golf Club'),
  ('United States', 'Royal Oak Golf Club'),
  ('United States', 'Royal Oaks Country Club'),
  ('United States', 'Royal Oaks Golf Club'),
  ('United States', 'Royal Palm Country Club'),
  ('United States', 'Royal Palm Yacht Country Club'),
  ('United States', 'Royal Palms Golf Course'),
  ('United States', 'Royal Sabal At Grand Palms Golf Country Club'),
  ('United States', 'Royal Saint Patrick''s Golf Links'),
  ('United States', 'Royal Scot Golf Course'),
  ('United States', 'Royal St Augustine Golf And Country Club'),
  ('United States', 'Royal St Cloud Golf Links Blue Red Course'),
  ('United States', 'Royal St Cloud Golf Links Red White Course'),
  ('United States', 'Royal St Cloud Golf Links White Blue Course'),
  ('United States', 'Royal Vista Golf Club'),
  ('United States', 'Royal Wood Golf Country Club'),
  ('United States', 'Royalwood Golf Club'),
  ('United States', 'Royce Brook Golf Club'),
  ('United States', 'Royce Brook Golf Club East Golf Course'),
  ('United States', 'Roys All Steak Hamburgers Golf Center Pine Acres Golf Course'),
  ('United States', 'Royster Memorial Golf Course'),
  ('United States', 'Ruby Hill Golf Club'),
  ('United States', 'Ruby View Golf Course'),
  ('United States', 'Ruffled Feathers Golf Community'),
  ('United States', 'Rum Creek Golf'),
  ('United States', 'Rum Pointe Golf Course'),
  ('United States', 'Rum River Hills Golf Club'),
  ('United States', 'Rumson Golf Club'),
  ('United States', 'Running Deer Golf Club'),
  ('United States', 'Rupert Country Club'),
  ('United States', 'Rush Creek Golf Club'),
  ('United States', 'Rush Creek Golf Club - Mac 9'),
  ('United States', 'Rush Lake Hills Golf Club'),
  ('United States', 'Russell Memorial Park Golf Course'),
  ('United States', 'Russellville Country Club'),
  ('United States', 'Russian Jack Springs Golf Course'),
  ('United States', 'Rustic Canyon Golf Course'),
  ('United States', 'Rustic Glen Golf Course'),
  ('United States', 'Rustic Golf Country Club'),
  ('United States', 'Rustic Ridge Golf Course'),
  ('United States', 'Ruston Golf Country Club'),
  ('United States', 'Rutgers University Golf Course'),
  ('United States', 'Ruth Lake Country Club'),
  ('United States', 'Ruth Park Golf Couse'),
  ('United States', 'Rutherfordton Golf Club'),
  ('United States', 'Rutland Country Club'),
  ('United States', 'Ryder Brook Golf Course'),
  ('United States', 'Ryder Course At Pga Golf Club'),
  ('United States', 'Ryder Golf Course'),
  ('United States', 'Rye Golf Club'),
  ('United States', 'Ryland Lakes Golf Course'),
  ('United States', 'SPG Green Garden Country Club'),
  ('United States', 'Sabal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Sabal Grand At Grand Palms Golf Country Club'),
  ('United States', 'Sabal Springs Golf Racquet Club'),
  ('United States', 'Sabetha Golf Country Club'),
  ('United States', 'Sable Creek Golf Course'),
  ('United States', 'Sable Oaks Golf Club'),
  ('United States', 'Sabot At Hermitage Country Club'),
  ('United States', 'Sacandaga Golf Club'),
  ('United States', 'Sadaquada Golf Club'),
  ('United States', 'Saddle Cycle Club'),
  ('United States', 'Saddle Ridge'),
  ('United States', 'Saddle Rock Golf Course'),
  ('United States', 'SaddleBrook Golf Club'),
  ('United States', 'Saddleback Golf Club'),
  ('United States', 'Saddleback Ridge Golf Course'),
  ('United States', 'Saddlebrook At The Villages Executive Golf Trail'),
  ('United States', 'Saddlebrook Golf Course'),
  ('United States', 'Saddlebrook Resort Cypress Pine'),
  ('United States', 'Saddlebrook Resort Oak Cypress'),
  ('United States', 'Saddlebrook Resort Pine Oak'),
  ('United States', 'Saddlebrooke Ranch Golf Club'),
  ('United States', 'Saddlebrooke Tucson At Saddlebrooke Country Club'),
  ('United States', 'Safari Golf Club'),
  ('United States', 'Sag Harbor Golf Club'),
  ('United States', 'Sagamore Hampton Golf Club'),
  ('United States', 'Sagamore Resort And Golf Club'),
  ('United States', 'Sagamore Spring Golf Club'),
  ('United States', 'Sage Hills Golf Resort'),
  ('United States', 'Sage Lakes Municipal Golf Course'),
  ('United States', 'Sage Meadows Golf Course'),
  ('United States', 'Sage Run Golf Course'),
  ('United States', 'Sage Valley Golf Club'),
  ('United States', 'Saginaw Country Club'),
  ('United States', 'Saguaro Course At We Ko Pa Golf Club'),
  ('United States', 'Sailfish Point Golf Club'),
  ('United States', 'Sailfish Sands Golf Course Sailfish Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Black Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Gold Course'),
  ('United States', 'Saint Andrew''s Golf and Country Club'),
  ('United States', 'Saint Andrews Golf Course'),
  ('United States', 'Saint Charles Country Club'),
  ('United States', 'Saint Clair Shores Golf Club'),
  ('United States', 'Saint Croix National Golf & Event Center'),
  ('United States', 'Saint Elmo Golf Club'),
  ('United States', 'Saint Francois Country Club'),
  ('United States', 'Saint Germain Golf Club'),
  ('United States', 'Saint Ignace Golf & Country Club'),
  ('United States', 'Saint Ives'),
  ('United States', 'Saint Joe Valley Golf Course'),
  ('United States', 'Saint John Fisher Golf Course'),
  ('United States', 'Saint John''s Resort Golf Course'),
  ('United States', 'Saint Marys Golf Club'),
  ('United States', 'Sakima Country Club'),
  ('United States', 'Sakonnet Golf Club'),
  ('United States', 'Salem Country Club'),
  ('United States', 'Salem Glen Country Club'),
  ('United States', 'Salem Golf Club'),
  ('United States', 'Salem Golf Course'),
  ('United States', 'Salem Harbour Golf Course'),
  ('United States', 'Salem Hills Golf Club'),
  ('United States', 'Salida Golf Club'),
  ('United States', 'Salina Country Club'),
  ('United States', 'Salina Municipal Golf Course'),
  ('United States', 'Salinas Fairways Golf Course'),
  ('United States', 'Saline County Golf Club'),
  ('United States', 'Salisbury Country Club Buckingham Course'),
  ('United States', 'Salisbury Country Club Huguenot Course'),
  ('United States', 'Salisbury Country Club Monacan Course'),
  ('United States', 'Salish Cliffs Golf Club'),
  ('United States', 'Salmo Golf Club'),
  ('United States', 'Salmon Creek Country Club'),
  ('United States', 'Salmon Falls Golf Club'),
  ('United States', 'Salmon Run Golf Course'),
  ('United States', 'Salmon Valley Golf Course'),
  ('United States', 'Salt Creek Country Club'),
  ('United States', 'Salt Creek Golf Club'),
  ('United States', 'Salt Creek Golf Resort'),
  ('United States', 'Salt Fork State Park Golf Course'),
  ('United States', 'Salt River Golf Course'),
  ('United States', 'Saltleaf Golf Preserve The Leaf'),
  ('United States', 'Saltleaf Golf Preserve The Preserve'),
  ('United States', 'Saltville Golf Course'),
  ('United States', 'Saluda Valley Country Club'),
  ('United States', 'Samoset Resort'),
  ('United States', 'San Carlos Golf Club'),
  ('United States', 'San Clemente Municipal Golf Course'),
  ('United States', 'San Diego Country Club'),
  ('United States', 'San Dimas Canyon Golf Course'),
  ('United States', 'San Francisco Golf Club'),
  ('United States', 'San Gabriel Country Club'),
  ('United States', 'San Ignacio Golf Club'),
  ('United States', 'San Joaquin Country Club'),
  ('United States', 'San Jose Country Club'),
  ('United States', 'San Jose Municipal Golf Course'),
  ('United States', 'San Juan Country Club'),
  ('United States', 'San Juan Golf Country Club'),
  ('United States', 'San Juan Hills Golf Club'),
  ('United States', 'San Juan Oaks Golf Club'),
  ('United States', 'San Luis Obispo Country Club'),
  ('United States', 'San Manuel Golf Club'),
  ('United States', 'San Marcos Golf Resort'),
  ('United States', 'San Pedro Golf Course'),
  ('United States', 'San Ramon Golf Club'),
  ('United States', 'San Tan Course At Sunland Springs Village'),
  ('United States', 'San Tan Highlands'),
  ('United States', 'San Vicente Golf Resort'),
  ('United States', 'Sanborn Golf and Country Club'),
  ('United States', 'Sanctuary At River Strand Golf And Country Club'),
  ('United States', 'Sanctuary Golf Club'),
  ('United States', 'Sanctuary Golf Course'),
  ('United States', 'Sanctuary Lake Golf Course'),
  ('United States', 'Sand Canyon Country Club'),
  ('United States', 'Sand Creek Country Club'),
  ('United States', 'Sand Creek Golf Club'),
  ('United States', 'Sand Creek Golf Course'),
  ('United States', 'Sand Creek Short Course'),
  ('United States', 'Sand Creek Station Golf Club'),
  ('United States', 'Sand Hill Golf Course'),
  ('United States', 'Sand Hollow Golf Resort The Championship Course'),
  ('United States', 'Sand Hollow Golf Resort The Links Course'),
  ('United States', 'Sand Hollow Golf Resort Wee Course'),
  ('United States', 'Sand Point Country Club'),
  ('United States', 'Sand Ridge Golf Club'),
  ('United States', 'Sand Springs Golf Course'),
  ('United States', 'Sand Valley Golf Resort'),
  ('United States', 'Sandalwood Country Club'),
  ('United States', 'Sandhill At The Villages Executive Golf Trail'),
  ('United States', 'Sandhill Crane Golf Club Championship Golf Course'),
  ('United States', 'Sandhill Crane Golf Club The Nest Par 3'),
  ('United States', 'Sandhill Golf Course'),
  ('United States', 'Sandia Golf Club'),
  ('United States', 'Sandpiper At Spring Lake Golf Club'),
  ('United States', 'Sandpiper Bay Golf Country Club Bay Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Piper Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Sand Nine'),
  ('United States', 'Sandpiper Cove Golf Course'),
  ('United States', 'Sandpiper Golf Course'),
  ('United States', 'Sands Lakes At Star Hill Golf Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Sands Point Golf Club'),
  ('United States', 'Sandstone Area Golf Course'),
  ('United States', 'Sandstone Hollow Golf Club At Turning Stone'),
  ('United States', 'Sandtrap Golf Course'),
  ('United States', 'Sandwich Hollows Golf Club'),
  ('United States', 'Sandy Burr Country Club'),
  ('United States', 'Sandy Creek Golf Course'),
  ('United States', 'Sandy Hollow Golf Course'),
  ('United States', 'Sandy Pebbles Golf Course'),
  ('United States', 'Sandy Pines Golf Course'),
  ('United States', 'Sandy Point Golf Course'),
  ('United States', 'Sandy Pond Par 3 Golf Course'),
  ('United States', 'Sandy Ridge Country Club'),
  ('United States', 'Sandy Ridge Golf Course'),
  ('United States', 'Sandy River Golf Course'),
  ('United States', 'Sandy Row Golf Club'),
  ('United States', 'Sandy Run Country Club'),
  ('United States', 'Sanford Golf Club'),
  ('United States', 'Sanford Golf Course'),
  ('United States', 'Sanibel Island Golf Club'),
  ('United States', 'Sankaty Head Golf Club'),
  ('United States', 'Sanlan Golf Course Alligator Course'),
  ('United States', 'Sanlan Golf Course Bobcat Course'),
  ('United States', 'Sanlan Golf Course Coyote Course'),
  ('United States', 'Santa Ana Country Club'),
  ('United States', 'Santa Anita Golf Course'),
  ('United States', 'Santa Barbara Golf Club'),
  ('United States', 'Santa Fe Country Club'),
  ('United States', 'Santa Lucia River Club The Ballantrae Golf Course'),
  ('United States', 'Santa Maria Country Club'),
  ('United States', 'Santa Maria Golf Club'),
  ('United States', 'Santa Paula Community Golf Course'),
  ('United States', 'Santa Rosa Country Club'),
  ('United States', 'Santa Rosa Golf Beach Club'),
  ('United States', 'Santa Rosa Golf Beach Club The Loop'),
  ('United States', 'Santa Rosa Golf Country Club'),
  ('United States', 'Santa Rosa Golf Course'),
  ('United States', 'Santee Cooper Country Club'),
  ('United States', 'Santee National Golf Club'),
  ('United States', 'Sapelo Hammock Golf Club'),
  ('United States', 'Sapona Ridge Country Club'),
  ('United States', 'Sapphire National Golf Club'),
  ('United States', 'Sapulpa Municipal Golf Course'),
  ('United States', 'Sara Bay Country Club'),
  ('United States', 'Sarah Shank Golf Course'),
  ('United States', 'Saranac Inn Golf Country Club'),
  ('United States', 'Saranac Lake Golf Club'),
  ('United States', 'Sarasota At The Villages Executive Golf Trail'),
  ('United States', 'Sarasota National Golf Club'),
  ('United States', 'Saratoga Country Club'),
  ('United States', 'Saratoga Golf Polo Club'),
  ('United States', 'Saratoga Hot Springs Resort Saratoga Public Golf Course'),
  ('United States', 'Saratoga Lake Golf Club'),
  ('United States', 'Saratoga National Golf Club'),
  ('United States', 'Sarnia Golf and Curling'),
  ('United States', 'Saskatoon Golf Club'),
  ('United States', 'Sassamon Trace Golf Course'),
  ('United States', 'Saticoy Country Club'),
  ('United States', 'Saticoy Regional Golf Course'),
  ('United States', 'Saugahatchee Country Club'),
  ('United States', 'Sauganash'),
  ('United States', 'Saukie Golf Course'),
  ('United States', 'Sault Country Club'),
  ('United States', 'Sault Sainte Marie Country Club'),
  ('United States', 'Saunders Golf Course'),
  ('United States', 'Sauquoit Knolls Golf Club'),
  ('United States', 'Savanna Club Golf Course'),
  ('United States', 'Savannah Country Club'),
  ('United States', 'Savannah Oaks Golf Club'),
  ('United States', 'Sawgrass Country Club East South'),
  ('United States', 'Sawgrass Country Club South West'),
  ('United States', 'Sawgrass Country Club West East'),
  ('United States', 'Sawgrass Gleneagles At Waterford Golf Club'),
  ('United States', 'Sawgrass Turnberry At Waterford Golf Club'),
  ('United States', 'Sawmill Creek Golf Club'),
  ('United States', 'Sawmill Golf Course'),
  ('United States', 'Sawmill Woods Golf Course'),
  ('United States', 'Saxon East At Saxon Golf Course'),
  ('United States', 'Saxon Woods Golf Course'),
  ('United States', 'Sayre National Golf Course'),
  ('United States', 'Scalawags Golf Club'),
  ('United States', 'Scarlet At Paradise Point Golf Course'),
  ('United States', 'Scarlet Oaks Country Club'),
  ('United States', 'Scarsdale Golf Club'),
  ('United States', 'Scenic Farms Golf Course'),
  ('United States', 'Scenic Golf and Country Club'),
  ('United States', 'Scenic Heights Golf Course'),
  ('United States', 'Scenic Hills Country Club'),
  ('United States', 'Scenic Knolls Golf Course'),
  ('United States', 'Scenic Valley Golf Course'),
  ('United States', 'Scenic View Country Club'),
  ('United States', 'Scenic View Golf Course'),
  ('United States', 'Scepter Golf Club Falcon Ibis Course'),
  ('United States', 'Scepter Golf Club Ibis Osprey Course'),
  ('United States', 'Scepter Golf Club Osprey Falcon Course'),
  ('United States', 'Schaffers Mill Club'),
  ('United States', 'Schalamar Creek Golf Club'),
  ('United States', 'Schaumburg Golf Club'),
  ('United States', 'Schenectady Municipal Golf Course'),
  ('United States', 'Scherwood Golf'),
  ('United States', 'Schifferdecker Golf Course'),
  ('United States', 'Schleswig Community Golf Club'),
  ('United States', 'Schneiters Bluff Golf Club'),
  ('United States', 'Schneiters Riverside Golf Course'),
  ('United States', 'Scholl Canyon Golf Tennis Club'),
  ('United States', 'Schroon Lake Municipal Golf Course'),
  ('United States', 'Schuss Mountain Golf Course'),
  ('United States', 'Schuyler Meadows Club'),
  ('United States', 'Schuylkill Country Club'),
  ('United States', 'Scioto Country Club'),
  ('United States', 'Scioto Reserve Country Club'),
  ('United States', 'Scituate Country Club'),
  ('United States', 'Scobey Golf Club'),
  ('United States', 'Scotch Hills Country Club'),
  ('United States', 'Scotch Meadows Country Club'),
  ('United States', 'Scotch Pines Golf Course'),
  ('United States', 'Scotch Valley Country Club'),
  ('United States', 'Scotfield Country Club'),
  ('United States', 'Scothurst Country Club'),
  ('United States', 'Scotland Run Golf Club'),
  ('United States', 'Scotland Yards Golf Club'),
  ('United States', 'Scott City Country Club'),
  ('United States', 'Scott County Park Golf'),
  ('United States', 'Scott Greens Golf Club'),
  ('United States', 'Scott Lake Country Club'),
  ('United States', 'Scott Lake Golf Course'),
  ('United States', 'Scott Park Golf Links'),
  ('United States', 'Scottish Heights Golf Club'),
  ('United States', 'Scottish Links At Lake Shastina Golf Resort'),
  ('United States', 'Scotts Bluff Country Club'),
  ('United States', 'Scotts Corners Golf Course'),
  ('United States', 'Scottsdale National Golf Club'),
  ('United States', 'Scottsdale National Golf Club The Bad Little Nine'),
  ('United States', 'Scottsdale National Golf Club The Other Course'),
  ('United States', 'Scottsdale Shadows Golf Club'),
  ('United States', 'Scottsdale Silverado Golf Club'),
  ('United States', 'Scottsdale Silverado Golf Club Silver Pony Course'),
  ('United States', 'Scranton Canoe Club'),
  ('United States', 'Scranton Municipal Golf Course'),
  ('United States', 'Sea Aire Park Golf Course'),
  ('United States', 'Sea Mountain Golf Course'),
  ('United States', 'Sea N Air Golf Course'),
  ('United States', 'Sea Palms Golf Tennis Resort'),
  ('United States', 'Sea Pines Country Club'),
  ('United States', 'Sea Pines Golf Resort'),
  ('United States', 'Sea Scape Golf Links'),
  ('United States', 'Seabee Golf Club Of Port Hueneme'),
  ('United States', 'Seacliff Country Club'),
  ('United States', 'Seagate Country Club'),
  ('United States', 'Searcy Country Club'),
  ('United States', 'Searsport Pines Golf Course'),
  ('United States', 'Seascape Golf Beach And Tennis'),
  ('United States', 'Seascape Golf Club'),
  ('United States', 'Seaside At Sea Island Golf Club'),
  ('United States', 'Seaside Golf Club'),
  ('United States', 'Seattle Golf Club'),
  ('United States', 'Seaview The Bay Course'),
  ('United States', 'Seaview The Pines Course'),
  ('United States', 'Seawane Club The'),
  ('United States', 'Sebasco Harbor Resort Golf Club'),
  ('United States', 'Sebastian Municipal Golf Course'),
  ('United States', 'Sebastopol Golf Course'),
  ('United States', 'Sebonack Golf Club'),
  ('United States', 'Sebring Golf Club'),
  ('United States', 'Sebring International Golf Resort Green Course'),
  ('United States', 'Sebring International Golf Resort Red Course'),
  ('United States', 'Sebring International Golf Resort The 12'),
  ('United States', 'Sebring International Golf Resort Yellow Course'),
  ('United States', 'Sebring Lakeside Golf Resort'),
  ('United States', 'Secession Golf Club'),
  ('United States', 'Second Nine At Edison Club The'),
  ('United States', 'Second Nine At Montclair Golf Club'),
  ('United States', 'Second Nine Third Nine At Bermuda Dunes Country Club'),
  ('United States', 'Second Nine Third Nine At Cloverleaf Golf Club'),
  ('United States', 'Second Third At Lake Venice Golf Club'),
  ('United States', 'Sedan Country Club'),
  ('United States', 'Sedgefield Country Club Ross Course'),
  ('United States', 'Sedgewick County Golf Club'),
  ('United States', 'Sedgewood Country Club'),
  ('United States', 'Sedona Golf Resort'),
  ('United States', 'Segregansett Country Club'),
  ('United States', 'Seidel Golf Course'),
  ('United States', 'Seiling Golf Course'),
  ('United States', 'Selfridge ANGB Golf Course'),
  ('United States', 'Selma Valley Golf Course'),
  ('United States', 'Selmer Golf Country Club'),
  ('United States', 'Semiahmoo Golf Country Club'),
  ('United States', 'Seminole At Canongate On White Oak'),
  ('United States', 'Seminole Choctaw At Indian Hills Country Club'),
  ('United States', 'Seminole Golf Club'),
  ('United States', 'Seminole Lake Country Club'),
  ('United States', 'Seminole Lakes Country Club'),
  ('United States', 'Seminole Legacy Golf Club'),
  ('United States', 'Seneca Falls Country Club'),
  ('United States', 'Seneca Golf Club'),
  ('United States', 'Seneca Golf Course'),
  ('United States', 'Seneca Hickory Stick Golf Course'),
  ('United States', 'Seneca Lake Country Club'),
  ('United States', 'Senica''s Oak Ridge Golf Club'),
  ('United States', 'Sensei Porcupine Creek Golf Club'),
  ('United States', 'Sentry World Golf Center'),
  ('United States', 'Sequoia Woods Country Club'),
  ('United States', 'Sequoyah Country Club'),
  ('United States', 'Sequoyah National Golf Club'),
  ('United States', 'Sequoyah State Park Golf Course'),
  ('United States', 'Serendipity Golf Course'),
  ('United States', 'Serenity Hill Golf Course'),
  ('United States', 'Serenoa Golf Club'),
  ('United States', 'Sergeant Jasper Golf Club'),
  ('United States', 'Serket'),
  ('United States', 'Serrano Country Club'),
  ('United States', 'Settler''s Hill Golf Course'),
  ('United States', 'Settlers Bay'),
  ('United States', 'Settlers Crossing Golf Course'),
  ('United States', 'Seven Bridges Golf Club'),
  ('United States', 'Seven Hills Golf Club'),
  ('United States', 'Seven Hills Golfers Club'),
  ('United States', 'Seven Lakes'),
  ('United States', 'Seven Lakes Country Club'),
  ('United States', 'Seven Lakes Golf Course'),
  ('United States', 'Seven Oaks Country Club'),
  ('United States', 'Seven Oaks Country Club Islands Oaks Course'),
  ('United States', 'Seven Oaks Country Club Lakes Islands Course'),
  ('United States', 'Seven Oaks Country Club Oaks Lakes Course'),
  ('United States', 'Seven Oaks Golf Club'),
  ('United States', 'Seville Golf Country Club'),
  ('United States', 'Sewailo Golf Club'),
  ('United States', 'Sewells Point Golf Course'),
  ('United States', 'Sewickley Heights Golf Club'),
  ('United States', 'Seymour Golf Course'),
  ('United States', 'Shackamaxon Golf Country Club'),
  ('United States', 'Shade Mountain Golf Club'),
  ('United States', 'Shadow Creek Golf Course'),
  ('United States', 'Shadow Glen The Golf Club'),
  ('United States', 'Shadow Hills Golf Club'),
  ('United States', 'Shadow Hills Golf Club North Par 3 Course'),
  ('United States', 'Shadow Lake Village Golf Course'),
  ('United States', 'Shadow Lakes Club'),
  ('United States', 'Shadow Mountain Golf Course'),
  ('United States', 'Shadow Ridge Country Club'),
  ('United States', 'Shadow Ridge Golf Club'),
  ('United States', 'Shadow Valley Country Club'),
  ('United States', 'Shadow Valley Golf Course'),
  ('United States', 'Shadow Wood Preserve'),
  ('United States', 'Shadowbrook Inn Resort'),
  ('United States', 'Shadowbrooke Golf Course'),
  ('United States', 'Shadowmoss Plantation Golf Club'),
  ('United States', 'Shadowood Golf Course'),
  ('United States', 'Shadowridge Golf Club'),
  ('United States', 'Shady Bend Golf Course'),
  ('United States', 'Shady Canyon Golf Club'),
  ('United States', 'Shady Grove Golf Course'),
  ('United States', 'Shady Hills Golf Course'),
  ('United States', 'Shady Hollow Country Club'),
  ('United States', 'Shady Oaks Golf Course'),
  ('United States', 'Shaffer''s Evergreen Golf Course'),
  ('United States', 'Shaftesbury Glen Golf Fish Club'),
  ('United States', 'Shagbark Golf & Country Club'),
  ('United States', 'Shaker Farms Country Club'),
  ('United States', 'Shaker Heights Country Club'),
  ('United States', 'Shaker Hills Country Club'),
  ('United States', 'Shaker Ridge Country Club'),
  ('United States', 'Shaker Run Golf Club'),
  ('United States', 'Shalimar Golf Club'),
  ('United States', 'Shalimar Pointe Golf Club'),
  ('United States', 'Shallow Creek Golf Club'),
  ('United States', 'Shambolee Golf Course'),
  ('United States', 'Shamrock Golf Club'),
  ('United States', 'Shamrock Golf Country Club'),
  ('United States', 'Shamrock Golf Course'),
  ('United States', 'Shamrock Hills Golf Club'),
  ('United States', 'Shamrock Public Golf Course'),
  ('United States', 'Shandin Hills Golf Club'),
  ('United States', 'Shangri La Country Club Champions Course'),
  ('United States', 'Shangri La Country Club Heritage Course'),
  ('United States', 'Shangri La Country Club Legends Course'),
  ('United States', 'Shangri La Resort The Battlefield Par 3'),
  ('United States', 'Shannon Greens Golf Club'),
  ('United States', 'Shannopin Country Club'),
  ('United States', 'Shark River Golf Course'),
  ('United States', 'Sharkey Country Club'),
  ('United States', 'Sharks Tooth Golf Club'),
  ('United States', 'Sharon Country Club'),
  ('United States', 'Sharon Country Club Pitch Putt Course'),
  ('United States', 'Sharon Heights Golf Country Club'),
  ('United States', 'Sharon Springs Golf Course'),
  ('United States', 'Sharon Woods Golf Course'),
  ('United States', 'Sharp Park Golf Course'),
  ('United States', 'Shasta Valley Golf Club'),
  ('United States', 'Shattuck Golf Country Club'),
  ('United States', 'Shattuck The'),
  ('United States', 'Shawano Lake Golf Course'),
  ('United States', 'Shawnee Country Club'),
  ('United States', 'Shawnee Golf Country Club'),
  ('United States', 'Shawnee Golf Country Club Chapel Creek Course'),
  ('United States', 'Shawnee Golf Country Club Clear Creek Course'),
  ('United States', 'Shawnee Golf Country Club Heartland Hills Course'),
  ('United States', 'Shawnee Golf Course'),
  ('United States', 'Shawnee Hills Country Club'),
  ('United States', 'Shawnee Hills Golf Course'),
  ('United States', 'Shawnee Inn Golf Resort Tillinghast Chip N Putt'),
  ('United States', 'Sheaffer Memorial Golf Park'),
  ('United States', 'Sheepscot Links Golf Course'),
  ('United States', 'Shelby Country Club'),
  ('United States', 'Shelby Oaks Golf Club'),
  ('United States', 'Shelbyville Country Club'),
  ('United States', 'Sheldon Golf and Country Club'),
  ('United States', 'Shell Bay Club'),
  ('United States', 'Shell Landing Golf Club'),
  ('United States', 'Shell Point Golf Club'),
  ('United States', 'Shelridge Country Club'),
  ('United States', 'Shelter Bay Golf Course'),
  ('United States', 'Shelter Cove Golf Course'),
  ('United States', 'Shelter Harbor Golf Club Championship Course'),
  ('United States', 'Shelter Harbor Golf Club Par 3 Course'),
  ('United States', 'Shelter Island Country Club'),
  ('United States', 'Shenandoah Country Club'),
  ('United States', 'Shenango Lake Golf Club'),
  ('United States', 'Shenendoah Golf Club At Turning Stone'),
  ('United States', 'Shennecossett Golf Club'),
  ('United States', 'Shenvalee Golf Resort Creek Miller'),
  ('United States', 'Shenvalee Golf Resort Miller Olde'),
  ('United States', 'Shenvalee Golf Resort Olde Creek'),
  ('United States', 'Shephard Hills Golf Course'),
  ('United States', 'Shepherd Hills Golf Club'),
  ('United States', 'Shepherd''s Crook Golf Course'),
  ('United States', 'Shepherd''s Hollow'),
  ('United States', 'Shepherds Meadow Golf Course'),
  ('United States', 'Sherbrooke Golf Country Club'),
  ('United States', 'Sheridan Golf Country Club'),
  ('United States', 'Sheridan Park Golf Course'),
  ('United States', 'Sherman Hills Golf Club'),
  ('United States', 'Sherwood Country Club'),
  ('United States', 'Sherwood Forest Golf Club'),
  ('United States', 'Sherwood Golf Club'),
  ('United States', 'Sherwood Hills Golf Course'),
  ('United States', 'Sherwood Lakes Club'),
  ('United States', 'Sherwood on the Hill Golf Course'),
  ('United States', 'Shield Crest Golf Course'),
  ('United States', 'Shiloh Golf Course'),
  ('United States', 'Shiloh Park Golf Course'),
  ('United States', 'Shiloh Ridge Athletic Club'),
  ('United States', 'Shiloh Springs Golf Club'),
  ('United States', 'Shingle Creek Golf Club'),
  ('United States', 'Shining Mountain Golf Club'),
  ('United States', 'Shining Rock Golf Club'),
  ('United States', 'Shinnecock Hills Golf Course'),
  ('United States', 'Shoaff Park Golf Course'),
  ('United States', 'Shoop Park'),
  ('United States', 'Shooting Star Of Jackson Hole'),
  ('United States', 'Shore Acres Course At Lake Shore Country Club'),
  ('United States', 'Shore At Monterey Peninsula Country Club'),
  ('United States', 'Shore Gate Golf Club'),
  ('United States', 'Shoreacres'),
  ('United States', 'Shorecliffs Golf Club'),
  ('United States', 'Shorehaven Golf Club'),
  ('United States', 'Shoreland Country Club'),
  ('United States', 'Shoreline Golf Links At Mountain View'),
  ('United States', 'Shorewood Country Club'),
  ('United States', 'Short At Cordillera Golf Course'),
  ('United States', 'Short At Highland Oaks Golf Course'),
  ('United States', 'Short At Saucon Valley Country Club'),
  ('United States', 'Short Beach Golf Course'),
  ('United States', 'Short Course'),
  ('United States', 'Short Hills Country Club'),
  ('United States', 'Short Nine At Villages Golf Country Club'),
  ('United States', 'Shoshone Golf Tennis Club'),
  ('United States', 'Shuksan Golf Club'),
  ('United States', 'Shuttle Meadow Country Club'),
  ('United States', 'Siasconset Golf Course'),
  ('United States', 'Sibley Golf and Country Club'),
  ('United States', 'Sidewinder At Gold Canyon Golf Resort'),
  ('United States', 'Sidney Country Club'),
  ('United States', 'Sidney Golf Course'),
  ('United States', 'Siena Golf Course'),
  ('United States', 'Sierra Comstock At Empire Ranch Golf Course'),
  ('United States', 'Sierra Hills Golf Club'),
  ('United States', 'Sierra Lakes Golf Club'),
  ('United States', 'Sierra River At Empire Ranch Golf Course'),
  ('United States', 'Sierra Sage Golf Course'),
  ('United States', 'Sierra Star Golf Club'),
  ('United States', 'Sierra View Country Club'),
  ('United States', 'Sierra Vista Golf Center At Pueblo Del Sol'),
  ('United States', 'Sigel Golf Course'),
  ('United States', 'Signal Hill Golf Course'),
  ('United States', 'Signal Point Club'),
  ('United States', 'Signal Point Country Club'),
  ('United States', 'Signal Point Golf Club'),
  ('United States', 'Signature Of Solon'),
  ('United States', 'Sigourney Golf Club'),
  ('United States', 'Siler City Country Club'),
  ('United States', 'Silo Point Country Club'),
  ('United States', 'Silo Ridge Field Club'),
  ('United States', 'Silo Run Golf Course'),
  ('United States', 'Silo Sleeping Indian At West Woods Golf Club'),
  ('United States', 'Siloam Springs Country Club'),
  ('United States', 'Silos Golf Course'),
  ('United States', 'Silver At Eisenhower Golf Course'),
  ('United States', 'Silver At Treasure Lake Golf Course'),
  ('United States', 'Silver Bay Golf Course')
on conflict (country, name) do nothing;