insert into public.golf_courses (country, name) values
  ('United States', 'Bridges Golf Course'),
  ('United States', 'Bridgeton Berry Hill Golf Course'),
  ('United States', 'Bridgewater Country Club'),
  ('United States', 'Bridgewater Golf Club'),
  ('United States', 'Bridgewater Links Golf Course'),
  ('United States', 'Bridgton Highlands Country Club'),
  ('United States', 'Brier Creek Country Club'),
  ('United States', 'Brier Creek Golf Course'),
  ('United States', 'Brierwood Country Club'),
  ('United States', 'Briery Country Club'),
  ('United States', 'Brigantine Clipper At Shipyard Golf Club'),
  ('United States', 'Brigantine Golf Links'),
  ('United States', 'Briggs Woods Golf Course'),
  ('United States', 'Bright Grandview Golf Course'),
  ('United States', 'Bright Meadows Golf Course Championship'),
  ('United States', 'Bright Meadows Golf Course Executive'),
  ('United States', 'Brighton Dale Links'),
  ('United States', 'Brighton Park Golf Course'),
  ('United States', 'Brights Creek Golf Club'),
  ('United States', 'Brightwater Club'),
  ('United States', 'Brightwood Hills Golf Course'),
  ('United States', 'Bringhurst Golf Course'),
  ('United States', 'Brinkley Country Club'),
  ('United States', 'Bristol Golf Club At The Cedars'),
  ('United States', 'Bristol Golf Park'),
  ('United States', 'Bristol Oaks Golf Club'),
  ('United States', 'Bristol Ridge Golf Course'),
  ('United States', 'Bristow Golf Country Club'),
  ('United States', 'Bristow Manor Golf Club'),
  ('United States', 'Britt Country Club'),
  ('United States', 'Broad Bay Country Club'),
  ('United States', 'Broad Run Golf Practice Facility'),
  ('United States', 'Broad Run Golfers Club'),
  ('United States', 'Broadacres Golf Club'),
  ('United States', 'Broadlands Golf Club'),
  ('United States', 'Broadlands Golf Course'),
  ('United States', 'Broadmoor Country Club'),
  ('United States', 'Broadmoor Golf Club'),
  ('United States', 'Broadmoor Golf Course'),
  ('United States', 'Broadmoor Golf Links'),
  ('United States', 'Broadmoore Golf Course'),
  ('United States', 'Brockton Country Club'),
  ('United States', 'Brockville Country Club'),
  ('United States', 'Brockville Highland Golf Club'),
  ('United States', 'Broken Arrow Golf Club'),
  ('United States', 'Broken Pine Golf Country Club'),
  ('United States', 'Broken Sound Club Club Course'),
  ('United States', 'Broken Sound Club Old Course'),
  ('United States', 'Broken Tee Englewood Golf Course'),
  ('United States', 'Broken Tee Englewood Par 3 Course'),
  ('United States', 'Bronson Golf Club'),
  ('United States', 'Bronzwood Golf Club'),
  ('United States', 'Brook Lea Country Club'),
  ('United States', 'Brook Tree Golf Course'),
  ('United States', 'Brook Valley Country Club'),
  ('United States', 'Brooke Hills Park Golf Course'),
  ('United States', 'Brookfield Country Club'),
  ('United States', 'Brookfield Hills Golf Course'),
  ('United States', 'Brookhaven Country Club'),
  ('United States', 'Brookhaven Golf Club'),
  ('United States', 'Brookhill Golf Course'),
  ('United States', 'Brookhills Golf Club'),
  ('United States', 'Brookings Country Club'),
  ('United States', 'Brooklake Country Club'),
  ('United States', 'Brookland Golf Park'),
  ('United States', 'Brooklawn Country Club'),
  ('United States', 'Brookledge Golf Course'),
  ('United States', 'Brookmeadow Country Club'),
  ('United States', 'Brookridge Golf Country Club'),
  ('United States', 'Brookridge Golf Fitness Championship Course'),
  ('United States', 'Brookridge Golf Fitness West Nine'),
  ('United States', 'Brooks Golf Club'),
  ('United States', 'Brookshire Golf Club'),
  ('United States', 'Brookside Country Club'),
  ('United States', 'Brookside Golf & Country Club'),
  ('United States', 'Brookside Golf Club'),
  ('United States', 'Brookside Golf Club C W Koiner Course'),
  ('United States', 'Brookside Golf Club E O Nay Course'),
  ('United States', 'Brookside Golf Course'),
  ('United States', 'Brookside Golf and Grill'),
  ('United States', 'Brookside Par 3 Golf Club'),
  ('United States', 'Brookside resort'),
  ('United States', 'Brookstone Golf Country Club'),
  ('United States', 'Brooksville Country Club'),
  ('United States', 'Brooktrails Golf Course'),
  ('United States', 'Brookview Golf Course'),
  ('United States', 'Brookville Country Club'),
  ('United States', 'Brookwood Golf Club'),
  ('United States', 'Brookwood Golf Course'),
  ('United States', 'Brookwoods Golf Club'),
  ('United States', 'Broomsedge Golf Club'),
  ('United States', 'Brown Acres Golf Course'),
  ('United States', 'Brown County Golf Course'),
  ('United States', 'Brown Deer Golf Club'),
  ('United States', 'Brown Deer Park Golf Course'),
  ('United States', 'Brown''s Run Country Club'),
  ('United States', 'Browns Lake Golf Course'),
  ('United States', 'Browns Mill Golf Course'),
  ('United States', 'Brownson Country Club'),
  ('United States', 'Brownstone Country Club Resort'),
  ('United States', 'Bruce Hills Golf Course'),
  ('United States', 'Brunswick Country Club'),
  ('United States', 'Brunswick Golf Club'),
  ('United States', 'Brunswick Golf Club Azalea Magnolia Course'),
  ('United States', 'Brunswick Golf Club Dogwood Azalea Course'),
  ('United States', 'Brunswick Golf Club Magnolia Dogwood'),
  ('United States', 'Brunswick Greens Golf Course'),
  ('United States', 'Brush Creek Golf Course'),
  ('United States', 'Brushy Mountain Golf Club'),
  ('United States', 'Brute At Grand Geneva Resort Spa'),
  ('United States', 'Bryan Park Champions Course'),
  ('United States', 'Bryan Park Players Course'),
  ('United States', 'Bryce Resort'),
  ('United States', 'Bryden Canyon Public Golf Course'),
  ('United States', 'Bryn Mawr Country Club'),
  ('United States', 'Buckeye Hills Country Club'),
  ('United States', 'Buckhorn Springs Golf Country Club'),
  ('United States', 'Buckingham Golf Country Club'),
  ('United States', 'Buckmeadow Golf Club'),
  ('United States', 'Bucknell Golf Club'),
  ('United States', 'Bucks Run Golf Club'),
  ('United States', 'Buckskin Golf Club'),
  ('United States', 'Bucksport Golf Club'),
  ('United States', 'Buena Vista Country Club'),
  ('United States', 'Buena Vista Golf Course'),
  ('United States', 'Buena Vista University Golf Course at Lake Creek'),
  ('United States', 'Buenaventura Golf Course'),
  ('United States', 'Buffalo Creek Golf Course'),
  ('United States', 'Buffalo Dunes Golf Course'),
  ('United States', 'Buffalo Golf Course'),
  ('United States', 'Buffalo Grove Golf Club'),
  ('United States', 'Buffalo Heights Golf Course'),
  ('United States', 'Buffalo Ridge Springs Golf Course'),
  ('United States', 'Buffalo Rock Golf Venue'),
  ('United States', 'Buffalo Run Golf Course'),
  ('United States', 'Buffalo Tournament Club'),
  ('United States', 'Buffalo Trace Golf Course'),
  ('United States', 'Buffalo Valley Golf Course'),
  ('United States', 'Buffer Park Golf Course'),
  ('United States', 'Buhl Farm Golf Course Driving Range'),
  ('United States', 'Bull Run Golf Club'),
  ('United States', 'Bull Valley Golf Club'),
  ('United States', 'Bull''s Eye Country Club'),
  ('United States', 'Bulls Bay Golf Club'),
  ('United States', 'Bulls Bridge Golf Club'),
  ('United States', 'Buncombe Creek Golf Course'),
  ('United States', 'Bungay Brook Golf Club'),
  ('United States', 'Bunker Hill Golf Course'),
  ('United States', 'Bunker Hills Executive Course'),
  ('United States', 'Bunker Hills Golf Course'),
  ('United States', 'Bunker Links Golf Course'),
  ('United States', 'Bunn Golf Course'),
  ('United States', 'Bur Mil Park Golf Course'),
  ('United States', 'Burden Lake Country Club'),
  ('United States', 'Burgis Back Nine'),
  ('United States', 'Burgundy Bay Golf Course'),
  ('United States', 'Burke Golf Course'),
  ('United States', 'Burke Lake Golf Center'),
  ('United States', 'Burl Oaks Golf Club'),
  ('United States', 'Burlingame Country Club'),
  ('United States', 'Burlington Country Club'),
  ('United States', 'Burlington Golf Club'),
  ('United States', 'Burnet Park Golf Course'),
  ('United States', 'Burnham Woods Golf Course'),
  ('United States', 'Burning Oak Country Club'),
  ('United States', 'Burning Ridge Golf Course'),
  ('United States', 'Burning Tree Country Club'),
  ('United States', 'Burning Tree Golf Club'),
  ('United States', 'Burnt Pine At Sandestin Golf And Beach Resort'),
  ('United States', 'Burr Oak Golf Club'),
  ('United States', 'Bushwood Golf Course'),
  ('United States', 'Butler Country Club'),
  ('United States', 'Butler National Golf Club'),
  ('United States', 'Butlers Golf Course Lakeside Course'),
  ('United States', 'Butlers Golf Course Woodside Course'),
  ('United States', 'Butte Country Club'),
  ('United States', 'Butte Creek Country Club'),
  ('United States', 'Butte des Morts Country Club'),
  ('United States', 'Butter Valley Golf Port'),
  ('United States', 'Butterbrook Golf Club'),
  ('United States', 'Butterfield Country Club'),
  ('United States', 'Butterfield Golf Course'),
  ('United States', 'Butterfield Trail Golf Club'),
  ('United States', 'Buttermilk Falls Golf Club'),
  ('United States', 'Butternut Creek Golf Course'),
  ('United States', 'Butternut Farm Golf Club'),
  ('United States', 'Butternut Hills Golf Course'),
  ('United States', 'Butternut Valley Golf'),
  ('United States', 'Button Hole Short Course Teaching Center'),
  ('United States', 'Buttonwood Golf Course'),
  ('United States', 'Byrd At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Byrncliff Golf Resort Banquets'),
  ('United States', 'Byron Hills Golf Course'),
  ('United States', 'C Way Golf Club'),
  ('United States', 'CNC Links'),
  ('United States', 'Cabarrus Country Club'),
  ('United States', 'Caberfae Peaks'),
  ('United States', 'Cabin Creek Golf Club'),
  ('United States', 'Cabin Greens Golf Course'),
  ('United States', 'Cabinet View Country Club'),
  ('United States', 'Cable Hollow Golf Course'),
  ('United States', 'Cabot Citrus Farms Karoo Course'),
  ('United States', 'Cabot Citrus Farms The Roost Course'),
  ('United States', 'Cabot Citrus Farms The Squeeze Course'),
  ('United States', 'Cabot Citrus Farms The Wedge Course'),
  ('United States', 'Cabot Links'),
  ('United States', 'Cacapon Resort State Park'),
  ('United States', 'Caddie Shack'),
  ('United States', 'Caddo Creek Golf Club'),
  ('United States', 'Cadillac Country Club'),
  ('United States', 'Cadiz Country Club'),
  ('United States', 'Caesars Pocono Palace Cove Haven'),
  ('United States', 'Cajun Pines Golf Course'),
  ('United States', 'Calabasas Golf Country Club'),
  ('United States', 'Calderone Farms Golf Club'),
  ('United States', 'Caldwell Country Club'),
  ('United States', 'Caldwell Golf Course'),
  ('United States', 'Caledonia Country Club'),
  ('United States', 'Caledonia Golf Club'),
  ('United States', 'Caledonia Golf Fish Club'),
  ('United States', 'Calhoun Elks Lodge Golf Club'),
  ('United States', 'Calhoun Hills Golf Complex'),
  ('United States', 'Caliente Springs Resort'),
  ('United States', 'California City Municipal Par 3 Golf Course'),
  ('United States', 'California Country Club'),
  ('United States', 'California Golf Club Of San Francisco'),
  ('United States', 'California Golf Course'),
  ('United States', 'California Oaks Golf Course'),
  ('United States', 'Callahan Golf Links'),
  ('United States', 'Callier Springs Country Club'),
  ('United States', 'Callippe Preserve Golf Course'),
  ('United States', 'Caloosa Golf Country Club'),
  ('United States', 'Calumet Country Club'),
  ('United States', 'Calumet Golf Club'),
  ('United States', 'Calusa Country Club'),
  ('United States', 'Calusa Country Club 12 Hole Course'),
  ('United States', 'Calusa Lakes Golf Club'),
  ('United States', 'Calusa Pines Golf Club'),
  ('United States', 'Calvert Crossing Golf Club'),
  ('United States', 'Cam2 Golf Club At Springview'),
  ('United States', 'Camaloch Golf Club'),
  ('United States', 'Camargo Club'),
  ('United States', 'Camarillo Springs Golf Course'),
  ('United States', 'Camas Meadows Golf Club'),
  ('United States', 'Cambrian Hills Golf Course'),
  ('United States', 'Cambridge Country Club'),
  ('United States', 'Camden Country Club'),
  ('United States', 'Camelback Golf Club Ambiente Course'),
  ('United States', 'Camelback Golf Club Padre Course'),
  ('United States', 'Camelia Boganvilia Golf Course At Cleveland Heights Golf Club'),
  ('United States', 'Cameron At Buffalo Hill Golf Club'),
  ('United States', 'Cameron Park Country Club'),
  ('United States', 'Camillus Golf Club'),
  ('United States', 'Camino Heights Golf Course'),
  ('United States', 'Camp Creek Golf Club'),
  ('United States', 'Camp Robinson Duffers Club'),
  ('United States', 'Campbells Scottish Highlands Golf Course'),
  ('United States', 'Campestre De Nogales'),
  ('United States', 'Camroden Golf Course'),
  ('United States', 'Canaan Country Club'),
  ('United States', 'Canadian Golf Club'),
  ('United States', 'Canajoharie Country Club'),
  ('United States', 'Canandaigua Country Club'),
  ('United States', 'Canasawacta Country Club'),
  ('United States', 'Candia Woods Golf Links'),
  ('United States', 'Candler Hills Golf Club'),
  ('United States', 'Candler Park Golf Course'),
  ('United States', 'Candlestone'),
  ('United States', 'Candlewood Country Club'),
  ('United States', 'Candlewood Golf Club'),
  ('United States', 'Candlewood Lake Club'),
  ('United States', 'Candlewood Valley Country Club'),
  ('United States', 'Cando Golf Club'),
  ('United States', 'Cane Garden Country Club Allamanda Hibiscus Course'),
  ('United States', 'Cane Garden Country Club Hibiscus Jacaranda Course'),
  ('United States', 'Cane Garden Country Club Jacaranda Allamanda Course'),
  ('United States', 'Cane Patch Par 3 Blue Nine'),
  ('United States', 'Cane Patch Par 3 Red Nine'),
  ('United States', 'Cane Patch Par 3 Yellow Nine'),
  ('United States', 'Cane Row Golf Turf Club'),
  ('United States', 'Canebrake Golf Club'),
  ('United States', 'Caney Golf Club'),
  ('United States', 'Cannon Golf Club'),
  ('United States', 'Cannonball Golf Course'),
  ('United States', 'Cannongate Golf At Sun City Peachtree'),
  ('United States', 'Canoa Hills Golf Course'),
  ('United States', 'Canoa Ranch Golf Club'),
  ('United States', 'Canongate Golf Club Lee Wilson Course'),
  ('United States', 'Canongate Golf Club Roquemore Burton Course'),
  ('United States', 'Canterbury Golf Club'),
  ('United States', 'Canterbury Green Golf Course'),
  ('United States', 'Canterbury Woods Country Club'),
  ('United States', 'Canterwood Golf Club'),
  ('United States', 'Cantiague Park Golf Course'),
  ('United States', 'Cantigny Golf'),
  ('United States', 'Cantigny Golf Youth Links'),
  ('United States', 'Canton Golf Club'),
  ('United States', 'Canyata Golf Club'),
  ('United States', 'Canyon At Forest Highlands Golf Club'),
  ('United States', 'Canyon At Mountain Dell Golf Course'),
  ('United States', 'Canyon Breeze Golf Course'),
  ('United States', 'Canyon Club'),
  ('United States', 'Canyon Crest Country Club'),
  ('United States', 'Canyon Estates Golf Course'),
  ('United States', 'Canyon Farms Golf Club'),
  ('United States', 'Canyon Gate Country Club'),
  ('United States', 'Canyon Hill At La Paloma Country Club'),
  ('United States', 'Canyon Hills Park Golf Course'),
  ('United States', 'Canyon Lake Country Club'),
  ('United States', 'Canyon Lakes At Spanish Trail Country Club'),
  ('United States', 'Canyon Lakes Golf Course'),
  ('United States', 'Canyon Lakes Golf Course Brewery'),
  ('United States', 'Canyon Meadow At Fox Hollow At Lakewood'),
  ('United States', 'Canyon Mesa Country Club'),
  ('United States', 'Canyon Oaks Country Club'),
  ('United States', 'Canyon River Golf Club'),
  ('United States', 'Canyon Springs Golf Course'),
  ('United States', 'Canyons At Oasis Golf Club'),
  ('United States', 'Canyons Golf Course'),
  ('United States', 'Cape Ann Golf Course'),
  ('United States', 'Cape Arundel Golf Club'),
  ('United States', 'Cape Cod Country Club'),
  ('United States', 'Cape Cod National Golf Club'),
  ('United States', 'Cape Fear Country Club'),
  ('United States', 'Cape Fear National At Brunswick Forest'),
  ('United States', 'Cape Girardeau Country Club'),
  ('United States', 'Cape Haze Links At Rotonda Golf Country Club'),
  ('United States', 'Cape Jaycee Municipal Golf Course'),
  ('United States', 'Cape May National Golf Club'),
  ('United States', 'Cape May Par 3 And Driving Range'),
  ('United States', 'Cape Neddick Country Club'),
  ('United States', 'Cape Royal Golf Club King Prince'),
  ('United States', 'Cape Royal Golf Club Prince Queen'),
  ('United States', 'Cape Royal Golf Club Queen King'),
  ('United States', 'Capital Canyon Club'),
  ('United States', 'Capital City Club Crabapple'),
  ('United States', 'Capital City Country Club'),
  ('United States', 'Capital Hills At Albany'),
  ('United States', 'Capitol City Golf Club'),
  ('United States', 'Capon Springs Golf Course'),
  ('United States', 'Capri Isles Golf Club'),
  ('United States', 'Caprock Ranch'),
  ('United States', 'Captains Cove'),
  ('United States', 'Captains Golf Course Port'),
  ('United States', 'Captains Golf Course Starboard'),
  ('United States', 'Captiva Course At South Seas Island Resort'),
  ('United States', 'Carbon Country Club'),
  ('United States', 'Card Inc. Golf & Country Club'),
  ('United States', 'Card Sound Golf Club'),
  ('United States', 'Cardinal At Diamondhead Country Club'),
  ('United States', 'Cardinal At Newport News Golf Club'),
  ('United States', 'Cardinal Country Club'),
  ('United States', 'Cardinal Creek Golf Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Blue Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams Red Course'),
  ('United States', 'Cardinal Golf Club At Fort Gregg Adams White Course'),
  ('United States', 'Cardinal Golf Course'),
  ('United States', 'Cardinal Hills Golf Course'),
  ('United States', 'Carefree Country Club'),
  ('United States', 'Carey Park Golf Course'),
  ('United States', 'Caribou Country Club'),
  ('United States', 'Caribou Highlands Golf And Rv'),
  ('United States', 'Carillon Golf Course'),
  ('United States', 'Carl Dickman Par 3 Golf Course'),
  ('United States', 'Carleton Glen Golf Club'),
  ('United States', 'Carlisle Barracks Golf Course'),
  ('United States', 'Carlisle Country Club'),
  ('United States', 'Carlowden Country Club'),
  ('United States', 'Carlton Oaks Lodge Country Club'),
  ('United States', 'Carmel Valley Ranch Resort'),
  ('United States', 'Carmi Country Club'),
  ('United States', 'Carmichaels Golf Club'),
  ('United States', 'Carnduff Golf Club'),
  ('United States', 'Caro Golf Club'),
  ('United States', 'Carolina Club The'),
  ('United States', 'Carolina Colours Golf Club'),
  ('United States', 'Carolina Country Club'),
  ('United States', 'Carolina Golf Club'),
  ('United States', 'Carolina Golf Par 3 Course'),
  ('United States', 'Carolina Lakes Golf Club'),
  ('United States', 'Carolina Lakes Golf Course'),
  ('United States', 'Carolina Meadows Golf Course'),
  ('United States', 'Carolina National Golf Club Egret Nine'),
  ('United States', 'Carolina National Golf Club Heron Nine'),
  ('United States', 'Carolina National Golf Club Ibis Nine'),
  ('United States', 'Carolina Plantation Golf Club'),
  ('United States', 'Carolina Shores Golf Country Club'),
  ('United States', 'Carolina Springs Golf Club'),
  ('United States', 'Carolinas Country Club'),
  ('United States', 'Caroline Virginia At Mallory Hill Golf Course'),
  ('United States', 'Carriage Greens Golf Club'),
  ('United States', 'Carrington Crossroads Golf Club'),
  ('United States', 'Carrington Golf Club'),
  ('United States', 'Carroll Country Club'),
  ('United States', 'Carroll County Country Club'),
  ('United States', 'Carroll Meadows golf course'),
  ('United States', 'Carroll Municipal Golf Course'),
  ('United States', 'Carroll Valley Golf Resort'),
  ('United States', 'Carrollton Park DGC'),
  ('United States', 'Carrollwood Country Club Cypress Meadows Course')
on conflict (country, name) do nothing;