insert into public.golf_courses (country, name) values
  ('United States', 'Eastpointe Country Club West Course'),
  ('United States', 'Eastward Ho Club'),
  ('United States', 'Eastwood Country Club'),
  ('United States', 'Eastwood Golf Club'),
  ('United States', 'Eastwood Golf Course'),
  ('United States', 'Eaton Canyon Golf Course'),
  ('United States', 'Eaton Country Club'),
  ('United States', 'Eau Claire Golf and Country Club'),
  ('United States', 'Ebensburg Country Club'),
  ('United States', 'Eberhart Petro Golf Course'),
  ('United States', 'Eccentric Duffer Golf Course'),
  ('United States', 'Echelon Golf Club'),
  ('United States', 'Echo Falls Country Club'),
  ('United States', 'Echo HIlls Golf Course'),
  ('United States', 'Echo Hills Golf Club'),
  ('United States', 'Echo Lake Country Club'),
  ('United States', 'Echo Mesa Golf Course At Sun City West'),
  ('United States', 'Echo Valley Country Club'),
  ('United States', 'Eco Golf Course'),
  ('United States', 'Ed Oliver Golf Club'),
  ('United States', 'Edelweiss Chalet Country Club'),
  ('United States', 'Eden Valley Golf Course'),
  ('United States', 'Edgartown Golf Club'),
  ('United States', 'Edge Hill Golf Course'),
  ('United States', 'EdgeBrook Golf Course'),
  ('United States', 'Edgebrook Country Club'),
  ('United States', 'Edgebrook Golf Course'),
  ('United States', 'Edgerton Towne Country Club'),
  ('United States', 'Edgewater Beach Resort Golf Course'),
  ('United States', 'Edgewater Country Club'),
  ('United States', 'Edgewater Golf Club'),
  ('United States', 'Edgewater Golf Course'),
  ('United States', 'Edgewood Club Of Tivoli'),
  ('United States', 'Edgewood Country Club'),
  ('United States', 'Edgewood Golf Club'),
  ('United States', 'Edgewood Golf Club (Closed)'),
  ('United States', 'Edgewood Golf Course'),
  ('United States', 'Edgewood Greens Golf Course'),
  ('United States', 'Edgewood In The Pines'),
  ('United States', 'Edgewood Park Golf Club'),
  ('United States', 'Edgewood Tahoe Golf Course'),
  ('United States', 'Edgewood Valley Country Club'),
  ('United States', 'Edina Country Club'),
  ('United States', 'Edinburgh USA'),
  ('United States', 'Edmore Golf Course'),
  ('United States', 'Edmundson Golf Course'),
  ('United States', 'Edwin Shaw Challenge Golf Course'),
  ('United States', 'Eel River Golf Course'),
  ('United States', 'Eglin Afb Golf Course Eagle'),
  ('United States', 'Eglin Afb Golf Course Falcon'),
  ('United States', 'Egremont Country Club'),
  ('United States', 'Egret Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Egypt Valley Country Club'),
  ('United States', 'Egyptian Country Club'),
  ('United States', 'Eighteen At Bangor Municipal Golf Course'),
  ('United States', 'Eighteen At Bing Maloney Golf Course'),
  ('United States', 'Eighteen At Eagle Crest Golf Course'),
  ('United States', 'Eighteen At Hi Level Golf Course'),
  ('United States', 'Eighteen At Race Brook Country Club'),
  ('United States', 'Eighteen At Tri Palm Country Club'),
  ('United States', 'Eighteen At White Birch Golf Course'),
  ('United States', 'Eighteen Hole At Balboa Park Municipal Golf Club'),
  ('United States', 'Eighteen Hole At Bright Leaf Golf Resort'),
  ('United States', 'Eighteen Hole At Cherry Hills Country Club'),
  ('United States', 'Eighteen Hole At Harder Hall Country Club'),
  ('United States', 'Eighteen Hole At Holiday Island Country Club'),
  ('United States', 'Eighteen Hole At Indian Tree Golf Club'),
  ('United States', 'Eighteen Hole At On Top Of The World Golf Club'),
  ('United States', 'Eighteen Hole At Pine Hills Country Club'),
  ('United States', 'Eighteen Hole At Pittsburgh North Golf Club'),
  ('United States', 'Eighteen Hole At Riverbend Golf Complex'),
  ('United States', 'Eighteen Hole At South Park Golf Course'),
  ('United States', 'Eighteen Hole At South Suburban Golf Course'),
  ('United States', 'Eighteen Hole At Van Nuys Golf Course'),
  ('United States', 'Eighteen Hole At Village Links Of Glen Ellyn'),
  ('United States', 'Eighteen Hole At Villages Golf Country Club'),
  ('United States', 'Eighteen Hole Executive At Outdoor Resort Country Club'),
  ('United States', 'Eighteen Hole Regulation At Pipestem State Park Resort'),
  ('United States', 'Eighteen Hole Regulation At Santa Teresa Golf Club'),
  ('United States', 'Eisenhower Lakes Golf Club Island View Nine'),
  ('United States', 'Eisenhower Lakes Golf Club Lake View Nine'),
  ('United States', 'Eisenhower Lakes Golf Club Pine View Nine'),
  ('United States', 'Ekwanok Country Club'),
  ('United States', 'El Caballero Country Club'),
  ('United States', 'El Camino Country Club'),
  ('United States', 'El Cariso Golf Course'),
  ('United States', 'El Cielo Los Lagos At Desert Princess Country Club'),
  ('United States', 'El Conquistador Golf Tennis Canada Course'),
  ('United States', 'El Conquistador Golf Tennis Conquistador Course'),
  ('United States', 'El Conquistador Golf Tennis Pusch X9 Course'),
  ('United States', 'El Diablo At The Villages Executive Golf Trail'),
  ('United States', 'El Dorado Golf Country Club'),
  ('United States', 'El Dorado Golf Course'),
  ('United States', 'El Dorado Park Golf Club'),
  ('United States', 'El Macero Country Club'),
  ('United States', 'El Monte Golf Course'),
  ('United States', 'El Niguel Country Club'),
  ('United States', 'El Paso Country Club'),
  ('United States', 'El Paso Golf Club'),
  ('United States', 'El Prado Golf Courses Butterfield Stage'),
  ('United States', 'El Prado Golf Courses Chino Creek'),
  ('United States', 'El Rio Golf Club'),
  ('United States', 'El Rio Golf Course'),
  ('United States', 'El Santiago At The Villages Executive Golf Trail'),
  ('United States', 'El Valle Escondido Golf Course'),
  ('United States', 'El Zagal Golf Course'),
  ('United States', 'Elbel Golf Course'),
  ('United States', 'Elberton Country Club'),
  ('United States', 'Elcona Country Club'),
  ('United States', 'Eldorado'),
  ('United States', 'Eldorado Country Club'),
  ('United States', 'Elephant Rocks At Williams'),
  ('United States', 'Elgin Country Club'),
  ('United States', 'Elizabeth Lake Country Club'),
  ('United States', 'Elizabeth Manor Country Club'),
  ('United States', 'Elk City Golf Country Club'),
  ('United States', 'Elk Course At Breckenridge Golf Club'),
  ('United States', 'Elk Creek Country Club'),
  ('United States', 'Elk Hollow Golf Course'),
  ('United States', 'Elk Rapids Golf Club'),
  ('United States', 'Elk Ridge Golf Club'),
  ('United States', 'Elk Ridge Golf Course'),
  ('United States', 'Elk River Club'),
  ('United States', 'Elk River Country Club'),
  ('United States', 'Elk River Golf Club'),
  ('United States', 'Elk Run Golf Club'),
  ('United States', 'Elk Valley Golf Course'),
  ('United States', 'Elkader Golf and Country Club'),
  ('United States', 'Elkdale Country Club'),
  ('United States', 'Elkhorn Golf Club'),
  ('United States', 'Elkhorn Golf Club At Sun Valley'),
  ('United States', 'Elkhorn Ridge Golf Course'),
  ('United States', 'Elkhorn Valley Golf Course'),
  ('United States', 'Elks Club Marion IN'),
  ('United States', 'Elks Country Club'),
  ('United States', 'Elks Fairview Golf Club'),
  ('United States', 'Elks Golf Club'),
  ('United States', 'Elks Golf Country Club'),
  ('United States', 'Elks Lodge Country Club'),
  ('United States', 'Elks Lodge Par 3 Golf Course'),
  ('United States', 'Elks Run Golf Club'),
  ('United States', 'Elkview Country Club'),
  ('United States', 'Ella Sharp Park Golf Course'),
  ('United States', 'Ellendale Country Club'),
  ('United States', 'Ellensburg Golf Club'),
  ('United States', 'Ellington Ridge Country Club'),
  ('United States', 'Ellinwood Country Club'),
  ('United States', 'Ellis Country Club'),
  ('United States', 'Ellis Golf Course'),
  ('United States', 'Ellsworth Country Club'),
  ('United States', 'Ellsworth Golf Municipal Course'),
  ('United States', 'Ellsworth Meadows Golf Club'),
  ('United States', 'Elm Lake Golf Course'),
  ('United States', 'Elm Tree Golf Course'),
  ('United States', 'Elma Meadows Golf Club'),
  ('United States', 'Elmbrook Golf Course'),
  ('United States', 'Elmcrest Country Club'),
  ('United States', 'Elmcrest Golf & Country Club'),
  ('United States', 'Elmhurst Country Club'),
  ('United States', 'Elmira Country Club'),
  ('United States', 'Elms Country Club'),
  ('United States', 'Elmwood Country Club'),
  ('United States', 'Elmwood Golf Course'),
  ('United States', 'Elmwood Golf Course 9 Hole Course'),
  ('United States', 'Elmwood Park Golf Course'),
  ('United States', 'Elwood Golf Course'),
  ('United States', 'Ely Golf Club'),
  ('United States', 'Ely Park Muni Golf Course'),
  ('United States', 'Elyria Country Club'),
  ('United States', 'Emanon Country Club'),
  ('United States', 'Emeis Golf Course'),
  ('United States', 'Emerald Bay Golf Club'),
  ('United States', 'Emerald Canyon Golf Course'),
  ('United States', 'Emerald Crest Golf Course'),
  ('United States', 'Emerald Dunes Golf Club'),
  ('United States', 'Emerald Greens'),
  ('United States', 'Emerald Greens Golf Club'),
  ('United States', 'Emerald Greens Golf Course'),
  ('United States', 'Emerald Hill'),
  ('United States', 'Emerald Hill Golf Course'),
  ('United States', 'Emerald Hills Golf Club'),
  ('United States', 'Emerald Hills Golf Course'),
  ('United States', 'Emerald Isle Golf Course'),
  ('United States', 'Emerald Lake Golf Club'),
  ('United States', 'Emerald Lakes Golf Course'),
  ('United States', 'Emerald Vale Golf Club'),
  ('United States', 'Emerywood Golf Course'),
  ('United States', 'Emmett Golf Course And Event Facilities'),
  ('United States', 'Empire Ranch Golf Club'),
  ('United States', 'Emporia Country Club'),
  ('United States', 'Emporia Municipal Golf Course'),
  ('United States', 'Emporium Country Club'),
  ('United States', 'En Joie Golf Course'),
  ('United States', 'Enagic Golf Club At Eastlake'),
  ('United States', 'Encanterra Country Club'),
  ('United States', 'Encanto Golf Course'),
  ('United States', 'Encanto Nine Golf Course'),
  ('United States', 'Encina Royale Golf Course'),
  ('United States', 'Encinitas Ranch Golf Course'),
  ('United States', 'Encino At Sepulveda Golf Complex'),
  ('United States', 'Endwell Greens Golf Club'),
  ('United States', 'Enger Park Golf Course'),
  ('United States', 'Engineers Country Club'),
  ('United States', 'England Country Club'),
  ('United States', 'English Turn Golf Country Club'),
  ('United States', 'Enosburg Falls Country Club'),
  ('United States', 'Entrada At Snow Canyon'),
  ('United States', 'Enumclaw Golf Course'),
  ('United States', 'Epworth Heights Golf Course'),
  ('United States', 'Equestrian At Polo Club The'),
  ('United States', 'Erie Golf Club'),
  ('United States', 'Erie Shores Golf Club'),
  ('United States', 'Erie Shores Golf Course'),
  ('United States', 'Erin Hills'),
  ('United States', 'Erinn Ashley At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Erskine Golf Course'),
  ('United States', 'Escalon Golf Course'),
  ('United States', 'Escambia At The Villages Executive Golf Trail'),
  ('United States', 'Escanaba Country Club'),
  ('United States', 'Escena Golf Club'),
  ('United States', 'Esmeralda Golf Course'),
  ('United States', 'Esplanade At Azario Lakewood Ranch'),
  ('United States', 'Esplanade At St Marys'),
  ('United States', 'Esplanade Golf And Country Club Of Naples'),
  ('United States', 'Esplanade Golf Country Club At Lakewood Ranch'),
  ('United States', 'Esquagama Golf Course'),
  ('United States', 'Essex Country Club'),
  ('United States', 'Essex County Club'),
  ('United States', 'Essex County Country Club'),
  ('United States', 'Essex Fells Country Club'),
  ('United States', 'Essex Golf Club'),
  ('United States', 'Essex Golf and Country Club'),
  ('United States', 'Essex Park Golf Course'),
  ('United States', 'Estate Golf Club'),
  ('United States', 'Estero Country Club'),
  ('United States', 'Estes Park Golf Course'),
  ('United States', 'Estevan Woodlawn Golf Club'),
  ('United States', 'Estherville Golf Course'),
  ('United States', 'Estuary At River Strand Golf And Country Club'),
  ('United States', 'Etowah Valley Golf Club'),
  ('United States', 'Eufaula Country Club'),
  ('United States', 'Eunice Country Club'),
  ('United States', 'Eunice Municipal Golf Course'),
  ('United States', 'Eupora Country Club'),
  ('United States', 'Eureka Country Club'),
  ('United States', 'Eureka Municipal Golf Course'),
  ('United States', 'Evans Heights Golf Club'),
  ('United States', 'Evans Prairie Country Club Egret Killdeer'),
  ('United States', 'Evans Prairie Country Club Killdeer Osprey'),
  ('United States', 'Evans Prairie Country Club Osprey Egret'),
  ('United States', 'Evanston Golf Club'),
  ('United States', 'Evansville Country Club'),
  ('United States', 'Eveleth Municipal Golf Course'),
  ('United States', 'Everett Golf Country Club'),
  ('United States', 'Everglades Golf Course'),
  ('United States', 'Evergreen 1 At Evergreen Country Club'),
  ('United States', 'Evergreen 2 At Evergreen Country Club'),
  ('United States', 'Evergreen Country Club'),
  ('United States', 'Evergreen Golf Club'),
  ('United States', 'Evergreen Golf Course'),
  ('United States', 'Evergreen Hills Golf Course'),
  ('United States', 'Evergreen Resort'),
  ('United States', 'Evergreen Valley Golf Course'),
  ('United States', 'Ewa Villages Golf Course'),
  ('United States', 'Exchange City Golf Course'),
  ('United States', 'Executive At A C Read Golf Course'),
  ('United States', 'Executive At Bel Aire Golf Club'),
  ('United States', 'Executive At Bing Maloney Golf Course'),
  ('United States', 'Executive At Boca Raton Municipal Golf Course'),
  ('United States', 'Executive At Evergreen Golf Course Inc'),
  ('United States', 'Executive At Ferncroft Country Club'),
  ('United States', 'Executive At Harbor Links Golf Course'),
  ('United States', 'Executive At Harder Hall Country Club'),
  ('United States', 'Executive At Hi Level Golf Course'),
  ('United States', 'Executive At Las Positas Golf Course'),
  ('United States', 'Executive At Lindenwood Golf Club'),
  ('United States', 'Executive At Mick Riley Golf Course'),
  ('United States', 'Executive At Newberry Country Club'),
  ('United States', 'Executive At Rebsamen Park Golf Course'),
  ('United States', 'Executive At Ridgecrest Golf Course'),
  ('United States', 'Executive At Rockland Lake Golf Course'),
  ('United States', 'Executive At Saratoga Spa State Park'),
  ('United States', 'Executive At Seven Springs Country Club'),
  ('United States', 'Executive At Shadow Lake Golf Racquet Club'),
  ('United States', 'Executive At Van Nuys Golf Course'),
  ('United States', 'Executive At Vista Valencia Golf Course'),
  ('United States', 'Executive At White Birch Golf Course'),
  ('United States', 'Executive At White Deer Golf Club'),
  ('United States', 'Executive Nine At High Cedars Golf Club'),
  ('United States', 'Executive South Family Golf Center'),
  ('United States', 'Exeter Country Club'),
  ('United States', 'Exeter Public Golf Course'),
  ('United States', 'Exmoor Country Club'),
  ('United States', 'F E Warren Afb Golf Club'),
  ('United States', 'F H Golf Course'),
  ('United States', 'Fairbanks Golf Country Club'),
  ('United States', 'Fairbanks Ranch Country Club Lakes Ocean Course'),
  ('United States', 'Fairbanks Ranch Country Club Ocean Valley Course'),
  ('United States', 'Fairbanks Ranch Country Club Valley Lakes Course'),
  ('United States', 'Fairbury Country Club'),
  ('United States', 'Fairdale Country Club'),
  ('United States', 'Fairfax Golf Club'),
  ('United States', 'Fairfield Country Club'),
  ('United States', 'Fairfield Fun Center'),
  ('United States', 'Fairfield Golf Club'),
  ('United States', 'Fairfield Golf and Country Club'),
  ('United States', 'Fairfield Hills Golf Course'),
  ('United States', 'Fairfield Plantation Golf Country Club'),
  ('United States', 'Fairgreens Golf Club'),
  ('United States', 'Fairgrounds Golf Center'),
  ('United States', 'Fairlawn Country Club'),
  ('United States', 'Fairlawn Golf Club'),
  ('United States', 'Fairlawn Golf Course'),
  ('United States', 'Fairmont Field Club'),
  ('United States', 'Fairmont Golf Club'),
  ('United States', 'Fairmont Hot Springs Resort'),
  ('United States', 'Fairmont Park Golf Course Country Club'),
  ('United States', 'Fairmount Country Club'),
  ('United States', 'Fairview Country Club'),
  ('United States', 'Fairview Farm Golf Course'),
  ('United States', 'Fairview Golf Course'),
  ('United States', 'Fairview Hills Golf Club'),
  ('United States', 'Fairview Lakeside Country Club'),
  ('United States', 'Fairview Mountain Golf Club'),
  ('United States', 'Fairview Municipal Golf Course'),
  ('United States', 'Fairway Mews Golf Club'),
  ('United States', 'Fairway River Links'),
  ('United States', 'Fairway Valley Golf Club'),
  ('United States', 'Fairway Village Golf Course'),
  ('United States', 'Fairways At Howards Barn'),
  ('United States', 'Fairways At Lincoln'),
  ('United States', 'Fairways Country Club'),
  ('United States', 'Fairways Golf Club'),
  ('United States', 'Fairways Meadows At Centennial Golf Club'),
  ('United States', 'Fairways Of Canton Golf Club'),
  ('United States', 'Fairways Of Halfmoon'),
  ('United States', 'Fairways Of Halfmoon Executive Course'),
  ('United States', 'Fairways of Woodside'),
  ('United States', 'Fairwinds Golf Course'),
  ('United States', 'Fairwood Country Club'),
  ('United States', 'Falcon Creek Golf Course'),
  ('United States', 'Falcon Crest Golf Club Cadet Course'),
  ('United States', 'Falcon Crest Golf Club Championship 18 Course'),
  ('United States', 'Falcon Crest Golf Club Freedom Course'),
  ('United States', 'Falcon Dunes Golf Course'),
  ('United States', 'Falcon Golf Club'),
  ('United States', 'Falcon Golf Course'),
  ('United States', 'Falcon Head Golf Club'),
  ('United States', 'Falcon Lakes Golf Course'),
  ('United States', 'Falcon Pointe Golf Club'),
  ('United States', 'Falcon Ridge Golf Club'),
  ('United States', 'Falcon Ridge Golf Course'),
  ('United States', 'Falcon Valley Golf Course'),
  ('United States', 'Falconhead Resort Country Club'),
  ('United States', 'Falcons Fire Golf Club'),
  ('United States', 'Faldo At Wildfire Golf Club At Desert Ridge Resort'),
  ('United States', 'Falkirk Estate Country Club'),
  ('United States', 'Fall Creek Golf Club'),
  ('United States', 'Fall River Country Club'),
  ('United States', 'Fall River Valley Golf Country Club'),
  ('United States', 'Fallen Oak Golf Course'),
  ('United States', 'Fallen Timbers Fairways'),
  ('United States', 'Falling Creek Country Club'),
  ('United States', 'Falling River Country Club'),
  ('United States', 'Fallon Golf Course'),
  ('United States', 'Falls At Blackhawk Country Club'),
  ('United States', 'Falls City Country Club'),
  ('United States', 'Falls Country Club'),
  ('United States', 'Falls Road Golf Course'),
  ('United States', 'Falls Village Golf Course'),
  ('United States', 'Falmouth Country Club'),
  ('United States', 'Falmouth Country Club Eighteen Hole Course'),
  ('United States', 'Falmouth Country Club Talon Course'),
  ('United States', 'False River Golf Country Club'),
  ('United States', 'Family Golf Learning Center'),
  ('United States', 'Family Sports Golf Course'),
  ('United States', 'Fantasy Valley Golf Course'),
  ('United States', 'Far Corner Golf Fox Heron Course'),
  ('United States', 'Far Corner Golf Hawk Fox Course'),
  ('United States', 'Far Corner Golf Heron Hawk Course'),
  ('United States', 'Far Oaks Golf Club'),
  ('United States', 'Far Vu Golf Course'),
  ('United States', 'Fargo Country Club'),
  ('United States', 'Fargo Recreation Golf Course'),
  ('United States', 'Faribault Golf Club'),
  ('United States', 'Farm Dallie Golf Club'),
  ('United States', 'Farm Golf Club The'),
  ('United States', 'Farm Neck Golf Club'),
  ('United States', 'Farmers Golf & Health Club'),
  ('United States', 'Farmingbury Hills Golf Club'),
  ('United States', 'Farmington Country Club'),
  ('United States', 'Farmington Hills Golf Club'),
  ('United States', 'Farmington Woods Golf Course'),
  ('United States', 'Farmsley Golf Center'),
  ('United States', 'Farmstead Golf Country Club Clubview Valleyview Course'),
  ('United States', 'Farmstead Golf Country Club Lakeview Clubview Course'),
  ('United States', 'Farmstead Golf Country Club Valleyview Lakeview Course'),
  ('United States', 'Farmstead Golf Links'),
  ('United States', 'Farmville Country Club'),
  ('United States', 'Farview Golf Club')
on conflict (country, name) do nothing;