insert into public.golf_courses (country, name) values
  ('United States', 'Carrollwood Country Club Meadows Pines Course'),
  ('United States', 'Carrollwood Country Club Pines Cypress Course'),
  ('United States', 'Carson Valley Golf Course'),
  ('United States', 'Carter Country Club'),
  ('United States', 'Carter Heights Golf Course'),
  ('United States', 'Carter Plantation'),
  ('United States', 'Carters Sweetland Pines Par 3 Golf Course'),
  ('United States', 'Cartersville Country Club'),
  ('United States', 'Carthage Golf Course'),
  ('United States', 'Carthage Municipal Golf Course'),
  ('United States', 'Caruthersville Country Club'),
  ('United States', 'Cary Country Club'),
  ('United States', 'Casablanca Resort Casino'),
  ('United States', 'Cascade Golf Course'),
  ('United States', 'Cascade Hills Country Club'),
  ('United States', 'Cascade Par 3 Golf Club'),
  ('United States', 'Cascades Golf Course'),
  ('United States', 'Cascata'),
  ('United States', 'Caseville Golf Course'),
  ('United States', 'Cashie Golf Country Club'),
  ('United States', 'Casolwood Golf Course'),
  ('United States', 'Casper Country Club'),
  ('United States', 'Casper Golf Club Highlands Links Course'),
  ('United States', 'Casper Golf Club Highlands Park Course'),
  ('United States', 'Casper Golf Club Park Links Course'),
  ('United States', 'Casperkill Golf Club'),
  ('United States', 'Cassadaga Country Club'),
  ('United States', 'Cassel Hills'),
  ('United States', 'Casselberry Golf Club'),
  ('United States', 'Casserly Par 3 Golf Course'),
  ('United States', 'Cassville Golf Club'),
  ('United States', 'Castine Golf Club'),
  ('United States', 'Castle Bay Country Club'),
  ('United States', 'Castle Creek Country Club'),
  ('United States', 'Castle Creek Golf Club'),
  ('United States', 'Castle Highlands Golf Course'),
  ('United States', 'Castle Hills Golf Course'),
  ('United States', 'Castle Oaks Golf Club'),
  ('United States', 'Castle Pines Golf Club'),
  ('United States', 'Castle Rock Golf Course'),
  ('United States', 'Castle Rock Golf Recreation'),
  ('United States', 'Castle Shannon Golf Course'),
  ('United States', 'Castlegar Golf Club'),
  ('United States', 'Castlewood Golf Course'),
  ('United States', 'Castlewoods Country Club The Bear Course'),
  ('United States', 'Caswell Pines Golf Club'),
  ('United States', 'Catalina Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Catalina Island Golf Club'),
  ('United States', 'Catalina Saddlebrooke At Saddlebrooke Country Club'),
  ('United States', 'Catamount Club'),
  ('United States', 'Catamount Ranch And Club'),
  ('United States', 'Catatonk Golf Club'),
  ('United States', 'Catawba Country Club'),
  ('United States', 'Catawba Creek Golf Course'),
  ('United States', 'Catawba Island Club'),
  ('United States', 'Cateechee Golf Club'),
  ('United States', 'Cathedral Canyon Golf Club'),
  ('United States', 'Cato Park'),
  ('United States', 'Catskill Golf Club'),
  ('United States', 'Catta Verdera Country Club'),
  ('United States', 'Cattail Creek Golf Course'),
  ('United States', 'Cattail Crossing Golf Course'),
  ('United States', 'Cattails At Meadowview Golf Course'),
  ('United States', 'Cattails Golf Club'),
  ('United States', 'Causeway Club'),
  ('United States', 'Cavalier Golf Yacht Club'),
  ('United States', 'Cavaliers Country Club'),
  ('United States', 'Cavalry Club'),
  ('United States', 'Cave Creek Golf Course'),
  ('United States', 'Caverns Country Club Resort'),
  ('United States', 'Cazenovia Country Club'),
  ('United States', 'Cazenovia Golf Club'),
  ('United States', 'Cazenovia Golf Course'),
  ('United States', 'Cda National Reserve'),
  ('United States', 'CeCelia''s Golf Course'),
  ('United States', 'Cecil Field Golf Club'),
  ('United States', 'Cedar Aspen At Mccall Golf Course'),
  ('United States', 'Cedar Beach Golf Course'),
  ('United States', 'Cedar Bend Golf Course'),
  ('United States', 'Cedar Chase Golf Club'),
  ('United States', 'Cedar Creek At Star Valley Ranch Country Club'),
  ('United States', 'Cedar Creek Family Golf Center'),
  ('United States', 'Cedar Creek Golf Club'),
  ('United States', 'Cedar Creek Golf Country Club'),
  ('United States', 'Cedar Creek Golf Course'),
  ('United States', 'Cedar Crest Golf Course'),
  ('United States', 'Cedar Farms Golf Club'),
  ('United States', 'Cedar Glen Golf Club'),
  ('United States', 'Cedar Glen Golf Course'),
  ('United States', 'Cedar Hammock Golf Country Club'),
  ('United States', 'Cedar Heights Golf Course'),
  ('United States', 'Cedar Hill Country Club'),
  ('United States', 'Cedar Hill Golf Club'),
  ('United States', 'Cedar Hill Golf Course'),
  ('United States', 'Cedar Hills Golf Club'),
  ('United States', 'Cedar Hills Golf Club Short Course'),
  ('United States', 'Cedar Hills Golf Course'),
  ('United States', 'Cedar Knob Golf Course'),
  ('United States', 'Cedar Lake Club'),
  ('United States', 'Cedar Lake Golf Club'),
  ('United States', 'Cedar Links Country Club'),
  ('United States', 'Cedar Park Golf Course'),
  ('United States', 'Cedar Park Putting Course'),
  ('United States', 'Cedar Pines Golf Course'),
  ('United States', 'Cedar Point Country Club'),
  ('United States', 'Cedar Point Country Club Par 3 Course'),
  ('United States', 'Cedar Point Golf Club'),
  ('United States', 'Cedar Pointe Golf Course'),
  ('United States', 'Cedar Rapids Country Club'),
  ('United States', 'Cedar Ridge Country Club'),
  ('United States', 'Cedar Ridge Golf Course'),
  ('United States', 'Cedar Ridges Golf Course'),
  ('United States', 'Cedar River Golf Club'),
  ('United States', 'Cedar River Golf Course'),
  ('United States', 'Cedar Rock Country Club'),
  ('United States', 'Cedar Springs Golf Course'),
  ('United States', 'Cedar Trace'),
  ('United States', 'Cedar Valley Golf And Country Club'),
  ('United States', 'Cedar Valley Golf Center'),
  ('United States', 'Cedar Valley Golf Club'),
  ('United States', 'Cedar Valley Golf Course'),
  ('United States', 'Cedar View Golf Course'),
  ('United States', 'Cedarbrook Country Club'),
  ('United States', 'Cedarbrook Golf Course'),
  ('United States', 'Cedarcrest Golf Course'),
  ('United States', 'Cedardell Golf Club'),
  ('United States', 'Cedaredge Golf Club'),
  ('United States', 'Cedarholm Golf Course'),
  ('United States', 'Cedars At High Cedars Golf Club'),
  ('United States', 'Cedars Country Club'),
  ('United States', 'Cedars Edge Golf Course'),
  ('United States', 'Cedars Golf Club'),
  ('United States', 'Cedars Golf Country Club'),
  ('United States', 'Cedars Golf Course'),
  ('United States', 'Cedarview Golf Course'),
  ('United States', 'Cedarwood Country Club'),
  ('United States', 'Celebration Golf Club'),
  ('United States', 'Celina Lynx Golf Club'),
  ('United States', 'Centennial Acres Midday Sunset'),
  ('United States', 'Centennial Acres Sunrise Midday'),
  ('United States', 'Centennial Acres Sunrise Sunset'),
  ('United States', 'Centennial At Philadelphia Country Club'),
  ('United States', 'Centennial Farm Golf Club'),
  ('United States', 'Centennial Golf Course'),
  ('United States', 'Centennial Park 9-Hole Golf Course'),
  ('United States', 'Centennial Toomey At Huntingdon Valley Country Club'),
  ('United States', 'Centennial Valley Golf Course'),
  ('United States', 'Center Country Club'),
  ('United States', 'Center West At Ridgewood Country Club The'),
  ('United States', 'Centerbrook Golf Course'),
  ('United States', 'Centerpointe Country Club'),
  ('United States', 'Centerton Golf Club'),
  ('United States', 'Central Valley Golf Club'),
  ('United States', 'Centre Hills Golf Course'),
  ('United States', 'Century Country Club'),
  ('United States', 'Century Oaks Golf Club'),
  ('United States', 'Cerbat Cliffs Golf Course'),
  ('United States', 'Cerritos Ironwood Golf Course'),
  ('United States', 'Chagrin Valley Country Club'),
  ('United States', 'Chalk Mountain Golf Course'),
  ('United States', 'Challenge At Pinewild Country Club'),
  ('United States', 'Challenge At Suntree Country Club'),
  ('United States', 'Challenge At White Deer Golf Club'),
  ('United States', 'Challenger 3 Golf Course'),
  ('United States', 'Challenger At Blue Hill Country Club'),
  ('United States', 'Challenger At Palm Valley Country Club'),
  ('United States', 'Challenger Golf Club Los Cumbres Course'),
  ('United States', 'Challis Golf Course'),
  ('United States', 'Chamberlyne Country Club'),
  ('United States', 'Chambers Bay'),
  ('United States', 'Chambersburg Country Club'),
  ('United States', 'Champaign Country Club'),
  ('United States', 'Champion At Battle Creek Public Golf'),
  ('United States', 'Champion At Fox Ridge Golf Course'),
  ('United States', 'Champion Hill Golf Course'),
  ('United States', 'Champion Hills Club'),
  ('United States', 'Champion Hills Country Club'),
  ('United States', 'Champion Lakes Golf And Country Club'),
  ('United States', 'Champion Lakes Golf Course'),
  ('United States', 'Champions At Palm Aire Country Club'),
  ('United States', 'Champions Golf Course'),
  ('United States', 'Champions Pointe Golf Club'),
  ('United States', 'Champions Retreat Golf Club Nicklaus Bluff Nine'),
  ('United States', 'Champions Retreat Golf Club Palmer Island Nine'),
  ('United States', 'Champions Retreat Golf Club Player Creek Nine'),
  ('United States', 'Champions Run'),
  ('United States', 'Champions Run Country Club'),
  ('United States', 'Championsgate Country Club'),
  ('United States', 'Championsgate Golf Club Champions 9'),
  ('United States', 'Championsgate Golf Club International'),
  ('United States', 'Championsgate Golf Club National'),
  ('United States', 'Championship At Blue Hill Country Club'),
  ('United States', 'Championship At Boca Raton Municipal Golf Course'),
  ('United States', 'Championship At Buffalo Hill Golf Club'),
  ('United States', 'Championship At Burns Park Golf Course'),
  ('United States', 'Championship At Colony West Country Club'),
  ('United States', 'Championship At Cyprian Keyes Golf Club'),
  ('United States', 'Championship At Ferncroft Country Club'),
  ('United States', 'Championship At Harbor Links Golf Course'),
  ('United States', 'Championship At Hollybrook Golf Tennis Club'),
  ('United States', 'Championship At Incline Village Golf Resort'),
  ('United States', 'Championship At Lake Shastina Golf Resort'),
  ('United States', 'Championship At Moon Valley Country Club'),
  ('United States', 'Championship At Palm Valley Country Club'),
  ('United States', 'Championship At Rebsamen Park Golf Course'),
  ('United States', 'Championship At Ridgecrest Golf Course'),
  ('United States', 'Championship At Rockland Lake Golf Course'),
  ('United States', 'Championship At Saint Clair Country Club'),
  ('United States', 'Championship At Saratoga Spa State Park'),
  ('United States', 'Championship At Seven Springs Country Club'),
  ('United States', 'Championship At Viewpoint Golf Resort'),
  ('United States', 'Championship Course At Crosswinds Golf Club'),
  ('United States', 'Championship Golf Course At University Of New Mexico'),
  ('United States', 'Champlain Country Club'),
  ('United States', 'Chandler Golf Course'),
  ('United States', 'Chandler Park Golf Course'),
  ('United States', 'Chanticlair Golf Club'),
  ('United States', 'Chanticleer At Greenville Country Club'),
  ('United States', 'Chantilly National Golf Country Club'),
  ('United States', 'Chaparral Country Club'),
  ('United States', 'Chapel Hill Country Club'),
  ('United States', 'Chapel Hill Golf Course'),
  ('United States', 'Chapel Hills Golf Course'),
  ('United States', 'Chappell Golf Course'),
  ('United States', 'Chardell Golf Course'),
  ('United States', 'Chardon Lakes Golf Course'),
  ('United States', 'Chardonnay Golf Club'),
  ('United States', 'Chariot Run'),
  ('United States', 'Charles River Country Club'),
  ('United States', 'Charles T Myers Public Golf Course'),
  ('United States', 'Charleston Municipal Golf Course'),
  ('United States', 'Charleston National Golf Club'),
  ('United States', 'Charleston Pines At Lima Golf Country Club'),
  ('United States', 'Charleston Springs Golf Course North Course'),
  ('United States', 'Charleston Springs Golf Course South Course'),
  ('United States', 'Charlevoix Municipal Golf Course'),
  ('United States', 'Charlie Vettner Golf Course'),
  ('United States', 'Charlie Yates Golf Course'),
  ('United States', 'Charlotte Country Club'),
  ('United States', 'Charlotte Harbor National Golf Club'),
  ('United States', 'Charlotte National Golf Course'),
  ('United States', 'Charter Oak Country Club'),
  ('United States', 'Chartiers Country Club'),
  ('United States', 'Charwood Golf Club'),
  ('United States', 'Chase Golf Course'),
  ('United States', 'Chase Hammond Golf Club'),
  ('United States', 'Chaska Golf Course'),
  ('United States', 'Chaska Par 30'),
  ('United States', 'Chaska Town Course'),
  ('United States', 'Chastain Park Golf Course'),
  ('United States', 'Chatata Valley Golf Club'),
  ('United States', 'Chateau Elan Golf Club Chateau Course'),
  ('United States', 'Chateau Elan Golf Club Executive Par 3 Course'),
  ('United States', 'Chateau Elan Golf Club Woodlands Course'),
  ('United States', 'Chateau Golf Country Club'),
  ('United States', 'Chatham Hills Golf Course'),
  ('United States', 'Chatham Seaside Links'),
  ('United States', 'Chatmoss Country Club'),
  ('United States', 'Chattahoochee Golf Club'),
  ('United States', 'Chattanooga Golf Country Club'),
  ('United States', 'Chattooga Golf Club'),
  ('United States', 'Chatuge Shores Golf Course'),
  ('United States', 'Chautauqua Golf Club Hill Course'),
  ('United States', 'Chautauqua Golf Club Lake Course'),
  ('United States', 'Chautauqua Point Golf Racquetball Center'),
  ('United States', 'Cheam Mountain Golf Course'),
  ('United States', 'Cheboygan Golf & Country Club'),
  ('United States', 'Chechessee Creek Club'),
  ('United States', 'Cheeca Lodge'),
  ('United States', 'Cheena Star Course At Santa Ana Golf Club'),
  ('United States', 'Chelmsford Country Club'),
  ('United States', 'Chemawa Golf Course'),
  ('United States', 'Chemung Golf Course'),
  ('United States', 'Chemung Hills Golf Club'),
  ('United States', 'Chena Bend Golf Course'),
  ('United States', 'Chenal Country Club Bear Den Mountain Course'),
  ('United States', 'Chenal Country Club Founders Course'),
  ('United States', 'Chenango Commons Golf Course'),
  ('United States', 'Chenango Valley State Park Golf Course'),
  ('United States', 'Chenequa Country Club'),
  ('United States', 'Chennault Park Golf Course'),
  ('United States', 'Chenoweth'),
  ('United States', 'Chequamegon Bay Golf Club'),
  ('United States', 'Chequessett Yacht Country Club'),
  ('United States', 'Cheraw State Park Golf Course'),
  ('United States', 'Cherokee Choctaw At Big Canoe Golf Club'),
  ('United States', 'Cherokee Creek Golf Club'),
  ('United States', 'Cherokee Golf Center'),
  ('United States', 'Cherokee Golf Country Club'),
  ('United States', 'Cherokee Golf Course'),
  ('United States', 'Cherokee Golf and Country Club'),
  ('United States', 'Cherokee Hills Golf Club'),
  ('United States', 'Cherokee Hills Golf Course'),
  ('United States', 'Cherokee National Golf Course'),
  ('United States', 'Cherokee Plantation'),
  ('United States', 'Cherokee Rose Country Club'),
  ('United States', 'Cherokee Run Golf Club'),
  ('United States', 'Cherokee Seminole At Indian Hills Country Club'),
  ('United States', 'Cherokee Springs Golf Club'),
  ('United States', 'Cherokee Trails Golf Course'),
  ('United States', 'Cherokee Valley Course And Club'),
  ('United States', 'Cherokee Valley Golf Club'),
  ('United States', 'Cherry Creek Golf Club'),
  ('United States', 'Cherry Creek Golf Course'),
  ('United States', 'Cherry Creek Golf The Links Course'),
  ('United States', 'Cherry Creek The Woods Course'),
  ('United States', 'Cherry Hill Country Club'),
  ('United States', 'Cherry Hill Golf Club'),
  ('United States', 'Cherry Hill Golf Course'),
  ('United States', 'Cherry Hill Golf Resort'),
  ('United States', 'Cherry Hills Course At Palmer Legends'),
  ('United States', 'Cherry Hills Golf Course'),
  ('United States', 'Cherry Island Golf Course'),
  ('United States', 'Cherry Oaks Golf Club'),
  ('United States', 'Cherry Ridge'),
  ('United States', 'Cherry Ridge Golf Course'),
  ('United States', 'Cherry Valley Club'),
  ('United States', 'Cherry Valley Country Club'),
  ('United States', 'Cherry Valley Golf Course'),
  ('United States', 'Cherryville Country Club'),
  ('United States', 'Cherrywood Golf Club'),
  ('United States', 'Cherrywood Golf Course'),
  ('United States', 'Chesapeake Bay Golf Club At Rising Sun'),
  ('United States', 'Chesapeake Golf Club'),
  ('United States', 'Chesapeake Hills Golf Club'),
  ('United States', 'Chesapeake Run Golf Club'),
  ('United States', 'Cheshire Hills Golf Course'),
  ('United States', 'Chesnee Country Club'),
  ('United States', 'Chestatee Golf Club'),
  ('United States', 'Chester Country Club'),
  ('United States', 'Chester Golf Club'),
  ('United States', 'Chester River Yacht Country Club'),
  ('United States', 'Chester Valley Golf Club'),
  ('United States', 'Chester Washington Golf Course'),
  ('United States', 'Chestnut Hill Golf Course'),
  ('United States', 'Chestnut Hills'),
  ('United States', 'Chestnut Hills Golf Club'),
  ('United States', 'Chestnut Mountain Golf Club'),
  ('United States', 'Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Chestnut Valley Golf Course'),
  ('United States', 'Chetremon Golf Course'),
  ('United States', 'Cheval Golf And Athletic Club'),
  ('United States', 'Chevy Chase Club'),
  ('United States', 'Chevy Chase Country Club'),
  ('United States', 'Chevy Chase Golf Club'),
  ('United States', 'Chewelah Golf Country Club'),
  ('United States', 'Chewelah Golf Country Club 9 Hole Course'),
  ('United States', 'Cheyenne Country Club'),
  ('United States', 'Cheyenne Golf Course'),
  ('United States', 'Cheyenne Hills Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course'),
  ('United States', 'Cheyenne Shadows Golf Course Coyote Run Junior'),
  ('United States', 'Chi Chi Rodriguez Golf Club'),
  ('United States', 'Chicago Golf Association'),
  ('United States', 'Chicago Golf Club'),
  ('United States', 'Chicago Heights Park District Golf Course East'),
  ('United States', 'Chicago Heights Park District Golf Course West'),
  ('United States', 'Chicago Highlands Club'),
  ('United States', 'Chick Evans Golf Course'),
  ('United States', 'Chickasaw Country Club'),
  ('United States', 'Chickasaw Point Golf Course'),
  ('United States', 'Chickasaw Pointe Golf Club'),
  ('United States', 'Chickasha Golf Country Club'),
  ('United States', 'Chicopee Country Club'),
  ('United States', 'Chicopee Woods Golf Course Mill Nine'),
  ('United States', 'Chicopee Woods Golf Course School Nine'),
  ('United States', 'Chicopee Woods Golf Course Village Nine'),
  ('United States', 'Chicora Country Club'),
  ('United States', 'Chiefland Golf Country Club'),
  ('United States', 'Chikaming Country Club'),
  ('United States', 'Childress Country Club'),
  ('United States', 'Chilliwack Golf Club'),
  ('United States', 'Chimera Golf Club'),
  ('United States', 'Chimney Oaks Golf Club'),
  ('United States', 'Chimney Rock Municipal Golf Course'),
  ('United States', 'China Lake Golf Course'),
  ('United States', 'Chinook Golf Country Club'),
  ('United States', 'Chip''s Clubhouse'),
  ('United States', 'Chipeta Golf Course'),
  ('United States', 'Chippanee Golf Club'),
  ('United States', 'Chippendale Golf Course'),
  ('United States', 'Chippers Practice Range'),
  ('United States', 'Chippewa Banks Disc Golf Course'),
  ('United States', 'Chippewa Golf Club'),
  ('United States', 'Chippewa Hills Country Club'),
  ('United States', 'Chiricahua Course At Desert Mountain Golf Club'),
  ('United States', 'Chisel Creek Golf Club'),
  ('United States', 'Chisholm Hills Country Club'),
  ('United States', 'Chockoyotte Country Club'),
  ('United States', 'Choctaw Cherokee At Indian Hills Country Club'),
  ('United States', 'Choctaw Country Club'),
  ('United States', 'Choctaw Creek At Big Canoe Golf Club'),
  ('United States', 'Choctaw Creek Golf Course'),
  ('United States', 'Cholla Course At We Ko Pa Golf Club'),
  ('United States', 'Chomonix Golf Course'),
  ('United States', 'Chosen Valley Golf Club'),
  ('United States', 'Choteau Country Club'),
  ('United States', 'Chris Bargas Golf Club At Whitney Farms'),
  ('United States', 'Christiana Creek Country Club'),
  ('United States', 'Christina Lake Golf Club')
on conflict (country, name) do nothing;