insert into public.golf_courses (country, name) values
  ('United States', 'Riverside At Greenville Country Club'),
  ('United States', 'Riverside At Juniper Hill Golf Course'),
  ('United States', 'Riverside Country Club'),
  ('United States', 'Riverside Golf & Recreation'),
  ('United States', 'Riverside Golf Academy'),
  ('United States', 'Riverside Golf Center'),
  ('United States', 'Riverside Golf Centre'),
  ('United States', 'Riverside Golf Club'),
  ('United States', 'Riverside Golf Country Club'),
  ('United States', 'Riverside Golf Course'),
  ('United States', 'Riverside Golf Course North Course'),
  ('United States', 'Riverside Golf Course Practice Course'),
  ('United States', 'Riverside Golf Course South Course'),
  ('United States', 'Riverside Greens'),
  ('United States', 'Riverside Municipal Golf Course'),
  ('United States', 'Riverside Of Fresno Golf Course'),
  ('United States', 'Riverside Recreation Golf Course'),
  ('United States', 'Riverton Country Club'),
  ('United States', 'Riverton Golf Club'),
  ('United States', 'Riverton Pointe Golf And Country Club'),
  ('United States', 'Rivertowne Country Club'),
  ('United States', 'Riverview Country Club'),
  ('United States', 'Riverview Golf Club'),
  ('United States', 'Riverview Golf Country Club'),
  ('United States', 'Riverview Golf Course'),
  ('United States', 'Riverview Highlands Golf Course'),
  ('United States', 'Riverview Park Golf Course'),
  ('United States', 'Riverview Rv Resort'),
  ('United States', 'Riverwalk Golf Club'),
  ('United States', 'Riverwalk Golf Club Sunset 9'),
  ('United States', 'Riverwood Golf Club'),
  ('United States', 'Riverwood Golf Club Deer Run Riverview Course'),
  ('United States', 'Riverwood Golf Club Meadowlands Deer Run Course'),
  ('United States', 'Riverwood Golf Club Riverview Meadowlands Course'),
  ('United States', 'Riverwood National'),
  ('United States', 'Riverwood Resort'),
  ('United States', 'Riverwoods'),
  ('United States', 'Riviera Country Club'),
  ('United States', 'Riviera Hills Golf And Country Club'),
  ('United States', 'Roadhaven Golf Course'),
  ('United States', 'Roadrunner Dunes Golf Course'),
  ('United States', 'Roadrunner Golf Country Club'),
  ('United States', 'Roane County Country Club'),
  ('United States', 'Roanoke Country Club'),
  ('United States', 'Roaring Fork Club'),
  ('United States', 'Roaring Gap Golf Club'),
  ('United States', 'Rob Roy Golf Club'),
  ('United States', 'Robbers Row At Port Royal Golf Club'),
  ('United States', 'Robbinhurst Golf Club'),
  ('United States', 'Robersonville Country Club'),
  ('United States', 'Robert A. Black Golf Course'),
  ('United States', 'Robert Cupp At Palmetto Hall Plantation'),
  ('United States', 'Robert Moses Golf Course'),
  ('United States', 'Robert T Lynch Municipal Brookline Golf Course'),
  ('United States', 'Robert Trent Jones Golf Club'),
  ('United States', 'Robert Trent Jones Golf Course Cornell University'),
  ('United States', 'Robertshaw Acres Golf Club'),
  ('United States', 'Robson Ranch Golf Club'),
  ('United States', 'Rochelle Country Club'),
  ('United States', 'Rochelle Ranch Golf Course'),
  ('United States', 'Rochester Country Club'),
  ('United States', 'Rochester Golf & Country Club'),
  ('United States', 'Rochester Golf Club'),
  ('United States', 'Rochester Place Golf Club'),
  ('United States', 'Rock Barn Golf And Spa Jackson Course'),
  ('United States', 'Rock Barn Golf And Spa Jones Course'),
  ('United States', 'Rock Creek Cattle Company'),
  ('United States', 'Rock Creek Country Club'),
  ('United States', 'Rock Creek Golf And Country Club'),
  ('United States', 'Rock Creek Golf Club'),
  ('United States', 'Rock Creek Golf Course'),
  ('United States', 'Rock Creek Park Golf'),
  ('United States', 'Rock Harbor Golf Course Boulder'),
  ('United States', 'Rock Harbor Golf Course Rock'),
  ('United States', 'Rock Hill Country Club'),
  ('United States', 'Rock Hill Golf Country Club'),
  ('United States', 'Rock Hollow Golf Course'),
  ('United States', 'Rock Island Golf Course'),
  ('United States', 'Rock Manor Golf Club'),
  ('United States', 'Rock Port Golf and Country Club'),
  ('United States', 'Rock Ridge Country Club'),
  ('United States', 'Rock Ridge Golf Course'),
  ('United States', 'Rock River Golf Course'),
  ('United States', 'Rock River Hills Golf Course'),
  ('United States', 'Rock Spring Golf Club'),
  ('United States', 'Rock Spring Golf Course'),
  ('United States', 'Rock Valley Golf Club'),
  ('United States', 'Rockaway Hunting Golf Course'),
  ('United States', 'Rockaway River Country Club'),
  ('United States', 'Rockfish Golf Course'),
  ('United States', 'Rockford Country Club'),
  ('United States', 'Rockingham Country Club'),
  ('United States', 'Rockland Country Club'),
  ('United States', 'Rockland Golf Club'),
  ('United States', 'Rockland Golf Course'),
  ('United States', 'Rockledge Country Club'),
  ('United States', 'Rockleigh Golf Course Blue'),
  ('United States', 'Rockleigh Golf Course Red White'),
  ('United States', 'Rockport Golf Club'),
  ('United States', 'Rockrimmon Country Club'),
  ('United States', 'Rockville Links Club'),
  ('United States', 'Rockwind Community Links Championship Course'),
  ('United States', 'Rockwind Community Links Lil Rock Par 3 Course'),
  ('United States', 'Rocky Bayou Country Club'),
  ('United States', 'Rocky Branch Golf Club'),
  ('United States', 'Rocky Creek Golf Club'),
  ('United States', 'Rocky Ford Golf Course'),
  ('United States', 'Rocky Ford Par 3'),
  ('United States', 'Rocky Gap Casino Resort'),
  ('United States', 'Rocky Knoll Country Club'),
  ('United States', 'Rocky Lakes Golf Course'),
  ('United States', 'Rocky Point Golf Course'),
  ('United States', 'Rocky Ridge Golf Club'),
  ('United States', 'Rocky River Golf Club At Concord'),
  ('United States', 'Rocky Run Golf Course'),
  ('United States', 'Rocky Spring Golf Course'),
  ('United States', 'Rogala Public Links'),
  ('United States', 'Rogers City Country Club'),
  ('United States', 'Rogers Gardens Golf Course'),
  ('United States', 'Rogers Park Golf Course'),
  ('United States', 'Rogers Park Golf Course Short Course'),
  ('United States', 'Rohannas Golf Course'),
  ('United States', 'Rolfe Golf Club'),
  ('United States', 'Rolling Acres Golf Club'),
  ('United States', 'Rolling Acres Golf Course'),
  ('United States', 'Rolling Fields Golf Club'),
  ('United States', 'Rolling Green Country Club'),
  ('United States', 'Rolling Green Golf Club'),
  ('United States', 'Rolling Green Golf Course'),
  ('United States', 'Rolling Green Golf Course Country Club'),
  ('United States', 'Rolling Greens Executive Golf Course'),
  ('United States', 'Rolling Greens Golf Club'),
  ('United States', 'Rolling Greens Golf Course'),
  ('United States', 'Rolling Hills'),
  ('United States', 'Rolling Hills Country Club'),
  ('United States', 'Rolling Hills County Park Disc Golf'),
  ('United States', 'Rolling Hills Golf Club'),
  ('United States', 'Rolling Hills Golf Course'),
  ('United States', 'Rolling Knolls Golf Course'),
  ('United States', 'Rolling Meadows'),
  ('United States', 'Rolling Meadows Country Club'),
  ('United States', 'Rolling Meadows Golf Club'),
  ('United States', 'Rolling Meadows Golf Course'),
  ('United States', 'Rolling Oaks Golf Course'),
  ('United States', 'Rolling Pines Golf Course'),
  ('United States', 'Rolling Rock Club'),
  ('United States', 'Rolling S Golf Club'),
  ('United States', 'Rolling Turf Golf Club'),
  ('United States', 'Rollingstone Ranch Golf Club'),
  ('United States', 'Roman Nose Golf Course'),
  ('United States', 'Rome Country Club'),
  ('United States', 'Ron Jaworskis Riverwinds Golf Tennis Club'),
  ('United States', 'Ron Jaworskis Valleybrook Country Club'),
  ('United States', 'Rooling Hills Golf Course'),
  ('United States', 'Roosevelt Course At The Villages Executive Golf Trail'),
  ('United States', 'Roosevelt Golf Course'),
  ('United States', 'Roosevelt Memorial Golf Course'),
  ('United States', 'Roosevelt Municipal Golf Course'),
  ('United States', 'Rooster Run Golf Club'),
  ('United States', 'Root River Country Club'),
  ('United States', 'Root River Golf Club'),
  ('United States', 'Roscoe Mountain Club'),
  ('United States', 'Rose Brook Golf Course'),
  ('United States', 'Rose City Golf Course'),
  ('United States', 'Rose Creek Golf Club'),
  ('United States', 'Rose Creek Golf Course'),
  ('United States', 'Rose Hill Golf Club'),
  ('United States', 'Rose Lake Golf Club'),
  ('United States', 'Rose Park Golf Course'),
  ('United States', 'Rose Ridge Golf Course'),
  ('United States', 'Rosedale Golf Country Club'),
  ('United States', 'Roseland Golf and Curling Club'),
  ('United States', 'Roses Run Country Club'),
  ('United States', 'Rosman-Glendale Farm Golf Course'),
  ('United States', 'Ross Mountain Club'),
  ('United States', 'Rossmoor Golf Club The Creekside Golf Course'),
  ('United States', 'Rossmoor Golf Club The Dollar Ranch Golf Course'),
  ('United States', 'Rossmoor Golf Course'),
  ('United States', 'Roswell Country Club'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Long Meadow'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Pine Valley Course'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The White Marsh'),
  ('United States', 'Rouge Park Golf Course'),
  ('United States', 'Round Barn Golf Club'),
  ('United States', 'Round Grove Golf and Country Club'),
  ('United States', 'Round Hill Club'),
  ('United States', 'Round Hill Community Golf Club'),
  ('United States', 'Round Hill Golf Country Club'),
  ('United States', 'Round Lake Public Golf Course'),
  ('United States', 'Round Mountain Golf Club'),
  ('United States', 'Round Valley Golf Course'),
  ('United States', 'Route 56 Golf Course'),
  ('United States', 'Rowley Country Club'),
  ('United States', 'Roxboro Country Club'),
  ('United States', 'Roxiticus Golf Club'),
  ('United States', 'Royal City Public Golf Course'),
  ('United States', 'Royal Colwood Golf Club'),
  ('United States', 'Royal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Royal Crest Country Club'),
  ('United States', 'Royal Crest Golf Club'),
  ('United States', 'Royal Fox Country Club'),
  ('United States', 'Royal Fox Golf Club'),
  ('United States', 'Royal Golf Club'),
  ('United States', 'Royal Hawaiian Golf Club'),
  ('United States', 'Royal Hylands Golf Club'),
  ('United States', 'Royal Kaanapali'),
  ('United States', 'Royal Kunia Country Club'),
  ('United States', 'Royal Lakes Golf Country Club'),
  ('United States', 'Royal Manchester Golf Links'),
  ('United States', 'Royal Melbourne'),
  ('United States', 'Royal New Kent Golf Club'),
  ('United States', 'Royal Oak Golf Club'),
  ('United States', 'Royal Oaks Country Club'),
  ('United States', 'Royal Oaks Golf Club'),
  ('United States', 'Royal Palm Country Club'),
  ('United States', 'Royal Palm Yacht Country Club'),
  ('United States', 'Royal Palms Golf Course'),
  ('United States', 'Royal Sabal At Grand Palms Golf Country Club'),
  ('United States', 'Royal Saint Patrick''s Golf Links'),
  ('United States', 'Royal Scot Golf Course'),
  ('United States', 'Royal St Augustine Golf And Country Club'),
  ('United States', 'Royal St Cloud Golf Links Blue Red Course'),
  ('United States', 'Royal St Cloud Golf Links Red White Course'),
  ('United States', 'Royal St Cloud Golf Links White Blue Course'),
  ('United States', 'Royal Vista Golf Club'),
  ('United States', 'Royal Wood Golf Country Club'),
  ('United States', 'Royalwood Golf Club'),
  ('United States', 'Royce Brook Golf Club'),
  ('United States', 'Royce Brook Golf Club East Golf Course'),
  ('United States', 'Roys All Steak Hamburgers Golf Center Pine Acres Golf Course'),
  ('United States', 'Royster Memorial Golf Course'),
  ('United States', 'Ruby Hill Golf Club'),
  ('United States', 'Ruby View Golf Course'),
  ('United States', 'Ruffled Feathers Golf Community'),
  ('United States', 'Rum Creek Golf'),
  ('United States', 'Rum Pointe Golf Course'),
  ('United States', 'Rum River Hills Golf Club'),
  ('United States', 'Rumson Golf Club'),
  ('United States', 'Running Deer Golf Club'),
  ('United States', 'Rupert Country Club'),
  ('United States', 'Rush Creek Golf Club'),
  ('United States', 'Rush Creek Golf Club - Mac 9'),
  ('United States', 'Rush Lake Hills Golf Club'),
  ('United States', 'Russell Memorial Park Golf Course'),
  ('United States', 'Russellville Country Club'),
  ('United States', 'Russian Jack Springs Golf Course'),
  ('United States', 'Rustic Canyon Golf Course'),
  ('United States', 'Rustic Glen Golf Course'),
  ('United States', 'Rustic Golf Country Club'),
  ('United States', 'Rustic Ridge Golf Course'),
  ('United States', 'Ruston Golf Country Club'),
  ('United States', 'Rutgers University Golf Course'),
  ('United States', 'Ruth Lake Country Club'),
  ('United States', 'Ruth Park Golf Couse'),
  ('United States', 'Rutherfordton Golf Club'),
  ('United States', 'Rutland Country Club'),
  ('United States', 'Ryder Brook Golf Course'),
  ('United States', 'Ryder Course At Pga Golf Club'),
  ('United States', 'Ryder Golf Course'),
  ('United States', 'Rye Golf Club'),
  ('United States', 'Ryland Lakes Golf Course'),
  ('United States', 'SPG Green Garden Country Club'),
  ('United States', 'Sabal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Sabal Grand At Grand Palms Golf Country Club'),
  ('United States', 'Sabal Springs Golf Racquet Club'),
  ('United States', 'Sabetha Golf Country Club'),
  ('United States', 'Sable Creek Golf Course'),
  ('United States', 'Sable Oaks Golf Club'),
  ('United States', 'Sabot At Hermitage Country Club'),
  ('United States', 'Sacandaga Golf Club'),
  ('United States', 'Sadaquada Golf Club'),
  ('United States', 'Saddle Cycle Club'),
  ('United States', 'Saddle Ridge'),
  ('United States', 'Saddle Rock Golf Course'),
  ('United States', 'SaddleBrook Golf Club'),
  ('United States', 'Saddleback Golf Club'),
  ('United States', 'Saddleback Ridge Golf Course'),
  ('United States', 'Saddlebrook At The Villages Executive Golf Trail'),
  ('United States', 'Saddlebrook Golf Course'),
  ('United States', 'Saddlebrook Resort Cypress Pine'),
  ('United States', 'Saddlebrook Resort Oak Cypress'),
  ('United States', 'Saddlebrook Resort Pine Oak'),
  ('United States', 'Saddlebrooke Ranch Golf Club'),
  ('United States', 'Saddlebrooke Tucson At Saddlebrooke Country Club'),
  ('United States', 'Safari Golf Club'),
  ('United States', 'Sag Harbor Golf Club'),
  ('United States', 'Sagamore Hampton Golf Club'),
  ('United States', 'Sagamore Resort And Golf Club'),
  ('United States', 'Sagamore Spring Golf Club'),
  ('United States', 'Sage Hills Golf Resort'),
  ('United States', 'Sage Lakes Municipal Golf Course'),
  ('United States', 'Sage Meadows Golf Course'),
  ('United States', 'Sage Run Golf Course'),
  ('United States', 'Sage Valley Golf Club'),
  ('United States', 'Saginaw Country Club'),
  ('United States', 'Saguaro Course At We Ko Pa Golf Club'),
  ('United States', 'Sailfish Point Golf Club'),
  ('United States', 'Sailfish Sands Golf Course Sailfish Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Black Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Gold Course'),
  ('United States', 'Saint Andrew''s Golf and Country Club'),
  ('United States', 'Saint Andrews Golf Course'),
  ('United States', 'Saint Charles Country Club'),
  ('United States', 'Saint Clair Shores Golf Club'),
  ('United States', 'Saint Croix National Golf & Event Center'),
  ('United States', 'Saint Elmo Golf Club'),
  ('United States', 'Saint Francois Country Club'),
  ('United States', 'Saint Germain Golf Club'),
  ('United States', 'Saint Ignace Golf & Country Club'),
  ('United States', 'Saint Ives'),
  ('United States', 'Saint Joe Valley Golf Course'),
  ('United States', 'Saint John Fisher Golf Course'),
  ('United States', 'Saint John''s Resort Golf Course'),
  ('United States', 'Saint Marys Golf Club'),
  ('United States', 'Sakima Country Club'),
  ('United States', 'Sakonnet Golf Club'),
  ('United States', 'Salem Country Club'),
  ('United States', 'Salem Glen Country Club'),
  ('United States', 'Salem Golf Club'),
  ('United States', 'Salem Golf Course'),
  ('United States', 'Salem Harbour Golf Course'),
  ('United States', 'Salem Hills Golf Club'),
  ('United States', 'Salida Golf Club'),
  ('United States', 'Salina Country Club'),
  ('United States', 'Salina Municipal Golf Course'),
  ('United States', 'Salinas Fairways Golf Course'),
  ('United States', 'Saline County Golf Club'),
  ('United States', 'Salisbury Country Club Buckingham Course'),
  ('United States', 'Salisbury Country Club Huguenot Course'),
  ('United States', 'Salisbury Country Club Monacan Course'),
  ('United States', 'Salish Cliffs Golf Club'),
  ('United States', 'Salmo Golf Club'),
  ('United States', 'Salmon Creek Country Club'),
  ('United States', 'Salmon Falls Golf Club'),
  ('United States', 'Salmon Run Golf Course'),
  ('United States', 'Salmon Valley Golf Course'),
  ('United States', 'Salt Creek Country Club'),
  ('United States', 'Salt Creek Golf Club'),
  ('United States', 'Salt Creek Golf Resort'),
  ('United States', 'Salt Fork State Park Golf Course'),
  ('United States', 'Salt River Golf Course'),
  ('United States', 'Saltleaf Golf Preserve The Leaf'),
  ('United States', 'Saltleaf Golf Preserve The Preserve'),
  ('United States', 'Saltville Golf Course'),
  ('United States', 'Saluda Valley Country Club'),
  ('United States', 'Samoset Resort'),
  ('United States', 'San Carlos Golf Club'),
  ('United States', 'San Clemente Municipal Golf Course'),
  ('United States', 'San Diego Country Club'),
  ('United States', 'San Dimas Canyon Golf Course'),
  ('United States', 'San Francisco Golf Club'),
  ('United States', 'San Gabriel Country Club'),
  ('United States', 'San Ignacio Golf Club'),
  ('United States', 'San Joaquin Country Club'),
  ('United States', 'San Jose Country Club'),
  ('United States', 'San Jose Municipal Golf Course'),
  ('United States', 'San Juan Country Club'),
  ('United States', 'San Juan Golf Country Club'),
  ('United States', 'San Juan Hills Golf Club'),
  ('United States', 'San Juan Oaks Golf Club'),
  ('United States', 'San Luis Obispo Country Club'),
  ('United States', 'San Manuel Golf Club'),
  ('United States', 'San Marcos Golf Resort'),
  ('United States', 'San Pedro Golf Course'),
  ('United States', 'San Ramon Golf Club'),
  ('United States', 'San Tan Course At Sunland Springs Village'),
  ('United States', 'San Tan Highlands'),
  ('United States', 'San Vicente Golf Resort'),
  ('United States', 'Sanborn Golf and Country Club'),
  ('United States', 'Sanctuary At River Strand Golf And Country Club'),
  ('United States', 'Sanctuary Golf Club'),
  ('United States', 'Sanctuary Golf Course'),
  ('United States', 'Sanctuary Lake Golf Course'),
  ('United States', 'Sand Canyon Country Club'),
  ('United States', 'Sand Creek Country Club'),
  ('United States', 'Sand Creek Golf Club'),
  ('United States', 'Sand Creek Golf Course'),
  ('United States', 'Sand Creek Short Course'),
  ('United States', 'Sand Creek Station Golf Club'),
  ('United States', 'Sand Hill Golf Course'),
  ('United States', 'Sand Hollow Golf Resort The Championship Course'),
  ('United States', 'Sand Hollow Golf Resort The Links Course'),
  ('United States', 'Sand Hollow Golf Resort Wee Course'),
  ('United States', 'Sand Point Country Club'),
  ('United States', 'Sand Ridge Golf Club'),
  ('United States', 'Sand Springs Golf Course'),
  ('United States', 'Sand Valley Golf Resort'),
  ('United States', 'Sandalwood Country Club'),
  ('United States', 'Sandhill At The Villages Executive Golf Trail'),
  ('United States', 'Sandhill Crane Golf Club Championship Golf Course'),
  ('United States', 'Sandhill Crane Golf Club The Nest Par 3'),
  ('United States', 'Sandhill Golf Course'),
  ('United States', 'Sandia Golf Club'),
  ('United States', 'Sandpiper At Spring Lake Golf Club'),
  ('United States', 'Sandpiper Bay Golf Country Club Bay Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Piper Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Sand Nine'),
  ('United States', 'Sandpiper Cove Golf Course'),
  ('United States', 'Sandpiper Golf Course'),
  ('United States', 'Sands Lakes At Star Hill Golf Country Club')
on conflict (country, name) do nothing;