insert into public.golf_courses (country, name) values
  ('United States', 'The Emerald Golf Course'),
  ('United States', 'The Estancia Club'),
  ('United States', 'The Evans at Canal Shores'),
  ('United States', 'The Executive At Fore Lakes Golf Course'),
  ('United States', 'The Executive At Victor Hills Golf Club'),
  ('United States', 'The Executive Course At Lakehouse'),
  ('United States', 'The Fairways'),
  ('United States', 'The Fairways At Prestonwood Country Club'),
  ('United States', 'The Fairways at Twin Lakes'),
  ('United States', 'The Fall Line East Course'),
  ('United States', 'The Fall Line Short Course'),
  ('United States', 'The Fall Line West Course'),
  ('United States', 'The Falls Club Of The Palm Beaches'),
  ('United States', 'The Falls Golf Club'),
  ('United States', 'The Falls at Barber Creek'),
  ('United States', 'The Farms Country Club'),
  ('United States', 'The Farms Golf Club'),
  ('United States', 'The Federal Club'),
  ('United States', 'The Fields Golf Club'),
  ('United States', 'The Fields Golf Course'),
  ('United States', 'The First Tee Of Central Arkansas Chairmans Course'),
  ('United States', 'The First Tee Of Central Arkansas Honors Course'),
  ('United States', 'The First Tee Of Fort Smith The Jack Stephens Youth Golf Academy'),
  ('United States', 'The First Tee Of Greater Richmond'),
  ('United States', 'The First Tee Of Hampton Roads'),
  ('United States', 'The First Tee Of Monterey County'),
  ('United States', 'The First Tee Of North Florida Brentwood Golf Course'),
  ('United States', 'The First Tee Of Phoenix'),
  ('United States', 'The First Tee Of The Lowcountry Golf Course'),
  ('United States', 'The First Tee Of Troup County'),
  ('United States', 'The First Tee Syracuse Golf Complex At Butternut Creek'),
  ('United States', 'The First Tee Youth Golf Course'),
  ('United States', 'The Florida Club'),
  ('United States', 'The Floridian'),
  ('United States', 'The Floridian The Harmon Par 3 Course'),
  ('United States', 'The Ford Field River Club'),
  ('United States', 'The Fort Golf Course'),
  ('United States', 'The Fortress Golf Course'),
  ('United States', 'The Founders Golf Club'),
  ('United States', 'The Fountaingrove Club'),
  ('United States', 'The Four Seasons Island Resort'),
  ('United States', 'The Fox Golf Club'),
  ('United States', 'The Fox Valley Club'),
  ('United States', 'The Frog At The Georgian'),
  ('United States', 'The Gailes'),
  ('United States', 'The Gauntlet Golf Club'),
  ('United States', 'The General'),
  ('United States', 'The Georgia Club Chancellors Black Silver Course'),
  ('United States', 'The Georgia Club Chancellors Red Black Course'),
  ('United States', 'The Georgia Club Chancellors Red Silver Course'),
  ('United States', 'The Glacier Golf Course & The Prairie Glen Golf Course'),
  ('United States', 'The Glades Resort'),
  ('United States', 'The Glen Club'),
  ('United States', 'The Glen Golf Park'),
  ('United States', 'The Golden Bear Club At Keene S Point'),
  ('United States', 'The Golf Center At Balloon Fiesta Park'),
  ('United States', 'The Golf Center At Palm Desert'),
  ('United States', 'The Golf Center Par 3 Course'),
  ('United States', 'The Golf Club'),
  ('United States', 'The Golf Club At Bear Dance'),
  ('United States', 'The Golf Club At Blue Heron Hills'),
  ('United States', 'The Golf Club At Bluewater Bay'),
  ('United States', 'The Golf Club At Bradshaw Farm Blue Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm Red Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm White Nine'),
  ('United States', 'The Golf Club At Briars Creek'),
  ('United States', 'The Golf Club At Chaparral Pines'),
  ('United States', 'The Golf Club At Chapel Ridge'),
  ('United States', 'The Golf Club At Cimarron Trails'),
  ('United States', 'The Golf Club At Copper Valley'),
  ('United States', 'The Golf Club At Creighton Farms'),
  ('United States', 'The Golf Club At Devils Tower'),
  ('United States', 'The Golf Club At Dove Mountain Saguaro Tortolita'),
  ('United States', 'The Golf Club At Dove Mountain Tortolita Wild Burro'),
  ('United States', 'The Golf Club At Dove Mountain Wild Burro Saguaro'),
  ('United States', 'The Golf Club At Eagle Creek'),
  ('United States', 'The Golf Club At Equinox'),
  ('United States', 'The Golf Club At Fiddlers Creek'),
  ('United States', 'The Golf Club At Grays Crossing'),
  ('United States', 'The Golf Club At Hawks Prairie The Links'),
  ('United States', 'The Golf Club At Hawks Prairie The Woodlands'),
  ('United States', 'The Golf Club At Hilton Head Lakes'),
  ('United States', 'The Golf Club At Indigo Run'),
  ('United States', 'The Golf Club At Mattaponi Springs'),
  ('United States', 'The Golf Club At Middle Bay'),
  ('United States', 'The Golf Club At Newcastle China Creek Course'),
  ('United States', 'The Golf Club At Newcastle Coal Creek Course'),
  ('United States', 'The Golf Club At North Hampton'),
  ('United States', 'The Golf Club At Oxford Greens'),
  ('United States', 'The Golf Club At Rainmakers'),
  ('United States', 'The Golf Club At Rancho California'),
  ('United States', 'The Golf Club At Redlands Mesa'),
  ('United States', 'The Golf Club At Redmond Ridge'),
  ('United States', 'The Golf Club At Sacconnesset'),
  ('United States', 'The Golf Club At Southport'),
  ('United States', 'The Golf Club At Southwind'),
  ('United States', 'The Golf Club At Star Fort'),
  ('United States', 'The Golf Club At Summerbrooke'),
  ('United States', 'The Golf Club At The Highlands'),
  ('United States', 'The Golf Club At Wyndhurst Manor Club'),
  ('United States', 'The Golf Club Of Bristol'),
  ('United States', 'The Golf Club Of California'),
  ('United States', 'The Golf Club Of Cypress Creek'),
  ('United States', 'The Golf Club Of Fernley'),
  ('United States', 'The Golf Club Of Jupiter'),
  ('United States', 'The Golf Club Of New England'),
  ('United States', 'The Golf Club Of Oklahoma'),
  ('United States', 'The Golf Club Of Purchase'),
  ('United States', 'The Golf Club Of Quincy'),
  ('United States', 'The Golf Club Tierra Oaks'),
  ('United States', 'The Golf Club at Cedar Creek'),
  ('United States', 'The Golf Club at Eagle Pointe'),
  ('United States', 'The Golf Club at Little Turtle'),
  ('United States', 'The Golf Club at Mt. Brighton'),
  ('United States', 'The Golf Club at Stonelick Hills'),
  ('United States', 'The Golf Club at Table Creek'),
  ('United States', 'The Golf Club at Yankee Trace'),
  ('United States', 'The Golf Club of Bucyrus'),
  ('United States', 'The Golf Course at Branch River'),
  ('United States', 'The Golf Course at Camelot'),
  ('United States', 'The Golf Depot'),
  ('United States', 'The Golf Dome'),
  ('United States', 'The Golf Garden Of Destin'),
  ('United States', 'The Golf Lodge At The Quarry'),
  ('United States', 'The Golf Preserve'),
  ('United States', 'The Golf Ranch'),
  ('United States', 'The Golf Village'),
  ('United States', 'The Grand Bear Golf Course'),
  ('United States', 'The Grand Golf Club'),
  ('United States', 'The Greens At Beaumont'),
  ('United States', 'The Greens At Churchill S'),
  ('United States', 'The Greens At Deerfield'),
  ('United States', 'The Greens At Half Hollow'),
  ('United States', 'The Greens At Hamilton Run'),
  ('United States', 'The Greens At North Hills'),
  ('United States', 'The Greens At Tanyard'),
  ('United States', 'The Greens Burns Flat Golf Course'),
  ('United States', 'The Greens Golf Course'),
  ('United States', 'The Greens Of Altus Golf Course'),
  ('United States', 'The Greens Of Greenville'),
  ('United States', 'The Greens On Blossom Way Golf Country Club'),
  ('United States', 'The Grizzly Golf and Social Lodge'),
  ('United States', 'The Grove Country Club'),
  ('United States', 'The Groves Golf And Country Club'),
  ('United States', 'The Groves Golf Course'),
  ('United States', 'The Habitat Golf Course'),
  ('United States', 'The Hamptons Golf Course Lakes Links'),
  ('United States', 'The Hamptons Golf Course Woods Lakes'),
  ('United States', 'The Hamptons Golf Course Woods Links'),
  ('United States', 'The Harbor At Grand Harbor Golf Beach Club'),
  ('United States', 'The Harvester Golf Club'),
  ('United States', 'The Hasentree Club'),
  ('United States', 'The Haven Country Club'),
  ('United States', 'The Havens Country Club'),
  ('United States', 'The Hawk Country Club'),
  ('United States', 'The Hawthorns Golf & Country Club'),
  ('United States', 'The Hayden Lake Country Club'),
  ('United States', 'The Haytm'),
  ('United States', 'The Heather'),
  ('United States', 'The Heathlands'),
  ('United States', 'The Heights Golf Club'),
  ('United States', 'The Heritage At Marion Country Club'),
  ('United States', 'The Heritage Club'),
  ('United States', 'The Heritage Golf Club'),
  ('United States', 'The Hickory At Hamilton Farm'),
  ('United States', 'The Hideaway At Country Greens'),
  ('United States', 'The Hideaway Country Club'),
  ('United States', 'The Hideout'),
  ('United States', 'The Hideout Golf Club'),
  ('United States', 'The Highland Course At Primland Resort'),
  ('United States', 'The Highlands'),
  ('United States', 'The Highlands At Hamilton Farm'),
  ('United States', 'The Highlands At Prestonwood Country Club'),
  ('United States', 'The Highlands Golf Club At Fisher Mountain'),
  ('United States', 'The Highlands Golf Course'),
  ('United States', 'The Hill At Blacksburg Municipal Golf Course'),
  ('United States', 'The Hills At Portal Golf Club'),
  ('United States', 'The Hills Course At Red Hawk'),
  ('United States', 'The Hills Golf Club at McKendree University'),
  ('United States', 'The Hollows Golf Club Cottage Road'),
  ('United States', 'The Hollows Golf Club Lake Cottage'),
  ('United States', 'The Hollows Golf Club Lake Road'),
  ('United States', 'The Holly At Pinewild Country Club'),
  ('United States', 'The Home Course'),
  ('United States', 'The Homestead Golf Course'),
  ('United States', 'The Honors Course'),
  ('United States', 'The Hoop Loop At Tsatsu Dunes'),
  ('United States', 'The Idaho Club'),
  ('United States', 'The Inn At Pocono Manor East Course'),
  ('United States', 'The Inn Golf Course'),
  ('United States', 'The Institute Llc'),
  ('United States', 'The Island Country Club'),
  ('United States', 'The Jay Lionel Hebert Municipal Golf Course'),
  ('United States', 'The Jayhawk Club'),
  ('United States', 'The Jewel Golf Club'),
  ('United States', 'The Jewel of Grand Blanc'),
  ('United States', 'The Kaddyshack Par 3 Golf Course'),
  ('United States', 'The Kanawha Club'),
  ('United States', 'The King And Prince Beach Golf Resort'),
  ('United States', 'The Kingsley Club'),
  ('United States', 'The Kittansett Club'),
  ('United States', 'The Knolls Golf Course'),
  ('United States', 'The Lake Club'),
  ('United States', 'The Lakes'),
  ('United States', 'The Lakes At Ahwatukee'),
  ('United States', 'The Lakes Country Club'),
  ('United States', 'The Lakes Course At Red Hawk'),
  ('United States', 'The Lakes Golf & Country Club'),
  ('United States', 'The Lakes Golf Club'),
  ('United States', 'The Lakes Golf Course'),
  ('United States', 'The Lamberts Point Golf Course'),
  ('United States', 'The Landing At Fort Harrison'),
  ('United States', 'The Landing At Pleasant Point'),
  ('United States', 'The Landing Golf Course'),
  ('United States', 'The Landings Club Deer Creek Course'),
  ('United States', 'The Landings Club Magnolia Course'),
  ('United States', 'The Landings Club Marshwood Course'),
  ('United States', 'The Landings Club Oakridge Course'),
  ('United States', 'The Landings Club Palmetto Course'),
  ('United States', 'The Landings Club Terrapin Point Course'),
  ('United States', 'The Landings Golf Club Trestle Bluff'),
  ('United States', 'The Ledgend'),
  ('United States', 'The Ledges'),
  ('United States', 'The Ledges Golf Club'),
  ('United States', 'The Leelanau Club at Bahle Farms'),
  ('United States', 'The Legacy'),
  ('United States', 'The Legacy Golf Club'),
  ('United States', 'The Legacy Golf Tennis Club Championship Course'),
  ('United States', 'The Legacy Golf Tennis Club Executive Course'),
  ('United States', 'The Legacy Resort At Frenchman Hills'),
  ('United States', 'The Legend Golf Course'),
  ('United States', 'The Legend at Bergamont'),
  ('United States', 'The Legend at Brandybrook'),
  ('United States', 'The Legend at Bristlecone'),
  ('United States', 'The Legend at Merrill Hills'),
  ('United States', 'The Legends At Chateau Elan'),
  ('United States', 'The Legends At Orange Lake Resort'),
  ('United States', 'The Legends Golf Club'),
  ('United States', 'The Legends Golf Course At Parris Island'),
  ('United States', 'The Legends of Massillon'),
  ('United States', 'The Lincoln Hills Golf Club Hills Course'),
  ('United States', 'The Lincoln Hills Golf Club Orchard Course'),
  ('United States', 'The Links At Audubon'),
  ('United States', 'The Links At Bodega Harbour'),
  ('United States', 'The Links At Boynton Beach Championship Course'),
  ('United States', 'The Links At Boynton Beach The Family Course'),
  ('United States', 'The Links At Brick Landing'),
  ('United States', 'The Links At Cadron Valley Golf Country Club'),
  ('United States', 'The Links At Cobble Creek'),
  ('United States', 'The Links At Cotton Valley Golf Club'),
  ('United States', 'The Links At Dardenne'),
  ('United States', 'The Links At Davy Crockett'),
  ('United States', 'The Links At Erie Village'),
  ('United States', 'The Links At Everline'),
  ('United States', 'The Links At Fayetteville Golf Country Club'),
  ('United States', 'The Links At Fort Smith Golf Athletic Club'),
  ('United States', 'The Links At Fox Meadows'),
  ('United States', 'The Links At Galloway'),
  ('United States', 'The Links At Grandview'),
  ('United States', 'The Links At Greenfield Plantation'),
  ('United States', 'The Links At Greystone'),
  ('United States', 'The Links At Hampton Cove'),
  ('United States', 'The Links At Harrison Golf Athletic Club'),
  ('United States', 'The Links At Hemlock Creek'),
  ('United States', 'The Links At Hiawatha Landing'),
  ('United States', 'The Links At Ivy Ridge'),
  ('United States', 'The Links At Jonesboro Golf Athletic Club'),
  ('United States', 'The Links At Kansas Golf Club'),
  ('United States', 'The Links At Kiley Ranch'),
  ('United States', 'The Links At Labelle Winery'),
  ('United States', 'The Links At Lake Toccoa'),
  ('United States', 'The Links At Lakehouse'),
  ('United States', 'The Links At Lang Farm'),
  ('United States', 'The Links At Lighthouse Sound'),
  ('United States', 'The Links At Moses Pointe'),
  ('United States', 'The Links At Mulberry Hill'),
  ('United States', 'The Links At Muny'),
  ('United States', 'The Links At Mustang Creek Golf Country Club'),
  ('United States', 'The Links At Oklahoma City Golf Athletic Club'),
  ('United States', 'The Links At Outlook'),
  ('United States', 'The Links At Overlake'),
  ('United States', 'The Links At Overton Park'),
  ('United States', 'The Links At Oxford Golf Country Club'),
  ('United States', 'The Links At Pine Hill'),
  ('United States', 'The Links At Poland Spring Resort'),
  ('United States', 'The Links At Pretty Prairie'),
  ('United States', 'The Links At Rainbow Curve Golf Country Club'),
  ('United States', 'The Links At Rising Star Casino'),
  ('United States', 'The Links At Riverside'),
  ('United States', 'The Links At Rolling Hills'),
  ('United States', 'The Links At Rolling Meadows'),
  ('United States', 'The Links At Sleepy Ridge'),
  ('United States', 'The Links At Spanish Baytm'),
  ('United States', 'The Links At Spring Church'),
  ('United States', 'The Links At Springdale Golf Country Club'),
  ('United States', 'The Links At Starkville Golf Country Club'),
  ('United States', 'The Links At Stillwater Golf Country Club'),
  ('United States', 'The Links At Stono Ferry'),
  ('United States', 'The Links At Summerly'),
  ('United States', 'The Links At Terranea'),
  ('United States', 'The Links At Teton Peaks'),
  ('United States', 'The Links At Texarkana Golf Athletic Club'),
  ('United States', 'The Links At The Rock Golf Country Club'),
  ('United States', 'The Links At Union Vale'),
  ('United States', 'The Links At Valley Fields'),
  ('United States', 'The Links At Whitehaven'),
  ('United States', 'The Links At Woodcliff'),
  ('United States', 'The Links Golf Club'),
  ('United States', 'The Links Golf Club At Queen Creek'),
  ('United States', 'The Links Golf Course'),
  ('United States', 'The Links Indoor Golf'),
  ('United States', 'The Links Of Madison County Golf Country Club'),
  ('United States', 'The Links Of Naples'),
  ('United States', 'The Links Of North Dakota'),
  ('United States', 'The Links On Memorial Golf Athletic Club'),
  ('United States', 'The Links at Bowen Lake'),
  ('United States', 'The Links at Crystal Lake'),
  ('United States', 'The Links at Ireland Grove'),
  ('United States', 'The Links at Rising Star Casino Resort'),
  ('United States', 'The Links by the Tracks'),
  ('United States', 'The Links of Jacksonville'),
  ('United States', 'The Links of Novi'),
  ('United States', 'The Little Club'),
  ('United States', 'The Little Course'),
  ('United States', 'The Lodge Golf Course'),
  ('United States', 'The Loma Club'),
  ('United States', 'The Loon Golf Resort'),
  ('United States', 'The Loop at Chaska'),
  ('United States', 'The Lynx At River Bend Golf Club'),
  ('United States', 'The Madison Club'),
  ('United States', 'The Magnolia At Pinewild Country Club'),
  ('United States', 'The Majors Golf Club At Bayside Lakes'),
  ('United States', 'The Manor Golf And Country Club'),
  ('United States', 'The Manor Golf Club'),
  ('United States', 'The Meadow At Peabody'),
  ('United States', 'The Meadows'),
  ('United States', 'The Meadows At Countrywood'),
  ('United States', 'The Meadows At Middlesex Golf Club'),
  ('United States', 'The Meadows At Prestonwood Country Club'),
  ('United States', 'The Meadows Country Club'),
  ('United States', 'The Meadows Golf And Country Club'),
  ('United States', 'The Meadows at Grand Valley State University'),
  ('United States', 'The Meadows of Six Mile Creek Golf Course'),
  ('United States', 'The Medalist Golf Club'),
  ('United States', 'The Members Club At Aldarra'),
  ('United States', 'The Members Club At Wildewood'),
  ('United States', 'The Members Club At Woodcreek'),
  ('United States', 'The Metropolitan Golf Links'),
  ('United States', 'The Mill Course'),
  ('United States', 'The Milton Hoosic Club'),
  ('United States', 'The Minikahda Club'),
  ('United States', 'The Mission Club'),
  ('United States', 'The Montrose Club'),
  ('United States', 'The Monument'),
  ('United States', 'The Moor'),
  ('United States', 'The Moor At The Highlands Boyne'),
  ('United States', 'The Moorings Yacht Country Club Hawks Nest'),
  ('United States', 'The Moorings Yacht Country Club Moorings Course'),
  ('United States', 'The Mountain At Christmans Windham House'),
  ('United States', 'The Mountain Course At Spruce Peak'),
  ('United States', 'The Mountains At Bighorn Golf Club'),
  ('United States', 'The Myth'),
  ('United States', 'The National'),
  ('United States', 'The National Golf Club Of Louisiana'),
  ('United States', 'The National Golf Country Club'),
  ('United States', 'The National Golf Course at Eagle Creek'),
  ('United States', 'The Natural at Beaver Creek Resort'),
  ('United States', 'The Neuse Golf Club'),
  ('United States', 'The New England Country Club'),
  ('United States', 'The New Vineyards Golf Course'),
  ('United States', 'The Nightmare GC'),
  ('United States', 'The Nine Hole At Augusta National Golf Club'),
  ('United States', 'The Nine Hole At Centre Hills Country Club'),
  ('United States', 'The Nine Hole Par 3 At Bel Aire Golf Club'),
  ('United States', 'The North At Goodwin Golf Course'),
  ('United States', 'The Oaks'),
  ('United States', 'The Oaks At Margaritaville Lake Resort'),
  ('United States', 'The Oaks At Spanish Fork'),
  ('United States', 'The Oaks Club At Valencia'),
  ('United States', 'The Oaks Club Eagle Course'),
  ('United States', 'The Oaks Club Heron Course'),
  ('United States', 'The Oaks Course'),
  ('United States', 'The Oaks Golf Club'),
  ('United States', 'The Oaks Golf Course'),
  ('United States', 'The Oaks Golf Links'),
  ('United States', 'The Oaks at Kincheloe'),
  ('United States', 'The Oasis'),
  ('United States', 'The Ocean Course At Hokuala'),
  ('United States', 'The Ocean Course At Kiawah Island Golf Resort'),
  ('United States', 'The Ocean North At Pelican Hill Golf Club'),
  ('United States', 'The Ocean South At Pelican Hill Golf Club'),
  ('United States', 'The Old Collier Golf Club'),
  ('United States', 'The Old Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Olde Farm Golf Club'),
  ('United States', 'The Olympic At Gold Mountain Golf Course'),
  ('United States', 'The Olympic Club Cliffs Course'),
  ('United States', 'The Olympic Club Lake Course'),
  ('United States', 'The Olympic Club Ocean Course'),
  ('United States', 'The Omni Grove Park Inn'),
  ('United States', 'The Omni Homestead Resort Spa Cascades Course')
on conflict (country, name) do nothing;