insert into public.golf_courses (country, name) values
  ('United States', 'Quint Valley Golf Club'),
  ('United States', 'Quinter Golf Club'),
  ('United States', 'Quintero Golf Club'),
  ('United States', 'Quinton Oaks Golf Course'),
  ('United States', 'Quitman Country Club'),
  ('United States', 'Quixote Club'),
  ('United States', 'Quogue Field Club'),
  ('United States', 'Raber Golf Course'),
  ('United States', 'Rabun County Golf Club'),
  ('United States', 'Raccoon Creek Golf Course'),
  ('United States', 'Raccoon Hill Golf Club'),
  ('United States', 'Raccoon International'),
  ('United States', 'Raceway Golf Club'),
  ('United States', 'Racine Country Club'),
  ('United States', 'Rackham Golf Course'),
  ('United States', 'Radcliffe Friendly Fareways'),
  ('United States', 'Radisson Greens Golf Course'),
  ('United States', 'Radley Run Country Club'),
  ('United States', 'Radnor Valley Country Club'),
  ('United States', 'Radrick Farms Golf Course'),
  ('United States', 'Railside Golf Club'),
  ('United States', 'Rainbow Golf Club'),
  ('United States', 'Rainbow S End Golf Club'),
  ('United States', 'Raindance National'),
  ('United States', 'Rainier Golf Country Club'),
  ('United States', 'Raintree Country Club'),
  ('United States', 'Raintree Golf & Event Center'),
  ('United States', 'Raintree Golf Club'),
  ('United States', 'Raintree Golf Course'),
  ('United States', 'Raisin Valley Golf Club'),
  ('United States', 'Raleigh Country Club'),
  ('United States', 'Raleigh Golf Association'),
  ('United States', 'Raleigh Golf Association Stockholders Course'),
  ('United States', 'Ralph Myhre Golf Course'),
  ('United States', 'Rammler Golf Club'),
  ('United States', 'Rams Hill Golf Club'),
  ('United States', 'Ramsey Golf Country Club'),
  ('United States', 'Ramsey Lake Golf Course'),
  ('United States', 'Ranch At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Ranch At Roaring Fork Golf Course'),
  ('United States', 'Ranch At Tonto Verde Golf Club'),
  ('United States', 'Ranch Club Golf Course'),
  ('United States', 'Ranch Course At Alisal'),
  ('United States', 'Ranch Course At Genoa Lakes Golf Club'),
  ('United States', 'Ranch Golf Course At Pole Creek Golf Club'),
  ('United States', 'Rancho Bernardo Inn'),
  ('United States', 'Rancho Carlsbad Golf Club'),
  ('United States', 'Rancho Casa Blanca Country Club'),
  ('United States', 'Rancho Del Pueblo Golf Course'),
  ('United States', 'Rancho Del Rey Golf Club'),
  ('United States', 'Rancho Del Sol Golf Club'),
  ('United States', 'Rancho La Quinta Jones Course'),
  ('United States', 'Rancho La Quinta Pate Course'),
  ('United States', 'Rancho Manana Golf Club'),
  ('United States', 'Rancho Maria Golf Club'),
  ('United States', 'Rancho Mirage Country Club'),
  ('United States', 'Rancho Monserate Country Club'),
  ('United States', 'Rancho Park Golf Course'),
  ('United States', 'Rancho Park Par 3 Golf Course'),
  ('United States', 'Rancho San Joaquin Golf Course'),
  ('United States', 'Rancho San Marcos Golf Course'),
  ('United States', 'Rancho Santa Fe Golf Club'),
  ('United States', 'Rancho Sierra Golf Course'),
  ('United States', 'Rancho Solano Golf Course'),
  ('United States', 'Rancho Vista Golf Course'),
  ('United States', 'Rancocas Golf Club'),
  ('United States', 'Randall Hills Country Club'),
  ('United States', 'Randall Oaks Golf Course'),
  ('United States', 'Randolph Country Club'),
  ('United States', 'Range End Country Club'),
  ('United States', 'Range Line Golf Course'),
  ('United States', 'Raptor At Grayhawk Golf Club'),
  ('United States', 'Raquette River Golf Country Club'),
  ('United States', 'Raritan Landing Golf Course'),
  ('United States', 'Raritan Valley Country Club'),
  ('United States', 'Raspberry Falls Golf Hunt Club'),
  ('United States', 'Raspberry Ridge Golf Course'),
  ('United States', 'Raton Country Club'),
  ('United States', 'Rattle Run Golf Course'),
  ('United States', 'Rattlesnake Ridge Golf Club'),
  ('United States', 'Raven At Sandestin Golf And Beach Resort'),
  ('United States', 'Raven Golf Club At Snowshoe Mountain'),
  ('United States', 'Raven Golf Club Phoenix'),
  ('United States', 'Raven Rock Golf Course'),
  ('United States', 'Ravenna Creeks Golf Course'),
  ('United States', 'Ravens Claw Golf Club'),
  ('United States', 'Ravenwood Golf Course'),
  ('United States', 'Ravines Golf Club'),
  ('United States', 'Ravinia Green Country Club'),
  ('United States', 'Ravisloe Country Club'),
  ('United States', 'Ray Golf Association'),
  ('United States', 'Rayburn Country Resort'),
  ('United States', 'Raymond Memorial Golf Course'),
  ('United States', 'Raymond Shoal Creek Golf Course'),
  ('United States', 'Raystown Golf Resort'),
  ('United States', 'Rea Park Golf Course'),
  ('United States', 'Reading Country Club'),
  ('United States', 'Recreation Park 18 Golf Course'),
  ('United States', 'Recreation Park 9 Golf Course'),
  ('United States', 'Red Apple Inn Country Club'),
  ('United States', 'Red Arrow Golf Course'),
  ('United States', 'Red At Bethpage State Park Golf Course'),
  ('United States', 'Red At Cedarbrook Golf Course'),
  ('United States', 'Red At D Fairchild Wheeler Golf Course'),
  ('United States', 'Red At Eisenhower Park Golf Course'),
  ('United States', 'Red At Ford Hill Country Club'),
  ('United States', 'Red At Golf Club Of Avon'),
  ('United States', 'Red At Palmetto Pines Golf Course'),
  ('United States', 'Red At Tunxis Country Club'),
  ('United States', 'Red Bank Plantation'),
  ('United States', 'Red Barn Golf Course'),
  ('United States', 'Red Bird Golf Links'),
  ('United States', 'Red Blue At Edgewood Country Club'),
  ('United States', 'Red Blue At Lindenwood Golf Club'),
  ('United States', 'Red Blue At Ramblewood Country Club'),
  ('United States', 'Red Blue At Sugar Mill Country Club'),
  ('United States', 'Red Blue At Sunken Meadow State Park Golf Course'),
  ('United States', 'Red Blue At Timber Point Country Club'),
  ('United States', 'Red Blue At Westchester Golf Country Club'),
  ('United States', 'Red Blue At Woods Golf Course The'),
  ('United States', 'Red Bridge Golf And Country Club'),
  ('United States', 'Red Carpet Golf Course'),
  ('United States', 'Red Cloud Golf Course'),
  ('United States', 'Red Dog Run'),
  ('United States', 'Red Farm Golf'),
  ('United States', 'Red Fox Country Club'),
  ('United States', 'Red Fox Run'),
  ('United States', 'Red Gold At Rothland Golf Course'),
  ('United States', 'Red Gold At Valley Brook Country Club'),
  ('United States', 'Red Hawk Golf Club'),
  ('United States', 'Red Hawk Golf Course & Learning Center'),
  ('United States', 'Red Hawk Ridge'),
  ('United States', 'Red Hill Country Club'),
  ('United States', 'Red Hook Golf Club'),
  ('United States', 'Red Ledges Golf Club 12 Hole Golf Park Course'),
  ('United States', 'Red Ledges Golf Club Nicklaus Signature Course'),
  ('United States', 'Red Lodge Mountain Golf Course'),
  ('United States', 'Red Maples Golf Course'),
  ('United States', 'Red Martin Country Club'),
  ('United States', 'Red Mountain Ranch Country Club'),
  ('United States', 'Red Nine At Hyde Park Golf Course'),
  ('United States', 'Red Oak Country Club'),
  ('United States', 'Red Oaks Golf Course'),
  ('United States', 'Red Pines Golf Course'),
  ('United States', 'Red Reef Executive Golf Course'),
  ('United States', 'Red River Golf Club'),
  ('United States', 'Red Rock Country Club'),
  ('United States', 'Red Rock Golf Course'),
  ('United States', 'Red Rocks Country Club'),
  ('United States', 'Red Run Golf Club'),
  ('United States', 'Red Silver At Foxfire Country Club'),
  ('United States', 'Red Sky Golf Club Fazio Course'),
  ('United States', 'Red Sky Golf Club Norman Course'),
  ('United States', 'Red Tail Golf Club'),
  ('United States', 'Red Tail Run Golf Club'),
  ('United States', 'Red Trail Links'),
  ('United States', 'Red White At Arrowhead Golf Course'),
  ('United States', 'Red White At Buck Hill Falls Golf Club'),
  ('United States', 'Red White At Glen Oaks Club'),
  ('United States', 'Red White At Highland Lakes Golf Course'),
  ('United States', 'Red White At Little Mill Country Club'),
  ('United States', 'Red White At Myakka Pines Golf Club'),
  ('United States', 'Red White At Ringgold Golf Club'),
  ('United States', 'Red White At Rothland Golf Course'),
  ('United States', 'Red White At Shawnee Inn Golf Resort'),
  ('United States', 'Red White At Town Of Colonie Golf Course'),
  ('United States', 'Red White At Western Turnpike Golf Course'),
  ('United States', 'Red White At Woods Golf Course The'),
  ('United States', 'Red Wing Golf Club'),
  ('United States', 'Red Wing Lake Golf Course'),
  ('United States', 'Red Wolf Golf Club'),
  ('United States', 'Red Yellow At Willowbrook Golf Club'),
  ('United States', 'RedTail Golf Club'),
  ('United States', 'Redbud Crabapple At Roanoke Country Club'),
  ('United States', 'Redbud Springs Golf Club'),
  ('United States', 'Redding Country Club'),
  ('United States', 'Redfish Run At The Villages Executive Golf Trail'),
  ('United States', 'Redhawk Golf Club'),
  ('United States', 'Redhawk Golf Course'),
  ('United States', 'Redland Golf Country Club'),
  ('United States', 'Redlands Country Club'),
  ('United States', 'Redmont Country Club'),
  ('United States', 'Redstick Golf Club'),
  ('United States', 'Redstone Resort'),
  ('United States', 'Redtail Golf Club'),
  ('United States', 'Redwood Canyon Golf Course'),
  ('United States', 'Redwood Empire Golf Country Club'),
  ('United States', 'Redwood Falls Golf Club'),
  ('United States', 'Reedsburg Country Club'),
  ('United States', 'Reedy Creek Golf Course'),
  ('United States', 'Reedy Meadow Golf Course'),
  ('United States', 'Reems Creek Golf Course'),
  ('United States', 'Reeves Golf Course'),
  ('United States', 'Reflection Bay Golf Club'),
  ('United States', 'Reflection Ridge Golf Club'),
  ('United States', 'Regatta Bay Golf Yacht Club'),
  ('United States', 'Regency At Dominion Valley Country Club'),
  ('United States', 'Regency At Monroe Golf And Country Club'),
  ('United States', 'Regents Glen Country Club'),
  ('United States', 'Regulation At Borland Golf Center'),
  ('United States', 'Regulation At Jackson Park Golf Course'),
  ('United States', 'Regulation At Jefferson Park Golf Club'),
  ('United States', 'Regulation At Las Positas Golf Course'),
  ('United States', 'Regulation At Marine Memorial Golf Course'),
  ('United States', 'Regulation At Mick Riley Golf Course'),
  ('United States', 'Regulation At Pleasant Valley Country Club'),
  ('United States', 'Regulation Eighteen At Smithtown Landing Golf Club'),
  ('United States', 'Regulation Nine At Cherokee Ridge Golf Course'),
  ('United States', 'Rehoboth Beach Country Club'),
  ('United States', 'Rehoboth Country Club'),
  ('United States', 'Reid Municipal Golf Course'),
  ('United States', 'Reidy Creek Golf Course'),
  ('United States', 'Remington Golf Club'),
  ('United States', 'Remsen Golf Course'),
  ('United States', 'Remuda Golf Course'),
  ('United States', 'Renaissance Golf Club'),
  ('United States', 'Renaissance Golf Course'),
  ('United States', 'Renaissance Vinoy Resort'),
  ('United States', 'Rendezvous Meadows Golf Course'),
  ('United States', 'Renegade Course At Desert Mountain Golf Club'),
  ('United States', 'Renwood Golf Course'),
  ('United States', 'Republic Golf Course Club'),
  ('United States', 'Reservation Golf Club'),
  ('United States', 'Reserve Club At St James Plantation'),
  ('United States', 'Reserve Run Golf Course'),
  ('United States', 'Reservoir Creek Golf Course'),
  ('United States', 'Resort At Tahquitz Creek Golf Resort'),
  ('United States', 'Reston National Golf Course'),
  ('United States', 'Retreat At Sea Island Golf Club'),
  ('United States', 'Reunion Country Club'),
  ('United States', 'Reunion Golf Country Club'),
  ('United States', 'Reunion Resort Nicklaus Course'),
  ('United States', 'Reunion Resort Palmer Course'),
  ('United States', 'Reunion Resort Watson Course'),
  ('United States', 'Revere Golf Club Concord Course'),
  ('United States', 'Revere Golf Club Lexington Course'),
  ('United States', 'Reynolds Golf Course'),
  ('United States', 'Reynolds Lake Oconee Great Waters'),
  ('United States', 'Reynolds Lake Oconee Richland Course'),
  ('United States', 'Reynolds Lake Oconee The Creek Club'),
  ('United States', 'Reynolds Lake Oconee The Landing'),
  ('United States', 'Reynolds Lake Oconee The National'),
  ('United States', 'Reynolds Lake Oconee The Oconee'),
  ('United States', 'Reynolds Lake Oconee The Preserve Course'),
  ('United States', 'Reynolds Park Golf Course'),
  ('United States', 'Rhinelander Country Club'),
  ('United States', 'Rhode Island Country Club'),
  ('United States', 'Rhodes Ranch Country Club'),
  ('United States', 'Rib Mountain Golf Course'),
  ('United States', 'Rice Lake Golf and Country Club'),
  ('United States', 'Riceville Country Club'),
  ('United States', 'Rich Harvest Farms Golf Course'),
  ('United States', 'Rich Maiden Golf Course'),
  ('United States', 'Rich Valley Golf Course'),
  ('United States', 'Richford Country Club'),
  ('United States', 'Richland Country Club'),
  ('United States', 'Richland Greens Golf Center'),
  ('United States', 'Richmond Country Club'),
  ('United States', 'Richmond County Country Club'),
  ('United States', 'Richmond Hill Golf Club'),
  ('United States', 'Richmond Pitch And Putt At The Villages Executive Golf Trail'),
  ('United States', 'Richter Park Golf Course'),
  ('United States', 'Ridder Farm Golf Country Club'),
  ('United States', 'Ridge At Mulligans South'),
  ('United States', 'Ridge Canyon At La Paloma Country Club'),
  ('United States', 'Ridge Club'),
  ('United States', 'Ridge Country Club'),
  ('United States', 'Ridge Creek Dinuba Golf Club'),
  ('United States', 'Ridge Golf Club'),
  ('United States', 'Ridge Golf Course'),
  ('United States', 'Ridge Golf Course At Pole Creek Golf Club'),
  ('United States', 'Ridge Manor Oaks Golf Country Club'),
  ('United States', 'Ridge Stone Golf Club'),
  ('United States', 'Ridge Trail At Blue Ridge Trail Golf Club'),
  ('United States', 'Ridge top golf course'),
  ('United States', 'Ridgecrest Country Club'),
  ('United States', 'Ridgefield Golf Course'),
  ('United States', 'Ridgefields Country Club'),
  ('United States', 'Ridgemark Golf Country Club'),
  ('United States', 'Ridgemont Country Club'),
  ('United States', 'Ridgemoor Country Club'),
  ('United States', 'Ridgepointe Country Club'),
  ('United States', 'Ridges at Sand Creek'),
  ('United States', 'Ridgeview Country Club'),
  ('United States', 'Ridgeview Golf Course'),
  ('United States', 'Ridgeway Country Club'),
  ('United States', 'Ridgeway Shores Golf Club'),
  ('United States', 'Ridgewood Country Club'),
  ('United States', 'Ridgewood Golf Course'),
  ('United States', 'Riegelwood Country Club'),
  ('United States', 'Rifle Creek Golf Course'),
  ('United States', 'Rifle River Golf Course'),
  ('United States', 'Riley Grove Course At Palmer Legends'),
  ('United States', 'Rio Bend Golf Course'),
  ('United States', 'Rio Bravo Country Club'),
  ('United States', 'Rio Grande Club'),
  ('United States', 'Rio Hondo Golf Club'),
  ('United States', 'Rio Mimbres Country Club'),
  ('United States', 'Rio Pinar Golf'),
  ('United States', 'Rio Vista Golf Club'),
  ('United States', 'Rio Vista Golf Course'),
  ('United States', 'Riomar Country Club'),
  ('United States', 'Rip Arnold At Cherry Hills Country Club'),
  ('United States', 'Rip Van Winkle Country Club'),
  ('United States', 'Ripon Golf Club'),
  ('United States', 'Rippling Rapids Golf Club'),
  ('United States', 'Rising Sun Golf Course At Mountain Sky Guest Ranch'),
  ('United States', 'Rittswood Golf Club'),
  ('United States', 'Ritz Carlton Members Golf Club'),
  ('United States', 'Ritzville Municipal Golf'),
  ('United States', 'Rivard Golf Country Club'),
  ('United States', 'River At Indian Springs Country Club'),
  ('United States', 'River Bank Golf Course'),
  ('United States', 'River Bend Country Club'),
  ('United States', 'River Bend Golf Club'),
  ('United States', 'River Bend Golf Club North Course'),
  ('United States', 'River Bend Golf Club South Course'),
  ('United States', 'River Bend Golf Country Club'),
  ('United States', 'River Bend Golf Course'),
  ('United States', 'River Bend Links'),
  ('United States', 'River Bend Municipal Golf Course'),
  ('United States', 'River Bend Ymca Golf Course'),
  ('United States', 'River Birch Golf Club'),
  ('United States', 'River Birch Golf Course'),
  ('United States', 'River Club'),
  ('United States', 'River Club of Mequon'),
  ('United States', 'River Course At Alisal'),
  ('United States', 'River Course At Fiddlers Elbow Country Club'),
  ('United States', 'River Creek Club'),
  ('United States', 'River Creek Golf Course'),
  ('United States', 'River Creek Park Golf Course'),
  ('United States', 'River Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'River Edge Golf Course'),
  ('United States', 'River Falls Golf Club'),
  ('United States', 'River Falls Plantation'),
  ('United States', 'River Forest Country Club'),
  ('United States', 'River Forest Golf Course'),
  ('United States', 'River Glen Country Club'),
  ('United States', 'River Golf Country Club The'),
  ('United States', 'River Greens Golf Course'),
  ('United States', 'River Hall Country Club'),
  ('United States', 'River Heights Golf Course'),
  ('United States', 'River Hills Country Club'),
  ('United States', 'River Hills Golf Country Club'),
  ('United States', 'River Island Country Club'),
  ('United States', 'River Island Golf Course'),
  ('United States', 'River Isles Golf Course'),
  ('United States', 'River Lake At Woodbridge Golf Country Club'),
  ('United States', 'River Lakes Course At Pelican Sound Golf River Club'),
  ('United States', 'River Lakes Golf Course'),
  ('United States', 'River Landing At Sandy Ridge'),
  ('United States', 'River Landing Landing Course'),
  ('United States', 'River Landing River Course'),
  ('United States', 'River Marsh Golf Club Hyatt Chesapeake Bay'),
  ('United States', 'River Middle At Woodbridge Golf Country Club'),
  ('United States', 'River Oak At Del Rio Country Club'),
  ('United States', 'River Oaks Golf Club'),
  ('United States', 'River Oaks Golf Course'),
  ('United States', 'River Park Golf Course'),
  ('United States', 'River Pointe Golf Club'),
  ('United States', 'River Ridge At Harbour Ridge Yacht Country Club'),
  ('United States', 'River Ridge Golf Club'),
  ('United States', 'River Ridge Golf Club The Victoria Lakes Course'),
  ('United States', 'River Ridge Golf Club The Vineyard Course'),
  ('United States', 'River Ridge Golf Course'),
  ('United States', 'River Road Golf Club'),
  ('United States', 'River Run Golf Country Club'),
  ('United States', 'River Run Golf Course'),
  ('United States', 'River Run Golf Links'),
  ('United States', 'River Run Ii Golf Links'),
  ('United States', 'River Tasalmi Golf Course'),
  ('United States', 'River Trace Golf At Mac'),
  ('United States', 'River Vale Country Club'),
  ('United States', 'River Valley Country Club'),
  ('United States', 'River Valley Golf Course'),
  ('United States', 'River Valley Ranch Golf Club'),
  ('United States', 'River View Club'),
  ('United States', 'River View Golf Course'),
  ('United States', 'River Wilds Golf Club'),
  ('United States', 'River''s Edge Golf Club'),
  ('United States', 'Riverbend Golf Club'),
  ('United States', 'Riverbend Golf Course'),
  ('United States', 'Rivercliff Golf Course'),
  ('United States', 'Riverdale Country Club'),
  ('United States', 'Riverdale Dunes'),
  ('United States', 'Riverdale Knolls'),
  ('United States', 'Riverfront Golf Club'),
  ('United States', 'Riveria Country Club Golf Course'),
  ('United States', 'Riverland Country Club'),
  ('United States', 'Riverlands Golf Country Club'),
  ('United States', 'Rivermeadow Golf Club'),
  ('United States', 'Rivermont Golf Country Club'),
  ('United States', 'Rivermoor Golf Club'),
  ('United States', 'Riverpines Golf Course'),
  ('United States', 'Riverpines Golf Course Par 3 Course'),
  ('United States', 'Rivers Bend Golf Club'),
  ('United States', 'Rivers Bend Golf Course'),
  ('United States', 'Rivers Edge Golf Club'),
  ('United States', 'Rivers Edge Golf Club At Burley'),
  ('United States', 'Rivers Edge Golf Course')
on conflict (country, name) do nothing;