insert into public.golf_courses (country, name) values
  ('United States', 'Myrtle Beach National Golf Club South Creek Course'),
  ('United States', 'Myrtle Beach National Golf Club West Course'),
  ('United States', 'Mystery Valley Golf Club'),
  ('United States', 'Mystic Creek Golf Club'),
  ('United States', 'Mystic Dunes Golf Club'),
  ('United States', 'Mystic Oak Golf Course'),
  ('United States', 'NCR Country Club'),
  ('United States', 'Nabnasset Lake Country Club'),
  ('United States', 'Naga-Waukee War Memorial Golf Course'),
  ('United States', 'Nags Head Golf Links'),
  ('United States', 'Nahma Golf Course'),
  ('United States', 'Nakoma Country Club'),
  ('United States', 'Nakoma Golf Resort Dragon Course'),
  ('United States', 'Nancy Lopez Golf Course At Spring River'),
  ('United States', 'Nanea Golf Club'),
  ('United States', 'Naniloa Golf Club'),
  ('United States', 'Nansemond River Golf Club'),
  ('United States', 'Nantucket Golf Club'),
  ('United States', 'Napa Golf Course At Kennedy Park'),
  ('United States', 'Napa Valley Country Club'),
  ('United States', 'Naperbrook Golf Course'),
  ('United States', 'Naperville Country Club'),
  ('United States', 'Naples Beach Hotel Golf Club'),
  ('United States', 'Naples Golf Country Club'),
  ('United States', 'Naples Grande Golf Club'),
  ('United States', 'Naples Heritage'),
  ('United States', 'Naples Lakes Country Club'),
  ('United States', 'Naples National Golf Club'),
  ('United States', 'Napoleon Municipal Golf Course'),
  ('United States', 'Nas Jacksonville Golf Club Blue Nine'),
  ('United States', 'Nas Jacksonville Golf Club Red Nine'),
  ('United States', 'Nas Jacksonville Golf Club White Nine'),
  ('United States', 'Nashawtuc Country Club'),
  ('United States', 'Nashua Country Club'),
  ('United States', 'Nashville Country Club'),
  ('United States', 'Nashville Golf Course'),
  ('United States', 'Nassau Country Club'),
  ('United States', 'Natanis Golf Course Arrowhead'),
  ('United States', 'Natanis Golf Course Tomahawk'),
  ('United States', 'Natchez Trace Golf Club'),
  ('United States', 'Natchitoches Country Club'),
  ('United States', 'National City Golf Course'),
  ('United States', 'National Golf Club'),
  ('United States', 'National Golf Club Of Kansas City'),
  ('United States', 'National Golf Links'),
  ('United States', 'National Golf Links Of America'),
  ('United States', 'Nationview Golf Course'),
  ('United States', 'Native Oaks Golf Club'),
  ('United States', 'Nature Walk Course At Chinquapin'),
  ('United States', 'Nature Walk Golf Club'),
  ('United States', 'Naval Air Station Barbers Point Golf Course'),
  ('United States', 'Naval Base San Diegos Golf Performance Center'),
  ('United States', 'Navesink Country Club'),
  ('United States', 'Navy Marine Golf Course'),
  ('United States', 'Needham Golf Club'),
  ('United States', 'Needles Eye Golf Club'),
  ('United States', 'Nehoiden Golf Club At Wellesley College'),
  ('United States', 'Neillsville Country Club'),
  ('United States', 'Nemacolin Country Club'),
  ('United States', 'Nemacolin Woodlands Resort Mystic Rock Course'),
  ('United States', 'Nemacolin Woodlands Resort Shepherds Rock Golf Course'),
  ('United States', 'Nemadji Golf Course'),
  ('United States', 'Neosho Municipal Golf Course Lakes Nine'),
  ('United States', 'Neosho Municipal Golf Course Oaks Nine'),
  ('United States', 'Neosho Municipal Golf Course Valley Nine'),
  ('United States', 'Neshaminy Valley Golf Club'),
  ('United States', 'Neshanic Valley Golf Course Academy Course'),
  ('United States', 'Neshanic Valley Golf Course Lake Ridge Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Lake Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Ridge Course'),
  ('United States', 'Neshobe Golf Club'),
  ('United States', 'Ness County Country Club'),
  ('United States', 'Nettle Creek Country Club'),
  ('United States', 'Neumann Golf Course'),
  ('United States', 'Nevada Country Club'),
  ('United States', 'Nevada County Country Club'),
  ('United States', 'Nevel Meade Golf Course'),
  ('United States', 'New Albany Country Club'),
  ('United States', 'New Albany Golf Course'),
  ('United States', 'New Albany Links Golf Club'),
  ('United States', 'New Berlin Hills Golf Course'),
  ('United States', 'New Bern Golf Country Club'),
  ('United States', 'New Ellenton Golf Course'),
  ('United States', 'New England Golf Club'),
  ('United States', 'New Haven Country Club'),
  ('United States', 'New Haven Golf Club'),
  ('United States', 'New Holland Pitch Putt'),
  ('United States', 'New Hope Village Golf Course'),
  ('United States', 'New Horizons Golf Course'),
  ('United States', 'New Jersey National Golf Club'),
  ('United States', 'New Kirk Country Club'),
  ('United States', 'New Meadows Golf Club'),
  ('United States', 'New Mexico Military Institute Golf Course'),
  ('United States', 'New Mexico State University Golf Course'),
  ('United States', 'New Mexico Tech Golf Course'),
  ('United States', 'New Orleans Country Club'),
  ('United States', 'New Paltz Golf Course'),
  ('United States', 'New Richmond Golf Club'),
  ('United States', 'New Richmond Links Course'),
  ('United States', 'New River Country Club'),
  ('United States', 'New Rockford Golf Club'),
  ('United States', 'New Salisbury Golf Course'),
  ('United States', 'New Smyrna Golf Club'),
  ('United States', 'New Ulm Country Club'),
  ('United States', 'New York Chiropractic College Executive Links Course'),
  ('United States', 'New York Country Club'),
  ('United States', 'New York Presbyterian Hospital Golf Course'),
  ('United States', 'Newark Country Club'),
  ('United States', 'Newark Valley Golf Club'),
  ('United States', 'Newberry Country Club'),
  ('United States', 'Newcastle Country Club'),
  ('United States', 'Newell Golf Course'),
  ('United States', 'Newfane Pro Am Par 3 Golf Course'),
  ('United States', 'Newfoundland Golf Course'),
  ('United States', 'Newlands Golf And Country Club'),
  ('United States', 'Newman Golf Course'),
  ('United States', 'Newman Municipal Golf Course'),
  ('United States', 'Newnan Country Club'),
  ('United States', 'Newport American Legion Country Club'),
  ('United States', 'Newport Beach Country Club'),
  ('United States', 'Newport Beach Golf Course'),
  ('United States', 'Newport Country Club'),
  ('United States', 'Newport Golf Club'),
  ('United States', 'Newport National Golf Club Orchard Course'),
  ('United States', 'Newton Commonwealth Golf Course'),
  ('United States', 'Newton Country Club'),
  ('United States', 'Newton Public Golf Course Driving Range'),
  ('United States', 'Newtown Country Club'),
  ('United States', 'Niagara County Golf Course'),
  ('United States', 'Niagara Falls Country Club'),
  ('United States', 'Niagara Frontier Country Club'),
  ('United States', 'Niagara National Golf Country Club'),
  ('United States', 'Niagara On The Lake Golf Club'),
  ('United States', 'Niagara Orleans Country Club'),
  ('United States', 'Nibley Park Golf Course'),
  ('United States', 'Nick Stoner Golf Course'),
  ('United States', 'Nickerson Dunes Pitch Putt'),
  ('United States', 'Nicklaus At Colleton River Club'),
  ('United States', 'Nicklaus Golf Club At Lionsgate'),
  ('United States', 'Nickol Knoll Golf Course'),
  ('United States', 'Nico Wynd Golf Club'),
  ('United States', 'Nicolet Country Club'),
  ('United States', 'Nile Shrine Golf Course'),
  ('United States', 'Nine At Eagle Crest Golf Course'),
  ('United States', 'Nine Hole At Balboa Park Municipal Golf Club'),
  ('United States', 'Nine Hole At Bangor Municipal Golf Course'),
  ('United States', 'Nine Hole At Bright Leaf Golf Resort'),
  ('United States', 'Nine Hole At On Top Of The World Golf Club'),
  ('United States', 'Nine Hole At Outdoor Resort Country Club'),
  ('United States', 'Nine Hole At Race Brook Country Club'),
  ('United States', 'Nine Hole At Santa Teresa Golf Club'),
  ('United States', 'Nine Hole At South Park Golf Course'),
  ('United States', 'Nine Hole At South Suburban Golf Course'),
  ('United States', 'Nine Hole At Village Links Of Glen Ellyn'),
  ('United States', 'Nine Hole Executive At Viewpoint Golf Resort'),
  ('United States', 'Nine Hole Par 3 At Smithtown Landing Golf Club'),
  ('United States', 'Nine Hole Regulation At Highland View Golf Club'),
  ('United States', 'Nine Springs Golf Course'),
  ('United States', 'Nippersink Resort'),
  ('United States', 'Nippo Lake Golf Club'),
  ('United States', 'Nishna Hills Golf Club'),
  ('United States', 'Nishna Valley Golf Course'),
  ('United States', 'Nissequogue Golf Course'),
  ('United States', 'Nittany Country Club'),
  ('United States', 'Nkmip Canyon Desert Golf Course'),
  ('United States', 'No 7 At Desert Mountain Golf Club'),
  ('United States', 'Nob North Golf Course'),
  ('United States', 'Nocona Hills Country Club'),
  ('United States', 'Nolichucky View Golf Club'),
  ('United States', 'Nonami Plantation Golf Course'),
  ('United States', 'Nonesuch River Golf Club'),
  ('United States', 'Nonquitt Golf Club'),
  ('United States', 'Norfolk Country Club'),
  ('United States', 'Norfolk Golf Club'),
  ('United States', 'Norman K. Probstein Golf Course'),
  ('United States', 'Normandie Golf Club'),
  ('United States', 'Normandy Shores Golf Course'),
  ('United States', 'Normanside Country Club'),
  ('United States', 'Norsk Golf Club'),
  ('United States', 'North Adams Country Club'),
  ('United States', 'North Andover Country Club'),
  ('United States', 'North At Admiral Baker Golf Course'),
  ('United States', 'North At Alondra Park Golf Course'),
  ('United States', 'North At Antelope Hills Golf Course'),
  ('United States', 'North At Bay Palms Golf Complex'),
  ('United States', 'North At Boulders Golf Club Resort'),
  ('United States', 'North At Bretwood Golf Course'),
  ('United States', 'North At Canoe Brook Country Club'),
  ('United States', 'North At Carmel Country Club'),
  ('United States', 'North At Cherokee Town Country Club'),
  ('United States', 'North At Cherokee Village'),
  ('United States', 'North At Coto De Caza Golf Racquet Club'),
  ('United States', 'North At Country Club Of Scranton The'),
  ('United States', 'North At Crestview Country Club'),
  ('United States', 'North At Daytona Beach Golf Country Club'),
  ('United States', 'North At Deerfield Country Club'),
  ('United States', 'North At Earlywine Golf Course'),
  ('United States', 'North At Fountains Country Club'),
  ('United States', 'North At Frenchmans Creek Beach Country Club'),
  ('United States', 'North At Heather Hill Country Club'),
  ('United States', 'North At Hunters Run Golf Course'),
  ('United States', 'North At Hyde Park Golf Course'),
  ('United States', 'North At Ironwood Country Club'),
  ('United States', 'North At Johns Island Club'),
  ('United States', 'North At Lake Hefner Golf Course'),
  ('United States', 'North At Lake Henry Golf Club'),
  ('United States', 'North At Los Angeles Country Club The'),
  ('United States', 'North At Los Serranos Golf Country Club'),
  ('United States', 'North At Moss Creek Golf Club'),
  ('United States', 'North At Quail Ridge Country Club'),
  ('United States', 'North At Raintree Country Club'),
  ('United States', 'North At Rancho Murieta Country Club'),
  ('United States', 'North At Randolph Golf Course'),
  ('United States', 'North At Torrey Pines Municipal Golf Course'),
  ('United States', 'North At Victor Hills Golf Club'),
  ('United States', 'North At Vineyards Of Naples The'),
  ('United States', 'North At Wilmington Country Club'),
  ('United States', 'North Bellingham Golf Course'),
  ('United States', 'North Bend Golf Course'),
  ('United States', 'North Branch Golf Course'),
  ('United States', 'North Carolina State University Club'),
  ('United States', 'North Conway Country Club'),
  ('United States', 'North Country Golf Club'),
  ('United States', 'North County Country Club'),
  ('United States', 'North Course'),
  ('United States', 'North Course At Highlands Ridge'),
  ('United States', 'North Course At Lake Of Isles'),
  ('United States', 'North Course At Shadow Wood Country Club'),
  ('United States', 'North Course At Terry Hills Golf Course'),
  ('United States', 'North Course At Whitefish Lake Golf Club'),
  ('United States', 'North Course Golf Course At Stonewall Links'),
  ('United States', 'North Creek Golf Club'),
  ('United States', 'North East At Athens Country Club'),
  ('United States', 'North East At Farmington Country Club'),
  ('United States', 'North East At Lakes Country Club The'),
  ('United States', 'North East At Oaks North Golf Course'),
  ('United States', 'North East At Ocean Breeze Golf Country Club'),
  ('United States', 'North East At Sahalee Country Club'),
  ('United States', 'North East At Silver Lakes Country Club'),
  ('United States', 'North Eighteen At Cross Creek Resort'),
  ('United States', 'North Fork Country Club'),
  ('United States', 'North Fork Golf Tennis Club'),
  ('United States', 'North Golf Course At Big Cypress Golf Country Club'),
  ('United States', 'North Golf Course At Granite Falls Golf Club'),
  ('United States', 'North Golf Course At Sun City'),
  ('United States', 'North Greens Golf Course'),
  ('United States', 'North Haven Golf Club'),
  ('United States', 'North Hempstead Country Club'),
  ('United States', 'North Hill Country Club'),
  ('United States', 'North Hills Country Club'),
  ('United States', 'North Hills Municipal Golf Course'),
  ('United States', 'North Jersey Country Club'),
  ('United States', 'North Kent Golf Course'),
  ('United States', 'North Kingstown Municipal Golf Club'),
  ('United States', 'North Kossuth Golf Club'),
  ('United States', 'North Las Vegas Golf Course'),
  ('United States', 'North Links Golf Course'),
  ('United States', 'North Oaks Golf Course'),
  ('United States', 'North Olmsted Golf Club'),
  ('United States', 'North Palm Beach Country Club'),
  ('United States', 'North Park Dr Range Par 3'),
  ('United States', 'North Park Golf Course'),
  ('United States', 'North Ridge Country Club'),
  ('United States', 'North Ridge Golf Club'),
  ('United States', 'North Shore Country Club'),
  ('United States', 'North Shore Golf Club'),
  ('United States', 'North Shore Golf Course'),
  ('United States', 'North South At Elmridge Golf Club'),
  ('United States', 'North South At Killearn Country Club Inn'),
  ('United States', 'North South At Krendale Golf Course'),
  ('United States', 'North South At Mountain Gate Country Club'),
  ('United States', 'North South At Rolling Acres Golf Course'),
  ('United States', 'North South At Silver Lakes Country Club'),
  ('United States', 'North South At South Hills Golf Club'),
  ('United States', 'North Star Golf Course'),
  ('United States', 'North Stone Club'),
  ('United States', 'North Topeka Golf Center'),
  ('United States', 'North West At Fernandina Beach Golf Club'),
  ('United States', 'North West At South Hills Golf Club'),
  ('United States', 'North Woodmere Golf Course'),
  ('United States', 'Northampton Country Club'),
  ('United States', 'Northampton Valley Country Club'),
  ('United States', 'Northbrook Country Club'),
  ('United States', 'Northdale Golf Club'),
  ('United States', 'Northeast Harbor Golf Club'),
  ('United States', 'Northern Bay Resort'),
  ('United States', 'Northern FonDuLac Archery Golf'),
  ('United States', 'Northern Hills Golf Course'),
  ('United States', 'Northern Links Golf Course'),
  ('United States', 'Northern Michigan University Golf Course'),
  ('United States', 'Northern Pines Golf Club'),
  ('United States', 'Northfield Country Club'),
  ('United States', 'Northfield Golf Club'),
  ('United States', 'Northfields'),
  ('United States', 'Northgreen Country Club'),
  ('United States', 'Northland Country Club'),
  ('United States', 'Northmoor Country Club'),
  ('United States', 'Northmoor Golf Course'),
  ('United States', 'Northport Creek'),
  ('United States', 'Northport Golf Club'),
  ('United States', 'Northport Golf Course'),
  ('United States', 'Northport Point Golf Club'),
  ('United States', 'Northridge Country Club'),
  ('United States', 'Northridge Hills'),
  ('United States', 'Northside Golf Club'),
  ('United States', 'Northstar California Golf Course'),
  ('United States', 'Northville Hills Golf Club'),
  ('United States', 'Northwest Angle Golf Course'),
  ('United States', 'Northwestern Hills Golf Course'),
  ('United States', 'Northwinds Golf Course'),
  ('United States', 'Northwood Country Club'),
  ('United States', 'Northwood Family Traditions'),
  ('United States', 'Northwood Golf Club'),
  ('United States', 'Northwood Golf Course'),
  ('United States', 'Northwood Hills Golf Course'),
  ('United States', 'Northwoods Golf Course'),
  ('United States', 'Norton Country Club'),
  ('United States', 'Norton Knolls Golf Course'),
  ('United States', 'Norvelt Golf Club Lukes Links Course'),
  ('United States', 'Norvelt Golf Club Norvelt Course'),
  ('United States', 'Norway Country Club'),
  ('United States', 'Norwich Golf Club'),
  ('United States', 'Norwood Acres'),
  ('United States', 'Norwood Country Club'),
  ('United States', 'Norwood Golf Club'),
  ('United States', 'Norwood Hills Country Club'),
  ('United States', 'Norwoods Golf Club'),
  ('United States', 'Nottoway River Country Club'),
  ('United States', 'Nowata Country Club'),
  ('United States', 'Noyac Golf Club'),
  ('United States', 'Noyes Park Golf Course'),
  ('United States', 'NuMark Golf Course'),
  ('United States', 'Nutters Chapel Golf Country Club'),
  ('United States', 'Nutters Crossing Golf Course'),
  ('United States', 'Oahu Country Club'),
  ('United States', 'Oak At Beau Chene Golf Racquet Club'),
  ('United States', 'Oak Bluff At Del Rio Country Club'),
  ('United States', 'Oak Brook Golf'),
  ('United States', 'Oak Brook Golf Club'),
  ('United States', 'Oak Brook Golf Course'),
  ('United States', 'Oak Country Club'),
  ('United States', 'Oak Creek Golf Club'),
  ('United States', 'Oak Creek Golf Course'),
  ('United States', 'Oak Crest Golf Course'),
  ('United States', 'Oak Glen Golf Course'),
  ('United States', 'Oak Grove Golf Club'),
  ('United States', 'Oak Grove Golf Course'),
  ('United States', 'Oak Hall Par 3'),
  ('United States', 'Oak Harbor Country Club'),
  ('United States', 'Oak Harbor Golf Club'),
  ('United States', 'Oak Harbor Golf Course'),
  ('United States', 'Oak Hill Country Club'),
  ('United States', 'Oak Hill Golf Club'),
  ('United States', 'Oak Hill Golf Course'),
  ('United States', 'Oak Hills Country Club'),
  ('United States', 'Oak Hills Golf Club'),
  ('United States', 'Oak Hills Golf Country Club'),
  ('United States', 'Oak Hills Golf Course'),
  ('United States', 'Oak Hills Golf Event Center'),
  ('United States', 'Oak Hills Park Golf Course'),
  ('United States', 'Oak Hollow Golf Course'),
  ('United States', 'Oak Island Golf Club'),
  ('United States', 'Oak Knoll Country Club'),
  ('United States', 'Oak Knoll Golf Course'),
  ('United States', 'Oak Knolls Golf Course'),
  ('United States', 'Oak Lake Golf Course'),
  ('United States', 'Oak Lane Golf Club'),
  ('United States', 'Oak Lawn Country Club'),
  ('United States', 'Oak Leaf Golf Course'),
  ('United States', 'Oak Maple At Hunters Creek Plantation'),
  ('United States', 'Oak Marsh Golf Course'),
  ('United States', 'Oak Meadow Country Club'),
  ('United States', 'Oak Mountain Championship Golf Course'),
  ('United States', 'Oak Park Country Club'),
  ('United States', 'Oak Park Golf & Recreation'),
  ('United States', 'Oak Point At Kiawah Island Golf Resort'),
  ('United States', 'Oak Pointe Country Club'),
  ('United States', 'Oak Quarry Golf Club'),
  ('United States', 'Oak Ridge Golf Club'),
  ('United States', 'Oak Ridge Golf Course'),
  ('United States', 'Oak Run Golf Club'),
  ('United States', 'Oak Shadows Golf Club'),
  ('United States', 'Oak Springs Golf Club'),
  ('United States', 'Oak Stonehouse At Temecula Creek Inn Golf Resort'),
  ('United States', 'Oak Summit Golf Course'),
  ('United States', 'Oak Tree Country Club'),
  ('United States', 'Oak Tree Golf Club'),
  ('United States', 'Oak Tree National Golf Club'),
  ('United States', 'Oak Tree Spruce At Middle Island Country Club'),
  ('United States', 'Oak Valley Golf Club'),
  ('United States', 'Oakbourne Country Club'),
  ('United States', 'Oakbrook Golf Club'),
  ('United States', 'Oakbrook Golf Course'),
  ('United States', 'Oakcreek Country Club'),
  ('United States', 'Oakdale Country Club'),
  ('United States', 'Oakdale Golf Country Club'),
  ('United States', 'Oakdale Golf Course'),
  ('United States', 'Oakgreen Golf Course & Driving Range'),
  ('United States', 'Oakhaven Golf Club'),
  ('United States', 'Oakhurst Country Club')
on conflict (country, name) do nothing;