insert into public.golf_courses (country, name) values
  ('United States', 'Greenbriar Brooklyn'),
  ('United States', 'Greenbriar Golf Club At Whittingham'),
  ('United States', 'Greenbriar Golf Course'),
  ('United States', 'Greenbriar Hills Country Club'),
  ('United States', 'Greenbriar Woodlands Golf Course'),
  ('United States', 'Greenbrier Country Club'),
  ('United States', 'Greenbrier Golf Club'),
  ('United States', 'Greenbrier Greenbrier Course'),
  ('United States', 'Greenbrier Meadows Course'),
  ('United States', 'Greenbrier Old White Course'),
  ('United States', 'Greenbrier Sporting Club Snead Course'),
  ('United States', 'Greenbush Golf Course'),
  ('United States', 'Greencastle Golf Club'),
  ('United States', 'Greendale Golf Course'),
  ('United States', 'Greene Country Club Event Center'),
  ('United States', 'Greene County Country Club'),
  ('United States', 'Greene Hills Club'),
  ('United States', 'Greeneacre Golf Club'),
  ('United States', 'Greenfield Country Club'),
  ('United States', 'Greenfield Lakes Golf Course'),
  ('United States', 'Greenfield Park Golf Course'),
  ('United States', 'Greenhills Golf Course'),
  ('United States', 'Greenhorn Creek Golf Course'),
  ('United States', 'Greenlake Golf Course'),
  ('United States', 'Greenlea Golf Course'),
  ('United States', 'Greenlee Country Club'),
  ('United States', 'Greenock Country Club'),
  ('United States', 'Greens Folly Golf Course'),
  ('United States', 'Greens Golf Racquet Club'),
  ('United States', 'Greens Of Manatee Golf Course'),
  ('United States', 'Greensboro Country Club Farm Course'),
  ('United States', 'Greensboro Country Club Irving Park Course'),
  ('United States', 'Greensboro National Golf Club'),
  ('United States', 'Greensbridge Golf Course'),
  ('United States', 'Greensburg Country Club'),
  ('United States', 'Greenshire Golf Course'),
  ('United States', 'Greenvalley At Greenview Country Club'),
  ('United States', 'Greenview At Greenview Country Club'),
  ('United States', 'Greenview Golf Club'),
  ('United States', 'Greenville Country Club'),
  ('United States', 'Greenville Public Golf Course'),
  ('United States', 'Greenway Creek Golf Course'),
  ('United States', 'Greenway Park Golf Course'),
  ('United States', 'Greenwich Country Club'),
  ('United States', 'Greenwood Country Club'),
  ('United States', 'Greenwood Golf Course'),
  ('United States', 'Greenwood Hills Country Club'),
  ('United States', 'Greer Golf'),
  ('United States', 'Greeville Country Club'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Blue Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Gold Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills North Par 3 Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills South Par 3 Course'),
  ('United States', 'Grenadier Island Country Club'),
  ('United States', 'Gresham Golf Course'),
  ('United States', 'Grey Oaks Country Club Estuary Golf Course'),
  ('United States', 'Grey Oaks Country Club Palm Golf Course'),
  ('United States', 'Grey Oaks Country Club Pine Golf Course'),
  ('United States', 'GreyStone Golf Club'),
  ('United States', 'Greynolds Golf Course'),
  ('United States', 'Greystone Country Club'),
  ('United States', 'Greystone Golf Club'),
  ('United States', 'Greystone Golf Country Club'),
  ('United States', 'Greystone Golf Course'),
  ('United States', 'Greystone Mountain Golf Club'),
  ('United States', 'Greywalls Course At Marquette Golf Club'),
  ('United States', 'Griffin Bell Golf Conference Center'),
  ('United States', 'Griffin City Golf Course'),
  ('United States', 'Griffith E Harris Golf Course'),
  ('United States', 'Grindstone Neck Golf Course'),
  ('United States', 'Grinnell College Golf Course'),
  ('United States', 'Grinnell Cow Paddy Golf Club'),
  ('United States', 'Grizzly Oaks Disc Golf Course'),
  ('United States', 'Grizzly Ranch Golf Club'),
  ('United States', 'Groesbeck Golf Course'),
  ('United States', 'Grosse Ile Golf & Country Club'),
  ('United States', 'Groton Country Club'),
  ('United States', 'Grove City Country Club'),
  ('United States', 'Grove Lakes At Treesdale Golf Country Club'),
  ('United States', 'Grove Park Golf Club'),
  ('United States', 'Grove Park Golf Course'),
  ('United States', 'Grove Xxiii'),
  ('United States', 'Groveport Municipal Golf Course'),
  ('United States', 'Grover Cleveland Golf Course'),
  ('United States', 'Gruis Golf Course'),
  ('United States', 'Gruis Recreation Area The Barn'),
  ('United States', 'Guilford Lakes Golf Course'),
  ('United States', 'Gulf Harbour Golf Country Club'),
  ('United States', 'Gulf Hills Golf Club'),
  ('United States', 'Gulf Stream Golf Course'),
  ('United States', 'Gull Haven Golf Club'),
  ('United States', 'Gull Lake Country Club'),
  ('United States', 'Gull Lake View East'),
  ('United States', 'Gull Lake View West'),
  ('United States', 'Gully Golf Course'),
  ('United States', 'Gulph Mills Golf Club'),
  ('United States', 'Gun Ridge Golf Course'),
  ('United States', 'Gunflint Hills Golf Course'),
  ('United States', 'Guthrie Center Golf Club'),
  ('United States', 'Guthrie Golf Country Club'),
  ('United States', 'Guttenberg Community Golf'),
  ('United States', 'Guttenberg Golf and Country Club'),
  ('United States', 'Guyan Golf and Country Club'),
  ('United States', 'Gypsum Creek Golf Course'),
  ('United States', 'Gypsy Hill Golf Club'),
  ('United States', 'H Smith Richardson Golf Course'),
  ('United States', 'Hacienda Golf Club'),
  ('United States', 'Hackensack Golf Club'),
  ('United States', 'Haddam Community Golf Course'),
  ('United States', 'Hadley Acres Golf Club'),
  ('United States', 'Hadley Creek Golf Learning Center'),
  ('United States', 'Haile Plantation Golf Country Club'),
  ('United States', 'Hailwood Golf Course'),
  ('United States', 'Hale S Location Golf Course'),
  ('United States', 'Hales Mills Country Club'),
  ('United States', 'Half Moon Bay Golf Links Ocean Course'),
  ('United States', 'Half Moon Bay Golf Links Old Course'),
  ('United States', 'Halifax Country Club'),
  ('United States', 'Halifax Plantation'),
  ('United States', 'Halla Greens'),
  ('United States', 'Hallbrook Country Club'),
  ('United States', 'Hamakua Country Club'),
  ('United States', 'Hamilton College Golf Course'),
  ('United States', 'Hamilton Elks Golf Club'),
  ('United States', 'Hamilton Golf Club'),
  ('United States', 'Hamilton Lake Conference Center'),
  ('United States', 'Hamilton Mill Golf Course'),
  ('United States', 'Hamilton Trails Country Club'),
  ('United States', 'Hamlet Golf Country Club'),
  ('United States', 'Hamlet Golf Course'),
  ('United States', 'Hamlin Golf Club'),
  ('United States', 'Hammock At Ocean Reef Club'),
  ('United States', 'Hammock Bay Golf Course'),
  ('United States', 'Hammock Beach Resort The Conservatory Course'),
  ('United States', 'Hammock Beach Resort The Ocean Course'),
  ('United States', 'Hammock Creek Golf Club'),
  ('United States', 'Hammock Dunes Rees Jones Creek Course'),
  ('United States', 'Hammock Dunes Tom Fazio Links Course'),
  ('United States', 'Hammond Golf Center'),
  ('United States', 'Hammond Golf Club'),
  ('United States', 'Hampden Country Club'),
  ('United States', 'Hampshire Country Club'),
  ('United States', 'Hampton Country Club'),
  ('United States', 'Hampton Golf Village'),
  ('United States', 'Hampton Golf and Country Club'),
  ('United States', 'Hampton Hall Club'),
  ('United States', 'Hampton Heights Golf Course'),
  ('United States', 'Hampton Hills Golf Country Club'),
  ('United States', 'Hamptons Golf Club The'),
  ('United States', 'Hanah Mountain Resort Country Club'),
  ('United States', 'Hancock Golf Country Club'),
  ('United States', 'Hanging Rock Golf Club'),
  ('United States', 'Hankerd Hills Golf Course'),
  ('United States', 'Hanks Golf'),
  ('United States', 'Hanks Swank Par Three Golf Course'),
  ('United States', 'Hanks Woodlake Ranch Golf'),
  ('United States', 'Hannastown Golf Club'),
  ('United States', 'Hannibal Country Club'),
  ('United States', 'Hanover Country Club'),
  ('United States', 'Hanover Golf Club'),
  ('United States', 'Hansen Dam Golf Course'),
  ('United States', 'Hansen Park Golf Course'),
  ('United States', 'Hansford Golf Course'),
  ('United States', 'Happy Hollow Club'),
  ('United States', 'Hapuna Golf Course'),
  ('United States', 'Harbor At Wild Dunes Golf Links'),
  ('United States', 'Harbor Club On Lake Oconee'),
  ('United States', 'Harbor Hills Country Club'),
  ('United States', 'Harbor Lights Golf Country Club'),
  ('United States', 'Harbor Links At Sagamore Resort'),
  ('United States', 'Harbor Links Public Golf'),
  ('United States', 'Harbor Oaks Golf Club'),
  ('United States', 'Harbor Park Golf Course'),
  ('United States', 'Harbor Pines Golf Club'),
  ('United States', 'Harbor Point Golf Club'),
  ('United States', 'Harbor Ridge Golf Course'),
  ('United States', 'Harbor Shores'),
  ('United States', 'Harborside International Golf Center'),
  ('United States', 'Harbour Pointe Golf Club'),
  ('United States', 'Harbour Town Golf Links At Sea Pines Resort'),
  ('United States', 'Harbour View Golf Complex'),
  ('United States', 'Harbour Village Golf Yacht Club'),
  ('United States', 'Hardeman County Golf Country Club'),
  ('United States', 'Harding At Griffith Park Golf Courses'),
  ('United States', 'Hardscrabble Country Club'),
  ('United States', 'Hardwick Crossing Country Club'),
  ('United States', 'Hardwood Hills Golf Course'),
  ('United States', 'Hardys Custom Golf Center'),
  ('United States', 'Harkers Hollow Golf Club'),
  ('United States', 'Harlan Country Club'),
  ('United States', 'Harlan Golf and Country Club'),
  ('United States', 'Harlem Golf Course'),
  ('United States', 'Harlem Valley Golf Club'),
  ('United States', 'Harmon Golf Fitness Club'),
  ('United States', 'Harmony Golf Club'),
  ('United States', 'Harmony Golf Club Community'),
  ('United States', 'Harmony Golf Preserve'),
  ('United States', 'Harmony Landing'),
  ('United States', 'Harmony Ridge Golf Club'),
  ('United States', 'Harrington Golf Country Club'),
  ('United States', 'Harris Hill Golf Center'),
  ('United States', 'Harris Park Golf Course'),
  ('United States', 'Harrison Country Club'),
  ('United States', 'Harrison Hills Golf Course'),
  ('United States', 'Harrison Lake Country Club'),
  ('United States', 'Harrison Meadows Country Club'),
  ('United States', 'Harrison Park Golf Course'),
  ('United States', 'Harrisonville Golf Club'),
  ('United States', 'Harrisville Golf Course'),
  ('United States', 'Harry L Jones Sr Golf Course'),
  ('United States', 'Harry Mussatto Golf Course (WIU)'),
  ('United States', 'Hart Ridge Golf Course'),
  ('United States', 'Hartefeld National Golf Club'),
  ('United States', 'Hartford Golf Club'),
  ('United States', 'Hartford Golf Club Blue Course'),
  ('United States', 'Hartford Golf Club Green Course'),
  ('United States', 'Hartford Golf Club Red Course'),
  ('United States', 'Hartland Glen Golf Club'),
  ('United States', 'Hartley Hills Country Club'),
  ('United States', 'Hartmanns Deep Valley Golf Course'),
  ('United States', 'Hartstown Golf Course'),
  ('United States', 'Hartsville Country Club'),
  ('United States', 'Hartwell Golf Club'),
  ('United States', 'Hartwood Golf Course'),
  ('United States', 'Harvard Gulch Golf Course'),
  ('United States', 'Harvest Hill Golf Course'),
  ('United States', 'Harvest Hills Golf Course'),
  ('United States', 'Harvest Point Golf Course'),
  ('United States', 'Harwich Port Golf Club'),
  ('United States', 'Hastings Country Club'),
  ('United States', 'Hat Creek Golf Course'),
  ('United States', 'Hat Island Golf Course'),
  ('United States', 'Hatherly Country Club'),
  ('United States', 'Hattiesburg Country Club'),
  ('United States', 'Havana Golf Country Club'),
  ('United States', 'Havanah Hills'),
  ('United States', 'Havasu Island Golf Course'),
  ('United States', 'Havasu Springs Resort'),
  ('United States', 'Haven At Haven Public Golf Club'),
  ('United States', 'Haven Golf Club'),
  ('United States', 'Haverhill Country Club'),
  ('United States', 'Hawaii Country Club'),
  ('United States', 'Hawaii Kai Executive Golf Course'),
  ('United States', 'Hawaii Kai Golf Course'),
  ('United States', 'Hawaii Prince Golf Club A B Nines'),
  ('United States', 'Hawaii Prince Golf Club B C Nines'),
  ('United States', 'Hawaii Prince Golf Club C A Nines'),
  ('United States', 'Hawarden Golf Course'),
  ('United States', 'Hawk Golf Course'),
  ('United States', 'Hawk Hollow Golf Course'),
  ('United States', 'Hawk Meadows'),
  ('United States', 'Hawk Pointe Golf Course'),
  ('United States', 'Hawk Ridge Golf Course'),
  ('United States', 'Hawk S Eye At Shanty Creek'),
  ('United States', 'Hawk Valley Golf Club'),
  ('United States', 'Hawk''s Eye Golf Course'),
  ('United States', 'Hawk''s View Golf Club'),
  ('United States', 'Hawkes Bay At The Villages Executive Golf Trail'),
  ('United States', 'Hawks Landing Country Club'),
  ('United States', 'Hawks Landing Golf Club'),
  ('United States', 'Hawks Landing Golf Course'),
  ('United States', 'Hawks Point Golf Club'),
  ('United States', 'Hawks Ridge'),
  ('United States', 'Hawks Ridge Par 3 Course'),
  ('United States', 'Hawks Tail Of Greenfield'),
  ('United States', 'Hawkshead'),
  ('United States', 'Hawkshead Links Golf Course'),
  ('United States', 'Hawktree Golf Club'),
  ('United States', 'Hawley Golf and Country Club'),
  ('United States', 'Haworth Golf Club'),
  ('United States', 'Hawthorn Woods Country Club'),
  ('United States', 'Hawthorne Country Club'),
  ('United States', 'Hawthorne Hills Golf Course'),
  ('United States', 'Hawthorne Ridge Golf Course'),
  ('United States', 'Hawthorne Valley Golf Club'),
  ('United States', 'Hay Creek Golf Course'),
  ('United States', 'Hay Harbor Golf Club'),
  ('United States', 'Hayden Golf Club'),
  ('United States', 'Haymaker'),
  ('United States', 'Haynesville Golf Course'),
  ('United States', 'Haystack Mountain Golf Course'),
  ('United States', 'Hayward Golf Club'),
  ('United States', 'Hayward National Golf Club'),
  ('United States', 'Hazard Creek Golf Course'),
  ('United States', 'Hazelden Country Club'),
  ('United States', 'Hazelmere Country Club'),
  ('United States', 'Hazeltine National Golf Course'),
  ('United States', 'Hazelton Golf Club'),
  ('United States', 'Hazen Golf Club'),
  ('United States', 'Hazy Hills Golf Course'),
  ('United States', 'Headland Country Club'),
  ('United States', 'Headwaters Club At Teton Springs'),
  ('United States', 'Headwaters Club At Teton Springs Par 3 Course'),
  ('United States', 'Headwaters Golf Club'),
  ('United States', 'Headwaters Public Golf Course'),
  ('United States', 'Healdsburg Golf Club At Tayman Park'),
  ('United States', 'Healing Springs Ranch'),
  ('United States', 'Healy Point Country Club'),
  ('United States', 'Heart Of America Golf Academy River Course'),
  ('United States', 'Heart Of America Golf Academy Rock Course'),
  ('United States', 'Heart of the Valley Golf Club'),
  ('United States', 'Heartland Crossing Golf Links'),
  ('United States', 'Heartland Golf Park'),
  ('United States', 'Heartland Resort'),
  ('United States', 'Heartwell Golf Course'),
  ('United States', 'Heather Downs Country Club'),
  ('United States', 'Heather Gardens Golf Course'),
  ('United States', 'Heather Golf Country Club'),
  ('United States', 'Heather Highlands Golf Club'),
  ('United States', 'Heather Hills Golf Course'),
  ('United States', 'Heather Ridge Golf Course'),
  ('United States', 'Heathers Club of Bloomfield'),
  ('United States', 'Heatherwoode Golf Club'),
  ('United States', 'Heatherwoods Golf Course'),
  ('United States', 'Heathrow Country Club'),
  ('United States', 'Heaven On Earth Par 3 Ranch Golf Course'),
  ('United States', 'Hebron Country Club'),
  ('United States', 'Hebron Pines Rv And Golf'),
  ('United States', 'Hedingham Golf Club'),
  ('United States', 'Heidelberg Country Club'),
  ('United States', 'Heise Hills Golf Course'),
  ('United States', 'Helena Country Club'),
  ('United States', 'Helena West Helena Public Golf Course'),
  ('United States', 'Helfrich Golf Course'),
  ('United States', 'Hells Point Golf Club'),
  ('United States', 'Hemet Golf Club'),
  ('United States', 'Hemet West Mobile Estates'),
  ('United States', 'Hemingway Kilimanjaro At Havana Country Club'),
  ('United States', 'Hemlock Golf Club'),
  ('United States', 'Hemlock Golf Course'),
  ('United States', 'Hemlock Ridge Golf Course'),
  ('United States', 'Hemlock View Golf Course'),
  ('United States', 'Hempstead Golf Country Club'),
  ('United States', 'Henderson Country Club'),
  ('United States', 'Henderson Golf Club'),
  ('United States', 'Henderson Municipal Golf Course'),
  ('United States', 'Henderson Park Golf Course'),
  ('United States', 'Hendersonville Country Club'),
  ('United States', 'Hendricks Field Golf Course'),
  ('United States', 'Hendricks Golf Club'),
  ('United States', 'Henry Stambaugh Golf Course'),
  ('United States', 'Henryetta Golf Country Club'),
  ('United States', 'Henson Creek Golf Course'),
  ('United States', 'Herington Country Club'),
  ('United States', 'Heritage Bay Golf And Country Club Cypress Course'),
  ('United States', 'Heritage Bay Golf And Country Club Oak Course'),
  ('United States', 'Heritage Bay Golf And Country Club Pine Course'),
  ('United States', 'Heritage Bluffs Public Golf Club'),
  ('United States', 'Heritage Club'),
  ('United States', 'Heritage Country Club'),
  ('United States', 'Heritage Creek Golf Club'),
  ('United States', 'Heritage Eagle Bend Golf Club'),
  ('United States', 'Heritage Glen Golf Club'),
  ('United States', 'Heritage Golf Club'),
  ('United States', 'Heritage Golf Club Blue Course'),
  ('United States', 'Heritage Golf Club Green Course'),
  ('United States', 'Heritage Golf Club Orange Course'),
  ('United States', 'Heritage Golf Links Heritage Nine'),
  ('United States', 'Heritage Golf Links Legacy Nine'),
  ('United States', 'Heritage Golf Links Tradition Nine'),
  ('United States', 'Heritage Harbor'),
  ('United States', 'Heritage Harbour Golf Club'),
  ('United States', 'Heritage Hill Golf Course'),
  ('United States', 'Heritage Hills Golf Course'),
  ('United States', 'Heritage Hills Golf Resort'),
  ('United States', 'Heritage Hunt Golf Club'),
  ('United States', 'Heritage Isles Golf And Country Club'),
  ('United States', 'Heritage Landing Golf Country Club'),
  ('United States', 'Heritage Links'),
  ('United States', 'Heritage Links Golf Club'),
  ('United States', 'Heritage Oaks Golf Club'),
  ('United States', 'Heritage Oaks Golf Country Club'),
  ('United States', 'Heritage Oaks Golf Course'),
  ('United States', 'Heritage Of Hawk Ridge'),
  ('United States', 'Heritage Palms Golf Club'),
  ('United States', 'Heritage Park Golf Course'),
  ('United States', 'Heritage Pines Country Club'),
  ('United States', 'Heritage Ridge Golf Club'),
  ('United States', 'Heritage Shores Golf'),
  ('United States', 'Heritage Springs Country Club'),
  ('United States', 'Heritage Woods Golf Course'),
  ('United States', 'Heritage of Hawk Ridge'),
  ('United States', 'Hermitage Club'),
  ('United States', 'Hermon Meadow Golf Club Training Center'),
  ('United States', 'Hernando Oaks Golf Country Club'),
  ('United States', 'Herndon Centennial Golf Course'),
  ('United States', 'Heroes Golf Course'),
  ('United States', 'Heron At The Villages Executive Golf Trail'),
  ('United States', 'Heron Bay Golf Country Club'),
  ('United States', 'Heron Creek Golf And Country Club Creek Oaks Course'),
  ('United States', 'Heron Creek Golf And Country Club Marsh Creek Course'),
  ('United States', 'Heron Creek Golf And Country Club Oaks Marsh Course'),
  ('United States', 'Heron Creek Golf Club'),
  ('United States', 'Heron Eagle At Okeeheelee Golf Course'),
  ('United States', 'Heron Glen Golf Course'),
  ('United States', 'Heron Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Heron Lakes Golf Club Great Blue Course'),
  ('United States', 'Heron Lakes Golf Club Greenback Course'),
  ('United States', 'Heron Osprey At Burnt Store Marina Country Club'),
  ('United States', 'Heron Pelican At Burnt Store Marina Country Club')
on conflict (country, name) do nothing;
