insert into public.golf_courses (country, name) values
  ('United States', 'Las Vegas Golf Club'),
  ('United States', 'Las Vegas National Golf Course'),
  ('United States', 'Lasalle Golf Country Club'),
  ('United States', 'Lassing Pointe Golf Course'),
  ('United States', 'Latah Creek Golf Course'),
  ('United States', 'Latex Golf Course'),
  ('United States', 'Latimer Golf Club'),
  ('United States', 'Latona Country Club'),
  ('United States', 'Latour Golf Club'),
  ('United States', 'Latourette Golf Course'),
  ('United States', 'Latrobe Country Club'),
  ('United States', 'Latrobe Elks Golf Club'),
  ('United States', 'Latta Lea Golf Club'),
  ('United States', 'Lauderdale Lakes Country Club'),
  ('United States', 'Laughlin Ranch Golf Club'),
  ('United States', 'Laurel Azalea At Houndslake Country Club'),
  ('United States', 'Laurel Country Club'),
  ('United States', 'Laurel Creek Country Club'),
  ('United States', 'Laurel Golf Club'),
  ('United States', 'Laurel Hill Golf Club'),
  ('United States', 'Laurel Island Links'),
  ('United States', 'Laurel Lane Country Club'),
  ('United States', 'Laurel Links Golf Course'),
  ('United States', 'Laurel Mill Golf Course'),
  ('United States', 'Laurel Oak At The Villages Executive Golf Trail'),
  ('United States', 'Laurel Oaks Golf Course'),
  ('United States', 'Laurel Ridge Country Club'),
  ('United States', 'Laurel Springs Golf Club'),
  ('United States', 'Laurel Valley Course At Palmer Legends'),
  ('United States', 'Laurel Valley Golf Club'),
  ('United States', 'Laurens Golf and Country Club'),
  ('United States', 'Lava Creek Golf Course'),
  ('United States', 'Laverne Golf Country Club'),
  ('United States', 'Lawrence Country Club'),
  ('United States', 'Lawrence Park Golf Club'),
  ('United States', 'Lawrence Yacht Country Club'),
  ('United States', 'Lawrenceville School Golf Course The'),
  ('United States', 'Lawton Country Club'),
  ('United States', 'Lawton Golf Club'),
  ('United States', 'Lawton Municipal Golf Course'),
  ('United States', 'Lbi National Golf Resort'),
  ('United States', 'Le Patrimoine Golf Club'),
  ('United States', 'Le Roy Country Club'),
  ('United States', 'Le Triomphe Golf Club'),
  ('United States', 'LeRoy Golf Course'),
  ('United States', 'Lead Country Club'),
  ('United States', 'Leake Country Club'),
  ('United States', 'Leaning Pines Golf Course'),
  ('United States', 'Leaning Rock Golf Course'),
  ('United States', 'Leaning Tree Golf Course'),
  ('United States', 'Leatherstocking Golf Course'),
  ('United States', 'Leavenworth Golf Club'),
  ('United States', 'Lebanon Country Club'),
  ('United States', 'Lebanon Pines Golf Course'),
  ('United States', 'Lebanon Valley Golf Course'),
  ('United States', 'Lebaron Hills Country Club'),
  ('United States', 'Lederach Golf Club'),
  ('United States', 'Ledge Meadows Golf Course'),
  ('United States', 'Ledgemont Country Club'),
  ('United States', 'Ledgerock Golf Club'),
  ('United States', 'Ledges Golf Club'),
  ('United States', 'Ledgeview Golf And Country Club'),
  ('United States', 'Ledgeview Golf Course'),
  ('United States', 'Leeds Golf Club'),
  ('United States', 'Lees Hill Golf Club'),
  ('United States', 'Leesville Municipal Golf Course'),
  ('United States', 'Leewood Golf Club'),
  ('United States', 'Lefleurss Bluff Golf Course'),
  ('United States', 'Leflore County Country Club'),
  ('United States', 'Legacy Club At Alaqua Lakes'),
  ('United States', 'Legacy Courses at Cragun''s'),
  ('United States', 'Legacy Golf Club'),
  ('United States', 'Legacy Golf Club Executive Course'),
  ('United States', 'Legacy Golf Course'),
  ('United States', 'Legacy Golf Course 3 Holes Course'),
  ('United States', 'Legacy Golf Links'),
  ('United States', 'Legacy Hills Golf Club'),
  ('United States', 'Legacy Pines Golf Club'),
  ('United States', 'Legacy Ridge Country Club'),
  ('United States', 'Legacy Ridge Golf Course At Westminster'),
  ('United States', 'Legend At Tahquitz Creek Golf Resort'),
  ('United States', 'Legend Lake Golf Course'),
  ('United States', 'Legend Oaks Golf Club'),
  ('United States', 'Legend Trail Golf Club'),
  ('United States', 'Legend Trail Golf Course'),
  ('United States', 'Legendary Run Golf Course'),
  ('United States', 'Legends Golf Club'),
  ('United States', 'Legends Golf Country Club'),
  ('United States', 'Legends Golf Course'),
  ('United States', 'Legends Golf Resort Heathland Course'),
  ('United States', 'Legends Golf Resort Moorland Course'),
  ('United States', 'Legends Golf Resort Parkland Course'),
  ('United States', 'Legends On The Niagara Golf Course Battlefield'),
  ('United States', 'Legends On The Niagara Golf Course Chippawa'),
  ('United States', 'Legends On The Niagara Golf Course Usshers Creek'),
  ('United States', 'Legends Walk At Orange Lake Resort'),
  ('United States', 'Legion Memorial Golf Course'),
  ('United States', 'Legion Town Country Club'),
  ('United States', 'Lehigh Country Club'),
  ('United States', 'Lehigh Resort Club'),
  ('United States', 'Lehman Golf Club'),
  ('United States', 'Leicester Country Club'),
  ('United States', 'Leilehua Golf Course'),
  ('United States', 'Leisure Village Golf Club'),
  ('United States', 'Leisure Village Golf Course'),
  ('United States', 'Leisure Village Golf Course East Course'),
  ('United States', 'Leisure Village Par 3'),
  ('United States', 'Leisure Village West Pines Nine'),
  ('United States', 'Leisure Village West Willow Nine'),
  ('United States', 'Leisure World 3 Par Golf Course'),
  ('United States', 'Leisure World Golf Coyote Run Course'),
  ('United States', 'Leisure World Golf Heron Lakes Course'),
  ('United States', 'Leisureville Fairway'),
  ('United States', 'Leisureville Golf Course'),
  ('United States', 'Leland Country Club'),
  ('United States', 'Lely Resort Golf Country Club Flamingo Island Course'),
  ('United States', 'Lely Resort Golf Country Club Mustang Course'),
  ('United States', 'Lemon Bay Golf Club'),
  ('United States', 'Lemondrop Lounge Golf Links'),
  ('United States', 'Lemoore Golf Course'),
  ('United States', 'Lenape Heights Golf Course'),
  ('United States', 'Lenawee Country Club'),
  ('United States', 'Lenoir Golf Course'),
  ('United States', 'Lenox Community Golf Course'),
  ('United States', 'Leo J Martin Memorial Golf Course'),
  ('United States', 'Leonardville Golf Course'),
  ('United States', 'Leopards Chase Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Les Bolstad Golf Course'),
  ('United States', 'Les Cheneaux Golf Course'),
  ('United States', 'Les Rochers Bleus Golf And Auberge'),
  ('United States', 'Les Vieux Chenes Golf Course'),
  ('United States', 'Leslie Park Golf Course'),
  ('United States', 'Lester Park Golf Course'),
  ('United States', 'Lew Wentz Golf Course'),
  ('United States', 'Lewis Clark Public Golf Course'),
  ('United States', 'Lewis River Golf Course'),
  ('United States', 'Lewiston Golf & Country Club'),
  ('United States', 'Lewiston Golf Country Club'),
  ('United States', 'Lewistown Country Club'),
  ('United States', 'Lexington Country Club'),
  ('United States', 'Lexington Golf Club'),
  ('United States', 'Lexington Golf Country Club'),
  ('United States', 'Lexington Oaks Golf Club'),
  ('United States', 'Liberal Country Club'),
  ('United States', 'Liberty Forge Golf Course'),
  ('United States', 'Liberty Hills Golf Club'),
  ('United States', 'Liberty Lake Golf Course'),
  ('United States', 'Liberty National Golf Course'),
  ('United States', 'Lick Creek Golf Course'),
  ('United States', 'Lida Greens'),
  ('United States', 'Lidgerwood Golf Course'),
  ('United States', 'Lido Golf Club'),
  ('United States', 'Ligonier Country Club'),
  ('United States', 'Likely Place Rv Golf'),
  ('United States', 'Lilmole Run Golf Course'),
  ('United States', 'Lily Lake Golf Resort'),
  ('United States', 'Limestone Country Club'),
  ('United States', 'Lincoln Country Club'),
  ('United States', 'Lincoln Elks Country Club'),
  ('United States', 'Lincoln Golf Course'),
  ('United States', 'Lincoln Greens Golf Course'),
  ('United States', 'Lincoln Hills Golf Club'),
  ('United States', 'Lincoln Hills Golf Course'),
  ('United States', 'Lincoln Homestead State Park'),
  ('United States', 'Lincoln Oaks Golf Course'),
  ('United States', 'Lincoln Park Golf Course'),
  ('United States', 'Lincoln Valley Golf Course / City of State Center'),
  ('United States', 'Lincolnshire Country Club'),
  ('United States', 'Lincolnshire Fields Country Club'),
  ('United States', 'Linda Vista Golf Course'),
  ('United States', 'Linden Golf Country Club'),
  ('United States', 'Linden Hall Golf Course'),
  ('United States', 'Linderhof Country Club'),
  ('United States', 'Lindsay Municipal Golf Course'),
  ('United States', 'Lindsborg Golf Course'),
  ('United States', 'Lindsey Golf Course'),
  ('United States', 'Linfield National Golf Club'),
  ('United States', 'Link Hills Country Club'),
  ('United States', 'Links & Tees Golf Facility'),
  ('United States', 'Links At Bear Lakes Country Club'),
  ('United States', 'Links At Bentonville Golf Athletic Club'),
  ('United States', 'Links At City Park Golf Course The'),
  ('United States', 'Links At Gettysburg'),
  ('United States', 'Links At Lowell The'),
  ('United States', 'Links At Norman Golf Country Club'),
  ('United States', 'Links At On Top Of The World'),
  ('United States', 'Links At Riverlakes Ranch'),
  ('United States', 'Links At Sandestin Golf And Beach Resort'),
  ('United States', 'Links At Sherwood The'),
  ('United States', 'Links At Sierra Blanca The'),
  ('United States', 'Links At Wild Dunes Golf Links'),
  ('United States', 'Links Canyon At Fox Hollow At Lakewood'),
  ('United States', 'Links Course At Paso Robles'),
  ('United States', 'Links Golf Club'),
  ('United States', 'Links Of Kent Golf Club & Event Centre'),
  ('United States', 'Links Of Lake Bernadette'),
  ('United States', 'Links Of Lake Mary'),
  ('United States', 'Links Of Sandpiper'),
  ('United States', 'Links Of Spruce Creek South'),
  ('United States', 'Links On The Bayou'),
  ('United States', 'Links Otryon'),
  ('United States', 'Links at Gateway'),
  ('United States', 'Links at Northfork'),
  ('United States', 'Links at Whitmore Lake Golf Course'),
  ('United States', 'Linkside At Pebble Creek Country Club'),
  ('United States', 'Linn Grove Country Club'),
  ('United States', 'Linrick Golf Course'),
  ('United States', 'Linville Falls Golf Club'),
  ('United States', 'Linville Golf Club'),
  ('United States', 'Linville Land Harbor Golf Club'),
  ('United States', 'Linville Ridge Country Club'),
  ('United States', 'Linwood Country Club'),
  ('United States', 'Lion Golf Club'),
  ('United States', 'Lion Hills Golf Course At East Mississippi Community College'),
  ('United States', 'Lions Club Municipal Golf Course'),
  ('United States', 'Lions Den Golf Club'),
  ('United States', 'Lions Head Country Club'),
  ('United States', 'Lions Paw At Ocean Ridge Plantation'),
  ('United States', 'Lisbon Village Country Club'),
  ('United States', 'Litchfield Country Club'),
  ('United States', 'Litchfield Golf Club'),
  ('United States', 'Litchfield Greens'),
  ('United States', 'Litl Links Golf Club'),
  ('United States', 'Little America Resort Golf'),
  ('United States', 'Little Apple Golf Course'),
  ('United States', 'Little Bear Golf Club'),
  ('United States', 'Little Bear Golf Course'),
  ('United States', 'Little Creek Golf Course'),
  ('United States', 'Little Creek Recreation Club'),
  ('United States', 'Little Crow Country Club'),
  ('United States', 'Little Falls Golf Course'),
  ('United States', 'Little Falls Municipal Golf Course'),
  ('United States', 'Little Fishing Creek Golf Course'),
  ('United States', 'Little Harbor Country Club'),
  ('United States', 'Little Met Golf Course'),
  ('United States', 'Little Miami Golf Center'),
  ('United States', 'Little Mountain Country Club'),
  ('United States', 'Little Nugget Golf Course (Closed)'),
  ('United States', 'Little Ocmulgee At Wallace Adams Course'),
  ('United States', 'Little River Country Club'),
  ('United States', 'Little River Inn Golf Tennis Club'),
  ('United States', 'Little River Municipal Golf Course'),
  ('United States', 'Little Willow Executive Course'),
  ('United States', 'Littleton Golf And Tennis Club'),
  ('United States', 'Live Oak Pitch Putt Golf Course'),
  ('United States', 'Live Oak Rv Golf Course'),
  ('United States', 'Live Oaks Golf Club'),
  ('United States', 'Livingston Country Club'),
  ('United States', 'Livingston Golf Country Club'),
  ('United States', 'Llanerch Country Club'),
  ('United States', 'Llano Grande Golf Course'),
  ('United States', 'Loblolly Executive Golf Course'),
  ('United States', 'Loblolly Pines Golf Course'),
  ('United States', 'Loch Haven Golf Center'),
  ('United States', 'Loch Lloyd Country Club'),
  ('United States', 'Loch Lloyd Country Club Sechrest Nine'),
  ('United States', 'Loch Lomond Golf Course'),
  ('United States', 'LochenHeath Golf Club'),
  ('United States', 'Lochmere Golf Club'),
  ('United States', 'Lochmere Golf Country Club'),
  ('United States', 'Lochmoor Club'),
  ('United States', 'Lochmor Golf Course'),
  ('United States', 'Lockeford Springs Golf Course'),
  ('United States', 'Lockport Golf and Recreation Club'),
  ('United States', 'Lockport Hole 1'),
  ('United States', 'Lockport Hole 2'),
  ('United States', 'Lockport Hole 3'),
  ('United States', 'Lockport Hole 4'),
  ('United States', 'Lockport Town Country Club'),
  ('United States', 'Lockwood Folly Country Club'),
  ('United States', 'Locust Hill Country Club'),
  ('United States', 'Locust Hills Golf Course'),
  ('United States', 'Lodge Of Four Seasons Cove Course'),
  ('United States', 'Lodge Of Four Seasons Ridge Course'),
  ('United States', 'Lodi Golf Club'),
  ('United States', 'Log Cabin Club'),
  ('United States', 'Logan Country Club'),
  ('United States', 'Logan Golf Country Club'),
  ('United States', 'Logan River Golf Course'),
  ('United States', 'Logansport Country Club'),
  ('United States', 'Loggers Trace'),
  ('United States', 'Loggers Trail Golf Course'),
  ('United States', 'Lomas Santa Fe Country Club'),
  ('United States', 'Lomas Santa Fe Executive Golf Course'),
  ('United States', 'London Downs Golf Club'),
  ('United States', 'Londonderry Country Club'),
  ('United States', 'Lone Palm Golf Club'),
  ('United States', 'Lone Pine Country Club'),
  ('United States', 'Lone Pine Golf Course'),
  ('United States', 'Lone Star Golf Course'),
  ('United States', 'Lone Tree Golf Club'),
  ('United States', 'Lone Tree Golf Club Hotel'),
  ('United States', 'Lone Tree Golf Course'),
  ('United States', 'Lonesome Pine Country Club'),
  ('United States', 'Long Bay Club'),
  ('United States', 'Long Beach Country Club'),
  ('United States', 'Long Bow Golf Club'),
  ('United States', 'Long Bridge Golf Course'),
  ('United States', 'Long Cove Club'),
  ('United States', 'Long Island National Golf Club'),
  ('United States', 'Long Lake Country Club'),
  ('United States', 'Long Meadow Golf Club'),
  ('United States', 'Long Point At Amelia Island Club'),
  ('United States', 'Long Prairie Country Club'),
  ('United States', 'Long Run Golf Course'),
  ('United States', 'Longbow Golf Club'),
  ('United States', 'Longest Hole Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Longhills Golf Course'),
  ('United States', 'Longhis Golf'),
  ('United States', 'Longleaf Executive Golf Course'),
  ('United States', 'Longleaf Golf Family Club'),
  ('United States', 'Longmeadow Country Club'),
  ('United States', 'Longue Vue Club'),
  ('United States', 'Longview Country Club'),
  ('United States', 'Longview Golf Course'),
  ('United States', 'Longwood Golf Course'),
  ('United States', 'Lonnie Poole Golf Course At North Carolina State University'),
  ('United States', 'Lonoke Golf Course'),
  ('United States', 'Lookaway Golf Club'),
  ('United States', 'Lookout Mountain Golf Club'),
  ('United States', 'Loomis Trail Golf Club'),
  ('United States', 'Loons Cove Golf Course'),
  ('United States', 'Lopez Island Golf Club'),
  ('United States', 'Lords Valley Country Club'),
  ('United States', 'Los Alamos Golf Course'),
  ('United States', 'Los Altos Golf Country Club'),
  ('United States', 'Los Altos Golf Course Executive Course'),
  ('United States', 'Los Altos Golf Course Los Altos Course'),
  ('United States', 'Los Amigos Country Club'),
  ('United States', 'Los Caballeros Golf Club'),
  ('United States', 'Los Feliz 3 Par Golf Course'),
  ('United States', 'Los Lagos At Costa Mesa Golf Country Club'),
  ('United States', 'Los Lagos Golf Club'),
  ('United States', 'Los Lagos Golf Course'),
  ('United States', 'Los Lagos La Vista At Desert Princess Country Club'),
  ('United States', 'Los Prados Golf Course'),
  ('United States', 'Los Robles Greens Golf Course'),
  ('United States', 'Los Verdes Golf Course'),
  ('United States', 'Losantiville Country Club'),
  ('United States', 'Lost Brook Golf Club'),
  ('United States', 'Lost City Golf Club East North'),
  ('United States', 'Lost City Golf Club East South'),
  ('United States', 'Lost City Golf Club South North'),
  ('United States', 'Lost Creek Golf Club'),
  ('United States', 'Lost Creek Golfers Club'),
  ('United States', 'Lost Dunes'),
  ('United States', 'Lost Key Golf Club'),
  ('United States', 'Lost Lake Golf Club'),
  ('United States', 'Lost Lake Woods Golf Course'),
  ('United States', 'Lost Marsh Golf Course'),
  ('United States', 'Lost Nation Golf Course'),
  ('United States', 'Lost Plantation Golf Club'),
  ('United States', 'Lost Springs Golf Athletic Club'),
  ('United States', 'Lost Spur Country Club'),
  ('United States', 'Lost Tree Club'),
  ('United States', 'Lost Woods Golf Course'),
  ('United States', 'Loudon Country Club'),
  ('United States', 'Loudon Meadows Golf Club'),
  ('United States', 'Loudoun Golf Country Club'),
  ('United States', 'Louisiana Technical Golf Course'),
  ('United States', 'Louisquisset Golf Club'),
  ('United States', 'Louisville Country Club'),
  ('United States', 'Lovington Country Club'),
  ('United States', 'Lower At Baltusrol Golf Club'),
  ('United States', 'Lower At Peekn Peak Golf Course'),
  ('United States', 'Lowlands Executive Golf Course'),
  ('United States', 'Loxahatchee Club'),
  ('United States', 'Loyal Oak Golf Course'),
  ('United States', 'Lpga International Hills Course'),
  ('United States', 'Lpga International Jones Course'),
  ('United States', 'Lpga International Practice Academy'),
  ('United States', 'Lsu Golf Course'),
  ('United States', 'Lu Gene Links Country Club'),
  ('United States', 'Lucas Oil Golf Course'),
  ('United States', 'Lucerne In Maine Golf Course'),
  ('United States', 'Lucky Hills Golf Course'),
  ('United States', 'Ludden Lake Golf Club'),
  ('United States', 'Ludlow Country Club'),
  ('United States', 'Lulu Country Club'),
  ('United States', 'Lunenburg Country Club'),
  ('United States', 'Lusk Municipal Golf Course'),
  ('United States', 'Lutz Executive Golf Center'),
  ('United States', 'Luverne Country Club'),
  ('United States', 'Lykens Valley Golf Course'),
  ('United States', 'Lyndon Golf Course'),
  ('United States', 'Lyndway Hills Golf Course'),
  ('United States', 'Lynndale''s Golf'),
  ('United States', 'Lynnwood Municipal Golf Course'),
  ('United States', 'Lynrock Golf Course'),
  ('United States', 'Lyon Oaks Golf Course'),
  ('United States', 'Lyons Town Country Club'),
  ('United States', 'M A 8 Golf'),
  ('United States', 'Ma Cal Grove Country Club'),
  ('United States', 'Macatawa Legends Golf & Country Club'),
  ('United States', 'Maccripine Country Club'),
  ('United States', 'Macdonald Golf Course'),
  ('United States', 'Macgregor Downs Country Club'),
  ('United States', 'Mack Mayfield Municipal Golf Course'),
  ('United States', 'Mackinaw Club'),
  ('United States', 'Macktown Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Macoby Run Golf Course'),
  ('United States', 'Macomb Country Club'),
  ('United States', 'Mad Anthony III''s Short Course'),
  ('United States', 'Mad Russian Golf Course'),
  ('United States', 'Madden Golf Course'),
  ('United States', 'Madeline Island Golf Club'),
  ('United States', 'Madera Golf Country Club'),
  ('United States', 'Madera Municipal Golf Course'),
  ('United States', 'Maderas Golf Club'),
  ('United States', 'Madison Country Club'),
  ('United States', 'Madison Golf & Country Club'),
  ('United States', 'Madison Golf Club'),
  ('United States', 'Madison Golf Course'),
  ('United States', 'Madison Green Country Club'),
  ('United States', 'Madison Meadows Golf Club'),
  ('United States', 'Madison Park Golf Course'),
  ('United States', 'Madisonville Country Club'),
  ('United States', 'Madrid Golf Course'),
  ('United States', 'Madrona Links Golf Course'),
  ('United States', 'Magellan Golf Course'),
  ('United States', 'Maggie Hathaway Par 3 Golf Course'),
  ('United States', 'Maggie Valley Resort Country Club'),
  ('United States', 'Magnolia At Beau Chene Golf Racquet Club'),
  ('United States', 'Magnolia Country Club'),
  ('United States', 'Magnolia Dogwood At Callawassie Island Club'),
  ('United States', 'Magnolia Green Golf Club'),
  ('United States', 'Magnolia Greens Golf Course Camellia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Camellia'),
  ('United States', 'Magnolia Grove Golf Club Crossings Course'),
  ('United States', 'Magnolia Grove Golf Club Falls Course'),
  ('United States', 'Magnolia Grove Golf Club Short Course'),
  ('United States', 'Magnolia Highlands At Highland Oaks Golf Course'),
  ('United States', 'Magnolia Landing Golf Country Club'),
  ('United States', 'Magnolia Plantation Golf Club'),
  ('United States', 'Magnolia Point Golf Country Club'),
  ('United States', 'Magnolia Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Magnolia Willow At Ben Geren Regional Park Golf Course'),
  ('United States', 'Mahnomen County Country Club'),
  ('United States', 'Mahoney Golf Course'),
  ('United States', 'Mahoning Country Club'),
  ('United States', 'Mahopac Golf Club'),
  ('United States', 'Main At Brae Burn Country Club'),
  ('United States', 'Main At Country Club The'),
  ('United States', 'Main At Shadow Lake Golf Racquet Club'),
  ('United States', 'Maine Golf Center Freeport'),
  ('United States', 'Mainland Golf Course'),
  ('United States', 'Mainlands Golf Course'),
  ('United States', 'Majestic Hills Golf Course'),
  ('United States', 'Majestic Oaks Golf Club'),
  ('United States', 'Majestic Oaks at Lake Lawn Resort'),
  ('United States', 'Majestic Springs Golf Club'),
  ('United States', 'Majestic at Lake Walden Golf Course'),
  ('United States', 'Makaha Valley Country Club'),
  ('United States', 'Makalei Golf Club'),
  ('United States', 'Makani Golf Club'),
  ('United States', 'Makefield Highlands Golf Club'),
  ('United States', 'Makena Beach Golf Resort'),
  ('United States', 'Maketewah Country Club'),
  ('United States', 'Makray Memorial Golf Club'),
  ('United States', 'Malden Country Club'),
  ('United States', 'Malden Municipal Golf Course'),
  ('United States', 'Mallard Creek Golf Club'),
  ('United States', 'Mallard Golf Club'),
  ('United States', 'Mallard Head Country Club'),
  ('United States', 'Mallard Pointe Golf Course'),
  ('United States', 'Mallards Landing Golf Course At Melbourne'),
  ('United States', 'Malvern Country Club'),
  ('United States', 'Mamala Bay Golf Course'),
  ('United States', 'Man O War Golf Course'),
  ('United States', 'Manada Golf Club'),
  ('United States', 'Manakiki Golf Course'),
  ('United States', 'Manakin At Hermitage Country Club'),
  ('United States', 'Manasquan River Golf Club'),
  ('United States', 'Manatee Cove Golf Course'),
  ('United States', 'Manatee Golf Course'),
  ('United States', 'Manchester Country Club'),
  ('United States', 'Manchester Golf and Country Club'),
  ('United States', 'Manele Golf Course'),
  ('United States', 'Mangrove At The Villages Executive Golf Trail'),
  ('United States', 'Mangrove Bay Golf Course'),
  ('United States', 'Mangum Golf Course'),
  ('United States', 'Manhattan Country Club'),
  ('United States', 'Manhattan Woods Golf Club'),
  ('United States', 'Manistee Golf & Country Club'),
  ('United States', 'Manito Golf Country Club'),
  ('United States', 'Manitou Passage Golf Club'),
  ('United States', 'Manitou Ridge Golf Course'),
  ('United States', 'Manitoulin Island Country Club'),
  ('United States', 'Manning Manilla Golf Course'),
  ('United States', 'Mannitto Golf Club'),
  ('United States', 'Manor Golf Course'),
  ('United States', 'Manor Valley Country Club'),
  ('United States', 'Mansfield Golf Country Club'),
  ('United States', 'Manson Golf and Country Club'),
  ('United States', 'Manteca Park Golf Course'),
  ('United States', 'Manteno Golf Club'),
  ('United States', 'Manufacturers Golf Country Club'),
  ('United States', 'Maple Bluff Country Club'),
  ('United States', 'Maple Brook Golf Course'),
  ('United States', 'Maple Chase Golf Country Club'),
  ('United States', 'Maple Creek Golf Club'),
  ('United States', 'Maple Creek Golf and Country Club'),
  ('United States', 'Maple Crest Golf Course'),
  ('United States', 'Maple Dale Country Club'),
  ('United States', 'Maple Grove Golf'),
  ('United States', 'Maple Grove Golf Course'),
  ('United States', 'Maple Heights Golf and Country Club'),
  ('United States', 'Maple Hill Golf Club'),
  ('United States', 'Maple Hill Golf Course'),
  ('United States', 'Maple Hills Golf Course'),
  ('United States', 'Maple Hills Public Golf Course'),
  ('United States', 'Maple Lane Golf Club'),
  ('United States', 'Maple Lane Golf Course'),
  ('United States', 'Maple Leaf Golf Country Club'),
  ('United States', 'Maple Leaf Golf Course'),
  ('United States', 'Maple Meadows Golf Club'),
  ('United States', 'Maple Moor Golf Course'),
  ('United States', 'Maple Ridge Golf'),
  ('United States', 'Maple Ridge Golf Club'),
  ('United States', 'Maple River Golf Club'),
  ('United States', 'Maple River Resort'),
  ('United States', 'Maple Run Golf Course'),
  ('United States', 'Maple Valley Golf & Country Club'),
  ('United States', 'Maple Willow At Hunters Creek Plantation'),
  ('United States', 'Maplecrest Country Club'),
  ('United States', 'Maplegate Country Club'),
  ('United States', 'Maplehurst Country Club'),
  ('United States', 'Maples At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Maplewood Country Club'),
  ('United States', 'Maplewood Golf Club'),
  ('United States', 'Maplewood Golf Course'),
  ('United States', 'Mapple Hills'),
  ('United States', 'Maquoketa Country Club'),
  ('United States', 'Marbella Country Club'),
  ('United States', 'Marcus Community Golf Club'),
  ('United States', 'Marcus Pointe Golf Club'),
  ('United States', 'Marengo Golf Club'),
  ('United States', 'Marengo Ridge Golf Curse'),
  ('United States', 'Margate Executive Golf Course'),
  ('United States', 'Mari Mac Golf Complex'),
  ('United States', 'Mariah Hills'),
  ('United States', 'Marian Hills Golf Course'),
  ('United States', 'Mariana Butte Golf Course'),
  ('United States', 'Marianna Country Club'),
  ('United States', 'Marias Valley Golf Country Club'),
  ('United States', 'Marietta Country Club'),
  ('United States', 'Marietta Country Club Lake View Nine'),
  ('United States', 'Marietta Country Club Mountain View Nine'),
  ('United States', 'Marietta Country Club Overlook Nine'),
  ('United States', 'Marin Country Club'),
  ('United States', 'Marine Memorial Golf Course'),
  ('United States', 'Marine Park Golf Course'),
  ('United States', 'Mariner Sands Country Club Blue Course'),
  ('United States', 'Mariner Sands Country Club Gold Course'),
  ('United States', 'Mariners Landing Golf Country Club'),
  ('United States', 'Mariners Point Golf Links Practice Center'),
  ('United States', 'Marion Country Club'),
  ('United States', 'Marion Golf Club'),
  ('United States', 'Marion Lake Golf Club'),
  ('United States', 'Marion Oaks Country Club'),
  ('United States', 'Marjon Golf Course'),
  ('United States', 'Mark Bostick Golf Course At The University Of Florida'),
  ('United States', 'Mark Twain Golf Course'),
  ('United States', 'Mark''s Golf'),
  ('United States', 'Mark''s Par 3'),
  ('United States', 'Marlboro Country Club'),
  ('United States', 'Marlborough Country Club'),
  ('United States', 'Maroon Creek Club Golf Course'),
  ('United States', 'Marquette Golf Club'),
  ('United States', 'Marquette Golf Club Greywalls'),
  ('United States', 'Marquette Park Golf Course'),
  ('United States', 'Marquette Trails Country Club'),
  ('United States', 'Marrakesh Golf Club'),
  ('United States', 'Mars Bethel Golf Course'),
  ('United States', 'Mars Hill Country Club'),
  ('United States', 'Marsh At Bonita Bay Club'),
  ('United States', 'Marsh Creek Country Club'),
  ('United States', 'Marsh Landing Country Club'),
  ('United States', 'Marsh Ridge Golf Course and Resort'),
  ('United States', 'Marsh View Pitch Putt'),
  ('United States', 'Marshall Canyon Golf Club'),
  ('United States', 'Marshall Country Club'),
  ('United States', 'Marshall Golf Club'),
  ('United States', 'Marshall Lakeside Country Club'),
  ('United States', 'Marshfield Country Club'),
  ('United States', 'Marshwood Magnolia At Highland Oaks Golf Course'),
  ('United States', 'Martin Downs Country Club Osprey Creek Course'),
  ('United States', 'Martindale Country Club'),
  ('United States', 'Martinsville Golf Club'),
  ('United States', 'Martis Camp Club'),
  ('United States', 'Marty Sanchez Links De Santa Fe Great 28 Course'),
  ('United States', 'Marty Sanchez Links De Santa Fe Links Course'),
  ('United States', 'Mary Calder Golf Club'),
  ('United States', 'Marysville Country Club'),
  ('United States', 'Marysville Golf Club'),
  ('United States', 'Marysville Golf Course'),
  ('United States', 'Marywood Country Club'),
  ('United States', 'Mascoutin Golf Club'),
  ('United States', 'Mason City Country Club'),
  ('United States', 'Massanutten Resort Mountain Greens Course'),
  ('United States', 'Massanutten Resort Woodstone Meadows Course'),
  ('United States', 'Massena Country Club'),
  ('United States', 'Masterpiece'),
  ('United States', 'Mastick Woods Golf Course'),
  ('United States', 'Mather Golf Course'),
  ('United States', 'Mattawang Golf Club'),
  ('United States', 'Matthew Creek Par 3'),
  ('United States', 'Mattoon Golf & Country Club'),
  ('United States', 'Mauh-Nah-Tee-See Country Club'),
  ('United States', 'Maui Country Club'),
  ('United States', 'Maui Nui Golf Club'),
  ('United States', 'Maumee Bay State Park Golf Course'),
  ('United States', 'Maumelle Country Club'),
  ('United States', 'Mauna Kea Golf Course'),
  ('United States', 'Mauna Lani Resort North Course'),
  ('United States', 'Mauna Lani Resort South Course'),
  ('United States', 'Mauna Lani Resort Wikiwiki Course'),
  ('United States', 'Maxwelton Braes Golf Resort'),
  ('United States', 'Maxwelton Golf Club'),
  ('United States', 'May River Golf Course At Palmetto Bluff'),
  ('United States', 'Mayacama Golf Club'),
  ('United States', 'Mayacoo Lakes Country Club'),
  ('United States', 'Mayapple Golf Links'),
  ('United States', 'Mayfair Country Club'),
  ('United States', 'Mayfield Sand Ridge Club'),
  ('United States', 'Mayflower Golf Club'),
  ('United States', 'Maynard Golf Course'),
  ('United States', 'Mays Landing Golf Club'),
  ('United States', 'Mayville Golf Club'),
  ('United States', 'Mayville Golf Course'),
  ('United States', 'McArthur Golf Course'),
  ('United States', 'McCaslin Brook Golf & Country Club'),
  ('United States', 'McCormick Creek Golf Course'),
  ('United States', 'McDonald Golf Course'),
  ('United States', 'McHenry Country Club'),
  ('United States', 'McLeansboro Golf Club'),
  ('United States', 'McMillen Park Golf Course'),
  ('United States', 'Mcalester Country Club'),
  ('United States', 'Mcarthur Golf Club'),
  ('United States', 'Mcarthur Golf Club Backyard Course'),
  ('United States', 'Mccall Field Golf Course'),
  ('United States', 'Mccanless Golf Club'),
  ('United States', 'Mccann Memorial Golf Course'),
  ('United States', 'Mccloud Golf Club'),
  ('United States', 'Mcconnellsville Golf Club'),
  ('United States', 'Mccormick Country Club'),
  ('United States', 'Mccormick Woods Golf Course'),
  ('United States', 'Mcculloughs Emerald Golf Links'),
  ('United States', 'Mcdaniel College Golf Club'),
  ('United States', 'Mcdonald Hills Golf Club'),
  ('United States', 'Mcdowell Mountain Golf Club'),
  ('United States', 'Mcgregor Links Country Club'),
  ('United States', 'Mcinnis Park Golf Center'),
  ('United States', 'Mckenzie Memorial Golf Course'),
  ('United States', 'Mclemore Club Highlands Course'),
  ('United States', 'Mclemore Club The Cairn Short Course'),
  ('United States', 'Mclemore Club The Keep'),
  ('United States', 'Mcpherson Country Club'),
  ('United States', 'Meade Country Club'),
  ('United States', 'Meadia Heights Golf Club'),
  ('United States', 'Meadow Acres Golf Course'),
  ('United States', 'Meadow At Forest Highlands Golf Club'),
  ('United States', 'Meadow At Mulligans South'),
  ('United States', 'Meadow Brook Club'),
  ('United States', 'Meadow Brook Golf Club'),
  ('United States', 'Meadow Brook Golf Course'),
  ('United States', 'Meadow Club'),
  ('United States', 'Meadow Course At Fiddlers Elbow Country Club'),
  ('United States', 'Meadow Creek Dogwood At Lancaster Country Club'),
  ('United States', 'Meadow Creek Golf Course'),
  ('United States', 'Meadow Golf Course At Pole Creek Golf Club'),
  ('United States', 'Meadow Greens Golf Course'),
  ('United States', 'Meadow Hills Golf Course'),
  ('United States', 'Meadow Lake Golf Club'),
  ('United States', 'Meadow Lake Golf Country Club'),
  ('United States', 'Meadow Lake Golf Resort'),
  ('United States', 'Meadow Lake Village And Golf Course'),
  ('United States', 'Meadow Lakes Golf Club'),
  ('United States', 'Meadow Lane Golf Course'),
  ('United States', 'Meadow Lark Country Club'),
  ('United States', 'Meadow Links & Golf Academy'),
  ('United States', 'Meadow Links At Fox Hollow At Lakewood'),
  ('United States', 'Meadow Links Golf Course'),
  ('United States', 'Meadow Links Golf Course At George T Bagby'),
  ('United States', 'Meadow Oak Golf Club'),
  ('United States', 'Meadow Oaks Golf Country Club'),
  ('United States', 'Meadow Park At Meadow Park Golf Course'),
  ('United States', 'Meadow Ponds Golf Course'),
  ('United States', 'Meadow Springs Country Club'),
  ('United States', 'Meadow Valley Golf Club'),
  ('United States', 'Meadow Valleys At Blackwolf Run Golf Course'),
  ('United States', 'Meadow Woods'),
  ('United States', 'Meadowbrook Country Club'),
  ('United States', 'Meadowbrook Golf Club'),
  ('United States', 'Meadowbrook Golf Course'),
  ('United States', 'Meadowbrook Golf and Country Club'),
  ('United States', 'Meadowbrook at Clayton'),
  ('United States', 'Meadowcreek Golf Course'),
  ('United States', 'Meadowcreek Golf Resort'),
  ('United States', 'Meadowgreens Golf Course'),
  ('United States', 'Meadowink Golf Course'),
  ('United States', 'Meadowlake Golf Course'),
  ('United States', 'Meadowland Golf Course'),
  ('United States', 'Meadowlands Golf Club'),
  ('United States', 'Meadowlands Golf Course'),
  ('United States', 'Meadowlark Golf Course'),
  ('United States', 'Meadowmeer Golf Country Club'),
  ('United States', 'Meadowood Golf Course'),
  ('United States', 'Meadowood Golf Tennis Club'),
  ('United States', 'Meadows Creekside At Traces Golf Club The'),
  ('United States', 'Meadows Golf Center'),
  ('United States', 'Meadows Golf Club'),
  ('United States', 'Meadows Golf Club The'),
  ('United States', 'Meadows Golf Course The'),
  ('United States', 'Meadows Oaks Golf Course At Pennbrooke Fairways'),
  ('United States', 'Meadows Of Six Mile Creek'),
  ('United States', 'Meadows Pinon At Pagosa Springs Golf Club'),
  ('United States', 'Meadowview Golf & Country Club'),
  ('United States', 'Meadowview Golf Course'),
  ('United States', 'Meadowwood Golf Course'),
  ('United States', 'Meander Golf Course'),
  ('United States', 'Mechanicville Golf Club'),
  ('United States', 'Mecklenburg Country Club'),
  ('United States', 'Medal Of Honor Golf Course'),
  ('United States', 'Medalist Golf Club'),
  ('United States', 'Medalist Village Golf'),
  ('United States', 'Medallion Golf Club'),
  ('United States', 'Medford Lakes Country Club'),
  ('United States', 'Medford Village Country Club'),
  ('United States', 'Medicine Lodge Golf Club'),
  ('United States', 'Medina Golf & Country Club'),
  ('United States', 'Medinah Country Club'),
  ('United States', 'Mee-Kwon Park Golf Course'),
  ('United States', 'Meeker Golf Course'),
  ('United States', 'Megunticook Golf Club'),
  ('United States', 'Meigs Golf Course'),
  ('United States', 'Mellen country Club'),
  ('United States', 'Melody Hill Golf Course'),
  ('United States', 'Melrose Country Club'),
  ('United States', 'Members Club At St James Plantation Cate Nine Course'),
  ('United States', 'Members Club At St James Plantation Irwin Course'),
  ('United States', 'Memorial Links Golf Club'),
  ('United States', 'Memorial Park Golf Course'),
  ('United States', 'Memphis Athletic Ministries Park Golf Course'),
  ('United States', 'Memphis Country Club The'),
  ('United States', 'Memphis National Golf Club Champions Course'),
  ('United States', 'Memphis National Golf Club Legends Course'),
  ('United States', 'Memphremagog Golf Club'),
  ('United States', 'Mendakota Country Club'),
  ('United States', 'Mendenhall Golf Course'),
  ('United States', 'Mendham Golf Tennis Club'),
  ('United States', 'Mendon Golf Club'),
  ('United States', 'Mendota Golf Club'),
  ('United States', 'Mendota Heights Par 3 Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Lakes Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Palms Golf Course'),
  ('United States', 'Menlo Country Club'),
  ('United States', 'Menomonie Country Club'),
  ('United States', 'Mentel Memorial Golf Course'),
  ('United States', 'Meramec Lakes Golf Course'),
  ('United States', 'Merced Golf Country Club'),
  ('United States', 'Mercer County Elks Golf Club'),
  ('United States', 'Mercer Oaks Golf Course East Course'),
  ('United States', 'Mercer Oaks Golf Course West Course'),
  ('United States', 'Mercer Public Golf Course'),
  ('United States', 'Merchantville Country Club'),
  ('United States', 'Mere Creek Golf Course'),
  ('United States', 'Meridian Golf Club'),
  ('United States', 'Meridian Golf Par 3 Golf Club'),
  ('United States', 'Meridian Hills County Club'),
  ('United States', 'Meridian Sun Golf Club'),
  ('United States', 'Meridian Valley Country Club'),
  ('United States', 'Merit Club'),
  ('United States', 'Mermaid Swim Golf Club'),
  ('United States', 'Merrick Road Park Golf Course'),
  ('United States', 'Merriland Farm Par 3 Golf Course'),
  ('United States', 'Merrill Golf Club'),
  ('United States', 'Merrimack Valley Golf Club'),
  ('United States', 'Mesa At Adobe Creek National Golf Course'),
  ('United States', 'Mesa Country Club'),
  ('United States', 'Mesa Del Sol Golf Course'),
  ('United States', 'Mesa Linda At Costa Mesa Golf Country Club'),
  ('United States', 'Mesa Verde Country Club'),
  ('United States', 'Mesa View Golf Course'),
  ('United States', 'Mesaba Country Club'),
  ('United States', 'Mesquite Ironwood At Kierland Golf Club'),
  ('United States', 'Met Links'),
  ('United States', 'Metairie Country Club'),
  ('United States', 'Metamora Country Club'),
  ('United States', 'Metamora Fields Golf Club'),
  ('United States', 'Metchosin Golf And Country Club'),
  ('United States', 'Methodist College Golf Club'),
  ('United States', 'Metropolis Country Club'),
  ('United States', 'Metrowest Golf Club'),
  ('United States', 'Metuchen Golf Country Club'),
  ('United States', 'Mga Links At Mamantapett'),
  ('United States', 'Miacomet Golf Course'),
  ('United States', 'Miami Beach Golf Club'),
  ('United States', 'Miami Shores Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Miami Shores Golf Course'),
  ('United States', 'Miami Springs Golf Country Club'),
  ('United States', 'Miami Valley Golf Club'),
  ('United States', 'Miami Whitewater Forest Golf Course'),
  ('United States', 'Miamiview Golf Course'),
  ('United States', 'Miccosukee Golf Country Club Barracuda Course'),
  ('United States', 'Miccosukee Golf Country Club Dolphin Course'),
  ('United States', 'Miccosukee Golf Country Club Marlin Course'),
  ('United States', 'Michaywe Pines'),
  ('United States', 'Michigan City Municipal Golf Course'),
  ('United States', 'Michigan Meadows Golf Course'),
  ('United States', 'Michipicoten Golf Club'),
  ('United States', 'Micke Grove Golf Links'),
  ('United States', 'Mickey S On Flambeau'),
  ('United States', 'Mickey''s Golf Range'),
  ('United States', 'Mickylee Pitch Putt At The Villages Executive Golf Trail'),
  ('United States', 'Mid Carolina Club'),
  ('United States', 'Mid Iron Golf Club'),
  ('United States', 'Mid Pacific Country Club'),
  ('United States', 'Mid Pines Inn Golf Club'),
  ('United States', 'Mid South Club'),
  ('United States', 'Mid Vallee Golf Course'),
  ('United States', 'Middle Back At Rolling Green Golf Club'),
  ('United States', 'Middle Channel Golf & Country Club'),
  ('United States', 'Middle Lake At Woodbridge Golf Country Club'),
  ('United States', 'Middle South At Heather Hill Country Club'),
  ('United States', 'Middlebrook Country Club'),
  ('United States', 'Middlecreek Golf Course'),
  ('United States', 'Middlefork Country Club'),
  ('United States', 'Middlesboro Country Club'),
  ('United States', 'Middleton Golf Course'),
  ('United States', 'Middletown Country Club'),
  ('United States', 'Midland Country Club'),
  ('United States', 'Midland Hills Country Club'),
  ('United States', 'Midland Trail Golf Club'),
  ('United States', 'Midland Valley Golf Club'),
  ('United States', 'Midlane Golf Resort'),
  ('United States', 'Midlothian Country Club'),
  ('United States', 'Midnight Sun Golf Course'),
  ('United States', 'Midvale Golf Country Club'),
  ('United States', 'Midville Country Club'),
  ('United States', 'Midway Golf Club'),
  ('United States', 'Midway Golf Complex'),
  ('United States', 'Midway Par 3 East Nine'),
  ('United States', 'Midway Par 3 Golf Course'),
  ('United States', 'Midway Par 3 North Nine'),
  ('United States', 'Midway Par 3 West Nine'),
  ('United States', 'Milan Creek Golf Course'),
  ('United States', 'Milbrook Club'),
  ('United States', 'Milburn Country Club'),
  ('United States', 'Mile Square Golf Course The Classic Course'),
  ('United States', 'Mile Square Golf Course The Players Course'),
  ('United States', 'Miles City Town Country Club'),
  ('United States', 'Miles Grant Country Club'),
  ('United States', 'Milestone Golf Club'),
  ('United States', 'Milford Country Club'),
  ('United States', 'Milham Park Golf Club'),
  ('United States', 'Mililani Golf Club'),
  ('United States', 'Militia Hill Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Mill Creek Country Club'),
  ('United States', 'Mill Creek Golf Club'),
  ('United States', 'Mill Creek Golf Course'),
  ('United States', 'Mill Creek Golf Course (North)'),
  ('United States', 'Mill Creek Golf Course (South)'),
  ('United States', 'Mill Creek Metroparks Par-3 Golf Course'),
  ('United States', 'Mill Pond Golf Course'),
  ('United States', 'Mill Quarter Plantation Country Club'),
  ('United States', 'Mill Race Golf Camping Resort'),
  ('United States', 'Mill Race Golf Course'),
  ('United States', 'Mill River Club'),
  ('United States', 'Mill River Country Club'),
  ('United States', 'Mill Road Acres Golf Course'),
  ('United States', 'Mill Run Golf Course'),
  ('United States', 'Mill Valley Country Club'),
  ('United States', 'Mill Valley Golf Course'),
  ('United States', 'Millbrook Country Club'),
  ('United States', 'Millbrook Golf Tennis Club'),
  ('United States', 'Millburn Municipal Golf Course'),
  ('United States', 'Millcreek Golf And Learning Center'),
  ('United States', 'Millers Glen Golf Gourse'),
  ('United States', 'Mills Creek Golf Course'),
  ('United States', 'Millsite Golf Course'),
  ('United States', 'Millstone Executive Golf Course'),
  ('United States', 'Millstone Golf Course'),
  ('United States', 'Millwood Country Club'),
  ('United States', 'Millwood Farms Golf Course'),
  ('United States', 'Millwood Landing Golf Rv Resort'),
  ('United States', 'Milt''s Golf Course (9-Hole)'),
  ('United States', 'Milton Freewater Golf Course'),
  ('United States', 'Miltonvale Country Club'),
  ('United States', 'Milts Golf Center'),
  ('United States', 'Milwaukee Country Club'),
  ('United States', 'Mimosa Hills Golf Country Club'),
  ('United States', 'Minakwa Golf Course'),
  ('United States', 'Miner Hills Golf Course'),
  ('United States', 'Mineral Mound State Park Golf Course'),
  ('United States', 'Minerals Golf Club'),
  ('United States', 'Mines Golf Course'),
  ('United States', 'Mingo Bottom Golf Club'),
  ('United States', 'Mingo Springs Golf Course'),
  ('United States', 'Mini Golf'),
  ('United States', 'Mini-Golf'),
  ('United States', 'Mini-golf Course'),
  ('United States', 'Miniature Golf'),
  ('United States', 'Minibel Golf Course'),
  ('United States', 'Mink Lake Golf Course'),
  ('United States', 'Mink Meadows Golf Club'),
  ('United States', 'Minne Monesse Golf Club'),
  ('United States', 'Minneapolis Golf Club'),
  ('United States', 'Minneapolis Golf Course'),
  ('United States', 'Minnechaug Golf Course'),
  ('United States', 'Minnehaha Country Club'),
  ('United States', 'Minneopa Golf Club'),
  ('United States', 'Minnesota Valley Country Club'),
  ('United States', 'Minnesott Golf Country Club'),
  ('United States', 'Minnesuing Acres Conference Center'),
  ('United States', 'Minniwaska Golf Club'),
  ('United States', 'Minocqua Country Club'),
  ('United States', 'Minor Park Golf Course'),
  ('United States', 'Mint Valley Golf Course'),
  ('United States', 'Mint Valley Golf Course Executive Course'),
  ('United States', 'Mira Mesa At The Villages Executive Golf Trail'),
  ('United States', 'Mirabel Golf Club'),
  ('United States', 'Miracle Hill Driving Range'),
  ('United States', 'Miracle Hill Golf Course'),
  ('United States', 'Miramar Memorial Golf Course'),
  ('United States', 'Miromar Lakes Golf Club'),
  ('United States', 'Mirror Lake Golf Club Lake Course'),
  ('United States', 'Mirror Lake Golf Club Mountain Course'),
  ('United States', 'Mirror Lake Golf Course'),
  ('United States', 'Misquamicut Club'),
  ('United States', 'Missaukee Golf Club'),
  ('United States', 'Missing Links Golf Course'),
  ('United States', 'Mission Bay Golf Course'),
  ('United States', 'Mission Hills Country Club'),
  ('United States', 'Mission Hills Gary Player Course'),
  ('United States', 'Mission Hills Golf Course'),
  ('United States', 'Mission Hills Of Hayward Golf Course'),
  ('United States', 'Mission Inn Resort Club El Campeon Course'),
  ('United States', 'Mission Inn Resort Club Las Colinas Course'),
  ('United States', 'Mission Lake Country Club'),
  ('United States', 'Mission Lakes Country Club'),
  ('United States', 'Mission Mountain Golf Club'),
  ('United States', 'Mission Royale Golf Club'),
  ('United States', 'Mission Trails Golf Course'),
  ('United States', 'Mission Valley Golf Country Club'),
  ('United States', 'Mission Viejo Country Club'),
  ('United States', 'Mississippi National Golf Links'),
  ('United States', 'Mississippi State University Golf Club'),
  ('United States', 'Missoula Country Club'),
  ('United States', 'Missouri Bluffs Golf Club'),
  ('United States', 'Mistwood Golf Course'),
  ('United States', 'Misty Creek Country Club'),
  ('United States', 'Mizner Country Club'),
  ('United States', 'Moab Golf Club'),
  ('United States', 'Moanalua Golf Club'),
  ('United States', 'Moccasin Bend Golf Club'),
  ('United States', 'Moccasin Run Golf Course'),
  ('United States', 'Moccasin Wallow Golf Club'),
  ('United States', 'Modesto Municipal Golf Course'),
  ('United States', 'Moffett Field Golf Club'),
  ('United States', 'Mohansic Golf Course'),
  ('United States', 'Mohawk Glen Golf Course'),
  ('United States', 'Mohawk Golf and Country Club'),
  ('United States', 'Mohawk River Country Club Chateau'),
  ('United States', 'Mohawk Valley Country Club'),
  ('United States', 'Mohegan Sun Golf Club'),
  ('United States', 'Mohican Hills Golf Club'),
  ('United States', 'Mohonk Mountain House Golf Course'),
  ('United States', 'Moila Country Club'),
  ('United States', 'Mojave Resort Golf Club'),
  ('United States', 'Monadnock Country Club'),
  ('United States', 'Monarch Bay Golf Club Marina Course'),
  ('United States', 'Monarch Bay Golf Club Tony Lema Course'),
  ('United States', 'Monarch Beach Golf Links'),
  ('United States', 'Monarch Country Club'),
  ('United States', 'Monarch Dunes Golf Club The Challenge Course'),
  ('United States', 'Monarch Dunes Golf Club The Old Course'),
  ('United States', 'Monarch Golf Club At Royal Highlands'),
  ('United States', 'Monarch Ridge Golf Course'),
  ('United States', 'Money Hill Golf Country Club'),
  ('United States', 'Monmouth Country Club'),
  ('United States', 'Monona Golf Course'),
  ('United States', 'Monongahela Valley Country Club'),
  ('United States', 'Monoosnock Country Club'),
  ('United States', 'Monroe Country Club'),
  ('United States', 'Monroe Golf & Country Club'),
  ('United States', 'Monroe Golf Club'),
  ('United States', 'Monroe Golf Country Club'),
  ('United States', 'Monroeton Golf Club'),
  ('United States', 'Monster Golf Club At Resorts World Catskills'),
  ('United States', 'Montague Golf Club'),
  ('United States', 'Montammy Golf Club'),
  ('United States', 'Montauk Downs State Park'),
  ('United States', 'Montaup Country Club'),
  ('United States', 'Montcalm Golf Club'),
  ('United States', 'Montclair Golf Club'),
  ('United States', 'Montclair Golf Course'),
  ('United States', 'Monte Vista Country Club'),
  ('United States', 'Monte Vista Golf Club'),
  ('United States', 'Montecito Country Club'),
  ('United States', 'Monterey Country Club'),
  ('United States', 'Monterey Park Golf Course'),
  ('United States', 'Monterey Pines Golf Club'),
  ('United States', 'Monterey Yacht Country Club'),
  ('United States', 'Montezuma Country Club'),
  ('United States', 'Monticello Country Club'),
  ('United States', 'Monticello Golf Club'),
  ('United States', 'Monticello Golf Club At Savannah Lakes'),
  ('United States', 'Montour Heights Country Club'),
  ('United States', 'Montpelier Elks Country Club'),
  ('United States', 'Montpelier Golf Course'),
  ('United States', 'Montreux Golf Country Club'),
  ('United States', 'Monument At Adobe Creek National Golf Course'),
  ('United States', 'Monument At Troon North Golf Club'),
  ('United States', 'Monument Express At Troon North Golf Club'),
  ('United States', 'Monument Shadows Golf Course'),
  ('United States', 'Moody Quiet Pines Golf Course'),
  ('United States', 'Moon Brook Country Club'),
  ('United States', 'Moon Golf Club'),
  ('United States', 'Moon Walk At Moon Valley Country Club'),
  ('United States', 'Moor Downs Golf Course'),
  ('United States', 'Moore Golf Club'),
  ('United States', 'Moores Mill Golf Club'),
  ('United States', 'Moorestown Field Club'),
  ('United States', 'Mooresville Golf Club'),
  ('United States', 'Moorings Country Club'),
  ('United States', 'Moorland Road Golf Center'),
  ('United States', 'Moorpark Country Club The Canyon Crest Golf Course'),
  ('United States', 'Moorpark Country Club The Creekside Golf Course'),
  ('United States', 'Moorpark Country Club The Ridgeline Golf Course'),
  ('United States', 'Moors Golf Club'),
  ('United States', 'Moose Ridge Golf Course'),
  ('United States', 'Moose River Golf Course'),
  ('United States', 'Moose Run Golf Course Creek Course'),
  ('United States', 'Moose Run Golf Course Hill Course'),
  ('United States', 'Moraga Country Club'),
  ('United States', 'Moraine Country Club'),
  ('United States', 'Morees Cheraw Country Club'),
  ('United States', 'Morefar Golf Course'),
  ('United States', 'Morehead City Country Club'),
  ('United States', 'Morehouse Country Club'),
  ('United States', 'Morgan Creek Golf And Country Club'),
  ('United States', 'Morgan Creek Golf Course'),
  ('United States', 'Morgan Dairy Golf Club'),
  ('United States', 'Morgan Hill Golf Course'),
  ('United States', 'Morgan Hills Golf Course'),
  ('United States', 'Morgan River At Dataw Island Golf Course'),
  ('United States', 'Morgan S Crossing'),
  ('United States', 'Moriah Country Club'),
  ('United States', 'Morning Star Golf Course'),
  ('United States', 'Morningstar Golf''s Club'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Champions Course'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Legends Course'),
  ('United States', 'Morrilton Country Club'),
  ('United States', 'Morris County Golf Club'),
  ('United States', 'Morris Park Country Club'),
  ('United States', 'Morrisburg Golf Club'),
  ('United States', 'Morrison Lake Golf Club'),
  ('United States', 'Morro Bay Golf Course'),
  ('United States', 'Moscow Elks Golf Club'),
  ('United States', 'Moselem Springs Golf Club'),
  ('United States', 'Moses Lake Golf Club'),
  ('United States', 'Mosholu Golf Course'),
  ('United States', 'Moss Ridge'),
  ('United States', 'Mossland Memorial Golf Course'),
  ('United States', 'Mosswood Country Club'),
  ('United States', 'Mossy Creek Golf Club'),
  ('United States', 'Mossy Oak Golf Club'),
  ('United States', 'Motorcoach Country Club'),
  ('United States', 'Mound City Golf Club'),
  ('United States', 'Mound Golf Course'),
  ('United States', 'Mound Grove Golf Recreation'),
  ('United States', 'Mound View Golf Course'),
  ('United States', 'Mounds Ditches At Brickyard Plantation Golf Club'),
  ('United States', 'Moundsville Country Club'),
  ('United States', 'Mount Airy Country Club'),
  ('United States', 'Mount Airy Golf Club'),
  ('United States', 'Mount Ayr Golf and Country Club'),
  ('United States', 'Mount Carmel Municipal Golf Course'),
  ('United States', 'Mount Cashmere Golf Course'),
  ('United States', 'Mount Dora Golf Club'),
  ('United States', 'Mount Douglas Golf Course'),
  ('United States', 'Mount Fairweather Golf Course'),
  ('United States', 'Mount Frontenac Golf Course'),
  ('United States', 'Mount Hawley Country Club'),
  ('United States', 'Mount Hood Golf Course'),
  ('United States', 'Mount Huff Golf Course'),
  ('United States', 'Mount Kisco Country Club'),
  ('United States', 'Mount Lebanon Golf Course'),
  ('United States', 'Mount Massive Golf Course'),
  ('United States', 'Mount Mitchell Golf Club'),
  ('United States', 'Mount Odin Golf Course'),
  ('United States', 'Mount Ogden Golf Course'),
  ('United States', 'Mount Pleasant At Mount Washington Hotel Resort'),
  ('United States', 'Mount Pleasant Country Club'),
  ('United States', 'Mount Pleasant Golf & Country Club'),
  ('United States', 'Mount Pocono Public Golf Course'),
  ('United States', 'Mount Prospect Golf Course'),
  ('United States', 'Mount Saint Helena Golf Course'),
  ('United States', 'Mount Shasta Resort'),
  ('United States', 'Mount Si Golf Course'),
  ('United States', 'Mount Snow Golf Club'),
  ('United States', 'Mount Summit Golf Course'),
  ('United States', 'Mount Tabor Country Club'),
  ('United States', 'Mount Vernon Country Club'),
  ('United States', 'Mount Vintage Golf Club Chester Course'),
  ('United States', 'Mount Vintage Golf Club Independent Course'),
  ('United States', 'Mount Vintage Golf Club Vintage Course'),
  ('United States', 'Mount Washington At Mount Washington Hotel Resort'),
  ('United States', 'Mountain Air Country Club'),
  ('United States', 'Mountain Aire Golf Club'),
  ('United States', 'Mountain At Angel Park Golf Club'),
  ('United States', 'Mountain At Cordillera Golf Course'),
  ('United States', 'Mountain At Incline Village Golf Resort'),
  ('United States', 'Mountain At Wasatch Mountain State Park'),
  ('United States', 'Mountain Brook Golf Club'),
  ('United States', 'Mountain Falls Golf Course'),
  ('United States', 'Mountain Flowers'),
  ('United States', 'Mountain Forest At Stratton Mountain Country Club'),
  ('United States', 'Mountain Glen Golf Course'),
  ('United States', 'Mountain Harbour Golf Club'),
  ('United States', 'Mountain Lake'),
  ('United States', 'Mountain Lake At Pinery Country Club'),
  ('United States', 'Mountain Lake Golf Course'),
  ('United States', 'Mountain Laurel Golf Club'),
  ('United States', 'Mountain Meadows Golf Course'),
  ('United States', 'Mountain Ranch Golf Club At Fairfield Bay'),
  ('United States', 'Mountain Ridge'),
  ('United States', 'Mountain Ridge Country Club'),
  ('United States', 'Mountain Shadows Golf Course'),
  ('United States', 'Mountain Springs At Grandfather Golf Country Club'),
  ('United States', 'Mountain Top Course'),
  ('United States', 'Mountain Top Golf Course'),
  ('United States', 'Mountain Valley Golf Center'),
  ('United States', 'Mountain Valley Golf Course Mountain Course'),
  ('United States', 'Mountain Valley Golf Course Valley Course'),
  ('United States', 'Mountain View At Callaway Gardens Resort'),
  ('United States', 'Mountain View At Desert Willow Golf Resort'),
  ('United States', 'Mountain View Country Club'),
  ('United States', 'Mountain View Golf Club'),
  ('United States', 'Mountain View Golf Course'),
  ('United States', 'Mountain View Grand Golf Course'),
  ('United States', 'Mountain Vista Golf Club San Gorgonio Course'),
  ('United States', 'Mountain Vista Golf Club Santa Rosa Course'),
  ('United States', 'Mountain Vista Greens Golf Course'),
  ('United States', 'Mountaineer Golf Country Club'),
  ('United States', 'Mountaineer Woodview Golf Course'),
  ('United States', 'Mountaineers Woodview Golf Course'),
  ('United States', 'Mountaintop Golf Lake Club'),
  ('United States', 'Mountainview Country Club'),
  ('United States', 'Mountainview Par 3 Gramling Course'),
  ('United States', 'Mozingo Lake Recreation Watson 9 Course'),
  ('United States', 'Mr Golfs Ultimate Range'),
  ('United States', 'Mr. Golf'),
  ('United States', 'Mt Adams Country Club'),
  ('United States', 'Mt Anthony Golf Tennis Club'),
  ('United States', 'Mt Freedom Golf'),
  ('United States', 'Mt Graham Golf Course'),
  ('United States', 'Mt Hope Golf Course'),
  ('United States', 'Mt Kineo Golf Course'),
  ('United States', 'Mt Meadows Golf Course'),
  ('United States', 'Mt Pleasant Golf Club'),
  ('United States', 'Mt Whitney Golf Club'),
  ('United States', 'Mt Woodson Golf Club'),
  ('United States', 'Mud Run Golf Course'),
  ('United States', 'Mueller''s Valley View Farm Golf Course'),
  ('United States', 'Muirfield Village Golf Club'),
  ('United States', 'Mulberry Hills Golf Course'),
  ('United States', 'Muleshoe Country Club'),
  ('United States', 'Mulholland Hills Country Club Canyons'),
  ('United States', 'Mulholland Hills Country Club Trails'),
  ('United States', 'Mulholland Hills Country Club Vista'),
  ('United States', 'Mullenhurst Golf Course'),
  ('United States', 'Mullett Lake Country Club'),
  ('United States', 'Mulligan S Pointe'),
  ('United States', 'Mulligan''s Fairway'),
  ('United States', 'Mulligans Creekside Golf Center'),
  ('United States', 'Mulligans Island Par 3 Course'),
  ('United States', 'Muncie Elks Country Club'),
  ('United States', 'Munoscong Golf Club'),
  ('United States', 'Muroc Lake Golf Course'),
  ('United States', 'Murphy Creek Golf Course'),
  ('United States', 'Murphys Garrison Golf Center'),
  ('United States', 'Murray Parkway Golf Course'),
  ('United States', 'Murrysville Golf Club'),
  ('United States', 'Muscatine Municipal Golf Course'),
  ('United States', 'Musgrove Mill Golf Club'),
  ('United States', 'Muskeg Meadows Golf Course'),
  ('United States', 'Muskego Lakes Country Club'),
  ('United States', 'Muskegon Country Club'),
  ('United States', 'Muskogee Country Club'),
  ('United States', 'Muttontown Golf Country Club'),
  ('United States', 'Myerlee Country Club'),
  ('United States', 'Myers Park Country Club'),
  ('United States', 'Mylora Golf Course'),
  ('United States', 'Mylora On No 5 Road'),
  ('United States', 'Myopia Hunt Club'),
  ('United States', 'Myrick Hills Country Club'),
  ('United States', 'Myrtle Beach National Golf Club Kings North Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Myrtle Beach National Golf Club South Creek Course'),
  ('United States', 'Myrtle Beach National Golf Club West Course'),
  ('United States', 'Mystery Valley Golf Club'),
  ('United States', 'Mystic Creek Golf Club'),
  ('United States', 'Mystic Dunes Golf Club'),
  ('United States', 'Mystic Oak Golf Course'),
  ('United States', 'NCR Country Club'),
  ('United States', 'Nabnasset Lake Country Club'),
  ('United States', 'Naga-Waukee War Memorial Golf Course'),
  ('United States', 'Nags Head Golf Links'),
  ('United States', 'Nahma Golf Course'),
  ('United States', 'Nakoma Country Club'),
  ('United States', 'Nakoma Golf Resort Dragon Course'),
  ('United States', 'Nancy Lopez Golf Course At Spring River'),
  ('United States', 'Nanea Golf Club'),
  ('United States', 'Naniloa Golf Club'),
  ('United States', 'Nansemond River Golf Club'),
  ('United States', 'Nantucket Golf Club'),
  ('United States', 'Napa Golf Course At Kennedy Park'),
  ('United States', 'Napa Valley Country Club'),
  ('United States', 'Naperbrook Golf Course'),
  ('United States', 'Naperville Country Club'),
  ('United States', 'Naples Beach Hotel Golf Club'),
  ('United States', 'Naples Golf Country Club'),
  ('United States', 'Naples Grande Golf Club'),
  ('United States', 'Naples Heritage'),
  ('United States', 'Naples Lakes Country Club'),
  ('United States', 'Naples National Golf Club'),
  ('United States', 'Napoleon Municipal Golf Course'),
  ('United States', 'Nas Jacksonville Golf Club Blue Nine'),
  ('United States', 'Nas Jacksonville Golf Club Red Nine'),
  ('United States', 'Nas Jacksonville Golf Club White Nine'),
  ('United States', 'Nashawtuc Country Club'),
  ('United States', 'Nashua Country Club'),
  ('United States', 'Nashville Country Club'),
  ('United States', 'Nashville Golf Course'),
  ('United States', 'Nassau Country Club'),
  ('United States', 'Natanis Golf Course Arrowhead'),
  ('United States', 'Natanis Golf Course Tomahawk'),
  ('United States', 'Natchez Trace Golf Club'),
  ('United States', 'Natchitoches Country Club'),
  ('United States', 'National City Golf Course'),
  ('United States', 'National Golf Club'),
  ('United States', 'National Golf Club Of Kansas City'),
  ('United States', 'National Golf Links'),
  ('United States', 'National Golf Links Of America'),
  ('United States', 'Nationview Golf Course'),
  ('United States', 'Native Oaks Golf Club'),
  ('United States', 'Nature Walk Course At Chinquapin'),
  ('United States', 'Nature Walk Golf Club'),
  ('United States', 'Naval Air Station Barbers Point Golf Course'),
  ('United States', 'Naval Base San Diegos Golf Performance Center'),
  ('United States', 'Navesink Country Club'),
  ('United States', 'Navy Marine Golf Course'),
  ('United States', 'Needham Golf Club'),
  ('United States', 'Needles Eye Golf Club'),
  ('United States', 'Nehoiden Golf Club At Wellesley College'),
  ('United States', 'Neillsville Country Club'),
  ('United States', 'Nemacolin Country Club'),
  ('United States', 'Nemacolin Woodlands Resort Mystic Rock Course'),
  ('United States', 'Nemacolin Woodlands Resort Shepherds Rock Golf Course'),
  ('United States', 'Nemadji Golf Course'),
  ('United States', 'Neosho Municipal Golf Course Lakes Nine'),
  ('United States', 'Neosho Municipal Golf Course Oaks Nine'),
  ('United States', 'Neosho Municipal Golf Course Valley Nine'),
  ('United States', 'Neshaminy Valley Golf Club'),
  ('United States', 'Neshanic Valley Golf Course Academy Course'),
  ('United States', 'Neshanic Valley Golf Course Lake Ridge Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Lake Course'),
  ('United States', 'Neshanic Valley Golf Course Meadow Ridge Course'),
  ('United States', 'Neshobe Golf Club'),
  ('United States', 'Ness County Country Club'),
  ('United States', 'Nettle Creek Country Club'),
  ('United States', 'Neumann Golf Course'),
  ('United States', 'Nevada Country Club'),
  ('United States', 'Nevada County Country Club'),
  ('United States', 'Nevel Meade Golf Course'),
  ('United States', 'New Albany Country Club'),
  ('United States', 'New Albany Golf Course'),
  ('United States', 'New Albany Links Golf Club'),
  ('United States', 'New Berlin Hills Golf Course'),
  ('United States', 'New Bern Golf Country Club'),
  ('United States', 'New Ellenton Golf Course'),
  ('United States', 'New England Golf Club'),
  ('United States', 'New Haven Country Club'),
  ('United States', 'New Haven Golf Club'),
  ('United States', 'New Holland Pitch Putt'),
  ('United States', 'New Hope Village Golf Course'),
  ('United States', 'New Horizons Golf Course'),
  ('United States', 'New Jersey National Golf Club'),
  ('United States', 'New Kirk Country Club'),
  ('United States', 'New Meadows Golf Club'),
  ('United States', 'New Mexico Military Institute Golf Course'),
  ('United States', 'New Mexico State University Golf Course'),
  ('United States', 'New Mexico Tech Golf Course'),
  ('United States', 'New Orleans Country Club'),
  ('United States', 'New Paltz Golf Course'),
  ('United States', 'New Richmond Golf Club'),
  ('United States', 'New Richmond Links Course'),
  ('United States', 'New River Country Club'),
  ('United States', 'New Rockford Golf Club'),
  ('United States', 'New Salisbury Golf Course'),
  ('United States', 'New Smyrna Golf Club'),
  ('United States', 'New Ulm Country Club'),
  ('United States', 'New York Chiropractic College Executive Links Course'),
  ('United States', 'New York Country Club'),
  ('United States', 'New York Presbyterian Hospital Golf Course'),
  ('United States', 'Newark Country Club'),
  ('United States', 'Newark Valley Golf Club'),
  ('United States', 'Newberry Country Club'),
  ('United States', 'Newcastle Country Club'),
  ('United States', 'Newell Golf Course'),
  ('United States', 'Newfane Pro Am Par 3 Golf Course'),
  ('United States', 'Newfoundland Golf Course'),
  ('United States', 'Newlands Golf And Country Club'),
  ('United States', 'Newman Golf Course'),
  ('United States', 'Newman Municipal Golf Course'),
  ('United States', 'Newnan Country Club'),
  ('United States', 'Newport American Legion Country Club'),
  ('United States', 'Newport Beach Country Club'),
  ('United States', 'Newport Beach Golf Course'),
  ('United States', 'Newport Country Club'),
  ('United States', 'Newport Golf Club'),
  ('United States', 'Newport National Golf Club Orchard Course'),
  ('United States', 'Newton Commonwealth Golf Course'),
  ('United States', 'Newton Country Club'),
  ('United States', 'Newton Public Golf Course Driving Range'),
  ('United States', 'Newtown Country Club'),
  ('United States', 'Niagara County Golf Course'),
  ('United States', 'Niagara Falls Country Club'),
  ('United States', 'Niagara Frontier Country Club'),
  ('United States', 'Niagara National Golf Country Club'),
  ('United States', 'Niagara On The Lake Golf Club'),
  ('United States', 'Niagara Orleans Country Club'),
  ('United States', 'Nibley Park Golf Course'),
  ('United States', 'Nick Stoner Golf Course'),
  ('United States', 'Nickerson Dunes Pitch Putt'),
  ('United States', 'Nicklaus At Colleton River Club'),
  ('United States', 'Nicklaus Golf Club At Lionsgate'),
  ('United States', 'Nickol Knoll Golf Course'),
  ('United States', 'Nico Wynd Golf Club'),
  ('United States', 'Nicolet Country Club'),
  ('United States', 'Nile Shrine Golf Course'),
  ('United States', 'Nine At Eagle Crest Golf Course'),
  ('United States', 'Nine Hole At Balboa Park Municipal Golf Club'),
  ('United States', 'Nine Hole At Bangor Municipal Golf Course'),
  ('United States', 'Nine Hole At Bright Leaf Golf Resort'),
  ('United States', 'Nine Hole At On Top Of The World Golf Club'),
  ('United States', 'Nine Hole At Outdoor Resort Country Club'),
  ('United States', 'Nine Hole At Race Brook Country Club'),
  ('United States', 'Nine Hole At Santa Teresa Golf Club'),
  ('United States', 'Nine Hole At South Park Golf Course'),
  ('United States', 'Nine Hole At South Suburban Golf Course'),
  ('United States', 'Nine Hole At Village Links Of Glen Ellyn'),
  ('United States', 'Nine Hole Executive At Viewpoint Golf Resort'),
  ('United States', 'Nine Hole Par 3 At Smithtown Landing Golf Club'),
  ('United States', 'Nine Hole Regulation At Highland View Golf Club'),
  ('United States', 'Nine Springs Golf Course'),
  ('United States', 'Nippersink Resort'),
  ('United States', 'Nippo Lake Golf Club'),
  ('United States', 'Nishna Hills Golf Club'),
  ('United States', 'Nishna Valley Golf Course'),
  ('United States', 'Nissequogue Golf Course'),
  ('United States', 'Nittany Country Club'),
  ('United States', 'Nkmip Canyon Desert Golf Course'),
  ('United States', 'No 7 At Desert Mountain Golf Club'),
  ('United States', 'Nob North Golf Course'),
  ('United States', 'Nocona Hills Country Club'),
  ('United States', 'Nolichucky View Golf Club'),
  ('United States', 'Nonami Plantation Golf Course'),
  ('United States', 'Nonesuch River Golf Club'),
  ('United States', 'Nonquitt Golf Club'),
  ('United States', 'Norfolk Country Club'),
  ('United States', 'Norfolk Golf Club'),
  ('United States', 'Norman K. Probstein Golf Course'),
  ('United States', 'Normandie Golf Club'),
  ('United States', 'Normandy Shores Golf Course'),
  ('United States', 'Normanside Country Club'),
  ('United States', 'Norsk Golf Club'),
  ('United States', 'North Adams Country Club'),
  ('United States', 'North Andover Country Club'),
  ('United States', 'North At Admiral Baker Golf Course'),
  ('United States', 'North At Alondra Park Golf Course'),
  ('United States', 'North At Antelope Hills Golf Course'),
  ('United States', 'North At Bay Palms Golf Complex'),
  ('United States', 'North At Boulders Golf Club Resort'),
  ('United States', 'North At Bretwood Golf Course'),
  ('United States', 'North At Canoe Brook Country Club'),
  ('United States', 'North At Carmel Country Club'),
  ('United States', 'North At Cherokee Town Country Club'),
  ('United States', 'North At Cherokee Village'),
  ('United States', 'North At Coto De Caza Golf Racquet Club'),
  ('United States', 'North At Country Club Of Scranton The'),
  ('United States', 'North At Crestview Country Club'),
  ('United States', 'North At Daytona Beach Golf Country Club'),
  ('United States', 'North At Deerfield Country Club'),
  ('United States', 'North At Earlywine Golf Course'),
  ('United States', 'North At Fountains Country Club'),
  ('United States', 'North At Frenchmans Creek Beach Country Club'),
  ('United States', 'North At Heather Hill Country Club'),
  ('United States', 'North At Hunters Run Golf Course'),
  ('United States', 'North At Hyde Park Golf Course'),
  ('United States', 'North At Ironwood Country Club'),
  ('United States', 'North At Johns Island Club'),
  ('United States', 'North At Lake Hefner Golf Course'),
  ('United States', 'North At Lake Henry Golf Club'),
  ('United States', 'North At Los Angeles Country Club The'),
  ('United States', 'North At Los Serranos Golf Country Club'),
  ('United States', 'North At Moss Creek Golf Club'),
  ('United States', 'North At Quail Ridge Country Club'),
  ('United States', 'North At Raintree Country Club'),
  ('United States', 'North At Rancho Murieta Country Club'),
  ('United States', 'North At Randolph Golf Course'),
  ('United States', 'North At Torrey Pines Municipal Golf Course'),
  ('United States', 'North At Victor Hills Golf Club'),
  ('United States', 'North At Vineyards Of Naples The'),
  ('United States', 'North At Wilmington Country Club'),
  ('United States', 'North Bellingham Golf Course'),
  ('United States', 'North Bend Golf Course'),
  ('United States', 'North Branch Golf Course'),
  ('United States', 'North Carolina State University Club'),
  ('United States', 'North Conway Country Club'),
  ('United States', 'North Country Golf Club'),
  ('United States', 'North County Country Club'),
  ('United States', 'North Course'),
  ('United States', 'North Course At Highlands Ridge'),
  ('United States', 'North Course At Lake Of Isles'),
  ('United States', 'North Course At Shadow Wood Country Club'),
  ('United States', 'North Course At Terry Hills Golf Course'),
  ('United States', 'North Course At Whitefish Lake Golf Club'),
  ('United States', 'North Course Golf Course At Stonewall Links'),
  ('United States', 'North Creek Golf Club'),
  ('United States', 'North East At Athens Country Club'),
  ('United States', 'North East At Farmington Country Club'),
  ('United States', 'North East At Lakes Country Club The'),
  ('United States', 'North East At Oaks North Golf Course'),
  ('United States', 'North East At Ocean Breeze Golf Country Club'),
  ('United States', 'North East At Sahalee Country Club'),
  ('United States', 'North East At Silver Lakes Country Club'),
  ('United States', 'North Eighteen At Cross Creek Resort'),
  ('United States', 'North Fork Country Club'),
  ('United States', 'North Fork Golf Tennis Club'),
  ('United States', 'North Golf Course At Big Cypress Golf Country Club'),
  ('United States', 'North Golf Course At Granite Falls Golf Club'),
  ('United States', 'North Golf Course At Sun City'),
  ('United States', 'North Greens Golf Course'),
  ('United States', 'North Haven Golf Club'),
  ('United States', 'North Hempstead Country Club'),
  ('United States', 'North Hill Country Club'),
  ('United States', 'North Hills Country Club'),
  ('United States', 'North Hills Municipal Golf Course'),
  ('United States', 'North Jersey Country Club'),
  ('United States', 'North Kent Golf Course'),
  ('United States', 'North Kingstown Municipal Golf Club'),
  ('United States', 'North Kossuth Golf Club'),
  ('United States', 'North Las Vegas Golf Course'),
  ('United States', 'North Links Golf Course'),
  ('United States', 'North Oaks Golf Course'),
  ('United States', 'North Olmsted Golf Club'),
  ('United States', 'North Palm Beach Country Club'),
  ('United States', 'North Park Dr Range Par 3'),
  ('United States', 'North Park Golf Course'),
  ('United States', 'North Ridge Country Club'),
  ('United States', 'North Ridge Golf Club'),
  ('United States', 'North Shore Country Club'),
  ('United States', 'North Shore Golf Club'),
  ('United States', 'North Shore Golf Course'),
  ('United States', 'North South At Elmridge Golf Club'),
  ('United States', 'North South At Killearn Country Club Inn'),
  ('United States', 'North South At Krendale Golf Course'),
  ('United States', 'North South At Mountain Gate Country Club'),
  ('United States', 'North South At Rolling Acres Golf Course'),
  ('United States', 'North South At Silver Lakes Country Club'),
  ('United States', 'North South At South Hills Golf Club'),
  ('United States', 'North Star Golf Course'),
  ('United States', 'North Stone Club'),
  ('United States', 'North Topeka Golf Center'),
  ('United States', 'North West At Fernandina Beach Golf Club'),
  ('United States', 'North West At South Hills Golf Club'),
  ('United States', 'North Woodmere Golf Course'),
  ('United States', 'Northampton Country Club'),
  ('United States', 'Northampton Valley Country Club'),
  ('United States', 'Northbrook Country Club'),
  ('United States', 'Northdale Golf Club'),
  ('United States', 'Northeast Harbor Golf Club'),
  ('United States', 'Northern Bay Resort'),
  ('United States', 'Northern FonDuLac Archery Golf'),
  ('United States', 'Northern Hills Golf Course'),
  ('United States', 'Northern Links Golf Course'),
  ('United States', 'Northern Michigan University Golf Course'),
  ('United States', 'Northern Pines Golf Club'),
  ('United States', 'Northfield Country Club'),
  ('United States', 'Northfield Golf Club'),
  ('United States', 'Northfields'),
  ('United States', 'Northgreen Country Club'),
  ('United States', 'Northland Country Club'),
  ('United States', 'Northmoor Country Club'),
  ('United States', 'Northmoor Golf Course'),
  ('United States', 'Northport Creek'),
  ('United States', 'Northport Golf Club'),
  ('United States', 'Northport Golf Course'),
  ('United States', 'Northport Point Golf Club'),
  ('United States', 'Northridge Country Club'),
  ('United States', 'Northridge Hills'),
  ('United States', 'Northside Golf Club'),
  ('United States', 'Northstar California Golf Course'),
  ('United States', 'Northville Hills Golf Club'),
  ('United States', 'Northwest Angle Golf Course'),
  ('United States', 'Northwestern Hills Golf Course'),
  ('United States', 'Northwinds Golf Course'),
  ('United States', 'Northwood Country Club'),
  ('United States', 'Northwood Family Traditions'),
  ('United States', 'Northwood Golf Club'),
  ('United States', 'Northwood Golf Course'),
  ('United States', 'Northwood Hills Golf Course'),
  ('United States', 'Northwoods Golf Course'),
  ('United States', 'Norton Country Club'),
  ('United States', 'Norton Knolls Golf Course'),
  ('United States', 'Norvelt Golf Club Lukes Links Course'),
  ('United States', 'Norvelt Golf Club Norvelt Course'),
  ('United States', 'Norway Country Club'),
  ('United States', 'Norwich Golf Club'),
  ('United States', 'Norwood Acres'),
  ('United States', 'Norwood Country Club'),
  ('United States', 'Norwood Golf Club'),
  ('United States', 'Norwood Hills Country Club'),
  ('United States', 'Norwoods Golf Club'),
  ('United States', 'Nottoway River Country Club'),
  ('United States', 'Nowata Country Club'),
  ('United States', 'Noyac Golf Club'),
  ('United States', 'Noyes Park Golf Course'),
  ('United States', 'NuMark Golf Course'),
  ('United States', 'Nutters Chapel Golf Country Club'),
  ('United States', 'Nutters Crossing Golf Course'),
  ('United States', 'Oahu Country Club'),
  ('United States', 'Oak At Beau Chene Golf Racquet Club'),
  ('United States', 'Oak Bluff At Del Rio Country Club'),
  ('United States', 'Oak Brook Golf'),
  ('United States', 'Oak Brook Golf Club'),
  ('United States', 'Oak Brook Golf Course'),
  ('United States', 'Oak Country Club'),
  ('United States', 'Oak Creek Golf Club'),
  ('United States', 'Oak Creek Golf Course'),
  ('United States', 'Oak Crest Golf Course'),
  ('United States', 'Oak Glen Golf Course'),
  ('United States', 'Oak Grove Golf Club'),
  ('United States', 'Oak Grove Golf Course'),
  ('United States', 'Oak Hall Par 3'),
  ('United States', 'Oak Harbor Country Club'),
  ('United States', 'Oak Harbor Golf Club'),
  ('United States', 'Oak Harbor Golf Course'),
  ('United States', 'Oak Hill Country Club'),
  ('United States', 'Oak Hill Golf Club'),
  ('United States', 'Oak Hill Golf Course'),
  ('United States', 'Oak Hills Country Club'),
  ('United States', 'Oak Hills Golf Club'),
  ('United States', 'Oak Hills Golf Country Club'),
  ('United States', 'Oak Hills Golf Course'),
  ('United States', 'Oak Hills Golf Event Center'),
  ('United States', 'Oak Hills Park Golf Course'),
  ('United States', 'Oak Hollow Golf Course'),
  ('United States', 'Oak Island Golf Club'),
  ('United States', 'Oak Knoll Country Club'),
  ('United States', 'Oak Knoll Golf Course'),
  ('United States', 'Oak Knolls Golf Course'),
  ('United States', 'Oak Lake Golf Course'),
  ('United States', 'Oak Lane Golf Club'),
  ('United States', 'Oak Lawn Country Club'),
  ('United States', 'Oak Leaf Golf Course'),
  ('United States', 'Oak Maple At Hunters Creek Plantation'),
  ('United States', 'Oak Marsh Golf Course'),
  ('United States', 'Oak Meadow Country Club'),
  ('United States', 'Oak Mountain Championship Golf Course'),
  ('United States', 'Oak Park Country Club'),
  ('United States', 'Oak Park Golf & Recreation'),
  ('United States', 'Oak Point At Kiawah Island Golf Resort'),
  ('United States', 'Oak Pointe Country Club'),
  ('United States', 'Oak Quarry Golf Club'),
  ('United States', 'Oak Ridge Golf Club'),
  ('United States', 'Oak Ridge Golf Course'),
  ('United States', 'Oak Run Golf Club'),
  ('United States', 'Oak Shadows Golf Club'),
  ('United States', 'Oak Springs Golf Club'),
  ('United States', 'Oak Stonehouse At Temecula Creek Inn Golf Resort'),
  ('United States', 'Oak Summit Golf Course'),
  ('United States', 'Oak Tree Country Club'),
  ('United States', 'Oak Tree Golf Club'),
  ('United States', 'Oak Tree National Golf Club'),
  ('United States', 'Oak Tree Spruce At Middle Island Country Club'),
  ('United States', 'Oak Valley Golf Club'),
  ('United States', 'Oakbourne Country Club'),
  ('United States', 'Oakbrook Golf Club'),
  ('United States', 'Oakbrook Golf Course'),
  ('United States', 'Oakcreek Country Club'),
  ('United States', 'Oakdale Country Club'),
  ('United States', 'Oakdale Golf Country Club'),
  ('United States', 'Oakdale Golf Course'),
  ('United States', 'Oakgreen Golf Course & Driving Range'),
  ('United States', 'Oakhaven Golf Club'),
  ('United States', 'Oakhurst Country Club')
on conflict (country, name) do nothing;
