insert into public.golf_courses (country, name) values
  ('United States', 'Oakhurst Golf & Country Club'),
  ('United States', 'Oakland Acres Golf Club'),
  ('United States', 'Oakland Beach Golf Club'),
  ('United States', 'Oakland Country Club'),
  ('United States', 'Oakland Golf Club'),
  ('United States', 'Oakland Hills Country Club'),
  ('United States', 'Oakland Plantation Country Club'),
  ('United States', 'Oakland Plantation Golf Course At Lsu'),
  ('United States', 'Oakland University Golf and Learning Center'),
  ('United States', 'Oakleaf Golf and Country Club'),
  ('United States', 'Oakleigh At The Villages Executive Golf Trail'),
  ('United States', 'Oakley Country Club'),
  ('United States', 'Oakmont Country Club'),
  ('United States', 'Oakmont East Golf Course'),
  ('United States', 'Oakmont Golf Center'),
  ('United States', 'Oakmont Green Golf Club'),
  ('United States', 'Oakmoore Golf Course'),
  ('United States', 'Oakridge Country Club'),
  ('United States', 'Oakridge Golf Course'),
  ('United States', 'Oaks At Ft Walton Beach Golf Club'),
  ('United States', 'Oaks At North Ridge Country Club'),
  ('United States', 'Oaks At Palm Aire Country Club'),
  ('United States', 'Oaks Canyon At Blacklake Golf Course'),
  ('United States', 'Oaks Country Club'),
  ('United States', 'Oaks Course At Stonegate Golf Club'),
  ('United States', 'Oaks Golf Club The'),
  ('United States', 'Oaks Golf Country Club'),
  ('United States', 'Oaks Golf Course'),
  ('United States', 'Oaks Lakes At North Ranch Country Club'),
  ('United States', 'Oaks Lakes At Valley Oaks Golf Club'),
  ('United States', 'Oaks National Golf Club'),
  ('United States', 'Oaks Palms At Hacienda Hills Golf Country Club'),
  ('United States', 'Oaksridge Golf Course'),
  ('United States', 'Oakton Driving Range'),
  ('United States', 'Oaktree Golf Club'),
  ('United States', 'Oaktree Golf Course'),
  ('United States', 'Oakview Golf Country Club'),
  ('United States', 'Oakview Lakes Golf Course'),
  ('United States', 'Oakview Links'),
  ('United States', 'Oakwing Golf Club'),
  ('United States', 'Oakwood Country Club'),
  ('United States', 'Oakwood Country Club Par 3 Course'),
  ('United States', 'Oakwood Golf Club'),
  ('United States', 'Oakwood Golf Course'),
  ('United States', 'Oakwood Park Golf Course'),
  ('United States', 'Oakwood Supper Club & Golf Course'),
  ('United States', 'Oakwoods Country Club'),
  ('United States', 'Oasis Country Club'),
  ('United States', 'Oasis Golf Club'),
  ('United States', 'Oasis Rv Park Golf Course'),
  ('United States', 'Oberlin Country Club'),
  ('United States', 'Oberlin Golf Club'),
  ('United States', 'Ocala Golf Club'),
  ('United States', 'Ocala National Golf Club'),
  ('United States', 'Ocala Palms Golf Club'),
  ('United States', 'Occano'),
  ('United States', 'Occoneechee Golf Club'),
  ('United States', 'Ocean Acres Country Club'),
  ('United States', 'Ocean At Ponte Vedra Inn Club'),
  ('United States', 'Ocean City Golf Club Newport Bay'),
  ('United States', 'Ocean City Golf Club Seaside'),
  ('United States', 'Ocean City Golf Course'),
  ('United States', 'Ocean Club At The Hutchinson Island Beach Resort And Marina'),
  ('United States', 'Ocean County Golf Course At Atlantis'),
  ('United States', 'Ocean County Golf Course At Forge Pond'),
  ('United States', 'Ocean Creek At Fripp Island Resort'),
  ('United States', 'Ocean Edge Resort Club On Cape Cod'),
  ('United States', 'Ocean Forest Golf Club'),
  ('United States', 'Ocean Hills Country Club'),
  ('United States', 'Ocean Palm Golf Course'),
  ('United States', 'Ocean Pines Golf Club'),
  ('United States', 'Ocean Point At Fripp Island Resort'),
  ('United States', 'Ocean Resorts Golf Club'),
  ('United States', 'Ocean Shores Golf Course'),
  ('United States', 'Ocean View Municipal Golf Course'),
  ('United States', 'Ocean Village Golf Course'),
  ('United States', 'Ocean Winds At Seabrook Island Resort'),
  ('United States', 'Oceana Golf Club'),
  ('United States', 'Oceans Golf Club'),
  ('United States', 'Oceanside Golf Country Club'),
  ('United States', 'Oceanside Golf Course'),
  ('United States', 'Ocilla Country Club'),
  ('United States', 'Oconee Country Club'),
  ('United States', 'Oconomowoc Golf Club'),
  ('United States', 'Ocotillo Golf Club Blue White'),
  ('United States', 'Ocotillo Golf Club Gold Blue'),
  ('United States', 'Ocotillo Golf Club White Gold'),
  ('United States', 'Odana Hills Golf Course'),
  ('United States', 'Odessa Golf Club Rv Park'),
  ('United States', 'Odessa National Golf Club'),
  ('United States', 'Odonnell Golf Club'),
  ('United States', 'Odyssey Country Club'),
  ('United States', 'Ogden Golf Country Club'),
  ('United States', 'Ogeechee Valley Country Club'),
  ('United States', 'Oglebay Resort Crispin Course'),
  ('United States', 'Oglebay Resort Crispin Golf Course'),
  ('United States', 'Oglebay Resort Par 3 Course'),
  ('United States', 'Oglebay Resort Speidel Golf Club Par 3 Course'),
  ('United States', 'Ohio Prestwick Country Club'),
  ('United States', 'Ohio State University Golf Course'),
  ('United States', 'Ohio University Driving Range'),
  ('United States', 'Ohio University Golf Course'),
  ('United States', 'Ohoopee Match Club'),
  ('United States', 'Oil Field Recreation Association Golf Course'),
  ('United States', 'Ojai Valley Inn'),
  ('United States', 'Ojibwa Golf & Bowl'),
  ('United States', 'Ojibwa Golf Bowl'),
  ('United States', 'Okanogan Valley Golf Club'),
  ('United States', 'Okatie Creek Golf Club'),
  ('United States', 'Okatoma Golf Club'),
  ('United States', 'Okeechobee At The Villages Executive Golf Trail'),
  ('United States', 'Okeene Golf Club'),
  ('United States', 'Okefenokee Country Club'),
  ('United States', 'Okemah Golf Course'),
  ('United States', 'Oklahoma City Golf Country Club'),
  ('United States', 'Okmulgee Country Club'),
  ('United States', 'Okoboji View Golf Course'),
  ('United States', 'Okolona Country Club'),
  ('United States', 'Old At Canongate On White Oak'),
  ('United States', 'Old At Country Club Of Scranton The'),
  ('United States', 'Old At Saucon Valley Country Club'),
  ('United States', 'Old At Saxon Golf Course'),
  ('United States', 'Old Avalon Golf Course'),
  ('United States', 'Old Baldy Club'),
  ('United States', 'Old Baldy Golf Course'),
  ('United States', 'Old Barnwell Old Barnwell Golf Course'),
  ('United States', 'Old Bridge Golf Club'),
  ('United States', 'Old Brockway Golf Course'),
  ('United States', 'Old Capital Golf Club'),
  ('United States', 'Old Channel Trail'),
  ('United States', 'Old Chatham Golf Club'),
  ('United States', 'Old Club Par 3 Course'),
  ('United States', 'Old Corkscrew Golf Club'),
  ('United States', 'Old Course Golf Course At Stonewall Links'),
  ('United States', 'Old Course Sauk Centre'),
  ('United States', 'Old Dane Golf Club'),
  ('United States', 'Old Edwards Club'),
  ('United States', 'Old Elm Club'),
  ('United States', 'Old Erie Golf Club'),
  ('United States', 'Old Field Short Course'),
  ('United States', 'Old Greenwood Golf Course'),
  ('United States', 'Old Hickory At Fort Jackson Golf Club'),
  ('United States', 'Old Hickory Golf Club'),
  ('United States', 'Old Landing Golf Course'),
  ('United States', 'Old Lyme Country Club'),
  ('United States', 'Old Marsh Country Club'),
  ('United States', 'Old Marsh Golf Club'),
  ('United States', 'Old Memorial Golf Club'),
  ('United States', 'Old Mill Golf Club'),
  ('United States', 'Old Mill Graveyard At Flat Creek Golf Club'),
  ('United States', 'Old North State Club At Uwharrie Point'),
  ('United States', 'Old Oak Country Club'),
  ('United States', 'Old Oakland Golf Club'),
  ('United States', 'Old Oaks Golf Course'),
  ('United States', 'Old Orange At Verandah'),
  ('United States', 'Old Orchard Country Club'),
  ('United States', 'Old Orchard GC'),
  ('United States', 'Old Palm Golf Club'),
  ('United States', 'Old Ranch Country Club'),
  ('United States', 'Old River Golf Course'),
  ('United States', 'Old Sandwich Golf Club'),
  ('United States', 'Old South Golf Links'),
  ('United States', 'Old Tabby Links'),
  ('United States', 'Old Tappan Golf Course'),
  ('United States', 'Old Toccoa Farm'),
  ('United States', 'Old Top Farm'),
  ('United States', 'Old Town Club'),
  ('United States', 'Old Town Golf Course'),
  ('United States', 'Old Trail Golf Club'),
  ('United States', 'Old Union Golf Course'),
  ('United States', 'Old Warson Country Club'),
  ('United States', 'Old Waverly Golf Club'),
  ('United States', 'Old Wayne Golf Course'),
  ('United States', 'Old Works'),
  ('United States', 'Old Works Little Bear'),
  ('United States', 'Old York Country Club'),
  ('United States', 'Old York Road Country Club'),
  ('United States', 'Olde Atlanta Golf Club'),
  ('United States', 'Olde Barnstable Fairgrounds Golf Club'),
  ('United States', 'Olde Beau Resort Golf Club'),
  ('United States', 'Olde Beaufort Golf Club'),
  ('United States', 'Olde Course At Loveland'),
  ('United States', 'Olde Dutch Mill Golf Course'),
  ('United States', 'Olde Eight'),
  ('United States', 'Olde English Trail Golf Club'),
  ('United States', 'Olde Florida Golf Club'),
  ('United States', 'Olde Fort Golf Course'),
  ('United States', 'Olde Hickory Golf Country Club'),
  ('United States', 'Olde Homeplace Golf Club'),
  ('United States', 'Olde Homestead Golf Club'),
  ('United States', 'Olde Kinderhook Golf Course'),
  ('United States', 'Olde Liberty Golf Country Club'),
  ('United States', 'Olde Mill Golf Club'),
  ('United States', 'Olde Mill Resort'),
  ('United States', 'Olde Oak Golf Club'),
  ('United States', 'Olde Oaks Golf Club Cypress Meadow'),
  ('United States', 'Olde Oaks Golf Club Cypress Oak'),
  ('United States', 'Olde Oaks Golf Club Meadow Oak'),
  ('United States', 'Olde Page At Page Belcher Golf Course'),
  ('United States', 'Olde Point Golf Country Club'),
  ('United States', 'Olde Salem Greens Golf Course'),
  ('United States', 'Olde Scotland Links At Bridgewater'),
  ('United States', 'Olde Stonewall Golf Club'),
  ('United States', 'Olde Sycamore Golf Club'),
  ('United States', 'Oldfield Club'),
  ('United States', 'Oldham County Country Club'),
  ('United States', 'Ole Miss Golf Course'),
  ('United States', 'Ole Monterey Golf Club'),
  ('United States', 'Olivas Links Golf Course'),
  ('United States', 'Olive Branch Country Club'),
  ('United States', 'Olive Glenn Golf Country Club'),
  ('United States', 'Olivet Country Club'),
  ('United States', 'Olomana Golf Links'),
  ('United States', 'Olympia Country Golf Club'),
  ('United States', 'Olympia Fields Country Club'),
  ('United States', 'Olympic Hills Golf Club'),
  ('United States', 'Olympic View Golf Club'),
  ('United States', 'Omaha Country Club'),
  ('United States', 'Omni Amelia Island Resort Spa Little Sandy Short Course'),
  ('United States', 'Omni Amelia Island Resort Spa Oak Marsh'),
  ('United States', 'Omni Bedford Springs Resort Old Course'),
  ('United States', 'Omni La Costa Resort Spa North Course'),
  ('United States', 'Omni La Costa Resort Spa South Course'),
  ('United States', 'Omni Rancho Las Palmas Resort North South'),
  ('United States', 'Omni Rancho Las Palmas Resort South West'),
  ('United States', 'Omni Rancho Las Palmas Resort West North'),
  ('United States', 'One East Course At Apple Greens Golf Course'),
  ('United States', 'One Two Course At Apple Greens Golf Course'),
  ('United States', 'Oneida Community Golf Club'),
  ('United States', 'Oneida Golf & Country Club'),
  ('United States', 'Oneka Ridge Golf Course'),
  ('United States', 'Oneonta Country Club'),
  ('United States', 'Onondaga Golf Country Club'),
  ('United States', 'Ontario Country Club'),
  ('United States', 'Onteora Club'),
  ('United States', 'Ontonagon Golf Club'),
  ('United States', 'Onwentsia Club'),
  ('United States', 'Ooltewah Club'),
  ('United States', 'Oquirrh Hills Golf Course'),
  ('United States', 'Orange At Ford Hill Country Club'),
  ('United States', 'Orange At Palmetto Pines Golf Course'),
  ('United States', 'Orange Beach Golf Center'),
  ('United States', 'Orange Blossom Hills Golf Country Club'),
  ('United States', 'Orange Hills Country Club'),
  ('United States', 'Orange Tree Golf Club'),
  ('United States', 'Orange Tree Golf Conference Resort'),
  ('United States', 'Orcas Island Country Golf Club'),
  ('United States', 'Orchard Creek'),
  ('United States', 'Orchard Creek Public Golf Club'),
  ('United States', 'Orchard Golf Country Club'),
  ('United States', 'Orchard Grove At Treesdale Golf Country Club'),
  ('United States', 'Orchard Hill Country Club'),
  ('United States', 'Orchard Hills Golf Club'),
  ('United States', 'Orchard Hills Golf Course'),
  ('United States', 'Orchard Lake Country Club'),
  ('United States', 'Orchard Park Country Club'),
  ('United States', 'Orchard Ponds Golf Club'),
  ('United States', 'Orchard Ridge Country Club'),
  ('United States', 'Orchard Trace Golf Club'),
  ('United States', 'Orchard Vali Golf Club'),
  ('United States', 'Orchard Valley Golf Course'),
  ('United States', 'Orchard Vally Golf Course'),
  ('United States', 'Orchards Executive Golf Course'),
  ('United States', 'Orchards Golf Club'),
  ('United States', 'Orchards at Egg Harbor'),
  ('United States', 'Orchid Island Golf Beach Club'),
  ('United States', 'Oregon Country Club'),
  ('United States', 'Oregon Trail Country Club'),
  ('United States', 'Orgill Golf Course'),
  ('United States', 'Origins Golf Club'),
  ('United States', 'Orinda Country Club'),
  ('United States', 'Oriole Golf Club'),
  ('United States', 'Oriskany Hill Golf Club'),
  ('United States', 'Orleans Country Club'),
  ('United States', 'Oro Valley Country Club'),
  ('United States', 'Orofino Golf Course'),
  ('United States', 'Orono Public Golf Course'),
  ('United States', 'Oroville Golf Club'),
  ('United States', 'Osage City Country Club'),
  ('United States', 'Osawatomie Golf Course'),
  ('United States', 'Osborne Country Club'),
  ('United States', 'Osceola Golf Course'),
  ('United States', 'Osceola Municipal Golf Course'),
  ('United States', 'Osgood Golf Course'),
  ('United States', 'Oshkosh Country Club'),
  ('United States', 'Oshux Golf'),
  ('United States', 'Osiris Country Club'),
  ('United States', 'Oskaloosa Golf'),
  ('United States', 'Oso Creek Golf Course'),
  ('United States', 'Osoyoos Golf And Country Club Desert Gold'),
  ('United States', 'Osoyoos Golf And Country Club Park Meadows'),
  ('United States', 'Osprey Heron At Okeeheelee Golf Course'),
  ('United States', 'Osprey Point At Kiawah Island Golf Resort'),
  ('United States', 'Osprey Point Golf Club Falcon Raven Course'),
  ('United States', 'Osprey Point Golf Club Hawk Falcon Course'),
  ('United States', 'Osprey Point Golf Club Hawk Raven Course'),
  ('United States', 'Osseo Golf Club'),
  ('United States', 'Oswego Country Club The'),
  ('United States', 'Oswego Golf Association'),
  ('United States', 'Othello Golf Club'),
  ('United States', 'Otsego Golf Club'),
  ('United States', 'Ottawa Golf Course'),
  ('United States', 'Ottawa Park Golf Course'),
  ('United States', 'Otte Golf & Family Fun Center'),
  ('United States', 'Otter Creek Golf Course'),
  ('United States', 'Otter Valley Country Club'),
  ('United States', 'Otterkill Golf Country Club'),
  ('United States', 'Ottumwa Country Club'),
  ('United States', 'Ouachita Country Club'),
  ('United States', 'Ould Newbury Golf Club'),
  ('United States', 'Ouleout Creek Golf Course'),
  ('United States', 'Outdoor Country Club'),
  ('United States', 'Outdoor Resort Indio'),
  ('United States', 'Outlaw At Paradise Pointe Golf Complex'),
  ('United States', 'Outlaw Course At Desert Mountain Golf Club'),
  ('United States', 'Outlaw Golf Club At Hideout Canyon Challenge Course'),
  ('United States', 'Over Lake Golf Course'),
  ('United States', 'Over Look Woods At Old Westbury Golf Country Club'),
  ('United States', 'Overbrook Golf Club'),
  ('United States', 'Overlake Golf Country Club'),
  ('United States', 'Overland Golf Course'),
  ('United States', 'Overland Park Golf Course'),
  ('United States', 'Overlook Golf Course'),
  ('United States', 'Overlook The'),
  ('United States', 'Overpeck Golf Course'),
  ('United States', 'Owasco Country Club'),
  ('United States', 'Owasso Golf Athletic Club'),
  ('United States', 'Owatonna Country Club'),
  ('United States', 'Owens Brockway Golf Course'),
  ('United States', 'Owensboro Country Club'),
  ('United States', 'Owl Creek Country Club'),
  ('United States', 'Owls Head Golf Club'),
  ('United States', 'Owls Nest Golf Club'),
  ('United States', 'Owosso Country Club'),
  ('United States', 'Oxbow Country Club'),
  ('United States', 'Oxbow Creek Golf Course'),
  ('United States', 'Oxbow Golf Course'),
  ('United States', 'Oxford Hills Country Club'),
  ('United States', 'Oxford Valley Golf Course'),
  ('United States', 'Oxmoor Country Club'),
  ('United States', 'Oyster Bay Golf Links'),
  ('United States', 'Oyster Bay Town Golf Course Clubhouse'),
  ('United States', 'Oyster Creek Golf Country Club'),
  ('United States', 'Oyster Harbors Club'),
  ('United States', 'Oyster Reef Golf Course'),
  ('United States', 'Ozark Recreation Association Club'),
  ('United States', 'Ozark Ridge Golf Course'),
  ('United States', 'Ozarks National'),
  ('United States', 'Ozaukee Country Club'),
  ('United States', 'O’Bannon Creek Golf Club'),
  ('United States', 'Paa Ko Ridge Golf Club Course 1'),
  ('United States', 'Paa Ko Ridge Golf Club Course 2'),
  ('United States', 'Paa Ko Ridge Golf Club Course 3'),
  ('United States', 'Pablo Creek Club'),
  ('United States', 'Pacific Grove Golf Links'),
  ('United States', 'Pacific Springs Golf Course'),
  ('United States', 'Packanack Golf Club'),
  ('United States', 'Packsaddle Ridge Golf Course'),
  ('United States', 'Paganica Golf Course'),
  ('United States', 'Paint Creek Country Club'),
  ('United States', 'Painted Desert Golf Club'),
  ('United States', 'Painted Dunes Desert Golf Club East West Course'),
  ('United States', 'Painted Dunes Desert Golf Course East North Course'),
  ('United States', 'Painted Dunes Desert Golf Course North West Course'),
  ('United States', 'Painted Hills Golf Club'),
  ('United States', 'Painted Mountain Golf Club'),
  ('United States', 'Pajaro Valley Golf Club'),
  ('United States', 'Pakachoag Golf Course'),
  ('United States', 'Pala Mesa Resort'),
  ('United States', 'Palacio Del Mar Golf Course'),
  ('United States', 'Palatine Hills Golf Course'),
  ('United States', 'Palatka Golf Club'),
  ('United States', 'Pali Municipal Golf Course'),
  ('United States', 'Palisade State Park Golf Course'),
  ('United States', 'Palisades Golf Course'),
  ('United States', 'Pallo''s Par 3 Golf Course'),
  ('United States', 'Palm At Angel Park Golf Club'),
  ('United States', 'Palm At Mccormick Ranch Golf Club'),
  ('United States', 'Palm Beach Country Club'),
  ('United States', 'Palm Beach Golf Course'),
  ('United States', 'Palm Beach National Golf Course'),
  ('United States', 'Palm Cove Golf And Yacht Club'),
  ('United States', 'Palm Creek Golf Club'),
  ('United States', 'Palm Desert Country Club'),
  ('United States', 'Palm Desert Greens Country Club'),
  ('United States', 'Palm Desert Resort Country Club'),
  ('United States', 'Palm Harbor Golf Club'),
  ('United States', 'Palm Hill Country Club'),
  ('United States', 'Palm Royale Country Club'),
  ('United States', 'Palm Valley Golf Club'),
  ('United States', 'Palm Valley Golf Club North South'),
  ('United States', 'Palm Valley Golf Club North West'),
  ('United States', 'Palm Valley Golf Club South West'),
  ('United States', 'Palma Ceia Golf Country Club'),
  ('United States', 'Palmbrook Golf Club'),
  ('United States', 'Palmer At Oasis Golf Club'),
  ('United States', 'Palmer Course At Wildfire Golf Club At Desert Ridge'),
  ('United States', 'Palmer Golf Course'),
  ('United States', 'Palmer Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Palmer Hills Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Palmetto At Glades Country Club'),
  ('United States', 'Palmetto At Myrtlewood Golf Club'),
  ('United States', 'Palmetto At The Villages Executive Golf Trail'),
  ('United States', 'Palmetto Golf Club'),
  ('United States', 'Palmetto Golf Course'),
  ('United States', 'Palmetto Hills Golf Club'),
  ('United States', 'Palmetto Magnolia At Callawassie Island Club'),
  ('United States', 'Palmetto Pine Country Club'),
  ('United States', 'Palmira Golf Club'),
  ('United States', 'Palmira Golf Club Egret Ibis'),
  ('United States', 'Palmira Golf Club Ibis Osprey'),
  ('United States', 'Palmira Golf Club Osprey Egret'),
  ('United States', 'Palms At Marriotts Desert Springs Resort'),
  ('United States', 'Palms At Palm Aire Country Club'),
  ('United States', 'Palms At Pompano Beach Golf Course'),
  ('United States', 'Palms At Rotonda Golf Country Club'),
  ('United States', 'Palms Golf Club'),
  ('United States', 'Palms Golf Course At Oakwood Country Club'),
  ('United States', 'Palms Lakes At Hacienda Hills Golf Country Club'),
  ('United States', 'Palmyra Golf Course'),
  ('United States', 'Palo Alto Hills Golf Country Club'),
  ('United States', 'Palo Verde Golf Course'),
  ('United States', 'Palos Country Club'),
  ('United States', 'Palos Hills Golf Club'),
  ('United States', 'Palos Verdes Golf Club'),
  ('United States', 'Palos Verdes Shores Golf Club'),
  ('United States', 'Palouse Ridge Golf Club At Washington State University'),
  ('United States', 'Pan-Yak Golf Course'),
  ('United States', 'Pana Country Club'),
  ('United States', 'Panama Country Club'),
  ('United States', 'Panhandle State University Golf Course'),
  ('United States', 'Panola Country Club'),
  ('United States', 'Panola Mountain Golf Club 10 Hole Course'),
  ('United States', 'Panola Mountain Golf Club 18 Hole Course'),
  ('United States', 'Panola Woods Country Club'),
  ('United States', 'Panorama At Balsams Grand Resort Hotel The'),
  ('United States', 'Panorama Golf Course'),
  ('United States', 'Panorama Village Golf Course'),
  ('United States', 'Panorama West Golf Course'),
  ('United States', 'Panther Creek Country Club'),
  ('United States', 'Panther Lake At Orange County National'),
  ('United States', 'Panther National Championship Course'),
  ('United States', 'Panther National Short Course Panther9'),
  ('United States', 'Panther Run Golf Club'),
  ('United States', 'Panther Valley Golf Country Club'),
  ('United States', 'Panthers Run At Ocean Ridge Plantation'),
  ('United States', 'Paola Country Club'),
  ('United States', 'Pap Pap Par 3 Golf Course'),
  ('United States', 'Papago Golf Club'),
  ('United States', 'Par 3 At Battle Creek Public Golf'),
  ('United States', 'Par 3 At Ben Hawes State Park'),
  ('United States', 'Par 3 At Borland Golf Center'),
  ('United States', 'Par 3 At Bright Leaf Golf Resort'),
  ('United States', 'Par 3 At Cherokee Ridge Golf Course'),
  ('United States', 'Par 3 At Clovis Municipal Golf Course'),
  ('United States', 'Par 3 At Colleton River Club'),
  ('United States', 'Par 3 At Cyprian Keyes Golf Club'),
  ('United States', 'Par 3 At Fore Lakes Golf Course'),
  ('United States', 'Par 3 At Fox Ridge Golf Course'),
  ('United States', 'Par 3 At Hollybrook Golf Tennis Club'),
  ('United States', 'Par 3 At Indian Tree Golf Club'),
  ('United States', 'Par 3 At Jefferson Park Golf Club'),
  ('United States', 'Par 3 At Lafortune Park Golf Course'),
  ('United States', 'Par 3 At Marine Memorial Golf Course'),
  ('United States', 'Par 3 At Mill Creek Golf Club'),
  ('United States', 'Par 3 At Olde Homestead Golf Club'),
  ('United States', 'Par 3 At Tri Palm Country Club'),
  ('United States', 'Par 3 At Vista Valencia Golf Course'),
  ('United States', 'Par 3 At Westchester Golf Country Club'),
  ('United States', 'Par 3 At Windyke Country Club'),
  ('United States', 'Par 3 Championship At Scallys Golf Center'),
  ('United States', 'Par 3 Course'),
  ('United States', 'Par 3 Course At Crosswinds Golf Club'),
  ('United States', 'Par 3 Course At Eagle Point Golf Club'),
  ('United States', 'Par 3 Golf At Sandy Bottom Park'),
  ('United States', 'Par 3 Golf Course At Westchester Country Club'),
  ('United States', 'Par 3 Practice At Tradition Golf Club'),
  ('United States', 'Par 3 West'),
  ('United States', 'Par Three At Highland View Golf Club'),
  ('United States', 'Par Three At Jackson Park Golf Course'),
  ('United States', 'Par Three At Quaker Meadows Golf Club'),
  ('United States', 'Par Three At Windy Hill Golf Course'),
  ('United States', 'Paradise Golf Course'),
  ('United States', 'Paradise Golf Resort'),
  ('United States', 'Paradise Hills Golf Course'),
  ('United States', 'Paradise Peak West'),
  ('United States', 'Paradise Valley'),
  ('United States', 'Paradise Valley Country Club'),
  ('United States', 'Paradise Valley Golf & Country Club'),
  ('United States', 'Paradise Valley Golf Club'),
  ('United States', 'Paradise Valley Golf Course'),
  ('United States', 'Paradise Valley Par 3'),
  ('United States', 'Paragould Country Club'),
  ('United States', 'Paramount Country Club'),
  ('United States', 'Paramus Golf Course'),
  ('United States', 'Paris Golf Country Club'),
  ('United States', 'Paris Hill Country Club'),
  ('United States', 'Paris Mountain Country Club'),
  ('United States', 'Park City Golf Club'),
  ('United States', 'Park Falls Country Club'),
  ('United States', 'Park Hill Golf Club'),
  ('United States', 'Park Hills Country Club'),
  ('United States', 'Park Hills Golf Course'),
  ('United States', 'Park Hills Golf Supper Club'),
  ('United States', 'Park Meadows Golf Club'),
  ('United States', 'Park Ridge Country Club'),
  ('United States', 'Park Ridge Golf Course'),
  ('United States', 'Park Shore Golf Course'),
  ('United States', 'Parke County Golf Course'),
  ('United States', 'Parkland Golf Club'),
  ('United States', 'Parkston Country Club'),
  ('United States', 'Parkview Fairways Golf Course'),
  ('United States', 'Parkview Golf Course'),
  ('United States', 'Parkway Golf Course'),
  ('United States', 'Parsons Katy Golf Club'),
  ('United States', 'Parto''s Big On Golf'),
  ('United States', 'Partos Big On Golf Learning Center'),
  ('United States', 'Partridge Run Golf Country Club'),
  ('United States', 'Pasadena Ridge Par 3 Golf Course'),
  ('United States', 'Pasadena Yacht Country Club'),
  ('United States', 'Pasatiempo Golf Club'),
  ('United States', 'Pascagoula Country Club'),
  ('United States', 'Paschal Golf Club'),
  ('United States', 'Pasco Golfland'),
  ('United States', 'Pasfield Golf Course'),
  ('United States', 'Paso Robles Golf Club'),
  ('United States', 'Pass Christian Isles Golf Club'),
  ('United States', 'Passaconaway Country Club'),
  ('United States', 'Pathfinder Village Golf Course'),
  ('United States', 'Patricia Island Golf Club'),
  ('United States', 'Patrick Farms Golf Course'),
  ('United States', 'Patriot Golf Club'),
  ('United States', 'Patriot Golf Course'),
  ('United States', 'Patriot Hills Golf Club'),
  ('United States', 'Patriots Glen Golf Club'),
  ('United States', 'Patriots Point Golf Links'),
  ('United States', 'Patterson Club'),
  ('United States', 'Pattison Park Golf course'),
  ('United States', 'Patty Jewett Golf Course Peak Nine'),
  ('United States', 'Patty Jewett Golf Course Plains Nine'),
  ('United States', 'Patty Jewett Golf Course Prairie Nine'),
  ('United States', 'Paul Harney Golf Club'),
  ('United States', 'Paul Hunt Thompson Golf Course'),
  ('United States', 'Paullina Golf Course'),
  ('United States', 'Pauls Valley Municipal Golf Course'),
  ('United States', 'Pauma Valley Country Club'),
  ('United States', 'Paupack Hills Golf Country Club'),
  ('United States', 'Paw Paw Lake Golf Course'),
  ('United States', 'Pawhuska Golf Country Club'),
  ('United States', 'Pawleys Plantation Golf Country Club'),
  ('United States', 'Pawnee Municipal Golf Course'),
  ('United States', 'Pawtucket Country Club'),
  ('United States', 'Paxon Hollow Golf Club'),
  ('United States', 'Paxton Park Golf Course'),
  ('United States', 'Payne S Valley'),
  ('United States', 'Payson Golf Club'),
  ('United States', 'Peabody Golf Course'),
  ('United States', 'Peace Pipe Golf Club'),
  ('United States', 'Peace Portal Par 3 Golf Course'),
  ('United States', 'Peach Tree Golf Country Club'),
  ('United States', 'Peach Trees Executive Golf Club'),
  ('United States', 'Peachtree Golf Center'),
  ('United States', 'Peachtree Golf Club'),
  ('United States', 'Peachtree Hills Country Club'),
  ('United States', 'Peacock Gap Golf Club'),
  ('United States', 'Peaks At Tonto Verde Golf Club'),
  ('United States', 'Peaks Par 3 Golf Course'),
  ('United States', 'Pearl At Kalauao'),
  ('United States', 'Pearl Lakes Country Club'),
  ('United States', 'Pearl Municipal Golf Course'),
  ('United States', 'Pease Blue Golf Course'),
  ('United States', 'Pease Original 18 Golf Course'),
  ('United States', 'Pebble Beach Golf Linkstm'),
  ('United States', 'Pebble Brook Golf Club'),
  ('United States', 'Pebble Creek'),
  ('United States', 'Pebble Creek Golf Club'),
  ('United States', 'Pebble Creek Golf Course'),
  ('United States', 'Pebble Lake Golf Club'),
  ('United States', 'Pebble Lake Golf Course'),
  ('United States', 'Pebble Ponds Golf Course'),
  ('United States', 'Pebblebrook Golf Club'),
  ('United States', 'Pebblebrook Golf Course'),
  ('United States', 'Pebblebrook Golf Links'),
  ('United States', 'Pebblewood Golf Course'),
  ('United States', 'Pecan Valley At Mohawk Park Golf Course'),
  ('United States', 'Pecan Valley Golf Course'),
  ('United States', 'Peddie Golf Club'),
  ('United States', 'Pehquenakonck Country Club'),
  ('United States', 'Pekin Country Club'),
  ('United States', 'Pelham Bay At Pelham Split Rock Golf Course'),
  ('United States', 'Pelham Country Club'),
  ('United States', 'Pelican At The Villages Executive Golf Trail'),
  ('United States', 'Pelican Falls At Pelican Lakes Golf Club'),
  ('United States', 'Pelican Golf Club'),
  ('United States', 'Pelican Lakes At Pelican Lakes Golf Club'),
  ('United States', 'Pelican Marsh Golf Club'),
  ('United States', 'Pelican Osprey At Burnt Store Marina Country Club'),
  ('United States', 'Pelican Point Golf Club Get Golf Ready Course'),
  ('United States', 'Pelican Point Golf Club Links Course'),
  ('United States', 'Pelican Pointe Golf Country Club Hatchett Meadows Course'),
  ('United States', 'Pelican Pointe Golf Country Club Meadows Preserve Course'),
  ('United States', 'Pelican Pointe Golf Country Club Preserve Hatchett Course'),
  ('United States', 'Pelicans Nest Golf Club Gator Course'),
  ('United States', 'Pelicans Nest Golf Club Hurricane Course'),
  ('United States', 'Pella Golf & Country Club'),
  ('United States', 'Pembroke Country Club'),
  ('United States', 'Pembroke Lakes Golf Racquet Club'),
  ('United States', 'Pembroke Pines Country Club'),
  ('United States', 'Pend Oreille Golf Country Club'),
  ('United States', 'Pendaries Golf Country Club'),
  ('United States', 'Pender Island Golf And Country Club'),
  ('United States', 'Penderbrook Golf Club'),
  ('United States', 'Pendleton Golf Club'),
  ('United States', 'Pendleton Harbor Golf Course'),
  ('United States', 'Pendleton Hills'),
  ('United States', 'Penfield Country Club'),
  ('United States', 'Peninsula Golf Club'),
  ('United States', 'Peninsula Golf Country Club'),
  ('United States', 'Peninsula Golf Course'),
  ('United States', 'Peninsula Golf Resort'),
  ('United States', 'Peninsula State Park Golf Course'),
  ('United States', 'Penmar Golf Course'),
  ('United States', 'Penn Oaks Country Club'),
  ('United States', 'Penn Terra Golf Course'),
  ('United States', 'Penney Farms Retirement Community Golf Course'),
  ('United States', 'Pennhills Club'),
  ('United States', 'Pennrose Park Country Club'),
  ('United States', 'Pennsauken Country Club'),
  ('United States', 'Pennyrile Forest State Park Resort'),
  ('United States', 'Penobscot Valley Country Club'),
  ('United States', 'Pensacola Country Club'),
  ('United States', 'Peoria Pines Golf Club'),
  ('United States', 'Peoria Ridge'),
  ('United States', 'Pepper Pike Club'),
  ('United States', 'Pequabuck Golf Club'),
  ('United States', 'Pequot Golf Club'),
  ('United States', 'Perdido Bay Golf Club'),
  ('United States', 'Perham Lakeside Golf Club'),
  ('United States', 'Peridia Golf Country Club'),
  ('United States', 'Perinton Golf Country Club'),
  ('United States', 'Perry Creek Golf Racquet Club'),
  ('United States', 'Perry Golf Country Club'),
  ('United States', 'Perry Golf Course'),
  ('United States', 'Perry Golf and Country Club'),
  ('United States', 'Perry Park Country Club'),
  ('United States', 'Perryton Golf Club'),
  ('United States', 'Perryville Country Club'),
  ('United States', 'Persimmon Country Club'),
  ('United States', 'Persimmon Hill Golf Club'),
  ('United States', 'Persimmon Ridge Golf Club'),
  ('United States', 'Perttu''s Big Spruce Golf Course'),
  ('United States', 'Petaluma Golf Country Club'),
  ('United States', 'Pete Brown Golf Facility'),
  ('United States', 'Pete Dye Challenge At Mission Hills Country Club'),
  ('United States', 'Pete Dye Course'),
  ('United States', 'Pete Dye Course At Hideaway Club'),
  ('United States', 'Pete Dye River Course Of Virginia Tech'),
  ('United States', 'Peter Yegen Jr Golf Club'),
  ('United States', 'Petersburg Country Club'),
  ('United States', 'Petoskey - Bay View Country Club'),
  ('United States', 'Petrifying Springs Golf Course'),
  ('United States', 'Pevely Farms Golf Course'),
  ('United States', 'Pfau Indiana University Golf Course'),
  ('United States', 'Pga National Resort Champion Course'),
  ('United States', 'Pga National Resort Estates Course'),
  ('United States', 'Pga National Resort Fazio Course'),
  ('United States', 'Pga National Resort Palmer Course'),
  ('United States', 'Pga National Resort The Match'),
  ('United States', 'Pga National Resort The Staple'),
  ('United States', 'Pga West Greg Norman Course'),
  ('United States', 'Pga West Jack Nicklaus Tournament Course'),
  ('United States', 'Pga West Pete Dye Dunes Course'),
  ('United States', 'Pga West Pete Dye Mountain Course'),
  ('United States', 'Pga West Private Arnold Palmer Course'),
  ('United States', 'Pga West Private Jack Nicklaus Private Course'),
  ('United States', 'Pga West Private Tom Weiskopf Course'),
  ('United States', 'Pheasand Hills Golf Course'),
  ('United States', 'Pheasant Acres Golf Course'),
  ('United States', 'Pheasant Glen Golf Resort'),
  ('United States', 'Pheasant Hill Country Club'),
  ('United States', 'Pheasant Hollow Golf Course'),
  ('United States', 'Pheasant Links'),
  ('United States', 'Pheasant Ridge Golf Club'),
  ('United States', 'Pheasant Ridge Golf Course'),
  ('United States', 'Pheasant Run Golf Club'),
  ('United States', 'Pheasant Run Golf Course'),
  ('United States', 'Pheasant Run Golfcourse'),
  ('United States', 'Phil Harris Golf Course'),
  ('United States', 'Philadelphia Country Club'),
  ('United States', 'Philipsburg Elks Lodge Country Club'),
  ('United States', 'Phillip J Rotella Memorial Golf Course'),
  ('United States', 'Phillips Park Golf Course'),
  ('United States', 'Phillipsburg Golf Course'),
  ('United States', 'Philmont Country Club'),
  ('United States', 'Phoenix Country Club 1'),
  ('United States', 'Phoenixville Country Club'),
  ('United States', 'Piankatank River Golf Club'),
  ('United States', 'Picacho Hills Country Club'),
  ('United States', 'Picatinny Golf Club'),
  ('United States', 'Pickaway Golf Course'),
  ('United States', 'Pickens Golf Club'),
  ('United States', 'Pickering Valley Golf Club'),
  ('United States', 'Pickwick Landing State Park Golf Course'),
  ('United States', 'Pico Rivera Golf Club'),
  ('United States', 'Pictured Rocks Golf Club'),
  ('United States', 'Piedmont Canyon Club'),
  ('United States', 'Piedmont Driving Club'),
  ('United States', 'Piedmont Driving Club Par 3 Course'),
  ('United States', 'Piedmont Golf Club'),
  ('United States', 'Pierce Lake Golf Course and Park'),
  ('United States', 'Pierce Park Golf & Events'),
  ('United States', 'Pierce Park Greens'),
  ('United States', 'Pierson Golf Course'),
  ('United States', 'Pigeon Creek Golf Course'),
  ('United States', 'Pike Lake Golf Course'),
  ('United States', 'Pike Run Country Club'),
  ('United States', 'Pike Run Golf Club'),
  ('United States', 'Pikeville Country Club'),
  ('United States', 'Pilgrim''s Run Golf Course'),
  ('United States', 'Pilgrims Oak Golf Course'),
  ('United States', 'Pilot Knob Park Golf Course'),
  ('United States', 'Pimlico At The Villages Executive Golf Trail'),
  ('United States', 'Pinch Brook Golf Course'),
  ('United States', 'Pine Acres Country Club'),
  ('United States', 'Pine Acres Golf Course'),
  ('United States', 'Pine Acres Par 3 Golf Course Driving Range'),
  ('United States', 'Pine At Mccormick Ranch Golf Club'),
  ('United States', 'Pine Barrens'),
  ('United States', 'Pine Bay Golf Course'),
  ('United States', 'Pine Bayhead Golf Course At Countryside Country Club'),
  ('United States', 'Pine Beach East Golf Course'),
  ('United States', 'Pine Bluff Country Club'),
  ('United States', 'Pine Brook Country Club'),
  ('United States', 'Pine Brook Golf Course'),
  ('United States', 'Pine Brook Golf Links'),
  ('United States', 'Pine Burr Country Club'),
  ('United States', 'Pine Burr Golf Course'),
  ('United States', 'Pine Canyon Club'),
  ('United States', 'Pine Creek Golf Club'),
  ('United States', 'Pine Creek Golf Course'),
  ('United States', 'Pine Crest Golf Course'),
  ('United States', 'Pine Edge Golf Course'),
  ('United States', 'Pine Forest Country Club'),
  ('United States', 'Pine Grove Country Club'),
  ('United States', 'Pine Grove Golf Course'),
  ('United States', 'Pine Grove Springs Country Club'),
  ('United States', 'Pine Hill Country Club'),
  ('United States', 'Pine Hill Golf Club'),
  ('United States', 'Pine Hill Golf Country Club'),
  ('United States', 'Pine Hill Golf Course'),
  ('United States', 'Pine Hills Country Club'),
  ('United States', 'Pine Hills Golf Club'),
  ('United States', 'Pine Hills Golf Course'),
  ('United States', 'Pine Hollow Country Club'),
  ('United States', 'Pine Hollow Golf Club'),
  ('United States', 'Pine Hollow Golf Course'),
  ('United States', 'Pine Island Country Club'),
  ('United States', 'Pine Island Golf Course'),
  ('United States', 'Pine Island Ridge Country Club'),
  ('United States', 'Pine Islands Golf Club'),
  ('United States', 'Pine Knob Golf Club'),
  ('United States', 'Pine Knoll Executive Golf Course'),
  ('United States', 'Pine Knolls Country Club'),
  ('United States', 'Pine Knolls Golf Course'),
  ('United States', 'Pine Lake Country Club'),
  ('United States', 'Pine Lake Golf Club'),
  ('United States', 'Pine Lake Golf Course'),
  ('United States', 'Pine Lakes Country Club'),
  ('United States', 'Pine Lakes Golf Club'),
  ('United States', 'Pine Marsh Golf Course'),
  ('United States', 'Pine Meadow Country Club Estates'),
  ('United States', 'Pine Meadow Golf Club'),
  ('United States', 'Pine Meadows Golf Club'),
  ('United States', 'Pine Meadows Golf Course'),
  ('United States', 'Pine Mountain Golf Club'),
  ('United States', 'Pine Mountain Golf Course'),
  ('United States', 'Pine Mountain Lake Golf Course'),
  ('United States', 'Pine Needles Country Club'),
  ('United States', 'Pine Needles Lodge Golf Club'),
  ('United States', 'Pine Needles Lodge Golf Club Practice Loop'),
  ('United States', 'Pine Oaks Golf Club'),
  ('United States', 'Pine Orchard Yacht Country Club'),
  ('United States', 'Pine Ridge Classic Golf Course'),
  ('United States', 'Pine Ridge Country Club'),
  ('United States', 'Pine Ridge Golf Club'),
  ('United States', 'Pine Ridge Golf Club Little Pine'),
  ('United States', 'Pine Ridge Golf Course'),
  ('United States', 'Pine Ridge Municipal Golf Center'),
  ('United States', 'Pine River Country Club'),
  ('United States', 'Pine River Golf Club'),
  ('United States', 'Pine Royale Golf Club'),
  ('United States', 'Pine Shore Golf Course'),
  ('United States', 'Pine Trace Golf Club'),
  ('United States', 'Pine Tree Golf Club'),
  ('United States', 'Pine Valley Country Club'),
  ('United States', 'Pine Valley Golf & Country Club'),
  ('United States', 'Pine Valley Golf Club'),
  ('United States', 'Pine Valley Golf Club Championship'),
  ('United States', 'Pine Valley Golf Club Short'),
  ('United States', 'Pine Valley Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Pine View Golf Course'),
  ('United States', 'Pine View Highlands'),
  ('United States', 'Pine Woods Golf Course'),
  ('United States', 'Pinebrook Ironwood Golf Course'),
  ('United States', 'Pinecone Thistle At Resort At The Mountain The'),
  ('United States', 'Pinecrest Country Club'),
  ('United States', 'Pinecrest Golf Club'),
  ('United States', 'Pinecrest Golf Course'),
  ('United States', 'Pinecrest Lake Golf Club'),
  ('United States', 'Pinecroft Golf Course'),
  ('United States', 'Pinehaven Country Club'),
  ('United States', 'Pinehills At Myrtlewood Golf Club'),
  ('United States', 'Pinehills Golf Club Jones Course'),
  ('United States', 'Pinehills Golf Club Nicklaus Course'),
  ('United States', 'Pinehurst Golf Club'),
  ('United States', 'Pinehurst Golf Course'),
  ('United States', 'Pinehurst Resort Country Club No 1'),
  ('United States', 'Pinehurst Resort Country Club No 10'),
  ('United States', 'Pinehurst Resort Country Club No 2'),
  ('United States', 'Pinehurst Resort Country Club No 3'),
  ('United States', 'Pinehurst Resort Country Club No 4'),
  ('United States', 'Pinehurst Resort Country Club No 5'),
  ('United States', 'Pinehurst Resort Country Club No 6'),
  ('United States', 'Pinehurst Resort Country Club No 7'),
  ('United States', 'Pinehurst Resort Country Club No 8'),
  ('United States', 'Pinehurst Resort Country Club No 9'),
  ('United States', 'Pinehurst Resort Country Club The Cradle'),
  ('United States', 'Pinehurst Resort Country Club Thistle Dhu Putting Course'),
  ('United States', 'Pineknoll Golf Club'),
  ('United States', 'Pinelands Golf Club'),
  ('United States', 'Pinemoor West Golf Club'),
  ('United States', 'Pineridge Golf Course'),
  ('United States', 'Pines At Clermont'),
  ('United States', 'Pines At Colonial Springs Golf Course'),
  ('United States', 'Pines At Diamondhead Country Club'),
  ('United States', 'Pines At Ft Walton Beach Golf Club'),
  ('United States', 'Pines At Glades Country Club'),
  ('United States', 'Pines At Pompano Beach Golf Course'),
  ('United States', 'Pines At Royal Poinciana Golf Club'),
  ('United States', 'Pines At Willowcreek Golf Club'),
  ('United States', 'Pines At Woodmont Country Club'),
  ('United States', 'Pines Course'),
  ('United States', 'Pines Golf Club'),
  ('United States', 'Pines Golf Club The'),
  ('United States', 'Pines Golf Course'),
  ('United States', 'Pines Lake At Tri Cities Golf Course'),
  ('United States', 'Pines Sands At Star Hill Golf Country Club'),
  ('United States', 'Pines Woodland At Blue Hill Golf Course'),
  ('United States', 'Pinetop Country Club'),
  ('United States', 'Pinetop Lakes Golf Country Club'),
  ('United States', 'Pinetree Country Club'),
  ('United States', 'Pinetuck Golf Course'),
  ('United States', 'Pineview Country Club'),
  ('United States', 'Pinewood Country Club'),
  ('United States', 'Pinewood Golf Club'),
  ('United States', 'Pinewood Golf Course'),
  ('United States', 'Piney Apple Golf Course'),
  ('United States', 'Piney Point Golf Club'),
  ('United States', 'Pinnacle At Troon North Golf Club'),
  ('United States', 'Pinnacle Country Club'),
  ('United States', 'Pinnacle Country Club and Golf Course'),
  ('United States', 'Pinnacle Golf Club'),
  ('United States', 'Pinnacle Hills Golf Course'),
  ('United States', 'Pinnacle Peak Country Club'),
  ('United States', 'Pinnacle State Park Golf Club'),
  ('United States', 'Pinon At Towa Golf Resort'),
  ('United States', 'Pinon Hills Golf Course'),
  ('United States', 'Pinon Ponderosa At Pagosa Springs Golf Club'),
  ('United States', 'Pioneer Creek'),
  ('United States', 'Pioneer Family Golf Center'),
  ('United States', 'Pioneer Hills Golf Course'),
  ('United States', 'Pioneer Pointe'),
  ('United States', 'Pioneer Town & Country Club'),
  ('United States', 'Piper Glen Golf Course'),
  ('United States', 'Piper Hills Golf Course'),
  ('United States', 'Pipers Landing Country Club'),
  ('United States', 'Pipestone Creek Golf Course'),
  ('United States', 'Pipestone Golf & Country Club'),
  ('United States', 'Piping Rock Club'),
  ('United States', 'Piscataquis Country Club'),
  ('United States', 'Pismo State Beach Golf Course'),
  ('United States', 'Pistakee Golf Course'),
  ('United States', 'Pitch And Putt At Evergreen Golf Course Inc'),
  ('United States', 'Pitch Putt At Pine Hills Country Club'),
  ('United States', 'Pitch Putt At Scallys Golf Center'),
  ('United States', 'Pitman Golf Course'),
  ('United States', 'Pittsboro Golf Club'),
  ('United States', 'Pittsburgh Field Club'),
  ('United States', 'Pittsburgh National Golf Club'),
  ('United States', 'Placid Lakes Country Club'),
  ('United States', 'Plainfield Country Club'),
  ('United States', 'Plainfield West Nine'),
  ('United States', 'Plains Municipal Golf Course'),
  ('United States', 'Plainsman Golf Club'),
  ('United States', 'Plandome Country Club'),
  ('United States', 'Plantation At Ponte Vedra'),
  ('United States', 'Plantation At Sea Island Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club North South Course'),
  ('United States', 'Plantation Bay Golf And Country Club Prestwick Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club South West Course'),
  ('United States', 'Plantation Bay Golf And Country Club West North Course'),
  ('United States', 'Plantation Bottom At Valdosta Country Club'),
  ('United States', 'Plantation Golf Club'),
  ('United States', 'Plantation Golf Course'),
  ('United States', 'Plantation Lakes Golf And Country Club'),
  ('United States', 'Plantation On Crystal River Championship Course'),
  ('United States', 'Plantation On Crystal River Lagoons Course'),
  ('United States', 'Plantation Palms Golf Club'),
  ('United States', 'Plantation Preserve Golf Course'),
  ('United States', 'Planterra Ridge Golf Club'),
  ('United States', 'Planters Row At Port Royal Golf Club'),
  ('United States', 'Platteville Golf and Country Club'),
  ('United States', 'Player At Lyman Orchards Golf Club'),
  ('United States', 'Player S Ridge Golf'),
  ('United States', 'Players Club At Deer Creek Highlands 9'),
  ('United States', 'Players Club At Deer Creek Palmer Championship'),
  ('United States', 'Players Club At St James Plantation'),
  ('United States', 'Pleasant Acres Golf Course'),
  ('United States', 'Pleasant Hill Golf Club'),
  ('United States', 'Pleasant Hill Golf Course'),
  ('United States', 'Pleasant Hills Golf Course'),
  ('United States', 'Pleasant Knolls Golf Course At Turning Stone'),
  ('United States', 'Pleasant Meadows'),
  ('United States', 'Pleasant Run Golf Club'),
  ('United States', 'Pleasant Run Recreation Center'),
  ('United States', 'Pleasant Valley Country Club'),
  ('United States', 'Pleasant Valley Golf Club'),
  ('United States', 'Pleasant Valley Golf Course'),
  ('United States', 'Pleasant Valley Sports Club'),
  ('United States', 'Pleasant View Golf Club'),
  ('United States', 'Pleasant View Golf Course'),
  ('United States', 'Pleasanton Golf Center'),
  ('United States', 'Pleasantville Golf & Country Club'),
  ('United States', 'Plentywood Golf Club'),
  ('United States', 'Plum Brook Country Club'),
  ('United States', 'Plum Brook Golf Course'),
  ('United States', 'Plum Creek Golf Country Club'),
  ('United States', 'Plum Creek Golf Course'),
  ('United States', 'Plum Hollow Country Club'),
  ('United States', 'Plum Lake Golf Course'),
  ('United States', 'Plum River Golf Course'),
  ('United States', 'Plum Tree Country Club'),
  ('United States', 'Plumas Lake Golf Country Club'),
  ('United States', 'Plumas Pines Golf Resort'),
  ('United States', 'Plym Park Golf Course'),
  ('United States', 'Plymouth Country Club'),
  ('United States', 'Pocahontas Country Club'),
  ('United States', 'Pocahontas Golf Club'),
  ('United States', 'Pocantico Hills Golf Course'),
  ('United States', 'Pocasset Golf Club'),
  ('United States', 'Poco Diablo Resort'),
  ('United States', 'Pocono Farms Golf Course'),
  ('United States', 'Pocono Hills Golf Course'),
  ('United States', 'Pohick Bay Golf Course'),
  ('United States', 'Pohlcat'),
  ('United States', 'Poinciana Country Club'),
  ('United States', 'Point Judith Country Club'),
  ('United States', 'Point O'' Woods'),
  ('United States', 'Point Rock Golf Club'),
  ('United States', 'Point Sebago Golf Beach Resort'),
  ('United States', 'Point University Golf Club'),
  ('United States', 'Pointe Aux Barques Golf Course'),
  ('United States', 'Pointe South Golf Club'),
  ('United States', 'Pointe West Country Club'),
  ('United States', 'Pointe West Golf Course'),
  ('United States', 'Poipu Bay Golf Course'),
  ('United States', 'Pokegama Golf Course'),
  ('United States', 'Pokegama Pitch & Putt'),
  ('United States', 'Pole Valley Players Golf Course'),
  ('United States', 'Polo Fields Golf and Country Club'),
  ('United States', 'Polo Golf Country Club'),
  ('United States', 'Polo Park East'),
  ('United States', 'Polo Park Golf Course'),
  ('United States', 'Polson Bay Golf Course Championship Course'),
  ('United States', 'Polson Bay Golf Course Olde Course'),
  ('United States', 'Pomona Golf Country Club'),
  ('United States', 'Pomperaug Golf Club'),
  ('United States', 'Pompey Club The'),
  ('United States', 'Ponca City Country Club'),
  ('United States', 'Ponce De Leon Golf Course'),
  ('United States', 'Pondera Golf Club'),
  ('United States', 'Ponderosa Butte Public Golf Course'),
  ('United States', 'Ponderosa Country Club'),
  ('United States', 'Ponderosa Golf Club'),
  ('United States', 'Ponderosa Golf Course'),
  ('United States', 'Ponderosa Meadows At Pagosa Springs Golf Club'),
  ('United States', 'Ponderosa Pines Golf Course'),
  ('United States', 'Ponderosa Springs Golf Course'),
  ('United States', 'Ponds Golf Course At Quail Heights Country Club'),
  ('United States', 'Ponemah Green Family Golf Center'),
  ('United States', 'Ponta Creek Golf Course Nas'),
  ('United States', 'Pontiac Country Club'),
  ('United States', 'Pontotoc Country Club'),
  ('United States', 'Poolesville Golf Course'),
  ('United States', 'Poolsbrook Golf Course'),
  ('United States', 'Popes Grove Golf Course'),
  ('United States', 'Poplar Creek Golf Course'),
  ('United States', 'Poplar Forest Golf Course'),
  ('United States', 'Poplar Golf Course'),
  ('United States', 'Poplar Grove Golf Club'),
  ('United States', 'Poppy Estate Golf Course'),
  ('United States', 'Poppy Hills Golf Course'),
  ('United States', 'Poppy Ridge Golf Course 18 Hole'),
  ('United States', 'Poppy Ridge Golf Course The Ridge 9'),
  ('United States', 'Poquoy Brook Golf Course'),
  ('United States', 'Port Bay Golf Club'),
  ('United States', 'Port Charlotte Golf Club'),
  ('United States', 'Port Huron Elks Lodge Golf Course'),
  ('United States', 'Port Huron Golf Club'),
  ('United States', 'Port Jefferson Country Club At Harbor Hills'),
  ('United States', 'Port Ludlow Golf Resort'),
  ('United States', 'Port Townsend Golf Club'),
  ('United States', 'Portage Country Club'),
  ('United States', 'Portage Golf Club'),
  ('United States', 'Portage Hills Country Club'),
  ('United States', 'Portage Lake Golf Course'),
  ('United States', 'Portales Country Club'),
  ('United States', 'Porter S Neck Country Club'),
  ('United States', 'Porter Valley Country Club'),
  ('United States', 'Porterville Municipal Golf Course'),
  ('United States', 'Portland Country Club'),
  ('United States', 'Portland Golf Course'),
  ('United States', 'Portland Golf Course West'),
  ('United States', 'Portola Country Club'),
  ('United States', 'Portsmouth Country Club'),
  ('United States', 'Posse At Paradise Pointe Golf Complex'),
  ('United States', 'Poston Butte Golf Club'),
  ('United States', 'Potomac Shores Golf Club'),
  ('United States', 'Potowomut Golf Club'),
  ('United States', 'Potsdam Golf Country Club'),
  ('United States', 'Pottawatomie Golf Course'),
  ('United States', 'Pottawattamie Country Club'),
  ('United States', 'Potters Park Golf Course'),
  ('United States', 'Pound Ridge Golf Club'),
  ('United States', 'Powell Country Club'),
  ('United States', 'Powelton Club The'),
  ('United States', 'Power Ranch Golf Club'),
  ('United States', 'Poxabogue Golf Center'),
  ('United States', 'Practice Area'),
  ('United States', 'Practice Area - Driving Range'),
  ('United States', 'Prague Golf Course'),
  ('United States', 'Prairie At Green Meadow Golf Club'),
  ('United States', 'Prairie Bluff Public Golf Club'),
  ('United States', 'Prairie Country Club'),
  ('United States', 'Prairie Creek Golf Course'),
  ('United States', 'Prairie Dog Golf Course'),
  ('United States', 'Prairie Dunes Country Club'),
  ('United States', 'Prairie Dunes Golf Course'),
  ('United States', 'Prairie Falls Golf Club'),
  ('United States', 'Prairie Farms Golf Course'),
  ('United States', 'Prairie Highlands Golf Course'),
  ('United States', 'Prairie Isle Golf Club'),
  ('United States', 'Prairie Landing'),
  ('United States', 'Prairie Landing Golf Club'),
  ('United States', 'Prairie Links Golf Course & Event Center'),
  ('United States', 'Prairie Pines Golf Club'),
  ('United States', 'Prairie Pines Golf Course'),
  ('United States', 'Prairie Ridge Golf Course'),
  ('United States', 'Prairie Rose Golf Club'),
  ('United States', 'Prairie Trace Golf Club'),
  ('United States', 'Prairie Trail Golf Course'),
  ('United States', 'Prairie Trails Golf Course'),
  ('United States', 'Prairie View Golf Club'),
  ('United States', 'Prairie View Golf Course'),
  ('United States', 'Prairie Vista Golf Course'),
  ('United States', 'Prairie West Colf Course'),
  ('United States', 'Prairie West Golf Club At Weatherford'),
  ('United States', 'Prairie Winds Golf Club'),
  ('United States', 'Prairie Winds Golf Course'),
  ('United States', 'Prairie Woods Golf Course'),
  ('United States', 'Prairie du Chien Country Club'),
  ('United States', 'Prairiewood Golf Course'),
  ('United States', 'Preakness Hills Country Club'),
  ('United States', 'Preakness Valley Golf Course East'),
  ('United States', 'Preakness Valley Golf Course West'),
  ('United States', 'Prentice Pines Golf Course'),
  ('United States', 'Prentiss Country Club'),
  ('United States', 'Prescott Country Club'),
  ('United States', 'Prescott Golf Club'),
  ('United States', 'Preserve At Quail West Golf Country Club'),
  ('United States', 'Preserve Golf Course'),
  ('United States', 'Presidential At Hickory Valley Golf Club'),
  ('United States', 'Presidents Golf Course'),
  ('United States', 'Presidio Golf Course'),
  ('United States', 'Presidio Hills Golf Course'),
  ('United States', 'Presque Isle Country Club'),
  ('United States', 'Prestbury Golf Course'),
  ('United States', 'Preston Golf Country Club'),
  ('United States', 'Preston Golf and Country Club'),
  ('United States', 'Prestwick Country Club'),
  ('United States', 'Prestwick Golf Club'),
  ('United States', 'Prestwick Village Golf Club'),
  ('United States', 'Priest Lake Golf Club'),
  ('United States', 'Primghar Golf and Country Club'),
  ('United States', 'Primm Valley Golf Club Desert Course'),
  ('United States', 'Primm Valley Golf Club Lakes Course'),
  ('United States', 'Primrose At Country Club The'),
  ('United States', 'Prince George Golf Course'),
  ('United States', 'Prince William Golf Club'),
  ('United States', 'Princess Anne Country Club'),
  ('United States', 'Princeton Country Club'),
  ('United States', 'Princeton Elks Golf Course'),
  ('United States', 'Princeton Valley Golf Course'),
  ('United States', 'Princeville Makai Golf Club Makai Course'),
  ('United States', 'Princeville Makai Golf Club Woods Course'),
  ('United States', 'Prison View Golf Course'),
  ('United States', 'Pro Putt Miniature Golf Course'),
  ('United States', 'Proctor Golf Club and Course'),
  ('United States', 'Proctor Pittsford Country Club'),
  ('United States', 'Profile Golf Club'),
  ('United States', 'Promontory Club Dye Canyon Golf Course'),
  ('United States', 'Promontory Club Painted Valley Golf Course'),
  ('United States', 'Prospect Hill Golf Course'),
  ('United States', 'Prospect Point Golf Club'),
  ('United States', 'Prospect Valley Golf Club'),
  ('United States', 'Prouts Neck Country Club'),
  ('United States', 'Providence Club'),
  ('United States', 'Providence Country Club'),
  ('United States', 'Providence Golf Club'),
  ('United States', 'Pruneridge Golf Course'),
  ('United States', 'Pryor Creek Golf Club Elmer Link Course'),
  ('United States', 'Pryor Creek Golf Club Johnny Walker Course'),
  ('United States', 'Pryor Creek Municipal Golf Course'),
  ('United States', 'Ptarmigan Country Club'),
  ('United States', 'Puakea Golf Course'),
  ('United States', 'Pub Course At Mcmenamins Edgefield East 12'),
  ('United States', 'Pub Course At Mcmenamins Edgefield West 20'),
  ('United States', 'Pudding Ridge Golf Club'),
  ('United States', 'Pueblo Country Club'),
  ('United States', 'Pueblo El Mirage Golf Club'),
  ('United States', 'Puerto Del Sol Golf Course'),
  ('United States', 'Pukalani Country Club'),
  ('United States', 'Pumpkin Hollow Driving Range'),
  ('United States', 'Pumpkin Vine Golf Course'),
  ('United States', 'Punderson Golf Course'),
  ('United States', 'Punxsutawney Country Club'),
  ('United States', 'Purgatory Golf Club'),
  ('United States', 'Purple Hawk Country Club'),
  ('United States', 'Purple Sage Municipal Golf Course'),
  ('United States', 'Purpoodock Club'),
  ('United States', 'Putnam County Golf Course'),
  ('United States', 'Putting Green Mini Golf'),
  ('United States', 'Quaboag Country Club'),
  ('United States', 'Quail At Quail Creek Country Club'),
  ('United States', 'Quail Brook Golf Course'),
  ('United States', 'Quail Chase Golf Course'),
  ('United States', 'Quail Creek Golf Club'),
  ('United States', 'Quail Creek Golf Club Coyote Road Runner Course'),
  ('United States', 'Quail Creek Golf Club Quail Coyote Course'),
  ('United States', 'Quail Creek Golf Club Road Runner Quail Course'),
  ('United States', 'Quail Creek Golf Country Club'),
  ('United States', 'Quail Creek Golf Course'),
  ('United States', 'Quail Dunes Golf Course'),
  ('United States', 'Quail Hollow Country Club'),
  ('United States', 'Quail Hollow Golf Club'),
  ('United States', 'Quail Hollow Golf Course Championship'),
  ('United States', 'Quail Hollow Golf Course Short'),
  ('United States', 'Quail Lodge Resort Golf Club'),
  ('United States', 'Quail Meadows Golf Course'),
  ('United States', 'Quail Ridge Country Club'),
  ('United States', 'Quail Ridge Golf Club'),
  ('United States', 'Quail Ridge Golf Country Club'),
  ('United States', 'Quail Ridge Golf Course'),
  ('United States', 'Quail Ridge Golf World Executive Golf Course'),
  ('United States', 'Quail Run At Rio Verde Country Club'),
  ('United States', 'Quail Run Executive Golf Course'),
  ('United States', 'Quail Run Golf Club'),
  ('United States', 'Quail Run Golf Course'),
  ('United States', 'Quail Valley Golf Club'),
  ('United States', 'Quail Valley Golf Course'),
  ('United States', 'Quail Village Golf Club'),
  ('United States', 'Quailwood Greens Golf Course'),
  ('United States', 'Quaker Creek Golf Course'),
  ('United States', 'Quaker Hill Country Club'),
  ('United States', 'Quaker Meadows Golf Course'),
  ('United States', 'Quaker Ridge Golf Club'),
  ('United States', 'Quality Inn Suites Golf Resort'),
  ('United States', 'Quanah Country Club'),
  ('United States', 'Quarry At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Quarry Oaks Golf Course'),
  ('United States', 'Quarry Pines Golf Club'),
  ('United States', 'Quarry Ridge Golf Center'),
  ('United States', 'Quarry Ridge Golf Course'),
  ('United States', 'Quarry View Golf Course'),
  ('United States', 'Quartz Mountain Golf Course'),
  ('United States', 'Quashnet Valley Country Club'),
  ('United States', 'Queen Valley Golf Course'),
  ('United States', 'Queenfield Golf Club'),
  ('United States', 'Queens Harbour Yacht Country Club'),
  ('United States', 'Queensbury Country Club'),
  ('United States', 'Queenston Golf Club'),
  ('United States', 'Querbes Park Golf Course'),
  ('United States', 'Quicksilver Golf Club'),
  ('United States', 'Quidnessett Country Club'),
  ('United States', 'Quiet Times Golf Course'),
  ('United States', 'Quig''s Maplewood Golf Course'),
  ('United States', 'Quimby Golf Course'),
  ('United States', 'Quincy Country Club'),
  ('United States', 'Quincy Golf Course'),
  ('United States', 'Quinnatisset Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Quint Valley Golf Club'),
  ('United States', 'Quinter Golf Club'),
  ('United States', 'Quintero Golf Club'),
  ('United States', 'Quinton Oaks Golf Course'),
  ('United States', 'Quitman Country Club'),
  ('United States', 'Quixote Club'),
  ('United States', 'Quogue Field Club'),
  ('United States', 'Raber Golf Course'),
  ('United States', 'Rabun County Golf Club'),
  ('United States', 'Raccoon Creek Golf Course'),
  ('United States', 'Raccoon Hill Golf Club'),
  ('United States', 'Raccoon International'),
  ('United States', 'Raceway Golf Club'),
  ('United States', 'Racine Country Club'),
  ('United States', 'Rackham Golf Course'),
  ('United States', 'Radcliffe Friendly Fareways'),
  ('United States', 'Radisson Greens Golf Course'),
  ('United States', 'Radley Run Country Club'),
  ('United States', 'Radnor Valley Country Club'),
  ('United States', 'Radrick Farms Golf Course'),
  ('United States', 'Railside Golf Club'),
  ('United States', 'Rainbow Golf Club'),
  ('United States', 'Rainbow S End Golf Club'),
  ('United States', 'Raindance National'),
  ('United States', 'Rainier Golf Country Club'),
  ('United States', 'Raintree Country Club'),
  ('United States', 'Raintree Golf & Event Center'),
  ('United States', 'Raintree Golf Club'),
  ('United States', 'Raintree Golf Course'),
  ('United States', 'Raisin Valley Golf Club'),
  ('United States', 'Raleigh Country Club'),
  ('United States', 'Raleigh Golf Association'),
  ('United States', 'Raleigh Golf Association Stockholders Course'),
  ('United States', 'Ralph Myhre Golf Course'),
  ('United States', 'Rammler Golf Club'),
  ('United States', 'Rams Hill Golf Club'),
  ('United States', 'Ramsey Golf Country Club'),
  ('United States', 'Ramsey Lake Golf Course'),
  ('United States', 'Ranch At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Ranch At Roaring Fork Golf Course'),
  ('United States', 'Ranch At Tonto Verde Golf Club'),
  ('United States', 'Ranch Club Golf Course'),
  ('United States', 'Ranch Course At Alisal'),
  ('United States', 'Ranch Course At Genoa Lakes Golf Club'),
  ('United States', 'Ranch Golf Course At Pole Creek Golf Club'),
  ('United States', 'Rancho Bernardo Inn'),
  ('United States', 'Rancho Carlsbad Golf Club'),
  ('United States', 'Rancho Casa Blanca Country Club'),
  ('United States', 'Rancho Del Pueblo Golf Course'),
  ('United States', 'Rancho Del Rey Golf Club'),
  ('United States', 'Rancho Del Sol Golf Club'),
  ('United States', 'Rancho La Quinta Jones Course'),
  ('United States', 'Rancho La Quinta Pate Course'),
  ('United States', 'Rancho Manana Golf Club'),
  ('United States', 'Rancho Maria Golf Club'),
  ('United States', 'Rancho Mirage Country Club'),
  ('United States', 'Rancho Monserate Country Club'),
  ('United States', 'Rancho Park Golf Course'),
  ('United States', 'Rancho Park Par 3 Golf Course'),
  ('United States', 'Rancho San Joaquin Golf Course'),
  ('United States', 'Rancho San Marcos Golf Course'),
  ('United States', 'Rancho Santa Fe Golf Club'),
  ('United States', 'Rancho Sierra Golf Course'),
  ('United States', 'Rancho Solano Golf Course'),
  ('United States', 'Rancho Vista Golf Course'),
  ('United States', 'Rancocas Golf Club'),
  ('United States', 'Randall Hills Country Club'),
  ('United States', 'Randall Oaks Golf Course'),
  ('United States', 'Randolph Country Club'),
  ('United States', 'Range End Country Club'),
  ('United States', 'Range Line Golf Course'),
  ('United States', 'Raptor At Grayhawk Golf Club'),
  ('United States', 'Raquette River Golf Country Club'),
  ('United States', 'Raritan Landing Golf Course'),
  ('United States', 'Raritan Valley Country Club'),
  ('United States', 'Raspberry Falls Golf Hunt Club'),
  ('United States', 'Raspberry Ridge Golf Course'),
  ('United States', 'Raton Country Club'),
  ('United States', 'Rattle Run Golf Course'),
  ('United States', 'Rattlesnake Ridge Golf Club'),
  ('United States', 'Raven At Sandestin Golf And Beach Resort'),
  ('United States', 'Raven Golf Club At Snowshoe Mountain'),
  ('United States', 'Raven Golf Club Phoenix'),
  ('United States', 'Raven Rock Golf Course'),
  ('United States', 'Ravenna Creeks Golf Course'),
  ('United States', 'Ravens Claw Golf Club'),
  ('United States', 'Ravenwood Golf Course'),
  ('United States', 'Ravines Golf Club'),
  ('United States', 'Ravinia Green Country Club'),
  ('United States', 'Ravisloe Country Club'),
  ('United States', 'Ray Golf Association'),
  ('United States', 'Rayburn Country Resort'),
  ('United States', 'Raymond Memorial Golf Course'),
  ('United States', 'Raymond Shoal Creek Golf Course'),
  ('United States', 'Raystown Golf Resort'),
  ('United States', 'Rea Park Golf Course'),
  ('United States', 'Reading Country Club'),
  ('United States', 'Recreation Park 18 Golf Course'),
  ('United States', 'Recreation Park 9 Golf Course'),
  ('United States', 'Red Apple Inn Country Club'),
  ('United States', 'Red Arrow Golf Course'),
  ('United States', 'Red At Bethpage State Park Golf Course'),
  ('United States', 'Red At Cedarbrook Golf Course'),
  ('United States', 'Red At D Fairchild Wheeler Golf Course'),
  ('United States', 'Red At Eisenhower Park Golf Course'),
  ('United States', 'Red At Ford Hill Country Club'),
  ('United States', 'Red At Golf Club Of Avon'),
  ('United States', 'Red At Palmetto Pines Golf Course'),
  ('United States', 'Red At Tunxis Country Club'),
  ('United States', 'Red Bank Plantation'),
  ('United States', 'Red Barn Golf Course'),
  ('United States', 'Red Bird Golf Links'),
  ('United States', 'Red Blue At Edgewood Country Club'),
  ('United States', 'Red Blue At Lindenwood Golf Club'),
  ('United States', 'Red Blue At Ramblewood Country Club'),
  ('United States', 'Red Blue At Sugar Mill Country Club'),
  ('United States', 'Red Blue At Sunken Meadow State Park Golf Course'),
  ('United States', 'Red Blue At Timber Point Country Club'),
  ('United States', 'Red Blue At Westchester Golf Country Club'),
  ('United States', 'Red Blue At Woods Golf Course The'),
  ('United States', 'Red Bridge Golf And Country Club'),
  ('United States', 'Red Carpet Golf Course'),
  ('United States', 'Red Cloud Golf Course'),
  ('United States', 'Red Dog Run'),
  ('United States', 'Red Farm Golf'),
  ('United States', 'Red Fox Country Club'),
  ('United States', 'Red Fox Run'),
  ('United States', 'Red Gold At Rothland Golf Course'),
  ('United States', 'Red Gold At Valley Brook Country Club'),
  ('United States', 'Red Hawk Golf Club'),
  ('United States', 'Red Hawk Golf Course & Learning Center'),
  ('United States', 'Red Hawk Ridge'),
  ('United States', 'Red Hill Country Club'),
  ('United States', 'Red Hook Golf Club'),
  ('United States', 'Red Ledges Golf Club 12 Hole Golf Park Course'),
  ('United States', 'Red Ledges Golf Club Nicklaus Signature Course'),
  ('United States', 'Red Lodge Mountain Golf Course'),
  ('United States', 'Red Maples Golf Course'),
  ('United States', 'Red Martin Country Club'),
  ('United States', 'Red Mountain Ranch Country Club'),
  ('United States', 'Red Nine At Hyde Park Golf Course'),
  ('United States', 'Red Oak Country Club'),
  ('United States', 'Red Oaks Golf Course'),
  ('United States', 'Red Pines Golf Course'),
  ('United States', 'Red Reef Executive Golf Course'),
  ('United States', 'Red River Golf Club'),
  ('United States', 'Red Rock Country Club'),
  ('United States', 'Red Rock Golf Course'),
  ('United States', 'Red Rocks Country Club'),
  ('United States', 'Red Run Golf Club'),
  ('United States', 'Red Silver At Foxfire Country Club'),
  ('United States', 'Red Sky Golf Club Fazio Course'),
  ('United States', 'Red Sky Golf Club Norman Course'),
  ('United States', 'Red Tail Golf Club'),
  ('United States', 'Red Tail Run Golf Club'),
  ('United States', 'Red Trail Links'),
  ('United States', 'Red White At Arrowhead Golf Course'),
  ('United States', 'Red White At Buck Hill Falls Golf Club'),
  ('United States', 'Red White At Glen Oaks Club'),
  ('United States', 'Red White At Highland Lakes Golf Course'),
  ('United States', 'Red White At Little Mill Country Club'),
  ('United States', 'Red White At Myakka Pines Golf Club'),
  ('United States', 'Red White At Ringgold Golf Club'),
  ('United States', 'Red White At Rothland Golf Course'),
  ('United States', 'Red White At Shawnee Inn Golf Resort'),
  ('United States', 'Red White At Town Of Colonie Golf Course'),
  ('United States', 'Red White At Western Turnpike Golf Course'),
  ('United States', 'Red White At Woods Golf Course The'),
  ('United States', 'Red Wing Golf Club'),
  ('United States', 'Red Wing Lake Golf Course'),
  ('United States', 'Red Wolf Golf Club'),
  ('United States', 'Red Yellow At Willowbrook Golf Club'),
  ('United States', 'RedTail Golf Club'),
  ('United States', 'Redbud Crabapple At Roanoke Country Club'),
  ('United States', 'Redbud Springs Golf Club'),
  ('United States', 'Redding Country Club'),
  ('United States', 'Redfish Run At The Villages Executive Golf Trail'),
  ('United States', 'Redhawk Golf Club'),
  ('United States', 'Redhawk Golf Course'),
  ('United States', 'Redland Golf Country Club'),
  ('United States', 'Redlands Country Club'),
  ('United States', 'Redmont Country Club'),
  ('United States', 'Redstick Golf Club'),
  ('United States', 'Redstone Resort'),
  ('United States', 'Redtail Golf Club'),
  ('United States', 'Redwood Canyon Golf Course'),
  ('United States', 'Redwood Empire Golf Country Club'),
  ('United States', 'Redwood Falls Golf Club'),
  ('United States', 'Reedsburg Country Club'),
  ('United States', 'Reedy Creek Golf Course'),
  ('United States', 'Reedy Meadow Golf Course'),
  ('United States', 'Reems Creek Golf Course'),
  ('United States', 'Reeves Golf Course'),
  ('United States', 'Reflection Bay Golf Club'),
  ('United States', 'Reflection Ridge Golf Club'),
  ('United States', 'Regatta Bay Golf Yacht Club'),
  ('United States', 'Regency At Dominion Valley Country Club'),
  ('United States', 'Regency At Monroe Golf And Country Club'),
  ('United States', 'Regents Glen Country Club'),
  ('United States', 'Regulation At Borland Golf Center'),
  ('United States', 'Regulation At Jackson Park Golf Course'),
  ('United States', 'Regulation At Jefferson Park Golf Club'),
  ('United States', 'Regulation At Las Positas Golf Course'),
  ('United States', 'Regulation At Marine Memorial Golf Course'),
  ('United States', 'Regulation At Mick Riley Golf Course'),
  ('United States', 'Regulation At Pleasant Valley Country Club'),
  ('United States', 'Regulation Eighteen At Smithtown Landing Golf Club'),
  ('United States', 'Regulation Nine At Cherokee Ridge Golf Course'),
  ('United States', 'Rehoboth Beach Country Club'),
  ('United States', 'Rehoboth Country Club'),
  ('United States', 'Reid Municipal Golf Course'),
  ('United States', 'Reidy Creek Golf Course'),
  ('United States', 'Remington Golf Club'),
  ('United States', 'Remsen Golf Course'),
  ('United States', 'Remuda Golf Course'),
  ('United States', 'Renaissance Golf Club'),
  ('United States', 'Renaissance Golf Course'),
  ('United States', 'Renaissance Vinoy Resort'),
  ('United States', 'Rendezvous Meadows Golf Course'),
  ('United States', 'Renegade Course At Desert Mountain Golf Club'),
  ('United States', 'Renwood Golf Course'),
  ('United States', 'Republic Golf Course Club'),
  ('United States', 'Reservation Golf Club'),
  ('United States', 'Reserve Club At St James Plantation'),
  ('United States', 'Reserve Run Golf Course'),
  ('United States', 'Reservoir Creek Golf Course'),
  ('United States', 'Resort At Tahquitz Creek Golf Resort'),
  ('United States', 'Reston National Golf Course'),
  ('United States', 'Retreat At Sea Island Golf Club'),
  ('United States', 'Reunion Country Club'),
  ('United States', 'Reunion Golf Country Club'),
  ('United States', 'Reunion Resort Nicklaus Course'),
  ('United States', 'Reunion Resort Palmer Course'),
  ('United States', 'Reunion Resort Watson Course'),
  ('United States', 'Revere Golf Club Concord Course'),
  ('United States', 'Revere Golf Club Lexington Course'),
  ('United States', 'Reynolds Golf Course'),
  ('United States', 'Reynolds Lake Oconee Great Waters'),
  ('United States', 'Reynolds Lake Oconee Richland Course'),
  ('United States', 'Reynolds Lake Oconee The Creek Club'),
  ('United States', 'Reynolds Lake Oconee The Landing'),
  ('United States', 'Reynolds Lake Oconee The National'),
  ('United States', 'Reynolds Lake Oconee The Oconee'),
  ('United States', 'Reynolds Lake Oconee The Preserve Course'),
  ('United States', 'Reynolds Park Golf Course'),
  ('United States', 'Rhinelander Country Club'),
  ('United States', 'Rhode Island Country Club'),
  ('United States', 'Rhodes Ranch Country Club'),
  ('United States', 'Rib Mountain Golf Course'),
  ('United States', 'Rice Lake Golf and Country Club'),
  ('United States', 'Riceville Country Club'),
  ('United States', 'Rich Harvest Farms Golf Course'),
  ('United States', 'Rich Maiden Golf Course'),
  ('United States', 'Rich Valley Golf Course'),
  ('United States', 'Richford Country Club'),
  ('United States', 'Richland Country Club'),
  ('United States', 'Richland Greens Golf Center'),
  ('United States', 'Richmond Country Club'),
  ('United States', 'Richmond County Country Club'),
  ('United States', 'Richmond Hill Golf Club'),
  ('United States', 'Richmond Pitch And Putt At The Villages Executive Golf Trail'),
  ('United States', 'Richter Park Golf Course'),
  ('United States', 'Ridder Farm Golf Country Club'),
  ('United States', 'Ridge At Mulligans South'),
  ('United States', 'Ridge Canyon At La Paloma Country Club'),
  ('United States', 'Ridge Club'),
  ('United States', 'Ridge Country Club'),
  ('United States', 'Ridge Creek Dinuba Golf Club'),
  ('United States', 'Ridge Golf Club'),
  ('United States', 'Ridge Golf Course'),
  ('United States', 'Ridge Golf Course At Pole Creek Golf Club'),
  ('United States', 'Ridge Manor Oaks Golf Country Club'),
  ('United States', 'Ridge Stone Golf Club'),
  ('United States', 'Ridge Trail At Blue Ridge Trail Golf Club'),
  ('United States', 'Ridge top golf course'),
  ('United States', 'Ridgecrest Country Club'),
  ('United States', 'Ridgefield Golf Course'),
  ('United States', 'Ridgefields Country Club'),
  ('United States', 'Ridgemark Golf Country Club'),
  ('United States', 'Ridgemont Country Club'),
  ('United States', 'Ridgemoor Country Club'),
  ('United States', 'Ridgepointe Country Club'),
  ('United States', 'Ridges at Sand Creek'),
  ('United States', 'Ridgeview Country Club'),
  ('United States', 'Ridgeview Golf Course'),
  ('United States', 'Ridgeway Country Club'),
  ('United States', 'Ridgeway Shores Golf Club'),
  ('United States', 'Ridgewood Country Club'),
  ('United States', 'Ridgewood Golf Course'),
  ('United States', 'Riegelwood Country Club'),
  ('United States', 'Rifle Creek Golf Course'),
  ('United States', 'Rifle River Golf Course'),
  ('United States', 'Riley Grove Course At Palmer Legends'),
  ('United States', 'Rio Bend Golf Course'),
  ('United States', 'Rio Bravo Country Club'),
  ('United States', 'Rio Grande Club'),
  ('United States', 'Rio Hondo Golf Club'),
  ('United States', 'Rio Mimbres Country Club'),
  ('United States', 'Rio Pinar Golf'),
  ('United States', 'Rio Vista Golf Club'),
  ('United States', 'Rio Vista Golf Course'),
  ('United States', 'Riomar Country Club'),
  ('United States', 'Rip Arnold At Cherry Hills Country Club'),
  ('United States', 'Rip Van Winkle Country Club'),
  ('United States', 'Ripon Golf Club'),
  ('United States', 'Rippling Rapids Golf Club'),
  ('United States', 'Rising Sun Golf Course At Mountain Sky Guest Ranch'),
  ('United States', 'Rittswood Golf Club'),
  ('United States', 'Ritz Carlton Members Golf Club'),
  ('United States', 'Ritzville Municipal Golf'),
  ('United States', 'Rivard Golf Country Club'),
  ('United States', 'River At Indian Springs Country Club'),
  ('United States', 'River Bank Golf Course'),
  ('United States', 'River Bend Country Club'),
  ('United States', 'River Bend Golf Club'),
  ('United States', 'River Bend Golf Club North Course'),
  ('United States', 'River Bend Golf Club South Course'),
  ('United States', 'River Bend Golf Country Club'),
  ('United States', 'River Bend Golf Course'),
  ('United States', 'River Bend Links'),
  ('United States', 'River Bend Municipal Golf Course'),
  ('United States', 'River Bend Ymca Golf Course'),
  ('United States', 'River Birch Golf Club'),
  ('United States', 'River Birch Golf Course'),
  ('United States', 'River Club'),
  ('United States', 'River Club of Mequon'),
  ('United States', 'River Course At Alisal'),
  ('United States', 'River Course At Fiddlers Elbow Country Club'),
  ('United States', 'River Creek Club'),
  ('United States', 'River Creek Golf Course'),
  ('United States', 'River Creek Park Golf Course'),
  ('United States', 'River Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'River Edge Golf Course'),
  ('United States', 'River Falls Golf Club'),
  ('United States', 'River Falls Plantation'),
  ('United States', 'River Forest Country Club'),
  ('United States', 'River Forest Golf Course'),
  ('United States', 'River Glen Country Club'),
  ('United States', 'River Golf Country Club The'),
  ('United States', 'River Greens Golf Course'),
  ('United States', 'River Hall Country Club'),
  ('United States', 'River Heights Golf Course'),
  ('United States', 'River Hills Country Club'),
  ('United States', 'River Hills Golf Country Club'),
  ('United States', 'River Island Country Club'),
  ('United States', 'River Island Golf Course'),
  ('United States', 'River Isles Golf Course'),
  ('United States', 'River Lake At Woodbridge Golf Country Club'),
  ('United States', 'River Lakes Course At Pelican Sound Golf River Club'),
  ('United States', 'River Lakes Golf Course'),
  ('United States', 'River Landing At Sandy Ridge'),
  ('United States', 'River Landing Landing Course'),
  ('United States', 'River Landing River Course'),
  ('United States', 'River Marsh Golf Club Hyatt Chesapeake Bay'),
  ('United States', 'River Middle At Woodbridge Golf Country Club'),
  ('United States', 'River Oak At Del Rio Country Club'),
  ('United States', 'River Oaks Golf Club'),
  ('United States', 'River Oaks Golf Course'),
  ('United States', 'River Park Golf Course'),
  ('United States', 'River Pointe Golf Club'),
  ('United States', 'River Ridge At Harbour Ridge Yacht Country Club'),
  ('United States', 'River Ridge Golf Club'),
  ('United States', 'River Ridge Golf Club The Victoria Lakes Course'),
  ('United States', 'River Ridge Golf Club The Vineyard Course'),
  ('United States', 'River Ridge Golf Course'),
  ('United States', 'River Road Golf Club'),
  ('United States', 'River Run Golf Country Club'),
  ('United States', 'River Run Golf Course'),
  ('United States', 'River Run Golf Links'),
  ('United States', 'River Run Ii Golf Links'),
  ('United States', 'River Tasalmi Golf Course'),
  ('United States', 'River Trace Golf At Mac'),
  ('United States', 'River Vale Country Club'),
  ('United States', 'River Valley Country Club'),
  ('United States', 'River Valley Golf Course'),
  ('United States', 'River Valley Ranch Golf Club'),
  ('United States', 'River View Club'),
  ('United States', 'River View Golf Course'),
  ('United States', 'River Wilds Golf Club'),
  ('United States', 'River''s Edge Golf Club'),
  ('United States', 'Riverbend Golf Club'),
  ('United States', 'Riverbend Golf Course'),
  ('United States', 'Rivercliff Golf Course'),
  ('United States', 'Riverdale Country Club'),
  ('United States', 'Riverdale Dunes'),
  ('United States', 'Riverdale Knolls'),
  ('United States', 'Riverfront Golf Club'),
  ('United States', 'Riveria Country Club Golf Course'),
  ('United States', 'Riverland Country Club'),
  ('United States', 'Riverlands Golf Country Club'),
  ('United States', 'Rivermeadow Golf Club'),
  ('United States', 'Rivermont Golf Country Club'),
  ('United States', 'Rivermoor Golf Club'),
  ('United States', 'Riverpines Golf Course'),
  ('United States', 'Riverpines Golf Course Par 3 Course'),
  ('United States', 'Rivers Bend Golf Club'),
  ('United States', 'Rivers Bend Golf Course'),
  ('United States', 'Rivers Edge Golf Club'),
  ('United States', 'Rivers Edge Golf Club At Burley'),
  ('United States', 'Rivers Edge Golf Course')
on conflict (country, name) do nothing;
