insert into public.golf_courses (country, name) values
  ('United States', 'Victoria National Golf Club'),
  ('United States', 'Victors Par 3 Golf Course'),
  ('United States', 'Victory Hills Golf Course'),
  ('United States', 'Victory Lake Golf Course'),
  ('United States', 'Victory Links Golf Course'),
  ('United States', 'Victory Ranch Golf Club'),
  ('United States', 'Vienna Greens Country Club'),
  ('United States', 'Viera East Golf Club'),
  ('United States', 'Viking Golf Course'),
  ('United States', 'Viking Meadows Golf Club'),
  ('United States', 'Villa Olivia Country Club'),
  ('United States', 'Villa Roma Golf Course'),
  ('United States', 'Village At Jupiter Hills Club'),
  ('United States', 'Village Club Of Sands Point'),
  ('United States', 'Village Creek Golf Club'),
  ('United States', 'Village Golf Course'),
  ('United States', 'Village Green Country Club'),
  ('United States', 'Village Green Golf Club'),
  ('United States', 'Village Green Golf Course'),
  ('United States', 'Village Greens Golf Country Club'),
  ('United States', 'Village Greens Golf Course'),
  ('United States', 'Village Greens of Woodridge'),
  ('United States', 'Village Links Golf Club'),
  ('United States', 'Villages At Country Creek The'),
  ('United States', 'Villas Crossing Golf Course'),
  ('United States', 'Ville Platte Golf Country Club'),
  ('United States', 'Vinces Sport Center Par 3 Golf Course'),
  ('United States', 'Vineland Golf Course'),
  ('United States', 'Vineyard Golf At White Lake'),
  ('United States', 'Vineyard Golf Club'),
  ('United States', 'Vineyard Golf Course'),
  ('United States', 'Vineyard Greens Golf Course'),
  ('United States', 'Vineyard Knolls Golf Club'),
  ('United States', 'Vineyard National Golf Course'),
  ('United States', 'Vineyard Valley Golf Club'),
  ('United States', 'Vintage At White Deer Golf Club'),
  ('United States', 'Vintners Golf Club'),
  ('United States', 'Vinton Country Club'),
  ('United States', 'Virginia Amelia At Mallory Hill Golf Course'),
  ('United States', 'Virginia Beach National Golf Club'),
  ('United States', 'Virginia Country Club'),
  ('United States', 'Virginia Golf Center'),
  ('United States', 'Virginia Golf Course'),
  ('United States', 'Virginia Tech Golf Course'),
  ('United States', 'Viroqua Hills Golf Course'),
  ('United States', 'Visalia Country Club'),
  ('United States', 'Vista Golf Course'),
  ('United States', 'Vista Lake At Los Coyotes Country Club'),
  ('United States', 'Vista Plantation Golf Course'),
  ('United States', 'Volcano Golf Country Club'),
  ('United States', 'Volusia At The Villages Executive Golf Trail'),
  ('United States', 'Voyager Rv Resort And Golf Course'),
  ('United States', 'Voyager Village'),
  ('United States', 'Voyager Village Par 3'),
  ('United States', 'Wa Noa Golf Club'),
  ('United States', 'Waabooz Run Golf Course'),
  ('United States', 'Wabaunsee Pines Golf Course'),
  ('United States', 'Wabeek Country Club'),
  ('United States', 'Waccabuc Country Club'),
  ('United States', 'Wachesaw East Golf Club'),
  ('United States', 'Wachesaw Plantation Club'),
  ('United States', 'Wachusett Country Club'),
  ('United States', 'Wade Hampton Golf Course'),
  ('United States', 'Wagon Trail To Lonesome Pine Golf Course'),
  ('United States', 'Wahconah Country Club'),
  ('United States', 'Wahkonsa Country Club'),
  ('United States', 'Waialae Country Club'),
  ('United States', 'Waiehu Golf Course'),
  ('United States', 'Waikele Country Club'),
  ('United States', 'Waikoloa Beach Resort Beach Course'),
  ('United States', 'Waikoloa Beach Resort Kings Lakes Course'),
  ('United States', 'Wailea Golf Club Emerald Course'),
  ('United States', 'Wailea Golf Club Gold Course'),
  ('United States', 'Wailea Golf Club Old Blue Course'),
  ('United States', 'Wailua Municipal Golf Course'),
  ('United States', 'Wakonda Club'),
  ('United States', 'Wakulla Sands Golf Club'),
  ('United States', 'Walden Oaks Country Club'),
  ('United States', 'Walden Ponds Golf Club'),
  ('United States', 'Waldorf Astoria Golf Club'),
  ('United States', 'Waldron Country Club'),
  ('United States', 'Walker Creek Golf Course'),
  ('United States', 'Walking Stick Golf Course'),
  ('United States', 'Walla Walla Country Club'),
  ('United States', 'Wallingford Country Club'),
  ('United States', 'Wallinwood Springs Golf Club'),
  ('United States', 'Wallkill Golf Club'),
  ('United States', 'Walloon Lake Country Club'),
  ('United States', 'Walnut Creek Country Club'),
  ('United States', 'Walnut Creek Golf Club'),
  ('United States', 'Walnut Creek Golf Preserve'),
  ('United States', 'Walnut Greens Golf Course'),
  ('United States', 'Walnut Grove At The Villages Executive Golf Trail'),
  ('United States', 'Walnut Grove Golf Course'),
  ('United States', 'Walnut Lake Country Club'),
  ('United States', 'Walnut Lane Golf Club'),
  ('United States', 'Walnut Ridge Golf Country Club'),
  ('United States', 'Walpole Country Club'),
  ('United States', 'Walsenburg Golf Course'),
  ('United States', 'Walsh Golf Center'),
  ('United States', 'Walter E Hall Memorial Golf Course'),
  ('United States', 'Walter J Nagorski Golf Course'),
  ('United States', 'Walter Sellers Memorial Country Club'),
  ('United States', 'Walther''s Golf Driving Range'),
  ('United States', 'Walton Golf Club'),
  ('United States', 'Waltz Golf Farm'),
  ('United States', 'Wamego Country Club'),
  ('United States', 'Wampanoag Country Club'),
  ('United States', 'Wampanoag Golf Course'),
  ('United States', 'Wampatuck Country Club'),
  ('United States', 'Wanakah Country Club'),
  ('United States', 'Wanaki Golf Course'),
  ('United States', 'Wanamaker Course At Pga Golf Club'),
  ('United States', 'Wanango Country Club'),
  ('United States', 'Wander Springs Golf Course'),
  ('United States', 'Wandering Creek Golf Course'),
  ('United States', 'Wandermere Golf Course'),
  ('United States', 'Wanee Lake Country Club'),
  ('United States', 'Wannamoisett Country Club'),
  ('United States', 'Wanumetonomy Golf Country Club'),
  ('United States', 'Wapicada Golf Club'),
  ('United States', 'Wapsi Oaks Country Club'),
  ('United States', 'Wapsie Ridge Golf Course'),
  ('United States', 'Wapsipinicon Country Club'),
  ('United States', 'Ware Shoals Golf Course'),
  ('United States', 'Warfield Greens Golf Club'),
  ('United States', 'Warm Springs Golf Course'),
  ('United States', 'Warminsters Five Ponds Golf Club'),
  ('United States', 'Warner Springs Ranch'),
  ('United States', 'Warnimont Park Golf Course'),
  ('United States', 'Warren Country Club'),
  ('United States', 'Warren Golf Course'),
  ('United States', 'Warren Swigart 9-Hole Golf Course'),
  ('United States', 'Warren Valley Golf Course'),
  ('United States', 'Warrenbrook Golf Course'),
  ('United States', 'Warrenton Golf Course'),
  ('United States', 'Warrior Golf Club'),
  ('United States', 'Warrior Hills Golf Course'),
  ('United States', 'Warrior Run Golf Course'),
  ('United States', 'Warriors Path State Park Golf Course'),
  ('United States', 'Warroad Estates Golf Course'),
  ('United States', 'Warwick Country Club'),
  ('United States', 'Warwick Hills Golf & Country Club'),
  ('United States', 'Warwick Valley Country Club'),
  ('United States', 'Washakie Golf and RV Resort'),
  ('United States', 'Washington Country Club'),
  ('United States', 'Washington County Golf Country Club'),
  ('United States', 'Washington County Golf Course'),
  ('United States', 'Washington Golf Club'),
  ('United States', 'Washington Golf Country Club'),
  ('United States', 'Washington Golf Learning Center'),
  ('United States', 'Washington National Golf Club'),
  ('United States', 'Washington Park Golf Course'),
  ('United States', 'Washington Park Municipal Golf Course'),
  ('United States', 'Washington Township Municipal Golf Course'),
  ('United States', 'Washington Wilkes Country Club'),
  ('United States', 'Washington Yacht Country Club'),
  ('United States', 'Washoe Golf Course'),
  ('United States', 'Washtenaw Golf Club'),
  ('United States', 'Wasioto Winds At Pine Mountain State Park Golf Course'),
  ('United States', 'Waskada Golf Club'),
  ('United States', 'Watchung Valley Golf Club'),
  ('United States', 'Water Oak Golf Club'),
  ('United States', 'Water''s Edge Golf Club'),
  ('United States', 'Waterfall Golf Club'),
  ('United States', 'Waterford Golf Club'),
  ('United States', 'Waterlefe Golf River Club'),
  ('United States', 'Waterloo Country Club'),
  ('United States', 'Waterloo Golf Course'),
  ('United States', 'Watermark Country Club'),
  ('United States', 'Waters Edge Gold Course'),
  ('United States', 'Waters Edge Golf Course'),
  ('United States', 'Waters Mounds At Brickyard Plantation Golf Club'),
  ('United States', 'Watertown Coutry Club'),
  ('United States', 'Watertown Golf Club'),
  ('United States', 'Waterville Community Golf Association'),
  ('United States', 'Waterville Country Club'),
  ('United States', 'Waterville Valley Golf Club'),
  ('United States', 'Waterways Golf Resort East Course'),
  ('United States', 'Waterways Golf Resort West Course'),
  ('United States', 'Watkins Glen Golf Club'),
  ('United States', 'Watonga Golf Club'),
  ('United States', 'Waubeeka Golf Links'),
  ('United States', 'Waukewan Golf Club'),
  ('United States', 'Waukon Golf and Country Club'),
  ('United States', 'Waumbek Golf Club'),
  ('United States', 'Waupaca Country Club'),
  ('United States', 'Wausau Country Club'),
  ('United States', 'Wausaukee Club'),
  ('United States', 'Waushara Country Club'),
  ('United States', 'Waveland Golf Course'),
  ('United States', 'Waverly Municipal Golf Course'),
  ('United States', 'Waverly Oaks Golf Club'),
  ('United States', 'Wawasee Golf Club'),
  ('United States', 'Wawashkamo Golf Course'),
  ('United States', 'Wawenock Golf Club'),
  ('United States', 'Wawona Golf Course'),
  ('United States', 'Wawonowin Golf Course'),
  ('United States', 'Wayland Country Club'),
  ('United States', 'Wayne Hills Country Club'),
  ('United States', 'Waynesboro Country Club'),
  ('United States', 'Waynesboro Par 3 Golf Course'),
  ('United States', 'Waynesborough Country Club'),
  ('United States', 'Waynesville Inn Golf Club'),
  ('United States', 'Wayton Hill''s Golf Course'),
  ('United States', 'Wayzata Country Club'),
  ('United States', 'Weathervane Golf Club'),
  ('United States', 'WeaverRidge Golf Club'),
  ('United States', 'Webb Park Golf Course'),
  ('United States', 'Webbs Reserve Golf Club'),
  ('United States', 'Weber Park Golf Course'),
  ('United States', 'Webhannet Golf Club'),
  ('United States', 'Webster City Country Club'),
  ('United States', 'Weddington Golf And Tennis'),
  ('United States', 'Wedgefield Country Club'),
  ('United States', 'Wedgefield Golf Club'),
  ('United States', 'Wedgewood'),
  ('United States', 'Wedgewood Cove Golf Club'),
  ('United States', 'Wedgewood Golf & Country Club'),
  ('United States', 'Wedgewood Golf Club'),
  ('United States', 'Wedgewood Golf Club Maple Course'),
  ('United States', 'Wedgewood Golf Club Oak Course'),
  ('United States', 'Wedgewood Golf Club Pine Course'),
  ('United States', 'Wedgewood Golf Course'),
  ('United States', 'Wedgewood Par 3 Golf Course'),
  ('United States', 'Wedgewood Pines Country Club'),
  ('United States', 'Wedgwood Country Club'),
  ('United States', 'Wee Burn Country Club'),
  ('United States', 'Wee Nip At Grand Geneva Resort Spa'),
  ('United States', 'Weed Golf Club'),
  ('United States', 'Weekapaug Golf Club'),
  ('United States', 'Weeping Trout Sports Resort'),
  ('United States', 'Weequahic Park Golf Course'),
  ('United States', 'Weibring Golf Club'),
  ('United States', 'Weissinger Hills Golf Course'),
  ('United States', 'Wekiva Golf Club'),
  ('United States', 'Welk Resort San Diego Fountains Executive Course'),
  ('United States', 'Welk Resort San Diego Oaks Course'),
  ('United States', 'Wellen Park Golf Country Club'),
  ('United States', 'Wellesley Country Club'),
  ('United States', 'Wellesley Island State Park Golf Course'),
  ('United States', 'Wellington Country Club'),
  ('United States', 'Wellington Golf Club'),
  ('United States', 'Wellington Greens Golf Course'),
  ('United States', 'Wellington National Golf Club'),
  ('United States', 'Wellman Golf Club'),
  ('United States', 'Wellman Golf Course'),
  ('United States', 'Wells College Golf Course'),
  ('United States', 'Wells Golf Course'),
  ('United States', 'Wellshire Golf Course'),
  ('United States', 'Wellsville Country Club'),
  ('United States', 'Wemberly Hills Golf Course'),
  ('United States', 'Wenatchee Golf Country Club'),
  ('United States', 'Wendell Coffee Golf Center'),
  ('United States', 'Wendell Country Club'),
  ('United States', 'Wenham Country Club'),
  ('United States', 'Wentworth By The Sea Country Club'),
  ('United States', 'Wentworth Golf Club'),
  ('United States', 'Wentworth Hills Golf Country Club Semi Private'),
  ('United States', 'Wequetonsing Golf Club'),
  ('United States', 'Wesburn Golf Club'),
  ('United States', 'West Appleton Country Club'),
  ('United States', 'West At Belfair Golf Club'),
  ('United States', 'West At Broadmoor Golf Club'),
  ('United States', 'West At Bull Creek Golf Course'),
  ('United States', 'West At Churchville Park Golf Course'),
  ('United States', 'West At Country Club Of Hershey'),
  ('United States', 'West At Eagle Valley Golf Course'),
  ('United States', 'West At Fountains Country Club'),
  ('United States', 'West At Glendoveer Golf Course'),
  ('United States', 'West At Grandover Resort'),
  ('United States', 'West At Imperial Golf Club'),
  ('United States', 'West At Jacaranda Golf Club'),
  ('United States', 'West At Johns Island Club'),
  ('United States', 'West At Laurel Oak Country Club'),
  ('United States', 'West At Lincoln Park Golf Course'),
  ('United States', 'West At Maidstone Club'),
  ('United States', 'West At Malone Golf Club'),
  ('United States', 'West At Merion Golf Club'),
  ('United States', 'West At Mohawk Golf Club'),
  ('United States', 'West At Oak Hill Country Club'),
  ('United States', 'West At Oak Tree Country Club'),
  ('United States', 'West At Orangebrook Country Club'),
  ('United States', 'West At Rogues Roost Golf Country Club'),
  ('United States', 'West At Tamarack Golf Course'),
  ('United States', 'West At Westchester Country Club'),
  ('United States', 'West At Windyke Country Club'),
  ('United States', 'West At Winged Foot Golf Club'),
  ('United States', 'West At Wycliffe Country Club'),
  ('United States', 'West Bay Golf Club'),
  ('United States', 'West Bend Country Club'),
  ('United States', 'West Bend Golf and Country Club'),
  ('United States', 'West Bend Lakes'),
  ('United States', 'West Bend Lakes Golf Club'),
  ('United States', 'West Bolton Golf Club'),
  ('United States', 'West Branch Country Club'),
  ('United States', 'West Bridgewater Country Club'),
  ('United States', 'West Chase Golf Club'),
  ('United States', 'West Chester Golf Country Club'),
  ('United States', 'West Course At Belleair Country Club'),
  ('United States', 'West East At Ridgewood Country Club The'),
  ('United States', 'West End Golf Course'),
  ('United States', 'West Grand Golf'),
  ('United States', 'West Hill Country Club'),
  ('United States', 'West Hills Country Club'),
  ('United States', 'West Hills Country Club River Course'),
  ('United States', 'West Hills Par 3'),
  ('United States', 'West Lafayette Golf Club'),
  ('United States', 'West Lake Country Club'),
  ('United States', 'West Liberty Country Club'),
  ('United States', 'West Loch Municipal Golf Course'),
  ('United States', 'West Nine At Firethorn'),
  ('United States', 'West Nine At Southern Hills Country Club'),
  ('United States', 'West North At Cedar Knoll Country Club'),
  ('United States', 'West North At Elmridge Golf Club'),
  ('United States', 'West North At Krendale Golf Course'),
  ('United States', 'West North At Rolling Acres Golf Course'),
  ('United States', 'West Orange Country Club'),
  ('United States', 'West Ottawa Golf Course'),
  ('United States', 'West Pines Golf Club'),
  ('United States', 'West Plains Country Club'),
  ('United States', 'West Point Country Club'),
  ('United States', 'West Point Golf Course'),
  ('United States', 'West Public At Drumlins Golf Club'),
  ('United States', 'West Richland Municipal Golf'),
  ('United States', 'West Sayville Golf Course'),
  ('United States', 'West Seattle Golf Club'),
  ('United States', 'West Shore Country Club'),
  ('United States', 'West Shore Golf & Country Club'),
  ('United States', 'West Side Golf Club'),
  ('United States', 'West South At Cedar Knoll Country Club'),
  ('United States', 'West South At Fernandina Beach Golf Club'),
  ('United States', 'West South At South Hills Golf Club'),
  ('United States', 'West Warwick Country Club'),
  ('United States', 'Westborough Country Club'),
  ('United States', 'Westborough County Club'),
  ('United States', 'Westbrook Country Club'),
  ('United States', 'Westbrook Golf Club Lakes Course'),
  ('United States', 'Westbrook Golf Club Vistas Course'),
  ('United States', 'Westbrook Hills Golf Course'),
  ('United States', 'Westchase Golf Club'),
  ('United States', 'Westchester Golf Course'),
  ('United States', 'Westchester Hills Golf Club'),
  ('United States', 'Westdrift Manhattan Beach Golf Club'),
  ('United States', 'Western Acres Golf Course'),
  ('United States', 'Western Golf and Country Club'),
  ('United States', 'Western Greens Country Club'),
  ('United States', 'Western Hills Country Club'),
  ('United States', 'Western Hills Golf Club'),
  ('United States', 'Western Hills Golf Country Club'),
  ('United States', 'Western Hills Golf Course'),
  ('United States', 'Western Lakes Golf Course'),
  ('United States', 'Western Skies Golf Club'),
  ('United States', 'Western View Golf Club'),
  ('United States', 'Westerville Golf Center'),
  ('United States', 'Westfield Country Club'),
  ('United States', 'Westfield Golf Club'),
  ('United States', 'Westfields Golf Club'),
  ('United States', 'Westgate River Ranch Resort'),
  ('United States', 'Westhampton Country Club'),
  ('United States', 'Westhaven Golf Club'),
  ('United States', 'Westin Rancho Mirage Golf Resort Spa Pete Dye Resort Course'),
  ('United States', 'Westlake Country Club'),
  ('United States', 'Westlake Golf And Country Club'),
  ('United States', 'Westlake Golf Country Club'),
  ('United States', 'Westlake Golf Course'),
  ('United States', 'Westminster Country Club'),
  ('United States', 'Westminster National Golf Course'),
  ('United States', 'Westmoor Country Club'),
  ('United States', 'Westmoreland Country Club'),
  ('United States', 'Westmoreland Golf Club'),
  ('United States', 'Weston Golf Club'),
  ('United States', 'Weston Hills Country Club Players Course'),
  ('United States', 'Weston Hills Country Club Tour Course'),
  ('United States', 'Westover Golf Club'),
  ('United States', 'Westport Country Club The'),
  ('United States', 'Westport Golf Course'),
  ('United States', 'Westport Longshore Golf Club'),
  ('United States', 'Westridge Golf Club'),
  ('United States', 'Westvale Golf Course'),
  ('United States', 'Westview Golf Course'),
  ('United States', 'Westwind Golf Course'),
  ('United States', 'Westwind Rv Golf Resort'),
  ('United States', 'Westwood Country Club'),
  ('United States', 'Westwood Golf Club'),
  ('United States', 'Westwood Golf Course'),
  ('United States', 'Westwood Golf Course (9-hole)'),
  ('United States', 'Westwood Hills Country Club'),
  ('United States', 'Westwood Park Golf Course'),
  ('United States', 'Westwood West Golf Course'),
  ('United States', 'Westwoods Golf Club'),
  ('United States', 'Westwynd Golf Course'),
  ('United States', 'Wetherington Golf & Country Club'),
  ('United States', 'Wethersfield Country Club'),
  ('United States', 'Wetumka Golf Club'),
  ('United States', 'Wexford Golf'),
  ('United States', 'Weyhill At Saucon Valley Country Club'),
  ('United States', 'Weymont Run Country Club'),
  ('United States', 'Whaling City Golf Course At New Bedford'),
  ('United States', 'Wheatfield Valley Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Wheatland Golf Club'),
  ('United States', 'Wheatley Hills Golf Club'),
  ('United States', 'Wheeler Family Traditions Golf Club'),
  ('United States', 'Wheeling Country Club'),
  ('United States', 'Wheeling Country Club Golf Course'),
  ('United States', 'Wheeling Park Golf Course'),
  ('United States', 'Wheeling Park Minature Golf'),
  ('United States', 'Whidbey Golf Club'),
  ('United States', 'Whip Poor Will Golf Course'),
  ('United States', 'Whippoorwill Club'),
  ('United States', 'Whirlpool Golf Course'),
  ('United States', 'Whirlwind Golf Club The Cattail Course'),
  ('United States', 'Whirlwind Golf Club The Devils Claw Course'),
  ('United States', 'Whiskey Creek Country Club'),
  ('United States', 'Whisky Run Golf Club Fox'),
  ('United States', 'Whisper Creek Country Club'),
  ('United States', 'Whisper Lake Country Club'),
  ('United States', 'Whisper Rock Golf Club Lower Course'),
  ('United States', 'Whisper Rock Golf Club Upper Course'),
  ('United States', 'Whispering Creek Golf Club'),
  ('United States', 'Whispering Creek Golf Course'),
  ('United States', 'Whispering Firs Golf Club'),
  ('United States', 'Whispering Hills Golf Course'),
  ('United States', 'Whispering Lakes Golf Course'),
  ('United States', 'Whispering Meadows Golf Course'),
  ('United States', 'Whispering Oak At Verandah'),
  ('United States', 'Whispering Oaks Golf Club'),
  ('United States', 'Whispering Pines Golf Club'),
  ('United States', 'Whispering Pines Golf Course'),
  ('United States', 'Whispering Springs Golf Club'),
  ('United States', 'Whispering Willows Golf Course'),
  ('United States', 'Whispering Winds Golf Club'),
  ('United States', 'Whispering Woods Golf Club'),
  ('United States', 'Whispering Woods Golf Course'),
  ('United States', 'Whistling Straits'),
  ('United States', 'White At Eisenhower Park Golf Course'),
  ('United States', 'White At Ford Hill Country Club'),
  ('United States', 'White At Golf Club Of Avon'),
  ('United States', 'White At Penn State Golf Courses'),
  ('United States', 'White At Tunxis Country Club'),
  ('United States', 'White Barn Estates'),
  ('United States', 'White Bear Yacht Club'),
  ('United States', 'White Beeches Golf Country Club'),
  ('United States', 'White Birch Golf Course'),
  ('United States', 'White Birch Hills Golf Course'),
  ('United States', 'White Birches Country Club'),
  ('United States', 'White Blue At Buck Hill Falls Golf Club'),
  ('United States', 'White Blue At Glen Oaks Club'),
  ('United States', 'White Blue At Highland Lakes Golf Course'),
  ('United States', 'White Blue At Little Mill Country Club'),
  ('United States', 'White Blue At Myakka Pines Golf Club'),
  ('United States', 'White Blue At Ramblewood Country Club'),
  ('United States', 'White Blue At Shawnee Inn Golf Resort'),
  ('United States', 'White Blue At Shenandoah Valley Golf Club'),
  ('United States', 'White Blue At Town Of Colonie Golf Course'),
  ('United States', 'White Blue At Western Turnpike Golf Course'),
  ('United States', 'White Clay Creek Country Club At Delaware Park'),
  ('United States', 'White Cliffs Country Club'),
  ('United States', 'White Clouds At Sun Valley Resort'),
  ('United States', 'White Columns Golf Club'),
  ('United States', 'White Deer Country Club'),
  ('United States', 'White Deer Run Golf Club'),
  ('United States', 'White Eagle Golf Club'),
  ('United States', 'White Gold At Wyndemere Country Club'),
  ('United States', 'White Hawk Country Club'),
  ('United States', 'White Heron Golf Club'),
  ('United States', 'White Horse Golf Club'),
  ('United States', 'White Lake Golf Club'),
  ('United States', 'White Lake Oaks Golf Course'),
  ('United States', 'White Lick Golf Course'),
  ('United States', 'White Manor Country Club'),
  ('United States', 'White Mountain Country Club'),
  ('United States', 'White Mountain Golf Course Desert Nine'),
  ('United States', 'White Mountain Golf Course Lakes Nine'),
  ('United States', 'White Mountain Golf Course Sands Nine'),
  ('United States', 'White Mountain Golf Park'),
  ('United States', 'White Nine At Hyde Park Golf Course'),
  ('United States', 'White Oak Golf Course'),
  ('United States', 'White Oak Plantation'),
  ('United States', 'White Oaks Country Club'),
  ('United States', 'White Oaks Golf Club'),
  ('United States', 'White Path Golf Club'),
  ('United States', 'White Pine Golf Course'),
  ('United States', 'White Pine National'),
  ('United States', 'White Pines Country Club'),
  ('United States', 'White Pines Golf Club'),
  ('United States', 'White Pines Golf Course'),
  ('United States', 'White Plains Golf Club'),
  ('United States', 'White Plains Golf Course'),
  ('United States', 'White Red At Edgewood Country Club'),
  ('United States', 'White Red At Ramblewood Country Club'),
  ('United States', 'White Red At Sugar Mill Country Club'),
  ('United States', 'White Red At Timber Point Country Club'),
  ('United States', 'White Red At Willowbrook Golf Club'),
  ('United States', 'White River Golf Club'),
  ('United States', 'White Springs Golf Course'),
  ('United States', 'White Tail Golf Course'),
  ('United States', 'White Wing At Rio Verde Country Club'),
  ('United States', 'Whitebirch Golf Course'),
  ('United States', 'Whiteface Club'),
  ('United States', 'Whitefish Golf club'),
  ('United States', 'Whitefish Lake Golf Club'),
  ('United States', 'Whiteford Valley Golf Club'),
  ('United States', 'Whitehall Public Golf Course'),
  ('United States', 'Whitehawk Ranch Golf Club'),
  ('United States', 'Whitemarsh Valley Country Club'),
  ('United States', 'Whitetail Golf Club'),
  ('United States', 'Whitetail Golf Course'),
  ('United States', 'Whitetail Golf Resort'),
  ('United States', 'Whitetail Ridge Golf Course'),
  ('United States', 'Whitetail Run Golf Course'),
  ('United States', 'Whitewater Creek Country Club'),
  ('United States', 'Whitford Country Club'),
  ('United States', 'Whitinsville Golf Club'),
  ('United States', 'Whitmire Country Club'),
  ('United States', 'Whitmoor Country Club - North Course'),
  ('United States', 'Whitnall Park Golf Course'),
  ('United States', 'Whitney Oaks Golf Club'),
  ('United States', 'Whittaker Woods Golf Club'),
  ('United States', 'Whittier Mobile Country Club'),
  ('United States', 'Whittier Narrows Golf Course Mountain Course'),
  ('United States', 'Whittier Narrows Golf Course Mountain River'),
  ('United States', 'Whittier Narrows Golf Course Pine Mountain'),
  ('United States', 'Whittier Narrows Golf Course River Pine'),
  ('United States', 'Wianno Club'),
  ('United States', 'Wichita Country Club'),
  ('United States', 'Wichita County Municipal Golf Course'),
  ('United States', 'Wickenburg Country Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club Lil Wick'),
  ('United States', 'Wicker Hills Golf Club'),
  ('United States', 'Wicker Memorial Park Golf Course'),
  ('United States', 'Wicomico Shores Golf Course'),
  ('United States', 'Widows Walk Golf Course'),
  ('United States', 'Wigwam Resort Blue Course'),
  ('United States', 'Wigwam Resort Gold Course'),
  ('United States', 'Wigwam Resort Red Course'),
  ('United States', 'Wilcox Cove Cottages Golf'),
  ('United States', 'Wilcox Oaks Golf Club'),
  ('United States', 'Wild Bluff Golf Course'),
  ('United States', 'Wild Horse Plains Golf Course'),
  ('United States', 'Wild Marsh Golf Club'),
  ('United States', 'Wild Oak Golf Club'),
  ('United States', 'Wild Oaks Golf Course White Cedar Pin Oaks'),
  ('United States', 'Wild Oaks Golf Course White Cedar Willow Oaks'),
  ('United States', 'Wild Oaks Golf Course Willow Oaks Pin Oaks'),
  ('United States', 'Wild Quail Golf Country Club'),
  ('United States', 'Wild Ridge Golf Course'),
  ('United States', 'Wild Rock Golf Club at The Wilderness'),
  ('United States', 'Wild Turkey Golf Club'),
  ('United States', 'Wild Wing Plantation Avocet Course'),
  ('United States', 'Wild Wing Plantation Hummingbird Course'),
  ('United States', 'Wild Wings Golf Club'),
  ('United States', 'Wild Wood Country Club'),
  ('United States', 'Wildcat At Fort Jackson Golf Club'),
  ('United States', 'Wildcat Cliffs Country Club'),
  ('United States', 'Wildcat Creek Golf Course'),
  ('United States', 'Wildcat Crossing Golf Club'),
  ('United States', 'Wildcat Golf Course'),
  ('United States', 'Wildcat Run Country Club'),
  ('United States', 'Wildcreek Executive Golf Course'),
  ('United States', 'Wilderness Club'),
  ('United States', 'Wilderness Country Club'),
  ('United States', 'Wilderness Golf Course'),
  ('United States', 'Wilderness Valley'),
  ('United States', 'Wildfire Golf Club'),
  ('United States', 'Wildflower GC'),
  ('United States', 'Wildhawk Golf Club'),
  ('United States', 'Wildhorse Golf Club'),
  ('United States', 'Wildhorse Golf Course'),
  ('United States', 'Wildhorse Resort Golf Course'),
  ('United States', 'Wildwood Country Club'),
  ('United States', 'Wildwood Golf Club'),
  ('United States', 'Wildwood Golf Course'),
  ('United States', 'Wildwood Golf and RV Resort'),
  ('United States', 'Wildwood Green Golf Course'),
  ('United States', 'Wildwood Lake Golf Course'),
  ('United States', 'Wildwood Marshes Golf Course'),
  ('United States', 'Wildwood Mobile Country Club'),
  ('United States', 'Wilkes Barre Golf Club'),
  ('United States', 'Wilkshire Golf Course'),
  ('United States', 'Willandale Golf Club'),
  ('United States', 'Willapa Harbor Golf Course'),
  ('United States', 'Willard Golf Club'),
  ('United States', 'Willbrook Plantation Golf Club'),
  ('United States', 'William F Larkin Golf Course At Colonial Terrace'),
  ('United States', 'William J Devine Franklin Park Golf Course'),
  ('United States', 'William Land Park Municipal Golf Course'),
  ('United States', 'William S. Sahm Park Golf Course'),
  ('United States', 'Williams Country Club'),
  ('United States', 'Williams Country Club Golf Course'),
  ('United States', 'Williams Nine At Meadow Park Golf Course'),
  ('United States', 'Williamsburg Golf Club'),
  ('United States', 'Williamsburg National Golf Club Jamestown Course'),
  ('United States', 'Williamsburg National Golf Club Yorktown Course'),
  ('United States', 'Williamsport Country Club'),
  ('United States', 'Willingers Golf Club'),
  ('United States', 'Willis Case Golf Course'),
  ('United States', 'Williston Country Club'),
  ('United States', 'Williston Golf Club'),
  ('United States', 'Willoughby Golf Club'),
  ('United States', 'Willow Bend Country Club'),
  ('United States', 'Willow Brook Golf Course'),
  ('United States', 'Willow Creek Country Club'),
  ('United States', 'Willow Creek Golf'),
  ('United States', 'Willow Creek Golf Club At Eagle Vail'),
  ('United States', 'Willow Creek Golf Country Club'),
  ('United States', 'Willow Creek Golf Course'),
  ('United States', 'Willow Creek Municiple Golf Course'),
  ('United States', 'Willow Crest Golf Club'),
  ('United States', 'Willow Hills Golf Center'),
  ('United States', 'Willow Hollow Golf Course'),
  ('United States', 'Willow Lake Golf Club'),
  ('United States', 'Willow Lakes Golf Club'),
  ('United States', 'Willow Lakes Golf Course'),
  ('United States', 'Willow Oak At Hunters Creek Plantation'),
  ('United States', 'Willow Oaks Country Club'),
  ('United States', 'Willow Pond Golf Course'),
  ('United States', 'Willow Ridge Golf & Country Club'),
  ('United States', 'Willow Ridge Golf Club'),
  ('United States', 'Willow Ridge Golf Course'),
  ('United States', 'Willow Run Country Club'),
  ('United States', 'Willow Run Golf Club'),
  ('United States', 'Willow Run Golf Course'),
  ('United States', 'Willow Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Willow Springs Country Club'),
  ('United States', 'Willow Springs Golf Course'),
  ('United States', 'Willow Springs Golf and Country Club'),
  ('United States', 'Willow Tree Golf Course'),
  ('United States', 'Willow Vale Golf Club'),
  ('United States', 'Willow Valley Golf Course'),
  ('United States', 'Willow Wood Golf Course'),
  ('United States', 'Willowbend Country Club Bay Nine'),
  ('United States', 'Willowbend Country Club Bend Nine'),
  ('United States', 'Willowbend Country Club Bog Nine'),
  ('United States', 'Willowbend Golf Club'),
  ('United States', 'Willowbrook Country Club'),
  ('United States', 'Willowbrook Executive Golf Course At Willowcreek Golf Course'),
  ('United States', 'Willowbrook Golf Club'),
  ('United States', 'Willowbrook Golf Course'),
  ('United States', 'Willowbrook Golf Course The North Course'),
  ('United States', 'Willowbrook Golf Course The South Course'),
  ('United States', 'Willowbrook Golf Course The West Course'),
  ('United States', 'Willowcreek Golf Course'),
  ('United States', 'Willowdale Golf Club'),
  ('United States', 'Willowdale Golf Course'),
  ('United States', 'Willowhill Golf Course'),
  ('United States', 'Willowick Golf Course'),
  ('United States', 'Willows At Willowcreek Golf Club'),
  ('United States', 'Willows Run Golf Club Coyote Creek Course'),
  ('United States', 'Willows Run Golf Club Discovery Trails'),
  ('United States', 'Willows Run Golf Club Eagles Talon Course'),
  ('United States', 'Willows Run Golf Club Heron Links Course'),
  ('United States', 'Willsboro Golf Club'),
  ('United States', 'Wilmette Golf Club'),
  ('United States', 'Wilmington Municipal Golf Course'),
  ('United States', 'Wilmington Municipal Golf Course The First Tee Of Greater Wilmington'),
  ('United States', 'Wilshire Country Club'),
  ('United States', 'Wilshire Golf Club'),
  ('United States', 'Wilson At Griffith Park Golf Courses'),
  ('United States', 'Wilson Country Club'),
  ('United States', 'Wilson Lake Country Club'),
  ('United States', 'Wilson Road Golf Course'),
  ('United States', 'Wilsons Willow Run Executive Golf Course'),
  ('United States', 'Wiltwyck Golf Club'),
  ('United States', 'Winchester Country Club'),
  ('United States', 'Wind Watch Golf Country Club'),
  ('United States', 'Windance Country Club'),
  ('United States', 'Windber Country Club'),
  ('United States', 'Windermere Golf Club'),
  ('United States', 'Windham Country Club'),
  ('United States', 'Windham Golf Course'),
  ('United States', 'Winding Branch Golf Course'),
  ('United States', 'Winding Brook Country Club'),
  ('United States', 'Winding Creek Golf Club'),
  ('United States', 'Winding Creek Golf Course'),
  ('United States', 'Winding Hills Golf Club'),
  ('United States', 'Winding Ridge Gold Cub'),
  ('United States', 'Winding River Golf Course'),
  ('United States', 'Windmill At Indian Springs Country Club'),
  ('United States', 'Windmill Golf Center'),
  ('United States', 'Windmill Hill Golf Course'),
  ('United States', 'Windmill Lakes Golf Club'),
  ('United States', 'Windsong Farm Golf Club'),
  ('United States', 'Windsor At Walhalla'),
  ('United States', 'Windsor Club The'),
  ('United States', 'Windsor Golf Club'),
  ('United States', 'Windsor Parke Golf Club'),
  ('United States', 'Windstar On Naples Bay'),
  ('United States', 'Windstone Golf Country Club'),
  ('United States', 'Windswept Dunes Golf Course'),
  ('United States', 'Windwood Hollow Golf Course'),
  ('United States', 'Windwood of Watertown'),
  ('United States', 'Windy Acres Golf Course'),
  ('United States', 'Windy Harbor Golf Club'),
  ('United States', 'Windy Hill Country Club'),
  ('United States', 'Windy Hills Golf Course'),
  ('United States', 'Windy Knoll Golf Club'),
  ('United States', 'Windy Trails Golf Course At Altus Afb'),
  ('United States', 'Wine Valley Golf Course'),
  ('United States', 'Winfield Country Club'),
  ('United States', 'Wing Park Golf Course'),
  ('United States', 'Wing Point Golf Country Club'),
  ('United States', 'WingHaven Country Club'),
  ('United States', 'Winkler County Golf Course'),
  ('United States', 'Winkler Golf Club'),
  ('United States', 'Winn Mountain Golf Course'),
  ('United States', 'Winnapaug Country Club'),
  ('United States', 'Winnemucca Municipal Golf Course'),
  ('United States', 'Winnetka Golf Club'),
  ('United States', 'Winnfield Golf'),
  ('United States', 'Winona Country Club'),
  ('United States', 'Winstar Golf Course Redbud'),
  ('United States', 'Winstar Golf Course Scissortail'),
  ('United States', 'Winston Lake Golf Course'),
  ('United States', 'Winston Trails Golf Club'),
  ('United States', 'Winter Clove Inn Resort'),
  ('United States', 'Winter Creek Golf Country Club'),
  ('United States', 'Winter Park Golf Course'),
  ('United States', 'Winter Park Pines Golf Club'),
  ('United States', 'Winter Quarters Municipal Golf Course'),
  ('United States', 'Wintergreen Resort Devils Knob'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Shamokin'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Tuckahoe'),
  ('United States', 'Wintergreen Resort Stoney Creek Shamokin Tuckahoe'),
  ('United States', 'Winthrop Golf Club'),
  ('United States', 'Winthrop University Golf Course'),
  ('United States', 'Winton Country Club'),
  ('United States', 'Wintonbury Hills Golf Course'),
  ('United States', 'Wisconsin Club'),
  ('United States', 'Wisconsin River Country Club'),
  ('United States', 'Wissahickon Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Witch Golf Club'),
  ('United States', 'Woburn Country Club'),
  ('United States', 'Wohali Country Club Eagle Course'),
  ('United States', 'Wolf At Las Vegas Paiute Golf Resort'),
  ('United States', 'Wolf Creek Golf Club'),
  ('United States', 'Wolf Creek Golf Country Club'),
  ('United States', 'Wolf Creek Golf Course'),
  ('United States', 'Wolf Creek Golf Resort'),
  ('United States', 'Wolf Hollow Golf Club'),
  ('United States', 'Wolf Hollow Golf Course At Copiah Lincoln College'),
  ('United States', 'Wolf Laurel Country Club'),
  ('United States', 'Wolf Ridge Golf Course'),
  ('United States', 'Wolf Run Golf Club'),
  ('United States', 'Wolf Run Golf Course'),
  ('United States', 'Wolfe Island Riverfront Golf Course'),
  ('United States', 'Wolferts Roost Golf Course'),
  ('United States', 'Wolfridge Golf Course'),
  ('United States', 'Wollaston Golf Club'),
  ('United States', 'Wolves Crossing Golf Course'),
  ('United States', 'Wood Creek Golf Links'),
  ('United States', 'Wood Ranch Golf Club'),
  ('United States', 'Wood River Golf Course'),
  ('United States', 'Wood Wind Golf Club'),
  ('United States', 'Woodberry Forest Golf Course'),
  ('United States', 'Woodbine At Mohawk Park Golf Course'),
  ('United States', 'Woodbine Bend Golf Course'),
  ('United States', 'Woodbridge Golf Links'),
  ('United States', 'Woodbrier Golf Course'),
  ('United States', 'Woodbury Golf Course'),
  ('United States', 'Woodcreek Golf Club'),
  ('United States', 'Woodcrest Country Club'),
  ('United States', 'Woodcrest Golf Club'),
  ('United States', 'Wooded View Golf Course'),
  ('United States', 'Woodfield Country Club'),
  ('United States', 'Woodfin Ridge Golf Club'),
  ('United States', 'Woodgate Pines Golf Club'),
  ('United States', 'Woodhaven Country Club'),
  ('United States', 'Woodhaven Golf Club'),
  ('United States', 'Woodhill Country Club'),
  ('United States', 'Woodlake Country Club'),
  ('United States', 'Woodlake Golf Club'),
  ('United States', 'Woodland Country Club'),
  ('United States', 'Woodland Golf Club'),
  ('United States', 'Woodland Golf Course'),
  ('United States', 'Woodland Hills Country Club'),
  ('United States', 'Woodland Hills Golf Club'),
  ('United States', 'Woodland Hills Golf Course'),
  ('United States', 'Woodland Lakeside At Blue Hill Golf Course'),
  ('United States', 'Woodland Ridge Golf Course'),
  ('United States', 'Woodlands Championship Golf Course'),
  ('United States', 'Woodlands Club'),
  ('United States', 'Woodlands Course'),
  ('United States', 'Woodlands Creekside At Traces Golf Club The'),
  ('United States', 'Woodlands Golf Course'),
  ('United States', 'Woodlands Meadows At Traces Golf Club The'),
  ('United States', 'Woodlawn Country Club'),
  ('United States', 'Woodlawn Golf Club'),
  ('United States', 'Woodley Lakes Golf Course'),
  ('United States', 'Woodloch Springs Country Club'),
  ('United States', 'Woodlyn Hills Golf Course'),
  ('United States', 'Woodlynn Hills Golf Course'),
  ('United States', 'Woodmere Country Club'),
  ('United States', 'Woodmont Golf Country Club'),
  ('United States', 'Woodridge Golf Club'),
  ('United States', 'Woodruff Golf Course'),
  ('United States', 'Woods At Boca Woods Country Club'),
  ('United States', 'Woods Blue Grass At Old Westbury Golf Country Club'),
  ('United States', 'Woods Edge Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Woods Fort Golf Course'),
  ('United States', 'Woods Hole Golf Club'),
  ('United States', 'Woods Pines At Tri Cities Golf Course'),
  ('United States', 'Woodside Club'),
  ('United States', 'Woodside Country Club'),
  ('United States', 'Woodside Country Club Cupp Course'),
  ('United States', 'Woodside Country Club Hunters Run Par 3 Course'),
  ('United States', 'Woodside Country Club Jones Course'),
  ('United States', 'Woodside Golf Course'),
  ('United States', 'Woodside Meadows Golf Course'),
  ('United States', 'Woodson Bend Resort'),
  ('United States', 'Woodstock Club'),
  ('United States', 'Woodstock Country Club'),
  ('United States', 'Woodstock Golf Club'),
  ('United States', 'Woodstock Golf Course'),
  ('United States', 'Woodstone Country Club'),
  ('United States', 'Woodward Municipal Golf Course'),
  ('United States', 'Woodway Country Club'),
  ('United States', 'Woodys Run Inc'),
  ('United States', 'Woody’s Run Public Golf Course'),
  ('United States', 'Wooster Country Club'),
  ('United States', 'Worcester Country Club'),
  ('United States', 'Worcester Golf Club'),
  ('United States', 'World Of Golf'),
  ('United States', 'World Tour Golf Links'),
  ('United States', 'Worthington Country Club'),
  ('United States', 'Worthington Golf Club'),
  ('United States', 'Worthington Hills Country Club'),
  ('United States', 'Wray Golf Course'),
  ('United States', 'Wrenwoods Golf Club At Charleston Air Force Base'),
  ('United States', 'Wuskowhan Players Club'),
  ('United States', 'Wyaloosing Creek'),
  ('United States', 'Wyandotte Hills Golf Course'),
  ('United States', 'Wyandotte Shores Golf Course'),
  ('United States', 'Wyantenuck Country Club'),
  ('United States', 'Wyboo Golf Club'),
  ('United States', 'Wyckoff Country Club'),
  ('United States', 'Wykagyl Country Club'),
  ('United States', 'Wymore Country Club'),
  ('United States', 'Wyncote Golf Club'),
  ('United States', 'Wynding Brook Golf Club'),
  ('United States', 'Wynmoor Golf Course'),
  ('United States', 'Wynn Golf Club'),
  ('United States', 'Wynstone Golf Club'),
  ('United States', 'Wyoming Golf Club'),
  ('United States', 'Wyoming Valley Country Club'),
  ('United States', 'Wytheville Golf Course'),
  ('United States', 'X-Golf'),
  ('United States', 'Yacht Country Club The'),
  ('United States', 'Yadkin Country Club'),
  ('United States', 'Yahara Hills Golf Course'),
  ('United States', 'Yahnundasis Golf Club'),
  ('United States', 'Yakima Country Club'),
  ('United States', 'Yakima Elks Golf Country Club'),
  ('United States', 'Yale Golf Course'),
  ('United States', 'Yalobusha Country Club'),
  ('United States', 'Yampa Valley Golf Club'),
  ('United States', 'Yankee Clipper At The Villages Executive Golf Trail'),
  ('United States', 'Yankee Run Golf Course'),
  ('United States', 'Yankee Springs Golf Course'),
  ('United States', 'Yardley Country Club'),
  ('United States', 'Yawgoo Valley Golf Course'),
  ('United States', 'Yazoo Country Club'),
  ('United States', 'Ye Nyne Old Holles Golf Course'),
  ('United States', 'Ye Olde Country Club'),
  ('United States', 'Yeamans Hall Country Club'),
  ('United States', 'Yellow At Bethpage State Park Golf Course'),
  ('United States', 'Yellow White At Willowbrook Golf Club'),
  ('United States', 'Yellowstone Country Club'),
  ('United States', 'Yellowstone Golf Club'),
  ('United States', 'Yellowstone Golf Course'),
  ('United States', 'Yellowstone Golf Resort At Aspen Acres Rv Park'),
  ('United States', 'Yinglings Golf Center'),
  ('United States', 'Ymca Par 3 Home Of The First Tee Of Lakeland'),
  ('United States', 'Yoakum County Golf Club'),
  ('United States', 'Yocha Dehe Golf Club At Cache Creek Casino Resort'),
  ('United States', 'Yolo Fliers Club'),
  ('United States', 'Yorba Linda Country Club'),
  ('United States', 'York Golf Club'),
  ('United States', 'York Golf Tennis Club'),
  ('United States', 'York Par 3 Golf Course'),
  ('United States', 'Yorktown Golf Complex'),
  ('United States', 'Yosemite Lakes Park Golf Course'),
  ('United States', 'Youche Country Club'),
  ('United States', 'Youghiogheny Country Club'),
  ('United States', 'Youngstown Country Club'),
  ('United States', 'Yucaipa Valley Golf Club'),
  ('United States', 'Yucca Ridge Golf Club'),
  ('United States', 'Yuma Golf Country Club'),
  ('United States', 'Zaca Creek Golf Course'),
  ('United States', 'Zach Brooks Golf Course'),
  ('United States', 'Zanesville Country Club'),
  ('United States', 'Zanesville Jaycees Public Golf Course'),
  ('United States', 'Zebulon Country Club'),
  ('United States', 'Zellwood Station Country Club'),
  ('United States', 'Zenwoods Golf Club'),
  ('United States', 'Zephyrhills City Golf Course'),
  ('United States', 'Zigfield Troy Par 3 Golf Course'),
  ('United States', 'Zintel Creek Golf Club'),
  ('United States', 'Zionsville Golf Course'),
  ('United States', 'Zollner Golf Course'),
  ('United States', 'Zumbro Valley Golf Course'),
  ('United States', 'Zumbrota Golf Club')
on conflict (country, name) do nothing;
