insert into public.golf_courses (country, name) values
  ('United States', 'Dequeen Country Club'),
  ('United States', 'Derby Grange Golf & Recreation Center'),
  ('United States', 'Derrick''s Creek Golf Course at Edgewood Country Club'),
  ('United States', 'Derryfield Country Club'),
  ('United States', 'Des Moines Driving Range'),
  ('United States', 'Des Moines Golf & Country Club'),
  ('United States', 'Desert Aire Golf Course'),
  ('United States', 'Desert At Adobe Creek National Golf Course'),
  ('United States', 'Desert Canyon Golf Club'),
  ('United States', 'Desert Canyon Golf Course'),
  ('United States', 'Desert Canyon Golf Resort'),
  ('United States', 'Desert Crest Country Club'),
  ('United States', 'Desert Dunes Golf Course'),
  ('United States', 'Desert Falls Country Club'),
  ('United States', 'Desert Forest Golf Club'),
  ('United States', 'Desert Hawk At Pueblo West'),
  ('United States', 'Desert Highlands Golf Club'),
  ('United States', 'Desert Hills Golf Club'),
  ('United States', 'Desert Hills Golf Course'),
  ('United States', 'Desert Hills Par 3 Golf Course'),
  ('United States', 'Desert Horizons Country Club'),
  ('United States', 'Desert Island Country Club'),
  ('United States', 'Desert Lakes Golf Course'),
  ('United States', 'Desert Mirage Golf Course'),
  ('United States', 'Desert Pines Golf Club'),
  ('United States', 'Desert Sands Golf Course'),
  ('United States', 'Desert Springs Golf Club'),
  ('United States', 'Desert Springs Ranch Golf Course'),
  ('United States', 'Desert Trail Rv Resort Golf Course'),
  ('United States', 'Desert Trails Golf Course At Sun City West'),
  ('United States', 'Desert Willow Golf Course'),
  ('United States', 'Desert Winds Golf Course'),
  ('United States', 'Desoto Golf Course'),
  ('United States', 'Destroyer At Seal Beach Navy Golf Course'),
  ('United States', 'Detroit Country Club'),
  ('United States', 'Detroit Golf Club'),
  ('United States', 'Detwiler Golf Course'),
  ('United States', 'Devil''s Knob Golf Course'),
  ('United States', 'Devil''s Ridge Golf Club'),
  ('United States', 'Devils Head Resort Convention Center Glacier Course'),
  ('United States', 'Devils Lake Golf Course'),
  ('United States', 'Devils Ridge Golf Club'),
  ('United States', 'Devils Thumb Golf Club'),
  ('United States', 'Devou Golf & Event Center'),
  ('United States', 'Dexter Municipal Golf Club'),
  ('United States', 'Diablo Country Club'),
  ('United States', 'Diablo Creek Golf Course'),
  ('United States', 'Diablo Hills Golf Course'),
  ('United States', 'Diadema Golf Club'),
  ('United States', 'Diamante Country Club'),
  ('United States', 'Diamond Bar Golf Course'),
  ('United States', 'Diamond Creek'),
  ('United States', 'Diamond Dunes At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Diamond Hawk Golf Course'),
  ('United States', 'Diamond Hill Golf Country Club'),
  ('United States', 'Diamond Hills Country Club'),
  ('United States', 'Diamond Lake Golf Club'),
  ('United States', 'Diamond Mountain Golf Club'),
  ('United States', 'Diamond Oaks Municipal Golf Course'),
  ('United States', 'Diamond Run Golf Club'),
  ('United States', 'Diamond Springs Golf Course'),
  ('United States', 'Diamond Trail Golf Club'),
  ('United States', 'Diamondback Golf Course'),
  ('United States', 'Diamondhead Golf Club'),
  ('United States', 'Dimmock Hill Golf Course'),
  ('United States', 'Dinah Shore Tournament At Mission Hills Country Club'),
  ('United States', 'Dinaland Golf Course'),
  ('United States', 'Dinosaur Mountain At Gold Canyon Golf Resort'),
  ('United States', 'Dinsmore Golf Course'),
  ('United States', 'Disc Golf'),
  ('United States', 'Disc Golf Course'),
  ('United States', 'Discovery Bay Country Club'),
  ('United States', 'Discovery Bay Golf Club'),
  ('United States', 'Disk Golf Course'),
  ('United States', 'Disneys Lake Buena Vista Golf Course'),
  ('United States', 'Disneys Magnolia Golf Course'),
  ('United States', 'Disneys Oak Trail Golf Course'),
  ('United States', 'Disneys Palm Golf Course'),
  ('United States', 'Ditches Waters At Brickyard Plantation Golf Club'),
  ('United States', 'Divide Ranch Club'),
  ('United States', 'Dix Hills Park Golf Course'),
  ('United States', 'Dixie Driving Range'),
  ('United States', 'Dixie Golf Club'),
  ('United States', 'Dixie Red Hills Golf Course'),
  ('United States', 'Djs Golf Center Par 3'),
  ('United States', 'Dobson Ranch Golf Course'),
  ('United States', 'Doby Springs Golf Course'),
  ('United States', 'Dodge City Country Club'),
  ('United States', 'Dodge Country Club'),
  ('United States', 'Dodge County Golf Club'),
  ('United States', 'Dodge Point Country Club'),
  ('United States', 'Dodge Riverside Golf Club'),
  ('United States', 'Doe Valley'),
  ('United States', 'Dogwood Golf Country Club'),
  ('United States', 'Dogwood Highland At Lancaster Country Club'),
  ('United States', 'Dogwood Hills'),
  ('United States', 'Dogwood Hills Golf Club'),
  ('United States', 'Dogwood Hills Golf Course'),
  ('United States', 'Dogwood Knolls Golf Course'),
  ('United States', 'Dogwood Lakes Golf Club'),
  ('United States', 'Dogwood Laurel At Houndslake Country Club'),
  ('United States', 'Dogwood Oak Tree At Middle Island Country Club'),
  ('United States', 'Dogwood Palmetto At Callawassie Island Club'),
  ('United States', 'Dogwood Redbud At Roanoke Country Club'),
  ('United States', 'Dogwood Trace Golf Course'),
  ('United States', 'Dogwood Valley Golf Course'),
  ('United States', 'Dolphin At Ocean Reef Club'),
  ('United States', 'Dolphin Head Golf Course'),
  ('United States', 'Domenicos Golf Course'),
  ('United States', 'Dominion Golf & Country Club'),
  ('United States', 'Dominion Meadows Golf Course'),
  ('United States', 'Dominion Valley Country Club'),
  ('United States', 'Don Knabe Golf Center Junior Academy'),
  ('United States', 'Don Williams Golf Course'),
  ('United States', 'Donald Ross Golf Club'),
  ('United States', 'Donald Ross Memorial'),
  ('United States', 'Donalsonville Country Club'),
  ('United States', 'Donegal Highlands Golf Course'),
  ('United States', 'Donnybrook Country Club'),
  ('United States', 'Donnybrook Golf Course'),
  ('United States', 'Door Creek Golf Course'),
  ('United States', 'Dorado Country Club'),
  ('United States', 'Dormie Club'),
  ('United States', 'Dornick Hills Golf Country Club'),
  ('United States', 'Dorset Field Club'),
  ('United States', 'Dos Lagos Golf Club'),
  ('United States', 'Dos Lagos Golf Course'),
  ('United States', 'Dos Osos Golf Club'),
  ('United States', 'Dos Rios Country Club'),
  ('United States', 'Dothan Country Club'),
  ('United States', 'Dothan National Golf Club'),
  ('United States', 'Dotys Golf Course'),
  ('United States', 'Double Arrow Golf Resort'),
  ('United States', 'Double Black Diamond At Holiday Valley Resort'),
  ('United States', 'Double Eagle Golf Club'),
  ('United States', 'Double Oaks Golf Club'),
  ('United States', 'Doublegate Country Club'),
  ('United States', 'Douglas Golf Club'),
  ('United States', 'Douglas Golf Country Club'),
  ('United States', 'Douglass Golf Course'),
  ('United States', 'Douglaston Golf Club'),
  ('United States', 'Dove Canyon Country Club'),
  ('United States', 'Dove Valley Ranch Golf Club'),
  ('United States', 'Dover Par 3 Driving Range'),
  ('United States', 'Dowagiac Elk''s Golf Course'),
  ('United States', 'Down River Golf Course'),
  ('United States', 'Downers Grove Golf Club'),
  ('United States', 'Downing Farms Golf Course'),
  ('United States', 'Downing Municipal Golf Course'),
  ('United States', 'Downingtown Country Club'),
  ('United States', 'Downriver Golf Course'),
  ('United States', 'Downs Golf Course'),
  ('United States', 'Dows Golf Course'),
  ('United States', 'Doylestown Country Club'),
  ('United States', 'Dr Charles L Sifford Golf Course At Revolution Park'),
  ('United States', 'Dragonfly Golf Club'),
  ('United States', 'Dragonridge Golf Course'),
  ('United States', 'Draper Valley Golf Club'),
  ('United States', 'Dretzka Park Golf Course'),
  ('United States', 'Drew Country Club'),
  ('United States', 'Driftwood Golf Course'),
  ('United States', 'Driving Range'),
  ('United States', 'Drugan''s Castle Mound'),
  ('United States', 'Drugans Castle Mound'),
  ('United States', 'Druid Hills Golf Club'),
  ('United States', 'Druids Glen'),
  ('United States', 'Drummond Island Golf Club'),
  ('United States', 'Drumright Golf Club'),
  ('United States', 'Dry Creek Ranch Golf Course'),
  ('United States', 'Dryden Lake Golf Club'),
  ('United States', 'Dryden Park Golf Course'),
  ('United States', 'Dublin Country Club'),
  ('United States', 'Dublin Lake Golf Club'),
  ('United States', 'Dublin Ranch Golf Course'),
  ('United States', 'Dubois Country Club'),
  ('United States', 'Dubs Dread Golf Club'),
  ('United States', 'Dubsdread Golf Course'),
  ('United States', 'Dubuque Country Club'),
  ('United States', 'Duck Creek Golf Course'),
  ('United States', 'Duck Hollow Golf Club'),
  ('United States', 'Duck Lake Country Club'),
  ('United States', 'Duck Woods Country Club'),
  ('United States', 'Duckers Lake Golf Club'),
  ('United States', 'Dudley Hill Golf Club'),
  ('United States', 'Due Process Stable'),
  ('United States', 'Duke University Golf Club'),
  ('United States', 'Dumas Memorial Golf Course'),
  ('United States', 'Duncan Golf Country Club'),
  ('United States', 'Duncan Hills Golf Course'),
  ('United States', 'Duncan Park Golf Club'),
  ('United States', 'Dundee Golf Club'),
  ('United States', 'Dunedin Golf Club'),
  ('United States', 'Dunedin Stirling Links'),
  ('United States', 'Dunegrass Country Club'),
  ('United States', 'Dunes Arroyo At Gainey Ranch Golf Club'),
  ('United States', 'Dunes At Monterey Peninsula Country Club'),
  ('United States', 'Dunes At Sandridge Golf Club'),
  ('United States', 'Dunes Golf Club'),
  ('United States', 'Dunes West Golf Club'),
  ('United States', 'Dunham Hills Golf Club'),
  ('United States', 'Dunlap Golf Club'),
  ('United States', 'Dunmaglas Golf Club'),
  ('United States', 'Dunwoodie Golf Course'),
  ('United States', 'Dunwoody Country Club'),
  ('United States', 'Duplin Country Club'),
  ('United States', 'Dupont Country Club Championship Course'),
  ('United States', 'Dupont Country Club Montchanin Course'),
  ('United States', 'Dupont Country Club Nemours Course'),
  ('United States', 'Duran Golf Club Championship Course'),
  ('United States', 'Duran Golf Club Short Course'),
  ('United States', 'Durand Eastman Golf Course'),
  ('United States', 'Durango Hills Golf Course'),
  ('United States', 'Durham Lakes Country Club'),
  ('United States', 'Duston Country Club'),
  ('United States', 'Dusty Hills Country Club'),
  ('United States', 'Dutch Elm Golf Club'),
  ('United States', 'Dutch Hollow Country Club'),
  ('United States', 'Dutch Hollow Golf Club'),
  ('United States', 'Dutchaven Golf Course'),
  ('United States', 'Dutcher Golf Course'),
  ('United States', 'Dutchmans Pipe Golf Club'),
  ('United States', 'Duxbury Yacht Club'),
  ('United States', 'Dwan Golf Course'),
  ('United States', 'Dye At Colleton River Club'),
  ('United States', 'Dye Course At Pga Golf Club'),
  ('United States', 'Dye''s Walk Country Club'),
  ('United States', 'Dyer Country Club'),
  ('United States', 'Dyersburg Municipal Golf Course'),
  ('United States', 'Dyersville Golf and Country Club'),
  ('United States', 'Dyker Beach Golf Course'),
  ('United States', 'Dysart Country Club'),
  ('United States', 'E Gaynor Brennan Golf Course'),
  ('United States', 'E H Lynch Links Golf Course'),
  ('United States', 'E agle Pass Golf Course'),
  ('United States', 'EMS Links Golf Course'),
  ('United States', 'Eads Golf Course'),
  ('United States', 'Eagle Bend Golf Club Bear Osprey Course'),
  ('United States', 'Eagle Bend Golf Club Eagle Bear Course'),
  ('United States', 'Eagle Bend Golf Club Eagle Osprey Course'),
  ('United States', 'Eagle Bend Golf Course'),
  ('United States', 'Eagle Bluff Golf Club'),
  ('United States', 'Eagle Chase Golf Club'),
  ('United States', 'Eagle Creek'),
  ('United States', 'Eagle Creek Country Club'),
  ('United States', 'Eagle Creek Golf Club'),
  ('United States', 'Eagle Creek Golf Course'),
  ('United States', 'Eagle Crest'),
  ('United States', 'Eagle Crest Golf Club'),
  ('United States', 'Eagle Crest Resort'),
  ('United States', 'Eagle Dunes Golf Club'),
  ('United States', 'Eagle Eye Golf Club'),
  ('United States', 'Eagle Falls Golf Club'),
  ('United States', 'Eagle Falls Golf Course'),
  ('United States', 'Eagle Glen Golf Club'),
  ('United States', 'Eagle Glen Golf Course'),
  ('United States', 'Eagle Grove Country Club'),
  ('United States', 'Eagle Harbor Golf Club'),
  ('United States', 'Eagle Haven Golf Course'),
  ('United States', 'Eagle Hill Golf Athletic Club'),
  ('United States', 'Eagle Hills Academy Golf Course'),
  ('United States', 'Eagle Hills Golf Course'),
  ('United States', 'Eagle Island Golf Course'),
  ('United States', 'Eagle Lake - Birdie Course'),
  ('United States', 'Eagle Lake - Eagle Course'),
  ('United States', 'Eagle Lake Golf Course'),
  ('United States', 'Eagle Lakes Golf Club'),
  ('United States', 'Eagle Landing Golf Club'),
  ('United States', 'Eagle Links Golf Club'),
  ('United States', 'Eagle Mountain Golf Club'),
  ('United States', 'Eagle Mountain Golf Course'),
  ('United States', 'Eagle Nest Golf Club'),
  ('United States', 'Eagle Oaks Golf Country Club'),
  ('United States', 'Eagle Osprey At Okeeheelee Golf Course'),
  ('United States', 'Eagle Point Golf Club'),
  ('United States', 'Eagle Pointe Back 9'),
  ('United States', 'Eagle Ranch Golf Club'),
  ('United States', 'Eagle Ridge Gold Course'),
  ('United States', 'Eagle Ridge Golf Club'),
  ('United States', 'Eagle Ridge Golf Club Champions Course'),
  ('United States', 'Eagle Ridge Golf Club Heritage Course'),
  ('United States', 'Eagle Ridge Golf Club Links Course'),
  ('United States', 'Eagle Ridge Golf Club Masters Course'),
  ('United States', 'Eagle Ridge Golf Club Memorial Course'),
  ('United States', 'Eagle Ridge Golf Club Pines Course'),
  ('United States', 'Eagle Ridge Golf Course'),
  ('United States', 'Eagle River Golf Course'),
  ('United States', 'Eagle Rock Golf Club'),
  ('United States', 'Eagle Rock Golf Ski Resort'),
  ('United States', 'Eagle Rock Golf Ski Resort Executive Course'),
  ('United States', 'Eagle Run Golf Course'),
  ('United States', 'Eagle Springs Golf Club'),
  ('United States', 'Eagle Springs Golf Country Club'),
  ('United States', 'Eagle Springs Golf Course'),
  ('United States', 'Eagle Springs Golf Resort'),
  ('United States', 'Eagle Trace Country Club'),
  ('United States', 'Eagle Trace Golf Club'),
  ('United States', 'Eagle Vale Golf Course'),
  ('United States', 'Eagle Valley Golf Club'),
  ('United States', 'Eagle Valley Golf Course'),
  ('United States', 'Eagle View Golf Club'),
  ('United States', 'Eagle View Golf Course'),
  ('United States', 'Eagle Vines Golf Club'),
  ('United States', 'Eagle Watch Golf Club'),
  ('United States', 'Eagle''s Landing Golf Club and Grill'),
  ('United States', 'EagleSticks'),
  ('United States', 'Eaglebrook Country Club'),
  ('United States', 'Eaglerock Golf Course'),
  ('United States', 'Eagles Bluff Golf Course'),
  ('United States', 'Eagles Brooke Golf And Country Club'),
  ('United States', 'Eagles Crossing Golf Course'),
  ('United States', 'Eagles Landing'),
  ('United States', 'Eagles Landing Country Club Creek Nine'),
  ('United States', 'Eagles Landing Country Club Hill Nine'),
  ('United States', 'Eagles Landing Country Club Lake Nine'),
  ('United States', 'Eagles Landing Golf Course'),
  ('United States', 'Eagles Landing Golf Course Of Belton'),
  ('United States', 'Eagles Mere Country Club'),
  ('United States', 'Eagles Nest Country Club At Pebble Creek Resort'),
  ('United States', 'Eagles Nest Golf Course'),
  ('United States', 'Eagles Pointe Golf Club'),
  ('United States', 'Eagles Pride Golf Course Blue Green'),
  ('United States', 'Eagles Pride Golf Course Green Red'),
  ('United States', 'Eagles Pride Golf Course Red Blue'),
  ('United States', 'Eagles Pub Golf Course'),
  ('United States', 'Eagles Ridge Golf Club'),
  ('United States', 'Eaglevail Golf Club'),
  ('United States', 'Eaglewood Country Club'),
  ('United States', 'Eaglewood Golf Course'),
  ('United States', 'Eaglewood Golf Course Eagle Course'),
  ('United States', 'Eaglewood Golf Course Raptor Course'),
  ('United States', 'Eaglewood Resort Spa'),
  ('United States', 'Eaglewood Resort and Spa'),
  ('United States', 'Earlville Country Club'),
  ('United States', 'East At Belfair Golf Club'),
  ('United States', 'East At Broadmoor Golf Club'),
  ('United States', 'East At Bull Creek Golf Course'),
  ('United States', 'East At Churchville Park Golf Course'),
  ('United States', 'East At Country Club Of Hershey'),
  ('United States', 'East At Deerfield Country Club'),
  ('United States', 'East At Eagle Valley Golf Course'),
  ('United States', 'East At Glendoveer Golf Course'),
  ('United States', 'East At Grandover Resort'),
  ('United States', 'East At Hunters Run Golf Course'),
  ('United States', 'East At Imperial Golf Club'),
  ('United States', 'East At Jacaranda Golf Club'),
  ('United States', 'East At Laurel Oak Country Club'),
  ('United States', 'East At Lincoln Park Golf Course'),
  ('United States', 'East At Maidstone Club'),
  ('United States', 'East At Malone Golf Club'),
  ('United States', 'East At Merion Golf Club'),
  ('United States', 'East At Mohawk Golf Club'),
  ('United States', 'East At Oak Hill Country Club'),
  ('United States', 'East At Oak Tree Country Club'),
  ('United States', 'East At Orangebrook Country Club'),
  ('United States', 'East At Rogues Roost Golf Country Club'),
  ('United States', 'East At Tamarack Golf Course'),
  ('United States', 'East At Victor Hills Golf Club'),
  ('United States', 'East At Webster Golf Club'),
  ('United States', 'East At Windyke Country Club'),
  ('United States', 'East At Winged Foot Golf Club'),
  ('United States', 'East At Wycliffe Country Club'),
  ('United States', 'East Aurora Country Club'),
  ('United States', 'East Bay Golf Club'),
  ('United States', 'East Center At Ridgewood Country Club The'),
  ('United States', 'East Course'),
  ('United States', 'East Course At Belleair Country Club'),
  ('United States', 'East Course At Terry Hills Golf Course'),
  ('United States', 'East Fork Par-3 Golf Course'),
  ('United States', 'East Greenwich Golf Country Club'),
  ('United States', 'East Hampton Golf Club'),
  ('United States', 'East Hartford Golf Club'),
  ('United States', 'East Lake Golf Club'),
  ('United States', 'East Liverpool Country Club'),
  ('United States', 'East Mountain Country Club'),
  ('United States', 'East Mountain Golf Course'),
  ('United States', 'East North At Killearn Country Club Inn'),
  ('United States', 'East North At Spanish Wells Country Club'),
  ('United States', 'East Orange Golf Course'),
  ('United States', 'East Palestine Country Club'),
  ('United States', 'East Potomac Golf Links Blue Course'),
  ('United States', 'East Potomac Golf Links Red Course'),
  ('United States', 'East Potomac Golf Links White Course'),
  ('United States', 'East Private At Drumlins Golf Club'),
  ('United States', 'East Ridge Country Club'),
  ('United States', 'East South At Athens Country Club'),
  ('United States', 'East South At Lakes Country Club The'),
  ('United States', 'East South At Monterey Country Club'),
  ('United States', 'East South At Oaks North Golf Course'),
  ('United States', 'East South At Ocean Breeze Golf Country Club'),
  ('United States', 'East South At Sahalee Country Club'),
  ('United States', 'East South At Silver Lakes Country Club'),
  ('United States', 'East West At Monterey Country Club'),
  ('United States', 'East West At Newaukum Valley Golf Course'),
  ('United States', 'Eastern Hills Golf Club'),
  ('United States', 'Eastern Shore Yacht Country Club'),
  ('United States', 'Eastland Fairways'),
  ('United States', 'Eastlyn Golf Course'),
  ('United States', 'Eastman Golf Links'),
  ('United States', 'Easton Country Club'),
  ('United States', 'Eastpointe Country Club East Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Eastpointe Country Club West Course'),
  ('United States', 'Eastward Ho Club'),
  ('United States', 'Eastwood Country Club'),
  ('United States', 'Eastwood Golf Club'),
  ('United States', 'Eastwood Golf Course'),
  ('United States', 'Eaton Canyon Golf Course'),
  ('United States', 'Eaton Country Club'),
  ('United States', 'Eau Claire Golf and Country Club'),
  ('United States', 'Ebensburg Country Club'),
  ('United States', 'Eberhart Petro Golf Course'),
  ('United States', 'Eccentric Duffer Golf Course'),
  ('United States', 'Echelon Golf Club'),
  ('United States', 'Echo Falls Country Club'),
  ('United States', 'Echo HIlls Golf Course'),
  ('United States', 'Echo Hills Golf Club'),
  ('United States', 'Echo Lake Country Club'),
  ('United States', 'Echo Mesa Golf Course At Sun City West'),
  ('United States', 'Echo Valley Country Club'),
  ('United States', 'Eco Golf Course'),
  ('United States', 'Ed Oliver Golf Club'),
  ('United States', 'Edelweiss Chalet Country Club'),
  ('United States', 'Eden Valley Golf Course'),
  ('United States', 'Edgartown Golf Club'),
  ('United States', 'Edge Hill Golf Course'),
  ('United States', 'EdgeBrook Golf Course'),
  ('United States', 'Edgebrook Country Club'),
  ('United States', 'Edgebrook Golf Course'),
  ('United States', 'Edgerton Towne Country Club'),
  ('United States', 'Edgewater Beach Resort Golf Course'),
  ('United States', 'Edgewater Country Club'),
  ('United States', 'Edgewater Golf Club'),
  ('United States', 'Edgewater Golf Course'),
  ('United States', 'Edgewood Club Of Tivoli'),
  ('United States', 'Edgewood Country Club'),
  ('United States', 'Edgewood Golf Club'),
  ('United States', 'Edgewood Golf Club (Closed)'),
  ('United States', 'Edgewood Golf Course'),
  ('United States', 'Edgewood Greens Golf Course'),
  ('United States', 'Edgewood In The Pines'),
  ('United States', 'Edgewood Park Golf Club'),
  ('United States', 'Edgewood Tahoe Golf Course'),
  ('United States', 'Edgewood Valley Country Club'),
  ('United States', 'Edina Country Club'),
  ('United States', 'Edinburgh USA'),
  ('United States', 'Edmore Golf Course'),
  ('United States', 'Edmundson Golf Course'),
  ('United States', 'Edwin Shaw Challenge Golf Course'),
  ('United States', 'Eel River Golf Course'),
  ('United States', 'Eglin Afb Golf Course Eagle'),
  ('United States', 'Eglin Afb Golf Course Falcon'),
  ('United States', 'Egremont Country Club'),
  ('United States', 'Egret Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Egypt Valley Country Club'),
  ('United States', 'Egyptian Country Club'),
  ('United States', 'Eighteen At Bangor Municipal Golf Course'),
  ('United States', 'Eighteen At Bing Maloney Golf Course'),
  ('United States', 'Eighteen At Eagle Crest Golf Course'),
  ('United States', 'Eighteen At Hi Level Golf Course'),
  ('United States', 'Eighteen At Race Brook Country Club'),
  ('United States', 'Eighteen At Tri Palm Country Club'),
  ('United States', 'Eighteen At White Birch Golf Course'),
  ('United States', 'Eighteen Hole At Balboa Park Municipal Golf Club'),
  ('United States', 'Eighteen Hole At Bright Leaf Golf Resort'),
  ('United States', 'Eighteen Hole At Cherry Hills Country Club'),
  ('United States', 'Eighteen Hole At Harder Hall Country Club'),
  ('United States', 'Eighteen Hole At Holiday Island Country Club'),
  ('United States', 'Eighteen Hole At Indian Tree Golf Club'),
  ('United States', 'Eighteen Hole At On Top Of The World Golf Club'),
  ('United States', 'Eighteen Hole At Pine Hills Country Club'),
  ('United States', 'Eighteen Hole At Pittsburgh North Golf Club'),
  ('United States', 'Eighteen Hole At Riverbend Golf Complex'),
  ('United States', 'Eighteen Hole At South Park Golf Course'),
  ('United States', 'Eighteen Hole At South Suburban Golf Course'),
  ('United States', 'Eighteen Hole At Van Nuys Golf Course'),
  ('United States', 'Eighteen Hole At Village Links Of Glen Ellyn'),
  ('United States', 'Eighteen Hole At Villages Golf Country Club'),
  ('United States', 'Eighteen Hole Executive At Outdoor Resort Country Club'),
  ('United States', 'Eighteen Hole Regulation At Pipestem State Park Resort'),
  ('United States', 'Eighteen Hole Regulation At Santa Teresa Golf Club'),
  ('United States', 'Eisenhower Lakes Golf Club Island View Nine'),
  ('United States', 'Eisenhower Lakes Golf Club Lake View Nine'),
  ('United States', 'Eisenhower Lakes Golf Club Pine View Nine'),
  ('United States', 'Ekwanok Country Club'),
  ('United States', 'El Caballero Country Club'),
  ('United States', 'El Camino Country Club'),
  ('United States', 'El Cariso Golf Course'),
  ('United States', 'El Cielo Los Lagos At Desert Princess Country Club'),
  ('United States', 'El Conquistador Golf Tennis Canada Course'),
  ('United States', 'El Conquistador Golf Tennis Conquistador Course'),
  ('United States', 'El Conquistador Golf Tennis Pusch X9 Course'),
  ('United States', 'El Diablo At The Villages Executive Golf Trail'),
  ('United States', 'El Dorado Golf Country Club'),
  ('United States', 'El Dorado Golf Course'),
  ('United States', 'El Dorado Park Golf Club'),
  ('United States', 'El Macero Country Club'),
  ('United States', 'El Monte Golf Course'),
  ('United States', 'El Niguel Country Club'),
  ('United States', 'El Paso Country Club'),
  ('United States', 'El Paso Golf Club'),
  ('United States', 'El Prado Golf Courses Butterfield Stage'),
  ('United States', 'El Prado Golf Courses Chino Creek'),
  ('United States', 'El Rio Golf Club'),
  ('United States', 'El Rio Golf Course'),
  ('United States', 'El Santiago At The Villages Executive Golf Trail'),
  ('United States', 'El Valle Escondido Golf Course'),
  ('United States', 'El Zagal Golf Course'),
  ('United States', 'Elbel Golf Course'),
  ('United States', 'Elberton Country Club'),
  ('United States', 'Elcona Country Club'),
  ('United States', 'Eldorado'),
  ('United States', 'Eldorado Country Club'),
  ('United States', 'Elephant Rocks At Williams'),
  ('United States', 'Elgin Country Club'),
  ('United States', 'Elizabeth Lake Country Club'),
  ('United States', 'Elizabeth Manor Country Club'),
  ('United States', 'Elk City Golf Country Club'),
  ('United States', 'Elk Course At Breckenridge Golf Club'),
  ('United States', 'Elk Creek Country Club'),
  ('United States', 'Elk Hollow Golf Course'),
  ('United States', 'Elk Rapids Golf Club'),
  ('United States', 'Elk Ridge Golf Club'),
  ('United States', 'Elk Ridge Golf Course'),
  ('United States', 'Elk River Club'),
  ('United States', 'Elk River Country Club'),
  ('United States', 'Elk River Golf Club'),
  ('United States', 'Elk Run Golf Club'),
  ('United States', 'Elk Valley Golf Course'),
  ('United States', 'Elkader Golf and Country Club'),
  ('United States', 'Elkdale Country Club'),
  ('United States', 'Elkhorn Golf Club'),
  ('United States', 'Elkhorn Golf Club At Sun Valley'),
  ('United States', 'Elkhorn Ridge Golf Course'),
  ('United States', 'Elkhorn Valley Golf Course'),
  ('United States', 'Elks Club Marion IN'),
  ('United States', 'Elks Country Club'),
  ('United States', 'Elks Fairview Golf Club'),
  ('United States', 'Elks Golf Club'),
  ('United States', 'Elks Golf Country Club'),
  ('United States', 'Elks Lodge Country Club'),
  ('United States', 'Elks Lodge Par 3 Golf Course'),
  ('United States', 'Elks Run Golf Club'),
  ('United States', 'Elkview Country Club'),
  ('United States', 'Ella Sharp Park Golf Course'),
  ('United States', 'Ellendale Country Club'),
  ('United States', 'Ellensburg Golf Club'),
  ('United States', 'Ellington Ridge Country Club'),
  ('United States', 'Ellinwood Country Club'),
  ('United States', 'Ellis Country Club'),
  ('United States', 'Ellis Golf Course'),
  ('United States', 'Ellsworth Country Club'),
  ('United States', 'Ellsworth Golf Municipal Course'),
  ('United States', 'Ellsworth Meadows Golf Club'),
  ('United States', 'Elm Lake Golf Course'),
  ('United States', 'Elm Tree Golf Course'),
  ('United States', 'Elma Meadows Golf Club'),
  ('United States', 'Elmbrook Golf Course'),
  ('United States', 'Elmcrest Country Club'),
  ('United States', 'Elmcrest Golf & Country Club'),
  ('United States', 'Elmhurst Country Club'),
  ('United States', 'Elmira Country Club'),
  ('United States', 'Elms Country Club'),
  ('United States', 'Elmwood Country Club'),
  ('United States', 'Elmwood Golf Course'),
  ('United States', 'Elmwood Golf Course 9 Hole Course'),
  ('United States', 'Elmwood Park Golf Course'),
  ('United States', 'Elwood Golf Course'),
  ('United States', 'Ely Golf Club'),
  ('United States', 'Ely Park Muni Golf Course'),
  ('United States', 'Elyria Country Club'),
  ('United States', 'Emanon Country Club'),
  ('United States', 'Emeis Golf Course'),
  ('United States', 'Emerald Bay Golf Club'),
  ('United States', 'Emerald Canyon Golf Course'),
  ('United States', 'Emerald Crest Golf Course'),
  ('United States', 'Emerald Dunes Golf Club'),
  ('United States', 'Emerald Greens'),
  ('United States', 'Emerald Greens Golf Club'),
  ('United States', 'Emerald Greens Golf Course'),
  ('United States', 'Emerald Hill'),
  ('United States', 'Emerald Hill Golf Course'),
  ('United States', 'Emerald Hills Golf Club'),
  ('United States', 'Emerald Hills Golf Course'),
  ('United States', 'Emerald Isle Golf Course'),
  ('United States', 'Emerald Lake Golf Club'),
  ('United States', 'Emerald Lakes Golf Course'),
  ('United States', 'Emerald Vale Golf Club'),
  ('United States', 'Emerywood Golf Course'),
  ('United States', 'Emmett Golf Course And Event Facilities'),
  ('United States', 'Empire Ranch Golf Club'),
  ('United States', 'Emporia Country Club'),
  ('United States', 'Emporia Municipal Golf Course'),
  ('United States', 'Emporium Country Club'),
  ('United States', 'En Joie Golf Course'),
  ('United States', 'Enagic Golf Club At Eastlake'),
  ('United States', 'Encanterra Country Club'),
  ('United States', 'Encanto Golf Course'),
  ('United States', 'Encanto Nine Golf Course'),
  ('United States', 'Encina Royale Golf Course'),
  ('United States', 'Encinitas Ranch Golf Course'),
  ('United States', 'Encino At Sepulveda Golf Complex'),
  ('United States', 'Endwell Greens Golf Club'),
  ('United States', 'Enger Park Golf Course'),
  ('United States', 'Engineers Country Club'),
  ('United States', 'England Country Club'),
  ('United States', 'English Turn Golf Country Club'),
  ('United States', 'Enosburg Falls Country Club'),
  ('United States', 'Entrada At Snow Canyon'),
  ('United States', 'Enumclaw Golf Course'),
  ('United States', 'Epworth Heights Golf Course'),
  ('United States', 'Equestrian At Polo Club The'),
  ('United States', 'Erie Golf Club'),
  ('United States', 'Erie Shores Golf Club'),
  ('United States', 'Erie Shores Golf Course'),
  ('United States', 'Erin Hills'),
  ('United States', 'Erinn Ashley At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Erskine Golf Course'),
  ('United States', 'Escalon Golf Course'),
  ('United States', 'Escambia At The Villages Executive Golf Trail'),
  ('United States', 'Escanaba Country Club'),
  ('United States', 'Escena Golf Club'),
  ('United States', 'Esmeralda Golf Course'),
  ('United States', 'Esplanade At Azario Lakewood Ranch'),
  ('United States', 'Esplanade At St Marys'),
  ('United States', 'Esplanade Golf And Country Club Of Naples'),
  ('United States', 'Esplanade Golf Country Club At Lakewood Ranch'),
  ('United States', 'Esquagama Golf Course'),
  ('United States', 'Essex Country Club'),
  ('United States', 'Essex County Club'),
  ('United States', 'Essex County Country Club'),
  ('United States', 'Essex Fells Country Club'),
  ('United States', 'Essex Golf Club'),
  ('United States', 'Essex Golf and Country Club'),
  ('United States', 'Essex Park Golf Course'),
  ('United States', 'Estate Golf Club'),
  ('United States', 'Estero Country Club'),
  ('United States', 'Estes Park Golf Course'),
  ('United States', 'Estevan Woodlawn Golf Club'),
  ('United States', 'Estherville Golf Course'),
  ('United States', 'Estuary At River Strand Golf And Country Club'),
  ('United States', 'Etowah Valley Golf Club'),
  ('United States', 'Eufaula Country Club'),
  ('United States', 'Eunice Country Club'),
  ('United States', 'Eunice Municipal Golf Course'),
  ('United States', 'Eupora Country Club'),
  ('United States', 'Eureka Country Club'),
  ('United States', 'Eureka Municipal Golf Course'),
  ('United States', 'Evans Heights Golf Club'),
  ('United States', 'Evans Prairie Country Club Egret Killdeer'),
  ('United States', 'Evans Prairie Country Club Killdeer Osprey'),
  ('United States', 'Evans Prairie Country Club Osprey Egret'),
  ('United States', 'Evanston Golf Club'),
  ('United States', 'Evansville Country Club'),
  ('United States', 'Eveleth Municipal Golf Course'),
  ('United States', 'Everett Golf Country Club'),
  ('United States', 'Everglades Golf Course'),
  ('United States', 'Evergreen 1 At Evergreen Country Club'),
  ('United States', 'Evergreen 2 At Evergreen Country Club'),
  ('United States', 'Evergreen Country Club'),
  ('United States', 'Evergreen Golf Club'),
  ('United States', 'Evergreen Golf Course'),
  ('United States', 'Evergreen Hills Golf Course'),
  ('United States', 'Evergreen Resort'),
  ('United States', 'Evergreen Valley Golf Course'),
  ('United States', 'Ewa Villages Golf Course'),
  ('United States', 'Exchange City Golf Course'),
  ('United States', 'Executive At A C Read Golf Course'),
  ('United States', 'Executive At Bel Aire Golf Club'),
  ('United States', 'Executive At Bing Maloney Golf Course'),
  ('United States', 'Executive At Boca Raton Municipal Golf Course'),
  ('United States', 'Executive At Evergreen Golf Course Inc'),
  ('United States', 'Executive At Ferncroft Country Club'),
  ('United States', 'Executive At Harbor Links Golf Course'),
  ('United States', 'Executive At Harder Hall Country Club'),
  ('United States', 'Executive At Hi Level Golf Course'),
  ('United States', 'Executive At Las Positas Golf Course'),
  ('United States', 'Executive At Lindenwood Golf Club'),
  ('United States', 'Executive At Mick Riley Golf Course'),
  ('United States', 'Executive At Newberry Country Club'),
  ('United States', 'Executive At Rebsamen Park Golf Course'),
  ('United States', 'Executive At Ridgecrest Golf Course'),
  ('United States', 'Executive At Rockland Lake Golf Course'),
  ('United States', 'Executive At Saratoga Spa State Park'),
  ('United States', 'Executive At Seven Springs Country Club'),
  ('United States', 'Executive At Shadow Lake Golf Racquet Club'),
  ('United States', 'Executive At Van Nuys Golf Course'),
  ('United States', 'Executive At Vista Valencia Golf Course'),
  ('United States', 'Executive At White Birch Golf Course'),
  ('United States', 'Executive At White Deer Golf Club'),
  ('United States', 'Executive Nine At High Cedars Golf Club'),
  ('United States', 'Executive South Family Golf Center'),
  ('United States', 'Exeter Country Club'),
  ('United States', 'Exeter Public Golf Course'),
  ('United States', 'Exmoor Country Club'),
  ('United States', 'F E Warren Afb Golf Club'),
  ('United States', 'F H Golf Course'),
  ('United States', 'Fairbanks Golf Country Club'),
  ('United States', 'Fairbanks Ranch Country Club Lakes Ocean Course'),
  ('United States', 'Fairbanks Ranch Country Club Ocean Valley Course'),
  ('United States', 'Fairbanks Ranch Country Club Valley Lakes Course'),
  ('United States', 'Fairbury Country Club'),
  ('United States', 'Fairdale Country Club'),
  ('United States', 'Fairfax Golf Club'),
  ('United States', 'Fairfield Country Club'),
  ('United States', 'Fairfield Fun Center'),
  ('United States', 'Fairfield Golf Club'),
  ('United States', 'Fairfield Golf and Country Club'),
  ('United States', 'Fairfield Hills Golf Course'),
  ('United States', 'Fairfield Plantation Golf Country Club'),
  ('United States', 'Fairgreens Golf Club'),
  ('United States', 'Fairgrounds Golf Center'),
  ('United States', 'Fairlawn Country Club'),
  ('United States', 'Fairlawn Golf Club'),
  ('United States', 'Fairlawn Golf Course'),
  ('United States', 'Fairmont Field Club'),
  ('United States', 'Fairmont Golf Club'),
  ('United States', 'Fairmont Hot Springs Resort'),
  ('United States', 'Fairmont Park Golf Course Country Club'),
  ('United States', 'Fairmount Country Club'),
  ('United States', 'Fairview Country Club'),
  ('United States', 'Fairview Farm Golf Course'),
  ('United States', 'Fairview Golf Course'),
  ('United States', 'Fairview Hills Golf Club'),
  ('United States', 'Fairview Lakeside Country Club'),
  ('United States', 'Fairview Mountain Golf Club'),
  ('United States', 'Fairview Municipal Golf Course'),
  ('United States', 'Fairway Mews Golf Club'),
  ('United States', 'Fairway River Links'),
  ('United States', 'Fairway Valley Golf Club'),
  ('United States', 'Fairway Village Golf Course'),
  ('United States', 'Fairways At Howards Barn'),
  ('United States', 'Fairways At Lincoln'),
  ('United States', 'Fairways Country Club'),
  ('United States', 'Fairways Golf Club'),
  ('United States', 'Fairways Meadows At Centennial Golf Club'),
  ('United States', 'Fairways Of Canton Golf Club'),
  ('United States', 'Fairways Of Halfmoon'),
  ('United States', 'Fairways Of Halfmoon Executive Course'),
  ('United States', 'Fairways of Woodside'),
  ('United States', 'Fairwinds Golf Course'),
  ('United States', 'Fairwood Country Club'),
  ('United States', 'Falcon Creek Golf Course'),
  ('United States', 'Falcon Crest Golf Club Cadet Course'),
  ('United States', 'Falcon Crest Golf Club Championship 18 Course'),
  ('United States', 'Falcon Crest Golf Club Freedom Course'),
  ('United States', 'Falcon Dunes Golf Course'),
  ('United States', 'Falcon Golf Club'),
  ('United States', 'Falcon Golf Course'),
  ('United States', 'Falcon Head Golf Club'),
  ('United States', 'Falcon Lakes Golf Course'),
  ('United States', 'Falcon Pointe Golf Club'),
  ('United States', 'Falcon Ridge Golf Club'),
  ('United States', 'Falcon Ridge Golf Course'),
  ('United States', 'Falcon Valley Golf Course'),
  ('United States', 'Falconhead Resort Country Club'),
  ('United States', 'Falcons Fire Golf Club'),
  ('United States', 'Faldo At Wildfire Golf Club At Desert Ridge Resort'),
  ('United States', 'Falkirk Estate Country Club'),
  ('United States', 'Fall Creek Golf Club'),
  ('United States', 'Fall River Country Club'),
  ('United States', 'Fall River Valley Golf Country Club'),
  ('United States', 'Fallen Oak Golf Course'),
  ('United States', 'Fallen Timbers Fairways'),
  ('United States', 'Falling Creek Country Club'),
  ('United States', 'Falling River Country Club'),
  ('United States', 'Fallon Golf Course'),
  ('United States', 'Falls At Blackhawk Country Club'),
  ('United States', 'Falls City Country Club'),
  ('United States', 'Falls Country Club'),
  ('United States', 'Falls Road Golf Course'),
  ('United States', 'Falls Village Golf Course'),
  ('United States', 'Falmouth Country Club'),
  ('United States', 'Falmouth Country Club Eighteen Hole Course'),
  ('United States', 'Falmouth Country Club Talon Course'),
  ('United States', 'False River Golf Country Club'),
  ('United States', 'Family Golf Learning Center'),
  ('United States', 'Family Sports Golf Course'),
  ('United States', 'Fantasy Valley Golf Course'),
  ('United States', 'Far Corner Golf Fox Heron Course'),
  ('United States', 'Far Corner Golf Hawk Fox Course'),
  ('United States', 'Far Corner Golf Heron Hawk Course'),
  ('United States', 'Far Oaks Golf Club'),
  ('United States', 'Far Vu Golf Course'),
  ('United States', 'Fargo Country Club'),
  ('United States', 'Fargo Recreation Golf Course'),
  ('United States', 'Faribault Golf Club'),
  ('United States', 'Farm Dallie Golf Club'),
  ('United States', 'Farm Golf Club The'),
  ('United States', 'Farm Neck Golf Club'),
  ('United States', 'Farmers Golf & Health Club'),
  ('United States', 'Farmingbury Hills Golf Club'),
  ('United States', 'Farmington Country Club'),
  ('United States', 'Farmington Hills Golf Club'),
  ('United States', 'Farmington Woods Golf Course'),
  ('United States', 'Farmsley Golf Center'),
  ('United States', 'Farmstead Golf Country Club Clubview Valleyview Course'),
  ('United States', 'Farmstead Golf Country Club Lakeview Clubview Course'),
  ('United States', 'Farmstead Golf Country Club Valleyview Lakeview Course'),
  ('United States', 'Farmstead Golf Links'),
  ('United States', 'Farmville Country Club'),
  ('United States', 'Farview Golf Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Farwell Country Club'),
  ('United States', 'Fashion Golf Country Club'),
  ('United States', 'Faulkwood Shores Golf Club'),
  ('United States', 'Fauquier Springs Country Club'),
  ('United States', 'Fawn Creek Golf Course'),
  ('United States', 'Fawn Crest Golf Course'),
  ('United States', 'Fawn Lake Country Club'),
  ('United States', 'Fayetteville Country Club'),
  ('United States', 'Fazio Premier At Treetops Resort'),
  ('United States', 'Feather River Park Resort'),
  ('United States', 'Feather Sound Country Club'),
  ('United States', 'Fellows Creek Municipal Golf Club'),
  ('United States', 'Fendrich Golf Course'),
  ('United States', 'Fenner Hill Golf Club'),
  ('United States', 'Fennwood Hills Country Club'),
  ('United States', 'Fenton Farms Golf Club'),
  ('United States', 'Fenway Golf Club'),
  ('United States', 'Fenwick Golf Club'),
  ('United States', 'Fern Hill Golf Club'),
  ('United States', 'Ferndale Country Club'),
  ('United States', 'Fernwood Country Club'),
  ('United States', 'Fessenden Golf Club'),
  ('United States', 'Fianna Hills Country Club'),
  ('United States', 'Fiddlesticks Country Club Long Mean Course'),
  ('United States', 'Fiddlesticks Country Club Wee Friendly Course'),
  ('United States', 'Field Club of Omaha (north)'),
  ('United States', 'Field Club of Omaha (south)'),
  ('United States', 'Fields Ferry Golf Club'),
  ('United States', 'Fieldstone Golf Club'),
  ('United States', 'Fillmore Fairways Golf Course'),
  ('United States', 'Fillmore Golf Club'),
  ('United States', 'Fincastle On The Mountain Golf Course'),
  ('United States', 'Findlay Country Club'),
  ('United States', 'Finkbine Golf Course'),
  ('United States', 'Fircrest Golf Club'),
  ('United States', 'Fire Fox Resorts The Witch Golf Course'),
  ('United States', 'Fire Ridge Golf Club'),
  ('United States', 'Fire Ridge Golf Course'),
  ('United States', 'Firecliff At Desert Willow Golf Resort'),
  ('United States', 'Firefly Golf Course'),
  ('United States', 'Firefly Golf Links'),
  ('United States', 'Firekeeper Golf Course'),
  ('United States', 'Firelake Golf Course'),
  ('United States', 'Firerock Country Club'),
  ('United States', 'Firerock Country Club Littlerock Course'),
  ('United States', 'Firestone Country Club'),
  ('United States', 'Firethorn Golf Club'),
  ('United States', 'Firethorne Country Club'),
  ('United States', 'Fireweed Meadows Golf Course'),
  ('United States', 'First Nine At Edison Club The'),
  ('United States', 'First Nine At Montclair Golf Club'),
  ('United States', 'First Nine Second Nine At Bermuda Dunes Country Club'),
  ('United States', 'First Nine Second Nine At Cloverleaf Golf Club'),
  ('United States', 'First Nine Third Nine At Cloverleaf Golf Club'),
  ('United States', 'First Second At Lake Venice Golf Club'),
  ('United States', 'First Tee Northwest Arkansas'),
  ('United States', 'First Tee Of Augusta'),
  ('United States', 'First Tee Par 3 At Green Valley Ranch Golf Club'),
  ('United States', 'Fish Lake Country Club'),
  ('United States', 'Fisher Island Club'),
  ('United States', 'Fisher Park Golf Course'),
  ('United States', 'Fishermans Cove Golf Marina'),
  ('United States', 'Fishers Island Golf Country Club'),
  ('United States', 'Fishhook Golf Course'),
  ('United States', 'Fishkill Golf Course Driving Range'),
  ('United States', 'Five Flags Golf'),
  ('United States', 'Five Island Golf Course'),
  ('United States', 'Flagg Creek Golf Course'),
  ('United States', 'Flagstaff Ranch Golf Club'),
  ('United States', 'Flamingo Lakes Country Club'),
  ('United States', 'Flanders Valley Golf Club Red Gold Course'),
  ('United States', 'Flanders Valley Golf Club White Blue Course'),
  ('United States', 'Flatbush Golf Course'),
  ('United States', 'Flatirons Golf Course'),
  ('United States', 'Fleming County Golf Association'),
  ('United States', 'Fleming Island Golf Club'),
  ('United States', 'Fletchers Landing At Swingin Things'),
  ('United States', 'Flight Range'),
  ('United States', 'Flint Golf Club'),
  ('United States', 'Flint Hills Golf Course'),
  ('United States', 'Flint Hills National Golf Club'),
  ('United States', 'Flint River Golf Course'),
  ('United States', 'Florence Country Club'),
  ('United States', 'Florida Caverns Golf Course'),
  ('United States', 'Florida Keys Country Club'),
  ('United States', 'Florissant Golf Club'),
  ('United States', 'Flossmoor Country Club'),
  ('United States', 'Flourtown Country Club'),
  ('United States', 'Floyd Park Golf Course'),
  ('United States', 'Flushing Meadows Pitch Putt'),
  ('United States', 'Flushing Valley Golf Club'),
  ('United States', 'Flying "B" Golf Course'),
  ('United States', 'Flying Hills Golf Club'),
  ('United States', 'Flynn Centennial At Huntingdon Valley Country Club'),
  ('United States', 'Folkston Golf Club'),
  ('United States', 'Fon Du Lac Golf Course'),
  ('United States', 'Fonda Golf Course'),
  ('United States', 'Fontenelle Golf Course'),
  ('United States', 'Foothill Golf Course'),
  ('United States', 'Foothills Executive Golf Course'),
  ('United States', 'Foothills Golf Club'),
  ('United States', 'Foothills Golf Course Championship 18 Course'),
  ('United States', 'Foothills Golf Course Executive Course'),
  ('United States', 'Foothills Golf Course Par 3 Course'),
  ('United States', 'Foothills Par 3 Golf Course'),
  ('United States', 'Forbes Golf Course'),
  ('United States', 'Fords Colony Country Club Blackheath Course'),
  ('United States', 'Fords Colony Country Club Blue Heron Course'),
  ('United States', 'Fords Colony Country Club Marsh Hawk Course'),
  ('United States', 'Fordyce Country Club'),
  ('United States', 'Fore Honor Golf Course'),
  ('United States', 'Fore Kicks Golf Club'),
  ('United States', 'Fore U Golf Center'),
  ('United States', 'Fore Way Challenge Golf & Driving Range'),
  ('United States', 'Forebay Golf Course'),
  ('United States', 'Forest Akers East'),
  ('United States', 'Forest Akers West'),
  ('United States', 'Forest City Municipal Golf Course'),
  ('United States', 'Forest Country Club'),
  ('United States', 'Forest Course At Fiddlers Elbow Country Club'),
  ('United States', 'Forest Creek Golf Club North Course'),
  ('United States', 'Forest Creek Golf Club South Course'),
  ('United States', 'Forest Dale Golf Course'),
  ('United States', 'Forest Dunes Golf Resort'),
  ('United States', 'Forest E. Everhart Memorial Golf Course'),
  ('United States', 'Forest Glen Golf Country Club'),
  ('United States', 'Forest Greens Golf Club'),
  ('United States', 'Forest Heights Country Club'),
  ('United States', 'Forest Heights Golf Course'),
  ('United States', 'Forest Hill Field Club'),
  ('United States', 'Forest Hill Golf Course'),
  ('United States', 'Forest Hills'),
  ('United States', 'Forest Hills Country Club'),
  ('United States', 'Forest Hills Country Club Vue 791'),
  ('United States', 'Forest Hills Golf Club'),
  ('United States', 'Forest Hills Golf Course'),
  ('United States', 'Forest Lake At Stratton Mountain Country Club'),
  ('United States', 'Forest Lake Club'),
  ('United States', 'Forest Lake Country Club'),
  ('United States', 'Forest Lake Golf Club'),
  ('United States', 'Forest Lakes Golf Club At Abac'),
  ('United States', 'Forest Meadows Golf Course'),
  ('United States', 'Forest Oaks Country Club'),
  ('United States', 'Forest Oaks Golf Club'),
  ('United States', 'Forest Park Country Club'),
  ('United States', 'Forest Park Golf Course'),
  ('United States', 'Forest Point Golf Course'),
  ('United States', 'Forest View Golf Center'),
  ('United States', 'Forewinds Golf Course'),
  ('United States', 'Former Hara Greens'),
  ('United States', 'Forrest City Country Club'),
  ('United States', 'Forsgate Country Club The Banks'),
  ('United States', 'Forsgate Country Club The Palmer'),
  ('United States', 'Forsyth Country Club'),
  ('United States', 'Forsyth Golf Club'),
  ('United States', 'Fort Belvoir Golf Club Gunston Course'),
  ('United States', 'Fort Belvoir Golf Club Woodlawn Course'),
  ('United States', 'Fort Cherry Golf Club'),
  ('United States', 'Fort Collins Country Club'),
  ('United States', 'Fort Custer Golf Club'),
  ('United States', 'Fort Dodge Country Club'),
  ('United States', 'Fort Erie Golf Club'),
  ('United States', 'Fort Hays Municipal Golf Course'),
  ('United States', 'Fort Kent Golf Club'),
  ('United States', 'Fort Lauderdale Country Club North Course'),
  ('United States', 'Fort Lauderdale Country Club South Course'),
  ('United States', 'Fort Mill Golf Club'),
  ('United States', 'Fort Mitchell Country Club Golf Course'),
  ('United States', 'Fort Moore Golf Course Bradley Nine'),
  ('United States', 'Fort Moore Golf Course Marshall Nine'),
  ('United States', 'Fort Myers Country Club'),
  ('United States', 'Fort Sill Golf Club'),
  ('United States', 'Fort Smith Country Club'),
  ('United States', 'Fort Snelling Golf Course'),
  ('United States', 'Fort Washington Golf Country Club'),
  ('United States', 'Fortuna Delrey Golf Course'),
  ('United States', 'Forty Niner Country Club'),
  ('United States', 'Foss Park Golf Course'),
  ('United States', 'Fossil Island Golf Club'),
  ('United States', 'Fossil Trace Golf Club'),
  ('United States', 'Fosston Golf Club'),
  ('United States', 'Foster Country Club'),
  ('United States', 'Foster Golf Links'),
  ('United States', 'Foster Gulch Golf Course'),
  ('United States', 'Foster Park Golf Course'),
  ('United States', 'Fostoria Country Club'),
  ('United States', 'Founders At Penn National Golf Club Inn'),
  ('United States', 'Founders Club At St James Plantation'),
  ('United States', 'Founders Club Of Pawleys Island'),
  ('United States', 'Foundry Golf Club'),
  ('United States', 'Fountain Green Golf Course'),
  ('United States', 'Fountain Head Country Club'),
  ('United States', 'Fountain Hills Golf Club'),
  ('United States', 'Fountain Lakes Golf Course'),
  ('United States', 'Fountain Of The Sun Country Club'),
  ('United States', 'Fountain Springs Golf Course'),
  ('United States', 'Fountain Valley Golf Course'),
  ('United States', 'Fountainhead Creek Golf Club'),
  ('United States', 'Fountains Golf & Banquet'),
  ('United States', 'Four Bridges Country Club'),
  ('United States', 'Four Lakes Country Club'),
  ('United States', 'Four Lakes Golf Club'),
  ('United States', 'Four Mile Ranch Golf Club'),
  ('United States', 'Four Oaks Golf Course'),
  ('United States', 'Four Peaks Course At Sunland Springs Village'),
  ('United States', 'Four Seasons Country Club'),
  ('United States', 'Four Seasons Golf Club'),
  ('United States', 'Four Seasons Golf Course'),
  ('United States', 'Four Seasons Ranch Golf Course'),
  ('United States', 'Four Seasons Spa Country Club'),
  ('United States', 'Four Streams Golf Club'),
  ('United States', 'Four Willows Golf Course'),
  ('United States', 'Four Winds Golf Course'),
  ('United States', 'Fourth Nine At Montclair Golf Club'),
  ('United States', 'Fowler''s Mill Golf Course'),
  ('United States', 'Fox At Pittsburgh North Golf Club'),
  ('United States', 'Fox Bend Golf Course'),
  ('United States', 'Fox Chapel Golf Club'),
  ('United States', 'Fox Chase Golf Course At Carroll Farms'),
  ('United States', 'Fox Creek'),
  ('United States', 'Fox Creek Golf Club'),
  ('United States', 'Fox Creek Golf Course'),
  ('United States', 'Fox Den Golf Course'),
  ('United States', 'Fox Glen Golf Club'),
  ('United States', 'Fox Hill Country Club'),
  ('United States', 'Fox Hill Golf And Country Club'),
  ('United States', 'Fox Hills Country Club'),
  ('United States', 'Fox Hollow Golf Club'),
  ('United States', 'Fox Hollow Golf Course'),
  ('United States', 'Fox Hopyard Golf Club'),
  ('United States', 'Fox Lake Country Club'),
  ('United States', 'Fox Lake Golf Club'),
  ('United States', 'Fox Lake Golf Course'),
  ('United States', 'Fox Meadow Golf Course'),
  ('United States', 'Fox Prairie Golf Course'),
  ('United States', 'Fox Ridge'),
  ('United States', 'Fox Ridge Golf Club'),
  ('United States', 'Fox Ridge Golf Course'),
  ('United States', 'Fox River Resort'),
  ('United States', 'Fox Run Country Club'),
  ('United States', 'Fox Run Course At Glenview Champions Country Club'),
  ('United States', 'Fox Run Driving Range'),
  ('United States', 'Fox Run Golf Club'),
  ('United States', 'Fox Run Golf Course'),
  ('United States', 'Fox Run Golf Links'),
  ('United States', 'Fox Valley Golf Course'),
  ('United States', 'Fox Woods Golf Course'),
  ('United States', 'FoxCreek Golf & Racquet Club'),
  ('United States', 'Foxboro Golf Club'),
  ('United States', 'Foxborough Country Club'),
  ('United States', 'Foxburg Country Club'),
  ('United States', 'Foxchase Golf Club'),
  ('United States', 'Foxcliff Golf Club'),
  ('United States', 'Foxcroft Golf Club'),
  ('United States', 'Foxfire At Village Green'),
  ('United States', 'Foxfire Golf Club'),
  ('United States', 'Foxfire Resort Golf Club Grey Fox Course'),
  ('United States', 'Foxfire Resort Golf Club Red Fox Course'),
  ('United States', 'Foxford Hills Golf Course'),
  ('United States', 'Foxglove Pinecone At Resort At The Mountain The'),
  ('United States', 'Foxtail Golf Club North Course'),
  ('United States', 'Foxtail Golf Club South Course'),
  ('United States', 'Foxwood Country Club'),
  ('United States', 'Foxwood Hills Country Club'),
  ('United States', 'Framingham Country Club'),
  ('United States', 'Francis Byrne Golf Course'),
  ('United States', 'Francis Gross Golf Course'),
  ('United States', 'Francis Lake Golf Club'),
  ('United States', 'Francisco Grande Resort Golf Club'),
  ('United States', 'Franconia Golf Course'),
  ('United States', 'Frank E Peters Municipal Golf Course'),
  ('United States', 'Frank Skul Memorial Golf Course'),
  ('United States', 'Franklin Canyon Golf Course'),
  ('United States', 'Franklin Country Club'),
  ('United States', 'Franklin County Country Club'),
  ('United States', 'Franklin Golf Club'),
  ('United States', 'Franklin Golf Course'),
  ('United States', 'Franklin Hills Country Club'),
  ('United States', 'Franklin Valley Golf Club'),
  ('United States', 'Franklinton Country Club'),
  ('United States', 'Frasch Park Golf Club'),
  ('United States', 'Fraser Edmundston Golf Club'),
  ('United States', 'Fraserglen Golf Course Training Centre'),
  ('United States', 'Fraternal Order Of Eagles Eagles Hills Golf Course'),
  ('United States', 'Frazee Golf Course'),
  ('United States', 'Frear Park Golf Course'),
  ('United States', 'Fred Enke Golf Course'),
  ('United States', 'Frederic Golf Course'),
  ('United States', 'Frederica Golf Club'),
  ('United States', 'Frederick Golf Country Club'),
  ('United States', 'Frederick Peak Golf Club'),
  ('United States', 'Fredericksburg Country Club'),
  ('United States', 'Fredonia Country Club'),
  ('United States', 'Freedom Fairways'),
  ('United States', 'Freeport Mills Golf Course'),
  ('United States', 'Fremont Country Club'),
  ('United States', 'Fremont County Golf Course'),
  ('United States', 'Fremont County Recreation Area'),
  ('United States', 'Fremont Golf Club'),
  ('United States', 'Fremont Park Golf Course'),
  ('United States', 'French Camp Golf Course'),
  ('United States', 'French Creek Golf Course'),
  ('United States', 'French Oaks Golf Club'),
  ('United States', 'French Woods Golf Course'),
  ('United States', 'Frenchmans Bend Golf Country Club'),
  ('United States', 'Frenchmans Reserve Golf Course'),
  ('United States', 'Frenchs Hollow Fairways Golf Course'),
  ('United States', 'Fresh Meadow Country Club'),
  ('United States', 'Fresh Meadow Golf Club'),
  ('United States', 'Fresh Pond Golf Course'),
  ('United States', 'Friars Head Golf Course'),
  ('United States', 'Friars Presidio At Riverwalk Golf Club'),
  ('United States', 'Friendly Hills Country Club'),
  ('United States', 'Friendly Meadows Golf Course'),
  ('United States', 'Friendly Valley Golf Course'),
  ('United States', 'Frog Hollow Golf Club'),
  ('United States', 'Frog Rock Country Club'),
  ('United States', 'Front Back At Metedeconk National Golf Club'),
  ('United States', 'Front Back At Rolling Green Golf Club'),
  ('United States', 'Front Eighteen At Black Hawk Golf Course'),
  ('United States', 'Front Middle At Rolling Green Golf Club'),
  ('United States', 'Front Nine Back Nine At Southern Hills Country Club'),
  ('United States', 'Front Royal Golf Club'),
  ('United States', 'Front Third At Metedeconk National Golf Club'),
  ('United States', 'Frontier Road House Golf Course'),
  ('United States', 'Frost Creek'),
  ('United States', 'Frosty Valley Country Club'),
  ('United States', 'Frosty Valley Golf Links'),
  ('United States', 'Fruitport Golf Club'),
  ('United States', 'Frye Island Golf Course'),
  ('United States', 'Ft Cobb Golf Course'),
  ('United States', 'Fulda Town and Country Golf'),
  ('United States', 'Full Cry At Keswick Hall And Golf Club'),
  ('United States', 'Fuller''s Fairways'),
  ('United States', 'Fullerton Golf Course'),
  ('United States', 'Fulton Country Club'),
  ('United States', 'Furman University Golf Course'),
  ('United States', 'Furnace Bay Golf Course'),
  ('United States', 'Furnace Brook Golf Club'),
  ('United States', 'Furnace Creek Golf Course'),
  ('United States', 'Fyre Lake Golf Club'),
  ('United States', 'GLC Links'),
  ('United States', 'Gaffney Country Club'),
  ('United States', 'Gahanna Municipal Golf Course'),
  ('United States', 'Gaillardia Country Club'),
  ('United States', 'Gainesville Country Club'),
  ('United States', 'Gainesville Municipal Golf Course'),
  ('United States', 'Gainfield Farms Golf Course'),
  ('United States', 'Galax Municipal Golf Course'),
  ('United States', 'Galen Hall Golf Club'),
  ('United States', 'Galena Golf Club'),
  ('United States', 'Galena Ridge At Silver Mountain Resort'),
  ('United States', 'Galion Country Club'),
  ('United States', 'Galla Creek Golf Course'),
  ('United States', 'Galleon Brigantine At Shipyard Golf Club'),
  ('United States', 'Gallery Golf Club North Golf Course'),
  ('United States', 'Gallery Golf Club South Golf Course'),
  ('United States', 'Gallery Golf Course'),
  ('United States', 'Galloping Hill Golf Course'),
  ('United States', 'Galloping Hill Golf Course Learning Center 9'),
  ('United States', 'Galloway National Golf Club'),
  ('United States', 'Galway Golf Course'),
  ('United States', 'Gamble Sands Golf Club Cascade Putting Course'),
  ('United States', 'Gamble Sands Golf Club Quicksands Course'),
  ('United States', 'Gamble Sands Golf Club Scarecrow Course'),
  ('United States', 'Gamble Sands Golf Club The Sands Course'),
  ('United States', 'Gambler Ridge Golf Club'),
  ('United States', 'Gananoque Golf And Country Club'),
  ('United States', 'Ganienkeh Golf Course'),
  ('United States', 'Garden City Country Club'),
  ('United States', 'Garden City Golf Club'),
  ('United States', 'Garden Golf Club'),
  ('United States', 'Garden Of The Gods Club North Course'),
  ('United States', 'Garden Of The Gods Club South Course'),
  ('United States', 'Garden Of The Gods Club West Course'),
  ('United States', 'Garden Park'),
  ('United States', 'Gardiners Bay Country Club'),
  ('United States', 'Gardner Golf Course'),
  ('United States', 'Gardner Municipal Golf Course'),
  ('United States', 'Garland Lodge & Resort'),
  ('United States', 'Garner Country Club'),
  ('United States', 'Garner Golf and Country Club'),
  ('United States', 'Garnett Country Club'),
  ('United States', 'Garrison Golf Club'),
  ('United States', 'Garrisons Lake Golf Club'),
  ('United States', 'Gasparilla Inn Golf Course'),
  ('United States', 'Gaston Country Club'),
  ('United States', 'Gate City Golf Course'),
  ('United States', 'Gates Four Golf Country Club'),
  ('United States', 'Gates Park Golf Course'),
  ('United States', 'Gateway Cities Golf Club'),
  ('United States', 'Gateway Golf Course'),
  ('United States', 'Gateway Lodge Golf Course'),
  ('United States', 'Gateway National Golf Links'),
  ('United States', 'Gateway Recreation Golf Course'),
  ('United States', 'Gator Creek Golf Course'),
  ('United States', 'Gator Lakes Golf Course'),
  ('United States', 'Gator Trace Golf Country Club'),
  ('United States', 'Gauss'' Green Valley Golf Course'),
  ('United States', 'Gavilan Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Gay Brewer Jr Course At Picadome'),
  ('United States', 'Gaylord Country Club'),
  ('United States', 'Gearhart Golf Links'),
  ('United States', 'Gem Lake Hills Golf Course'),
  ('United States', 'Gene Torres Golf Course At Highlands University'),
  ('United States', 'Genegantslet Golf Club'),
  ('United States', 'General Burnside State Park'),
  ('United States', 'General Electric Athletic Club'),
  ('United States', 'General George V Underwood Jr Golf Complex Sunrise Course'),
  ('United States', 'General George V Underwood Jr Golf Complex Sunset Course'),
  ('United States', 'General James Hackler Golf Course At Coastal Carolina University'),
  ('United States', 'General Old Golf Course'),
  ('United States', 'Generations Golf Course'),
  ('United States', 'Genesee Valley Golf Course North'),
  ('United States', 'Genesee Valley Golf Course South'),
  ('United States', 'Genesee Valley Meadows Golf Course'),
  ('United States', 'Geneseo Golf Course'),
  ('United States', 'Geneva Country Club'),
  ('United States', 'Geneva Farm Golf Course'),
  ('United States', 'Geneva Golf Club'),
  ('United States', 'Geneva Golf and Country Club'),
  ('United States', 'Geneva on-the Lake Village Golf Course'),
  ('United States', 'Gentz''s Homestead Golf Course'),
  ('United States', 'George W. Dunne National Driving Range'),
  ('United States', 'George W. Dunne National Golf Course'),
  ('United States', 'George Wright Golf Course'),
  ('United States', 'George Young Golf Course'),
  ('United States', 'George Young Recreation'),
  ('United States', 'Georgetown Country Club'),
  ('United States', 'Georgia National Golf Club'),
  ('United States', 'Georgia Southern University Golf Course'),
  ('United States', 'Georgia Veterans Memorial Golf Course At Lake Blackshear Resort Golf Club'),
  ('United States', 'Germantown Country Club'),
  ('United States', 'Germany Hill Golf Course'),
  ('United States', 'Geronimo Course At Desert Mountain Golf Club'),
  ('United States', 'Gettysburg National Golf Club'),
  ('United States', 'Giant Oak Golf Club'),
  ('United States', 'Gibson Woods Golf Course'),
  ('United States', 'Gig Harbor Golf Country Club'),
  ('United States', 'Gil Morgan Golf Course'),
  ('United States', 'Gilbert Greens Country Club'),
  ('United States', 'Giles Country Club'),
  ('United States', 'Gillespie Country Club'),
  ('United States', 'Gillespie Golf Club'),
  ('United States', 'Gillette Golf Club'),
  ('United States', 'Gillette Ridge'),
  ('United States', 'Gilroy Golf Course'),
  ('United States', 'Glacier Club Golf Course'),
  ('United States', 'Glacier Club Mountain Course'),
  ('United States', 'Glacier Club Valley Course'),
  ('United States', 'Glacier Park Golf Club'),
  ('United States', 'Glacier View Golf Club'),
  ('United States', 'Glades At Colony West Country Club'),
  ('United States', 'Gladstan Golf Course'),
  ('United States', 'Gladstone Golf Club'),
  ('United States', 'Gladwin Heights Golf Course'),
  ('United States', 'Glasco Golf Club'),
  ('United States', 'Glass Hill Golf Club'),
  ('United States', 'Glastonbury Hills Country Club'),
  ('United States', 'Glen Abbey Golf Club'),
  ('United States', 'Glen Acres Golf Country Club'),
  ('United States', 'Glen Annie Golf Club'),
  ('United States', 'Glen Arven Country Club'),
  ('United States', 'Glen Brook Country Club'),
  ('United States', 'Glen Cove Golf Club'),
  ('United States', 'Glen Dornoch Waterway Golf Links'),
  ('United States', 'Glen Eagle Golf Club'),
  ('United States', 'Glen Eagle Golf Country Club'),
  ('United States', 'Glen Eagle Golf Course'),
  ('United States', 'Glen Echo Country Club'),
  ('United States', 'Glen Ellen Country Club'),
  ('United States', 'Glen Ellyn Village Links Golf Course'),
  ('United States', 'Glen Erin Golf Club'),
  ('United States', 'Glen Flora Country Club'),
  ('United States', 'Glen Head Country Club'),
  ('United States', 'Glen Hills Golf Club'),
  ('United States', 'Glen Ivy Golf Club'),
  ('United States', 'Glen Kernan Club'),
  ('United States', 'Glen Lake Golf & Practice Center'),
  ('United States', 'Glen Mills Golf Course'),
  ('United States', 'Glen Oak Country Club'),
  ('United States', 'Glen Oak Golf Club'),
  ('United States', 'Glen Oaks Country Club'),
  ('United States', 'Glen Oaks Golf Club'),
  ('United States', 'Glen Oaks Golf Course'),
  ('United States', 'Glen Oaks Golf Racquet Club'),
  ('United States', 'Glen Ridge Country Club'),
  ('United States', 'Glen View Club'),
  ('United States', 'Glenarbor Golf Club'),
  ('United States', 'Glenbrier Golf Course'),
  ('United States', 'Glenbrook Golf Course'),
  ('United States', 'Glencoe Country Club'),
  ('United States', 'Glencoe Golf Club'),
  ('United States', 'Glendale Country Club'),
  ('United States', 'Glendale Golf Course'),
  ('United States', 'Glendale Lakes Golf Course'),
  ('United States', 'Glendarin Hills Golf Club'),
  ('United States', 'Glendora Country Club'),
  ('United States', 'Gleneagle Golf Course'),
  ('United States', 'Gleneagles Country Club Legends Course'),
  ('United States', 'Gleneagles Country Club Victory Course'),
  ('United States', 'Gleneagles Golf Club'),
  ('United States', 'Gleneagles Golf Course At Mclaren Park'),
  ('United States', 'Gleneagles Turnberry At Waterford Golf Club'),
  ('United States', 'Glengarry Golf Links'),
  ('United States', 'Glenhardie Country Club'),
  ('United States', 'Glenhurst Golf Course'),
  ('United States', 'Glenkerry Golf Course'),
  ('United States', 'Glenlakes Country Club'),
  ('United States', 'Glenlakes Golf Club Lakes Course'),
  ('United States', 'Glenlakes Golf Club Vista Dunes Course'),
  ('United States', 'Glenlore Golf Course'),
  ('United States', 'Glenmary Country Club'),
  ('United States', 'Glenmaura National Golf Course'),
  ('United States', 'Glenmoor Country Club'),
  ('United States', 'Glenmoor Golf Course'),
  ('United States', 'Glenmore Country Club'),
  ('United States', 'Glenn Golf Country Club'),
  ('United States', 'Glenriddle Golf Club Man O War Course'),
  ('United States', 'Glenrochie Country Club'),
  ('United States', 'Glenrock Golf Course'),
  ('United States', 'Glenross Golf Club'),
  ('United States', 'Glens Falls Country Club'),
  ('United States', 'Glenview Golf Course'),
  ('United States', 'Glenview Park Golf Club'),
  ('United States', 'Glenview Prairie Club'),
  ('United States', 'Glenville Golf Club'),
  ('United States', 'Glenwild Golf Club And Spa'),
  ('United States', 'Glenwild Greens Golf Course'),
  ('United States', 'Glenwood Country Club'),
  ('United States', 'Glenwood Golf Course'),
  ('United States', 'Glenwood Springs Golf Club'),
  ('United States', 'Glenwoodie Golf Club'),
  ('United States', 'Glocester Country Club'),
  ('United States', 'Gloucester Country Club'),
  ('United States', 'Glynlea Country Club'),
  ('United States', 'Glynns Creek Golf Course'),
  ('United States', 'Goat Hill Park'),
  ('United States', 'Goddard State Memorial Park'),
  ('United States', 'Godwin Creek Golf Course'),
  ('United States', 'Gof Mohr Golf Course'),
  ('United States', 'Gogebic Country Club'),
  ('United States', 'Gold At Cedarbrook Golf Course'),
  ('United States', 'Gold At Congressional Country Club'),
  ('United States', 'Gold At Golden Horseshoe Golf Club The'),
  ('United States', 'Gold At Paradise Point Golf Course'),
  ('United States', 'Gold At Treasure Lake Golf Course'),
  ('United States', 'Gold Blue At Valley Brook Country Club'),
  ('United States', 'Gold Canyon Rv Golf Resort'),
  ('United States', 'Gold Green At Wyndemere Country Club'),
  ('United States', 'Gold Hills Golf Club'),
  ('United States', 'Gold Hills Golf Course'),
  ('United States', 'Gold Red At Lindenwood Golf Club'),
  ('United States', 'Gold Red At Westchester Golf Country Club'),
  ('United States', 'Gold White At Rothland Golf Course'),
  ('United States', 'Golden Bear Golf Club At Indigo Run'),
  ('United States', 'Golden Eagle Country Club'),
  ('United States', 'Golden Eagle Golf Club'),
  ('United States', 'Golden Eagle Golf Club At Tides Inn Resort'),
  ('United States', 'Golden Era Golf Course'),
  ('United States', 'Golden Gate Park Golf Course'),
  ('United States', 'Golden Hawk Golf Club'),
  ('United States', 'Golden Hills Country Club'),
  ('United States', 'Golden Hills Golf Club'),
  ('United States', 'Golden Lakes Golf Course'),
  ('United States', 'Golden Locket Golf Course'),
  ('United States', 'Golden Marsh At Harbour Ridge Yacht Country Club'),
  ('United States', 'Golden Oak Golf Club'),
  ('United States', 'Golden Oaks Golf Club'),
  ('United States', 'Golden Oaks Village Green Golf'),
  ('United States', 'Golden Ocala Golf Equestrian Club'),
  ('United States', 'Golden Pheasant Golf Club'),
  ('United States', 'Golden Plains At Akron Golf Course'),
  ('United States', 'Golden Sands Golf Community'),
  ('United States', 'Golden Sands Golf Course'),
  ('United States', 'Golden Valley Country Club'),
  ('United States', 'Goldendale Golf Club'),
  ('United States', 'Goldeneye Club'),
  ('United States', 'Goldsboro Municipal Golf Course'),
  ('United States', 'Goldside Golf Course'),
  ('United States', 'Golf Academy Of Delaware Vandegift Course'),
  ('United States', 'Golf Academy at Terra Cotta'),
  ('United States', 'Golf At Province Lake'),
  ('United States', 'Golf Center Des Plaines'),
  ('United States', 'Golf Club At Boulder Ridge'),
  ('United States', 'Golf Club At Cuscowilla'),
  ('United States', 'Golf Club At Fox Acres'),
  ('United States', 'Golf Club At Heather Ridge'),
  ('United States', 'Golf Club At Mansion Ridge'),
  ('United States', 'Golf Club At South Hampton'),
  ('United States', 'Golf Club At Stonebridge'),
  ('United States', 'Golf Club At Terra Lago North Course'),
  ('United States', 'Golf Club At Terra Lago South Course'),
  ('United States', 'Golf Club At Valley View'),
  ('United States', 'Golf Club At Wescott Plantation Black Robin Course'),
  ('United States', 'Golf Club At Wescott Plantation Burn Kill Course'),
  ('United States', 'Golf Club At Wescott Plantation Oak Forest Course'),
  ('United States', 'Golf Club Of Amelia Island At Summer Beach The'),
  ('United States', 'Golf Club Of Estrella'),
  ('United States', 'Golf Club Of Newport The'),
  ('United States', 'Golf Club Of South Georgia'),
  ('United States', 'Golf Club Of St Saint Joseph The'),
  ('United States', 'Golf Club Of The Everglades'),
  ('United States', 'Golf Club of Dublin'),
  ('United States', 'Golf Club of Illinois'),
  ('United States', 'Golf Club of Incline Village'),
  ('United States', 'Golf Club of Indiana'),
  ('United States', 'Golf Club of Wentzville'),
  ('United States', 'Golf Club of West Virginia'),
  ('United States', 'Golf Course At Bolduc Park The'),
  ('United States', 'Golf Course On Turkey Mountain'),
  ('United States', 'Golf Courses of Lawsonia'),
  ('United States', 'Golf Driving Range'),
  ('United States', 'Golf Du Moulin Laflamme'),
  ('United States', 'Golf Granby Ranch'),
  ('United States', 'Golf Hammock Country Club'),
  ('United States', 'Golf Headquarters Golfplex'),
  ('United States', 'Golf Hemmingford Frontier'),
  ('United States', 'Golf Hemmingford Village'),
  ('United States', 'Golf Learning Center'),
  ('United States', 'Golf North Hills'),
  ('United States', 'Golf Summerlin Eagle Crest Course'),
  ('United States', 'Golf Summerlin Highland Falls Course'),
  ('United States', 'Golf Summerlin Palm Valley Course'),
  ('United States', 'Golf The Round'),
  ('United States', 'Golf at Indian Creek'),
  ('United States', 'Golf at Indian Creek - Blackbird Course'),
  ('United States', 'Golf at Indian Creek - Gray Hawk Course'),
  ('United States', 'Golf at Indian Creek - Red Feather Course'),
  ('United States', 'Golfview Golf Recreation'),
  ('United States', 'Gooding Golf Course'),
  ('United States', 'Goodpark Golf Course'),
  ('United States', 'Goodrich Country Club'),
  ('United States', 'Goodrich Golf Course'),
  ('United States', 'Goodwin At Goodwin Golf Course'),
  ('United States', 'Goodyear Golf Club'),
  ('United States', 'Goose Creek Golf Club'),
  ('United States', 'Goose River Golf Club'),
  ('United States', 'Goose Run Golf Course At Naval Submarine Base'),
  ('United States', 'Gordon Pines Golf Course'),
  ('United States', 'Gordon Trent Golf Course'),
  ('United States', 'Gorge Vale Golf Club'),
  ('United States', 'Gorham Country Club'),
  ('United States', 'Goshen Golf Club'),
  ('United States', 'Gothic Hill Golf Course'),
  ('United States', 'Gouverneur Country Club'),
  ('United States', 'Governors Club Foothills Course'),
  ('United States', 'Governors Club Lakes Course'),
  ('United States', 'Governors Club Mountain Course'),
  ('United States', 'Governors Run Golf Club'),
  ('United States', 'Governors Run Golf Course'),
  ('United States', 'Governors Towne Club'),
  ('United States', 'Gowanda Country Club'),
  ('United States', 'Gowanie Country Club'),
  ('United States', 'Gowrie Municipal Golf Course'),
  ('United States', 'Gozzer Ranch Golf Lake Club'),
  ('United States', 'Grace At Saucon Valley Country Club'),
  ('United States', 'Graceville Golf Club'),
  ('United States', 'Gracewil Country Club'),
  ('United States', 'Graeagle Meadows Golf Course'),
  ('United States', 'Granada Farms Country Club'),
  ('United States', 'Granada Golf Course'),
  ('United States', 'Grand Beach Golf Course'),
  ('United States', 'Grand Canyon University Golf Course'),
  ('United States', 'Grand Cherokee State Park Golf Course'),
  ('United States', 'Grand Cypress Golf Club Cypress Course'),
  ('United States', 'Grand Cypress Golf Club Links Course'),
  ('United States', 'Grand Elk Golf Course'),
  ('United States', 'Grand Forks Country Club'),
  ('United States', 'Grand Geneva Golf Resort'),
  ('United States', 'Grand Haven Golf Club'),
  ('United States', 'Grand Lake Golf Course'),
  ('United States', 'Grand Lake Rv And Golf Resort'),
  ('United States', 'Grand Ledge Country Club'),
  ('United States', 'Grand National Golf Course'),
  ('United States', 'Grand Prairie Country Club'),
  ('United States', 'Grand Prarie Golf Course'),
  ('United States', 'Grand Reserve Golf Club'),
  ('United States', 'Grand Ridge Golf Club'),
  ('United States', 'Grand Royal At Grand Palms Golf Country Club'),
  ('United States', 'Grand View Golf Club'),
  ('United States', 'Grand View Golf Course'),
  ('United States', 'Grand View Lodge The Garden'),
  ('United States', 'Grand Vue Park Golf Course'),
  ('United States', 'Grande Dunes Members Club'),
  ('United States', 'Grande Dunes Resort Club'),
  ('United States', 'Grande Golf Club'),
  ('United States', 'Grande Oaks Golf Club'),
  ('United States', 'Grande Oaks Golf Club Par 3'),
  ('United States', 'Grande Vista Golf Club'),
  ('United States', 'Grandfather At Grandfather Golf Country Club'),
  ('United States', 'Grandote Peaks Golf Course'),
  ('United States', 'Grandpa''s Woods Golf Course'),
  ('United States', 'Grandpas Woods Golf'),
  ('United States', 'Grandview Country Club'),
  ('United States', 'Grandview Farms Golf Course'),
  ('United States', 'Grandview Golf Club'),
  ('United States', 'Grandview Golf Course'),
  ('United States', 'Grandview Golf Course At Sun City West'),
  ('United States', 'Grandy Nine Golf & Camp'),
  ('United States', 'Grangeville Country Club'),
  ('United States', 'Granite Bay Golf Club'),
  ('United States', 'Granite Fields Golf Club'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Granite Nine'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Milton Nine'),
  ('United States', 'Granite Links Golf Club At Quarry Hills Quincy Nine'),
  ('United States', 'Granliden On Sunapee Golf Course'),
  ('United States', 'Grant Golf Club'),
  ('United States', 'Grant Park Golf Course'),
  ('United States', 'Grantsburg Golf Course'),
  ('United States', 'Grantwood Golf Course'),
  ('United States', 'Grape Ranch Golf Club'),
  ('United States', 'Grass Clippings At Rolling Hills'),
  ('United States', 'Grasslands Golf Country Club'),
  ('United States', 'Grassmere Country Club'),
  ('United States', 'Grassy Creek Golf Country Club'),
  ('United States', 'Grassy Hill Country Club'),
  ('United States', 'Grassy Lane Golf Club'),
  ('United States', 'Grave Yard Homestead At Flat Creek Golf Club'),
  ('United States', 'Gravel Pit'),
  ('United States', 'Gray Eagle Golf Club and Academy'),
  ('United States', 'Gray Plantation'),
  ('United States', 'Grayling Country Club'),
  ('United States', 'Grays Harbor Country Club'),
  ('United States', 'Great Bear Golf Club'),
  ('United States', 'Great Chebeague Golf Club'),
  ('United States', 'Great Cove Golf Course'),
  ('United States', 'Great Cove Golf Recreation'),
  ('United States', 'Great Eagle Golf Club'),
  ('United States', 'Great Gorge Golf Club Lake Quarry Course'),
  ('United States', 'Great Gorge Golf Club Quarry Rail Course'),
  ('United States', 'Great Gorge Golf Club Rail Lake Course'),
  ('United States', 'Great Hope Golf Course'),
  ('United States', 'Great Neck Country Club'),
  ('United States', 'Great Oaks Country Club'),
  ('United States', 'Great Outdoors Rv Golf Resort'),
  ('United States', 'Great River Golf Club'),
  ('United States', 'Great Rock Golf Club'),
  ('United States', 'Great Trail Golf Course'),
  ('United States', 'Greate Bay Golf Club'),
  ('United States', 'Greathorse Golf Course'),
  ('United States', 'Greatlife Golf Fitness Chisholm Trail'),
  ('United States', 'Greatlife Golf Fitness Lebanon'),
  ('United States', 'Greatlife Golf Fitness Salina'),
  ('United States', 'Greeley Country Club'),
  ('United States', 'Greeley County Golf Course'),
  ('United States', 'Green Acres Country Club'),
  ('United States', 'Green Acres Golf Club'),
  ('United States', 'Green Acres Golf Course'),
  ('United States', 'Green Acres Golf Recreation'),
  ('United States', 'Green At Bethpage State Park Golf Course'),
  ('United States', 'Green At Golden Horseshoe Golf Club The'),
  ('United States', 'Green At Tunxis Country Club'),
  ('United States', 'Green Bay Country Club'),
  ('United States', 'Green Brook Country Club'),
  ('United States', 'Green County Golf Association'),
  ('United States', 'Green Crest Golf Course'),
  ('United States', 'Green Gables Golf Course'),
  ('United States', 'Green Harbor Golf Club'),
  ('United States', 'Green Haven Golf Course'),
  ('United States', 'Green Hill Country Club'),
  ('United States', 'Green Hill Golf Club'),
  ('United States', 'Green Hill Golf Course'),
  ('United States', 'Green Hills Country Club'),
  ('United States', 'Green Hills Golf Course'),
  ('United States', 'Green Hills Municipal Golf Course'),
  ('United States', 'Green Island Country Club'),
  ('United States', 'Green Knoll Golf Course'),
  ('United States', 'Green Lakes Golf Course'),
  ('United States', 'Green Lea Golf Course'),
  ('United States', 'Green Mansions Golf Club'),
  ('United States', 'Green Meadow Country Club'),
  ('United States', 'Green Meadows Golf Club'),
  ('United States', 'Green Meadows Golf Course'),
  ('United States', 'Green Mountain National Golf Course'),
  ('United States', 'Green Oaks Country Club'),
  ('United States', 'Green Oaks Golf Club'),
  ('United States', 'Green Oaks Golf Course'),
  ('United States', 'Green Pond Country Club'),
  ('United States', 'Green Red At Sunken Meadow State Park Golf Course'),
  ('United States', 'Green Red At Town Of Colonie Golf Course'),
  ('United States', 'Green Ridge Golf Club'),
  ('United States', 'Green Ridge Public Golf Course'),
  ('United States', 'Green River Country Club'),
  ('United States', 'Green River Golf Club'),
  ('United States', 'Green River Golf Course'),
  ('United States', 'Green Spring Golf Course'),
  ('United States', 'Green Tree Golf Course'),
  ('United States', 'Green Trees Golf Course'),
  ('United States', 'Green Valley'),
  ('United States', 'Green Valley Country Club'),
  ('United States', 'Green Valley Golf Club'),
  ('United States', 'Green Valley Golf Course'),
  ('United States', 'Green Valley Greens Golf Course'),
  ('United States', 'Green Valley Ranch Golf Club'),
  ('United States', 'Green Way Golf Course'),
  ('United States', 'Green White At Wyndemere Country Club'),
  ('United States', 'Green Woods Country Club'),
  ('United States', 'Greenbelt Golf Course'),
  ('United States', 'Greenbriar At Ocean Aire Golf And Country Club')
on conflict (country, name) do nothing;
