insert into public.golf_courses (country, name) values
  ('United States', 'Sycamore Ridge Golf Club'),
  ('United States', 'Sycamore Springs'),
  ('United States', 'Sycamore Springs Golf Course'),
  ('United States', 'Sycamore Valley Golf Course'),
  ('United States', 'Sydney R. Marovitz Golf Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club North South Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club Par 3 Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club South West Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club West North Course'),
  ('United States', 'Sylvan Glen Golf Course'),
  ('United States', 'Sylvan Heights Golf Course'),
  ('United States', 'Sylvan Hills Golf Course'),
  ('United States', 'Sylvania Golf Club'),
  ('United States', 'Syracuse Country Club'),
  ('United States', 'TPC Deere Run'),
  ('United States', 'TPC Michigan'),
  ('United States', 'TPC Twin Cities'),
  ('United States', 'TPC Wisconsin'),
  ('United States', 'Taberna Country Club'),
  ('United States', 'Table Mountain Golf Club'),
  ('United States', 'Tacoma Country Golf Club'),
  ('United States', 'Taconic Golf Club'),
  ('United States', 'Tagalong Golf & Resort'),
  ('United States', 'Tahlequah City Golf Course'),
  ('United States', 'Tahoe City Golf Course'),
  ('United States', 'Tahoe Paradise Golf Course'),
  ('United States', 'Tahoma Valley Golf Country Club'),
  ('United States', 'Talamore Country Club'),
  ('United States', 'Talamore Golf Resort'),
  ('United States', 'Talbot Trail Golf Club'),
  ('United States', 'Talega Golf Club'),
  ('United States', 'Talis Park Golf Club'),
  ('United States', 'Talisker Golf At Tuhaye Golf Course'),
  ('United States', 'Talking Rock Golf Club'),
  ('United States', 'Talking Stick Golf Club Oodham Course'),
  ('United States', 'Talking Stick Golf Club Piipaash Course'),
  ('United States', 'Tall Pines Players Club'),
  ('United States', 'Tall Timber Golf Course'),
  ('United States', 'Tallahatchie Country Club'),
  ('United States', 'Talley Ho Course At Glenview Champions Country Club'),
  ('United States', 'Tallgrass Country Club'),
  ('United States', 'Tallulah Country Club'),
  ('United States', 'Tallwood Country Club'),
  ('United States', 'Tally Mountain Golf Course'),
  ('United States', 'Talon At Grayhawk Golf Club'),
  ('United States', 'Talons of Tuscany Golf Club'),
  ('United States', 'Talonscove At Saratoga Springs'),
  ('United States', 'Tam O''Shanter Country Club'),
  ('United States', 'Tam O''Shanter Golf Course'),
  ('United States', 'Tam Oshanter Golf Country Club'),
  ('United States', 'Tam Oshanter Of Pennsylvania'),
  ('United States', 'Tama Toledo Country Club'),
  ('United States', 'Tamahka Trails'),
  ('United States', 'Tamaqua Golf Course'),
  ('United States', 'Tamarac Golf Course'),
  ('United States', 'Tamarack Country Club'),
  ('United States', 'Tamarack Golf Club'),
  ('United States', 'Tamarack Golf Course'),
  ('United States', 'Tamarack Resort Osprey Meadows Golf Course'),
  ('United States', 'Tamarisk Country Club'),
  ('United States', 'Tamarisk Golf Course'),
  ('United States', 'Tamaron Country Club'),
  ('United States', 'Tamaya Cheena Course At Santa Ana Golf Club'),
  ('United States', 'Tamaya Star Course At Santa Ana Golf Club'),
  ('United States', 'Tameka Woods Golf Course'),
  ('United States', 'Tamer Win Golf & Country Club'),
  ('United States', 'Tampa Bay Golf Country Club'),
  ('United States', 'Tampa Bay Golf Country Club Executive Course'),
  ('United States', 'Tampa Palms Golf Country Club'),
  ('United States', 'Tan Tara Golf Club'),
  ('United States', 'Tanglewood Club'),
  ('United States', 'Tanglewood Golf And Country Club'),
  ('United States', 'Tanglewood Golf Club'),
  ('United States', 'Tanglewood Golf Club Championship Course'),
  ('United States', 'Tanglewood Golf Club Par 3 Course'),
  ('United States', 'Tanglewood Golf Club Reynolds Course'),
  ('United States', 'Tanglewood Golf Course'),
  ('United States', 'Tanglewood Greens'),
  ('United States', 'Tanglewood Manor Golf Club'),
  ('United States', 'Tanglewood Marsh Golf Course'),
  ('United States', 'Tanglewood Resort Hotel And Conference Center'),
  ('United States', 'Tanglewood Shores Golf Country Club'),
  ('United States', 'Tannenbaum Golf Club'),
  ('United States', 'Tannenhauf Golf Club'),
  ('United States', 'Tanner Valley Golf 18 Hole'),
  ('United States', 'Tanner''s Brook'),
  ('United States', 'Tanoan Country Club Acoma Course'),
  ('United States', 'Tanoan Country Club Sandia Course'),
  ('United States', 'Tanoan Country Club Zia Course'),
  ('United States', 'Taos Country Club'),
  ('United States', 'Tapawingo National Golf Club'),
  ('United States', 'Tapps Island Golf Course'),
  ('United States', 'Tara Golf Club At Savannah Lakes'),
  ('United States', 'Tara Golf Country Club'),
  ('United States', 'Tara Greens Golf Center Pitch N Putt'),
  ('United States', 'Tara Hills Country Club'),
  ('United States', 'Tara Hills Golf Course'),
  ('United States', 'Targhee Village Golf Course'),
  ('United States', 'Tarkio Golf Club'),
  ('United States', 'Tarpon Boil At The Villages Executive Golf Trail'),
  ('United States', 'Tarpon Springs Golf Course'),
  ('United States', 'Tarpon Woods Golf Club'),
  ('United States', 'Tarratine Golf Club'),
  ('United States', 'Tarry Brae Golf Course'),
  ('United States', 'Tashua Knolls Golf Club Tashua Glen'),
  ('United States', 'Tashua Knolls Golf Club Tashua Knolls'),
  ('United States', 'Tater Hill Country Club'),
  ('United States', 'Tatnuck Country Club'),
  ('United States', 'Tatum Ranch Golf Club'),
  ('United States', 'Tatum Ridge Golf Links'),
  ('United States', 'Tavistock Country Club'),
  ('United States', 'Tawas Creek Golf Club'),
  ('United States', 'Taylor Meadows Golf Course'),
  ('United States', 'Taylors Creek Golf Course'),
  ('United States', 'Taylors Par 3'),
  ('United States', 'Tazewell County Country Club'),
  ('United States', 'Tchefuncta Country Club'),
  ('United States', 'Teal Bend Golf Club'),
  ('United States', 'Tecolote Canyon Golf Course'),
  ('United States', 'Tecumseh Golf Club'),
  ('United States', 'Ted Makalena Golf Course'),
  ('United States', 'Tedesco Country Club'),
  ('United States', 'Tee Hi Club'),
  ('United States', 'Tee Time Golf Cafe'),
  ('United States', 'Tee Time Golf Complex'),
  ('United States', 'Tee-Hi Golf Course'),
  ('United States', 'Teetering Rocks Executive Links'),
  ('United States', 'Tega Cay Golf Club The Cove'),
  ('United States', 'Tega Cay Golf Club The Grande View'),
  ('United States', 'Tega Cay Golf Club The Pines'),
  ('United States', 'Tehama Golf Club'),
  ('United States', 'Tekoa Country Club'),
  ('United States', 'Tekoa Golf Course'),
  ('United States', 'Teleli Golf Club'),
  ('United States', 'Telemark Golf Course'),
  ('United States', 'Telluride Golf Club'),
  ('United States', 'Temple Terrace Golf Country Club'),
  ('United States', 'Templewood Golf Course'),
  ('United States', 'Tennessee Valley Country Club'),
  ('United States', 'Tepetonka Golf Club'),
  ('United States', 'Tequesta Country Club'),
  ('United States', 'Terra Ceia Bay Golf Tennis Club'),
  ('United States', 'Terra Greens Golf Course'),
  ('United States', 'Terra Verde Golf Course'),
  ('United States', 'Terrace At Saint Clair Country Club'),
  ('United States', 'Terrace Bluff Golf Course'),
  ('United States', 'Terrace Hill Golf Club'),
  ('United States', 'Terrace Hills Golf Course'),
  ('United States', 'Terrace Lakes Resort'),
  ('United States', 'Terrace Park Country Club'),
  ('United States', 'Terrace View Golf Course'),
  ('United States', 'Terradyne Country Club'),
  ('United States', 'Terrapin Hills Country Club'),
  ('United States', 'Terraverde Country Club'),
  ('United States', 'Terravita Golf Club'),
  ('United States', 'Territory Golf Club'),
  ('United States', 'Terry Park Golf Course'),
  ('United States', 'Teton Lakes Golf Course Middle Fork'),
  ('United States', 'Teton Lakes Golf Course North Fork'),
  ('United States', 'Teton Lakes Golf Course South Fork'),
  ('United States', 'Teton Pines Country Club Resort'),
  ('United States', 'Teton Reserve'),
  ('United States', 'Teugega Country Club'),
  ('United States', 'Tewksbury Country Club'),
  ('United States', 'Tex Consolver Municipal Golf Course'),
  ('United States', 'Texarkana Country Club'),
  ('United States', 'Texarkana Golf Ranch'),
  ('United States', 'Thal Acres Golf Course'),
  ('United States', 'Thal Acres Links Lanes'),
  ('United States', 'Thanksgiving Point Golf Club'),
  ('United States', 'Thatcher Golf Course'),
  ('United States', 'Thayer Country Club'),
  ('United States', 'The 1912 Club'),
  ('United States', 'The 500 Club'),
  ('United States', 'The 500 Club Futures Course'),
  ('United States', 'The Abington Club'),
  ('United States', 'The Alpine'),
  ('United States', 'The Amelia River Club'),
  ('United States', 'The Apawamis Club'),
  ('United States', 'The Aquidneck Club'),
  ('United States', 'The Arboretum Club'),
  ('United States', 'The Architects Golf Club'),
  ('United States', 'The Arizona Country Club'),
  ('United States', 'The Arnold Palmer Signature Course At Stonewall Resort'),
  ('United States', 'The Ashford Short Course'),
  ('United States', 'The Atchafalaya At Idlewild'),
  ('United States', 'The Azalea At Pinewild Country Club'),
  ('United States', 'The Back Nine Club'),
  ('United States', 'The Barn Golf Club'),
  ('United States', 'The Bath Golf Club'),
  ('United States', 'The Baths Of Blackwolf Run'),
  ('United States', 'The Bay Club At Mattapoisett'),
  ('United States', 'The Bayonet At Bayonet Black Horse Golf Course'),
  ('United States', 'The Bear Golf Course'),
  ('United States', 'The Bear S Club Par 3 Course'),
  ('United States', 'The Bears Club'),
  ('United States', 'The Beaufort Club'),
  ('United States', 'The Biltmore Golf Course'),
  ('United States', 'The Blandford Golf Tennis Club'),
  ('United States', 'The Bluff Golf Links'),
  ('United States', 'The Bluffs At Coffee Mill'),
  ('United States', 'The Bluffs At The National Golf Club Of Kansas City'),
  ('United States', 'The Bluffs On Thompson Creek'),
  ('United States', 'The Bobcat At Plantation Golf Country Club'),
  ('United States', 'The Boca Raton'),
  ('United States', 'The Bog'),
  ('United States', 'The Bolivar Golf Club'),
  ('United States', 'The Bourne'),
  ('United States', 'The Brassie Golf Club'),
  ('United States', 'The Breakers Ocean Course'),
  ('United States', 'The Breakers Rees Jones Course'),
  ('United States', 'The Bridgehampton Club'),
  ('United States', 'The Bridges'),
  ('United States', 'The Bridges At Beresford'),
  ('United States', 'The Bridges At Rancho Santa Fe'),
  ('United States', 'The Bridges At Springtree Golf Club'),
  ('United States', 'The Bridges Golf Club'),
  ('United States', 'The Bridges Golf Club At Hollywood Casino'),
  ('United States', 'The Bridges Golf Country Club'),
  ('United States', 'The Brookside Club'),
  ('United States', 'The Bucks Club'),
  ('United States', 'The Bull at Pinehurst Farms'),
  ('United States', 'The Calibogue The Haig At Haig Point Club'),
  ('United States', 'The Canyons At Bighorn Golf Club'),
  ('United States', 'The Canyons At Blackjack Ridge'),
  ('United States', 'The Cape Club'),
  ('United States', 'The Cape Club Of Palm City'),
  ('United States', 'The Cape Club Of Sharon'),
  ('United States', 'The Captain''s Club at Woodfield'),
  ('United States', 'The Cardinal By Pete Dye'),
  ('United States', 'The Cascade At Gold Mountain Golf Course'),
  ('United States', 'The Cedars At Dungeness'),
  ('United States', 'The Challenge At Cypress Hills'),
  ('United States', 'The Challenge Golf Club'),
  ('United States', 'The Champion Turf Club At St James'),
  ('United States', 'The Champions Club At Summerfield'),
  ('United States', 'The Chief Golf Course'),
  ('United States', 'The Chimneys Golf Course'),
  ('United States', 'The Classic'),
  ('United States', 'The Classic Club'),
  ('United States', 'The Classic at Madden''s'),
  ('United States', 'The Classics Country Club'),
  ('United States', 'The Cleghorn Club'),
  ('United States', 'The Cliffs At Glassy Golf Course'),
  ('United States', 'The Cliffs At Keowee Falls Golf Course'),
  ('United States', 'The Cliffs At Keowee Springs'),
  ('United States', 'The Cliffs At Keowee Vineyards'),
  ('United States', 'The Cliffs At Mountain Park Golf Course'),
  ('United States', 'The Cliffs At Walnut Cove'),
  ('United States', 'The Cliffs Valley Golf Course'),
  ('United States', 'The Club At Arrowcreek Challenge Course'),
  ('United States', 'The Club At Arrowcreek Legend Course'),
  ('United States', 'The Club At Black Rock 18 Hole Putting Course'),
  ('United States', 'The Club At Black Rock Jim Engh Course'),
  ('United States', 'The Club At Brookstone'),
  ('United States', 'The Club At Clear Creek'),
  ('United States', 'The Club At Crazy Horse Ranch'),
  ('United States', 'The Club At Crested Butte'),
  ('United States', 'The Club At Discovery Harbour'),
  ('United States', 'The Club At Eaglebrooke'),
  ('United States', 'The Club At Emerald Hills'),
  ('United States', 'The Club At Flying Horse'),
  ('United States', 'The Club At Flying Horse North Course'),
  ('United States', 'The Club At Forest Ridge'),
  ('United States', 'The Club At Gateway'),
  ('United States', 'The Club At Grandezza'),
  ('United States', 'The Club At Hokulia'),
  ('United States', 'The Club At Ibis The Heritage Course'),
  ('United States', 'The Club At Ibis The Legend Course'),
  ('United States', 'The Club At Ibis The Tradition Course'),
  ('United States', 'The Club At Irish Creek'),
  ('United States', 'The Club At Kingsmill Woods Course'),
  ('United States', 'The Club At Lake Sinclair'),
  ('United States', 'The Club At Longview'),
  ('United States', 'The Club At Mediterra North Course'),
  ('United States', 'The Club At Mediterra South Course'),
  ('United States', 'The Club At Morningside'),
  ('United States', 'The Club At Nevillewood'),
  ('United States', 'The Club At New Seabury Dunes Course'),
  ('United States', 'The Club At New Seabury Ocean Course'),
  ('United States', 'The Club At Old Hawthorne'),
  ('United States', 'The Club At Olde Cypress'),
  ('United States', 'The Club At Osprey Cove'),
  ('United States', 'The Club At Pelican Bay North Course'),
  ('United States', 'The Club At Pine Forest'),
  ('United States', 'The Club At Pradera'),
  ('United States', 'The Club At Prescott Lakes'),
  ('United States', 'The Club At Ravenna'),
  ('United States', 'The Club At Renaissance'),
  ('United States', 'The Club At River Forest'),
  ('United States', 'The Club At River Wilderness'),
  ('United States', 'The Club At Savannah Harbor'),
  ('United States', 'The Club At Savannah Quarters'),
  ('United States', 'The Club At Seven Canyons'),
  ('United States', 'The Club At Shadow Lakes'),
  ('United States', 'The Club At Shannondell'),
  ('United States', 'The Club At Shepard Hills'),
  ('United States', 'The Club At Silver Lake'),
  ('United States', 'The Club At Snoqualmie Ridge'),
  ('United States', 'The Club At Spanish Peaks'),
  ('United States', 'The Club At Spurwing Challenge Course'),
  ('United States', 'The Club At Spurwing Championship Course'),
  ('United States', 'The Club At Starr Pass Gambler Pioneer'),
  ('United States', 'The Club At Starr Pass Palmer Gambler'),
  ('United States', 'The Club At Starr Pass Pioneer Palmer'),
  ('United States', 'The Club At Stoneridge'),
  ('United States', 'The Club At Sunrise'),
  ('United States', 'The Club At The Highlands'),
  ('United States', 'The Club At The Strand Preserve Savannah Course'),
  ('United States', 'The Club At The Strand Sabal Preserve Course'),
  ('United States', 'The Club At The Strand Savannah Sabal Course'),
  ('United States', 'The Club At Twin Lakes'),
  ('United States', 'The Club At Venetian Bay'),
  ('United States', 'The Club At Viniterra'),
  ('United States', 'The Club At Westminster'),
  ('United States', 'The Club Of Staunton'),
  ('United States', 'The Club Pelican Bay Club Bay Course'),
  ('United States', 'The Club Pelican Bay Club Pelican Course'),
  ('United States', 'The Club Pelican Bay Pelican Bay Course'),
  ('United States', 'The Club Renaissance'),
  ('United States', 'The Club at Lac La Belle'),
  ('United States', 'The Club at Strawberry Creek'),
  ('United States', 'The Club at Tartan Fields'),
  ('United States', 'The Clubs At Arrowhead'),
  ('United States', 'The Clubs At Arrowhead Legend Course'),
  ('United States', 'The College Golf Course At Delhi'),
  ('United States', 'The Colony Golf Country Club'),
  ('United States', 'The Columbia Golf And Country Club'),
  ('United States', 'The Concession Golf Club'),
  ('United States', 'The Concession Golf Club The Gimme Course'),
  ('United States', 'The Country Club'),
  ('United States', 'The Country Club At Dc Ranch'),
  ('United States', 'The Country Club At Lake City'),
  ('United States', 'The Country Club At Soboba Springs'),
  ('United States', 'The Country Club At The Golden Nugget'),
  ('United States', 'The Country Club At Woodmoor'),
  ('United States', 'The Country Club Of Arkansas'),
  ('United States', 'The Country Club Of Colorado At Cheyenne Mountain Resort'),
  ('United States', 'The Country Club Of Greenfield'),
  ('United States', 'The Country Club Of Lexington'),
  ('United States', 'The Country Club Of Louisiana'),
  ('United States', 'The Country Club Of Meadville'),
  ('United States', 'The Country Club Of Mount Dora'),
  ('United States', 'The Country Club Of North Carolina Cardinal Course'),
  ('United States', 'The Country Club Of North Carolina Dogwood Course'),
  ('United States', 'The Country Club Of Orlando'),
  ('United States', 'The Country Club Of Oxford'),
  ('United States', 'The Country Club Of Rancho Bernardo'),
  ('United States', 'The Country Club Of Sapphire Valley'),
  ('United States', 'The Country Club Of South Carolina'),
  ('United States', 'The Country Club Of Spartanburg'),
  ('United States', 'The Country Club Of Troy'),
  ('United States', 'The Country Club Of Virginia James River Course'),
  ('United States', 'The Country Club Of Virginia Tuckahoe Creek Course'),
  ('United States', 'The Country Club Of Virginia Westhampton Course'),
  ('United States', 'The Country Club at Muirfield Village'),
  ('United States', 'The Country Club of Indianapolis'),
  ('United States', 'The Country Club of Saint Albans'),
  ('United States', 'The County Club of Hudson'),
  ('United States', 'The Course At Eagle Mountain'),
  ('United States', 'The Course At Petteys Park'),
  ('United States', 'The Course At River Oaks'),
  ('United States', 'The Course At Wente Vineyards'),
  ('United States', 'The Cove Of Rotonda Golf Center'),
  ('United States', 'The Coves At Round Mountain'),
  ('United States', 'The Creek'),
  ('United States', 'The Creek At Hard Labor State Park'),
  ('United States', 'The Creek At Qualchan Golf Course'),
  ('United States', 'The Creek Golf Club'),
  ('United States', 'The Creeks Golf Rv Resort'),
  ('United States', 'The Crosby Club'),
  ('United States', 'The Crossings'),
  ('United States', 'The Crossings At Carlsbad'),
  ('United States', 'The Crossings At Montevideo'),
  ('United States', 'The Crossings Golf Club'),
  ('United States', 'The Crossings Golf Course'),
  ('United States', 'The Crown Golf Club'),
  ('United States', 'The Currituck Club'),
  ('United States', 'The Cypress At Palm Beach Polo Country Club'),
  ('United States', 'The Dalles Golf Country Club'),
  ('United States', 'The Den at Fox Creek'),
  ('United States', 'The Derby Golf Country Club'),
  ('United States', 'The Divide Golf Club'),
  ('United States', 'The Dogwoods Golf Course At Hugh White State Park'),
  ('United States', 'The Dominion Club'),
  ('United States', 'The Dream GC'),
  ('United States', 'The Duke At Rancho El Dorado'),
  ('United States', 'The Dunes At Maui Lani Golf Course'),
  ('United States', 'The Dunes Club'),
  ('United States', 'The Dunes Golf Beach Club'),
  ('United States', 'The Dunes Golf Tennis Club'),
  ('United States', 'The Dye Preserve Golf Club'),
  ('United States', 'The Eagles Golf Club Forest'),
  ('United States', 'The Eagles Golf Club Lakes'),
  ('United States', 'The East West At Upper Montclair Country Club'),
  ('United States', 'The Eastwood Golf Course & Restaurant'),
  ('United States', 'The Eighteen Hole At Centre Hills Country Club'),
  ('United States', 'The Elks Golf Course At Sandpoint'),
  ('United States', 'The Elms Golf Club'),
  ('United States', 'The Emerald Golf Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'The Emerald Golf Course'),
  ('United States', 'The Estancia Club'),
  ('United States', 'The Evans at Canal Shores'),
  ('United States', 'The Executive At Fore Lakes Golf Course'),
  ('United States', 'The Executive At Victor Hills Golf Club'),
  ('United States', 'The Executive Course At Lakehouse'),
  ('United States', 'The Fairways'),
  ('United States', 'The Fairways At Prestonwood Country Club'),
  ('United States', 'The Fairways at Twin Lakes'),
  ('United States', 'The Fall Line East Course'),
  ('United States', 'The Fall Line Short Course'),
  ('United States', 'The Fall Line West Course'),
  ('United States', 'The Falls Club Of The Palm Beaches'),
  ('United States', 'The Falls Golf Club'),
  ('United States', 'The Falls at Barber Creek'),
  ('United States', 'The Farms Country Club'),
  ('United States', 'The Farms Golf Club'),
  ('United States', 'The Federal Club'),
  ('United States', 'The Fields Golf Club'),
  ('United States', 'The Fields Golf Course'),
  ('United States', 'The First Tee Of Central Arkansas Chairmans Course'),
  ('United States', 'The First Tee Of Central Arkansas Honors Course'),
  ('United States', 'The First Tee Of Fort Smith The Jack Stephens Youth Golf Academy'),
  ('United States', 'The First Tee Of Greater Richmond'),
  ('United States', 'The First Tee Of Hampton Roads'),
  ('United States', 'The First Tee Of Monterey County'),
  ('United States', 'The First Tee Of North Florida Brentwood Golf Course'),
  ('United States', 'The First Tee Of Phoenix'),
  ('United States', 'The First Tee Of The Lowcountry Golf Course'),
  ('United States', 'The First Tee Of Troup County'),
  ('United States', 'The First Tee Syracuse Golf Complex At Butternut Creek'),
  ('United States', 'The First Tee Youth Golf Course'),
  ('United States', 'The Florida Club'),
  ('United States', 'The Floridian'),
  ('United States', 'The Floridian The Harmon Par 3 Course'),
  ('United States', 'The Ford Field River Club'),
  ('United States', 'The Fort Golf Course'),
  ('United States', 'The Fortress Golf Course'),
  ('United States', 'The Founders Golf Club'),
  ('United States', 'The Fountaingrove Club'),
  ('United States', 'The Four Seasons Island Resort'),
  ('United States', 'The Fox Golf Club'),
  ('United States', 'The Fox Valley Club'),
  ('United States', 'The Frog At The Georgian'),
  ('United States', 'The Gailes'),
  ('United States', 'The Gauntlet Golf Club'),
  ('United States', 'The General'),
  ('United States', 'The Georgia Club Chancellors Black Silver Course'),
  ('United States', 'The Georgia Club Chancellors Red Black Course'),
  ('United States', 'The Georgia Club Chancellors Red Silver Course'),
  ('United States', 'The Glacier Golf Course & The Prairie Glen Golf Course'),
  ('United States', 'The Glades Resort'),
  ('United States', 'The Glen Club'),
  ('United States', 'The Glen Golf Park'),
  ('United States', 'The Golden Bear Club At Keene S Point'),
  ('United States', 'The Golf Center At Balloon Fiesta Park'),
  ('United States', 'The Golf Center At Palm Desert'),
  ('United States', 'The Golf Center Par 3 Course'),
  ('United States', 'The Golf Club'),
  ('United States', 'The Golf Club At Bear Dance'),
  ('United States', 'The Golf Club At Blue Heron Hills'),
  ('United States', 'The Golf Club At Bluewater Bay'),
  ('United States', 'The Golf Club At Bradshaw Farm Blue Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm Red Nine'),
  ('United States', 'The Golf Club At Bradshaw Farm White Nine'),
  ('United States', 'The Golf Club At Briars Creek'),
  ('United States', 'The Golf Club At Chaparral Pines'),
  ('United States', 'The Golf Club At Chapel Ridge'),
  ('United States', 'The Golf Club At Cimarron Trails'),
  ('United States', 'The Golf Club At Copper Valley'),
  ('United States', 'The Golf Club At Creighton Farms'),
  ('United States', 'The Golf Club At Devils Tower'),
  ('United States', 'The Golf Club At Dove Mountain Saguaro Tortolita'),
  ('United States', 'The Golf Club At Dove Mountain Tortolita Wild Burro'),
  ('United States', 'The Golf Club At Dove Mountain Wild Burro Saguaro'),
  ('United States', 'The Golf Club At Eagle Creek'),
  ('United States', 'The Golf Club At Equinox'),
  ('United States', 'The Golf Club At Fiddlers Creek'),
  ('United States', 'The Golf Club At Grays Crossing'),
  ('United States', 'The Golf Club At Hawks Prairie The Links'),
  ('United States', 'The Golf Club At Hawks Prairie The Woodlands'),
  ('United States', 'The Golf Club At Hilton Head Lakes'),
  ('United States', 'The Golf Club At Indigo Run'),
  ('United States', 'The Golf Club At Mattaponi Springs'),
  ('United States', 'The Golf Club At Middle Bay'),
  ('United States', 'The Golf Club At Newcastle China Creek Course'),
  ('United States', 'The Golf Club At Newcastle Coal Creek Course'),
  ('United States', 'The Golf Club At North Hampton'),
  ('United States', 'The Golf Club At Oxford Greens'),
  ('United States', 'The Golf Club At Rainmakers'),
  ('United States', 'The Golf Club At Rancho California'),
  ('United States', 'The Golf Club At Redlands Mesa'),
  ('United States', 'The Golf Club At Redmond Ridge'),
  ('United States', 'The Golf Club At Sacconnesset'),
  ('United States', 'The Golf Club At Southport'),
  ('United States', 'The Golf Club At Southwind'),
  ('United States', 'The Golf Club At Star Fort'),
  ('United States', 'The Golf Club At Summerbrooke'),
  ('United States', 'The Golf Club At The Highlands'),
  ('United States', 'The Golf Club At Wyndhurst Manor Club'),
  ('United States', 'The Golf Club Of Bristol'),
  ('United States', 'The Golf Club Of California'),
  ('United States', 'The Golf Club Of Cypress Creek'),
  ('United States', 'The Golf Club Of Fernley'),
  ('United States', 'The Golf Club Of Jupiter'),
  ('United States', 'The Golf Club Of New England'),
  ('United States', 'The Golf Club Of Oklahoma'),
  ('United States', 'The Golf Club Of Purchase'),
  ('United States', 'The Golf Club Of Quincy'),
  ('United States', 'The Golf Club Tierra Oaks'),
  ('United States', 'The Golf Club at Cedar Creek'),
  ('United States', 'The Golf Club at Eagle Pointe'),
  ('United States', 'The Golf Club at Little Turtle'),
  ('United States', 'The Golf Club at Mt. Brighton'),
  ('United States', 'The Golf Club at Stonelick Hills'),
  ('United States', 'The Golf Club at Table Creek'),
  ('United States', 'The Golf Club at Yankee Trace'),
  ('United States', 'The Golf Club of Bucyrus'),
  ('United States', 'The Golf Course at Branch River'),
  ('United States', 'The Golf Course at Camelot'),
  ('United States', 'The Golf Depot'),
  ('United States', 'The Golf Dome'),
  ('United States', 'The Golf Garden Of Destin'),
  ('United States', 'The Golf Lodge At The Quarry'),
  ('United States', 'The Golf Preserve'),
  ('United States', 'The Golf Ranch'),
  ('United States', 'The Golf Village'),
  ('United States', 'The Grand Bear Golf Course'),
  ('United States', 'The Grand Golf Club'),
  ('United States', 'The Greens At Beaumont'),
  ('United States', 'The Greens At Churchill S'),
  ('United States', 'The Greens At Deerfield'),
  ('United States', 'The Greens At Half Hollow'),
  ('United States', 'The Greens At Hamilton Run'),
  ('United States', 'The Greens At North Hills'),
  ('United States', 'The Greens At Tanyard'),
  ('United States', 'The Greens Burns Flat Golf Course'),
  ('United States', 'The Greens Golf Course'),
  ('United States', 'The Greens Of Altus Golf Course'),
  ('United States', 'The Greens Of Greenville'),
  ('United States', 'The Greens On Blossom Way Golf Country Club'),
  ('United States', 'The Grizzly Golf and Social Lodge'),
  ('United States', 'The Grove Country Club'),
  ('United States', 'The Groves Golf And Country Club'),
  ('United States', 'The Groves Golf Course'),
  ('United States', 'The Habitat Golf Course'),
  ('United States', 'The Hamptons Golf Course Lakes Links'),
  ('United States', 'The Hamptons Golf Course Woods Lakes'),
  ('United States', 'The Hamptons Golf Course Woods Links'),
  ('United States', 'The Harbor At Grand Harbor Golf Beach Club'),
  ('United States', 'The Harvester Golf Club'),
  ('United States', 'The Hasentree Club'),
  ('United States', 'The Haven Country Club'),
  ('United States', 'The Havens Country Club'),
  ('United States', 'The Hawk Country Club'),
  ('United States', 'The Hawthorns Golf & Country Club'),
  ('United States', 'The Hayden Lake Country Club'),
  ('United States', 'The Haytm'),
  ('United States', 'The Heather'),
  ('United States', 'The Heathlands'),
  ('United States', 'The Heights Golf Club'),
  ('United States', 'The Heritage At Marion Country Club'),
  ('United States', 'The Heritage Club'),
  ('United States', 'The Heritage Golf Club'),
  ('United States', 'The Hickory At Hamilton Farm'),
  ('United States', 'The Hideaway At Country Greens'),
  ('United States', 'The Hideaway Country Club'),
  ('United States', 'The Hideout'),
  ('United States', 'The Hideout Golf Club'),
  ('United States', 'The Highland Course At Primland Resort'),
  ('United States', 'The Highlands'),
  ('United States', 'The Highlands At Hamilton Farm'),
  ('United States', 'The Highlands At Prestonwood Country Club'),
  ('United States', 'The Highlands Golf Club At Fisher Mountain'),
  ('United States', 'The Highlands Golf Course'),
  ('United States', 'The Hill At Blacksburg Municipal Golf Course'),
  ('United States', 'The Hills At Portal Golf Club'),
  ('United States', 'The Hills Course At Red Hawk'),
  ('United States', 'The Hills Golf Club at McKendree University'),
  ('United States', 'The Hollows Golf Club Cottage Road'),
  ('United States', 'The Hollows Golf Club Lake Cottage'),
  ('United States', 'The Hollows Golf Club Lake Road'),
  ('United States', 'The Holly At Pinewild Country Club'),
  ('United States', 'The Home Course'),
  ('United States', 'The Homestead Golf Course'),
  ('United States', 'The Honors Course'),
  ('United States', 'The Hoop Loop At Tsatsu Dunes'),
  ('United States', 'The Idaho Club'),
  ('United States', 'The Inn At Pocono Manor East Course'),
  ('United States', 'The Inn Golf Course'),
  ('United States', 'The Institute Llc'),
  ('United States', 'The Island Country Club'),
  ('United States', 'The Jay Lionel Hebert Municipal Golf Course'),
  ('United States', 'The Jayhawk Club'),
  ('United States', 'The Jewel Golf Club'),
  ('United States', 'The Jewel of Grand Blanc'),
  ('United States', 'The Kaddyshack Par 3 Golf Course'),
  ('United States', 'The Kanawha Club'),
  ('United States', 'The King And Prince Beach Golf Resort'),
  ('United States', 'The Kingsley Club'),
  ('United States', 'The Kittansett Club'),
  ('United States', 'The Knolls Golf Course'),
  ('United States', 'The Lake Club'),
  ('United States', 'The Lakes'),
  ('United States', 'The Lakes At Ahwatukee'),
  ('United States', 'The Lakes Country Club'),
  ('United States', 'The Lakes Course At Red Hawk'),
  ('United States', 'The Lakes Golf & Country Club'),
  ('United States', 'The Lakes Golf Club'),
  ('United States', 'The Lakes Golf Course'),
  ('United States', 'The Lamberts Point Golf Course'),
  ('United States', 'The Landing At Fort Harrison'),
  ('United States', 'The Landing At Pleasant Point'),
  ('United States', 'The Landing Golf Course'),
  ('United States', 'The Landings Club Deer Creek Course'),
  ('United States', 'The Landings Club Magnolia Course'),
  ('United States', 'The Landings Club Marshwood Course'),
  ('United States', 'The Landings Club Oakridge Course'),
  ('United States', 'The Landings Club Palmetto Course'),
  ('United States', 'The Landings Club Terrapin Point Course'),
  ('United States', 'The Landings Golf Club Trestle Bluff'),
  ('United States', 'The Ledgend'),
  ('United States', 'The Ledges'),
  ('United States', 'The Ledges Golf Club'),
  ('United States', 'The Leelanau Club at Bahle Farms'),
  ('United States', 'The Legacy'),
  ('United States', 'The Legacy Golf Club'),
  ('United States', 'The Legacy Golf Tennis Club Championship Course'),
  ('United States', 'The Legacy Golf Tennis Club Executive Course'),
  ('United States', 'The Legacy Resort At Frenchman Hills'),
  ('United States', 'The Legend Golf Course'),
  ('United States', 'The Legend at Bergamont'),
  ('United States', 'The Legend at Brandybrook'),
  ('United States', 'The Legend at Bristlecone'),
  ('United States', 'The Legend at Merrill Hills'),
  ('United States', 'The Legends At Chateau Elan'),
  ('United States', 'The Legends At Orange Lake Resort'),
  ('United States', 'The Legends Golf Club'),
  ('United States', 'The Legends Golf Course At Parris Island'),
  ('United States', 'The Legends of Massillon'),
  ('United States', 'The Lincoln Hills Golf Club Hills Course'),
  ('United States', 'The Lincoln Hills Golf Club Orchard Course'),
  ('United States', 'The Links At Audubon'),
  ('United States', 'The Links At Bodega Harbour'),
  ('United States', 'The Links At Boynton Beach Championship Course'),
  ('United States', 'The Links At Boynton Beach The Family Course'),
  ('United States', 'The Links At Brick Landing'),
  ('United States', 'The Links At Cadron Valley Golf Country Club'),
  ('United States', 'The Links At Cobble Creek'),
  ('United States', 'The Links At Cotton Valley Golf Club'),
  ('United States', 'The Links At Dardenne'),
  ('United States', 'The Links At Davy Crockett'),
  ('United States', 'The Links At Erie Village'),
  ('United States', 'The Links At Everline'),
  ('United States', 'The Links At Fayetteville Golf Country Club'),
  ('United States', 'The Links At Fort Smith Golf Athletic Club'),
  ('United States', 'The Links At Fox Meadows'),
  ('United States', 'The Links At Galloway'),
  ('United States', 'The Links At Grandview'),
  ('United States', 'The Links At Greenfield Plantation'),
  ('United States', 'The Links At Greystone'),
  ('United States', 'The Links At Hampton Cove'),
  ('United States', 'The Links At Harrison Golf Athletic Club'),
  ('United States', 'The Links At Hemlock Creek'),
  ('United States', 'The Links At Hiawatha Landing'),
  ('United States', 'The Links At Ivy Ridge'),
  ('United States', 'The Links At Jonesboro Golf Athletic Club'),
  ('United States', 'The Links At Kansas Golf Club'),
  ('United States', 'The Links At Kiley Ranch'),
  ('United States', 'The Links At Labelle Winery'),
  ('United States', 'The Links At Lake Toccoa'),
  ('United States', 'The Links At Lakehouse'),
  ('United States', 'The Links At Lang Farm'),
  ('United States', 'The Links At Lighthouse Sound'),
  ('United States', 'The Links At Moses Pointe'),
  ('United States', 'The Links At Mulberry Hill'),
  ('United States', 'The Links At Muny'),
  ('United States', 'The Links At Mustang Creek Golf Country Club'),
  ('United States', 'The Links At Oklahoma City Golf Athletic Club'),
  ('United States', 'The Links At Outlook'),
  ('United States', 'The Links At Overlake'),
  ('United States', 'The Links At Overton Park'),
  ('United States', 'The Links At Oxford Golf Country Club'),
  ('United States', 'The Links At Pine Hill'),
  ('United States', 'The Links At Poland Spring Resort'),
  ('United States', 'The Links At Pretty Prairie'),
  ('United States', 'The Links At Rainbow Curve Golf Country Club'),
  ('United States', 'The Links At Rising Star Casino'),
  ('United States', 'The Links At Riverside'),
  ('United States', 'The Links At Rolling Hills'),
  ('United States', 'The Links At Rolling Meadows'),
  ('United States', 'The Links At Sleepy Ridge'),
  ('United States', 'The Links At Spanish Baytm'),
  ('United States', 'The Links At Spring Church'),
  ('United States', 'The Links At Springdale Golf Country Club'),
  ('United States', 'The Links At Starkville Golf Country Club'),
  ('United States', 'The Links At Stillwater Golf Country Club'),
  ('United States', 'The Links At Stono Ferry'),
  ('United States', 'The Links At Summerly'),
  ('United States', 'The Links At Terranea'),
  ('United States', 'The Links At Teton Peaks'),
  ('United States', 'The Links At Texarkana Golf Athletic Club'),
  ('United States', 'The Links At The Rock Golf Country Club'),
  ('United States', 'The Links At Union Vale'),
  ('United States', 'The Links At Valley Fields'),
  ('United States', 'The Links At Whitehaven'),
  ('United States', 'The Links At Woodcliff'),
  ('United States', 'The Links Golf Club'),
  ('United States', 'The Links Golf Club At Queen Creek'),
  ('United States', 'The Links Golf Course'),
  ('United States', 'The Links Indoor Golf'),
  ('United States', 'The Links Of Madison County Golf Country Club'),
  ('United States', 'The Links Of Naples'),
  ('United States', 'The Links Of North Dakota'),
  ('United States', 'The Links On Memorial Golf Athletic Club'),
  ('United States', 'The Links at Bowen Lake'),
  ('United States', 'The Links at Crystal Lake'),
  ('United States', 'The Links at Ireland Grove'),
  ('United States', 'The Links at Rising Star Casino Resort'),
  ('United States', 'The Links by the Tracks'),
  ('United States', 'The Links of Jacksonville'),
  ('United States', 'The Links of Novi'),
  ('United States', 'The Little Club'),
  ('United States', 'The Little Course'),
  ('United States', 'The Lodge Golf Course'),
  ('United States', 'The Loma Club'),
  ('United States', 'The Loon Golf Resort'),
  ('United States', 'The Loop at Chaska'),
  ('United States', 'The Lynx At River Bend Golf Club'),
  ('United States', 'The Madison Club'),
  ('United States', 'The Magnolia At Pinewild Country Club'),
  ('United States', 'The Majors Golf Club At Bayside Lakes'),
  ('United States', 'The Manor Golf And Country Club'),
  ('United States', 'The Manor Golf Club'),
  ('United States', 'The Meadow At Peabody'),
  ('United States', 'The Meadows'),
  ('United States', 'The Meadows At Countrywood'),
  ('United States', 'The Meadows At Middlesex Golf Club'),
  ('United States', 'The Meadows At Prestonwood Country Club'),
  ('United States', 'The Meadows Country Club'),
  ('United States', 'The Meadows Golf And Country Club'),
  ('United States', 'The Meadows at Grand Valley State University'),
  ('United States', 'The Meadows of Six Mile Creek Golf Course'),
  ('United States', 'The Medalist Golf Club'),
  ('United States', 'The Members Club At Aldarra'),
  ('United States', 'The Members Club At Wildewood'),
  ('United States', 'The Members Club At Woodcreek'),
  ('United States', 'The Metropolitan Golf Links'),
  ('United States', 'The Mill Course'),
  ('United States', 'The Milton Hoosic Club'),
  ('United States', 'The Minikahda Club'),
  ('United States', 'The Mission Club'),
  ('United States', 'The Montrose Club'),
  ('United States', 'The Monument'),
  ('United States', 'The Moor'),
  ('United States', 'The Moor At The Highlands Boyne'),
  ('United States', 'The Moorings Yacht Country Club Hawks Nest'),
  ('United States', 'The Moorings Yacht Country Club Moorings Course'),
  ('United States', 'The Mountain At Christmans Windham House'),
  ('United States', 'The Mountain Course At Spruce Peak'),
  ('United States', 'The Mountains At Bighorn Golf Club'),
  ('United States', 'The Myth'),
  ('United States', 'The National'),
  ('United States', 'The National Golf Club Of Louisiana'),
  ('United States', 'The National Golf Country Club'),
  ('United States', 'The National Golf Course at Eagle Creek'),
  ('United States', 'The Natural at Beaver Creek Resort'),
  ('United States', 'The Neuse Golf Club'),
  ('United States', 'The New England Country Club'),
  ('United States', 'The New Vineyards Golf Course'),
  ('United States', 'The Nightmare GC'),
  ('United States', 'The Nine Hole At Augusta National Golf Club'),
  ('United States', 'The Nine Hole At Centre Hills Country Club'),
  ('United States', 'The Nine Hole Par 3 At Bel Aire Golf Club'),
  ('United States', 'The North At Goodwin Golf Course'),
  ('United States', 'The Oaks'),
  ('United States', 'The Oaks At Margaritaville Lake Resort'),
  ('United States', 'The Oaks At Spanish Fork'),
  ('United States', 'The Oaks Club At Valencia'),
  ('United States', 'The Oaks Club Eagle Course'),
  ('United States', 'The Oaks Club Heron Course'),
  ('United States', 'The Oaks Course'),
  ('United States', 'The Oaks Golf Club'),
  ('United States', 'The Oaks Golf Course'),
  ('United States', 'The Oaks Golf Links'),
  ('United States', 'The Oaks at Kincheloe'),
  ('United States', 'The Oasis'),
  ('United States', 'The Ocean Course At Hokuala'),
  ('United States', 'The Ocean Course At Kiawah Island Golf Resort'),
  ('United States', 'The Ocean North At Pelican Hill Golf Club'),
  ('United States', 'The Ocean South At Pelican Hill Golf Club'),
  ('United States', 'The Old Collier Golf Club'),
  ('United States', 'The Old Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Olde Farm Golf Club'),
  ('United States', 'The Olympic At Gold Mountain Golf Course'),
  ('United States', 'The Olympic Club Cliffs Course'),
  ('United States', 'The Olympic Club Lake Course'),
  ('United States', 'The Olympic Club Ocean Course'),
  ('United States', 'The Omni Grove Park Inn'),
  ('United States', 'The Omni Homestead Resort Spa Cascades Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'The Omni Homestead Resort Spa Old Course'),
  ('United States', 'The Orchards At Egg Harbor'),
  ('United States', 'The Orchards Golf Club'),
  ('United States', 'The Orchards Golf Course'),
  ('United States', 'The Osprey At Haig Point Club'),
  ('United States', 'The Outlaw At Alto Lakes'),
  ('United States', 'The Palencia Club'),
  ('United States', 'The Palisades Country Club'),
  ('United States', 'The Palms Course'),
  ('United States', 'The Palms Golf Club'),
  ('United States', 'The Palms Golf Club At Forest Lakes'),
  ('United States', 'The Panther At Plantation Golf Country Club'),
  ('United States', 'The Par 3 At Pipestem State Park Resort'),
  ('United States', 'The Park Country Club'),
  ('United States', 'The Park West Palm'),
  ('United States', 'The Park West Palm The Lit 9'),
  ('United States', 'The Patriot Golf Club At Grand Harbor'),
  ('United States', 'The Pearl Club'),
  ('United States', 'The Pearl Golf Links East Course'),
  ('United States', 'The Pearl Golf Links North Course'),
  ('United States', 'The Pearl Golf Links West Course'),
  ('United States', 'The Peninsula Club'),
  ('United States', 'The Peninsula On The Indian River Bay Golf Club'),
  ('United States', 'The Pheasant Golf Links Front Back Course'),
  ('United States', 'The Pheasant Golf Links Roc Course'),
  ('United States', 'The Phoenician Golf Club'),
  ('United States', 'The Piedmont Club'),
  ('United States', 'The Pines'),
  ('United States', 'The Pines At Elizabeth City'),
  ('United States', 'The Pines At Lindsey Wilson'),
  ('United States', 'The Pines At North Park'),
  ('United States', 'The Pines Country Club'),
  ('United States', 'The Pines Golf Club'),
  ('United States', 'The Pines Golf Course'),
  ('United States', 'The Pines Golf Course At Fort Eustis Ponderosa Pines Shortleaf Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Ponderosa Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Shortleaf Pines'),
  ('United States', 'The Pines Of Chatom Golf Course'),
  ('United States', 'The Plantation Course At Edisto'),
  ('United States', 'The Plantation Golf And Country Club'),
  ('United States', 'The Plantation Golf Club Cranes Roost Course'),
  ('United States', 'The Plantation Golf Club Otter Creek Course'),
  ('United States', 'The Plateau Club'),
  ('United States', 'The Players Club'),
  ('United States', 'The Players Club at Foxfire'),
  ('United States', 'The Players Club at Woodland Trails'),
  ('United States', 'The Players Course At Wyboo'),
  ('United States', 'The Poconos Club'),
  ('United States', 'The Pointe Golf Club'),
  ('United States', 'The Pointe Golf Course'),
  ('United States', 'The Pointe Golf Event Center'),
  ('United States', 'The Polo Fields - Ann Arbor'),
  ('United States', 'The Ponds at Battle Creek'),
  ('United States', 'The Powder Horn Golf Club Eagle Nine'),
  ('United States', 'The Powder Horn Golf Club Mountain Nine'),
  ('United States', 'The Powder Horn Golf Club Stag Nine'),
  ('United States', 'The Practice Center - Clear Creek'),
  ('United States', 'The Practice Tee At Sunset Hills'),
  ('United States', 'The Prairie Club Dunes Course'),
  ('United States', 'The Prairie Club Horse Course'),
  ('United States', 'The Prairies Golf Club'),
  ('United States', 'The Prairies Golf Course'),
  ('United States', 'The Preserve'),
  ('United States', 'The Preserve At Boulder Hills'),
  ('United States', 'The Preserve At Ironhorse'),
  ('United States', 'The Preserve At Jordan Lake Golf Club'),
  ('United States', 'The Preserve At Oak Meadows'),
  ('United States', 'The Preserve At Turnbull Bay'),
  ('United States', 'The Preserve At Verdae'),
  ('United States', 'The Preserve Golf Club'),
  ('United States', 'The Preserve On Rathbun Lake'),
  ('United States', 'The Preserve at Oak Meadows'),
  ('United States', 'The Quarry'),
  ('United States', 'The Quarry At La Quinta'),
  ('United States', 'The Quarry At La Quinta Short Course'),
  ('United States', 'The Quarry Golf Club'),
  ('United States', 'The Quarry at Crystal Springs'),
  ('United States', 'The Quechee Club Highland Course'),
  ('United States', 'The Quechee Club Lakeland Course'),
  ('United States', 'The Quest Golf Club'),
  ('United States', 'The Rail Golf Course'),
  ('United States', 'The Ranch At Laguna Beach'),
  ('United States', 'The Ranch Club'),
  ('United States', 'The Ranch Country Club'),
  ('United States', 'The Ranch Golf Club'),
  ('United States', 'The Ranches Golf Club'),
  ('United States', 'The Raven Golf Club At Three Peaks'),
  ('United States', 'The Ravines Golf Course'),
  ('United States', 'The Refuge Golf Course'),
  ('United States', 'The Reserve At Lake Keowee'),
  ('United States', 'The Reserve At Moonlight Basin Golf Club'),
  ('United States', 'The Reserve At Orange Lake Resort'),
  ('United States', 'The Reserve At Spanos Park'),
  ('United States', 'The Reserve Club'),
  ('United States', 'The Reserve Club At Woodside Plantation Hollow Creek Course'),
  ('United States', 'The Reserve Club At Woodside Plantation The Reserve Course'),
  ('United States', 'The Reserve Golf Club'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Blue Heron Red Hawk'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Red Hawk White Egret'),
  ('United States', 'The Resort At Longboat Key Club Harbourside White Egret Blue Heron'),
  ('United States', 'The Resort At Longboat Key Club Links On Longboat'),
  ('United States', 'The Retreat'),
  ('United States', 'The Revenge'),
  ('United States', 'The Revival Golf Club At The Crescent'),
  ('United States', 'The Ridge'),
  ('United States', 'The Ridge At Back Brook'),
  ('United States', 'The Ridge At Castle Pines Colorado'),
  ('United States', 'The Ridge Country Club'),
  ('United States', 'The Ridge Golf Club'),
  ('United States', 'The Ridge Golf Course Events Center'),
  ('United States', 'The Ridges At Village Creek North Ridge East Ridge'),
  ('United States', 'The Ridges At Village Creek North Ridge West Ridge'),
  ('United States', 'The Ridges At Village Creek West Ridge East Ridge'),
  ('United States', 'The Ridges Golf Course'),
  ('United States', 'The Rim Golf Club'),
  ('United States', 'The Ritz Carlton Golf Club Orlando Grande Lakes'),
  ('United States', 'The River At Grand Harbor Golf Beach Club'),
  ('United States', 'The River Club'),
  ('United States', 'The River Club Golf Course'),
  ('United States', 'The River Course At Keystone'),
  ('United States', 'The River Golf Club'),
  ('United States', 'The River Golf Course, Inc.'),
  ('United States', 'The Rivercrest Golf Club And Preserve'),
  ('United States', 'The Riverside Club of West Virginia'),
  ('United States', 'The Riviera Country Club'),
  ('United States', 'The Rock Golf Club'),
  ('United States', 'The Rock Golf Club Resort'),
  ('United States', 'The Rock Golf Course'),
  ('United States', 'The Rockland Farm Course At Shenandoah Valley'),
  ('United States', 'The Rookery At Marco'),
  ('United States', 'The Rookery South'),
  ('United States', 'The Rose Golf Course'),
  ('United States', 'The Royal'),
  ('United States', 'The Royal Ancient Chappaquiddick Links'),
  ('United States', 'The Royal Virginian Golf Course'),
  ('United States', 'The Running Y Ranch Golf Course'),
  ('United States', 'The Saddle At Glencove'),
  ('United States', 'The Saints At Port St Lucie'),
  ('United States', 'The Salt Pond Golf Club'),
  ('United States', 'The Sanctuary'),
  ('United States', 'The Sanctuary Golf Club'),
  ('United States', 'The Sanctuary Golf Course At Pennbrooke Fairways'),
  ('United States', 'The Sands Golf Rv Resort'),
  ('United States', 'The Santaluz Club'),
  ('United States', 'The Savannah Golf Club'),
  ('United States', 'The Savannahs Golf Course'),
  ('United States', 'The Sawmill Golf Club'),
  ('United States', 'The Schoolhouse Nine'),
  ('United States', 'The Sea Ranch Golf Links'),
  ('United States', 'The Sedgewood Golf Club'),
  ('United States', 'The Senator Course At Shulas Golf Club'),
  ('United States', 'The Serradella'),
  ('United States', 'The Shoe Course At Golden Horseshoe Golf Club'),
  ('United States', 'The Shore Club'),
  ('United States', 'The Shores Of North River Golf Club'),
  ('United States', 'The Sidewinder Golf Course'),
  ('United States', 'The Silverleaf Golf Club'),
  ('United States', 'The Sound Golf Links At Albemarle Plantation'),
  ('United States', 'The South East At Upper Montclair Country Club'),
  ('United States', 'The Springs At Borrego'),
  ('United States', 'The Springs Club'),
  ('United States', 'The Spruce Creek Preserve Golf Club'),
  ('United States', 'The St Anne S Club'),
  ('United States', 'The Stadium Course At Pga West'),
  ('United States', 'The Summit'),
  ('United States', 'The Summit Club'),
  ('United States', 'The Swan Golf Country Club'),
  ('United States', 'The Tamaracks Golf Course'),
  ('United States', 'The Tattersall Youth Development Center At The First Tee Chesterfield Golf Course'),
  ('United States', 'The Territory'),
  ('United States', 'The Tesoro Club Palmer Course'),
  ('United States', 'The Tesoro Club Watson Course'),
  ('United States', 'The Third Golf Course'),
  ('United States', 'The Tillery Tradition Country Club'),
  ('United States', 'The Timbers Golf Club'),
  ('United States', 'The Titus Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Tradition Golf Club'),
  ('United States', 'The Traditional'),
  ('United States', 'The Trails Golf Club'),
  ('United States', 'The Tree Farm'),
  ('United States', 'The Tribute'),
  ('United States', 'The Trophy Club Of Apalachee'),
  ('United States', 'The Trophy Club Of Atlanta'),
  ('United States', 'The Tuxedo Club'),
  ('United States', 'The Valley At Eastport Golf Club'),
  ('United States', 'The Valley Club North Course'),
  ('United States', 'The Valley Club South Course'),
  ('United States', 'The Valley Club West Course'),
  ('United States', 'The Valley Golf Course'),
  ('United States', 'The Views Golf Club At Oro Valley'),
  ('United States', 'The Village Course At Waikoloa'),
  ('United States', 'The Village Of Fenney Gray Fox Course'),
  ('United States', 'The Village Of Fenney Red Fox Course'),
  ('United States', 'The Vineyard At Escondido'),
  ('United States', 'The Vineyards Golf Club'),
  ('United States', 'The Vintage At Staples'),
  ('United States', 'The Vintage Club Desert Course'),
  ('United States', 'The Vintage Club Mountain Course'),
  ('United States', 'The Virginian Golf Club'),
  ('United States', 'The Virtues Golf Club'),
  ('United States', 'The Vue'),
  ('United States', 'The Walker Golf Course At Clemson University'),
  ('United States', 'The Wanderers Club At Wellington'),
  ('United States', 'The Water S Edge Country Club'),
  ('United States', 'The Waterfront Country Club'),
  ('United States', 'The Wedgewood Club'),
  ('United States', 'The West South At Upper Montclair Country Club'),
  ('United States', 'The Wetlands Golf Course'),
  ('United States', 'The Wilderness at Fortune Bay'),
  ('United States', 'The Wilds'),
  ('United States', 'The Willows At Runk Pratt'),
  ('United States', 'The Windermere Club'),
  ('United States', 'The Wizard Golf Course'),
  ('United States', 'The Wolf At Tenkiller'),
  ('United States', 'The Wolverine Golf Course'),
  ('United States', 'The Wood'),
  ('United States', 'The Woodlands Golf Club'),
  ('United States', 'The Woodlands Golf Country Club'),
  ('United States', 'The Woods Golf Club'),
  ('United States', 'The Woods Of Westminster'),
  ('United States', 'The Woods Resort Mountain View Course'),
  ('United States', 'The Woods Resort Stony Lick Course'),
  ('United States', 'The Woods at Possum Run'),
  ('United States', 'The Wyndgate'),
  ('United States', 'The Yards'),
  ('United States', 'Thendara Golf Club'),
  ('United States', 'Theodore Wirth Golf Course'),
  ('United States', 'Third First At Lake Venice Golf Club'),
  ('United States', 'Third Nine At Edison Club The'),
  ('United States', 'Third Nine At Montclair Golf Club'),
  ('United States', 'Third Nine At Pleasant Valley Country Club'),
  ('United States', 'Third Nine First Nine At Bermuda Dunes Country Club'),
  ('United States', 'Thistle Foxglove At Resort At The Mountain The'),
  ('United States', 'Thistle Golf Club Cameron Course'),
  ('United States', 'Thistle Golf Club Mackay Course'),
  ('United States', 'Thistle Golf Club Stewart Course'),
  ('United States', 'Thomas Memorial Golf Country Club'),
  ('United States', 'Thomson Country Club'),
  ('United States', 'Thorn Apple Country Club'),
  ('United States', 'Thorn Spring Golf Course'),
  ('United States', 'Thornberry Creek Country Club'),
  ('United States', 'Thornblade Club'),
  ('United States', 'Thorncreek Golf Club'),
  ('United States', 'Thorndale Country Club'),
  ('United States', 'Thorne Hills Golf Course'),
  ('United States', 'Thornhurst Country Club'),
  ('United States', 'Thorny Lea Golf Club'),
  ('United States', 'Thoroughbred Golf Club'),
  ('United States', 'Thousand Acres Golf Club'),
  ('United States', 'Thousand Hills Resort Golf Club'),
  ('United States', 'Thousand Islands Country Club The Lake Course'),
  ('United States', 'Thousand Islands Country Club The Old Course'),
  ('United States', 'Thousand Oaks Golf Club'),
  ('United States', 'Three Crowns Golf Club'),
  ('United States', 'Three Eagles Golf Course'),
  ('United States', 'Three Elms Golf Course'),
  ('United States', 'Three Lakes Golf Course'),
  ('United States', 'Three Pines Country Club'),
  ('United States', 'Three Ponds Farm'),
  ('United States', 'Three Ponds Golf Club'),
  ('United States', 'Three Rivers Country Club'),
  ('United States', 'Three Rivers Golf Course'),
  ('United States', 'Three Sticks Golf Club'),
  ('United States', 'Thumper Pond'),
  ('United States', 'Thunder Bay Resort'),
  ('United States', 'Thunder Bayou Golf Links'),
  ('United States', 'Thunder Hills Country Club'),
  ('United States', 'Thunder Mountain Ranch Buckaroo Greens'),
  ('United States', 'Thunderbird At Spring Lake Golf Club'),
  ('United States', 'Thunderbird Country Club'),
  ('United States', 'Thunderbird Driving Range'),
  ('United States', 'Thunderbird Golf Course Resort'),
  ('United States', 'Thunderbird North'),
  ('United States', 'Thunderbird South'),
  ('United States', 'Thunderbolt Pass Golf Course'),
  ('United States', 'Thunderhart Golf Course'),
  ('United States', 'Thunderhawk Golf Club'),
  ('United States', 'Thundering Waters Golf Club'),
  ('United States', 'Tianna Country Club'),
  ('United States', 'Tiara Rado Golf Course'),
  ('United States', 'Tiburon Golf Club The Black Course'),
  ('United States', 'Tiburon Golf Club The Gold Course'),
  ('United States', 'Tiburon Golf Course'),
  ('United States', 'Ticonderoga Country Club'),
  ('United States', 'Tidelands Golf Country Club'),
  ('United States', 'Tidewater Golf Club'),
  ('United States', 'Tierra Del Sol Golf Club'),
  ('United States', 'Tierra Del Sol Golf Country Club'),
  ('United States', 'Tierra Del Sol Golf Course'),
  ('United States', 'Tierra Grande Country Club'),
  ('United States', 'Tierra Rejada Golf Club'),
  ('United States', 'Tiffany Greens Golf Club'),
  ('United States', 'Tiger Point Golf Club'),
  ('United States', 'Tigers Eye Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Tijeras Arroyo Golf Course'),
  ('United States', 'Tijeras Creek Golf Club'),
  ('United States', 'Tilbury Golf Course'),
  ('United States', 'Tilden Park Golf Course'),
  ('United States', 'Timber Banks Golf Club Marina'),
  ('United States', 'Timber City Golf Course'),
  ('United States', 'Timber Creek'),
  ('United States', 'Timber Creek Golf'),
  ('United States', 'Timber Creek Golf Course'),
  ('United States', 'Timber Creek Golf Course Lakes Oaks'),
  ('United States', 'Timber Creek Golf Course Sierra Pines'),
  ('United States', 'Timber Greens Country Club'),
  ('United States', 'Timber Lake Club'),
  ('United States', 'Timber Lake Golf Course'),
  ('United States', 'Timber Pines The Grand Pines Course'),
  ('United States', 'Timber Pines The Highlands Course'),
  ('United States', 'Timber Pines The Hills Course'),
  ('United States', 'Timber Pines The Lakes Course'),
  ('United States', 'Timber Ridge Golf Club'),
  ('United States', 'Timber Terrace Golf Course'),
  ('United States', 'Timber Trace Golf Club'),
  ('United States', 'Timber Trails Golf Club'),
  ('United States', 'Timber Truss Golf Course'),
  ('United States', 'Timber Wolf Golf Club'),
  ('United States', 'Timbergate Golf Course'),
  ('United States', 'Timberlake Country Club'),
  ('United States', 'Timberlake Golf Club'),
  ('United States', 'Timberlane Golf Recreation'),
  ('United States', 'Timberlin Golf Club'),
  ('United States', 'Timberline Golf Course'),
  ('United States', 'Timberline Short Nine'),
  ('United States', 'Timberlink Golf Course'),
  ('United States', 'Timberon Golf Country Club'),
  ('United States', 'Timberstone'),
  ('United States', 'Timberstone Golf Course'),
  ('United States', 'Timberton Golf Club'),
  ('United States', 'Timberview Golf Club'),
  ('United States', 'Timberwood Golf Club'),
  ('United States', 'Timpanogos Golf Club The Championship Course'),
  ('United States', 'Timpanogos Golf Club The Pasture Executive Course'),
  ('United States', 'Timuquana Country Club'),
  ('United States', 'Tin Cup Golf Driving Range'),
  ('United States', 'Tincap Golf Club'),
  ('United States', 'Tinker Afb Golf Course'),
  ('United States', 'Tioga Golf Club'),
  ('United States', 'Tippecanoe Country Club'),
  ('United States', 'Tippecanoe Lake Country Club'),
  ('United States', 'Tipsinah Mounds'),
  ('United States', 'Tipton Golf and Country Club'),
  ('United States', 'Tipton Municipal Golf Course'),
  ('United States', 'Tired Creek Golf Course'),
  ('United States', 'Tishomingo Golf Course'),
  ('United States', 'Toad Valley Golf Course'),
  ('United States', 'Toana Vista Golf Course'),
  ('United States', 'Tobacco Road Golf Club'),
  ('United States', 'Todd Creek Golf Club'),
  ('United States', 'Toddy Brook Golf Course'),
  ('United States', 'Toftrees Resort'),
  ('United States', 'Toiyabe Golf Club'),
  ('United States', 'Toka Sticks Golf Club'),
  ('United States', 'Toledo Country Club'),
  ('United States', 'Tom & Jerry''s Mini Golf'),
  ('United States', 'Tom Oleary Golf Club'),
  ('United States', 'Tomah VA Veterans Golf Course'),
  ('United States', 'Tomahawk Hills Golf Course'),
  ('United States', 'Tommy Jacobs Bel Air Greens'),
  ('United States', 'Toms River Country Club'),
  ('United States', 'Toms Run At Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Toomey Flynn At Huntingdon Valley Country Club'),
  ('United States', 'Tooth 9 Hole Course At Orange County National'),
  ('United States', 'Top Of The Rock Golf Course'),
  ('United States', 'Top Of The World Golf Course'),
  ('United States', 'Topeka Country Club'),
  ('United States', 'Topstone Golf Course'),
  ('United States', 'Torch'),
  ('United States', 'Torreon Golf Club Cabin Course'),
  ('United States', 'Torreon Golf Club Tower Course'),
  ('United States', 'Torres Blancas Golf Club'),
  ('United States', 'Torrey Oaks Rv And Golf Resort'),
  ('United States', 'Torri Erinn At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Torrington Country Club'),
  ('United States', 'Tortoise Hare At On Top Of The World'),
  ('United States', 'Tortuga At Haven Public Golf Club'),
  ('United States', 'Toscana Country Club North Course'),
  ('United States', 'Toscana Country Club South Course'),
  ('United States', 'Tot Hill Farm Golf Club'),
  ('United States', 'Totteridge Golf Course'),
  ('United States', 'Touchet Valley Golf Course'),
  ('United States', 'Touisset Country Club'),
  ('United States', 'Tournament At Burns Park Golf Course'),
  ('United States', 'Tournament Club of Iowa'),
  ('United States', 'Tournament Player’s Club at River’s Bend'),
  ('United States', 'Towanda Country Club'),
  ('United States', 'Tower Tee'),
  ('United States', 'Tower Tee Golf & Recreation'),
  ('United States', 'Towers Country Club'),
  ('United States', 'Town & Country Club'),
  ('United States', 'Town & Country Golf Course'),
  ('United States', 'Town Country Golf Links'),
  ('United States', 'Town Of Wallkill Golf Club'),
  ('United States', 'Town Park Villas Golf Course'),
  ('United States', 'Town and Country Golf Club'),
  ('United States', 'Towne Lake Hills Golf Club'),
  ('United States', 'Townsend Ridge Country Club'),
  ('United States', 'Tpc Boston'),
  ('United States', 'Tpc Colorado')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Tpc Deere Run'),
  ('United States', 'Tpc Harding Park Fleming Course'),
  ('United States', 'Tpc Harding Park Harding Course'),
  ('United States', 'Tpc Jasna Polana'),
  ('United States', 'Tpc Las Vegas'),
  ('United States', 'Tpc Louisiana'),
  ('United States', 'Tpc Michigan'),
  ('United States', 'Tpc Monterey At Pasadera'),
  ('United States', 'Tpc Myrtle Beach'),
  ('United States', 'Tpc Piper Glen'),
  ('United States', 'Tpc Potomac At Avenel Farm'),
  ('United States', 'Tpc Prestancia The Players Course'),
  ('United States', 'Tpc Prestancia The Stadium Course'),
  ('United States', 'Tpc River Highlands'),
  ('United States', 'Tpc Sawgrass Dyes Valley Course'),
  ('United States', 'Tpc Sawgrass The Players Stadium Course'),
  ('United States', 'Tpc Scottsdale The Champions Course'),
  ('United States', 'Tpc Scottsdale The Stadium Course'),
  ('United States', 'Tpc Southwind'),
  ('United States', 'Tpc Stonebrae'),
  ('United States', 'Tpc Sugarloaf Pines Course'),
  ('United States', 'Tpc Sugarloaf Stables Meadows Course'),
  ('United States', 'Tpc Summerlin'),
  ('United States', 'Tpc Tampa Bay'),
  ('United States', 'Tpc Treviso Bay'),
  ('United States', 'Tpc Wakefield Plantation'),
  ('United States', 'Tpc Wakefield Plantation Practice Course'),
  ('United States', 'Tpc Wisconsin'),
  ('United States', 'Tracy Country Club'),
  ('United States', 'Tracy Golf Country Club'),
  ('United States', 'Tradition At Tradition Golf Club'),
  ('United States', 'Tradition Golf Club'),
  ('United States', 'Tradition Golf Club At Oak Lane'),
  ('United States', 'Traditions At The Glen'),
  ('United States', 'Traditions Golf Club Learning Center'),
  ('United States', 'Traditions Of Braselton Golf Club'),
  ('United States', 'Traer Golf Club'),
  ('United States', 'Trail Blue At Blue Ridge Trail Golf Club'),
  ('United States', 'Trail Creek Course At Sun Valley Resort'),
  ('United States', 'Trail Ridge Golf Course At Sun City West'),
  ('United States', 'Trail Ruts Golf Course'),
  ('United States', 'Trail Side Golf and Foot Golf'),
  ('United States', 'Trailhead Golf Course'),
  ('United States', 'Trails End Golf Course'),
  ('United States', 'Trails West Golf Course'),
  ('United States', 'Tranquilo Golf Club At Four Seasons Resort Orlando'),
  ('United States', 'Transit Valley Country Club'),
  ('United States', 'Trapp River Golf Course'),
  ('United States', 'Trappers Turn Golf Club'),
  ('United States', 'Traveler''s Country Club'),
  ('United States', 'Travelers Rest Rv Resort Golf Course'),
  ('United States', 'Traverse City Golf and Country Club'),
  ('United States', 'Travis Pointe Country Club'),
  ('United States', 'Treasure Bay Golf Tennis'),
  ('United States', 'Tree Links Golf Course'),
  ('United States', 'Tree Top Golf Course'),
  ('United States', 'Treetops'),
  ('United States', 'Tregaron Golf Course'),
  ('United States', 'Trenton Country Club'),
  ('United States', 'Trenton Golf Club'),
  ('United States', 'Trestle Creek Golf Club'),
  ('United States', 'Treyburn Country Club'),
  ('United States', 'Treynor Recreation Area'),
  ('United States', 'Tri County Country Club'),
  ('United States', 'Tri Mountain Golf Course'),
  ('United States', 'Tri-City Country Club'),
  ('United States', 'Tri-Club Golf Club'),
  ('United States', 'Tri-County Golf Club'),
  ('United States', 'Tributary At River Strand Golf And Country Club'),
  ('United States', 'Tribute Golf Course'),
  ('United States', 'Trident Lakes Golf Club'),
  ('United States', 'Triggs Memorial Golf Course'),
  ('United States', 'Trillium Links'),
  ('United States', 'Trilogy Golf Club At La Quinta'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Players Loop'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Skills Course'),
  ('United States', 'Trilogy Golf Club At Vistancia'),
  ('United States', 'Trinidad Golf Course'),
  ('United States', 'Trinity Alps Golf Course'),
  ('United States', 'Trinity Golf Course'),
  ('United States', 'Triple Creek Golf Club'),
  ('United States', 'Triple Lakes Golf Course'),
  ('United States', 'Tripoli Country Club'),
  ('United States', 'Trona Golf Course'),
  ('United States', 'Troon Country Club'),
  ('United States', 'Trophy Lake Golf Casting Club'),
  ('United States', 'Trosper Golf Club'),
  ('United States', 'Trout Lake Golf Club'),
  ('United States', 'Troy Burne Golf Club'),
  ('United States', 'True Blue Golf Club'),
  ('United States', 'True North Golf Club'),
  ('United States', 'Trull Brook Golf Course'),
  ('United States', 'Truman At The Villages Executive Golf Trail'),
  ('United States', 'Trumann Country Club'),
  ('United States', 'Trumansburg Golf Club'),
  ('United States', 'Trump International Golf Club'),
  ('United States', 'Trump International Golf Club The Executive Golf Course'),
  ('United States', 'Trump National Doral Miami Blue Monster Course'),
  ('United States', 'Trump National Doral Miami Golden Palm Course'),
  ('United States', 'Trump National Doral Miami Red Tiger Course'),
  ('United States', 'Trump National Doral Miami Silver Fox Course'),
  ('United States', 'Trump National Golf Club'),
  ('United States', 'Trump National Golf Club Bedminster New Course'),
  ('United States', 'Trump National Golf Club Bedminster Old Course'),
  ('United States', 'Trump National Golf Club Charlotte'),
  ('United States', 'Trump National Golf Club Colts Neck Championship Course'),
  ('United States', 'Trump National Golf Club Colts Neck Par 3 Course'),
  ('United States', 'Trump National Golf Club Hudson Valley'),
  ('United States', 'Trump National Golf Club Philadelphia'),
  ('United States', 'Trump National Golf Club Washington D C Championship Course'),
  ('United States', 'Trump National Golf Club Washington D C River Course'),
  ('United States', 'Truth Or Consequence City Golf Course'),
  ('United States', 'Tryon Country Club'),
  ('United States', 'Tsawwassen Springs Golf'),
  ('United States', 'Tubac Golf Resort Anza Rancho'),
  ('United States', 'Tubac Golf Resort Otero Anza'),
  ('United States', 'Tubac Golf Resort Rancho Otero'),
  ('United States', 'Tuckaway Country Club'),
  ('United States', 'Tucson Catalina At Saddlebrooke Country Club'),
  ('United States', 'Tucson Country Club'),
  ('United States', 'Tucson Estates Country Club Golf Course'),
  ('United States', 'Tucumcari Municipal Golf Course'),
  ('United States', 'Tug Valley Country Club'),
  ('United States', 'Tulare Golf Course'),
  ('United States', 'Tullymore'),
  ('United States', 'Tulsa Country Club'),
  ('United States', 'Tumble Brook Country Club Blue Nine'),
  ('United States', 'Tumble Brook Country Club Green Nine'),
  ('United States', 'Tumble Brook Country Club Red Nine'),
  ('United States', 'Tumble Creek At Suncadia'),
  ('United States', 'Tumwater Valley Golf Club'),
  ('United States', 'Tunica National Golf And Tennis'),
  ('United States', 'Tunnel Hill Golf Course'),
  ('United States', 'Tupelo Bay Golf Complex Executive Course'),
  ('United States', 'Tupelo Bay Golf Complex Par 3 Course'),
  ('United States', 'Tupelo Country Club'),
  ('United States', 'Tupper Lake Country Club'),
  ('United States', 'Turin Highlands Golf Course'),
  ('United States', 'Turkana Golf Course'),
  ('United States', 'Turkey Creek Golf Club'),
  ('United States', 'Turkey Creek Golf Course'),
  ('United States', 'Turkey Run Golf Course'),
  ('United States', 'Turkeyfoot Lake Golf Links'),
  ('United States', 'Turlock Golf Country Club'),
  ('United States', 'Turnberry Golf Club'),
  ('United States', 'Turnberry Golf Course'),
  ('United States', 'Turnberry Isle Country Club Soffer Course'),
  ('United States', 'Turnberry Isle Country Club The Miller Course'),
  ('United States', 'Turner Highlands Country Club'),
  ('United States', 'Turner Hill Golf Racquet Club'),
  ('United States', 'Turquoise Hills Family Golf Center'),
  ('United States', 'Turtle Bay Resort Arnold Palmer Course'),
  ('United States', 'Turtle Bay Resort George Fazio Course'),
  ('United States', 'Turtle Bay Resort The Breaks Putting Course'),
  ('United States', 'Turtle Cove Property Owners Association Inc'),
  ('United States', 'Turtle Creek Club'),
  ('United States', 'Turtle Creek Golf Club'),
  ('United States', 'Turtle Creek Golf Course'),
  ('United States', 'Turtle Creek Golf Course At Garden Cathay'),
  ('United States', 'Turtle Hill Golf Course'),
  ('United States', 'Turtle Mound At The Villages Executive Golf Trail'),
  ('United States', 'Turtle Point At Kiawah Island Golf Resort'),
  ('United States', 'Turtle Run At Sun N Lake Golf Country Club'),
  ('United States', 'Turtle Run Golf Course'),
  ('United States', 'Turtleback'),
  ('United States', 'Turtleback Golf Course'),
  ('United States', 'Turtleback Mountain Golf Resort'),
  ('United States', 'Tuscan Ridge Golf Club'),
  ('United States', 'Tuscany Falls At Pebblecreek East Course'),
  ('United States', 'Tuscany Falls At Pebblecreek West Course'),
  ('United States', 'Tuscarora Country Club'),
  ('United States', 'Tuscarora Golf Club'),
  ('United States', 'Tuscawilla Golf Course'),
  ('United States', 'Tuscumbia Country Club'),
  ('United States', 'Tussey Mountain Golf Course'),
  ('United States', 'Tustin Ranch Golf Club'),
  ('United States', 'Tustin Trails Golf Course'),
  ('United States', 'Twaalfskill Club'),
  ('United States', 'Twain Harte Golf Club'),
  ('United States', 'Twelve Shores Golf Club'),
  ('United States', 'Twilight Golf Course'),
  ('United States', 'Twin Base Golf Course'),
  ('United States', 'Twin Beach Country Club'),
  ('United States', 'Twin Birch Golf Course'),
  ('United States', 'Twin Bridges Golf Club'),
  ('United States', 'Twin Bridges Golf Course'),
  ('United States', 'Twin Brook Golf Center'),
  ('United States', 'Twin Brooks Golf Course'),
  ('United States', 'Twin City Country Club'),
  ('United States', 'Twin Creeks Golf Course'),
  ('United States', 'Twin Falls Golf Club'),
  ('United States', 'Twin Falls Municipal Golf Course'),
  ('United States', 'Twin Falls State Park'),
  ('United States', 'Twin Hickory Golf Club'),
  ('United States', 'Twin Hills Country Club'),
  ('United States', 'Twin Hills Golf Country Club'),
  ('United States', 'Twin Hills Golf Course'),
  ('United States', 'Twin Isles Country Club'),
  ('United States', 'Twin Lake Par 3 Golf Course'),
  ('United States', 'Twin Lake Village Par 3 Golf Course'),
  ('United States', 'Twin Lakes Country Club'),
  ('United States', 'Twin Lakes Golf & Swim Club'),
  ('United States', 'Twin Lakes Golf Club'),
  ('United States', 'Twin Lakes Golf Country Club'),
  ('United States', 'Twin Lakes Golf Course'),
  ('United States', 'Twin Lakes Lakes Course'),
  ('United States', 'Twin Lakes Municipal Golf Course'),
  ('United States', 'Twin Lakes Oaks Course'),
  ('United States', 'Twin Lakes Of Kahoka'),
  ('United States', 'Twin Lakes Village Golf Course'),
  ('United States', 'Twin Oaks Country Club'),
  ('United States', 'Twin Oaks Golf Club'),
  ('United States', 'Twin Oaks Golf Country Club'),
  ('United States', 'Twin Oaks Golf Course'),
  ('United States', 'Twin Oaks Golf and Plantation Club'),
  ('United States', 'Twin Oaks Par 3 Golf Driving Range'),
  ('United States', 'Twin Orchards Country Club'),
  ('United States', 'Twin Peaks Golf Course'),
  ('United States', 'Twin Pines Golf Course'),
  ('United States', 'Twin Ponds Golf Club'),
  ('United States', 'Twin Ponds Golf Country Club'),
  ('United States', 'Twin Rivers Golf Club'),
  ('United States', 'Twin Rivers Golf Course'),
  ('United States', 'Twin Run Golf Course'),
  ('United States', 'Twin Springs Golf Course'),
  ('United States', 'Twin Valley Country Club'),
  ('United States', 'Twin Village Golf Club'),
  ('United States', 'Twin Warriors Golf Club'),
  ('United States', 'Twin Willows Par 3 Golf Course'),
  ('United States', 'Twin Woods Golf Club'),
  ('United States', 'Twineagles Golf Country Club Eagle Course'),
  ('United States', 'Twineagles Golf Country Club Talon Course'),
  ('United States', 'Twisted Dune Golf Club'),
  ('United States', 'Twisted Gun Golf Course'),
  ('United States', 'Twisted Oaks Golf Club'),
  ('United States', 'Twisted Pine Golf Course'),
  ('United States', 'Two East Course At Apple Greens Golf Course'),
  ('United States', 'Two Oaks North Golf Club'),
  ('United States', 'Two Rivers Country Club'),
  ('United States', 'Two Rivers Golf Club'),
  ('United States', 'Tyler Creek Golf Club'),
  ('United States', 'Tylertown Country Club'),
  ('United States', 'Tyngsboro Country Club'),
  ('United States', 'Tyoga Golf Course'),
  ('United States', 'Tyrone Hills Golf Club'),
  ('United States', 'U S Soldiers And Airmens Home Golf Course'),
  ('United States', 'Ubly Heights Golf & Country Club'),
  ('United States', 'Uchee Trail Country Club'),
  ('United States', 'Ukiah Valley Golf Course'),
  ('United States', 'Ulen Country Club'),
  ('United States', 'Umstead Pines Golf Swim Club At Willowhaven'),
  ('United States', 'Unc Finley Golf Course'),
  ('United States', 'Uncle Remus Golf Course'),
  ('United States', 'Undermountain Golf Course'),
  ('United States', 'Unf Golf Complex At The Hayt Learning Center'),
  ('United States', 'Unicorn Golf Course'),
  ('United States', 'Union City Country Club'),
  ('United States', 'Union Country Club'),
  ('United States', 'Union County Country Club'),
  ('United States', 'Union Golf Course'),
  ('United States', 'Union Hills Golf Country Club'),
  ('United States', 'Union Lake Golf Course'),
  ('United States', 'Union League Golf Club At Torresdale'),
  ('United States', 'Union League Liberty Hill'),
  ('United States', 'Union League National Golf Club Meade Grant'),
  ('United States', 'Union League National Golf Club Sherman Grant'),
  ('United States', 'Union League National Golf Club Sherman Meade'),
  ('United States', 'Uniontown Country Club'),
  ('United States', 'University Club'),
  ('United States', 'University Club Of Milwaukee'),
  ('United States', 'University Golf Club'),
  ('United States', 'University Of Denver Golf Club At Highlands Ranch'),
  ('United States', 'University Of Georgia Golf Course'),
  ('United States', 'University Of Idaho Golf Course'),
  ('United States', 'University Of Maryland Golf Course'),
  ('United States', 'University Of Montana Golf Course The'),
  ('United States', 'University Of New Mexico North Course'),
  ('United States', 'University Park Golf Course'),
  ('United States', 'University Ridge Golf Course'),
  ('United States', 'University of Illinois Golf Course'),
  ('United States', 'University of Louisville Golf Club'),
  ('United States', 'University of Michigan Golf Course'),
  ('United States', 'University of North Dakota Golf Course'),
  ('United States', 'Upland Hills Country Club'),
  ('United States', 'Upland Trace Golf Club'),
  ('United States', 'Uplands Golf Club'),
  ('United States', 'Upper At Baltusrol Golf Club'),
  ('United States', 'Upper At Peekn Peak Golf Course'),
  ('United States', 'Upper Canada Golf Course'),
  ('United States', 'Upper Lansdowne Golf Course'),
  ('United States', 'Urban Put Put'),
  ('United States', 'Urbana Country Club'),
  ('United States', 'Urbandale Golf & Country Club'),
  ('United States', 'Useless Bay Golf Country Club'),
  ('United States', 'Ute Creek Golf Course'),
  ('United States', 'Utica Golf Club'),
  ('United States', 'Va Jo Wa Golf Club'),
  ('United States', 'Vache Grasse Country Club'),
  ('United States', 'Vail Golf Club'),
  ('United States', 'Vails Grove Golf Course'),
  ('United States', 'Val Halla Golf Recreation Center'),
  ('United States', 'Valencia Country Club'),
  ('United States', 'Valencia Golf Country Club'),
  ('United States', 'Valhalla Golf Club'),
  ('United States', 'Valle Del Sol Golf Course'),
  ('United States', 'Valle Vista Golf Course'),
  ('United States', 'Valleaire Golf Club'),
  ('United States', 'Valley At Castlewood Country Club'),
  ('United States', 'Valley At Colonial Springs Golf Course'),
  ('United States', 'Valley At Cordillera Golf Course'),
  ('United States', 'Valley At Marriotts Desert Springs Resort'),
  ('United States', 'Valley At Towa Golf Resort'),
  ('United States', 'Valley Brook Golf Course'),
  ('United States', 'Valley Club Of Montecito'),
  ('United States', 'Valley Country Club'),
  ('United States', 'Valley Course At Christmans Windham House'),
  ('United States', 'Valley Gardens Golf Course'),
  ('United States', 'Valley Golf Center'),
  ('United States', 'Valley Golf Centre'),
  ('United States', 'Valley Golf Course'),
  ('United States', 'Valley Green Golf Country Club'),
  ('United States', 'Valley Green Golf Course'),
  ('United States', 'Valley Green Par 3 Course'),
  ('United States', 'Valley Hi Country Club'),
  ('United States', 'Valley Hi Municipal Golf Course'),
  ('United States', 'Valley High Golf Course'),
  ('United States', 'Valley Links Course'),
  ('United States', 'Valley Lo Club'),
  ('United States', 'Valley Mountain At Pinery Country Club'),
  ('United States', 'Valley Oaks At North Ranch Country Club'),
  ('United States', 'Valley Oaks At Valley Oaks Golf Club'),
  ('United States', 'Valley Of The Eagles Golf Links'),
  ('United States', 'Valley Of The Moon Golf Club'),
  ('United States', 'Valley Pine Country Club'),
  ('United States', 'Valley Pines Golf Club'),
  ('United States', 'Valley Point Golf Course'),
  ('United States', 'Valley View Country Club'),
  ('United States', 'Valley View Golf'),
  ('United States', 'Valley View Golf Club'),
  ('United States', 'Valley View Golf Course'),
  ('United States', 'Valley View Municipal Golf Course'),
  ('United States', 'Valley Vista At Los Coyotes Country Club'),
  ('United States', 'Valley Vista Golf Course'),
  ('United States', 'Valleywood Golf Club'),
  ('United States', 'Valleywood Golf Course'),
  ('United States', 'Valparaiso Country Club'),
  ('United States', 'Van Buren Golf Center'),
  ('United States', 'Van Buren Recreation Area Golf'),
  ('United States', 'Van Cortlandt Park Golf Course'),
  ('United States', 'Van Patten Golf Club Blue Red'),
  ('United States', 'Van Patten Golf Club Red White'),
  ('United States', 'Van Patten Golf Club White Blue'),
  ('United States', 'Van Schaick Island Country Club'),
  ('United States', 'Vanderbilt Country Club'),
  ('United States', 'Vandergrift Golf Club'),
  ('United States', 'Vanmetre 9 At Stonebridge'),
  ('United States', 'Vardon Golf Club'),
  ('United States', 'Vasari Country Club'),
  ('United States', 'Vashon Island Golf Country Club'),
  ('United States', 'Vassar Golf Course'),
  ('United States', 'Vassar Golf and Country Club'),
  ('United States', 'Veenker Memorial Golf Course'),
  ('United States', 'Venango Valley Inn Golf Course'),
  ('United States', 'Venetian Gardens Golf Course'),
  ('United States', 'Venetian Golf Club'),
  ('United States', 'Venice East Golf Club'),
  ('United States', 'Venice Golf Country Club'),
  ('United States', 'Ventana Canyon Canyon Course'),
  ('United States', 'Ventana Canyon Mountain Course'),
  ('United States', 'Ventura Country Club'),
  ('United States', 'Verde River Golf Social Club'),
  ('United States', 'Verdict Ridge Golf Country Club'),
  ('United States', 'Vermilion Golf Course'),
  ('United States', 'Vermilion River Greens'),
  ('United States', 'Vermillion Fairways'),
  ('United States', 'Vermont National Country Club'),
  ('United States', 'Vernon Hills Golf Course'),
  ('United States', 'Vernonia Golf Club'),
  ('United States', 'Vero Beach Country Club'),
  ('United States', 'Verona Hills Golf Club'),
  ('United States', 'Verona Meadows'),
  ('United States', 'Verrado Golf Club Founders Course'),
  ('United States', 'Verrado Golf Club Victory Course'),
  ('United States', 'Vesper Country Club'),
  ('United States', 'Vesper Hills Golf Club'),
  ('United States', 'Vestal Hills Country Club'),
  ('United States', 'Veteran''s Memorial Golf Course'),
  ('United States', 'Veterans Golf Course'),
  ('United States', 'Veterans Memorial Golf Course'),
  ('United States', 'Via Mizner Golf Country Club'),
  ('United States', 'Via Verde Country Club'),
  ('United States', 'Viburnum Golf & Country Club'),
  ('United States', 'Vic Meyers Golf Course At Sun Lakes'),
  ('United States', 'Vicksburg Country Club'),
  ('United States', 'Victoria Club'),
  ('United States', 'Victoria Country Club'),
  ('United States', 'Victoria Golf Centre'),
  ('United States', 'Victoria Golf Club'),
  ('United States', 'Victoria Golf Course'),
  ('United States', 'Victoria Hills Golf Club')
on conflict (country, name) do nothing;
