insert into public.golf_courses (country, name) values
  ('United States', 'Greenbriar Brooklyn'),
  ('United States', 'Greenbriar Golf Club At Whittingham'),
  ('United States', 'Greenbriar Golf Course'),
  ('United States', 'Greenbriar Hills Country Club'),
  ('United States', 'Greenbriar Woodlands Golf Course'),
  ('United States', 'Greenbrier Country Club'),
  ('United States', 'Greenbrier Golf Club'),
  ('United States', 'Greenbrier Greenbrier Course'),
  ('United States', 'Greenbrier Meadows Course'),
  ('United States', 'Greenbrier Old White Course'),
  ('United States', 'Greenbrier Sporting Club Snead Course'),
  ('United States', 'Greenbush Golf Course'),
  ('United States', 'Greencastle Golf Club'),
  ('United States', 'Greendale Golf Course'),
  ('United States', 'Greene Country Club Event Center'),
  ('United States', 'Greene County Country Club'),
  ('United States', 'Greene Hills Club'),
  ('United States', 'Greeneacre Golf Club'),
  ('United States', 'Greenfield Country Club'),
  ('United States', 'Greenfield Lakes Golf Course'),
  ('United States', 'Greenfield Park Golf Course'),
  ('United States', 'Greenhills Golf Course'),
  ('United States', 'Greenhorn Creek Golf Course'),
  ('United States', 'Greenlake Golf Course'),
  ('United States', 'Greenlea Golf Course'),
  ('United States', 'Greenlee Country Club'),
  ('United States', 'Greenock Country Club'),
  ('United States', 'Greens Folly Golf Course'),
  ('United States', 'Greens Golf Racquet Club'),
  ('United States', 'Greens Of Manatee Golf Course'),
  ('United States', 'Greensboro Country Club Farm Course'),
  ('United States', 'Greensboro Country Club Irving Park Course'),
  ('United States', 'Greensboro National Golf Club'),
  ('United States', 'Greensbridge Golf Course'),
  ('United States', 'Greensburg Country Club'),
  ('United States', 'Greenshire Golf Course'),
  ('United States', 'Greenvalley At Greenview Country Club'),
  ('United States', 'Greenview At Greenview Country Club'),
  ('United States', 'Greenview Golf Club'),
  ('United States', 'Greenville Country Club'),
  ('United States', 'Greenville Public Golf Course'),
  ('United States', 'Greenway Creek Golf Course'),
  ('United States', 'Greenway Park Golf Course'),
  ('United States', 'Greenwich Country Club'),
  ('United States', 'Greenwood Country Club'),
  ('United States', 'Greenwood Golf Course'),
  ('United States', 'Greenwood Hills Country Club'),
  ('United States', 'Greer Golf'),
  ('United States', 'Greeville Country Club'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Blue Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills Gold Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills North Par 3 Course'),
  ('United States', 'Greg Mastriona Golf Courses At Hyland Hills South Par 3 Course'),
  ('United States', 'Grenadier Island Country Club'),
  ('United States', 'Gresham Golf Course'),
  ('United States', 'Grey Oaks Country Club Estuary Golf Course'),
  ('United States', 'Grey Oaks Country Club Palm Golf Course'),
  ('United States', 'Grey Oaks Country Club Pine Golf Course'),
  ('United States', 'GreyStone Golf Club'),
  ('United States', 'Greynolds Golf Course'),
  ('United States', 'Greystone Country Club'),
  ('United States', 'Greystone Golf Club'),
  ('United States', 'Greystone Golf Country Club'),
  ('United States', 'Greystone Golf Course'),
  ('United States', 'Greystone Mountain Golf Club'),
  ('United States', 'Greywalls Course At Marquette Golf Club'),
  ('United States', 'Griffin Bell Golf Conference Center'),
  ('United States', 'Griffin City Golf Course'),
  ('United States', 'Griffith E Harris Golf Course'),
  ('United States', 'Grindstone Neck Golf Course'),
  ('United States', 'Grinnell College Golf Course'),
  ('United States', 'Grinnell Cow Paddy Golf Club'),
  ('United States', 'Grizzly Oaks Disc Golf Course'),
  ('United States', 'Grizzly Ranch Golf Club'),
  ('United States', 'Groesbeck Golf Course'),
  ('United States', 'Grosse Ile Golf & Country Club'),
  ('United States', 'Groton Country Club'),
  ('United States', 'Grove City Country Club'),
  ('United States', 'Grove Lakes At Treesdale Golf Country Club'),
  ('United States', 'Grove Park Golf Club'),
  ('United States', 'Grove Park Golf Course'),
  ('United States', 'Grove Xxiii'),
  ('United States', 'Groveport Municipal Golf Course'),
  ('United States', 'Grover Cleveland Golf Course'),
  ('United States', 'Gruis Golf Course'),
  ('United States', 'Gruis Recreation Area The Barn'),
  ('United States', 'Guilford Lakes Golf Course'),
  ('United States', 'Gulf Harbour Golf Country Club'),
  ('United States', 'Gulf Hills Golf Club'),
  ('United States', 'Gulf Stream Golf Course'),
  ('United States', 'Gull Haven Golf Club'),
  ('United States', 'Gull Lake Country Club'),
  ('United States', 'Gull Lake View East'),
  ('United States', 'Gull Lake View West'),
  ('United States', 'Gully Golf Course'),
  ('United States', 'Gulph Mills Golf Club'),
  ('United States', 'Gun Ridge Golf Course'),
  ('United States', 'Gunflint Hills Golf Course'),
  ('United States', 'Guthrie Center Golf Club'),
  ('United States', 'Guthrie Golf Country Club'),
  ('United States', 'Guttenberg Community Golf'),
  ('United States', 'Guttenberg Golf and Country Club'),
  ('United States', 'Guyan Golf and Country Club'),
  ('United States', 'Gypsum Creek Golf Course'),
  ('United States', 'Gypsy Hill Golf Club'),
  ('United States', 'H Smith Richardson Golf Course'),
  ('United States', 'Hacienda Golf Club'),
  ('United States', 'Hackensack Golf Club'),
  ('United States', 'Haddam Community Golf Course'),
  ('United States', 'Hadley Acres Golf Club'),
  ('United States', 'Hadley Creek Golf Learning Center'),
  ('United States', 'Haile Plantation Golf Country Club'),
  ('United States', 'Hailwood Golf Course'),
  ('United States', 'Hale S Location Golf Course'),
  ('United States', 'Hales Mills Country Club'),
  ('United States', 'Half Moon Bay Golf Links Ocean Course'),
  ('United States', 'Half Moon Bay Golf Links Old Course'),
  ('United States', 'Halifax Country Club'),
  ('United States', 'Halifax Plantation'),
  ('United States', 'Halla Greens'),
  ('United States', 'Hallbrook Country Club'),
  ('United States', 'Hamakua Country Club'),
  ('United States', 'Hamilton College Golf Course'),
  ('United States', 'Hamilton Elks Golf Club'),
  ('United States', 'Hamilton Golf Club'),
  ('United States', 'Hamilton Lake Conference Center'),
  ('United States', 'Hamilton Mill Golf Course'),
  ('United States', 'Hamilton Trails Country Club'),
  ('United States', 'Hamlet Golf Country Club'),
  ('United States', 'Hamlet Golf Course'),
  ('United States', 'Hamlin Golf Club'),
  ('United States', 'Hammock At Ocean Reef Club'),
  ('United States', 'Hammock Bay Golf Course'),
  ('United States', 'Hammock Beach Resort The Conservatory Course'),
  ('United States', 'Hammock Beach Resort The Ocean Course'),
  ('United States', 'Hammock Creek Golf Club'),
  ('United States', 'Hammock Dunes Rees Jones Creek Course'),
  ('United States', 'Hammock Dunes Tom Fazio Links Course'),
  ('United States', 'Hammond Golf Center'),
  ('United States', 'Hammond Golf Club'),
  ('United States', 'Hampden Country Club'),
  ('United States', 'Hampshire Country Club'),
  ('United States', 'Hampton Country Club'),
  ('United States', 'Hampton Golf Village'),
  ('United States', 'Hampton Golf and Country Club'),
  ('United States', 'Hampton Hall Club'),
  ('United States', 'Hampton Heights Golf Course'),
  ('United States', 'Hampton Hills Golf Country Club'),
  ('United States', 'Hamptons Golf Club The'),
  ('United States', 'Hanah Mountain Resort Country Club'),
  ('United States', 'Hancock Golf Country Club'),
  ('United States', 'Hanging Rock Golf Club'),
  ('United States', 'Hankerd Hills Golf Course'),
  ('United States', 'Hanks Golf'),
  ('United States', 'Hanks Swank Par Three Golf Course'),
  ('United States', 'Hanks Woodlake Ranch Golf'),
  ('United States', 'Hannastown Golf Club'),
  ('United States', 'Hannibal Country Club'),
  ('United States', 'Hanover Country Club'),
  ('United States', 'Hanover Golf Club'),
  ('United States', 'Hansen Dam Golf Course'),
  ('United States', 'Hansen Park Golf Course'),
  ('United States', 'Hansford Golf Course'),
  ('United States', 'Happy Hollow Club'),
  ('United States', 'Hapuna Golf Course'),
  ('United States', 'Harbor At Wild Dunes Golf Links'),
  ('United States', 'Harbor Club On Lake Oconee'),
  ('United States', 'Harbor Hills Country Club'),
  ('United States', 'Harbor Lights Golf Country Club'),
  ('United States', 'Harbor Links At Sagamore Resort'),
  ('United States', 'Harbor Links Public Golf'),
  ('United States', 'Harbor Oaks Golf Club'),
  ('United States', 'Harbor Park Golf Course'),
  ('United States', 'Harbor Pines Golf Club'),
  ('United States', 'Harbor Point Golf Club'),
  ('United States', 'Harbor Ridge Golf Course'),
  ('United States', 'Harbor Shores'),
  ('United States', 'Harborside International Golf Center'),
  ('United States', 'Harbour Pointe Golf Club'),
  ('United States', 'Harbour Town Golf Links At Sea Pines Resort'),
  ('United States', 'Harbour View Golf Complex'),
  ('United States', 'Harbour Village Golf Yacht Club'),
  ('United States', 'Hardeman County Golf Country Club'),
  ('United States', 'Harding At Griffith Park Golf Courses'),
  ('United States', 'Hardscrabble Country Club'),
  ('United States', 'Hardwick Crossing Country Club'),
  ('United States', 'Hardwood Hills Golf Course'),
  ('United States', 'Hardys Custom Golf Center'),
  ('United States', 'Harkers Hollow Golf Club'),
  ('United States', 'Harlan Country Club'),
  ('United States', 'Harlan Golf and Country Club'),
  ('United States', 'Harlem Golf Course'),
  ('United States', 'Harlem Valley Golf Club'),
  ('United States', 'Harmon Golf Fitness Club'),
  ('United States', 'Harmony Golf Club'),
  ('United States', 'Harmony Golf Club Community'),
  ('United States', 'Harmony Golf Preserve'),
  ('United States', 'Harmony Landing'),
  ('United States', 'Harmony Ridge Golf Club'),
  ('United States', 'Harrington Golf Country Club'),
  ('United States', 'Harris Hill Golf Center'),
  ('United States', 'Harris Park Golf Course'),
  ('United States', 'Harrison Country Club'),
  ('United States', 'Harrison Hills Golf Course'),
  ('United States', 'Harrison Lake Country Club'),
  ('United States', 'Harrison Meadows Country Club'),
  ('United States', 'Harrison Park Golf Course'),
  ('United States', 'Harrisonville Golf Club'),
  ('United States', 'Harrisville Golf Course'),
  ('United States', 'Harry L Jones Sr Golf Course'),
  ('United States', 'Harry Mussatto Golf Course (WIU)'),
  ('United States', 'Hart Ridge Golf Course'),
  ('United States', 'Hartefeld National Golf Club'),
  ('United States', 'Hartford Golf Club'),
  ('United States', 'Hartford Golf Club Blue Course'),
  ('United States', 'Hartford Golf Club Green Course'),
  ('United States', 'Hartford Golf Club Red Course'),
  ('United States', 'Hartland Glen Golf Club'),
  ('United States', 'Hartley Hills Country Club'),
  ('United States', 'Hartmanns Deep Valley Golf Course'),
  ('United States', 'Hartstown Golf Course'),
  ('United States', 'Hartsville Country Club'),
  ('United States', 'Hartwell Golf Club'),
  ('United States', 'Hartwood Golf Course'),
  ('United States', 'Harvard Gulch Golf Course'),
  ('United States', 'Harvest Hill Golf Course'),
  ('United States', 'Harvest Hills Golf Course'),
  ('United States', 'Harvest Point Golf Course'),
  ('United States', 'Harwich Port Golf Club'),
  ('United States', 'Hastings Country Club'),
  ('United States', 'Hat Creek Golf Course'),
  ('United States', 'Hat Island Golf Course'),
  ('United States', 'Hatherly Country Club'),
  ('United States', 'Hattiesburg Country Club'),
  ('United States', 'Havana Golf Country Club'),
  ('United States', 'Havanah Hills'),
  ('United States', 'Havasu Island Golf Course'),
  ('United States', 'Havasu Springs Resort'),
  ('United States', 'Haven At Haven Public Golf Club'),
  ('United States', 'Haven Golf Club'),
  ('United States', 'Haverhill Country Club'),
  ('United States', 'Hawaii Country Club'),
  ('United States', 'Hawaii Kai Executive Golf Course'),
  ('United States', 'Hawaii Kai Golf Course'),
  ('United States', 'Hawaii Prince Golf Club A B Nines'),
  ('United States', 'Hawaii Prince Golf Club B C Nines'),
  ('United States', 'Hawaii Prince Golf Club C A Nines'),
  ('United States', 'Hawarden Golf Course'),
  ('United States', 'Hawk Golf Course'),
  ('United States', 'Hawk Hollow Golf Course'),
  ('United States', 'Hawk Meadows'),
  ('United States', 'Hawk Pointe Golf Course'),
  ('United States', 'Hawk Ridge Golf Course'),
  ('United States', 'Hawk S Eye At Shanty Creek'),
  ('United States', 'Hawk Valley Golf Club'),
  ('United States', 'Hawk''s Eye Golf Course'),
  ('United States', 'Hawk''s View Golf Club'),
  ('United States', 'Hawkes Bay At The Villages Executive Golf Trail'),
  ('United States', 'Hawks Landing Country Club'),
  ('United States', 'Hawks Landing Golf Club'),
  ('United States', 'Hawks Landing Golf Course'),
  ('United States', 'Hawks Point Golf Club'),
  ('United States', 'Hawks Ridge'),
  ('United States', 'Hawks Ridge Par 3 Course'),
  ('United States', 'Hawks Tail Of Greenfield'),
  ('United States', 'Hawkshead'),
  ('United States', 'Hawkshead Links Golf Course'),
  ('United States', 'Hawktree Golf Club'),
  ('United States', 'Hawley Golf and Country Club'),
  ('United States', 'Haworth Golf Club'),
  ('United States', 'Hawthorn Woods Country Club'),
  ('United States', 'Hawthorne Country Club'),
  ('United States', 'Hawthorne Hills Golf Course'),
  ('United States', 'Hawthorne Ridge Golf Course'),
  ('United States', 'Hawthorne Valley Golf Club'),
  ('United States', 'Hay Creek Golf Course'),
  ('United States', 'Hay Harbor Golf Club'),
  ('United States', 'Hayden Golf Club'),
  ('United States', 'Haymaker'),
  ('United States', 'Haynesville Golf Course'),
  ('United States', 'Haystack Mountain Golf Course'),
  ('United States', 'Hayward Golf Club'),
  ('United States', 'Hayward National Golf Club'),
  ('United States', 'Hazard Creek Golf Course'),
  ('United States', 'Hazelden Country Club'),
  ('United States', 'Hazelmere Country Club'),
  ('United States', 'Hazeltine National Golf Course'),
  ('United States', 'Hazelton Golf Club'),
  ('United States', 'Hazen Golf Club'),
  ('United States', 'Hazy Hills Golf Course'),
  ('United States', 'Headland Country Club'),
  ('United States', 'Headwaters Club At Teton Springs'),
  ('United States', 'Headwaters Club At Teton Springs Par 3 Course'),
  ('United States', 'Headwaters Golf Club'),
  ('United States', 'Headwaters Public Golf Course'),
  ('United States', 'Healdsburg Golf Club At Tayman Park'),
  ('United States', 'Healing Springs Ranch'),
  ('United States', 'Healy Point Country Club'),
  ('United States', 'Heart Of America Golf Academy River Course'),
  ('United States', 'Heart Of America Golf Academy Rock Course'),
  ('United States', 'Heart of the Valley Golf Club'),
  ('United States', 'Heartland Crossing Golf Links'),
  ('United States', 'Heartland Golf Park'),
  ('United States', 'Heartland Resort'),
  ('United States', 'Heartwell Golf Course'),
  ('United States', 'Heather Downs Country Club'),
  ('United States', 'Heather Gardens Golf Course'),
  ('United States', 'Heather Golf Country Club'),
  ('United States', 'Heather Highlands Golf Club'),
  ('United States', 'Heather Hills Golf Course'),
  ('United States', 'Heather Ridge Golf Course'),
  ('United States', 'Heathers Club of Bloomfield'),
  ('United States', 'Heatherwoode Golf Club'),
  ('United States', 'Heatherwoods Golf Course'),
  ('United States', 'Heathrow Country Club'),
  ('United States', 'Heaven On Earth Par 3 Ranch Golf Course'),
  ('United States', 'Hebron Country Club'),
  ('United States', 'Hebron Pines Rv And Golf'),
  ('United States', 'Hedingham Golf Club'),
  ('United States', 'Heidelberg Country Club'),
  ('United States', 'Heise Hills Golf Course'),
  ('United States', 'Helena Country Club'),
  ('United States', 'Helena West Helena Public Golf Course'),
  ('United States', 'Helfrich Golf Course'),
  ('United States', 'Hells Point Golf Club'),
  ('United States', 'Hemet Golf Club'),
  ('United States', 'Hemet West Mobile Estates'),
  ('United States', 'Hemingway Kilimanjaro At Havana Country Club'),
  ('United States', 'Hemlock Golf Club'),
  ('United States', 'Hemlock Golf Course'),
  ('United States', 'Hemlock Ridge Golf Course'),
  ('United States', 'Hemlock View Golf Course'),
  ('United States', 'Hempstead Golf Country Club'),
  ('United States', 'Henderson Country Club'),
  ('United States', 'Henderson Golf Club'),
  ('United States', 'Henderson Municipal Golf Course'),
  ('United States', 'Henderson Park Golf Course'),
  ('United States', 'Hendersonville Country Club'),
  ('United States', 'Hendricks Field Golf Course'),
  ('United States', 'Hendricks Golf Club'),
  ('United States', 'Henry Stambaugh Golf Course'),
  ('United States', 'Henryetta Golf Country Club'),
  ('United States', 'Henson Creek Golf Course'),
  ('United States', 'Herington Country Club'),
  ('United States', 'Heritage Bay Golf And Country Club Cypress Course'),
  ('United States', 'Heritage Bay Golf And Country Club Oak Course'),
  ('United States', 'Heritage Bay Golf And Country Club Pine Course'),
  ('United States', 'Heritage Bluffs Public Golf Club'),
  ('United States', 'Heritage Club'),
  ('United States', 'Heritage Country Club'),
  ('United States', 'Heritage Creek Golf Club'),
  ('United States', 'Heritage Eagle Bend Golf Club'),
  ('United States', 'Heritage Glen Golf Club'),
  ('United States', 'Heritage Golf Club'),
  ('United States', 'Heritage Golf Club Blue Course'),
  ('United States', 'Heritage Golf Club Green Course'),
  ('United States', 'Heritage Golf Club Orange Course'),
  ('United States', 'Heritage Golf Links Heritage Nine'),
  ('United States', 'Heritage Golf Links Legacy Nine'),
  ('United States', 'Heritage Golf Links Tradition Nine'),
  ('United States', 'Heritage Harbor'),
  ('United States', 'Heritage Harbour Golf Club'),
  ('United States', 'Heritage Hill Golf Course'),
  ('United States', 'Heritage Hills Golf Course'),
  ('United States', 'Heritage Hills Golf Resort'),
  ('United States', 'Heritage Hunt Golf Club'),
  ('United States', 'Heritage Isles Golf And Country Club'),
  ('United States', 'Heritage Landing Golf Country Club'),
  ('United States', 'Heritage Links'),
  ('United States', 'Heritage Links Golf Club'),
  ('United States', 'Heritage Oaks Golf Club'),
  ('United States', 'Heritage Oaks Golf Country Club'),
  ('United States', 'Heritage Oaks Golf Course'),
  ('United States', 'Heritage Of Hawk Ridge'),
  ('United States', 'Heritage Palms Golf Club'),
  ('United States', 'Heritage Park Golf Course'),
  ('United States', 'Heritage Pines Country Club'),
  ('United States', 'Heritage Ridge Golf Club'),
  ('United States', 'Heritage Shores Golf'),
  ('United States', 'Heritage Springs Country Club'),
  ('United States', 'Heritage Woods Golf Course'),
  ('United States', 'Heritage of Hawk Ridge'),
  ('United States', 'Hermitage Club'),
  ('United States', 'Hermon Meadow Golf Club Training Center'),
  ('United States', 'Hernando Oaks Golf Country Club'),
  ('United States', 'Herndon Centennial Golf Course'),
  ('United States', 'Heroes Golf Course'),
  ('United States', 'Heron At The Villages Executive Golf Trail'),
  ('United States', 'Heron Bay Golf Country Club'),
  ('United States', 'Heron Creek Golf And Country Club Creek Oaks Course'),
  ('United States', 'Heron Creek Golf And Country Club Marsh Creek Course'),
  ('United States', 'Heron Creek Golf And Country Club Oaks Marsh Course'),
  ('United States', 'Heron Creek Golf Club'),
  ('United States', 'Heron Eagle At Okeeheelee Golf Course'),
  ('United States', 'Heron Glen Golf Course'),
  ('United States', 'Heron Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Heron Lakes Golf Club Great Blue Course'),
  ('United States', 'Heron Lakes Golf Club Greenback Course'),
  ('United States', 'Heron Osprey At Burnt Store Marina Country Club'),
  ('United States', 'Heron Pelican At Burnt Store Marina Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Heron Point At Sea Pines Resort'),
  ('United States', 'Heron Ridge Golf Club'),
  ('United States', 'Herons Glen Golf Country Club'),
  ('United States', 'Herring Cove Provincial Golf Course'),
  ('United States', 'Hersheys Mill Golf Club'),
  ('United States', 'Hesperia Golf Country Club'),
  ('United States', 'Hessel Ridge Golf'),
  ('United States', 'Hesston Municipal Golf Park'),
  ('United States', 'Hi Point Golf Course'),
  ('United States', 'Hiawatha Country Club'),
  ('United States', 'Hiawatha Golf Club'),
  ('United States', 'Hiawatha Sportsman’s Club Golf Course'),
  ('United States', 'Hiawatha Trails'),
  ('United States', 'Hibiscus Golf Club'),
  ('United States', 'Hickory Bend Golf Course'),
  ('United States', 'Hickory Creek Golf Course'),
  ('United States', 'Hickory Flats Golf Course'),
  ('United States', 'Hickory Grove Country Club'),
  ('United States', 'Hickory Grove Golf Club'),
  ('United States', 'Hickory Grove Golf Course'),
  ('United States', 'Hickory Heights Golf Club'),
  ('United States', 'Hickory Hill Country Club Resort'),
  ('United States', 'Hickory Hill Golf Club'),
  ('United States', 'Hickory Hill Golf Course'),
  ('United States', 'Hickory Hill Golf Course Creekside Roadside'),
  ('United States', 'Hickory Hill Golf Course Fieldside Creekside'),
  ('United States', 'Hickory Hill Golf Course Roadside Fieldside'),
  ('United States', 'Hickory Hills Country Club'),
  ('United States', 'Hickory Hills Golf Club'),
  ('United States', 'Hickory Hills Golf Course'),
  ('United States', 'Hickory Hollow Golf Course'),
  ('United States', 'Hickory Knob Golf Course'),
  ('United States', 'Hickory Knoll Golf Course'),
  ('United States', 'Hickory Point Golf Course'),
  ('United States', 'Hickory Ridge Golf Country Club'),
  ('United States', 'Hickory Ridge Golf Course'),
  ('United States', 'Hickory Ridge Public Golf Center'),
  ('United States', 'Hickory Sticks Golf Club'),
  ('United States', 'Hickory Swing Golf Course'),
  ('United States', 'Hickory Woods Golf Course'),
  ('United States', 'Hidden Acres Executive Golf'),
  ('United States', 'Hidden Acres Golf Course'),
  ('United States', 'Hidden Bridge Golf Club'),
  ('United States', 'Hidden Cove Golf Course'),
  ('United States', 'Hidden Creek Country Club'),
  ('United States', 'Hidden Creek Family Golf Course'),
  ('United States', 'Hidden Creek Golf Club'),
  ('United States', 'Hidden Cypress Golf Club'),
  ('United States', 'Hidden Glen At Bentdale Farms'),
  ('United States', 'Hidden Greens'),
  ('United States', 'Hidden Greens North'),
  ('United States', 'Hidden Hills'),
  ('United States', 'Hidden Hills Golf Course'),
  ('United States', 'Hidden Hollow Country Club'),
  ('United States', 'Hidden Lake Country Club'),
  ('United States', 'Hidden Lakes Golf Course'),
  ('United States', 'Hidden Meadows Golf Course'),
  ('United States', 'Hidden Oaks Country Club'),
  ('United States', 'Hidden Oaks Golf Course'),
  ('United States', 'Hidden River Golf and Casting Club'),
  ('United States', 'Hidden Springs Country Club'),
  ('United States', 'Hidden Springs Golf Course'),
  ('United States', 'Hidden Trails Country Club'),
  ('United States', 'Hidden Valley Country Club'),
  ('United States', 'Hidden Valley Country Club Lakes Mountain'),
  ('United States', 'Hidden Valley Country Club Lakes Valley'),
  ('United States', 'Hidden Valley Country Club Mountain Valley'),
  ('United States', 'Hidden Valley Golf Club'),
  ('United States', 'Hidden Valley Golf Course'),
  ('United States', 'Hidden Valley Golf Resort'),
  ('United States', 'Hidden Valley Lake Golf Course'),
  ('United States', 'Hidden Valley Rv And Golf Park'),
  ('United States', 'Hidden Valley Rv And Golf Park Par 3'),
  ('United States', 'Hidden Waters Golf Course'),
  ('United States', 'Hiddenbrooke Golf Club'),
  ('United States', 'Hideaway Beach Golf Course'),
  ('United States', 'Hideaway Hills Golf Club'),
  ('United States', 'Hideout Golf Club'),
  ('United States', 'High Bridge Hills Golf Club'),
  ('United States', 'High Cliff Public Golf Course'),
  ('United States', 'High Grove Golf'),
  ('United States', 'High Hampton'),
  ('United States', 'High Meadows Country Club'),
  ('United States', 'High Meadows Golf Country Club'),
  ('United States', 'High Peaks Golf Course'),
  ('United States', 'High Point Country Club'),
  ('United States', 'High Point Golf Club'),
  ('United States', 'High Point Golf Course'),
  ('United States', 'High Pointe Golf Club'),
  ('United States', 'High Pointe Golf Course'),
  ('United States', 'High Ridge Country Club'),
  ('United States', 'High Valley Country Club'),
  ('United States', 'Highfield Club'),
  ('United States', 'Highfields Golf Country Club'),
  ('United States', 'Highland 9 Hole Golf Course'),
  ('United States', 'Highland At Brae Burn Country Club'),
  ('United States', 'Highland Country Club'),
  ('United States', 'Highland Creek Golf Club'),
  ('United States', 'Highland Fairways Golf Club'),
  ('United States', 'Highland Florida Golf Club'),
  ('United States', 'Highland Golf Club'),
  ('United States', 'Highland Golf Course'),
  ('United States', 'Highland Green Golf Club'),
  ('United States', 'Highland Greens Golf Course'),
  ('United States', 'Highland Hills Golf Course'),
  ('United States', 'Highland Lake Golf Course'),
  ('United States', 'Highland Links Cape Cod'),
  ('United States', 'Highland Links Golf Club'),
  ('United States', 'Highland Meadow Creek At Lancaster Country Club'),
  ('United States', 'Highland Meadows Golf Club'),
  ('United States', 'Highland Meadows Golf Country Club'),
  ('United States', 'Highland Meadows Golf Course'),
  ('United States', 'Highland National Golf Course'),
  ('United States', 'Highland Palms Senior Estates Country Club'),
  ('United States', 'Highland Park Golf Club'),
  ('United States', 'Highland Park Golf Course'),
  ('United States', 'Highland Spring Golf Course'),
  ('United States', 'Highland Springs Golf Course'),
  ('United States', 'Highland Springs Municipal Golf Course'),
  ('United States', 'Highland Springs Village Golf Club'),
  ('United States', 'Highland Walk At Victoria Bryant'),
  ('United States', 'Highland Woods Golf Country Club'),
  ('United States', 'Highland Woods Golf Course'),
  ('United States', 'Highlander Golf Club'),
  ('United States', 'Highlands At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Highlands At Dove Mountain'),
  ('United States', 'Highlands At Grand Geneva Resort Spa'),
  ('United States', 'Highlands Country Club'),
  ('United States', 'Highlands Course'),
  ('United States', 'Highlands Falls Country Club'),
  ('United States', 'Highlands Golf Club'),
  ('United States', 'Highlands Golf Club Hidden Valley Course'),
  ('United States', 'Highlands Golf Club Seven Springs Course'),
  ('United States', 'Highlands Golf Club The'),
  ('United States', 'Highlands Golf Course'),
  ('United States', 'Highlands Marshwood At Highland Oaks Golf Course'),
  ('United States', 'Highlands Of Donegal Golf Course'),
  ('United States', 'Highlands Reserve Golf Club'),
  ('United States', 'Highlands of Elgin'),
  ('United States', 'Hilaman Park Municipal Golf Course'),
  ('United States', 'Hiland Golf Course'),
  ('United States', 'Hiland Park Country Club'),
  ('United States', 'Hilands Golf Club'),
  ('United States', 'Hill At Castlewood Country Club'),
  ('United States', 'Hill Crest Country Club'),
  ('United States', 'Hill Golf Course'),
  ('United States', 'Hill N Dale Golf Country Club'),
  ('United States', 'Hill Ridge At La Paloma Country Club'),
  ('United States', 'Hill Top'),
  ('United States', 'Hill Top At The Villages Executive Golf Trail'),
  ('United States', 'Hillandale Country Club'),
  ('United States', 'Hillandale Golf Course'),
  ('United States', 'Hillcrest'),
  ('United States', 'Hillcrest Country Club'),
  ('United States', 'Hillcrest Country Club of Dallas County'),
  ('United States', 'Hillcrest Event Center'),
  ('United States', 'Hillcrest Golf & Country Club'),
  ('United States', 'Hillcrest Golf Center'),
  ('United States', 'Hillcrest Golf Club'),
  ('United States', 'Hillcrest Golf Club At Sun City West'),
  ('United States', 'Hillcrest Golf Country Club'),
  ('United States', 'Hillcrest Golf Course'),
  ('United States', 'Hillcrest Golf and Country Club'),
  ('United States', 'Hilldale Golf Club'),
  ('United States', 'Hillendale Golf Course'),
  ('United States', 'Hillhigh Hotel Spa Golf Resort Cedar Glade Golf Course'),
  ('United States', 'Hilliard Lakes Golf Club'),
  ('United States', 'Hills At Hernando Country Club'),
  ('United States', 'Hills At Jupiter Hills Club'),
  ('United States', 'Hills At Rotonda Golf Country Club'),
  ('United States', 'Hills Heart of the Lakes Golf Course'),
  ('United States', 'Hillsboro Elks Golf Course'),
  ('United States', 'Hillsboro Municipal Golf'),
  ('United States', 'Hillsborough Country Club'),
  ('United States', 'Hillsdale Country Club'),
  ('United States', 'Hillside Country Club'),
  ('United States', 'Hillside Golf Club'),
  ('United States', 'Hillside Links'),
  ('United States', 'Hilltop Country Club'),
  ('United States', 'Hilltop Golf Course'),
  ('United States', 'Hillview Country Club'),
  ('United States', 'Hillview Golf Course'),
  ('United States', 'Hilly Haven Golf Course'),
  ('United States', 'Hilo Municipal Golf Course'),
  ('United States', 'Hilton Chicago/Indian Lakes Resort'),
  ('United States', 'Hilton Head National Golf Club'),
  ('United States', 'Hinckley Hills Golf Course'),
  ('United States', 'Hinsdale Golf Club'),
  ('United States', 'Historic Black Knight Municipal Park'),
  ('United States', 'Hiwan Golf Club'),
  ('United States', 'Hoakalei Country Club At Ocean Pointe'),
  ('United States', 'Hobart Municipal Golf Course'),
  ('United States', 'Hobble Creek Golf Course'),
  ('United States', 'Hobbs Country Club'),
  ('United States', 'Hobbs Hole Golf Course'),
  ('United States', 'Hobe Sound Golf Club'),
  ('United States', 'Hocking Hills Golf Club'),
  ('United States', 'Hogansville Golf Club'),
  ('United States', 'Holbrook Country Club'),
  ('United States', 'Holden Hills Country Club'),
  ('United States', 'Hole 1'),
  ('United States', 'Hole 2'),
  ('United States', 'Hole 3'),
  ('United States', 'Hole In One Golf Center'),
  ('United States', 'Hole In The Wall Golf Club'),
  ('United States', 'Holiday Hills Golf Course'),
  ('United States', 'Holiday Hills Resort And Golf Club'),
  ('United States', 'Holiday Inn Golf Course'),
  ('United States', 'Holiday Lodge Golf Resort'),
  ('United States', 'Holiday Meadows Golf Course'),
  ('United States', 'Holland Heights Golf Course'),
  ('United States', 'Holland Hills Country Club'),
  ('United States', 'Holland Lake Golf Course'),
  ('United States', 'Holland Meadows Golf Course'),
  ('United States', 'Hollenback Golf Club'),
  ('United States', 'Holley Brook Golf Course'),
  ('United States', 'Holliday Farms'),
  ('United States', 'Hollis Golf Country Club'),
  ('United States', 'Hollow Acres Golf Center'),
  ('United States', 'Hollow Brook Golf Course'),
  ('United States', 'Holly Hills Golf Course'),
  ('United States', 'Holly Meadows Golf Course'),
  ('United States', 'Holly Ridge Golf Club'),
  ('United States', 'Holly Ridge Golf Course'),
  ('United States', 'Holly Ridge Golf Links'),
  ('United States', 'Holly Tree Country Club'),
  ('United States', 'Hollybrook Country Club'),
  ('United States', 'Hollydot Golf Course'),
  ('United States', 'Hollywood Beach Golf Country Club'),
  ('United States', 'Hollywood Golf Club'),
  ('United States', 'Holmes County Country Club'),
  ('United States', 'Holmes Harbor Golf Club'),
  ('United States', 'Holmes Park Golf Course'),
  ('United States', 'Holston Hills Community Golf Course'),
  ('United States', 'Holton Country Club'),
  ('United States', 'Holyoke Golf Club'),
  ('United States', 'Homer Golf Course'),
  ('United States', 'Homestead Golf Club'),
  ('United States', 'Homestead Golf Course'),
  ('United States', 'Homestead Old Mill At Flat Creek Golf Club'),
  ('United States', 'Homestead Springs Golf Course'),
  ('United States', 'Homewood Acres Golf Course'),
  ('United States', 'Homewood Golf Course'),
  ('United States', 'Hominy Hill Golf Course'),
  ('United States', 'Hon-E-Kor Country Club'),
  ('United States', 'Honesdale Golf Club'),
  ('United States', 'Honey Bee Golf Club'),
  ('United States', 'Honey Creek Golf Club'),
  ('United States', 'Honey Creek Golf Country Club'),
  ('United States', 'Honey Creek Golf Course'),
  ('United States', 'Honey Pond Farm'),
  ('United States', 'Honey Run Golf Club'),
  ('United States', 'Honeybrook Golf Club'),
  ('United States', 'Honeysuckle At The Villages Executive Golf Trail'),
  ('United States', 'Honeywell Golf Course'),
  ('United States', 'Honolulu Country Club'),
  ('United States', 'Hood River Golf Country Club'),
  ('United States', 'Hoodkroft Country Club'),
  ('United States', 'Hooper Golf Course'),
  ('United States', 'Hoopers Landing Golf Course'),
  ('United States', 'Hoosick Falls Country Club'),
  ('United States', 'Hoosier Heights Country Club'),
  ('United States', 'Hoosier Links Golf Club'),
  ('United States', 'Hop Brook Golf Course'),
  ('United States', 'Hop Meadow Country Club'),
  ('United States', 'Hope Country Club'),
  ('United States', 'Hope Golf Club'),
  ('United States', 'Hope Valley Country Club'),
  ('United States', 'Hopedale Country Club'),
  ('United States', 'Hopewell Valley Golf Country Club'),
  ('United States', 'Hopkinton Country Club'),
  ('United States', 'Hopson Hills Golf Course'),
  ('United States', 'Horn Rapids Golf Club'),
  ('United States', 'Hornell Golf Club'),
  ('United States', 'Horseleg Plantation Country Club'),
  ('United States', 'Horsepasture Par 3 Golf Course'),
  ('United States', 'Horseshoe Bay Golf Club'),
  ('United States', 'Horseshoe Bend Country Club'),
  ('United States', 'Horseshoe Bend Golf Course'),
  ('United States', 'Horseshoe Lake Golf Course'),
  ('United States', 'Hot Springs Country Club Arlington Course'),
  ('United States', 'Hot Springs Country Club Park Course'),
  ('United States', 'Hotchkiss School Golf Course'),
  ('United States', 'Houlton Community Golf Course'),
  ('United States', 'Houma Golf Club'),
  ('United States', 'Hound Ears Club'),
  ('United States', 'House on the Rock Resort'),
  ('United States', 'Houston Country Club'),
  ('United States', 'Houston Lake Country Club'),
  ('United States', 'Houston Springs Resort And Golf Course'),
  ('United States', 'Howell Par 3 Golf Course'),
  ('United States', 'Howell Park Golf Course'),
  ('United States', 'Hoxie Golf Course'),
  ('United States', 'Hoyt Lakes Municipal Golf Course'),
  ('United States', 'Hualalai Golf Course'),
  ('United States', 'Hubbard Golf Course Hill Afb'),
  ('United States', 'Hubbard Golf and Recreation Club'),
  ('United States', 'Huckleberry Creek Golf Course'),
  ('United States', 'Hudson Hills Golf Course'),
  ('United States', 'Hudson Mills Metropark Golf Course'),
  ('United States', 'Hudson National Golf Club'),
  ('United States', 'Hudson Valley Resort Conference Center'),
  ('United States', 'Hueston Woods State Park Golf Course'),
  ('United States', 'Hugo Golf Club'),
  ('United States', 'Huletts Golf Club'),
  ('United States', 'Hulman Links Golf Course'),
  ('United States', 'Humboldt  Country  Club'),
  ('United States', 'Humeston Lakeside Golf Course'),
  ('United States', 'Humphreys County Country Club'),
  ('United States', 'Hunter Country Club'),
  ('United States', 'Hunter Golf Club'),
  ('United States', 'Hunter Pope Country Club'),
  ('United States', 'Hunter Ranch Golf Course'),
  ('United States', 'Hunters Glen Golf Club'),
  ('United States', 'Hunters Green Country Club'),
  ('United States', 'Hunters Ridge Country Club'),
  ('United States', 'Hunters Ridge Golf Course'),
  ('United States', 'Hunters Run Golf Course'),
  ('United States', 'Hunters Station Golf Course'),
  ('United States', 'Hunting Creek Golf Course'),
  ('United States', 'Hunting Hawk Golf Club'),
  ('United States', 'Hunting Hills Country Club'),
  ('United States', 'Huntingburg Country Club'),
  ('United States', 'Huntingdon Country Club'),
  ('United States', 'Huntington Country Club'),
  ('United States', 'Huntington Crescent Club'),
  ('United States', 'Huntington Golf Club'),
  ('United States', 'Huntington Hills Golf Country Club'),
  ('United States', 'Huntington Park Golf Course'),
  ('United States', 'Huntmore Golf Club'),
  ('United States', 'Huntsman Springs Golf Club'),
  ('United States', 'Huntsville Golf Club'),
  ('United States', 'Huron Breeze Golf and Country Club'),
  ('United States', 'Huron Hills Golf Course'),
  ('United States', 'Huron Meadows Golf Course'),
  ('United States', 'Huron Oaks Golf Course'),
  ('United States', 'Huron Pines Golf and Country Club'),
  ('United States', 'Huron Shores Golf Club & Restaurant'),
  ('United States', 'Hurricane Golf Country Club'),
  ('United States', 'Hurryville Driving Range'),
  ('United States', 'Hurryville Driving Range Par 3'),
  ('United States', 'Hurstbourne Country Club'),
  ('United States', 'Huukan Golf Club'),
  ('United States', 'Hyannis Golf Club'),
  ('United States', 'Hyannisport Club'),
  ('United States', 'Hyatt Hills Golf Complex'),
  ('United States', 'Hyde Park Golf & Country Club'),
  ('United States', 'Hyde Park Golf Club'),
  ('United States', 'Hydeaway Golf'),
  ('United States', 'Hyland Golf Club'),
  ('United States', 'Hyland Greens Golf Course'),
  ('United States', 'Hyperion Field Club'),
  ('United States', 'Hyperion Golf Course'),
  ('United States', 'IBM Disc Golf Course'),
  ('United States', 'IMA Brookwood Golf Club'),
  ('United States', 'Ibis Golf Course At Pelican Preserve Golf Club'),
  ('United States', 'Ibis Landing Golf Country Club'),
  ('United States', 'Ida Grove Golf and Country Club'),
  ('United States', 'Idabel Country Club'),
  ('United States', 'Idaho Falls Country Club'),
  ('United States', 'Idle Creek Golf Course'),
  ('United States', 'Idle Hour Golf Country Club'),
  ('United States', 'IdleWild Golf Club'),
  ('United States', 'Idlewild Country Club'),
  ('United States', 'Idylwyld Golf Club'),
  ('United States', 'Illini Golf Course'),
  ('United States', 'Illinois Valley Golf Club'),
  ('United States', 'Img Academy Golf Club'),
  ('United States', 'Immergrun Golf Club'),
  ('United States', 'Imperial Lakes Golf Country Club'),
  ('United States', 'Independence Country Club'),
  ('United States', 'Independence Golf Club Championship'),
  ('United States', 'Independence Golf Club The Bear Course'),
  ('United States', 'Indian Bayou Golf Club'),
  ('United States', 'Indian Bluff Forest Preserve Golf Course'),
  ('United States', 'Indian Boundary Golf Course'),
  ('United States', 'Indian Camp Golf Course'),
  ('United States', 'Indian Canyon Golf Course'),
  ('United States', 'Indian Canyons Golf Resort North Course'),
  ('United States', 'Indian Canyons Golf Resort South Course'),
  ('United States', 'Indian Creek Country Club'),
  ('United States', 'Indian Creek Golf Course'),
  ('United States', 'Indian Head Golf Course'),
  ('United States', 'Indian Hill Country Club'),
  ('United States', 'Indian Hill Golf Club'),
  ('United States', 'Indian Hill Golf Course'),
  ('United States', 'Indian Hills Country Club'),
  ('United States', 'Indian Hills Golf Club'),
  ('United States', 'Indian Hills Golf Course'),
  ('United States', 'Indian Hills Golf Resort'),
  ('United States', 'Indian Hills State Golf Course'),
  ('United States', 'Indian Island Country Club'),
  ('United States', 'Indian Lake Estates Golf Country Club'),
  ('United States', 'Indian Lake Golf Club'),
  ('United States', 'Indian Lake Golf and Country Club'),
  ('United States', 'Indian Lake Hills Golf Course'),
  ('United States', 'Indian Lakes Golf Club'),
  ('United States', 'Indian Meadows Golf Club'),
  ('United States', 'Indian Mound Golf Club'),
  ('United States', 'Indian Mountain Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Indian Palms Golf Country Club Indian Mountain'),
  ('United States', 'Indian Palms Golf Country Club Mountain Royal'),
  ('United States', 'Indian Palms Golf Country Club Royal Indian'),
  ('United States', 'Indian Peaks Golf Club'),
  ('United States', 'Indian Pond Country Club'),
  ('United States', 'Indian Ridge Country Club'),
  ('United States', 'Indian Ridge Country Club Arroyo Course'),
  ('United States', 'Indian Ridge Country Club Grove Course'),
  ('United States', 'Indian Ridge Golf Club'),
  ('United States', 'Indian River Club'),
  ('United States', 'Indian River Colony Club'),
  ('United States', 'Indian River Golf Club'),
  ('United States', 'Indian River Preserve Golf Club'),
  ('United States', 'Indian Run Golf Club'),
  ('United States', 'Indian Run Golf Course'),
  ('United States', 'Indian Spring Country Club East Course'),
  ('United States', 'Indian Spring Country Club West Course'),
  ('United States', 'Indian Spring Golf Club'),
  ('United States', 'Indian Springs Country Club'),
  ('United States', 'Indian Springs Golf And Country Club'),
  ('United States', 'Indian Springs Golf Club'),
  ('United States', 'Indian Springs Golf Course'),
  ('United States', 'Indian Springs Metropark Golf Course'),
  ('United States', 'Indian Springs Ranch'),
  ('United States', 'Indian Summer Golf Country Club'),
  ('United States', 'Indian Trace Golf Course'),
  ('United States', 'Indian Trail Golf Course'),
  ('United States', 'Indian Trails Golf Course'),
  ('United States', 'Indian Valley Country Club'),
  ('United States', 'Indian Valley Golf Club'),
  ('United States', 'Indian Valley Golf Course'),
  ('United States', 'Indian Wells Country Club The Classic Course'),
  ('United States', 'Indian Wells Country Club The Cove Course'),
  ('United States', 'Indian Wells Golf Resort Celebrity Course'),
  ('United States', 'Indian Wells Golf Resort Players Course'),
  ('United States', 'Indiana Country Club'),
  ('United States', 'Indianhead Golf Course'),
  ('United States', 'Indianola Country Club'),
  ('United States', 'Indianwood Gold & Country Club'),
  ('United States', 'Indianwood Golf Country Club'),
  ('United States', 'Indigo Creek Golf Club'),
  ('United States', 'Indio Golf Club'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Eisenhower Course'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Zaharias Course'),
  ('United States', 'Ingersoll Golf Course'),
  ('United States', 'Ingleside Golf Club'),
  ('United States', 'Ingleside Resort Country Club'),
  ('United States', 'Inglewood Country Club'),
  ('United States', 'Inkster Valley Golf Course'),
  ('United States', 'Inland Greens Golf Course'),
  ('United States', 'Inlet Golf Club'),
  ('United States', 'Inn Of The Mountain Gods'),
  ('United States', 'Inness Golf Course'),
  ('United States', 'Innis Arden Golf Club'),
  ('United States', 'Innisbrook Resort Golf Club Copperhead Course'),
  ('United States', 'Innisbrook Resort Golf Club Fox Squirrel Course'),
  ('United States', 'Innisbrook Resort Golf Club Island Course'),
  ('United States', 'Innisbrook Resort Golf Club North Course'),
  ('United States', 'Innisbrook Resort Golf Club South Course'),
  ('United States', 'Inniscrone Golf Club'),
  ('United States', 'Innsbrook Country Club'),
  ('United States', 'Innsbrook Golf Course'),
  ('United States', 'Innsbrook Village Country Club'),
  ('United States', 'Inshalla Country Club'),
  ('United States', 'Interbay Family Golf Center'),
  ('United States', 'Interlachen Country Club'),
  ('United States', 'Interlaken Golf Club'),
  ('United States', 'Interlochen Golf Course'),
  ('United States', 'Interlocken Golf Club Eldorado Sunshine'),
  ('United States', 'Interlocken Golf Club Sunshine Vista'),
  ('United States', 'Interlocken Golf Club Vista Eldorado'),
  ('United States', 'International At Cedar Valley Golf Club'),
  ('United States', 'International City Golf Club'),
  ('United States', 'International Club Of Myrtle Beach'),
  ('United States', 'International Country Club'),
  ('United States', 'International Golf Club Oaks Course'),
  ('United States', 'International Golf Club Pines Course'),
  ('United States', 'Intervale Country Club'),
  ('United States', 'Intimidator Golf Course'),
  ('United States', 'Inver Wood Golf Course'),
  ('United States', 'Inverness Club'),
  ('United States', 'Inverness Country Club'),
  ('United States', 'Inverness Golf Club'),
  ('United States', 'Inverness Golf Country Club'),
  ('United States', 'Inverness Hotel Golf Club'),
  ('United States', 'Inverugie Golf Club'),
  ('United States', 'Inwood Country Club'),
  ('United States', 'Inwood Golf Course'),
  ('United States', 'Ipswich Country Club'),
  ('United States', 'Irem Country Club'),
  ('United States', 'Irene Golf And Country Club'),
  ('United States', 'Irish Green Golf Course'),
  ('United States', 'Irish Hills Golf Club'),
  ('United States', 'Irish Hills Shore Golf Course'),
  ('United States', 'Irish Oaks Golf Course and Driving Range'),
  ('United States', 'Irish Waters Golf Course'),
  ('United States', 'Iron Forge At Penn National Golf Club Inn'),
  ('United States', 'Iron Horse Golf Club'),
  ('United States', 'Iron Horse Golf Course'),
  ('United States', 'Iron Links Golf Course'),
  ('United States', 'Iron Masters Country Club'),
  ('United States', 'Iron Play Golf Course'),
  ('United States', 'Iron River Country Club'),
  ('United States', 'Iron Valley Golf Club'),
  ('United States', 'Iron Wolf Golf Country Club'),
  ('United States', 'Ironbridge Golf Club'),
  ('United States', 'Ironclad Golf And Beer Garden'),
  ('United States', 'Irondequoit Country Club'),
  ('United States', 'Ironhorse Golf Club'),
  ('United States', 'Ironwood Acacia At Kierland Golf Club'),
  ('United States', 'Ironwood Country Club'),
  ('United States', 'Ironwood Golf Club'),
  ('United States', 'Ironwood Golf Country Club'),
  ('United States', 'Ironwood Golf Course'),
  ('United States', 'Ironwood Golf Range'),
  ('United States', 'Ironwood Green Golf Course'),
  ('United States', 'Ironwood Hills Golf Club'),
  ('United States', 'Iroquois Golf Club'),
  ('United States', 'Iroquois Golf Course'),
  ('United States', 'Irv Warren Memorial Golf Course'),
  ('United States', 'Irwin Country Club'),
  ('United States', 'Isabella Golf Course Nina'),
  ('United States', 'Isabella Golf Course Pinta'),
  ('United States', 'Isabella Golf Course Santa Maria'),
  ('United States', 'Ischua Valley Country Club'),
  ('United States', 'Isla Del Sol Golf Yacht Country Club'),
  ('United States', 'Island At Holiday Island Country Club'),
  ('United States', 'Island Country Club'),
  ('United States', 'Island Dunes Country Club'),
  ('United States', 'Island Green Golf Course'),
  ('United States', 'Island Green Longest Hole At Meadows Farms Golf Course'),
  ('United States', 'Island Green Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Island Hills Golf Club'),
  ('United States', 'Island Lake Golf'),
  ('United States', 'Island Oaks At Lima Golf Country Club'),
  ('United States', 'Island Park Village Resort'),
  ('United States', 'Island Pines Golf Club'),
  ('United States', 'Island Valley Golf Course'),
  ('United States', 'Island West Golf Club'),
  ('United States', 'Islands End Golf Country Club'),
  ('United States', 'Isle Dauphine Golf Club'),
  ('United States', 'Isleta Eagle Golf Course Arroyo Mesa Course'),
  ('United States', 'Isleta Eagle Golf Course Lakes Arroyo Course'),
  ('United States', 'Isleta Eagle Golf Course Mesa Lakes Course'),
  ('United States', 'Isleworth Country Club'),
  ('United States', 'Itasca Country Club'),
  ('United States', 'Iuka Country Club'),
  ('United States', 'Ivanhoe Club'),
  ('United States', 'Ives Grove Golf Links'),
  ('United States', 'Ives Hill Country Club'),
  ('United States', 'Ivey Ranch Country Club'),
  ('United States', 'Ivy Hill Golf Club'),
  ('United States', 'Ivy Hills Country Club'),
  ('United States', 'Iyopawa Island Golf Course'),
  ('United States', 'J B Golf Course'),
  ('United States', 'J F Kennedy Golf Center Par 3 Course'),
  ('United States', 'J F Kennedy Golf Center West Creek Course'),
  ('United States', 'J S Clark Park Golf Course'),
  ('United States', 'Jacaranda West Country Club'),
  ('United States', 'Jack Frost National Golf Course'),
  ('United States', 'Jack Olantern Golf Resort'),
  ('United States', 'Jackpot Golf Club'),
  ('United States', 'Jackson College Disc Golf'),
  ('United States', 'Jackson County Country Club'),
  ('United States', 'Jackson Golf Club'),
  ('United States', 'Jackson Heights Golf Club'),
  ('United States', 'Jackson Hole Golf Tennis Club'),
  ('United States', 'Jackson Park Driving Range'),
  ('United States', 'Jackson Park Golf Course'),
  ('United States', 'Jackson Valley Country Club'),
  ('United States', 'Jacksonville Beach Golf Club'),
  ('United States', 'Jacksonville Country Club'),
  ('United States', 'Jacksonville Golf Country Club'),
  ('United States', 'Jacob Riis Park Golf Course'),
  ('United States', 'Jacoby Golf Course'),
  ('United States', 'Jade Trace At Mystic Meadows'),
  ('United States', 'Jake Gaither Municipal Golf Course'),
  ('United States', 'Jal Country Club'),
  ('United States', 'James Baird State Park Golf Course'),
  ('United States', 'James C Haggerty North Kern Golf Course'),
  ('United States', 'James E Stewart Golf Course'),
  ('United States', 'James River Country Club'),
  ('United States', 'Jamestown Golf Course'),
  ('United States', 'Jamestown Park Golf Course'),
  ('United States', 'Janesville Country Club'),
  ('United States', 'Jasper Hills Golf Club'),
  ('United States', 'Jato Highlands Golf Course'),
  ('United States', 'Jawbone Creek Country Club'),
  ('United States', 'Jay Peak Golf Course'),
  ('United States', 'Jaycee Golf Course'),
  ('United States', 'Jefferson Barracks Golf Tee'),
  ('United States', 'Jefferson Country Club'),
  ('United States', 'Jefferson District Golf Course'),
  ('United States', 'Jefferson Golf Club'),
  ('United States', 'Jefferson Hills Golf Recreation'),
  ('United States', 'Jefferson Lakeside Country Club'),
  ('United States', 'Jefferson Landing On The New River'),
  ('United States', 'Jeffersonville Golf Club'),
  ('United States', 'Jekyll Island Golf Club Great Dunes Course'),
  ('United States', 'Jekyll Island Golf Club Indian Mound Course'),
  ('United States', 'Jekyll Island Golf Club Pine Lakes Course'),
  ('United States', 'Jennings Golf Club'),
  ('United States', 'Jennings Mill Country Club'),
  ('United States', 'Jenny Wiley State Resort Park'),
  ('United States', 'Jensen Beach Golf Club'),
  ('United States', 'Jeptha Lake Golf Course'),
  ('United States', 'Jeremy Ranch Golf Country Club'),
  ('United States', 'Jeremy S Creek'),
  ('United States', 'Jericho National Golf Club'),
  ('United States', 'Jerome Country Club'),
  ('United States', 'Jerry Tim Brooks Golf Course'),
  ('United States', 'Jester Park Executive Golf Course'),
  ('United States', 'Jester Park Golf Course'),
  ('United States', 'Jester Park Learning and Practice Facility'),
  ('United States', 'Jesup Golf & Country Club'),
  ('United States', 'Jewel Golf Course - Grand Nine'),
  ('United States', 'Jewel Golf Course - Woods Nine'),
  ('United States', 'Jewell Golf and Country Club'),
  ('United States', 'Jimmie Austin Golf Course'),
  ('United States', 'Jimmie Austin University Of Oklahoma Golf Course'),
  ('United States', 'Jo Daddys Golf Course'),
  ('United States', 'Joa Company Golf Course'),
  ('United States', 'Joe Louis "The Champ" Golf Course'),
  ('United States', 'John A White Golf Course'),
  ('United States', 'John Conrad Golf Course'),
  ('United States', 'John F Byrne Golf Course'),
  ('United States', 'John James Audubon Golf Course'),
  ('United States', 'John P Larkin Country Club'),
  ('United States', 'John Prince Golf Learning Center'),
  ('United States', 'Johnny Goodman Golf Course'),
  ('United States', 'Johnson County Country Club'),
  ('United States', 'Johnson Park Golf Course'),
  ('United States', 'Johnson Ridge Golf Course'),
  ('United States', 'Johnson W Parks Golf Course'),
  ('United States', 'Joliet Country Club (closed)'),
  ('United States', 'Jonathans Landing Golf Club Match Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Club Medal Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Course'),
  ('United States', 'Jonathans Landing Village Course'),
  ('United States', 'Jones At Lyman Orchards Golf Club'),
  ('United States', 'Jones At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Jones Beach State Park Golf Course'),
  ('United States', 'Jones Golf Course'),
  ('United States', 'Jones Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Jones Masterpiece At Treetops Resort'),
  ('United States', 'Jonesboro Country Club'),
  ('United States', 'Jordan River Par Three Golf Course'),
  ('United States', 'Joseph C Martin Golf Course'),
  ('United States', 'Joseph M Bartholomew Golf Course'),
  ('United States', 'Journey At Pechanga'),
  ('United States', 'Journey S End Golf Course'),
  ('United States', 'Jrs Pub Grill Golf Course'),
  ('United States', 'Juan De Fuca Parks Golf Club'),
  ('United States', 'Juday Creek Golf Course'),
  ('United States', 'Judge Rodney S. Webb Memorial Golf Park'),
  ('United States', 'Judith Shadows Golf Course'),
  ('United States', 'Jug Mountain Ranch Golf Course'),
  ('United States', 'Juliette Falls'),
  ('United States', 'Julington Creek Golf Club'),
  ('United States', 'Jumping Brook Country Club'),
  ('United States', 'Junction City Golf Course'),
  ('United States', 'Jungle At Green Meadow Golf Club'),
  ('United States', 'Juniata Golf Club'),
  ('United States', 'Junior National Golf Club'),
  ('United States', 'Juniper Hill Golf Course'),
  ('United States', 'Juniper Hills Country Club'),
  ('United States', 'Juniper Ridge R V Resort'),
  ('United States', 'Jupiter Country Club'),
  ('United States', 'Jupiter Dunes Golf Course'),
  ('United States', 'Jupiter Island Club'),
  ('United States', 'Jurupa Hills Country Club'),
  ('United States', 'Kaanapali Kai'),
  ('United States', 'Kah Wah C Country Club'),
  ('United States', 'Kahili Golf Course'),
  ('United States', 'Kahkwa Club'),
  ('United States', 'Kahler Mountain Club'),
  ('United States', 'Kahuku Golf Course'),
  ('United States', 'Kalamazoo Country Club'),
  ('United States', 'Kalispel Golf Country Club'),
  ('United States', 'Kalona Golf Club'),
  ('United States', 'Kaluhyat Golf Club At Turning Stone'),
  ('United States', 'Kampen Golf Course'),
  ('United States', 'Kane Country Club'),
  ('United States', 'Kaneohe Klipper Golf Course'),
  ('United States', 'Kankakee Country Club'),
  ('United States', 'Kankakee Elks Country Club'),
  ('United States', 'Kanon Valley Country Club'),
  ('United States', 'Kansas City Country Club'),
  ('United States', 'Kapalua Resort The Bay Course'),
  ('United States', 'Kapalua Resort The Plantation Course'),
  ('United States', 'Kapolei Golf Club'),
  ('United States', 'Karsten Creek Golf Club'),
  ('United States', 'Katahdin Country Club'),
  ('United States', 'Katke Golf Course'),
  ('United States', 'Kaufman Golf Course'),
  ('United States', 'Kaylers Bend Golf Course'),
  ('United States', 'Ke Olu Course At Hualalai'),
  ('United States', 'Kealohi Par 3 Golf Course'),
  ('United States', 'Kearny Golf Club'),
  ('United States', 'Kearsley Lake Golf Course'),
  ('United States', 'Kebo Valley Club'),
  ('United States', 'Keene Country Club'),
  ('United States', 'Keith Hills Golf Club Black Course'),
  ('United States', 'Keith Hills Golf Club Orange Course'),
  ('United States', 'Keith Hills Golf Club White Course'),
  ('United States', 'Kelley Greens Golf Course'),
  ('United States', 'Kellogg Executive 9'),
  ('United States', 'Kellogg Golf Course'),
  ('United States', 'Kelly Greens Golf Country Club'),
  ('United States', 'Kelly Plantation Golf Club'),
  ('United States', 'Kelly''s Miniature Golf'),
  ('United States', 'Kemper Lakes Golf Club'),
  ('United States', 'Kempsville Greens Golf Course'),
  ('United States', 'Ken Mcdonald Golf Course'),
  ('United States', 'Kenai Golf Course'),
  ('United States', 'Kendrick Golf Course'),
  ('United States', 'Kenduskeag Valley Golf Club'),
  ('United States', 'Keney Park Golf Club'),
  ('United States', 'Kenmure Country Club'),
  ('United States', 'Kennett Country Club'),
  ('United States', 'Kennett Square Golf Country Club'),
  ('United States', 'Kenosha Country Club'),
  ('United States', 'Kensington Driving Range'),
  ('United States', 'Kensington Golf Club'),
  ('United States', 'Kensington Golf Country Club'),
  ('United States', 'Kensington Metropark Golf Course'),
  ('United States', 'Kent Country Club'),
  ('United States', 'Kenterra Golf Course'),
  ('United States', 'Kenton Station Golf Course'),
  ('United States', 'Kentucky Dam Village State Resort Park'),
  ('United States', 'Kenwanda Golf Course'),
  ('United States', 'Kenwood Country Club'),
  ('United States', 'Kenwood Golf Country Club'),
  ('United States', 'Kenya Hemingway At Havana Country Club'),
  ('United States', 'Kenyon Country Club'),
  ('United States', 'Keokuk Country Club'),
  ('United States', 'Keowee Key Golf Country Club'),
  ('United States', 'Kern River Golf Course'),
  ('United States', 'Kern Valley Golf Course'),
  ('United States', 'Kernoustie Golf Club'),
  ('United States', 'Kernwood Country Club'),
  ('United States', 'Kerr Lake Country Club'),
  ('United States', 'Kershaw Country Club'),
  ('United States', 'Kestrel Ridge Golf Club'),
  ('United States', 'Kettle Brook Golf Club'),
  ('United States', 'Kettle Hills Golf Course'),
  ('United States', 'Kettle Valley Golf Club'),
  ('United States', 'Kewanee Dunes Golf Club'),
  ('United States', 'Keweenaw Mountain Lodge Golf Course'),
  ('United States', 'Key Colony Beach Golf Tennis'),
  ('United States', 'Key Royale Club'),
  ('United States', 'Key Vista Country Club'),
  ('United States', 'Key West Golf Club'),
  ('United States', 'Keyhole Country Club'),
  ('United States', 'Keystone Golf Country Club'),
  ('United States', 'Keystone Golf Course'),
  ('United States', 'Keystone Ranch Golf Course'),
  ('United States', 'Kiahuna Golf Club'),
  ('United States', 'Kiawah Island Club Cassique Course'),
  ('United States', 'Kiawah Island Club River Course'),
  ('United States', 'Kickingbird Golf Club'),
  ('United States', 'Kilgores Roundabout Plantation Golf Course'),
  ('United States', 'Kilimanjaro Kenya At Havana Country Club'),
  ('United States', 'Kilkarney Hills Golf Course'),
  ('United States', 'Killarney Lakeside Golf Club'),
  ('United States', 'Killian Greens Golf Club'),
  ('United States', 'Killington Golf Resort'),
  ('United States', 'Kilmarlic Golf Club'),
  ('United States', 'Kiln Creek Golf Club Resort'),
  ('United States', 'Kimball Farm Golf Club'),
  ('United States', 'Kimball Golf Club'),
  ('United States', 'Kimbeland Country Club'),
  ('United States', 'Kimberly Oaks Golf Club'),
  ('United States', 'Kimberton Golf Club'),
  ('United States', 'Kincaid Lake Golf Course'),
  ('United States', 'Kinderlou Forest Golf Club'),
  ('United States', 'Kinderton Country Club'),
  ('United States', 'King And Bear Golf Course At World Golf Village'),
  ('United States', 'King City Golf Course'),
  ('United States', 'King Ferry Golf Club'),
  ('United States', 'King Kamehameha Golf Club'),
  ('United States', 'King Links Golf Course'),
  ('United States', 'King Rail Reserve Golf Course'),
  ('United States', 'King Ranch Golf Course'),
  ('United States', 'King Valley Golf Course'),
  ('United States', 'King''s Walk'),
  ('United States', 'Kingfisher Golf Course'),
  ('United States', 'Kingham Prairie View Golf Course'),
  ('United States', 'Kings Arrow Ranch Hillsdale Course'),
  ('United States', 'Kings Country Club'),
  ('United States', 'Kings Creek Country Club'),
  ('United States', 'Kings Crossing Golf Club'),
  ('United States', 'Kings Deer Golf Club'),
  ('United States', 'Kings Gate Golf Club'),
  ('United States', 'Kings Grant Golf Country Club'),
  ('United States', 'Kings Mountain Country Club'),
  ('United States', 'Kings Mountain Golf Course'),
  ('United States', 'Kings Point Executive Course'),
  ('United States', 'Kings Point Executive Golf Course'),
  ('United States', 'Kings Point Par 3')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Kings Ridge Golf Club Kings Course'),
  ('United States', 'Kings Ridge Golf Club Ridge Course'),
  ('United States', 'Kings River Golf Country Club'),
  ('United States', 'Kings River Golf Course'),
  ('United States', 'Kings Valley Golf Course'),
  ('United States', 'Kings Walk'),
  ('United States', 'Kings Way Golf Club'),
  ('United States', 'Kingsboro Golf Club'),
  ('United States', 'Kingsmill Resort Plantation Course'),
  ('United States', 'Kingsmill Resort River Course'),
  ('United States', 'Kingston Fairways Golf Club'),
  ('United States', 'Kingsville Golf & Country Club'),
  ('United States', 'Kingswell Glen'),
  ('United States', 'Kingswood Golf Club'),
  ('United States', 'Kingwood Golf Club Resort'),
  ('United States', 'Kinkora Golf Course'),
  ('United States', 'Kinloch Golf Club'),
  ('United States', 'Kino Springs Golf Course'),
  ('United States', 'Kinsale Golf Club'),
  ('United States', 'Kinsale Golf and Fitness Club'),
  ('United States', 'Kinsley Country Club'),
  ('United States', 'Kinston Country Club'),
  ('United States', 'Kira S Kingdom Golf Course'),
  ('United States', 'Kirby Country Club'),
  ('United States', 'Kirkbrae Country Club'),
  ('United States', 'Kirkmans Lakeview Golf Course'),
  ('United States', 'Kirkwood National Golf Club'),
  ('United States', 'Kis N Greens Golf Course'),
  ('United States', 'Kishwaukee Country Club'),
  ('United States', 'Kiski Prep School Golf Course'),
  ('United States', 'Kiskiack Golf Club'),
  ('United States', 'Kissena Park Golf Course'),
  ('United States', 'Kissimmee Bay Country Club'),
  ('United States', 'Kissing Tree Golf Club'),
  ('United States', 'Kitsap Golf Country Club'),
  ('United States', 'Kittanning Country Club'),
  ('United States', 'Klinger Lake Country Club'),
  ('United States', 'Knickerbocker Country Club'),
  ('United States', 'Knights Play Golf Center'),
  ('United States', 'Knights Play Golf Center 9 Hole Par 3'),
  ('United States', 'Knights of Columbus Par 3 Course'),
  ('United States', 'Knob Hill Golf Course'),
  ('United States', 'Knobbs Creek Par 3 Golf Course'),
  ('United States', 'Knoll East Country Club The'),
  ('United States', 'Knoll Run Golf Course'),
  ('United States', 'Knoll View Golf Course'),
  ('United States', 'Knoll West Country Club'),
  ('United States', 'Knolls Country Club'),
  ('United States', 'Knollwood Club Golf Course'),
  ('United States', 'Knollwood Country Club'),
  ('United States', 'Knollwood Country Club - East Course'),
  ('United States', 'Knollwood Country Club - West Course'),
  ('United States', 'Knollwood Fairways'),
  ('United States', 'Knollwood Golf Course'),
  ('United States', 'Ko Olina Golf Club'),
  ('United States', 'Koa Fairways Golf Course'),
  ('United States', 'Koasati Pines At Coushatta'),
  ('United States', 'Kohala Golf Park'),
  ('United States', 'Kohanaiki Club'),
  ('United States', 'Kokomo Country Club'),
  ('United States', 'Kokopelli Club'),
  ('United States', 'Kokopelli Golf Course'),
  ('United States', 'Kona Country Club'),
  ('United States', 'Kona Mansion Inn'),
  ('United States', 'Koronis Hills Golf Club'),
  ('United States', 'Koshkonong Mounds Country Club'),
  ('United States', 'Kountryside Golf Course'),
  ('United States', 'Kraftsmens Club'),
  ('United States', 'Kresson Golf Club'),
  ('United States', 'Krooked Kreek Golf Course'),
  ('United States', 'Krueger-Haskell Golf Course'),
  ('United States', 'Kuehn Golf Course'),
  ('United States', 'Kukio 10 Hole Course'),
  ('United States', 'Kukio Championship Course'),
  ('United States', 'Kukuiolono Golf Course'),
  ('United States', 'Kukuiula Golf Course'),
  ('United States', 'Kulm Golf Club'),
  ('United States', 'Kwiniaska Golf Club'),
  ('United States', 'Kyle Memorial Golf Course'),
  ('United States', 'L A Golf Club'),
  ('United States', 'L W Clapp Golf Club'),
  ('United States', 'L''Anse Golf Club'),
  ('United States', 'L.C. Boles Golf Course Holes 1-2,9'),
  ('United States', 'L.C. Boles Golf Course Holes 3-8'),
  ('United States', 'LYNX Golf Course & Grill'),
  ('United States', 'La Canada Flintridge Country Club'),
  ('United States', 'La Cita Country Club'),
  ('United States', 'La Contenta Golf Club'),
  ('United States', 'La Crosse Country Club'),
  ('United States', 'La Cumbre Country Club'),
  ('United States', 'La Gorce Country Club'),
  ('United States', 'La Grange Country Club'),
  ('United States', 'La Jolla Beach Tennis Club'),
  ('United States', 'La Jolla Country Club'),
  ('United States', 'La Junta Golf Course'),
  ('United States', 'La Mirada Golf Club'),
  ('United States', 'La Porte City Golf Club'),
  ('United States', 'La Purisima Golf Course'),
  ('United States', 'La Quinta Country Club'),
  ('United States', 'La Quinta Resort Citrus Course'),
  ('United States', 'La Rinconada Country Club'),
  ('United States', 'La Valle Coastal Club East South Course'),
  ('United States', 'La Valle Coastal Club North East Course'),
  ('United States', 'La Valle Coastal Club South North Course'),
  ('United States', 'La Vida Country Club'),
  ('United States', 'La Vista El Cielo At Desert Princess Country Club'),
  ('United States', 'Lac Vieux Desert Golf Course'),
  ('United States', 'Lacoma Golf Course'),
  ('United States', 'Laconia Country Club'),
  ('United States', 'Ladera Golf Club'),
  ('United States', 'Ladera Golf Course Championship Course'),
  ('United States', 'Ladera Golf Course Executive Course'),
  ('United States', 'Lafayette Club'),
  ('United States', 'Lafayette Country Club'),
  ('United States', 'Lafayette Municipal Golf Course'),
  ('United States', 'Lafollette Country Club'),
  ('United States', 'Lafortune Park At Lafortune Park Golf Course'),
  ('United States', 'Lago Mar Country Club'),
  ('United States', 'Lagoon At Ponte Vedra Inn Club'),
  ('United States', 'Lagos Acres Golf & Country Club'),
  ('United States', 'Laguna Lake Golf Course'),
  ('United States', 'Laguna Oaks Golf Course'),
  ('United States', 'Laguna Seca Golf Club'),
  ('United States', 'Laguna Woods Golf Club 1 2 Course'),
  ('United States', 'Laguna Woods Golf Club 1 3 Course'),
  ('United States', 'Laguna Woods Golf Club 2 3 Course'),
  ('United States', 'Laguna Woods Golf Club Par 3 Course'),
  ('United States', 'Lahontan Golf Club'),
  ('United States', 'Lahontan Golf Club The Par 3 Course'),
  ('United States', 'Lake Almanor Country Club'),
  ('United States', 'Lake Almanor West Golf Course'),
  ('United States', 'Lake Arbor Golf Course'),
  ('United States', 'Lake Arrowhead Country Club'),
  ('United States', 'Lake Arrowhead Yacht Country Club Highlands Course'),
  ('United States', 'Lake Arthur Country Club'),
  ('United States', 'Lake Ashton Golf Club The East Course'),
  ('United States', 'Lake Ashton Golf Club The West Course'),
  ('United States', 'Lake At Carolina Trace Country Club'),
  ('United States', 'Lake At Mountain Dell Golf Course'),
  ('United States', 'Lake At Wasatch Mountain State Park'),
  ('United States', 'Lake Barrington Shores Golf Club'),
  ('United States', 'Lake Barton Golf Course'),
  ('United States', 'Lake Bess Country Club'),
  ('United States', 'Lake Bluff Golf Course'),
  ('United States', 'Lake Bonaventure Country Club'),
  ('United States', 'Lake Breeze Golf Club'),
  ('United States', 'Lake Bruin Golf Country Club'),
  ('United States', 'Lake Carlsbad Golf Course Championship Course'),
  ('United States', 'Lake Carlsbad Golf Course Par 3 Course'),
  ('United States', 'Lake Caroline Golf Club'),
  ('United States', 'Lake Carroll Golf Club'),
  ('United States', 'Lake Chabot Golf Course Executive Par 3 Course'),
  ('United States', 'Lake Chabot Golf Course The 18 Hole Course'),
  ('United States', 'Lake Charles Country Club'),
  ('United States', 'Lake Chelan Golf Course'),
  ('United States', 'Lake Chesdin Golf Club'),
  ('United States', 'Lake City Country Club'),
  ('United States', 'Lake City Golf'),
  ('United States', 'Lake Cora Hills'),
  ('United States', 'Lake Cushman Golf Course'),
  ('United States', 'Lake Darbonne Country Club'),
  ('United States', 'Lake Diamond Golf Country Club'),
  ('United States', 'Lake Doster Golf Club'),
  ('United States', 'Lake Erie Metropark Golf Course'),
  ('United States', 'Lake Estes Executive 9 Hole Course'),
  ('United States', 'Lake Fairways Country Club'),
  ('United States', 'Lake Forest Country Club'),
  ('United States', 'Lake Forest Golf Club'),
  ('United States', 'Lake Forest Golf Practice Center'),
  ('United States', 'Lake Gaston Golf Club'),
  ('United States', 'Lake Geneva Country Club'),
  ('United States', 'Lake Hallie Golf'),
  ('United States', 'Lake Havasu Golf Club East Course'),
  ('United States', 'Lake Havasu Golf Club West Course'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Dogwood'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Fox Run'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Sulphur Springs'),
  ('United States', 'Lake Hickory Country Club Town Course'),
  ('United States', 'Lake Hills Golf Club'),
  ('United States', 'Lake Isle Country Club'),
  ('United States', 'Lake James Golf Course'),
  ('United States', 'Lake Jonesco Golf Course'),
  ('United States', 'Lake Jovita Golf Country Club North Course'),
  ('United States', 'Lake Jovita Golf Country Club South Course'),
  ('United States', 'Lake Junaluska Golf Course'),
  ('United States', 'Lake June West Golf Course'),
  ('United States', 'Lake Kezar Country Club'),
  ('United States', 'Lake Kiowa Country Club'),
  ('United States', 'Lake Lackawanna Golf Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Ii Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Iii Course'),
  ('United States', 'Lake Land Village Golf Course Generation Ii Iii Course'),
  ('United States', 'Lake Leann Golf Course'),
  ('United States', 'Lake Limerick Country Club'),
  ('United States', 'Lake Lindero Golf Course'),
  ('United States', 'Lake Lorain Golf Club'),
  ('United States', 'Lake Lure Municipal Golf Course'),
  ('United States', 'Lake MacBride Golf Course'),
  ('United States', 'Lake Marion Golf Course'),
  ('United States', 'Lake Merced Golf Country Club'),
  ('United States', 'Lake Michigan Hills Golf Club'),
  ('United States', 'Lake Mills Golf Course'),
  ('United States', 'Lake Mohawk Golf Club'),
  ('United States', 'Lake Monterey Golf Course'),
  ('United States', 'Lake Monticello Golf Course'),
  ('United States', 'Lake Morey Inn Resort Country Club'),
  ('United States', 'Lake Mountain At Stratton Mountain Country Club'),
  ('United States', 'Lake Murray Golf Center'),
  ('United States', 'Lake Murray State Park Golf Course'),
  ('United States', 'Lake Nona Golf Country Club'),
  ('United States', 'Lake North At Mountain Gate Country Club'),
  ('United States', 'Lake Of The Forest Golf Course'),
  ('United States', 'Lake Of The Pines Country Club'),
  ('United States', 'Lake Of The Woods Country Club'),
  ('United States', 'Lake Oroville Golf Country Club'),
  ('United States', 'Lake Padden Golf Course'),
  ('United States', 'Lake Panorama National Golf Course'),
  ('United States', 'Lake Park Golf Course'),
  ('United States', 'Lake Pepin Golf Course'),
  ('United States', 'Lake Perry Country Club'),
  ('United States', 'Lake Pine Golf Course At Countryside Country Club'),
  ('United States', 'Lake Placid Club Links Course'),
  ('United States', 'Lake Placid Club Mountain Course'),
  ('United States', 'Lake Placid Club Pristine Nine Course'),
  ('United States', 'Lake Platte Golf Club'),
  ('United States', 'Lake Pleasant Golf Club'),
  ('United States', 'Lake Pleasant Golf Course'),
  ('United States', 'Lake Powell National Golf Course'),
  ('United States', 'Lake Providence Country Club'),
  ('United States', 'Lake Quivira Country Club'),
  ('United States', 'Lake Redding Golf Course'),
  ('United States', 'Lake Ridge Park Golf Marina'),
  ('United States', 'Lake Ripley Country Club'),
  ('United States', 'Lake Saint Louis 9-Hole Golf Course'),
  ('United States', 'Lake Shawnee Golf Course'),
  ('United States', 'Lake Shore Country Club'),
  ('United States', 'Lake Shore Course At Lake Shore Country Club'),
  ('United States', 'Lake Shore Golf Club'),
  ('United States', 'Lake Side Golf Course'),
  ('United States', 'Lake Spanaway Golf Course'),
  ('United States', 'Lake Spivey Golf Club'),
  ('United States', 'Lake St Catherine Country Club'),
  ('United States', 'Lake Success Golf Club'),
  ('United States', 'Lake Sunapee Country Club'),
  ('United States', 'Lake Superior View Golf'),
  ('United States', 'Lake Tahoe Golf Course'),
  ('United States', 'Lake Tamarisk Golf Course'),
  ('United States', 'Lake Toxaway Country Club'),
  ('United States', 'Lake Valley At Los Coyotes Country Club'),
  ('United States', 'Lake Valley At Pinery Country Club'),
  ('United States', 'Lake Valley Golf Club'),
  ('United States', 'Lake View At Callaway Gardens Resort'),
  ('United States', 'Lake View Country Club'),
  ('United States', 'Lake View Executive Golf Course'),
  ('United States', 'Lake View National Golf Course'),
  ('United States', 'Lake Village Country Club'),
  ('United States', 'Lake Wales Country Club'),
  ('United States', 'Lake Waramaug Country Club'),
  ('United States', 'Lake Wilderness Golf Course'),
  ('United States', 'Lake Wildwood Golf Course'),
  ('United States', 'Lake Winds Golf Course'),
  ('United States', 'Lake Windsor Country Club'),
  ('United States', 'Lake Winnipesaukee Golf Club'),
  ('United States', 'Lake Wisconsin Country Club'),
  ('United States', 'Lake Wissota Golf & Events'),
  ('United States', 'Lake Woods At Tri Cities Golf Course'),
  ('United States', 'Lake Woods Golf Club'),
  ('United States', 'Lake Worth Beach Golf Club'),
  ('United States', 'Lake Zurich Golf Club'),
  ('United States', 'Lake o'' the Hills Golf Course'),
  ('United States', 'Lake of the Sandhills'),
  ('United States', 'Lake of the Woods Golf Course'),
  ('United States', 'Lakeland Golf Club'),
  ('United States', 'Lakeland Hills Golf Course'),
  ('United States', 'Lakelands Golf and Country Club'),
  ('United States', 'Lakemont At Stone Mountain Golf Course'),
  ('United States', 'Lakeridge Golf Course'),
  ('United States', 'Lakes At Bear Lakes Country Club'),
  ('United States', 'Lakes At Blackhawk Country Club'),
  ('United States', 'Lakes At Boca Woods Country Club'),
  ('United States', 'Lakes At Colonial Springs Golf Course'),
  ('United States', 'Lakes At El Segundo The'),
  ('United States', 'Lakes At Leesburg'),
  ('United States', 'Lakes At North Ridge Country Club'),
  ('United States', 'Lakes At Palm Aire Country Club'),
  ('United States', 'Lakes At Quail West Golf Country Club'),
  ('United States', 'Lakes At Sandridge Golf Club'),
  ('United States', 'Lakes At Windy Hill Golf Course'),
  ('United States', 'Lakes Canyon At Blacklake Golf Course'),
  ('United States', 'Lakes Course At Genoa Lakes Golf Club'),
  ('United States', 'Lakes Cypress At Arrowhead Country Club'),
  ('United States', 'Lakes Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'Lakes Dunes At Gainey Ranch Golf Club'),
  ('United States', 'Lakes Fairways At Centennial Golf Club'),
  ('United States', 'Lakes Golf Course At Laura Walker State Park'),
  ('United States', 'Lakes Golf Course At Oakwood Country Club'),
  ('United States', 'Lakes Meadows At Centennial Golf Club'),
  ('United States', 'Lakes Oaks At Blacklake Golf Course'),
  ('United States', 'Lakes Oaks At Hacienda Hills Golf Country Club'),
  ('United States', 'Lakes Orchard At Treesdale Golf Country Club'),
  ('United States', 'Lakes Pines At Star Hill Golf Country Club'),
  ('United States', 'Lakes River Golf Course Cocoa Beach Country Club'),
  ('United States', 'Lakes Sound Course At Pelican Sound Golf River Club'),
  ('United States', 'Lakes Sunrise At Spanish Trail Country Club'),
  ('United States', 'Lakes Valley At North Ranch Country Club'),
  ('United States', 'Lakes Valley At Valley Oaks Golf Club'),
  ('United States', 'Lakes Waterway At Arrowhead Country Club'),
  ('United States', 'Lakes of Taylor Golf Club'),
  ('United States', 'Lakes of the Four Seasons Golf Course'),
  ('United States', 'Lakeshore Golf Course'),
  ('United States', 'Lakeshore Golf and Country Club'),
  ('United States', 'Lakeshore Yacht Country Club'),
  ('United States', 'Lakeside At Golf Club Of Georgia The'),
  ('United States', 'Lakeside At Juniper Hill Golf Course'),
  ('United States', 'Lakeside Country Club'),
  ('United States', 'Lakeside Golf Club'),
  ('United States', 'Lakeside Golf Course'),
  ('United States', 'Lakeside Links'),
  ('United States', 'Lakeside Memorial Golf Course'),
  ('United States', 'Lakeside Municipal Golf Course'),
  ('United States', 'Lakeside Park Golf Club'),
  ('United States', 'Lakeside Pines At Blue Hill Golf Course'),
  ('United States', 'Lakeside Village Golf Athletic Club'),
  ('United States', 'Lakeview Bayview At A C Read Golf Course'),
  ('United States', 'Lakeview Country Club'),
  ('United States', 'Lakeview Golf And Country Club'),
  ('United States', 'Lakeview Golf Club'),
  ('United States', 'Lakeview Golf Club Eagle Eye Par 3 Course'),
  ('United States', 'Lakeview Golf Club Lake Course'),
  ('United States', 'Lakeview Golf Club Mountain Course'),
  ('United States', 'Lakeview Golf Club Peak Course'),
  ('United States', 'Lakeview Golf Country Club'),
  ('United States', 'Lakeview Golf Course'),
  ('United States', 'Lakeview Golf Resort Lakeview Course'),
  ('United States', 'Lakeview Golf Resort Mountainview Course'),
  ('United States', 'Lakeview Hills Golf Resort - North Course'),
  ('United States', 'Lakeview Hills Golf Resort - South Course'),
  ('United States', 'Lakeview Municipal Golf Course'),
  ('United States', 'Lakeview Par 3 Golf Challenge'),
  ('United States', 'Lakeview Springs Golf'),
  ('United States', 'Lakeville Country Club'),
  ('United States', 'Lakevue North Golf Course'),
  ('United States', 'Lakewood Country Club'),
  ('United States', 'Lakewood Golf Club'),
  ('United States', 'Lakewood Golf Country Club'),
  ('United States', 'Lakewood Golf Course'),
  ('United States', 'Lakewood Links'),
  ('United States', 'Lakewood National Golf Club Commander Course'),
  ('United States', 'Lakewood National Golf Club Piper Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Cypress Links Course'),
  ('United States', 'Lakewood Ranch Golf Country Club King Dunes Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Royal Lakes Course'),
  ('United States', 'Lakewood on the Green'),
  ('United States', 'Lakin Country Club'),
  ('United States', 'Lakota Links Golf Club'),
  ('United States', 'Lamoine Valley Golf Club'),
  ('United States', 'Lamoni Golf and Country Club'),
  ('United States', 'Lamont Hill Resort'),
  ('United States', 'Lampman Golf Club'),
  ('United States', 'Lancaster Country Club'),
  ('United States', 'Lancaster Golf Center'),
  ('United States', 'Lancaster Golf Club'),
  ('United States', 'Lancaster Host Golf Resort'),
  ('United States', 'Lancaster Riverside Golf Club'),
  ('United States', 'Land O Lakes Golf Club'),
  ('United States', 'Lander Golf Country Club'),
  ('United States', 'Landings Golf Club'),
  ('United States', 'Landings Yacht Golf Tennis Club'),
  ('United States', 'Landis Creek Golf Club'),
  ('United States', 'Landsmeer Golf Club'),
  ('United States', 'Lane County Country Club'),
  ('United States', 'Lane Creek Golf Club'),
  ('United States', 'Lane Tree Golf Club'),
  ('United States', 'Langbrook Meadows Golf Country Club'),
  ('United States', 'Langendorf Park Golf Course'),
  ('United States', 'Langley Golf Club'),
  ('United States', 'Langston Golf Course'),
  ('United States', 'Lanier Islands Resort Legacy Golf Course'),
  ('United States', 'Lanier Islands Resort The Six'),
  ('United States', 'Lansbrook Golf Club'),
  ('United States', 'Lansdowne Resort Shark Bite Course'),
  ('United States', 'Lansdowne Resort The Norman Course'),
  ('United States', 'Lansdowne Resort The Robert Trent Jones Ii Course'),
  ('United States', 'Lansing Country Club'),
  ('United States', 'Lapeer Country Club'),
  ('United States', 'Laplaya Beach Golf Resort'),
  ('United States', 'Larchmont Golf Course'),
  ('United States', 'Largo Golf Course'),
  ('United States', 'Larimore Golf Club'),
  ('United States', 'Larned Country Club'),
  ('United States', 'Larry Gannon Municipal Golf Course'),
  ('United States', 'Las Animas Golf Course'),
  ('United States', 'Las Barrancas Golf Course'),
  ('United States', 'Las Campanas Sunrise Course'),
  ('United States', 'Las Campanas Sunset Course'),
  ('United States', 'Las Colinas Golf Club'),
  ('United States', 'Las Posas Country Club'),
  ('United States', 'Las Sendas Golf Club'),
  ('United States', 'Las Vegas Country Club'),
  ('United States', 'Las Vegas Golf Center')
on conflict (country, name) do nothing;
