insert into public.golf_courses (country, name) values
  ('United States', 'Riverside At Greenville Country Club'),
  ('United States', 'Riverside At Juniper Hill Golf Course'),
  ('United States', 'Riverside Country Club'),
  ('United States', 'Riverside Golf & Recreation'),
  ('United States', 'Riverside Golf Academy'),
  ('United States', 'Riverside Golf Center'),
  ('United States', 'Riverside Golf Centre'),
  ('United States', 'Riverside Golf Club'),
  ('United States', 'Riverside Golf Country Club'),
  ('United States', 'Riverside Golf Course'),
  ('United States', 'Riverside Golf Course North Course'),
  ('United States', 'Riverside Golf Course Practice Course'),
  ('United States', 'Riverside Golf Course South Course'),
  ('United States', 'Riverside Greens'),
  ('United States', 'Riverside Municipal Golf Course'),
  ('United States', 'Riverside Of Fresno Golf Course'),
  ('United States', 'Riverside Recreation Golf Course'),
  ('United States', 'Riverton Country Club'),
  ('United States', 'Riverton Golf Club'),
  ('United States', 'Riverton Pointe Golf And Country Club'),
  ('United States', 'Rivertowne Country Club'),
  ('United States', 'Riverview Country Club'),
  ('United States', 'Riverview Golf Club'),
  ('United States', 'Riverview Golf Country Club'),
  ('United States', 'Riverview Golf Course'),
  ('United States', 'Riverview Highlands Golf Course'),
  ('United States', 'Riverview Park Golf Course'),
  ('United States', 'Riverview Rv Resort'),
  ('United States', 'Riverwalk Golf Club'),
  ('United States', 'Riverwalk Golf Club Sunset 9'),
  ('United States', 'Riverwood Golf Club'),
  ('United States', 'Riverwood Golf Club Deer Run Riverview Course'),
  ('United States', 'Riverwood Golf Club Meadowlands Deer Run Course'),
  ('United States', 'Riverwood Golf Club Riverview Meadowlands Course'),
  ('United States', 'Riverwood National'),
  ('United States', 'Riverwood Resort'),
  ('United States', 'Riverwoods'),
  ('United States', 'Riviera Country Club'),
  ('United States', 'Riviera Hills Golf And Country Club'),
  ('United States', 'Roadhaven Golf Course'),
  ('United States', 'Roadrunner Dunes Golf Course'),
  ('United States', 'Roadrunner Golf Country Club'),
  ('United States', 'Roane County Country Club'),
  ('United States', 'Roanoke Country Club'),
  ('United States', 'Roaring Fork Club'),
  ('United States', 'Roaring Gap Golf Club'),
  ('United States', 'Rob Roy Golf Club'),
  ('United States', 'Robbers Row At Port Royal Golf Club'),
  ('United States', 'Robbinhurst Golf Club'),
  ('United States', 'Robersonville Country Club'),
  ('United States', 'Robert A. Black Golf Course'),
  ('United States', 'Robert Cupp At Palmetto Hall Plantation'),
  ('United States', 'Robert Moses Golf Course'),
  ('United States', 'Robert T Lynch Municipal Brookline Golf Course'),
  ('United States', 'Robert Trent Jones Golf Club'),
  ('United States', 'Robert Trent Jones Golf Course Cornell University'),
  ('United States', 'Robertshaw Acres Golf Club'),
  ('United States', 'Robson Ranch Golf Club'),
  ('United States', 'Rochelle Country Club'),
  ('United States', 'Rochelle Ranch Golf Course'),
  ('United States', 'Rochester Country Club'),
  ('United States', 'Rochester Golf & Country Club'),
  ('United States', 'Rochester Golf Club'),
  ('United States', 'Rochester Place Golf Club'),
  ('United States', 'Rock Barn Golf And Spa Jackson Course'),
  ('United States', 'Rock Barn Golf And Spa Jones Course'),
  ('United States', 'Rock Creek Cattle Company'),
  ('United States', 'Rock Creek Country Club'),
  ('United States', 'Rock Creek Golf And Country Club'),
  ('United States', 'Rock Creek Golf Club'),
  ('United States', 'Rock Creek Golf Course'),
  ('United States', 'Rock Creek Park Golf'),
  ('United States', 'Rock Harbor Golf Course Boulder'),
  ('United States', 'Rock Harbor Golf Course Rock'),
  ('United States', 'Rock Hill Country Club'),
  ('United States', 'Rock Hill Golf Country Club'),
  ('United States', 'Rock Hollow Golf Course'),
  ('United States', 'Rock Island Golf Course'),
  ('United States', 'Rock Manor Golf Club'),
  ('United States', 'Rock Port Golf and Country Club'),
  ('United States', 'Rock Ridge Country Club'),
  ('United States', 'Rock Ridge Golf Course'),
  ('United States', 'Rock River Golf Course'),
  ('United States', 'Rock River Hills Golf Course'),
  ('United States', 'Rock Spring Golf Club'),
  ('United States', 'Rock Spring Golf Course'),
  ('United States', 'Rock Valley Golf Club'),
  ('United States', 'Rockaway Hunting Golf Course'),
  ('United States', 'Rockaway River Country Club'),
  ('United States', 'Rockfish Golf Course'),
  ('United States', 'Rockford Country Club'),
  ('United States', 'Rockingham Country Club'),
  ('United States', 'Rockland Country Club'),
  ('United States', 'Rockland Golf Club'),
  ('United States', 'Rockland Golf Course'),
  ('United States', 'Rockledge Country Club'),
  ('United States', 'Rockleigh Golf Course Blue'),
  ('United States', 'Rockleigh Golf Course Red White'),
  ('United States', 'Rockport Golf Club'),
  ('United States', 'Rockrimmon Country Club'),
  ('United States', 'Rockville Links Club'),
  ('United States', 'Rockwind Community Links Championship Course'),
  ('United States', 'Rockwind Community Links Lil Rock Par 3 Course'),
  ('United States', 'Rocky Bayou Country Club'),
  ('United States', 'Rocky Branch Golf Club'),
  ('United States', 'Rocky Creek Golf Club'),
  ('United States', 'Rocky Ford Golf Course'),
  ('United States', 'Rocky Ford Par 3'),
  ('United States', 'Rocky Gap Casino Resort'),
  ('United States', 'Rocky Knoll Country Club'),
  ('United States', 'Rocky Lakes Golf Course'),
  ('United States', 'Rocky Point Golf Course'),
  ('United States', 'Rocky Ridge Golf Club'),
  ('United States', 'Rocky River Golf Club At Concord'),
  ('United States', 'Rocky Run Golf Course'),
  ('United States', 'Rocky Spring Golf Course'),
  ('United States', 'Rogala Public Links'),
  ('United States', 'Rogers City Country Club'),
  ('United States', 'Rogers Gardens Golf Course'),
  ('United States', 'Rogers Park Golf Course'),
  ('United States', 'Rogers Park Golf Course Short Course'),
  ('United States', 'Rohannas Golf Course'),
  ('United States', 'Rolfe Golf Club'),
  ('United States', 'Rolling Acres Golf Club'),
  ('United States', 'Rolling Acres Golf Course'),
  ('United States', 'Rolling Fields Golf Club'),
  ('United States', 'Rolling Green Country Club'),
  ('United States', 'Rolling Green Golf Club'),
  ('United States', 'Rolling Green Golf Course'),
  ('United States', 'Rolling Green Golf Course Country Club'),
  ('United States', 'Rolling Greens Executive Golf Course'),
  ('United States', 'Rolling Greens Golf Club'),
  ('United States', 'Rolling Greens Golf Course'),
  ('United States', 'Rolling Hills'),
  ('United States', 'Rolling Hills Country Club'),
  ('United States', 'Rolling Hills County Park Disc Golf'),
  ('United States', 'Rolling Hills Golf Club'),
  ('United States', 'Rolling Hills Golf Course'),
  ('United States', 'Rolling Knolls Golf Course'),
  ('United States', 'Rolling Meadows'),
  ('United States', 'Rolling Meadows Country Club'),
  ('United States', 'Rolling Meadows Golf Club'),
  ('United States', 'Rolling Meadows Golf Course'),
  ('United States', 'Rolling Oaks Golf Course'),
  ('United States', 'Rolling Pines Golf Course'),
  ('United States', 'Rolling Rock Club'),
  ('United States', 'Rolling S Golf Club'),
  ('United States', 'Rolling Turf Golf Club'),
  ('United States', 'Rollingstone Ranch Golf Club'),
  ('United States', 'Roman Nose Golf Course'),
  ('United States', 'Rome Country Club'),
  ('United States', 'Ron Jaworskis Riverwinds Golf Tennis Club'),
  ('United States', 'Ron Jaworskis Valleybrook Country Club'),
  ('United States', 'Rooling Hills Golf Course'),
  ('United States', 'Roosevelt Course At The Villages Executive Golf Trail'),
  ('United States', 'Roosevelt Golf Course'),
  ('United States', 'Roosevelt Memorial Golf Course'),
  ('United States', 'Roosevelt Municipal Golf Course'),
  ('United States', 'Rooster Run Golf Club'),
  ('United States', 'Root River Country Club'),
  ('United States', 'Root River Golf Club'),
  ('United States', 'Roscoe Mountain Club'),
  ('United States', 'Rose Brook Golf Course'),
  ('United States', 'Rose City Golf Course'),
  ('United States', 'Rose Creek Golf Club'),
  ('United States', 'Rose Creek Golf Course'),
  ('United States', 'Rose Hill Golf Club'),
  ('United States', 'Rose Lake Golf Club'),
  ('United States', 'Rose Park Golf Course'),
  ('United States', 'Rose Ridge Golf Course'),
  ('United States', 'Rosedale Golf Country Club'),
  ('United States', 'Roseland Golf and Curling Club'),
  ('United States', 'Roses Run Country Club'),
  ('United States', 'Rosman-Glendale Farm Golf Course'),
  ('United States', 'Ross Mountain Club'),
  ('United States', 'Rossmoor Golf Club The Creekside Golf Course'),
  ('United States', 'Rossmoor Golf Club The Dollar Ranch Golf Course'),
  ('United States', 'Rossmoor Golf Course'),
  ('United States', 'Roswell Country Club'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Long Meadow'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The Pine Valley Course'),
  ('United States', 'Rotonda Golf Country Club Long Marsh The White Marsh'),
  ('United States', 'Rouge Park Golf Course'),
  ('United States', 'Round Barn Golf Club'),
  ('United States', 'Round Grove Golf and Country Club'),
  ('United States', 'Round Hill Club'),
  ('United States', 'Round Hill Community Golf Club'),
  ('United States', 'Round Hill Golf Country Club'),
  ('United States', 'Round Lake Public Golf Course'),
  ('United States', 'Round Mountain Golf Club'),
  ('United States', 'Round Valley Golf Course'),
  ('United States', 'Route 56 Golf Course'),
  ('United States', 'Rowley Country Club'),
  ('United States', 'Roxboro Country Club'),
  ('United States', 'Roxiticus Golf Club'),
  ('United States', 'Royal City Public Golf Course'),
  ('United States', 'Royal Colwood Golf Club'),
  ('United States', 'Royal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Royal Crest Country Club'),
  ('United States', 'Royal Crest Golf Club'),
  ('United States', 'Royal Fox Country Club'),
  ('United States', 'Royal Fox Golf Club'),
  ('United States', 'Royal Golf Club'),
  ('United States', 'Royal Hawaiian Golf Club'),
  ('United States', 'Royal Hylands Golf Club'),
  ('United States', 'Royal Kaanapali'),
  ('United States', 'Royal Kunia Country Club'),
  ('United States', 'Royal Lakes Golf Country Club'),
  ('United States', 'Royal Manchester Golf Links'),
  ('United States', 'Royal Melbourne'),
  ('United States', 'Royal New Kent Golf Club'),
  ('United States', 'Royal Oak Golf Club'),
  ('United States', 'Royal Oaks Country Club'),
  ('United States', 'Royal Oaks Golf Club'),
  ('United States', 'Royal Palm Country Club'),
  ('United States', 'Royal Palm Yacht Country Club'),
  ('United States', 'Royal Palms Golf Course'),
  ('United States', 'Royal Sabal At Grand Palms Golf Country Club'),
  ('United States', 'Royal Saint Patrick''s Golf Links'),
  ('United States', 'Royal Scot Golf Course'),
  ('United States', 'Royal St Augustine Golf And Country Club'),
  ('United States', 'Royal St Cloud Golf Links Blue Red Course'),
  ('United States', 'Royal St Cloud Golf Links Red White Course'),
  ('United States', 'Royal St Cloud Golf Links White Blue Course'),
  ('United States', 'Royal Vista Golf Club'),
  ('United States', 'Royal Wood Golf Country Club'),
  ('United States', 'Royalwood Golf Club'),
  ('United States', 'Royce Brook Golf Club'),
  ('United States', 'Royce Brook Golf Club East Golf Course'),
  ('United States', 'Roys All Steak Hamburgers Golf Center Pine Acres Golf Course'),
  ('United States', 'Royster Memorial Golf Course'),
  ('United States', 'Ruby Hill Golf Club'),
  ('United States', 'Ruby View Golf Course'),
  ('United States', 'Ruffled Feathers Golf Community'),
  ('United States', 'Rum Creek Golf'),
  ('United States', 'Rum Pointe Golf Course'),
  ('United States', 'Rum River Hills Golf Club'),
  ('United States', 'Rumson Golf Club'),
  ('United States', 'Running Deer Golf Club'),
  ('United States', 'Rupert Country Club'),
  ('United States', 'Rush Creek Golf Club'),
  ('United States', 'Rush Creek Golf Club - Mac 9'),
  ('United States', 'Rush Lake Hills Golf Club'),
  ('United States', 'Russell Memorial Park Golf Course'),
  ('United States', 'Russellville Country Club'),
  ('United States', 'Russian Jack Springs Golf Course'),
  ('United States', 'Rustic Canyon Golf Course'),
  ('United States', 'Rustic Glen Golf Course'),
  ('United States', 'Rustic Golf Country Club'),
  ('United States', 'Rustic Ridge Golf Course'),
  ('United States', 'Ruston Golf Country Club'),
  ('United States', 'Rutgers University Golf Course'),
  ('United States', 'Ruth Lake Country Club'),
  ('United States', 'Ruth Park Golf Couse'),
  ('United States', 'Rutherfordton Golf Club'),
  ('United States', 'Rutland Country Club'),
  ('United States', 'Ryder Brook Golf Course'),
  ('United States', 'Ryder Course At Pga Golf Club'),
  ('United States', 'Ryder Golf Course'),
  ('United States', 'Rye Golf Club'),
  ('United States', 'Ryland Lakes Golf Course'),
  ('United States', 'SPG Green Garden Country Club'),
  ('United States', 'Sabal Course At Heritage Palms Golf Country Club'),
  ('United States', 'Sabal Grand At Grand Palms Golf Country Club'),
  ('United States', 'Sabal Springs Golf Racquet Club'),
  ('United States', 'Sabetha Golf Country Club'),
  ('United States', 'Sable Creek Golf Course'),
  ('United States', 'Sable Oaks Golf Club'),
  ('United States', 'Sabot At Hermitage Country Club'),
  ('United States', 'Sacandaga Golf Club'),
  ('United States', 'Sadaquada Golf Club'),
  ('United States', 'Saddle Cycle Club'),
  ('United States', 'Saddle Ridge'),
  ('United States', 'Saddle Rock Golf Course'),
  ('United States', 'SaddleBrook Golf Club'),
  ('United States', 'Saddleback Golf Club'),
  ('United States', 'Saddleback Ridge Golf Course'),
  ('United States', 'Saddlebrook At The Villages Executive Golf Trail'),
  ('United States', 'Saddlebrook Golf Course'),
  ('United States', 'Saddlebrook Resort Cypress Pine'),
  ('United States', 'Saddlebrook Resort Oak Cypress'),
  ('United States', 'Saddlebrook Resort Pine Oak'),
  ('United States', 'Saddlebrooke Ranch Golf Club'),
  ('United States', 'Saddlebrooke Tucson At Saddlebrooke Country Club'),
  ('United States', 'Safari Golf Club'),
  ('United States', 'Sag Harbor Golf Club'),
  ('United States', 'Sagamore Hampton Golf Club'),
  ('United States', 'Sagamore Resort And Golf Club'),
  ('United States', 'Sagamore Spring Golf Club'),
  ('United States', 'Sage Hills Golf Resort'),
  ('United States', 'Sage Lakes Municipal Golf Course'),
  ('United States', 'Sage Meadows Golf Course'),
  ('United States', 'Sage Run Golf Course'),
  ('United States', 'Sage Valley Golf Club'),
  ('United States', 'Saginaw Country Club'),
  ('United States', 'Saguaro Course At We Ko Pa Golf Club'),
  ('United States', 'Sailfish Point Golf Club'),
  ('United States', 'Sailfish Sands Golf Course Sailfish Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Black Course'),
  ('United States', 'Sailfish Sands Golf Course Sands Reversible Gold Course'),
  ('United States', 'Saint Andrew''s Golf and Country Club'),
  ('United States', 'Saint Andrews Golf Course'),
  ('United States', 'Saint Charles Country Club'),
  ('United States', 'Saint Clair Shores Golf Club'),
  ('United States', 'Saint Croix National Golf & Event Center'),
  ('United States', 'Saint Elmo Golf Club'),
  ('United States', 'Saint Francois Country Club'),
  ('United States', 'Saint Germain Golf Club'),
  ('United States', 'Saint Ignace Golf & Country Club'),
  ('United States', 'Saint Ives'),
  ('United States', 'Saint Joe Valley Golf Course'),
  ('United States', 'Saint John Fisher Golf Course'),
  ('United States', 'Saint John''s Resort Golf Course'),
  ('United States', 'Saint Marys Golf Club'),
  ('United States', 'Sakima Country Club'),
  ('United States', 'Sakonnet Golf Club'),
  ('United States', 'Salem Country Club'),
  ('United States', 'Salem Glen Country Club'),
  ('United States', 'Salem Golf Club'),
  ('United States', 'Salem Golf Course'),
  ('United States', 'Salem Harbour Golf Course'),
  ('United States', 'Salem Hills Golf Club'),
  ('United States', 'Salida Golf Club'),
  ('United States', 'Salina Country Club'),
  ('United States', 'Salina Municipal Golf Course'),
  ('United States', 'Salinas Fairways Golf Course'),
  ('United States', 'Saline County Golf Club'),
  ('United States', 'Salisbury Country Club Buckingham Course'),
  ('United States', 'Salisbury Country Club Huguenot Course'),
  ('United States', 'Salisbury Country Club Monacan Course'),
  ('United States', 'Salish Cliffs Golf Club'),
  ('United States', 'Salmo Golf Club'),
  ('United States', 'Salmon Creek Country Club'),
  ('United States', 'Salmon Falls Golf Club'),
  ('United States', 'Salmon Run Golf Course'),
  ('United States', 'Salmon Valley Golf Course'),
  ('United States', 'Salt Creek Country Club'),
  ('United States', 'Salt Creek Golf Club'),
  ('United States', 'Salt Creek Golf Resort'),
  ('United States', 'Salt Fork State Park Golf Course'),
  ('United States', 'Salt River Golf Course'),
  ('United States', 'Saltleaf Golf Preserve The Leaf'),
  ('United States', 'Saltleaf Golf Preserve The Preserve'),
  ('United States', 'Saltville Golf Course'),
  ('United States', 'Saluda Valley Country Club'),
  ('United States', 'Samoset Resort'),
  ('United States', 'San Carlos Golf Club'),
  ('United States', 'San Clemente Municipal Golf Course'),
  ('United States', 'San Diego Country Club'),
  ('United States', 'San Dimas Canyon Golf Course'),
  ('United States', 'San Francisco Golf Club'),
  ('United States', 'San Gabriel Country Club'),
  ('United States', 'San Ignacio Golf Club'),
  ('United States', 'San Joaquin Country Club'),
  ('United States', 'San Jose Country Club'),
  ('United States', 'San Jose Municipal Golf Course'),
  ('United States', 'San Juan Country Club'),
  ('United States', 'San Juan Golf Country Club'),
  ('United States', 'San Juan Hills Golf Club'),
  ('United States', 'San Juan Oaks Golf Club'),
  ('United States', 'San Luis Obispo Country Club'),
  ('United States', 'San Manuel Golf Club'),
  ('United States', 'San Marcos Golf Resort'),
  ('United States', 'San Pedro Golf Course'),
  ('United States', 'San Ramon Golf Club'),
  ('United States', 'San Tan Course At Sunland Springs Village'),
  ('United States', 'San Tan Highlands'),
  ('United States', 'San Vicente Golf Resort'),
  ('United States', 'Sanborn Golf and Country Club'),
  ('United States', 'Sanctuary At River Strand Golf And Country Club'),
  ('United States', 'Sanctuary Golf Club'),
  ('United States', 'Sanctuary Golf Course'),
  ('United States', 'Sanctuary Lake Golf Course'),
  ('United States', 'Sand Canyon Country Club'),
  ('United States', 'Sand Creek Country Club'),
  ('United States', 'Sand Creek Golf Club'),
  ('United States', 'Sand Creek Golf Course'),
  ('United States', 'Sand Creek Short Course'),
  ('United States', 'Sand Creek Station Golf Club'),
  ('United States', 'Sand Hill Golf Course'),
  ('United States', 'Sand Hollow Golf Resort The Championship Course'),
  ('United States', 'Sand Hollow Golf Resort The Links Course'),
  ('United States', 'Sand Hollow Golf Resort Wee Course'),
  ('United States', 'Sand Point Country Club'),
  ('United States', 'Sand Ridge Golf Club'),
  ('United States', 'Sand Springs Golf Course'),
  ('United States', 'Sand Valley Golf Resort'),
  ('United States', 'Sandalwood Country Club'),
  ('United States', 'Sandhill At The Villages Executive Golf Trail'),
  ('United States', 'Sandhill Crane Golf Club Championship Golf Course'),
  ('United States', 'Sandhill Crane Golf Club The Nest Par 3'),
  ('United States', 'Sandhill Golf Course'),
  ('United States', 'Sandia Golf Club'),
  ('United States', 'Sandpiper At Spring Lake Golf Club'),
  ('United States', 'Sandpiper Bay Golf Country Club Bay Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Piper Nine'),
  ('United States', 'Sandpiper Bay Golf Country Club Sand Nine'),
  ('United States', 'Sandpiper Cove Golf Course'),
  ('United States', 'Sandpiper Golf Course'),
  ('United States', 'Sands Lakes At Star Hill Golf Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Sands Point Golf Club'),
  ('United States', 'Sandstone Area Golf Course'),
  ('United States', 'Sandstone Hollow Golf Club At Turning Stone'),
  ('United States', 'Sandtrap Golf Course'),
  ('United States', 'Sandwich Hollows Golf Club'),
  ('United States', 'Sandy Burr Country Club'),
  ('United States', 'Sandy Creek Golf Course'),
  ('United States', 'Sandy Hollow Golf Course'),
  ('United States', 'Sandy Pebbles Golf Course'),
  ('United States', 'Sandy Pines Golf Course'),
  ('United States', 'Sandy Point Golf Course'),
  ('United States', 'Sandy Pond Par 3 Golf Course'),
  ('United States', 'Sandy Ridge Country Club'),
  ('United States', 'Sandy Ridge Golf Course'),
  ('United States', 'Sandy River Golf Course'),
  ('United States', 'Sandy Row Golf Club'),
  ('United States', 'Sandy Run Country Club'),
  ('United States', 'Sanford Golf Club'),
  ('United States', 'Sanford Golf Course'),
  ('United States', 'Sanibel Island Golf Club'),
  ('United States', 'Sankaty Head Golf Club'),
  ('United States', 'Sanlan Golf Course Alligator Course'),
  ('United States', 'Sanlan Golf Course Bobcat Course'),
  ('United States', 'Sanlan Golf Course Coyote Course'),
  ('United States', 'Santa Ana Country Club'),
  ('United States', 'Santa Anita Golf Course'),
  ('United States', 'Santa Barbara Golf Club'),
  ('United States', 'Santa Fe Country Club'),
  ('United States', 'Santa Lucia River Club The Ballantrae Golf Course'),
  ('United States', 'Santa Maria Country Club'),
  ('United States', 'Santa Maria Golf Club'),
  ('United States', 'Santa Paula Community Golf Course'),
  ('United States', 'Santa Rosa Country Club'),
  ('United States', 'Santa Rosa Golf Beach Club'),
  ('United States', 'Santa Rosa Golf Beach Club The Loop'),
  ('United States', 'Santa Rosa Golf Country Club'),
  ('United States', 'Santa Rosa Golf Course'),
  ('United States', 'Santee Cooper Country Club'),
  ('United States', 'Santee National Golf Club'),
  ('United States', 'Sapelo Hammock Golf Club'),
  ('United States', 'Sapona Ridge Country Club'),
  ('United States', 'Sapphire National Golf Club'),
  ('United States', 'Sapulpa Municipal Golf Course'),
  ('United States', 'Sara Bay Country Club'),
  ('United States', 'Sarah Shank Golf Course'),
  ('United States', 'Saranac Inn Golf Country Club'),
  ('United States', 'Saranac Lake Golf Club'),
  ('United States', 'Sarasota At The Villages Executive Golf Trail'),
  ('United States', 'Sarasota National Golf Club'),
  ('United States', 'Saratoga Country Club'),
  ('United States', 'Saratoga Golf Polo Club'),
  ('United States', 'Saratoga Hot Springs Resort Saratoga Public Golf Course'),
  ('United States', 'Saratoga Lake Golf Club'),
  ('United States', 'Saratoga National Golf Club'),
  ('United States', 'Sarnia Golf and Curling'),
  ('United States', 'Saskatoon Golf Club'),
  ('United States', 'Sassamon Trace Golf Course'),
  ('United States', 'Saticoy Country Club'),
  ('United States', 'Saticoy Regional Golf Course'),
  ('United States', 'Saugahatchee Country Club'),
  ('United States', 'Sauganash'),
  ('United States', 'Saukie Golf Course'),
  ('United States', 'Sault Country Club'),
  ('United States', 'Sault Sainte Marie Country Club'),
  ('United States', 'Saunders Golf Course'),
  ('United States', 'Sauquoit Knolls Golf Club'),
  ('United States', 'Savanna Club Golf Course'),
  ('United States', 'Savannah Country Club'),
  ('United States', 'Savannah Oaks Golf Club'),
  ('United States', 'Sawgrass Country Club East South'),
  ('United States', 'Sawgrass Country Club South West'),
  ('United States', 'Sawgrass Country Club West East'),
  ('United States', 'Sawgrass Gleneagles At Waterford Golf Club'),
  ('United States', 'Sawgrass Turnberry At Waterford Golf Club'),
  ('United States', 'Sawmill Creek Golf Club'),
  ('United States', 'Sawmill Golf Course'),
  ('United States', 'Sawmill Woods Golf Course'),
  ('United States', 'Saxon East At Saxon Golf Course'),
  ('United States', 'Saxon Woods Golf Course'),
  ('United States', 'Sayre National Golf Course'),
  ('United States', 'Scalawags Golf Club'),
  ('United States', 'Scarlet At Paradise Point Golf Course'),
  ('United States', 'Scarlet Oaks Country Club'),
  ('United States', 'Scarsdale Golf Club'),
  ('United States', 'Scenic Farms Golf Course'),
  ('United States', 'Scenic Golf and Country Club'),
  ('United States', 'Scenic Heights Golf Course'),
  ('United States', 'Scenic Hills Country Club'),
  ('United States', 'Scenic Knolls Golf Course'),
  ('United States', 'Scenic Valley Golf Course'),
  ('United States', 'Scenic View Country Club'),
  ('United States', 'Scenic View Golf Course'),
  ('United States', 'Scepter Golf Club Falcon Ibis Course'),
  ('United States', 'Scepter Golf Club Ibis Osprey Course'),
  ('United States', 'Scepter Golf Club Osprey Falcon Course'),
  ('United States', 'Schaffers Mill Club'),
  ('United States', 'Schalamar Creek Golf Club'),
  ('United States', 'Schaumburg Golf Club'),
  ('United States', 'Schenectady Municipal Golf Course'),
  ('United States', 'Scherwood Golf'),
  ('United States', 'Schifferdecker Golf Course'),
  ('United States', 'Schleswig Community Golf Club'),
  ('United States', 'Schneiters Bluff Golf Club'),
  ('United States', 'Schneiters Riverside Golf Course'),
  ('United States', 'Scholl Canyon Golf Tennis Club'),
  ('United States', 'Schroon Lake Municipal Golf Course'),
  ('United States', 'Schuss Mountain Golf Course'),
  ('United States', 'Schuyler Meadows Club'),
  ('United States', 'Schuylkill Country Club'),
  ('United States', 'Scioto Country Club'),
  ('United States', 'Scioto Reserve Country Club'),
  ('United States', 'Scituate Country Club'),
  ('United States', 'Scobey Golf Club'),
  ('United States', 'Scotch Hills Country Club'),
  ('United States', 'Scotch Meadows Country Club'),
  ('United States', 'Scotch Pines Golf Course'),
  ('United States', 'Scotch Valley Country Club'),
  ('United States', 'Scotfield Country Club'),
  ('United States', 'Scothurst Country Club'),
  ('United States', 'Scotland Run Golf Club'),
  ('United States', 'Scotland Yards Golf Club'),
  ('United States', 'Scott City Country Club'),
  ('United States', 'Scott County Park Golf'),
  ('United States', 'Scott Greens Golf Club'),
  ('United States', 'Scott Lake Country Club'),
  ('United States', 'Scott Lake Golf Course'),
  ('United States', 'Scott Park Golf Links'),
  ('United States', 'Scottish Heights Golf Club'),
  ('United States', 'Scottish Links At Lake Shastina Golf Resort'),
  ('United States', 'Scotts Bluff Country Club'),
  ('United States', 'Scotts Corners Golf Course'),
  ('United States', 'Scottsdale National Golf Club'),
  ('United States', 'Scottsdale National Golf Club The Bad Little Nine'),
  ('United States', 'Scottsdale National Golf Club The Other Course'),
  ('United States', 'Scottsdale Shadows Golf Club'),
  ('United States', 'Scottsdale Silverado Golf Club'),
  ('United States', 'Scottsdale Silverado Golf Club Silver Pony Course'),
  ('United States', 'Scranton Canoe Club'),
  ('United States', 'Scranton Municipal Golf Course'),
  ('United States', 'Sea Aire Park Golf Course'),
  ('United States', 'Sea Mountain Golf Course'),
  ('United States', 'Sea N Air Golf Course'),
  ('United States', 'Sea Palms Golf Tennis Resort'),
  ('United States', 'Sea Pines Country Club'),
  ('United States', 'Sea Pines Golf Resort'),
  ('United States', 'Sea Scape Golf Links'),
  ('United States', 'Seabee Golf Club Of Port Hueneme'),
  ('United States', 'Seacliff Country Club'),
  ('United States', 'Seagate Country Club'),
  ('United States', 'Searcy Country Club'),
  ('United States', 'Searsport Pines Golf Course'),
  ('United States', 'Seascape Golf Beach And Tennis'),
  ('United States', 'Seascape Golf Club'),
  ('United States', 'Seaside At Sea Island Golf Club'),
  ('United States', 'Seaside Golf Club'),
  ('United States', 'Seattle Golf Club'),
  ('United States', 'Seaview The Bay Course'),
  ('United States', 'Seaview The Pines Course'),
  ('United States', 'Seawane Club The'),
  ('United States', 'Sebasco Harbor Resort Golf Club'),
  ('United States', 'Sebastian Municipal Golf Course'),
  ('United States', 'Sebastopol Golf Course'),
  ('United States', 'Sebonack Golf Club'),
  ('United States', 'Sebring Golf Club'),
  ('United States', 'Sebring International Golf Resort Green Course'),
  ('United States', 'Sebring International Golf Resort Red Course'),
  ('United States', 'Sebring International Golf Resort The 12'),
  ('United States', 'Sebring International Golf Resort Yellow Course'),
  ('United States', 'Sebring Lakeside Golf Resort'),
  ('United States', 'Secession Golf Club'),
  ('United States', 'Second Nine At Edison Club The'),
  ('United States', 'Second Nine At Montclair Golf Club'),
  ('United States', 'Second Nine Third Nine At Bermuda Dunes Country Club'),
  ('United States', 'Second Nine Third Nine At Cloverleaf Golf Club'),
  ('United States', 'Second Third At Lake Venice Golf Club'),
  ('United States', 'Sedan Country Club'),
  ('United States', 'Sedgefield Country Club Ross Course'),
  ('United States', 'Sedgewick County Golf Club'),
  ('United States', 'Sedgewood Country Club'),
  ('United States', 'Sedona Golf Resort'),
  ('United States', 'Segregansett Country Club'),
  ('United States', 'Seidel Golf Course'),
  ('United States', 'Seiling Golf Course'),
  ('United States', 'Selfridge ANGB Golf Course'),
  ('United States', 'Selma Valley Golf Course'),
  ('United States', 'Selmer Golf Country Club'),
  ('United States', 'Semiahmoo Golf Country Club'),
  ('United States', 'Seminole At Canongate On White Oak'),
  ('United States', 'Seminole Choctaw At Indian Hills Country Club'),
  ('United States', 'Seminole Golf Club'),
  ('United States', 'Seminole Lake Country Club'),
  ('United States', 'Seminole Lakes Country Club'),
  ('United States', 'Seminole Legacy Golf Club'),
  ('United States', 'Seneca Falls Country Club'),
  ('United States', 'Seneca Golf Club'),
  ('United States', 'Seneca Golf Course'),
  ('United States', 'Seneca Hickory Stick Golf Course'),
  ('United States', 'Seneca Lake Country Club'),
  ('United States', 'Senica''s Oak Ridge Golf Club'),
  ('United States', 'Sensei Porcupine Creek Golf Club'),
  ('United States', 'Sentry World Golf Center'),
  ('United States', 'Sequoia Woods Country Club'),
  ('United States', 'Sequoyah Country Club'),
  ('United States', 'Sequoyah National Golf Club'),
  ('United States', 'Sequoyah State Park Golf Course'),
  ('United States', 'Serendipity Golf Course'),
  ('United States', 'Serenity Hill Golf Course'),
  ('United States', 'Serenoa Golf Club'),
  ('United States', 'Sergeant Jasper Golf Club'),
  ('United States', 'Serket'),
  ('United States', 'Serrano Country Club'),
  ('United States', 'Settler''s Hill Golf Course'),
  ('United States', 'Settlers Bay'),
  ('United States', 'Settlers Crossing Golf Course'),
  ('United States', 'Seven Bridges Golf Club'),
  ('United States', 'Seven Hills Golf Club'),
  ('United States', 'Seven Hills Golfers Club'),
  ('United States', 'Seven Lakes'),
  ('United States', 'Seven Lakes Country Club'),
  ('United States', 'Seven Lakes Golf Course'),
  ('United States', 'Seven Oaks Country Club'),
  ('United States', 'Seven Oaks Country Club Islands Oaks Course'),
  ('United States', 'Seven Oaks Country Club Lakes Islands Course'),
  ('United States', 'Seven Oaks Country Club Oaks Lakes Course'),
  ('United States', 'Seven Oaks Golf Club'),
  ('United States', 'Seville Golf Country Club'),
  ('United States', 'Sewailo Golf Club'),
  ('United States', 'Sewells Point Golf Course'),
  ('United States', 'Sewickley Heights Golf Club'),
  ('United States', 'Seymour Golf Course'),
  ('United States', 'Shackamaxon Golf Country Club'),
  ('United States', 'Shade Mountain Golf Club'),
  ('United States', 'Shadow Creek Golf Course'),
  ('United States', 'Shadow Glen The Golf Club'),
  ('United States', 'Shadow Hills Golf Club'),
  ('United States', 'Shadow Hills Golf Club North Par 3 Course'),
  ('United States', 'Shadow Lake Village Golf Course'),
  ('United States', 'Shadow Lakes Club'),
  ('United States', 'Shadow Mountain Golf Course'),
  ('United States', 'Shadow Ridge Country Club'),
  ('United States', 'Shadow Ridge Golf Club'),
  ('United States', 'Shadow Valley Country Club'),
  ('United States', 'Shadow Valley Golf Course'),
  ('United States', 'Shadow Wood Preserve'),
  ('United States', 'Shadowbrook Inn Resort'),
  ('United States', 'Shadowbrooke Golf Course'),
  ('United States', 'Shadowmoss Plantation Golf Club'),
  ('United States', 'Shadowood Golf Course'),
  ('United States', 'Shadowridge Golf Club'),
  ('United States', 'Shady Bend Golf Course'),
  ('United States', 'Shady Canyon Golf Club'),
  ('United States', 'Shady Grove Golf Course'),
  ('United States', 'Shady Hills Golf Course'),
  ('United States', 'Shady Hollow Country Club'),
  ('United States', 'Shady Oaks Golf Course'),
  ('United States', 'Shaffer''s Evergreen Golf Course'),
  ('United States', 'Shaftesbury Glen Golf Fish Club'),
  ('United States', 'Shagbark Golf & Country Club'),
  ('United States', 'Shaker Farms Country Club'),
  ('United States', 'Shaker Heights Country Club'),
  ('United States', 'Shaker Hills Country Club'),
  ('United States', 'Shaker Ridge Country Club'),
  ('United States', 'Shaker Run Golf Club'),
  ('United States', 'Shalimar Golf Club'),
  ('United States', 'Shalimar Pointe Golf Club'),
  ('United States', 'Shallow Creek Golf Club'),
  ('United States', 'Shambolee Golf Course'),
  ('United States', 'Shamrock Golf Club'),
  ('United States', 'Shamrock Golf Country Club'),
  ('United States', 'Shamrock Golf Course'),
  ('United States', 'Shamrock Hills Golf Club'),
  ('United States', 'Shamrock Public Golf Course'),
  ('United States', 'Shandin Hills Golf Club'),
  ('United States', 'Shangri La Country Club Champions Course'),
  ('United States', 'Shangri La Country Club Heritage Course'),
  ('United States', 'Shangri La Country Club Legends Course'),
  ('United States', 'Shangri La Resort The Battlefield Par 3'),
  ('United States', 'Shannon Greens Golf Club'),
  ('United States', 'Shannopin Country Club'),
  ('United States', 'Shark River Golf Course'),
  ('United States', 'Sharkey Country Club'),
  ('United States', 'Sharks Tooth Golf Club'),
  ('United States', 'Sharon Country Club'),
  ('United States', 'Sharon Country Club Pitch Putt Course'),
  ('United States', 'Sharon Heights Golf Country Club'),
  ('United States', 'Sharon Springs Golf Course'),
  ('United States', 'Sharon Woods Golf Course'),
  ('United States', 'Sharp Park Golf Course'),
  ('United States', 'Shasta Valley Golf Club'),
  ('United States', 'Shattuck Golf Country Club'),
  ('United States', 'Shattuck The'),
  ('United States', 'Shawano Lake Golf Course'),
  ('United States', 'Shawnee Country Club'),
  ('United States', 'Shawnee Golf Country Club'),
  ('United States', 'Shawnee Golf Country Club Chapel Creek Course'),
  ('United States', 'Shawnee Golf Country Club Clear Creek Course'),
  ('United States', 'Shawnee Golf Country Club Heartland Hills Course'),
  ('United States', 'Shawnee Golf Course'),
  ('United States', 'Shawnee Hills Country Club'),
  ('United States', 'Shawnee Hills Golf Course'),
  ('United States', 'Shawnee Inn Golf Resort Tillinghast Chip N Putt'),
  ('United States', 'Sheaffer Memorial Golf Park'),
  ('United States', 'Sheepscot Links Golf Course'),
  ('United States', 'Shelby Country Club'),
  ('United States', 'Shelby Oaks Golf Club'),
  ('United States', 'Shelbyville Country Club'),
  ('United States', 'Sheldon Golf and Country Club'),
  ('United States', 'Shell Bay Club'),
  ('United States', 'Shell Landing Golf Club'),
  ('United States', 'Shell Point Golf Club'),
  ('United States', 'Shelridge Country Club'),
  ('United States', 'Shelter Bay Golf Course'),
  ('United States', 'Shelter Cove Golf Course'),
  ('United States', 'Shelter Harbor Golf Club Championship Course'),
  ('United States', 'Shelter Harbor Golf Club Par 3 Course'),
  ('United States', 'Shelter Island Country Club'),
  ('United States', 'Shenandoah Country Club'),
  ('United States', 'Shenango Lake Golf Club'),
  ('United States', 'Shenendoah Golf Club At Turning Stone'),
  ('United States', 'Shennecossett Golf Club'),
  ('United States', 'Shenvalee Golf Resort Creek Miller'),
  ('United States', 'Shenvalee Golf Resort Miller Olde'),
  ('United States', 'Shenvalee Golf Resort Olde Creek'),
  ('United States', 'Shephard Hills Golf Course'),
  ('United States', 'Shepherd Hills Golf Club'),
  ('United States', 'Shepherd''s Crook Golf Course'),
  ('United States', 'Shepherd''s Hollow'),
  ('United States', 'Shepherds Meadow Golf Course'),
  ('United States', 'Sherbrooke Golf Country Club'),
  ('United States', 'Sheridan Golf Country Club'),
  ('United States', 'Sheridan Park Golf Course'),
  ('United States', 'Sherman Hills Golf Club'),
  ('United States', 'Sherwood Country Club'),
  ('United States', 'Sherwood Forest Golf Club'),
  ('United States', 'Sherwood Golf Club'),
  ('United States', 'Sherwood Hills Golf Course'),
  ('United States', 'Sherwood Lakes Club'),
  ('United States', 'Sherwood on the Hill Golf Course'),
  ('United States', 'Shield Crest Golf Course'),
  ('United States', 'Shiloh Golf Course'),
  ('United States', 'Shiloh Park Golf Course'),
  ('United States', 'Shiloh Ridge Athletic Club'),
  ('United States', 'Shiloh Springs Golf Club'),
  ('United States', 'Shingle Creek Golf Club'),
  ('United States', 'Shining Mountain Golf Club'),
  ('United States', 'Shining Rock Golf Club'),
  ('United States', 'Shinnecock Hills Golf Course'),
  ('United States', 'Shoaff Park Golf Course'),
  ('United States', 'Shoop Park'),
  ('United States', 'Shooting Star Of Jackson Hole'),
  ('United States', 'Shore Acres Course At Lake Shore Country Club'),
  ('United States', 'Shore At Monterey Peninsula Country Club'),
  ('United States', 'Shore Gate Golf Club'),
  ('United States', 'Shoreacres'),
  ('United States', 'Shorecliffs Golf Club'),
  ('United States', 'Shorehaven Golf Club'),
  ('United States', 'Shoreland Country Club'),
  ('United States', 'Shoreline Golf Links At Mountain View'),
  ('United States', 'Shorewood Country Club'),
  ('United States', 'Short At Cordillera Golf Course'),
  ('United States', 'Short At Highland Oaks Golf Course'),
  ('United States', 'Short At Saucon Valley Country Club'),
  ('United States', 'Short Beach Golf Course'),
  ('United States', 'Short Course'),
  ('United States', 'Short Hills Country Club'),
  ('United States', 'Short Nine At Villages Golf Country Club'),
  ('United States', 'Shoshone Golf Tennis Club'),
  ('United States', 'Shuksan Golf Club'),
  ('United States', 'Shuttle Meadow Country Club'),
  ('United States', 'Siasconset Golf Course'),
  ('United States', 'Sibley Golf and Country Club'),
  ('United States', 'Sidewinder At Gold Canyon Golf Resort'),
  ('United States', 'Sidney Country Club'),
  ('United States', 'Sidney Golf Course'),
  ('United States', 'Siena Golf Course'),
  ('United States', 'Sierra Comstock At Empire Ranch Golf Course'),
  ('United States', 'Sierra Hills Golf Club'),
  ('United States', 'Sierra Lakes Golf Club'),
  ('United States', 'Sierra River At Empire Ranch Golf Course'),
  ('United States', 'Sierra Sage Golf Course'),
  ('United States', 'Sierra Star Golf Club'),
  ('United States', 'Sierra View Country Club'),
  ('United States', 'Sierra Vista Golf Center At Pueblo Del Sol'),
  ('United States', 'Sigel Golf Course'),
  ('United States', 'Signal Hill Golf Course'),
  ('United States', 'Signal Point Club'),
  ('United States', 'Signal Point Country Club'),
  ('United States', 'Signal Point Golf Club'),
  ('United States', 'Signature Of Solon'),
  ('United States', 'Sigourney Golf Club'),
  ('United States', 'Siler City Country Club'),
  ('United States', 'Silo Point Country Club'),
  ('United States', 'Silo Ridge Field Club'),
  ('United States', 'Silo Run Golf Course'),
  ('United States', 'Silo Sleeping Indian At West Woods Golf Club'),
  ('United States', 'Siloam Springs Country Club'),
  ('United States', 'Silos Golf Course'),
  ('United States', 'Silver At Eisenhower Golf Course'),
  ('United States', 'Silver At Treasure Lake Golf Course'),
  ('United States', 'Silver Bay Golf Course')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'Silver Blue At Foxfire Country Club'),
  ('United States', 'Silver Creek Golf Club'),
  ('United States', 'Silver Creek Golf Course'),
  ('United States', 'Silver Creek Plantation'),
  ('United States', 'Silver Creek Valley Country Club'),
  ('United States', 'Silver Dollar Golf Trap Club Bobcat Gator Course'),
  ('United States', 'Silver Dollar Golf Trap Club Gator Panther Course'),
  ('United States', 'Silver Dollar Golf Trap Club Panther Bobcat Course'),
  ('United States', 'Silver Fox Golf Course'),
  ('United States', 'Silver King Golf Club'),
  ('United States', 'Silver Lake At The Villages Executive Golf Trail'),
  ('United States', 'Silver Lake Country Club'),
  ('United States', 'Silver Lake Golf Course'),
  ('United States', 'Silver Lakes Rv Resort Golf Club'),
  ('United States', 'Silver Oak Golf Course'),
  ('United States', 'Silver Oaks Golf Club'),
  ('United States', 'Silver Ridge'),
  ('United States', 'Silver Sage Golf Course'),
  ('United States', 'Silver Spring Country Club'),
  ('United States', 'Silver Spring Golf Club'),
  ('United States', 'Silver Spring Golf Course'),
  ('United States', 'Silver Springs Country Club'),
  ('United States', 'Silver Springs Golf Club'),
  ('United States', 'Silverado Golf Country Club'),
  ('United States', 'Silverado Resort Spa North Course'),
  ('United States', 'Silverado Resort Spa South Course'),
  ('United States', 'Silverbell Municipal Golf Course'),
  ('United States', 'Silvercrest Golf Club'),
  ('United States', 'Silvermine Golf Club Pro Shop 9 Course'),
  ('United States', 'Silvermine Golf Club Woods 9 Barn 9 Course'),
  ('United States', 'Silverrock Resort'),
  ('United States', 'Silverthorn Country Club'),
  ('United States', 'Sim Park Golf Course'),
  ('United States', 'Simi Hills Golf Course'),
  ('United States', 'Simpson Country Club'),
  ('United States', 'Simsbury Farms Golf Club'),
  ('United States', 'Sinaloa Golf Course'),
  ('United States', 'Sinclair Golf Club'),
  ('United States', 'Singing Bridge Golf Course'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Oak Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Pine Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Willow Glen'),
  ('United States', 'Sinking Valley Country Club'),
  ('United States', 'Sinnissippi Golf Course'),
  ('United States', 'Sioux City Country Club'),
  ('United States', 'Sioux Valley Golf Course'),
  ('United States', 'Siren National Golf Club'),
  ('United States', 'Sistersville Country Club Golf Course'),
  ('United States', 'Sitzmark Lodge'),
  ('United States', 'Siwanoy Country Club'),
  ('United States', 'Six Lakes Country Club'),
  ('United States', 'Skagit Golf Country Club'),
  ('United States', 'Skamania Lodge The Gorge 9'),
  ('United States', 'Skaneateles Country Club'),
  ('United States', 'Skenandoa Club Of Clinton'),
  ('United States', 'Skene Valley Country Club'),
  ('United States', 'Skippack Golf Course'),
  ('United States', 'Skokie Country Club'),
  ('United States', 'Skungamaug River Golf Club'),
  ('United States', 'Sky Meadow Country Club'),
  ('United States', 'Sky Mountain Golf Course'),
  ('United States', 'Sky Ranch Golf Course'),
  ('United States', 'Sky Valley Country Club'),
  ('United States', 'Skybrook Golf Club'),
  ('United States', 'Skyland Lakes Golf Course Resort'),
  ('United States', 'Skyline Country Club'),
  ('United States', 'Skyline Golf Course'),
  ('United States', 'Skyline Mountain Resort And Golf Course'),
  ('United States', 'Skyline Public Golf Course'),
  ('United States', 'Skyline Ranch Country Club'),
  ('United States', 'Skylinks At Buchanan Fields'),
  ('United States', 'Skylinks Golf Course'),
  ('United States', 'Skyridge Golf Course'),
  ('United States', 'Skytop Lodge Poconos Golf Course'),
  ('United States', 'Skytop Mountain Golf Club'),
  ('United States', 'Skyview At Terra Vista'),
  ('United States', 'Skyview Golf Club'),
  ('United States', 'Skyway Golf Course'),
  ('United States', 'Skyway Golf Course At Lincoln Park West'),
  ('United States', 'Skyway Golf Park'),
  ('United States', 'Slammer And Squire Golf Course At World Golf Village'),
  ('United States', 'Slayton Country Club'),
  ('United States', 'Sleeping Giant Golf Course'),
  ('United States', 'Sleeping Indian Cottonwood At West Woods Golf Club'),
  ('United States', 'Sleepy Eye Golf Club'),
  ('United States', 'Sleepy Hole Golf Course'),
  ('United States', 'Sleepy Hollow Country Club'),
  ('United States', 'Sleepy Hollow Country Club Lower Course'),
  ('United States', 'Sleepy Hollow Country Club Upper Course'),
  ('United States', 'Sleepy Hollow Golf Club'),
  ('United States', 'Sleepy Hollow Golf Country Club'),
  ('United States', 'Sleepy Hollow Golf Course'),
  ('United States', 'Sleepy Hollow Sports Park'),
  ('United States', 'Sliding Rock Golf Course'),
  ('United States', 'Sligo Creek Golf Course'),
  ('United States', 'Slippery Elm Golf Course'),
  ('United States', 'Slippery Rock Golf Club Events Center'),
  ('United States', 'Sloan Golf Course'),
  ('United States', 'Sly Fox Golf Club'),
  ('United States', 'Smethport Country Club'),
  ('United States', 'Smileys Executive Golf Club'),
  ('United States', 'Smith Center Municipal Golf Course'),
  ('United States', 'Smithfield Golf Club'),
  ('United States', 'Smithfields Country Club'),
  ('United States', 'Smock Golf Course'),
  ('United States', 'Smoke Rise Country Club'),
  ('United States', 'Smoky Hill Country Club'),
  ('United States', 'Smoky Mountain Country Club'),
  ('United States', 'Smoky River Golf Course'),
  ('United States', 'Smugglers Glen Golf Course'),
  ('United States', 'Snake River Golf Course'),
  ('United States', 'Snee Farm Country Club'),
  ('United States', 'Snohomish Public Golf Course'),
  ('United States', 'Snoqualmie Falls Golf Course'),
  ('United States', 'Snow Hill Country Club'),
  ('United States', 'Snow Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Snow Snake Golf Course'),
  ('United States', 'Snowcreek Golf Course'),
  ('United States', 'Snowflake Municipal Golf Course 18 Hole Course'),
  ('United States', 'Snowflake Municipal Golf Course 9 Hole Course'),
  ('United States', 'Snowflake Ski Club'),
  ('United States', 'Snowmass Club'),
  ('United States', 'Snyder Park Golf Course'),
  ('United States', 'Soaring Eagles Golf Course'),
  ('United States', 'Social Nine At Maddens On Gull Lake'),
  ('United States', 'Sodus Bay Heights Golf Club'),
  ('United States', 'Soldier Hill Golf Course'),
  ('United States', 'Soldier Hollow Golf Course The Gold Course'),
  ('United States', 'Soldier Hollow Golf Course The Silver Course'),
  ('United States', 'Soldiers Creek Golf Club'),
  ('United States', 'Soldiers Field Golf Course'),
  ('United States', 'Soleta Golf Golf Club'),
  ('United States', 'Soleta Golf Golf Club The Colt'),
  ('United States', 'Solina Golf Club'),
  ('United States', 'Solitude Links Golf Course & Banquet Center'),
  ('United States', 'Somerby Golf Club'),
  ('United States', 'Somers National Golf Club'),
  ('United States', 'Somerset Country Club'),
  ('United States', 'Somerset Farms Golf Course'),
  ('United States', 'Somerset Golf Course'),
  ('United States', 'Somerset Hills Country Club'),
  ('United States', 'Somersett Country Club Canyon Nine'),
  ('United States', 'Somersett Country Club Championship'),
  ('United States', 'Songbird Hills Golf Club'),
  ('United States', 'Sonnenalp Resort Of Vail'),
  ('United States', 'Sonnys Par 3 And Driving Range'),
  ('United States', 'Sonoma Golf Club'),
  ('United States', 'Sonoma Ranch Golf Course'),
  ('United States', 'Sonora Dunes Golf Course'),
  ('United States', 'Sonoran Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Sonoran Golf Course At Oakwood Country Club'),
  ('United States', 'Sonyea Golf Course'),
  ('United States', 'Sorrento Par 3 Golf Course'),
  ('United States', 'Souhegan Woods Golf Club'),
  ('United States', 'Soule Park Golf Club'),
  ('United States', 'Sound Of Freedom Golf Course'),
  ('United States', 'Sound River Course At Pelican Sound Golf River Club'),
  ('United States', 'South At Admiral Baker Golf Course'),
  ('United States', 'South At Antelope Hills Golf Course'),
  ('United States', 'South At Bay Palms Golf Complex'),
  ('United States', 'South At Boulders Golf Club Resort'),
  ('United States', 'South At Bretwood Golf Course'),
  ('United States', 'South At Canoe Brook Country Club'),
  ('United States', 'South At Carmel Country Club'),
  ('United States', 'South At Cherokee Town Country Club'),
  ('United States', 'South At Cherokee Village'),
  ('United States', 'South At Churchville Park Golf Course'),
  ('United States', 'South At Coto De Caza Golf Racquet Club'),
  ('United States', 'South At Country Club Of Scranton The'),
  ('United States', 'South At Crestview Country Club'),
  ('United States', 'South At Daytona Beach Golf Country Club'),
  ('United States', 'South At Deerfield Country Club'),
  ('United States', 'South At Earlywine Golf Course'),
  ('United States', 'South At Fountains Country Club'),
  ('United States', 'South At Frenchmans Creek Beach Country Club'),
  ('United States', 'South At Hunters Run Golf Course'),
  ('United States', 'South At Ironwood Country Club'),
  ('United States', 'South At Johns Island Club'),
  ('United States', 'South At Lake Hefner Golf Course'),
  ('United States', 'South At Los Angeles Country Club The'),
  ('United States', 'South At Los Serranos Golf Country Club'),
  ('United States', 'South At Moss Creek Golf Club'),
  ('United States', 'South At Quail Ridge Country Club'),
  ('United States', 'South At Raintree Country Club'),
  ('United States', 'South At Rancho Murieta Country Club'),
  ('United States', 'South At Torrey Pines Municipal Golf Course'),
  ('United States', 'South At Victor Hills Golf Club'),
  ('United States', 'South At Vineyards Of Naples The'),
  ('United States', 'South At Westchester Country Club'),
  ('United States', 'South At Wilmington Country Club'),
  ('United States', 'South Bend Country Club'),
  ('United States', 'South Bluff Country Club'),
  ('United States', 'South Course'),
  ('United States', 'South Course At Big Cypress Golf Country Club'),
  ('United States', 'South Course At Highlands Ridge'),
  ('United States', 'South Course At Lake Of Isles'),
  ('United States', 'South Course At Shadow Wood Country Club'),
  ('United States', 'South Course At Terry Hills Golf Course'),
  ('United States', 'South Course At Whitefish Lake Golf Club'),
  ('United States', 'South East At Farmington Country Club'),
  ('United States', 'South East At Killearn Country Club Inn'),
  ('United States', 'South East At Newaukum Valley Golf Course'),
  ('United States', 'South East At Spanish Wells Country Club'),
  ('United States', 'South Fork Country Club'),
  ('United States', 'South Forty Golf Course Driving Range'),
  ('United States', 'South Gate Municipal Golf Course'),
  ('United States', 'South Gleason Park Course'),
  ('United States', 'South Golf Course At Granite Falls Golf Club'),
  ('United States', 'South Granville Country Club'),
  ('United States', 'South Grove Golf Course'),
  ('United States', 'South Harbour Golf Links'),
  ('United States', 'South Hardin Recreation Area'),
  ('United States', 'South Hill Country Club'),
  ('United States', 'South Hills Country Club'),
  ('United States', 'South Hills Golf & Country Club'),
  ('United States', 'South Hills Golf Club'),
  ('United States', 'South Hills Golf Course'),
  ('United States', 'South Lake At Mountain Gate Country Club'),
  ('United States', 'South Lakes Golf Course'),
  ('United States', 'South Mountain Golf Club'),
  ('United States', 'South Mountain Golf Course'),
  ('United States', 'South Nine At Cross Creek Resort'),
  ('United States', 'South North At Athens Country Club'),
  ('United States', 'South North At Cedar Knoll Country Club'),
  ('United States', 'South North At Farmington Country Club'),
  ('United States', 'South North At Fernandina Beach Golf Club'),
  ('United States', 'South North At Lakes Country Club The'),
  ('United States', 'South North At Oaks North Golf Course'),
  ('United States', 'South North At Ocean Breeze Golf Country Club'),
  ('United States', 'South North At Sahalee Country Club'),
  ('United States', 'South North At Spanish Wells Country Club'),
  ('United States', 'South Par 3 At Alondra Park Golf Course'),
  ('United States', 'South Park Golf Course'),
  ('United States', 'South Portland Municipal Golf Course'),
  ('United States', 'South Ridge Golf Course'),
  ('United States', 'South Riding Golf Club'),
  ('United States', 'South Shore Country Club'),
  ('United States', 'South Shore Golf Club'),
  ('United States', 'South Shore Golf Course'),
  ('United States', 'South Shore Village Golf Club'),
  ('United States', 'South Side Country Club'),
  ('United States', 'South Side Links'),
  ('United States', 'South Toledo Golf Club'),
  ('United States', 'South Wales Golf Club'),
  ('United States', 'South West At Elmridge Golf Club'),
  ('United States', 'South West At Krendale Golf Course'),
  ('United States', 'South West At Monterey Country Club'),
  ('United States', 'South West At Newaukum Valley Golf Course'),
  ('United States', 'South West At Rolling Acres Golf Course'),
  ('United States', 'South Winn Golf & Country Club'),
  ('United States', 'Southampton Country Club'),
  ('United States', 'Southampton Golf Club'),
  ('United States', 'Southaven Golf Center'),
  ('United States', 'Southborough Golf Club'),
  ('United States', 'Southbridge Savannah Golf Club'),
  ('United States', 'Southern Delaware Golf Club'),
  ('United States', 'Southern Dunes Golf Country Club'),
  ('United States', 'Southern Dunes Golf Course'),
  ('United States', 'Southern Dutchess Country Club'),
  ('United States', 'Southern Fairways Golf Course'),
  ('United States', 'Southern Gate Golf Course'),
  ('United States', 'Southern Highlands Golf Course'),
  ('United States', 'Southern Hills Golf Club'),
  ('United States', 'Southern Hills Golf Course'),
  ('United States', 'Southern Hills Plantation'),
  ('United States', 'Southern Meadows Par Four'),
  ('United States', 'Southern Oaks Country Club'),
  ('United States', 'Southern Oaks Golf Club'),
  ('United States', 'Southern Oaks Golf Course'),
  ('United States', 'Southern Pines Golf Club'),
  ('United States', 'Southern Ridge Golf Club'),
  ('United States', 'Southern Star At The Villages Executive Golf Trail'),
  ('United States', 'Southern Tee Golf Course'),
  ('United States', 'Southern Trace Country Club'),
  ('United States', 'Southern Wayne Country Club'),
  ('United States', 'Southers Marsh Golf Club'),
  ('United States', 'Southgate Golf Club'),
  ('United States', 'Southglenn Country Club'),
  ('United States', 'Southington Country Club'),
  ('United States', 'Southland Golf Country Club'),
  ('United States', 'Southmoor Golf Course (former)'),
  ('United States', 'Southmoore Golf Course'),
  ('United States', 'Southpointe Golf Club'),
  ('United States', 'Southport Springs Golf Country Club'),
  ('United States', 'Southridge Golf Club'),
  ('United States', 'Southshore Golf Club'),
  ('United States', 'Southshore Golf Learning Center'),
  ('United States', 'Southview Country Club'),
  ('United States', 'Southward Ho Country Club'),
  ('United States', 'Southwick Country Club'),
  ('United States', 'Southwinds Golf Course'),
  ('United States', 'Southwood Golf Club'),
  ('United States', 'Spanish Hills Golf Country Club'),
  ('United States', 'Spanish Lakes Country Club'),
  ('United States', 'Spanish Lakes Fairways'),
  ('United States', 'Spanish Lakes Golf Course'),
  ('United States', 'Spanish Lakes Golf Village'),
  ('United States', 'Spanish Peaks Mountain Club Toms 10 Golf Course'),
  ('United States', 'Spanish Trail Golf Club'),
  ('United States', 'Spanish Wells Club'),
  ('United States', 'Sparta Country Club'),
  ('United States', 'Sparta Moose Lodge Golf Course'),
  ('United States', 'Spearfish Canyon Country Club'),
  ('United States', 'Speedway Putting Course At Sea Island Golf Club'),
  ('United States', 'Speers Public Golf Course'),
  ('United States', 'Speidel Jones Golf Course'),
  ('United States', 'Speidel Palmer Golf Course'),
  ('United States', 'Spencer Golf and Country Club'),
  ('United States', 'Spencer T. Olin Community Golf Course'),
  ('United States', 'Spessard Holland Golf Course'),
  ('United States', 'Spider Lake Golf Resort'),
  ('United States', 'Spirit Hollow Golf Course'),
  ('United States', 'Split Rock At Pelham Split Rock Golf Course'),
  ('United States', 'Split Rock Golf Club'),
  ('United States', 'Split Rock Golf Club North Course'),
  ('United States', 'Split Rock Golf Club South Course'),
  ('United States', 'Spook Rock Golf Course'),
  ('United States', 'Spooky Brook Golf Course'),
  ('United States', 'Spooner Golf Club'),
  ('United States', 'Sportsmans Golf Course'),
  ('United States', 'Spotswood Country Club'),
  ('United States', 'Sprain Lake Golf Course'),
  ('United States', 'Spreading Antlers Golf Course'),
  ('United States', 'Spring Bayou Golf Country Club'),
  ('United States', 'Spring Brook Country Club'),
  ('United States', 'Spring Brook Golf Course'),
  ('United States', 'Spring Creek Golf Club'),
  ('United States', 'Spring Creek Golf Course'),
  ('United States', 'Spring Creek Golf Course Country Club'),
  ('United States', 'Spring Ford Country Club'),
  ('United States', 'Spring Green Municipal Golf Course'),
  ('United States', 'Spring Hill Country Club'),
  ('United States', 'Spring Hill Golf Club'),
  ('United States', 'Spring Hill Golf Course'),
  ('United States', 'Spring Hills Country Club'),
  ('United States', 'Spring Hills Golf Club'),
  ('United States', 'Spring Hills Golf Course'),
  ('United States', 'Spring Hollow Golf Course'),
  ('United States', 'Spring Lake Country Club'),
  ('United States', 'Spring Lake Golf & Country Club'),
  ('United States', 'Spring Lake Golf Club'),
  ('United States', 'Spring Lake Golf Course'),
  ('United States', 'Spring Lake Golf Resort Bobcat Run Executive Course'),
  ('United States', 'Spring Lakes Golf Club'),
  ('United States', 'Spring Meadow Golf Club'),
  ('United States', 'Spring Meadows Country Club'),
  ('United States', 'Spring Meadows Golf Club'),
  ('United States', 'Spring Mill At Philadelphia Country Club'),
  ('United States', 'Spring Mill Country Club'),
  ('United States', 'Spring Run Golf Club'),
  ('United States', 'Spring Valley Country Club'),
  ('United States', 'Spring Valley Golf Club'),
  ('United States', 'Spring Valley Golf Course'),
  ('United States', 'Springbrook Country Club'),
  ('United States', 'Springbrook Golf Club'),
  ('United States', 'Springbrook Golf Course'),
  ('United States', 'Springbrook Greens Golf Course'),
  ('United States', 'Springdale Country Club'),
  ('United States', 'Springdale Golf Club'),
  ('United States', 'Springdale Park and Golf Course'),
  ('United States', 'Springdale Resort'),
  ('United States', 'Springfield Country Club'),
  ('United States', 'Springfield Golf Center'),
  ('United States', 'Springfield Golf Club'),
  ('United States', 'Springfield Golf Country Club'),
  ('United States', 'Springfield Golf Course'),
  ('United States', 'Springfield Golf Resort'),
  ('United States', 'Springfield Oaks Golf Course'),
  ('United States', 'Springhaven Club'),
  ('United States', 'Springhill Country Club'),
  ('United States', 'Springhill Golf Course'),
  ('United States', 'Springside Par 3 Golf Course'),
  ('United States', 'Springvale Golf Course'),
  ('United States', 'Springville Country Club'),
  ('United States', 'Spruce Creek Country Club'),
  ('United States', 'Spruce Dogwood At Middle Island Country Club'),
  ('United States', 'Spruce Ridge Golf Club'),
  ('United States', 'Spruce Ridge Golf Course'),
  ('United States', 'Spruce Run Golf Course'),
  ('United States', 'Spud Run Golf'),
  ('United States', 'Spy Ring Golf Club'),
  ('United States', 'Spyglass Hilltm Golf Course'),
  ('United States', 'Squaw Creek Golf Course'),
  ('United States', 'Squaw Mountain Village Golf Course'),
  ('United States', 'Squire Creek Country Club'),
  ('United States', 'Squires Golf Club'),
  ('United States', 'Squirrel Run Country Club'),
  ('United States', 'St Alban''s Golf Course'),
  ('United States', 'St Andrews At Westcliffe'),
  ('United States', 'St Andrews By The Lake Golf Club'),
  ('United States', 'St Andrews Club'),
  ('United States', 'St Andrews Country Club Arnold Palmer Course'),
  ('United States', 'St Andrews Country Club Fazio Ii Course'),
  ('United States', 'St Andrews Golf Club'),
  ('United States', 'St Andrews Golf Club The'),
  ('United States', 'St Andrews South Golf Club'),
  ('United States', 'St Anne Country Club'),
  ('United States', 'St Augustine Shores Golf Club'),
  ('United States', 'St Bonaventure Golf Club'),
  ('United States', 'St Croix Country Club')
on conflict (country, name) do nothing;
insert into public.golf_courses (country, name) values
  ('United States', 'St Davids Golf Club'),
  ('United States', 'St George Country Club'),
  ('United States', 'St George Golf Club'),
  ('United States', 'St Georges Golf Country Club'),
  ('United States', 'St Helens Golf Course'),
  ('United States', 'St Ives Country Club'),
  ('United States', 'St James Bay Golf Club'),
  ('United States', 'St John Golf Country Club'),
  ('United States', 'St Johns Golf Club'),
  ('United States', 'St Johns Golf Country Club'),
  ('United States', 'St Johnsbury Country Club'),
  ('United States', 'St Joseph Bay Golf Club'),
  ('United States', 'St Joseph Country Club'),
  ('United States', 'St Lawrence State Park Golf Course'),
  ('United States', 'St Lawrence University Golf Country Club'),
  ('United States', 'St Lucie Trail Golf Club'),
  ('United States', 'St Malo Golf Cabins'),
  ('United States', 'St Maries Golf Course'),
  ('United States', 'St Marlo Country Club'),
  ('United States', 'St Martins Golf Course At Philadelphia Cricket Club'),
  ('United States', 'St Mary Golf Country Club'),
  ('United States', 'St Marys Public Golf Course'),
  ('United States', 'St Mellion Golf Club Nicklaus Course'),
  ('United States', 'St Petersburg Country Club'),
  ('United States', 'St Stanislaus Golf Course'),
  ('United States', 'St Stephen Golf Club'),
  ('United States', 'St. Anne''s Golf Course'),
  ('United States', 'St. Bernard Golf Club'),
  ('United States', 'St. Charles Disc Golf Course'),
  ('United States', 'St. Charles Golf Club'),
  ('United States', 'St. Clair Country Club'),
  ('United States', 'St. Clair Golf Club'),
  ('United States', 'St. Clair Parkway Golf Course'),
  ('United States', 'St. Cloud Country Club'),
  ('United States', 'St. Croix Valley Golf Course'),
  ('United States', 'St. Denis Golf Course'),
  ('United States', 'St. Germain Golf 9 Hole'),
  ('United States', 'St. Louis Country Club'),
  ('United States', 'St. Mike''s Golf Course'),
  ('United States', 'St. Peters Golf Course'),
  ('United States', 'St. Urho'),
  ('United States', 'Stadium Golf Club'),
  ('United States', 'Stafford Country Club'),
  ('United States', 'Stafford County Country Club'),
  ('United States', 'Stagg Hill Golf Club'),
  ('United States', 'Stahlstown Par 3 Golf Course'),
  ('United States', 'Stallion Mountain Golf Club'),
  ('United States', 'Stamford Golf Course'),
  ('United States', 'Stamford Valley Golf Course'),
  ('United States', 'Standard Club The'),
  ('United States', 'Standard Country Club'),
  ('United States', 'Stanford Golf Club'),
  ('United States', 'Stanley Golf Course Blue White'),
  ('United States', 'Stanley Golf Course Red Blue'),
  ('United States', 'Stanley Golf Course White Red'),
  ('United States', 'Stansbury Park Golf Course'),
  ('United States', 'Stanton County Prairie Pines'),
  ('United States', 'Stanton Ridge Golf Country Club'),
  ('United States', 'Stanwich Club'),
  ('United States', 'Star Valley Rv Golf Course'),
  ('United States', 'Star Valley View Golf Course'),
  ('United States', 'Stardust Golf Course At Sun City West'),
  ('United States', 'Starfire Golf Club The King Course'),
  ('United States', 'Starfire Golf Club The Mulligan 9'),
  ('United States', 'Starke Country Club'),
  ('United States', 'Starkville Country Club'),
  ('United States', 'Starmount Forest Country Club'),
  ('United States', 'Starx Golf Course'),
  ('United States', 'States Golf Club'),
  ('United States', 'Statesville Country Club'),
  ('United States', 'Steamboat Golf Club'),
  ('United States', 'Steel Canyon Golf Club'),
  ('United States', 'Steel Club Championship Course'),
  ('United States', 'Steel Club Hill Nine'),
  ('United States', 'Steel Creek Golf Course'),
  ('United States', 'Steele Canyon Golf Club Canyon Ranch'),
  ('United States', 'Steele Canyon Golf Club Canyon Vineyard'),
  ('United States', 'Steele Canyon Golf Club Ranch Vineyard'),
  ('United States', 'Steele Hill Resort Golf Course'),
  ('United States', 'Steeple Chase Golf Club'),
  ('United States', 'Stengers Shamrock Farms Par 3 Golf Course'),
  ('United States', 'Stephen Golf Course'),
  ('United States', 'Sterling Country Club'),
  ('United States', 'Sterling Farms Golf Course'),
  ('United States', 'Sterling Grove Golf Country Club'),
  ('United States', 'Sterling Hills Golf Club'),
  ('United States', 'Sterling National Country Club'),
  ('United States', 'Sterling Park Golf Club'),
  ('United States', 'Steubenville Country Club'),
  ('United States', 'Steve Hogan Golf Course'),
  ('United States', 'Stevens Point Country Club'),
  ('United States', 'Stewartville Golf Club'),
  ('United States', 'Stillmeadow Country Club'),
  ('United States', 'Stillwater Country Club'),
  ('United States', 'Stillwater Golf And Country Club'),
  ('United States', 'Stillwater Golf Course'),
  ('United States', 'Stillwater Oaks Golf Course'),
  ('United States', 'Stillwater Valley Golf Club'),
  ('United States', 'Stirrup Cup Course At Glenview Champions Country Club'),
  ('United States', 'Stoatin Brae Golf Club'),
  ('United States', 'Stock Farm'),
  ('United States', 'Stockbridge Golf Club'),
  ('United States', 'Stockdale Country Club'),
  ('United States', 'Stockton Golf Country Club'),
  ('United States', 'Stoeckeler Memorial Park Golf Course'),
  ('United States', 'Stone Canyon Club'),
  ('United States', 'Stone Creek At Page Belcher Golf Course'),
  ('United States', 'Stone Creek Cove Golf Course'),
  ('United States', 'Stone Creek Golf Club'),
  ('United States', 'Stone Creek Golf Course'),
  ('United States', 'Stone Crossing Golf Club'),
  ('United States', 'Stone Dock Golf Club'),
  ('United States', 'Stone E Lea Golf Course'),
  ('United States', 'Stone Eagle Golf Club'),
  ('United States', 'Stone Harbor Golf Club'),
  ('United States', 'Stone Hedge Country Club'),
  ('United States', 'Stone Meadow Golf'),
  ('United States', 'Stone Meadows Golf Course'),
  ('United States', 'Stone Mountain Golf Club'),
  ('United States', 'Stone Oak Country Club'),
  ('United States', 'Stone Ridge Golf Club'),
  ('United States', 'Stone Tree Golf Club'),
  ('United States', 'StoneRidge Golf Club'),
  ('United States', 'Stonebridge Country Club'),
  ('United States', 'Stonebridge Golf Club'),
  ('United States', 'Stonebridge Golf Club Creekside Sunrise Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Championship Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Harvey 9 Course'),
  ('United States', 'Stonebridge Golf Club Sagebrush Creekside Course'),
  ('United States', 'Stonebridge Golf Club Sunrise Sagebrush Course'),
  ('United States', 'Stonebridge Golf Country Club'),
  ('United States', 'Stonebridge Golf Links Country Club'),
  ('United States', 'Stonebridge Meadows Golf Club'),
  ('United States', 'Stonebrook Golf Course'),
  ('United States', 'Stonebrooke Golf Course'),
  ('United States', 'Stonecreek Golf Club'),
  ('United States', 'Stonecrest'),
  ('United States', 'Stonecrest Golf Club'),
  ('United States', 'Stonecrest Golf Club Meadows Course'),
  ('United States', 'Stonecrest Golf Course'),
  ('United States', 'Stonegate Golf Club'),
  ('United States', 'Stonegate Golf Course'),
  ('United States', 'Stoneham Oaks Golf Course'),
  ('United States', 'Stonehedge Golf Course'),
  ('United States', 'Stonehedge North'),
  ('United States', 'Stonehedge South'),
  ('United States', 'Stonehedges Golf Club'),
  ('United States', 'Stonehenge Golf Club'),
  ('United States', 'Stonehenge Golf Country Club'),
  ('United States', 'Stonehenge Golf Course'),
  ('United States', 'Stonehouse Creek At Temecula Creek Inn Golf Resort'),
  ('United States', 'Stonehouse Golf Club'),
  ('United States', 'Stoneleigh Golf Club'),
  ('United States', 'Stonemont At Stone Mountain Golf Course'),
  ('United States', 'Stoneridge Golf Course'),
  ('United States', 'Stones Throw Golf Course'),
  ('United States', 'Stonewall Golf Club At Lake Manassas'),
  ('United States', 'Stonewall Golf Course'),
  ('United States', 'Stonewall Orchard Golf Club'),
  ('United States', 'Stonewater Country Club'),
  ('United States', 'Stonewater Golf Club'),
  ('United States', 'Stonewolf Golf Club'),
  ('United States', 'Stoney Creek Golf Club'),
  ('United States', 'Stoney Creek Golf Course'),
  ('United States', 'Stoney Links'),
  ('United States', 'Stoney Links Golf Course (closed)'),
  ('United States', 'Stoney Ridge Golf Course'),
  ('United States', 'Stoneybrook East Golf Course'),
  ('United States', 'Stoneybrook Golf Club'),
  ('United States', 'Stoneybrook Golf Country Club'),
  ('United States', 'Stoneybrook West Golf Course'),
  ('United States', 'Stonington Country Club'),
  ('United States', 'Stony Creek Golf Course'),
  ('United States', 'Stony Creek Metropark Golf Course'),
  ('United States', 'Stony Ford Golf Course'),
  ('United States', 'Stony Point Golf Course'),
  ('United States', 'Stonybrook Golf Club'),
  ('United States', 'Stonybrook Golf Course'),
  ('United States', 'Stonycreek Golf Club'),
  ('United States', 'Stonycroft Hills Club'),
  ('United States', 'Stop N Sock Golf Course'),
  ('United States', 'Storm King Golf Club'),
  ('United States', 'Storm Lake Golf Course'),
  ('United States', 'Stoughton Acres Golf Course'),
  ('United States', 'Stoughton Country Club'),
  ('United States', 'Stow North At Stow Acres Country Club'),
  ('United States', 'Stow South At Stow Acres Country Club'),
  ('United States', 'Stowaway Golf Course'),
  ('United States', 'Stowe Country Club'),
  ('United States', 'Stoweflake Mountain Resort Spa'),
  ('United States', 'Straight River Golf Course'),
  ('United States', 'Stratford Country Club'),
  ('United States', 'Stratton Golf Club'),
  ('United States', 'Strawberry Farms Golf Club'),
  ('United States', 'Strawberry Ridge Golf Course'),
  ('United States', 'Strawberry Valley Golf Club'),
  ('United States', 'Streamside Golf Course'),
  ('United States', 'Streamside Golf Course And Country Club'),
  ('United States', 'Streamsong Resort Black Course'),
  ('United States', 'Streamsong Resort Blue Course'),
  ('United States', 'Streamsong Resort Red Course'),
  ('United States', 'Streamsong Resort The Chain'),
  ('United States', 'Streamsong Resort The Gauntlet Putting Course'),
  ('United States', 'Streamwood Oaks Golf Club'),
  ('United States', 'Stripe Show Golf Club'),
  ('United States', 'Stroud Municipal Golf Course'),
  ('United States', 'Stryker Golf Course'),
  ('United States', 'Studebaker Park'),
  ('United States', 'Studio59 Golf - Libertyville Golf Course'),
  ('United States', 'Stumpy Lake Golf Course'),
  ('United States', 'Stuttgart Country Club'),
  ('United States', 'Suburban Golf Club'),
  ('United States', 'Sudden Valley Golf Country Club'),
  ('United States', 'Suffield Country Club'),
  ('United States', 'Suffield Springs Golf Club'),
  ('United States', 'Suffolk Golf Course'),
  ('United States', 'Sugar Bush Golf Course'),
  ('United States', 'Sugar Creek Country Club'),
  ('United States', 'Sugar Creek Golf Course'),
  ('United States', 'Sugar Creek Golf Tennis Club'),
  ('United States', 'Sugar Hill Golf Club'),
  ('United States', 'Sugar Hill Golf Course'),
  ('United States', 'Sugar Hills Golf Club'),
  ('United States', 'Sugar Mountain Golf Club'),
  ('United States', 'Sugar Oaks Golf Country Club'),
  ('United States', 'Sugar Ridge Golf Club'),
  ('United States', 'Sugar River Greens'),
  ('United States', 'Sugar Springs Golf Club'),
  ('United States', 'Sugar Valley Lakes Homes Association'),
  ('United States', 'Sugarbrooke Golf Course'),
  ('United States', 'Sugarbush Golf Club'),
  ('United States', 'Sugarbush Golf Course'),
  ('United States', 'Sugarland Country Club'),
  ('United States', 'Sugarloaf Golf Club'),
  ('United States', 'Sugarloaf Golf Club Resort'),
  ('United States', 'Sugarmill Woods Country Club Cypress Course'),
  ('United States', 'Sugarmill Woods Country Club Oak Course'),
  ('United States', 'Sugarmill Woods Country Club Pine Course'),
  ('United States', 'Sullivan County Golf Country Club'),
  ('United States', 'Sullivan Elks Country Club'),
  ('United States', 'Sullivans Par 3'),
  ('United States', 'Sulphur Hills Golf Course'),
  ('United States', 'Sultan’s Run Golf Club'),
  ('United States', 'Summer Breeze Par Three Golf Course'),
  ('United States', 'Summerfield Crossings Golf Club'),
  ('United States', 'Summerglen Golf Club'),
  ('United States', 'Summergrove Golf Club'),
  ('United States', 'Summerheights Golf Links South Course'),
  ('United States', 'Summerheights Golf Links West Course'),
  ('United States', 'Summertree Golf Club'),
  ('United States', 'Summertree Golf Course'),
  ('United States', 'Summerville Country Club'),
  ('United States', 'Summit At Cordillera Summit Course'),
  ('United States', 'Summit Chase Country Club'),
  ('United States', 'Summit Country Club'),
  ('United States', 'Summit Golf Course'),
  ('United States', 'Summit Hills Country Club'),
  ('United States', 'Summit Hills Golf Club'),
  ('United States', 'Summit Municipal Golf Course'),
  ('United States', 'Summit Springs Golf Course'),
  ('United States', 'Sumo Golf Village'),
  ('United States', 'Sumpwams Creek At E Donald Conroy Golf Course'),
  ('United States', 'Sumter Country Club'),
  ('United States', 'Sun City Country Club'),
  ('United States', 'Sun City Lakes Golf Club East Course'),
  ('United States', 'Sun City Lakes Golf Club West Course'),
  ('United States', 'Sun City South Golf Course'),
  ('United States', 'Sun Country Golf Resort'),
  ('United States', 'Sun Hills Golf Course'),
  ('United States', 'Sun Lakes Country Club'),
  ('United States', 'Sun Lakes Country Club Executive Course'),
  ('United States', 'Sun Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Sun River Golf Club'),
  ('United States', 'Sun Valley Golf Course'),
  ('United States', 'Sun Village Golf Course'),
  ('United States', 'Sun Willows Golf Course'),
  ('United States', 'Sunbird Golf Resort'),
  ('United States', 'Sunbrook Golf Club Black Rock The Point Course'),
  ('United States', 'Sunbrook Golf Club The Point Woodbridge Course'),
  ('United States', 'Sunbrook Golf Club Woodbridge Black Rock Course'),
  ('United States', 'Suncadia Resort Prospector Course'),
  ('United States', 'Suncadia Resort Rope Rider Course'),
  ('United States', 'Suncoast Golf Center'),
  ('United States', 'Suncrest Country Club'),
  ('United States', 'Suncrest Golf Course'),
  ('United States', 'Sundale Country Club'),
  ('United States', 'Sundance'),
  ('United States', 'Sundance Golf Banquet Bowl'),
  ('United States', 'Sundance Golf Club'),
  ('United States', 'Sundance Golf Course'),
  ('United States', 'Sunday River Golf Club'),
  ('United States', 'Sundown Golf Country Club'),
  ('United States', 'Suneagles Golf Club'),
  ('United States', 'Sunflower Hills Golf Course'),
  ('United States', 'Sunken Gardens Golf Course'),
  ('United States', 'Sunkist Country Club'),
  ('United States', 'Sunland Golf Country Club'),
  ('United States', 'Sunland Village East Golf Course'),
  ('United States', 'Sunland Village Golf Course'),
  ('United States', 'Sunnehanna Country Club'),
  ('United States', 'Sunnidell Golf Course'),
  ('United States', 'Sunningdale Country Club'),
  ('United States', 'Sunny Brae Golf & Country Club'),
  ('United States', 'Sunny Hill Golf Course'),
  ('United States', 'Sunny Hill Resort Golf Course'),
  ('United States', 'Sunny Hills Golf Club'),
  ('United States', 'Sunnybrook Country Club'),
  ('United States', 'Sunnybrook Golf Club'),
  ('United States', 'Sunnycrest Golf Course'),
  ('United States', 'Sunnylands Golf Course'),
  ('United States', 'Sunnyside Country Club'),
  ('United States', 'Sunnyside Golf Country Club'),
  ('United States', 'Sunnyside Par 3 Golf Course'),
  ('United States', 'Sunnyvale Municipal Golf Course'),
  ('United States', 'Sunridge Canyon Golf Club'),
  ('United States', 'Sunridge Golf Club'),
  ('United States', 'Sunrise Canyon At Spanish Trail Country Club'),
  ('United States', 'Sunrise Country Club'),
  ('United States', 'Sunrise Course At Country Club At Mirasol'),
  ('United States', 'Sunrise Golf Course'),
  ('United States', 'Sunrise Lakes Phase 3 Golf Course'),
  ('United States', 'Sunrise Lakes Phase Iv Golf Course'),
  ('United States', 'Sunrise Ridge Golf Course'),
  ('United States', 'Sunrise Vista Golf Course'),
  ('United States', 'Sunserra Golf At Crescent Bar'),
  ('United States', 'Sunset At Lancaster Country Club'),
  ('United States', 'Sunset Country Club'),
  ('United States', 'Sunset Course At Country Club At Mirasol'),
  ('United States', 'Sunset Golf Course'),
  ('United States', 'Sunset Grove Country Club'),
  ('United States', 'Sunset Hill Golf Club'),
  ('United States', 'Sunset Hill Golf Course'),
  ('United States', 'Sunset Hills Country Club'),
  ('United States', 'Sunset Hills Golf Club'),
  ('United States', 'Sunset Hills Golf Course'),
  ('United States', 'Sunset Hills Golf Course Old Course'),
  ('United States', 'Sunset Hills Golf Course Par 3 Course'),
  ('United States', 'Sunset Par 3'),
  ('United States', 'Sunset Ridge Country Club'),
  ('United States', 'Sunset Ridge Golf Club'),
  ('United States', 'Sunset Ridge Golf Links'),
  ('United States', 'Sunset Ridge Golf Links Par 3 Course'),
  ('United States', 'Sunset Valley Country Club'),
  ('United States', 'Sunset Valley Golf Course'),
  ('United States', 'Sunset View Golf Course'),
  ('United States', 'Sunshine Woods Golf Club'),
  ('United States', 'Suntides Golf Course'),
  ('United States', 'Superior Country Club'),
  ('United States', 'Superior National at Lutsen-Golf Course'),
  ('United States', 'Superstition Course At Sunland Springs Village'),
  ('United States', 'Superstition Mountain Golf Country Club Lost Gold Course'),
  ('United States', 'Superstition Mountain Golf Country Club Prospector Course'),
  ('United States', 'Superstition Springs Golf Club'),
  ('United States', 'Suppesville Golf Course'),
  ('United States', 'Surf Golf Beach Club'),
  ('United States', 'Surfside Golf Course'),
  ('United States', 'Surrey Hills Country Club'),
  ('United States', 'Susquehanna Valley Country Club'),
  ('United States', 'Sutton Bay Golf'),
  ('United States', 'Sutton Creek Golf Course'),
  ('United States', 'Suwannee Country Club'),
  ('United States', 'Swainsboro Golf Club'),
  ('United States', 'Swallows Nest Country Club'),
  ('United States', 'Swamp Fox Golf Club'),
  ('United States', 'Swan Hills Golf Course'),
  ('United States', 'Swan Lake Country Club'),
  ('United States', 'Swan Lake Golf Club'),
  ('United States', 'Swan Lake Golf Country Club'),
  ('United States', 'Swan Lake Golf Courses'),
  ('United States', 'Swan Lakes Golf Course'),
  ('United States', 'Swan Point Yacht Country Club'),
  ('United States', 'Swan Valley Golf Course'),
  ('United States', 'Swanhills'),
  ('United States', 'Swannanoa Country Club'),
  ('United States', 'Swansea Clinton Hills Conservation Park'),
  ('United States', 'Swansea Country Club'),
  ('United States', 'Swansea Country Club Par 3 Course'),
  ('United States', 'Swanson Meadows Golf Course'),
  ('United States', 'Swartz Creek Golf Course'),
  ('United States', 'Sweet Water Golf Course'),
  ('United States', 'Sweetbriar Golf & Pro Shop'),
  ('United States', 'Sweetens Cove Golf Club'),
  ('United States', 'Sweetgrass Golf Club'),
  ('United States', 'Sweetgum At The Villages Executive Golf Trail'),
  ('United States', 'Sweetwater Country Club'),
  ('United States', 'Sweetwater Golf Country Club'),
  ('United States', 'Sweetwater Golf Tennis Club'),
  ('United States', 'Swenson Park Golf Course Magnolia Executive Par 3'),
  ('United States', 'Swenson Park Golf Course The Oak Course'),
  ('United States', 'Swinomish Golf Links'),
  ('United States', 'Swiss Fairways Golf Course'),
  ('United States', 'Switzerland of Ohio Golf Course'),
  ('United States', 'Swope Memorial Golf Course'),
  ('United States', 'Sycamore Country Club'),
  ('United States', 'Sycamore Creek County Club'),
  ('United States', 'Sycamore Creek Golf Course'),
  ('United States', 'Sycamore Golf Club'),
  ('United States', 'Sycamore Hills Country Club'),
  ('United States', 'Sycamore Hills Golf Club'),
  ('United States', 'Sycamore Ridge')
on conflict (country, name) do nothing;
