insert into public.golf_courses (country, name) values
  ('United States', 'Pine View Golf Course'),
  ('United States', 'Pine View Highlands'),
  ('United States', 'Pine Woods Golf Course'),
  ('United States', 'Pinebrook Ironwood Golf Course'),
  ('United States', 'Pinecone Thistle At Resort At The Mountain The'),
  ('United States', 'Pinecrest Country Club'),
  ('United States', 'Pinecrest Golf Club'),
  ('United States', 'Pinecrest Golf Course'),
  ('United States', 'Pinecrest Lake Golf Club'),
  ('United States', 'Pinecroft Golf Course'),
  ('United States', 'Pinehaven Country Club'),
  ('United States', 'Pinehills At Myrtlewood Golf Club'),
  ('United States', 'Pinehills Golf Club Jones Course'),
  ('United States', 'Pinehills Golf Club Nicklaus Course'),
  ('United States', 'Pinehurst Golf Club'),
  ('United States', 'Pinehurst Golf Course'),
  ('United States', 'Pinehurst Resort Country Club No 1'),
  ('United States', 'Pinehurst Resort Country Club No 10'),
  ('United States', 'Pinehurst Resort Country Club No 2'),
  ('United States', 'Pinehurst Resort Country Club No 3'),
  ('United States', 'Pinehurst Resort Country Club No 4'),
  ('United States', 'Pinehurst Resort Country Club No 5'),
  ('United States', 'Pinehurst Resort Country Club No 6'),
  ('United States', 'Pinehurst Resort Country Club No 7'),
  ('United States', 'Pinehurst Resort Country Club No 8'),
  ('United States', 'Pinehurst Resort Country Club No 9'),
  ('United States', 'Pinehurst Resort Country Club The Cradle'),
  ('United States', 'Pinehurst Resort Country Club Thistle Dhu Putting Course'),
  ('United States', 'Pineknoll Golf Club'),
  ('United States', 'Pinelands Golf Club'),
  ('United States', 'Pinemoor West Golf Club'),
  ('United States', 'Pineridge Golf Course'),
  ('United States', 'Pines At Clermont'),
  ('United States', 'Pines At Colonial Springs Golf Course'),
  ('United States', 'Pines At Diamondhead Country Club'),
  ('United States', 'Pines At Ft Walton Beach Golf Club'),
  ('United States', 'Pines At Glades Country Club'),
  ('United States', 'Pines At Pompano Beach Golf Course'),
  ('United States', 'Pines At Royal Poinciana Golf Club'),
  ('United States', 'Pines At Willowcreek Golf Club'),
  ('United States', 'Pines At Woodmont Country Club'),
  ('United States', 'Pines Course'),
  ('United States', 'Pines Golf Club'),
  ('United States', 'Pines Golf Club The'),
  ('United States', 'Pines Golf Course'),
  ('United States', 'Pines Lake At Tri Cities Golf Course'),
  ('United States', 'Pines Sands At Star Hill Golf Country Club'),
  ('United States', 'Pines Woodland At Blue Hill Golf Course'),
  ('United States', 'Pinetop Country Club'),
  ('United States', 'Pinetop Lakes Golf Country Club'),
  ('United States', 'Pinetree Country Club'),
  ('United States', 'Pinetuck Golf Course'),
  ('United States', 'Pineview Country Club'),
  ('United States', 'Pinewood Country Club'),
  ('United States', 'Pinewood Golf Club'),
  ('United States', 'Pinewood Golf Course'),
  ('United States', 'Piney Apple Golf Course'),
  ('United States', 'Piney Point Golf Club'),
  ('United States', 'Pinnacle At Troon North Golf Club'),
  ('United States', 'Pinnacle Country Club'),
  ('United States', 'Pinnacle Country Club and Golf Course'),
  ('United States', 'Pinnacle Golf Club'),
  ('United States', 'Pinnacle Hills Golf Course'),
  ('United States', 'Pinnacle Peak Country Club'),
  ('United States', 'Pinnacle State Park Golf Club'),
  ('United States', 'Pinon At Towa Golf Resort'),
  ('United States', 'Pinon Hills Golf Course'),
  ('United States', 'Pinon Ponderosa At Pagosa Springs Golf Club'),
  ('United States', 'Pioneer Creek'),
  ('United States', 'Pioneer Family Golf Center'),
  ('United States', 'Pioneer Hills Golf Course'),
  ('United States', 'Pioneer Pointe'),
  ('United States', 'Pioneer Town & Country Club'),
  ('United States', 'Piper Glen Golf Course'),
  ('United States', 'Piper Hills Golf Course'),
  ('United States', 'Pipers Landing Country Club'),
  ('United States', 'Pipestone Creek Golf Course'),
  ('United States', 'Pipestone Golf & Country Club'),
  ('United States', 'Piping Rock Club'),
  ('United States', 'Piscataquis Country Club'),
  ('United States', 'Pismo State Beach Golf Course'),
  ('United States', 'Pistakee Golf Course'),
  ('United States', 'Pitch And Putt At Evergreen Golf Course Inc'),
  ('United States', 'Pitch Putt At Pine Hills Country Club'),
  ('United States', 'Pitch Putt At Scallys Golf Center'),
  ('United States', 'Pitman Golf Course'),
  ('United States', 'Pittsboro Golf Club'),
  ('United States', 'Pittsburgh Field Club'),
  ('United States', 'Pittsburgh National Golf Club'),
  ('United States', 'Placid Lakes Country Club'),
  ('United States', 'Plainfield Country Club'),
  ('United States', 'Plainfield West Nine'),
  ('United States', 'Plains Municipal Golf Course'),
  ('United States', 'Plainsman Golf Club'),
  ('United States', 'Plandome Country Club'),
  ('United States', 'Plantation At Ponte Vedra'),
  ('United States', 'Plantation At Sea Island Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club North South Course'),
  ('United States', 'Plantation Bay Golf And Country Club Prestwick Golf Club'),
  ('United States', 'Plantation Bay Golf And Country Club South West Course'),
  ('United States', 'Plantation Bay Golf And Country Club West North Course'),
  ('United States', 'Plantation Bottom At Valdosta Country Club'),
  ('United States', 'Plantation Golf Club'),
  ('United States', 'Plantation Golf Course'),
  ('United States', 'Plantation Lakes Golf And Country Club'),
  ('United States', 'Plantation On Crystal River Championship Course'),
  ('United States', 'Plantation On Crystal River Lagoons Course'),
  ('United States', 'Plantation Palms Golf Club'),
  ('United States', 'Plantation Preserve Golf Course'),
  ('United States', 'Planterra Ridge Golf Club'),
  ('United States', 'Planters Row At Port Royal Golf Club'),
  ('United States', 'Platteville Golf and Country Club'),
  ('United States', 'Player At Lyman Orchards Golf Club'),
  ('United States', 'Player S Ridge Golf'),
  ('United States', 'Players Club At Deer Creek Highlands 9'),
  ('United States', 'Players Club At Deer Creek Palmer Championship'),
  ('United States', 'Players Club At St James Plantation'),
  ('United States', 'Pleasant Acres Golf Course'),
  ('United States', 'Pleasant Hill Golf Club'),
  ('United States', 'Pleasant Hill Golf Course'),
  ('United States', 'Pleasant Hills Golf Course'),
  ('United States', 'Pleasant Knolls Golf Course At Turning Stone'),
  ('United States', 'Pleasant Meadows'),
  ('United States', 'Pleasant Run Golf Club'),
  ('United States', 'Pleasant Run Recreation Center'),
  ('United States', 'Pleasant Valley Country Club'),
  ('United States', 'Pleasant Valley Golf Club'),
  ('United States', 'Pleasant Valley Golf Course'),
  ('United States', 'Pleasant Valley Sports Club'),
  ('United States', 'Pleasant View Golf Club'),
  ('United States', 'Pleasant View Golf Course'),
  ('United States', 'Pleasanton Golf Center'),
  ('United States', 'Pleasantville Golf & Country Club'),
  ('United States', 'Plentywood Golf Club'),
  ('United States', 'Plum Brook Country Club'),
  ('United States', 'Plum Brook Golf Course'),
  ('United States', 'Plum Creek Golf Country Club'),
  ('United States', 'Plum Creek Golf Course'),
  ('United States', 'Plum Hollow Country Club'),
  ('United States', 'Plum Lake Golf Course'),
  ('United States', 'Plum River Golf Course'),
  ('United States', 'Plum Tree Country Club'),
  ('United States', 'Plumas Lake Golf Country Club'),
  ('United States', 'Plumas Pines Golf Resort'),
  ('United States', 'Plym Park Golf Course'),
  ('United States', 'Plymouth Country Club'),
  ('United States', 'Pocahontas Country Club'),
  ('United States', 'Pocahontas Golf Club'),
  ('United States', 'Pocantico Hills Golf Course'),
  ('United States', 'Pocasset Golf Club'),
  ('United States', 'Poco Diablo Resort'),
  ('United States', 'Pocono Farms Golf Course'),
  ('United States', 'Pocono Hills Golf Course'),
  ('United States', 'Pohick Bay Golf Course'),
  ('United States', 'Pohlcat'),
  ('United States', 'Poinciana Country Club'),
  ('United States', 'Point Judith Country Club'),
  ('United States', 'Point O'' Woods'),
  ('United States', 'Point Rock Golf Club'),
  ('United States', 'Point Sebago Golf Beach Resort'),
  ('United States', 'Point University Golf Club'),
  ('United States', 'Pointe Aux Barques Golf Course'),
  ('United States', 'Pointe South Golf Club'),
  ('United States', 'Pointe West Country Club'),
  ('United States', 'Pointe West Golf Course'),
  ('United States', 'Poipu Bay Golf Course'),
  ('United States', 'Pokegama Golf Course'),
  ('United States', 'Pokegama Pitch & Putt'),
  ('United States', 'Pole Valley Players Golf Course'),
  ('United States', 'Polo Fields Golf and Country Club'),
  ('United States', 'Polo Golf Country Club'),
  ('United States', 'Polo Park East'),
  ('United States', 'Polo Park Golf Course'),
  ('United States', 'Polson Bay Golf Course Championship Course'),
  ('United States', 'Polson Bay Golf Course Olde Course'),
  ('United States', 'Pomona Golf Country Club'),
  ('United States', 'Pomperaug Golf Club'),
  ('United States', 'Pompey Club The'),
  ('United States', 'Ponca City Country Club'),
  ('United States', 'Ponce De Leon Golf Course'),
  ('United States', 'Pondera Golf Club'),
  ('United States', 'Ponderosa Butte Public Golf Course'),
  ('United States', 'Ponderosa Country Club'),
  ('United States', 'Ponderosa Golf Club'),
  ('United States', 'Ponderosa Golf Course'),
  ('United States', 'Ponderosa Meadows At Pagosa Springs Golf Club'),
  ('United States', 'Ponderosa Pines Golf Course'),
  ('United States', 'Ponderosa Springs Golf Course'),
  ('United States', 'Ponds Golf Course At Quail Heights Country Club'),
  ('United States', 'Ponemah Green Family Golf Center'),
  ('United States', 'Ponta Creek Golf Course Nas'),
  ('United States', 'Pontiac Country Club'),
  ('United States', 'Pontotoc Country Club'),
  ('United States', 'Poolesville Golf Course'),
  ('United States', 'Poolsbrook Golf Course'),
  ('United States', 'Popes Grove Golf Course'),
  ('United States', 'Poplar Creek Golf Course'),
  ('United States', 'Poplar Forest Golf Course'),
  ('United States', 'Poplar Golf Course'),
  ('United States', 'Poplar Grove Golf Club'),
  ('United States', 'Poppy Estate Golf Course'),
  ('United States', 'Poppy Hills Golf Course'),
  ('United States', 'Poppy Ridge Golf Course 18 Hole'),
  ('United States', 'Poppy Ridge Golf Course The Ridge 9'),
  ('United States', 'Poquoy Brook Golf Course'),
  ('United States', 'Port Bay Golf Club'),
  ('United States', 'Port Charlotte Golf Club'),
  ('United States', 'Port Huron Elks Lodge Golf Course'),
  ('United States', 'Port Huron Golf Club'),
  ('United States', 'Port Jefferson Country Club At Harbor Hills'),
  ('United States', 'Port Ludlow Golf Resort'),
  ('United States', 'Port Townsend Golf Club'),
  ('United States', 'Portage Country Club'),
  ('United States', 'Portage Golf Club'),
  ('United States', 'Portage Hills Country Club'),
  ('United States', 'Portage Lake Golf Course'),
  ('United States', 'Portales Country Club'),
  ('United States', 'Porter S Neck Country Club'),
  ('United States', 'Porter Valley Country Club'),
  ('United States', 'Porterville Municipal Golf Course'),
  ('United States', 'Portland Country Club'),
  ('United States', 'Portland Golf Course'),
  ('United States', 'Portland Golf Course West'),
  ('United States', 'Portola Country Club'),
  ('United States', 'Portsmouth Country Club'),
  ('United States', 'Posse At Paradise Pointe Golf Complex'),
  ('United States', 'Poston Butte Golf Club'),
  ('United States', 'Potomac Shores Golf Club'),
  ('United States', 'Potowomut Golf Club'),
  ('United States', 'Potsdam Golf Country Club'),
  ('United States', 'Pottawatomie Golf Course'),
  ('United States', 'Pottawattamie Country Club'),
  ('United States', 'Potters Park Golf Course'),
  ('United States', 'Pound Ridge Golf Club'),
  ('United States', 'Powell Country Club'),
  ('United States', 'Powelton Club The'),
  ('United States', 'Power Ranch Golf Club'),
  ('United States', 'Poxabogue Golf Center'),
  ('United States', 'Practice Area'),
  ('United States', 'Practice Area - Driving Range'),
  ('United States', 'Prague Golf Course'),
  ('United States', 'Prairie At Green Meadow Golf Club'),
  ('United States', 'Prairie Bluff Public Golf Club'),
  ('United States', 'Prairie Country Club'),
  ('United States', 'Prairie Creek Golf Course'),
  ('United States', 'Prairie Dog Golf Course'),
  ('United States', 'Prairie Dunes Country Club'),
  ('United States', 'Prairie Dunes Golf Course'),
  ('United States', 'Prairie Falls Golf Club'),
  ('United States', 'Prairie Farms Golf Course'),
  ('United States', 'Prairie Highlands Golf Course'),
  ('United States', 'Prairie Isle Golf Club'),
  ('United States', 'Prairie Landing'),
  ('United States', 'Prairie Landing Golf Club'),
  ('United States', 'Prairie Links Golf Course & Event Center'),
  ('United States', 'Prairie Pines Golf Club'),
  ('United States', 'Prairie Pines Golf Course'),
  ('United States', 'Prairie Ridge Golf Course'),
  ('United States', 'Prairie Rose Golf Club'),
  ('United States', 'Prairie Trace Golf Club'),
  ('United States', 'Prairie Trail Golf Course'),
  ('United States', 'Prairie Trails Golf Course'),
  ('United States', 'Prairie View Golf Club'),
  ('United States', 'Prairie View Golf Course'),
  ('United States', 'Prairie Vista Golf Course'),
  ('United States', 'Prairie West Colf Course'),
  ('United States', 'Prairie West Golf Club At Weatherford'),
  ('United States', 'Prairie Winds Golf Club'),
  ('United States', 'Prairie Winds Golf Course'),
  ('United States', 'Prairie Woods Golf Course'),
  ('United States', 'Prairie du Chien Country Club'),
  ('United States', 'Prairiewood Golf Course'),
  ('United States', 'Preakness Hills Country Club'),
  ('United States', 'Preakness Valley Golf Course East'),
  ('United States', 'Preakness Valley Golf Course West'),
  ('United States', 'Prentice Pines Golf Course'),
  ('United States', 'Prentiss Country Club'),
  ('United States', 'Prescott Country Club'),
  ('United States', 'Prescott Golf Club'),
  ('United States', 'Preserve At Quail West Golf Country Club'),
  ('United States', 'Preserve Golf Course'),
  ('United States', 'Presidential At Hickory Valley Golf Club'),
  ('United States', 'Presidents Golf Course'),
  ('United States', 'Presidio Golf Course'),
  ('United States', 'Presidio Hills Golf Course'),
  ('United States', 'Presque Isle Country Club'),
  ('United States', 'Prestbury Golf Course'),
  ('United States', 'Preston Golf Country Club'),
  ('United States', 'Preston Golf and Country Club'),
  ('United States', 'Prestwick Country Club'),
  ('United States', 'Prestwick Golf Club'),
  ('United States', 'Prestwick Village Golf Club'),
  ('United States', 'Priest Lake Golf Club'),
  ('United States', 'Primghar Golf and Country Club'),
  ('United States', 'Primm Valley Golf Club Desert Course'),
  ('United States', 'Primm Valley Golf Club Lakes Course'),
  ('United States', 'Primrose At Country Club The'),
  ('United States', 'Prince George Golf Course'),
  ('United States', 'Prince William Golf Club'),
  ('United States', 'Princess Anne Country Club'),
  ('United States', 'Princeton Country Club'),
  ('United States', 'Princeton Elks Golf Course'),
  ('United States', 'Princeton Valley Golf Course'),
  ('United States', 'Princeville Makai Golf Club Makai Course'),
  ('United States', 'Princeville Makai Golf Club Woods Course'),
  ('United States', 'Prison View Golf Course'),
  ('United States', 'Pro Putt Miniature Golf Course'),
  ('United States', 'Proctor Golf Club and Course'),
  ('United States', 'Proctor Pittsford Country Club'),
  ('United States', 'Profile Golf Club'),
  ('United States', 'Promontory Club Dye Canyon Golf Course'),
  ('United States', 'Promontory Club Painted Valley Golf Course'),
  ('United States', 'Prospect Hill Golf Course'),
  ('United States', 'Prospect Point Golf Club'),
  ('United States', 'Prospect Valley Golf Club'),
  ('United States', 'Prouts Neck Country Club'),
  ('United States', 'Providence Club'),
  ('United States', 'Providence Country Club'),
  ('United States', 'Providence Golf Club'),
  ('United States', 'Pruneridge Golf Course'),
  ('United States', 'Pryor Creek Golf Club Elmer Link Course'),
  ('United States', 'Pryor Creek Golf Club Johnny Walker Course'),
  ('United States', 'Pryor Creek Municipal Golf Course'),
  ('United States', 'Ptarmigan Country Club'),
  ('United States', 'Puakea Golf Course'),
  ('United States', 'Pub Course At Mcmenamins Edgefield East 12'),
  ('United States', 'Pub Course At Mcmenamins Edgefield West 20'),
  ('United States', 'Pudding Ridge Golf Club'),
  ('United States', 'Pueblo Country Club'),
  ('United States', 'Pueblo El Mirage Golf Club'),
  ('United States', 'Puerto Del Sol Golf Course'),
  ('United States', 'Pukalani Country Club'),
  ('United States', 'Pumpkin Hollow Driving Range'),
  ('United States', 'Pumpkin Vine Golf Course'),
  ('United States', 'Punderson Golf Course'),
  ('United States', 'Punxsutawney Country Club'),
  ('United States', 'Purgatory Golf Club'),
  ('United States', 'Purple Hawk Country Club'),
  ('United States', 'Purple Sage Municipal Golf Course'),
  ('United States', 'Purpoodock Club'),
  ('United States', 'Putnam County Golf Course'),
  ('United States', 'Putting Green Mini Golf'),
  ('United States', 'Quaboag Country Club'),
  ('United States', 'Quail At Quail Creek Country Club'),
  ('United States', 'Quail Brook Golf Course'),
  ('United States', 'Quail Chase Golf Course'),
  ('United States', 'Quail Creek Golf Club'),
  ('United States', 'Quail Creek Golf Club Coyote Road Runner Course'),
  ('United States', 'Quail Creek Golf Club Quail Coyote Course'),
  ('United States', 'Quail Creek Golf Club Road Runner Quail Course'),
  ('United States', 'Quail Creek Golf Country Club'),
  ('United States', 'Quail Creek Golf Course'),
  ('United States', 'Quail Dunes Golf Course'),
  ('United States', 'Quail Hollow Country Club'),
  ('United States', 'Quail Hollow Golf Club'),
  ('United States', 'Quail Hollow Golf Course Championship'),
  ('United States', 'Quail Hollow Golf Course Short'),
  ('United States', 'Quail Lodge Resort Golf Club'),
  ('United States', 'Quail Meadows Golf Course'),
  ('United States', 'Quail Ridge Country Club'),
  ('United States', 'Quail Ridge Golf Club'),
  ('United States', 'Quail Ridge Golf Country Club'),
  ('United States', 'Quail Ridge Golf Course'),
  ('United States', 'Quail Ridge Golf World Executive Golf Course'),
  ('United States', 'Quail Run At Rio Verde Country Club'),
  ('United States', 'Quail Run Executive Golf Course'),
  ('United States', 'Quail Run Golf Club'),
  ('United States', 'Quail Run Golf Course'),
  ('United States', 'Quail Valley Golf Club'),
  ('United States', 'Quail Valley Golf Course'),
  ('United States', 'Quail Village Golf Club'),
  ('United States', 'Quailwood Greens Golf Course'),
  ('United States', 'Quaker Creek Golf Course'),
  ('United States', 'Quaker Hill Country Club'),
  ('United States', 'Quaker Meadows Golf Course'),
  ('United States', 'Quaker Ridge Golf Club'),
  ('United States', 'Quality Inn Suites Golf Resort'),
  ('United States', 'Quanah Country Club'),
  ('United States', 'Quarry At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Quarry Oaks Golf Course'),
  ('United States', 'Quarry Pines Golf Club'),
  ('United States', 'Quarry Ridge Golf Center'),
  ('United States', 'Quarry Ridge Golf Course'),
  ('United States', 'Quarry View Golf Course'),
  ('United States', 'Quartz Mountain Golf Course'),
  ('United States', 'Quashnet Valley Country Club'),
  ('United States', 'Queen Valley Golf Course'),
  ('United States', 'Queenfield Golf Club'),
  ('United States', 'Queens Harbour Yacht Country Club'),
  ('United States', 'Queensbury Country Club'),
  ('United States', 'Queenston Golf Club'),
  ('United States', 'Querbes Park Golf Course'),
  ('United States', 'Quicksilver Golf Club'),
  ('United States', 'Quidnessett Country Club'),
  ('United States', 'Quiet Times Golf Course'),
  ('United States', 'Quig''s Maplewood Golf Course'),
  ('United States', 'Quimby Golf Course'),
  ('United States', 'Quincy Country Club'),
  ('United States', 'Quincy Golf Course'),
  ('United States', 'Quinnatisset Country Club')
on conflict (country, name) do nothing;