insert into public.golf_courses (country, name) values
  ('United States', 'Victoria National Golf Club'),
  ('United States', 'Victors Par 3 Golf Course'),
  ('United States', 'Victory Hills Golf Course'),
  ('United States', 'Victory Lake Golf Course'),
  ('United States', 'Victory Links Golf Course'),
  ('United States', 'Victory Ranch Golf Club'),
  ('United States', 'Vienna Greens Country Club'),
  ('United States', 'Viera East Golf Club'),
  ('United States', 'Viking Golf Course'),
  ('United States', 'Viking Meadows Golf Club'),
  ('United States', 'Villa Olivia Country Club'),
  ('United States', 'Villa Roma Golf Course'),
  ('United States', 'Village At Jupiter Hills Club'),
  ('United States', 'Village Club Of Sands Point'),
  ('United States', 'Village Creek Golf Club'),
  ('United States', 'Village Golf Course'),
  ('United States', 'Village Green Country Club'),
  ('United States', 'Village Green Golf Club'),
  ('United States', 'Village Green Golf Course'),
  ('United States', 'Village Greens Golf Country Club'),
  ('United States', 'Village Greens Golf Course'),
  ('United States', 'Village Greens of Woodridge'),
  ('United States', 'Village Links Golf Club'),
  ('United States', 'Villages At Country Creek The'),
  ('United States', 'Villas Crossing Golf Course'),
  ('United States', 'Ville Platte Golf Country Club'),
  ('United States', 'Vinces Sport Center Par 3 Golf Course'),
  ('United States', 'Vineland Golf Course'),
  ('United States', 'Vineyard Golf At White Lake'),
  ('United States', 'Vineyard Golf Club'),
  ('United States', 'Vineyard Golf Course'),
  ('United States', 'Vineyard Greens Golf Course'),
  ('United States', 'Vineyard Knolls Golf Club'),
  ('United States', 'Vineyard National Golf Course'),
  ('United States', 'Vineyard Valley Golf Club'),
  ('United States', 'Vintage At White Deer Golf Club'),
  ('United States', 'Vintners Golf Club'),
  ('United States', 'Vinton Country Club'),
  ('United States', 'Virginia Amelia At Mallory Hill Golf Course'),
  ('United States', 'Virginia Beach National Golf Club'),
  ('United States', 'Virginia Country Club'),
  ('United States', 'Virginia Golf Center'),
  ('United States', 'Virginia Golf Course'),
  ('United States', 'Virginia Tech Golf Course'),
  ('United States', 'Viroqua Hills Golf Course'),
  ('United States', 'Visalia Country Club'),
  ('United States', 'Vista Golf Course'),
  ('United States', 'Vista Lake At Los Coyotes Country Club'),
  ('United States', 'Vista Plantation Golf Course'),
  ('United States', 'Volcano Golf Country Club'),
  ('United States', 'Volusia At The Villages Executive Golf Trail'),
  ('United States', 'Voyager Rv Resort And Golf Course'),
  ('United States', 'Voyager Village'),
  ('United States', 'Voyager Village Par 3'),
  ('United States', 'Wa Noa Golf Club'),
  ('United States', 'Waabooz Run Golf Course'),
  ('United States', 'Wabaunsee Pines Golf Course'),
  ('United States', 'Wabeek Country Club'),
  ('United States', 'Waccabuc Country Club'),
  ('United States', 'Wachesaw East Golf Club'),
  ('United States', 'Wachesaw Plantation Club'),
  ('United States', 'Wachusett Country Club'),
  ('United States', 'Wade Hampton Golf Course'),
  ('United States', 'Wagon Trail To Lonesome Pine Golf Course'),
  ('United States', 'Wahconah Country Club'),
  ('United States', 'Wahkonsa Country Club'),
  ('United States', 'Waialae Country Club'),
  ('United States', 'Waiehu Golf Course'),
  ('United States', 'Waikele Country Club'),
  ('United States', 'Waikoloa Beach Resort Beach Course'),
  ('United States', 'Waikoloa Beach Resort Kings Lakes Course'),
  ('United States', 'Wailea Golf Club Emerald Course'),
  ('United States', 'Wailea Golf Club Gold Course'),
  ('United States', 'Wailea Golf Club Old Blue Course'),
  ('United States', 'Wailua Municipal Golf Course'),
  ('United States', 'Wakonda Club'),
  ('United States', 'Wakulla Sands Golf Club'),
  ('United States', 'Walden Oaks Country Club'),
  ('United States', 'Walden Ponds Golf Club'),
  ('United States', 'Waldorf Astoria Golf Club'),
  ('United States', 'Waldron Country Club'),
  ('United States', 'Walker Creek Golf Course'),
  ('United States', 'Walking Stick Golf Course'),
  ('United States', 'Walla Walla Country Club'),
  ('United States', 'Wallingford Country Club'),
  ('United States', 'Wallinwood Springs Golf Club'),
  ('United States', 'Wallkill Golf Club'),
  ('United States', 'Walloon Lake Country Club'),
  ('United States', 'Walnut Creek Country Club'),
  ('United States', 'Walnut Creek Golf Club'),
  ('United States', 'Walnut Creek Golf Preserve'),
  ('United States', 'Walnut Greens Golf Course'),
  ('United States', 'Walnut Grove At The Villages Executive Golf Trail'),
  ('United States', 'Walnut Grove Golf Course'),
  ('United States', 'Walnut Lake Country Club'),
  ('United States', 'Walnut Lane Golf Club'),
  ('United States', 'Walnut Ridge Golf Country Club'),
  ('United States', 'Walpole Country Club'),
  ('United States', 'Walsenburg Golf Course'),
  ('United States', 'Walsh Golf Center'),
  ('United States', 'Walter E Hall Memorial Golf Course'),
  ('United States', 'Walter J Nagorski Golf Course'),
  ('United States', 'Walter Sellers Memorial Country Club'),
  ('United States', 'Walther''s Golf Driving Range'),
  ('United States', 'Walton Golf Club'),
  ('United States', 'Waltz Golf Farm'),
  ('United States', 'Wamego Country Club'),
  ('United States', 'Wampanoag Country Club'),
  ('United States', 'Wampanoag Golf Course'),
  ('United States', 'Wampatuck Country Club'),
  ('United States', 'Wanakah Country Club'),
  ('United States', 'Wanaki Golf Course'),
  ('United States', 'Wanamaker Course At Pga Golf Club'),
  ('United States', 'Wanango Country Club'),
  ('United States', 'Wander Springs Golf Course'),
  ('United States', 'Wandering Creek Golf Course'),
  ('United States', 'Wandermere Golf Course'),
  ('United States', 'Wanee Lake Country Club'),
  ('United States', 'Wannamoisett Country Club'),
  ('United States', 'Wanumetonomy Golf Country Club'),
  ('United States', 'Wapicada Golf Club'),
  ('United States', 'Wapsi Oaks Country Club'),
  ('United States', 'Wapsie Ridge Golf Course'),
  ('United States', 'Wapsipinicon Country Club'),
  ('United States', 'Ware Shoals Golf Course'),
  ('United States', 'Warfield Greens Golf Club'),
  ('United States', 'Warm Springs Golf Course'),
  ('United States', 'Warminsters Five Ponds Golf Club'),
  ('United States', 'Warner Springs Ranch'),
  ('United States', 'Warnimont Park Golf Course'),
  ('United States', 'Warren Country Club'),
  ('United States', 'Warren Golf Course'),
  ('United States', 'Warren Swigart 9-Hole Golf Course'),
  ('United States', 'Warren Valley Golf Course'),
  ('United States', 'Warrenbrook Golf Course'),
  ('United States', 'Warrenton Golf Course'),
  ('United States', 'Warrior Golf Club'),
  ('United States', 'Warrior Hills Golf Course'),
  ('United States', 'Warrior Run Golf Course'),
  ('United States', 'Warriors Path State Park Golf Course'),
  ('United States', 'Warroad Estates Golf Course'),
  ('United States', 'Warwick Country Club'),
  ('United States', 'Warwick Hills Golf & Country Club'),
  ('United States', 'Warwick Valley Country Club'),
  ('United States', 'Washakie Golf and RV Resort'),
  ('United States', 'Washington Country Club'),
  ('United States', 'Washington County Golf Country Club'),
  ('United States', 'Washington County Golf Course'),
  ('United States', 'Washington Golf Club'),
  ('United States', 'Washington Golf Country Club'),
  ('United States', 'Washington Golf Learning Center'),
  ('United States', 'Washington National Golf Club'),
  ('United States', 'Washington Park Golf Course'),
  ('United States', 'Washington Park Municipal Golf Course'),
  ('United States', 'Washington Township Municipal Golf Course'),
  ('United States', 'Washington Wilkes Country Club'),
  ('United States', 'Washington Yacht Country Club'),
  ('United States', 'Washoe Golf Course'),
  ('United States', 'Washtenaw Golf Club'),
  ('United States', 'Wasioto Winds At Pine Mountain State Park Golf Course'),
  ('United States', 'Waskada Golf Club'),
  ('United States', 'Watchung Valley Golf Club'),
  ('United States', 'Water Oak Golf Club'),
  ('United States', 'Water''s Edge Golf Club'),
  ('United States', 'Waterfall Golf Club'),
  ('United States', 'Waterford Golf Club'),
  ('United States', 'Waterlefe Golf River Club'),
  ('United States', 'Waterloo Country Club'),
  ('United States', 'Waterloo Golf Course'),
  ('United States', 'Watermark Country Club'),
  ('United States', 'Waters Edge Gold Course'),
  ('United States', 'Waters Edge Golf Course'),
  ('United States', 'Waters Mounds At Brickyard Plantation Golf Club'),
  ('United States', 'Watertown Coutry Club'),
  ('United States', 'Watertown Golf Club'),
  ('United States', 'Waterville Community Golf Association'),
  ('United States', 'Waterville Country Club'),
  ('United States', 'Waterville Valley Golf Club'),
  ('United States', 'Waterways Golf Resort East Course'),
  ('United States', 'Waterways Golf Resort West Course'),
  ('United States', 'Watkins Glen Golf Club'),
  ('United States', 'Watonga Golf Club'),
  ('United States', 'Waubeeka Golf Links'),
  ('United States', 'Waukewan Golf Club'),
  ('United States', 'Waukon Golf and Country Club'),
  ('United States', 'Waumbek Golf Club'),
  ('United States', 'Waupaca Country Club'),
  ('United States', 'Wausau Country Club'),
  ('United States', 'Wausaukee Club'),
  ('United States', 'Waushara Country Club'),
  ('United States', 'Waveland Golf Course'),
  ('United States', 'Waverly Municipal Golf Course'),
  ('United States', 'Waverly Oaks Golf Club'),
  ('United States', 'Wawasee Golf Club'),
  ('United States', 'Wawashkamo Golf Course'),
  ('United States', 'Wawenock Golf Club'),
  ('United States', 'Wawona Golf Course'),
  ('United States', 'Wawonowin Golf Course'),
  ('United States', 'Wayland Country Club'),
  ('United States', 'Wayne Hills Country Club'),
  ('United States', 'Waynesboro Country Club'),
  ('United States', 'Waynesboro Par 3 Golf Course'),
  ('United States', 'Waynesborough Country Club'),
  ('United States', 'Waynesville Inn Golf Club'),
  ('United States', 'Wayton Hill''s Golf Course'),
  ('United States', 'Wayzata Country Club'),
  ('United States', 'Weathervane Golf Club'),
  ('United States', 'WeaverRidge Golf Club'),
  ('United States', 'Webb Park Golf Course'),
  ('United States', 'Webbs Reserve Golf Club'),
  ('United States', 'Weber Park Golf Course'),
  ('United States', 'Webhannet Golf Club'),
  ('United States', 'Webster City Country Club'),
  ('United States', 'Weddington Golf And Tennis'),
  ('United States', 'Wedgefield Country Club'),
  ('United States', 'Wedgefield Golf Club'),
  ('United States', 'Wedgewood'),
  ('United States', 'Wedgewood Cove Golf Club'),
  ('United States', 'Wedgewood Golf & Country Club'),
  ('United States', 'Wedgewood Golf Club'),
  ('United States', 'Wedgewood Golf Club Maple Course'),
  ('United States', 'Wedgewood Golf Club Oak Course'),
  ('United States', 'Wedgewood Golf Club Pine Course'),
  ('United States', 'Wedgewood Golf Course'),
  ('United States', 'Wedgewood Par 3 Golf Course'),
  ('United States', 'Wedgewood Pines Country Club'),
  ('United States', 'Wedgwood Country Club'),
  ('United States', 'Wee Burn Country Club'),
  ('United States', 'Wee Nip At Grand Geneva Resort Spa'),
  ('United States', 'Weed Golf Club'),
  ('United States', 'Weekapaug Golf Club'),
  ('United States', 'Weeping Trout Sports Resort'),
  ('United States', 'Weequahic Park Golf Course'),
  ('United States', 'Weibring Golf Club'),
  ('United States', 'Weissinger Hills Golf Course'),
  ('United States', 'Wekiva Golf Club'),
  ('United States', 'Welk Resort San Diego Fountains Executive Course'),
  ('United States', 'Welk Resort San Diego Oaks Course'),
  ('United States', 'Wellen Park Golf Country Club'),
  ('United States', 'Wellesley Country Club'),
  ('United States', 'Wellesley Island State Park Golf Course'),
  ('United States', 'Wellington Country Club'),
  ('United States', 'Wellington Golf Club'),
  ('United States', 'Wellington Greens Golf Course'),
  ('United States', 'Wellington National Golf Club'),
  ('United States', 'Wellman Golf Club'),
  ('United States', 'Wellman Golf Course'),
  ('United States', 'Wells College Golf Course'),
  ('United States', 'Wells Golf Course'),
  ('United States', 'Wellshire Golf Course'),
  ('United States', 'Wellsville Country Club'),
  ('United States', 'Wemberly Hills Golf Course'),
  ('United States', 'Wenatchee Golf Country Club'),
  ('United States', 'Wendell Coffee Golf Center'),
  ('United States', 'Wendell Country Club'),
  ('United States', 'Wenham Country Club'),
  ('United States', 'Wentworth By The Sea Country Club'),
  ('United States', 'Wentworth Golf Club'),
  ('United States', 'Wentworth Hills Golf Country Club Semi Private'),
  ('United States', 'Wequetonsing Golf Club'),
  ('United States', 'Wesburn Golf Club'),
  ('United States', 'West Appleton Country Club'),
  ('United States', 'West At Belfair Golf Club'),
  ('United States', 'West At Broadmoor Golf Club'),
  ('United States', 'West At Bull Creek Golf Course'),
  ('United States', 'West At Churchville Park Golf Course'),
  ('United States', 'West At Country Club Of Hershey'),
  ('United States', 'West At Eagle Valley Golf Course'),
  ('United States', 'West At Fountains Country Club'),
  ('United States', 'West At Glendoveer Golf Course'),
  ('United States', 'West At Grandover Resort'),
  ('United States', 'West At Imperial Golf Club'),
  ('United States', 'West At Jacaranda Golf Club'),
  ('United States', 'West At Johns Island Club'),
  ('United States', 'West At Laurel Oak Country Club'),
  ('United States', 'West At Lincoln Park Golf Course'),
  ('United States', 'West At Maidstone Club'),
  ('United States', 'West At Malone Golf Club'),
  ('United States', 'West At Merion Golf Club'),
  ('United States', 'West At Mohawk Golf Club'),
  ('United States', 'West At Oak Hill Country Club'),
  ('United States', 'West At Oak Tree Country Club'),
  ('United States', 'West At Orangebrook Country Club'),
  ('United States', 'West At Rogues Roost Golf Country Club'),
  ('United States', 'West At Tamarack Golf Course'),
  ('United States', 'West At Westchester Country Club'),
  ('United States', 'West At Windyke Country Club'),
  ('United States', 'West At Winged Foot Golf Club'),
  ('United States', 'West At Wycliffe Country Club'),
  ('United States', 'West Bay Golf Club'),
  ('United States', 'West Bend Country Club'),
  ('United States', 'West Bend Golf and Country Club'),
  ('United States', 'West Bend Lakes'),
  ('United States', 'West Bend Lakes Golf Club'),
  ('United States', 'West Bolton Golf Club'),
  ('United States', 'West Branch Country Club'),
  ('United States', 'West Bridgewater Country Club'),
  ('United States', 'West Chase Golf Club'),
  ('United States', 'West Chester Golf Country Club'),
  ('United States', 'West Course At Belleair Country Club'),
  ('United States', 'West East At Ridgewood Country Club The'),
  ('United States', 'West End Golf Course'),
  ('United States', 'West Grand Golf'),
  ('United States', 'West Hill Country Club'),
  ('United States', 'West Hills Country Club'),
  ('United States', 'West Hills Country Club River Course'),
  ('United States', 'West Hills Par 3'),
  ('United States', 'West Lafayette Golf Club'),
  ('United States', 'West Lake Country Club'),
  ('United States', 'West Liberty Country Club'),
  ('United States', 'West Loch Municipal Golf Course'),
  ('United States', 'West Nine At Firethorn'),
  ('United States', 'West Nine At Southern Hills Country Club'),
  ('United States', 'West North At Cedar Knoll Country Club'),
  ('United States', 'West North At Elmridge Golf Club'),
  ('United States', 'West North At Krendale Golf Course'),
  ('United States', 'West North At Rolling Acres Golf Course'),
  ('United States', 'West Orange Country Club'),
  ('United States', 'West Ottawa Golf Course'),
  ('United States', 'West Pines Golf Club'),
  ('United States', 'West Plains Country Club'),
  ('United States', 'West Point Country Club'),
  ('United States', 'West Point Golf Course'),
  ('United States', 'West Public At Drumlins Golf Club'),
  ('United States', 'West Richland Municipal Golf'),
  ('United States', 'West Sayville Golf Course'),
  ('United States', 'West Seattle Golf Club'),
  ('United States', 'West Shore Country Club'),
  ('United States', 'West Shore Golf & Country Club'),
  ('United States', 'West Side Golf Club'),
  ('United States', 'West South At Cedar Knoll Country Club'),
  ('United States', 'West South At Fernandina Beach Golf Club'),
  ('United States', 'West South At South Hills Golf Club'),
  ('United States', 'West Warwick Country Club'),
  ('United States', 'Westborough Country Club'),
  ('United States', 'Westborough County Club'),
  ('United States', 'Westbrook Country Club'),
  ('United States', 'Westbrook Golf Club Lakes Course'),
  ('United States', 'Westbrook Golf Club Vistas Course'),
  ('United States', 'Westbrook Hills Golf Course'),
  ('United States', 'Westchase Golf Club'),
  ('United States', 'Westchester Golf Course'),
  ('United States', 'Westchester Hills Golf Club'),
  ('United States', 'Westdrift Manhattan Beach Golf Club'),
  ('United States', 'Western Acres Golf Course'),
  ('United States', 'Western Golf and Country Club'),
  ('United States', 'Western Greens Country Club'),
  ('United States', 'Western Hills Country Club'),
  ('United States', 'Western Hills Golf Club'),
  ('United States', 'Western Hills Golf Country Club'),
  ('United States', 'Western Hills Golf Course'),
  ('United States', 'Western Lakes Golf Course'),
  ('United States', 'Western Skies Golf Club'),
  ('United States', 'Western View Golf Club'),
  ('United States', 'Westerville Golf Center'),
  ('United States', 'Westfield Country Club'),
  ('United States', 'Westfield Golf Club'),
  ('United States', 'Westfields Golf Club'),
  ('United States', 'Westgate River Ranch Resort'),
  ('United States', 'Westhampton Country Club'),
  ('United States', 'Westhaven Golf Club'),
  ('United States', 'Westin Rancho Mirage Golf Resort Spa Pete Dye Resort Course'),
  ('United States', 'Westlake Country Club'),
  ('United States', 'Westlake Golf And Country Club'),
  ('United States', 'Westlake Golf Country Club'),
  ('United States', 'Westlake Golf Course'),
  ('United States', 'Westminster Country Club'),
  ('United States', 'Westminster National Golf Course'),
  ('United States', 'Westmoor Country Club'),
  ('United States', 'Westmoreland Country Club'),
  ('United States', 'Westmoreland Golf Club'),
  ('United States', 'Weston Golf Club'),
  ('United States', 'Weston Hills Country Club Players Course'),
  ('United States', 'Weston Hills Country Club Tour Course'),
  ('United States', 'Westover Golf Club'),
  ('United States', 'Westport Country Club The'),
  ('United States', 'Westport Golf Course'),
  ('United States', 'Westport Longshore Golf Club'),
  ('United States', 'Westridge Golf Club'),
  ('United States', 'Westvale Golf Course'),
  ('United States', 'Westview Golf Course'),
  ('United States', 'Westwind Golf Course'),
  ('United States', 'Westwind Rv Golf Resort'),
  ('United States', 'Westwood Country Club'),
  ('United States', 'Westwood Golf Club'),
  ('United States', 'Westwood Golf Course'),
  ('United States', 'Westwood Golf Course (9-hole)'),
  ('United States', 'Westwood Hills Country Club'),
  ('United States', 'Westwood Park Golf Course'),
  ('United States', 'Westwood West Golf Course'),
  ('United States', 'Westwoods Golf Club'),
  ('United States', 'Westwynd Golf Course'),
  ('United States', 'Wetherington Golf & Country Club'),
  ('United States', 'Wethersfield Country Club'),
  ('United States', 'Wetumka Golf Club'),
  ('United States', 'Wexford Golf'),
  ('United States', 'Weyhill At Saucon Valley Country Club'),
  ('United States', 'Weymont Run Country Club'),
  ('United States', 'Whaling City Golf Course At New Bedford'),
  ('United States', 'Wheatfield Valley Golf Course')
on conflict (country, name) do nothing;