insert into public.golf_courses (country, name) values
  ('United States', 'Christopher Morley Park'),
  ('United States', 'Chula Vista At The Villages Executive Golf Trail'),
  ('United States', 'Chula Vista Golf Course'),
  ('United States', 'Churchill Greens At The Villages Executive Golf Trail'),
  ('United States', 'Churn Creek Golf Course'),
  ('United States', 'Cimarron County Golf Course'),
  ('United States', 'Cimarron Golf Club'),
  ('United States', 'Cimarron Golf Club Boulder Course'),
  ('United States', 'Cimarron Golf Club Pebble Par 3 Course'),
  ('United States', 'Cimarron Golf Course'),
  ('United States', 'Cimarron National Golf Club Aqua Canyon Course'),
  ('United States', 'Cimarron National Golf Club Cimarron National Course'),
  ('United States', 'Cimarron Valley Golf Club'),
  ('United States', 'Cimarrone Golf Club'),
  ('United States', 'Cincinnati Country Club'),
  ('United States', 'Cinder Ridge Golf Course'),
  ('United States', 'Cinnabar Hills Golf Club Canyon Mountain'),
  ('United States', 'Cinnabar Hills Golf Club Lake Canyon'),
  ('United States', 'Cinnabar Hills Golf Club Mountain Lake'),
  ('United States', 'Circle R Golf Course'),
  ('United States', 'Circlestone Country Club'),
  ('United States', 'Circling Hills Golf Course'),
  ('United States', 'Circling Raven Golf Club'),
  ('United States', 'Citrus Hills Golf Country Club Meadows Course'),
  ('United States', 'Citrus Hills Golf Country Club Oaks Course'),
  ('United States', 'Citrus National Golf Club'),
  ('United States', 'Citrus Springs Golf Country Club'),
  ('United States', 'City Club Marietta'),
  ('United States', 'City Of Douglas Municipal Golf Course'),
  ('United States', 'City Of Lauderhill Golf Course'),
  ('United States', 'City Of Portsmouth Bide A Wee Golf Course'),
  ('United States', 'City Park Golf Course'),
  ('United States', 'City Park Nine Golf Course'),
  ('United States', 'City of Florence Golf Course'),
  ('United States', 'Civitan Golf Course'),
  ('United States', 'Cj S Par 3 Golf Course'),
  ('United States', 'Claflin Golf Club'),
  ('United States', 'Clair Mar Golf Course'),
  ('United States', 'Claremont Country Club'),
  ('United States', 'Clarinda Country Club'),
  ('United States', 'Clarion Oaks Golf Course'),
  ('United States', 'Clark Lake Golf Course'),
  ('United States', 'Clarksdale Country Club'),
  ('United States', 'Clarksville Country Club'),
  ('United States', 'Clarmond Country Club'),
  ('United States', 'Classic At Suntree Country Club'),
  ('United States', 'Classic Golf Club'),
  ('United States', 'Clay Center Country Club'),
  ('United States', 'Clay County Country Club'),
  ('United States', 'Clayton Country Club'),
  ('United States', 'Clayton Golf Club'),
  ('United States', 'Clayton Park Golf Course'),
  ('United States', 'Clear Creek Golf Center'),
  ('United States', 'Clear Creek Golf Club'),
  ('United States', 'Clear Fork Valley Country Club'),
  ('United States', 'Clear Lake Country Club'),
  ('United States', 'Clear Lake Golf Club'),
  ('United States', 'Clearbrook'),
  ('United States', 'Clearbrook Golf Course'),
  ('United States', 'Clearfield Curwensville Country Club'),
  ('United States', 'Clearview Country Club'),
  ('United States', 'Clearview Golf Course'),
  ('United States', 'Clearview Park Golf Course'),
  ('United States', 'Clearwater Country Club'),
  ('United States', 'Clearwater Lake Golf Course'),
  ('United States', 'Clerbrook Golf Rv Resort'),
  ('United States', 'Clermont National Golf Course'),
  ('United States', 'Cleveland Country Club'),
  ('United States', 'Clewiston Golf Course'),
  ('United States', 'Cliff Park Inn Golf Course'),
  ('United States', 'Cliff View Golf Club And Inn'),
  ('United States', 'Cliffhangers Golf Course'),
  ('United States', 'Clifton Fine Municipal Golf Course'),
  ('United States', 'Clifton Highlands Golf Club'),
  ('United States', 'Clifton Highlands Short Course'),
  ('United States', 'Clifton Hollow Golf Club'),
  ('United States', 'Clifton Springs Country Club'),
  ('United States', 'Cliftondale Country Club'),
  ('United States', 'Clifty Creek Golf Course'),
  ('United States', 'Clinchview Golf Club'),
  ('United States', 'Clinton Country Club'),
  ('United States', 'Clinton Golf Course'),
  ('United States', 'Clinton Heights Golf'),
  ('United States', 'Clintonville Riverside Golf Course'),
  ('United States', 'Clio Country Club'),
  ('United States', 'Clipper Galleon At Shipyard Golf Club'),
  ('United States', 'Clive Clark Course At Hideaway Club'),
  ('United States', 'Cloquet Country Club'),
  ('United States', 'Cloud 9 At Angel Park Golf Club'),
  ('United States', 'Clover Hill Golf Course'),
  ('United States', 'Clover Meadows Golf Course'),
  ('United States', 'Clovercrest Golf Course'),
  ('United States', 'Cloverleaf Golf Course'),
  ('United States', 'Clovernook Country Club'),
  ('United States', 'Club Adena'),
  ('United States', 'Club At Hidden Creek The'),
  ('United States', 'Club At Polo Club The'),
  ('United States', 'Club At River Oaks'),
  ('United States', 'Club At Shoal Creek'),
  ('United States', 'Club Campestre De Cananea'),
  ('United States', 'Club Campestre De Tijuana'),
  ('United States', 'Club Campestre Mexicali'),
  ('United States', 'Club De Golf Baie Missisquoi'),
  ('United States', 'Club De Golf Chateau Bromont'),
  ('United States', 'Club De Golf Coaticook'),
  ('United States', 'Club De Golf De Cowansville'),
  ('United States', 'Club De Golf De Knowlton'),
  ('United States', 'Club De Golf De La Vallee Du Temiscouata'),
  ('United States', 'Club De Golf De Napierville'),
  ('United States', 'Club De Golf Dufferin Heights'),
  ('United States', 'Club De Golf International 2000 America Saint Bernard'),
  ('United States', 'Club De Golf International 2000 Champlain America'),
  ('United States', 'Club De Golf International 2000 Saint Bernard Champlain'),
  ('United States', 'Club De Golf Inverness'),
  ('United States', 'Club De Golf Lac Brome'),
  ('United States', 'Club De Golf Lac Megantic'),
  ('United States', 'Club De Golf Milby'),
  ('United States', 'Club De Golf North Hatley'),
  ('United States', 'Club De Golf Ormstown'),
  ('United States', 'Club De Golf St Anicet Port Lewis'),
  ('United States', 'Club De Golf St Anicet St Anicet'),
  ('United States', 'Club De Golf Trout River'),
  ('United States', 'Club De Golf Venise Le Deauville'),
  ('United States', 'Club De Golf Venise Le Venise'),
  ('United States', 'Club De Golf Waterville'),
  ('United States', 'Club Green Meadows'),
  ('United States', 'Club Med Sandpiper Bay'),
  ('United States', 'Club Tucker Golf Course'),
  ('United States', 'Cnc Links'),
  ('United States', 'Coachmans Golf Resort'),
  ('United States', 'Coahoma Country Club'),
  ('United States', 'Coakley Russo Memorial Golf Course'),
  ('United States', 'Coal Creek Golf Course'),
  ('United States', 'Coashaukee At Balsams Grand Resort Hotel The'),
  ('United States', 'Coatesville Country Club'),
  ('United States', 'Cobble Hill Golf Course'),
  ('United States', 'Cobblestone Creek Country Club'),
  ('United States', 'Cobblestone Creek Golf Club'),
  ('United States', 'Cobblestone Golf Course'),
  ('United States', 'Cobblestone Park Golf Club Black Course'),
  ('United States', 'Cobblestone Park Golf Club Garnet Course'),
  ('United States', 'Cobblestone Park Golf Club Gold Course'),
  ('United States', 'Cobbossee Colony Golf'),
  ('United States', 'Cobbs Glen Country Club'),
  ('United States', 'Cobleskill Golf Country Club'),
  ('United States', 'Cobre Valle Country Club'),
  ('United States', 'Cochecho Country Club'),
  ('United States', 'Cochise Course At Desert Mountain Golf Club'),
  ('United States', 'Cochiti Golf Club'),
  ('United States', 'Cocopah Bend Rv Golf Resort'),
  ('United States', 'Cocopah Rio Colorado Golf Course'),
  ('United States', 'Coeur Dalene Golf Club'),
  ('United States', 'Coeur Dalene Resort Golf Course'),
  ('United States', 'Coffee Mill Country Club'),
  ('United States', 'Coffeyville Country Club'),
  ('United States', 'Coffin Golf Course'),
  ('United States', 'Cog Hill Golf & Country Club'),
  ('United States', 'Coharie Country Club'),
  ('United States', 'Cohasse Country Club'),
  ('United States', 'Cohasset Golf Club'),
  ('United States', 'Cokesbury Hills Golf Club'),
  ('United States', 'Colbert Hills'),
  ('United States', 'Colbert Hills Par 3'),
  ('United States', 'Cold Brook Golf Rv Resort'),
  ('United States', 'Cold Spring Country Club'),
  ('United States', 'Cold Springs Golf Country Club'),
  ('United States', 'Cold Springs Golf Course'),
  ('United States', 'Cold Water Canyon Golf Course'),
  ('United States', 'Coldstream Country Club'),
  ('United States', 'Coldwater Country Club'),
  ('United States', 'Coldwater Golf Club'),
  ('United States', 'Coldwater Golf Course'),
  ('United States', 'Coldwater Golf Links'),
  ('United States', 'Cole Acres Golf Course'),
  ('United States', 'Colebrook Country Club'),
  ('United States', 'Colfax Golf Club'),
  ('United States', 'Colin Creek Golf Club'),
  ('United States', 'Colina Park Golf Course'),
  ('United States', 'College Fields Golf Club'),
  ('United States', 'College Hill Golf Course'),
  ('United States', 'College Park Municipal Golf Course'),
  ('United States', 'Collegiate Peaks Golf Course'),
  ('United States', 'Colliers Reserve Country Club'),
  ('United States', 'Collindale Golf Course'),
  ('United States', 'Collins Hill Golf Club'),
  ('United States', 'Collison Par 3 Golf Course'),
  ('United States', 'Colockum Ridge Golf Course'),
  ('United States', 'Colonia Country Club'),
  ('United States', 'Colonial Acres Golf Course'),
  ('United States', 'Colonial Charters Golf Club'),
  ('United States', 'Colonial Country Club'),
  ('United States', 'Colonial Golf Course'),
  ('United States', 'Colonial Golf Tennis Club'),
  ('United States', 'Colonial Golfers Club'),
  ('United States', 'Colonial Heritage 9 Course'),
  ('United States', 'Colonial Heritage Club'),
  ('United States', 'Colonial Hills Golf Club'),
  ('United States', 'Colonial Oaks Golf Club'),
  ('United States', 'Colonial Park Golf Course'),
  ('United States', 'Colonial Ridge Golf'),
  ('United States', 'Colonie Country Club'),
  ('United States', 'Colonnade Golf And Country Club'),
  ('United States', 'Colorado Golf Club'),
  ('United States', 'Colorado Golf Club 9 Hole Course'),
  ('United States', 'Colorado National Golf Club'),
  ('United States', 'Colorado Springs Country Club'),
  ('United States', 'Colton Golf Club'),
  ('United States', 'Colts Neck Golf Club'),
  ('United States', 'Columbia Country Club'),
  ('United States', 'Columbia Country Club Ridgewood Lakeside'),
  ('United States', 'Columbia Country Club Ridgewood Tall Pines'),
  ('United States', 'Columbia Country Club Tall Pines Lakeside'),
  ('United States', 'Columbia Edgewater Country Club Macan Course'),
  ('United States', 'Columbia Edgewater Country Club Par 3 Mason Course'),
  ('United States', 'Columbia Golf Club'),
  ('United States', 'Columbia Golf Country Club'),
  ('United States', 'Columbia Golf Course'),
  ('United States', 'Columbia Hills Golf and Swim Club'),
  ('United States', 'Columbia Park Golf Links'),
  ('United States', 'Columbia Point Golf Course'),
  ('United States', 'Columbine Country Club'),
  ('United States', 'Columbine Country Club Par 3 Golf Course'),
  ('United States', 'Columbus Country Club'),
  ('United States', 'Columbus Park Golf Course'),
  ('United States', 'Colusa Golf Country Club'),
  ('United States', 'Colwood Golf Center'),
  ('United States', 'Comanche Lake Golf Course'),
  ('United States', 'Comanche Nation Golf Course'),
  ('United States', 'Commonground Golf Course'),
  ('United States', 'Commonground Golf Course Junior Par 3 Course'),
  ('United States', 'Commonwealth National Golf Club'),
  ('United States', 'Community Golf Course'),
  ('United States', 'Como Park Golf Course'),
  ('United States', 'Compass Pointe Golf Course'),
  ('United States', 'Compton Par 3 Golf Course'),
  ('United States', 'Comstock River At Empire Ranch Golf Course'),
  ('United States', 'Conchas Dam Park Golf Course'),
  ('United States', 'Concord Country Club'),
  ('United States', 'Concord Crest Golf Course'),
  ('United States', 'Concord Golf Club'),
  ('United States', 'Concord Hills Golf Course'),
  ('United States', 'Concordia Golf Club'),
  ('United States', 'Concordia Golf Wellness'),
  ('United States', 'Conestoga Country Club'),
  ('United States', 'Conestoga Golf Club'),
  ('United States', 'Conesus Golf Club'),
  ('United States', 'Conewango Valley Country Club'),
  ('United States', 'Congaree Golf Club'),
  ('United States', 'Congress Lake Golf Club'),
  ('United States', 'Conklin Players Club'),
  ('United States', 'Conley Resort'),
  ('United States', 'Connecticut Golf Club'),
  ('United States', 'Connecticut National Golf Club'),
  ('United States', 'Connestee Falls Golf Course'),
  ('United States', 'Connoquenessing Country Club'),
  ('United States', 'Conocodell Golf Club'),
  ('United States', 'Conquistador Golf Course'),
  ('United States', 'Conrad Golf Course'),
  ('United States', 'Continental Country Club'),
  ('United States', 'Continental Golf Course'),
  ('United States', 'Contra Costa Country Club'),
  ('United States', 'Contraband Bayou Golf Club At Lauberge Du Lac'),
  ('United States', 'Conway Country Club'),
  ('United States', 'Conway Farms Golf Club'),
  ('United States', 'Cool Creek Country Club'),
  ('United States', 'Cool Springs Golf Course'),
  ('United States', 'Coon Rapids Country Club'),
  ('United States', 'Cooper Colony Country Club'),
  ('United States', 'Coopers Hawk Golf Course'),
  ('United States', 'Coosa Country Club'),
  ('United States', 'Coosaw Creek Country Club'),
  ('United States', 'Copake Country Club'),
  ('United States', 'Copley Country Club'),
  ('United States', 'Copper Basin Golf Club'),
  ('United States', 'Copper Canyon Golf Club Lake Mountain Course'),
  ('United States', 'Copper Canyon Golf Club Mountain Vista Course'),
  ('United States', 'Copper Canyon Golf Club Vista Lake Course'),
  ('United States', 'Copper Creek Golf Club'),
  ('United States', 'Copper Creek Golf Course'),
  ('United States', 'Copper Golf Club'),
  ('United States', 'Copper Hill Country Club'),
  ('United States', 'Copper Hill Golf Club'),
  ('United States', 'Copper Hills Golf and Country Club'),
  ('United States', 'Copper Mill Golf Club'),
  ('United States', 'Copper Ridge Golf Club'),
  ('United States', 'Copper River Country Club'),
  ('United States', 'Copper Rock Golf Course'),
  ('United States', 'Copperleaf Golf Club'),
  ('United States', 'Coral Canyon Golf Course'),
  ('United States', 'Coral Creek Club'),
  ('United States', 'Coral Creek Golf Course'),
  ('United States', 'Coral Oaks Golf Course'),
  ('United States', 'Coral Ridge Country Club'),
  ('United States', 'Coral Ridge Country Club Rees 9'),
  ('United States', 'Corbin Hills Golf Course'),
  ('United States', 'Cordevalle Golf Club'),
  ('United States', 'Cordova Bay Golf Course'),
  ('United States', 'Cordova Bay Golf Course Ridge'),
  ('United States', 'Cordova Golf Course'),
  ('United States', 'Corey Creek Golf Club'),
  ('United States', 'Corica Park South Course'),
  ('United States', 'Corica Park The Earl Fry North Course'),
  ('United States', 'Corica Park The Mif Albright Par 3 Course'),
  ('United States', 'Cornerstone Club'),
  ('United States', 'Corning Country Club'),
  ('United States', 'Cornwall Golf And Country Club'),
  ('United States', 'Coronach Golf Club'),
  ('United States', 'Coronado Country Club'),
  ('United States', 'Coronado Golf Course'),
  ('United States', 'Corral De Tierra Country Club'),
  ('United States', 'Correctionville Golf Club'),
  ('United States', 'Corry Country Club'),
  ('United States', 'Corte Bella Golf Club'),
  ('United States', 'Cortez Golf Course'),
  ('United States', 'Cortland Country Club'),
  ('United States', 'Corunna Hills Golf Course'),
  ('United States', 'Corydon Municipal Golf Course'),
  ('United States', 'Costa Del Sol Golf Club'),
  ('United States', 'Cotton Creek At The Craft Farms Resort'),
  ('United States', 'Cotton Dike At Dataw Island Golf Course'),
  ('United States', 'Cottonwood At Torrington Golf Course'),
  ('United States', 'Cottonwood Country Club'),
  ('United States', 'Cottonwood Falls Country Club'),
  ('United States', 'Cottonwood Golf Club'),
  ('United States', 'Cottonwood Golf Club Ivanhoe Course'),
  ('United States', 'Cottonwood Golf Course'),
  ('United States', 'Cottonwood Hills Golf Club'),
  ('United States', 'Cottonwood Hills Golf Club Championship Course'),
  ('United States', 'Cottonwood Hills Golf Club Executive Par 3 Course'),
  ('United States', 'Cottonwood Links'),
  ('United States', 'Cottonwood Silo At West Woods Golf Club'),
  ('United States', 'Cotuit Highground Country Club'),
  ('United States', 'Coudersport Golf Club'),
  ('United States', 'Cougar Point At Kiawah Island Golf Resort'),
  ('United States', 'Coulee Golf Bowl'),
  ('United States', 'Council Bluffs Country Club'),
  ('United States', 'Council Fire Golf Club'),
  ('United States', 'Council Grove Country Club'),
  ('United States', 'Council Mountain Golf Course'),
  ('United States', 'Country Club At Boca Raton Resort Club The'),
  ('United States', 'Country Club At Castle Pines'),
  ('United States', 'Country Club At Pleasantville The'),
  ('United States', 'Country Club Estates Golf Course'),
  ('United States', 'Country Club Of Alabama'),
  ('United States', 'Country Club Of Asheville The'),
  ('United States', 'Country Club Of Barre'),
  ('United States', 'Country Club Of Billerica'),
  ('United States', 'Country Club Of Buffalo'),
  ('United States', 'Country Club Of Canton'),
  ('United States', 'Country Club Of Charleston'),
  ('United States', 'Country Club Of Columbus'),
  ('United States', 'Country Club Of Coral Springs'),
  ('United States', 'Country Club Of Culpeper'),
  ('United States', 'Country Club Of Darien'),
  ('United States', 'Country Club Of Fairfax'),
  ('United States', 'Country Club Of Fairfield'),
  ('United States', 'Country Club Of Farmington'),
  ('United States', 'Country Club Of Florida'),
  ('United States', 'Country Club Of Green Valley'),
  ('United States', 'Country Club Of Gwinnett'),
  ('United States', 'Country Club Of Halifax'),
  ('United States', 'Country Club Of Harrisburg'),
  ('United States', 'Country Club Of Hilton Head'),
  ('United States', 'Country Club Of Ithaca The'),
  ('United States', 'Country Club Of Jackson Azalea Course'),
  ('United States', 'Country Club Of Jackson Cypress Course'),
  ('United States', 'Country Club Of Jackson Dogwood Course'),
  ('United States', 'Country Club Of Johnston County'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Marsh Pines'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Ocean Marsh'),
  ('United States', 'Country Club Of Landfall Nicklaus Course Pines Ocean'),
  ('United States', 'Country Club Of Landfall Pete Dye Course'),
  ('United States', 'Country Club Of Leawood'),
  ('United States', 'Country Club Of Little Rock'),
  ('United States', 'Country Club Of Miami East'),
  ('United States', 'Country Club Of Miami West'),
  ('United States', 'Country Club Of Naples'),
  ('United States', 'Country Club Of New Bedford'),
  ('United States', 'Country Club Of New Canaan'),
  ('United States', 'Country Club Of New Hampshire'),
  ('United States', 'Country Club Of Newberry'),
  ('United States', 'Country Club Of Ocala'),
  ('United States', 'Country Club Of Orangeburg'),
  ('United States', 'Country Club Of Pittsfield'),
  ('United States', 'Country Club Of Rochester'),
  ('United States', 'Country Club Of Roswell'),
  ('United States', 'Country Club Of Salisbury'),
  ('United States', 'Country Club Of Sebring'),
  ('United States', 'Country Club Of Silver Springs Shores'),
  ('United States', 'Country Club Of The Rockies'),
  ('United States', 'Country Club Of The South'),
  ('United States', 'Country Club Of Vermont'),
  ('United States', 'Country Club Of Waterbury'),
  ('United States', 'Country Club Of Whispering Pines Pines Course'),
  ('United States', 'Country Club Of Whispering Pines River Course'),
  ('United States', 'Country Club Of Wilbraham'),
  ('United States', 'Country Club Of Winter Haven'),
  ('United States', 'Country Club Of York'),
  ('United States', 'Country Club of Beloit'),
  ('United States', 'Country Club of Decatur')
on conflict (country, name) do nothing;