insert into public.golf_courses (country, name) values
  ('United States', 'Betmar Acres Golf Club White Course'),
  ('United States', 'Betsie Valley'),
  ('United States', 'Better Shots Driving Range'),
  ('United States', 'Beverly Country Club'),
  ('United States', 'Beverly Golf Tennis Club'),
  ('United States', 'Bey Lea Municipal Golf Course'),
  ('United States', 'Biddeford Saco Country Club'),
  ('United States', 'Bidermann Golf Club'),
  ('United States', 'Bidwell Park Golf Course'),
  ('United States', 'Big Al''s Greens & Grille'),
  ('United States', 'Big Beaver Creek Golf Club'),
  ('United States', 'Big Bend Golf Country Club'),
  ('United States', 'Big Canyon Country Club'),
  ('United States', 'Big Creek Country Club'),
  ('United States', 'Big Creek Golf Course'),
  ('United States', 'Big Easy Ranch 9 Hole Course'),
  ('United States', 'Big Fish Golf Course'),
  ('United States', 'Big Foot Country Club'),
  ('United States', 'Big Lake Country Club'),
  ('United States', 'Big Met Golf Course'),
  ('United States', 'Big Oak Public Golf Course'),
  ('United States', 'Big Oaks Golf Course'),
  ('United States', 'Big River Golf Course'),
  ('United States', 'Big Rock Country Club'),
  ('United States', 'Big Run Golf Club'),
  ('United States', 'Big Sand Lake Club Golf Course'),
  ('United States', 'Big Sky Resort Golf Course'),
  ('United States', 'Big Spring Country Club'),
  ('United States', 'Big Stone Golf Course'),
  ('United States', 'Big Sugar Golf Club'),
  ('United States', 'Big Walnut Golf Course'),
  ('United States', 'Bigfoot Golf Country Club'),
  ('United States', 'Bigwood Golf Course'),
  ('United States', 'Bijou Municipal Golf Course'),
  ('United States', 'Bill Flynns Windham Country Club'),
  ('United States', 'Bill Roberts Municipal Golf Course'),
  ('United States', 'Billy Caldwell Golf Course'),
  ('United States', 'Biltmore Country Club'),
  ('United States', 'Biltmore Forest Country Club'),
  ('United States', 'Binder Park Golf Course'),
  ('United States', 'Binghamton Country Club'),
  ('United States', 'Birch Bay Village Golf Course'),
  ('United States', 'Birch Cedar At Mccall Golf Course'),
  ('United States', 'Birch Creek Golf Club'),
  ('United States', 'Birch Hill Country Club'),
  ('United States', 'Birch Hills Golf Course'),
  ('United States', 'Birch Pointe Golf Club'),
  ('United States', 'Birch Ridge Golf Course'),
  ('United States', 'Birch Run Golf Club'),
  ('United States', 'Birch Run Golf Course'),
  ('United States', 'Birch Tree Golf Course'),
  ('United States', 'Birch Valley Golf Course'),
  ('United States', 'Birchbank Golf Course'),
  ('United States', 'Birchwood At Spring Lake Golf Club'),
  ('United States', 'Birchwood Country Club'),
  ('United States', 'Birchwood Farms Golf & Country Club'),
  ('United States', 'Birchwood Golf Course'),
  ('United States', 'Bird City Golf Course'),
  ('United States', 'Bird Creek Golf Club'),
  ('United States', 'Bird Homestead Golf Course'),
  ('United States', 'Birdie Ranch At Silver Creek'),
  ('United States', 'Birdsfoot Golf Club'),
  ('United States', 'Birdwood Golf Course'),
  ('United States', 'Birdwood Golf Course Par 3'),
  ('United States', 'Birkdale Golf Club'),
  ('United States', 'Birmingham Country Club'),
  ('United States', 'Birnam Wood Golf Club'),
  ('United States', 'Birnamwood Golf Course'),
  ('United States', 'Bishop Country Club'),
  ('United States', 'Bishops Bay Golf Course'),
  ('United States', 'Bishops Gate Golf And Lakeside Community'),
  ('United States', 'Bison Golf Club'),
  ('United States', 'Bitter Creek At Willowcreek Golf Club'),
  ('United States', 'Bittersweet Golf Club'),
  ('United States', 'Bixby Village Golf Course'),
  ('United States', 'Black At Bethpage State Park Golf Course'),
  ('United States', 'Black At D Fairchild Wheeler Golf Course'),
  ('United States', 'Black Bear Golf Club'),
  ('United States', 'Black Bear Golf Course'),
  ('United States', 'Black Birch Golf Club'),
  ('United States', 'Black Brook Golf Club'),
  ('United States', 'Black Bull Golf Club'),
  ('United States', 'Black Canyon Golf Course'),
  ('United States', 'Black Creek Club'),
  ('United States', 'Black Creek Golf Club'),
  ('United States', 'Black Creek Golf Course'),
  ('United States', 'Black Desert Resort'),
  ('United States', 'Black Diamond Golf Course'),
  ('United States', 'Black Forest at Wilderness Valley'),
  ('United States', 'Black Gold Golf Club'),
  ('United States', 'Black Hall Club'),
  ('United States', 'Black Hawk Run Golf Club'),
  ('United States', 'Black Horse At Bayonet Black Horse Golf Course'),
  ('United States', 'Black Horse Golf And Learning Center'),
  ('United States', 'Black Lake Golf Course'),
  ('United States', 'Black Locust Disc Golf Course'),
  ('United States', 'Black Mesa Golf Club'),
  ('United States', 'Black Mountain Golf Course'),
  ('United States', 'Black Oak Golf Club'),
  ('United States', 'Black Oak Golf Course'),
  ('United States', 'Black River Golf Club'),
  ('United States', 'Black River Golf Course'),
  ('United States', 'Black Rock Country Club'),
  ('United States', 'Black Rock Creek Golf Club'),
  ('United States', 'Black Rock Golf Course'),
  ('United States', 'Black Sheep Golf Club'),
  ('United States', 'Black Squirrel Golf Club'),
  ('United States', 'Black Stone Creek Golf Club'),
  ('United States', 'Black Swan Country Club'),
  ('United States', 'Black Wolf Links'),
  ('United States', 'Blackberry Farm Golf Course'),
  ('United States', 'Blackberry Oaks Golf Course'),
  ('United States', 'Blackberry Ridge'),
  ('United States', 'Blackberry Trails Golf Course'),
  ('United States', 'Blackduck Municipal Golf Course'),
  ('United States', 'Blackfoot Municipal Golf Course'),
  ('United States', 'Blackford Golf Club'),
  ('United States', 'Blackhawk Country Club'),
  ('United States', 'Blackhawk Golf Course'),
  ('United States', 'Blackhead Mountain Lodge Country Club'),
  ('United States', 'Blackheath Golf Club'),
  ('United States', 'Blackledge Country Club Andersons Glen'),
  ('United States', 'Blackledge Country Club Gilead Highlands'),
  ('United States', 'Blacklick Woods Golf Course'),
  ('United States', 'Blackmer Municipal Golf Course'),
  ('United States', 'Blackmoor Golf Club'),
  ('United States', 'Blackmount Country Club'),
  ('United States', 'Blacksburg Country Club'),
  ('United States', 'Blackshire'),
  ('United States', 'Blackstone Country Club'),
  ('United States', 'Blackstone Golf Club'),
  ('United States', 'Blackstone Golf Course'),
  ('United States', 'Blackstone National Golf Club'),
  ('United States', 'Blackthorn Golf Club'),
  ('United States', 'Blackwell Municipal Golf Course'),
  ('United States', 'Blackwolf Run'),
  ('United States', 'Blackwood Golf Course'),
  ('United States', 'Blair Academy Golf Course'),
  ('United States', 'Blair Park Golf Course'),
  ('United States', 'Blakely Town Country Club'),
  ('United States', 'Blank Park Golf Course'),
  ('United States', 'Blessings Golf Club'),
  ('United States', 'Blind Brook Club'),
  ('United States', 'Blink Bonnie Golf Links'),
  ('United States', 'Blissful Meadows Golf Club'),
  ('United States', 'Bloch Memorial Golf Course'),
  ('United States', 'Bloody Point Golf Course'),
  ('United States', 'Bloomfield Country Club'),
  ('United States', 'Bloomfield Hills Country Club'),
  ('United States', 'Blooming Prairie Country Club'),
  ('United States', 'Bloomingdale Golf Club'),
  ('United States', 'Bloomingdale Golfers Club'),
  ('United States', 'Bloomington Country Club'),
  ('United States', 'Blossom Trails Golf Club'),
  ('United States', 'Blowing Rock Country Club'),
  ('United States', 'Blue Ash Golf Course'),
  ('United States', 'Blue At Arrowhead Golf Course'),
  ('United States', 'Blue At Bethpage State Park Golf Course'),
  ('United States', 'Blue At Congressional Country Club'),
  ('United States', 'Blue At Eisenhower Golf Course'),
  ('United States', 'Blue At Eisenhower Park Golf Course'),
  ('United States', 'Blue At Ford Hill Country Club'),
  ('United States', 'Blue At Golf Club Of Avon'),
  ('United States', 'Blue At Penn State Golf Courses'),
  ('United States', 'Blue At Ringgold Golf Club'),
  ('United States', 'Blue Bell Country Club'),
  ('United States', 'Blue Boy West Golf Course'),
  ('United States', 'Blue Cypress Golf Club'),
  ('United States', 'Blue Cypress Golf Rv Resort'),
  ('United States', 'Blue Fox Run Golf Club Blue Nine'),
  ('United States', 'Blue Fox Run Golf Club Red Nine'),
  ('United States', 'Blue Fox Run Golf Club White Nine'),
  ('United States', 'Blue Gold At Lindenwood Golf Club'),
  ('United States', 'Blue Gold At Westchester Golf Country Club'),
  ('United States', 'Blue Grass Over Look At Old Westbury Golf Country Club'),
  ('United States', 'Blue Green At Sunken Meadow State Park Golf Course'),
  ('United States', 'Blue Green At Town Of Colonie Golf Course'),
  ('United States', 'Blue Heron Golf Club'),
  ('United States', 'Blue Heron Golf Course'),
  ('United States', 'Blue Heron Pines'),
  ('United States', 'Blue Heron Pines Golf Club'),
  ('United States', 'Blue Hill Country Club'),
  ('United States', 'Blue Hills Country Club'),
  ('United States', 'Blue Hills Golf Course'),
  ('United States', 'Blue Knob Golf Club'),
  ('United States', 'Blue Lakes Country Club'),
  ('United States', 'Blue Mound Golf & Country Club'),
  ('United States', 'Blue Mountain View Golf Course'),
  ('United States', 'Blue Red At Buck Hill Falls Golf Club'),
  ('United States', 'Blue Red At Foxfire Country Club'),
  ('United States', 'Blue Red At Glen Oaks Club'),
  ('United States', 'Blue Red At Highland Lakes Golf Course'),
  ('United States', 'Blue Red At Little Mill Country Club'),
  ('United States', 'Blue Red At Myakka Pines Golf Club'),
  ('United States', 'Blue Red At Shawnee Inn Golf Resort'),
  ('United States', 'Blue Red At Shenandoah Valley Golf Club'),
  ('United States', 'Blue Red At Valley Brook Country Club'),
  ('United States', 'Blue Red At Western Turnpike Golf Course'),
  ('United States', 'Blue Ridge At Blue Ridge Trail Golf Club'),
  ('United States', 'Blue Ridge Country Club'),
  ('United States', 'Blue Ridge Golf Club'),
  ('United States', 'Blue Ridge Shadows Golf Club'),
  ('United States', 'Blue Rock Golf Course'),
  ('United States', 'Blue Rock Springs Golf Course East'),
  ('United States', 'Blue Rock Springs Golf Course West'),
  ('United States', 'Blue Shamrock Golf Club'),
  ('United States', 'Blue Sky Golf Club'),
  ('United States', 'Blue Stone Golf Course'),
  ('United States', 'Blue Top Ridge'),
  ('United States', 'Blue White At Edgewood Country Club'),
  ('United States', 'Blue White At Sugar Mill Country Club'),
  ('United States', 'Blue White At Timber Point Country Club'),
  ('United States', 'Blue White At Woods Golf Course The'),
  ('United States', 'Blueberry Hill Golf Club'),
  ('United States', 'Blueberry Hills Golf Course'),
  ('United States', 'Blueberry Pines Golf Club'),
  ('United States', 'Blueberry Plantation Country Club'),
  ('United States', 'Bluefield Elks Country Club'),
  ('United States', 'Blues Creek Golf Club'),
  ('United States', 'Bluestone Country Club'),
  ('United States', 'Bluff Creek Golf Course'),
  ('United States', 'Bluff Point Golf Club Resort'),
  ('United States', 'Bluff Pointe Golf Course Learning Center'),
  ('United States', 'Bluff River At Del Rio Country Club'),
  ('United States', 'Bluffs Golf Course'),
  ('United States', 'Bluffton Golf Club'),
  ('United States', 'Blush Hill Country Club'),
  ('United States', 'Blythe Golf Course'),
  ('United States', 'Blythefield Country Club'),
  ('United States', 'Blytheville Country Club'),
  ('United States', 'Blytheville Municipal Golf Course'),
  ('United States', 'Bob Burns Golf'),
  ('United States', 'Bob O Link Golf Club'),
  ('United States', 'Bob Oconnor Golf Course At Schenley Park The First Tee Of Pittsburgh'),
  ('United States', 'Bob-O-Link Golf Course'),
  ('United States', 'Bobby Jones Golf Club Championship Course'),
  ('United States', 'Bobby Jones Golf Club John Hamilton Gillespie Course'),
  ('United States', 'Bobby Jones Golf Course The Azalea Nine'),
  ('United States', 'Bobby Jones Golf Course The Cupp Links'),
  ('United States', 'Bobby Jones Golf Course The Magnolia Nine'),
  ('United States', 'Bobby Nichols Golf Course'),
  ('United States', 'Bobcat At Forest Country Club The'),
  ('United States', 'Boca Delray Golf Country Club'),
  ('United States', 'Boca Dunes Golf Country Club'),
  ('United States', 'Boca Greens Country Club'),
  ('United States', 'Boca Grove Plantation Golf Course'),
  ('United States', 'Boca Lago Country Club East Course'),
  ('United States', 'Boca Lago Country Club South Course'),
  ('United States', 'Boca Lago Country Club West Course'),
  ('United States', 'Boca Pointe Country Club'),
  ('United States', 'Boca Rio Golf Club'),
  ('United States', 'Boca Royale Golf Country Club'),
  ('United States', 'Boca West Country Club Dye Iv'),
  ('United States', 'Boca West Country Club Fazio Ii'),
  ('United States', 'Boca West Country Club Palmer I'),
  ('United States', 'Boca West Country Club Palmer Iii'),
  ('United States', 'Bocaire Country Club'),
  ('United States', 'Boeuf River Country Club'),
  ('United States', 'Bogalusa Country Club'),
  ('United States', 'Bogart At The Villages Executive Golf Trail'),
  ('United States', 'Bogey Club The'),
  ('United States', 'Bogey Hills Country Club'),
  ('United States', 'Boiling Springs Golf Course'),
  ('United States', 'Boise Ranch Golf Course'),
  ('United States', 'Boissevain Golf Club'),
  ('United States', 'Bolingbrook Golf Club'),
  ('United States', 'Bomber''s Golf Course'),
  ('United States', 'Bon Air Country Club'),
  ('United States', 'Bon Homme Country Club'),
  ('United States', 'Bonaventure Golf Club'),
  ('United States', 'Bonavista State Park Golf Course'),
  ('United States', 'Bonham Golf Country Club'),
  ('United States', 'Bonifay Country Club Destin Fort Walton'),
  ('United States', 'Bonifay Country Club Fort Walton Pensacola'),
  ('United States', 'Bonifay Country Club Pensacola Destin'),
  ('United States', 'Bonita Bay East Cypress Course'),
  ('United States', 'Bonita Bay East Sabal Course'),
  ('United States', 'Bonita Fairways'),
  ('United States', 'Bonita Golf Club'),
  ('United States', 'Bonita National Golf Country Club'),
  ('United States', 'Bonita Pass At The Villages Executive Golf Trail'),
  ('United States', 'Bonneville Golf Course'),
  ('United States', 'Bonnie Brae Golf Course'),
  ('United States', 'Bonnie Briar Country Club'),
  ('United States', 'Bonnie Brook Golf Course'),
  ('United States', 'Bonnie Brook Golf Range'),
  ('United States', 'Bonnie Dundee Golf Club'),
  ('United States', 'Bonnie View Golf Course'),
  ('United States', 'Bonniebrook Club House Golf Course'),
  ('United States', 'Bookcliff Country Club'),
  ('United States', 'Booker Country Club'),
  ('United States', 'Boomerang Links'),
  ('United States', 'Boone Creek Golf Course'),
  ('United States', 'Boone Golf Club'),
  ('United States', 'Boone Links Golf Course'),
  ('United States', 'Boone Valley Golf Club'),
  ('United States', 'Booneville Country Club'),
  ('United States', 'Boonsboro Country Club'),
  ('United States', 'Boothbay Harbor Country Club'),
  ('United States', 'Bos Landen Golf Club'),
  ('United States', 'Boscobel Country Club'),
  ('United States', 'Boston Golf Club'),
  ('United States', 'Bostonia Country Club'),
  ('United States', 'Botten''s Green Acres'),
  ('United States', 'Bottom Bellemeade At Valdosta Country Club'),
  ('United States', 'Boughton Ridge Golf Course'),
  ('United States', 'Boulder At Towa Golf Resort'),
  ('United States', 'Boulder City Municipal Golf Course'),
  ('United States', 'Boulder Country Club Championship Course'),
  ('United States', 'Boulder Country Club Par 3 Course'),
  ('United States', 'Boulder Creek Golf Club'),
  ('United States', 'Boulder Creek Golf Club Coyote Run Eldorado Valley'),
  ('United States', 'Boulder Creek Golf Club Desert Hawk Coyote Run'),
  ('United States', 'Boulder Creek Golf Club Desert Hawk Eldorado Valley'),
  ('United States', 'Boulder Creek Golf Country Club'),
  ('United States', 'Boulder Creek Golf Course'),
  ('United States', 'Boulder Oaks Golf Club'),
  ('United States', 'Boulder Pointe Golf Club'),
  ('United States', 'Boulder Ridge Country Club'),
  ('United States', 'Boundary Oak Golf Course'),
  ('United States', 'Bountiful Ridge Golf Course'),
  ('United States', 'Bourne Golf Club'),
  ('United States', 'Boutetourt Golf Swim Club'),
  ('United States', 'Bow Creek Golf Course'),
  ('United States', 'Bowden Golf Course'),
  ('United States', 'Bowdon Golf Club'),
  ('United States', 'Bowes Creek Country Club'),
  ('United States', 'Bowler''s Country Club'),
  ('United States', 'Bowling Green Country Club'),
  ('United States', 'Bowling Green Golf Club'),
  ('United States', 'Brabender Southwoods Golf Course'),
  ('United States', 'Brackenridge Heights Golf Course'),
  ('United States', 'Bradenton Country Club'),
  ('United States', 'Bradford Country Club'),
  ('United States', 'Bradford Creek Golf Club'),
  ('United States', 'Bradford Golf Club'),
  ('United States', 'Bradshaw Ranch Golf Course'),
  ('United States', 'Brae Burn Country Club'),
  ('United States', 'Brae Burn Golf Country Club'),
  ('United States', 'Brae Burn Golf Course'),
  ('United States', 'Brae Loch Golf Course'),
  ('United States', 'Brae-Burn Golf Club'),
  ('United States', 'Braelinn Golf Club'),
  ('United States', 'Braemar Country Club'),
  ('United States', 'Braemar Golf Course'),
  ('United States', 'Brainerd Golf Course'),
  ('United States', 'Braintree Municipal Golf Course'),
  ('United States', 'Brambles'),
  ('United States', 'Brambleton Regional Park Golf Course'),
  ('United States', 'Bramblewood Country Club'),
  ('United States', 'Brandermill Country Club'),
  ('United States', 'Brandon Golf Course'),
  ('United States', 'Brandywine Bay Golf Club'),
  ('United States', 'Branson Bay Golf Course'),
  ('United States', 'Brantingham Golf Club'),
  ('United States', 'Brasstown Valley Resort'),
  ('United States', 'Brattleboro Country Club'),
  ('United States', 'Brays Island Plantation Golf Club'),
  ('United States', 'Brazells Creek Golf Course'),
  ('United States', 'Brea Creek Golf Course'),
  ('United States', 'Breakfast Hill Golf Club'),
  ('United States', 'Breaking Bad Golf'),
  ('United States', 'Breckenridge Golf Tennis Club'),
  ('United States', 'Breckinridge County Community Center'),
  ('United States', 'Breckinridge Golf Course'),
  ('United States', 'Breda Golf Club'),
  ('United States', 'Breezewood Golf Links'),
  ('United States', 'Brent Bruehl Memorial Golf Course'),
  ('United States', 'Brentwood Country Club'),
  ('United States', 'Brentwood Farms Golf Club'),
  ('United States', 'Brentwood Golf Club Creekside Diablo Course'),
  ('United States', 'Brentwood Golf Club Creekside Hillside Course'),
  ('United States', 'Brentwood Golf Club Hillside Diablo Course'),
  ('United States', 'Brentwood Golf Club and Banquet Center'),
  ('United States', 'Breton Bay Golf Country Club'),
  ('United States', 'Bretton Woods Country Club'),
  ('United States', 'Bretton Woods Golf Course'),
  ('United States', 'Brevofield Golf Course'),
  ('United States', 'Briar Bay Golf Course'),
  ('United States', 'Briar Creek Country Club'),
  ('United States', 'Briar Creek Golf Course'),
  ('United States', 'Briar Leaf Golf Club'),
  ('United States', 'Briar Ridge Golf Course'),
  ('United States', 'Briarbrook Golf Course'),
  ('United States', 'Briardale Greens Golf Course'),
  ('United States', 'Briarwood At The Villages Executive Golf Trail'),
  ('United States', 'Briarwood Club of Ankeny'),
  ('United States', 'Briarwood Country Club'),
  ('United States', 'Briarwood Country Club At Sun City West'),
  ('United States', 'Briarwood Country Club The'),
  ('United States', 'Briarwood Golf Club'),
  ('United States', 'Briarwood Golf Club Final Five Course'),
  ('United States', 'Brickshire Golf Club'),
  ('United States', 'Brickyard At Riverside'),
  ('United States', 'Brickyard Crossing Golf Course'),
  ('United States', 'Bridge Golf Course'),
  ('United States', 'Bridge Street Golf At Snipes'),
  ('United States', 'Bridgemill Athletic Club'),
  ('United States', 'Bridger Creek Golf Course'),
  ('United States', 'Bridger Mountain Golf Course')
on conflict (country, name) do nothing;