insert into public.golf_courses (country, name) values
  ('United States', 'Wheatland Golf Club'),
  ('United States', 'Wheatley Hills Golf Club'),
  ('United States', 'Wheeler Family Traditions Golf Club'),
  ('United States', 'Wheeling Country Club'),
  ('United States', 'Wheeling Country Club Golf Course'),
  ('United States', 'Wheeling Park Golf Course'),
  ('United States', 'Wheeling Park Minature Golf'),
  ('United States', 'Whidbey Golf Club'),
  ('United States', 'Whip Poor Will Golf Course'),
  ('United States', 'Whippoorwill Club'),
  ('United States', 'Whirlpool Golf Course'),
  ('United States', 'Whirlwind Golf Club The Cattail Course'),
  ('United States', 'Whirlwind Golf Club The Devils Claw Course'),
  ('United States', 'Whiskey Creek Country Club'),
  ('United States', 'Whisky Run Golf Club Fox'),
  ('United States', 'Whisper Creek Country Club'),
  ('United States', 'Whisper Lake Country Club'),
  ('United States', 'Whisper Rock Golf Club Lower Course'),
  ('United States', 'Whisper Rock Golf Club Upper Course'),
  ('United States', 'Whispering Creek Golf Club'),
  ('United States', 'Whispering Creek Golf Course'),
  ('United States', 'Whispering Firs Golf Club'),
  ('United States', 'Whispering Hills Golf Course'),
  ('United States', 'Whispering Lakes Golf Course'),
  ('United States', 'Whispering Meadows Golf Course'),
  ('United States', 'Whispering Oak At Verandah'),
  ('United States', 'Whispering Oaks Golf Club'),
  ('United States', 'Whispering Pines Golf Club'),
  ('United States', 'Whispering Pines Golf Course'),
  ('United States', 'Whispering Springs Golf Club'),
  ('United States', 'Whispering Willows Golf Course'),
  ('United States', 'Whispering Winds Golf Club'),
  ('United States', 'Whispering Woods Golf Club'),
  ('United States', 'Whispering Woods Golf Course'),
  ('United States', 'Whistling Straits'),
  ('United States', 'White At Eisenhower Park Golf Course'),
  ('United States', 'White At Ford Hill Country Club'),
  ('United States', 'White At Golf Club Of Avon'),
  ('United States', 'White At Penn State Golf Courses'),
  ('United States', 'White At Tunxis Country Club'),
  ('United States', 'White Barn Estates'),
  ('United States', 'White Bear Yacht Club'),
  ('United States', 'White Beeches Golf Country Club'),
  ('United States', 'White Birch Golf Course'),
  ('United States', 'White Birch Hills Golf Course'),
  ('United States', 'White Birches Country Club'),
  ('United States', 'White Blue At Buck Hill Falls Golf Club'),
  ('United States', 'White Blue At Glen Oaks Club'),
  ('United States', 'White Blue At Highland Lakes Golf Course'),
  ('United States', 'White Blue At Little Mill Country Club'),
  ('United States', 'White Blue At Myakka Pines Golf Club'),
  ('United States', 'White Blue At Ramblewood Country Club'),
  ('United States', 'White Blue At Shawnee Inn Golf Resort'),
  ('United States', 'White Blue At Shenandoah Valley Golf Club'),
  ('United States', 'White Blue At Town Of Colonie Golf Course'),
  ('United States', 'White Blue At Western Turnpike Golf Course'),
  ('United States', 'White Clay Creek Country Club At Delaware Park'),
  ('United States', 'White Cliffs Country Club'),
  ('United States', 'White Clouds At Sun Valley Resort'),
  ('United States', 'White Columns Golf Club'),
  ('United States', 'White Deer Country Club'),
  ('United States', 'White Deer Run Golf Club'),
  ('United States', 'White Eagle Golf Club'),
  ('United States', 'White Gold At Wyndemere Country Club'),
  ('United States', 'White Hawk Country Club'),
  ('United States', 'White Heron Golf Club'),
  ('United States', 'White Horse Golf Club'),
  ('United States', 'White Lake Golf Club'),
  ('United States', 'White Lake Oaks Golf Course'),
  ('United States', 'White Lick Golf Course'),
  ('United States', 'White Manor Country Club'),
  ('United States', 'White Mountain Country Club'),
  ('United States', 'White Mountain Golf Course Desert Nine'),
  ('United States', 'White Mountain Golf Course Lakes Nine'),
  ('United States', 'White Mountain Golf Course Sands Nine'),
  ('United States', 'White Mountain Golf Park'),
  ('United States', 'White Nine At Hyde Park Golf Course'),
  ('United States', 'White Oak Golf Course'),
  ('United States', 'White Oak Plantation'),
  ('United States', 'White Oaks Country Club'),
  ('United States', 'White Oaks Golf Club'),
  ('United States', 'White Path Golf Club'),
  ('United States', 'White Pine Golf Course'),
  ('United States', 'White Pine National'),
  ('United States', 'White Pines Country Club'),
  ('United States', 'White Pines Golf Club'),
  ('United States', 'White Pines Golf Course'),
  ('United States', 'White Plains Golf Club'),
  ('United States', 'White Plains Golf Course'),
  ('United States', 'White Red At Edgewood Country Club'),
  ('United States', 'White Red At Ramblewood Country Club'),
  ('United States', 'White Red At Sugar Mill Country Club'),
  ('United States', 'White Red At Timber Point Country Club'),
  ('United States', 'White Red At Willowbrook Golf Club'),
  ('United States', 'White River Golf Club'),
  ('United States', 'White Springs Golf Course'),
  ('United States', 'White Tail Golf Course'),
  ('United States', 'White Wing At Rio Verde Country Club'),
  ('United States', 'Whitebirch Golf Course'),
  ('United States', 'Whiteface Club'),
  ('United States', 'Whitefish Golf club'),
  ('United States', 'Whitefish Lake Golf Club'),
  ('United States', 'Whiteford Valley Golf Club'),
  ('United States', 'Whitehall Public Golf Course'),
  ('United States', 'Whitehawk Ranch Golf Club'),
  ('United States', 'Whitemarsh Valley Country Club'),
  ('United States', 'Whitetail Golf Club'),
  ('United States', 'Whitetail Golf Course'),
  ('United States', 'Whitetail Golf Resort'),
  ('United States', 'Whitetail Ridge Golf Course'),
  ('United States', 'Whitetail Run Golf Course'),
  ('United States', 'Whitewater Creek Country Club'),
  ('United States', 'Whitford Country Club'),
  ('United States', 'Whitinsville Golf Club'),
  ('United States', 'Whitmire Country Club'),
  ('United States', 'Whitmoor Country Club - North Course'),
  ('United States', 'Whitnall Park Golf Course'),
  ('United States', 'Whitney Oaks Golf Club'),
  ('United States', 'Whittaker Woods Golf Club'),
  ('United States', 'Whittier Mobile Country Club'),
  ('United States', 'Whittier Narrows Golf Course Mountain Course'),
  ('United States', 'Whittier Narrows Golf Course Mountain River'),
  ('United States', 'Whittier Narrows Golf Course Pine Mountain'),
  ('United States', 'Whittier Narrows Golf Course River Pine'),
  ('United States', 'Wianno Club'),
  ('United States', 'Wichita Country Club'),
  ('United States', 'Wichita County Municipal Golf Course'),
  ('United States', 'Wickenburg Country Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club'),
  ('United States', 'Wickenburg Ranch Golf Social Club Lil Wick'),
  ('United States', 'Wicker Hills Golf Club'),
  ('United States', 'Wicker Memorial Park Golf Course'),
  ('United States', 'Wicomico Shores Golf Course'),
  ('United States', 'Widows Walk Golf Course'),
  ('United States', 'Wigwam Resort Blue Course'),
  ('United States', 'Wigwam Resort Gold Course'),
  ('United States', 'Wigwam Resort Red Course'),
  ('United States', 'Wilcox Cove Cottages Golf'),
  ('United States', 'Wilcox Oaks Golf Club'),
  ('United States', 'Wild Bluff Golf Course'),
  ('United States', 'Wild Horse Plains Golf Course'),
  ('United States', 'Wild Marsh Golf Club'),
  ('United States', 'Wild Oak Golf Club'),
  ('United States', 'Wild Oaks Golf Course White Cedar Pin Oaks'),
  ('United States', 'Wild Oaks Golf Course White Cedar Willow Oaks'),
  ('United States', 'Wild Oaks Golf Course Willow Oaks Pin Oaks'),
  ('United States', 'Wild Quail Golf Country Club'),
  ('United States', 'Wild Ridge Golf Course'),
  ('United States', 'Wild Rock Golf Club at The Wilderness'),
  ('United States', 'Wild Turkey Golf Club'),
  ('United States', 'Wild Wing Plantation Avocet Course'),
  ('United States', 'Wild Wing Plantation Hummingbird Course'),
  ('United States', 'Wild Wings Golf Club'),
  ('United States', 'Wild Wood Country Club'),
  ('United States', 'Wildcat At Fort Jackson Golf Club'),
  ('United States', 'Wildcat Cliffs Country Club'),
  ('United States', 'Wildcat Creek Golf Course'),
  ('United States', 'Wildcat Crossing Golf Club'),
  ('United States', 'Wildcat Golf Course'),
  ('United States', 'Wildcat Run Country Club'),
  ('United States', 'Wildcreek Executive Golf Course'),
  ('United States', 'Wilderness Club'),
  ('United States', 'Wilderness Country Club'),
  ('United States', 'Wilderness Golf Course'),
  ('United States', 'Wilderness Valley'),
  ('United States', 'Wildfire Golf Club'),
  ('United States', 'Wildflower GC'),
  ('United States', 'Wildhawk Golf Club'),
  ('United States', 'Wildhorse Golf Club'),
  ('United States', 'Wildhorse Golf Course'),
  ('United States', 'Wildhorse Resort Golf Course'),
  ('United States', 'Wildwood Country Club'),
  ('United States', 'Wildwood Golf Club'),
  ('United States', 'Wildwood Golf Course'),
  ('United States', 'Wildwood Golf and RV Resort'),
  ('United States', 'Wildwood Green Golf Course'),
  ('United States', 'Wildwood Lake Golf Course'),
  ('United States', 'Wildwood Marshes Golf Course'),
  ('United States', 'Wildwood Mobile Country Club'),
  ('United States', 'Wilkes Barre Golf Club'),
  ('United States', 'Wilkshire Golf Course'),
  ('United States', 'Willandale Golf Club'),
  ('United States', 'Willapa Harbor Golf Course'),
  ('United States', 'Willard Golf Club'),
  ('United States', 'Willbrook Plantation Golf Club'),
  ('United States', 'William F Larkin Golf Course At Colonial Terrace'),
  ('United States', 'William J Devine Franklin Park Golf Course'),
  ('United States', 'William Land Park Municipal Golf Course'),
  ('United States', 'William S. Sahm Park Golf Course'),
  ('United States', 'Williams Country Club'),
  ('United States', 'Williams Country Club Golf Course'),
  ('United States', 'Williams Nine At Meadow Park Golf Course'),
  ('United States', 'Williamsburg Golf Club'),
  ('United States', 'Williamsburg National Golf Club Jamestown Course'),
  ('United States', 'Williamsburg National Golf Club Yorktown Course'),
  ('United States', 'Williamsport Country Club'),
  ('United States', 'Willingers Golf Club'),
  ('United States', 'Willis Case Golf Course'),
  ('United States', 'Williston Country Club'),
  ('United States', 'Williston Golf Club'),
  ('United States', 'Willoughby Golf Club'),
  ('United States', 'Willow Bend Country Club'),
  ('United States', 'Willow Brook Golf Course'),
  ('United States', 'Willow Creek Country Club'),
  ('United States', 'Willow Creek Golf'),
  ('United States', 'Willow Creek Golf Club At Eagle Vail'),
  ('United States', 'Willow Creek Golf Country Club'),
  ('United States', 'Willow Creek Golf Course'),
  ('United States', 'Willow Creek Municiple Golf Course'),
  ('United States', 'Willow Crest Golf Club'),
  ('United States', 'Willow Hills Golf Center'),
  ('United States', 'Willow Hollow Golf Course'),
  ('United States', 'Willow Lake Golf Club'),
  ('United States', 'Willow Lakes Golf Club'),
  ('United States', 'Willow Lakes Golf Course'),
  ('United States', 'Willow Oak At Hunters Creek Plantation'),
  ('United States', 'Willow Oaks Country Club'),
  ('United States', 'Willow Pond Golf Course'),
  ('United States', 'Willow Ridge Golf & Country Club'),
  ('United States', 'Willow Ridge Golf Club'),
  ('United States', 'Willow Ridge Golf Course'),
  ('United States', 'Willow Run Country Club'),
  ('United States', 'Willow Run Golf Club'),
  ('United States', 'Willow Run Golf Course'),
  ('United States', 'Willow Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Willow Springs Country Club'),
  ('United States', 'Willow Springs Golf Course'),
  ('United States', 'Willow Springs Golf and Country Club'),
  ('United States', 'Willow Tree Golf Course'),
  ('United States', 'Willow Vale Golf Club'),
  ('United States', 'Willow Valley Golf Course'),
  ('United States', 'Willow Wood Golf Course'),
  ('United States', 'Willowbend Country Club Bay Nine'),
  ('United States', 'Willowbend Country Club Bend Nine'),
  ('United States', 'Willowbend Country Club Bog Nine'),
  ('United States', 'Willowbend Golf Club'),
  ('United States', 'Willowbrook Country Club'),
  ('United States', 'Willowbrook Executive Golf Course At Willowcreek Golf Course'),
  ('United States', 'Willowbrook Golf Club'),
  ('United States', 'Willowbrook Golf Course'),
  ('United States', 'Willowbrook Golf Course The North Course'),
  ('United States', 'Willowbrook Golf Course The South Course'),
  ('United States', 'Willowbrook Golf Course The West Course'),
  ('United States', 'Willowcreek Golf Course'),
  ('United States', 'Willowdale Golf Club'),
  ('United States', 'Willowdale Golf Course'),
  ('United States', 'Willowhill Golf Course'),
  ('United States', 'Willowick Golf Course'),
  ('United States', 'Willows At Willowcreek Golf Club'),
  ('United States', 'Willows Run Golf Club Coyote Creek Course'),
  ('United States', 'Willows Run Golf Club Discovery Trails'),
  ('United States', 'Willows Run Golf Club Eagles Talon Course'),
  ('United States', 'Willows Run Golf Club Heron Links Course'),
  ('United States', 'Willsboro Golf Club'),
  ('United States', 'Wilmette Golf Club'),
  ('United States', 'Wilmington Municipal Golf Course'),
  ('United States', 'Wilmington Municipal Golf Course The First Tee Of Greater Wilmington'),
  ('United States', 'Wilshire Country Club'),
  ('United States', 'Wilshire Golf Club'),
  ('United States', 'Wilson At Griffith Park Golf Courses'),
  ('United States', 'Wilson Country Club'),
  ('United States', 'Wilson Lake Country Club'),
  ('United States', 'Wilson Road Golf Course'),
  ('United States', 'Wilsons Willow Run Executive Golf Course'),
  ('United States', 'Wiltwyck Golf Club'),
  ('United States', 'Winchester Country Club'),
  ('United States', 'Wind Watch Golf Country Club'),
  ('United States', 'Windance Country Club'),
  ('United States', 'Windber Country Club'),
  ('United States', 'Windermere Golf Club'),
  ('United States', 'Windham Country Club'),
  ('United States', 'Windham Golf Course'),
  ('United States', 'Winding Branch Golf Course'),
  ('United States', 'Winding Brook Country Club'),
  ('United States', 'Winding Creek Golf Club'),
  ('United States', 'Winding Creek Golf Course'),
  ('United States', 'Winding Hills Golf Club'),
  ('United States', 'Winding Ridge Gold Cub'),
  ('United States', 'Winding River Golf Course'),
  ('United States', 'Windmill At Indian Springs Country Club'),
  ('United States', 'Windmill Golf Center'),
  ('United States', 'Windmill Hill Golf Course'),
  ('United States', 'Windmill Lakes Golf Club'),
  ('United States', 'Windsong Farm Golf Club'),
  ('United States', 'Windsor At Walhalla'),
  ('United States', 'Windsor Club The'),
  ('United States', 'Windsor Golf Club'),
  ('United States', 'Windsor Parke Golf Club'),
  ('United States', 'Windstar On Naples Bay'),
  ('United States', 'Windstone Golf Country Club'),
  ('United States', 'Windswept Dunes Golf Course'),
  ('United States', 'Windwood Hollow Golf Course'),
  ('United States', 'Windwood of Watertown'),
  ('United States', 'Windy Acres Golf Course'),
  ('United States', 'Windy Harbor Golf Club'),
  ('United States', 'Windy Hill Country Club'),
  ('United States', 'Windy Hills Golf Course'),
  ('United States', 'Windy Knoll Golf Club'),
  ('United States', 'Windy Trails Golf Course At Altus Afb'),
  ('United States', 'Wine Valley Golf Course'),
  ('United States', 'Winfield Country Club'),
  ('United States', 'Wing Park Golf Course'),
  ('United States', 'Wing Point Golf Country Club'),
  ('United States', 'WingHaven Country Club'),
  ('United States', 'Winkler County Golf Course'),
  ('United States', 'Winkler Golf Club'),
  ('United States', 'Winn Mountain Golf Course'),
  ('United States', 'Winnapaug Country Club'),
  ('United States', 'Winnemucca Municipal Golf Course'),
  ('United States', 'Winnetka Golf Club'),
  ('United States', 'Winnfield Golf'),
  ('United States', 'Winona Country Club'),
  ('United States', 'Winstar Golf Course Redbud'),
  ('United States', 'Winstar Golf Course Scissortail'),
  ('United States', 'Winston Lake Golf Course'),
  ('United States', 'Winston Trails Golf Club'),
  ('United States', 'Winter Clove Inn Resort'),
  ('United States', 'Winter Creek Golf Country Club'),
  ('United States', 'Winter Park Golf Course'),
  ('United States', 'Winter Park Pines Golf Club'),
  ('United States', 'Winter Quarters Municipal Golf Course'),
  ('United States', 'Wintergreen Resort Devils Knob'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Shamokin'),
  ('United States', 'Wintergreen Resort Stoney Creek Monocan Tuckahoe'),
  ('United States', 'Wintergreen Resort Stoney Creek Shamokin Tuckahoe'),
  ('United States', 'Winthrop Golf Club'),
  ('United States', 'Winthrop University Golf Course'),
  ('United States', 'Winton Country Club'),
  ('United States', 'Wintonbury Hills Golf Course'),
  ('United States', 'Wisconsin Club'),
  ('United States', 'Wisconsin River Country Club'),
  ('United States', 'Wissahickon Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Witch Golf Club'),
  ('United States', 'Woburn Country Club'),
  ('United States', 'Wohali Country Club Eagle Course'),
  ('United States', 'Wolf At Las Vegas Paiute Golf Resort'),
  ('United States', 'Wolf Creek Golf Club'),
  ('United States', 'Wolf Creek Golf Country Club'),
  ('United States', 'Wolf Creek Golf Course'),
  ('United States', 'Wolf Creek Golf Resort'),
  ('United States', 'Wolf Hollow Golf Club'),
  ('United States', 'Wolf Hollow Golf Course At Copiah Lincoln College'),
  ('United States', 'Wolf Laurel Country Club'),
  ('United States', 'Wolf Ridge Golf Course'),
  ('United States', 'Wolf Run Golf Club'),
  ('United States', 'Wolf Run Golf Course'),
  ('United States', 'Wolfe Island Riverfront Golf Course'),
  ('United States', 'Wolferts Roost Golf Course'),
  ('United States', 'Wolfridge Golf Course'),
  ('United States', 'Wollaston Golf Club'),
  ('United States', 'Wolves Crossing Golf Course'),
  ('United States', 'Wood Creek Golf Links'),
  ('United States', 'Wood Ranch Golf Club'),
  ('United States', 'Wood River Golf Course'),
  ('United States', 'Wood Wind Golf Club'),
  ('United States', 'Woodberry Forest Golf Course'),
  ('United States', 'Woodbine At Mohawk Park Golf Course'),
  ('United States', 'Woodbine Bend Golf Course'),
  ('United States', 'Woodbridge Golf Links'),
  ('United States', 'Woodbrier Golf Course'),
  ('United States', 'Woodbury Golf Course'),
  ('United States', 'Woodcreek Golf Club'),
  ('United States', 'Woodcrest Country Club'),
  ('United States', 'Woodcrest Golf Club'),
  ('United States', 'Wooded View Golf Course'),
  ('United States', 'Woodfield Country Club'),
  ('United States', 'Woodfin Ridge Golf Club'),
  ('United States', 'Woodgate Pines Golf Club'),
  ('United States', 'Woodhaven Country Club'),
  ('United States', 'Woodhaven Golf Club'),
  ('United States', 'Woodhill Country Club'),
  ('United States', 'Woodlake Country Club'),
  ('United States', 'Woodlake Golf Club'),
  ('United States', 'Woodland Country Club'),
  ('United States', 'Woodland Golf Club'),
  ('United States', 'Woodland Golf Course'),
  ('United States', 'Woodland Hills Country Club'),
  ('United States', 'Woodland Hills Golf Club'),
  ('United States', 'Woodland Hills Golf Course'),
  ('United States', 'Woodland Lakeside At Blue Hill Golf Course'),
  ('United States', 'Woodland Ridge Golf Course'),
  ('United States', 'Woodlands Championship Golf Course'),
  ('United States', 'Woodlands Club'),
  ('United States', 'Woodlands Course'),
  ('United States', 'Woodlands Creekside At Traces Golf Club The'),
  ('United States', 'Woodlands Golf Course'),
  ('United States', 'Woodlands Meadows At Traces Golf Club The'),
  ('United States', 'Woodlawn Country Club'),
  ('United States', 'Woodlawn Golf Club'),
  ('United States', 'Woodley Lakes Golf Course'),
  ('United States', 'Woodloch Springs Country Club'),
  ('United States', 'Woodlyn Hills Golf Course'),
  ('United States', 'Woodlynn Hills Golf Course'),
  ('United States', 'Woodmere Country Club'),
  ('United States', 'Woodmont Golf Country Club'),
  ('United States', 'Woodridge Golf Club'),
  ('United States', 'Woodruff Golf Course'),
  ('United States', 'Woods At Boca Woods Country Club'),
  ('United States', 'Woods Blue Grass At Old Westbury Golf Country Club'),
  ('United States', 'Woods Edge Golf Course')
on conflict (country, name) do nothing;