insert into public.golf_courses (country, name) values
  ('United States', 'Dequeen Country Club'),
  ('United States', 'Derby Grange Golf & Recreation Center'),
  ('United States', 'Derrick''s Creek Golf Course at Edgewood Country Club'),
  ('United States', 'Derryfield Country Club'),
  ('United States', 'Des Moines Driving Range'),
  ('United States', 'Des Moines Golf & Country Club'),
  ('United States', 'Desert Aire Golf Course'),
  ('United States', 'Desert At Adobe Creek National Golf Course'),
  ('United States', 'Desert Canyon Golf Club'),
  ('United States', 'Desert Canyon Golf Course'),
  ('United States', 'Desert Canyon Golf Resort'),
  ('United States', 'Desert Crest Country Club'),
  ('United States', 'Desert Dunes Golf Course'),
  ('United States', 'Desert Falls Country Club'),
  ('United States', 'Desert Forest Golf Club'),
  ('United States', 'Desert Hawk At Pueblo West'),
  ('United States', 'Desert Highlands Golf Club'),
  ('United States', 'Desert Hills Golf Club'),
  ('United States', 'Desert Hills Golf Course'),
  ('United States', 'Desert Hills Par 3 Golf Course'),
  ('United States', 'Desert Horizons Country Club'),
  ('United States', 'Desert Island Country Club'),
  ('United States', 'Desert Lakes Golf Course'),
  ('United States', 'Desert Mirage Golf Course'),
  ('United States', 'Desert Pines Golf Club'),
  ('United States', 'Desert Sands Golf Course'),
  ('United States', 'Desert Springs Golf Club'),
  ('United States', 'Desert Springs Ranch Golf Course'),
  ('United States', 'Desert Trail Rv Resort Golf Course'),
  ('United States', 'Desert Trails Golf Course At Sun City West'),
  ('United States', 'Desert Willow Golf Course'),
  ('United States', 'Desert Winds Golf Course'),
  ('United States', 'Desoto Golf Course'),
  ('United States', 'Destroyer At Seal Beach Navy Golf Course'),
  ('United States', 'Detroit Country Club'),
  ('United States', 'Detroit Golf Club'),
  ('United States', 'Detwiler Golf Course'),
  ('United States', 'Devil''s Knob Golf Course'),
  ('United States', 'Devil''s Ridge Golf Club'),
  ('United States', 'Devils Head Resort Convention Center Glacier Course'),
  ('United States', 'Devils Lake Golf Course'),
  ('United States', 'Devils Ridge Golf Club'),
  ('United States', 'Devils Thumb Golf Club'),
  ('United States', 'Devou Golf & Event Center'),
  ('United States', 'Dexter Municipal Golf Club'),
  ('United States', 'Diablo Country Club'),
  ('United States', 'Diablo Creek Golf Course'),
  ('United States', 'Diablo Hills Golf Course'),
  ('United States', 'Diadema Golf Club'),
  ('United States', 'Diamante Country Club'),
  ('United States', 'Diamond Bar Golf Course'),
  ('United States', 'Diamond Creek'),
  ('United States', 'Diamond Dunes At Black Diamond Ranch Golf Country Club'),
  ('United States', 'Diamond Hawk Golf Course'),
  ('United States', 'Diamond Hill Golf Country Club'),
  ('United States', 'Diamond Hills Country Club'),
  ('United States', 'Diamond Lake Golf Club'),
  ('United States', 'Diamond Mountain Golf Club'),
  ('United States', 'Diamond Oaks Municipal Golf Course'),
  ('United States', 'Diamond Run Golf Club'),
  ('United States', 'Diamond Springs Golf Course'),
  ('United States', 'Diamond Trail Golf Club'),
  ('United States', 'Diamondback Golf Course'),
  ('United States', 'Diamondhead Golf Club'),
  ('United States', 'Dimmock Hill Golf Course'),
  ('United States', 'Dinah Shore Tournament At Mission Hills Country Club'),
  ('United States', 'Dinaland Golf Course'),
  ('United States', 'Dinosaur Mountain At Gold Canyon Golf Resort'),
  ('United States', 'Dinsmore Golf Course'),
  ('United States', 'Disc Golf'),
  ('United States', 'Disc Golf Course'),
  ('United States', 'Discovery Bay Country Club'),
  ('United States', 'Discovery Bay Golf Club'),
  ('United States', 'Disk Golf Course'),
  ('United States', 'Disneys Lake Buena Vista Golf Course'),
  ('United States', 'Disneys Magnolia Golf Course'),
  ('United States', 'Disneys Oak Trail Golf Course'),
  ('United States', 'Disneys Palm Golf Course'),
  ('United States', 'Ditches Waters At Brickyard Plantation Golf Club'),
  ('United States', 'Divide Ranch Club'),
  ('United States', 'Dix Hills Park Golf Course'),
  ('United States', 'Dixie Driving Range'),
  ('United States', 'Dixie Golf Club'),
  ('United States', 'Dixie Red Hills Golf Course'),
  ('United States', 'Djs Golf Center Par 3'),
  ('United States', 'Dobson Ranch Golf Course'),
  ('United States', 'Doby Springs Golf Course'),
  ('United States', 'Dodge City Country Club'),
  ('United States', 'Dodge Country Club'),
  ('United States', 'Dodge County Golf Club'),
  ('United States', 'Dodge Point Country Club'),
  ('United States', 'Dodge Riverside Golf Club'),
  ('United States', 'Doe Valley'),
  ('United States', 'Dogwood Golf Country Club'),
  ('United States', 'Dogwood Highland At Lancaster Country Club'),
  ('United States', 'Dogwood Hills'),
  ('United States', 'Dogwood Hills Golf Club'),
  ('United States', 'Dogwood Hills Golf Course'),
  ('United States', 'Dogwood Knolls Golf Course'),
  ('United States', 'Dogwood Lakes Golf Club'),
  ('United States', 'Dogwood Laurel At Houndslake Country Club'),
  ('United States', 'Dogwood Oak Tree At Middle Island Country Club'),
  ('United States', 'Dogwood Palmetto At Callawassie Island Club'),
  ('United States', 'Dogwood Redbud At Roanoke Country Club'),
  ('United States', 'Dogwood Trace Golf Course'),
  ('United States', 'Dogwood Valley Golf Course'),
  ('United States', 'Dolphin At Ocean Reef Club'),
  ('United States', 'Dolphin Head Golf Course'),
  ('United States', 'Domenicos Golf Course'),
  ('United States', 'Dominion Golf & Country Club'),
  ('United States', 'Dominion Meadows Golf Course'),
  ('United States', 'Dominion Valley Country Club'),
  ('United States', 'Don Knabe Golf Center Junior Academy'),
  ('United States', 'Don Williams Golf Course'),
  ('United States', 'Donald Ross Golf Club'),
  ('United States', 'Donald Ross Memorial'),
  ('United States', 'Donalsonville Country Club'),
  ('United States', 'Donegal Highlands Golf Course'),
  ('United States', 'Donnybrook Country Club'),
  ('United States', 'Donnybrook Golf Course'),
  ('United States', 'Door Creek Golf Course'),
  ('United States', 'Dorado Country Club'),
  ('United States', 'Dormie Club'),
  ('United States', 'Dornick Hills Golf Country Club'),
  ('United States', 'Dorset Field Club'),
  ('United States', 'Dos Lagos Golf Club'),
  ('United States', 'Dos Lagos Golf Course'),
  ('United States', 'Dos Osos Golf Club'),
  ('United States', 'Dos Rios Country Club'),
  ('United States', 'Dothan Country Club'),
  ('United States', 'Dothan National Golf Club'),
  ('United States', 'Dotys Golf Course'),
  ('United States', 'Double Arrow Golf Resort'),
  ('United States', 'Double Black Diamond At Holiday Valley Resort'),
  ('United States', 'Double Eagle Golf Club'),
  ('United States', 'Double Oaks Golf Club'),
  ('United States', 'Doublegate Country Club'),
  ('United States', 'Douglas Golf Club'),
  ('United States', 'Douglas Golf Country Club'),
  ('United States', 'Douglass Golf Course'),
  ('United States', 'Douglaston Golf Club'),
  ('United States', 'Dove Canyon Country Club'),
  ('United States', 'Dove Valley Ranch Golf Club'),
  ('United States', 'Dover Par 3 Driving Range'),
  ('United States', 'Dowagiac Elk''s Golf Course'),
  ('United States', 'Down River Golf Course'),
  ('United States', 'Downers Grove Golf Club'),
  ('United States', 'Downing Farms Golf Course'),
  ('United States', 'Downing Municipal Golf Course'),
  ('United States', 'Downingtown Country Club'),
  ('United States', 'Downriver Golf Course'),
  ('United States', 'Downs Golf Course'),
  ('United States', 'Dows Golf Course'),
  ('United States', 'Doylestown Country Club'),
  ('United States', 'Dr Charles L Sifford Golf Course At Revolution Park'),
  ('United States', 'Dragonfly Golf Club'),
  ('United States', 'Dragonridge Golf Course'),
  ('United States', 'Draper Valley Golf Club'),
  ('United States', 'Dretzka Park Golf Course'),
  ('United States', 'Drew Country Club'),
  ('United States', 'Driftwood Golf Course'),
  ('United States', 'Driving Range'),
  ('United States', 'Drugan''s Castle Mound'),
  ('United States', 'Drugans Castle Mound'),
  ('United States', 'Druid Hills Golf Club'),
  ('United States', 'Druids Glen'),
  ('United States', 'Drummond Island Golf Club'),
  ('United States', 'Drumright Golf Club'),
  ('United States', 'Dry Creek Ranch Golf Course'),
  ('United States', 'Dryden Lake Golf Club'),
  ('United States', 'Dryden Park Golf Course'),
  ('United States', 'Dublin Country Club'),
  ('United States', 'Dublin Lake Golf Club'),
  ('United States', 'Dublin Ranch Golf Course'),
  ('United States', 'Dubois Country Club'),
  ('United States', 'Dubs Dread Golf Club'),
  ('United States', 'Dubsdread Golf Course'),
  ('United States', 'Dubuque Country Club'),
  ('United States', 'Duck Creek Golf Course'),
  ('United States', 'Duck Hollow Golf Club'),
  ('United States', 'Duck Lake Country Club'),
  ('United States', 'Duck Woods Country Club'),
  ('United States', 'Duckers Lake Golf Club'),
  ('United States', 'Dudley Hill Golf Club'),
  ('United States', 'Due Process Stable'),
  ('United States', 'Duke University Golf Club'),
  ('United States', 'Dumas Memorial Golf Course'),
  ('United States', 'Duncan Golf Country Club'),
  ('United States', 'Duncan Hills Golf Course'),
  ('United States', 'Duncan Park Golf Club'),
  ('United States', 'Dundee Golf Club'),
  ('United States', 'Dunedin Golf Club'),
  ('United States', 'Dunedin Stirling Links'),
  ('United States', 'Dunegrass Country Club'),
  ('United States', 'Dunes Arroyo At Gainey Ranch Golf Club'),
  ('United States', 'Dunes At Monterey Peninsula Country Club'),
  ('United States', 'Dunes At Sandridge Golf Club'),
  ('United States', 'Dunes Golf Club'),
  ('United States', 'Dunes West Golf Club'),
  ('United States', 'Dunham Hills Golf Club'),
  ('United States', 'Dunlap Golf Club'),
  ('United States', 'Dunmaglas Golf Club'),
  ('United States', 'Dunwoodie Golf Course'),
  ('United States', 'Dunwoody Country Club'),
  ('United States', 'Duplin Country Club'),
  ('United States', 'Dupont Country Club Championship Course'),
  ('United States', 'Dupont Country Club Montchanin Course'),
  ('United States', 'Dupont Country Club Nemours Course'),
  ('United States', 'Duran Golf Club Championship Course'),
  ('United States', 'Duran Golf Club Short Course'),
  ('United States', 'Durand Eastman Golf Course'),
  ('United States', 'Durango Hills Golf Course'),
  ('United States', 'Durham Lakes Country Club'),
  ('United States', 'Duston Country Club'),
  ('United States', 'Dusty Hills Country Club'),
  ('United States', 'Dutch Elm Golf Club'),
  ('United States', 'Dutch Hollow Country Club'),
  ('United States', 'Dutch Hollow Golf Club'),
  ('United States', 'Dutchaven Golf Course'),
  ('United States', 'Dutcher Golf Course'),
  ('United States', 'Dutchmans Pipe Golf Club'),
  ('United States', 'Duxbury Yacht Club'),
  ('United States', 'Dwan Golf Course'),
  ('United States', 'Dye At Colleton River Club'),
  ('United States', 'Dye Course At Pga Golf Club'),
  ('United States', 'Dye''s Walk Country Club'),
  ('United States', 'Dyer Country Club'),
  ('United States', 'Dyersburg Municipal Golf Course'),
  ('United States', 'Dyersville Golf and Country Club'),
  ('United States', 'Dyker Beach Golf Course'),
  ('United States', 'Dysart Country Club'),
  ('United States', 'E Gaynor Brennan Golf Course'),
  ('United States', 'E H Lynch Links Golf Course'),
  ('United States', 'E agle Pass Golf Course'),
  ('United States', 'EMS Links Golf Course'),
  ('United States', 'Eads Golf Course'),
  ('United States', 'Eagle Bend Golf Club Bear Osprey Course'),
  ('United States', 'Eagle Bend Golf Club Eagle Bear Course'),
  ('United States', 'Eagle Bend Golf Club Eagle Osprey Course'),
  ('United States', 'Eagle Bend Golf Course'),
  ('United States', 'Eagle Bluff Golf Club'),
  ('United States', 'Eagle Chase Golf Club'),
  ('United States', 'Eagle Creek'),
  ('United States', 'Eagle Creek Country Club'),
  ('United States', 'Eagle Creek Golf Club'),
  ('United States', 'Eagle Creek Golf Course'),
  ('United States', 'Eagle Crest'),
  ('United States', 'Eagle Crest Golf Club'),
  ('United States', 'Eagle Crest Resort'),
  ('United States', 'Eagle Dunes Golf Club'),
  ('United States', 'Eagle Eye Golf Club'),
  ('United States', 'Eagle Falls Golf Club'),
  ('United States', 'Eagle Falls Golf Course'),
  ('United States', 'Eagle Glen Golf Club'),
  ('United States', 'Eagle Glen Golf Course'),
  ('United States', 'Eagle Grove Country Club'),
  ('United States', 'Eagle Harbor Golf Club'),
  ('United States', 'Eagle Haven Golf Course'),
  ('United States', 'Eagle Hill Golf Athletic Club'),
  ('United States', 'Eagle Hills Academy Golf Course'),
  ('United States', 'Eagle Hills Golf Course'),
  ('United States', 'Eagle Island Golf Course'),
  ('United States', 'Eagle Lake - Birdie Course'),
  ('United States', 'Eagle Lake - Eagle Course'),
  ('United States', 'Eagle Lake Golf Course'),
  ('United States', 'Eagle Lakes Golf Club'),
  ('United States', 'Eagle Landing Golf Club'),
  ('United States', 'Eagle Links Golf Club'),
  ('United States', 'Eagle Mountain Golf Club'),
  ('United States', 'Eagle Mountain Golf Course'),
  ('United States', 'Eagle Nest Golf Club'),
  ('United States', 'Eagle Oaks Golf Country Club'),
  ('United States', 'Eagle Osprey At Okeeheelee Golf Course'),
  ('United States', 'Eagle Point Golf Club'),
  ('United States', 'Eagle Pointe Back 9'),
  ('United States', 'Eagle Ranch Golf Club'),
  ('United States', 'Eagle Ridge Gold Course'),
  ('United States', 'Eagle Ridge Golf Club'),
  ('United States', 'Eagle Ridge Golf Club Champions Course'),
  ('United States', 'Eagle Ridge Golf Club Heritage Course'),
  ('United States', 'Eagle Ridge Golf Club Links Course'),
  ('United States', 'Eagle Ridge Golf Club Masters Course'),
  ('United States', 'Eagle Ridge Golf Club Memorial Course'),
  ('United States', 'Eagle Ridge Golf Club Pines Course'),
  ('United States', 'Eagle Ridge Golf Course'),
  ('United States', 'Eagle River Golf Course'),
  ('United States', 'Eagle Rock Golf Club'),
  ('United States', 'Eagle Rock Golf Ski Resort'),
  ('United States', 'Eagle Rock Golf Ski Resort Executive Course'),
  ('United States', 'Eagle Run Golf Course'),
  ('United States', 'Eagle Springs Golf Club'),
  ('United States', 'Eagle Springs Golf Country Club'),
  ('United States', 'Eagle Springs Golf Course'),
  ('United States', 'Eagle Springs Golf Resort'),
  ('United States', 'Eagle Trace Country Club'),
  ('United States', 'Eagle Trace Golf Club'),
  ('United States', 'Eagle Vale Golf Course'),
  ('United States', 'Eagle Valley Golf Club'),
  ('United States', 'Eagle Valley Golf Course'),
  ('United States', 'Eagle View Golf Club'),
  ('United States', 'Eagle View Golf Course'),
  ('United States', 'Eagle Vines Golf Club'),
  ('United States', 'Eagle Watch Golf Club'),
  ('United States', 'Eagle''s Landing Golf Club and Grill'),
  ('United States', 'EagleSticks'),
  ('United States', 'Eaglebrook Country Club'),
  ('United States', 'Eaglerock Golf Course'),
  ('United States', 'Eagles Bluff Golf Course'),
  ('United States', 'Eagles Brooke Golf And Country Club'),
  ('United States', 'Eagles Crossing Golf Course'),
  ('United States', 'Eagles Landing'),
  ('United States', 'Eagles Landing Country Club Creek Nine'),
  ('United States', 'Eagles Landing Country Club Hill Nine'),
  ('United States', 'Eagles Landing Country Club Lake Nine'),
  ('United States', 'Eagles Landing Golf Course'),
  ('United States', 'Eagles Landing Golf Course Of Belton'),
  ('United States', 'Eagles Mere Country Club'),
  ('United States', 'Eagles Nest Country Club At Pebble Creek Resort'),
  ('United States', 'Eagles Nest Golf Course'),
  ('United States', 'Eagles Pointe Golf Club'),
  ('United States', 'Eagles Pride Golf Course Blue Green'),
  ('United States', 'Eagles Pride Golf Course Green Red'),
  ('United States', 'Eagles Pride Golf Course Red Blue'),
  ('United States', 'Eagles Pub Golf Course'),
  ('United States', 'Eagles Ridge Golf Club'),
  ('United States', 'Eaglevail Golf Club'),
  ('United States', 'Eaglewood Country Club'),
  ('United States', 'Eaglewood Golf Course'),
  ('United States', 'Eaglewood Golf Course Eagle Course'),
  ('United States', 'Eaglewood Golf Course Raptor Course'),
  ('United States', 'Eaglewood Resort Spa'),
  ('United States', 'Eaglewood Resort and Spa'),
  ('United States', 'Earlville Country Club'),
  ('United States', 'East At Belfair Golf Club'),
  ('United States', 'East At Broadmoor Golf Club'),
  ('United States', 'East At Bull Creek Golf Course'),
  ('United States', 'East At Churchville Park Golf Course'),
  ('United States', 'East At Country Club Of Hershey'),
  ('United States', 'East At Deerfield Country Club'),
  ('United States', 'East At Eagle Valley Golf Course'),
  ('United States', 'East At Glendoveer Golf Course'),
  ('United States', 'East At Grandover Resort'),
  ('United States', 'East At Hunters Run Golf Course'),
  ('United States', 'East At Imperial Golf Club'),
  ('United States', 'East At Jacaranda Golf Club'),
  ('United States', 'East At Laurel Oak Country Club'),
  ('United States', 'East At Lincoln Park Golf Course'),
  ('United States', 'East At Maidstone Club'),
  ('United States', 'East At Malone Golf Club'),
  ('United States', 'East At Merion Golf Club'),
  ('United States', 'East At Mohawk Golf Club'),
  ('United States', 'East At Oak Hill Country Club'),
  ('United States', 'East At Oak Tree Country Club'),
  ('United States', 'East At Orangebrook Country Club'),
  ('United States', 'East At Rogues Roost Golf Country Club'),
  ('United States', 'East At Tamarack Golf Course'),
  ('United States', 'East At Victor Hills Golf Club'),
  ('United States', 'East At Webster Golf Club'),
  ('United States', 'East At Windyke Country Club'),
  ('United States', 'East At Winged Foot Golf Club'),
  ('United States', 'East At Wycliffe Country Club'),
  ('United States', 'East Aurora Country Club'),
  ('United States', 'East Bay Golf Club'),
  ('United States', 'East Center At Ridgewood Country Club The'),
  ('United States', 'East Course'),
  ('United States', 'East Course At Belleair Country Club'),
  ('United States', 'East Course At Terry Hills Golf Course'),
  ('United States', 'East Fork Par-3 Golf Course'),
  ('United States', 'East Greenwich Golf Country Club'),
  ('United States', 'East Hampton Golf Club'),
  ('United States', 'East Hartford Golf Club'),
  ('United States', 'East Lake Golf Club'),
  ('United States', 'East Liverpool Country Club'),
  ('United States', 'East Mountain Country Club'),
  ('United States', 'East Mountain Golf Course'),
  ('United States', 'East North At Killearn Country Club Inn'),
  ('United States', 'East North At Spanish Wells Country Club'),
  ('United States', 'East Orange Golf Course'),
  ('United States', 'East Palestine Country Club'),
  ('United States', 'East Potomac Golf Links Blue Course'),
  ('United States', 'East Potomac Golf Links Red Course'),
  ('United States', 'East Potomac Golf Links White Course'),
  ('United States', 'East Private At Drumlins Golf Club'),
  ('United States', 'East Ridge Country Club'),
  ('United States', 'East South At Athens Country Club'),
  ('United States', 'East South At Lakes Country Club The'),
  ('United States', 'East South At Monterey Country Club'),
  ('United States', 'East South At Oaks North Golf Course'),
  ('United States', 'East South At Ocean Breeze Golf Country Club'),
  ('United States', 'East South At Sahalee Country Club'),
  ('United States', 'East South At Silver Lakes Country Club'),
  ('United States', 'East West At Monterey Country Club'),
  ('United States', 'East West At Newaukum Valley Golf Course'),
  ('United States', 'Eastern Hills Golf Club'),
  ('United States', 'Eastern Shore Yacht Country Club'),
  ('United States', 'Eastland Fairways'),
  ('United States', 'Eastlyn Golf Course'),
  ('United States', 'Eastman Golf Links'),
  ('United States', 'Easton Country Club'),
  ('United States', 'Eastpointe Country Club East Course')
on conflict (country, name) do nothing;