insert into public.golf_courses (country, name) values
  ('United States', 'Sycamore Ridge Golf Club'),
  ('United States', 'Sycamore Springs'),
  ('United States', 'Sycamore Springs Golf Course'),
  ('United States', 'Sycamore Valley Golf Course'),
  ('United States', 'Sydney R. Marovitz Golf Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club North South Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club Par 3 Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club South West Course'),
  ('United States', 'Sykes Lady Overland Park Golf Club West North Course'),
  ('United States', 'Sylvan Glen Golf Course'),
  ('United States', 'Sylvan Heights Golf Course'),
  ('United States', 'Sylvan Hills Golf Course'),
  ('United States', 'Sylvania Golf Club'),
  ('United States', 'Syracuse Country Club'),
  ('United States', 'TPC Deere Run'),
  ('United States', 'TPC Michigan'),
  ('United States', 'TPC Twin Cities'),
  ('United States', 'TPC Wisconsin'),
  ('United States', 'Taberna Country Club'),
  ('United States', 'Table Mountain Golf Club'),
  ('United States', 'Tacoma Country Golf Club'),
  ('United States', 'Taconic Golf Club'),
  ('United States', 'Tagalong Golf & Resort'),
  ('United States', 'Tahlequah City Golf Course'),
  ('United States', 'Tahoe City Golf Course'),
  ('United States', 'Tahoe Paradise Golf Course'),
  ('United States', 'Tahoma Valley Golf Country Club'),
  ('United States', 'Talamore Country Club'),
  ('United States', 'Talamore Golf Resort'),
  ('United States', 'Talbot Trail Golf Club'),
  ('United States', 'Talega Golf Club'),
  ('United States', 'Talis Park Golf Club'),
  ('United States', 'Talisker Golf At Tuhaye Golf Course'),
  ('United States', 'Talking Rock Golf Club'),
  ('United States', 'Talking Stick Golf Club Oodham Course'),
  ('United States', 'Talking Stick Golf Club Piipaash Course'),
  ('United States', 'Tall Pines Players Club'),
  ('United States', 'Tall Timber Golf Course'),
  ('United States', 'Tallahatchie Country Club'),
  ('United States', 'Talley Ho Course At Glenview Champions Country Club'),
  ('United States', 'Tallgrass Country Club'),
  ('United States', 'Tallulah Country Club'),
  ('United States', 'Tallwood Country Club'),
  ('United States', 'Tally Mountain Golf Course'),
  ('United States', 'Talon At Grayhawk Golf Club'),
  ('United States', 'Talons of Tuscany Golf Club'),
  ('United States', 'Talonscove At Saratoga Springs'),
  ('United States', 'Tam O''Shanter Country Club'),
  ('United States', 'Tam O''Shanter Golf Course'),
  ('United States', 'Tam Oshanter Golf Country Club'),
  ('United States', 'Tam Oshanter Of Pennsylvania'),
  ('United States', 'Tama Toledo Country Club'),
  ('United States', 'Tamahka Trails'),
  ('United States', 'Tamaqua Golf Course'),
  ('United States', 'Tamarac Golf Course'),
  ('United States', 'Tamarack Country Club'),
  ('United States', 'Tamarack Golf Club'),
  ('United States', 'Tamarack Golf Course'),
  ('United States', 'Tamarack Resort Osprey Meadows Golf Course'),
  ('United States', 'Tamarisk Country Club'),
  ('United States', 'Tamarisk Golf Course'),
  ('United States', 'Tamaron Country Club'),
  ('United States', 'Tamaya Cheena Course At Santa Ana Golf Club'),
  ('United States', 'Tamaya Star Course At Santa Ana Golf Club'),
  ('United States', 'Tameka Woods Golf Course'),
  ('United States', 'Tamer Win Golf & Country Club'),
  ('United States', 'Tampa Bay Golf Country Club'),
  ('United States', 'Tampa Bay Golf Country Club Executive Course'),
  ('United States', 'Tampa Palms Golf Country Club'),
  ('United States', 'Tan Tara Golf Club'),
  ('United States', 'Tanglewood Club'),
  ('United States', 'Tanglewood Golf And Country Club'),
  ('United States', 'Tanglewood Golf Club'),
  ('United States', 'Tanglewood Golf Club Championship Course'),
  ('United States', 'Tanglewood Golf Club Par 3 Course'),
  ('United States', 'Tanglewood Golf Club Reynolds Course'),
  ('United States', 'Tanglewood Golf Course'),
  ('United States', 'Tanglewood Greens'),
  ('United States', 'Tanglewood Manor Golf Club'),
  ('United States', 'Tanglewood Marsh Golf Course'),
  ('United States', 'Tanglewood Resort Hotel And Conference Center'),
  ('United States', 'Tanglewood Shores Golf Country Club'),
  ('United States', 'Tannenbaum Golf Club'),
  ('United States', 'Tannenhauf Golf Club'),
  ('United States', 'Tanner Valley Golf 18 Hole'),
  ('United States', 'Tanner''s Brook'),
  ('United States', 'Tanoan Country Club Acoma Course'),
  ('United States', 'Tanoan Country Club Sandia Course'),
  ('United States', 'Tanoan Country Club Zia Course'),
  ('United States', 'Taos Country Club'),
  ('United States', 'Tapawingo National Golf Club'),
  ('United States', 'Tapps Island Golf Course'),
  ('United States', 'Tara Golf Club At Savannah Lakes'),
  ('United States', 'Tara Golf Country Club'),
  ('United States', 'Tara Greens Golf Center Pitch N Putt'),
  ('United States', 'Tara Hills Country Club'),
  ('United States', 'Tara Hills Golf Course'),
  ('United States', 'Targhee Village Golf Course'),
  ('United States', 'Tarkio Golf Club'),
  ('United States', 'Tarpon Boil At The Villages Executive Golf Trail'),
  ('United States', 'Tarpon Springs Golf Course'),
  ('United States', 'Tarpon Woods Golf Club'),
  ('United States', 'Tarratine Golf Club'),
  ('United States', 'Tarry Brae Golf Course'),
  ('United States', 'Tashua Knolls Golf Club Tashua Glen'),
  ('United States', 'Tashua Knolls Golf Club Tashua Knolls'),
  ('United States', 'Tater Hill Country Club'),
  ('United States', 'Tatnuck Country Club'),
  ('United States', 'Tatum Ranch Golf Club'),
  ('United States', 'Tatum Ridge Golf Links'),
  ('United States', 'Tavistock Country Club'),
  ('United States', 'Tawas Creek Golf Club'),
  ('United States', 'Taylor Meadows Golf Course'),
  ('United States', 'Taylors Creek Golf Course'),
  ('United States', 'Taylors Par 3'),
  ('United States', 'Tazewell County Country Club'),
  ('United States', 'Tchefuncta Country Club'),
  ('United States', 'Teal Bend Golf Club'),
  ('United States', 'Tecolote Canyon Golf Course'),
  ('United States', 'Tecumseh Golf Club'),
  ('United States', 'Ted Makalena Golf Course'),
  ('United States', 'Tedesco Country Club'),
  ('United States', 'Tee Hi Club'),
  ('United States', 'Tee Time Golf Cafe'),
  ('United States', 'Tee Time Golf Complex'),
  ('United States', 'Tee-Hi Golf Course'),
  ('United States', 'Teetering Rocks Executive Links'),
  ('United States', 'Tega Cay Golf Club The Cove'),
  ('United States', 'Tega Cay Golf Club The Grande View'),
  ('United States', 'Tega Cay Golf Club The Pines'),
  ('United States', 'Tehama Golf Club'),
  ('United States', 'Tekoa Country Club'),
  ('United States', 'Tekoa Golf Course'),
  ('United States', 'Teleli Golf Club'),
  ('United States', 'Telemark Golf Course'),
  ('United States', 'Telluride Golf Club'),
  ('United States', 'Temple Terrace Golf Country Club'),
  ('United States', 'Templewood Golf Course'),
  ('United States', 'Tennessee Valley Country Club'),
  ('United States', 'Tepetonka Golf Club'),
  ('United States', 'Tequesta Country Club'),
  ('United States', 'Terra Ceia Bay Golf Tennis Club'),
  ('United States', 'Terra Greens Golf Course'),
  ('United States', 'Terra Verde Golf Course'),
  ('United States', 'Terrace At Saint Clair Country Club'),
  ('United States', 'Terrace Bluff Golf Course'),
  ('United States', 'Terrace Hill Golf Club'),
  ('United States', 'Terrace Hills Golf Course'),
  ('United States', 'Terrace Lakes Resort'),
  ('United States', 'Terrace Park Country Club'),
  ('United States', 'Terrace View Golf Course'),
  ('United States', 'Terradyne Country Club'),
  ('United States', 'Terrapin Hills Country Club'),
  ('United States', 'Terraverde Country Club'),
  ('United States', 'Terravita Golf Club'),
  ('United States', 'Territory Golf Club'),
  ('United States', 'Terry Park Golf Course'),
  ('United States', 'Teton Lakes Golf Course Middle Fork'),
  ('United States', 'Teton Lakes Golf Course North Fork'),
  ('United States', 'Teton Lakes Golf Course South Fork'),
  ('United States', 'Teton Pines Country Club Resort'),
  ('United States', 'Teton Reserve'),
  ('United States', 'Teugega Country Club'),
  ('United States', 'Tewksbury Country Club'),
  ('United States', 'Tex Consolver Municipal Golf Course'),
  ('United States', 'Texarkana Country Club'),
  ('United States', 'Texarkana Golf Ranch'),
  ('United States', 'Thal Acres Golf Course'),
  ('United States', 'Thal Acres Links Lanes'),
  ('United States', 'Thanksgiving Point Golf Club'),
  ('United States', 'Thatcher Golf Course'),
  ('United States', 'Thayer Country Club'),
  ('United States', 'The 1912 Club'),
  ('United States', 'The 500 Club'),
  ('United States', 'The 500 Club Futures Course'),
  ('United States', 'The Abington Club'),
  ('United States', 'The Alpine'),
  ('United States', 'The Amelia River Club'),
  ('United States', 'The Apawamis Club'),
  ('United States', 'The Aquidneck Club'),
  ('United States', 'The Arboretum Club'),
  ('United States', 'The Architects Golf Club'),
  ('United States', 'The Arizona Country Club'),
  ('United States', 'The Arnold Palmer Signature Course At Stonewall Resort'),
  ('United States', 'The Ashford Short Course'),
  ('United States', 'The Atchafalaya At Idlewild'),
  ('United States', 'The Azalea At Pinewild Country Club'),
  ('United States', 'The Back Nine Club'),
  ('United States', 'The Barn Golf Club'),
  ('United States', 'The Bath Golf Club'),
  ('United States', 'The Baths Of Blackwolf Run'),
  ('United States', 'The Bay Club At Mattapoisett'),
  ('United States', 'The Bayonet At Bayonet Black Horse Golf Course'),
  ('United States', 'The Bear Golf Course'),
  ('United States', 'The Bear S Club Par 3 Course'),
  ('United States', 'The Bears Club'),
  ('United States', 'The Beaufort Club'),
  ('United States', 'The Biltmore Golf Course'),
  ('United States', 'The Blandford Golf Tennis Club'),
  ('United States', 'The Bluff Golf Links'),
  ('United States', 'The Bluffs At Coffee Mill'),
  ('United States', 'The Bluffs At The National Golf Club Of Kansas City'),
  ('United States', 'The Bluffs On Thompson Creek'),
  ('United States', 'The Bobcat At Plantation Golf Country Club'),
  ('United States', 'The Boca Raton'),
  ('United States', 'The Bog'),
  ('United States', 'The Bolivar Golf Club'),
  ('United States', 'The Bourne'),
  ('United States', 'The Brassie Golf Club'),
  ('United States', 'The Breakers Ocean Course'),
  ('United States', 'The Breakers Rees Jones Course'),
  ('United States', 'The Bridgehampton Club'),
  ('United States', 'The Bridges'),
  ('United States', 'The Bridges At Beresford'),
  ('United States', 'The Bridges At Rancho Santa Fe'),
  ('United States', 'The Bridges At Springtree Golf Club'),
  ('United States', 'The Bridges Golf Club'),
  ('United States', 'The Bridges Golf Club At Hollywood Casino'),
  ('United States', 'The Bridges Golf Country Club'),
  ('United States', 'The Brookside Club'),
  ('United States', 'The Bucks Club'),
  ('United States', 'The Bull at Pinehurst Farms'),
  ('United States', 'The Calibogue The Haig At Haig Point Club'),
  ('United States', 'The Canyons At Bighorn Golf Club'),
  ('United States', 'The Canyons At Blackjack Ridge'),
  ('United States', 'The Cape Club'),
  ('United States', 'The Cape Club Of Palm City'),
  ('United States', 'The Cape Club Of Sharon'),
  ('United States', 'The Captain''s Club at Woodfield'),
  ('United States', 'The Cardinal By Pete Dye'),
  ('United States', 'The Cascade At Gold Mountain Golf Course'),
  ('United States', 'The Cedars At Dungeness'),
  ('United States', 'The Challenge At Cypress Hills'),
  ('United States', 'The Challenge Golf Club'),
  ('United States', 'The Champion Turf Club At St James'),
  ('United States', 'The Champions Club At Summerfield'),
  ('United States', 'The Chief Golf Course'),
  ('United States', 'The Chimneys Golf Course'),
  ('United States', 'The Classic'),
  ('United States', 'The Classic Club'),
  ('United States', 'The Classic at Madden''s'),
  ('United States', 'The Classics Country Club'),
  ('United States', 'The Cleghorn Club'),
  ('United States', 'The Cliffs At Glassy Golf Course'),
  ('United States', 'The Cliffs At Keowee Falls Golf Course'),
  ('United States', 'The Cliffs At Keowee Springs'),
  ('United States', 'The Cliffs At Keowee Vineyards'),
  ('United States', 'The Cliffs At Mountain Park Golf Course'),
  ('United States', 'The Cliffs At Walnut Cove'),
  ('United States', 'The Cliffs Valley Golf Course'),
  ('United States', 'The Club At Arrowcreek Challenge Course'),
  ('United States', 'The Club At Arrowcreek Legend Course'),
  ('United States', 'The Club At Black Rock 18 Hole Putting Course'),
  ('United States', 'The Club At Black Rock Jim Engh Course'),
  ('United States', 'The Club At Brookstone'),
  ('United States', 'The Club At Clear Creek'),
  ('United States', 'The Club At Crazy Horse Ranch'),
  ('United States', 'The Club At Crested Butte'),
  ('United States', 'The Club At Discovery Harbour'),
  ('United States', 'The Club At Eaglebrooke'),
  ('United States', 'The Club At Emerald Hills'),
  ('United States', 'The Club At Flying Horse'),
  ('United States', 'The Club At Flying Horse North Course'),
  ('United States', 'The Club At Forest Ridge'),
  ('United States', 'The Club At Gateway'),
  ('United States', 'The Club At Grandezza'),
  ('United States', 'The Club At Hokulia'),
  ('United States', 'The Club At Ibis The Heritage Course'),
  ('United States', 'The Club At Ibis The Legend Course'),
  ('United States', 'The Club At Ibis The Tradition Course'),
  ('United States', 'The Club At Irish Creek'),
  ('United States', 'The Club At Kingsmill Woods Course'),
  ('United States', 'The Club At Lake Sinclair'),
  ('United States', 'The Club At Longview'),
  ('United States', 'The Club At Mediterra North Course'),
  ('United States', 'The Club At Mediterra South Course'),
  ('United States', 'The Club At Morningside'),
  ('United States', 'The Club At Nevillewood'),
  ('United States', 'The Club At New Seabury Dunes Course'),
  ('United States', 'The Club At New Seabury Ocean Course'),
  ('United States', 'The Club At Old Hawthorne'),
  ('United States', 'The Club At Olde Cypress'),
  ('United States', 'The Club At Osprey Cove'),
  ('United States', 'The Club At Pelican Bay North Course'),
  ('United States', 'The Club At Pine Forest'),
  ('United States', 'The Club At Pradera'),
  ('United States', 'The Club At Prescott Lakes'),
  ('United States', 'The Club At Ravenna'),
  ('United States', 'The Club At Renaissance'),
  ('United States', 'The Club At River Forest'),
  ('United States', 'The Club At River Wilderness'),
  ('United States', 'The Club At Savannah Harbor'),
  ('United States', 'The Club At Savannah Quarters'),
  ('United States', 'The Club At Seven Canyons'),
  ('United States', 'The Club At Shadow Lakes'),
  ('United States', 'The Club At Shannondell'),
  ('United States', 'The Club At Shepard Hills'),
  ('United States', 'The Club At Silver Lake'),
  ('United States', 'The Club At Snoqualmie Ridge'),
  ('United States', 'The Club At Spanish Peaks'),
  ('United States', 'The Club At Spurwing Challenge Course'),
  ('United States', 'The Club At Spurwing Championship Course'),
  ('United States', 'The Club At Starr Pass Gambler Pioneer'),
  ('United States', 'The Club At Starr Pass Palmer Gambler'),
  ('United States', 'The Club At Starr Pass Pioneer Palmer'),
  ('United States', 'The Club At Stoneridge'),
  ('United States', 'The Club At Sunrise'),
  ('United States', 'The Club At The Highlands'),
  ('United States', 'The Club At The Strand Preserve Savannah Course'),
  ('United States', 'The Club At The Strand Sabal Preserve Course'),
  ('United States', 'The Club At The Strand Savannah Sabal Course'),
  ('United States', 'The Club At Twin Lakes'),
  ('United States', 'The Club At Venetian Bay'),
  ('United States', 'The Club At Viniterra'),
  ('United States', 'The Club At Westminster'),
  ('United States', 'The Club Of Staunton'),
  ('United States', 'The Club Pelican Bay Club Bay Course'),
  ('United States', 'The Club Pelican Bay Club Pelican Course'),
  ('United States', 'The Club Pelican Bay Pelican Bay Course'),
  ('United States', 'The Club Renaissance'),
  ('United States', 'The Club at Lac La Belle'),
  ('United States', 'The Club at Strawberry Creek'),
  ('United States', 'The Club at Tartan Fields'),
  ('United States', 'The Clubs At Arrowhead'),
  ('United States', 'The Clubs At Arrowhead Legend Course'),
  ('United States', 'The College Golf Course At Delhi'),
  ('United States', 'The Colony Golf Country Club'),
  ('United States', 'The Columbia Golf And Country Club'),
  ('United States', 'The Concession Golf Club'),
  ('United States', 'The Concession Golf Club The Gimme Course'),
  ('United States', 'The Country Club'),
  ('United States', 'The Country Club At Dc Ranch'),
  ('United States', 'The Country Club At Lake City'),
  ('United States', 'The Country Club At Soboba Springs'),
  ('United States', 'The Country Club At The Golden Nugget'),
  ('United States', 'The Country Club At Woodmoor'),
  ('United States', 'The Country Club Of Arkansas'),
  ('United States', 'The Country Club Of Colorado At Cheyenne Mountain Resort'),
  ('United States', 'The Country Club Of Greenfield'),
  ('United States', 'The Country Club Of Lexington'),
  ('United States', 'The Country Club Of Louisiana'),
  ('United States', 'The Country Club Of Meadville'),
  ('United States', 'The Country Club Of Mount Dora'),
  ('United States', 'The Country Club Of North Carolina Cardinal Course'),
  ('United States', 'The Country Club Of North Carolina Dogwood Course'),
  ('United States', 'The Country Club Of Orlando'),
  ('United States', 'The Country Club Of Oxford'),
  ('United States', 'The Country Club Of Rancho Bernardo'),
  ('United States', 'The Country Club Of Sapphire Valley'),
  ('United States', 'The Country Club Of South Carolina'),
  ('United States', 'The Country Club Of Spartanburg'),
  ('United States', 'The Country Club Of Troy'),
  ('United States', 'The Country Club Of Virginia James River Course'),
  ('United States', 'The Country Club Of Virginia Tuckahoe Creek Course'),
  ('United States', 'The Country Club Of Virginia Westhampton Course'),
  ('United States', 'The Country Club at Muirfield Village'),
  ('United States', 'The Country Club of Indianapolis'),
  ('United States', 'The Country Club of Saint Albans'),
  ('United States', 'The County Club of Hudson'),
  ('United States', 'The Course At Eagle Mountain'),
  ('United States', 'The Course At Petteys Park'),
  ('United States', 'The Course At River Oaks'),
  ('United States', 'The Course At Wente Vineyards'),
  ('United States', 'The Cove Of Rotonda Golf Center'),
  ('United States', 'The Coves At Round Mountain'),
  ('United States', 'The Creek'),
  ('United States', 'The Creek At Hard Labor State Park'),
  ('United States', 'The Creek At Qualchan Golf Course'),
  ('United States', 'The Creek Golf Club'),
  ('United States', 'The Creeks Golf Rv Resort'),
  ('United States', 'The Crosby Club'),
  ('United States', 'The Crossings'),
  ('United States', 'The Crossings At Carlsbad'),
  ('United States', 'The Crossings At Montevideo'),
  ('United States', 'The Crossings Golf Club'),
  ('United States', 'The Crossings Golf Course'),
  ('United States', 'The Crown Golf Club'),
  ('United States', 'The Currituck Club'),
  ('United States', 'The Cypress At Palm Beach Polo Country Club'),
  ('United States', 'The Dalles Golf Country Club'),
  ('United States', 'The Den at Fox Creek'),
  ('United States', 'The Derby Golf Country Club'),
  ('United States', 'The Divide Golf Club'),
  ('United States', 'The Dogwoods Golf Course At Hugh White State Park'),
  ('United States', 'The Dominion Club'),
  ('United States', 'The Dream GC'),
  ('United States', 'The Duke At Rancho El Dorado'),
  ('United States', 'The Dunes At Maui Lani Golf Course'),
  ('United States', 'The Dunes Club'),
  ('United States', 'The Dunes Golf Beach Club'),
  ('United States', 'The Dunes Golf Tennis Club'),
  ('United States', 'The Dye Preserve Golf Club'),
  ('United States', 'The Eagles Golf Club Forest'),
  ('United States', 'The Eagles Golf Club Lakes'),
  ('United States', 'The East West At Upper Montclair Country Club'),
  ('United States', 'The Eastwood Golf Course & Restaurant'),
  ('United States', 'The Eighteen Hole At Centre Hills Country Club'),
  ('United States', 'The Elks Golf Course At Sandpoint'),
  ('United States', 'The Elms Golf Club'),
  ('United States', 'The Emerald Golf Club')
on conflict (country, name) do nothing;