insert into public.golf_courses (country, name) values
  ('United States', 'St Davids Golf Club'),
  ('United States', 'St George Country Club'),
  ('United States', 'St George Golf Club'),
  ('United States', 'St Georges Golf Country Club'),
  ('United States', 'St Helens Golf Course'),
  ('United States', 'St Ives Country Club'),
  ('United States', 'St James Bay Golf Club'),
  ('United States', 'St John Golf Country Club'),
  ('United States', 'St Johns Golf Club'),
  ('United States', 'St Johns Golf Country Club'),
  ('United States', 'St Johnsbury Country Club'),
  ('United States', 'St Joseph Bay Golf Club'),
  ('United States', 'St Joseph Country Club'),
  ('United States', 'St Lawrence State Park Golf Course'),
  ('United States', 'St Lawrence University Golf Country Club'),
  ('United States', 'St Lucie Trail Golf Club'),
  ('United States', 'St Malo Golf Cabins'),
  ('United States', 'St Maries Golf Course'),
  ('United States', 'St Marlo Country Club'),
  ('United States', 'St Martins Golf Course At Philadelphia Cricket Club'),
  ('United States', 'St Mary Golf Country Club'),
  ('United States', 'St Marys Public Golf Course'),
  ('United States', 'St Mellion Golf Club Nicklaus Course'),
  ('United States', 'St Petersburg Country Club'),
  ('United States', 'St Stanislaus Golf Course'),
  ('United States', 'St Stephen Golf Club'),
  ('United States', 'St. Anne''s Golf Course'),
  ('United States', 'St. Bernard Golf Club'),
  ('United States', 'St. Charles Disc Golf Course'),
  ('United States', 'St. Charles Golf Club'),
  ('United States', 'St. Clair Country Club'),
  ('United States', 'St. Clair Golf Club'),
  ('United States', 'St. Clair Parkway Golf Course'),
  ('United States', 'St. Cloud Country Club'),
  ('United States', 'St. Croix Valley Golf Course'),
  ('United States', 'St. Denis Golf Course'),
  ('United States', 'St. Germain Golf 9 Hole'),
  ('United States', 'St. Louis Country Club'),
  ('United States', 'St. Mike''s Golf Course'),
  ('United States', 'St. Peters Golf Course'),
  ('United States', 'St. Urho'),
  ('United States', 'Stadium Golf Club'),
  ('United States', 'Stafford Country Club'),
  ('United States', 'Stafford County Country Club'),
  ('United States', 'Stagg Hill Golf Club'),
  ('United States', 'Stahlstown Par 3 Golf Course'),
  ('United States', 'Stallion Mountain Golf Club'),
  ('United States', 'Stamford Golf Course'),
  ('United States', 'Stamford Valley Golf Course'),
  ('United States', 'Standard Club The'),
  ('United States', 'Standard Country Club'),
  ('United States', 'Stanford Golf Club'),
  ('United States', 'Stanley Golf Course Blue White'),
  ('United States', 'Stanley Golf Course Red Blue'),
  ('United States', 'Stanley Golf Course White Red'),
  ('United States', 'Stansbury Park Golf Course'),
  ('United States', 'Stanton County Prairie Pines'),
  ('United States', 'Stanton Ridge Golf Country Club'),
  ('United States', 'Stanwich Club'),
  ('United States', 'Star Valley Rv Golf Course'),
  ('United States', 'Star Valley View Golf Course'),
  ('United States', 'Stardust Golf Course At Sun City West'),
  ('United States', 'Starfire Golf Club The King Course'),
  ('United States', 'Starfire Golf Club The Mulligan 9'),
  ('United States', 'Starke Country Club'),
  ('United States', 'Starkville Country Club'),
  ('United States', 'Starmount Forest Country Club'),
  ('United States', 'Starx Golf Course'),
  ('United States', 'States Golf Club'),
  ('United States', 'Statesville Country Club'),
  ('United States', 'Steamboat Golf Club'),
  ('United States', 'Steel Canyon Golf Club'),
  ('United States', 'Steel Club Championship Course'),
  ('United States', 'Steel Club Hill Nine'),
  ('United States', 'Steel Creek Golf Course'),
  ('United States', 'Steele Canyon Golf Club Canyon Ranch'),
  ('United States', 'Steele Canyon Golf Club Canyon Vineyard'),
  ('United States', 'Steele Canyon Golf Club Ranch Vineyard'),
  ('United States', 'Steele Hill Resort Golf Course'),
  ('United States', 'Steeple Chase Golf Club'),
  ('United States', 'Stengers Shamrock Farms Par 3 Golf Course'),
  ('United States', 'Stephen Golf Course'),
  ('United States', 'Sterling Country Club'),
  ('United States', 'Sterling Farms Golf Course'),
  ('United States', 'Sterling Grove Golf Country Club'),
  ('United States', 'Sterling Hills Golf Club'),
  ('United States', 'Sterling National Country Club'),
  ('United States', 'Sterling Park Golf Club'),
  ('United States', 'Steubenville Country Club'),
  ('United States', 'Steve Hogan Golf Course'),
  ('United States', 'Stevens Point Country Club'),
  ('United States', 'Stewartville Golf Club'),
  ('United States', 'Stillmeadow Country Club'),
  ('United States', 'Stillwater Country Club'),
  ('United States', 'Stillwater Golf And Country Club'),
  ('United States', 'Stillwater Golf Course'),
  ('United States', 'Stillwater Oaks Golf Course'),
  ('United States', 'Stillwater Valley Golf Club'),
  ('United States', 'Stirrup Cup Course At Glenview Champions Country Club'),
  ('United States', 'Stoatin Brae Golf Club'),
  ('United States', 'Stock Farm'),
  ('United States', 'Stockbridge Golf Club'),
  ('United States', 'Stockdale Country Club'),
  ('United States', 'Stockton Golf Country Club'),
  ('United States', 'Stoeckeler Memorial Park Golf Course'),
  ('United States', 'Stone Canyon Club'),
  ('United States', 'Stone Creek At Page Belcher Golf Course'),
  ('United States', 'Stone Creek Cove Golf Course'),
  ('United States', 'Stone Creek Golf Club'),
  ('United States', 'Stone Creek Golf Course'),
  ('United States', 'Stone Crossing Golf Club'),
  ('United States', 'Stone Dock Golf Club'),
  ('United States', 'Stone E Lea Golf Course'),
  ('United States', 'Stone Eagle Golf Club'),
  ('United States', 'Stone Harbor Golf Club'),
  ('United States', 'Stone Hedge Country Club'),
  ('United States', 'Stone Meadow Golf'),
  ('United States', 'Stone Meadows Golf Course'),
  ('United States', 'Stone Mountain Golf Club'),
  ('United States', 'Stone Oak Country Club'),
  ('United States', 'Stone Ridge Golf Club'),
  ('United States', 'Stone Tree Golf Club'),
  ('United States', 'StoneRidge Golf Club'),
  ('United States', 'Stonebridge Country Club'),
  ('United States', 'Stonebridge Golf Club'),
  ('United States', 'Stonebridge Golf Club Creekside Sunrise Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Championship Course'),
  ('United States', 'Stonebridge Golf Club Of New Orleans Harvey 9 Course'),
  ('United States', 'Stonebridge Golf Club Sagebrush Creekside Course'),
  ('United States', 'Stonebridge Golf Club Sunrise Sagebrush Course'),
  ('United States', 'Stonebridge Golf Country Club'),
  ('United States', 'Stonebridge Golf Links Country Club'),
  ('United States', 'Stonebridge Meadows Golf Club'),
  ('United States', 'Stonebrook Golf Course'),
  ('United States', 'Stonebrooke Golf Course'),
  ('United States', 'Stonecreek Golf Club'),
  ('United States', 'Stonecrest'),
  ('United States', 'Stonecrest Golf Club'),
  ('United States', 'Stonecrest Golf Club Meadows Course'),
  ('United States', 'Stonecrest Golf Course'),
  ('United States', 'Stonegate Golf Club'),
  ('United States', 'Stonegate Golf Course'),
  ('United States', 'Stoneham Oaks Golf Course'),
  ('United States', 'Stonehedge Golf Course'),
  ('United States', 'Stonehedge North'),
  ('United States', 'Stonehedge South'),
  ('United States', 'Stonehedges Golf Club'),
  ('United States', 'Stonehenge Golf Club'),
  ('United States', 'Stonehenge Golf Country Club'),
  ('United States', 'Stonehenge Golf Course'),
  ('United States', 'Stonehouse Creek At Temecula Creek Inn Golf Resort'),
  ('United States', 'Stonehouse Golf Club'),
  ('United States', 'Stoneleigh Golf Club'),
  ('United States', 'Stonemont At Stone Mountain Golf Course'),
  ('United States', 'Stoneridge Golf Course'),
  ('United States', 'Stones Throw Golf Course'),
  ('United States', 'Stonewall Golf Club At Lake Manassas'),
  ('United States', 'Stonewall Golf Course'),
  ('United States', 'Stonewall Orchard Golf Club'),
  ('United States', 'Stonewater Country Club'),
  ('United States', 'Stonewater Golf Club'),
  ('United States', 'Stonewolf Golf Club'),
  ('United States', 'Stoney Creek Golf Club'),
  ('United States', 'Stoney Creek Golf Course'),
  ('United States', 'Stoney Links'),
  ('United States', 'Stoney Links Golf Course (closed)'),
  ('United States', 'Stoney Ridge Golf Course'),
  ('United States', 'Stoneybrook East Golf Course'),
  ('United States', 'Stoneybrook Golf Club'),
  ('United States', 'Stoneybrook Golf Country Club'),
  ('United States', 'Stoneybrook West Golf Course'),
  ('United States', 'Stonington Country Club'),
  ('United States', 'Stony Creek Golf Course'),
  ('United States', 'Stony Creek Metropark Golf Course'),
  ('United States', 'Stony Ford Golf Course'),
  ('United States', 'Stony Point Golf Course'),
  ('United States', 'Stonybrook Golf Club'),
  ('United States', 'Stonybrook Golf Course'),
  ('United States', 'Stonycreek Golf Club'),
  ('United States', 'Stonycroft Hills Club'),
  ('United States', 'Stop N Sock Golf Course'),
  ('United States', 'Storm King Golf Club'),
  ('United States', 'Storm Lake Golf Course'),
  ('United States', 'Stoughton Acres Golf Course'),
  ('United States', 'Stoughton Country Club'),
  ('United States', 'Stow North At Stow Acres Country Club'),
  ('United States', 'Stow South At Stow Acres Country Club'),
  ('United States', 'Stowaway Golf Course'),
  ('United States', 'Stowe Country Club'),
  ('United States', 'Stoweflake Mountain Resort Spa'),
  ('United States', 'Straight River Golf Course'),
  ('United States', 'Stratford Country Club'),
  ('United States', 'Stratton Golf Club'),
  ('United States', 'Strawberry Farms Golf Club'),
  ('United States', 'Strawberry Ridge Golf Course'),
  ('United States', 'Strawberry Valley Golf Club'),
  ('United States', 'Streamside Golf Course'),
  ('United States', 'Streamside Golf Course And Country Club'),
  ('United States', 'Streamsong Resort Black Course'),
  ('United States', 'Streamsong Resort Blue Course'),
  ('United States', 'Streamsong Resort Red Course'),
  ('United States', 'Streamsong Resort The Chain'),
  ('United States', 'Streamsong Resort The Gauntlet Putting Course'),
  ('United States', 'Streamwood Oaks Golf Club'),
  ('United States', 'Stripe Show Golf Club'),
  ('United States', 'Stroud Municipal Golf Course'),
  ('United States', 'Stryker Golf Course'),
  ('United States', 'Studebaker Park'),
  ('United States', 'Studio59 Golf - Libertyville Golf Course'),
  ('United States', 'Stumpy Lake Golf Course'),
  ('United States', 'Stuttgart Country Club'),
  ('United States', 'Suburban Golf Club'),
  ('United States', 'Sudden Valley Golf Country Club'),
  ('United States', 'Suffield Country Club'),
  ('United States', 'Suffield Springs Golf Club'),
  ('United States', 'Suffolk Golf Course'),
  ('United States', 'Sugar Bush Golf Course'),
  ('United States', 'Sugar Creek Country Club'),
  ('United States', 'Sugar Creek Golf Course'),
  ('United States', 'Sugar Creek Golf Tennis Club'),
  ('United States', 'Sugar Hill Golf Club'),
  ('United States', 'Sugar Hill Golf Course'),
  ('United States', 'Sugar Hills Golf Club'),
  ('United States', 'Sugar Mountain Golf Club'),
  ('United States', 'Sugar Oaks Golf Country Club'),
  ('United States', 'Sugar Ridge Golf Club'),
  ('United States', 'Sugar River Greens'),
  ('United States', 'Sugar Springs Golf Club'),
  ('United States', 'Sugar Valley Lakes Homes Association'),
  ('United States', 'Sugarbrooke Golf Course'),
  ('United States', 'Sugarbush Golf Club'),
  ('United States', 'Sugarbush Golf Course'),
  ('United States', 'Sugarland Country Club'),
  ('United States', 'Sugarloaf Golf Club'),
  ('United States', 'Sugarloaf Golf Club Resort'),
  ('United States', 'Sugarmill Woods Country Club Cypress Course'),
  ('United States', 'Sugarmill Woods Country Club Oak Course'),
  ('United States', 'Sugarmill Woods Country Club Pine Course'),
  ('United States', 'Sullivan County Golf Country Club'),
  ('United States', 'Sullivan Elks Country Club'),
  ('United States', 'Sullivans Par 3'),
  ('United States', 'Sulphur Hills Golf Course'),
  ('United States', 'Sultan’s Run Golf Club'),
  ('United States', 'Summer Breeze Par Three Golf Course'),
  ('United States', 'Summerfield Crossings Golf Club'),
  ('United States', 'Summerglen Golf Club'),
  ('United States', 'Summergrove Golf Club'),
  ('United States', 'Summerheights Golf Links South Course'),
  ('United States', 'Summerheights Golf Links West Course'),
  ('United States', 'Summertree Golf Club'),
  ('United States', 'Summertree Golf Course'),
  ('United States', 'Summerville Country Club'),
  ('United States', 'Summit At Cordillera Summit Course'),
  ('United States', 'Summit Chase Country Club'),
  ('United States', 'Summit Country Club'),
  ('United States', 'Summit Golf Course'),
  ('United States', 'Summit Hills Country Club'),
  ('United States', 'Summit Hills Golf Club'),
  ('United States', 'Summit Municipal Golf Course'),
  ('United States', 'Summit Springs Golf Course'),
  ('United States', 'Sumo Golf Village'),
  ('United States', 'Sumpwams Creek At E Donald Conroy Golf Course'),
  ('United States', 'Sumter Country Club'),
  ('United States', 'Sun City Country Club'),
  ('United States', 'Sun City Lakes Golf Club East Course'),
  ('United States', 'Sun City Lakes Golf Club West Course'),
  ('United States', 'Sun City South Golf Course'),
  ('United States', 'Sun Country Golf Resort'),
  ('United States', 'Sun Hills Golf Course'),
  ('United States', 'Sun Lakes Country Club'),
  ('United States', 'Sun Lakes Country Club Executive Course'),
  ('United States', 'Sun Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Sun River Golf Club'),
  ('United States', 'Sun Valley Golf Course'),
  ('United States', 'Sun Village Golf Course'),
  ('United States', 'Sun Willows Golf Course'),
  ('United States', 'Sunbird Golf Resort'),
  ('United States', 'Sunbrook Golf Club Black Rock The Point Course'),
  ('United States', 'Sunbrook Golf Club The Point Woodbridge Course'),
  ('United States', 'Sunbrook Golf Club Woodbridge Black Rock Course'),
  ('United States', 'Suncadia Resort Prospector Course'),
  ('United States', 'Suncadia Resort Rope Rider Course'),
  ('United States', 'Suncoast Golf Center'),
  ('United States', 'Suncrest Country Club'),
  ('United States', 'Suncrest Golf Course'),
  ('United States', 'Sundale Country Club'),
  ('United States', 'Sundance'),
  ('United States', 'Sundance Golf Banquet Bowl'),
  ('United States', 'Sundance Golf Club'),
  ('United States', 'Sundance Golf Course'),
  ('United States', 'Sunday River Golf Club'),
  ('United States', 'Sundown Golf Country Club'),
  ('United States', 'Suneagles Golf Club'),
  ('United States', 'Sunflower Hills Golf Course'),
  ('United States', 'Sunken Gardens Golf Course'),
  ('United States', 'Sunkist Country Club'),
  ('United States', 'Sunland Golf Country Club'),
  ('United States', 'Sunland Village East Golf Course'),
  ('United States', 'Sunland Village Golf Course'),
  ('United States', 'Sunnehanna Country Club'),
  ('United States', 'Sunnidell Golf Course'),
  ('United States', 'Sunningdale Country Club'),
  ('United States', 'Sunny Brae Golf & Country Club'),
  ('United States', 'Sunny Hill Golf Course'),
  ('United States', 'Sunny Hill Resort Golf Course'),
  ('United States', 'Sunny Hills Golf Club'),
  ('United States', 'Sunnybrook Country Club'),
  ('United States', 'Sunnybrook Golf Club'),
  ('United States', 'Sunnycrest Golf Course'),
  ('United States', 'Sunnylands Golf Course'),
  ('United States', 'Sunnyside Country Club'),
  ('United States', 'Sunnyside Golf Country Club'),
  ('United States', 'Sunnyside Par 3 Golf Course'),
  ('United States', 'Sunnyvale Municipal Golf Course'),
  ('United States', 'Sunridge Canyon Golf Club'),
  ('United States', 'Sunridge Golf Club'),
  ('United States', 'Sunrise Canyon At Spanish Trail Country Club'),
  ('United States', 'Sunrise Country Club'),
  ('United States', 'Sunrise Course At Country Club At Mirasol'),
  ('United States', 'Sunrise Golf Course'),
  ('United States', 'Sunrise Lakes Phase 3 Golf Course'),
  ('United States', 'Sunrise Lakes Phase Iv Golf Course'),
  ('United States', 'Sunrise Ridge Golf Course'),
  ('United States', 'Sunrise Vista Golf Course'),
  ('United States', 'Sunserra Golf At Crescent Bar'),
  ('United States', 'Sunset At Lancaster Country Club'),
  ('United States', 'Sunset Country Club'),
  ('United States', 'Sunset Course At Country Club At Mirasol'),
  ('United States', 'Sunset Golf Course'),
  ('United States', 'Sunset Grove Country Club'),
  ('United States', 'Sunset Hill Golf Club'),
  ('United States', 'Sunset Hill Golf Course'),
  ('United States', 'Sunset Hills Country Club'),
  ('United States', 'Sunset Hills Golf Club'),
  ('United States', 'Sunset Hills Golf Course'),
  ('United States', 'Sunset Hills Golf Course Old Course'),
  ('United States', 'Sunset Hills Golf Course Par 3 Course'),
  ('United States', 'Sunset Par 3'),
  ('United States', 'Sunset Ridge Country Club'),
  ('United States', 'Sunset Ridge Golf Club'),
  ('United States', 'Sunset Ridge Golf Links'),
  ('United States', 'Sunset Ridge Golf Links Par 3 Course'),
  ('United States', 'Sunset Valley Country Club'),
  ('United States', 'Sunset Valley Golf Course'),
  ('United States', 'Sunset View Golf Course'),
  ('United States', 'Sunshine Woods Golf Club'),
  ('United States', 'Suntides Golf Course'),
  ('United States', 'Superior Country Club'),
  ('United States', 'Superior National at Lutsen-Golf Course'),
  ('United States', 'Superstition Course At Sunland Springs Village'),
  ('United States', 'Superstition Mountain Golf Country Club Lost Gold Course'),
  ('United States', 'Superstition Mountain Golf Country Club Prospector Course'),
  ('United States', 'Superstition Springs Golf Club'),
  ('United States', 'Suppesville Golf Course'),
  ('United States', 'Surf Golf Beach Club'),
  ('United States', 'Surfside Golf Course'),
  ('United States', 'Surrey Hills Country Club'),
  ('United States', 'Susquehanna Valley Country Club'),
  ('United States', 'Sutton Bay Golf'),
  ('United States', 'Sutton Creek Golf Course'),
  ('United States', 'Suwannee Country Club'),
  ('United States', 'Swainsboro Golf Club'),
  ('United States', 'Swallows Nest Country Club'),
  ('United States', 'Swamp Fox Golf Club'),
  ('United States', 'Swan Hills Golf Course'),
  ('United States', 'Swan Lake Country Club'),
  ('United States', 'Swan Lake Golf Club'),
  ('United States', 'Swan Lake Golf Country Club'),
  ('United States', 'Swan Lake Golf Courses'),
  ('United States', 'Swan Lakes Golf Course'),
  ('United States', 'Swan Point Yacht Country Club'),
  ('United States', 'Swan Valley Golf Course'),
  ('United States', 'Swanhills'),
  ('United States', 'Swannanoa Country Club'),
  ('United States', 'Swansea Clinton Hills Conservation Park'),
  ('United States', 'Swansea Country Club'),
  ('United States', 'Swansea Country Club Par 3 Course'),
  ('United States', 'Swanson Meadows Golf Course'),
  ('United States', 'Swartz Creek Golf Course'),
  ('United States', 'Sweet Water Golf Course'),
  ('United States', 'Sweetbriar Golf & Pro Shop'),
  ('United States', 'Sweetens Cove Golf Club'),
  ('United States', 'Sweetgrass Golf Club'),
  ('United States', 'Sweetgum At The Villages Executive Golf Trail'),
  ('United States', 'Sweetwater Country Club'),
  ('United States', 'Sweetwater Golf Country Club'),
  ('United States', 'Sweetwater Golf Tennis Club'),
  ('United States', 'Swenson Park Golf Course Magnolia Executive Par 3'),
  ('United States', 'Swenson Park Golf Course The Oak Course'),
  ('United States', 'Swinomish Golf Links'),
  ('United States', 'Swiss Fairways Golf Course'),
  ('United States', 'Switzerland of Ohio Golf Course'),
  ('United States', 'Swope Memorial Golf Course'),
  ('United States', 'Sycamore Country Club'),
  ('United States', 'Sycamore Creek County Club'),
  ('United States', 'Sycamore Creek Golf Course'),
  ('United States', 'Sycamore Golf Club'),
  ('United States', 'Sycamore Hills Country Club'),
  ('United States', 'Sycamore Hills Golf Club'),
  ('United States', 'Sycamore Ridge')
on conflict (country, name) do nothing;