insert into public.golf_courses (country, name) values
  ('United States', 'Woods Fort Golf Course'),
  ('United States', 'Woods Hole Golf Club'),
  ('United States', 'Woods Pines At Tri Cities Golf Course'),
  ('United States', 'Woodside Club'),
  ('United States', 'Woodside Country Club'),
  ('United States', 'Woodside Country Club Cupp Course'),
  ('United States', 'Woodside Country Club Hunters Run Par 3 Course'),
  ('United States', 'Woodside Country Club Jones Course'),
  ('United States', 'Woodside Golf Course'),
  ('United States', 'Woodside Meadows Golf Course'),
  ('United States', 'Woodson Bend Resort'),
  ('United States', 'Woodstock Club'),
  ('United States', 'Woodstock Country Club'),
  ('United States', 'Woodstock Golf Club'),
  ('United States', 'Woodstock Golf Course'),
  ('United States', 'Woodstone Country Club'),
  ('United States', 'Woodward Municipal Golf Course'),
  ('United States', 'Woodway Country Club'),
  ('United States', 'Woodys Run Inc'),
  ('United States', 'Woody’s Run Public Golf Course'),
  ('United States', 'Wooster Country Club'),
  ('United States', 'Worcester Country Club'),
  ('United States', 'Worcester Golf Club'),
  ('United States', 'World Of Golf'),
  ('United States', 'World Tour Golf Links'),
  ('United States', 'Worthington Country Club'),
  ('United States', 'Worthington Golf Club'),
  ('United States', 'Worthington Hills Country Club'),
  ('United States', 'Wray Golf Course'),
  ('United States', 'Wrenwoods Golf Club At Charleston Air Force Base'),
  ('United States', 'Wuskowhan Players Club'),
  ('United States', 'Wyaloosing Creek'),
  ('United States', 'Wyandotte Hills Golf Course'),
  ('United States', 'Wyandotte Shores Golf Course'),
  ('United States', 'Wyantenuck Country Club'),
  ('United States', 'Wyboo Golf Club'),
  ('United States', 'Wyckoff Country Club'),
  ('United States', 'Wykagyl Country Club'),
  ('United States', 'Wymore Country Club'),
  ('United States', 'Wyncote Golf Club'),
  ('United States', 'Wynding Brook Golf Club'),
  ('United States', 'Wynmoor Golf Course'),
  ('United States', 'Wynn Golf Club'),
  ('United States', 'Wynstone Golf Club'),
  ('United States', 'Wyoming Golf Club'),
  ('United States', 'Wyoming Valley Country Club'),
  ('United States', 'Wytheville Golf Course'),
  ('United States', 'X-Golf'),
  ('United States', 'Yacht Country Club The'),
  ('United States', 'Yadkin Country Club'),
  ('United States', 'Yahara Hills Golf Course'),
  ('United States', 'Yahnundasis Golf Club'),
  ('United States', 'Yakima Country Club'),
  ('United States', 'Yakima Elks Golf Country Club'),
  ('United States', 'Yale Golf Course'),
  ('United States', 'Yalobusha Country Club'),
  ('United States', 'Yampa Valley Golf Club'),
  ('United States', 'Yankee Clipper At The Villages Executive Golf Trail'),
  ('United States', 'Yankee Run Golf Course'),
  ('United States', 'Yankee Springs Golf Course'),
  ('United States', 'Yardley Country Club'),
  ('United States', 'Yawgoo Valley Golf Course'),
  ('United States', 'Yazoo Country Club'),
  ('United States', 'Ye Nyne Old Holles Golf Course'),
  ('United States', 'Ye Olde Country Club'),
  ('United States', 'Yeamans Hall Country Club'),
  ('United States', 'Yellow At Bethpage State Park Golf Course'),
  ('United States', 'Yellow White At Willowbrook Golf Club'),
  ('United States', 'Yellowstone Country Club'),
  ('United States', 'Yellowstone Golf Club'),
  ('United States', 'Yellowstone Golf Course'),
  ('United States', 'Yellowstone Golf Resort At Aspen Acres Rv Park'),
  ('United States', 'Yinglings Golf Center'),
  ('United States', 'Ymca Par 3 Home Of The First Tee Of Lakeland'),
  ('United States', 'Yoakum County Golf Club'),
  ('United States', 'Yocha Dehe Golf Club At Cache Creek Casino Resort'),
  ('United States', 'Yolo Fliers Club'),
  ('United States', 'Yorba Linda Country Club'),
  ('United States', 'York Golf Club'),
  ('United States', 'York Golf Tennis Club'),
  ('United States', 'York Par 3 Golf Course'),
  ('United States', 'Yorktown Golf Complex'),
  ('United States', 'Yosemite Lakes Park Golf Course'),
  ('United States', 'Youche Country Club'),
  ('United States', 'Youghiogheny Country Club'),
  ('United States', 'Youngstown Country Club'),
  ('United States', 'Yucaipa Valley Golf Club'),
  ('United States', 'Yucca Ridge Golf Club'),
  ('United States', 'Yuma Golf Country Club'),
  ('United States', 'Zaca Creek Golf Course'),
  ('United States', 'Zach Brooks Golf Course'),
  ('United States', 'Zanesville Country Club'),
  ('United States', 'Zanesville Jaycees Public Golf Course'),
  ('United States', 'Zebulon Country Club'),
  ('United States', 'Zellwood Station Country Club'),
  ('United States', 'Zenwoods Golf Club'),
  ('United States', 'Zephyrhills City Golf Course'),
  ('United States', 'Zigfield Troy Par 3 Golf Course'),
  ('United States', 'Zintel Creek Golf Club'),
  ('United States', 'Zionsville Golf Course'),
  ('United States', 'Zollner Golf Course'),
  ('United States', 'Zumbro Valley Golf Course'),
  ('United States', 'Zumbrota Golf Club')
on conflict (country, name) do nothing;