insert into public.golf_courses (country, name) values
  ('United States', 'Oakhurst Golf & Country Club'),
  ('United States', 'Oakland Acres Golf Club'),
  ('United States', 'Oakland Beach Golf Club'),
  ('United States', 'Oakland Country Club'),
  ('United States', 'Oakland Golf Club'),
  ('United States', 'Oakland Hills Country Club'),
  ('United States', 'Oakland Plantation Country Club'),
  ('United States', 'Oakland Plantation Golf Course At Lsu'),
  ('United States', 'Oakland University Golf and Learning Center'),
  ('United States', 'Oakleaf Golf and Country Club'),
  ('United States', 'Oakleigh At The Villages Executive Golf Trail'),
  ('United States', 'Oakley Country Club'),
  ('United States', 'Oakmont Country Club'),
  ('United States', 'Oakmont East Golf Course'),
  ('United States', 'Oakmont Golf Center'),
  ('United States', 'Oakmont Green Golf Club'),
  ('United States', 'Oakmoore Golf Course'),
  ('United States', 'Oakridge Country Club'),
  ('United States', 'Oakridge Golf Course'),
  ('United States', 'Oaks At Ft Walton Beach Golf Club'),
  ('United States', 'Oaks At North Ridge Country Club'),
  ('United States', 'Oaks At Palm Aire Country Club'),
  ('United States', 'Oaks Canyon At Blacklake Golf Course'),
  ('United States', 'Oaks Country Club'),
  ('United States', 'Oaks Course At Stonegate Golf Club'),
  ('United States', 'Oaks Golf Club The'),
  ('United States', 'Oaks Golf Country Club'),
  ('United States', 'Oaks Golf Course'),
  ('United States', 'Oaks Lakes At North Ranch Country Club'),
  ('United States', 'Oaks Lakes At Valley Oaks Golf Club'),
  ('United States', 'Oaks National Golf Club'),
  ('United States', 'Oaks Palms At Hacienda Hills Golf Country Club'),
  ('United States', 'Oaksridge Golf Course'),
  ('United States', 'Oakton Driving Range'),
  ('United States', 'Oaktree Golf Club'),
  ('United States', 'Oaktree Golf Course'),
  ('United States', 'Oakview Golf Country Club'),
  ('United States', 'Oakview Lakes Golf Course'),
  ('United States', 'Oakview Links'),
  ('United States', 'Oakwing Golf Club'),
  ('United States', 'Oakwood Country Club'),
  ('United States', 'Oakwood Country Club Par 3 Course'),
  ('United States', 'Oakwood Golf Club'),
  ('United States', 'Oakwood Golf Course'),
  ('United States', 'Oakwood Park Golf Course'),
  ('United States', 'Oakwood Supper Club & Golf Course'),
  ('United States', 'Oakwoods Country Club'),
  ('United States', 'Oasis Country Club'),
  ('United States', 'Oasis Golf Club'),
  ('United States', 'Oasis Rv Park Golf Course'),
  ('United States', 'Oberlin Country Club'),
  ('United States', 'Oberlin Golf Club'),
  ('United States', 'Ocala Golf Club'),
  ('United States', 'Ocala National Golf Club'),
  ('United States', 'Ocala Palms Golf Club'),
  ('United States', 'Occano'),
  ('United States', 'Occoneechee Golf Club'),
  ('United States', 'Ocean Acres Country Club'),
  ('United States', 'Ocean At Ponte Vedra Inn Club'),
  ('United States', 'Ocean City Golf Club Newport Bay'),
  ('United States', 'Ocean City Golf Club Seaside'),
  ('United States', 'Ocean City Golf Course'),
  ('United States', 'Ocean Club At The Hutchinson Island Beach Resort And Marina'),
  ('United States', 'Ocean County Golf Course At Atlantis'),
  ('United States', 'Ocean County Golf Course At Forge Pond'),
  ('United States', 'Ocean Creek At Fripp Island Resort'),
  ('United States', 'Ocean Edge Resort Club On Cape Cod'),
  ('United States', 'Ocean Forest Golf Club'),
  ('United States', 'Ocean Hills Country Club'),
  ('United States', 'Ocean Palm Golf Course'),
  ('United States', 'Ocean Pines Golf Club'),
  ('United States', 'Ocean Point At Fripp Island Resort'),
  ('United States', 'Ocean Resorts Golf Club'),
  ('United States', 'Ocean Shores Golf Course'),
  ('United States', 'Ocean View Municipal Golf Course'),
  ('United States', 'Ocean Village Golf Course'),
  ('United States', 'Ocean Winds At Seabrook Island Resort'),
  ('United States', 'Oceana Golf Club'),
  ('United States', 'Oceans Golf Club'),
  ('United States', 'Oceanside Golf Country Club'),
  ('United States', 'Oceanside Golf Course'),
  ('United States', 'Ocilla Country Club'),
  ('United States', 'Oconee Country Club'),
  ('United States', 'Oconomowoc Golf Club'),
  ('United States', 'Ocotillo Golf Club Blue White'),
  ('United States', 'Ocotillo Golf Club Gold Blue'),
  ('United States', 'Ocotillo Golf Club White Gold'),
  ('United States', 'Odana Hills Golf Course'),
  ('United States', 'Odessa Golf Club Rv Park'),
  ('United States', 'Odessa National Golf Club'),
  ('United States', 'Odonnell Golf Club'),
  ('United States', 'Odyssey Country Club'),
  ('United States', 'Ogden Golf Country Club'),
  ('United States', 'Ogeechee Valley Country Club'),
  ('United States', 'Oglebay Resort Crispin Course'),
  ('United States', 'Oglebay Resort Crispin Golf Course'),
  ('United States', 'Oglebay Resort Par 3 Course'),
  ('United States', 'Oglebay Resort Speidel Golf Club Par 3 Course'),
  ('United States', 'Ohio Prestwick Country Club'),
  ('United States', 'Ohio State University Golf Course'),
  ('United States', 'Ohio University Driving Range'),
  ('United States', 'Ohio University Golf Course'),
  ('United States', 'Ohoopee Match Club'),
  ('United States', 'Oil Field Recreation Association Golf Course'),
  ('United States', 'Ojai Valley Inn'),
  ('United States', 'Ojibwa Golf & Bowl'),
  ('United States', 'Ojibwa Golf Bowl'),
  ('United States', 'Okanogan Valley Golf Club'),
  ('United States', 'Okatie Creek Golf Club'),
  ('United States', 'Okatoma Golf Club'),
  ('United States', 'Okeechobee At The Villages Executive Golf Trail'),
  ('United States', 'Okeene Golf Club'),
  ('United States', 'Okefenokee Country Club'),
  ('United States', 'Okemah Golf Course'),
  ('United States', 'Oklahoma City Golf Country Club'),
  ('United States', 'Okmulgee Country Club'),
  ('United States', 'Okoboji View Golf Course'),
  ('United States', 'Okolona Country Club'),
  ('United States', 'Old At Canongate On White Oak'),
  ('United States', 'Old At Country Club Of Scranton The'),
  ('United States', 'Old At Saucon Valley Country Club'),
  ('United States', 'Old At Saxon Golf Course'),
  ('United States', 'Old Avalon Golf Course'),
  ('United States', 'Old Baldy Club'),
  ('United States', 'Old Baldy Golf Course'),
  ('United States', 'Old Barnwell Old Barnwell Golf Course'),
  ('United States', 'Old Bridge Golf Club'),
  ('United States', 'Old Brockway Golf Course'),
  ('United States', 'Old Capital Golf Club'),
  ('United States', 'Old Channel Trail'),
  ('United States', 'Old Chatham Golf Club'),
  ('United States', 'Old Club Par 3 Course'),
  ('United States', 'Old Corkscrew Golf Club'),
  ('United States', 'Old Course Golf Course At Stonewall Links'),
  ('United States', 'Old Course Sauk Centre'),
  ('United States', 'Old Dane Golf Club'),
  ('United States', 'Old Edwards Club'),
  ('United States', 'Old Elm Club'),
  ('United States', 'Old Erie Golf Club'),
  ('United States', 'Old Field Short Course'),
  ('United States', 'Old Greenwood Golf Course'),
  ('United States', 'Old Hickory At Fort Jackson Golf Club'),
  ('United States', 'Old Hickory Golf Club'),
  ('United States', 'Old Landing Golf Course'),
  ('United States', 'Old Lyme Country Club'),
  ('United States', 'Old Marsh Country Club'),
  ('United States', 'Old Marsh Golf Club'),
  ('United States', 'Old Memorial Golf Club'),
  ('United States', 'Old Mill Golf Club'),
  ('United States', 'Old Mill Graveyard At Flat Creek Golf Club'),
  ('United States', 'Old North State Club At Uwharrie Point'),
  ('United States', 'Old Oak Country Club'),
  ('United States', 'Old Oakland Golf Club'),
  ('United States', 'Old Oaks Golf Course'),
  ('United States', 'Old Orange At Verandah'),
  ('United States', 'Old Orchard Country Club'),
  ('United States', 'Old Orchard GC'),
  ('United States', 'Old Palm Golf Club'),
  ('United States', 'Old Ranch Country Club'),
  ('United States', 'Old River Golf Course'),
  ('United States', 'Old Sandwich Golf Club'),
  ('United States', 'Old South Golf Links'),
  ('United States', 'Old Tabby Links'),
  ('United States', 'Old Tappan Golf Course'),
  ('United States', 'Old Toccoa Farm'),
  ('United States', 'Old Top Farm'),
  ('United States', 'Old Town Club'),
  ('United States', 'Old Town Golf Course'),
  ('United States', 'Old Trail Golf Club'),
  ('United States', 'Old Union Golf Course'),
  ('United States', 'Old Warson Country Club'),
  ('United States', 'Old Waverly Golf Club'),
  ('United States', 'Old Wayne Golf Course'),
  ('United States', 'Old Works'),
  ('United States', 'Old Works Little Bear'),
  ('United States', 'Old York Country Club'),
  ('United States', 'Old York Road Country Club'),
  ('United States', 'Olde Atlanta Golf Club'),
  ('United States', 'Olde Barnstable Fairgrounds Golf Club'),
  ('United States', 'Olde Beau Resort Golf Club'),
  ('United States', 'Olde Beaufort Golf Club'),
  ('United States', 'Olde Course At Loveland'),
  ('United States', 'Olde Dutch Mill Golf Course'),
  ('United States', 'Olde Eight'),
  ('United States', 'Olde English Trail Golf Club'),
  ('United States', 'Olde Florida Golf Club'),
  ('United States', 'Olde Fort Golf Course'),
  ('United States', 'Olde Hickory Golf Country Club'),
  ('United States', 'Olde Homeplace Golf Club'),
  ('United States', 'Olde Homestead Golf Club'),
  ('United States', 'Olde Kinderhook Golf Course'),
  ('United States', 'Olde Liberty Golf Country Club'),
  ('United States', 'Olde Mill Golf Club'),
  ('United States', 'Olde Mill Resort'),
  ('United States', 'Olde Oak Golf Club'),
  ('United States', 'Olde Oaks Golf Club Cypress Meadow'),
  ('United States', 'Olde Oaks Golf Club Cypress Oak'),
  ('United States', 'Olde Oaks Golf Club Meadow Oak'),
  ('United States', 'Olde Page At Page Belcher Golf Course'),
  ('United States', 'Olde Point Golf Country Club'),
  ('United States', 'Olde Salem Greens Golf Course'),
  ('United States', 'Olde Scotland Links At Bridgewater'),
  ('United States', 'Olde Stonewall Golf Club'),
  ('United States', 'Olde Sycamore Golf Club'),
  ('United States', 'Oldfield Club'),
  ('United States', 'Oldham County Country Club'),
  ('United States', 'Ole Miss Golf Course'),
  ('United States', 'Ole Monterey Golf Club'),
  ('United States', 'Olivas Links Golf Course'),
  ('United States', 'Olive Branch Country Club'),
  ('United States', 'Olive Glenn Golf Country Club'),
  ('United States', 'Olivet Country Club'),
  ('United States', 'Olomana Golf Links'),
  ('United States', 'Olympia Country Golf Club'),
  ('United States', 'Olympia Fields Country Club'),
  ('United States', 'Olympic Hills Golf Club'),
  ('United States', 'Olympic View Golf Club'),
  ('United States', 'Omaha Country Club'),
  ('United States', 'Omni Amelia Island Resort Spa Little Sandy Short Course'),
  ('United States', 'Omni Amelia Island Resort Spa Oak Marsh'),
  ('United States', 'Omni Bedford Springs Resort Old Course'),
  ('United States', 'Omni La Costa Resort Spa North Course'),
  ('United States', 'Omni La Costa Resort Spa South Course'),
  ('United States', 'Omni Rancho Las Palmas Resort North South'),
  ('United States', 'Omni Rancho Las Palmas Resort South West'),
  ('United States', 'Omni Rancho Las Palmas Resort West North'),
  ('United States', 'One East Course At Apple Greens Golf Course'),
  ('United States', 'One Two Course At Apple Greens Golf Course'),
  ('United States', 'Oneida Community Golf Club'),
  ('United States', 'Oneida Golf & Country Club'),
  ('United States', 'Oneka Ridge Golf Course'),
  ('United States', 'Oneonta Country Club'),
  ('United States', 'Onondaga Golf Country Club'),
  ('United States', 'Ontario Country Club'),
  ('United States', 'Onteora Club'),
  ('United States', 'Ontonagon Golf Club'),
  ('United States', 'Onwentsia Club'),
  ('United States', 'Ooltewah Club'),
  ('United States', 'Oquirrh Hills Golf Course'),
  ('United States', 'Orange At Ford Hill Country Club'),
  ('United States', 'Orange At Palmetto Pines Golf Course'),
  ('United States', 'Orange Beach Golf Center'),
  ('United States', 'Orange Blossom Hills Golf Country Club'),
  ('United States', 'Orange Hills Country Club'),
  ('United States', 'Orange Tree Golf Club'),
  ('United States', 'Orange Tree Golf Conference Resort'),
  ('United States', 'Orcas Island Country Golf Club'),
  ('United States', 'Orchard Creek'),
  ('United States', 'Orchard Creek Public Golf Club'),
  ('United States', 'Orchard Golf Country Club'),
  ('United States', 'Orchard Grove At Treesdale Golf Country Club'),
  ('United States', 'Orchard Hill Country Club'),
  ('United States', 'Orchard Hills Golf Club'),
  ('United States', 'Orchard Hills Golf Course'),
  ('United States', 'Orchard Lake Country Club'),
  ('United States', 'Orchard Park Country Club'),
  ('United States', 'Orchard Ponds Golf Club'),
  ('United States', 'Orchard Ridge Country Club'),
  ('United States', 'Orchard Trace Golf Club'),
  ('United States', 'Orchard Vali Golf Club'),
  ('United States', 'Orchard Valley Golf Course'),
  ('United States', 'Orchard Vally Golf Course'),
  ('United States', 'Orchards Executive Golf Course'),
  ('United States', 'Orchards Golf Club'),
  ('United States', 'Orchards at Egg Harbor'),
  ('United States', 'Orchid Island Golf Beach Club'),
  ('United States', 'Oregon Country Club'),
  ('United States', 'Oregon Trail Country Club'),
  ('United States', 'Orgill Golf Course'),
  ('United States', 'Origins Golf Club'),
  ('United States', 'Orinda Country Club'),
  ('United States', 'Oriole Golf Club'),
  ('United States', 'Oriskany Hill Golf Club'),
  ('United States', 'Orleans Country Club'),
  ('United States', 'Oro Valley Country Club'),
  ('United States', 'Orofino Golf Course'),
  ('United States', 'Orono Public Golf Course'),
  ('United States', 'Oroville Golf Club'),
  ('United States', 'Osage City Country Club'),
  ('United States', 'Osawatomie Golf Course'),
  ('United States', 'Osborne Country Club'),
  ('United States', 'Osceola Golf Course'),
  ('United States', 'Osceola Municipal Golf Course'),
  ('United States', 'Osgood Golf Course'),
  ('United States', 'Oshkosh Country Club'),
  ('United States', 'Oshux Golf'),
  ('United States', 'Osiris Country Club'),
  ('United States', 'Oskaloosa Golf'),
  ('United States', 'Oso Creek Golf Course'),
  ('United States', 'Osoyoos Golf And Country Club Desert Gold'),
  ('United States', 'Osoyoos Golf And Country Club Park Meadows'),
  ('United States', 'Osprey Heron At Okeeheelee Golf Course'),
  ('United States', 'Osprey Point At Kiawah Island Golf Resort'),
  ('United States', 'Osprey Point Golf Club Falcon Raven Course'),
  ('United States', 'Osprey Point Golf Club Hawk Falcon Course'),
  ('United States', 'Osprey Point Golf Club Hawk Raven Course'),
  ('United States', 'Osseo Golf Club'),
  ('United States', 'Oswego Country Club The'),
  ('United States', 'Oswego Golf Association'),
  ('United States', 'Othello Golf Club'),
  ('United States', 'Otsego Golf Club'),
  ('United States', 'Ottawa Golf Course'),
  ('United States', 'Ottawa Park Golf Course'),
  ('United States', 'Otte Golf & Family Fun Center'),
  ('United States', 'Otter Creek Golf Course'),
  ('United States', 'Otter Valley Country Club'),
  ('United States', 'Otterkill Golf Country Club'),
  ('United States', 'Ottumwa Country Club'),
  ('United States', 'Ouachita Country Club'),
  ('United States', 'Ould Newbury Golf Club'),
  ('United States', 'Ouleout Creek Golf Course'),
  ('United States', 'Outdoor Country Club'),
  ('United States', 'Outdoor Resort Indio'),
  ('United States', 'Outlaw At Paradise Pointe Golf Complex'),
  ('United States', 'Outlaw Course At Desert Mountain Golf Club'),
  ('United States', 'Outlaw Golf Club At Hideout Canyon Challenge Course'),
  ('United States', 'Over Lake Golf Course'),
  ('United States', 'Over Look Woods At Old Westbury Golf Country Club'),
  ('United States', 'Overbrook Golf Club'),
  ('United States', 'Overlake Golf Country Club'),
  ('United States', 'Overland Golf Course'),
  ('United States', 'Overland Park Golf Course'),
  ('United States', 'Overlook Golf Course'),
  ('United States', 'Overlook The'),
  ('United States', 'Overpeck Golf Course'),
  ('United States', 'Owasco Country Club'),
  ('United States', 'Owasso Golf Athletic Club'),
  ('United States', 'Owatonna Country Club'),
  ('United States', 'Owens Brockway Golf Course'),
  ('United States', 'Owensboro Country Club'),
  ('United States', 'Owl Creek Country Club'),
  ('United States', 'Owls Head Golf Club'),
  ('United States', 'Owls Nest Golf Club'),
  ('United States', 'Owosso Country Club'),
  ('United States', 'Oxbow Country Club'),
  ('United States', 'Oxbow Creek Golf Course'),
  ('United States', 'Oxbow Golf Course'),
  ('United States', 'Oxford Hills Country Club'),
  ('United States', 'Oxford Valley Golf Course'),
  ('United States', 'Oxmoor Country Club'),
  ('United States', 'Oyster Bay Golf Links'),
  ('United States', 'Oyster Bay Town Golf Course Clubhouse'),
  ('United States', 'Oyster Creek Golf Country Club'),
  ('United States', 'Oyster Harbors Club'),
  ('United States', 'Oyster Reef Golf Course'),
  ('United States', 'Ozark Recreation Association Club'),
  ('United States', 'Ozark Ridge Golf Course'),
  ('United States', 'Ozarks National'),
  ('United States', 'Ozaukee Country Club'),
  ('United States', 'O’Bannon Creek Golf Club'),
  ('United States', 'Paa Ko Ridge Golf Club Course 1'),
  ('United States', 'Paa Ko Ridge Golf Club Course 2'),
  ('United States', 'Paa Ko Ridge Golf Club Course 3'),
  ('United States', 'Pablo Creek Club'),
  ('United States', 'Pacific Grove Golf Links'),
  ('United States', 'Pacific Springs Golf Course'),
  ('United States', 'Packanack Golf Club'),
  ('United States', 'Packsaddle Ridge Golf Course'),
  ('United States', 'Paganica Golf Course'),
  ('United States', 'Paint Creek Country Club'),
  ('United States', 'Painted Desert Golf Club'),
  ('United States', 'Painted Dunes Desert Golf Club East West Course'),
  ('United States', 'Painted Dunes Desert Golf Course East North Course'),
  ('United States', 'Painted Dunes Desert Golf Course North West Course'),
  ('United States', 'Painted Hills Golf Club'),
  ('United States', 'Painted Mountain Golf Club'),
  ('United States', 'Pajaro Valley Golf Club'),
  ('United States', 'Pakachoag Golf Course'),
  ('United States', 'Pala Mesa Resort'),
  ('United States', 'Palacio Del Mar Golf Course'),
  ('United States', 'Palatine Hills Golf Course'),
  ('United States', 'Palatka Golf Club'),
  ('United States', 'Pali Municipal Golf Course'),
  ('United States', 'Palisade State Park Golf Course'),
  ('United States', 'Palisades Golf Course'),
  ('United States', 'Pallo''s Par 3 Golf Course'),
  ('United States', 'Palm At Angel Park Golf Club'),
  ('United States', 'Palm At Mccormick Ranch Golf Club'),
  ('United States', 'Palm Beach Country Club'),
  ('United States', 'Palm Beach Golf Course'),
  ('United States', 'Palm Beach National Golf Course'),
  ('United States', 'Palm Cove Golf And Yacht Club'),
  ('United States', 'Palm Creek Golf Club'),
  ('United States', 'Palm Desert Country Club'),
  ('United States', 'Palm Desert Greens Country Club'),
  ('United States', 'Palm Desert Resort Country Club'),
  ('United States', 'Palm Harbor Golf Club'),
  ('United States', 'Palm Hill Country Club'),
  ('United States', 'Palm Royale Country Club'),
  ('United States', 'Palm Valley Golf Club'),
  ('United States', 'Palm Valley Golf Club North South'),
  ('United States', 'Palm Valley Golf Club North West'),
  ('United States', 'Palm Valley Golf Club South West'),
  ('United States', 'Palma Ceia Golf Country Club'),
  ('United States', 'Palmbrook Golf Club'),
  ('United States', 'Palmer At Oasis Golf Club'),
  ('United States', 'Palmer Course At Wildfire Golf Club At Desert Ridge'),
  ('United States', 'Palmer Golf Course'),
  ('United States', 'Palmer Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Palmer Hills Golf Course')
on conflict (country, name) do nothing;