insert into public.golf_courses (country, name) values
  ('United States', 'Miami Shores Golf Course'),
  ('United States', 'Miami Springs Golf Country Club'),
  ('United States', 'Miami Valley Golf Club'),
  ('United States', 'Miami Whitewater Forest Golf Course'),
  ('United States', 'Miamiview Golf Course'),
  ('United States', 'Miccosukee Golf Country Club Barracuda Course'),
  ('United States', 'Miccosukee Golf Country Club Dolphin Course'),
  ('United States', 'Miccosukee Golf Country Club Marlin Course'),
  ('United States', 'Michaywe Pines'),
  ('United States', 'Michigan City Municipal Golf Course'),
  ('United States', 'Michigan Meadows Golf Course'),
  ('United States', 'Michipicoten Golf Club'),
  ('United States', 'Micke Grove Golf Links'),
  ('United States', 'Mickey S On Flambeau'),
  ('United States', 'Mickey''s Golf Range'),
  ('United States', 'Mickylee Pitch Putt At The Villages Executive Golf Trail'),
  ('United States', 'Mid Carolina Club'),
  ('United States', 'Mid Iron Golf Club'),
  ('United States', 'Mid Pacific Country Club'),
  ('United States', 'Mid Pines Inn Golf Club'),
  ('United States', 'Mid South Club'),
  ('United States', 'Mid Vallee Golf Course'),
  ('United States', 'Middle Back At Rolling Green Golf Club'),
  ('United States', 'Middle Channel Golf & Country Club'),
  ('United States', 'Middle Lake At Woodbridge Golf Country Club'),
  ('United States', 'Middle South At Heather Hill Country Club'),
  ('United States', 'Middlebrook Country Club'),
  ('United States', 'Middlecreek Golf Course'),
  ('United States', 'Middlefork Country Club'),
  ('United States', 'Middlesboro Country Club'),
  ('United States', 'Middleton Golf Course'),
  ('United States', 'Middletown Country Club'),
  ('United States', 'Midland Country Club'),
  ('United States', 'Midland Hills Country Club'),
  ('United States', 'Midland Trail Golf Club'),
  ('United States', 'Midland Valley Golf Club'),
  ('United States', 'Midlane Golf Resort'),
  ('United States', 'Midlothian Country Club'),
  ('United States', 'Midnight Sun Golf Course'),
  ('United States', 'Midvale Golf Country Club'),
  ('United States', 'Midville Country Club'),
  ('United States', 'Midway Golf Club'),
  ('United States', 'Midway Golf Complex'),
  ('United States', 'Midway Par 3 East Nine'),
  ('United States', 'Midway Par 3 Golf Course'),
  ('United States', 'Midway Par 3 North Nine'),
  ('United States', 'Midway Par 3 West Nine'),
  ('United States', 'Milan Creek Golf Course'),
  ('United States', 'Milbrook Club'),
  ('United States', 'Milburn Country Club'),
  ('United States', 'Mile Square Golf Course The Classic Course'),
  ('United States', 'Mile Square Golf Course The Players Course'),
  ('United States', 'Miles City Town Country Club'),
  ('United States', 'Miles Grant Country Club'),
  ('United States', 'Milestone Golf Club'),
  ('United States', 'Milford Country Club'),
  ('United States', 'Milham Park Golf Club'),
  ('United States', 'Mililani Golf Club'),
  ('United States', 'Militia Hill Golf Course At Philadelphia Cricket Club'),
  ('United States', 'Mill Creek Country Club'),
  ('United States', 'Mill Creek Golf Club'),
  ('United States', 'Mill Creek Golf Course'),
  ('United States', 'Mill Creek Golf Course (North)'),
  ('United States', 'Mill Creek Golf Course (South)'),
  ('United States', 'Mill Creek Metroparks Par-3 Golf Course'),
  ('United States', 'Mill Pond Golf Course'),
  ('United States', 'Mill Quarter Plantation Country Club'),
  ('United States', 'Mill Race Golf Camping Resort'),
  ('United States', 'Mill Race Golf Course'),
  ('United States', 'Mill River Club'),
  ('United States', 'Mill River Country Club'),
  ('United States', 'Mill Road Acres Golf Course'),
  ('United States', 'Mill Run Golf Course'),
  ('United States', 'Mill Valley Country Club'),
  ('United States', 'Mill Valley Golf Course'),
  ('United States', 'Millbrook Country Club'),
  ('United States', 'Millbrook Golf Tennis Club'),
  ('United States', 'Millburn Municipal Golf Course'),
  ('United States', 'Millcreek Golf And Learning Center'),
  ('United States', 'Millers Glen Golf Gourse'),
  ('United States', 'Mills Creek Golf Course'),
  ('United States', 'Millsite Golf Course'),
  ('United States', 'Millstone Executive Golf Course'),
  ('United States', 'Millstone Golf Course'),
  ('United States', 'Millwood Country Club'),
  ('United States', 'Millwood Farms Golf Course'),
  ('United States', 'Millwood Landing Golf Rv Resort'),
  ('United States', 'Milt''s Golf Course (9-Hole)'),
  ('United States', 'Milton Freewater Golf Course'),
  ('United States', 'Miltonvale Country Club'),
  ('United States', 'Milts Golf Center'),
  ('United States', 'Milwaukee Country Club'),
  ('United States', 'Mimosa Hills Golf Country Club'),
  ('United States', 'Minakwa Golf Course'),
  ('United States', 'Miner Hills Golf Course'),
  ('United States', 'Mineral Mound State Park Golf Course'),
  ('United States', 'Minerals Golf Club'),
  ('United States', 'Mines Golf Course'),
  ('United States', 'Mingo Bottom Golf Club'),
  ('United States', 'Mingo Springs Golf Course'),
  ('United States', 'Mini Golf'),
  ('United States', 'Mini-Golf'),
  ('United States', 'Mini-golf Course'),
  ('United States', 'Miniature Golf'),
  ('United States', 'Minibel Golf Course'),
  ('United States', 'Mink Lake Golf Course'),
  ('United States', 'Mink Meadows Golf Club'),
  ('United States', 'Minne Monesse Golf Club'),
  ('United States', 'Minneapolis Golf Club'),
  ('United States', 'Minneapolis Golf Course'),
  ('United States', 'Minnechaug Golf Course'),
  ('United States', 'Minnehaha Country Club'),
  ('United States', 'Minneopa Golf Club'),
  ('United States', 'Minnesota Valley Country Club'),
  ('United States', 'Minnesott Golf Country Club'),
  ('United States', 'Minnesuing Acres Conference Center'),
  ('United States', 'Minniwaska Golf Club'),
  ('United States', 'Minocqua Country Club'),
  ('United States', 'Minor Park Golf Course'),
  ('United States', 'Mint Valley Golf Course'),
  ('United States', 'Mint Valley Golf Course Executive Course'),
  ('United States', 'Mira Mesa At The Villages Executive Golf Trail'),
  ('United States', 'Mirabel Golf Club'),
  ('United States', 'Miracle Hill Driving Range'),
  ('United States', 'Miracle Hill Golf Course'),
  ('United States', 'Miramar Memorial Golf Course'),
  ('United States', 'Miromar Lakes Golf Club'),
  ('United States', 'Mirror Lake Golf Club Lake Course'),
  ('United States', 'Mirror Lake Golf Club Mountain Course'),
  ('United States', 'Mirror Lake Golf Course'),
  ('United States', 'Misquamicut Club'),
  ('United States', 'Missaukee Golf Club'),
  ('United States', 'Missing Links Golf Course'),
  ('United States', 'Mission Bay Golf Course'),
  ('United States', 'Mission Hills Country Club'),
  ('United States', 'Mission Hills Gary Player Course'),
  ('United States', 'Mission Hills Golf Course'),
  ('United States', 'Mission Hills Of Hayward Golf Course'),
  ('United States', 'Mission Inn Resort Club El Campeon Course'),
  ('United States', 'Mission Inn Resort Club Las Colinas Course'),
  ('United States', 'Mission Lake Country Club'),
  ('United States', 'Mission Lakes Country Club'),
  ('United States', 'Mission Mountain Golf Club'),
  ('United States', 'Mission Royale Golf Club'),
  ('United States', 'Mission Trails Golf Course'),
  ('United States', 'Mission Valley Golf Country Club'),
  ('United States', 'Mission Viejo Country Club'),
  ('United States', 'Mississippi National Golf Links'),
  ('United States', 'Mississippi State University Golf Club'),
  ('United States', 'Missoula Country Club'),
  ('United States', 'Missouri Bluffs Golf Club'),
  ('United States', 'Mistwood Golf Course'),
  ('United States', 'Misty Creek Country Club'),
  ('United States', 'Mizner Country Club'),
  ('United States', 'Moab Golf Club'),
  ('United States', 'Moanalua Golf Club'),
  ('United States', 'Moccasin Bend Golf Club'),
  ('United States', 'Moccasin Run Golf Course'),
  ('United States', 'Moccasin Wallow Golf Club'),
  ('United States', 'Modesto Municipal Golf Course'),
  ('United States', 'Moffett Field Golf Club'),
  ('United States', 'Mohansic Golf Course'),
  ('United States', 'Mohawk Glen Golf Course'),
  ('United States', 'Mohawk Golf and Country Club'),
  ('United States', 'Mohawk River Country Club Chateau'),
  ('United States', 'Mohawk Valley Country Club'),
  ('United States', 'Mohegan Sun Golf Club'),
  ('United States', 'Mohican Hills Golf Club'),
  ('United States', 'Mohonk Mountain House Golf Course'),
  ('United States', 'Moila Country Club'),
  ('United States', 'Mojave Resort Golf Club'),
  ('United States', 'Monadnock Country Club'),
  ('United States', 'Monarch Bay Golf Club Marina Course'),
  ('United States', 'Monarch Bay Golf Club Tony Lema Course'),
  ('United States', 'Monarch Beach Golf Links'),
  ('United States', 'Monarch Country Club'),
  ('United States', 'Monarch Dunes Golf Club The Challenge Course'),
  ('United States', 'Monarch Dunes Golf Club The Old Course'),
  ('United States', 'Monarch Golf Club At Royal Highlands'),
  ('United States', 'Monarch Ridge Golf Course'),
  ('United States', 'Money Hill Golf Country Club'),
  ('United States', 'Monmouth Country Club'),
  ('United States', 'Monona Golf Course'),
  ('United States', 'Monongahela Valley Country Club'),
  ('United States', 'Monoosnock Country Club'),
  ('United States', 'Monroe Country Club'),
  ('United States', 'Monroe Golf & Country Club'),
  ('United States', 'Monroe Golf Club'),
  ('United States', 'Monroe Golf Country Club'),
  ('United States', 'Monroeton Golf Club'),
  ('United States', 'Monster Golf Club At Resorts World Catskills'),
  ('United States', 'Montague Golf Club'),
  ('United States', 'Montammy Golf Club'),
  ('United States', 'Montauk Downs State Park'),
  ('United States', 'Montaup Country Club'),
  ('United States', 'Montcalm Golf Club'),
  ('United States', 'Montclair Golf Club'),
  ('United States', 'Montclair Golf Course'),
  ('United States', 'Monte Vista Country Club'),
  ('United States', 'Monte Vista Golf Club'),
  ('United States', 'Montecito Country Club'),
  ('United States', 'Monterey Country Club'),
  ('United States', 'Monterey Park Golf Course'),
  ('United States', 'Monterey Pines Golf Club'),
  ('United States', 'Monterey Yacht Country Club'),
  ('United States', 'Montezuma Country Club'),
  ('United States', 'Monticello Country Club'),
  ('United States', 'Monticello Golf Club'),
  ('United States', 'Monticello Golf Club At Savannah Lakes'),
  ('United States', 'Montour Heights Country Club'),
  ('United States', 'Montpelier Elks Country Club'),
  ('United States', 'Montpelier Golf Course'),
  ('United States', 'Montreux Golf Country Club'),
  ('United States', 'Monument At Adobe Creek National Golf Course'),
  ('United States', 'Monument At Troon North Golf Club'),
  ('United States', 'Monument Express At Troon North Golf Club'),
  ('United States', 'Monument Shadows Golf Course'),
  ('United States', 'Moody Quiet Pines Golf Course'),
  ('United States', 'Moon Brook Country Club'),
  ('United States', 'Moon Golf Club'),
  ('United States', 'Moon Walk At Moon Valley Country Club'),
  ('United States', 'Moor Downs Golf Course'),
  ('United States', 'Moore Golf Club'),
  ('United States', 'Moores Mill Golf Club'),
  ('United States', 'Moorestown Field Club'),
  ('United States', 'Mooresville Golf Club'),
  ('United States', 'Moorings Country Club'),
  ('United States', 'Moorland Road Golf Center'),
  ('United States', 'Moorpark Country Club The Canyon Crest Golf Course'),
  ('United States', 'Moorpark Country Club The Creekside Golf Course'),
  ('United States', 'Moorpark Country Club The Ridgeline Golf Course'),
  ('United States', 'Moors Golf Club'),
  ('United States', 'Moose Ridge Golf Course'),
  ('United States', 'Moose River Golf Course'),
  ('United States', 'Moose Run Golf Course Creek Course'),
  ('United States', 'Moose Run Golf Course Hill Course'),
  ('United States', 'Moraga Country Club'),
  ('United States', 'Moraine Country Club'),
  ('United States', 'Morees Cheraw Country Club'),
  ('United States', 'Morefar Golf Course'),
  ('United States', 'Morehead City Country Club'),
  ('United States', 'Morehouse Country Club'),
  ('United States', 'Morgan Creek Golf And Country Club'),
  ('United States', 'Morgan Creek Golf Course'),
  ('United States', 'Morgan Dairy Golf Club'),
  ('United States', 'Morgan Hill Golf Course'),
  ('United States', 'Morgan Hills Golf Course'),
  ('United States', 'Morgan River At Dataw Island Golf Course'),
  ('United States', 'Morgan S Crossing'),
  ('United States', 'Moriah Country Club'),
  ('United States', 'Morning Star Golf Course'),
  ('United States', 'Morningstar Golf''s Club'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Champions Course'),
  ('United States', 'Morongo Golf Club At Tukwet Canyon Legends Course'),
  ('United States', 'Morrilton Country Club'),
  ('United States', 'Morris County Golf Club'),
  ('United States', 'Morris Park Country Club'),
  ('United States', 'Morrisburg Golf Club'),
  ('United States', 'Morrison Lake Golf Club'),
  ('United States', 'Morro Bay Golf Course'),
  ('United States', 'Moscow Elks Golf Club'),
  ('United States', 'Moselem Springs Golf Club'),
  ('United States', 'Moses Lake Golf Club'),
  ('United States', 'Mosholu Golf Course'),
  ('United States', 'Moss Ridge'),
  ('United States', 'Mossland Memorial Golf Course'),
  ('United States', 'Mosswood Country Club'),
  ('United States', 'Mossy Creek Golf Club'),
  ('United States', 'Mossy Oak Golf Club'),
  ('United States', 'Motorcoach Country Club'),
  ('United States', 'Mound City Golf Club'),
  ('United States', 'Mound Golf Course'),
  ('United States', 'Mound Grove Golf Recreation'),
  ('United States', 'Mound View Golf Course'),
  ('United States', 'Mounds Ditches At Brickyard Plantation Golf Club'),
  ('United States', 'Moundsville Country Club'),
  ('United States', 'Mount Airy Country Club'),
  ('United States', 'Mount Airy Golf Club'),
  ('United States', 'Mount Ayr Golf and Country Club'),
  ('United States', 'Mount Carmel Municipal Golf Course'),
  ('United States', 'Mount Cashmere Golf Course'),
  ('United States', 'Mount Dora Golf Club'),
  ('United States', 'Mount Douglas Golf Course'),
  ('United States', 'Mount Fairweather Golf Course'),
  ('United States', 'Mount Frontenac Golf Course'),
  ('United States', 'Mount Hawley Country Club'),
  ('United States', 'Mount Hood Golf Course'),
  ('United States', 'Mount Huff Golf Course'),
  ('United States', 'Mount Kisco Country Club'),
  ('United States', 'Mount Lebanon Golf Course'),
  ('United States', 'Mount Massive Golf Course'),
  ('United States', 'Mount Mitchell Golf Club'),
  ('United States', 'Mount Odin Golf Course'),
  ('United States', 'Mount Ogden Golf Course'),
  ('United States', 'Mount Pleasant At Mount Washington Hotel Resort'),
  ('United States', 'Mount Pleasant Country Club'),
  ('United States', 'Mount Pleasant Golf & Country Club'),
  ('United States', 'Mount Pocono Public Golf Course'),
  ('United States', 'Mount Prospect Golf Course'),
  ('United States', 'Mount Saint Helena Golf Course'),
  ('United States', 'Mount Shasta Resort'),
  ('United States', 'Mount Si Golf Course'),
  ('United States', 'Mount Snow Golf Club'),
  ('United States', 'Mount Summit Golf Course'),
  ('United States', 'Mount Tabor Country Club'),
  ('United States', 'Mount Vernon Country Club'),
  ('United States', 'Mount Vintage Golf Club Chester Course'),
  ('United States', 'Mount Vintage Golf Club Independent Course'),
  ('United States', 'Mount Vintage Golf Club Vintage Course'),
  ('United States', 'Mount Washington At Mount Washington Hotel Resort'),
  ('United States', 'Mountain Air Country Club'),
  ('United States', 'Mountain Aire Golf Club'),
  ('United States', 'Mountain At Angel Park Golf Club'),
  ('United States', 'Mountain At Cordillera Golf Course'),
  ('United States', 'Mountain At Incline Village Golf Resort'),
  ('United States', 'Mountain At Wasatch Mountain State Park'),
  ('United States', 'Mountain Brook Golf Club'),
  ('United States', 'Mountain Falls Golf Course'),
  ('United States', 'Mountain Flowers'),
  ('United States', 'Mountain Forest At Stratton Mountain Country Club'),
  ('United States', 'Mountain Glen Golf Course'),
  ('United States', 'Mountain Harbour Golf Club'),
  ('United States', 'Mountain Lake'),
  ('United States', 'Mountain Lake At Pinery Country Club'),
  ('United States', 'Mountain Lake Golf Course'),
  ('United States', 'Mountain Laurel Golf Club'),
  ('United States', 'Mountain Meadows Golf Course'),
  ('United States', 'Mountain Ranch Golf Club At Fairfield Bay'),
  ('United States', 'Mountain Ridge'),
  ('United States', 'Mountain Ridge Country Club'),
  ('United States', 'Mountain Shadows Golf Course'),
  ('United States', 'Mountain Springs At Grandfather Golf Country Club'),
  ('United States', 'Mountain Top Course'),
  ('United States', 'Mountain Top Golf Course'),
  ('United States', 'Mountain Valley Golf Center'),
  ('United States', 'Mountain Valley Golf Course Mountain Course'),
  ('United States', 'Mountain Valley Golf Course Valley Course'),
  ('United States', 'Mountain View At Callaway Gardens Resort'),
  ('United States', 'Mountain View At Desert Willow Golf Resort'),
  ('United States', 'Mountain View Country Club'),
  ('United States', 'Mountain View Golf Club'),
  ('United States', 'Mountain View Golf Course'),
  ('United States', 'Mountain View Grand Golf Course'),
  ('United States', 'Mountain Vista Golf Club San Gorgonio Course'),
  ('United States', 'Mountain Vista Golf Club Santa Rosa Course'),
  ('United States', 'Mountain Vista Greens Golf Course'),
  ('United States', 'Mountaineer Golf Country Club'),
  ('United States', 'Mountaineer Woodview Golf Course'),
  ('United States', 'Mountaineers Woodview Golf Course'),
  ('United States', 'Mountaintop Golf Lake Club'),
  ('United States', 'Mountainview Country Club'),
  ('United States', 'Mountainview Par 3 Gramling Course'),
  ('United States', 'Mozingo Lake Recreation Watson 9 Course'),
  ('United States', 'Mr Golfs Ultimate Range'),
  ('United States', 'Mr. Golf'),
  ('United States', 'Mt Adams Country Club'),
  ('United States', 'Mt Anthony Golf Tennis Club'),
  ('United States', 'Mt Freedom Golf'),
  ('United States', 'Mt Graham Golf Course'),
  ('United States', 'Mt Hope Golf Course'),
  ('United States', 'Mt Kineo Golf Course'),
  ('United States', 'Mt Meadows Golf Course'),
  ('United States', 'Mt Pleasant Golf Club'),
  ('United States', 'Mt Whitney Golf Club'),
  ('United States', 'Mt Woodson Golf Club'),
  ('United States', 'Mud Run Golf Course'),
  ('United States', 'Mueller''s Valley View Farm Golf Course'),
  ('United States', 'Muirfield Village Golf Club'),
  ('United States', 'Mulberry Hills Golf Course'),
  ('United States', 'Muleshoe Country Club'),
  ('United States', 'Mulholland Hills Country Club Canyons'),
  ('United States', 'Mulholland Hills Country Club Trails'),
  ('United States', 'Mulholland Hills Country Club Vista'),
  ('United States', 'Mullenhurst Golf Course'),
  ('United States', 'Mullett Lake Country Club'),
  ('United States', 'Mulligan S Pointe'),
  ('United States', 'Mulligan''s Fairway'),
  ('United States', 'Mulligans Creekside Golf Center'),
  ('United States', 'Mulligans Island Par 3 Course'),
  ('United States', 'Muncie Elks Country Club'),
  ('United States', 'Munoscong Golf Club'),
  ('United States', 'Muroc Lake Golf Course'),
  ('United States', 'Murphy Creek Golf Course'),
  ('United States', 'Murphys Garrison Golf Center'),
  ('United States', 'Murray Parkway Golf Course'),
  ('United States', 'Murrysville Golf Club'),
  ('United States', 'Muscatine Municipal Golf Course'),
  ('United States', 'Musgrove Mill Golf Club'),
  ('United States', 'Muskeg Meadows Golf Course'),
  ('United States', 'Muskego Lakes Country Club'),
  ('United States', 'Muskegon Country Club'),
  ('United States', 'Muskogee Country Club'),
  ('United States', 'Muttontown Golf Country Club'),
  ('United States', 'Myerlee Country Club'),
  ('United States', 'Myers Park Country Club'),
  ('United States', 'Mylora Golf Course'),
  ('United States', 'Mylora On No 5 Road'),
  ('United States', 'Myopia Hunt Club'),
  ('United States', 'Myrick Hills Country Club'),
  ('United States', 'Myrtle Beach National Golf Club Kings North Course')
on conflict (country, name) do nothing;