insert into public.golf_courses (country, name) values
  ('United States', 'The Omni Homestead Resort Spa Old Course'),
  ('United States', 'The Orchards At Egg Harbor'),
  ('United States', 'The Orchards Golf Club'),
  ('United States', 'The Orchards Golf Course'),
  ('United States', 'The Osprey At Haig Point Club'),
  ('United States', 'The Outlaw At Alto Lakes'),
  ('United States', 'The Palencia Club'),
  ('United States', 'The Palisades Country Club'),
  ('United States', 'The Palms Course'),
  ('United States', 'The Palms Golf Club'),
  ('United States', 'The Palms Golf Club At Forest Lakes'),
  ('United States', 'The Panther At Plantation Golf Country Club'),
  ('United States', 'The Par 3 At Pipestem State Park Resort'),
  ('United States', 'The Park Country Club'),
  ('United States', 'The Park West Palm'),
  ('United States', 'The Park West Palm The Lit 9'),
  ('United States', 'The Patriot Golf Club At Grand Harbor'),
  ('United States', 'The Pearl Club'),
  ('United States', 'The Pearl Golf Links East Course'),
  ('United States', 'The Pearl Golf Links North Course'),
  ('United States', 'The Pearl Golf Links West Course'),
  ('United States', 'The Peninsula Club'),
  ('United States', 'The Peninsula On The Indian River Bay Golf Club'),
  ('United States', 'The Pheasant Golf Links Front Back Course'),
  ('United States', 'The Pheasant Golf Links Roc Course'),
  ('United States', 'The Phoenician Golf Club'),
  ('United States', 'The Piedmont Club'),
  ('United States', 'The Pines'),
  ('United States', 'The Pines At Elizabeth City'),
  ('United States', 'The Pines At Lindsey Wilson'),
  ('United States', 'The Pines At North Park'),
  ('United States', 'The Pines Country Club'),
  ('United States', 'The Pines Golf Club'),
  ('United States', 'The Pines Golf Course'),
  ('United States', 'The Pines Golf Course At Fort Eustis Ponderosa Pines Shortleaf Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Ponderosa Pines'),
  ('United States', 'The Pines Golf Course At Fort Eustis Virginia Pines Shortleaf Pines'),
  ('United States', 'The Pines Of Chatom Golf Course'),
  ('United States', 'The Plantation Course At Edisto'),
  ('United States', 'The Plantation Golf And Country Club'),
  ('United States', 'The Plantation Golf Club Cranes Roost Course'),
  ('United States', 'The Plantation Golf Club Otter Creek Course'),
  ('United States', 'The Plateau Club'),
  ('United States', 'The Players Club'),
  ('United States', 'The Players Club at Foxfire'),
  ('United States', 'The Players Club at Woodland Trails'),
  ('United States', 'The Players Course At Wyboo'),
  ('United States', 'The Poconos Club'),
  ('United States', 'The Pointe Golf Club'),
  ('United States', 'The Pointe Golf Course'),
  ('United States', 'The Pointe Golf Event Center'),
  ('United States', 'The Polo Fields - Ann Arbor'),
  ('United States', 'The Ponds at Battle Creek'),
  ('United States', 'The Powder Horn Golf Club Eagle Nine'),
  ('United States', 'The Powder Horn Golf Club Mountain Nine'),
  ('United States', 'The Powder Horn Golf Club Stag Nine'),
  ('United States', 'The Practice Center - Clear Creek'),
  ('United States', 'The Practice Tee At Sunset Hills'),
  ('United States', 'The Prairie Club Dunes Course'),
  ('United States', 'The Prairie Club Horse Course'),
  ('United States', 'The Prairies Golf Club'),
  ('United States', 'The Prairies Golf Course'),
  ('United States', 'The Preserve'),
  ('United States', 'The Preserve At Boulder Hills'),
  ('United States', 'The Preserve At Ironhorse'),
  ('United States', 'The Preserve At Jordan Lake Golf Club'),
  ('United States', 'The Preserve At Oak Meadows'),
  ('United States', 'The Preserve At Turnbull Bay'),
  ('United States', 'The Preserve At Verdae'),
  ('United States', 'The Preserve Golf Club'),
  ('United States', 'The Preserve On Rathbun Lake'),
  ('United States', 'The Preserve at Oak Meadows'),
  ('United States', 'The Quarry'),
  ('United States', 'The Quarry At La Quinta'),
  ('United States', 'The Quarry At La Quinta Short Course'),
  ('United States', 'The Quarry Golf Club'),
  ('United States', 'The Quarry at Crystal Springs'),
  ('United States', 'The Quechee Club Highland Course'),
  ('United States', 'The Quechee Club Lakeland Course'),
  ('United States', 'The Quest Golf Club'),
  ('United States', 'The Rail Golf Course'),
  ('United States', 'The Ranch At Laguna Beach'),
  ('United States', 'The Ranch Club'),
  ('United States', 'The Ranch Country Club'),
  ('United States', 'The Ranch Golf Club'),
  ('United States', 'The Ranches Golf Club'),
  ('United States', 'The Raven Golf Club At Three Peaks'),
  ('United States', 'The Ravines Golf Course'),
  ('United States', 'The Refuge Golf Course'),
  ('United States', 'The Reserve At Lake Keowee'),
  ('United States', 'The Reserve At Moonlight Basin Golf Club'),
  ('United States', 'The Reserve At Orange Lake Resort'),
  ('United States', 'The Reserve At Spanos Park'),
  ('United States', 'The Reserve Club'),
  ('United States', 'The Reserve Club At Woodside Plantation Hollow Creek Course'),
  ('United States', 'The Reserve Club At Woodside Plantation The Reserve Course'),
  ('United States', 'The Reserve Golf Club'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Blue Heron Red Hawk'),
  ('United States', 'The Resort At Longboat Key Club Harbourside Red Hawk White Egret'),
  ('United States', 'The Resort At Longboat Key Club Harbourside White Egret Blue Heron'),
  ('United States', 'The Resort At Longboat Key Club Links On Longboat'),
  ('United States', 'The Retreat'),
  ('United States', 'The Revenge'),
  ('United States', 'The Revival Golf Club At The Crescent'),
  ('United States', 'The Ridge'),
  ('United States', 'The Ridge At Back Brook'),
  ('United States', 'The Ridge At Castle Pines Colorado'),
  ('United States', 'The Ridge Country Club'),
  ('United States', 'The Ridge Golf Club'),
  ('United States', 'The Ridge Golf Course Events Center'),
  ('United States', 'The Ridges At Village Creek North Ridge East Ridge'),
  ('United States', 'The Ridges At Village Creek North Ridge West Ridge'),
  ('United States', 'The Ridges At Village Creek West Ridge East Ridge'),
  ('United States', 'The Ridges Golf Course'),
  ('United States', 'The Rim Golf Club'),
  ('United States', 'The Ritz Carlton Golf Club Orlando Grande Lakes'),
  ('United States', 'The River At Grand Harbor Golf Beach Club'),
  ('United States', 'The River Club'),
  ('United States', 'The River Club Golf Course'),
  ('United States', 'The River Course At Keystone'),
  ('United States', 'The River Golf Club'),
  ('United States', 'The River Golf Course, Inc.'),
  ('United States', 'The Rivercrest Golf Club And Preserve'),
  ('United States', 'The Riverside Club of West Virginia'),
  ('United States', 'The Riviera Country Club'),
  ('United States', 'The Rock Golf Club'),
  ('United States', 'The Rock Golf Club Resort'),
  ('United States', 'The Rock Golf Course'),
  ('United States', 'The Rockland Farm Course At Shenandoah Valley'),
  ('United States', 'The Rookery At Marco'),
  ('United States', 'The Rookery South'),
  ('United States', 'The Rose Golf Course'),
  ('United States', 'The Royal'),
  ('United States', 'The Royal Ancient Chappaquiddick Links'),
  ('United States', 'The Royal Virginian Golf Course'),
  ('United States', 'The Running Y Ranch Golf Course'),
  ('United States', 'The Saddle At Glencove'),
  ('United States', 'The Saints At Port St Lucie'),
  ('United States', 'The Salt Pond Golf Club'),
  ('United States', 'The Sanctuary'),
  ('United States', 'The Sanctuary Golf Club'),
  ('United States', 'The Sanctuary Golf Course At Pennbrooke Fairways'),
  ('United States', 'The Sands Golf Rv Resort'),
  ('United States', 'The Santaluz Club'),
  ('United States', 'The Savannah Golf Club'),
  ('United States', 'The Savannahs Golf Course'),
  ('United States', 'The Sawmill Golf Club'),
  ('United States', 'The Schoolhouse Nine'),
  ('United States', 'The Sea Ranch Golf Links'),
  ('United States', 'The Sedgewood Golf Club'),
  ('United States', 'The Senator Course At Shulas Golf Club'),
  ('United States', 'The Serradella'),
  ('United States', 'The Shoe Course At Golden Horseshoe Golf Club'),
  ('United States', 'The Shore Club'),
  ('United States', 'The Shores Of North River Golf Club'),
  ('United States', 'The Sidewinder Golf Course'),
  ('United States', 'The Silverleaf Golf Club'),
  ('United States', 'The Sound Golf Links At Albemarle Plantation'),
  ('United States', 'The South East At Upper Montclair Country Club'),
  ('United States', 'The Springs At Borrego'),
  ('United States', 'The Springs Club'),
  ('United States', 'The Spruce Creek Preserve Golf Club'),
  ('United States', 'The St Anne S Club'),
  ('United States', 'The Stadium Course At Pga West'),
  ('United States', 'The Summit'),
  ('United States', 'The Summit Club'),
  ('United States', 'The Swan Golf Country Club'),
  ('United States', 'The Tamaracks Golf Course'),
  ('United States', 'The Tattersall Youth Development Center At The First Tee Chesterfield Golf Course'),
  ('United States', 'The Territory'),
  ('United States', 'The Tesoro Club Palmer Course'),
  ('United States', 'The Tesoro Club Watson Course'),
  ('United States', 'The Third Golf Course'),
  ('United States', 'The Tillery Tradition Country Club'),
  ('United States', 'The Timbers Golf Club'),
  ('United States', 'The Titus Course At Shenandoah Valley Golf Club'),
  ('United States', 'The Tradition Golf Club'),
  ('United States', 'The Traditional'),
  ('United States', 'The Trails Golf Club'),
  ('United States', 'The Tree Farm'),
  ('United States', 'The Tribute'),
  ('United States', 'The Trophy Club Of Apalachee'),
  ('United States', 'The Trophy Club Of Atlanta'),
  ('United States', 'The Tuxedo Club'),
  ('United States', 'The Valley At Eastport Golf Club'),
  ('United States', 'The Valley Club North Course'),
  ('United States', 'The Valley Club South Course'),
  ('United States', 'The Valley Club West Course'),
  ('United States', 'The Valley Golf Course'),
  ('United States', 'The Views Golf Club At Oro Valley'),
  ('United States', 'The Village Course At Waikoloa'),
  ('United States', 'The Village Of Fenney Gray Fox Course'),
  ('United States', 'The Village Of Fenney Red Fox Course'),
  ('United States', 'The Vineyard At Escondido'),
  ('United States', 'The Vineyards Golf Club'),
  ('United States', 'The Vintage At Staples'),
  ('United States', 'The Vintage Club Desert Course'),
  ('United States', 'The Vintage Club Mountain Course'),
  ('United States', 'The Virginian Golf Club'),
  ('United States', 'The Virtues Golf Club'),
  ('United States', 'The Vue'),
  ('United States', 'The Walker Golf Course At Clemson University'),
  ('United States', 'The Wanderers Club At Wellington'),
  ('United States', 'The Water S Edge Country Club'),
  ('United States', 'The Waterfront Country Club'),
  ('United States', 'The Wedgewood Club'),
  ('United States', 'The West South At Upper Montclair Country Club'),
  ('United States', 'The Wetlands Golf Course'),
  ('United States', 'The Wilderness at Fortune Bay'),
  ('United States', 'The Wilds'),
  ('United States', 'The Willows At Runk Pratt'),
  ('United States', 'The Windermere Club'),
  ('United States', 'The Wizard Golf Course'),
  ('United States', 'The Wolf At Tenkiller'),
  ('United States', 'The Wolverine Golf Course'),
  ('United States', 'The Wood'),
  ('United States', 'The Woodlands Golf Club'),
  ('United States', 'The Woodlands Golf Country Club'),
  ('United States', 'The Woods Golf Club'),
  ('United States', 'The Woods Of Westminster'),
  ('United States', 'The Woods Resort Mountain View Course'),
  ('United States', 'The Woods Resort Stony Lick Course'),
  ('United States', 'The Woods at Possum Run'),
  ('United States', 'The Wyndgate'),
  ('United States', 'The Yards'),
  ('United States', 'Thendara Golf Club'),
  ('United States', 'Theodore Wirth Golf Course'),
  ('United States', 'Third First At Lake Venice Golf Club'),
  ('United States', 'Third Nine At Edison Club The'),
  ('United States', 'Third Nine At Montclair Golf Club'),
  ('United States', 'Third Nine At Pleasant Valley Country Club'),
  ('United States', 'Third Nine First Nine At Bermuda Dunes Country Club'),
  ('United States', 'Thistle Foxglove At Resort At The Mountain The'),
  ('United States', 'Thistle Golf Club Cameron Course'),
  ('United States', 'Thistle Golf Club Mackay Course'),
  ('United States', 'Thistle Golf Club Stewart Course'),
  ('United States', 'Thomas Memorial Golf Country Club'),
  ('United States', 'Thomson Country Club'),
  ('United States', 'Thorn Apple Country Club'),
  ('United States', 'Thorn Spring Golf Course'),
  ('United States', 'Thornberry Creek Country Club'),
  ('United States', 'Thornblade Club'),
  ('United States', 'Thorncreek Golf Club'),
  ('United States', 'Thorndale Country Club'),
  ('United States', 'Thorne Hills Golf Course'),
  ('United States', 'Thornhurst Country Club'),
  ('United States', 'Thorny Lea Golf Club'),
  ('United States', 'Thoroughbred Golf Club'),
  ('United States', 'Thousand Acres Golf Club'),
  ('United States', 'Thousand Hills Resort Golf Club'),
  ('United States', 'Thousand Islands Country Club The Lake Course'),
  ('United States', 'Thousand Islands Country Club The Old Course'),
  ('United States', 'Thousand Oaks Golf Club'),
  ('United States', 'Three Crowns Golf Club'),
  ('United States', 'Three Eagles Golf Course'),
  ('United States', 'Three Elms Golf Course'),
  ('United States', 'Three Lakes Golf Course'),
  ('United States', 'Three Pines Country Club'),
  ('United States', 'Three Ponds Farm'),
  ('United States', 'Three Ponds Golf Club'),
  ('United States', 'Three Rivers Country Club'),
  ('United States', 'Three Rivers Golf Course'),
  ('United States', 'Three Sticks Golf Club'),
  ('United States', 'Thumper Pond'),
  ('United States', 'Thunder Bay Resort'),
  ('United States', 'Thunder Bayou Golf Links'),
  ('United States', 'Thunder Hills Country Club'),
  ('United States', 'Thunder Mountain Ranch Buckaroo Greens'),
  ('United States', 'Thunderbird At Spring Lake Golf Club'),
  ('United States', 'Thunderbird Country Club'),
  ('United States', 'Thunderbird Driving Range'),
  ('United States', 'Thunderbird Golf Course Resort'),
  ('United States', 'Thunderbird North'),
  ('United States', 'Thunderbird South'),
  ('United States', 'Thunderbolt Pass Golf Course'),
  ('United States', 'Thunderhart Golf Course'),
  ('United States', 'Thunderhawk Golf Club'),
  ('United States', 'Thundering Waters Golf Club'),
  ('United States', 'Tianna Country Club'),
  ('United States', 'Tiara Rado Golf Course'),
  ('United States', 'Tiburon Golf Club The Black Course'),
  ('United States', 'Tiburon Golf Club The Gold Course'),
  ('United States', 'Tiburon Golf Course'),
  ('United States', 'Ticonderoga Country Club'),
  ('United States', 'Tidelands Golf Country Club'),
  ('United States', 'Tidewater Golf Club'),
  ('United States', 'Tierra Del Sol Golf Club'),
  ('United States', 'Tierra Del Sol Golf Country Club'),
  ('United States', 'Tierra Del Sol Golf Course'),
  ('United States', 'Tierra Grande Country Club'),
  ('United States', 'Tierra Rejada Golf Club'),
  ('United States', 'Tiffany Greens Golf Club'),
  ('United States', 'Tiger Point Golf Club'),
  ('United States', 'Tigers Eye Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Tijeras Arroyo Golf Course'),
  ('United States', 'Tijeras Creek Golf Club'),
  ('United States', 'Tilbury Golf Course'),
  ('United States', 'Tilden Park Golf Course'),
  ('United States', 'Timber Banks Golf Club Marina'),
  ('United States', 'Timber City Golf Course'),
  ('United States', 'Timber Creek'),
  ('United States', 'Timber Creek Golf'),
  ('United States', 'Timber Creek Golf Course'),
  ('United States', 'Timber Creek Golf Course Lakes Oaks'),
  ('United States', 'Timber Creek Golf Course Sierra Pines'),
  ('United States', 'Timber Greens Country Club'),
  ('United States', 'Timber Lake Club'),
  ('United States', 'Timber Lake Golf Course'),
  ('United States', 'Timber Pines The Grand Pines Course'),
  ('United States', 'Timber Pines The Highlands Course'),
  ('United States', 'Timber Pines The Hills Course'),
  ('United States', 'Timber Pines The Lakes Course'),
  ('United States', 'Timber Ridge Golf Club'),
  ('United States', 'Timber Terrace Golf Course'),
  ('United States', 'Timber Trace Golf Club'),
  ('United States', 'Timber Trails Golf Club'),
  ('United States', 'Timber Truss Golf Course'),
  ('United States', 'Timber Wolf Golf Club'),
  ('United States', 'Timbergate Golf Course'),
  ('United States', 'Timberlake Country Club'),
  ('United States', 'Timberlake Golf Club'),
  ('United States', 'Timberlane Golf Recreation'),
  ('United States', 'Timberlin Golf Club'),
  ('United States', 'Timberline Golf Course'),
  ('United States', 'Timberline Short Nine'),
  ('United States', 'Timberlink Golf Course'),
  ('United States', 'Timberon Golf Country Club'),
  ('United States', 'Timberstone'),
  ('United States', 'Timberstone Golf Course'),
  ('United States', 'Timberton Golf Club'),
  ('United States', 'Timberview Golf Club'),
  ('United States', 'Timberwood Golf Club'),
  ('United States', 'Timpanogos Golf Club The Championship Course'),
  ('United States', 'Timpanogos Golf Club The Pasture Executive Course'),
  ('United States', 'Timuquana Country Club'),
  ('United States', 'Tin Cup Golf Driving Range'),
  ('United States', 'Tincap Golf Club'),
  ('United States', 'Tinker Afb Golf Course'),
  ('United States', 'Tioga Golf Club'),
  ('United States', 'Tippecanoe Country Club'),
  ('United States', 'Tippecanoe Lake Country Club'),
  ('United States', 'Tipsinah Mounds'),
  ('United States', 'Tipton Golf and Country Club'),
  ('United States', 'Tipton Municipal Golf Course'),
  ('United States', 'Tired Creek Golf Course'),
  ('United States', 'Tishomingo Golf Course'),
  ('United States', 'Toad Valley Golf Course'),
  ('United States', 'Toana Vista Golf Course'),
  ('United States', 'Tobacco Road Golf Club'),
  ('United States', 'Todd Creek Golf Club'),
  ('United States', 'Toddy Brook Golf Course'),
  ('United States', 'Toftrees Resort'),
  ('United States', 'Toiyabe Golf Club'),
  ('United States', 'Toka Sticks Golf Club'),
  ('United States', 'Toledo Country Club'),
  ('United States', 'Tom & Jerry''s Mini Golf'),
  ('United States', 'Tom Oleary Golf Club'),
  ('United States', 'Tomah VA Veterans Golf Course'),
  ('United States', 'Tomahawk Hills Golf Course'),
  ('United States', 'Tommy Jacobs Bel Air Greens'),
  ('United States', 'Toms River Country Club'),
  ('United States', 'Toms Run At Chestnut Ridge Golf Resort Conference Center'),
  ('United States', 'Toomey Flynn At Huntingdon Valley Country Club'),
  ('United States', 'Tooth 9 Hole Course At Orange County National'),
  ('United States', 'Top Of The Rock Golf Course'),
  ('United States', 'Top Of The World Golf Course'),
  ('United States', 'Topeka Country Club'),
  ('United States', 'Topstone Golf Course'),
  ('United States', 'Torch'),
  ('United States', 'Torreon Golf Club Cabin Course'),
  ('United States', 'Torreon Golf Club Tower Course'),
  ('United States', 'Torres Blancas Golf Club'),
  ('United States', 'Torrey Oaks Rv And Golf Resort'),
  ('United States', 'Torri Erinn At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Torrington Country Club'),
  ('United States', 'Tortoise Hare At On Top Of The World'),
  ('United States', 'Tortuga At Haven Public Golf Club'),
  ('United States', 'Toscana Country Club North Course'),
  ('United States', 'Toscana Country Club South Course'),
  ('United States', 'Tot Hill Farm Golf Club'),
  ('United States', 'Totteridge Golf Course'),
  ('United States', 'Touchet Valley Golf Course'),
  ('United States', 'Touisset Country Club'),
  ('United States', 'Tournament At Burns Park Golf Course'),
  ('United States', 'Tournament Club of Iowa'),
  ('United States', 'Tournament Player’s Club at River’s Bend'),
  ('United States', 'Towanda Country Club'),
  ('United States', 'Tower Tee'),
  ('United States', 'Tower Tee Golf & Recreation'),
  ('United States', 'Towers Country Club'),
  ('United States', 'Town & Country Club'),
  ('United States', 'Town & Country Golf Course'),
  ('United States', 'Town Country Golf Links'),
  ('United States', 'Town Of Wallkill Golf Club'),
  ('United States', 'Town Park Villas Golf Course'),
  ('United States', 'Town and Country Golf Club'),
  ('United States', 'Towne Lake Hills Golf Club'),
  ('United States', 'Townsend Ridge Country Club'),
  ('United States', 'Tpc Boston'),
  ('United States', 'Tpc Colorado')
on conflict (country, name) do nothing;