insert into public.golf_courses (country, name) values
  ('United States', '"The Old Course" at Sugar Loaf'),
  ('United States', '1 10 At University Park Country Club'),
  ('United States', '1 At Ponkapoag Golf Club'),
  ('United States', '10 19 At University Park Country Club'),
  ('United States', '12 Oaks'),
  ('United States', '1757 Golf Club'),
  ('United States', '18 Mile Creek Golf Course'),
  ('United States', '19 1 At University Park Country Club'),
  ('United States', '19th Hole Sports Bar Grill'),
  ('United States', '2 At Ponkapoag Golf Club'),
  ('United States', '27 Pines Golf Course'),
  ('United States', '3 30 Club'),
  ('United States', '3 Creek Ranch Golf Club'),
  ('United States', '3 Lakes Golf Course'),
  ('United States', '3 Par At Four Points'),
  ('United States', '3 Parks Fairways'),
  ('United States', '3 S Greenville'),
  ('United States', '3/30 Golf & Country Club'),
  ('United States', '360 Ewa Beach Country Club'),
  ('United States', '401 Par Golf'),
  ('United States', '5 by 80 Golf and Country Club'),
  ('United States', '7 Lakes Golf Club'),
  ('United States', '9-Hole Short/Executive Course'),
  ('United States', '93 Golf Ranch'),
  ('United States', 'A Bar A Ranch Golf Course'),
  ('United States', 'A. J. Jolly Golf Course'),
  ('United States', 'Abacoa Golf Club'),
  ('United States', 'Abbey Course At St Leo University The'),
  ('United States', 'Abbey Springs Golf Course'),
  ('United States', 'Abenakee Club'),
  ('United States', 'Abenaqui Country Club'),
  ('United States', 'Aberdeen Country Club Highlands Meadows'),
  ('United States', 'Aberdeen Golf Club'),
  ('United States', 'Aberdeen Golf Country Club'),
  ('United States', 'Aberdeen Golf Country Club National'),
  ('United States', 'Abilene Golf Fitness'),
  ('United States', 'Abita Springs Golf Country Club'),
  ('United States', 'Acacia Mesquite At Kierland Golf Club'),
  ('United States', 'Achasta Golf Club'),
  ('United States', 'Ackerman Country Club'),
  ('United States', 'Ackerman-Allen Golf Course'),
  ('United States', 'Ackley Country Club'),
  ('United States', 'Acoaxet Club'),
  ('United States', 'Acorn Park Golf Course'),
  ('United States', 'Acorns Golf Links'),
  ('United States', 'Acushnet River Valley Golf Course'),
  ('United States', 'Adams Country Club'),
  ('United States', 'Adams County Country Club'),
  ('United States', 'Adams Golf Club'),
  ('United States', 'Adams Springs Golf Course'),
  ('United States', 'Addison Reserve Country Club Redemption Golf Course'),
  ('United States', 'Addison Reserve Country Club Salvation Golf Course'),
  ('United States', 'Addison Reserve Country Club Trepidation Golf Course'),
  ('United States', 'Adios Golf Club'),
  ('United States', 'Adirondack Golf Country Club'),
  ('United States', 'Admirals Cove East Course'),
  ('United States', 'Admirals Cove Golf Village North Course'),
  ('United States', 'Admirals Cove Golf Village South Course'),
  ('United States', 'Admirals Cove Golf Village West Course'),
  ('United States', 'Adrian Country Club'),
  ('United States', 'Advance Country Club'),
  ('United States', 'Aero Club Short Course'),
  ('United States', 'Aeropines Golf Club Hornet Course'),
  ('United States', 'Aeropines Golf Club Tomcat Course'),
  ('United States', 'Afton Golf Course'),
  ('United States', 'Agave Highlands'),
  ('United States', 'Agawam Hunt'),
  ('United States', 'Agawam Municipal Golf Course'),
  ('United States', 'Aguila Golf Course'),
  ('United States', 'Aguila Nine Golf Course'),
  ('United States', 'Ahwatukee Country Club'),
  ('United States', 'Aiken Golf Club'),
  ('United States', 'Aileron Golf Club'),
  ('United States', 'Airport Golf Batting Center'),
  ('United States', 'Airport Golf Club'),
  ('United States', 'Airport Golf Course'),
  ('United States', 'Airport National Golf Course'),
  ('United States', 'Airway Hills Golf Center'),
  ('United States', 'Airway Meadows Golf Course'),
  ('United States', 'Airways Golf Course'),
  ('United States', 'Airways Golf Course Country Club'),
  ('United States', 'Ajemians Liverpool Golf Public Country Club'),
  ('United States', 'Ajo Country Club'),
  ('United States', 'Ak Chin Southern Dunes Golf Club'),
  ('United States', 'Akron Golf Club'),
  ('United States', 'Ala Wai Golf Course'),
  ('United States', 'Alamance Country Club'),
  ('United States', 'Alapaha Golf Center'),
  ('United States', 'Alaqua Country Club'),
  ('United States', 'Albany 18 Hole Public Course'),
  ('United States', 'Albany Country Club'),
  ('United States', 'Albia Golf and Leisure'),
  ('United States', 'Albion Ridges Golf Course'),
  ('United States', 'Albuquerque Country Club'),
  ('United States', 'Alburg Country Club'),
  ('United States', 'Aldeen Golf Club'),
  ('United States', 'Alden Pines Country Club'),
  ('United States', 'Alder Creek Golf Course'),
  ('United States', 'Alderbrook Golf Club'),
  ('United States', 'Alexandria Bay Golf Course'),
  ('United States', 'Alexandria Golf Club'),
  ('United States', 'Alfred Tup Holmes Golf Club'),
  ('United States', 'Algona Country Club'),
  ('United States', 'Algonkian Golf Course'),
  ('United States', 'Algonquin Golf Club'),
  ('United States', 'Algonquin Golf Course'),
  ('United States', 'Alhambra Municipal Golf Course'),
  ('United States', 'Aliante Golf Course'),
  ('United States', 'Aliceville Golf Course'),
  ('United States', 'Alico Family Golf Short Course'),
  ('United States', 'Aliso Viejo Country Club'),
  ('United States', 'Alister Mackenzie At Haggin Oaks Golf Course'),
  ('United States', 'All About Golf Mount Chestnut Golf Course Driving Range'),
  ('United States', 'All Seasons Driving Range'),
  ('United States', 'All Vets Golf Course'),
  ('United States', 'Allegany Hills Golf Course'),
  ('United States', 'Alleghany Country Club'),
  ('United States', 'Allegheny Country Club'),
  ('United States', 'Allen County Country Club Golf Course'),
  ('United States', 'Allendale Country Club'),
  ('United States', 'Allenmore Golf Course'),
  ('United States', 'Allens Golf Course'),
  ('United States', 'Allentown Municipal Golf Course'),
  ('United States', 'Alliance Country Club'),
  ('United States', 'Alling Memorial Golf Course'),
  ('United States', 'Alma Municipal Golf Club'),
  ('United States', 'Almaden Golf Country Club'),
  ('United States', 'Alotian Golf Club'),
  ('United States', 'Alpena Golf Club'),
  ('United States', 'Alpine At Boyne Mountain Resort'),
  ('United States', 'Alpine Country Club'),
  ('United States', 'Alpine Golf Club'),
  ('United States', 'Alpine Lake Resort'),
  ('United States', 'Alpine Resort Golf Course'),
  ('United States', 'Alpine Valley Resort'),
  ('United States', 'Alta Golf and Country Club'),
  ('United States', 'Alta Lake Golf Resort'),
  ('United States', 'Alta Mesa Country Club'),
  ('United States', 'Alta Sierra Country Club'),
  ('United States', 'Alta Vista Country Club'),
  ('United States', 'Altadena Golf Course'),
  ('United States', 'Alto Lakes Golf Country Club'),
  ('United States', 'Alva Golf And Country Club'),
  ('United States', 'Alvamar Golf Club Members Course'),
  ('United States', 'Alverthorpe Park'),
  ('United States', 'Alwyn Downs Golf Club'),
  ('United States', 'Amana Colonies Golf Course'),
  ('United States', 'Amara Golf Social Club'),
  ('United States', 'Ambassador At Hickory Valley Golf Club'),
  ('United States', 'Ambassador Golf Club'),
  ('United States', 'Amberwood At The Villages Executive Golf Trail'),
  ('United States', 'Amelia Caroline At Mallory Hill Golf Course'),
  ('United States', 'Amelia Golf Country Club'),
  ('United States', 'Amelia National Golf And Country Club'),
  ('United States', 'American Classic Golf Club'),
  ('United States', 'American Dunes Golf Club'),
  ('United States', 'American Falls Golf Course'),
  ('United States', 'American Golf Club Vero Beach Blue Course'),
  ('United States', 'American Golf Club Vero Beach Red Course'),
  ('United States', 'American Golf Club Vero Beach White Course'),
  ('United States', 'American Lake Veterans Golf Course'),
  ('United States', 'American Legion Country Club'),
  ('United States', 'American Legion Golf Course'),
  ('United States', 'Amery Golf Club'),
  ('United States', 'Ames Golf & Country Club'),
  ('United States', 'Amesbury Golf Country Club'),
  ('United States', 'Amherst Audubon Golf Course Par Three Course'),
  ('United States', 'Amherst Country Club'),
  ('United States', 'Amherst Golf Club'),
  ('United States', 'Amory Golf Club'),
  ('United States', 'Amsterdam Municipal Golf Course'),
  ('United States', 'Anaconda Country Club'),
  ('United States', 'Anaconda Hills Golf Course'),
  ('United States', 'Anaheim Hills Public Country Club'),
  ('United States', 'Ancala Country Club'),
  ('United States', 'Anchor Golf Land'),
  ('United States', 'Anchorage Golf Course'),
  ('United States', 'Anchored Golf Course'),
  ('United States', 'Ancil Hoffman Golf Course'),
  ('United States', 'Andalusia Country Club'),
  ('United States', 'Anderson Country Club'),
  ('United States', 'Anderson Creek Golf Club'),
  ('United States', 'Anderson Fields Golf Course'),
  ('United States', 'Andover Country Club'),
  ('United States', 'Andover Golf Course'),
  ('United States', 'Andover Municipal Golf Course'),
  ('United States', 'Andover Public Golf Course'),
  ('United States', 'Andrew Johnson Golf Club'),
  ('United States', 'Androscoggin Valley Country Club'),
  ('United States', 'Anetsberger Golf Course'),
  ('United States', 'Angel Fire Resort Country Club'),
  ('United States', 'Angel Hill GC'),
  ('United States', 'Angeles National Golf Club'),
  ('United States', 'Angels Crossing Golf Course'),
  ('United States', 'Anglebrook Golf Club'),
  ('United States', 'Anglers Green'),
  ('United States', 'Angus Lea Golf Tennis Club'),
  ('United States', 'Angushire Golf Club'),
  ('United States', 'Ankeny Golf and Country Club'),
  ('United States', 'Ann Arbor Country Club'),
  ('United States', 'Ann Arbor Golf and Outing Club'),
  ('United States', 'Annandale Golf Club'),
  ('United States', 'Annandale Golf Course'),
  ('United States', 'Annbriar Golf Course'),
  ('United States', 'Ansley Golf Club Midtown Course'),
  ('United States', 'Ansley Golf Club Settindown Creek Course'),
  ('United States', 'Anson Point At Palmetto Bluff'),
  ('United States', 'Antelope Greens Golf Course'),
  ('United States', 'Antelope Hills Golf Course'),
  ('United States', 'Antelope Valley Country Club'),
  ('United States', 'Anthem Country Club'),
  ('United States', 'Anthem Golf Country Club Ironwood Course'),
  ('United States', 'Anthem Golf Country Club Persimmon Course'),
  ('United States', 'Anthon Golf Club'),
  ('United States', 'Anthony Country Club'),
  ('United States', 'Anthony Golf Course'),
  ('United States', 'Antioch Golf Club'),
  ('United States', 'Antioch Hills Golf Club'),
  ('United States', 'Antler Creek Golf Course'),
  ('United States', 'Antler Springs Of Chattaroy Golf Course'),
  ('United States', 'Antlers Springs Golf Course'),
  ('United States', 'Antrim Dells'),
  ('United States', 'Apache Course At Desert Mountain Golf Club'),
  ('United States', 'Apache Creek Golf Club'),
  ('United States', 'Apache Mesa Golf Course'),
  ('United States', 'Apache Sun Golf Club'),
  ('United States', 'Apache Wells Country Club'),
  ('United States', 'Apalachin Golf Course'),
  ('United States', 'Aplington Recreation Complex'),
  ('United States', 'Apogee Golf Club South'),
  ('United States', 'Apogee Golf Club West Couse'),
  ('United States', 'Apollo Beach Golf Sea Club'),
  ('United States', 'Apollo Elks Country Club'),
  ('United States', 'Apostle Highlands Golf Course'),
  ('United States', 'Apple Canyon Lake Golf Course'),
  ('United States', 'Apple Creek Country Club'),
  ('United States', 'Apple Hill Golf Club Par 3 Course'),
  ('United States', 'Apple Island Resort Golf Course'),
  ('United States', 'Apple Mountain Golf Course'),
  ('United States', 'Apple Mountain Golf Resort'),
  ('United States', 'Apple Mountain Resort'),
  ('United States', 'Apple Nine At Lyman Orchards Golf Club'),
  ('United States', 'Apple Ridge Country Club'),
  ('United States', 'Apple Tree Golf Course'),
  ('United States', 'Apple Valley Golf Club'),
  ('United States', 'Apple Valley Golf Course'),
  ('United States', 'Apple Valley Golf Course At Rumbling Bald Resort On Lake Lure'),
  ('United States', 'Applebrook Golf Club'),
  ('United States', 'Applecross Country Club'),
  ('United States', 'Applehill Golf Club'),
  ('United States', 'Appleland Sports Center'),
  ('United States', 'Applewood Golf Course'),
  ('United States', 'Applewood Hills Golf Course'),
  ('United States', 'Appling Country Club'),
  ('United States', 'Aquarina Country Club'),
  ('United States', 'Aquia Harbour Golf Country Club'),
  ('United States', 'Arapahoe Municipal Golf Course'),
  ('United States', 'Arbor Hills Golf Club'),
  ('United States', 'Arbor Pointe Golf Club'),
  ('United States', 'Arbor Trace Golf Club'),
  ('United States', 'Arbuckle Golf Club'),
  ('United States', 'Arcade Creek At Haggin Oaks Golf Course'),
  ('United States', 'Arcadia Bluffs - South Course'),
  ('United States', 'Arcadia Bluffs Golf Club'),
  ('United States', 'Arcadia Country Club'),
  ('United States', 'Arcadia Hills Golf Club'),
  ('United States', 'Arcadia Municipal Golf Course'),
  ('United States', 'Arcadia Par 3 Golf Course'),
  ('United States', 'Arcadia Village Country Club'),
  ('United States', 'Arcadian Shores Golf Club'),
  ('United States', 'Archies Family Golf Club'),
  ('United States', 'Arcola Country Club'),
  ('United States', 'Ardea Country Club North Course'),
  ('United States', 'Ardea Country Club South Course'),
  ('United States', 'Ardsley Country Club'),
  ('United States', 'Argent Lakes Golf Course'),
  ('United States', 'Arizona Biltmore Golf Club Estates Course'),
  ('United States', 'Arizona Biltmore Golf Club Links Course'),
  ('United States', 'Arizona City Golf Club'),
  ('United States', 'Arizona Grand Resort'),
  ('United States', 'Arizona National Golf Club'),
  ('United States', 'Arizona Traditions Golf Club'),
  ('United States', 'Arkansas City Country Club'),
  ('United States', 'Arlington Greens Golf Course'),
  ('United States', 'Arlington Lakes Golf Course'),
  ('United States', 'Arlington Park Golf Course'),
  ('United States', 'Arlington Ridge Golf Club'),
  ('United States', 'Armand Hammer Holmby Park Pony Golf Course'),
  ('United States', 'Armco Park Golf Course'),
  ('United States', 'Armitage Golf Course'),
  ('United States', 'Army Navy Country Club Arlington Blue Red Course'),
  ('United States', 'Army Navy Country Club Arlington Red White Course'),
  ('United States', 'Army Navy Country Club Arlington White Blue Course'),
  ('United States', 'Army Navy Country Club Fairfax Blue Red Course'),
  ('United States', 'Army Navy Country Club Fairfax Red White Course'),
  ('United States', 'Army Navy Country Club Fairfax White Blue Course'),
  ('United States', 'Arnold Palmer At Mission Hills Country Club'),
  ('United States', 'Arnolds Golf Course'),
  ('United States', 'Aronimink Golf Club'),
  ('United States', 'Aroostook Valley Country Club'),
  ('United States', 'Arrowhead Country Club'),
  ('United States', 'Arrowhead Creek Golf Course'),
  ('United States', 'Arrowhead Golf Club'),
  ('United States', 'Arrowhead Golf Course'),
  ('United States', 'Arrowhead Golf Course Championship'),
  ('United States', 'Arrowhead Golf Course Marina'),
  ('United States', 'Arrowhead Golf Course Short'),
  ('United States', 'Arrowhead Heights Golf Course'),
  ('United States', 'Arrowhead Lakes Golf Course'),
  ('United States', 'Arrowhead Meadows Golf Association'),
  ('United States', 'Arrowhead Pointe At Lake Richard B Russell'),
  ('United States', 'Arrowhead State Park Golf Course'),
  ('United States', 'Arrowood Golf Course'),
  ('United States', 'Arrowwood Golf Course'),
  ('United States', 'Arroyo Del Oso Golf Course Championship Course'),
  ('United States', 'Arroyo Del Oso Golf Course Dam Nine Course'),
  ('United States', 'Arroyo Golf Club'),
  ('United States', 'Arroyo Lakes At Gainey Ranch Golf Club'),
  ('United States', 'Arroyo Seco Golf Course'),
  ('United States', 'Arroyo Trabuco Golf Club'),
  ('United States', 'Arsenal Island Golf Course'),
  ('United States', 'Artesia Country Club'),
  ('United States', 'Arthur Hills'),
  ('United States', 'Arthur Hills At Palmetto Hall Plantation'),
  ('United States', 'Ascarate At Ascarate Park Golf Course'),
  ('United States', 'Ash Brook Golf Course'),
  ('United States', 'Ash Brook Golf Course 9 Hole Pitch Putt'),
  ('United States', 'Asheboro Country Club'),
  ('United States', 'Asheboro Municipal Golf Course'),
  ('United States', 'Asheville Municipal Golf Course'),
  ('United States', 'Ashfield Community Golf Course'),
  ('United States', 'Ashland Golf Club'),
  ('United States', 'Ashland Golf Course'),
  ('United States', 'Ashley Plantation Country Club Hills Course'),
  ('United States', 'Ashley Plantation Country Club Meadows Course'),
  ('United States', 'Ashley Plantation Country Club Orchards Course'),
  ('United States', 'Ashley Torri At Nancy Lopez Legacy Golf Country Club'),
  ('United States', 'Ashton Hills Golf Club'),
  ('United States', 'Ashwood Golf Club Birch Mesquite Course'),
  ('United States', 'Ashwood Golf Club Mesquite Sycamore Course'),
  ('United States', 'Ashwood Golf Club Sycamore Birch'),
  ('United States', 'Aspen Birch At Mccall Golf Course'),
  ('United States', 'Aspen Glen Club'),
  ('United States', 'Aspen Golf Course'),
  ('United States', 'Aspen Hills At Star Valley Ranch Country Club'),
  ('United States', 'Aspen Ridge Golf Course'),
  ('United States', 'Aspen Valley Golf Club'),
  ('United States', 'Aspetuck Valley Country Club'),
  ('United States', 'Assateague Greens Golf Center'),
  ('United States', 'Aston Oaks Golf Club'),
  ('United States', 'Astor Creek Golf Country Club'),
  ('United States', 'Astoria Golf Country Club'),
  ('United States', 'Atchison Golf Club At Bellevue'),
  ('United States', 'Atikwa Golf Club'),
  ('United States', 'Atkins Golf Club at the University of Illinois'),
  ('United States', 'Atkinson Resort Country Club Championship Course'),
  ('United States', 'Atkinson Resort Country Club Par 3 Course'),
  ('United States', 'Atlanta Athletic Club Highlands Course'),
  ('United States', 'Atlanta Athletic Club Par 3 Course'),
  ('United States', 'Atlanta Athletic Club Riverside Course'),
  ('United States', 'Atlanta Country Club'),
  ('United States', 'Atlanta National Golf Club'),
  ('United States', 'Atlantic Beach Country Club'),
  ('United States', 'Atlantic City Country Club'),
  ('United States', 'Atlantic Country Club'),
  ('United States', 'Atlantic Dunes At Sea Pines Resort'),
  ('United States', 'Atlantic Golf & Country Club'),
  ('United States', 'Atlantic Golf Center Pitch Putt'),
  ('United States', 'Atlantic Golf Center Shadow Brook Golf Course'),
  ('United States', 'Atlantic Golf Club'),
  ('United States', 'Atlantic National Golf Club'),
  ('United States', 'Atlantis Country Club'),
  ('United States', 'Atlas Valley Country Club'),
  ('United States', 'Atoka Trails Golf Course'),
  ('United States', 'Attica Golf Club Inc'),
  ('United States', 'Atunyote Golf Club At Turning Stone'),
  ('United States', 'Atwood Country Club'),
  ('United States', 'Atwood Homestead'),
  ('United States', 'Aubrey S Dubbs Dred Golf Course'),
  ('United States', 'Auburn Golf Course'),
  ('United States', 'Auburn Hills Golf Club'),
  ('United States', 'Auburn Hills Golf Course'),
  ('United States', 'Auburn Lake Trails Golf Course'),
  ('United States', 'Auburn Valley Golf Club'),
  ('United States', 'Audubon At Amherst Audubon Golf Course'),
  ('United States', 'Audubon Country Club'),
  ('United States', 'Audubon Golf and Country Club'),
  ('United States', 'Audubon Park Golf Course'),
  ('United States', 'Auglaize Golf Club'),
  ('United States', 'Augusta At Cedar Valley Golf Club'),
  ('United States', 'Augusta Country Club'),
  ('United States', 'Augusta Municipal Golf Course The Loop At The Patch'),
  ('United States', 'Augusta Municipal Golf Course The Patch'),
  ('United States', 'Augusta National Golf Club'),
  ('United States', 'Augusta Ranch Golf Club'),
  ('United States', 'Augustine Golf Club'),
  ('United States', 'Aurelia Golf Club'),
  ('United States', 'Aurora Country Club'),
  ('United States', 'Aurora Hills Golf Course'),
  ('United States', 'Ausable Club')
on conflict (country, name) do nothing;