insert into public.golf_courses (country, name) values
  ('United States', 'Macoby Run Golf Course'),
  ('United States', 'Macomb Country Club'),
  ('United States', 'Mad Anthony III''s Short Course'),
  ('United States', 'Mad Russian Golf Course'),
  ('United States', 'Madden Golf Course'),
  ('United States', 'Madeline Island Golf Club'),
  ('United States', 'Madera Golf Country Club'),
  ('United States', 'Madera Municipal Golf Course'),
  ('United States', 'Maderas Golf Club'),
  ('United States', 'Madison Country Club'),
  ('United States', 'Madison Golf & Country Club'),
  ('United States', 'Madison Golf Club'),
  ('United States', 'Madison Golf Course'),
  ('United States', 'Madison Green Country Club'),
  ('United States', 'Madison Meadows Golf Club'),
  ('United States', 'Madison Park Golf Course'),
  ('United States', 'Madisonville Country Club'),
  ('United States', 'Madrid Golf Course'),
  ('United States', 'Madrona Links Golf Course'),
  ('United States', 'Magellan Golf Course'),
  ('United States', 'Maggie Hathaway Par 3 Golf Course'),
  ('United States', 'Maggie Valley Resort Country Club'),
  ('United States', 'Magnolia At Beau Chene Golf Racquet Club'),
  ('United States', 'Magnolia Country Club'),
  ('United States', 'Magnolia Dogwood At Callawassie Island Club'),
  ('United States', 'Magnolia Green Golf Club'),
  ('United States', 'Magnolia Greens Golf Course Camellia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Azalea'),
  ('United States', 'Magnolia Greens Golf Course Magnolia Camellia'),
  ('United States', 'Magnolia Grove Golf Club Crossings Course'),
  ('United States', 'Magnolia Grove Golf Club Falls Course'),
  ('United States', 'Magnolia Grove Golf Club Short Course'),
  ('United States', 'Magnolia Highlands At Highland Oaks Golf Course'),
  ('United States', 'Magnolia Landing Golf Country Club'),
  ('United States', 'Magnolia Plantation Golf Club'),
  ('United States', 'Magnolia Point Golf Country Club'),
  ('United States', 'Magnolia Silo At Ben Geren Regional Park Golf Course'),
  ('United States', 'Magnolia Willow At Ben Geren Regional Park Golf Course'),
  ('United States', 'Mahnomen County Country Club'),
  ('United States', 'Mahoney Golf Course'),
  ('United States', 'Mahoning Country Club'),
  ('United States', 'Mahopac Golf Club'),
  ('United States', 'Main At Brae Burn Country Club'),
  ('United States', 'Main At Country Club The'),
  ('United States', 'Main At Shadow Lake Golf Racquet Club'),
  ('United States', 'Maine Golf Center Freeport'),
  ('United States', 'Mainland Golf Course'),
  ('United States', 'Mainlands Golf Course'),
  ('United States', 'Majestic Hills Golf Course'),
  ('United States', 'Majestic Oaks Golf Club'),
  ('United States', 'Majestic Oaks at Lake Lawn Resort'),
  ('United States', 'Majestic Springs Golf Club'),
  ('United States', 'Majestic at Lake Walden Golf Course'),
  ('United States', 'Makaha Valley Country Club'),
  ('United States', 'Makalei Golf Club'),
  ('United States', 'Makani Golf Club'),
  ('United States', 'Makefield Highlands Golf Club'),
  ('United States', 'Makena Beach Golf Resort'),
  ('United States', 'Maketewah Country Club'),
  ('United States', 'Makray Memorial Golf Club'),
  ('United States', 'Malden Country Club'),
  ('United States', 'Malden Municipal Golf Course'),
  ('United States', 'Mallard Creek Golf Club'),
  ('United States', 'Mallard Golf Club'),
  ('United States', 'Mallard Head Country Club'),
  ('United States', 'Mallard Pointe Golf Course'),
  ('United States', 'Mallards Landing Golf Course At Melbourne'),
  ('United States', 'Malvern Country Club'),
  ('United States', 'Mamala Bay Golf Course'),
  ('United States', 'Man O War Golf Course'),
  ('United States', 'Manada Golf Club'),
  ('United States', 'Manakiki Golf Course'),
  ('United States', 'Manakin At Hermitage Country Club'),
  ('United States', 'Manasquan River Golf Club'),
  ('United States', 'Manatee Cove Golf Course'),
  ('United States', 'Manatee Golf Course'),
  ('United States', 'Manchester Country Club'),
  ('United States', 'Manchester Golf and Country Club'),
  ('United States', 'Manele Golf Course'),
  ('United States', 'Mangrove At The Villages Executive Golf Trail'),
  ('United States', 'Mangrove Bay Golf Course'),
  ('United States', 'Mangum Golf Course'),
  ('United States', 'Manhattan Country Club'),
  ('United States', 'Manhattan Woods Golf Club'),
  ('United States', 'Manistee Golf & Country Club'),
  ('United States', 'Manito Golf Country Club'),
  ('United States', 'Manitou Passage Golf Club'),
  ('United States', 'Manitou Ridge Golf Course'),
  ('United States', 'Manitoulin Island Country Club'),
  ('United States', 'Manning Manilla Golf Course'),
  ('United States', 'Mannitto Golf Club'),
  ('United States', 'Manor Golf Course'),
  ('United States', 'Manor Valley Country Club'),
  ('United States', 'Mansfield Golf Country Club'),
  ('United States', 'Manson Golf and Country Club'),
  ('United States', 'Manteca Park Golf Course'),
  ('United States', 'Manteno Golf Club'),
  ('United States', 'Manufacturers Golf Country Club'),
  ('United States', 'Maple Bluff Country Club'),
  ('United States', 'Maple Brook Golf Course'),
  ('United States', 'Maple Chase Golf Country Club'),
  ('United States', 'Maple Creek Golf Club'),
  ('United States', 'Maple Creek Golf and Country Club'),
  ('United States', 'Maple Crest Golf Course'),
  ('United States', 'Maple Dale Country Club'),
  ('United States', 'Maple Grove Golf'),
  ('United States', 'Maple Grove Golf Course'),
  ('United States', 'Maple Heights Golf and Country Club'),
  ('United States', 'Maple Hill Golf Club'),
  ('United States', 'Maple Hill Golf Course'),
  ('United States', 'Maple Hills Golf Course'),
  ('United States', 'Maple Hills Public Golf Course'),
  ('United States', 'Maple Lane Golf Club'),
  ('United States', 'Maple Lane Golf Course'),
  ('United States', 'Maple Leaf Golf Country Club'),
  ('United States', 'Maple Leaf Golf Course'),
  ('United States', 'Maple Meadows Golf Club'),
  ('United States', 'Maple Moor Golf Course'),
  ('United States', 'Maple Ridge Golf'),
  ('United States', 'Maple Ridge Golf Club'),
  ('United States', 'Maple River Golf Club'),
  ('United States', 'Maple River Resort'),
  ('United States', 'Maple Run Golf Course'),
  ('United States', 'Maple Valley Golf & Country Club'),
  ('United States', 'Maple Willow At Hunters Creek Plantation'),
  ('United States', 'Maplecrest Country Club'),
  ('United States', 'Maplegate Country Club'),
  ('United States', 'Maplehurst Country Club'),
  ('United States', 'Maples At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Maplewood Country Club'),
  ('United States', 'Maplewood Golf Club'),
  ('United States', 'Maplewood Golf Course'),
  ('United States', 'Mapple Hills'),
  ('United States', 'Maquoketa Country Club'),
  ('United States', 'Marbella Country Club'),
  ('United States', 'Marcus Community Golf Club'),
  ('United States', 'Marcus Pointe Golf Club'),
  ('United States', 'Marengo Golf Club'),
  ('United States', 'Marengo Ridge Golf Curse'),
  ('United States', 'Margate Executive Golf Course'),
  ('United States', 'Mari Mac Golf Complex'),
  ('United States', 'Mariah Hills'),
  ('United States', 'Marian Hills Golf Course'),
  ('United States', 'Mariana Butte Golf Course'),
  ('United States', 'Marianna Country Club'),
  ('United States', 'Marias Valley Golf Country Club'),
  ('United States', 'Marietta Country Club'),
  ('United States', 'Marietta Country Club Lake View Nine'),
  ('United States', 'Marietta Country Club Mountain View Nine'),
  ('United States', 'Marietta Country Club Overlook Nine'),
  ('United States', 'Marin Country Club'),
  ('United States', 'Marine Memorial Golf Course'),
  ('United States', 'Marine Park Golf Course'),
  ('United States', 'Mariner Sands Country Club Blue Course'),
  ('United States', 'Mariner Sands Country Club Gold Course'),
  ('United States', 'Mariners Landing Golf Country Club'),
  ('United States', 'Mariners Point Golf Links Practice Center'),
  ('United States', 'Marion Country Club'),
  ('United States', 'Marion Golf Club'),
  ('United States', 'Marion Lake Golf Club'),
  ('United States', 'Marion Oaks Country Club'),
  ('United States', 'Marjon Golf Course'),
  ('United States', 'Mark Bostick Golf Course At The University Of Florida'),
  ('United States', 'Mark Twain Golf Course'),
  ('United States', 'Mark''s Golf'),
  ('United States', 'Mark''s Par 3'),
  ('United States', 'Marlboro Country Club'),
  ('United States', 'Marlborough Country Club'),
  ('United States', 'Maroon Creek Club Golf Course'),
  ('United States', 'Marquette Golf Club'),
  ('United States', 'Marquette Golf Club Greywalls'),
  ('United States', 'Marquette Park Golf Course'),
  ('United States', 'Marquette Trails Country Club'),
  ('United States', 'Marrakesh Golf Club'),
  ('United States', 'Mars Bethel Golf Course'),
  ('United States', 'Mars Hill Country Club'),
  ('United States', 'Marsh At Bonita Bay Club'),
  ('United States', 'Marsh Creek Country Club'),
  ('United States', 'Marsh Landing Country Club'),
  ('United States', 'Marsh Ridge Golf Course and Resort'),
  ('United States', 'Marsh View Pitch Putt'),
  ('United States', 'Marshall Canyon Golf Club'),
  ('United States', 'Marshall Country Club'),
  ('United States', 'Marshall Golf Club'),
  ('United States', 'Marshall Lakeside Country Club'),
  ('United States', 'Marshfield Country Club'),
  ('United States', 'Marshwood Magnolia At Highland Oaks Golf Course'),
  ('United States', 'Martin Downs Country Club Osprey Creek Course'),
  ('United States', 'Martindale Country Club'),
  ('United States', 'Martinsville Golf Club'),
  ('United States', 'Martis Camp Club'),
  ('United States', 'Marty Sanchez Links De Santa Fe Great 28 Course'),
  ('United States', 'Marty Sanchez Links De Santa Fe Links Course'),
  ('United States', 'Mary Calder Golf Club'),
  ('United States', 'Marysville Country Club'),
  ('United States', 'Marysville Golf Club'),
  ('United States', 'Marysville Golf Course'),
  ('United States', 'Marywood Country Club'),
  ('United States', 'Mascoutin Golf Club'),
  ('United States', 'Mason City Country Club'),
  ('United States', 'Massanutten Resort Mountain Greens Course'),
  ('United States', 'Massanutten Resort Woodstone Meadows Course'),
  ('United States', 'Massena Country Club'),
  ('United States', 'Masterpiece'),
  ('United States', 'Mastick Woods Golf Course'),
  ('United States', 'Mather Golf Course'),
  ('United States', 'Mattawang Golf Club'),
  ('United States', 'Matthew Creek Par 3'),
  ('United States', 'Mattoon Golf & Country Club'),
  ('United States', 'Mauh-Nah-Tee-See Country Club'),
  ('United States', 'Maui Country Club'),
  ('United States', 'Maui Nui Golf Club'),
  ('United States', 'Maumee Bay State Park Golf Course'),
  ('United States', 'Maumelle Country Club'),
  ('United States', 'Mauna Kea Golf Course'),
  ('United States', 'Mauna Lani Resort North Course'),
  ('United States', 'Mauna Lani Resort South Course'),
  ('United States', 'Mauna Lani Resort Wikiwiki Course'),
  ('United States', 'Maxwelton Braes Golf Resort'),
  ('United States', 'Maxwelton Golf Club'),
  ('United States', 'May River Golf Course At Palmetto Bluff'),
  ('United States', 'Mayacama Golf Club'),
  ('United States', 'Mayacoo Lakes Country Club'),
  ('United States', 'Mayapple Golf Links'),
  ('United States', 'Mayfair Country Club'),
  ('United States', 'Mayfield Sand Ridge Club'),
  ('United States', 'Mayflower Golf Club'),
  ('United States', 'Maynard Golf Course'),
  ('United States', 'Mays Landing Golf Club'),
  ('United States', 'Mayville Golf Club'),
  ('United States', 'Mayville Golf Course'),
  ('United States', 'McArthur Golf Course'),
  ('United States', 'McCaslin Brook Golf & Country Club'),
  ('United States', 'McCormick Creek Golf Course'),
  ('United States', 'McDonald Golf Course'),
  ('United States', 'McHenry Country Club'),
  ('United States', 'McLeansboro Golf Club'),
  ('United States', 'McMillen Park Golf Course'),
  ('United States', 'Mcalester Country Club'),
  ('United States', 'Mcarthur Golf Club'),
  ('United States', 'Mcarthur Golf Club Backyard Course'),
  ('United States', 'Mccall Field Golf Course'),
  ('United States', 'Mccanless Golf Club'),
  ('United States', 'Mccann Memorial Golf Course'),
  ('United States', 'Mccloud Golf Club'),
  ('United States', 'Mcconnellsville Golf Club'),
  ('United States', 'Mccormick Country Club'),
  ('United States', 'Mccormick Woods Golf Course'),
  ('United States', 'Mcculloughs Emerald Golf Links'),
  ('United States', 'Mcdaniel College Golf Club'),
  ('United States', 'Mcdonald Hills Golf Club'),
  ('United States', 'Mcdowell Mountain Golf Club'),
  ('United States', 'Mcgregor Links Country Club'),
  ('United States', 'Mcinnis Park Golf Center'),
  ('United States', 'Mckenzie Memorial Golf Course'),
  ('United States', 'Mclemore Club Highlands Course'),
  ('United States', 'Mclemore Club The Cairn Short Course'),
  ('United States', 'Mclemore Club The Keep'),
  ('United States', 'Mcpherson Country Club'),
  ('United States', 'Meade Country Club'),
  ('United States', 'Meadia Heights Golf Club'),
  ('United States', 'Meadow Acres Golf Course'),
  ('United States', 'Meadow At Forest Highlands Golf Club'),
  ('United States', 'Meadow At Mulligans South'),
  ('United States', 'Meadow Brook Club'),
  ('United States', 'Meadow Brook Golf Club'),
  ('United States', 'Meadow Brook Golf Course'),
  ('United States', 'Meadow Club'),
  ('United States', 'Meadow Course At Fiddlers Elbow Country Club'),
  ('United States', 'Meadow Creek Dogwood At Lancaster Country Club'),
  ('United States', 'Meadow Creek Golf Course'),
  ('United States', 'Meadow Golf Course At Pole Creek Golf Club'),
  ('United States', 'Meadow Greens Golf Course'),
  ('United States', 'Meadow Hills Golf Course'),
  ('United States', 'Meadow Lake Golf Club'),
  ('United States', 'Meadow Lake Golf Country Club'),
  ('United States', 'Meadow Lake Golf Resort'),
  ('United States', 'Meadow Lake Village And Golf Course'),
  ('United States', 'Meadow Lakes Golf Club'),
  ('United States', 'Meadow Lane Golf Course'),
  ('United States', 'Meadow Lark Country Club'),
  ('United States', 'Meadow Links & Golf Academy'),
  ('United States', 'Meadow Links At Fox Hollow At Lakewood'),
  ('United States', 'Meadow Links Golf Course'),
  ('United States', 'Meadow Links Golf Course At George T Bagby'),
  ('United States', 'Meadow Oak Golf Club'),
  ('United States', 'Meadow Oaks Golf Country Club'),
  ('United States', 'Meadow Park At Meadow Park Golf Course'),
  ('United States', 'Meadow Ponds Golf Course'),
  ('United States', 'Meadow Springs Country Club'),
  ('United States', 'Meadow Valley Golf Club'),
  ('United States', 'Meadow Valleys At Blackwolf Run Golf Course'),
  ('United States', 'Meadow Woods'),
  ('United States', 'Meadowbrook Country Club'),
  ('United States', 'Meadowbrook Golf Club'),
  ('United States', 'Meadowbrook Golf Course'),
  ('United States', 'Meadowbrook Golf and Country Club'),
  ('United States', 'Meadowbrook at Clayton'),
  ('United States', 'Meadowcreek Golf Course'),
  ('United States', 'Meadowcreek Golf Resort'),
  ('United States', 'Meadowgreens Golf Course'),
  ('United States', 'Meadowink Golf Course'),
  ('United States', 'Meadowlake Golf Course'),
  ('United States', 'Meadowland Golf Course'),
  ('United States', 'Meadowlands Golf Club'),
  ('United States', 'Meadowlands Golf Course'),
  ('United States', 'Meadowlark Golf Course'),
  ('United States', 'Meadowmeer Golf Country Club'),
  ('United States', 'Meadowood Golf Course'),
  ('United States', 'Meadowood Golf Tennis Club'),
  ('United States', 'Meadows Creekside At Traces Golf Club The'),
  ('United States', 'Meadows Golf Center'),
  ('United States', 'Meadows Golf Club'),
  ('United States', 'Meadows Golf Club The'),
  ('United States', 'Meadows Golf Course The'),
  ('United States', 'Meadows Oaks Golf Course At Pennbrooke Fairways'),
  ('United States', 'Meadows Of Six Mile Creek'),
  ('United States', 'Meadows Pinon At Pagosa Springs Golf Club'),
  ('United States', 'Meadowview Golf & Country Club'),
  ('United States', 'Meadowview Golf Course'),
  ('United States', 'Meadowwood Golf Course'),
  ('United States', 'Meander Golf Course'),
  ('United States', 'Mechanicville Golf Club'),
  ('United States', 'Mecklenburg Country Club'),
  ('United States', 'Medal Of Honor Golf Course'),
  ('United States', 'Medalist Golf Club'),
  ('United States', 'Medalist Village Golf'),
  ('United States', 'Medallion Golf Club'),
  ('United States', 'Medford Lakes Country Club'),
  ('United States', 'Medford Village Country Club'),
  ('United States', 'Medicine Lodge Golf Club'),
  ('United States', 'Medina Golf & Country Club'),
  ('United States', 'Medinah Country Club'),
  ('United States', 'Mee-Kwon Park Golf Course'),
  ('United States', 'Meeker Golf Course'),
  ('United States', 'Megunticook Golf Club'),
  ('United States', 'Meigs Golf Course'),
  ('United States', 'Mellen country Club'),
  ('United States', 'Melody Hill Golf Course'),
  ('United States', 'Melrose Country Club'),
  ('United States', 'Members Club At St James Plantation Cate Nine Course'),
  ('United States', 'Members Club At St James Plantation Irwin Course'),
  ('United States', 'Memorial Links Golf Club'),
  ('United States', 'Memorial Park Golf Course'),
  ('United States', 'Memphis Athletic Ministries Park Golf Course'),
  ('United States', 'Memphis Country Club The'),
  ('United States', 'Memphis National Golf Club Champions Course'),
  ('United States', 'Memphis National Golf Club Legends Course'),
  ('United States', 'Memphremagog Golf Club'),
  ('United States', 'Mendakota Country Club'),
  ('United States', 'Mendenhall Golf Course'),
  ('United States', 'Mendham Golf Tennis Club'),
  ('United States', 'Mendon Golf Club'),
  ('United States', 'Mendota Golf Club'),
  ('United States', 'Mendota Heights Par 3 Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Lakes Golf Course'),
  ('United States', 'Menifee Lakes Country Club The Palms Golf Course'),
  ('United States', 'Menlo Country Club'),
  ('United States', 'Menomonie Country Club'),
  ('United States', 'Mentel Memorial Golf Course'),
  ('United States', 'Meramec Lakes Golf Course'),
  ('United States', 'Merced Golf Country Club'),
  ('United States', 'Mercer County Elks Golf Club'),
  ('United States', 'Mercer Oaks Golf Course East Course'),
  ('United States', 'Mercer Oaks Golf Course West Course'),
  ('United States', 'Mercer Public Golf Course'),
  ('United States', 'Merchantville Country Club'),
  ('United States', 'Mere Creek Golf Course'),
  ('United States', 'Meridian Golf Club'),
  ('United States', 'Meridian Golf Par 3 Golf Club'),
  ('United States', 'Meridian Hills County Club'),
  ('United States', 'Meridian Sun Golf Club'),
  ('United States', 'Meridian Valley Country Club'),
  ('United States', 'Merit Club'),
  ('United States', 'Mermaid Swim Golf Club'),
  ('United States', 'Merrick Road Park Golf Course'),
  ('United States', 'Merriland Farm Par 3 Golf Course'),
  ('United States', 'Merrill Golf Club'),
  ('United States', 'Merrimack Valley Golf Club'),
  ('United States', 'Mesa At Adobe Creek National Golf Course'),
  ('United States', 'Mesa Country Club'),
  ('United States', 'Mesa Del Sol Golf Course'),
  ('United States', 'Mesa Linda At Costa Mesa Golf Country Club'),
  ('United States', 'Mesa Verde Country Club'),
  ('United States', 'Mesa View Golf Course'),
  ('United States', 'Mesaba Country Club'),
  ('United States', 'Mesquite Ironwood At Kierland Golf Club'),
  ('United States', 'Met Links'),
  ('United States', 'Metairie Country Club'),
  ('United States', 'Metamora Country Club'),
  ('United States', 'Metamora Fields Golf Club'),
  ('United States', 'Metchosin Golf And Country Club'),
  ('United States', 'Methodist College Golf Club'),
  ('United States', 'Metropolis Country Club'),
  ('United States', 'Metrowest Golf Club'),
  ('United States', 'Metuchen Golf Country Club'),
  ('United States', 'Mga Links At Mamantapett'),
  ('United States', 'Miacomet Golf Course'),
  ('United States', 'Miami Beach Golf Club'),
  ('United States', 'Miami Shores Country Club')
on conflict (country, name) do nothing;