insert into public.golf_courses (country, name) values
  ('United States', 'Tpc Deere Run'),
  ('United States', 'Tpc Harding Park Fleming Course'),
  ('United States', 'Tpc Harding Park Harding Course'),
  ('United States', 'Tpc Jasna Polana'),
  ('United States', 'Tpc Las Vegas'),
  ('United States', 'Tpc Louisiana'),
  ('United States', 'Tpc Michigan'),
  ('United States', 'Tpc Monterey At Pasadera'),
  ('United States', 'Tpc Myrtle Beach'),
  ('United States', 'Tpc Piper Glen'),
  ('United States', 'Tpc Potomac At Avenel Farm'),
  ('United States', 'Tpc Prestancia The Players Course'),
  ('United States', 'Tpc Prestancia The Stadium Course'),
  ('United States', 'Tpc River Highlands'),
  ('United States', 'Tpc Sawgrass Dyes Valley Course'),
  ('United States', 'Tpc Sawgrass The Players Stadium Course'),
  ('United States', 'Tpc Scottsdale The Champions Course'),
  ('United States', 'Tpc Scottsdale The Stadium Course'),
  ('United States', 'Tpc Southwind'),
  ('United States', 'Tpc Stonebrae'),
  ('United States', 'Tpc Sugarloaf Pines Course'),
  ('United States', 'Tpc Sugarloaf Stables Meadows Course'),
  ('United States', 'Tpc Summerlin'),
  ('United States', 'Tpc Tampa Bay'),
  ('United States', 'Tpc Treviso Bay'),
  ('United States', 'Tpc Wakefield Plantation'),
  ('United States', 'Tpc Wakefield Plantation Practice Course'),
  ('United States', 'Tpc Wisconsin'),
  ('United States', 'Tracy Country Club'),
  ('United States', 'Tracy Golf Country Club'),
  ('United States', 'Tradition At Tradition Golf Club'),
  ('United States', 'Tradition Golf Club'),
  ('United States', 'Tradition Golf Club At Oak Lane'),
  ('United States', 'Traditions At The Glen'),
  ('United States', 'Traditions Golf Club Learning Center'),
  ('United States', 'Traditions Of Braselton Golf Club'),
  ('United States', 'Traer Golf Club'),
  ('United States', 'Trail Blue At Blue Ridge Trail Golf Club'),
  ('United States', 'Trail Creek Course At Sun Valley Resort'),
  ('United States', 'Trail Ridge Golf Course At Sun City West'),
  ('United States', 'Trail Ruts Golf Course'),
  ('United States', 'Trail Side Golf and Foot Golf'),
  ('United States', 'Trailhead Golf Course'),
  ('United States', 'Trails End Golf Course'),
  ('United States', 'Trails West Golf Course'),
  ('United States', 'Tranquilo Golf Club At Four Seasons Resort Orlando'),
  ('United States', 'Transit Valley Country Club'),
  ('United States', 'Trapp River Golf Course'),
  ('United States', 'Trappers Turn Golf Club'),
  ('United States', 'Traveler''s Country Club'),
  ('United States', 'Travelers Rest Rv Resort Golf Course'),
  ('United States', 'Traverse City Golf and Country Club'),
  ('United States', 'Travis Pointe Country Club'),
  ('United States', 'Treasure Bay Golf Tennis'),
  ('United States', 'Tree Links Golf Course'),
  ('United States', 'Tree Top Golf Course'),
  ('United States', 'Treetops'),
  ('United States', 'Tregaron Golf Course'),
  ('United States', 'Trenton Country Club'),
  ('United States', 'Trenton Golf Club'),
  ('United States', 'Trestle Creek Golf Club'),
  ('United States', 'Treyburn Country Club'),
  ('United States', 'Treynor Recreation Area'),
  ('United States', 'Tri County Country Club'),
  ('United States', 'Tri Mountain Golf Course'),
  ('United States', 'Tri-City Country Club'),
  ('United States', 'Tri-Club Golf Club'),
  ('United States', 'Tri-County Golf Club'),
  ('United States', 'Tributary At River Strand Golf And Country Club'),
  ('United States', 'Tribute Golf Course'),
  ('United States', 'Trident Lakes Golf Club'),
  ('United States', 'Triggs Memorial Golf Course'),
  ('United States', 'Trillium Links'),
  ('United States', 'Trilogy Golf Club At La Quinta'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Players Loop'),
  ('United States', 'Trilogy Golf Club At Ocala Preserve Skills Course'),
  ('United States', 'Trilogy Golf Club At Vistancia'),
  ('United States', 'Trinidad Golf Course'),
  ('United States', 'Trinity Alps Golf Course'),
  ('United States', 'Trinity Golf Course'),
  ('United States', 'Triple Creek Golf Club'),
  ('United States', 'Triple Lakes Golf Course'),
  ('United States', 'Tripoli Country Club'),
  ('United States', 'Trona Golf Course'),
  ('United States', 'Troon Country Club'),
  ('United States', 'Trophy Lake Golf Casting Club'),
  ('United States', 'Trosper Golf Club'),
  ('United States', 'Trout Lake Golf Club'),
  ('United States', 'Troy Burne Golf Club'),
  ('United States', 'True Blue Golf Club'),
  ('United States', 'True North Golf Club'),
  ('United States', 'Trull Brook Golf Course'),
  ('United States', 'Truman At The Villages Executive Golf Trail'),
  ('United States', 'Trumann Country Club'),
  ('United States', 'Trumansburg Golf Club'),
  ('United States', 'Trump International Golf Club'),
  ('United States', 'Trump International Golf Club The Executive Golf Course'),
  ('United States', 'Trump National Doral Miami Blue Monster Course'),
  ('United States', 'Trump National Doral Miami Golden Palm Course'),
  ('United States', 'Trump National Doral Miami Red Tiger Course'),
  ('United States', 'Trump National Doral Miami Silver Fox Course'),
  ('United States', 'Trump National Golf Club'),
  ('United States', 'Trump National Golf Club Bedminster New Course'),
  ('United States', 'Trump National Golf Club Bedminster Old Course'),
  ('United States', 'Trump National Golf Club Charlotte'),
  ('United States', 'Trump National Golf Club Colts Neck Championship Course'),
  ('United States', 'Trump National Golf Club Colts Neck Par 3 Course'),
  ('United States', 'Trump National Golf Club Hudson Valley'),
  ('United States', 'Trump National Golf Club Philadelphia'),
  ('United States', 'Trump National Golf Club Washington D C Championship Course'),
  ('United States', 'Trump National Golf Club Washington D C River Course'),
  ('United States', 'Truth Or Consequence City Golf Course'),
  ('United States', 'Tryon Country Club'),
  ('United States', 'Tsawwassen Springs Golf'),
  ('United States', 'Tubac Golf Resort Anza Rancho'),
  ('United States', 'Tubac Golf Resort Otero Anza'),
  ('United States', 'Tubac Golf Resort Rancho Otero'),
  ('United States', 'Tuckaway Country Club'),
  ('United States', 'Tucson Catalina At Saddlebrooke Country Club'),
  ('United States', 'Tucson Country Club'),
  ('United States', 'Tucson Estates Country Club Golf Course'),
  ('United States', 'Tucumcari Municipal Golf Course'),
  ('United States', 'Tug Valley Country Club'),
  ('United States', 'Tulare Golf Course'),
  ('United States', 'Tullymore'),
  ('United States', 'Tulsa Country Club'),
  ('United States', 'Tumble Brook Country Club Blue Nine'),
  ('United States', 'Tumble Brook Country Club Green Nine'),
  ('United States', 'Tumble Brook Country Club Red Nine'),
  ('United States', 'Tumble Creek At Suncadia'),
  ('United States', 'Tumwater Valley Golf Club'),
  ('United States', 'Tunica National Golf And Tennis'),
  ('United States', 'Tunnel Hill Golf Course'),
  ('United States', 'Tupelo Bay Golf Complex Executive Course'),
  ('United States', 'Tupelo Bay Golf Complex Par 3 Course'),
  ('United States', 'Tupelo Country Club'),
  ('United States', 'Tupper Lake Country Club'),
  ('United States', 'Turin Highlands Golf Course'),
  ('United States', 'Turkana Golf Course'),
  ('United States', 'Turkey Creek Golf Club'),
  ('United States', 'Turkey Creek Golf Course'),
  ('United States', 'Turkey Run Golf Course'),
  ('United States', 'Turkeyfoot Lake Golf Links'),
  ('United States', 'Turlock Golf Country Club'),
  ('United States', 'Turnberry Golf Club'),
  ('United States', 'Turnberry Golf Course'),
  ('United States', 'Turnberry Isle Country Club Soffer Course'),
  ('United States', 'Turnberry Isle Country Club The Miller Course'),
  ('United States', 'Turner Highlands Country Club'),
  ('United States', 'Turner Hill Golf Racquet Club'),
  ('United States', 'Turquoise Hills Family Golf Center'),
  ('United States', 'Turtle Bay Resort Arnold Palmer Course'),
  ('United States', 'Turtle Bay Resort George Fazio Course'),
  ('United States', 'Turtle Bay Resort The Breaks Putting Course'),
  ('United States', 'Turtle Cove Property Owners Association Inc'),
  ('United States', 'Turtle Creek Club'),
  ('United States', 'Turtle Creek Golf Club'),
  ('United States', 'Turtle Creek Golf Course'),
  ('United States', 'Turtle Creek Golf Course At Garden Cathay'),
  ('United States', 'Turtle Hill Golf Course'),
  ('United States', 'Turtle Mound At The Villages Executive Golf Trail'),
  ('United States', 'Turtle Point At Kiawah Island Golf Resort'),
  ('United States', 'Turtle Run At Sun N Lake Golf Country Club'),
  ('United States', 'Turtle Run Golf Course'),
  ('United States', 'Turtleback'),
  ('United States', 'Turtleback Golf Course'),
  ('United States', 'Turtleback Mountain Golf Resort'),
  ('United States', 'Tuscan Ridge Golf Club'),
  ('United States', 'Tuscany Falls At Pebblecreek East Course'),
  ('United States', 'Tuscany Falls At Pebblecreek West Course'),
  ('United States', 'Tuscarora Country Club'),
  ('United States', 'Tuscarora Golf Club'),
  ('United States', 'Tuscawilla Golf Course'),
  ('United States', 'Tuscumbia Country Club'),
  ('United States', 'Tussey Mountain Golf Course'),
  ('United States', 'Tustin Ranch Golf Club'),
  ('United States', 'Tustin Trails Golf Course'),
  ('United States', 'Twaalfskill Club'),
  ('United States', 'Twain Harte Golf Club'),
  ('United States', 'Twelve Shores Golf Club'),
  ('United States', 'Twilight Golf Course'),
  ('United States', 'Twin Base Golf Course'),
  ('United States', 'Twin Beach Country Club'),
  ('United States', 'Twin Birch Golf Course'),
  ('United States', 'Twin Bridges Golf Club'),
  ('United States', 'Twin Bridges Golf Course'),
  ('United States', 'Twin Brook Golf Center'),
  ('United States', 'Twin Brooks Golf Course'),
  ('United States', 'Twin City Country Club'),
  ('United States', 'Twin Creeks Golf Course'),
  ('United States', 'Twin Falls Golf Club'),
  ('United States', 'Twin Falls Municipal Golf Course'),
  ('United States', 'Twin Falls State Park'),
  ('United States', 'Twin Hickory Golf Club'),
  ('United States', 'Twin Hills Country Club'),
  ('United States', 'Twin Hills Golf Country Club'),
  ('United States', 'Twin Hills Golf Course'),
  ('United States', 'Twin Isles Country Club'),
  ('United States', 'Twin Lake Par 3 Golf Course'),
  ('United States', 'Twin Lake Village Par 3 Golf Course'),
  ('United States', 'Twin Lakes Country Club'),
  ('United States', 'Twin Lakes Golf & Swim Club'),
  ('United States', 'Twin Lakes Golf Club'),
  ('United States', 'Twin Lakes Golf Country Club'),
  ('United States', 'Twin Lakes Golf Course'),
  ('United States', 'Twin Lakes Lakes Course'),
  ('United States', 'Twin Lakes Municipal Golf Course'),
  ('United States', 'Twin Lakes Oaks Course'),
  ('United States', 'Twin Lakes Of Kahoka'),
  ('United States', 'Twin Lakes Village Golf Course'),
  ('United States', 'Twin Oaks Country Club'),
  ('United States', 'Twin Oaks Golf Club'),
  ('United States', 'Twin Oaks Golf Country Club'),
  ('United States', 'Twin Oaks Golf Course'),
  ('United States', 'Twin Oaks Golf and Plantation Club'),
  ('United States', 'Twin Oaks Par 3 Golf Driving Range'),
  ('United States', 'Twin Orchards Country Club'),
  ('United States', 'Twin Peaks Golf Course'),
  ('United States', 'Twin Pines Golf Course'),
  ('United States', 'Twin Ponds Golf Club'),
  ('United States', 'Twin Ponds Golf Country Club'),
  ('United States', 'Twin Rivers Golf Club'),
  ('United States', 'Twin Rivers Golf Course'),
  ('United States', 'Twin Run Golf Course'),
  ('United States', 'Twin Springs Golf Course'),
  ('United States', 'Twin Valley Country Club'),
  ('United States', 'Twin Village Golf Club'),
  ('United States', 'Twin Warriors Golf Club'),
  ('United States', 'Twin Willows Par 3 Golf Course'),
  ('United States', 'Twin Woods Golf Club'),
  ('United States', 'Twineagles Golf Country Club Eagle Course'),
  ('United States', 'Twineagles Golf Country Club Talon Course'),
  ('United States', 'Twisted Dune Golf Club'),
  ('United States', 'Twisted Gun Golf Course'),
  ('United States', 'Twisted Oaks Golf Club'),
  ('United States', 'Twisted Pine Golf Course'),
  ('United States', 'Two East Course At Apple Greens Golf Course'),
  ('United States', 'Two Oaks North Golf Club'),
  ('United States', 'Two Rivers Country Club'),
  ('United States', 'Two Rivers Golf Club'),
  ('United States', 'Tyler Creek Golf Club'),
  ('United States', 'Tylertown Country Club'),
  ('United States', 'Tyngsboro Country Club'),
  ('United States', 'Tyoga Golf Course'),
  ('United States', 'Tyrone Hills Golf Club'),
  ('United States', 'U S Soldiers And Airmens Home Golf Course'),
  ('United States', 'Ubly Heights Golf & Country Club'),
  ('United States', 'Uchee Trail Country Club'),
  ('United States', 'Ukiah Valley Golf Course'),
  ('United States', 'Ulen Country Club'),
  ('United States', 'Umstead Pines Golf Swim Club At Willowhaven'),
  ('United States', 'Unc Finley Golf Course'),
  ('United States', 'Uncle Remus Golf Course'),
  ('United States', 'Undermountain Golf Course'),
  ('United States', 'Unf Golf Complex At The Hayt Learning Center'),
  ('United States', 'Unicorn Golf Course'),
  ('United States', 'Union City Country Club'),
  ('United States', 'Union Country Club'),
  ('United States', 'Union County Country Club'),
  ('United States', 'Union Golf Course'),
  ('United States', 'Union Hills Golf Country Club'),
  ('United States', 'Union Lake Golf Course'),
  ('United States', 'Union League Golf Club At Torresdale'),
  ('United States', 'Union League Liberty Hill'),
  ('United States', 'Union League National Golf Club Meade Grant'),
  ('United States', 'Union League National Golf Club Sherman Grant'),
  ('United States', 'Union League National Golf Club Sherman Meade'),
  ('United States', 'Uniontown Country Club'),
  ('United States', 'University Club'),
  ('United States', 'University Club Of Milwaukee'),
  ('United States', 'University Golf Club'),
  ('United States', 'University Of Denver Golf Club At Highlands Ranch'),
  ('United States', 'University Of Georgia Golf Course'),
  ('United States', 'University Of Idaho Golf Course'),
  ('United States', 'University Of Maryland Golf Course'),
  ('United States', 'University Of Montana Golf Course The'),
  ('United States', 'University Of New Mexico North Course'),
  ('United States', 'University Park Golf Course'),
  ('United States', 'University Ridge Golf Course'),
  ('United States', 'University of Illinois Golf Course'),
  ('United States', 'University of Louisville Golf Club'),
  ('United States', 'University of Michigan Golf Course'),
  ('United States', 'University of North Dakota Golf Course'),
  ('United States', 'Upland Hills Country Club'),
  ('United States', 'Upland Trace Golf Club'),
  ('United States', 'Uplands Golf Club'),
  ('United States', 'Upper At Baltusrol Golf Club'),
  ('United States', 'Upper At Peekn Peak Golf Course'),
  ('United States', 'Upper Canada Golf Course'),
  ('United States', 'Upper Lansdowne Golf Course'),
  ('United States', 'Urban Put Put'),
  ('United States', 'Urbana Country Club'),
  ('United States', 'Urbandale Golf & Country Club'),
  ('United States', 'Useless Bay Golf Country Club'),
  ('United States', 'Ute Creek Golf Course'),
  ('United States', 'Utica Golf Club'),
  ('United States', 'Va Jo Wa Golf Club'),
  ('United States', 'Vache Grasse Country Club'),
  ('United States', 'Vail Golf Club'),
  ('United States', 'Vails Grove Golf Course'),
  ('United States', 'Val Halla Golf Recreation Center'),
  ('United States', 'Valencia Country Club'),
  ('United States', 'Valencia Golf Country Club'),
  ('United States', 'Valhalla Golf Club'),
  ('United States', 'Valle Del Sol Golf Course'),
  ('United States', 'Valle Vista Golf Course'),
  ('United States', 'Valleaire Golf Club'),
  ('United States', 'Valley At Castlewood Country Club'),
  ('United States', 'Valley At Colonial Springs Golf Course'),
  ('United States', 'Valley At Cordillera Golf Course'),
  ('United States', 'Valley At Marriotts Desert Springs Resort'),
  ('United States', 'Valley At Towa Golf Resort'),
  ('United States', 'Valley Brook Golf Course'),
  ('United States', 'Valley Club Of Montecito'),
  ('United States', 'Valley Country Club'),
  ('United States', 'Valley Course At Christmans Windham House'),
  ('United States', 'Valley Gardens Golf Course'),
  ('United States', 'Valley Golf Center'),
  ('United States', 'Valley Golf Centre'),
  ('United States', 'Valley Golf Course'),
  ('United States', 'Valley Green Golf Country Club'),
  ('United States', 'Valley Green Golf Course'),
  ('United States', 'Valley Green Par 3 Course'),
  ('United States', 'Valley Hi Country Club'),
  ('United States', 'Valley Hi Municipal Golf Course'),
  ('United States', 'Valley High Golf Course'),
  ('United States', 'Valley Links Course'),
  ('United States', 'Valley Lo Club'),
  ('United States', 'Valley Mountain At Pinery Country Club'),
  ('United States', 'Valley Oaks At North Ranch Country Club'),
  ('United States', 'Valley Oaks At Valley Oaks Golf Club'),
  ('United States', 'Valley Of The Eagles Golf Links'),
  ('United States', 'Valley Of The Moon Golf Club'),
  ('United States', 'Valley Pine Country Club'),
  ('United States', 'Valley Pines Golf Club'),
  ('United States', 'Valley Point Golf Course'),
  ('United States', 'Valley View Country Club'),
  ('United States', 'Valley View Golf'),
  ('United States', 'Valley View Golf Club'),
  ('United States', 'Valley View Golf Course'),
  ('United States', 'Valley View Municipal Golf Course'),
  ('United States', 'Valley Vista At Los Coyotes Country Club'),
  ('United States', 'Valley Vista Golf Course'),
  ('United States', 'Valleywood Golf Club'),
  ('United States', 'Valleywood Golf Course'),
  ('United States', 'Valparaiso Country Club'),
  ('United States', 'Van Buren Golf Center'),
  ('United States', 'Van Buren Recreation Area Golf'),
  ('United States', 'Van Cortlandt Park Golf Course'),
  ('United States', 'Van Patten Golf Club Blue Red'),
  ('United States', 'Van Patten Golf Club Red White'),
  ('United States', 'Van Patten Golf Club White Blue'),
  ('United States', 'Van Schaick Island Country Club'),
  ('United States', 'Vanderbilt Country Club'),
  ('United States', 'Vandergrift Golf Club'),
  ('United States', 'Vanmetre 9 At Stonebridge'),
  ('United States', 'Vardon Golf Club'),
  ('United States', 'Vasari Country Club'),
  ('United States', 'Vashon Island Golf Country Club'),
  ('United States', 'Vassar Golf Course'),
  ('United States', 'Vassar Golf and Country Club'),
  ('United States', 'Veenker Memorial Golf Course'),
  ('United States', 'Venango Valley Inn Golf Course'),
  ('United States', 'Venetian Gardens Golf Course'),
  ('United States', 'Venetian Golf Club'),
  ('United States', 'Venice East Golf Club'),
  ('United States', 'Venice Golf Country Club'),
  ('United States', 'Ventana Canyon Canyon Course'),
  ('United States', 'Ventana Canyon Mountain Course'),
  ('United States', 'Ventura Country Club'),
  ('United States', 'Verde River Golf Social Club'),
  ('United States', 'Verdict Ridge Golf Country Club'),
  ('United States', 'Vermilion Golf Course'),
  ('United States', 'Vermilion River Greens'),
  ('United States', 'Vermillion Fairways'),
  ('United States', 'Vermont National Country Club'),
  ('United States', 'Vernon Hills Golf Course'),
  ('United States', 'Vernonia Golf Club'),
  ('United States', 'Vero Beach Country Club'),
  ('United States', 'Verona Hills Golf Club'),
  ('United States', 'Verona Meadows'),
  ('United States', 'Verrado Golf Club Founders Course'),
  ('United States', 'Verrado Golf Club Victory Course'),
  ('United States', 'Vesper Country Club'),
  ('United States', 'Vesper Hills Golf Club'),
  ('United States', 'Vestal Hills Country Club'),
  ('United States', 'Veteran''s Memorial Golf Course'),
  ('United States', 'Veterans Golf Course'),
  ('United States', 'Veterans Memorial Golf Course'),
  ('United States', 'Via Mizner Golf Country Club'),
  ('United States', 'Via Verde Country Club'),
  ('United States', 'Viburnum Golf & Country Club'),
  ('United States', 'Vic Meyers Golf Course At Sun Lakes'),
  ('United States', 'Vicksburg Country Club'),
  ('United States', 'Victoria Club'),
  ('United States', 'Victoria Country Club'),
  ('United States', 'Victoria Golf Centre'),
  ('United States', 'Victoria Golf Club'),
  ('United States', 'Victoria Golf Course'),
  ('United States', 'Victoria Hills Golf Club')
on conflict (country, name) do nothing;