insert into public.golf_courses (country, name) values
  ('United States', 'Las Vegas Golf Club'),
  ('United States', 'Las Vegas National Golf Course'),
  ('United States', 'Lasalle Golf Country Club'),
  ('United States', 'Lassing Pointe Golf Course'),
  ('United States', 'Latah Creek Golf Course'),
  ('United States', 'Latex Golf Course'),
  ('United States', 'Latimer Golf Club'),
  ('United States', 'Latona Country Club'),
  ('United States', 'Latour Golf Club'),
  ('United States', 'Latourette Golf Course'),
  ('United States', 'Latrobe Country Club'),
  ('United States', 'Latrobe Elks Golf Club'),
  ('United States', 'Latta Lea Golf Club'),
  ('United States', 'Lauderdale Lakes Country Club'),
  ('United States', 'Laughlin Ranch Golf Club'),
  ('United States', 'Laurel Azalea At Houndslake Country Club'),
  ('United States', 'Laurel Country Club'),
  ('United States', 'Laurel Creek Country Club'),
  ('United States', 'Laurel Golf Club'),
  ('United States', 'Laurel Hill Golf Club'),
  ('United States', 'Laurel Island Links'),
  ('United States', 'Laurel Lane Country Club'),
  ('United States', 'Laurel Links Golf Course'),
  ('United States', 'Laurel Mill Golf Course'),
  ('United States', 'Laurel Oak At The Villages Executive Golf Trail'),
  ('United States', 'Laurel Oaks Golf Course'),
  ('United States', 'Laurel Ridge Country Club'),
  ('United States', 'Laurel Springs Golf Club'),
  ('United States', 'Laurel Valley Course At Palmer Legends'),
  ('United States', 'Laurel Valley Golf Club'),
  ('United States', 'Laurens Golf and Country Club'),
  ('United States', 'Lava Creek Golf Course'),
  ('United States', 'Laverne Golf Country Club'),
  ('United States', 'Lawrence Country Club'),
  ('United States', 'Lawrence Park Golf Club'),
  ('United States', 'Lawrence Yacht Country Club'),
  ('United States', 'Lawrenceville School Golf Course The'),
  ('United States', 'Lawton Country Club'),
  ('United States', 'Lawton Golf Club'),
  ('United States', 'Lawton Municipal Golf Course'),
  ('United States', 'Lbi National Golf Resort'),
  ('United States', 'Le Patrimoine Golf Club'),
  ('United States', 'Le Roy Country Club'),
  ('United States', 'Le Triomphe Golf Club'),
  ('United States', 'LeRoy Golf Course'),
  ('United States', 'Lead Country Club'),
  ('United States', 'Leake Country Club'),
  ('United States', 'Leaning Pines Golf Course'),
  ('United States', 'Leaning Rock Golf Course'),
  ('United States', 'Leaning Tree Golf Course'),
  ('United States', 'Leatherstocking Golf Course'),
  ('United States', 'Leavenworth Golf Club'),
  ('United States', 'Lebanon Country Club'),
  ('United States', 'Lebanon Pines Golf Course'),
  ('United States', 'Lebanon Valley Golf Course'),
  ('United States', 'Lebaron Hills Country Club'),
  ('United States', 'Lederach Golf Club'),
  ('United States', 'Ledge Meadows Golf Course'),
  ('United States', 'Ledgemont Country Club'),
  ('United States', 'Ledgerock Golf Club'),
  ('United States', 'Ledges Golf Club'),
  ('United States', 'Ledgeview Golf And Country Club'),
  ('United States', 'Ledgeview Golf Course'),
  ('United States', 'Leeds Golf Club'),
  ('United States', 'Lees Hill Golf Club'),
  ('United States', 'Leesville Municipal Golf Course'),
  ('United States', 'Leewood Golf Club'),
  ('United States', 'Lefleurss Bluff Golf Course'),
  ('United States', 'Leflore County Country Club'),
  ('United States', 'Legacy Club At Alaqua Lakes'),
  ('United States', 'Legacy Courses at Cragun''s'),
  ('United States', 'Legacy Golf Club'),
  ('United States', 'Legacy Golf Club Executive Course'),
  ('United States', 'Legacy Golf Course'),
  ('United States', 'Legacy Golf Course 3 Holes Course'),
  ('United States', 'Legacy Golf Links'),
  ('United States', 'Legacy Hills Golf Club'),
  ('United States', 'Legacy Pines Golf Club'),
  ('United States', 'Legacy Ridge Country Club'),
  ('United States', 'Legacy Ridge Golf Course At Westminster'),
  ('United States', 'Legend At Tahquitz Creek Golf Resort'),
  ('United States', 'Legend Lake Golf Course'),
  ('United States', 'Legend Oaks Golf Club'),
  ('United States', 'Legend Trail Golf Club'),
  ('United States', 'Legend Trail Golf Course'),
  ('United States', 'Legendary Run Golf Course'),
  ('United States', 'Legends Golf Club'),
  ('United States', 'Legends Golf Country Club'),
  ('United States', 'Legends Golf Course'),
  ('United States', 'Legends Golf Resort Heathland Course'),
  ('United States', 'Legends Golf Resort Moorland Course'),
  ('United States', 'Legends Golf Resort Parkland Course'),
  ('United States', 'Legends On The Niagara Golf Course Battlefield'),
  ('United States', 'Legends On The Niagara Golf Course Chippawa'),
  ('United States', 'Legends On The Niagara Golf Course Usshers Creek'),
  ('United States', 'Legends Walk At Orange Lake Resort'),
  ('United States', 'Legion Memorial Golf Course'),
  ('United States', 'Legion Town Country Club'),
  ('United States', 'Lehigh Country Club'),
  ('United States', 'Lehigh Resort Club'),
  ('United States', 'Lehman Golf Club'),
  ('United States', 'Leicester Country Club'),
  ('United States', 'Leilehua Golf Course'),
  ('United States', 'Leisure Village Golf Club'),
  ('United States', 'Leisure Village Golf Course'),
  ('United States', 'Leisure Village Golf Course East Course'),
  ('United States', 'Leisure Village Par 3'),
  ('United States', 'Leisure Village West Pines Nine'),
  ('United States', 'Leisure Village West Willow Nine'),
  ('United States', 'Leisure World 3 Par Golf Course'),
  ('United States', 'Leisure World Golf Coyote Run Course'),
  ('United States', 'Leisure World Golf Heron Lakes Course'),
  ('United States', 'Leisureville Fairway'),
  ('United States', 'Leisureville Golf Course'),
  ('United States', 'Leland Country Club'),
  ('United States', 'Lely Resort Golf Country Club Flamingo Island Course'),
  ('United States', 'Lely Resort Golf Country Club Mustang Course'),
  ('United States', 'Lemon Bay Golf Club'),
  ('United States', 'Lemondrop Lounge Golf Links'),
  ('United States', 'Lemoore Golf Course'),
  ('United States', 'Lenape Heights Golf Course'),
  ('United States', 'Lenawee Country Club'),
  ('United States', 'Lenoir Golf Course'),
  ('United States', 'Lenox Community Golf Course'),
  ('United States', 'Leo J Martin Memorial Golf Course'),
  ('United States', 'Leonardville Golf Course'),
  ('United States', 'Leopards Chase Golf Links At Ocean Ridge Plantation'),
  ('United States', 'Les Bolstad Golf Course'),
  ('United States', 'Les Cheneaux Golf Course'),
  ('United States', 'Les Rochers Bleus Golf And Auberge'),
  ('United States', 'Les Vieux Chenes Golf Course'),
  ('United States', 'Leslie Park Golf Course'),
  ('United States', 'Lester Park Golf Course'),
  ('United States', 'Lew Wentz Golf Course'),
  ('United States', 'Lewis Clark Public Golf Course'),
  ('United States', 'Lewis River Golf Course'),
  ('United States', 'Lewiston Golf & Country Club'),
  ('United States', 'Lewiston Golf Country Club'),
  ('United States', 'Lewistown Country Club'),
  ('United States', 'Lexington Country Club'),
  ('United States', 'Lexington Golf Club'),
  ('United States', 'Lexington Golf Country Club'),
  ('United States', 'Lexington Oaks Golf Club'),
  ('United States', 'Liberal Country Club'),
  ('United States', 'Liberty Forge Golf Course'),
  ('United States', 'Liberty Hills Golf Club'),
  ('United States', 'Liberty Lake Golf Course'),
  ('United States', 'Liberty National Golf Course'),
  ('United States', 'Lick Creek Golf Course'),
  ('United States', 'Lida Greens'),
  ('United States', 'Lidgerwood Golf Course'),
  ('United States', 'Lido Golf Club'),
  ('United States', 'Ligonier Country Club'),
  ('United States', 'Likely Place Rv Golf'),
  ('United States', 'Lilmole Run Golf Course'),
  ('United States', 'Lily Lake Golf Resort'),
  ('United States', 'Limestone Country Club'),
  ('United States', 'Lincoln Country Club'),
  ('United States', 'Lincoln Elks Country Club'),
  ('United States', 'Lincoln Golf Course'),
  ('United States', 'Lincoln Greens Golf Course'),
  ('United States', 'Lincoln Hills Golf Club'),
  ('United States', 'Lincoln Hills Golf Course'),
  ('United States', 'Lincoln Homestead State Park'),
  ('United States', 'Lincoln Oaks Golf Course'),
  ('United States', 'Lincoln Park Golf Course'),
  ('United States', 'Lincoln Valley Golf Course / City of State Center'),
  ('United States', 'Lincolnshire Country Club'),
  ('United States', 'Lincolnshire Fields Country Club'),
  ('United States', 'Linda Vista Golf Course'),
  ('United States', 'Linden Golf Country Club'),
  ('United States', 'Linden Hall Golf Course'),
  ('United States', 'Linderhof Country Club'),
  ('United States', 'Lindsay Municipal Golf Course'),
  ('United States', 'Lindsborg Golf Course'),
  ('United States', 'Lindsey Golf Course'),
  ('United States', 'Linfield National Golf Club'),
  ('United States', 'Link Hills Country Club'),
  ('United States', 'Links & Tees Golf Facility'),
  ('United States', 'Links At Bear Lakes Country Club'),
  ('United States', 'Links At Bentonville Golf Athletic Club'),
  ('United States', 'Links At City Park Golf Course The'),
  ('United States', 'Links At Gettysburg'),
  ('United States', 'Links At Lowell The'),
  ('United States', 'Links At Norman Golf Country Club'),
  ('United States', 'Links At On Top Of The World'),
  ('United States', 'Links At Riverlakes Ranch'),
  ('United States', 'Links At Sandestin Golf And Beach Resort'),
  ('United States', 'Links At Sherwood The'),
  ('United States', 'Links At Sierra Blanca The'),
  ('United States', 'Links At Wild Dunes Golf Links'),
  ('United States', 'Links Canyon At Fox Hollow At Lakewood'),
  ('United States', 'Links Course At Paso Robles'),
  ('United States', 'Links Golf Club'),
  ('United States', 'Links Of Kent Golf Club & Event Centre'),
  ('United States', 'Links Of Lake Bernadette'),
  ('United States', 'Links Of Lake Mary'),
  ('United States', 'Links Of Sandpiper'),
  ('United States', 'Links Of Spruce Creek South'),
  ('United States', 'Links On The Bayou'),
  ('United States', 'Links Otryon'),
  ('United States', 'Links at Gateway'),
  ('United States', 'Links at Northfork'),
  ('United States', 'Links at Whitmore Lake Golf Course'),
  ('United States', 'Linkside At Pebble Creek Country Club'),
  ('United States', 'Linn Grove Country Club'),
  ('United States', 'Linrick Golf Course'),
  ('United States', 'Linville Falls Golf Club'),
  ('United States', 'Linville Golf Club'),
  ('United States', 'Linville Land Harbor Golf Club'),
  ('United States', 'Linville Ridge Country Club'),
  ('United States', 'Linwood Country Club'),
  ('United States', 'Lion Golf Club'),
  ('United States', 'Lion Hills Golf Course At East Mississippi Community College'),
  ('United States', 'Lions Club Municipal Golf Course'),
  ('United States', 'Lions Den Golf Club'),
  ('United States', 'Lions Head Country Club'),
  ('United States', 'Lions Paw At Ocean Ridge Plantation'),
  ('United States', 'Lisbon Village Country Club'),
  ('United States', 'Litchfield Country Club'),
  ('United States', 'Litchfield Golf Club'),
  ('United States', 'Litchfield Greens'),
  ('United States', 'Litl Links Golf Club'),
  ('United States', 'Little America Resort Golf'),
  ('United States', 'Little Apple Golf Course'),
  ('United States', 'Little Bear Golf Club'),
  ('United States', 'Little Bear Golf Course'),
  ('United States', 'Little Creek Golf Course'),
  ('United States', 'Little Creek Recreation Club'),
  ('United States', 'Little Crow Country Club'),
  ('United States', 'Little Falls Golf Course'),
  ('United States', 'Little Falls Municipal Golf Course'),
  ('United States', 'Little Fishing Creek Golf Course'),
  ('United States', 'Little Harbor Country Club'),
  ('United States', 'Little Met Golf Course'),
  ('United States', 'Little Miami Golf Center'),
  ('United States', 'Little Mountain Country Club'),
  ('United States', 'Little Nugget Golf Course (Closed)'),
  ('United States', 'Little Ocmulgee At Wallace Adams Course'),
  ('United States', 'Little River Country Club'),
  ('United States', 'Little River Inn Golf Tennis Club'),
  ('United States', 'Little River Municipal Golf Course'),
  ('United States', 'Little Willow Executive Course'),
  ('United States', 'Littleton Golf And Tennis Club'),
  ('United States', 'Live Oak Pitch Putt Golf Course'),
  ('United States', 'Live Oak Rv Golf Course'),
  ('United States', 'Live Oaks Golf Club'),
  ('United States', 'Livingston Country Club'),
  ('United States', 'Livingston Golf Country Club'),
  ('United States', 'Llanerch Country Club'),
  ('United States', 'Llano Grande Golf Course'),
  ('United States', 'Loblolly Executive Golf Course'),
  ('United States', 'Loblolly Pines Golf Course'),
  ('United States', 'Loch Haven Golf Center'),
  ('United States', 'Loch Lloyd Country Club'),
  ('United States', 'Loch Lloyd Country Club Sechrest Nine'),
  ('United States', 'Loch Lomond Golf Course'),
  ('United States', 'LochenHeath Golf Club'),
  ('United States', 'Lochmere Golf Club'),
  ('United States', 'Lochmere Golf Country Club'),
  ('United States', 'Lochmoor Club'),
  ('United States', 'Lochmor Golf Course'),
  ('United States', 'Lockeford Springs Golf Course'),
  ('United States', 'Lockport Golf and Recreation Club'),
  ('United States', 'Lockport Hole 1'),
  ('United States', 'Lockport Hole 2'),
  ('United States', 'Lockport Hole 3'),
  ('United States', 'Lockport Hole 4'),
  ('United States', 'Lockport Town Country Club'),
  ('United States', 'Lockwood Folly Country Club'),
  ('United States', 'Locust Hill Country Club'),
  ('United States', 'Locust Hills Golf Course'),
  ('United States', 'Lodge Of Four Seasons Cove Course'),
  ('United States', 'Lodge Of Four Seasons Ridge Course'),
  ('United States', 'Lodi Golf Club'),
  ('United States', 'Log Cabin Club'),
  ('United States', 'Logan Country Club'),
  ('United States', 'Logan Golf Country Club'),
  ('United States', 'Logan River Golf Course'),
  ('United States', 'Logansport Country Club'),
  ('United States', 'Loggers Trace'),
  ('United States', 'Loggers Trail Golf Course'),
  ('United States', 'Lomas Santa Fe Country Club'),
  ('United States', 'Lomas Santa Fe Executive Golf Course'),
  ('United States', 'London Downs Golf Club'),
  ('United States', 'Londonderry Country Club'),
  ('United States', 'Lone Palm Golf Club'),
  ('United States', 'Lone Pine Country Club'),
  ('United States', 'Lone Pine Golf Course'),
  ('United States', 'Lone Star Golf Course'),
  ('United States', 'Lone Tree Golf Club'),
  ('United States', 'Lone Tree Golf Club Hotel'),
  ('United States', 'Lone Tree Golf Course'),
  ('United States', 'Lonesome Pine Country Club'),
  ('United States', 'Long Bay Club'),
  ('United States', 'Long Beach Country Club'),
  ('United States', 'Long Bow Golf Club'),
  ('United States', 'Long Bridge Golf Course'),
  ('United States', 'Long Cove Club'),
  ('United States', 'Long Island National Golf Club'),
  ('United States', 'Long Lake Country Club'),
  ('United States', 'Long Meadow Golf Club'),
  ('United States', 'Long Point At Amelia Island Club'),
  ('United States', 'Long Prairie Country Club'),
  ('United States', 'Long Run Golf Course'),
  ('United States', 'Longbow Golf Club'),
  ('United States', 'Longest Hole Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Longhills Golf Course'),
  ('United States', 'Longhis Golf'),
  ('United States', 'Longleaf Executive Golf Course'),
  ('United States', 'Longleaf Golf Family Club'),
  ('United States', 'Longmeadow Country Club'),
  ('United States', 'Longue Vue Club'),
  ('United States', 'Longview Country Club'),
  ('United States', 'Longview Golf Course'),
  ('United States', 'Longwood Golf Course'),
  ('United States', 'Lonnie Poole Golf Course At North Carolina State University'),
  ('United States', 'Lonoke Golf Course'),
  ('United States', 'Lookaway Golf Club'),
  ('United States', 'Lookout Mountain Golf Club'),
  ('United States', 'Loomis Trail Golf Club'),
  ('United States', 'Loons Cove Golf Course'),
  ('United States', 'Lopez Island Golf Club'),
  ('United States', 'Lords Valley Country Club'),
  ('United States', 'Los Alamos Golf Course'),
  ('United States', 'Los Altos Golf Country Club'),
  ('United States', 'Los Altos Golf Course Executive Course'),
  ('United States', 'Los Altos Golf Course Los Altos Course'),
  ('United States', 'Los Amigos Country Club'),
  ('United States', 'Los Caballeros Golf Club'),
  ('United States', 'Los Feliz 3 Par Golf Course'),
  ('United States', 'Los Lagos At Costa Mesa Golf Country Club'),
  ('United States', 'Los Lagos Golf Club'),
  ('United States', 'Los Lagos Golf Course'),
  ('United States', 'Los Lagos La Vista At Desert Princess Country Club'),
  ('United States', 'Los Prados Golf Course'),
  ('United States', 'Los Robles Greens Golf Course'),
  ('United States', 'Los Verdes Golf Course'),
  ('United States', 'Losantiville Country Club'),
  ('United States', 'Lost Brook Golf Club'),
  ('United States', 'Lost City Golf Club East North'),
  ('United States', 'Lost City Golf Club East South'),
  ('United States', 'Lost City Golf Club South North'),
  ('United States', 'Lost Creek Golf Club'),
  ('United States', 'Lost Creek Golfers Club'),
  ('United States', 'Lost Dunes'),
  ('United States', 'Lost Key Golf Club'),
  ('United States', 'Lost Lake Golf Club'),
  ('United States', 'Lost Lake Woods Golf Course'),
  ('United States', 'Lost Marsh Golf Course'),
  ('United States', 'Lost Nation Golf Course'),
  ('United States', 'Lost Plantation Golf Club'),
  ('United States', 'Lost Springs Golf Athletic Club'),
  ('United States', 'Lost Spur Country Club'),
  ('United States', 'Lost Tree Club'),
  ('United States', 'Lost Woods Golf Course'),
  ('United States', 'Loudon Country Club'),
  ('United States', 'Loudon Meadows Golf Club'),
  ('United States', 'Loudoun Golf Country Club'),
  ('United States', 'Louisiana Technical Golf Course'),
  ('United States', 'Louisquisset Golf Club'),
  ('United States', 'Louisville Country Club'),
  ('United States', 'Lovington Country Club'),
  ('United States', 'Lower At Baltusrol Golf Club'),
  ('United States', 'Lower At Peekn Peak Golf Course'),
  ('United States', 'Lowlands Executive Golf Course'),
  ('United States', 'Loxahatchee Club'),
  ('United States', 'Loyal Oak Golf Course'),
  ('United States', 'Lpga International Hills Course'),
  ('United States', 'Lpga International Jones Course'),
  ('United States', 'Lpga International Practice Academy'),
  ('United States', 'Lsu Golf Course'),
  ('United States', 'Lu Gene Links Country Club'),
  ('United States', 'Lucas Oil Golf Course'),
  ('United States', 'Lucerne In Maine Golf Course'),
  ('United States', 'Lucky Hills Golf Course'),
  ('United States', 'Ludden Lake Golf Club'),
  ('United States', 'Ludlow Country Club'),
  ('United States', 'Lulu Country Club'),
  ('United States', 'Lunenburg Country Club'),
  ('United States', 'Lusk Municipal Golf Course'),
  ('United States', 'Lutz Executive Golf Center'),
  ('United States', 'Luverne Country Club'),
  ('United States', 'Lykens Valley Golf Course'),
  ('United States', 'Lyndon Golf Course'),
  ('United States', 'Lyndway Hills Golf Course'),
  ('United States', 'Lynndale''s Golf'),
  ('United States', 'Lynnwood Municipal Golf Course'),
  ('United States', 'Lynrock Golf Course'),
  ('United States', 'Lyon Oaks Golf Course'),
  ('United States', 'Lyons Town Country Club'),
  ('United States', 'M A 8 Golf'),
  ('United States', 'Ma Cal Grove Country Club'),
  ('United States', 'Macatawa Legends Golf & Country Club'),
  ('United States', 'Maccripine Country Club'),
  ('United States', 'Macdonald Golf Course'),
  ('United States', 'Macgregor Downs Country Club'),
  ('United States', 'Mack Mayfield Municipal Golf Course'),
  ('United States', 'Mackinaw Club'),
  ('United States', 'Macktown Golf Course')
on conflict (country, name) do nothing;