insert into public.golf_courses (country, name) values
  ('United States', 'Indian Palms Golf Country Club Indian Mountain'),
  ('United States', 'Indian Palms Golf Country Club Mountain Royal'),
  ('United States', 'Indian Palms Golf Country Club Royal Indian'),
  ('United States', 'Indian Peaks Golf Club'),
  ('United States', 'Indian Pond Country Club'),
  ('United States', 'Indian Ridge Country Club'),
  ('United States', 'Indian Ridge Country Club Arroyo Course'),
  ('United States', 'Indian Ridge Country Club Grove Course'),
  ('United States', 'Indian Ridge Golf Club'),
  ('United States', 'Indian River Club'),
  ('United States', 'Indian River Colony Club'),
  ('United States', 'Indian River Golf Club'),
  ('United States', 'Indian River Preserve Golf Club'),
  ('United States', 'Indian Run Golf Club'),
  ('United States', 'Indian Run Golf Course'),
  ('United States', 'Indian Spring Country Club East Course'),
  ('United States', 'Indian Spring Country Club West Course'),
  ('United States', 'Indian Spring Golf Club'),
  ('United States', 'Indian Springs Country Club'),
  ('United States', 'Indian Springs Golf And Country Club'),
  ('United States', 'Indian Springs Golf Club'),
  ('United States', 'Indian Springs Golf Course'),
  ('United States', 'Indian Springs Metropark Golf Course'),
  ('United States', 'Indian Springs Ranch'),
  ('United States', 'Indian Summer Golf Country Club'),
  ('United States', 'Indian Trace Golf Course'),
  ('United States', 'Indian Trail Golf Course'),
  ('United States', 'Indian Trails Golf Course'),
  ('United States', 'Indian Valley Country Club'),
  ('United States', 'Indian Valley Golf Club'),
  ('United States', 'Indian Valley Golf Course'),
  ('United States', 'Indian Wells Country Club The Classic Course'),
  ('United States', 'Indian Wells Country Club The Cove Course'),
  ('United States', 'Indian Wells Golf Resort Celebrity Course'),
  ('United States', 'Indian Wells Golf Resort Players Course'),
  ('United States', 'Indiana Country Club'),
  ('United States', 'Indianhead Golf Course'),
  ('United States', 'Indianola Country Club'),
  ('United States', 'Indianwood Gold & Country Club'),
  ('United States', 'Indianwood Golf Country Club'),
  ('United States', 'Indigo Creek Golf Club'),
  ('United States', 'Indio Golf Club'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Eisenhower Course'),
  ('United States', 'Industry Hills Golf Club At Pacific Palms Resort Zaharias Course'),
  ('United States', 'Ingersoll Golf Course'),
  ('United States', 'Ingleside Golf Club'),
  ('United States', 'Ingleside Resort Country Club'),
  ('United States', 'Inglewood Country Club'),
  ('United States', 'Inkster Valley Golf Course'),
  ('United States', 'Inland Greens Golf Course'),
  ('United States', 'Inlet Golf Club'),
  ('United States', 'Inn Of The Mountain Gods'),
  ('United States', 'Inness Golf Course'),
  ('United States', 'Innis Arden Golf Club'),
  ('United States', 'Innisbrook Resort Golf Club Copperhead Course'),
  ('United States', 'Innisbrook Resort Golf Club Fox Squirrel Course'),
  ('United States', 'Innisbrook Resort Golf Club Island Course'),
  ('United States', 'Innisbrook Resort Golf Club North Course'),
  ('United States', 'Innisbrook Resort Golf Club South Course'),
  ('United States', 'Inniscrone Golf Club'),
  ('United States', 'Innsbrook Country Club'),
  ('United States', 'Innsbrook Golf Course'),
  ('United States', 'Innsbrook Village Country Club'),
  ('United States', 'Inshalla Country Club'),
  ('United States', 'Interbay Family Golf Center'),
  ('United States', 'Interlachen Country Club'),
  ('United States', 'Interlaken Golf Club'),
  ('United States', 'Interlochen Golf Course'),
  ('United States', 'Interlocken Golf Club Eldorado Sunshine'),
  ('United States', 'Interlocken Golf Club Sunshine Vista'),
  ('United States', 'Interlocken Golf Club Vista Eldorado'),
  ('United States', 'International At Cedar Valley Golf Club'),
  ('United States', 'International City Golf Club'),
  ('United States', 'International Club Of Myrtle Beach'),
  ('United States', 'International Country Club'),
  ('United States', 'International Golf Club Oaks Course'),
  ('United States', 'International Golf Club Pines Course'),
  ('United States', 'Intervale Country Club'),
  ('United States', 'Intimidator Golf Course'),
  ('United States', 'Inver Wood Golf Course'),
  ('United States', 'Inverness Club'),
  ('United States', 'Inverness Country Club'),
  ('United States', 'Inverness Golf Club'),
  ('United States', 'Inverness Golf Country Club'),
  ('United States', 'Inverness Hotel Golf Club'),
  ('United States', 'Inverugie Golf Club'),
  ('United States', 'Inwood Country Club'),
  ('United States', 'Inwood Golf Course'),
  ('United States', 'Ipswich Country Club'),
  ('United States', 'Irem Country Club'),
  ('United States', 'Irene Golf And Country Club'),
  ('United States', 'Irish Green Golf Course'),
  ('United States', 'Irish Hills Golf Club'),
  ('United States', 'Irish Hills Shore Golf Course'),
  ('United States', 'Irish Oaks Golf Course and Driving Range'),
  ('United States', 'Irish Waters Golf Course'),
  ('United States', 'Iron Forge At Penn National Golf Club Inn'),
  ('United States', 'Iron Horse Golf Club'),
  ('United States', 'Iron Horse Golf Course'),
  ('United States', 'Iron Links Golf Course'),
  ('United States', 'Iron Masters Country Club'),
  ('United States', 'Iron Play Golf Course'),
  ('United States', 'Iron River Country Club'),
  ('United States', 'Iron Valley Golf Club'),
  ('United States', 'Iron Wolf Golf Country Club'),
  ('United States', 'Ironbridge Golf Club'),
  ('United States', 'Ironclad Golf And Beer Garden'),
  ('United States', 'Irondequoit Country Club'),
  ('United States', 'Ironhorse Golf Club'),
  ('United States', 'Ironwood Acacia At Kierland Golf Club'),
  ('United States', 'Ironwood Country Club'),
  ('United States', 'Ironwood Golf Club'),
  ('United States', 'Ironwood Golf Country Club'),
  ('United States', 'Ironwood Golf Course'),
  ('United States', 'Ironwood Golf Range'),
  ('United States', 'Ironwood Green Golf Course'),
  ('United States', 'Ironwood Hills Golf Club'),
  ('United States', 'Iroquois Golf Club'),
  ('United States', 'Iroquois Golf Course'),
  ('United States', 'Irv Warren Memorial Golf Course'),
  ('United States', 'Irwin Country Club'),
  ('United States', 'Isabella Golf Course Nina'),
  ('United States', 'Isabella Golf Course Pinta'),
  ('United States', 'Isabella Golf Course Santa Maria'),
  ('United States', 'Ischua Valley Country Club'),
  ('United States', 'Isla Del Sol Golf Yacht Country Club'),
  ('United States', 'Island At Holiday Island Country Club'),
  ('United States', 'Island Country Club'),
  ('United States', 'Island Dunes Country Club'),
  ('United States', 'Island Green Golf Course'),
  ('United States', 'Island Green Longest Hole At Meadows Farms Golf Course'),
  ('United States', 'Island Green Waterfall At Meadows Farms Golf Course'),
  ('United States', 'Island Hills Golf Club'),
  ('United States', 'Island Lake Golf'),
  ('United States', 'Island Oaks At Lima Golf Country Club'),
  ('United States', 'Island Park Village Resort'),
  ('United States', 'Island Pines Golf Club'),
  ('United States', 'Island Valley Golf Course'),
  ('United States', 'Island West Golf Club'),
  ('United States', 'Islands End Golf Country Club'),
  ('United States', 'Isle Dauphine Golf Club'),
  ('United States', 'Isleta Eagle Golf Course Arroyo Mesa Course'),
  ('United States', 'Isleta Eagle Golf Course Lakes Arroyo Course'),
  ('United States', 'Isleta Eagle Golf Course Mesa Lakes Course'),
  ('United States', 'Isleworth Country Club'),
  ('United States', 'Itasca Country Club'),
  ('United States', 'Iuka Country Club'),
  ('United States', 'Ivanhoe Club'),
  ('United States', 'Ives Grove Golf Links'),
  ('United States', 'Ives Hill Country Club'),
  ('United States', 'Ivey Ranch Country Club'),
  ('United States', 'Ivy Hill Golf Club'),
  ('United States', 'Ivy Hills Country Club'),
  ('United States', 'Iyopawa Island Golf Course'),
  ('United States', 'J B Golf Course'),
  ('United States', 'J F Kennedy Golf Center Par 3 Course'),
  ('United States', 'J F Kennedy Golf Center West Creek Course'),
  ('United States', 'J S Clark Park Golf Course'),
  ('United States', 'Jacaranda West Country Club'),
  ('United States', 'Jack Frost National Golf Course'),
  ('United States', 'Jack Olantern Golf Resort'),
  ('United States', 'Jackpot Golf Club'),
  ('United States', 'Jackson College Disc Golf'),
  ('United States', 'Jackson County Country Club'),
  ('United States', 'Jackson Golf Club'),
  ('United States', 'Jackson Heights Golf Club'),
  ('United States', 'Jackson Hole Golf Tennis Club'),
  ('United States', 'Jackson Park Driving Range'),
  ('United States', 'Jackson Park Golf Course'),
  ('United States', 'Jackson Valley Country Club'),
  ('United States', 'Jacksonville Beach Golf Club'),
  ('United States', 'Jacksonville Country Club'),
  ('United States', 'Jacksonville Golf Country Club'),
  ('United States', 'Jacob Riis Park Golf Course'),
  ('United States', 'Jacoby Golf Course'),
  ('United States', 'Jade Trace At Mystic Meadows'),
  ('United States', 'Jake Gaither Municipal Golf Course'),
  ('United States', 'Jal Country Club'),
  ('United States', 'James Baird State Park Golf Course'),
  ('United States', 'James C Haggerty North Kern Golf Course'),
  ('United States', 'James E Stewart Golf Course'),
  ('United States', 'James River Country Club'),
  ('United States', 'Jamestown Golf Course'),
  ('United States', 'Jamestown Park Golf Course'),
  ('United States', 'Janesville Country Club'),
  ('United States', 'Jasper Hills Golf Club'),
  ('United States', 'Jato Highlands Golf Course'),
  ('United States', 'Jawbone Creek Country Club'),
  ('United States', 'Jay Peak Golf Course'),
  ('United States', 'Jaycee Golf Course'),
  ('United States', 'Jefferson Barracks Golf Tee'),
  ('United States', 'Jefferson Country Club'),
  ('United States', 'Jefferson District Golf Course'),
  ('United States', 'Jefferson Golf Club'),
  ('United States', 'Jefferson Hills Golf Recreation'),
  ('United States', 'Jefferson Lakeside Country Club'),
  ('United States', 'Jefferson Landing On The New River'),
  ('United States', 'Jeffersonville Golf Club'),
  ('United States', 'Jekyll Island Golf Club Great Dunes Course'),
  ('United States', 'Jekyll Island Golf Club Indian Mound Course'),
  ('United States', 'Jekyll Island Golf Club Pine Lakes Course'),
  ('United States', 'Jennings Golf Club'),
  ('United States', 'Jennings Mill Country Club'),
  ('United States', 'Jenny Wiley State Resort Park'),
  ('United States', 'Jensen Beach Golf Club'),
  ('United States', 'Jeptha Lake Golf Course'),
  ('United States', 'Jeremy Ranch Golf Country Club'),
  ('United States', 'Jeremy S Creek'),
  ('United States', 'Jericho National Golf Club'),
  ('United States', 'Jerome Country Club'),
  ('United States', 'Jerry Tim Brooks Golf Course'),
  ('United States', 'Jester Park Executive Golf Course'),
  ('United States', 'Jester Park Golf Course'),
  ('United States', 'Jester Park Learning and Practice Facility'),
  ('United States', 'Jesup Golf & Country Club'),
  ('United States', 'Jewel Golf Course - Grand Nine'),
  ('United States', 'Jewel Golf Course - Woods Nine'),
  ('United States', 'Jewell Golf and Country Club'),
  ('United States', 'Jimmie Austin Golf Course'),
  ('United States', 'Jimmie Austin University Of Oklahoma Golf Course'),
  ('United States', 'Jo Daddys Golf Course'),
  ('United States', 'Joa Company Golf Course'),
  ('United States', 'Joe Louis "The Champ" Golf Course'),
  ('United States', 'John A White Golf Course'),
  ('United States', 'John Conrad Golf Course'),
  ('United States', 'John F Byrne Golf Course'),
  ('United States', 'John James Audubon Golf Course'),
  ('United States', 'John P Larkin Country Club'),
  ('United States', 'John Prince Golf Learning Center'),
  ('United States', 'Johnny Goodman Golf Course'),
  ('United States', 'Johnson County Country Club'),
  ('United States', 'Johnson Park Golf Course'),
  ('United States', 'Johnson Ridge Golf Course'),
  ('United States', 'Johnson W Parks Golf Course'),
  ('United States', 'Joliet Country Club (closed)'),
  ('United States', 'Jonathans Landing Golf Club Match Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Club Medal Course At Old Trail'),
  ('United States', 'Jonathans Landing Golf Course'),
  ('United States', 'Jonathans Landing Village Course'),
  ('United States', 'Jones At Lyman Orchards Golf Club'),
  ('United States', 'Jones At Sea Trail Golf Resort And Convention Center'),
  ('United States', 'Jones Beach State Park Golf Course'),
  ('United States', 'Jones Golf Course'),
  ('United States', 'Jones Golf Course Speidel At Oglebay Resort'),
  ('United States', 'Jones Masterpiece At Treetops Resort'),
  ('United States', 'Jonesboro Country Club'),
  ('United States', 'Jordan River Par Three Golf Course'),
  ('United States', 'Joseph C Martin Golf Course'),
  ('United States', 'Joseph M Bartholomew Golf Course'),
  ('United States', 'Journey At Pechanga'),
  ('United States', 'Journey S End Golf Course'),
  ('United States', 'Jrs Pub Grill Golf Course'),
  ('United States', 'Juan De Fuca Parks Golf Club'),
  ('United States', 'Juday Creek Golf Course'),
  ('United States', 'Judge Rodney S. Webb Memorial Golf Park'),
  ('United States', 'Judith Shadows Golf Course'),
  ('United States', 'Jug Mountain Ranch Golf Course'),
  ('United States', 'Juliette Falls'),
  ('United States', 'Julington Creek Golf Club'),
  ('United States', 'Jumping Brook Country Club'),
  ('United States', 'Junction City Golf Course'),
  ('United States', 'Jungle At Green Meadow Golf Club'),
  ('United States', 'Juniata Golf Club'),
  ('United States', 'Junior National Golf Club'),
  ('United States', 'Juniper Hill Golf Course'),
  ('United States', 'Juniper Hills Country Club'),
  ('United States', 'Juniper Ridge R V Resort'),
  ('United States', 'Jupiter Country Club'),
  ('United States', 'Jupiter Dunes Golf Course'),
  ('United States', 'Jupiter Island Club'),
  ('United States', 'Jurupa Hills Country Club'),
  ('United States', 'Kaanapali Kai'),
  ('United States', 'Kah Wah C Country Club'),
  ('United States', 'Kahili Golf Course'),
  ('United States', 'Kahkwa Club'),
  ('United States', 'Kahler Mountain Club'),
  ('United States', 'Kahuku Golf Course'),
  ('United States', 'Kalamazoo Country Club'),
  ('United States', 'Kalispel Golf Country Club'),
  ('United States', 'Kalona Golf Club'),
  ('United States', 'Kaluhyat Golf Club At Turning Stone'),
  ('United States', 'Kampen Golf Course'),
  ('United States', 'Kane Country Club'),
  ('United States', 'Kaneohe Klipper Golf Course'),
  ('United States', 'Kankakee Country Club'),
  ('United States', 'Kankakee Elks Country Club'),
  ('United States', 'Kanon Valley Country Club'),
  ('United States', 'Kansas City Country Club'),
  ('United States', 'Kapalua Resort The Bay Course'),
  ('United States', 'Kapalua Resort The Plantation Course'),
  ('United States', 'Kapolei Golf Club'),
  ('United States', 'Karsten Creek Golf Club'),
  ('United States', 'Katahdin Country Club'),
  ('United States', 'Katke Golf Course'),
  ('United States', 'Kaufman Golf Course'),
  ('United States', 'Kaylers Bend Golf Course'),
  ('United States', 'Ke Olu Course At Hualalai'),
  ('United States', 'Kealohi Par 3 Golf Course'),
  ('United States', 'Kearny Golf Club'),
  ('United States', 'Kearsley Lake Golf Course'),
  ('United States', 'Kebo Valley Club'),
  ('United States', 'Keene Country Club'),
  ('United States', 'Keith Hills Golf Club Black Course'),
  ('United States', 'Keith Hills Golf Club Orange Course'),
  ('United States', 'Keith Hills Golf Club White Course'),
  ('United States', 'Kelley Greens Golf Course'),
  ('United States', 'Kellogg Executive 9'),
  ('United States', 'Kellogg Golf Course'),
  ('United States', 'Kelly Greens Golf Country Club'),
  ('United States', 'Kelly Plantation Golf Club'),
  ('United States', 'Kelly''s Miniature Golf'),
  ('United States', 'Kemper Lakes Golf Club'),
  ('United States', 'Kempsville Greens Golf Course'),
  ('United States', 'Ken Mcdonald Golf Course'),
  ('United States', 'Kenai Golf Course'),
  ('United States', 'Kendrick Golf Course'),
  ('United States', 'Kenduskeag Valley Golf Club'),
  ('United States', 'Keney Park Golf Club'),
  ('United States', 'Kenmure Country Club'),
  ('United States', 'Kennett Country Club'),
  ('United States', 'Kennett Square Golf Country Club'),
  ('United States', 'Kenosha Country Club'),
  ('United States', 'Kensington Driving Range'),
  ('United States', 'Kensington Golf Club'),
  ('United States', 'Kensington Golf Country Club'),
  ('United States', 'Kensington Metropark Golf Course'),
  ('United States', 'Kent Country Club'),
  ('United States', 'Kenterra Golf Course'),
  ('United States', 'Kenton Station Golf Course'),
  ('United States', 'Kentucky Dam Village State Resort Park'),
  ('United States', 'Kenwanda Golf Course'),
  ('United States', 'Kenwood Country Club'),
  ('United States', 'Kenwood Golf Country Club'),
  ('United States', 'Kenya Hemingway At Havana Country Club'),
  ('United States', 'Kenyon Country Club'),
  ('United States', 'Keokuk Country Club'),
  ('United States', 'Keowee Key Golf Country Club'),
  ('United States', 'Kern River Golf Course'),
  ('United States', 'Kern Valley Golf Course'),
  ('United States', 'Kernoustie Golf Club'),
  ('United States', 'Kernwood Country Club'),
  ('United States', 'Kerr Lake Country Club'),
  ('United States', 'Kershaw Country Club'),
  ('United States', 'Kestrel Ridge Golf Club'),
  ('United States', 'Kettle Brook Golf Club'),
  ('United States', 'Kettle Hills Golf Course'),
  ('United States', 'Kettle Valley Golf Club'),
  ('United States', 'Kewanee Dunes Golf Club'),
  ('United States', 'Keweenaw Mountain Lodge Golf Course'),
  ('United States', 'Key Colony Beach Golf Tennis'),
  ('United States', 'Key Royale Club'),
  ('United States', 'Key Vista Country Club'),
  ('United States', 'Key West Golf Club'),
  ('United States', 'Keyhole Country Club'),
  ('United States', 'Keystone Golf Country Club'),
  ('United States', 'Keystone Golf Course'),
  ('United States', 'Keystone Ranch Golf Course'),
  ('United States', 'Kiahuna Golf Club'),
  ('United States', 'Kiawah Island Club Cassique Course'),
  ('United States', 'Kiawah Island Club River Course'),
  ('United States', 'Kickingbird Golf Club'),
  ('United States', 'Kilgores Roundabout Plantation Golf Course'),
  ('United States', 'Kilimanjaro Kenya At Havana Country Club'),
  ('United States', 'Kilkarney Hills Golf Course'),
  ('United States', 'Killarney Lakeside Golf Club'),
  ('United States', 'Killian Greens Golf Club'),
  ('United States', 'Killington Golf Resort'),
  ('United States', 'Kilmarlic Golf Club'),
  ('United States', 'Kiln Creek Golf Club Resort'),
  ('United States', 'Kimball Farm Golf Club'),
  ('United States', 'Kimball Golf Club'),
  ('United States', 'Kimbeland Country Club'),
  ('United States', 'Kimberly Oaks Golf Club'),
  ('United States', 'Kimberton Golf Club'),
  ('United States', 'Kincaid Lake Golf Course'),
  ('United States', 'Kinderlou Forest Golf Club'),
  ('United States', 'Kinderton Country Club'),
  ('United States', 'King And Bear Golf Course At World Golf Village'),
  ('United States', 'King City Golf Course'),
  ('United States', 'King Ferry Golf Club'),
  ('United States', 'King Kamehameha Golf Club'),
  ('United States', 'King Links Golf Course'),
  ('United States', 'King Rail Reserve Golf Course'),
  ('United States', 'King Ranch Golf Course'),
  ('United States', 'King Valley Golf Course'),
  ('United States', 'King''s Walk'),
  ('United States', 'Kingfisher Golf Course'),
  ('United States', 'Kingham Prairie View Golf Course'),
  ('United States', 'Kings Arrow Ranch Hillsdale Course'),
  ('United States', 'Kings Country Club'),
  ('United States', 'Kings Creek Country Club'),
  ('United States', 'Kings Crossing Golf Club'),
  ('United States', 'Kings Deer Golf Club'),
  ('United States', 'Kings Gate Golf Club'),
  ('United States', 'Kings Grant Golf Country Club'),
  ('United States', 'Kings Mountain Country Club'),
  ('United States', 'Kings Mountain Golf Course'),
  ('United States', 'Kings Point Executive Course'),
  ('United States', 'Kings Point Executive Golf Course'),
  ('United States', 'Kings Point Par 3')
on conflict (country, name) do nothing;