insert into public.golf_courses (country, name) values
  ('United States', 'Kings Ridge Golf Club Kings Course'),
  ('United States', 'Kings Ridge Golf Club Ridge Course'),
  ('United States', 'Kings River Golf Country Club'),
  ('United States', 'Kings River Golf Course'),
  ('United States', 'Kings Valley Golf Course'),
  ('United States', 'Kings Walk'),
  ('United States', 'Kings Way Golf Club'),
  ('United States', 'Kingsboro Golf Club'),
  ('United States', 'Kingsmill Resort Plantation Course'),
  ('United States', 'Kingsmill Resort River Course'),
  ('United States', 'Kingston Fairways Golf Club'),
  ('United States', 'Kingsville Golf & Country Club'),
  ('United States', 'Kingswell Glen'),
  ('United States', 'Kingswood Golf Club'),
  ('United States', 'Kingwood Golf Club Resort'),
  ('United States', 'Kinkora Golf Course'),
  ('United States', 'Kinloch Golf Club'),
  ('United States', 'Kino Springs Golf Course'),
  ('United States', 'Kinsale Golf Club'),
  ('United States', 'Kinsale Golf and Fitness Club'),
  ('United States', 'Kinsley Country Club'),
  ('United States', 'Kinston Country Club'),
  ('United States', 'Kira S Kingdom Golf Course'),
  ('United States', 'Kirby Country Club'),
  ('United States', 'Kirkbrae Country Club'),
  ('United States', 'Kirkmans Lakeview Golf Course'),
  ('United States', 'Kirkwood National Golf Club'),
  ('United States', 'Kis N Greens Golf Course'),
  ('United States', 'Kishwaukee Country Club'),
  ('United States', 'Kiski Prep School Golf Course'),
  ('United States', 'Kiskiack Golf Club'),
  ('United States', 'Kissena Park Golf Course'),
  ('United States', 'Kissimmee Bay Country Club'),
  ('United States', 'Kissing Tree Golf Club'),
  ('United States', 'Kitsap Golf Country Club'),
  ('United States', 'Kittanning Country Club'),
  ('United States', 'Klinger Lake Country Club'),
  ('United States', 'Knickerbocker Country Club'),
  ('United States', 'Knights Play Golf Center'),
  ('United States', 'Knights Play Golf Center 9 Hole Par 3'),
  ('United States', 'Knights of Columbus Par 3 Course'),
  ('United States', 'Knob Hill Golf Course'),
  ('United States', 'Knobbs Creek Par 3 Golf Course'),
  ('United States', 'Knoll East Country Club The'),
  ('United States', 'Knoll Run Golf Course'),
  ('United States', 'Knoll View Golf Course'),
  ('United States', 'Knoll West Country Club'),
  ('United States', 'Knolls Country Club'),
  ('United States', 'Knollwood Club Golf Course'),
  ('United States', 'Knollwood Country Club'),
  ('United States', 'Knollwood Country Club - East Course'),
  ('United States', 'Knollwood Country Club - West Course'),
  ('United States', 'Knollwood Fairways'),
  ('United States', 'Knollwood Golf Course'),
  ('United States', 'Ko Olina Golf Club'),
  ('United States', 'Koa Fairways Golf Course'),
  ('United States', 'Koasati Pines At Coushatta'),
  ('United States', 'Kohala Golf Park'),
  ('United States', 'Kohanaiki Club'),
  ('United States', 'Kokomo Country Club'),
  ('United States', 'Kokopelli Club'),
  ('United States', 'Kokopelli Golf Course'),
  ('United States', 'Kona Country Club'),
  ('United States', 'Kona Mansion Inn'),
  ('United States', 'Koronis Hills Golf Club'),
  ('United States', 'Koshkonong Mounds Country Club'),
  ('United States', 'Kountryside Golf Course'),
  ('United States', 'Kraftsmens Club'),
  ('United States', 'Kresson Golf Club'),
  ('United States', 'Krooked Kreek Golf Course'),
  ('United States', 'Krueger-Haskell Golf Course'),
  ('United States', 'Kuehn Golf Course'),
  ('United States', 'Kukio 10 Hole Course'),
  ('United States', 'Kukio Championship Course'),
  ('United States', 'Kukuiolono Golf Course'),
  ('United States', 'Kukuiula Golf Course'),
  ('United States', 'Kulm Golf Club'),
  ('United States', 'Kwiniaska Golf Club'),
  ('United States', 'Kyle Memorial Golf Course'),
  ('United States', 'L A Golf Club'),
  ('United States', 'L W Clapp Golf Club'),
  ('United States', 'L''Anse Golf Club'),
  ('United States', 'L.C. Boles Golf Course Holes 1-2,9'),
  ('United States', 'L.C. Boles Golf Course Holes 3-8'),
  ('United States', 'LYNX Golf Course & Grill'),
  ('United States', 'La Canada Flintridge Country Club'),
  ('United States', 'La Cita Country Club'),
  ('United States', 'La Contenta Golf Club'),
  ('United States', 'La Crosse Country Club'),
  ('United States', 'La Cumbre Country Club'),
  ('United States', 'La Gorce Country Club'),
  ('United States', 'La Grange Country Club'),
  ('United States', 'La Jolla Beach Tennis Club'),
  ('United States', 'La Jolla Country Club'),
  ('United States', 'La Junta Golf Course'),
  ('United States', 'La Mirada Golf Club'),
  ('United States', 'La Porte City Golf Club'),
  ('United States', 'La Purisima Golf Course'),
  ('United States', 'La Quinta Country Club'),
  ('United States', 'La Quinta Resort Citrus Course'),
  ('United States', 'La Rinconada Country Club'),
  ('United States', 'La Valle Coastal Club East South Course'),
  ('United States', 'La Valle Coastal Club North East Course'),
  ('United States', 'La Valle Coastal Club South North Course'),
  ('United States', 'La Vida Country Club'),
  ('United States', 'La Vista El Cielo At Desert Princess Country Club'),
  ('United States', 'Lac Vieux Desert Golf Course'),
  ('United States', 'Lacoma Golf Course'),
  ('United States', 'Laconia Country Club'),
  ('United States', 'Ladera Golf Club'),
  ('United States', 'Ladera Golf Course Championship Course'),
  ('United States', 'Ladera Golf Course Executive Course'),
  ('United States', 'Lafayette Club'),
  ('United States', 'Lafayette Country Club'),
  ('United States', 'Lafayette Municipal Golf Course'),
  ('United States', 'Lafollette Country Club'),
  ('United States', 'Lafortune Park At Lafortune Park Golf Course'),
  ('United States', 'Lago Mar Country Club'),
  ('United States', 'Lagoon At Ponte Vedra Inn Club'),
  ('United States', 'Lagos Acres Golf & Country Club'),
  ('United States', 'Laguna Lake Golf Course'),
  ('United States', 'Laguna Oaks Golf Course'),
  ('United States', 'Laguna Seca Golf Club'),
  ('United States', 'Laguna Woods Golf Club 1 2 Course'),
  ('United States', 'Laguna Woods Golf Club 1 3 Course'),
  ('United States', 'Laguna Woods Golf Club 2 3 Course'),
  ('United States', 'Laguna Woods Golf Club Par 3 Course'),
  ('United States', 'Lahontan Golf Club'),
  ('United States', 'Lahontan Golf Club The Par 3 Course'),
  ('United States', 'Lake Almanor Country Club'),
  ('United States', 'Lake Almanor West Golf Course'),
  ('United States', 'Lake Arbor Golf Course'),
  ('United States', 'Lake Arrowhead Country Club'),
  ('United States', 'Lake Arrowhead Yacht Country Club Highlands Course'),
  ('United States', 'Lake Arthur Country Club'),
  ('United States', 'Lake Ashton Golf Club The East Course'),
  ('United States', 'Lake Ashton Golf Club The West Course'),
  ('United States', 'Lake At Carolina Trace Country Club'),
  ('United States', 'Lake At Mountain Dell Golf Course'),
  ('United States', 'Lake At Wasatch Mountain State Park'),
  ('United States', 'Lake Barrington Shores Golf Club'),
  ('United States', 'Lake Barton Golf Course'),
  ('United States', 'Lake Bess Country Club'),
  ('United States', 'Lake Bluff Golf Course'),
  ('United States', 'Lake Bonaventure Country Club'),
  ('United States', 'Lake Breeze Golf Club'),
  ('United States', 'Lake Bruin Golf Country Club'),
  ('United States', 'Lake Carlsbad Golf Course Championship Course'),
  ('United States', 'Lake Carlsbad Golf Course Par 3 Course'),
  ('United States', 'Lake Caroline Golf Club'),
  ('United States', 'Lake Carroll Golf Club'),
  ('United States', 'Lake Chabot Golf Course Executive Par 3 Course'),
  ('United States', 'Lake Chabot Golf Course The 18 Hole Course'),
  ('United States', 'Lake Charles Country Club'),
  ('United States', 'Lake Chelan Golf Course'),
  ('United States', 'Lake Chesdin Golf Club'),
  ('United States', 'Lake City Country Club'),
  ('United States', 'Lake City Golf'),
  ('United States', 'Lake Cora Hills'),
  ('United States', 'Lake Cushman Golf Course'),
  ('United States', 'Lake Darbonne Country Club'),
  ('United States', 'Lake Diamond Golf Country Club'),
  ('United States', 'Lake Doster Golf Club'),
  ('United States', 'Lake Erie Metropark Golf Course'),
  ('United States', 'Lake Estes Executive 9 Hole Course'),
  ('United States', 'Lake Fairways Country Club'),
  ('United States', 'Lake Forest Country Club'),
  ('United States', 'Lake Forest Golf Club'),
  ('United States', 'Lake Forest Golf Practice Center'),
  ('United States', 'Lake Gaston Golf Club'),
  ('United States', 'Lake Geneva Country Club'),
  ('United States', 'Lake Hallie Golf'),
  ('United States', 'Lake Havasu Golf Club East Course'),
  ('United States', 'Lake Havasu Golf Club West Course'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Dogwood'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Fox Run'),
  ('United States', 'Lake Hickory Country Club At Catawba Springs Sulphur Springs'),
  ('United States', 'Lake Hickory Country Club Town Course'),
  ('United States', 'Lake Hills Golf Club'),
  ('United States', 'Lake Isle Country Club'),
  ('United States', 'Lake James Golf Course'),
  ('United States', 'Lake Jonesco Golf Course'),
  ('United States', 'Lake Jovita Golf Country Club North Course'),
  ('United States', 'Lake Jovita Golf Country Club South Course'),
  ('United States', 'Lake Junaluska Golf Course'),
  ('United States', 'Lake June West Golf Course'),
  ('United States', 'Lake Kezar Country Club'),
  ('United States', 'Lake Kiowa Country Club'),
  ('United States', 'Lake Lackawanna Golf Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Ii Course'),
  ('United States', 'Lake Land Village Golf Course Generation I Iii Course'),
  ('United States', 'Lake Land Village Golf Course Generation Ii Iii Course'),
  ('United States', 'Lake Leann Golf Course'),
  ('United States', 'Lake Limerick Country Club'),
  ('United States', 'Lake Lindero Golf Course'),
  ('United States', 'Lake Lorain Golf Club'),
  ('United States', 'Lake Lure Municipal Golf Course'),
  ('United States', 'Lake MacBride Golf Course'),
  ('United States', 'Lake Marion Golf Course'),
  ('United States', 'Lake Merced Golf Country Club'),
  ('United States', 'Lake Michigan Hills Golf Club'),
  ('United States', 'Lake Mills Golf Course'),
  ('United States', 'Lake Mohawk Golf Club'),
  ('United States', 'Lake Monterey Golf Course'),
  ('United States', 'Lake Monticello Golf Course'),
  ('United States', 'Lake Morey Inn Resort Country Club'),
  ('United States', 'Lake Mountain At Stratton Mountain Country Club'),
  ('United States', 'Lake Murray Golf Center'),
  ('United States', 'Lake Murray State Park Golf Course'),
  ('United States', 'Lake Nona Golf Country Club'),
  ('United States', 'Lake North At Mountain Gate Country Club'),
  ('United States', 'Lake Of The Forest Golf Course'),
  ('United States', 'Lake Of The Pines Country Club'),
  ('United States', 'Lake Of The Woods Country Club'),
  ('United States', 'Lake Oroville Golf Country Club'),
  ('United States', 'Lake Padden Golf Course'),
  ('United States', 'Lake Panorama National Golf Course'),
  ('United States', 'Lake Park Golf Course'),
  ('United States', 'Lake Pepin Golf Course'),
  ('United States', 'Lake Perry Country Club'),
  ('United States', 'Lake Pine Golf Course At Countryside Country Club'),
  ('United States', 'Lake Placid Club Links Course'),
  ('United States', 'Lake Placid Club Mountain Course'),
  ('United States', 'Lake Placid Club Pristine Nine Course'),
  ('United States', 'Lake Platte Golf Club'),
  ('United States', 'Lake Pleasant Golf Club'),
  ('United States', 'Lake Pleasant Golf Course'),
  ('United States', 'Lake Powell National Golf Course'),
  ('United States', 'Lake Providence Country Club'),
  ('United States', 'Lake Quivira Country Club'),
  ('United States', 'Lake Redding Golf Course'),
  ('United States', 'Lake Ridge Park Golf Marina'),
  ('United States', 'Lake Ripley Country Club'),
  ('United States', 'Lake Saint Louis 9-Hole Golf Course'),
  ('United States', 'Lake Shawnee Golf Course'),
  ('United States', 'Lake Shore Country Club'),
  ('United States', 'Lake Shore Course At Lake Shore Country Club'),
  ('United States', 'Lake Shore Golf Club'),
  ('United States', 'Lake Side Golf Course'),
  ('United States', 'Lake Spanaway Golf Course'),
  ('United States', 'Lake Spivey Golf Club'),
  ('United States', 'Lake St Catherine Country Club'),
  ('United States', 'Lake Success Golf Club'),
  ('United States', 'Lake Sunapee Country Club'),
  ('United States', 'Lake Superior View Golf'),
  ('United States', 'Lake Tahoe Golf Course'),
  ('United States', 'Lake Tamarisk Golf Course'),
  ('United States', 'Lake Toxaway Country Club'),
  ('United States', 'Lake Valley At Los Coyotes Country Club'),
  ('United States', 'Lake Valley At Pinery Country Club'),
  ('United States', 'Lake Valley Golf Club'),
  ('United States', 'Lake View At Callaway Gardens Resort'),
  ('United States', 'Lake View Country Club'),
  ('United States', 'Lake View Executive Golf Course'),
  ('United States', 'Lake View National Golf Course'),
  ('United States', 'Lake Village Country Club'),
  ('United States', 'Lake Wales Country Club'),
  ('United States', 'Lake Waramaug Country Club'),
  ('United States', 'Lake Wilderness Golf Course'),
  ('United States', 'Lake Wildwood Golf Course'),
  ('United States', 'Lake Winds Golf Course'),
  ('United States', 'Lake Windsor Country Club'),
  ('United States', 'Lake Winnipesaukee Golf Club'),
  ('United States', 'Lake Wisconsin Country Club'),
  ('United States', 'Lake Wissota Golf & Events'),
  ('United States', 'Lake Woods At Tri Cities Golf Course'),
  ('United States', 'Lake Woods Golf Club'),
  ('United States', 'Lake Worth Beach Golf Club'),
  ('United States', 'Lake Zurich Golf Club'),
  ('United States', 'Lake o'' the Hills Golf Course'),
  ('United States', 'Lake of the Sandhills'),
  ('United States', 'Lake of the Woods Golf Course'),
  ('United States', 'Lakeland Golf Club'),
  ('United States', 'Lakeland Hills Golf Course'),
  ('United States', 'Lakelands Golf and Country Club'),
  ('United States', 'Lakemont At Stone Mountain Golf Course'),
  ('United States', 'Lakeridge Golf Course'),
  ('United States', 'Lakes At Bear Lakes Country Club'),
  ('United States', 'Lakes At Blackhawk Country Club'),
  ('United States', 'Lakes At Boca Woods Country Club'),
  ('United States', 'Lakes At Colonial Springs Golf Course'),
  ('United States', 'Lakes At El Segundo The'),
  ('United States', 'Lakes At Leesburg'),
  ('United States', 'Lakes At North Ridge Country Club'),
  ('United States', 'Lakes At Palm Aire Country Club'),
  ('United States', 'Lakes At Quail West Golf Country Club'),
  ('United States', 'Lakes At Sandridge Golf Club'),
  ('United States', 'Lakes At Windy Hill Golf Course'),
  ('United States', 'Lakes Canyon At Blacklake Golf Course'),
  ('United States', 'Lakes Course At Genoa Lakes Golf Club'),
  ('United States', 'Lakes Cypress At Arrowhead Country Club'),
  ('United States', 'Lakes Dolphin Golf Course At Cocoa Beach Country Club'),
  ('United States', 'Lakes Dunes At Gainey Ranch Golf Club'),
  ('United States', 'Lakes Fairways At Centennial Golf Club'),
  ('United States', 'Lakes Golf Course At Laura Walker State Park'),
  ('United States', 'Lakes Golf Course At Oakwood Country Club'),
  ('United States', 'Lakes Meadows At Centennial Golf Club'),
  ('United States', 'Lakes Oaks At Blacklake Golf Course'),
  ('United States', 'Lakes Oaks At Hacienda Hills Golf Country Club'),
  ('United States', 'Lakes Orchard At Treesdale Golf Country Club'),
  ('United States', 'Lakes Pines At Star Hill Golf Country Club'),
  ('United States', 'Lakes River Golf Course Cocoa Beach Country Club'),
  ('United States', 'Lakes Sound Course At Pelican Sound Golf River Club'),
  ('United States', 'Lakes Sunrise At Spanish Trail Country Club'),
  ('United States', 'Lakes Valley At North Ranch Country Club'),
  ('United States', 'Lakes Valley At Valley Oaks Golf Club'),
  ('United States', 'Lakes Waterway At Arrowhead Country Club'),
  ('United States', 'Lakes of Taylor Golf Club'),
  ('United States', 'Lakes of the Four Seasons Golf Course'),
  ('United States', 'Lakeshore Golf Course'),
  ('United States', 'Lakeshore Golf and Country Club'),
  ('United States', 'Lakeshore Yacht Country Club'),
  ('United States', 'Lakeside At Golf Club Of Georgia The'),
  ('United States', 'Lakeside At Juniper Hill Golf Course'),
  ('United States', 'Lakeside Country Club'),
  ('United States', 'Lakeside Golf Club'),
  ('United States', 'Lakeside Golf Course'),
  ('United States', 'Lakeside Links'),
  ('United States', 'Lakeside Memorial Golf Course'),
  ('United States', 'Lakeside Municipal Golf Course'),
  ('United States', 'Lakeside Park Golf Club'),
  ('United States', 'Lakeside Pines At Blue Hill Golf Course'),
  ('United States', 'Lakeside Village Golf Athletic Club'),
  ('United States', 'Lakeview Bayview At A C Read Golf Course'),
  ('United States', 'Lakeview Country Club'),
  ('United States', 'Lakeview Golf And Country Club'),
  ('United States', 'Lakeview Golf Club'),
  ('United States', 'Lakeview Golf Club Eagle Eye Par 3 Course'),
  ('United States', 'Lakeview Golf Club Lake Course'),
  ('United States', 'Lakeview Golf Club Mountain Course'),
  ('United States', 'Lakeview Golf Club Peak Course'),
  ('United States', 'Lakeview Golf Country Club'),
  ('United States', 'Lakeview Golf Course'),
  ('United States', 'Lakeview Golf Resort Lakeview Course'),
  ('United States', 'Lakeview Golf Resort Mountainview Course'),
  ('United States', 'Lakeview Hills Golf Resort - North Course'),
  ('United States', 'Lakeview Hills Golf Resort - South Course'),
  ('United States', 'Lakeview Municipal Golf Course'),
  ('United States', 'Lakeview Par 3 Golf Challenge'),
  ('United States', 'Lakeview Springs Golf'),
  ('United States', 'Lakeville Country Club'),
  ('United States', 'Lakevue North Golf Course'),
  ('United States', 'Lakewood Country Club'),
  ('United States', 'Lakewood Golf Club'),
  ('United States', 'Lakewood Golf Country Club'),
  ('United States', 'Lakewood Golf Course'),
  ('United States', 'Lakewood Links'),
  ('United States', 'Lakewood National Golf Club Commander Course'),
  ('United States', 'Lakewood National Golf Club Piper Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Cypress Links Course'),
  ('United States', 'Lakewood Ranch Golf Country Club King Dunes Course'),
  ('United States', 'Lakewood Ranch Golf Country Club Royal Lakes Course'),
  ('United States', 'Lakewood on the Green'),
  ('United States', 'Lakin Country Club'),
  ('United States', 'Lakota Links Golf Club'),
  ('United States', 'Lamoine Valley Golf Club'),
  ('United States', 'Lamoni Golf and Country Club'),
  ('United States', 'Lamont Hill Resort'),
  ('United States', 'Lampman Golf Club'),
  ('United States', 'Lancaster Country Club'),
  ('United States', 'Lancaster Golf Center'),
  ('United States', 'Lancaster Golf Club'),
  ('United States', 'Lancaster Host Golf Resort'),
  ('United States', 'Lancaster Riverside Golf Club'),
  ('United States', 'Land O Lakes Golf Club'),
  ('United States', 'Lander Golf Country Club'),
  ('United States', 'Landings Golf Club'),
  ('United States', 'Landings Yacht Golf Tennis Club'),
  ('United States', 'Landis Creek Golf Club'),
  ('United States', 'Landsmeer Golf Club'),
  ('United States', 'Lane County Country Club'),
  ('United States', 'Lane Creek Golf Club'),
  ('United States', 'Lane Tree Golf Club'),
  ('United States', 'Langbrook Meadows Golf Country Club'),
  ('United States', 'Langendorf Park Golf Course'),
  ('United States', 'Langley Golf Club'),
  ('United States', 'Langston Golf Course'),
  ('United States', 'Lanier Islands Resort Legacy Golf Course'),
  ('United States', 'Lanier Islands Resort The Six'),
  ('United States', 'Lansbrook Golf Club'),
  ('United States', 'Lansdowne Resort Shark Bite Course'),
  ('United States', 'Lansdowne Resort The Norman Course'),
  ('United States', 'Lansdowne Resort The Robert Trent Jones Ii Course'),
  ('United States', 'Lansing Country Club'),
  ('United States', 'Lapeer Country Club'),
  ('United States', 'Laplaya Beach Golf Resort'),
  ('United States', 'Larchmont Golf Course'),
  ('United States', 'Largo Golf Course'),
  ('United States', 'Larimore Golf Club'),
  ('United States', 'Larned Country Club'),
  ('United States', 'Larry Gannon Municipal Golf Course'),
  ('United States', 'Las Animas Golf Course'),
  ('United States', 'Las Barrancas Golf Course'),
  ('United States', 'Las Campanas Sunrise Course'),
  ('United States', 'Las Campanas Sunset Course'),
  ('United States', 'Las Colinas Golf Club'),
  ('United States', 'Las Posas Country Club'),
  ('United States', 'Las Sendas Golf Club'),
  ('United States', 'Las Vegas Country Club'),
  ('United States', 'Las Vegas Golf Center')
on conflict (country, name) do nothing;