insert into public.golf_courses (country, name) values
  ('United States', 'Farwell Country Club'),
  ('United States', 'Fashion Golf Country Club'),
  ('United States', 'Faulkwood Shores Golf Club'),
  ('United States', 'Fauquier Springs Country Club'),
  ('United States', 'Fawn Creek Golf Course'),
  ('United States', 'Fawn Crest Golf Course'),
  ('United States', 'Fawn Lake Country Club'),
  ('United States', 'Fayetteville Country Club'),
  ('United States', 'Fazio Premier At Treetops Resort'),
  ('United States', 'Feather River Park Resort'),
  ('United States', 'Feather Sound Country Club'),
  ('United States', 'Fellows Creek Municipal Golf Club'),
  ('United States', 'Fendrich Golf Course'),
  ('United States', 'Fenner Hill Golf Club'),
  ('United States', 'Fennwood Hills Country Club'),
  ('United States', 'Fenton Farms Golf Club'),
  ('United States', 'Fenway Golf Club'),
  ('United States', 'Fenwick Golf Club'),
  ('United States', 'Fern Hill Golf Club'),
  ('United States', 'Ferndale Country Club'),
  ('United States', 'Fernwood Country Club'),
  ('United States', 'Fessenden Golf Club'),
  ('United States', 'Fianna Hills Country Club'),
  ('United States', 'Fiddlesticks Country Club Long Mean Course'),
  ('United States', 'Fiddlesticks Country Club Wee Friendly Course'),
  ('United States', 'Field Club of Omaha (north)'),
  ('United States', 'Field Club of Omaha (south)'),
  ('United States', 'Fields Ferry Golf Club'),
  ('United States', 'Fieldstone Golf Club'),
  ('United States', 'Fillmore Fairways Golf Course'),
  ('United States', 'Fillmore Golf Club'),
  ('United States', 'Fincastle On The Mountain Golf Course'),
  ('United States', 'Findlay Country Club'),
  ('United States', 'Finkbine Golf Course'),
  ('United States', 'Fircrest Golf Club'),
  ('United States', 'Fire Fox Resorts The Witch Golf Course'),
  ('United States', 'Fire Ridge Golf Club'),
  ('United States', 'Fire Ridge Golf Course'),
  ('United States', 'Firecliff At Desert Willow Golf Resort'),
  ('United States', 'Firefly Golf Course'),
  ('United States', 'Firefly Golf Links'),
  ('United States', 'Firekeeper Golf Course'),
  ('United States', 'Firelake Golf Course'),
  ('United States', 'Firerock Country Club'),
  ('United States', 'Firerock Country Club Littlerock Course'),
  ('United States', 'Firestone Country Club'),
  ('United States', 'Firethorn Golf Club'),
  ('United States', 'Firethorne Country Club'),
  ('United States', 'Fireweed Meadows Golf Course'),
  ('United States', 'First Nine At Edison Club The'),
  ('United States', 'First Nine At Montclair Golf Club'),
  ('United States', 'First Nine Second Nine At Bermuda Dunes Country Club'),
  ('United States', 'First Nine Second Nine At Cloverleaf Golf Club'),
  ('United States', 'First Nine Third Nine At Cloverleaf Golf Club'),
  ('United States', 'First Second At Lake Venice Golf Club'),
  ('United States', 'First Tee Northwest Arkansas'),
  ('United States', 'First Tee Of Augusta'),
  ('United States', 'First Tee Par 3 At Green Valley Ranch Golf Club'),
  ('United States', 'Fish Lake Country Club'),
  ('United States', 'Fisher Island Club'),
  ('United States', 'Fisher Park Golf Course'),
  ('United States', 'Fishermans Cove Golf Marina'),
  ('United States', 'Fishers Island Golf Country Club'),
  ('United States', 'Fishhook Golf Course'),
  ('United States', 'Fishkill Golf Course Driving Range'),
  ('United States', 'Five Flags Golf'),
  ('United States', 'Five Island Golf Course'),
  ('United States', 'Flagg Creek Golf Course'),
  ('United States', 'Flagstaff Ranch Golf Club'),
  ('United States', 'Flamingo Lakes Country Club'),
  ('United States', 'Flanders Valley Golf Club Red Gold Course'),
  ('United States', 'Flanders Valley Golf Club White Blue Course'),
  ('United States', 'Flatbush Golf Course'),
  ('United States', 'Flatirons Golf Course'),
  ('United States', 'Fleming County Golf Association'),
  ('United States', 'Fleming Island Golf Club'),
  ('United States', 'Fletchers Landing At Swingin Things'),
  ('United States', 'Flight Range'),
  ('United States', 'Flint Golf Club'),
  ('United States', 'Flint Hills Golf Course'),
  ('United States', 'Flint Hills National Golf Club'),
  ('United States', 'Flint River Golf Course'),
  ('United States', 'Florence Country Club'),
  ('United States', 'Florida Caverns Golf Course'),
  ('United States', 'Florida Keys Country Club'),
  ('United States', 'Florissant Golf Club'),
  ('United States', 'Flossmoor Country Club'),
  ('United States', 'Flourtown Country Club'),
  ('United States', 'Floyd Park Golf Course'),
  ('United States', 'Flushing Meadows Pitch Putt'),
  ('United States', 'Flushing Valley Golf Club'),
  ('United States', 'Flying "B" Golf Course'),
  ('United States', 'Flying Hills Golf Club'),
  ('United States', 'Flynn Centennial At Huntingdon Valley Country Club'),
  ('United States', 'Folkston Golf Club'),
  ('United States', 'Fon Du Lac Golf Course'),
  ('United States', 'Fonda Golf Course'),
  ('United States', 'Fontenelle Golf Course'),
  ('United States', 'Foothill Golf Course'),
  ('United States', 'Foothills Executive Golf Course'),
  ('United States', 'Foothills Golf Club'),
  ('United States', 'Foothills Golf Course Championship 18 Course'),
  ('United States', 'Foothills Golf Course Executive Course'),
  ('United States', 'Foothills Golf Course Par 3 Course'),
  ('United States', 'Foothills Par 3 Golf Course'),
  ('United States', 'Forbes Golf Course'),
  ('United States', 'Fords Colony Country Club Blackheath Course'),
  ('United States', 'Fords Colony Country Club Blue Heron Course'),
  ('United States', 'Fords Colony Country Club Marsh Hawk Course'),
  ('United States', 'Fordyce Country Club'),
  ('United States', 'Fore Honor Golf Course'),
  ('United States', 'Fore Kicks Golf Club'),
  ('United States', 'Fore U Golf Center'),
  ('United States', 'Fore Way Challenge Golf & Driving Range'),
  ('United States', 'Forebay Golf Course'),
  ('United States', 'Forest Akers East'),
  ('United States', 'Forest Akers West'),
  ('United States', 'Forest City Municipal Golf Course'),
  ('United States', 'Forest Country Club'),
  ('United States', 'Forest Course At Fiddlers Elbow Country Club'),
  ('United States', 'Forest Creek Golf Club North Course'),
  ('United States', 'Forest Creek Golf Club South Course'),
  ('United States', 'Forest Dale Golf Course'),
  ('United States', 'Forest Dunes Golf Resort'),
  ('United States', 'Forest E. Everhart Memorial Golf Course'),
  ('United States', 'Forest Glen Golf Country Club'),
  ('United States', 'Forest Greens Golf Club'),
  ('United States', 'Forest Heights Country Club'),
  ('United States', 'Forest Heights Golf Course'),
  ('United States', 'Forest Hill Field Club'),
  ('United States', 'Forest Hill Golf Course'),
  ('United States', 'Forest Hills'),
  ('United States', 'Forest Hills Country Club'),
  ('United States', 'Forest Hills Country Club Vue 791'),
  ('United States', 'Forest Hills Golf Club'),
  ('United States', 'Forest Hills Golf Course'),
  ('United States', 'Forest Lake At Stratton Mountain Country Club'),
  ('United States', 'Forest Lake Club'),
  ('United States', 'Forest Lake Country Club'),
  ('United States', 'Forest Lake Golf Club'),
  ('United States', 'Forest Lakes Golf Club At Abac'),
  ('United States', 'Forest Meadows Golf Course'),
  ('United States', 'Forest Oaks Country Club'),
  ('United States', 'Forest Oaks Golf Club'),
  ('United States', 'Forest Park Country Club'),
  ('United States', 'Forest Park Golf Course'),
  ('United States', 'Forest Point Golf Course'),
  ('United States', 'Forest View Golf Center'),
  ('United States', 'Forewinds Golf Course'),
  ('United States', 'Former Hara Greens'),
  ('United States', 'Forrest City Country Club'),
  ('United States', 'Forsgate Country Club The Banks'),
  ('United States', 'Forsgate Country Club The Palmer'),
  ('United States', 'Forsyth Country Club'),
  ('United States', 'Forsyth Golf Club'),
  ('United States', 'Fort Belvoir Golf Club Gunston Course'),
  ('United States', 'Fort Belvoir Golf Club Woodlawn Course'),
  ('United States', 'Fort Cherry Golf Club'),
  ('United States', 'Fort Collins Country Club'),
  ('United States', 'Fort Custer Golf Club'),
  ('United States', 'Fort Dodge Country Club'),
  ('United States', 'Fort Erie Golf Club'),
  ('United States', 'Fort Hays Municipal Golf Course'),
  ('United States', 'Fort Kent Golf Club'),
  ('United States', 'Fort Lauderdale Country Club North Course'),
  ('United States', 'Fort Lauderdale Country Club South Course'),
  ('United States', 'Fort Mill Golf Club'),
  ('United States', 'Fort Mitchell Country Club Golf Course'),
  ('United States', 'Fort Moore Golf Course Bradley Nine'),
  ('United States', 'Fort Moore Golf Course Marshall Nine'),
  ('United States', 'Fort Myers Country Club'),
  ('United States', 'Fort Sill Golf Club'),
  ('United States', 'Fort Smith Country Club'),
  ('United States', 'Fort Snelling Golf Course'),
  ('United States', 'Fort Washington Golf Country Club'),
  ('United States', 'Fortuna Delrey Golf Course'),
  ('United States', 'Forty Niner Country Club'),
  ('United States', 'Foss Park Golf Course'),
  ('United States', 'Fossil Island Golf Club'),
  ('United States', 'Fossil Trace Golf Club'),
  ('United States', 'Fosston Golf Club'),
  ('United States', 'Foster Country Club'),
  ('United States', 'Foster Golf Links'),
  ('United States', 'Foster Gulch Golf Course'),
  ('United States', 'Foster Park Golf Course'),
  ('United States', 'Fostoria Country Club'),
  ('United States', 'Founders At Penn National Golf Club Inn'),
  ('United States', 'Founders Club At St James Plantation'),
  ('United States', 'Founders Club Of Pawleys Island'),
  ('United States', 'Foundry Golf Club'),
  ('United States', 'Fountain Green Golf Course'),
  ('United States', 'Fountain Head Country Club'),
  ('United States', 'Fountain Hills Golf Club'),
  ('United States', 'Fountain Lakes Golf Course'),
  ('United States', 'Fountain Of The Sun Country Club'),
  ('United States', 'Fountain Springs Golf Course'),
  ('United States', 'Fountain Valley Golf Course'),
  ('United States', 'Fountainhead Creek Golf Club'),
  ('United States', 'Fountains Golf & Banquet'),
  ('United States', 'Four Bridges Country Club'),
  ('United States', 'Four Lakes Country Club'),
  ('United States', 'Four Lakes Golf Club'),
  ('United States', 'Four Mile Ranch Golf Club'),
  ('United States', 'Four Oaks Golf Course'),
  ('United States', 'Four Peaks Course At Sunland Springs Village'),
  ('United States', 'Four Seasons Country Club'),
  ('United States', 'Four Seasons Golf Club'),
  ('United States', 'Four Seasons Golf Course'),
  ('United States', 'Four Seasons Ranch Golf Course'),
  ('United States', 'Four Seasons Spa Country Club'),
  ('United States', 'Four Streams Golf Club'),
  ('United States', 'Four Willows Golf Course'),
  ('United States', 'Four Winds Golf Course'),
  ('United States', 'Fourth Nine At Montclair Golf Club'),
  ('United States', 'Fowler''s Mill Golf Course'),
  ('United States', 'Fox At Pittsburgh North Golf Club'),
  ('United States', 'Fox Bend Golf Course'),
  ('United States', 'Fox Chapel Golf Club'),
  ('United States', 'Fox Chase Golf Course At Carroll Farms'),
  ('United States', 'Fox Creek'),
  ('United States', 'Fox Creek Golf Club'),
  ('United States', 'Fox Creek Golf Course'),
  ('United States', 'Fox Den Golf Course'),
  ('United States', 'Fox Glen Golf Club'),
  ('United States', 'Fox Hill Country Club'),
  ('United States', 'Fox Hill Golf And Country Club'),
  ('United States', 'Fox Hills Country Club'),
  ('United States', 'Fox Hollow Golf Club'),
  ('United States', 'Fox Hollow Golf Course'),
  ('United States', 'Fox Hopyard Golf Club'),
  ('United States', 'Fox Lake Country Club'),
  ('United States', 'Fox Lake Golf Club'),
  ('United States', 'Fox Lake Golf Course'),
  ('United States', 'Fox Meadow Golf Course'),
  ('United States', 'Fox Prairie Golf Course'),
  ('United States', 'Fox Ridge'),
  ('United States', 'Fox Ridge Golf Club'),
  ('United States', 'Fox Ridge Golf Course'),
  ('United States', 'Fox River Resort'),
  ('United States', 'Fox Run Country Club'),
  ('United States', 'Fox Run Course At Glenview Champions Country Club'),
  ('United States', 'Fox Run Driving Range'),
  ('United States', 'Fox Run Golf Club'),
  ('United States', 'Fox Run Golf Course'),
  ('United States', 'Fox Run Golf Links'),
  ('United States', 'Fox Valley Golf Course'),
  ('United States', 'Fox Woods Golf Course'),
  ('United States', 'FoxCreek Golf & Racquet Club'),
  ('United States', 'Foxboro Golf Club'),
  ('United States', 'Foxborough Country Club'),
  ('United States', 'Foxburg Country Club'),
  ('United States', 'Foxchase Golf Club'),
  ('United States', 'Foxcliff Golf Club'),
  ('United States', 'Foxcroft Golf Club'),
  ('United States', 'Foxfire At Village Green'),
  ('United States', 'Foxfire Golf Club'),
  ('United States', 'Foxfire Resort Golf Club Grey Fox Course'),
  ('United States', 'Foxfire Resort Golf Club Red Fox Course'),
  ('United States', 'Foxford Hills Golf Course'),
  ('United States', 'Foxglove Pinecone At Resort At The Mountain The'),
  ('United States', 'Foxtail Golf Club North Course'),
  ('United States', 'Foxtail Golf Club South Course'),
  ('United States', 'Foxwood Country Club'),
  ('United States', 'Foxwood Hills Country Club'),
  ('United States', 'Framingham Country Club'),
  ('United States', 'Francis Byrne Golf Course'),
  ('United States', 'Francis Gross Golf Course'),
  ('United States', 'Francis Lake Golf Club'),
  ('United States', 'Francisco Grande Resort Golf Club'),
  ('United States', 'Franconia Golf Course'),
  ('United States', 'Frank E Peters Municipal Golf Course'),
  ('United States', 'Frank Skul Memorial Golf Course'),
  ('United States', 'Franklin Canyon Golf Course'),
  ('United States', 'Franklin Country Club'),
  ('United States', 'Franklin County Country Club'),
  ('United States', 'Franklin Golf Club'),
  ('United States', 'Franklin Golf Course'),
  ('United States', 'Franklin Hills Country Club'),
  ('United States', 'Franklin Valley Golf Club'),
  ('United States', 'Franklinton Country Club'),
  ('United States', 'Frasch Park Golf Club'),
  ('United States', 'Fraser Edmundston Golf Club'),
  ('United States', 'Fraserglen Golf Course Training Centre'),
  ('United States', 'Fraternal Order Of Eagles Eagles Hills Golf Course'),
  ('United States', 'Frazee Golf Course'),
  ('United States', 'Frear Park Golf Course'),
  ('United States', 'Fred Enke Golf Course'),
  ('United States', 'Frederic Golf Course'),
  ('United States', 'Frederica Golf Club'),
  ('United States', 'Frederick Golf Country Club'),
  ('United States', 'Frederick Peak Golf Club'),
  ('United States', 'Fredericksburg Country Club'),
  ('United States', 'Fredonia Country Club'),
  ('United States', 'Freedom Fairways'),
  ('United States', 'Freeport Mills Golf Course'),
  ('United States', 'Fremont Country Club'),
  ('United States', 'Fremont County Golf Course'),
  ('United States', 'Fremont County Recreation Area'),
  ('United States', 'Fremont Golf Club'),
  ('United States', 'Fremont Park Golf Course'),
  ('United States', 'French Camp Golf Course'),
  ('United States', 'French Creek Golf Course'),
  ('United States', 'French Oaks Golf Club'),
  ('United States', 'French Woods Golf Course'),
  ('United States', 'Frenchmans Bend Golf Country Club'),
  ('United States', 'Frenchmans Reserve Golf Course'),
  ('United States', 'Frenchs Hollow Fairways Golf Course'),
  ('United States', 'Fresh Meadow Country Club'),
  ('United States', 'Fresh Meadow Golf Club'),
  ('United States', 'Fresh Pond Golf Course'),
  ('United States', 'Friars Head Golf Course'),
  ('United States', 'Friars Presidio At Riverwalk Golf Club'),
  ('United States', 'Friendly Hills Country Club'),
  ('United States', 'Friendly Meadows Golf Course'),
  ('United States', 'Friendly Valley Golf Course'),
  ('United States', 'Frog Hollow Golf Club'),
  ('United States', 'Frog Rock Country Club'),
  ('United States', 'Front Back At Metedeconk National Golf Club'),
  ('United States', 'Front Back At Rolling Green Golf Club'),
  ('United States', 'Front Eighteen At Black Hawk Golf Course'),
  ('United States', 'Front Middle At Rolling Green Golf Club'),
  ('United States', 'Front Nine Back Nine At Southern Hills Country Club'),
  ('United States', 'Front Royal Golf Club'),
  ('United States', 'Front Third At Metedeconk National Golf Club'),
  ('United States', 'Frontier Road House Golf Course'),
  ('United States', 'Frost Creek'),
  ('United States', 'Frosty Valley Country Club'),
  ('United States', 'Frosty Valley Golf Links'),
  ('United States', 'Fruitport Golf Club'),
  ('United States', 'Frye Island Golf Course'),
  ('United States', 'Ft Cobb Golf Course'),
  ('United States', 'Fulda Town and Country Golf'),
  ('United States', 'Full Cry At Keswick Hall And Golf Club'),
  ('United States', 'Fuller''s Fairways'),
  ('United States', 'Fullerton Golf Course'),
  ('United States', 'Fulton Country Club'),
  ('United States', 'Furman University Golf Course'),
  ('United States', 'Furnace Bay Golf Course'),
  ('United States', 'Furnace Brook Golf Club'),
  ('United States', 'Furnace Creek Golf Course'),
  ('United States', 'Fyre Lake Golf Club'),
  ('United States', 'GLC Links'),
  ('United States', 'Gaffney Country Club'),
  ('United States', 'Gahanna Municipal Golf Course'),
  ('United States', 'Gaillardia Country Club'),
  ('United States', 'Gainesville Country Club'),
  ('United States', 'Gainesville Municipal Golf Course'),
  ('United States', 'Gainfield Farms Golf Course'),
  ('United States', 'Galax Municipal Golf Course'),
  ('United States', 'Galen Hall Golf Club'),
  ('United States', 'Galena Golf Club'),
  ('United States', 'Galena Ridge At Silver Mountain Resort'),
  ('United States', 'Galion Country Club'),
  ('United States', 'Galla Creek Golf Course'),
  ('United States', 'Galleon Brigantine At Shipyard Golf Club'),
  ('United States', 'Gallery Golf Club North Golf Course'),
  ('United States', 'Gallery Golf Club South Golf Course'),
  ('United States', 'Gallery Golf Course'),
  ('United States', 'Galloping Hill Golf Course'),
  ('United States', 'Galloping Hill Golf Course Learning Center 9'),
  ('United States', 'Galloway National Golf Club'),
  ('United States', 'Galway Golf Course'),
  ('United States', 'Gamble Sands Golf Club Cascade Putting Course'),
  ('United States', 'Gamble Sands Golf Club Quicksands Course'),
  ('United States', 'Gamble Sands Golf Club Scarecrow Course'),
  ('United States', 'Gamble Sands Golf Club The Sands Course'),
  ('United States', 'Gambler Ridge Golf Club'),
  ('United States', 'Gananoque Golf And Country Club'),
  ('United States', 'Ganienkeh Golf Course'),
  ('United States', 'Garden City Country Club'),
  ('United States', 'Garden City Golf Club'),
  ('United States', 'Garden Golf Club'),
  ('United States', 'Garden Of The Gods Club North Course'),
  ('United States', 'Garden Of The Gods Club South Course'),
  ('United States', 'Garden Of The Gods Club West Course'),
  ('United States', 'Garden Park'),
  ('United States', 'Gardiners Bay Country Club'),
  ('United States', 'Gardner Golf Course'),
  ('United States', 'Gardner Municipal Golf Course'),
  ('United States', 'Garland Lodge & Resort'),
  ('United States', 'Garner Country Club'),
  ('United States', 'Garner Golf and Country Club'),
  ('United States', 'Garnett Country Club'),
  ('United States', 'Garrison Golf Club'),
  ('United States', 'Garrisons Lake Golf Club'),
  ('United States', 'Gasparilla Inn Golf Course'),
  ('United States', 'Gaston Country Club'),
  ('United States', 'Gate City Golf Course'),
  ('United States', 'Gates Four Golf Country Club'),
  ('United States', 'Gates Park Golf Course'),
  ('United States', 'Gateway Cities Golf Club'),
  ('United States', 'Gateway Golf Course'),
  ('United States', 'Gateway Lodge Golf Course'),
  ('United States', 'Gateway National Golf Links'),
  ('United States', 'Gateway Recreation Golf Course'),
  ('United States', 'Gator Creek Golf Course'),
  ('United States', 'Gator Lakes Golf Course'),
  ('United States', 'Gator Trace Golf Country Club'),
  ('United States', 'Gauss'' Green Valley Golf Course'),
  ('United States', 'Gavilan Golf Course')
on conflict (country, name) do nothing;