insert into public.golf_courses (country, name) values
  ('United States', 'Silver Blue At Foxfire Country Club'),
  ('United States', 'Silver Creek Golf Club'),
  ('United States', 'Silver Creek Golf Course'),
  ('United States', 'Silver Creek Plantation'),
  ('United States', 'Silver Creek Valley Country Club'),
  ('United States', 'Silver Dollar Golf Trap Club Bobcat Gator Course'),
  ('United States', 'Silver Dollar Golf Trap Club Gator Panther Course'),
  ('United States', 'Silver Dollar Golf Trap Club Panther Bobcat Course'),
  ('United States', 'Silver Fox Golf Course'),
  ('United States', 'Silver King Golf Club'),
  ('United States', 'Silver Lake At The Villages Executive Golf Trail'),
  ('United States', 'Silver Lake Country Club'),
  ('United States', 'Silver Lake Golf Course'),
  ('United States', 'Silver Lakes Rv Resort Golf Club'),
  ('United States', 'Silver Oak Golf Course'),
  ('United States', 'Silver Oaks Golf Club'),
  ('United States', 'Silver Ridge'),
  ('United States', 'Silver Sage Golf Course'),
  ('United States', 'Silver Spring Country Club'),
  ('United States', 'Silver Spring Golf Club'),
  ('United States', 'Silver Spring Golf Course'),
  ('United States', 'Silver Springs Country Club'),
  ('United States', 'Silver Springs Golf Club'),
  ('United States', 'Silverado Golf Country Club'),
  ('United States', 'Silverado Resort Spa North Course'),
  ('United States', 'Silverado Resort Spa South Course'),
  ('United States', 'Silverbell Municipal Golf Course'),
  ('United States', 'Silvercrest Golf Club'),
  ('United States', 'Silvermine Golf Club Pro Shop 9 Course'),
  ('United States', 'Silvermine Golf Club Woods 9 Barn 9 Course'),
  ('United States', 'Silverrock Resort'),
  ('United States', 'Silverthorn Country Club'),
  ('United States', 'Sim Park Golf Course'),
  ('United States', 'Simi Hills Golf Course'),
  ('United States', 'Simpson Country Club'),
  ('United States', 'Simsbury Farms Golf Club'),
  ('United States', 'Sinaloa Golf Course'),
  ('United States', 'Sinclair Golf Club'),
  ('United States', 'Singing Bridge Golf Course'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Oak Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Pine Glen'),
  ('United States', 'Singing Hills Golf Resort At Sycuan Willow Glen'),
  ('United States', 'Sinking Valley Country Club'),
  ('United States', 'Sinnissippi Golf Course'),
  ('United States', 'Sioux City Country Club'),
  ('United States', 'Sioux Valley Golf Course'),
  ('United States', 'Siren National Golf Club'),
  ('United States', 'Sistersville Country Club Golf Course'),
  ('United States', 'Sitzmark Lodge'),
  ('United States', 'Siwanoy Country Club'),
  ('United States', 'Six Lakes Country Club'),
  ('United States', 'Skagit Golf Country Club'),
  ('United States', 'Skamania Lodge The Gorge 9'),
  ('United States', 'Skaneateles Country Club'),
  ('United States', 'Skenandoa Club Of Clinton'),
  ('United States', 'Skene Valley Country Club'),
  ('United States', 'Skippack Golf Course'),
  ('United States', 'Skokie Country Club'),
  ('United States', 'Skungamaug River Golf Club'),
  ('United States', 'Sky Meadow Country Club'),
  ('United States', 'Sky Mountain Golf Course'),
  ('United States', 'Sky Ranch Golf Course'),
  ('United States', 'Sky Valley Country Club'),
  ('United States', 'Skybrook Golf Club'),
  ('United States', 'Skyland Lakes Golf Course Resort'),
  ('United States', 'Skyline Country Club'),
  ('United States', 'Skyline Golf Course'),
  ('United States', 'Skyline Mountain Resort And Golf Course'),
  ('United States', 'Skyline Public Golf Course'),
  ('United States', 'Skyline Ranch Country Club'),
  ('United States', 'Skylinks At Buchanan Fields'),
  ('United States', 'Skylinks Golf Course'),
  ('United States', 'Skyridge Golf Course'),
  ('United States', 'Skytop Lodge Poconos Golf Course'),
  ('United States', 'Skytop Mountain Golf Club'),
  ('United States', 'Skyview At Terra Vista'),
  ('United States', 'Skyview Golf Club'),
  ('United States', 'Skyway Golf Course'),
  ('United States', 'Skyway Golf Course At Lincoln Park West'),
  ('United States', 'Skyway Golf Park'),
  ('United States', 'Slammer And Squire Golf Course At World Golf Village'),
  ('United States', 'Slayton Country Club'),
  ('United States', 'Sleeping Giant Golf Course'),
  ('United States', 'Sleeping Indian Cottonwood At West Woods Golf Club'),
  ('United States', 'Sleepy Eye Golf Club'),
  ('United States', 'Sleepy Hole Golf Course'),
  ('United States', 'Sleepy Hollow Country Club'),
  ('United States', 'Sleepy Hollow Country Club Lower Course'),
  ('United States', 'Sleepy Hollow Country Club Upper Course'),
  ('United States', 'Sleepy Hollow Golf Club'),
  ('United States', 'Sleepy Hollow Golf Country Club'),
  ('United States', 'Sleepy Hollow Golf Course'),
  ('United States', 'Sleepy Hollow Sports Park'),
  ('United States', 'Sliding Rock Golf Course'),
  ('United States', 'Sligo Creek Golf Course'),
  ('United States', 'Slippery Elm Golf Course'),
  ('United States', 'Slippery Rock Golf Club Events Center'),
  ('United States', 'Sloan Golf Course'),
  ('United States', 'Sly Fox Golf Club'),
  ('United States', 'Smethport Country Club'),
  ('United States', 'Smileys Executive Golf Club'),
  ('United States', 'Smith Center Municipal Golf Course'),
  ('United States', 'Smithfield Golf Club'),
  ('United States', 'Smithfields Country Club'),
  ('United States', 'Smock Golf Course'),
  ('United States', 'Smoke Rise Country Club'),
  ('United States', 'Smoky Hill Country Club'),
  ('United States', 'Smoky Mountain Country Club'),
  ('United States', 'Smoky River Golf Course'),
  ('United States', 'Smugglers Glen Golf Course'),
  ('United States', 'Snake River Golf Course'),
  ('United States', 'Snee Farm Country Club'),
  ('United States', 'Snohomish Public Golf Course'),
  ('United States', 'Snoqualmie Falls Golf Course'),
  ('United States', 'Snow Hill Country Club'),
  ('United States', 'Snow Mountain At Las Vegas Paiute Golf Resort'),
  ('United States', 'Snow Snake Golf Course'),
  ('United States', 'Snowcreek Golf Course'),
  ('United States', 'Snowflake Municipal Golf Course 18 Hole Course'),
  ('United States', 'Snowflake Municipal Golf Course 9 Hole Course'),
  ('United States', 'Snowflake Ski Club'),
  ('United States', 'Snowmass Club'),
  ('United States', 'Snyder Park Golf Course'),
  ('United States', 'Soaring Eagles Golf Course'),
  ('United States', 'Social Nine At Maddens On Gull Lake'),
  ('United States', 'Sodus Bay Heights Golf Club'),
  ('United States', 'Soldier Hill Golf Course'),
  ('United States', 'Soldier Hollow Golf Course The Gold Course'),
  ('United States', 'Soldier Hollow Golf Course The Silver Course'),
  ('United States', 'Soldiers Creek Golf Club'),
  ('United States', 'Soldiers Field Golf Course'),
  ('United States', 'Soleta Golf Golf Club'),
  ('United States', 'Soleta Golf Golf Club The Colt'),
  ('United States', 'Solina Golf Club'),
  ('United States', 'Solitude Links Golf Course & Banquet Center'),
  ('United States', 'Somerby Golf Club'),
  ('United States', 'Somers National Golf Club'),
  ('United States', 'Somerset Country Club'),
  ('United States', 'Somerset Farms Golf Course'),
  ('United States', 'Somerset Golf Course'),
  ('United States', 'Somerset Hills Country Club'),
  ('United States', 'Somersett Country Club Canyon Nine'),
  ('United States', 'Somersett Country Club Championship'),
  ('United States', 'Songbird Hills Golf Club'),
  ('United States', 'Sonnenalp Resort Of Vail'),
  ('United States', 'Sonnys Par 3 And Driving Range'),
  ('United States', 'Sonoma Golf Club'),
  ('United States', 'Sonoma Ranch Golf Course'),
  ('United States', 'Sonora Dunes Golf Course'),
  ('United States', 'Sonoran Course At Omni Tucson National Golf Resort Spa'),
  ('United States', 'Sonoran Golf Course At Oakwood Country Club'),
  ('United States', 'Sonyea Golf Course'),
  ('United States', 'Sorrento Par 3 Golf Course'),
  ('United States', 'Souhegan Woods Golf Club'),
  ('United States', 'Soule Park Golf Club'),
  ('United States', 'Sound Of Freedom Golf Course'),
  ('United States', 'Sound River Course At Pelican Sound Golf River Club'),
  ('United States', 'South At Admiral Baker Golf Course'),
  ('United States', 'South At Antelope Hills Golf Course'),
  ('United States', 'South At Bay Palms Golf Complex'),
  ('United States', 'South At Boulders Golf Club Resort'),
  ('United States', 'South At Bretwood Golf Course'),
  ('United States', 'South At Canoe Brook Country Club'),
  ('United States', 'South At Carmel Country Club'),
  ('United States', 'South At Cherokee Town Country Club'),
  ('United States', 'South At Cherokee Village'),
  ('United States', 'South At Churchville Park Golf Course'),
  ('United States', 'South At Coto De Caza Golf Racquet Club'),
  ('United States', 'South At Country Club Of Scranton The'),
  ('United States', 'South At Crestview Country Club'),
  ('United States', 'South At Daytona Beach Golf Country Club'),
  ('United States', 'South At Deerfield Country Club'),
  ('United States', 'South At Earlywine Golf Course'),
  ('United States', 'South At Fountains Country Club'),
  ('United States', 'South At Frenchmans Creek Beach Country Club'),
  ('United States', 'South At Hunters Run Golf Course'),
  ('United States', 'South At Ironwood Country Club'),
  ('United States', 'South At Johns Island Club'),
  ('United States', 'South At Lake Hefner Golf Course'),
  ('United States', 'South At Los Angeles Country Club The'),
  ('United States', 'South At Los Serranos Golf Country Club'),
  ('United States', 'South At Moss Creek Golf Club'),
  ('United States', 'South At Quail Ridge Country Club'),
  ('United States', 'South At Raintree Country Club'),
  ('United States', 'South At Rancho Murieta Country Club'),
  ('United States', 'South At Torrey Pines Municipal Golf Course'),
  ('United States', 'South At Victor Hills Golf Club'),
  ('United States', 'South At Vineyards Of Naples The'),
  ('United States', 'South At Westchester Country Club'),
  ('United States', 'South At Wilmington Country Club'),
  ('United States', 'South Bend Country Club'),
  ('United States', 'South Bluff Country Club'),
  ('United States', 'South Course'),
  ('United States', 'South Course At Big Cypress Golf Country Club'),
  ('United States', 'South Course At Highlands Ridge'),
  ('United States', 'South Course At Lake Of Isles'),
  ('United States', 'South Course At Shadow Wood Country Club'),
  ('United States', 'South Course At Terry Hills Golf Course'),
  ('United States', 'South Course At Whitefish Lake Golf Club'),
  ('United States', 'South East At Farmington Country Club'),
  ('United States', 'South East At Killearn Country Club Inn'),
  ('United States', 'South East At Newaukum Valley Golf Course'),
  ('United States', 'South East At Spanish Wells Country Club'),
  ('United States', 'South Fork Country Club'),
  ('United States', 'South Forty Golf Course Driving Range'),
  ('United States', 'South Gate Municipal Golf Course'),
  ('United States', 'South Gleason Park Course'),
  ('United States', 'South Golf Course At Granite Falls Golf Club'),
  ('United States', 'South Granville Country Club'),
  ('United States', 'South Grove Golf Course'),
  ('United States', 'South Harbour Golf Links'),
  ('United States', 'South Hardin Recreation Area'),
  ('United States', 'South Hill Country Club'),
  ('United States', 'South Hills Country Club'),
  ('United States', 'South Hills Golf & Country Club'),
  ('United States', 'South Hills Golf Club'),
  ('United States', 'South Hills Golf Course'),
  ('United States', 'South Lake At Mountain Gate Country Club'),
  ('United States', 'South Lakes Golf Course'),
  ('United States', 'South Mountain Golf Club'),
  ('United States', 'South Mountain Golf Course'),
  ('United States', 'South Nine At Cross Creek Resort'),
  ('United States', 'South North At Athens Country Club'),
  ('United States', 'South North At Cedar Knoll Country Club'),
  ('United States', 'South North At Farmington Country Club'),
  ('United States', 'South North At Fernandina Beach Golf Club'),
  ('United States', 'South North At Lakes Country Club The'),
  ('United States', 'South North At Oaks North Golf Course'),
  ('United States', 'South North At Ocean Breeze Golf Country Club'),
  ('United States', 'South North At Sahalee Country Club'),
  ('United States', 'South North At Spanish Wells Country Club'),
  ('United States', 'South Par 3 At Alondra Park Golf Course'),
  ('United States', 'South Park Golf Course'),
  ('United States', 'South Portland Municipal Golf Course'),
  ('United States', 'South Ridge Golf Course'),
  ('United States', 'South Riding Golf Club'),
  ('United States', 'South Shore Country Club'),
  ('United States', 'South Shore Golf Club'),
  ('United States', 'South Shore Golf Course'),
  ('United States', 'South Shore Village Golf Club'),
  ('United States', 'South Side Country Club'),
  ('United States', 'South Side Links'),
  ('United States', 'South Toledo Golf Club'),
  ('United States', 'South Wales Golf Club'),
  ('United States', 'South West At Elmridge Golf Club'),
  ('United States', 'South West At Krendale Golf Course'),
  ('United States', 'South West At Monterey Country Club'),
  ('United States', 'South West At Newaukum Valley Golf Course'),
  ('United States', 'South West At Rolling Acres Golf Course'),
  ('United States', 'South Winn Golf & Country Club'),
  ('United States', 'Southampton Country Club'),
  ('United States', 'Southampton Golf Club'),
  ('United States', 'Southaven Golf Center'),
  ('United States', 'Southborough Golf Club'),
  ('United States', 'Southbridge Savannah Golf Club'),
  ('United States', 'Southern Delaware Golf Club'),
  ('United States', 'Southern Dunes Golf Country Club'),
  ('United States', 'Southern Dunes Golf Course'),
  ('United States', 'Southern Dutchess Country Club'),
  ('United States', 'Southern Fairways Golf Course'),
  ('United States', 'Southern Gate Golf Course'),
  ('United States', 'Southern Highlands Golf Course'),
  ('United States', 'Southern Hills Golf Club'),
  ('United States', 'Southern Hills Golf Course'),
  ('United States', 'Southern Hills Plantation'),
  ('United States', 'Southern Meadows Par Four'),
  ('United States', 'Southern Oaks Country Club'),
  ('United States', 'Southern Oaks Golf Club'),
  ('United States', 'Southern Oaks Golf Course'),
  ('United States', 'Southern Pines Golf Club'),
  ('United States', 'Southern Ridge Golf Club'),
  ('United States', 'Southern Star At The Villages Executive Golf Trail'),
  ('United States', 'Southern Tee Golf Course'),
  ('United States', 'Southern Trace Country Club'),
  ('United States', 'Southern Wayne Country Club'),
  ('United States', 'Southers Marsh Golf Club'),
  ('United States', 'Southgate Golf Club'),
  ('United States', 'Southglenn Country Club'),
  ('United States', 'Southington Country Club'),
  ('United States', 'Southland Golf Country Club'),
  ('United States', 'Southmoor Golf Course (former)'),
  ('United States', 'Southmoore Golf Course'),
  ('United States', 'Southpointe Golf Club'),
  ('United States', 'Southport Springs Golf Country Club'),
  ('United States', 'Southridge Golf Club'),
  ('United States', 'Southshore Golf Club'),
  ('United States', 'Southshore Golf Learning Center'),
  ('United States', 'Southview Country Club'),
  ('United States', 'Southward Ho Country Club'),
  ('United States', 'Southwick Country Club'),
  ('United States', 'Southwinds Golf Course'),
  ('United States', 'Southwood Golf Club'),
  ('United States', 'Spanish Hills Golf Country Club'),
  ('United States', 'Spanish Lakes Country Club'),
  ('United States', 'Spanish Lakes Fairways'),
  ('United States', 'Spanish Lakes Golf Course'),
  ('United States', 'Spanish Lakes Golf Village'),
  ('United States', 'Spanish Peaks Mountain Club Toms 10 Golf Course'),
  ('United States', 'Spanish Trail Golf Club'),
  ('United States', 'Spanish Wells Club'),
  ('United States', 'Sparta Country Club'),
  ('United States', 'Sparta Moose Lodge Golf Course'),
  ('United States', 'Spearfish Canyon Country Club'),
  ('United States', 'Speedway Putting Course At Sea Island Golf Club'),
  ('United States', 'Speers Public Golf Course'),
  ('United States', 'Speidel Jones Golf Course'),
  ('United States', 'Speidel Palmer Golf Course'),
  ('United States', 'Spencer Golf and Country Club'),
  ('United States', 'Spencer T. Olin Community Golf Course'),
  ('United States', 'Spessard Holland Golf Course'),
  ('United States', 'Spider Lake Golf Resort'),
  ('United States', 'Spirit Hollow Golf Course'),
  ('United States', 'Split Rock At Pelham Split Rock Golf Course'),
  ('United States', 'Split Rock Golf Club'),
  ('United States', 'Split Rock Golf Club North Course'),
  ('United States', 'Split Rock Golf Club South Course'),
  ('United States', 'Spook Rock Golf Course'),
  ('United States', 'Spooky Brook Golf Course'),
  ('United States', 'Spooner Golf Club'),
  ('United States', 'Sportsmans Golf Course'),
  ('United States', 'Spotswood Country Club'),
  ('United States', 'Sprain Lake Golf Course'),
  ('United States', 'Spreading Antlers Golf Course'),
  ('United States', 'Spring Bayou Golf Country Club'),
  ('United States', 'Spring Brook Country Club'),
  ('United States', 'Spring Brook Golf Course'),
  ('United States', 'Spring Creek Golf Club'),
  ('United States', 'Spring Creek Golf Course'),
  ('United States', 'Spring Creek Golf Course Country Club'),
  ('United States', 'Spring Ford Country Club'),
  ('United States', 'Spring Green Municipal Golf Course'),
  ('United States', 'Spring Hill Country Club'),
  ('United States', 'Spring Hill Golf Club'),
  ('United States', 'Spring Hill Golf Course'),
  ('United States', 'Spring Hills Country Club'),
  ('United States', 'Spring Hills Golf Club'),
  ('United States', 'Spring Hills Golf Course'),
  ('United States', 'Spring Hollow Golf Course'),
  ('United States', 'Spring Lake Country Club'),
  ('United States', 'Spring Lake Golf & Country Club'),
  ('United States', 'Spring Lake Golf Club'),
  ('United States', 'Spring Lake Golf Course'),
  ('United States', 'Spring Lake Golf Resort Bobcat Run Executive Course'),
  ('United States', 'Spring Lakes Golf Club'),
  ('United States', 'Spring Meadow Golf Club'),
  ('United States', 'Spring Meadows Country Club'),
  ('United States', 'Spring Meadows Golf Club'),
  ('United States', 'Spring Mill At Philadelphia Country Club'),
  ('United States', 'Spring Mill Country Club'),
  ('United States', 'Spring Run Golf Club'),
  ('United States', 'Spring Valley Country Club'),
  ('United States', 'Spring Valley Golf Club'),
  ('United States', 'Spring Valley Golf Course'),
  ('United States', 'Springbrook Country Club'),
  ('United States', 'Springbrook Golf Club'),
  ('United States', 'Springbrook Golf Course'),
  ('United States', 'Springbrook Greens Golf Course'),
  ('United States', 'Springdale Country Club'),
  ('United States', 'Springdale Golf Club'),
  ('United States', 'Springdale Park and Golf Course'),
  ('United States', 'Springdale Resort'),
  ('United States', 'Springfield Country Club'),
  ('United States', 'Springfield Golf Center'),
  ('United States', 'Springfield Golf Club'),
  ('United States', 'Springfield Golf Country Club'),
  ('United States', 'Springfield Golf Course'),
  ('United States', 'Springfield Golf Resort'),
  ('United States', 'Springfield Oaks Golf Course'),
  ('United States', 'Springhaven Club'),
  ('United States', 'Springhill Country Club'),
  ('United States', 'Springhill Golf Course'),
  ('United States', 'Springside Par 3 Golf Course'),
  ('United States', 'Springvale Golf Course'),
  ('United States', 'Springville Country Club'),
  ('United States', 'Spruce Creek Country Club'),
  ('United States', 'Spruce Dogwood At Middle Island Country Club'),
  ('United States', 'Spruce Ridge Golf Club'),
  ('United States', 'Spruce Ridge Golf Course'),
  ('United States', 'Spruce Run Golf Course'),
  ('United States', 'Spud Run Golf'),
  ('United States', 'Spy Ring Golf Club'),
  ('United States', 'Spyglass Hilltm Golf Course'),
  ('United States', 'Squaw Creek Golf Course'),
  ('United States', 'Squaw Mountain Village Golf Course'),
  ('United States', 'Squire Creek Country Club'),
  ('United States', 'Squires Golf Club'),
  ('United States', 'Squirrel Run Country Club'),
  ('United States', 'St Alban''s Golf Course'),
  ('United States', 'St Andrews At Westcliffe'),
  ('United States', 'St Andrews By The Lake Golf Club'),
  ('United States', 'St Andrews Club'),
  ('United States', 'St Andrews Country Club Arnold Palmer Course'),
  ('United States', 'St Andrews Country Club Fazio Ii Course'),
  ('United States', 'St Andrews Golf Club'),
  ('United States', 'St Andrews Golf Club The'),
  ('United States', 'St Andrews South Golf Club'),
  ('United States', 'St Anne Country Club'),
  ('United States', 'St Augustine Shores Golf Club'),
  ('United States', 'St Bonaventure Golf Club'),
  ('United States', 'St Croix Country Club')
on conflict (country, name) do nothing;