insert into public.golf_courses (country, name) values
  ('United States', 'Country Club of Detroit'),
  ('United States', 'Country Club of Jackson'),
  ('United States', 'Country Club of Lansing'),
  ('United States', 'Country Club of Paducah'),
  ('United States', 'Country Club of Peoria Golf Course'),
  ('United States', 'Country Club of Sioux Falls'),
  ('United States', 'Country Club of Terre Haute'),
  ('United States', 'Country Club of the North'),
  ('United States', 'Country Drive Golf Course'),
  ('United States', 'Country Fareways Par 3 Golf Course'),
  ('United States', 'Country Greens Golf Course'),
  ('United States', 'Country Hills Golf Course'),
  ('United States', 'Country Land Golf Course'),
  ('United States', 'Country Mark Golf Course'),
  ('United States', 'Country Meadows Golf Course'),
  ('United States', 'Country Oaks Golf Course'),
  ('United States', 'Country Side Golf Club'),
  ('United States', 'Country View Golf Club'),
  ('United States', 'Country View Golf Course'),
  ('United States', 'Countryside Golf Club'),
  ('United States', 'Countryside Golf Course'),
  ('United States', 'Countryview Golf Club'),
  ('United States', 'Countryway Golf Club'),
  ('United States', 'County Line Country Club'),
  ('United States', 'County Line Golf Course'),
  ('United States', 'Course 4 Dubsdread At Cog Hill Golf And Country Club'),
  ('United States', 'Coushatta Country Club'),
  ('United States', 'Cove Cay Golf Club'),
  ('United States', 'Cove View Golf Course'),
  ('United States', 'Coventry Pines Public Golf Course'),
  ('United States', 'Covered Bridge Golf And Country Club'),
  ('United States', 'Covered Bridge Golf Club'),
  ('United States', 'Coves Golf Club'),
  ('United States', 'Covington Country Club'),
  ('United States', 'Covington Links Golf Course'),
  ('United States', 'Cowans Ford Country Club'),
  ('United States', 'Coweta Club At Arbor Springs Plantation'),
  ('United States', 'Coyote Creek Golf Club'),
  ('United States', 'Coyote Creek Golf Club The Tournament Course'),
  ('United States', 'Coyote Creek Golf Club The Valley Course'),
  ('United States', 'Coyote Creek Golf Course'),
  ('United States', 'Coyote Crossing Golf Club'),
  ('United States', 'Coyote Del Malpais Golf Course'),
  ('United States', 'Coyote Golf Club'),
  ('United States', 'Coyote Hills Golf Course'),
  ('United States', 'Coyote Lakes Golf Club'),
  ('United States', 'Coyote Moon Golf Course'),
  ('United States', 'Coyote Preserve Golf Club'),
  ('United States', 'Coyote Run Golf Course'),
  ('United States', 'Coyote Springs Golf Club'),
  ('United States', 'Coyote Trails Golf Course'),
  ('United States', 'Coyote Wash Golf Course'),
  ('United States', 'Coyote Willows Golf Club'),
  ('United States', 'Cozy Acres Golf Links'),
  ('United States', 'Crab Apple Ridge Golf Course'),
  ('United States', 'Crab Meadow Golf Course'),
  ('United States', 'Crab Orchard Golf Club'),
  ('United States', 'Crabapple Dogwood At Roanoke Country Club'),
  ('United States', 'Cracklewood Golf Club!'),
  ('United States', 'Crag Burn Golf Club'),
  ('United States', 'Cragie Brae Golf Club'),
  ('United States', 'Cragun S Legacy Dutch 27 Blue Nine'),
  ('United States', 'Cragun S Legacy Dutch 27 Red Nine'),
  ('United States', 'Cragun S Legacy Dutch 27 White Nine'),
  ('United States', 'Cragun S Legacy Lehman 18'),
  ('United States', 'Craig Wood Golf Country Club'),
  ('United States', 'Craig Woods Golf Club'),
  ('United States', 'Cramer Mountain Country Club'),
  ('United States', 'Cranberry Highlands Golf Course'),
  ('United States', 'Cranberry Hills'),
  ('United States', 'Cranberry Valley Golf Course'),
  ('United States', 'Cranbury Golf Club'),
  ('United States', 'Crandon Golf At Key Biscayne'),
  ('United States', 'Crane Creek Country Club'),
  ('United States', 'Crane Creek Golf Course'),
  ('United States', 'Crane Creek Reserve Golf Course At Melbourne'),
  ('United States', 'Crane Field Golf Course'),
  ('United States', 'Crane Lakes Golf Country Club'),
  ('United States', 'Crane Meadows Golf Course'),
  ('United States', 'Crane Watch Club'),
  ('United States', 'Crane''s Landing Golf Club at Marriott Lincolnshire Resort'),
  ('United States', 'Cranebrook Hills Golf Course'),
  ('United States', 'Cranes Bend At Orange Lake Resort'),
  ('United States', 'Cranston Country Club'),
  ('United States', 'Crawford Hills Municipal Golf Course'),
  ('United States', 'Crawfordsville Golf Course'),
  ('United States', 'Crazy Horse Sports Club Golf Course'),
  ('United States', 'Cream Ridge Golf Club'),
  ('United States', 'Cree Meadows Country Club'),
  ('United States', 'Creek At Carolina Trace Country Club'),
  ('United States', 'Creek At Quail Creek Country Club'),
  ('United States', 'Creek Cherokee At Big Canoe Golf Club'),
  ('United States', 'Creek Oaks At Temecula Creek Inn Golf Resort'),
  ('United States', 'Creek Side Golf'),
  ('United States', 'Creeks Golf Course At Quail Heights Country Club'),
  ('United States', 'Creeksbend Golf Course'),
  ('United States', 'Creekside At Bonita Bay Club'),
  ('United States', 'Creekside At Golf Club Of Georgia The'),
  ('United States', 'Creekside At Pebble Creek Country Club'),
  ('United States', 'Creekside Golf'),
  ('United States', 'Creekside Golf Country Club'),
  ('United States', 'Creekside Golf Course'),
  ('United States', 'Creekview Par Three'),
  ('United States', 'Creekview Par Three At Albion'),
  ('United States', 'Crescent Bar Resort'),
  ('United States', 'Crescent Farms Golf Club'),
  ('United States', 'Crescent Hill Golf Course'),
  ('United States', 'Crescent Oaks Country Club'),
  ('United States', 'Crescent Pointe Golf Club'),
  ('United States', 'Cress Creek Country Club'),
  ('United States', 'Cressmoor Country Club'),
  ('United States', 'Cresta Verde Golf Club'),
  ('United States', 'Crestbrook Park Golf Course'),
  ('United States', 'Crestmont Country Club'),
  ('United States', 'Crestmoor Golf Club'),
  ('United States', 'Creston Golf Club'),
  ('United States', 'Crestview Country Club'),
  ('United States', 'Crestview Executive Course'),
  ('United States', 'Crestview Golf Club'),
  ('United States', 'Crestview Golf Course'),
  ('United States', 'Crestwicke Country Club'),
  ('United States', 'Crestwood Country Club'),
  ('United States', 'Crestwood Golf Club'),
  ('United States', 'Creve Coeur Golf Course'),
  ('United States', 'Crewe Country Club'),
  ('United States', 'Cricket Hill Golf Club'),
  ('United States', 'Cricket Ridge Golf Course'),
  ('United States', 'Crimson Creek Golf Course'),
  ('United States', 'Crimson Ridge'),
  ('United States', 'Cripple Creek Golf Country Club'),
  ('United States', 'Croasdaile Country Club'),
  ('United States', 'Crockett Ridge Golf Course'),
  ('United States', 'Cronins Golf Resort'),
  ('United States', 'Crooked Cat At Orange County National'),
  ('United States', 'Crooked Creek Club'),
  ('United States', 'Crooked Creek Country Club'),
  ('United States', 'Crooked Creek Golf Club'),
  ('United States', 'Crooked Creek Golf Course'),
  ('United States', 'Crooked Hollow Golf Club'),
  ('United States', 'Crooked Lake Golf Club'),
  ('United States', 'Crooked Oak Golf Club'),
  ('United States', 'Crooked Oaks At Seabrook Island Resort'),
  ('United States', 'Crooked Pines Golf Swim Club'),
  ('United States', 'Crooked Stick Golf Club'),
  ('United States', 'Crooked Tree Golf Club'),
  ('United States', 'Crooked Tree Golf Course'),
  ('United States', 'Cross Creek Country Club'),
  ('United States', 'Cross Creek Golf Club'),
  ('United States', 'Cross Creek Golf Course'),
  ('United States', 'Cross Creek Golf Links'),
  ('United States', 'Cross Creek Plantation'),
  ('United States', 'Crosscreek Golf Club'),
  ('United States', 'Crossgates Golf Course'),
  ('United States', 'Crossings At Grove Park The'),
  ('United States', 'Crossings Golf Club'),
  ('United States', 'Crossroads At Palmetto Bluff'),
  ('United States', 'Crossroads Par 3 Golf Course'),
  ('United States', 'Crosswater At Sunriver Resort'),
  ('United States', 'Crosswinds Golf Club Jones Ouimet'),
  ('United States', 'Crosswinds Golf Club Ouimet Zaharias'),
  ('United States', 'Crosswinds Golf Club Zaharias Jones'),
  ('United States', 'Crotched Mountain Golf Club'),
  ('United States', 'Crow Canyon Country Club'),
  ('United States', 'Crow Creek Golf Club'),
  ('United States', 'Crow River Country Club'),
  ('United States', 'Crow Valley Golf Club'),
  ('United States', 'Crowders Mountain Golf Club'),
  ('United States', 'Crowfield Golf Country Club'),
  ('United States', 'Crowleys Ridge Country Club'),
  ('United States', 'Crown Colony Golf Country Club'),
  ('United States', 'Crown Hill Golf Club'),
  ('United States', 'Crown Park Golf Course'),
  ('United States', 'Crown Point Country Club'),
  ('United States', 'Crown Pointe Golf Club'),
  ('United States', 'Crowne Plaza Tennis Golf Resort'),
  ('United States', 'Cruiser At Seal Beach Navy Golf Course'),
  ('United States', 'Crumpin Fox Club'),
  ('United States', 'Cruz Farm Golf Club'),
  ('United States', 'Crystal Coast Country Club'),
  ('United States', 'Crystal Downs Country Club'),
  ('United States', 'Crystal Falls Golf Club'),
  ('United States', 'Crystal Golf Course'),
  ('United States', 'Crystal Lake Club'),
  ('United States', 'Crystal Lake Country Club'),
  ('United States', 'Crystal Lake Golf Club'),
  ('United States', 'Crystal Lake Golf Country Club'),
  ('United States', 'Crystal Lakes Golf Course'),
  ('United States', 'Crystal Springs'),
  ('United States', 'Crystal Springs Golf Club'),
  ('United States', 'Crystal Springs Golf Course'),
  ('United States', 'Crystal Tree Golf and Country Club'),
  ('United States', 'Crystal View Golf Course'),
  ('United States', 'Crystal Woods Golf Club'),
  ('United States', 'Crystalaire Country Club'),
  ('United States', 'Culbertson Hills Golf Resort'),
  ('United States', 'Cullasaja Club'),
  ('United States', 'Cultus Lake Golf Club'),
  ('United States', 'Culver Lake Golf Course'),
  ('United States', 'Cumberland Country Club'),
  ('United States', 'Cumberland Golf Club'),
  ('United States', 'Cumberland Trail Golf Club'),
  ('United States', 'Cummaquid Golf Club'),
  ('United States', 'Cummings Cove Golf Country Club'),
  ('United States', 'Currahee Club'),
  ('United States', 'Currie Municipal Golf Course'),
  ('United States', 'Currie Park Golf Course'),
  ('United States', 'Curtis Creek Golf Course'),
  ('United States', 'Custer Greens Golf Course'),
  ('United States', 'Cut Bank Golf Country Club'),
  ('United States', 'Cutalong At Lake Anna'),
  ('United States', 'Cutter Creek Golf Club'),
  ('United States', 'Cyclone golf performance center'),
  ('United States', 'Cypress At Palm Aire Country Club'),
  ('United States', 'Cypress At Royal Poinciana Golf Club'),
  ('United States', 'Cypress At Woodmont Country Club'),
  ('United States', 'Cypress Bend Golf Resort'),
  ('United States', 'Cypress Course At Stonegate Golf Club'),
  ('United States', 'Cypress Cove Country Club'),
  ('United States', 'Cypress Creek At Greystone'),
  ('United States', 'Cypress Creek Country Club'),
  ('United States', 'Cypress Creek Golf Links'),
  ('United States', 'Cypress Creek Golfers Club'),
  ('United States', 'Cypress Greens Golf Tennis Community'),
  ('United States', 'Cypress Head Golf Club'),
  ('United States', 'Cypress Knoll Golf Country Club'),
  ('United States', 'Cypress Lake Country Club'),
  ('United States', 'Cypress Lake Par 3 Golf Course'),
  ('United States', 'Cypress Lakes Country Club'),
  ('United States', 'Cypress Lakes Golf Club'),
  ('United States', 'Cypress Lakes Golf Country Club'),
  ('United States', 'Cypress Lakes Golf Course'),
  ('United States', 'Cypress Lakes Homeowners Golf Course'),
  ('United States', 'Cypress Landing Golf Course'),
  ('United States', 'Cypress Links At Mangrove Bay'),
  ('United States', 'Cypress Point Club'),
  ('United States', 'Cypress Point Country Club'),
  ('United States', 'Cypress Point Par 3 Golf Course'),
  ('United States', 'Cypress Point Rv Golf Club'),
  ('United States', 'Cypress Ridge Golf Course'),
  ('United States', 'Cypress Run Golf Club'),
  ('United States', 'Cypress Run Golf Course'),
  ('United States', 'Cypress Waterway At Arrowhead Country Club'),
  ('United States', 'Cypress Woods Golf Country Club'),
  ('United States', 'Cypresswood Golf Country Club'),
  ('United States', 'D W Field Golf Course'),
  ('United States', 'Dacotah Ridge Golf Club'),
  ('United States', 'Dad Miller Golf Course'),
  ('United States', 'Dairy Creek Golf Course'),
  ('United States', 'Dairymens Country Club'),
  ('United States', 'Dakota Creek Golf Country Club'),
  ('United States', 'Dakota Dunes Country Club'),
  ('United States', 'Dakota Landing Golf Course'),
  ('United States', 'Dakota Trails Golf Course'),
  ('United States', 'Dakota Winds Golf Course'),
  ('United States', 'Dalhousie Golf Club'),
  ('United States', 'Dalton Golf Country Club'),
  ('United States', 'Dalton Ranch Golf Club'),
  ('United States', 'Dan Hall Mountain Resort'),
  ('United States', 'Dan Valley Golf Course'),
  ('United States', 'Dancing Rabbit Golf Club The Azaleas'),
  ('United States', 'Dancing Rabbit Golf Club The Oaks'),
  ('United States', 'Dande Farms Golf Course'),
  ('United States', 'Dandrea Golf Club'),
  ('United States', 'Daniel Island Club Beresford Creek Course'),
  ('United States', 'Daniel Island Club Ralston Creek Course'),
  ('United States', 'Danville Golf Club'),
  ('United States', 'Darby Creek Golf Course'),
  ('United States', 'Darkhorse Golf Club'),
  ('United States', 'Darlington Country Club'),
  ('United States', 'Darlington Golf Course'),
  ('United States', 'Date Palm Country Club'),
  ('United States', 'Dauphin Highlands Golf Course'),
  ('United States', 'Dave White Municipal Golf Course'),
  ('United States', 'Davenport Country Club'),
  ('United States', 'David L Baker Memorial Golf'),
  ('United States', 'David Toms Academy 265'),
  ('United States', 'Davie Golf Country Club'),
  ('United States', 'Davis Countryside Meadows'),
  ('United States', 'Davis Golf Course'),
  ('United States', 'Davis Monthan Afb General William Blanchard Course'),
  ('United States', 'Davis Park Golf Course'),
  ('United States', 'Davison Country Club'),
  ('United States', 'Dawson Country Club'),
  ('United States', 'Dawson Golf Course'),
  ('United States', 'Dawson Ridge Golf Course'),
  ('United States', 'Dayton Community Golf Club'),
  ('United States', 'Dayton Country Club'),
  ('United States', 'Dayton Ridge Golf Club'),
  ('United States', 'Dayton Valley Golf Club'),
  ('United States', 'Daytona Golf Course'),
  ('United States', 'De Anza Country Club'),
  ('United States', 'De La Vista At The Villages Executive Golf Trail'),
  ('United States', 'De Smidt''s Golf Course & Country Club'),
  ('United States', 'DeMor Hills Golf Course'),
  ('United States', 'Deacon''s Lodge'),
  ('United States', 'Deal Golf Country Club'),
  ('United States', 'Dearborn Country Club'),
  ('United States', 'Dearborn Hills'),
  ('United States', 'Debary Golf Country Club'),
  ('United States', 'Debell Golf Club'),
  ('United States', 'Debell Golf Club Par 3 Course'),
  ('United States', 'Debordieu Colony Country Club'),
  ('United States', 'Decatur County Golf and Country Club'),
  ('United States', 'Decatur Golf Club'),
  ('United States', 'Deception Pass Golf Center'),
  ('United States', 'Dedham Country Polo Club'),
  ('United States', 'Deep Brook Golf Course'),
  ('United States', 'Deep Cliff Golf Course'),
  ('United States', 'Deep Creek Golf Club'),
  ('United States', 'Deep Springs Country Club'),
  ('United States', 'Deepdale Golf Club'),
  ('United States', 'Deer Brook Golf Club'),
  ('United States', 'Deer Cove'),
  ('United States', 'Deer Creek Golf Club'),
  ('United States', 'Deer Creek Golf Club At Meadow Ranch'),
  ('United States', 'Deer Creek Golf Course'),
  ('United States', 'Deer Creek Rv Golf Country Club'),
  ('United States', 'Deer Creek State Park Golf Course'),
  ('United States', 'Deer Creek Town Racquet Club'),
  ('United States', 'Deer Field Golf Course'),
  ('United States', 'Deer Haven Golf Club'),
  ('United States', 'Deer Island Country Club'),
  ('United States', 'Deer Lodge Golf Club'),
  ('United States', 'Deer Park Country Club'),
  ('United States', 'Deer Park Golf Club'),
  ('United States', 'Deer Ridge Golf Club'),
  ('United States', 'Deer Run At Sun N Lake Golf Country Club'),
  ('United States', 'Deer Run Championship At Newport News Golf Club'),
  ('United States', 'Deer Run Golf Club'),
  ('United States', 'Deer Run Golf Course'),
  ('United States', 'Deer Run Golf at Lakes of the North'),
  ('United States', 'Deer Trace Golf Links'),
  ('United States', 'Deer Track Golf'),
  ('United States', 'Deer Track Golf Course'),
  ('United States', 'Deer Trail Country Club'),
  ('United States', 'Deer Trails Country Club'),
  ('United States', 'Deer Trails Golf Course'),
  ('United States', 'Deer Valley Golf Club'),
  ('United States', 'Deer Valley Golf Course'),
  ('United States', 'Deer Valley Golf Course At Sun City West'),
  ('United States', 'Deer View Golf Course'),
  ('United States', 'Deercreek Country Club'),
  ('United States', 'Deercroft Golf Club'),
  ('United States', 'Deerfield Golf Club'),
  ('United States', 'Deerfield Golf Club and Learning Center'),
  ('United States', 'Deerfield Golf Course'),
  ('United States', 'Deerfield Golf Tennis Club'),
  ('United States', 'Deering Bay Yacht Country Club'),
  ('United States', 'Deerpath Golf Course'),
  ('United States', 'Deertrak Golf Club'),
  ('United States', 'Deerwood Club The'),
  ('United States', 'Deerwood Country Club'),
  ('United States', 'Deerwood Golf Club'),
  ('United States', 'Deerwood Golf Course Buck Course'),
  ('United States', 'Deerwood Golf Course Doe Course'),
  ('United States', 'Deerwood Golf Course Fawn Course'),
  ('United States', 'Degray Lake Golf Course'),
  ('United States', 'Del Lago Golf Club'),
  ('United States', 'Del Mar Country Club'),
  ('United States', 'Del Mar Golf Course'),
  ('United States', 'Del Montetm Golf Course'),
  ('United States', 'Del Norte Golf Club'),
  ('United States', 'Del Paso Country Club'),
  ('United States', 'Del Rio Country Club'),
  ('United States', 'Del Tura Golf Country Club North West'),
  ('United States', 'Del Tura Golf Country Club South North'),
  ('United States', 'Del Tura Golf Country Club West South'),
  ('United States', 'Delaire Country Club Hills Woods'),
  ('United States', 'Delaire Country Club Lakes Hills'),
  ('United States', 'Delaire Country Club Woods Lakes'),
  ('United States', 'Delano Golf Course'),
  ('United States', 'Delaveaga Golf Course Lodge'),
  ('United States', 'Delaware Country Club'),
  ('United States', 'Delaware Golf Club'),
  ('United States', 'Delaware Park Course'),
  ('United States', 'Delaware Springs Golf Course'),
  ('United States', 'Delbrook Golf Club'),
  ('United States', 'Delcastle Golf Course'),
  ('United States', 'Delhi Country Club'),
  ('United States', 'Dell Urich At Randolph Golf Course'),
  ('United States', 'Dellwood Country Club'),
  ('United States', 'Delmont Golf Course'),
  ('United States', 'Delphi Falls Golf Course'),
  ('United States', 'Delphi Golf Club'),
  ('United States', 'Delray Beach Golf Club'),
  ('United States', 'Delray Dunes Golf Country Club'),
  ('United States', 'Delta Country Club'),
  ('United States', 'Delta Knolls Golf Center'),
  ('United States', 'Delta Nine At Ascarate Park Golf Course'),
  ('United States', 'Deltona Club'),
  ('United States', 'Deme Acres Golf Course'),
  ('United States', 'Dempsey Ridge Golf Course'),
  ('United States', 'Den Brae Golf Club'),
  ('United States', 'Denison Country Club'),
  ('United States', 'Denison Golf Club'),
  ('United States', 'Dennis Highlands Golf Course'),
  ('United States', 'Dennis Pines Golf Course'),
  ('United States', 'Densons Creek Golf Course'),
  ('United States', 'Denver City Park Golf Course'),
  ('United States', 'Denver Country Club')
on conflict (country, name) do nothing;